### ISSUE TITLE
Encounter connection reset while using chacha20-ietf cipher

### ISSUE THREAD

**Issue by testcaoy7** [shadowsocks/shadowsocks-libev#1000]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
shadowsocks-libev 2.5.6 with OpenSSL 1.0.2g

### What operating system are you using?
Ubuntu 16.10

### What did you do?
Browsing Internet via shadowsocks-libev

### What did you expect to see?
Maintain anonymity while browsing the Internet

### What did you see instead?
Suddenly, my connection was reset. I cannot visit the Internet. My VPS was not banned. I had to change cipher from chacha20-ietf to aes-128-ctr.

### What is your config in detail (with all sensitive info masked)?
ss-server -s 0.0.0.0 -p 80 -k PSK -m chacha20-ietf -t 20 -u -A -d 64.6.64.6 --fast-open

**Comment by madeye** [comment]
I don't think it's related to ciphers.  Make sure you have increased the file limit of the server.

**Comment by testcaoy7** [comment]
@madeye Maybe it is the port. Running shadowsocks protocol on 80 is a little distinctive from regular HTTP data.

**Comment by madeye** [comment]
They are not attacks. If you're using common ports like 80 or 443, log of spiders are expected.

**Comment by testcaoy7** [comment]
I think it is the port. Sadly, my VPS only allow traffic on 22, 80 and 443.

**Comment by madeye** [comment]
Again, ports are not related to your reset. And the logs are normal and expected.

**Comment by testcaoy7** [comment]
May be it it a rare phenominon. I shall be watching. By the way, my ISP is China Telecom.
@madeye Thank you for your assistance and patience.
