### ISSUE TITLE
Gcm connections get Fin errors

### ISSUE THREAD

**Issue by panzhitian** [shadowsocks/shadowsocks-libev#1004]
### What version of shadowsocks-libev are you using?
latest snapshot.
https://github.com/shadowsocks/shadowsocks-libev/commit/134a35fd6cd87465bcb7d17db852f30a3de0409f

### What operating system are you using?
Debian 7.

### What did you do?
Keep default timeout parm.

### What did you expect to see?
Gcm heartbeats keep alive.

### What did you see instead?
Gcm connections get a Fin error every minutes(60s) on TDD-LTE.

### What is your config in detail (with all sensitive info masked)?
If I set the timeout parm to a smaller one or a bigger one, the connection breaks in the same timeout circle. However, the connection is more stable in wifi environment.

**Comment by madeye** [comment]
Also increase the timeout on the client.

**Comment by panzhitian** [comment]
@madeye what's your recommendation? Gcm default heartbeat interval(28 mins)? or the mobile data nat timeout(5 mins maybe)?
But how can I configure the client on android? It overrides the config file by the default timeout if I reconnect the server?

**Comment by madeye** [comment]
The timeout of Android client is 600s. Make sure you're using the latest one.

**Comment by panzhitian** [comment]
I'm using the latest Android client (v3.3.1).
I increase the server timeout to 600 and the connections is stable now but only when the screen is on.
so I open a new issue here.
https://github.com/shadowsocks/shadowsocks-android/issues/1026
