### ISSUE TITLE
用copy paste的方式merge代码，也太不讲究了

### ISSUE THREAD

**Issue by s7lx** [shadowsocks/shadowsocks-libev#1010]
![image](https://cloud.githubusercontent.com/assets/3221213/21497637/563e695a-cc61-11e6-9317-858630a1caac.png)
如图，merge过来不好么

**Comment by madeye** [comment]
First of all, make sure you know what `squash` is.

**Comment by Mygod** [comment]
I'm not a big fan of squashing either as it makes `git bisect` harder if it is in the middle of the squashed commit. And we especially shouldn't squash the commits if it has already published for some days in the same repo, i.e. `shadowsocks/shadowsocks-libev`.

**Comment by madeye** [comment]
@Mygod Understood. The reason I choose squashing here is that many commits in this pull request is not complete or just drafts, e.g. commits starting with WiP.

And yes, we should not squash large pull request like `drawer` branch of shadowsocks-android.

**Comment by madeye** [comment]
@Mygod Maybe I should maintain a fork in my account and avoid pushing WiP branch to this repo?

**Comment by Mygod** [comment]
Yeah that sounds better.
