### ISSUE TITLE
fail to use ss-local behind a socks proxy (tsocks)

### ISSUE THREAD

**Issue by coeusite** [shadowsocks/shadowsocks-libev#1012]
Hello, there is any way to use shadowsocks behind a Socks5 proxy? 
Like this: SS-Client -> Proxy Server -> Internet -> SS-Server

It seems tsocks cannot help.

Thank you very much!

### What version of shadowsocks-libev are you using?
shadowsocks-libev 2.5.6 with mbed TLS 2.4.0
(official package from Debian Jessie-Backports)

### What operating system are you using?
Debian Jessie (VirtualBox Guest)

### What did you do?
/usr/bin/tsocks /usr/bin/ss-local -c /etc/shadowsocks-libev/config.json -u -A

### What did you expect to see?
working as usual

### What did you see instead?
using ss-local directly works well, but using ss-local behind a socks proxy fails at all.
log:
```
[user@debian]: /usr/bin/tsocks /usr/bin/ss-local -c /etc/shadowsocks-libev/config.json
 2016-12-27 20:40:36 INFO: initializing ciphers... chacha20
 2016-12-27 20:40:36 INFO: tcp port reuse enabled
 2016-12-27 20:40:36 INFO: listening at 127.0.0.1:9999
 2016-12-27 20:40:38 ERROR: getpeername: Transport endpoint is not connected
 2016-12-27 20:40:38 ERROR: getpeername: Transport endpoint is not connected
```
### What is your config in detail (with all sensitive info masked)?
```
{
    "server":"*****",
    "server_port":8838,
    "local_port":9999,
    "password":"*****",
    "timeout":60,
    "method":"chacha20"
}
```

**Comment by madeye** [comment]
Try the following tools instead:

1. Proxychains: https://github.com/rofl0r/proxychains-ng
2. Danate: https://www.inet.no/dante/doc/1.3.x/socksify.1.html
3. Redsocks: https://github.com/darkk/redsocks

**Comment by coeusite** [comment]
Thank you. I will try it later.

**Comment by coeusite** [comment]
Proxychains does not work, but it doesn't return any error either.

**Comment by Losses** [comment]
@coeusite Any new solutions? may be we could reopen this issue?
