### ISSUE TITLE
obfs in config.json

### ISSUE THREAD

**Issue by simonsmh** [shadowsocks/shadowsocks-libev#1013]
How about adding obfs config?

**Comment by madeye** [comment]
It's already added. For example,

```
{
    "server":"127.0.0.1",
    "server_port":8388,
    "local_port":1080,
    "password":"barfoo!",
    "timeout":60,
    "obfs":"http",
    "obfs_host":"www.baidu.com",
    "method":null
}
```

**Comment by debiansid** [comment]
Also on the server side?

**Comment by simonsmh** [comment]
"obfs_host" or "obfs-host"?

**Comment by simonsmh** [comment]
So the default config is out of date. Many params like `auth` `nofile` `mptcp` `fast_open` didn't show at the default config.
https://github.com/shadowsocks/shadowsocks-libev/blob/master/debian/config.json
Would you please add them into the config file?

@debiansid Yes.
