### ISSUE TITLE
ss-manager pid

### ISSUE THREAD

**Issue by lemoz** [shadowsocks/shadowsocks-libev#1014]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
latest

### What operating system are you using?
ubuntu 14.04.5

### What did you do?
ss-manager --manager-address 0.0.0.0:6001 -c /etc/shadowsocks-libev/config.json -v

### What did you expect to see?
My manager adding new servers using the ss-manager tool

### What did you see instead?
my manager adding the new servers.
My manager sends out add server command every 5 mins. every other time it sends out the command it seems it closes the port. My internet traffic stops. Then in 5 mins when it sends it again it does not fail.

### What is your config in detail (with all sensitive info masked)?
Did not use config file

**Comment by madeye** [comment]
I cannot get your point. Maybe you can try this project: https://github.com/shadowsocks/shadowsocks-manager, which works as a wrapper of shadowsocks management api.

**Comment by lemoz** [comment]
I am using the older version of shadowsocks manager. Everything seems to work at first but then it turns on and off.

take for example:


**WORKS** 2016-12-28 15:02:00 INFO: cmd: ss-server -p 443 -m aes-128-cfb -k qaz123 --manager-address 0.0.0.0:6001 -f /root/.shadowsocks/.shadowsocks_443.pid -t @iZj6cilar8wef66mclp3m6Z:~/.shadowsocks# -v -s 47.91.128.140
 
** DOES NOT WORK ** 2016-12-28 15:04:00 INFO: cmd: ss-server -p 443 -m aes-128-cfb -k qaz123 --manager-address 0.0.0.0:6001 -f /root/.shadowsocks/.shadowsocks_443.pid -t @iZj6cilar8wef66mclp3m6Z:~/.shadowsocks# -v -s 47.91.128.140
 
**WORKS** 2016-12-28 15:06:00 INFO: cmd: ss-server -p 443 -m aes-128-cfb -k qaz123 --manager-address 0.0.0.0:6001 -f /root/.shadowsocks/.shadowsocks_443.pid -t @iZj6cilar8wef66mclp3m6Z:~/.shadowsocks# -v -s 47.91.128.140

** DOES NOT WORK **  2016-12-28 15:08:00 INFO: cmd: ss-server -p 443 -m aes-128-cfb -k qaz123 --manager-address 0.0.0.0:6001 -f /root/.shadowsocks/.shadowsocks_443.pid -t @iZj6cilar8wef66mclp3m6Z:~/.shadowsocks# -v -s 47.91.128.140
 
**WORKS** 2016-12-28 15:10:00 INFO: cmd: ss-server -p 443 -m aes-128-cfb -k qaz123 --manager-address 0.0.0.0:6001 -f /root/.shadowsocks/.shadowsocks_443.pid -t @iZj6cilar8wef66mclp3m6Z:~/.shadowsocks# -v -s 47.91.128.140

**Comment by madeye** [comment]
What's your config file? The `/etc/shadowsocks-libev/config.json` in your command line.

**Comment by lemoz** [comment]
{
    "server":"***********",
    "server_port":24500,
    "local_port":1080,
    "password":"password",
    "timeout":5,
    "method":"aes-128-cfb"
}

**Comment by madeye** [comment]
It's quite weird that your log didn't include `-c path_to_config_file`. Is there any special character in your home directory path or your password?

**Comment by madeye** [comment]
An example of `ss-manager`'s output is:

```
 2016-12-28 15:29:48 INFO: cmd: src/ss-server -m aes-128-cfb --manager-address 127.0.0.1:8999 -f /Users/max/.shadowsocks/.shadowsocks_8001.pid -c /Users/max/.shadowsocks/.shadowsocks_8001.conf -t 5 -v -s 127.0.0.1
```

Also, password should be passed in config file. You should never have `-k password` in your log.

**Comment by madeye** [comment]
Could you confirm that you're using the latest shadowsocks-libev?

**Comment by lemoz** [comment]
My command is:
ss-manager --manager-address 0.0.0.0:6001 -c /etc/shadowsocks-libev/config.json -v

It doesn't use the config file at all for some reason. It does receive information from my web manager

**Comment by madeye** [comment]
What's your output of `ss-manager -h | head`

**Comment by lemoz** [comment]
2.4.0
Should I build from latest version?

**Comment by madeye** [comment]
Yes, please try the latest stable version 2.5.6.

2.4.0 is a very old version, and also a pre-release: https://github.com/shadowsocks/shadowsocks-libev/releases/tag/v2.4.0

**Comment by lemoz** [comment]
The installation directions are not clear. I have downloaded the source but when I follow the instructions the commanded given do not work. I am not experienced in building from source.

**Comment by madeye** [comment]
You may try this:

```
sudo sh -c 'printf "deb http://ftp.debian.org/debian jessie-backports main" > /etc/apt/sources.list.d/jessie-backports.list'
sudo apt update
sudo apt -t jessie-backports install shadowsocks-libev
```

**Comment by madeye** [comment]
Also you may try some scripts like this one:

https://raw.githubusercontent.com/teddysun/shadowsocks_install/master/shadowsocks-libev-debian.sh

**Comment by lemoz** [comment]
What is the password?
