### ISSUE TITLE
Ipv6 defaulting error

### ISSUE THREAD

**Issue by lemoz** [shadowsocks/shadowsocks-libev#1016]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
2.5.6

### What operating system are you using?
ubuntu 14

### What did you do?
Trying to get shadowsocks to defualt to ipv6
ss-manager --manager-address 0.0.0.0:6001 -c /etc/shadowsocks-libev/config.json -6 -v
### What did you expect to see?
success

### What did you see instead?
root@iZj6cilar8wef66mclp3m6Z:/etc/default# ss-manager --manager-address 0.0.0.0:6001 -c /etc/shadowsocks-libev/config.json -6 -v
 2016-12-28 17:53:54 ERROR: Unrecognized option: (null)

**Comment by madeye** [comment]
Fixed via 2694e86
