### ISSUE TITLE
TLS obf-method does not work.

### ISSUE THREAD

**Issue by testcaoy7** [shadowsocks/shadowsocks-libev#1019]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
v2.6.0 for both server and client

### What operating system are you using?
On Server: Ubuntu 14.04
On Client: Windows 10 + Cygwin

### What did you do?
Test functionality of obf methods

### What did you expect to see?
Working TLS obf method

### What did you see instead?
TLS obf-method does not work. 
The server gives me this: `ERROR: failed to handshake with ...`
HTTP obf-method works fine.

### What is your config in detail (with all sensitive info masked)?
On Server: `ss-server -s 0.0.0.0 -p 443 -k pswd -m aes-128-ctr -t 20 -u -A -d 45.124.66.200 --fast-open --obfs tls`
On Client: `ss-local -s server-ip -p 443 -l 1984 -k pswd -m aes-128-ctr -t 20 -u -A --obfs tls`

**Comment by debiansid** [comment]
Maybe you need certificate to make tls work?

**Comment by madeye** [comment]
Try to remove `--fast-open` in your server command line.

**Comment by madeye** [comment]
I tried your command line with the commit 47b3406. Everything works well. Could you double check your command line?

Also if you behind a `ss-redir` router, tls-obfs may not work for you. A workaround is to bypass your server IP on your router.

**Comment by testcaoy7** [comment]
I tried the commands below:
Server: `ss-server -s 0.0.0.0 -p 443 -k pswd -m aes-128-ctr -t 20 -A -d 45.124.66.200 --obfs tls`
Client: `ss-local -s server_ip -p 443 -l 1984 -k pswd -m aes-128-ctr -t 20 -A --obfs tls --obfs-host world.taobao.com`

And it's not working. HTTP obf works fine.

Server error: `ERROR: failed to handshake with client_ip`
Client error: `ERROR: remote_recv_cb_recv: 远程主机强迫关闭了一个现有的连接。`

Could this problem relate to ISP or Cygwin ?

**Comment by madeye** [comment]
@testcaoy7 Are you using shadowsocks on your router?

**Comment by madeye** [comment]
@testcaoy7 Any warning message when you build shadowsocks on Cygwin?

**Comment by wongsyrone** [comment]
Could this related to endianness check in obfs_tls?

**Comment by madeye** [comment]
@wongsyrone Nope, it looks related to `#pragma pack(1)`. It may have issues on very old cygwin.

**Comment by madeye** [comment]
Could you try this commit: b47d289

**Comment by testcaoy7** [comment]
I have tested commit b47d289 and error remains. This problem is related to Cygwin. I have compiled the same code under Ubuntu on Windows and TLS obf works fine.

**Comment by wongsyrone** [comment]
How about 60cdaf98df9e57cb37820afbc4b37792cdf08f98

**Comment by testcaoy7** [comment]
@wongsyrone The problem remains.

**Comment by bigtan** [comment]
@testcaoy7 try to compile with msys2.

**Comment by sadoneli** [comment]
works fine on ASUS merlin xiaobao firmware ss 3.1.4

**Comment by debiansid** [comment]
surge on iOS can not work either.
Dec 29 11:41:36 virmach /usr/bin/ss-server[29542]: message repeated 8 times: [ failed to handshake with 171.210.35.172]
Dec 29 11:41:36 virmach /usr/bin/ss-server[29542]: block all requests from 171.210.35.172

**Comment by debiansid** [comment]
ignore my input there, I did not update my server side into newest git version. obfs http works for surge

**Comment by testcaoy7** [comment]
@bigtan I tried and msys2 version of ss-local also has the same problem.

**Comment by madeye** [comment]
It looks like an issue related to `ms_struct` https://sourceforge.net/p/mingw-w64/bugs/275

**Comment by madeye** [comment]
Could you try this 6ecbf8e?

**Comment by testcaoy7** [comment]
I am sorry and problem remains with commit 6ecbf8e.

**Comment by madeye** [comment]
Could you post your full building log? Do it with

```
make V=99
```

**Comment by testcaoy7** [comment]
[make.txt](https://github.com/shadowsocks/shadowsocks-libev/files/678399/make.txt)

The Cygwin building log.

**Comment by madeye** [comment]
What about 79c722c?

**Comment by testcaoy7** [comment]
I cannot compile commit 79c722c on Ubuntu Server. System gives me errors. (See attached file)
[Error.txt](https://github.com/shadowsocks/shadowsocks-libev/files/678427/Error.txt)


I also compiled this commit under Cygwin and it passed. 

I use 79c722c version of ss-local and the problem remains. 

PS: The ss-server came from earlier commit because I cannot  compile 79c722c under Ubuntu.

**Comment by madeye** [comment]
Thanks! I'm installing a virtual machine to verify this issue....

**Comment by madeye** [comment]
I tried the latest version on Cygwin ([Babun]) + Windows 10. Everything works well.

Could you double check your config? Make sure no typos there. Also, you may try to update your Cygwin first.

[Babun]: http://babun.github.io/

**Comment by testcaoy7** [comment]
@madeye I tried Babun with the latest commit and the problem solved! Thank you for your hard work and patience.

**Comment by testcaoy7** [comment]
While using TLS obfs, I got a lot of `ERROR: getpeername: Transport endpoint is not connected` and lot of connection reset.

**Comment by cokebar** [comment]
@madeye I'm using a router with LEDE, and have the similar problem. I use @aa65535 's precompile ipk. Please refer to https://github.com/shadowsocks/luci-app-shadowsocks/issues/73
