### ISSUE TITLE
SSR好像被你们弄哭了？啥情况

### ISSUE THREAD

**Issue by s5s5** [shadowsocks/shadowsocks-libev#1021]
![SSR好像被你们弄哭了？](https://pbs.twimg.com/media/C01HWmkUoAE4y1l.jpg:large)

啥情况啊？

**Comment by pexcn** [comment]
代码敲不过别人就哭？。。。

**Comment by kxmp** [comment]
他这种人就该哭

**Comment by sdysj** [comment]
too young.

**Comment by madeye** [comment]
I really appreciate her effort on forking and improving shadowsocks protocol.  And I think her project is very cool. You can find more details about the discussion below:

https://github.com/shadowsocks/shadowsocks-org/issues/26#issuecomment-269334985
https://github.com/shadowsocks/shadowsocks-org/issues/26#issuecomment-269336695

**Comment by one360** [comment]
SSR作者有点玻璃心了，TA说的很多话给人的感觉就是一个酸溜溜的小姑娘。

**Comment by codexss** [comment]
Nice shot，我很愿意围观台下群众的嘴脸

**Comment by shmily0827** [comment]
这个时候出来装好人了啊？

**Comment by codexss** [comment]
![](https://pbs.twimg.com/profile_images/378800000822867536/3f5a00acf72df93528b6bb7cd0a4fd0c.jpeg)
