### ISSUE TITLE
Do not start with my original Python version config file

### ISSUE THREAD

**Issue by wck963** [shadowsocks/shadowsocks-libev#1023]
### What version of shadowsocks-libev are you using?
v2.6.0

### What operating system are you using?
Ubuntu 16.04.1 LTS with Linux Kernel 4.9

### What did you do?

```
root@hostname:~# wget https://github.com/shadowsocks/shadowsocks-libev/archive/v2.6.0.tar.gz
root@hostname:~# tar xzvf *gz
root@hostname:~# cd shadowsocks-libev*
root@hostname:~# apt install --no-install-recommends build-essential autoconf libtool libssl-dev gawk debhelper dh-systemd init-system-helpers pkg-config asciidoc xmlto apg libpcre3-dev
root@hostname:~# dpkg-buildpackage -b -us -uc -i
root@hostname:~# cd ..
root@hostname:~# dpkg -i shadowsocks-libev*.deb
root@hostname:~# ssserver -c /path/to/shadowsocks.json
```

### What did you expect to see?
run status or log info

### What did you see instead?
help message

### What is your config in detail (with all sensitive info masked)?
```
{
	"server":"0.0.0.0",
	"port_password":{
		"[0-9]{3,4}":"[0-9a-zA-Z.!-]+",
        	"[0-9]{3,4}":"[0-9a-zA-Z.!-]+",
		"[0-9]{3,4}":"[0-9a-zA-Z.!-]+",
		"[0-9]{3,4}":"[0-9a-zA-Z.!-]+",
		"[0-9]{3,4}":"[0-9a-zA-Z.!-]+",
		"[0-9]{3,4}":"[0-9a-zA-Z.!-]+",
		"[0-9]{3,4}":"[0-9a-zA-Z.!-]+",
		"[0-9]{3,4}":"[0-9a-zA-Z.!-]+",
		"[0-9]{3,4}":"[0-9a-zA-Z.!-]+",
		"[0-9]{3,4}":"[0-9a-zA-Z.!-]+",
        	"[0-9]{3,4}":"[0-9a-zA-Z.!-]+",
		"[0-9]{3,4}":"[0-9a-zA-Z.!-]+"
	},
	"timeout":300,
	"method":"chacha20"
}
```

**Tried to delete } or " and it recognized syntax error. Should not be file open issue.**

**Comment by madeye** [comment]
Unfortunately, shadowsocks-libev does not support "port_password" config. Search the issue tracker for more details.

**Comment by wck963** [comment]
lol I actually did the search but for whole repository, and see keyword "port_password" attended in source code so I tried.

Hope further version could have enhance to echo general message to notify config loading error.
