### ISSUE TITLE
ss-manger may need to check port avaliable

### ISSUE THREAD

**Issue by GhostFlying** [shadowsocks/shadowsocks-libev#1024]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?

2.5.6 on macOS via homebrew

### What operating system are you using?

macOS 10.12.2

### What did you do?

1. run ss-manager

2. send add command to one unavailable port ( other process used or over 65535)

3. ss-manager echo "ok" and try to add these servers

### What did you expect to see?

1. ss-manager echo anything but "ok"

2. no info in stats with this unavailable port

3. no meaningless process exist

### What did you see instead?

1. ss-manager always return "ok"

2. if port is used by other process, add server failed but it will exist in stats 

3. if port is over 65535, one meaningless process will be started and it will exist in stats

Actually this is a minor issue and maybe this should be done by other app?

**Comment by madeye** [comment]
Yes, I think it should be a problem. What about opening a pull request? I'm glad to merge that.

**Comment by GhostFlying** [comment]
I will try to do it :).
Max Lv <notifications@github.com>于2017年1月1日 周日上午10:24写道：

**Comment by GhostFlying** [comment]
After the holidays, I started to do it, and there's one hard choice here and I want to discuss or confirm.

To achieve this, I figure out two ways.

One is ss-manager try to bind the needed port before really run ss-server, it's simple but may have race-condition problem.

The other one is ss-server talks to ss-manager itself ( I think decrease stats report initial interval may enough.) runs normally and ss-manager wait for it and reply to users. It seems better but may lead to modification both in manager and server and the lag to reply (actually, the timeout is hard to decide).

**Comment by madeye** [comment]
I think `SO_REUSEPORT` can help to resolve the race condition here. First, you bind to a port after set `SO_REUSEPORT` on the socket. Then, start the ss-server which is already enabling `SO_REUSEPORT`. At last, you close the socket in `ss-manager`. It works like a lock here.

**Comment by GhostFlying** [comment]
It seems well, I will try it :).

**Comment by madeye** [comment]
Closed via 9753cc5.
