### ISSUE TITLE
docker build faild

### ISSUE THREAD

**Issue by keysona** [shadowsocks/shadowsocks-libev#1027]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?

2.6.0

### What version of  docker are you using?

```shell
➜  ~ docker -v
Docker version 1.12.5, build 7392c3b0ce
```
### What operating system are you using?

Archlinux

### What did you do?

Install shadowsocks-libev via docker.

### What did you expect to see?

Build success.

### What did you see instead?

```shell
➜  ~ curl -sSL "https://github.com/shadowsocks/shadowsocks-libev/raw/master/docker/alpine/Dockerfile" | docker build -t shadowsocks-libev .
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/key/Dockerfile: no such file or directory
(23) Failed writing body
```

### What is your config in detail (with all sensitive info masked)?

Irrelevant.

### How you solve it ?

```
curl -sSL "https://github.com/shadowsocks/shadowsocks-libev/raw/master/docker/alpine/Dockerfile" | docker build -t shadowsocks-libev -
```

Replace ```.``` with ```-```

**Comment by madeye** [comment]
Thanks! Fixed via bf38558.
