### ISSUE TITLE
obfs option in json config file

### ISSUE THREAD

**Issue by cokebar** [shadowsocks/shadowsocks-libev#1029]
### What version of shadowsocks-libev are you using?
2.6.0

### What operating system are you using?
Ubuntu 16.04/Windows7/Windows10

### What did you do?
I'm not sure if obfs is enabled or not when set in json config file.

### What did you expect to see?
A log shall be given out:  obfuscating enabled

### What did you see instead?
Ss will give out " obfuscating enabled" when obfs is enabled by command line:
ss-server(or ss-local) --obfs tls -s X.X.X.X -p XXXX ...

But when obfs is set in config.json like this:
"obfs":"tls"
there's no log given out about whether obfs is enabled.
I don't know if it is correct to set obfs like this in json file.

### What is your config in detail (with all sensitive info masked)?
{
      "server":"X.X.X.X",
      "server_port":9999,
      "local_port":9999,
      "password":"pass",
      "method":"chacha20",
      "auth":true,
      "obfs":"tls",
      "obfs_host":"live.com"
}

**Comment by madeye** [comment]
It should be a bug of log. However, as obfs is already deprecated, it won't be fixed in the future.

More details: https://github.com/shadowsocks/shadowsocks-org/issues/26

**Comment by cokebar** [comment]
thanks
