### ISSUE TITLE
Advice on obfs

### ISSUE THREAD

**Issue by Anonymous-Someneese** [shadowsocks/shadowsocks-libev#1030]
I though obfs is a good idea to get though naive QoS of some ISPs. However it would increase the flow characteristics, like UA always set to curl, 101 upgrade to WebSocket everytimes. The original shadowsocks protocol is designed to be no-characteristics, anonymous thus hard to be distinguished from the normal encrypted flows. I worried that obfs may be a weakness for the YOU KNOW WHO to detect shadowsocks protocol.
Further more, we cannot customize the request and response header. If this feature is widely used, it would be easy to collect all the shadowsocks server:port.

**Comment by madeye** [comment]
The proposal has been deprecated: https://github.com/shadowsocks/shadowsocks-org/issues/26
