### ISSUE TITLE
build dependencies

### ISSUE THREAD

**Issue by Jimmy-Z** [shadowsocks/shadowsocks-libev#1032]
I was told "Shadowsocks-libev is written in pure C and only depends on libev and OpenSSL or mbedTLS." but:

````
checking for asciidoc... /usr/bin/asciidoc
checking for xmlto... no
configure: error: Cannot find `xmlto` in PATH.
````

**Comment by hosiet** [comment]
Build dependencies can be adjusted and reduced to only libev and libssl. For example, you will need to pass `--disable-documentation` to configure script in order to prevent dependency to xmlto here.

View `./configure --help` for detailed options.

**Comment by Jimmy-Z** [comment]
thanks, and sorry not to RTFM.
