### ISSUE TITLE
plugin system

### ISSUE THREAD

**Issue by vfreex** [shadowsocks/shadowsocks-libev#1033]
Is there any proposal on implementing a plugin system?

If so, we are able to integrate obfs, tunneling protocols (like KCP), and other extensions without violating the KISS principle.

**Comment by wongsyrone** [comment]
https://github.com/shadowsocks/shadowsocks-org/issues/28

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks-org/issues/28

**Comment by vfreex** [comment]
Thanks.
It seems to me that the planed plugin system works more like a tunnel. It just help you start multiple processes in a command.  

I am more interested in defining hooks in shadowsocks' source code so that developers can write shared libraries that will be loaded at runtime. That will give developers much more flexibility.

**Comment by Mygod** [comment]
Create forks and make changes there instead for now.

**Comment by librehat** [comment]
@vfreex Do bear in mind that there are other implementations of `shadowsocks`. It would be much simpler for plugin developers to write their plugins (or tunnel services) with almost no restrictions (any programming languages, any licenses)
