### ISSUE TITLE
Connection reset by peer bug

### ISSUE THREAD

**Issue by abigchopstick** [shadowsocks/shadowsocks-libev#1038]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
the latest 2.6.0

### What operating system are you using?
debian, actually running on UBNT ER-X edgemax system, which is essentially a debian distro.

### What did you do?
I'm running ss-redir, tried 4 different servers from 4 different company (services) some with ss, some with ssr (I tried both ss-redir and ssr-redir), all of them have the same problem.

### What did you expect to see?
I expect it to run without error.

### What did you see instead?
I see connection reset by peer and the CPU usage is 70% as shown below.
![image](https://cloud.githubusercontent.com/assets/24934554/21708657/c528f784-d415-11e6-8c37-91fc7abf7f30.png)

The detailed error message is this:
![image](https://cloud.githubusercontent.com/assets/24934554/21708680/02fdf5f0-d416-11e6-9cc9-e6c4a9aa3ced.png)

Server is working fine for a while, but then with the 70% CPU SS-REDIR will be unresponsive and stop working.

I know that you might say it is a network related problem, but to my defense, when I am using clients on Windows or Mac under the same ISP provider, it doesn't show this error at all:
![image](https://cloud.githubusercontent.com/assets/24934554/21708748/7fd17494-d416-11e6-91a9-66ec800d61dc.png)

So I would say even if it is a network related problem, it is only doing it for ss-redir and not the others. Please help me resolve this issue.

To my knowledge this happens to openwrt version of libev ss-redir too because I've used the same 

### What is your config in detail (with all sensitive info masked)?
{
    "server":"106.186.117.xxx",
    "server_port":xxxxx,
    "local_address":"0.0.0.0",
    "local_port":1080,
    "password":"xxxxxxx",
    "timeout":600,
    "method":"aes-128-cfb",
}

Note that I tried at least four other different SS service providers with different encryption, protocol, and even osfd settings (SSR), but they all end up doing the same.

Also I've tried changing timeout to 900 and 1000 but it didn't help.

**Comment by abigchopstick** [comment]
please note that the
xxx.0bad.com from the windows screeenshot has the same IP address as the server config posted above.

**Comment by madeye** [comment]
Resets in your log are expected and normal. And according to your log and CPU time, everything works well.

**Comment by abigchopstick** [comment]
Except it didn't work, I cannot access blocked IPs, only IPs within China because they are not routed through ss-redir.

Also, this reset is occupying 70% of CPU time at all times, you can't call this "normal".

**Comment by abigchopstick** [comment]
thanks, how do I check my version please? I'm not so sure at this point.

**Comment by madeye** [comment]
Run 'ss-redir -v' to check the version number.

In addition, edge routers are never tested. I suggest try routers with OpenWRT instead, which is officially supported.

**Comment by abigchopstick** [comment]
it is shadowsocks-libev 2.5.6 with OpenSSL 1.0.2h  3 May 2016

Sorry I was mistaken.

I will try to get an openwrt to test it.

**Comment by abigchopstick** [comment]
Would it help if I provide my router's IP and ssh login to you, so you can take a look at it?

**Comment by madeye** [comment]
I don't think that will help. Actually, I have R7000 running 'ss-redir' 7x24 hours, if there is any issue, I even cannot send this comment to you.

**Comment by abigchopstick** [comment]
I'm pretty sure this bug is related to my ISP, but it is only occurring
with my ISP and ss-redir because it doesn't happen on WINDOWS/MAC clients
under the same network.

Are there any other LINUX clients with ss-redir support? I was told that GO
and PYTHON version doesn't support ss-dir but ss-local.

I'm trying to make this bug occur again on an openwrt router so then you
might want to look into it more.

I am also trying to get more people to report similar bugs. I don't think I
am alone here.

Also one of my friend is having the same setup on ER-X router, but he has
no problem because he is on a different province, however, if I use the
same SS server he uses, I will have the same problem.

Regards,

黄甦
Huang, Su

**Comment by madeye** [comment]
IMO, your issue looks related to your router's toolchain or kernel. That's why I suggest to use OpenWRT instead.

**Comment by abigchopstick** [comment]
As I mentioned above, my friend is using the same ER-X router and same OS
version 1.9.1. In fact, he compiled ss-redir for me, and he is not having
any issues.

Regards,

黄甦
Huang, Su

**Comment by madeye** [comment]
Have you enabled UDP? What's your solution for handling DNS queries?

**Comment by abigchopstick** [comment]
No I have not, using ChinaDNS for DNS queries.

Actually here's how it is done:
http://allenn.cn/articles/2016-10/2016-10-20-edgemax-ss-tutorial/

Regards,

黄甦
Huang, Su

**Comment by madeye** [comment]
Could you double check it's not an issue of ChinaDNS? To verify this, when your connection is lost, try to visit https://216.58.200.4

**Comment by madeye** [comment]
After reading the link, I found it's actually using UDP of `ss-tunnel` for DNS resolving. It may not work with some ISPs, as UDP traffic would be dropped for QoS purpose.

My suggestion is to use dnsmasq + dnscrypt (TCP mode) for DNS query instead. You can ask your friend to build dnscrypt for you.

**Comment by abigchopstick** [comment]
Will do, I will check it out first, thanks.

**Comment by abigchopstick** [comment]
![image](https://cloud.githubusercontent.com/assets/24934554/21712871/0432ee64-d432-11e6-8f5a-0ed8b2fee73c.png)

Before I try dnscrypt, I stopped ss-tunnel and chinadns, running ss-redir alone, but even when it is the only process running, it does the same thing.
![image](https://cloud.githubusercontent.com/assets/24934554/21712947/56c97508-d432-11e6-9e8b-ce5d2ed3d30c.png)

**Comment by madeye** [comment]
The log shows that the connection reset happens when receiving data from your devices in your LAN. It looks like a misconfig of the iptables rules.

Add `-v` to your `ss-redir` command line for verbose mode and post your logs here.

**Comment by abigchopstick** [comment]
![image](https://cloud.githubusercontent.com/assets/24934554/21713369/a504d29c-d434-11e6-9017-e1df190c8dd8.png)

Instead of a million connection reset by peer, it seems that 1/1000 of them went though as you can see from below log, but the other 999/1000 is still connection reset by peer.

2017-01-06 17:19:23 ERROR: server recv: Connection reset by peer
 2017-01-06 17:19:23 ERROR: server recv: Connection reset by peer
 2017-01-06 17:19:23 ERROR: server recv: Connection reset by peer
 2017-01-06 17:19:23 INFO: redir to 172.217.25.67:443, len=517, recv=517
 2017-01-06 17:19:23 ERROR: server recv: Connection reset by peer
 2017-01-06 17:19:23 INFO: redir to 64.202.125.16:443, len=517, recv=517
 2017-01-06 17:19:23 ERROR: server recv: Connection reset by peer

2017-01-06 17:19:26 ERROR: server recv: Connection reset by peer
 2017-01-06 17:19:26 ERROR: server recv: Connection reset by peer
 2017-01-06 17:19:26 INFO: redir to 172.217.25.67:443, len=216, recv=216
 2017-01-06 17:19:26 ERROR: server recv: Connection reset by peer
 2017-01-06 17:19:26 INFO: redir to 172.217.25.67:443, len=494, recv=494
 2017-01-06 17:19:26 ERROR: server recv: Connection reset by peer

**Comment by madeye** [comment]
I think you have some iptables issues in your configuration. In your log, never a `remote recv` log appears, which means it's not related to ISP or WAN connection, it's just an issue on your router or in your LAN connection.

**Comment by madeye** [comment]
BTW, `server recv: Connection reset by peer` means the client connected to your `ss-redir` closes the connection actively.

**Comment by abigchopstick** [comment]
Are you saying that some devices on my lan is trying to reset the connection of ss-redir repeatly and nothing related to the WAN?

**Comment by madeye** [comment]
From the log you provided, the answer is yes. None of your log is related to the connection to the remote shadowsocks server. So double check your iptables rules.

**Comment by abigchopstick** [comment]
Turns out it was one of my VM win7 machine constantly harassing ss-redir. I am unsure if it was parallel desktop or it was virus on my VM. At any rate it is unrelated to ss-redir.

Sorry for the mistake. 

Thanks a lot for your help!

**Comment by 0neday** [comment]
Got same error! But this could be improved by using haproxy to proxy your 2 ss server.
![image](https://user-images.githubusercontent.com/15697803/80798600-9e281a80-8b59-11ea-8109-62be5157e0bc.png)
