### ISSUE TITLE
插件现在怎么使用

### ISSUE THREAD

**Issue by Sherlock-Holo** [shadowsocks/shadowsocks-libev#1045]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
2.6.1

### What operating system are you using?
Arch Linux 4.9.0-1-lily

### What did you do?
update to 2.6.1

### What did you expect to see?
能够告诉咱如何使用插件

**Comment by rampageX** [comment]
On the server:

ss-server -c config.json --plugin "obfs-server --obfs http"
On the client:

ss-local -c config.json --plugin "obfs-local --obfs http --obfs-host www.baidu.com"

Tested work.

But i dont know how to set these in json file~

**Comment by Sherlock-Holo** [comment]
@rampageX 

` ss-server -c config.json --plugin "obfs-server --obfs tls" `

就是说，原有的obfs还是可以继续使用咯，可是如果使用第三方插件该怎么用？

**Comment by madeye** [comment]
Currently, there is only one SIP003 compatible plugin (simple-obfs).

**Comment by Sherlock-Holo** [comment]
所以其他插件等待他人开发中？
