### ISSUE TITLE
Plugin not quit with ss ?

### ISSUE THREAD

**Issue by rampageX** [shadowsocks/shadowsocks-libev#1046]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
ss 2.6.1                      obfs 0.0.1

### What operating system are you using?
Linux asus 2.6.36.4brcmarm #1 SMP PREEMPT Sat Nov 26 22:11:16 CST 2016 armv7l GNU/Linux

### What did you do?
Start :
`ss-local -c config.json --plugin "obfs-local --obfs http --obfs-host www.baidu.com"`
Stop:
kill `pidof ss-local`

### What did you expect to see?
obfs-local quit with ss-local

### What did you see instead?
obfs-local still running after ss-local be killed, if i start ss-local again, the tunnel stop work even though ss-local is running(Cant talk to old obfs-local?). I must manual kill obfs-local and ss-local at the same time, then start ss-local agian, tunnel work.

### What is your config in detail (with all sensitive info masked)?
...

ss-server and obfs-server have same behavior.

Is this the behavior of the design? Or a bug ?

**Comment by madeye** [comment]
What's your config?

**Comment by madeye** [comment]
I cannot reproduce this on my local machine. Have you updated both shadowsocks-libev and simple-obfs to the latest?

**Comment by rampageX** [comment]
OK, i know whats wrong with this. I always use **static** compile ss and obfs, so... 

I try normal compile version, it's ok.

BTW:  Is possible to fix this?

**Comment by madeye** [comment]
I think static linking should also work. Could you try a clean build again?

**Comment by rampageX** [comment]
I try clean build ss 2.6.1 from release tar.gz and obfs git newest, same...but i find a strange thing, i cant kill ss-local at all only if i kill obfs-local first: 

![111](https://cloud.githubusercontent.com/assets/994081/21750815/11010498-d5f7-11e6-9386-5d9c1ca466dc.gif)

and my config.json:

{
  "server": "xxx.xxx.xxx.xx",
  "server_port": 13026,
  "password": "fuckugfw",
  "method": "aes-128-cfb",
  "plugin": "obfs-local --obfs http --obfs-host www.baidu.com",
  "remarks": "SS-OBFS",
  "auth": false
}

**Comment by rampageX** [comment]
OK, i find out why. I start `ss-local` with `-a nobody`, at the same time `obfs-local` start by ss-local but run as `root`. I can fix all this by delete `-a nobody` parameter.

As i know Tomato only have two user: root and nobody, i dont know why `ss-local` run as `nobody` but `obfs-local` actually will run as `root`.

**Comment by madeye** [comment]
When adding `-a` to your shadowsocks command line, please make sure also add it to the plugin's.

**Comment by debiansid** [comment]
Is there startup script can start ss and plugin?

**Comment by rampageX** [comment]
@madeye I got it, thx.
