### ISSUE TITLE
Plugin Configuration in config.json

### ISSUE THREAD

**Issue by simonsmh** [shadowsocks/shadowsocks-libev#1048]
Plugin Configuration in config.json

### What version of shadowsocks-libev are you using?
2.6.1

### What operating system are you using?
Debian

### What did you do?
Trying to use default systemd only to manage ss-libev

### What did you expect to see?
Add plugin configuration to config.json

For example:
...
{plugin}:"plugin running command(obfs-local -foo -bar abc.xyz)";
...

**Comment by lcdtyph** [comment]
I saw some related code in [jconf.c](https://github.com/shadowsocks/shadowsocks-libev/blob/master/src/jconf.c#L202).
So you can just write these to your configuration file:
{
    ...
    ...
    "plugin": "obfs-local -foo -bar"
}
