### ISSUE TITLE
How uninstall shadowsocks

### ISSUE THREAD

**Issue by yzfdjzwl** [shadowsocks/shadowsocks-libev#1049]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
the newest

### What operating system are you using?
centos7

### What did you do?
I want to uninstall shadowsocks

### What did you expect to see?
I wish I can do this: "make uninstall/distclean/veryclean "

### What did you see instead?
You can't help me~

### What is your config in detail (with all sensitive info masked)?
Can I not answer this question?

**Comment by madeye** [comment]
`sudo make uninstall`

**Comment by yzfdjzwl** [comment]
I have tried, but it didn't work...

**Comment by madeye** [comment]
Try to detect the prefix by executing `which ss-local`, and make sure it matches your `prefix` settings when configuring.

**Comment by yzfdjzwl** [comment]
thank u,  I find <code>no ss-local</code> after try <code>which ss-local</code>, and I know I have uninstall ss, maybe because  the other version ss I have installed, how fool I am!!! Thanks again~
