### ISSUE TITLE
Question in plugin

### ISSUE THREAD

**Issue by Mygod** [shadowsocks/shadowsocks-libev#1050]
https://github.com/shadowsocks/shadowsocks-libev/commit/61b82c45c524e4ed13cc8e13f0d818b68a8cb4b5#diff-0235f01a49d01b35e981a41f59a9d2d6R1770

Because of this line, when launching a plugin in plugin mode,

* ss-server listens on a random port on server_host;
* plugin-server listens on server_host:server_port unless manually overridden by user.

This is really weird. Because:

* If ss-server without plugin isn't supposed to work, ss-server should listen on a random port on loopback address, i.e. `::1` and `127.0.0.1`, instead of server_host;
* If ss-server without plugin is supposed to work, ss-server should listen on server_host:server_port and plugin-server needs manual configuration by user, e.g. `-p 1984`.

Currently it's a mix of both which doesn't make sense. The same thing applies to `ss-local`.

**Comment by madeye** [comment]
Yes, it'd be my bug.

**Comment by Mygod** [comment]
So is ss-server without plugin supposed to work in this scenario?

**Comment by madeye** [comment]
Without plugin, ss-server listens on server_host.
With plugin, ss-server listens on 127.0.0.1.

**Comment by Mygod** [comment]
I see. So users that wishes both of them to work would need to use
standalone mode?

**Comment by madeye** [comment]
Right.
