### ISSUE TITLE
block all requests from 127.0.0.1

### ISSUE THREAD

**Issue by suikatomoki** [shadowsocks/shadowsocks-libev#1051]
客户端混淆参数填错无法使用，及时修正客户端混淆参数后仍无法使用，重启服务端程序后使用正常。
log如下：
![qq 20170109165607](https://cloud.githubusercontent.com/assets/10336224/21761463/1ea50292-d68e-11e6-8bcd-70a39205a868.png)

服务端正确的参数：--plugin "obfs-server --obfs tls"
客户端正确的参数：obfs-local --obfs tls --obfs-host www.baidu.com
客户端填错时的参数：obfs-local --obfs http --obfs-host www.baidu.com
服务端版本：libev2.6.1
客户端版本：libev2.6.1
混淆程序：simple-obfs

**Comment by madeye** [comment]
It's expected. Too many handshake failures would get your IP blocked automatically.

**Comment by suikatomoki** [comment]
@madeye 
It is not mean blocked 127.0.0.1? Just block my public IP? I am not sure. But I change my public IP just now, it also can not use. Only restart ss-server can solve that.

**Comment by madeye** [comment]
OK, it should be a bug.

**Comment by suikatomoki** [comment]
@madeye  maybe the ss-server blocked the obfs-server,not my.

**Comment by Jieee006** [comment]
I have the same issue "block all requests from 127.0.0.1", ss-libev version is 2.6.1 with simple-obfs. I had to restar ss-libev to resolve this problem.Is it a bug?

**Comment by Windendless** [comment]
server.c:1528:31: error: use of undeclared identifier 'plugin'
        if (!in_white_list && plugin == NULL
                              ^
1 error generated.

**Comment by feilongfl** [comment]
I have a similar issues,it show me:
> block all requests from ::1
