### ISSUE TITLE
多个插件的问题

### ISSUE THREAD

**Issue by Sherlock-Holo** [shadowsocks/shadowsocks-libev#1052]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
2.6.1

### What operating system are you using?
Arch Linux

### What did you expect to see?
如果可以使用多个插件的话，是否添加一下插件的调用顺序

**Comment by suikatomoki** [comment]
Plugin over plugin is NOT supported. Only one plugin can be enabled when a shadowsocks service is started. If you really need this feature, implement a plugin-over-plugin transport as a SIP003 plugin
