### ISSUE TITLE
可否实现vpn的功能

### ISSUE THREAD

**Issue by cjl3230** [shadowsocks/shadowsocks-libev#1056]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
v2.5.6

### What operating system are you using?
Centos 6

### What did you do?
VPS(Centos6(安装ss-libev服务端, 本地虚拟机(Centos6)做网关用shadowsocks-libev做客户端,实现tcp udp的透传,GTA5 玩家互联需要udp协议打洞,本地网络类型nat3 想通过shadowsocks-libev进行vpn的功能,不知道目前版本可否实现.应该如何实现.

### What did you expect to see?
VPS启动正常,端口开放正常

### What did you see instead?
基于目前几种vpn(pptp,l2tp,ipsec)被封锁,导致不能使用vpn达到上述要求,希望能通过ss

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks-libev#advanced-usage

**Comment by hellofwy** [comment]
也可以试试 OpenConnect VPN

**Comment by cjl3230** [comment]
@hellofwy @madeye  谢谢 我来试试看
