### ISSUE TITLE
commit 355c264 could not listen UDP port

### ISSUE THREAD

**Issue by lixingcong** [shadowsocks/shadowsocks-libev#1057]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?

	355c264a20321548373f37ab26335ffa864a55b6

### What operating system are you using?

	ubuntu 16.04.1 x64(both server and client side)

### What did you do?

1.upgrade 2.6.0 to 2.6.1
2.compiling and installation was ok.
3.service shadowsocks-libev restart

### What did you expect to see?

proxy UDP packet, e.g. DNS request.

### What did you see instead?

On client side I could not recv UDP packet(DNS tunnel).

Let me check the listening ports on server side(version: 2.6.1):

	root@ts:~# netstat -l
	Active Internet connections (only servers)
	Proto Recv-Q Send-Q Local Address           Foreign Address         State      
	tcp        0      0 *:https                 *:*                     LISTEN     
	tcp        0      0 *:8989                 *:*                     LISTEN     
	tcp        0      0 *:http                  *:*                     LISTEN         
	tcp6       0      0 [::]:https              [::]:*                  LISTEN     
	tcp6       0      0 [::]:8989              [::]:*                  LISTEN     
	tcp6       0      0 [::]:http               [::]:*                  LISTEN        
	udp        0      0 *:bootpc                *:*                                
	udp6       0      0 [::]:8989              [::]:*                             
	udp6       0      0 [::]:8989              [::]:* 

I could not find UDP listen pot on ipv4 stack.

Then I downgrade to shadoswsocks-libev 2.6.0, UDP packet proxy works fine, it seems that UDP port listening is ok.

	root@ts:~/temp/ss# netstat  -l
	Active Internet connections (only servers)
	Proto Recv-Q Send-Q Local Address           Foreign Address         State      
	tcp        0      0 *:https                 *:*                     LISTEN     
	tcp        0      0 *:8989                 *:*                     LISTEN     
	tcp        0      0 *:http                  *:*                     LISTEN          
	tcp6       0      0 [::]:https              [::]:*                  LISTEN     
	tcp6       0      0 [::]:8989              [::]:*                  LISTEN     
	tcp6       0      0 [::]:http               [::]:*                  LISTEN        
	udp        0      0 *:8989                 *:*                                
	udp        0      0 *:bootpc                *:*                                
	udp        0      0 *:38990                 *:*                                
	udp6       0      0 [::]:8989              [::]:* 

### What is your config in detail (with all sensitive info masked)?

	$ cat config.json
	{
		"server":["[::0]", "0.0.0.0"],
		"server_port":8989,
		"local_port":1080,
		"password":"password",
		"timeout":60,
		"auth":true,
		"method":"chacha20"
	}

**Comment by madeye** [comment]
Try `netstat -an | grep 1080`

**Comment by madeye** [comment]
I tried your config. Here is the output I got:

```
~/w/shadowsocks-libev> netstat -an | grep 8989
tcp        0      0 0.0.0.0:8989            0.0.0.0:*               LISTEN
tcp6       0      0 :::8989                 :::*                    LISTEN
udp6       0      0 :::8989                 :::*
udp6       0      0 :::8989                 :::*
```

**Comment by lixingcong** [comment]
Sorry for my typo

It seems that the following cmd works fine:

	ss-server -c config.json -u

But this command could not listen UDP port. Maybe it was caused by init.d script?

	service shadowsocks-libev restart

**Comment by madeye** [comment]
OK, it'd be a bug.
