### ISSUE TITLE
how run ss-server  on background？

### ISSUE THREAD

**Issue by elric8** [shadowsocks/shadowsocks-libev#1058]
ss-server -c /etc/config.json -d start -u --plugin "obfs-server --obfs http"
i add -d start
but still not run  on background

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks-libev/blob/master/doc/ss-server.asciidoc#options

**Comment by elric8** [comment]
@madeye
thanks for reply
but ur link there is nothing about how to run ss-server on background

**Comment by lcdtyph** [comment]
>-f <pid_file>
        Start shadowsocks as a **daemon** with specific pid file.

A daemon runs in background.

**Comment by pexcn** [comment]
Use `-f` params.

**Comment by suikatomoki** [comment]
ss-server -c config.json -f ss-server.pid

**Comment by Mygod** [comment]
`ss-server &`

**Comment by cdkfox** [comment]
> `ss-server &`

ss-server &! works better this way....
