### ISSUE TITLE
--firewall失效？

### ISSUE THREAD

**Issue by baggiogogo** [shadowsocks/shadowsocks-libev#1061]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
last version

### What operating system are you using?
debian8.0

 /usr/local/bin/ss-server -A -c /etc/shadowserver.json --firewall

升级采用的是 
git pull
./configure && make
make install

上一个版本启用 --firewall 参数，日志可以显示已打开，IPtables -L也可以显示，这个版本启用参数后什么都没有显示，也不知是否正确打开。

**Comment by madeye** [comment]
`--firewall` will be deprecated in the next release. It caused too many problems.

**Comment by baggiogogo** [comment]
明白了，请教下去除之后还能autoblock吗，--acl blacklist.txt？或者不需要设置任何参数？
谢谢！

**Comment by Mygod** [comment]
+1. We need a better autoban mechanism for SIP003?

**Comment by madeye** [comment]
@baggiogogo  Auto blocking still works, everything is handled internally.

**Comment by baggiogogo** [comment]
好的，谢谢！

**Comment by madeye** [comment]
@Mygod Yes, maybe send a blocking message to the plugin. But it's still a low priority issue.
