### ISSUE TITLE
How to check Shadowsocks port working or not remotely

### ISSUE THREAD

**Issue by CyberLeopard** [shadowsocks/shadowsocks-libev#1068]
Hi,

Is it possible to check whether a specific Shadowsocks port working or not by client side using Haproxy or some others?

Haproxy can using TCP to check weather a port open or not, but can't determine whether Shadowsocks work or not. Sometimes TCP check passed but Shadowsocks communication blocked by something.

Thank you so much!

**Comment by madeye** [comment]
The bad new is you can't. Shadowsocks is designed to be not detectable by third-party.

**Comment by Mygod** [comment]
You can do a HTTP client test as in shadowsocks-android.
