### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by Wyerchen** [shadowsocks/shadowsocks-libev#1069]
centos 6.8 

git了最新代码

报错如下

make[2]: Entering directory `/root/shadowsocks-libev/src'
  CC       ss_redir-redir.o
cc1: warnings being treated as errors
redir.c: 在函数‘main’中:
redir.c:777: 错误：未使用的变量‘plugin_args’
make[2]: *** [ss_redir-redir.o] 错误 1
make[2]: Leaving directory `/root/shadowsocks-libev/src'
make[1]: *** [all-recursive] 错误 1
make[1]: Leaving directory `/root/shadowsocks-libev'
make: *** [all] 错误 2

**Comment by spwei** [comment]
看下代码分支是否为：https://github.com/shadowsocks/shadowsocks-libev.git

**Comment by Wyerchen** [comment]
https://github.com/madeye/shadowsocks-libev  29e8022

**Comment by littlesum** [comment]
我也出现这个问题了 意思是madeye的分支有问题么？我也是git他的分支 换一个试试

**Comment by spwei** [comment]
@Wyerchen @littlesum 换成https://github.com/shadowsocks/shadowsocks-libev.git吧

**Comment by madeye** [comment]
Please update https://github.com/shadowsocks/shadowsocks-libev to the latest.
