### ISSUE TITLE
how to find out where's the problem?

### ISSUE THREAD

**Issue by smthvitas** [shadowsocks/shadowsocks-libev#1076]
### What version of shadowsocks-libev are you using?
2.4.5

### What operating system are you using?
netGear R7k router with merlin installed

### What did you do?
I have a ss server, which is working fine. I can use it within my windows laptop, mac book air.
Now I want to build up an automatic proxy on my router using shadowsocks-libev，
here's the command line:
_> ss-redir -v -c /opt/etc/shadowsocks.json > /var/log/ss-redir.log &_
and then：
_ps | grep ss     --router: the client is running well
netstat -an | grep 7070     --router: found 7070 port listening
telnet 192.168.1.1 7070     --MBA: telnet from my mac book air, connected_
But when I specify the proxy to 192.168.1.1:7070/socks5 in chrome, I just got an "ERR_TIMED_OUT" message.

How to debug this problem?
there's nothing in ss-redir.log except the startup message:
 2017-01-14 15:39:04 INFO: initialize ciphers... aes-256-cfb
 2017-01-14 15:39:04 INFO: listening at 0.0.0.0:7080

I've checked the config file shadowsocks.json many times.
Any info will be appreciated.

**Comment by madeye** [comment]
`ss-redir` works as an transparent proxy, rather than SOCKS5 proxy.

To setup a transparent proxy, please follow the instructions here https://github.com/shadowsocks/shadowsocks-libev#advanced-usage or try https://github.com/shadowsocks/luci-app-shadowsocks
