### ISSUE TITLE
Excessive server Timeout

### ISSUE THREAD

**Issue by lemoz** [shadowsocks/shadowsocks-libev#1080]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
From source code

### What operating system are you using?
ubuntu 16.04

### What did you do?
Every few hours I get some time with excessive time outs. Then it returns to normal

![time_out photo](https://cloud.githubusercontent.com/assets/6093725/21970620/1fcdd54a-dbe3-11e6-839b-c61c2df9c581.png)

### What did you expect to see?
Not what is shows me

**Comment by madeye** [comment]
It's expected. You can tune the timeout numbers with `-t timeout_in_sec`

**Comment by lemoz** [comment]
In your experience what is a good time in seconds to start from

**Comment by madeye** [comment]
@lemoz It depends. For public server, pick a small timeout, e.g. 5s. For personal server, pick a large timeout, e.g. 600s.

**Comment by lemoz** [comment]
What is the reasoning behind those numbers
