### ISSUE TITLE
Unable to start on boot

### ISSUE THREAD

**Issue by lemoz** [shadowsocks/shadowsocks-libev#1081]
I am using rc.local to try and run the command on boot but it doesn't seem to be working. 

I had this problem before when using the python port of shadowsocks and I solved it but initializing python before I attempt to call the shadow socks function.

What should I initialize first for shadowsocks-libev

**Comment by simonsmh** [comment]
Try systemd.
`systemctl enable shadowsocks-libev`

**Comment by lemoz** [comment]
This doesn't seem to work. I'm running ubunutu 14.04. 
systemctl: command not found

**Comment by simonsmh** [comment]
wow
try `update-rc.d`

**Comment by lemoz** [comment]
![image](https://cloud.githubusercontent.com/assets/6093725/21974829/1678560c-dc04-11e6-956f-a207344600af.png)

**Comment by simonsmh** [comment]
kidding?
`update-rc.d shadowsocks-libev enable`

lemoz <notifications@github.com>于2017年1月16日周一 15:54写道：

**Comment by lemoz** [comment]
I don't understand the functions that you are trying to make me use. Do you know of any material that will help me understand it.

**Comment by simonsmh** [comment]
man update-rc.d
ss-libev has built-in init.d script. Please use it directly.

lemoz <notifications@github.com>于2017年1月17日周二 06:25写道：

**Comment by lemoz** [comment]
update-rc.d: /etc/init.d/shadowsocks-libev: file does not exist

**Comment by simonsmh** [comment]
https://github.com/shadowsocks/shadowsocks-libev/blob/master/debian/shadowsocks-libev.init

**Comment by lemoz** [comment]
Where do I put the arguments to run as ss-manager with specific port

**Comment by simonsmh** [comment]
use /etc/shadowsocks-libev/config.json please

lemoz <notifications@github.com>于2017年1月17日周二 07:12写道：

**Comment by lemoz** [comment]
update-rc.d: warning: /etc/init.d/shadowsocks-libev missing LSB keyword 'provides'

update-rc.d: warning: /etc/init.d/shadowsocks-libev missing LSB keyword 'required-start'

update-rc.d: warning: /etc/init.d/shadowsocks-libev missing LSB keyword 'required-stop'

update-rc.d: warning: /etc/init.d/shadowsocks-libev missing LSB keyword 'default-start'

update-rc.d: warning: /etc/init.d/shadowsocks-libev missing LSB keyword 'default-stop'

**Comment by simonsmh** [comment]
WAIT A MINUTES!
You can't use the generated HTML index by github.
https://github.com/shadowsocks/shadowsocks-libev/raw/master/debian/shadowsocks-libev.init
Download it directly.

**Comment by lemoz** [comment]
I downloaded it directly.

**Comment by lemoz** [comment]
So all of the errors are fixed, but it is still not booting on start up. I tried running the script manually and everything seems fine but it is not working. 

I want to run ss-manager | define a listening port, set the config location, and set to output verbose 
I think I am not doing this write in the init script. Could you help me figure out how to modify it to work properly.

`# PATH should only include /usr/ if it runs after the mountnfs.sh script
PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC=shadowsocks-libev       # Introduce a short description here
NAME=shadowsocks-libev       # Introduce the short server's name here
DAEMON=/usr/bin/ss-manager   # Introduce the server's location here
DAEMON_ARGS="--manager-address X.X.X.X:XXXX -c /etc/shadowsocks-libev/config.js$
PIDFILE=/var/run/$NAME/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME
`

**Comment by simonsmh** [comment]
`DAEMON=/usr/bin/ss-server    # Introduce the server's location here`
maybe you should change the bin file path by hand and then try again. I didn't use ss-manager so I can't provide further information. 😋

**Comment by lemoz** [comment]
So the server location would be located in the folder where I cloned the repo and installed?
