### ISSUE TITLE
stop obfs-sever with ss-server

### ISSUE THREAD

**Issue by debiansid** [shadowsocks/shadowsocks-libev#1083]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
2.6.2

### What operating system are you using?
ubuntu 14

### What did you do?
/etc/init.d/shadowsocks-libev stop

### What did you expect to see?
ss-server and obfs-server stop

### What did you see instead?

only ss-server stoped

**Comment by madeye** [comment]
Add `a=nobody` to your `plugin_opts`.

**Comment by debiansid** [comment]
@ramnode:/etc/shadowsocks-libev$ sudo /etc/init.d/shadowsocks-libev stop
@ramnode:/etc/shadowsocks-libev$ ps -ef |grep obfsnobody   11354     1  0 06:12 ?        00:00:00 obfs-server

**Comment by debiansid** [comment]
Still cannot stop obfs-server with ss-server
