### ISSUE TITLE
Server: "server recv: Connection reset by peer", Client: "timed out"

### ISSUE THREAD

**Issue by slrslr** [shadowsocks/shadowsocks-libev#1086]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
Shadowsocks-libev 2.5.5

### What operating system are you using?
CentOS 6.8

### What did you do?
Connected successfully with client, but receiving occasional timeouts in logs

### What did you expect to see?
no errors

### What did you see instead?
SERVER: tail /var/log/messages
Jan 17 04:29:10 hostname **openvpn**[8527]: client/***myip***:61497 SENT CONTROL [client]: 'PUSH_REPLY,redirect-gateway def1 bypass-dhcp,dhcp-option DNS 5.9.49.12,dhcp-option DNS 89.18.27.34,dhcp-option DNS 193.183.98.154,dhcp-option DNS 87.98.175.85,dhcp-option DNS 50.116.23.211,dhcp-option DNS 209.141.53.57,dhcp-option DNS 8.8.8.8,route-gateway 10.8.0.1,topology subnet,ping 10,ping-restart 120,ifconfig 10.8.0.2 255.255.255.0' (status=1)
Jan 17 04:30:12 hostname /usr/bin/**ss-server**[28586]: server recv: Connection reset by peer
Jan 17 04:30:14 hostname /usr/bin/ss-server[28586]: server recv: Connection reset by peer
Jan 17 04:31:35 hostname /usr/bin/ss-server[28586]: server recv: Connection reset by peer

CLIENT (Windows 10): view logfile in Shadowsocks 3.3.4 for Windows and it shows plenty of "timed out" errors at the time ss-server shown "timed out" error and also in previous/next seconds.

### What is your config in detail (with all sensitive info masked)?
{
"server":"iphere",
"server_port":8388,
"local_port":1082,
"password":"passwordhere",
"timeout":200,
"method":"aes-256-cfb"
}

----
Please how to discover timeouts/connection reset cause without a doubt?
PS: I have another Linux server in different location that i can use to run Linux commands/scripts.

**Comment by madeye** [comment]
To minimize these logs, you may try large timeout numbers, say, 600s.

**Comment by wongsyrone** [comment]
Try latest shadowsocks-windows release.
