### ISSUE TITLE
Move third-party code to git submodules

### ISSUE THREAD

**Issue by Mygod** [shadowsocks/shadowsocks-libev#1087]
When I was developing simple-obfs-android, it's painful to see there's too many duplicated codes between this one and simple-obfs, especially the third-party code. Please move them to git submodules for easier maintaining as in shadowsocks-android. Thanks.

**Comment by madeye** [comment]
Fixed via 633de3e2288212fea426fbbbe63326cf3e51eb26

**Comment by Mygod** [comment]
Great! The codebase looks much cleaner now.
