### ISSUE TITLE
[RFC] improve document for install from source with CentOS 7

### ISSUE THREAD

**Issue by netroby** [shadowsocks/shadowsocks-libev#1088]
If some one want to compile latest shadowsocks-libev from source with CentOS 7
It may need setup following instruction
```
yum groupinstall "Development Tools"
yum install pcre-devel asciidoc xmlto zlib-devel openssl-devel

```

**Comment by madeye** [comment]
Could you open a pull request for this?

**Comment by netroby** [comment]
Sure.  i will see how can i do it .
