### ISSUE TITLE
build deb failed

### ISSUE THREAD

**Issue by debiansid** [shadowsocks/shadowsocks-libev#1089]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
https://github.com/shadowsocks/shadowsocks-libev/commit/d76a1e60674123e114722520ca46ab34bcb1997c

### What operating system are you using?
Ubuntu 14

### What did you do?
dpkg-buildpackage -b -us -uc -i

### What did you expect to see?
build deb successfully 

### What did you see instead?
ramnode:~/shadowsocks-libev$ dpkg-buildpackage -b -us -uc -i
dpkg-buildpackage: source package shadowsocks-libev
dpkg-buildpackage: source version 2.6.2-1
dpkg-buildpackage: source distribution unstable
dpkg-buildpackage: source changed by Max Lv <max.c.lv@gmail.com>
dpkg-buildpackage: host architecture amd64
 dpkg-source -i --before-build shadowsocks-libev
 fakeroot debian/rules clean
dh clean --with systemd
   dh_testdir
   dh_auto_clean
make[1]: Entering directory `/home/ezhang/shadowsocks-libev'
 cd . && /bin/bash /home/ezhang/shadowsocks-libev/auto/missing automake-1.14 --foreign Makefile
/bin/bash: /home/ezhang/shadowsocks-libev/auto/missing: No such file or directory
make[1]: *** [Makefile.in] Error 127
make[1]: Leaving directory `/home/ezhang/shadowsocks-libev'
dh_auto_clean: make -j1 distclean returned exit code 2
make: *** [clean] Error 2
dpkg-buildpackage: error: fakeroot debian/rules clean gave error exit status 2

### What is your config in detail (with all sensitive info masked)?

**Comment by madeye** [comment]
Try latest commit.

**Comment by debiansid** [comment]
dh_shlibdeps
dpkg-shlibdeps: error: no dependency information found for /usr/lib/libsodium.so.18 (used by debian/shadowsocks-libev/usr/bin/ss-server)
dh_shlibdeps: dpkg-shlibdeps -Tdebian/shadowsocks-libev.substvars debian/shadowsocks-libev/usr/bin/ss-manager debian/shadowsocks-libev/usr/bin/ss-tunnel debian/shadowsocks-libev/usr/bin/ss-local debian/shadowsocks-libev/usr/bin/ss-redir debian/shadowsocks-libev/usr/bin/ss-server returned exit code 2
make: *** [binary] Error 2
dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2

And fixed by change 
my $ignore_missing_info = 1;   
in /usr/bin/dpkg-shlibdeps 

Is that caused by my manual installation of libsodium?

**Comment by rogers0** [comment]
Please refer to the comment I made in another thread:
- https://github.com/shadowsocks/shadowsocks-libev/issues/1095#issuecomment-274445199
