### ISSUE TITLE
ss-manager如何配置运行

### ISSUE THREAD

**Issue by xingezhang** [shadowsocks/shadowsocks-libev#1092]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
2.6.2

### What operating system are you using?
openSUSE

### What did you do?
ss-manager正常工作

### What is your config in detail (with all sensitive info masked)?

ss-manager --manager-address /tmp/ss.sock --executable /usr/local/bin/ss-server -c /etc/shadowsocks/config.json -f /var/run/ss.pid

configfile

{
"server":"0.0.0.0",
"server_port":8080,
"local_address":"127.0.0.1",
"local_port":443,
"password":"Xxxxxxxx",
"timeout":"600",
"method":"chacha20",    
"fast_open":false,
"auth":true,
"plugin":"obfs-server",
"plugin_opts":"obfs=http"
}
可以看到ss-manager正常运行，但是看不到ss-server

然后我安装了netcat-openbsd，输入：
nc -Uu /tmp/ss.sock
提示：nc: cannot use -u and -U

这应该怎么解决？

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks-libev/blob/master/doc/ss-manager.asciidoc

**Comment by xingezhang** [comment]
是因为我的nc版本不对吗？我就是按照文档操作的，每次都提示nc: cannot use -u and -U，怎么办？

**Comment by hosiet** [comment]
GNU netcat does not support UNIX domain UDP protocol. If you really want to use `nc`, you should use OpenBSD-version netcat as described in the man page.

**Comment by xingezhang** [comment]
我安装的就是netcat-openbsd，版本1.89

**Comment by xingezhang** [comment]
This package contains the OpenBSD rewrite of netcat, including support for IPv6, proxies, and Unix sockets.

**Comment by hosiet** [comment]
1.89 is too old, released nearly 10 years ago.

On Debian, you will need netcat-openbsd >= 1.105-7.

**Comment by xingezhang** [comment]
openSUSE 目前找到最新的就是1.89了，看来应该是nc的问题，如果不用nc，有什么办法可以把port和password写进去呢？

**Comment by madeye** [comment]
Try `https://github.com/shadowsocks/shadowsocks-manager`
