### ISSUE TITLE
shadowsocks-libev 2.6.2版Windows 7(32位) MinGW 编译错误

### ISSUE THREAD

**Issue by Springchendg** [shadowsocks/shadowsocks-libev#1096]
错误信息：

  CCLD     ss-local.exe
ss_local-local.o: In function `main':
D:\MinGW\msys\1.0\home\user\shadowsocks-libev-2.6.2\src/local.c:1404: undefined reference to `get_local_port'
D:\MinGW\msys\1.0\home\user\shadowsocks-libev-2.6.2\src/local.c:1473: undefined reference to `start_plugin'
D:\MinGW\msys\1.0\home\user\shadowsocks-libev-2.6.2\src/local.c:1602: undefined reference to `stop_plugin'
collect2.exe: error: ld returned 1 exit status
make[2]: *** [ss-local.exe] Error 1
make[2]: Leaving directory `/home/user/shadowsocks-libev-2.6.2/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/user/shadowsocks-libev-2.6.2'
make: *** [all] Error 2

**Comment by madeye** [comment]
Try the latest commit.

**Comment by Springchendg** [comment]
Same result.

**Comment by Windendless** [comment]
Too many DLLs to deploy，and  Plugin is not supported on MinGW.
so... https://github.com/windendless/shadowsocks-libev
try it

**Comment by wxyzh** [comment]
我在win10 64 bit 用msys2 的mingw64 编译之后 无法运行
结果如下
```./ss-local.exe -c 163.json
 2017-01-21 09:22:29 INFO: initializing ciphers... aes-256-cfb
[1]    334652 segmentation fault  ./ss-local.exe -c 163.json
```
编译步骤
```
1. 编译安装libev，libudns ，libsodium
2.  ./autogen.sh
3.  ./configure --prefix=$HOME/ss --disable-documentation
4. make
```

**Comment by Springchendg** [comment]
Try the latest commit,and the message shows:

$ autoreconf
configure.ac:19: error: possibly undefined macro: AC_DISABLE_STATIC
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:20: error: possibly undefined macro: AC_DISABLE_SHARED
configure.ac:75: error: possibly undefined macro: AC_PROG_LIBTOOL
autoreconf: /usr/bin/autoconf-2.67 failed with exit status: 1

**Comment by Springchendg** [comment]
人工复制粘贴许多文件后终于编译成功。

**Comment by Windendless** [comment]
try：
https://github.com/Windendless/shadowsocks-libev

**Comment by madeye** [comment]
MinGW support is deprecated. Try Ubuntu on Windows 10 or cygwin instead.

**Comment by xseven007** [comment]
@Windendless In your subject"https://github.com/Windendless/shadowsocks-libev" , the libsodium has some bug in core.c. Please fix with "https://github.com/jedisct1/libsodium/issues/482"

**Comment by Windendless** [comment]
@xseven007 
Please try c0c5bc8
