### ISSUE TITLE
why drop udp packet when size > MTU in udprelay?

### ISSUE THREAD

**Issue by wyyzaw** [shadowsocks/shadowsocks-libev#1099]
你好，我在使用最近版本的过程中经常看到log中显示
`[udp] remote_recv_recvfrom fragmentation`
查了一下发现之前老版本的代码好像在udp包大于mtu的时候只会打日志，现在版本中直接把包丢弃了，想请教一下这是出于什么考虑？因为以前旧版本使用时没有感觉到问题，新版在报这个日志的时候udp就不通了
`LOGE("[udp] remote_recv_recvfrom fragmentation");
        goto CLEAN_UP;`

**Comment by madeye** [comment]
Increase `-mtu` if you have problems here.
