### ISSUE TITLE
Handshaking package not acceptable with ss-server

### ISSUE THREAD

**Issue by testingno09** [shadowsocks/shadowsocks-libev#1100]
### What version of shadowsocks-libev are you using?
shadowsocks-libev 2.6.2 with OpenSSL 1.0.2j

### What operating system are you using?
Mac OS 10.11.6

--------

I was testing out handshaking package against this `ss-server`, configuration follows:

- `ss-server` listening on `127.0.0.1:6001`
- using `RC4` cipher with `0123456789abcdef` as its passphrase
- destination IP address is `54.222.60.252:80`

According to spec, the first handshake package would be in pseudo code like:

```
rc4([1, 54, 222, 60, 252, 0, 80], "0123456789abcdef").toString("hex")
> 85 5e 9e 65 01 4e f0
```
> or try with [this][cs] online tool

Hence I've the following command-lines in shell:

```bash
printf %02x 1 54 222 60 252 0 80 |\
xxd -r -p |\
openssl rc4 -K `echo -n 0123456789abcdef | xxd -p` -nosalt -e -nopad |\
nc 127.0.0.1 6001
```

But server side keeps emit log as `ERROR: failed to handshake with x.x.x.x`, could use some help to figure out what's goes wrong, thanks.

[cs]: https://gchq.github.io/CyberChef/?recipe=%5B%7B%22op%22%3A%22From%20Decimal%22%2C%22args%22%3A%5B%22Space%22%5D%7D%2C%7B%22op%22%3A%22RC4%22%2C%22args%22%3A%5B%7B%22option%22%3A%22UTF8%22%2C%22string%22%3A%220123456789abcdef%22%7D%2C%22Latin1%22%2C%22Latin1%22%5D%7D%2C%7B%22op%22%3A%22To%20Hex%22%2C%22args%22%3A%5B%22Space%22%5D%7D%5D&input=MSA1NCAyMjIgNjAgMjUyIDAgODA

**Comment by madeye** [comment]
`54.222.60.252` is a IPv4 address (32bit number, 4 bytes).

**Comment by testingno09** [comment]
Thanks for replay, am I getting this correctly?

```bash
printf %02x  1 54 222 60 252 0 80 | xxd -r -p | xxd -b -c7
0000000: 00000001 00110110 11011110 00111100 11111100 00000000 01010000  .6.<..P
```

It's a buffer with 7 bytes in it.

**Comment by madeye** [comment]
Two more issues:

1. The key is a md5sum of your password.
2. The port number `80` should be big-endian.

**Comment by testingno09** [comment]
Thank you for the hint of that key should be in MD5 checksum, turns out I should be using `password` instead of `key` buffer directly, so the correct invoke would be:

```bash
printf %02x 1 54 222 60 252 0 80 |\
xxd -r -p |\
openssl rc4 -md md5 -k 0123456789abcdef -nosalt -e -nopad |\
nc 127.0.0.1 6001
```

Closing.
