### ISSUE TITLE
Warning showed up when I was trying to install the prequirement for shadowsocks-libev

### ISSUE THREAD

**Issue by xtronaltic** [shadowsocks/shadowsocks-libev#1106]
Please answer these questions before submitting your issue. Thanks!

**What version of shadowsocks-libev are you using?**

shadowsocks-libev-2.5.5-1.el7.centos.x86_64

**What operating system are you using?**

CentOS 7 on Vultr server

**What did you do?**

Trying to run this line to install the prequirement for shadowsocks-libev:

`yum install gcc autoconf libtool automake make openssl-devel pcre-devel asciidoc xmlto zlib-devel openssl-devel libsodium-devel udns-devel libev-devel  -y`

**What did you expect to see?**

No warnings I assume

**What did you see instead?**

Installing : gtk2-2.24.28-8.el7.x86_64                                                                             115/134 
gtk-query-immodules-2.0-64: error while loading shared libraries: libEGL.so.1: cannot open shared object file: No such file or directory
warning: %post(gtk2-2.24.28-8.el7.x86_64) scriptlet failed, exit status 127
Non-fatal POSTIN scriptlet failure in rpm package gtk2-2.24.28-8.el7.x86_64

**I`m new to CentOS 7.**

**As I just typed above, I was trying to install the prequirement for shadowsocks-libev on my Vultr VPS server. When I tried to run that line, I saw that warning showing up and had no clue what happened.** 

**help?**

**Comment by madeye** [comment]
I don't think it's related to shadowsocks. My suggestion is switching to Debian/Ubuntu instead.

**Comment by xtronaltic** [comment]
**Hey my friend! Thank you for your reply!** 

I`m actully learning linux from scratch now, lol. 

I just want to use shadowsocks on my VPS, nothing else. 

I tried to learn that online but got confused a lot.

**Could you tell me what I should do next? Thank you!**

I just downloaded yum repo on Fedora Copr and put it inside /etc/yum.repos.d/. 

I installed `shadowsocks-libev` via `yum install shadowsocks-libev`

Should I do this `vi /etc/shadowsocks-libev/config.json` next?

**Comment by xtronaltic** [comment]
Btw, will that warning regarding `gtk2-2.24.28-8.el7.x86_64 115/134` be an issue when I`m trying to use shadowsocks-libev by chacha20?
