### ISSUE TITLE
feature wishlist: ss-redir script

### ISSUE THREAD

**Issue by rogers0** [shadowsocks/shadowsocks-libev#1108]
The script described in below URL should to be checked in, just as src/ss-nat.
- https://github.com/shadowsocks/shadowsocks-libev#advanced-usage

**Comment by madeye** [comment]
Actually ss-nat is just the script for ss-redir. It has many more features than the usage in README.

**Comment by rogers0** [comment]
it's better if we can merge the script in README to ss-nat,
or we can create a new script under src/ or contrib/

so still tag as wishlist. please don't close this. thanks.

**Comment by rogers0** [comment]
I created a 3rd script to based on the sample from README.
Mine is to use as Linux client, while script in README is for Linux router/gateway.

```shell
#!/bin/sh

SERVER=$(grep server /etc/shadowsocks-libev/config.json|grep -v server_port|cut -d\" -f4)
PORT=$(grep server_port /etc/shadowsocks-libev/config.json|cut -d: -f2|cut -d, -f1)
LOCAL=$(grep local_port /etc/shadowsocks-libev/config.json|cut -d: -f2|cut -d, -f1)

iptables -F > /dev/null 2>&1
iptables -t nat -F > /dev/null 2>&1

# reset iptables and exit if there's a param in cmd line
[ -n "$1" ] && exit 0

# Ignore your shadowsocks server's addresses
# It's very IMPORTANT, just be careful.
iptables -t nat -A OUTPUT -d $SERVER -j RETURN

# Ignore LANs and any other addresses you'd like to bypass the proxy
# See Wikipedia and RFC5735 for full list of reserved networks.
# See ashi009/bestroutetb for a highly optimized CHN route list.
iptables -t nat -A OUTPUT -d 0.0.0.0/8 -j RETURN
iptables -t nat -A OUTPUT -d 10.0.0.0/8 -j RETURN
iptables -t nat -A OUTPUT -d 127.0.0.0/8 -j RETURN
iptables -t nat -A OUTPUT -d 169.254.0.0/16 -j RETURN
iptables -t nat -A OUTPUT -d 172.16.0.0/12 -j RETURN
iptables -t nat -A OUTPUT -d 192.168.0.0/16 -j RETURN
iptables -t nat -A OUTPUT -d 224.0.0.0/4 -j RETURN
iptables -t nat -A OUTPUT -d 240.0.0.0/4 -j RETURN

# Anything else should be redirected to shadowsocks's local port
iptables -t nat -A OUTPUT -p tcp -j REDIRECT --to-ports $LOCAL
iptables -t nat -A OUTPUT -p udp -j REDIRECT --to-ports $LOCAL

# Start the ss-redir
ss-redir -u -c /etc/shadowsocks-libev/config.json -f /var/run/ss-redir.pid
```

**Comment by madeye** [comment]
The network environment of each user is quite different. Incorrect settings would lead to connection problems, especially on a remote server. That's why we put these command lines in documents rather than in a script.

And actually, ss-nat provides more features than this simple example.

**Comment by rogers0** [comment]
@madeye ACK your point. For example. iptables default rule is DENY, so it'll become disaster after "iptables -F" in my script.

But the script above is for Linux PC, which means mostly local.
ss-nat is for gateway, means remote for sure.

**Comment by rogers0** [comment]
Updated the script above, to handle the DNS (via UDP) issue.

**Comment by madeye** [comment]
Let's keep transparent proxy scripts as a downstream project.

Closing the issue.
