### ISSUE TITLE
編譯失敗

### ISSUE THREAD

**Issue by ky0ncheng** [shadowsocks/shadowsocks-libev#1110]
make[2]: Entering directory '/root/shadowsocks-libev/src'
  CC       ss_redir-redir.o
redir.c: In function ‘main’:
redir.c:777:11: error: unused variable ‘plugin_args’ [-Werror=unused-variable]
     char *plugin_args = NULL;
           ^
cc1: all warnings being treated as errors
Makefile:1271: recipe for target 'ss_redir-redir.o' failed
make[2]: *** [ss_redir-redir.o] Error 1
make[2]: Leaving directory '/root/shadowsocks-libev/src'
Makefile:478: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/root/shadowsocks-libev'
Makefile:387: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by madeye** [comment]
Try the latest commit.
