### ISSUE TITLE
./autogen.sh 失败

### ISSUE THREAD

**Issue by LisonFan** [shadowsocks/shadowsocks-libev#1113]
CentOS

![snipaste20170122_091845](https://cloud.githubusercontent.com/assets/9424775/22179071/d76f0698-e083-11e6-8b00-4c35a0135f72.png)

**Comment by LisonFan** [comment]
知道是什么问题了

**Comment by hosiet** [comment]
Autoconf 2.67 is released on 2010. This error means the version on your system is older than that. You should either upgrade your system or install a newer autoconf.
