### ISSUE TITLE
make && make install 错误

### ISSUE THREAD

**Issue by LisonFan** [shadowsocks/shadowsocks-libev#1118]
在包含自 encrypt.c：76 的文件中:
cache.h:32:16: 错误：ev.h：没有那个文件或目录
In file included from encrypt.c:76:
cache.h:40: 错误：expected specifier-qualifier-list before ‘ev_tstamp’
cache.h:56: 错误：expected declaration specifiers or ‘...’ before ‘ev_tstamp’
make[2]: *** [libshadowsocks_libev_la-encrypt.lo] 错误 1
make[2]: Leaving directory `/root/shadowsocks-libev/src'
make[1]: *** [all-recursive] 错误 1
make[1]: Leaving directory `/root/shadowsocks-libev'
make: *** [all] 错误 2

**Comment by fulingfan** [comment]
大兄弟，这个问题你咋解决的

**Comment by LisonFan** [comment]
@fulingfan 换 CentOS7 了。估计有可能是我手动编译安装一些库的原因

**Comment by fulingfan** [comment]
@LisonFan 好的，谢谢，我用的是centos 6，在研究研究

**Comment by teddysun** [comment]
在使用GCC时经常会遇到expected specifier-qualifier-list before sth之类的错误。specifiers是指void、char、struct Foo等词汇；qualifiers是指像const和volatile一类的关键字。一个词汇再未定义之前就使用就会出项这种错误，可以通过typedef进行定义以后再使用。

Refer: [https://www.cplusplus.me/1718.html](https://www.cplusplus.me/1718.html)
