### ISSUE TITLE
ss-manager SEGFAULT on empty command

### ISSUE THREAD

**Issue by fortuna** [shadowsocks/shadowsocks-libev#1123]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
2.4.0

### What operating system are you using?
Ubuntu 16.04.1 LTS

### What did you do?
One terminal I ran:

    ss-manager --manager-address /tmp/manager.sock

On another, I ran:

    nc -uU /tmp/manager.sock

If I send the `ping` command, I get the `stat{}` back. But if I just hit enter, I get a segmentation fault on the `ss-manager` process. I'm then forced to restart the manager. The `ss-server` keeps running fine.

The same happens if I run the server and manager with a single command:

    ss-manager --manager-address /tmp/manager.sock --executable $(which ss-server) -m aes-256-cfb -A -p 2000 -k "${password}" 

### What did you expect to see?

`ss-manager` should not crash on bogus commands. It should keep running instead.

### What did you see instead?

Segmentation Fault on `ss-manager`.

### What is your config in detail (with all sensitive info masked)?

No config. See command line above.

**Comment by madeye** [comment]
Please try 2d3a1b2

**Comment by fortuna** [comment]
Thanks for the quick fix!
When should we expect the fix to be released? Is there a release schedule for shadowsocks-libev?

**Comment by madeye** [comment]
No release schedule here. But you can expect a new release this month.

**Comment by rogers0** [comment]
@madeye Debian Stretch will freeze soon, so if you want something more stable than v2.6.2+ds-1, please release soon.

We cannot upload a "latest" version to Stretch anymore, after the freeze.
This means no new feature and only bug fix is allowed.

We also need to support Stretch version (current is 2.6.2+ds-1) for about 5 years (including LTS period).

So what's your suggestion? To stay on 2.6.2, or upload 2.6.3 on the way?

**Comment by madeye** [comment]
@rogers0 Thanks! Here it is: https://github.com/shadowsocks/shadowsocks-libev/releases/tag/v2.6.3

**Comment by rogers0** [comment]
@madeye thanks!
seems you changed a lot on autotools config. hard work (for me) starts now ..

**Comment by madeye** [comment]
@rogers0 :smile:
