### ISSUE TITLE
Can't Compile on Mac OS 10.11

### ISSUE THREAD

**Issue by xingezhang** [shadowsocks/shadowsocks-libev#1125]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
2.6.2

### What operating system are you using?
Mac OS X 10.11

### What did you do?
Compile 

### What did you expect to see?
clang: warning: argument unused during compilation: '-pthread' 

### What is your config in detail (with all sensitive info masked)?

Mac 下编译shadowsocks-libev，在make时出现以下错误：
CCLD ss-local
clang: warning: argument unused during compilation: '-pthread' 

google很久也没找到解决办法

**Comment by Windendless** [comment]
#1126

**Comment by xingezhang** [comment]
感谢，已经成功了
