### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by LisonFan** [shadowsocks/shadowsocks-libev#1127]
copying selected object files to avoid basename conflicts...
make[2]: Leaving directory `/root/shadowsocks-libev/libipset'
Making all in src
make[2]: Entering directory `/root/shadowsocks-libev/src'
  CC       libshadowsocks_libev_la-utils.lo
  CC       libshadowsocks_libev_la-jconf.lo
  CC       libshadowsocks_libev_la-json.lo
  CC       libshadowsocks_libev_la-encrypt.lo
In file included from encrypt.c:76:
cache.h:32:16: error: ev.h: No such file or directory
In file included from encrypt.c:76:
cache.h:40: error: expected specifier-qualifier-list before 'ev_tstamp'
cache.h:56: error: expected declaration specifiers or '...' before 'ev_tstamp'
make[2]: *** [libshadowsocks_libev_la-encrypt.lo] Error 1
make[2]: Leaving directory `/root/shadowsocks-libev/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/root/shadowsocks-libev'
make: *** [all] Error 2

[config.txt](https://github.com/shadowsocks/shadowsocks-libev/files/724144/config.txt)

**Comment by madeye** [comment]
`apt-get install libev-dev"

**Comment by LisonFan** [comment]
@madeye 

![snipaste20170124_091151](https://cloud.githubusercontent.com/assets/9424775/22229857/332838fa-e215-11e6-8e5e-0474aac4f84e.png)

**Comment by LisonFan** [comment]
@madeye libev-devel 安装了，还是编译错误

**Comment by LisonFan** [comment]
@madeye ev.h 这些头文件的目录在 /usr/include/libev/ 这里，不在 /usr/include/

**Comment by LisonFan** [comment]
找到解决方案了

cp /usr/include/libev/* /usr/include/
