### ISSUE TITLE
Default path in the systemd script

### ISSUE THREAD

**Issue by lcdtyph** [shadowsocks/shadowsocks-libev#1128]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
61018b622eb2ad30fcc57026844bec5ceb4cba04

### What operating system are you using?
debian 8 amd64

I've noticed that ss now has a default prefix ```/usr/local```.
But the exec path in systemd script is still /usr/bin/xxxx
[here](https://github.com/shadowsocks/shadowsocks-libev/blob/master/debian/shadowsocks-libev.service#L22)

**Comment by hosiet** [comment]
There seems no easy fix.

Systemd units are not installed by Makefile targets, thus they know nothing about PREFIX.

**Comment by rogers0** [comment]
if building to deb, it should install under /usr/bin
if deb installs to /usr/local, it should be a bug to be fixed on makefile, but NOT systemd service file.

**Comment by lcdtyph** [comment]
@hosiet @rogers0 
Thx for reply!
