### ISSUE TITLE
CentOS6 编译安装 Shadowsocks-libev + Simple-obfs 教程

### ISSUE THREAD

**Issue by LisonFan** [shadowsocks/shadowsocks-libev#1129]
https://goo.gl/P0M5wt

**Comment by muronghan** [comment]
用最新的ss-liev服务端部署于VP, OS是Ubuntu 16.04, kernel 4.9，并安装simple-obfs；客户端是LEDE 4.4.42，编译的最新的ss-libev和luci-app-ss。在三个VPS上测试，结果如下：

三个VPS中，两个是国人开的，一个是老外开的。所有客户端在luci里必须将plugin name和plugin arguments留空，ss才跑得起来，要不然running status里就是not running。

下面是奇异的事情：其中两个国人开的VPS，服务端的/etc/shadowsocks-libev/config.json里添加诸如"plugin":"obfs-server"和"plugin_opts":"obfs=http"后，服务端必须运行诸如ss-server -A -u -c /etc/shadowsocks-libev/config.json才能跑ss，否则就表现为代理的网页打不开。如果Ctrl-C打断上述运行，则原先打开的网页就打不开。而老外开的VPS则不管服务端的config.json是否添加上述设置，restart ss后都能跑起来，但是否混淆成功就不得而知了，因为正如上段所说，客户端luci是留空的。

**Comment by lifetyper** [comment]
我也是centos6，调试了一下，
发现config.json中的plugin选项似乎应该用绝对路径
(/etc/init.d/shadowsock-libev里的SS-Server就是用的绝对路径)，否则会提示找不到obfs-server这个可执行文件，我改成绝对路径之后就可以了。

"plugin":"/usr/local/bin/obfs-server"

这个地址按你实际情况修改，默认的make install应该是这样了。
