### ISSUE TITLE
怎样设置才能实现ipv6优先

### ISSUE THREAD

**Issue by mkoplm777** [shadowsocks/shadowsocks-libev#113]
服务器是双栈，访问ipv6 only的站点一切正常，访问双栈的站点则ipv4优先。

**Comment by tufu9441** [comment]
Have you solved this problem? I think I can understand your meaning. My VPS (Digital Ocean) already has an ipv6 address and when I test on http://ipv6-test.com it shows that ipv6 connectivity is supported. Also, when I type "dig scholar.google.com" in ssh it will output: 

;; Query time: 26 msec
;; SERVER: 2001:4860:4860::8888#53(2001:4860:4860::8888) 

However, when I use the shadowsocks client to visit http://scholar.google.com, it will resolve the ipv4 address in priority, because I know the ipv4 address of my VPS (Digital Ocean SFO) has been forbidden by google scholar but ipv6 is available, so I cannot visit the page normally now. 

I tried to install shadowsocks-python on my VPS, then I didn't come across this problem, the shadowsocks on server will use ipv6 in priority the same as the VPS itself, and I could visit http://scholar.google.com through ipv6 address normally. 

So I think it may be specific issue on shadowsocks-libev, and I also want to let the shadowsocks on server use ipv6 address in priority.

**Comment by WhiteWorld** [comment]
I hava the same problems with @tufu9441

**Comment by singular78** [comment]
the same problems with @tufu9441

**Comment by Lencerf** [comment]
The same problems with @tufu9441

**Comment by billryan** [comment]
@tufu9441 Since Google Scholar blocked DO(IPv4), you can roll your own DNS server to resolve `scholar.google.*` with IPv6. Hit [Resolve Google Scholar with IPv6 only](https://github.com/sjtug/kxsw/wiki/Google-Scholar) for more info.

**Comment by Paull** [comment]
Same problem here. 
target url: http://v4v6.ipv6-test.com/json/defaultproto.php

1. Visit directly with curl on server I got

>  ({"address":"2402:9e80:0:1000::1:12c1","protocol":"6"})

2. client browser using a SOCKS5 proxy created by ssh -D, got 

> ({"address":"2402:9e80:0:1000::1:12c1","protocol":"6"})

3. client browser using a SOCKS5 proxy created by ss-local, got 

> ({"address":"45.124.66.123","protocol":"4"})

So I think ss-local or ss-server prefer IPv4. Any advise to make ss prefer IPv6?

**Comment by Paull** [comment]
Sorry, I found the IPv6 priority solution is made in 72ee77e.
Just add a param -6 to ss-server.

But the IPv6 to IPv4 fallback isn't suppoted after that.
try target url: http://fallback-v6.ipv6-test.com/json/proto.php

- Visit directly with curl on server I got

> ({"address":"45.124.66.188","protocol":"4"})

- client browser using a SOCKS5 proxy created by ssh -D, got

> ({"address":"45.124.66.188","protocol":"4"})

- client browser using a SOCKS5 proxy created by ss-local, got

> ERR_EMPTY_RESPONSE

**Comment by totmann** [comment]
Set "dns_ipv6": true solved the above problem.

**Comment by lihk11** [comment]
@totmann THX! Your method solved my problem!

**Comment by zeanzhou** [comment]
Really strange...
I'm using ` ssserver -c config.json --prefer-ipv6 -d start` to run my ssserver on my VPS.

- client browser using a shadowsocks as a proxy:

Test url: http://v4v6.ipv6-test.com/json/defaultproto.php
> ({"address":"2001:19f0:6001:xxxx:xxxx:xx:xxxx:xxxx","protocol":"6"})

Test url: http://fallback-v6.ipv6-test.com/json/proto.php
> 500 Internal Privoxy Error

But the result in google search when I search for "ip" shows that my IP is ipv6. And of course, I am still blocked by Google Scholar...

**Comment by ferstar** [comment]
@zeanzhou I have solved this problem by these steps:
> make sure your vps has right ipv6 access

1. vi /etc/default/shadowsocks-libev
```
...
# add '-6' to resovle hostname to IPv6 address first
DAEMON_ARGS="-u -6" 
...
```
2. vi /etc/shadowsocks-libev/config.json
```
...
"dns_ipv6": true
...
```
3. vi /etc/hosts
```
## Scholar
## type 'host google.com' to get the correct ipv6 address
## for me it's '2607:f8b0:4005:804::200e'
2607:f8b0:4005:804::200e scholar.google.cn
2607:f8b0:4005:804::200e scholar.google.com.hk
2607:f8b0:4005:804::200e scholar.google.com
2607:f8b0:4005:804::200e scholar.l.google.com
```
enjoy!

**Comment by moerfutin** [comment]
@ferstar  第一步，那个目录没有那个文件咋办？ 用的秋水逸冰一键脚本，

**Comment by ferstar** [comment]
@moerfutin 

https://github.com/teddysun/shadowsocks_install/blob/master/shadowsocks-libev#L74
https://github.com/teddysun/shadowsocks_install/blob/master/shadowsocks-libev-debian#L73

`vi /etc/init.d/shadowsocks-libev`

add '-6' to resovle hostname to IPv6 address first

**Comment by tortoo** [comment]
@ferstar 您好，按您的设置没有成功，想再请教一下
首先问下你们讨论的前提是vps本身自带ipv6吗？我是virmach的vps，自身没有提供ipv6，
我是按[这个地址](https://glorystar.me/archives/Access-to-Google-tips-needs-to-validate-solutions.html)的办法，申请了ipv6 tunnel。一直到ping6 ipv6.google.com这步，都成功了，ipv6应该生效了。这篇文末说ss-libev版无法通过hosts强制访问谷歌，它一直会通过DNS解析，但您给的办法应该做到了hosts访问谷歌吧？还是说，您的办法只适用vps自身有提供ipv6，这种ipv6 tunnel的情况不适用，只能自建DNS？

**Comment by blueveryday** [comment]
Yes, I have the same problem as yours.
My ssr server have two address , for IPv4 and IPv6 .
Client use the IPv4 to access internet by ssr.
but I want to use the IPv6 of SSR to access some website.
Because some website have limited for client's IP.

**Comment by ferstar** [comment]
> @ferstar 您好，按您的设置没有成功，想再请教一下
> 首先问下你们讨论的前提是vps本身自带ipv6吗？我是virmach的vps，自身没有提供ipv6，
> 我是按[这个地址](https://glorystar.me/archives/Access-to-Google-tips-needs-to-validate-solutions.html)的办法，申请了ipv6 tunnel。一直到ping6 ipv6.google.com这步，都成功了，ipv6应该生效了。这篇文末说ss-libev版无法通过hosts强制访问谷歌，它一直会通过DNS解析，但您给的办法应该做到了hosts访问谷歌吧？还是说，您的办法只适用vps自身有提供ipv6，这种ipv6 tunnel的情况不适用，只能自建DNS？

我是vps自带ipv6地址，你的这种情况我不清楚，而且现在我也没再用ssr了

**Comment by 0neday** [comment]
https://github.com/shadowsocks/shadowsocks-libev/issues/519#issuecomment-778773859
lastest 3.3.5 ss-redir is not work for ipv6 on v4

**Comment by profection** [comment]
> @zeanzhou I have solved this problem by these steps:
> 
> > make sure your vps has right ipv6 access
> > OS: Ubuntu 16.04.3 LTS (GNU/Linux 4.12.2-041202-generic x86_64)
> > ss version: shadowsocks-libev 3.1.3
> 
> 1. vi /etc/default/shadowsocks-libev
> 
> ```
> ...
> # add '-6' to resovle hostname to IPv6 address first
> DAEMON_ARGS="-u -6" 
> ...
> ```
> 
> 2. vi /etc/shadowsocks-libev/config.json
> 
> ```
> ...
> "dns_ipv6": true
> ...
> ```
> 
> 3. vi /etc/hosts
> 
> ```
> ...
> ## Scholar
> ## type 'host google.com' to get the correct ipv6 address
> ## for me it's '2607:f8b0:4005:804::200e'
> 2607:f8b0:4005:804::200e scholar.google.cn
> 2607:f8b0:4005:804::200e scholar.google.com.hk
> 2607:f8b0:4005:804::200e scholar.google.com
> 2607:f8b0:4005:804::200e scholar.l.google.com
> ```
> 
> 4. `systemctl restart shadowsocks-libev`
> 
> enjoy!

用你的方法解决了问题，太感谢了
