### ISSUE TITLE
Build failed under Debian Jessie

### ISSUE THREAD

**Issue by Amankwah** [shadowsocks/shadowsocks-libev#1130]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
d783aab

### What operating system are you using?
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.7 (jessie)
Release:	8.7
Codename:	jessie

### What did you do?
$ ./autogen
$ ./configure --disable-documentation
$ make

Then failed

### What did you expect to see?
build it success

### What did you see instead?
encrypt.c: In function 'crypto_stream_xor_ic':
encrypt.c:282:9: error: implicit declaration of function 'crypto_stream_chacha20_ietf_xor_ic' [-Werror=implicit-function-declaration]
         return crypto_stream_chacha20_ietf_xor_ic(c, m, mlen, n, (uint32_t)ic, k);
         ^
cc1: all warnings being treated as errors
Makefile:827: recipe for target 'libshadowsocks_libev_la-encrypt.lo' failed
make[2]: *** [libshadowsocks_libev_la-encrypt.lo] Error 1

### What is your config in detail (with all sensitive info masked)?
nothing special

### Possible reason
It seemed that shadowsocks-libev swithed to use system libsodium, which version is 1.0.0-1 in Debian Jessie. but the function crypto_stream_chacha20_ietf_xor_ic was introduce to libsodium since 1.0.4?

**Comment by rogers0** [comment]
@Amankwah https://github.com/shadowsocks/shadowsocks-libev/issues/1093#issuecomment-273528262

**Comment by Amankwah** [comment]
@rogers0 Greate thanks, it fixed.

**Comment by rogers0** [comment]
@Amankwah thanks for feedback.
install from apt repo if possible. actually there's not much benefit to build from source every time.
