### ISSUE TITLE
无法编译

### ISSUE THREAD

**Issue by Sherlock-Holo** [shadowsocks/shadowsocks-libev#1131]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
2.6.3

### What operating system are you using?
fedora 24

### What did you do?
编译

### What did you see instead?
运行` ./autogen.sh `时

> configure.ac:258: warning: AC_LIB_PREPARE_PREFIX is m4_require'd but not m4_defun'd
m4/lib-link.m4:57: AC_LIB_HAVE_LINKFLAGS is expanded from...
/usr/share/aclocal/pkg.m4:139: PKG_CHECK_MODULES is expanded from...
configure.ac:258: the top level
configure.ac:258: warning: AC_LIB_PROG_LD is m4_require'd but not m4_defun'd
m4/lib-link.m4:125: AC_LIB_RPATH is expanded from...
m4/lib-link.m4:57: AC_LIB_HAVE_LINKFLAGS is expanded from...
/usr/share/aclocal/pkg.m4:139: PKG_CHECK_MODULES is expanded from...
configure.ac:258: the top level
configure.ac:258: warning: AC_LIB_PREPARE_MULTILIB is m4_require'd but not m4_defun'd
m4/lib-link.m4:181: AC_LIB_LINKFLAGS_BODY is expanded from...
m4/lib-link.m4:57: AC_LIB_HAVE_LINKFLAGS is expanded from...
/usr/share/aclocal/pkg.m4:139: PKG_CHECK_MODULES is expanded from...
configure.ac:258: the top level
configure.ac:269: warning: AC_LIB_PREPARE_PREFIX is m4_require'd but not m4_defun'd
m4/lib-link.m4:57: AC_LIB_HAVE_LINKFLAGS is expanded from...
/usr/share/aclocal/pkg.m4:139: PKG_CHECK_MODULES is expanded from...
configure.ac:269: the top level
configure.ac:269: warning: AC_LIB_PREPARE_MULTILIB is m4_require'd but not m4_defun'd
m4/lib-link.m4:181: AC_LIB_LINKFLAGS_BODY is expanded from...
m4/lib-link.m4:57: AC_LIB_HAVE_LINKFLAGS is expanded from...
/usr/share/aclocal/pkg.m4:139: PKG_CHECK_MODULES is expanded from...
configure.ac:269: the top level
configure.ac:258: warning: AC_LIB_PREPARE_PREFIX is m4_require'd but not m4_defun'd
m4/lib-link.m4:57: AC_LIB_HAVE_LINKFLAGS is expanded from...
/usr/share/aclocal/pkg.m4:139: PKG_CHECK_MODULES is expanded from...
configure.ac:258: the top level
configure.ac:258: warning: AC_LIB_PROG_LD is m4_require'd but not m4_defun'd
m4/lib-link.m4:125: AC_LIB_RPATH is expanded from...
m4/lib-link.m4:57: AC_LIB_HAVE_LINKFLAGS is expanded from...
/usr/share/aclocal/pkg.m4:139: PKG_CHECK_MODULES is expanded from...
configure.ac:258: the top level
configure.ac:258: warning: AC_LIB_PREPARE_MULTILIB is m4_require'd but not m4_defun'd
m4/lib-link.m4:181: AC_LIB_LINKFLAGS_BODY is expanded from...
m4/lib-link.m4:57: AC_LIB_HAVE_LINKFLAGS is expanded from...
/usr/share/aclocal/pkg.m4:139: PKG_CHECK_MODULES is expanded from...
configure.ac:258: the top level
configure.ac:269: warning: AC_LIB_PREPARE_PREFIX is m4_require'd but not m4_defun'd
m4/lib-link.m4:57: AC_LIB_HAVE_LINKFLAGS is expanded from...
/usr/share/aclocal/pkg.m4:139: PKG_CHECK_MODULES is expanded from...
configure.ac:269: the top level
configure.ac:269: warning: AC_LIB_PREPARE_MULTILIB is m4_require'd but not m4_defun'd
m4/lib-link.m4:181: AC_LIB_LINKFLAGS_BODY is expanded from...
m4/lib-link.m4:57: AC_LIB_HAVE_LINKFLAGS is expanded from...
/usr/share/aclocal/pkg.m4:139: PKG_CHECK_MODULES is expanded from...
configure.ac:269: the top level
configure.ac:258: warning: AC_LIB_PREPARE_PREFIX is m4_require'd but not m4_defun'd
m4/lib-link.m4:57: AC_LIB_HAVE_LINKFLAGS is expanded from...
aclocal.m4:161: PKG_CHECK_MODULES is expanded from...
configure.ac:258: the top level
configure.ac:258: warning: AC_LIB_PROG_LD is m4_require'd but not m4_defun'd
m4/lib-link.m4:125: AC_LIB_RPATH is expanded from...
m4/lib-link.m4:57: AC_LIB_HAVE_LINKFLAGS is expanded from...
aclocal.m4:161: PKG_CHECK_MODULES is expanded from...
configure.ac:258: the top level
configure.ac:258: warning: AC_LIB_PREPARE_MULTILIB is m4_require'd but not m4_defun'd
m4/lib-link.m4:181: AC_LIB_LINKFLAGS_BODY is expanded from...
m4/lib-link.m4:57: AC_LIB_HAVE_LINKFLAGS is expanded from...
aclocal.m4:161: PKG_CHECK_MODULES is expanded from...
configure.ac:258: the top level
configure.ac:269: warning: AC_LIB_PREPARE_PREFIX is m4_require'd but not m4_defun'd
m4/lib-link.m4:57: AC_LIB_HAVE_LINKFLAGS is expanded from...
aclocal.m4:161: PKG_CHECK_MODULES is expanded from...
configure.ac:269: the top level
configure.ac:269: warning: AC_LIB_PREPARE_MULTILIB is m4_require'd but not m4_defun'd
m4/lib-link.m4:181: AC_LIB_LINKFLAGS_BODY is expanded from...
m4/lib-link.m4:57: AC_LIB_HAVE_LINKFLAGS is expanded from...
aclocal.m4:161: PKG_CHECK_MODULES is expanded from...
configure.ac:269: the top level
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'auto'.
libtoolize: copying file 'auto/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
configure.ac:258: warning: AC_LIB_PREPARE_PREFIX is m4_require'd but not m4_defun'd
m4/lib-link.m4:57: AC_LIB_HAVE_LINKFLAGS is expanded from...
/usr/share/aclocal/pkg.m4:139: PKG_CHECK_MODULES is expanded from...
configure.ac:258: the top level
configure.ac:258: warning: AC_LIB_PROG_LD is m4_require'd but not m4_defun'd
m4/lib-link.m4:125: AC_LIB_RPATH is expanded from...
m4/lib-link.m4:57: AC_LIB_HAVE_LINKFLAGS is expanded from...
/usr/share/aclocal/pkg.m4:139: PKG_CHECK_MODULES is expanded from...
configure.ac:258: the top level
configure.ac:258: warning: AC_LIB_PREPARE_MULTILIB is m4_require'd but not m4_defun'd
m4/lib-link.m4:181: AC_LIB_LINKFLAGS_BODY is expanded from...
m4/lib-link.m4:57: AC_LIB_HAVE_LINKFLAGS is expanded from...
/usr/share/aclocal/pkg.m4:139: PKG_CHECK_MODULES is expanded from...
configure.ac:258: the top level
configure.ac:269: warning: AC_LIB_PREPARE_PREFIX is m4_require'd but not m4_defun'd
m4/lib-link.m4:57: AC_LIB_HAVE_LINKFLAGS is expanded from...
/usr/share/aclocal/pkg.m4:139: PKG_CHECK_MODULES is expanded from...
configure.ac:269: the top level
configure.ac:269: warning: AC_LIB_PREPARE_MULTILIB is m4_require'd but not m4_defun'd
m4/lib-link.m4:181: AC_LIB_LINKFLAGS_BODY is expanded from...
m4/lib-link.m4:57: AC_LIB_HAVE_LINKFLAGS is expanded from...
/usr/share/aclocal/pkg.m4:139: PKG_CHECK_MODULES is expanded from...
configure.ac:269: the top level
configure.ac:258: warning: AC_LIB_PREPARE_PREFIX is m4_require'd but not m4_defun'd
m4/lib-link.m4:57: AC_LIB_HAVE_LINKFLAGS is expanded from...
/usr/share/aclocal/pkg.m4:139: PKG_CHECK_MODULES is expanded from...
configure.ac:258: the top level
configure.ac:258: warning: AC_LIB_PROG_LD is m4_require'd but not m4_defun'd
m4/lib-link.m4:125: AC_LIB_RPATH is expanded from...
m4/lib-link.m4:57: AC_LIB_HAVE_LINKFLAGS is expanded from...
/usr/share/aclocal/pkg.m4:139: PKG_CHECK_MODULES is expanded from...
configure.ac:258: the top level
configure.ac:258: warning: AC_LIB_PREPARE_MULTILIB is m4_require'd but not m4_defun'd
m4/lib-link.m4:181: AC_LIB_LINKFLAGS_BODY is expanded from...
m4/lib-link.m4:57: AC_LIB_HAVE_LINKFLAGS is expanded from...
/usr/share/aclocal/pkg.m4:139: PKG_CHECK_MODULES is expanded from...
configure.ac:258: the top level
configure.ac:269: warning: AC_LIB_PREPARE_PREFIX is m4_require'd but not m4_defun'd
m4/lib-link.m4:57: AC_LIB_HAVE_LINKFLAGS is expanded from...
/usr/share/aclocal/pkg.m4:139: PKG_CHECK_MODULES is expanded from...
configure.ac:269: the top level
configure.ac:269: warning: AC_LIB_PREPARE_MULTILIB is m4_require'd but not m4_defun'd
m4/lib-link.m4:181: AC_LIB_LINKFLAGS_BODY is expanded from...
m4/lib-link.m4:57: AC_LIB_HAVE_LINKFLAGS is expanded from...
/usr/share/aclocal/pkg.m4:139: PKG_CHECK_MODULES is expanded from...
configure.ac:269: the top level
configure.ac:258: warning: AC_LIB_PREPARE_PREFIX is m4_require'd but not m4_defun'd
m4/lib-link.m4:57: AC_LIB_HAVE_LINKFLAGS is expanded from...
aclocal.m4:161: PKG_CHECK_MODULES is expanded from...
configure.ac:258: the top level
configure.ac:258: warning: AC_LIB_PROG_LD is m4_require'd but not m4_defun'd
m4/lib-link.m4:125: AC_LIB_RPATH is expanded from...
m4/lib-link.m4:57: AC_LIB_HAVE_LINKFLAGS is expanded from...
aclocal.m4:161: PKG_CHECK_MODULES is expanded from...
configure.ac:258: the top level
configure.ac:258: warning: AC_LIB_PREPARE_MULTILIB is m4_require'd but not m4_defun'd
m4/lib-link.m4:181: AC_LIB_LINKFLAGS_BODY is expanded from...
m4/lib-link.m4:57: AC_LIB_HAVE_LINKFLAGS is expanded from...
aclocal.m4:161: PKG_CHECK_MODULES is expanded from...
configure.ac:258: the top level
configure.ac:269: warning: AC_LIB_PREPARE_PREFIX is m4_require'd but not m4_defun'd
m4/lib-link.m4:57: AC_LIB_HAVE_LINKFLAGS is expanded from...
aclocal.m4:161: PKG_CHECK_MODULES is expanded from...
configure.ac:269: the top level
configure.ac:269: warning: AC_LIB_PREPARE_MULTILIB is m4_require'd but not m4_defun'd
m4/lib-link.m4:181: AC_LIB_LINKFLAGS_BODY is expanded from...
m4/lib-link.m4:57: AC_LIB_HAVE_LINKFLAGS is expanded from...
aclocal.m4:161: PKG_CHECK_MODULES is expanded from...
configure.ac:269: the top level
configure:16721: error: possibly undefined macro: AC_LIB_PREPARE_PREFIX
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure:16722: error: possibly undefined macro: AC_LIB_PROG_LD
configure:16757: error: possibly undefined macro: AC_LIB_PREPARE_MULTILIB
configure:16833: error: possibly undefined macro: AC_LIB_WITH_FINAL_PREFIX
autoreconf: /usr/bin/autoconf failed with exit status: 1

**Comment by Sherlock-Holo** [comment]
arch没有这方面的问题，fedora上依赖装齐了，而且是重新clone下来的，有做submodule

**Comment by baggiogogo** [comment]
install gettext
树莓派2安装之后倒是编译成功了，但另一台debian8.2报错，还在摸索中。
configure.ac:26: error: possibly undefined macro: AC_MSG_ERROR
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:259: error: possibly undefined macro: AC_LIB_HAVE_LINKFLAGS
autoreconf: /usr/bin/autoconf failed with exit status: 1

**Comment by 3xpert** [comment]
On cento os 6x-86
`yum groupinstall "Development Tools"`

**Comment by enihcam** [comment]
apt-get install --no-install-recommends pkg-config gnulib

**Comment by Sherlock-Holo** [comment]
@3xpert 
on Fedora 24, the "Development Tools" can't help me.

**Comment by 3xpert** [comment]
@Sherlock-Holo Search key word "**build-essential**" for fedora may help.

**Comment by Sherlock-Holo** [comment]
and search build-essential
there is not build-essential

3xpert <notifications@github.com>于2017年1月25日周三 12:10写道：

**Comment by Sherlock-Holo** [comment]
dnf search build-essential

**Comment by 3xpert** [comment]
Sure, the package of "build-essential" is not for fadora. I mean that you can google search the key word with "build-essential fadora" may find the solution.

**Comment by Sherlock-Holo** [comment]
OK I will try this

3xpert <notifications@github.com>于2017年1月25日周三 15:11写道：

**Comment by xingezhang** [comment]
Maybe you need install gettext and gettext-tools

**Comment by Sherlock-Holo** [comment]
maybe, but now it is installed, it is a good idea to update the README

suse-free <notifications@github.com>于2017年1月26日周四 03:49写道：

**Comment by madeye** [comment]
Try the latest commit

**Comment by Sherlock-Holo** [comment]
` yum groupinstall "Development Tools" "Development Libraries" `
I use this but I clone the least source, so I don't know which fix the problem

**Comment by viRikaRe** [comment]
`yum groupinstall "Development Tools"` shall solve the problem (Scientific Linux 7.3), but only for [Source code (tar.gz)](https://github.com/shadowsocks/shadowsocks-libev/archive/v2.6.3.tar.gz) (./autogen.sh).

[shadowsocks-libev-2.6.3.tar.gz](https://github.com/shadowsocks/shadowsocks-libev/releases/download/v2.6.3/shadowsocks-libev-2.6.3.tar.gz) reported error when `make` (./configure)
`*** No rule to make target `ss-nat', needed by `all-am'.  Stop.`

Anyway, this wouldn't be an issue as I'll just build with autogen.sh .
