### ISSUE TITLE
mac/alpine dockerfile not building [proposing fix]

### ISSUE THREAD

**Issue by ghost** [shadowsocks/shadowsocks-libev#1132]
### What version of shadowsocks-libev are you using?
v2.6.3

### What operating system are you using?
docker/alpine

The dockerfile provided [here](https://github.com/shadowsocks/shadowsocks-libev/blob/master/docker/alpine/Dockerfile) does not work since `https://github.com/shadowsocks/shadowsocks-libev/archive/v2.6.3.tar.gz` does not have the `configure` bash script. Using the `configure` bash script from `https://github.com/shadowsocks/shadowsocks-libev/releases/download/v2.6.3/shadowsocks-libev-2.6.3.tar.gz` leads to error:

    make[1]: *** No rule to make target 'ss-nat', needed by 'all-am'.  Stop.
    make: *** [Makefile:493: install-recursive] Error 1

running autoconf after adding the dependencies: `libev-dev`, `udns-dev`, `libsodium-dev`, `gettext`, `automake`, `zlib` still leads to error:

```
configure: error: possibly undefined macro: AC_LIB_PREPARE_PREFIX
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.

configure: error: possibly undefined macro: AC_LIB_PROG_LD
configure: error: possibly undefined macro: AC_LIB_PREPARE_MULTILIB
configure: error: possibly undefined macro: AC_LIB_WITH_FINAL_PREFIX
autoreconf: /usr/bin/autoconf failed with exit status: 1
```

sample Dockerfile: [here](https://gist.github.com/celaena-sardothien/a8eb166436e02d9a508148820fa66e4e)

**Comment by enihcam** [comment]
apt-get install --no-install-recommends pkg-config gnulib

**Comment by celaena-sardothien** [comment]
@enihcam  thanks, but still does work with alpine docker container, with previous version `ARG SS_VER=2.6.2` the file works fine.

**Comment by celaena-sardothien** [comment]
on mac os, running `autoconf` with  libev,udns and autoconf installed also return the same error:


==> autoconf
configure.ac:12: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:15: error: possibly undefined macro: AM_MAINTAINER_MODE
configure.ac:16: error: possibly undefined macro: AM_DEP_TRACK
configure.ac:19: error: possibly undefined macro: AC_DISABLE_STATIC
configure.ac:20: error: possibly undefined macro: AC_DISABLE_SHARED
configure.ac:26: error: possibly undefined macro: AC_MSG_ERROR
configure.ac:39: error: possibly undefined macro: AM_CONDITIONAL
configure.ac:60: error: possibly undefined macro: AM_COND_IF
configure.ac:61: error: possibly undefined macro: AC_PATH_PROG
configure.ac:67: error: possibly undefined macro: AC_PROG_SED
configure.ac:72: error: possibly undefined macro: AM_PROG_CC_C_O
configure.ac:75: error: possibly undefined macro: AC_PROG_LIBTOOL
configure.ac:259: error: possibly undefined macro: AC_LIB_HAVE_LINKFLAGS
configure.ac:281: error: possibly undefined macro: AC_CONFIG_FILES

**Comment by celaena-sardothien** [comment]
found fix for macos build: additionally install `automake` and `mbedtls` through homebrew and then `./configure --with-crypto-library=mbedtls` since recent osx deprecated openssl. may need to  `export XML_CATALOG_FILES=/usr/local/etc/xml/catalog` to build the manpage.

**Comment by celaena-sardothien** [comment]
for docker, `git clone --recursive https://github.com/shadowsocks/shadowsocks-libev.git` instead of downloading the .tar.gz file works for me with `./autogen`

**Comment by xingezhang** [comment]
I have same error when I install 2.6.3
after I install gettext and brew link gettext --force 
Compile succeed.
