### ISSUE TITLE
Customize block_list parameters

### ISSUE THREAD

**Issue by renyidong** [shadowsocks/shadowsocks-libev#1134]
This issue is for tracking only and is not a bug report. 

I'm planning to add two command line parameters for customizing fail count and ban time for block_list. 
Although shorter ban time and more fail counts can undermine security, users should have rights to risk that in exchange for convenience. Currently, users can workaround the block list with acl. However such workaround is not enough for a shared environment. An all_proxy acl to completely disable block list doesn't sounds quite good either.

I'm planning to add two long options:
--jail-tries  number of failed handshake before being jailed
--jail-time  interval for fail count to be cleared

There will be two more variable in acl.c to store these values. They will be initialized from sever.c 

I wonder if this patch is welcome. After all, we can put a short wiki to instruct shared server admin to change these setting on compile.

If everything goes well, I will start working this weekend.  Please remind me if there is no more updates by the following Monday (Feb 6)

 All suggestions and opinions are welcome.

**Comment by madeye** [comment]
I'm OK with this change. My suggestion is to choose another option name, `jail` looks quite confusing here.

**Comment by rogers0** [comment]
@renyidong if I remember correctly, it's usually called fail2ban

**Comment by renyidong** [comment]
@rogers0 You are right.
@madeye Should we close this issue? as there are fail2ban rules all around, and shared server admins should have sufficient knowledge to deploy them.
