### ISSUE TITLE
Failed installation Ubuntu 16.04 from repository

### ISSUE THREAD

**Issue by asmadeus08** [shadowsocks/shadowsocks-libev#1135]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
2.6.1

### What operating system are you using?
Ubuntu 16.04

### What did you do?
Installing ss-libev from repository

### What did you expect to see?
Successful installation 

### What did you see instead?
After start this command what i see is that:
dh_install: shadowsocks-libev missing files: usr/bin/
dh_install: shadowsocks-libev missing files: usr/share/man/
dh_install: libshadowsocks-libev-dev missing files: usr/include/
dh_install: libshadowsocks-libev-dev missing files: usr/lib/*/libshadowsocks-lib          ev.so
dh_install: libshadowsocks-libev-dev missing files: usr/lib/*/pkgconfig/
dh_install: libshadowsocks-libev2 missing files: usr/lib/*/libshadowsocks-libev.          so.*
dh_install: missing files, aborting
debian/rules:28: recipe for target 'binary' failed
make: *** [binary] Error 2
dpkg-buildpackage: error: debian/rules binary gave error exit status 2
root@vps-116:~/shadowsocks-libev#
All libraries and modules updated

### What is your config in detail (with all sensitive info masked)?
Default config.json

**Comment by rogers0** [comment]
Please refer to the comment I made in another thread:
- https://github.com/shadowsocks/shadowsocks-libev/issues/1095#issuecomment-274445199

**Comment by asmadeus08** [comment]
Thta's what i'm receiving 

root@vps-116:~# gbp clone --pristine-tar https://anonscm.debian.org/git/collab-maint/shadowsocks-libev.git
The program 'gbp' is currently not installed. You can install it by typing:
apt install git-buildpackage
root@vps-116:~# apt install git-buildpackage
E: Malformed entry 1 in list file /etc/apt/sources.list.d/jessie-backports.list (Component)
E: The list of sources could not be read.

Seems like wrong ubuntu package. I dont understand at all what to do. And i dont need to install fresh ss-libev cause i'm already have this. I need installing update version under the old one.

**Comment by rogers0** [comment]
@asmadeus08 you're not using debian jessie, so should not do with jessie part

**Comment by asmadeus08** [comment]
@rogers0 yes I know that but what wrong with original source installing? Why it's saying that i missed some folder if i'm already have installed ss-libev 2.61? And how to update that over the old version properly?

**Comment by asmadeus08** [comment]
Seems like i got what to do. First one need to stop ss-libev and rename it with any other name like ss-libev1 (only if you are already have it).

Then need to do next:
sudo apt-get install --no-install-recommends autoconf libtool asciidoc zlib1g-dev libssl-dev libpcre3\
libpcre3-dev build-essential libpcre3 asciidoc libpcre3-dev zlib1g-dev libssl-dev automake libudns-dev \
libev-dev xmlto -y

sudo apt-get install automake
git clone https://github.com/shadowsocks/shadowsocks-libev.git
cd shadowsocks-libev
git reset --hard origin/master
git pull
git submodule init && git submodule update
sudo apt-get install --no-install-recommends build-essential autoconf libtool libssl-dev \
gawk debhelper dh-systemd init-system-helpers pkg-config asciidoc xmlto apg libpcre3-dev zlib1g-dev\
libev-dev libudns-dev libsodium-dev
./autogen.sh && dpkg-buildpackage -b -us -uc -i

That's all. !! Dont forget to uninstall renamed folder ss-libev1 from server !!

systemctl restart shadowsocks-libev.service
systemctl status shadowsocks-libev.service

Working perfect!

**Comment by rogers0** [comment]
@asmadeus08 I don't think it's required to touch the service file.

**Comment by asmadeus08** [comment]
Yes it's just optional for those who wanna see if service working or not :)
