### ISSUE TITLE
Compile for openwrt (LEDE), building error: Couldn't find libudns 

### ISSUE THREAD

**Issue by hqvv** [shadowsocks/shadowsocks-libev#1137]
### What version of shadowsocks-libev are you using?
Commit d714d1f , Jan 25

### What operating system are you using?
Ubuntu 16.04

### What did you do?
Hi,
I 'd like to compile the latest shadowsocks-libev( 2.6.3 commit d714d1f  ) on LEDE SDK.
libev and libsodium are available on LDED sdk, but not libudns.
Please help on this, how can I port libudns to lede (openwrt) ?
Thanks
HQ
```
checking for malloc... yes
checking for memset... (cached) yes
checking for socket... yes
checking udns.h usability... no
checking udns.h presence... no
checking for udns.h... no
configure: error: Couldn't find libudns. Try installing libudns-dev or udns-devel.
Makefile:85: recipe for target '/home/hqo/source/build_dir/target-mips_24kc_musl-1.1.16/shadowsocks-libev/openssl/shadowsocks-libev-2017-01-25/.configured_yyyyyyy' failed
```

**Comment by haodong** [comment]
[`libudns`](http://www.corpit.ru/mjt/udns.html) now is a required package for compiling.

**Comment by madeye** [comment]
Try this: https://github.com/groleo/openwrt-packages/tree/master/udns
