### ISSUE TITLE
UDP forwarding does not work

### ISSUE THREAD

**Issue by bsdhsr** [shadowsocks/shadowsocks-libev#114]
shadowsocks-libev 1.4.6 running on Debian wheezy.

TCP works OK.

Use case is connecting to a OpenVPN server (with proto udp) using the socks-proxy option, through shadowsocks.

[ovpn@freebsd] -----[socks5]----> [ss-local@debian] ----[internet]-----> [ss-server@debian] ----> [dst ovpn]

NOTE!!!: One unusual (I guess) aspect of this setup is that shadowsocks ss-local is not running locally on the machine that I'm running OpenVPN from; this is simply due to the shadowsocks-libev FreeBSD port segfaulting as soon as I throw any UDP traffic it's way (the port is older at 1.4.0, perhaps it's a bug from that version)

openvpn stdout reads (ips redacted):
Attempting to establish TCP connection with [AF_INET](ss-local):10080 [nonblock]
TCP connection established with [AF_INET]ss-local:10080
UDPv4 link local: [undef]
UDPv4 link remote: [AF_INET]ovpn-server:ovpn-port

Meanwhile, at ss-local, I see:
"INFO: [udp] assc request accepted"
"INFO: [udp] server receive a packet"
"INFO: [udp] cache missed: ovpn-server:ovpn-port <-> freebsd-ip:$someport

At the same time, I am running tcpdump, and see no attempts whatsoever to contact the remote ss-server at all.

Therefore, the forwarding doesn't work.

This seems to be the same issue as #105.

Any ideas?

**Comment by ovizii** [comment]
Just a quick follow-up:

Say I am using shadowsocks on my mobile phone and enable UDP forwarding while my shadowsocks-libev is installed on my NAS functioning as my proxy server, which ports would I need to enable on my firewall for UDP forwarding to work?

**Comment by Kein** [comment]
Ah yes, immortal classic - an issue from a decade ago that is relevant to my issue but has no resolution.

**Comment by Demigod-Moui** [comment]
> Ah yes, immortal classic - an issue from a decade ago that is relevant to my issue but has no resolution.

I encountered the same problem, one month later

**Comment by iblopez93** [comment]
Greetings, everyone. I have a corporate proxy in my LAN network. So, how i send all traffic of ss to my LAN proxy? I attempted this but It wasn't possible
