### ISSUE TITLE
Use other nameserver

### ISSUE THREAD

**Issue by xingezhang** [shadowsocks/shadowsocks-libev#1140]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
2.6.3

### What operating system are you using?
openSUSE

### What did you do?
use other nameserver 

### What is your config in detail (with all sensitive info masked)?
更新到2.6.3后，发现新增了一行信息：
using nameserver: 8.8.8.8

请问这个是否可以自定义？如果可以，如何配置config.json？谢谢

**Comment by lcdtyph** [comment]
```
{
    "nameserver": "xxx.xxx.xxx.xxx"
}
```

**Comment by xingezhang** [comment]
谢谢
