### ISSUE TITLE
trouble shooting help: "IP 127.0.0.1 is in forbidden list, drop"

### ISSUE THREAD

**Issue by smthvitas** [shadowsocks/shadowsocks-libev#1144]
### What version of shadowsocks-libev are you using?
ssserver(python): 2.6.8
ss-libev: 2.4.5

### What did you do?
I configured my router as following for udp relay testing：
iptables -t nat -A OUTPUT -d 8.8.8.8 -p udp -j LOG 
iptables -t nat -A OUTPUT -d 8.8.8.8 -p udp -j REDIRECT --to-ports "ss-redir listening ports"
and also opened iptables Logging of input/output chain on my vps.

When I execute "nslookup facebook.com 8.8.8.8" on my router,
1、I can see 9 OUTPUT packet logs in syslog on my router;
2、I can see 9 INPUT packet logs in syslog on my vps;
3、there's no OUTPUT packet logs in syslog on my vps, and when I run ssserver in verbose mode, there's 9 debug info: "IP 127.0.0.1 is in forbidden list, drop"
4、I've found this in the source code of ss：
        _IPNetwork(config.get('forbidden_ip', '127.0.0.0/8,::1/128'));_

I think the outgoing dns request packets will pass through with the following order:
5、the nslookup tool generate a dns request packet, with dest ip 8.8.8.8；
6、this packet goes into OUTPUT chain, then be redirected to local ss-redir port;
7、ss-libev received this packet, make some encryption, then generate a new packet with dest ip set to my_vps_ip；
8、the new packet goes into POSTROUTING chain, where it's source ip will be set to the public IP address from my ISP, by MASQUERADE operation.

so, my question is:
1、why ssserver dropped my dns request packet? where's the 127.0.0.1 comes from?
2、Is my analysis above, steps 5-8 right?  BTW, I think the original dns request packet will goes into INPUT chain after step 6，right？
3、Are there some materials  I should read to understand the mechanism of ssserver？

Thank you for your patience here, any help will be appreciated.

**Comment by madeye** [comment]
```
iptables -t nat -A OUTPUT -d 8.8.8.8 -p udp -j REDIRECT --to-ports "ss-redir listening ports"
```

It actually won't work. UDP NAT only works with TPROXY, REDIRECT would cause unexpected issues. More details can be found here: https://github.com/shadowsocks/shadowsocks-libev/blob/master/doc/ss-redir.asciidoc#example

**Comment by smthvitas** [comment]
@madeye thanks！ I will try this.

**Comment by rogers0** [comment]
@smthvitas maybe you could try my script, posted here: https://github.com/shadowsocks/shadowsocks-libev/issues/1108#issuecomment-275397280
