### ISSUE TITLE
autogen.sh和configure.ac的问题

### ISSUE THREAD

**Issue by testcaoy7** [shadowsocks/shadowsocks-libev#1145]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
2.6.3

### What operating system are you using?
ubuntu 16.10

### What did you do?
运行 ./autogen.sh

### What did you expect to see?
完成 autogen.sh

### What did you see instead?
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'auto'.
libtoolize: copying file 'auto/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
configure.ac:26: error: possibly undefined macro: AC_MSG_ERROR
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:259: error: possibly undefined macro: AC_LIB_HAVE_LINKFLAGS
autoreconf: /usr/bin/autoconf failed with exit status: 1

**Comment by rogers0** [comment]
@testcaoy7 try latest commit, please

**Comment by madeye** [comment]
Please try the latest commit.
