### ISSUE TITLE
Can't build deb on Raspbian

### ISSUE THREAD

**Issue by newphp** [shadowsocks/shadowsocks-libev#1147]
### What version of shadowsocks-libev are you using?
2.6.3

### What operating system are you using?
Raspbian GNU/Linux 8.0 (jessie)

### What did you do?
execute dpkg-buildpackage -b -us -uc -i

### What did you expect to see?
successfully build shadowsocks-libev_2.6.3-1_armrf.deb 

### What did you see instead?
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -D_FORTIFY_SOURCE=2 -g -O2 -Wall -Werror -Wno-deprecated-declarations -fno-strict-aliasing -std=gnu99 -D_GNU_SOURCE -pthread -I../libipset/include -I../libcork/include -DMODULE_LOCAL -DLIB_ONLY -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -pthread -c json.c  -fPIC -DPIC -o .libs/libshadowsocks_libev_la-json.o
/bin/bash ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..   -D_FORTIFY_SOURCE=2 -g -O2 -Wall -Werror -Wno-deprecated-declarations -fno-strict-aliasing -std=gnu99 -D_GNU_SOURCE -pthread -I../libipset/include -I../libcork/include  -DMODULE_LOCAL -DLIB_ONLY -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -pthread -c -o libshadowsocks_libev_la-encrypt.lo `test -f 'encrypt.c' || echo './'`encrypt.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -D_FORTIFY_SOURCE=2 -g -O2 -Wall -Werror -Wno-deprecated-declarations -fno-strict-aliasing -std=gnu99 -D_GNU_SOURCE -pthread -I../libipset/include -I../libcork/include -DMODULE_LOCAL -DLIB_ONLY -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -pthread -c encrypt.c  -fPIC -DPIC -o .libs/libshadowsocks_libev_la-encrypt.o
encrypt.c: In function 'crypto_stream_xor_ic':
encrypt.c:294:9: error: implicit declaration of function 'crypto_stream_chacha20_ietf_xor_ic' [-Werror=implicit-function-declaration]
         return crypto_stream_chacha20_ietf_xor_ic(c, m, mlen, n, (uint32_t)ic, k);
         ^
cc1: all warnings being treated as errors
Makefile:831: recipe for target 'libshadowsocks_libev_la-encrypt.lo' failed
make[3]: *** [libshadowsocks_libev_la-encrypt.lo] Error 1
make[3]: Leaving directory '/usr/src/shadowsocks-libev-2.6.3/src'
Makefile:484: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/usr/src/shadowsocks-libev-2.6.3'
Makefile:392: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/usr/src/shadowsocks-libev-2.6.3'
dh_auto_build: make -j1 returned exit code 2
debian/rules:28: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2

### What is your config in detail (with all sensitive info masked)?
wget https://github.com/shadowsocks/shadowsocks-libev/releases/download/v2.6.3/shadowsocks-libev-2.6.3.tar.gz
wget https://github.com/shadowsocks/shadowsocks-libev/archive/v2.6.3.tar.gz
tar -zxf v2.6.3.tar.gz && tar -zcf shadowsocks-libev-2.6.3.tar.gz 
cd shadowsocks-libev-2.6.3
sudo apt-get install --no-install-recommends gettext build-essential autoconf libtool libssl-dev \
    gawk debhelper dh-systemd init-system-helpers pkg-config asciidoc xmlto apg libpcre3-dev zlib1g-dev \
    libev-dev libudns-dev libsodium-dev
./autogen.sh
dpkg-buildpackage -b -us -uc -i

These codes did work on Ubuntu 16.04.1 LTS amd64.

### Other detail
By the way, if I get source by git clone https://github.com/shadowsocks/shadowsocks-libev.git , ./autogen.sh will failed with fowllowing codes:

libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, `auto'.
libtoolize: copying file `auto/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: copying file `m4/libtool.m4'
libtoolize: copying file `m4/ltoptions.m4'
libtoolize: copying file `m4/ltsugar.m4'
libtoolize: copying file `m4/ltversion.m4'
libtoolize: copying file `m4/lt~obsolete.m4'
configure.ac:13: installing 'auto/ar-lib'
configure.ac:10: installing 'auto/compile'
configure.ac:21: installing 'auto/config.guess'
configure.ac:21: installing 'auto/config.sub'
configure.ac:12: installing 'auto/install-sh'
configure.ac:12: installing 'auto/missing'
configure.ac:316: error: required file 'libcork/Makefile.in' not found
configure.ac:316: error: required file 'libipset/Makefile.in' not found
src/Makefile.am: installing 'auto/depcomp'
autoreconf: automake failed with exit status: 1

**Comment by rogers0** [comment]
@newphp just try latest commit

**Comment by newphp** [comment]
@rogers0 latest commit didn't help, please referer the "Other detail" on my issue comment.
I also tried to copy libcork/Makefile.in and libipset/Makefile.in to git cloned, but other errors encountered as bellow.

configure: creating ./config.status
config.status: creating doc/Makefile
config.status: creating shadowsocks-libev.pc
config.status: creating Makefile
config.status: creating libcork/Makefile
config.status: creating libipset/Makefile
config.status: creating src/Makefile
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing libtool commands
make[1]: Leaving directory '/usr/src/shadowsocks-libev'
   dh_auto_build
	make -j1
make[1]: Entering directory '/usr/src/shadowsocks-libev'
make  all-recursive
make[2]: Entering directory '/usr/src/shadowsocks-libev'
Making all in libcork
make[3]: Entering directory '/usr/src/shadowsocks-libev/libcork'
make[3]: *** No rule to make target 'src/libcork/cli/commands.c', needed by 'src/libcork/cli/libcork_la-commands.lo'.  Stop.
make[3]: Leaving directory '/usr/src/shadowsocks-libev/libcork'
Makefile:474: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/usr/src/shadowsocks-libev'
Makefile:378: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/usr/src/shadowsocks-libev'
dh_auto_build: make -j1 returned exit code 2
debian/rules:28: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2

**Comment by rogers0** [comment]
@newphp I'll have a solution for you after 8 days.
Now you can only try: https://github.com/shadowsocks/shadowsocks-libev/issues/1095#issuecomment-274445199
ping me after 8 days

**Comment by newphp** [comment]
@rogers0 Sure, thank you!
Have a nice Spring Festival.

**Comment by lcdtyph** [comment]
Did you run ```git submodule update --init --recursive``` after cloning?

**Comment by rogers0** [comment]
@newphp I refined the script in https://github.com/shadowsocks/shadowsocks-libev/issues/1095#issuecomment-274445199
and checked in the lastest jessie-backports in debian alioth repo (not official yet, so it's under test_jessie-backports2 branch).
So you can try to build your pkg under Raspbian.

If you meet any problem, just let me know.

```shell
#!/bin/sh

# please add xenial-backports repo to your apt source list
# because we use debhelper 10 in that repo
apt install -y git-buildpackage

gbp_build() {
    REPO=$1
    BRANCH=$2
    PROJECT_NAME=$(basename $1 | sed s/\.git$//)
    gbp clone --pristine-tar $REPO
    cd $PROJECT_NAME
    git checkout $BRANCH
    BUILD_DEP=$(perl -ne 'next if /^#/; $p=(s/^Build-Depends:\s*/ / or (/^ / and $p)); s/,|\n|\([^)]+\)//mg; print if $p' < debian/control)
    apt install -y $BUILD_DEP
    gbp buildpackage -us -uc --git-ignore-branch --git-pristine-tar
    cd ..
}

# build libcork deb if you don't have
gbp_build https://github.com/rogers0/libcork debian
dpkg -i libcork-dev_*.deb libcork16_*.deb

# build libcorkipset deb if you don't have
gbp_build https://github.com/rogers0/libcorkipset debian
dpkg -i libcorkipset-dev_*.deb libcorkipset1_*.deb

# build shadowsocks-libev
#gbp_build https://anonscm.debian.org/git/collab-maint/shadowsocks-libev.git jessie-backports2
gbp_build https://anonscm.debian.org/git/collab-maint/shadowsocks-libev.git test_jessie-backports2
dpkg -i shadowsocks-libev_*.deb
```

**Comment by newphp** [comment]
### I've also tried these on Raspbian GNU/Linux 8.0 (jessie):

./configure --build=arm-linux-gnueabihf --prefix=/usr --includedir=/usr/include --mandir=/usr/share/man --infodir=/usr/share/info --sysconfdir=/etc --localstatedir=/var --disable-silent-rules --libdir=/usr/lib/arm-linux-gnueabihf --libexecdir=/usr/lib/arm-linux-gnueabihf --disable-maintainer-mode --disable-dependency-tracking --enable-shared --disable-ssp
make

### Errors bellow:
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -g -O2 -Wall -Werror -Wno-deprecated-declarations -fno-strict-aliasing -std=gnu99 -D_GNU_SOURCE -pthread -I../libipset/include -I../libcork/include -DMODULE_LOCAL -DLIB_ONLY -g -O2 -pthread -c encrypt.c  -fPIC -DPIC -o .libs/libshadowsocks_libev_la-encrypt.o
encrypt.c: In function 'crypto_stream_xor_ic':
encrypt.c:294:9: error: implicit declaration of function 'crypto_stream_chacha20_ietf_xor_ic' [-Werror=implicit-function-declaration]
         return crypto_stream_chacha20_ietf_xor_ic(c, m, mlen, n, (uint32_t)ic, k);
         ^
cc1: all warnings being treated as errors
Makefile:831: recipe for target 'libshadowsocks_libev_la-encrypt.lo' failed
make[2]: *** [libshadowsocks_libev_la-encrypt.lo] Error 1
make[2]: Leaving directory '/usr/src/shadowsocks-libev-2.6.3/src'
Makefile:484: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/usr/src/shadowsocks-libev-2.6.3'
Makefile:392: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by lcdtyph** [comment]
@newphp 
```
apt purge libsodium*
```
Then install the latest libsodium from source with ```--prefix=/usr```.

```
git clone https://github.com/jedisct1/libsodium
cd libsodium
./autogen.sh
./configure --prefix=/usr
make && make install
```

**Comment by rogers0** [comment]
@lcdtyph why to recommend others to install from source?
Please stop doing it. Thanks.

**Comment by rogers0** [comment]
For jessie, it's still recommended this way: https://github.com/shadowsocks/shadowsocks-libev/issues/1147#issuecomment-276318637

**Comment by newphp** [comment]
@rogers0 Hi, there is no python3-cram pkg on raspbian, I also installed cram via pip3, and add , but didn't help.

**Comment by rogers0** [comment]
@newphp I guess changing it to python2-cram it still works. But it need some steps for that simple change.
I'll try it later then let you know.

**Comment by newphp** [comment]
After install mbedTLS and libsodium from source, Shadowsocks-libev 2.6.3 and 3.0.0 was compiled successfully. Thank you guys.
I'm able to install the built .deb pkg on another debian like opration system, but the program can't run normally.

/usr/bin/ss-server: symbol lookup error: /usr/bin/ss-server: undefined symbol: crypto_pwhash

It means that I have to install mbedTLS 1.0.11 and libsodium 2.4.0 from source on each computer or VPS.
