### ISSUE TITLE
Can ss-redir work with simple-obfs ?

### ISSUE THREAD

**Issue by qiang-yu** [shadowsocks/shadowsocks-libev#1149]
All example you showed was  ss-server / ss-local,  i never see any example show ss-redir work with simple-obfs,  can ss-redir work with that too ?

thanks

**Comment by madeye** [comment]
Yep.

**Comment by qiang-yu** [comment]
ss-server -c config.json --plugin obfs-server --plugin-opts "obfs=http"

how does the ss-server find the obfs-server executable file ?   

--plugin "here is the executable file name ? then, if they are in different directory, how to find this file ?"

**Comment by lcdtyph** [comment]
@qiang-yu 
You can specify an absolute path of the plugin.
If you only specify a file name, shadowsocks will search it in the ```PATH``` env var.

**Comment by qiang-yu** [comment]
thanks, got it
