### ISSUE TITLE
complie and meet "crypto_pwhash_SALTBYTES" undeclared

### ISSUE THREAD

**Issue by lixingcong** [shadowsocks/shadowsocks-libev#1157]
### What version of shadowsocks-libev are you using?

	commit 833594e

### What operating system are you using?

	ubuntu 16.04.1 
	Linux 4.4.0-59-generic #80-Ubuntu SMP Fri Jan 6 17:47:47 UTC 2017 x86_64

### What did you do?

	git pull && git submodule update --init --recursive
	./configure --disable-documentation
	make -j2

### What did you expect to see?

	compile pass

### What did you see instead?

	# make -j2

	make  all-recursive
	make[1]: Entering directory '/root/temp/ss/shadowsocks-libev'
	Making all in libcork
	make[2]: Entering directory '/root/temp/ss/shadowsocks-libev/libcork'
	CC       src/libcork/cli/libcork_la-commands.lo
	CC       src/libcork/core/libcork_la-allocator.lo
	CC       src/libcork/core/libcork_la-error.lo
	CC       src/libcork/core/libcork_la-gc.lo
	CC       src/libcork/core/libcork_la-hash.lo
	CC       src/libcork/core/libcork_la-ip-address.lo
	CC       src/libcork/core/libcork_la-mempool.lo
	CC       src/libcork/core/libcork_la-timestamp.lo
	CC       src/libcork/core/libcork_la-u128.lo
	CC       src/libcork/ds/libcork_la-array.lo
	CC       src/libcork/ds/libcork_la-bitset.lo
	CC       src/libcork/ds/libcork_la-buffer.lo
	CC       src/libcork/ds/libcork_la-dllist.lo
	CC       src/libcork/ds/libcork_la-file-stream.lo
	CC       src/libcork/ds/libcork_la-hash-table.lo
	CC       src/libcork/ds/libcork_la-managed-buffer.lo
	CC       src/libcork/ds/libcork_la-ring-buffer.lo
	CC       src/libcork/ds/libcork_la-slice.lo
	CC       src/libcork/posix/libcork_la-directory-walker.lo
	CC       src/libcork/posix/libcork_la-env.lo
	CC       src/libcork/posix/libcork_la-exec.lo
	CC       src/libcork/posix/libcork_la-files.lo
	CC       src/libcork/posix/libcork_la-process.lo
	CC       src/libcork/posix/libcork_la-subprocess.lo
	CC       src/libcork/pthreads/libcork_la-thread.lo
	CCLD     libcork.la
	ar: `u' modifier ignored since `D' is the default (see `U')
	make[2]: Leaving directory '/root/temp/ss/shadowsocks-libev/libcork'
	Making all in libipset
	make[2]: Entering directory '/root/temp/ss/shadowsocks-libev/libipset'
	CC       src/libipset/bdd/libipset_la-assignments.lo
	CC       src/libipset/libipset_la-general.lo
	CC       src/libipset/bdd/libipset_la-basics.lo
	CC       src/libipset/bdd/libipset_la-bdd-iterator.lo
	CC       src/libipset/bdd/libipset_la-expanded.lo
	CC       src/libipset/bdd/libipset_la-reachable.lo
	CC       src/libipset/bdd/libipset_la-read.lo
	CC       src/libipset/bdd/libipset_la-write.lo
	CC       src/libipset/map/libipset_la-allocation.lo
	CC       src/libipset/map/libipset_la-inspection.lo
	CC       src/libipset/map/libipset_la-ipv4_map.lo
	CC       src/libipset/map/libipset_la-ipv6_map.lo
	CC       src/libipset/map/libipset_la-storage.lo
	CC       src/libipset/set/libipset_la-allocation.lo
	CC       src/libipset/set/libipset_la-inspection.lo
	CC       src/libipset/set/libipset_la-ipv4_set.lo
	CC       src/libipset/set/libipset_la-ipv6_set.lo
	CC       src/libipset/set/libipset_la-iterator.lo
	CC       src/libipset/set/libipset_la-storage.lo
	CCLD     libipset.la
	copying selected object files to avoid basename conflicts...
	ar: `u' modifier ignored since `D' is the default (see `U')
	make[2]: Leaving directory '/root/temp/ss/shadowsocks-libev/libipset'
	Making all in src
	make[2]: Entering directory '/root/temp/ss/shadowsocks-libev/src'
	CC       libshadowsocks_libev_la-utils.lo
	CC       libshadowsocks_libev_la-jconf.lo
	CC       libshadowsocks_libev_la-json.lo
	CC       libshadowsocks_libev_la-udprelay.lo
	CC       libshadowsocks_libev_la-cache.lo
	CC       libshadowsocks_libev_la-acl.lo
	CC       libshadowsocks_libev_la-netutils.lo
	CC       libshadowsocks_libev_la-local.lo
	CC       libshadowsocks_libev_la-crypto.lo
	crypto.c: In function ‘crypto_derive_key’:
	crypto.c:108:34: error: ‘crypto_pwhash_SALTBYTES’ undeclared (first use in this function)
			const unsigned char salt[crypto_pwhash_SALTBYTES] = {
									^
	crypto.c:108:34: note: each undeclared identifier is reported only once for each function it appears in
	crypto.c:112:19: error: implicit declaration of function ‘crypto_pwhash’ [-Werror=implicit-function-declaration]
			int err = crypto_pwhash (key, nkey, (char*)pass, strlen(pass), salt,
					^
	crypto.c:113:17: error: ‘crypto_pwhash_OPSLIMIT_INTERACTIVE’ undeclared (first use in this function)
					crypto_pwhash_OPSLIMIT_INTERACTIVE, crypto_pwhash_MEMLIMIT_INTERACTIVE,
					^
	crypto.c:113:53: error: ‘crypto_pwhash_MEMLIMIT_INTERACTIVE’ undeclared (first use in this function)
					crypto_pwhash_OPSLIMIT_INTERACTIVE, crypto_pwhash_MEMLIMIT_INTERACTIVE,
														^
	crypto.c:114:17: error: ‘crypto_pwhash_ALG_DEFAULT’ undeclared (first use in this function)
					crypto_pwhash_ALG_DEFAULT);
					^
	crypto.c:108:29: error: unused variable ‘salt’ [-Werror=unused-variable]
			const unsigned char salt[crypto_pwhash_SALTBYTES] = {
								^
	cc1: all warnings being treated as errors
	Makefile:881: recipe for target 'libshadowsocks_libev_la-crypto.lo' failed
	make[2]: *** [libshadowsocks_libev_la-crypto.lo] Error 1
	make[2]: *** Waiting for unfinished jobs....
	make[2]: Leaving directory '/root/temp/ss/shadowsocks-libev/src'
	Makefile:477: recipe for target 'all-recursive' failed
	make[1]: *** [all-recursive] Error 1
	make[1]: Leaving directory '/root/temp/ss/shadowsocks-libev'
	Makefile:386: recipe for target 'all' failed
	make: *** [all] Error 2

**Comment by dsyo2008** [comment]
Yes, I have the same problem

`~/shadowsocks-libev# make && make install
make  all-recursive
make[1]: Entering directory '/root/shadowsocks-libev'
Making all in libcork
make[2]: Entering directory '/root/shadowsocks-libev/libcork'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/root/shadowsocks-libev/libcork'
Making all in libipset
make[2]: Entering directory '/root/shadowsocks-libev/libipset'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/root/shadowsocks-libev/libipset'
Making all in src
make[2]: Entering directory '/root/shadowsocks-libev/src'
  CCLD     ss-local
ss_local-crypto.o: In function `crypto_derive_key':
/root/shadowsocks-libev/src/crypto.c:112: undefined reference to `crypto_pwhash'
ss_local-aead.o: In function `cipher_aead_decrypt':
/root/shadowsocks-libev/src/aead.c:274: undefined reference to `crypto_aead_xchacha20poly1305_ietf_decrypt'
ss_local-aead.o: In function `cipher_aead_encrypt':
/root/shadowsocks-libev/src/aead.c:227: undefined reference to `crypto_aead_xchacha20poly1305_ietf_encrypt'
collect2: error: ld returned 1 exit status
Makefile:663: recipe for target 'ss-local' failed
make[2]: *** [ss-local] Error 1
make[2]: Leaving directory '/root/shadowsocks-libev/src'
Makefile:477: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/root/shadowsocks-libev'
Makefile:386: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by kevinzu007** [comment]
me too

**Comment by panzhitian** [comment]
Have you guys installed the new dependencies `libmbedtls-dev`?
https://github.com/shadowsocks/shadowsocks-libev/commit/78cf5348f0da73e8de1cb2d3e4644acca80be6a5

**Comment by flipphos** [comment]
I am also interested to know how to install this new dependency in Centos 7. Thanks in advance.

**Comment by lixingcong** [comment]
> Have you guys installed the new dependencies libmbedtls-dev?
> 78cf534

Yes I have installed it

> I am also interested to know how to install this new dependency in Centos 7.

I dont know. My OS is ubuntu

<hr>

I guess the problem caused by libsodium version. I guess we must install 1.0.9 or higher

**Comment by panzhitian** [comment]
The README was updated, however, the mentioned  packages on debian testing are new enough to build successfully.
https://github.com/shadowsocks/shadowsocks-libev/commit/3b8b30aec21892ef87e28a97b336f6f37c321912

**Comment by kevinzu007** [comment]
# 依赖组件

cd /usr/local/src

wget
https://download.libsodium.org/libsodium/releases/libsodium-1.0.11.tar.gz

tar zxf libsodium-1.0.11.tar.gz

cd libsodium-1.0.11/

./configure --prefix=/usr/local/libsodium

make

make install


cd /usr/local/src

wget  https://tls.mbed.org/download/mbedtls-2.4.0-apache.tgz

tar zxf mbedtls-2.4.0-apache.tgz

cd mbedtls-2.4.0/

make

使用稳定版--------------

cd /usr/local/src

wget
https://github.com/shadowsocks/shadowsocks-libev/releases/download/v3.0.0/shadowsocks-libev-3.0.0.tar.gz

tar zxf shadowsocks-libev-3.0.0.tar.gz

cd shadowsocks-libev-3.0.0/

./configure --help | grep tls

./configure --help | grep sodium

./configure --with-mbedtls=/usr/local/src/mbedtls-2.4.0
 --with-sodium=/usr/local/libsodium

make

sudo make install


2017-02-02 10:43 GMT+08:00 Lixingcong <notifications@github.com>:
