### ISSUE TITLE
Failed upgrade to the new version of SS-libev 3.0

### ISSUE THREAD

**Issue by asmadeus08** [shadowsocks/shadowsocks-libev#1159]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
SS-libev 2.6.1-1

### What operating system are you using?
ubuntu 16.04.1 Linux kernel 4.10

### What did you do?
cd shadowsocks-libev
git reset --hard origin/master
git pull
git submodule init && git submodule update
sudo apt-get install --no-install-recommends build-essential autoconf libtool libssl-dev \
gawk debhelper dh-systemd init-system-helpers pkg-config asciidoc xmlto apg libpcre3-dev zlib1g-dev \
libev-dev libudns-dev libsodium-dev
./autogen.sh && dpkg-buildpackage -b -us -uc -i

### What did you expect to see?
Succesed installation

### What did you see instead?
configure: exit 1
dh_auto_configure: ./configure --build=i686-linux-gnu --prefix=/usr --includedir=${prefix}/include --mandir=${prefix}/share/man --infodir=${prefix}/share/info --sysconfdir=/etc --localstatedir=/var --disable-silent-rules --libdir=${prefix}/lib/i386-linux-gnu --libexecdir=${prefix}/lib/i386-linux-gnu --disable-maintainer-mode --disable-dependency-tracking --enable-shared --disable-ssp returned exit code 1
debian/rules:17: recipe for target 'override_dh_auto_configure' failed
make[1]: *** [override_dh_auto_configure] Error 255
make[1]: Leaving directory '/root/shadowsocks-libev'
debian/rules:28: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2

### What is your config in detail (with all sensitive info masked)?
Basic config.json file

**Comment by eastmalon** [comment]
Try:
```
./configure
dpkg-buildpackage -b -us -uc -i
cd ..
sudo dpkg -i shadowsocks-libev_3.0.0*.deb
```

**Comment by asmadeus08** [comment]
Just updated from git and see that libsodium library was added so i tried to build ss libev again and go new error:
configure: error: mbed TLS libraries not found.
Makefile:417: recipe for target 'config.status' failed
make[1]: *** [config.status] Error 1
make[1]: Leaving directory '/root/shadowsocks-libev'
dh_auto_clean: make -j1 distclean returned exit code 2
debian/rules:28: recipe for target 'clean' failed
make: *** [clean] Error 2
dpkg-buildpackage: error: debian/rules clean gave error exit status 2

**Comment by asmadeus08** [comment]
Installed this library:
sudo apt-get install --no-install-recommends gettext build-essential autoconf libtool libpcre3-dev asciidoc xmlto libmbedtls-dev libev-dev libudns-dev libsodium-dev

And now that's what i see:

ss_local-crypto.o: In function `crypto_derive_key':
/root/shadowsocks-libev/src/crypto.c:112: undefined reference to `crypto_pwhash'
collect2: error: ld returned 1 exit status
Makefile:663: recipe for target 'ss-local' failed
make[3]: *** [ss-local] Error 1
make[3]: Leaving directory '/root/shadowsocks-libev/src'
Makefile:477: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/root/shadowsocks-libev'
Makefile:386: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/root/shadowsocks-libev'
dh_auto_build: make -j1 returned exit code 2
debian/rules:28: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2

**Comment by eastmalon** [comment]
shadowsocks-libev_3.0.0 depends on libsodium18 (>= 1.0.10) which requires ubuntu 16.10.

**Comment by asmadeus08** [comment]
@eastmalon but how to install ubuntu 16.10 if i checked that and that i got:
do-release-upgrade
Checking for a new Ubuntu release
No new release found

**Comment by eastmalon** [comment]
edit `/etc/update-manager/release-upgrades` file and set the variable prompt as below:
`Prompt=normal`

**Comment by lcdtyph** [comment]
@asmadeus08 
You can also install the latest libsodium from source.
Please remove old version installed from apt first.
```
git clone https://github.com/jedisct1/libsodium
cd libsodium
./autogen.sh
./configure --prefix=/usr
make && make install
```

**Comment by dsyo2008** [comment]
@lcdtyph
感谢你，编译成功，原来是要删除旧版本，编译OK！话说，OTA去掉？我试下命令说不存在

**Comment by asmadeus08** [comment]
@lcdtyph already have latest version of libsodium but when doing that git reset --hard origin/master it ask to check libsodium version? Do you you know how to remove old version first?
@eastmalon edit like you said and upgrading.. let's what will happened.

**Comment by dsyo2008** [comment]
@asmadeus08 sudo apt-get remove libsodium-dev
再编译libsodium就可以

**Comment by lcdtyph** [comment]
@asmadeus08 
Remove old version:
```apt purge libsodium*```
Then reinstall the latest libsodium with the ```prefix=/usr```

**Comment by asmadeus08** [comment]
Done. That's what i did:
1 Upgraded system to the 16.10
2
cd shadowsocks-libev
git reset --hard origin/master
git pull
git submodule init && git submodule update
sudo apt-get install --no-install-recommends build-essential autoconf libtool libssl-dev \
gawk debhelper dh-systemd init-system-helpers pkg-config asciidoc xmlto apg libpcre3-dev zlib1g-dev \
libev-dev libudns-dev libsodium-dev
sudo apt-get install --no-install-recommends gettext build-essential autoconf libtool libpcre3-dev asciidoc xmlto libmbedtls-dev libev-dev libudns-dev libsodium-dev
./autogen.sh && dpkg-buildpackage -b -us -uc -i

All is working fine.
