### ISSUE TITLE
Can't build shadowsocks 3.0.0 on Ubuntu 16.04

### ISSUE THREAD

**Issue by newphp** [shadowsocks/shadowsocks-libev#1160]
### What version of shadowsocks-libev are you using?
3.0.0

### What operating system are you using?
Ubuntu 16.04.1 LTS with kernel 4.9.2

### What did you do?
apt-get install --no-install-recommends gettext build-essential autoconf libtool gawk debhelper dh-systemd init-system-helpers pkg-config asciidoc xmlto apg libpcre3-dev libmbedtls-dev libev-dev libudns-dev libsodium-dev

cd /usr/src
git clone https://github.com/shadowsocks/shadowsocks-libev.git
cd /usr/src/shadowsocks-libev
git submodule update --init --recursive

./autogen.sh
./configure --build=x86_64-linux-gnu --prefix=/usr --includedir=/usr/include --mandir=/usr/share/man --infodir=/usr/share/info --sysconfdir=/etc --localstatedir=/var --disable-silent-rules --libdir=/usr/lib/x86_64-linux-gnu --libexecdir=/usr/lib/x86_64-linux-gnu --disable-maintainer-mode --disable-dependency-tracking --enable-shared --disable-ssp
make

### What did you expect to see?
make command return 0

### What did you see instead?
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -g -O2 -Wall -Werror -Wno-deprecated-declarations -fno-strict-aliasing -std=gnu99 -D_GNU_SOURCE -pthread -I../libipset/include -I../libcork/include -DMODULE_LOCAL -DLIB_ONLY -g -O2 -pthread -c crypto.c  -fPIC -DPIC -o .libs/libshadowsocks_libev_la-crypto.o
crypto.c: In function ‘crypto_derive_key’:
crypto.c:108:34: error: ‘crypto_pwhash_SALTBYTES’ undeclared (first use in this function)
         const unsigned char salt[crypto_pwhash_SALTBYTES] = {
                                  ^
crypto.c:108:34: note: each undeclared identifier is reported only once for each function it appears in
crypto.c:112:19: error: implicit declaration of function ‘crypto_pwhash’ [-Werror=implicit-function-declaration]
         int err = crypto_pwhash (key, nkey, (char*)pass, strlen(pass), salt,
                   ^
crypto.c:113:17: error: ‘crypto_pwhash_OPSLIMIT_INTERACTIVE’ undeclared (first use in this function)
                 crypto_pwhash_OPSLIMIT_INTERACTIVE, crypto_pwhash_MEMLIMIT_INTERACTIVE,
                 ^
crypto.c:113:53: error: ‘crypto_pwhash_MEMLIMIT_INTERACTIVE’ undeclared (first use in this function)
                 crypto_pwhash_OPSLIMIT_INTERACTIVE, crypto_pwhash_MEMLIMIT_INTERACTIVE,
                                                     ^
crypto.c:114:17: error: ‘crypto_pwhash_ALG_DEFAULT’ undeclared (first use in this function)
                 crypto_pwhash_ALG_DEFAULT);
                 ^
crypto.c:108:29: error: unused variable ‘salt’ [-Werror=unused-variable]
         const unsigned char salt[crypto_pwhash_SALTBYTES] = {
                             ^
cc1: all warnings being treated as errors
Makefile:885: recipe for target 'libshadowsocks_libev_la-crypto.lo' failed
make[2]: *** [libshadowsocks_libev_la-crypto.lo] Error 1
make[2]: Leaving directory '/usr/src/shadowsocks-libev/src'
Makefile:477: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/usr/src/shadowsocks-libev'
Makefile:386: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by lcdtyph** [comment]
@newphp 
Remove the old libsodium and install the latest version from source.

**Comment by asmadeus08** [comment]
Agree with previous comment but if you have ubuntu 16.10 and already installed old version of ss-libev then do this one:
cd shadowsocks-libev
git reset --hard origin/master
git pull
git submodule init && git submodule update
sudo apt-get install --no-install-recommends build-essential autoconf libtool libssl-dev \
gawk debhelper dh-systemd init-system-helpers pkg-config asciidoc xmlto apg libpcre3-dev zlib1g-dev \
libev-dev libudns-dev libsodium-dev
sudo apt-get install --no-install-recommends gettext build-essential autoconf libtool libpcre3-dev asciidoc xmlto libmbedtls-dev libev-dev libudns-dev libsodium-dev
./autogen.sh && dpkg-buildpackage -b -us -uc -i

I did and my ss-libev version upgraded with easy.

If you are installing on the fresh system then do this one:
cd shadowsocks-libev
git reset --hard origin/master
git pull
git submodule init && git submodule update (git pull && git submodule update --init --recursive)
sudo apt-get install --no-install-recommends build-essential autoconf libtool libssl-dev \
gawk debhelper dh-systemd init-system-helpers pkg-config asciidoc xmlto apg libpcre3-dev zlib1g-dev \
libev-dev libudns-dev libsodium-dev
sudo apt-get install --no-install-recommends gettext build-essential autoconf libtool libpcre3-dev asciidoc xmlto libmbedtls-dev libev-dev libudns-dev libsodium-dev
./autogen.sh && dpkg-buildpackage -b -us -uc -i
sudo dpkg -i shadowsocks-libev_3.0.0*.deb

**Comment by newphp** [comment]
After install mbedTLS and libsodium from source, Shadowsocks-libev 3.0.0 was compiled successfully.
Thank you guys.
Issue closed.
