### ISSUE TITLE
[SIP005] Support TCP MD5SIG option as a lightweight anti TCP MITM method

### ISSUE THREAD

**Issue by anonymous-contributor** [shadowsocks/shadowsocks-libev#1163]
# Backgroud
Although we have Tor PT support (only proxy mode yet), someone may consider it's too heavy.

The original purpose for Tor PT support is to avoid TCP RST Man-in-the-middle attack, for some it's too heavy and considering there is already some report about DPI devices [detecting obfs2/3/4 or screamblesuit](https://www.allot.com/products/platforms/supported-protocols/#1460974307058-a61550f0-8196), another lightweight implement won't hurt.

# Lightweight alternative
And I just found that there is already [RFC 2385](https://www.ietf.org/rfc/rfc2385.txt) addressing this problem by introducing MD5 signature for TCP.
Which even covers TCP handshake, making it quite a good option for us to simply defend TCP RST MITM attack.

# Further concern
The implementation should be even easier than Tor PT proxy mode, but I still have several concern on it.

1. Insecure hash algorithm
There is known attack against MD5, it's no longer considered as a safe hash algorithm.

2. More obvious connection characteristic
MD5SIG is normally strongly binded to BGP, which is far from common in normal use case.
Use of MD5SIG will make connection super easy to be detected and blocked.

3. Harder to debug
Since kernel will just drop any TCP packet with wrong or no MD5 signature, including the hand shake packets, withouth informing user space, it will be quite hard to debug.

So I think it's better to be discussed before pushing a PR.

**Comment by madeye** [comment]
Do you mean implement a new SIP003 proxy to support TCP MD5?

**Comment by madeye** [comment]
>More obvious connection characteristic
>MD5SIG is normally strongly binded to BGP, which is far from common in normal use case.
>Use of MD5SIG will make connection super easy to be detected and blocked.

It looks really a problem, as our goal is making the traffic indistinguishable.

**Comment by madeye** [comment]
Also, could you move this proposal to https://github.com/shadowsocks/shadowsocks-org/issues instead?

**Comment by anonymous-contributor** [comment]
@madeye Thanks for the info. I'm just wondering why I can't find any SIP in this repo.

And for SIP003, no, not implementing a new SIP003 proxy.

In fact, we should avoid wasteing any CPU in MD5SIG if we're connecting to a plugin.
So the MD5SIG is only for plain SS, not for plugin case.
