### ISSUE TITLE
0.0  centos7下编译最新版出错 麻烦指点

### ISSUE THREAD

**Issue by tianrking** [shadowsocks/shadowsocks-libev#1164]
### What version of shadowsocks-libev are you using?
the latest3.0.0 form github
### What operating system are you using?
centos7 64

### What did you do?
先编译了mbedtls和libsodium
cd进shadowsocks-libev 目录 git submodule update --init --recursive

bash autogen.sh
./configure
make(出错）
### What did you see instead?
[root@a shadowsocks-libev]# make
make  all-recursive
make[1]: Entering directory `/root/shadowsocks-libev'
Making all in libcork
make[2]: Entering directory `/root/shadowsocks-libev/libcork'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/root/shadowsocks-libev/libcork'
Making all in libipset
make[2]: Entering directory `/root/shadowsocks-libev/libipset'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/root/shadowsocks-libev/libipset'
Making all in src
make[2]: Entering directory `/root/shadowsocks-libev/src'
  CC       libshadowsocks_libev_la-crypto.lo
  CC       libshadowsocks_libev_la-aead.lo
  CC       libshadowsocks_libev_la-stream.lo
  CC       libshadowsocks_libev_la-plugin.lo
  CC       libshadowsocks_libev_la-http.lo
  CC       libshadowsocks_libev_la-tls.lo
  CC       libshadowsocks_libev_la-rule.lo
  CCLD     libshadowsocks-libev.la
  CC       ss_local-utils.o
  CC       ss_local-jconf.o
  CC       ss_local-json.o
  CC       ss_local-udprelay.o
  CC       ss_local-cache.o
  CC       ss_local-acl.o
  CC       ss_local-netutils.o
  CC       ss_local-local.o
  CC       ss_local-crypto.o
  CC       ss_local-aead.o
  CC       ss_local-stream.o
  CC       ss_local-plugin.o
  CC       ss_local-http.o
  CC       ss_local-tls.o
  CC       ss_local-rule.o
  CCLD     ss-local
ss_local-crypto.o: In function `crypto_derive_key':
/root/shadowsocks-libev/src/crypto.c:112: undefined reference to `crypto_pwhash'
ss_local-aead.o: In function `cipher_aead_decrypt':
/root/shadowsocks-libev/src/aead.c:274: undefined reference to `crypto_aead_xchacha20poly1305_ietf_decrypt'
ss_local-aead.o: In function `cipher_aead_encrypt':
/root/shadowsocks-libev/src/aead.c:227: undefined reference to `crypto_aead_xchacha20poly1305_ietf_encrypt'
collect2: error: ld returned 1 exit status
make[2]: *** [ss-local] Error 1
make[2]: Leaving directory `/root/shadowsocks-libev/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/root/shadowsocks-libev'
make: *** [all] Error 2

**Comment by lixingcong** [comment]
https://github.com/shadowsocks/shadowsocks-libev#build-and-install-the-latest-mbedtls-and-libsodium

**Comment by tianrking** [comment]
我照readme复制了一遍 还是用的centos7
export LIBSODIUM_VER=1.0.11
export MBEDTLS_VER=2.4.0
wget https://download.libsodium.org/libsodium/releases/libsodium-$LIBSODIUM_VER.tar.gz
tar xvf libsodium-$LIBSODIUM_VER.tar.gz
pushd libsodium-$LIBSODIUM_VER
./configure --prefix=/usr && make &&make install 
popd
wget https://tls.mbed.org/download/mbedtls-$MBEDTLS_VER-gpl.tgz
tar xvf mbedtls-$MBEDTLS_VER-gpl.tgz
 pushd mbedtls-$MBEDTLS_VER
make &&make install 
popd
yum install epel-release -y
yum install gcc gettext autoconf libtool automake make pcre-devel asciidoc xmlto libsodium-devel udns-devel libev-devel libmbedtls-devel -y
push sha*v
git submodule update --init --recursive
./autogen.sh && ./configure && make
之后报错
[root@a shadowsocks-libev]# ./autogen.sh && ./configure && make
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, `auto'.
libtoolize: copying file `auto/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: copying file `m4/libtool.m4'
libtoolize: copying file `m4/ltoptions.m4'
libtoolize: copying file `m4/ltsugar.m4'
libtoolize: copying file `m4/ltversion.m4'
libtoolize: copying file `m4/lt~obsolete.m4'
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking for style of include used by make... GNU
checking whether make supports nested variables... yes
checking dependency style of gcc... gcc3
checking for ar... ar
checking the archiver (ar) interface... ar
checking whether make supports nested variables... (cached) yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1966080
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
./configure: line 7021: /usr/bin/file: No such file or directory
checking for mt... no
checking if : is a manifest tool... no
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking for shl_load... no
checking for shl_load in -ldld... no
checking for dlopen... no
checking for dlopen in -ldl... yes
checking whether a program can dlopen itself... yes
checking whether a statically linked program can dlopen itself... yes
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... no
checking whether to build static libraries... yes
checking for pcre-config... pcre-config
checking for pcre headers in ... not found
checking for library containing pcre_exec... -lpcre
checking pcre.h usability... yes
checking pcre.h presence... yes
checking for pcre.h... yes
checking pcre/pcre.h usability... no
checking pcre/pcre.h presence... no
checking for pcre/pcre.h... no
checking for asciidoc... /usr/bin/asciidoc
checking for xmlto... /usr/bin/xmlto
checking for gzip... /usr/bin/gzip
checking for mv... /usr/bin/mv
checking for a sed that does not truncate output... (cached) /usr/bin/sed
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc and cc understand -c and -o together... yes
checking whether ln -s works... yes
checking whether make sets $(MAKE)... (cached) yes
checking for thread local storage (TLS) class... __thread
checking for mbedtls_cipher_setup in -lmbedcrypto... yes
checking whether mbedtls supports Cipher Feedback mode or not... ok
checking whether mbedtls supports the ARC4 stream cipher or not... ok
checking whether mbedtls supports the Blowfish block cipher or not... ok
checking whether mbedtls supports the Camellia block cipher or not... ok
checking for sodium_init in -lsodium... yes
checking for version of libsodium... yes
checking for C/C++ restrict keyword... __restrict
checking for netdb.h... yes
checking for library containing inet_ntop... none required
checking whether inet_ntop is declared... yes
checking for what kind of host... Linux
checking whether gcc is Clang... no
checking whether pthreads work with -pthread... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking whether more special flags are required for pthreads... no
checking for PTHREAD_PRIO_INHERIT... yes
checking if -fstack-protector and -fstack-protector-all are supported.... yes
configure: -fstack-protector enabled in CFLAGS
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking for stdint.h... (cached) yes
checking for inttypes.h... (cached) yes
checking arpa/inet.h usability... yes
checking arpa/inet.h presence... yes
checking for arpa/inet.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking langinfo.h usability... yes
checking langinfo.h presence... yes
checking for langinfo.h... yes
checking locale.h usability... yes
checking locale.h presence... yes
checking for locale.h... yes
checking for netdb.h... (cached) yes
checking netinet/in.h usability... yes
checking netinet/in.h presence... yes
checking for netinet/in.h... yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking for strings.h... (cached) yes
checking for unistd.h... (cached) yes
checking sys/ioctl.h usability... yes
checking sys/ioctl.h presence... yes
checking for sys/ioctl.h... yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking for net/if.h... yes
checking for linux/if.h... yes
checking for linux/netfilter_ipv4.h... yes
checking for linux/netfilter_ipv6/ip6_tables.h... yes
checking whether byte ordering is bigendian... no
checking for inline... inline
checking for ssize_t... yes
checking whether to enable assertions... yes
checking for ANSI C header files... (cached) yes
checking for sys/wait.h that is POSIX.1 compatible... yes
checking for an ANSI C-conforming const... yes
checking for pid_t... yes
checking for size_t... yes
checking for ssize_t... (cached) yes
checking for uint16_t... yes
checking for uint8_t... yes
checking whether time.h and sys/time.h may both be included... yes
checking vfork.h usability... no
checking vfork.h presence... no
checking for vfork.h... no
checking for fork... yes
checking for vfork... yes
checking for working fork... yes
checking for working vfork... (cached) yes
checking sys/select.h usability... yes
checking sys/select.h presence... yes
checking for sys/select.h... yes
checking for sys/socket.h... (cached) yes
checking types of arguments for select... int,fd_set *,struct timeval *
checking return type of signal handlers... void
checking for memset... yes
checking for select... yes
checking for setresuid... yes
checking for setreuid... yes
checking for strerror... yes
checking for getpwnam_r... yes
checking for setrlimit... yes
checking for connect in -lsocket... no
checking for malloc... yes
checking for memset... (cached) yes
checking for socket... yes
checking udns.h usability... yes
checking udns.h presence... yes
checking for udns.h... yes
checking for dns_dnlen in -ludns... yes
checking ev.h usability... yes
checking ev.h presence... yes
checking for ev.h... yes
checking for ev_loop_destroy in -lev... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating doc/Makefile
config.status: creating shadowsocks-libev.pc
config.status: creating Makefile
config.status: creating libcork/Makefile
config.status: creating libipset/Makefile
config.status: creating src/Makefile
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing depfiles commands
config.status: executing libtool commands
make  all-recursive
make[1]: Entering directory `/root/shadowsocks-libev'
Making all in libcork
make[2]: Entering directory `/root/shadowsocks-libev/libcork'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/root/shadowsocks-libev/libcork'
Making all in libipset
make[2]: Entering directory `/root/shadowsocks-libev/libipset'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/root/shadowsocks-libev/libipset'
Making all in src
make[2]: Entering directory `/root/shadowsocks-libev/src'
  CC       libshadowsocks_libev_la-utils.lo
  CC       libshadowsocks_libev_la-udprelay.lo
  CC       libshadowsocks_libev_la-local.lo
  CC       libshadowsocks_libev_la-crypto.lo
  CC       libshadowsocks_libev_la-aead.lo
  CC       libshadowsocks_libev_la-stream.lo
  CCLD     libshadowsocks-libev.la
  CC       ss_local-udprelay.o
  CC       ss_local-local.o
  CC       ss_local-crypto.o
  CC       ss_local-aead.o
  CC       ss_local-stream.o
  CCLD     ss-local
ss_local-crypto.o: In function `crypto_derive_key':
/root/shadowsocks-libev/src/crypto.c:112: undefined reference to `crypto_pwhash'
ss_local-aead.o: In function `cipher_aead_decrypt':
/root/shadowsocks-libev/src/aead.c:274: undefined reference to `crypto_aead_xchacha20poly1305_ietf_decrypt'
ss_local-aead.o: In function `cipher_aead_encrypt':
/root/shadowsocks-libev/src/aead.c:227: undefined reference to `crypto_aead_xchacha20poly1305_ietf_encrypt'
collect2: error: ld returned 1 exit status
make[2]: *** [ss-local] Error 1
make[2]: Leaving directory `/root/shadowsocks-libev/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/root/shadowsocks-libev'
make: *** [all] Error 2

**Comment by flipphos** [comment]
I tried under fresh Centos 7.3  1611, and followed the readme, and had the exact error message as the OP.

Any instruction is appreciated!

**Comment by oglops** [comment]
The error seems indicating it failed to find libsodium, maybe you can try explicitly setting the paths for it when executing configure.
```
--with-sodium=<your path> --with-mbedtls=<your path>
```

**Comment by WordlessEcho** [comment]
按照 README 中的编译也出现了此问题，当执行到 start building 那行时，替换为：
```--with-sodium-include=/usr/include --with-sodium-lib=/usr/local/lib --with-mbedtls-include=/usr/include --with-mbedtls-lib=/usr/lib```
通过

**Comment by itrump** [comment]
`# Start building
./autogen.sh && ./configure --with-sodium-include=/usr/include --with-sodium-lib=/usr/local/lib --with-mbedtls-include=/usr/include --with-mbedtls-lib=/usr/lib  && make
sudo make install`
It should solve the problem.
