### ISSUE TITLE
simple obfs permission error

### ISSUE THREAD

**Issue by simonsmh** [shadowsocks/shadowsocks-libev#1166]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
3.0.0

### What operating system are you using?
Debian stretch

### What did you do?
run

### What did you expect to see?
run properly

### What did you see instead?
● shadowsocks-libev.service - Shadowsocks-libev Default Server Service
   Loaded: loaded (/lib/systemd/system/shadowsocks-libev.service; enabled; vendor preset: enabled)
   Active: inactive (dead) since Thu 2017-02-02 14:14:01 CST; 2min 51s ago
     Docs: man:shadowsocks-libev(8)
  Process: 3270 ExecStart=/usr/bin/ss-server -c $CONFFILE $DAEMON_ARGS (code=exited, status=0/SUCCESS)
 Main PID: 3270 (code=exited, status=0/SUCCESS)

2月 02 14:14:01 simonsmh ss-server[3270]:  2017-02-02 14:14:01 INFO: initializing ciphers... chacha20-ietf-poly1305
2月 02 14:14:01 simonsmh ss-server[3270]:  2017-02-02 14:14:01 INFO: tcp port reuse enabled
2月 02 14:14:01 simonsmh ss-server[3270]:  2017-02-02 14:14:01 INFO: tcp server listening at 127.0.0.1:50179
2月 02 14:14:01 simonsmh ss-server[3270]:  2017-02-02 14:14:01 INFO: udp port reuse enabled
2月 02 14:14:01 simonsmh ss-server[3270]:  2017-02-02 14:14:01 INFO: udp server listening at [::]:112
2月 02 14:14:01 simonsmh ss-server[3270]:  2017-02-02 14:14:01 INFO: udp port reuse enabled
2月 02 14:14:01 simonsmh ss-server[3270]:  2017-02-02 14:14:01 INFO: udp server listening at 0.0.0.0:112
2月 02 14:14:01 simonsmh ss-server[3270]:  2017-02-02 14:14:01 [simple-obfs] INFO: obfuscating enabled
2月 02 14:14:01 simonsmh ss-server[3270]:  2017-02-02 14:14:01 [simple-obfs] INFO: tcp port reuse enabled
2月 02 14:14:01 simonsmh ss-server[3270]:  2017-02-02 14:14:01 [simple-obfs] ERROR: bind: Permission denied
~
~

### What is your config in detail (with all sensitive info masked)?
normal

**Comment by steveshi** [comment]
ss换个监听端口，我用443和80也会bind: Permission denied

**Comment by rogers0** [comment]
@simonsmh I guess you just need to:
```shell
setcap cap_net_bind_service+ep /path/to/your/simple-obfs
```
ss-* is done by postinst script (https://github.com/shadowsocks/shadowsocks-libev/blob/master/debian/shadowsocks-libev.postinst)
but simple-obfs hasn't been packaged, so you need to do it manually.

**Comment by simonsmh** [comment]
`setcap cap_net_bind_service+ep /usr/local/bin/obfs-server`
thx
