### ISSUE TITLE
Debian 8 编译出错

### ISSUE THREAD

**Issue by steveshi** [shadowsocks/shadowsocks-libev#1167]
#1160 Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
the latest3.0.0 form github

### What operating system are you using?
Debian 8 3.16.0-4-amd64
libsodium  1.0.11
mbedtls 2.4.0
### What did you do?
编译了最新版的mbedtls和libsodium
cd进shadowsocks-libev 目录 git submodule update --init --recursive
./autogen.sh后
dpkg-buildpackage -b -us -uc -i 出错

### What did you see instead?
/* confdefs.h */
#define PACKAGE_NAME "shadowsocks-libev"
#define PACKAGE_TARNAME "shadowsocks-libev"
#define PACKAGE_VERSION "3.0.0"
#define PACKAGE_STRING "shadowsocks-libev 3.0.0"
#define PACKAGE_BUGREPORT "max.c.lv@gmail.com"
#define PACKAGE_URL ""
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define __EXTENSIONS__ 1
#define _ALL_SOURCE 1
#define _GNU_SOURCE 1
#define _POSIX_PTHREAD_SEMANTICS 1
#define _TANDEM_SOURCE 1
#define PACKAGE "shadowsocks-libev"
#define VERSION "3.0.0"
#define HAVE_DLFCN_H 1
#define LT_OBJDIR ".libs/"
#define HAVE_PCRE_H 1
#define HAVE_LIBPCRE 1
#define TLS __thread

configure: exit 1
dh_auto_configure: ./configure --build=x86_64-linux-gnu --prefix=/usr --includedir=${prefix}/include --mandir=${prefix}/share/man -   -infodir=${prefix}/share/info --sysconfdir=/etc --localstatedir=/var --libdir=${prefix}/lib/x86_64-linux-gnu --libexecdir=${prefix}   /lib/x86_64-linux-gnu --disable-maintainer-mode --disable-dependency-tracking --enable-shared --disable-ssp returned exit code 1
debian/rules:17: recipe for target 'override_dh_auto_configure' failed
make[1]: *** [override_dh_auto_configure] Error 255
make[1]: Leaving directory '/tmp/shadowsocks-libev'
debian/rules:28: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2

**Comment by asmadeus08** [comment]
Your system must to be support latest version of libsodium

sudo apt-get install automake
git clone https://github.com/shadowsocks/shadowsocks-libev.git
cd shadowsocks-libev
git reset --hard origin/master
git pull
git submodule init && git submodule update
sudo apt-get install --no-install-recommends build-essential autoconf libtool libssl-dev \
gawk debhelper dh-systemd init-system-helpers pkg-config asciidoc xmlto apg libpcre3-dev zlib1g-dev \
libev-dev libudns-dev libsodium-dev
sudo apt-get install --no-install-recommends gettext build-essential autoconf libtool libpcre3-dev asciidoc xmlto libmbedtls-dev libev-dev libudns-dev libsodium-dev
./autogen.sh && dpkg-buildpackage -b -us -uc -i
cd ..
sudo dpkg -i shadowsocks-libev_3.0.0*.deb

**Comment by steveshi** [comment]
The libsodium is 1.0.11

**Comment by asmadeus08** [comment]
Then it ok. You can use what i gave to you. But i have port confclit cause upgrading to the new version over old one. This is my issue https://github.com/shadowsocks/shadowsocks-libev/issues/1162. But i think if try to install on clean system it will be work fine.

**Comment by triaqu** [comment]
我的debian8.0也出错。环境按readme安装了mbedTLS and libsodium，remove了老版，但总是错，请问如何解决呢。
/root/ss/shadowsocks-libev/src/aead.c:221: undefined reference to `crypto_aead_chacha20poly1305_ietf_encrypt'
ss_local-aead.o: In function `aead_chunk_encrypt':
/root/ss/shadowsocks-libev/src/aead.c:518: undefined reference to `sodium_increment'
/root/ss/shadowsocks-libev/src/aead.c:527: undefined reference to `sodium_increment'
ss_local-aead.o: In function `aead_chunk_decrypt':
/root/ss/shadowsocks-libev/src/aead.c:610: undefined reference to `sodium_increment'
/root/ss/shadowsocks-libev/src/aead.c:618: undefined reference to `sodium_increment'
ss_local-stream.o: In function `crypto_stream_xor_ic':
/root/ss/shadowsocks-libev/src/stream.c:141: undefined reference to `crypto_stream_chacha20_ietf_xor_ic'
collect2: error: ld returned 1 exit status
Makefile:652: recipe for target 'ss-local' failed
make[3]: *** [ss-local] Error 1
make[3]: Leaving directory '/root/ss/shadowsocks-libev/src'
Makefile:465: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/root/ss/shadowsocks-libev'
Makefile:373: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/root/ss/shadowsocks-libev'
dh_auto_build: make -j1 returned exit code 2
debian/rules:28: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2

**Comment by liyiecho** [comment]
@triaqu Remove the old libsodium (sudo apt-get remove libsodium-dev) and install the latest version from source.

**Comment by triaqu** [comment]
@liyiecho  thank you very much.

**Comment by cokebar** [comment]
@steveshi You may have compile mbedtls from source. By default, mbedTLS will not be compiled as a shared library. You should following this:
```
wget https://tls.mbed.org/download/mbedtls-$MBEDTLS_VER-gpl.tgz
tar xvf mbedtls-$MBEDTLS_VER-gpl.tgz
pushd mbedtls-$MBEDTLS_VER
export SHARED=1
make
sudo make install
popd
```
