### ISSUE TITLE
Consider shared libipset?

### ISSUE THREAD

**Issue by felixonmars** [shadowsocks/shadowsocks-libev#1168]
Currently libipset is forced to use shadowsocks/ipset, is it possible to use the shared lib when --enable-system-shared-lib is specified?

**Comment by madeye** [comment]
I'm OK with this. What about a pull request?

**Comment by Mygod** [comment]
+1. Seems like only Makefile is added in shadowsocks/ipset.

**Comment by felixonmars** [comment]
I am a bit confused where USE_SYSTEM_SHARED_LIB was used, as it seems system libs are mandatory from the code. I would start with a PR if this was clear to me :)

**Comment by madeye** [comment]
One thing to be careful about is the ipset we use in shadowsocks is not the ipset we usually know.

**Comment by rogers0** [comment]
@felixonmars when you make the PR, please keep in mind that ipset library is renamed to libcorkipset in Debian.
(because there's another ipset package already there)
- ss-libev need: https://tracker.debian.org/pkg/libcorkipset
- not relevant: https://tracker.debian.org/pkg/ipset

Thanks!

**Comment by felixonmars** [comment]
Wow that was fast... Thanks a lot!

**Comment by rogers0** [comment]
I still got error when compiling under Debian:

configure.ac:289: error: required file 'libcork/Makefile.in' not found
configure.ac:289: error: required file 'libipset/Makefile.in' not found
Makefile.am:4: error: required directory ./libcork does not exist
Makefile.am:4: error: required directory ./libipset does not exist

It seems it checks the existence of libcork&ipset folder, even no intention to use them.
Please help to fix if possible. Thank you!

**Comment by hosiet** [comment]
Looks hard to fix as long as `autoreconf` is to be run. The only solution (with no vendor libs) I have in mind currently is to patch those lines in `configure.ac` away.

**Comment by madeye** [comment]
Right, a patch is needed here.

**Comment by rogers0** [comment]
OK. So it's the 0001 patch here, I already rebase to match with v3.0.2:
- https://anonscm.debian.org/git/collab-maint/shadowsocks-libev.git/tree/debian/patches

How about 0002 patch? Can you add a conditional block to remove the patch?
Thanks!

**Comment by madeye** [comment]
I think there is already a conditional block:

```
AM_COND_IF([USE_SYSTEM_SHARED_LIB],
		   [],
		   [AC_CONFIG_FILES([libcork/Makefile libipset/Makefile])])
```

**Comment by rogers0** [comment]
I mean 0002 patch:
- https://anonscm.debian.org/git/collab-maint/shadowsocks-libev.git/tree/debian/patches/0002-use-libcorkipset-library-in-system.patch

the include folder name is different for src/acl.c

**Comment by madeye** [comment]
@rogers0 I see. Could you try 72f6041?

**Comment by rogers0** [comment]
@madeye thanks for your work!
It gets better than before, now patch 0002 can be removed.

**Comment by rogers0** [comment]
@madeye there's still something wrong. I'll try to fix it tomorrow.

**Comment by rogers0** [comment]
I enabled shared library by: --enable-shared
but still got the following config.h:

/* Define if use system shared lib. */
/* #undef USE_SYSTEM_SHARED_LIB */

**Comment by madeye** [comment]
@rogers0 I think the option should be `--enable-system-shared-lib`?

**Comment by rogers0** [comment]
@madeye oops. I didn't notice this change.
