### ISSUE TITLE
Youtube stop working after ss-libev 3.0

### ISSUE THREAD

**Issue by asmadeus08** [shadowsocks/shadowsocks-libev#1169]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
3.0.0

### What operating system are you using?
Ubuntu 16.10 linux kernel 10rc6

### What did you do?
Using ss-libev on my desktop with that https://github.com/shadowsocks/shadowsocks-windows/releases (note: auth - deleted)

### What did you expect to see?
Normal working for all sites

### What did you see instead?
Youtube and https sites doesnt work anymore, and after 5 minutes of working that's why i got on server:
18:42:26 ERROR: remote recv: Connection reset by peer

### What is your config in detail (with all sensitive info masked)?
{
    "server":"0.0.0.0",
    "server_port":995,
    "local_address":"127.0.0.1",
    "local_port":1080,
    "password":"****",
    "timeout":120,
    "method":"camellia-256-cfb"
}

**Comment by madeye** [comment]
Try the latest version.
