### ISSUE TITLE
Failed to build deb on Ubuntu 14.04

### ISSUE THREAD

**Issue by Mygod** [shadowsocks/shadowsocks-libev#1170]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?

3.0.0 (actually master)

### What operating system are you using?

Ubuntu 14.04.

### What did you do?

Build package.

### What did you expect to see?

Success.

### What did you see instead?

```
configure:13313: checking for mbedtls_cipher_setup in -lmbedcrypto
configure:13338: gcc -o conftest -g -O2 -fPIE -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now conftest.c -lmbedcrypto  -lpcre  >&5
/usr/bin/ld: //usr/local/lib/libmbedcrypto.a(cipher.o): relocation R_X86_64_32 against `mbedtls_cipher_supported' can not be used when making a shared object; recompile with -fPIC
//usr/local/lib/libmbedcrypto.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
configure:13338: $? = 1
```

However `make install` works.

### What is your config in detail (with all sensitive info masked)?

Not applicable.

**Comment by asmadeus08** [comment]
sudo apt-get install --no-install-recommends autoconf libtool asciidoc zlib1g-dev libssl-dev libpcre3 \
libpcre3-dev build-essential libpcre3 asciidoc libpcre3-dev zlib1g-dev libssl-dev automake libudns-dev \ 
libev-dev xmlto -y

then
sudo apt-get install automake
git clone https://github.com/shadowsocks/shadowsocks-libev.git
cd shadowsocks-libev
git reset --hard origin/master
git pull
git submodule init && git submodule update
sudo apt-get install --no-install-recommends build-essential autoconf libtool libssl-dev \
gawk debhelper dh-systemd init-system-helpers pkg-config asciidoc xmlto apg libpcre3-dev zlib1g-dev \
libev-dev libudns-dev libsodium-dev
sudo apt-get install --no-install-recommends gettext build-essential autoconf libtool libpcre3-dev asciidoc xmlto libmbedtls-dev libev-dev libudns-dev libsodium-dev
./autogen.sh && dpkg-buildpackage -b -us -uc -i
cd ..
sudo dpkg -i shadowsocks-libev*.deb

**Comment by hqvv** [comment]
same problem here.
```
install -m0755 /home/hq/lede/build_dir/target-mips_24kc_musl-1.1.16/shadowsocks-libev/openssl/shadowsocks-libev-20160202-2/src/ss-{local,redir,tunnel} /home/hq/lede/build_dir/target-mips_24kc_musl-1.1.16/shadowsocks-libev/openssl/shadowsocks-libev-20160202-2/ipkg-mips_24kc/shadowsocks-libev/usr/bin
find /home/hq/lede/build_dir/target-mips_24kc_musl-1.1.16/shadowsocks-libev/openssl/shadowsocks-libev-20160202-2/ipkg-mips_24kc/shadowsocks-libev -name 'CVS' -o -name '.svn' -o -name '.#*' -o -name '*~'| xargs -r rm -rf
Package shadowsocks-libev is missing dependencies for the following libraries:
libmbedcrypto.so.0
Makefile:75: recipe for target '/home/hq/lede/bin/packages/mips_24kc/base/shadowsocks-libev_20160202-2_mips_24kc.ipk' failed

```

**Comment by Mygod** [comment]
@hqvv That's obviously a different problem. You're missing libmbedcrypto.

**Comment by rogers0** [comment]
@Mygod I guess libsodium in ubuntu 14.04 is too old
- https://launchpad.net/ubuntu/+source/libsodium

**Comment by asmadeus08** [comment]
Yes that's it. Need to be ubuntu 16.10 with libsodium 1.0.10 at least

**Comment by zhfreal** [comment]
I have the same issue with the latest libsodium on ubuntu 14.04 and 16.04, configure and make succeed, but build deb package fail.  @rogers0 ,  It should  not due to the legacy libsodium

**Comment by epizza** [comment]
When build & install mbedTLS 2.4 on Ubuntu 16.04, Shadowsocks-libev deb fails to build also. But it's fine when I install mbedTLS 2.2 from repository.

**Comment by cokebar** [comment]
@epizza same problem with you.

**Comment by madeye** [comment]
When building mbedtls, try `env CFLAGS="-fPIC" make`

**Comment by Mygod** [comment]
That works.

**Comment by Mygod** [comment]
Might as well add this to README.
