### ISSUE TITLE
Confusing behavior when running two instances of ss-server listening on the same port

### ISSUE THREAD

**Issue by Mygod** [shadowsocks/shadowsocks-libev#1172]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?

3.0.0

### What operating system are you using?

Ubuntu 14.04.

### What did you do?

Accidentally started another ss-server with the exact same configuration.

### What did you expect to see?

The new started instance should probably terminate and give reasonable errors.

### What did you see instead?

It seems to be running fine, probably due to socks reuse. This results in confusing behavior:

1. A request sometimes being processed twice;
2. Random resets;
3. Efficiency decreases.

### What is your config in detail (with all sensitive info masked)?

Not applicable.

**Comment by madeye** [comment]
Maybe make port reuse optional? Currently, I enable it by default.

**Comment by Mygod** [comment]
Is port reuse supposed to work here?

**Comment by madeye** [comment]
Yes, it works on Linux kernel > 3.9, macOS and Windows NT.

**Comment by Mygod** [comment]
Hmm my kernel is 4.2.0-35 and this is the result.

**Comment by madeye** [comment]
Add the option via 7b290f3.
