### ISSUE TITLE
Automake should be added to build dependencies

### ISSUE THREAD

**Issue by t123yh** [shadowsocks/shadowsocks-libev#1174]
On Ubuntu 16.04.1, Automake is neither installed by default, nor mentioned in the build instructions.
```
$ ./autogen.sh
Can't exec "aclocal": No such file or directory at /usr/share/autoconf/Autom4te/FileUtils.pm line 326.
autoreconf: failed to run aclocal: No such file or directory

$ sudo apt install automake

$./autogen.sh
Everything goes fine here
```

So I doubt it should be added to the `apt-get install` list.

**Comment by t123yh** [comment]
And also `libssl-dev`.

**Comment by rogers0** [comment]
@t123yh it should be installed by dependency of debhelper or autoconf something.
Let me check.

**Comment by rogers0** [comment]
I think we should either bump to debhelper (>= 10), or add Build-Depends dh-autoreconf.
(debhelper => 10 already depends on dh-autoreconf)
For former, ubuntu 14.04 may don't have it. So maybe for the time being, later is better.

For libssl-dev, AFAIK the dependency is already dropped.

**Comment by hosiet** [comment]
I am against the idea of B-D on debhelper (>=10), which only exists on Debian 9 and Ubuntu 16.10+. This has no real benefit but will drive those who wish to build their own deb packages on Debian 8 and Ubuntu 16.04 or old systems crazy. B-D on dh-autoreconf is more reasonable.

**Comment by rogers0** [comment]
@hosiet FYI. actually debhelper is in jessie-backports / ubuntu 16.04.

**Comment by hosiet** [comment]
My thought is, you can't count on end users to enable backports repository and install it explicitly as a build dependency, unless that software itself is also in that backports repository. Doing that will only make things more complicated.

**Comment by Jieee006** [comment]
@rogers0 I just tried.libssl-dev was needed for dependency.Debian8 jessie.

**Comment by rogers0** [comment]
@hosiet now I added script&instruction for 14.04/16.04 user, so you won't be against bumping to debhelper 10, right?

**Comment by hosiet** [comment]
As long as we have build script, yes. Actually I do think compat version should be v10 in official packaging instructions. But if we want to keep upstream Debian dir identical with the Debian official one (which is not really necessary), we *can* go ahead and break compatibility with Ubuntu 16.04.

**Comment by rogers0** [comment]
@hosiet for ubuntu 16.04, there's debhelper 10.2 in its backports repo [0], so there's no breaking compatibility thing.

[0] https://launchpad.net/ubuntu/+source/debhelper

**Comment by hosiet** [comment]
As I said before, backports is not enabled by default in Ubuntu.

**Comment by rogers0** [comment]
@hosiet try the script, you will find debhelper 10 gets installed on 16.04, without changing anything under /etc/

**Comment by hosiet** [comment]
I am well aware of the new scripts. Manually enabling xenial-backports is always needed no matter the script is used or not.

**Comment by rogers0** [comment]
@hosiet FYI. jessie-backports is not enabled by default, however xenial-backports is *always* enabled, just in a lower Pin-Priority.

**Comment by hosiet** [comment]
Great. Sees that backports policy was changed since Ubuntu 11.10 and that makes sense.

**Comment by rogers0** [comment]
@hosiet though in my xenial environment there's xenial-backports on default install, maybe for older 16.04 system (16.04.0 ?), or some system upgraded from previous LTS, it's not enabled by default.
Because I see #1264
