### ISSUE TITLE
About 3.0 have doubts

### ISSUE THREAD

**Issue by xingezhang** [shadowsocks/shadowsocks-libev#1175]
3.0的更新不再依赖openssl，只需要mbedtls就可以了，但是移除OTA昰因为什么呢？
哪位有时间答疑解惑一下，谢谢了！

**Comment by madeye** [comment]
You can find more details here: https://github.com/shadowsocks/shadowsocks-org/issues/30

**Comment by Mygod** [comment]
In short, OTA provides weaker security than plain stream cipher.
