### ISSUE TITLE
[已解决]debian 8.7 x64从shadowsocks-libev-v2.6.3开始出现编译失败的提示

### ISSUE THREAD

**Issue by wukaisky** [shadowsocks/shadowsocks-libev#1176]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
shadowsocks-libev 3.0.0

### What operating system are you using?
DigitalOcean Debian 8.7 x64

### What did you do?
./autogen.sh && dpkg-buildpackage -b -us -uc -i

### What did you see instead?
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, `auto'.
libtoolize: copying file `auto/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: copying file `m4/libtool.m4'
libtoolize: copying file `m4/ltoptions.m4'
libtoolize: copying file `m4/ltsugar.m4'
libtoolize: copying file `m4/ltversion.m4'
libtoolize: copying file `m4/lt~obsolete.m4'
configure.ac:289: error: required file 'libcork/Makefile.in' not found
configure.ac:289: error: required file 'libipset/Makefile.in' not found
autoreconf: automake failed with exit status: 1

**Comment by haodong** [comment]
`git submodule update --init --recursive`

**Comment by asmadeus08** [comment]
sudo apt-get install automake
git clone https://github.com/shadowsocks/shadowsocks-libev.git
cd shadowsocks-libev
git reset --hard origin/master
git pull
git submodule init && git submodule update
sudo apt-get install --no-install-recommends build-essential autoconf libtool libssl-dev \
gawk debhelper dh-systemd init-system-helpers pkg-config asciidoc xmlto apg libpcre3-dev zlib1g-dev \
libev-dev libudns-dev libsodium-dev
sudo apt-get install --no-install-recommends gettext build-essential autoconf libtool libpcre3-dev asciidoc xmlto libmbedtls-dev libev-dev libudns-dev libsodium-dev
./autogen.sh && dpkg-buildpackage -b -us -uc -i
cd ..
sudo dpkg -i shadowsocks-libev*.deb

**Comment by wukaisky** [comment]
make[3]: Entering directory '/root/shadowsocks-libev/src'
  CC       libshadowsocks_libev_la-utils.lo
  CC       libshadowsocks_libev_la-jconf.lo
  CC       libshadowsocks_libev_la-json.lo
  CC       libshadowsocks_libev_la-udprelay.lo
  CC       libshadowsocks_libev_la-cache.lo
  CC       libshadowsocks_libev_la-acl.lo
  CC       libshadowsocks_libev_la-netutils.lo
  CC       libshadowsocks_libev_la-local.lo
  CC       libshadowsocks_libev_la-crypto.lo
  CC       libshadowsocks_libev_la-aead.lo
  CC       libshadowsocks_libev_la-stream.lo
  CC       libshadowsocks_libev_la-plugin.lo
  CC       libshadowsocks_libev_la-http.lo
  CC       libshadowsocks_libev_la-tls.lo
  CC       libshadowsocks_libev_la-rule.lo
  CCLD     libshadowsocks-libev.la
  CC       ss_local-utils.o
  CC       ss_local-jconf.o
  CC       ss_local-json.o
  CC       ss_local-udprelay.o
  CC       ss_local-cache.o
  CC       ss_local-acl.o
  CC       ss_local-netutils.o
  CC       ss_local-local.o
  CC       ss_local-crypto.o
  CC       ss_local-aead.o
  CC       ss_local-stream.o
  CC       ss_local-plugin.o
  CC       ss_local-http.o
  CC       ss_local-tls.o
  CC       ss_local-rule.o
  CCLD     ss-local
ss_local-crypto.o: In function `crypto_derive_key':
/root/shadowsocks-libev/src/crypto.c:112: undefined reference to `crypto_pwhash'
ss_local-aead.o: In function `cipher_aead_decrypt':
/root/shadowsocks-libev/src/aead.c:268: undefined reference to `crypto_aead_chacha20poly1305_ietf_decrypt'
ss_local-aead.o: In function `cipher_aead_encrypt':
/root/shadowsocks-libev/src/aead.c:221: undefined reference to `crypto_aead_chacha20poly1305_ietf_encrypt'
ss_local-aead.o: In function `aead_chunk_encrypt':
/root/shadowsocks-libev/src/aead.c:516: undefined reference to `sodium_increment'
/root/shadowsocks-libev/src/aead.c:525: undefined reference to `sodium_increment'
ss_local-aead.o: In function `aead_chunk_decrypt':
/root/shadowsocks-libev/src/aead.c:608: undefined reference to `sodium_increment'
/root/shadowsocks-libev/src/aead.c:616: undefined reference to `sodium_increment'
ss_local-stream.o: In function `crypto_stream_xor_ic':
/root/shadowsocks-libev/src/stream.c:141: undefined reference to `crypto_stream_chacha20_ietf_xor_ic'
collect2: error: ld returned 1 exit status
Makefile:657: recipe for target 'ss-local' failed
make[3]: *** [ss-local] Error 1
make[3]: Leaving directory '/root/shadowsocks-libev/src'
Makefile:467: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/root/shadowsocks-libev'
Makefile:375: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/root/shadowsocks-libev'
dh_auto_build: make -j1 returned exit code 2
debian/rules:28: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2
root@debian-512mb-sfo2-01:~/shadowsocks-libev#

**Comment by wukaisky** [comment]
找到原因了：
Deiban 8.7 x64自带的libsodium too old，需要先apt-get remove libsodium-dev卸载旧包。
and install the latest version from source.

**Comment by kimw** [comment]
@wukaisky How about close this issue?

**Comment by rogers0** [comment]
@wukaisky your problem will be solved when below pkg get thru NEW queue:
- https://ftp-master.debian.org/new/libsodium_1.0.11-1~bpo8+1.html

I still don't like install anything by "make install".
