### ISSUE TITLE
[已解决]cygwin 无法编译

### ISSUE THREAD

**Issue by wxyzh** [shadowsocks/shadowsocks-libev#1178]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
a906d0cfc81750c55a9ef432e8af4fe0228f6948

### What operating system are you using?
windows 10 pro x64 & babun

### What did you do?
Get the latest source code
Build and install the latest mbedTLS and libsodium

``` 
cd shadowsocks-libev
./autogen.sh
./configure --disable-documentation --with-mbedtls-include=$home/mbedtls-2.4.0/include --with-mbedtls-lib=$home/mbedtls-2.4.0/library
make -j
```
### What did you expect to see?
build pass

### What did you see instead?
```
.......
......
  CC       src/libcork/posix/libcork_la-process.lo
src/libcork/posix/process.c: In function ‘cork_cleanup_at_exit_named’:
src/libcork/posix/process.c:116:1: warning: visibility attribute not supported in this configuration; ignored [-Wattributes]
 }
 ^
  CC       src/libcork/posix/libcork_la-subprocess.lo
src/libcork/posix/subprocess.c:504:2: error: #error "Unknown thread yield implementation"
 #error "Unknown thread yield implementation"
  ^
Makefile:717: recipe for target 'src/libcork/posix/libcork_la-subprocess.lo' failed
make[2]: *** [src/libcork/posix/libcork_la-subprocess.lo] Error 1
make[2]: Leaving directory '$home/shadowsocks-libev/libcork'
Makefile:468: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '$home/shadowsocks-libev'
Makefile:376: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by wxyzh** [comment]
已经编译成功，但是运行速度太慢，数据传输速度大概只有不到2MB/s

**Comment by testcaoy7** [comment]
@wxyzh 怎么编译的，是编译的git版本还是release 3.0

**Comment by Springchendg** [comment]
@wxyzh 遇到同样的错误，请问怎样才能成功编译？

**Comment by wxyzh** [comment]
修改 libcork的代码
在以下两个位置最后添加|| defined(__CYGWIN__) 
libcork\src\libcork\posix\subprocess.c 500行
libcork\src\libcork\posix\env.c 186行

**Comment by madeye** [comment]
Please  try ce0d6d4

**Comment by testcaoy7** [comment]
@madeye 项目主页的Windows部分不见了，不知道现在babun该怎么编译，libsodium和mbedtls不在submodule里，该怎么处理呢

**Comment by testcaoy7** [comment]
我运行./autogen.sh 得到：

configure.ac:19: error: possibly undefined macro: AC_DISABLE_STATIC
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:20: error: possibly undefined macro: AC_DISABLE_SHARED
configure.ac:62: error: possibly undefined macro: AC_PROG_LIBTOOL
autoreconf-2.69: /usr/bin/autoconf-2.69 failed with exit status: 1

**Comment by testcaoy7** [comment]
解决了，udns在babun下没有包还要还要另外下源码编译……

**Comment by wxyzh** [comment]
@testcaoy7
确实，我自己编译了libudns，libsodium，mbedtls
@madeye  可以关闭issue了

**Comment by cokebar** [comment]
@wxyzh 求助编译步骤 感谢！
话说mbedtls可以从VS编译 不知道和GCC编译出来的会不会速度有差别

**Comment by wxyzh** [comment]
@cokebar ，和linux下编译一样，cygwin没有libudns，libsodium，mbedtls的包，需要自己编译。

**Comment by kimw** [comment]
@wxyzh If this issue was solved, maybe you wish to close it.

**Comment by cokebar** [comment]
@wxyzh 3.0可以用mingw编译么

**Comment by testcaoy7** [comment]
@cokebar 我记得mingw好像已经被drop support了吧

**Comment by cokebar** [comment]
@madeye I still got same error with latest src.
cygwin x86 on WIN7 pro x86

**Comment by cokebar** [comment]
@madeye Sorry, I made a mistake. I got same error when I'm building simple-obfs. You should merge this change into simple-obfs also.

**Comment by cokebar** [comment]
@wxyzh 感谢！我已经编译成功了。另：libsodium官方网站上有与编译好的dll，有vs编译的版本也有mingw编译的版本，直接用就行了，省好长时间。
