### ISSUE TITLE
编译3.0源码时报错

### ISSUE THREAD

**Issue by Eintler** [shadowsocks/shadowsocks-libev#1185]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
3.0

### What operating system are you using?
Ubuntu 16.04 x86_64

log

crypto.c: In function 'crypto_derive_key':
crypto.c:108:34: error: 'crypto_pwhash_SALTBYTES' undeclared (first use in this function)
         const unsigned char salt[crypto_pwhash_SALTBYTES] = {
                                  ^
crypto.c:108:34: note: each undeclared identifier is reported only once for each function it appears in
crypto.c:112:19: error: implicit declaration of function 'crypto_pwhash' [-Werror=implicit-function-declaration]
         int err = crypto_pwhash (key, nkey, (char*)pass, strlen(pass), salt,
                   ^
crypto.c:113:17: error: 'crypto_pwhash_OPSLIMIT_INTERACTIVE' undeclared (first use in this function)
                 crypto_pwhash_OPSLIMIT_INTERACTIVE, crypto_pwhash_MEMLIMIT_INTERACTIVE,
                 ^
crypto.c:113:53: error: 'crypto_pwhash_MEMLIMIT_INTERACTIVE' undeclared (first use in this function)
                 crypto_pwhash_OPSLIMIT_INTERACTIVE, crypto_pwhash_MEMLIMIT_INTERACTIVE,
                                                     ^
crypto.c:114:17: error: 'crypto_pwhash_ALG_DEFAULT' undeclared (first use in this function)
                 crypto_pwhash_ALG_DEFAULT);
                 ^
crypto.c:108:29: error: unused variable 'salt' [-Werror=unused-variable]
         const unsigned char salt[crypto_pwhash_SALTBYTES] = {
                             ^
cc1: all warnings being treated as errors
Makefile:890: recipe for target 'libshadowsocks_libev_la-crypto.lo' failed
make[3]: *** [libshadowsocks_libev_la-crypto.lo] Error 1
make[3]: Leaving directory '/root/shadowsocks-libev/src'
Makefile:479: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/root/shadowsocks-libev'
Makefile:388: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/root/shadowsocks-libev'
dh_auto_build: make -j1 returned exit code 2
debian/rules:28: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2

**Comment by xc2** [comment]
A newer version of `libsodium` is required.

**Comment by Eintler** [comment]
I install the version of LIBSODIUM_VER is 1.0.11,it is the latest as the instruction in home page. @xc2

**Comment by xc2** [comment]
@Eintler If you compiled the libsodium from source AND THEN followed the instruction of **Build deb package from source**, you may have installed a legacy version of `libsodium-dev` which will override files you compiled and installed before.

Just try:

- Remove packages: `libsodium18` and `libsodium-dev`
- Compile and install libsodium of version 1.0.11 into `/usr` again as you did before
- Then dpkg-buildpackage agian

**Comment by time-river** [comment]
`Ubuntu`
`libsodium`
[here](https://mirrors.tuna.tsinghua.edu.cn/ubuntu/pool/main/libs/libsodium/)
If you don't want to compile yourself, download it from here, the newest.
`mbedtls`
[here](https://mirrors.tuna.tsinghua.edu.cn/ubuntu/pool/universe/m/mbedtls/)

`Debian`
[libsodium](https://mirrors.tuna.tsinghua.edu.cn/debian/pool/main/libs/libsodium/)
[mbedtls](https://mirrors.tuna.tsinghua.edu.cn/debian/pool/main/m/mbedtls/)

**Comment by Eintler** [comment]
Thanks @xc2 @time-river

**Comment by kimw** [comment]
@Eintler Should this issue closed?
