### ISSUE TITLE
ss-server runs couples hours then stops

### ISSUE THREAD

**Issue by Jieee006** [shadowsocks/shadowsocks-libev#1189]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?

3.0
### What operating system are you using?
Debian8 

### What did you do?

start shadowsocks-libev
### What did you expect to see?

not stop
### What did you see instead?
ss-server runs couples hours then stops.

Feb 04 10:01:20 localhost ss-server[383]: 2017-02-04 10:01:20 ERROR: server recv: Bad address
Feb 04 10:21:23 localhost ss-server[383]: 2017-02-04 10:21:23 ERROR: server recv: Bad address
Feb 04 10:47:16 localhost ss-server[383]: 2017-02-04 10:47:16 ERROR: server recv: Bad address
Feb 04 10:51:21 localhost ss-server[383]: 2017-02-04 10:51:21 ERROR: server recv: Bad address
Feb 04 11:21:08 localhost ss-server[383]: 2017-02-04 11:21:08 ERROR: server recv: Bad address
Feb 04 12:02:07 localhost ss-server[383]: 2017-02-04 12:02:07 ERROR: failed to handshake with xx.xx.xx.xx: invalid address type
Feb 04 12:02:07 localhost ss-server[383]: 2017-02-04 12:02:07 ERROR: failed to handshake with xx.xx.xx.xx: invalid host name length
Feb 04 12:02:08 localhost ss-server[383]: 2017-02-04 12:02:08 ERROR: failed to handshake with xx.xx.xx.xx: invalid address type
Feb 04 12:02:08 localhost systemd[1]: shadowsocks-libev.service: main process exited, code=exited, status=1/FAILURE
Feb 04 12:02:08 localhost systemd[1]: Unit shadowsocks-libev.service entered failed state.

### What is your config in detail (with all sensitive info masked)?
{
    "server":"0.0.0.0",
    "server_port":443,
    "local_port":1080,
    "password":"xxxx",
    "timeout":600,
    "method":"chacha20"
}

**Comment by kimw** [comment]
It looks some kind like #1188

**Comment by Jieee006** [comment]
@kimw according to your description #1188. actually,there is no this issue in other servers of mine.Weird.

**Comment by madeye** [comment]
Please try this commit: 6892951

**Comment by kimw** [comment]
@Jieee006 6892951 is work for me. how's about you?

**Comment by Jieee006** [comment]
also works for me.it seems that the issue's been resolved.

**Comment by kimw** [comment]
Great!

I'm going to close my issue.

**Comment by yyjazsf** [comment]
@madeye hello,when I exec ./configure  `6892951`,it has an error `configure: error: Wrong libsodium: version >= 1.0.9 required`,cloud you help me?
