### ISSUE TITLE
ss-redir terminated on run in UDP mode

### ISSUE THREAD

**Issue by kimw** [shadowsocks/shadowsocks-libev#1194]
### What version of shadowsocks-libev are you using?

894eae5 (v3.0.0-dev)

### What operating system are you using?

elementary OS Loki based on Ubuntu Xenial

```
No LSB modules are available.
Distributor ID:	elementary
Description:	elementary OS 0.4 Loki
Release:	0.4
Codename:	loki
```

### What wrong?

`ss-redir` reports *IP_TRANSPARENT: Operation not permitted* on run in UDP mode.

```bash
$ ss-redir -s 1.2.3.4 -p 5678 -k passphrase -l 1081 -u
INFO: initializing ciphers... aes-256-cfb
INFO: UDP relay enabled
ERROR: [udp] setsockopt IP_TRANSPARENT: Operation not permitted
```

It works fine without UDP.

```bash
$ ss-redir -s 1.2.3.4 -p 5678 -k passphrase -l 1081
INFO: initializing ciphers... rc4-md5
INFO: listening at 127.0.0.1:1081
```

PS, the tag:v3.0.0 runs well, but the recent commit not.

**Comment by madeye** [comment]
You need to run ss-redir in root user when UDP transparent proxy is enabled.

**Comment by kimw** [comment]
Yes I see. But why there's no nessesery to run as root in previous commit? Is there  anything  changed in design ?

**Comment by madeye** [comment]
I think all the previous versions of ss-redir requires ROOT permission to work in TPROXY mode. Maybe you need double check.

**Comment by kimw** [comment]
I've checkout the tag v3.0.0 from repo, and build and run. It's work.

```
git checkout tags/v3.0.0 -b v300
git reset --hard
git submodule update
./autoconf.sh
./configure
make
src/ss-redir...
```

**Comment by kimw** [comment]
Yap, you're right. It's my bad. :(

**Comment by wongsyrone** [comment]
科普一下
是yup,yea和yep,等于yes
不是yap（n.狂吠声；废话；笨蛋vt.瞎讲vi.狂吠；哇啦哇啦地瞎说）和ya.

**Comment by kimw** [comment]
@wongsyrone I spelled *yep* first, but the auto-correction tip me that it's wrong...so I tried *yap*...the tip disappeared and joke made :D

Anyway, thank you very much for point it out. I learned 4 more words, yup, yea, yap and ya. lol.

**Comment by wongsyrone** [comment]
因为这些都是过于口语化的说法，如果是面向书面语的自动纠正很可能没有词库支持，于是告诉你是错的。
