### ISSUE TITLE
libsodium conflict, source built vs ubuntu official package repository

### ISSUE THREAD

**Issue by kimw** [shadowsocks/shadowsocks-libev#1196]
### What version of shadowsocks-libev are you using?

bf14944 (v3.0.0 dev)

### What operating system are you using?

Ubuntu Xenial based desktop

### What's the problem?

The `libsodium18` will be automatically installed from Ubuntu official repository because of an APP `ffmpeg`. Even if I installed `libsodium` from source code following the instruction in README, the `ss-server` will not work in crypt `chacha20-ietf-poly1305`. It stopped as follow,

```bash
$ ss-local -s 1.2.3.4 -p 5678 -b :: -l 1080 -k passphrase -m chacha20-ietf-poly1305 -v
INFO: initializing ciphers... chacha20-ietf-poly1305
ss-local: symbol lookup error: ss-local: undefined symbol: crypto_pwhash
```

Keep the libsodium built from source, but remove `libsodium18` as command `sudo apt autoremove --purge ffmpeg`, it works.

How can I get out of this conflict?

**Comment by kimw** [comment]
Additionally, the conflict will issue on previous crypt, e.g. aes-128-cfb.

**Comment by wxyzh** [comment]
```
export LIBSODIUM_VER=1.0.11
export MBEDTLS_VER=2.4.0
wget https://download.libsodium.org/libsodium/releases/libsodium-$LIBSODIUM_VER.tar.gz
tar xvf libsodium-$LIBSODIUM_VER.tar.gz
pushd libsodium-$LIBSODIUM_VER
./configure --prefix=/usr && make
sudo make install
popd
wget https://tls.mbed.org/download/mbedtls-$MBEDTLS_VER-gpl.tgz
tar xvf mbedtls-$MBEDTLS_VER-gpl.tgz
pushd mbedtls-$MBEDTLS_VER
make SHARED=1 CFLAGS=-fPIC
sudo make install
popd
```
cd to shadowsocks-libev 
```
./autogen.sh
./configure --disable-documentation --with-mbedtls=$HOME/mbedtls-2.4.0 --with-sodium-lib=$HOME/libsodium/src/libsodium --with-sodium-include=$HOME/libsodium/src/libsodium
make 
make install
```

**Comment by kimw** [comment]
It's work. Great thanks.
