### ISSUE TITLE
Can't start the shadowsocks-libev service

### ISSUE THREAD

**Issue by GitHubUi** [shadowsocks/shadowsocks-libev#1197]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
3.0.0

### What operating system are you using?
Debian 8.7

### What did you do?
installed latest mbedTLS and libsodium

### What did you expect to see?
can't start the shadowsocks-libev service

### What did you see instead?
log:
Process: 467 ExecStart=/usr/bin/ss-server -c $CONFFILE $DAEMON_ARGS (code=exited, status=127)
Feb 05 06:01:20 material systemd[1]: Started Shadowsocks-libev Default Server Service.
Feb 05 06:01:21 material ss-server[467]: /usr/bin/ss-server: error while loading shared libraries: libmbedcrypto.so.0: ...ectory
Feb 05 06:01:21 material systemd[1]: shadowsocks-libev.service: main process exited, code=exited, status=127/n/a
Feb 05 06:01:21 material systemd[1]: Unit shadowsocks-libev.service entered failed state.

### What is your config in detail (with all sensitive info masked)?
{
    "server":"0.0.0.0",
    "server_port":"8388",
    "local_address":"127.0.0.1",
    "local_port":"1080",
    "password":"isisisisiisis",
    "timeout":"600",
    "method":"chacha20",
    "plugin":"obfs-server",
    "plugin_opts":"obfs=http"
}

**Comment by kimw** [comment]
Try start ss in cli as `ss-server -c /etc/shadowsocks-libev/config.json`, and post the output here.

**Comment by cokebar** [comment]
Have you install libsodium & libmbedtls in /usr? or /usr/local?
By default, they all install in /usr/local.
You have two options:
1. Install them in /usr:
libsodium: `./configure --prifix=/usr`
libmbedtls: `make DESTDIR=/usr install`
2. Install them in /usr/local, meanwhile let system search library files in /usr/local:
```
echo /usr/local/lib > /etc/ld.so.conf.d/usr_local_lib.conf
ldconfig
```

**Comment by muronghan** [comment]
@cokebar now you are talking! I checked libsodium was under /usr/lib very well but libmbedtls not. I manually cp libmbedtls files from /usr/local/lib to /usr/local and now everything is OL.

So the readme must be modified. My OS is Ubuntu 16.04
