### ISSUE TITLE
Compiling looks fine but ss-server can not be connected

### ISSUE THREAD

**Issue by muronghan** [shadowsocks/shadowsocks-libev#1199]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
3.0.0.0 d87dc1d  

### What operating system are you using?
Ubuntu Server 16.04

### What did you do?
compiled ss successfully according to the instruction and ss-server started successfully.

### What did you expect to see?
compiled ss successfully according to the instruction and ss-server started successfully.

### What did you see instead?
compiled ss successfully according to the instruction and ss-server started successfully.

### What is your config in detail (with all sensitive info masked)?
{
    "server":"0.0.0.0",
    "server_port":5190,
    "local_port":1080,
    "password":"xxxxxxxx",
    "timeout":60,
    "method":"chacha20"
}

==============
I compiled 3.0.0.0 of yesterday's version and everything went fine.
I compiled this version today and everything went fine, incl. the ss-server run up smoothly. However, I could not access google.com and other sites as well. I did this on two different VPS and re-created this issue twice.

I also tired the client on openwrt, on windows and on android. No luck so far so probably it's the server issue. Meantime, my yesterday's build on another VPS is solid.

**Comment by muronghan** [comment]
Then I run "service shadowsocks-libev status", it appeared:

lines 1-11/11 (END)...skipping...
● shadowsocks-libev.service - Shadowsocks-libev Default Server Service
   Loaded: loaded (/lib/systemd/system/shadowsocks-libev.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2017-02-05 20:08:01 CST; 7min ago
     Docs: man:shadowsocks-libev(8)
  Process: 27221 ExecStart=/usr/bin/ss-server -c $CONFFILE $DAEMON_ARGS (code=exited, status=127)
 Main PID: 27221 (code=exited, status=127)

Feb 05 20:08:01 myvienna systemd[1]: Started Shadowsocks-libev Default Server Service.
Feb 05 20:08:01 myvienna systemd[1]: shadowsocks-libev.service: Main process exited, code=exited, status=127/n/a
Feb 05 20:08:01 myvienna systemd[1]: shadowsocks-libev.service: Unit entered failed state.
Feb 05 20:08:01 myvienna systemd[1]: shadowsocks-libev.service: Failed with result 'exit-code'.

**Comment by muronghan** [comment]
It should be:

.....
● shadowsocks-libev.service - Shadowsocks-libev Default Server Service
   Loaded: loaded (/lib/systemd/system/shadowsocks-libev.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2017-02-05 09:48:03 CST; 10h ago
     Docs: man:shadowsocks-libev(8)
 Main PID: 9719 (ss-server)
   CGroup: /system.slice/shadowsocks-libev.service
           └─9719 /usr/bin/ss-server -c /etc/shadowsocks-libev/config.json -u
.......

So something goes wrong?

**Comment by kimw** [comment]
How about post your log here?

**Comment by cokebar** [comment]
Maybe you have same problem with #1197

**Comment by muronghan** [comment]
@cokebar now you are talking! I checked libsodium was under /usr/lib very well but libmbedtls not. I manually cp libmbedtls files from /usr/local/lib to /usr/local and now everything is OL.

So the readme must be modified. My OS is Ubuntu 16.04

**Comment by muronghan** [comment]
I saw the readme was update. Hence close ths thread
