### ISSUE TITLE
Build deb on Ubuntu 14.04.5 LTS failed

### ISSUE THREAD

**Issue by debiansid** [shadowsocks/shadowsocks-libev#1200]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
https://github.com/shadowsocks/shadowsocks-libev/commit/d87dc1d642bd33c3a1bd6602b2f07fe5202190a3

### What operating system are you using?
Ubuntu 14.04.5 LTS 

### What did you do?
cd shadowsocks-libev
sudo apt-get install --no-install-recommends gettext build-essential autoconf automake libtool \
    gawk debhelper dh-systemd init-system-helpers pkg-config asciidoc xmlto apg libpcre3-dev \
    libev-dev libudns-dev dh-autoreconf
./autogen.sh && dpkg-buildpackage -b -us -uc -i

### What did you expect to see?
deb built successfully 

### What did you see instead?
configure: exit 1
dh_auto_configure: ./configure --build=x86_64-linux-gnu --prefix=/usr --includedir=${prefix}/include --mandir=${prefix}/share/man --infodir=${prefix}/share/info --sysconfdir=/etc --localstatedir=/var --libdir=${prefix}/lib/x86_64-linux-gnu --libexecdir=${prefix}/lib/x86_64-linux-gnu --disable-maintainer-mode --disable-dependency-tracking --enable-shared --disable-ssp returned exit code 1
make[1]: *** [override_dh_auto_configure] Error 255
make[1]: Leaving directory `/home/storage/shadowsocks-libev'
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2

### What is your config in detail (with all sensitive info masked)?

**Comment by wujysh** [comment]
need more logs
Perhaps, `libsodium` or `libmbedtls` can not be found.

**Comment by debiansid** [comment]
configure: error: mbed TLS libraries not found.

**Comment by wujysh** [comment]
On Ubuntu 14.04, you should compile the `libsodium` and `mbedtls` from source manually.

# Build and install the latest mbedTLS and libsodium
```
export LIBSODIUM_VER=1.0.11
export MBEDTLS_VER=2.4.0
wget https://download.libsodium.org/libsodium/releases/libsodium-$LIBSODIUM_VER.tar.gz
tar xvf libsodium-$LIBSODIUM_VER.tar.gz
pushd libsodium-$LIBSODIUM_VER
./configure --prefix=/usr && make
sudo make install
popd
wget https://tls.mbed.org/download/mbedtls-$MBEDTLS_VER-gpl.tgz
tar xvf mbedtls-$MBEDTLS_VER-gpl.tgz
pushd mbedtls-$MBEDTLS_VER
make SHARED=1 CFLAGS=-fPIC
sudo make install
popd
```

**Comment by debiansid** [comment]
Yep , after install mbedtls I can build deb. So I have to install mbedtls and libsodium on target as well.
