### ISSUE TITLE
Please append '-w' to iptable for waiting for the rule table lock

### ISSUE THREAD

**Issue by enihcam** [shadowsocks/shadowsocks-libev#1202]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
3.0.0

### What operating system are you using?
Archlinux

### What did you do?
shadowsocks-libev.service and miniupnpd.service start in parallel, where both of them try to access the rule table of iptables.

### What did you expect to see?
Both services start successfully.

### What did you see instead?
Accesses to the iptables rule table conflict

### What is your config in detail (with all sensitive info masked)?

I already filed a bug to miniupnp project at: https://github.com/miniupnp/miniupnp/issues/232
Same fix has to be applied to shadowsocks-libev project as well.

**Comment by madeye** [comment]
Try updating to the latest shadowsocks. The latest shadowsocks won't touch your iptables rules.
