### ISSUE TITLE
configure: error: Can not find pthreads.  This is required.

### ISSUE THREAD

**Issue by qq57240** [shadowsocks/shadowsocks-libev#1209]
### What version of shadowsocks-libev are you using?
3.0

### What operating system are you using?
ubuntu16.04
miwifi firmware(linux kenerl 2.6)

### What did you do?
wget https://github.com/shadowsocks/shadowsocks-libev/releases/download/v3.0.0/shadowsocks-libev-3.0.0.tar.gz
tar xf shadowsocks-libev-3.0.0.tar.gz
cd shadowsocks-libev-3.0.0
git submodule update --init --recursive
./autogen.sh
./configure -prefix /home/jiajia/mipsel/shadowsocks --host=mipsel-openwrt-linux-uclibc --with-pcre=/home/jiajia/mipsel/pcre --with-mbedtls=/home/jiajia/mipsel/mbedtls --with-sodium=/home/jiajia/mipsel/libsodium --disable-documentation --disable-ssp

### What did you expect to see?
comiled succesful!

### What did you see instead?
jiajia@CloudServer:~/mipsel/shadowsocks-libev$ ./configure -prefix /home/jiajia/mipsel/shadowsocks --host=mipsel-openwrt-linux-uclibc --with-pcre=/home/jiajia/mipsel/pcre --with-mbedtls=/home/jiajia/mipsel/mbedtls --with-sodium=/home/jiajia/mipsel/libsodium --disable-ssp --disable-documentation
checking for mipsel-openwrt-linux-uclibc-gcc... mipsel-openwrt-linux-gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... yes
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether mipsel-openwrt-linux-gcc accepts -g... yes
checking for mipsel-openwrt-linux-gcc option to accept ISO C89... none needed
checking whether mipsel-openwrt-linux-gcc understands -c and -o together... yes
checking how to run the C preprocessor... mipsel-openwrt-linux-gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for mipsel-openwrt-linux-uclibc-strip... mipsel-openwrt-linux-uclibc-strip
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking for style of include used by make... GNU
checking whether make supports nested variables... yes
checking dependency style of mipsel-openwrt-linux-gcc... gcc3
checking for mipsel-openwrt-linux-uclibc-ar... mipsel-openwrt-linux-ar
checking the archiver (mipsel-openwrt-linux-ar) interface... ar
checking whether make supports nested variables... (cached) yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking build system type... x86_64-pc-linux-uclibc
checking host system type... mipsel-openwrt-linux-uclibc
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for fgrep... /bin/grep -F
checking for ld used by mipsel-openwrt-linux-gcc... mipsel-openwrt-linux-ld
checking if the linker (mipsel-openwrt-linux-ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... mipsel-openwrt-linux-nm
checking the name lister (mipsel-openwrt-linux-nm) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-uclibc file names to mipsel-openwrt-linux-uclibc format... func_convert_file_noop
checking how to convert x86_64-pc-linux-uclibc file names to toolchain format... func_convert_file_noop
checking for mipsel-openwrt-linux-ld option to reload object files... -r
checking for mipsel-openwrt-linux-uclibc-objdump... mipsel-openwrt-linux-uclibc-objdump
checking how to recognize dependent libraries... pass_all
checking for mipsel-openwrt-linux-uclibc-dlltool... no
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for mipsel-openwrt-linux-uclibc-ar... (cached) mipsel-openwrt-linux-ar
checking for archiver @FILE support... @
checking for mipsel-openwrt-linux-uclibc-strip... (cached) mipsel-openwrt-linux-uclibc-strip
checking for mipsel-openwrt-linux-uclibc-ranlib... mipsel-openwrt-linux-ranlib
checking command to parse mipsel-openwrt-linux-nm output from mipsel-openwrt-linux-gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mipsel-openwrt-linux-uclibc-mt... no
checking for mt... mt
configure: WARNING: using cross tools not prefixed with host triplet
checking if mt is a manifest tool... no
checking for dlfcn.h... yes
checking for objdir... .libs
checking if mipsel-openwrt-linux-gcc supports -fno-rtti -fno-exceptions... no
checking for mipsel-openwrt-linux-gcc option to produce PIC... -fPIC -DPIC
checking if mipsel-openwrt-linux-gcc PIC flag -fPIC -DPIC works... yes
checking if mipsel-openwrt-linux-gcc static flag -static works... yes
checking if mipsel-openwrt-linux-gcc supports -c -o file.o... yes
checking if mipsel-openwrt-linux-gcc supports -c -o file.o... (cached) yes
checking whether the mipsel-openwrt-linux-gcc linker (mipsel-openwrt-linux-ld) supports shared libraries... yes
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking for shl_load... no
checking for shl_load in -ldld... no
checking for dlopen... no
checking for dlopen in -ldl... yes
checking whether a program can dlopen itself... cross
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... no
checking whether to build static libraries... yes
checking checking for pcre includes in /home/jiajia/mipsel/pcre... checking for pcre headers in /home/jiajia/mipsel/pcre/include... ok
configure: adding /home/jiajia/mipsel/pcre/lib to RPATH
checking for library containing pcre_exec... -lpcre
checking pcre.h usability... yes
checking pcre.h presence... no
configure: WARNING: pcre.h: accepted by the compiler, rejected by the preprocessor!
configure: WARNING: pcre.h: proceeding with the compiler's result
checking for pcre.h... yes
checking pcre/pcre.h usability... no
checking pcre/pcre.h presence... no
checking for pcre/pcre.h... no
checking for mipsel-openwrt-linux-uclibc-gcc... (cached) mipsel-openwrt-linux-gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether mipsel-openwrt-linux-gcc accepts -g... (cached) yes
checking for mipsel-openwrt-linux-gcc option to accept ISO C89... (cached) none needed
checking whether mipsel-openwrt-linux-gcc understands -c and -o together... (cached) yes
checking whether ln -s works... yes
checking whether make sets $(MAKE)... (cached) yes
checking for thread local storage (TLS) class... __thread
checking for mbedtls_cipher_setup in -lmbedcrypto... yes
checking whether mbedtls supports Cipher Feedback mode or not... ok
checking whether mbedtls supports the ARC4 stream cipher or not... ok
checking whether mbedtls supports the Blowfish block cipher or not... ok
checking whether mbedtls supports the Camellia block cipher or not... ok
checking for sodium_init in -lsodium... yes
checking for version of libsodium... yes
checking for C/C++ restrict keyword... __restrict
checking for netdb.h... yes
checking for library containing inet_ntop... none required
checking whether inet_ntop is declared... yes
checking for what kind of host... Linux
checking whether mipsel-openwrt-linux-gcc is Clang... no
checking whether pthreads work with -pthread... no
checking whether pthreads work with -pthreads... no
checking for the pthreads library -lpthreads... no
checking whether pthreads work without any flags... no
checking whether pthreads work with -Kthread... no
checking whether pthreads work with -pthread... no
checking whether pthreads work with -pthreads... no
checking whether pthreads work with -mthreads... no
checking for the pthreads library -lpthread... no
checking whether pthreads work with --thread-safe... no
checking whether pthreads work with -mt... no
checking for pthread-config... no
**configure: error: Can not find pthreads.  This is required.**

### What is your config in detail (with all sensitive info masked)?
cross compiling with toolchain of miwifi mini(mipsel-openwrt-linux-uclibc)
All libs are ready, and I found the libthread.a in toolchain's dir.
i compiled 2.5.x before,it's succesful!

**Comment by cokebar** [comment]
USD OPENWRT's SDK

**Comment by qq57240** [comment]
成功了
通过修改configure，因为修改比较简单粗爆，直接攻击检测判断语句，所以还是不push了
原因是miwifi toolchain的mipsel版不支持静态链接thread，需要加参数-ldl。直接在相关判断没有thread那边把错误提示换成加-ldl -thread就可以了。
