### ISSUE TITLE
Fragmentation

### ISSUE THREAD

**Issue by xiaodoudou** [shadowsocks/shadowsocks-libev#1211]
Hi,

Since few days, I have some warning displayed on my log of ss-redir:
Feb  7 09:57:00 ss-redir[791]: [udp] UDP server_recv_recvmsg fragmentation: File exists
Feb  7 09:57:00 ss-redir[791]: [udp] UDP server_recv_recvmsg fragmentation: File exists
Feb  7 09:57:02 ss-redir[791]: [udp] UDP server_recv_recvmsg fragmentation: File exists
Feb  7 09:57:05 ss-redir[791]: [udp] UDP server_recv_recvmsg fragmentation: File exists
Feb  7 09:57:10 ss-redir[791]: remote recv: Connection reset by peer
Feb  7 09:57:10 ss-redir[791]: [udp] UDP server_recv_recvmsg fragmentation: Connection reset by peer
Feb  7 09:57:13 ss-redir[791]: remote recv: Connection reset by peer

### What version of shadowsocks-libev are you using?
3.0.0-1

### What operating system are you using?
Client: Asus Merlin / Koolshare / Vertex 380.63_X7.2 SS 3.3.0
Server: Ubuntu 14.04.5 LTS or Ubuntu 16.04.1 LTS or Ubuntu 16.10 

### What did you do?
Nothing special, just seeing sometimes DNS queries are slow to be resolved so check the logs :)

### What is your config in detail (with all sensitive info masked)?
Server side:
{
    "server":"XXX.89.29.9",
    "local_address": "127.0.0.1",
    "local_port":1080,
    "timeout":300,
    "method":"rc4-md5",
    "mode":"tcp_and_udp",
    "fast_open": false,
    "server_port": "36067",
    "password": "XXXXXXXXX"
}

Client side:
{
    "server":"XXX.89.29.9",
    "server_port":36067,
    "local_port":3333,
    "password":"XXXXXXXXX",
    "timeout":600,
    "method":"rc4-md5"
}

Did reduce my router MTU to 1472 but issues still remains.

Thank you,
Cheers,

**Comment by madeye** [comment]
Try adding `mtu:1500` to your config file.

**Comment by xiaodoudou** [comment]
Did try on server side, nothing change :-/

Will try on client side.

**Comment by kimw** [comment]
Maybe you wanna upgrade ss-libev on both local & remote. Just maybe.

Earlier today, I got in the problem same as yours.

**Comment by xiaodoudou** [comment]
upgrading local side did fix the issue.

Cheers
