### ISSUE TITLE
3.0.0 的ss-tunnel在 OpenWrt/LEDE 上似乎无法正常工作

### ISSUE THREAD

**Issue by adolink** [shadowsocks/shadowsocks-libev#1212]
### What version of shadowsocks-libev are you using?
Shadowsocks-libev for OpenWrt/LEDE 3.0.0

### What operating system are you using?
LEDE  17.01.0-rc1
Linux lede 4.4.42 #0 SMP Sun Jan 29 16:34:29 2017 mips64 GNU/Linux

### What did you do?
从2.6.3升级到3.0.0

### What did you expect to see?
和使用2.6.3时一样正常

### What did you see instead?
DNS无法通过ss-tunnel转发
nslookup 任意地址 127.0.0.1均超时

### What is your config in detail (with all sensitive info masked)?
使用luci-app-shadowsocks进行配置，2.6.3一切正常，升级3.0.0后出现问题，未做任何配置更改

**Comment by cokebar** [comment]
try build from latest source

**Comment by debiansid** [comment]
I don't think you can build 3.0.0 for openers/lede

**Comment by adolink** [comment]
@debiansid  https://github.com/shadowsocks/openwrt-shadowsocks

**Comment by debiansid** [comment]
@wongsyrone could you please update your patch to 3.0.1? thanks

**Comment by cokebar** [comment]
@debiansid opewrt-shadowsocks is maintained by @aa65535

**Comment by wongsyrone** [comment]
旧版用的挺好，暂时还不想折腾，有兴趣可以自己折腾。

**Comment by debiansid** [comment]
What I mean is his lede-1

**Comment by adolink** [comment]
3.0.1已经正常使用
