### ISSUE TITLE
rpm package build failed on centos7

### ISSUE THREAD

**Issue by Ts1ng** [shadowsocks/shadowsocks-libev#1213]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
shadowsocks-libev-3.0.0

### What operating system are you using?
CentOS Linux release 7.3.1611 (Core) 

### What did you do?
sudo ./genrpm.sh

### What did you expect to see?
generate right rpm package

### What did you see instead?
/var/tmp/rpm-tmp.UHMhHJ: line 39: ./configure: No such file or directory
错误：/var/tmp/rpm-tmp.UHMhHJ (%build) 退出状态不好

### What is your config in detail (with all sensitive info masked)?
执行(%prep): /bin/sh -e /var/tmp/rpm-tmp.9sFcM3
+ umask 022
+ cd /home/centos/opensource/shadowsocks-libev/rpm/BUILD
+ cd /home/centos/opensource/shadowsocks-libev/rpm/BUILD
+ rm -rf shadowsocks-libev-3.0.0
+ /usr/bin/gzip -dc /home/centos/opensource/shadowsocks-libev/rpm/SOURCES/shadowsocks-libev-3.0.0.tar.gz
+ /usr/bin/tar -xf -
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd shadowsocks-libev-3.0.0
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ exit 0
执行(%build): /bin/sh -e /var/tmp/rpm-tmp.UHMhHJ
+ umask 022
+ cd /home/centos/opensource/shadowsocks-libev/rpm/BUILD
+ cd shadowsocks-libev-3.0.0
+ CFLAGS='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic'
+ export CFLAGS
+ CXXFLAGS='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic'
+ export CXXFLAGS
+ FFLAGS='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic -I/usr/lib64/gfortran/modules'
+ export FFLAGS
+ FCFLAGS='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic -I/usr/lib64/gfortran/modules'
+ export FCFLAGS
+ LDFLAGS='-Wl,-z,relro '
+ export LDFLAGS
+ '[' 1 == 1 ']'
+ '[' x86_64 == ppc64le ']'
++ find . -name config.guess -o -name config.sub
+ ./configure --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --enable-shared
/var/tmp/rpm-tmp.UHMhHJ: line 39: ./configure: No such file or directory
错误：/var/tmp/rpm-tmp.UHMhHJ (%build) 退出状态不好

RPM 构建错误：
    /var/tmp/rpm-tmp.UHMhHJ (%build) 退出状态不好

**Comment by quietnight** [comment]
这错误表示你缺少依赖性的库，导致退出。

**Comment by madeye** [comment]
Run `./autogen.sh` first.

**Comment by Ts1ng** [comment]
./autogen.sh 执行过了也报这错

**Comment by Ts1ng** [comment]
2.5.6的版本还正常，之后的就不行了

**Comment by quietnight** [comment]
2.6.3需要满足libsodium的依赖性。

**Comment by Ts1ng** [comment]
readme里面的步骤都做过了，你们本机生成rpm包的都没问题？

**Comment by registe** [comment]
个别依赖包 epel 里没有，也需要写个 spec 来打包
手上也没有openvz的机子了，几本都是docker解决，没有为rpm打包的动力...

**Comment by registe** [comment]
try it
https://copr.fedorainfracloud.org/coprs/registe/shadowsocks/

**Comment by Ts1ng** [comment]
Sorry,It doesn't work.
[centos@ip-172-31-22-227 rpm]$ ./genrpm.sh 
~/opensource/shadowsocks-libev ~/opensource/shadowsocks-libev/rpm
~/opensource/shadowsocks-libev/rpm ~/opensource/shadowsocks-libev ~/opensource/shadowsocks-libev/rpm
错误：构建依赖失败：
	libsodium-devel > 1.0.8 被 shadowsocks-libev-3.0.2-1.el7.centos.x86_64 需要

Actually,	libsodium-devel is installed.
[centos@ip-172-31-22-227 libsodium-1.0.11]$ ls -al /usr/lib
总用量 6296
dr-xr-xr-x. 29 root root    4096 2月  13 10:07 .
drwxr-xr-x. 13 root root    4096 2月   7 13:44 ..
drwxr-xr-x.  2 root root       6 11月 22 09:27 binfmt.d
lrwxrwxrwx.  1 root root      10 2月   7 14:12 cpp -> ../bin/cpp
drwxr-xr-x.  3 root root      59 11月  5 23:38 debug
drwxr-xr-x.  4 root root    4096 2月   7 13:45 dracut
drwxr-xr-x.  7 root root      78 2月   7 14:12 firewalld
drwxr-xr-x. 77 root root   12288 2月   7 13:45 firmware
dr-xr-xr-x.  2 root root       6 11月  5 23:38 games
drwxr-xr-x.  3 root root      32 2月   7 14:12 gcc
drwxr-xr-x.  3 root root      20 11月 22 23:51 grub
drwxr-xr-x.  6 root root      72 11月  6 00:55 kbd
drwxr-xr-x.  2 root root      54 2月   7 13:45 kdump
drwxr-xr-x.  3 root root      22 11月 22 09:27 kernel
-rw-r--r--.  1 root root 3970918 2月  13 10:07 libsodium.a
-rwxr-xr-x.  1 root root     937 2月  13 10:07 libsodium.la
lrwxrwxrwx.  1 root root      19 2月  13 10:07 libsodium.so -> libsodium.so.18.1.1
lrwxrwxrwx.  1 root root      19 2月  13 10:07 libsodium.so.18 -> libsodium.so.18.1.1
-rwxr-xr-x.  1 root root 2412184 2月  13 10:07 libsodium.so.18.1.1
drwxr-xr-x.  2 root root      53 2月   7 13:44 locale
drwxr-xr-x.  2 root root    4096 2月   7 13:45 modprobe.d
drwxr-xr-x.  5 root root     104 2月   7 13:45 modules
drwxr-xr-x.  2 root root       6 11月 22 09:27 modules-load.d
drwxr-xr-x.  4 root root      29 2月   7 13:45 NetworkManager
drwxr-xr-x.  2 root root      25 2月  13 10:07 pkgconfig
drwxr-xr-x.  2 root root      48 2月   7 13:45 polkit-1
drwxr-xr-x.  3 root root      26 11月  6 08:29 python2.7
drwxr-xr-x.  6 root root    4096 2月   7 14:21 rpm
lrwxrwxrwx.  1 root root      30 6月   6 2016 sendmail -> /etc/alternatives/mta-sendmail
lrwxrwxrwx.  1 root root      24 6月   6 2016 sendmail.postfix -> ../sbin/sendmail.postfix
dr-xr-xr-x.  2 root root       6 11月  5 23:38 sse2
drwxr-xr-x.  2 root root      49 2月   7 13:45 sysctl.d
drwxr-xr-x. 12 root root    4096 2月   7 13:45 systemd
drwxr-xr-x.  2 root root    4096 2月   7 14:12 tmpfiles.d
drwxr-xr-x. 11 root root    4096 2月   7 13:45 tuned
drwxr-xr-x.  4 root root    4096 2月   7 13:45 udev
drwxr-xr-x.  2 root root      77 11月 15 23:30 yum-plugins

**Comment by Ts1ng** [comment]
My modification about spec.in 

diff --git a/rpm/SPECS/shadowsocks-libev.spec.in b/rpm/SPECS/shadowsocks-libev.spec.in
index c920e08..ea06c6f 100644
--- a/rpm/SPECS/shadowsocks-libev.spec.in
+++ b/rpm/SPECS/shadowsocks-libev.spec.in
@@ -52,9 +52,19 @@ shadowsocks-libev is a lightweight secured scoks5 proxy for embedded devices and
 
 %build
 %if 0%{?use_system_lib}
+rm -rf libcork libipset
+cp -rf ../../../libcork ./libcork
+cp -rf ../../../libipset ./libipset
+./autogen.sh
 %configure --enable-shared --enable-system-shared-lib
+make clean
 %else
+rm -rf libcork libipset
+cp -rf ../../../libcork ./libcork
+cp -rf ../../../libipset ./libipset
+./autogen.sh
 %configure --enable-shared
+make clean
 %endif
 make %{?_smp_mflags}

And it dosen't look nice,but it works

**Comment by registe** [comment]
download source package from here: <https://github.com/shadowsocks/shadowsocks-libev/releases/download/v3.0.2/shadowsocks-libev-3.0.2.tar.gz>

don't need to run ./autogen.sh

**Comment by Ts1ng** [comment]
[centos@ip-172-31-22-227 rpm]$ ./genrpm.sh 
fatal: Not a git repository (or any of the parent directories): .git
./genrpm.sh: 第 47 行:pushd: 无其他目录

Generating rpm should be in git repository

**Comment by registe** [comment]
@Ts1ng 

...

I have done the job...add the below content to the file `/etc/yum.repos.d/registe-shadowsocks-epel-7.repo`:

```
[registe-shadowsocks]
name=Copr repo for shadowsocks owned by registe
baseurl=https://copr-be.cloud.fedoraproject.org/results/registe/shadowsocks/epel-7-$basearch/
type=rpm-md
skip_if_unavailable=True
gpgcheck=1
gpgkey=https://copr-be.cloud.fedoraproject.org/results/registe/shadowsocks/pubkey.gpg
repo_gpgcheck=0
enabled=1
enabled_metadata=1
```

And follow the below steps:

```
yum install epel-release
yum makecache
yum install shadowsocks-libev simple-obfs
```

**Comment by Ts1ng** [comment]
既然这个仓库里的rpm文件里的脚本打不了rpm包，建议把这个文件夹删了

**Comment by huangyanxiong01** [comment]
@zgist 
```
No package shadowsocks-libev available.
No package simple-obfs available.

```

**Comment by zgist** [comment]
@huangyanxiong01 https://copr.fedorainfracloud.org/coprs/
里面搜
找一个可用的
