### ISSUE TITLE
How to generate a key ?

### ISSUE THREAD

**Issue by testcaoy7** [shadowsocks/shadowsocks-libev#1214]
How to generate a base64 encoded key for ss-libev 3.0.1 ?

**Comment by wongsyrone** [comment]
随便输一个，不合格的话会自己给你生成一个，然后用生成的就行

**Comment by madeye** [comment]
try `./src/ss-server -s 0.0.0.0 -p 8388 -m chacha20 --key genkey`.

**Comment by madeye** [comment]
Or try this `head -c 32 /dev/urandom | base64 | sed 's/+/-/g; s/\//_/g;'`

**Comment by triaqu** [comment]
请问生成的这个KEY怎么用？
看了下https://github.com/shadowsocks/shadowsocks-org/issues/35没搞明白，就是生成个随机 -k 的密码吗？

**Comment by testcaoy7** [comment]
@triaqu This is a high-entropy key and **key is not password**. Use key can improve security.

**Comment by kimw** [comment]
@testcaoy7 When the key is set, the password is not necessary, right?

**Comment by testcaoy7** [comment]
@kimw Yes

**Comment by triaqu** [comment]
@testcaoy7 谢谢解答。现在客户端还不支持吧。

**Comment by testcaoy7** [comment]
@triaqu 可以在Windows下使用Cygwin编译shadowsocks-libev，然后在命令行里用ss-local
