### ISSUE TITLE
关于 --key 选项的默认值

### ISSUE THREAD

**Issue by pexcn** [shadowsocks/shadowsocks-libev#1215]
不过不指定 --key，那么默认值是什么？

是之前的这几行吗？
https://github.com/shadowsocks/shadowsocks-libev/blob/e18f71b03fb54a0d34b6aa41f8966620722c4c56/src/crypto.c#L108-L111

**Comment by madeye** [comment]
No default value for `--key`. If neither key nor password is provided, ss-server would exit with an error.

**Comment by pexcn** [comment]
@madeye 那这个 key 的作用是用来干什么呢？增加随机数熵？
