### ISSUE TITLE
compile error on Ubuntu 14.04.5 LTS

### ISSUE THREAD

**Issue by sadoneli** [shadowsocks/shadowsocks-libev#1216]
### What version of shadowsocks-libev are you using?
v3.0.1

### What operating system are you using?
Ubuntu 14.04.5 LTS

### What did you do?
compile

### What did you expect to see?
compile success

### What did you see instead?
```shell
  CCLD     libshadowsocks-libev.la
  CC       ss_local-utils.o
  CC       ss_local-jconf.o
  CC       ss_local-json.o
  CC       ss_local-udprelay.o
  CC       ss_local-cache.o
  CC       ss_local-acl.o
  CC       ss_local-netutils.o
  CC       ss_local-local.o
  CC       ss_local-crypto.o
  CC       ss_local-aead.o
  CC       ss_local-stream.o
  CC       ss_local-plugin.o
  CC       ss_local-http.o
  CC       ss_local-tls.o
  CC       ss_local-rule.o
  CCLD     ss-local
ss_local-crypto.o: In function `crypto_parse_key':
/home/shadowsocks-libev/src/crypto.c:219: undefined reference to `base64_decode'
/home/shadowsocks-libev/src/crypto.c:231: undefined reference to `base64_encode'
collect2: error: ld returned 1 exit status
make[2]: *** [ss-local] Error 1
make[2]: Leaving directory `/home/shadowsocks-libev/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/shadowsocks-libev'
make: *** [all] Error 2
```

### What is your config in detail (with all sensitive info masked)?
./configure && make

**Comment by jieee006** [comment]
@sadoneli  ss-tunnel you just updated still does not work with new encrypt method on asus merlin.

**Comment by jieee006** [comment]
the latest ss-tunnel @sadoneli just upgraded on asus merlin still does not work with new encrypt method,even if chacha20-ietf or camellia-256-cfb.

**Comment by wxyzh** [comment]
@sadoneli 
```
make clean
./autogen.sh
```

**Comment by madeye** [comment]
Try `./autogen.sh`.

**Comment by asmadeus08** [comment]
sudo apt install shadowsocks-libev
git clone https://github.com/shadowsocks/shadowsocks-libev.git
cd shadowsocks-libev
git reset --hard origin/master
git pull
git submodule init && git submodule update
sudo apt-get install --no-install-recommends build-essential autoconf automake libtool libssl-dev \
gawk debhelper dh-systemd init-system-helpers pkg-config asciidoc xmlto apg libpcre3-dev zlib1g-dev \
libev-dev libudns-dev libsodium-dev
sudo apt-get install --no-install-recommends gettext build-essential autoconf libtool libpcre3-dev asciidoc xmlto libmbedtls-dev libev-dev libudns-dev libsodium-dev
./autogen.sh && dpkg-buildpackage -b -us -uc -i
cd ..
sudo dpkg -i shadowsocks-libev*.deb

**Comment by sadoneli** [comment]
thx for you all， solved！
