### ISSUE TITLE
开启 --plugin 之后 ss-manager 的流量统计功能失效

### ISSUE THREAD

**Issue by bazingaterry** [shadowsocks/shadowsocks-libev#1217]
### What version of shadowsocks-libev are you using?

3.0.1

### What operating system are you using?

Ubuntu 14.04

### What did you do?

使用 `ss-manager` 统计 `ss-server` 的流量，开启了 `--plugin` 和 `--plugin-opts` 两个参数。

### What did you expect to see?

流量成功统计。

### What did you see instead?

```python
>>> cli = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
>>> cli.connect(('127.0.0.1',8888))
>>> cli.send(b'ping')
```

看到流量始终为 0。

### What is your config in detail (with all sensitive info masked)?

```bash
    ss-manager \
    --manager-address 127.0.0.1:8888 \
    --executable /usr/local/bin/ss-server \
    -s :: -s 0.0.0.0 \
    -u \
    -m $METHOD \
    -t $TIMEOUT \
    -f $PID_FILE \
    --fast-open \
    --acl $ACL_FILE \
    --plugin $PLUGIN \
    --plugin-opts $PLUGIN_OPTS
```

**Comment by madeye** [comment]
Please try f4b1641
