### ISSUE TITLE
SegmentFault when telnet to ss-server

### ISSUE THREAD

**Issue by xiaooloong** [shadowsocks/shadowsocks-libev#1218]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
`shadowsocks-libev 3.0.0`

### What operating system are you using?
`CentOS release 6.6 (Final)`

### What did you do?
`telnet 127.0.0.1 65535`

### What did you expect to see?
```
Connecting to 127.0.0.1:65535...
Connection established.
To escape to local shell, press Ctrl+Alt+].

```

### What did you see instead?
```
Connecting to 127.0.0.1:65535...
Connection established.
To escape to local shell, press Ctrl+Alt+].
test

Connection closed by foreign host.

```
and
```
[root]# dmesg 
ss-server[2102] general protection ip:42a62a sp:7fff5c5b2578 error:0 in ss-server[400000+42000]
```
### What is your config in detail (with all sensitive info masked)?
```json
{
    "server":"0.0.0.0",
    "server_port":65535,
    "local_port":1080,
    "password":"ooxxooxx",
    "timeout":60,
    "method":"aes-256-cfb"
}
```

**Comment by madeye** [comment]
Try the latest version.

**Comment by xiaooloong** [comment]
@madeye i have pulled the latest commit and compiled on my cent6, it works perfectlly. than you !

`yum install mbedtls`
by the way, it seems that package `mbedtls` is needed by the latest version.
`Starting shadowsocks-server: /usr/local/bin/ss-server: error while loading shared libraries: libmbedcrypto.so.0: cannot open shared object file: No such file or directory`
