### ISSUE TITLE
libcork and libipset not included in release 3.0.0 and 3.0.1

### ISSUE THREAD

**Issue by zhou0** [shadowsocks/shadowsocks-libev#1220]
### What version of shadowsocks-libev are you using?

3.0.0 and 3.0.1
### What operating system are you using?

Linux localhost.localdomain 4.9.6-200.fc25.x86_64 #1 SMP Thu Jan 26 10:17:45 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### What did you do?

autogen.sh
### What did you expect to see?

configure
### What did you see instead?

configure.ac:289: error: required file 'libcork/Makefile.in' not found
configure.ac:289: error: required file 'libipset/Makefile.in' not found
autoreconf: automake failed with exit status: 1

### What is your config in detail (with all sensitive info masked)?
none

**Comment by asmadeus08** [comment]
Tha's why you need to use this comand
git pull
git submodule init && git submodule update

**Comment by registe** [comment]
download below source pack
https://github.com/shadowsocks/shadowsocks-libev/releases/download/v3.0.1/shadowsocks-libev-3.0.1.tar.gz

**Comment by kimw** [comment]
@zhou0 Next time you fall in trouble, please check README first. That's always the first step you should go :)

**Comment by cokebar** [comment]
@asmadeus08 For release source package, sub-module should be included.

**Comment by cokebar** [comment]
@asmadeus08  git pull is not needed. this will pull the latest source instead of the release version.

**Comment by maxchendt** [comment]
in VirtualBox vm
```
wget  https://github.com/shadowsocks/shadowsocks-libev/releases/download/v3.0.1/shadowsocks-libev-3.0.1.tar.gz
tar xzvpf shadowsocks-libev-3.0.1.tar.gz
cd shadowsocks-libev-3.0.1
sudo apt-get install --no-install-recommends gettext build-essential autoconf automake libtool \
    gawk debhelper dh-systemd init-system-helpers pkg-config asciidoc xmlto apg libpcre3-dev \
    libev-dev libudns-dev dh-autoreconf libmbedtls-dev libsodium-dev  libssl-dev
# 'autogen.sh' not needed
dpkg-buildpackage -b -us -uc -i

```

with screenshot
![virtualbox-ss301](https://cloud.githubusercontent.com/assets/9275768/22828619/405c55ca-efd9-11e6-9e39-c16d87137466.png)
