### ISSUE TITLE
Compile error: No rule to make target 'ss-nat', needed by 'all-am'

### ISSUE THREAD

**Issue by darkgeek** [shadowsocks/shadowsocks-libev#1221]
### What version of shadowsocks-libev are you using?
2.6.3

### What operating system are you using?
GalliumOS 2.0 x86_64, a `Ubuntu 16.04` derived OS specifically optimized for Chromebook 

### What did you do?
Build it by using `linuxbrew`

### What did you expect to see?
Build without errors.

### What did you see instead?
It builds with errors:
```shell
...
  CC       ss_redir-plugin.o
  CC       ss_redir-http.o
  CC       ss_redir-tls.o
make[2]: *** No rule to make target 'ss-nat', needed by 'all-am'.  Stop.
make[2]: *** Waiting for unfinished jobs....
  CC       ss_redir-rule.o
make[2]: Leaving directory '/tmp/shadowsocks-libev-20170208-2565-1ch946m/shadowsocks-libev-2.6.3/src'
Makefile:493: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/tmp/shadowsocks-libev-20170208-2565-1ch946m/shadowsocks-libev-2.6.3'
Makefile:402: recipe for target 'all' failed
make: *** [all] Error 2
...
```
And more logs can be found [here](https://gist.github.com/ff42623efde1bf74d9118b00d3141031).
### What is your config in detail (with all sensitive info masked)?
All the configs and logs are in the gist posted [before](https://gist.github.com/ff42623efde1bf74d9118b00d3141031).

Don't hesitate to tell me if you need more information please, Thanks.

**Comment by madeye** [comment]
Try the latest commit.
