### ISSUE TITLE
多端口服务启动失败

### ISSUE THREAD

**Issue by love1st** [shadowsocks/shadowsocks-libev#1222]
### What version of shadowsocks-libev are you using?
3.0.1
### What operating system are you using?
Ubuntu 16.04 
### What did you do?
在VPS上为shadowsocks-libev开启2个端口。
1、安装shadowsocks-libev之后自带的shadowsocks-libev的配置为端口A，并且有obfs设置"plugin":"obfs-server","plugin_opts":"obfs=tls"
2、在/etc/shadowsocks-libev 中添加端口B的配置，这里的配置除了端口与A的不一样，其它完全一样。并复制/etc/defaults、/etc/init.d中的shadowsocks-libev文件各一份，更名为SS1，并且分别更改文件内相应内容。执行chmod 755 /etc/init.d/SS1 ; update-rc.d SS1 defaults ; service SS1 start
### What did you expect to see?
端口AB同时开启。
### What did you see instead?
不论A的obfs设置与否，当端口B有obfs设置时，端口AB中只有A可以开启，当B没有obfs设置时，AB可以同时开启。
### What is your config in detail (with all sensitive info masked)?
{
	"server":["::","0.0.0.0"],
	"server_port":1234,
	"local_address": "127.0.0.1",
	"local_port":1080,
	"password":"*",
	"timeout":3600,
	"method":"chacha20-ietf",
	"ipv6_first":true,
	"plugin":"obfs-server",
	"plugin_opts":"obfs=tls"
}
A、B配置只有server_port不同。

**Comment by xingezhang** [comment]
用ss-manager试试，我开3个端口没问题

**Comment by madeye** [comment]
You'd better not do that. Simply duplicating init scripts will cause a race condition.

Try start ss-server one by one, or add `"reuse-port":true`  to you config file.

**Comment by love1st** [comment]
@madeye @xingezhang 谢谢指导。
