### ISSUE TITLE
Installation destinations for libsodium and libmbedtls are not same

### ISSUE THREAD

**Issue by cokebar** [shadowsocks/shadowsocks-libev#1223]
In readme, this section:
```
export LIBSODIUM_VER=1.0.11
export MBEDTLS_VER=2.4.0
wget https://download.libsodium.org/libsodium/releases/libsodium-$LIBSODIUM_VER.tar.gz
tar xvf libsodium-$LIBSODIUM_VER.tar.gz
pushd libsodium-$LIBSODIUM_VER
./configure --prefix=/usr && make
sudo make install
popd
wget https://tls.mbed.org/download/mbedtls-$MBEDTLS_VER-gpl.tgz
tar xvf mbedtls-$MBEDTLS_VER-gpl.tgz
pushd mbedtls-$MBEDTLS_VER
make SHARED=1 CFLAGS=-fPIC
sudo make install
popd
```
libsodium is installed in `/usr`, but libmbedtls is installed in /usr/local (defined by it's makefile). They're not consistent.
Maybe there're two options, and one of them should be chosen.
1. Install libsodium & libmbedtls in `/usr/local`, which is defined by makefile's default. And modify system settings to let system also search lib files in /usr/local/lib.
2. Install libsodium & libmbedtls in `/usr`. Modify the readme like this:
```
export LIBSODIUM_VER=1.0.11
export MBEDTLS_VER=2.4.0
wget https://download.libsodium.org/libsodium/releases/libsodium-$LIBSODIUM_VER.tar.gz
tar xvf libsodium-$LIBSODIUM_VER.tar.gz
pushd libsodium-$LIBSODIUM_VER
./configure --prefix=/usr && make
sudo make install
popd
wget https://tls.mbed.org/download/mbedtls-$MBEDTLS_VER-gpl.tgz
tar xvf mbedtls-$MBEDTLS_VER-gpl.tgz
pushd mbedtls-$MBEDTLS_VER
make SHARED=1 CFLAGS=-fPIC
sudo make DESTDIR=/usr install
popd
```

**Comment by madeye** [comment]
Let's take Option 2 here. Maybe a PR?

**Comment by cokebar** [comment]
See PR #1225

**Comment by registe** [comment]
mbedtls:

cmake . -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE="Release" -DUSE_SHARED_MBEDTLS_LIBRARY=1
make && make test && make install

**Comment by registe** [comment]
I wrote spec file to build rpm binary package on CentOS 7,  installed into `/usr`, and get some error: 

```
file /usr/bin from install of mbedtls-2.4.0-1.el7.centos.x86_64 conflicts with file from package filesystem-3.2-21.el7.x86_64
file /usr/lib64 from install of mbedtls-2.4.0-1.el7.centos.x86_64 conflicts with file from package filesystem-3.2-21.el7.x86_64
```

so, I think `/usr/local` is more reasonable
