### ISSUE TITLE
AEAD的正确用法是怎么样的？大神们指点一下？

### ISSUE THREAD

**Issue by rule2c** [shadowsocks/shadowsocks-libev#1226]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

**Comment by cokebar** [comment]
using the following encrypt method：
```
AES-128-GCM
AES-192-GCM
AES-256-GCM
ChaCha20-IETF-Poly1305
XChaCha20-IETF-Poly1305
```
Details：http://shadowsocks.org/en/spec/AEAD.html

**Comment by rule2c** [comment]
谢谢啊 @cokebar
