### ISSUE TITLE
service cannot start with a config file

### ISSUE THREAD

**Issue by chenhaowen01** [shadowsocks/shadowsocks-libev#1228]
### What version of shadowsocks-libev are you using?
shadowsocks-libev 3.0.0

### What operating system are you using?
Arch Linux x86_64

### What did you do?
I try to start shadawsocks-liev(ss-server, ss-local) with a config file. The command line: 
```bash
ss-server -c shadowsocks.json
```

### What did you expect to see?
Started info.

### What did you see instead?
An help message just like excueted ```ss-server -h```.

### What is your config in detail (with all sensitive info masked)?
```
{
        "server": "0.0.0.0:1234",
        "local_address": "127.0.0.1",
        "loccal_port": 1080,
        "password": "mypassword",
        "time_out": 3000,
        "method": "aes-256-cfb",
}
```

**Comment by wxyzh** [comment]
```
{
        "server": "0.0.0.0:1234",
        "local_address": "127.0.0.1",
        "loccal_port": 1080,
        "password": "mypassword",
        "time_out": 3000,
        "method": "aes-256-cfb"
}
```

**Comment by chenhaowen01** [comment]
any wrong?

**Comment by wxyzh** [comment]
json syntax invalid,
{
        "server": "0.0.0.0:1234",
        "local_address": "127.0.0.1",
        "loccal_port": 1080,
        "password": "mypassword",
        "time_out": 3000,
        **"method": "aes-256-cfb"**
}

**Comment by chenhaowen01** [comment]
It is not an syntax error, I just try 
```
{
        "server": "0.0.0.0",
        "server_port": "1234",
        "local_address": "127.0.0.1",
        "loccal_port": 1080,
        "password": "mypassword",
        "time_out": 3000,
        "method": "aes-256-cfb"
}
```
It works.
But I want to config multiport with diff passwords, likt this:
```
{
        "server": "0.0.0.0",
        "local_address": "127.0.0.1",
        "loccal_port": 1080,
        "port_password": chenhaowen",
                "8003": "password1",
                "8004": "password2"
        },
        "time_out": 3000,
        "method": "aes-256-cfb",
        "fast_open": false
}
```
It can not start.

**Comment by hosiet** [comment]
"port_password" was *never* *ever* supported by ss-libev.

**Comment by chenhaowen01** [comment]
so what can i used to instead of "port_password"? The doc never note it.

**Comment by hosiet** [comment]
Doc (man page) said you can't do it. Please use multiple config files instead.

**Comment by chenhaowen01** [comment]
ok, thank you.

**Comment by chenhaowen01** [comment]
I can not find any infomation you mention above by ```man ss-server``` or ```man shadowsocks-libev```, can you tell me it in whitch section?

**Comment by madeye** [comment]
Try `./src/ss-manager -c config.json --manager-address 127.0.0.1:9090`

**Comment by hosiet** [comment]
OK maybe I didn't memorize it well. Thing about "port_password" can be repeatedly found in issues, like #5, #65, #383, #385, #444, #543, #684, #859, #1023. Maybe we should update documentation and say "port_password" can only be used by `ss-manager` and not understood by `ss-server`.

**Comment by madeye** [comment]
@hosiet I just remembered that I'd implemented it... So, it's my bad.

**Comment by chenhaowen01** [comment]
yes, it just works with ```ss-maager```. the doc should be update

**Comment by chenhaowen01** [comment]
thank you
