### ISSUE TITLE
The OpenWRT Version didnot provide ss-server

### ISSUE THREAD

**Issue by nomagick** [shadowsocks/shadowsocks-libev#123]
I found that the ss-server was compiled but not installed.

Is this to save disk-space for the openwrt-routers ?

Shall I PR this issue or Fork to some 'with-server' version?

**Comment by netomx** [comment]
I am sorry to open this, but why "design" ?

**Comment by bettermanbao** [comment]
you can download pre-compiled ipg for ar71xx here: http://pan.baidu.com/share/link?shareid=3520290966&uk=218370962
Enjoy!
