### ISSUE TITLE
libev, linudns, and libsodium seem to be missing

### ISSUE THREAD

**Issue by KarlM256** [shadowsocks/shadowsocks-libev#1230]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What did you see instead? missing
2.5.6 had these folders, 2.6.3 does not. Should they still be there? The configure failed, so I downloaded and started building each of these libraries, but that seems wrong.

**Comment by Bestoa** [comment]
libev/libsodium are provided by cygwin.
ibudns need to be built from source. Static lib is OK.

**Comment by KarlM256** [comment]
I started down that path to build libudns. But these source files were included in the previous shadowsocks-libev releases, such as 2.5.6. The libudns, for example has no releases so far. So getting it is just to clone the repository. It seems that this will make reproducing bugs more difficult because it will be difficult to tell what version of each component was used.

I just wanted to make sure that this was an intended change because libev, libsodium and linudns were previously included in the shadowsocks-libev releases.

Thanks,

...Karl
