### ISSUE TITLE
Unable to use AEAD with shadowrocket iOS client

### ISSUE THREAD

**Issue by alexyangjie** [shadowsocks/shadowsocks-libev#1231]
### What version of shadowsocks-libev are you using?
3.0.1

### What operating system are you using?
CentOS 7

### What did you do?
Use shadowrocket on iOS to connect to vps

### What did you expect to see?
Connection successful

### What did you see instead?
Unable to connect. Logs on server:
2017-02-10 09:29:40 ERROR: failed to handshake with [ip address removed]: authentication error

Nothing additional when running with -v.

ss-local on Windows (cygwin) works fine. The issue only occurred when using shadowrocket on iOS.

### What is your config in detail (with all sensitive info masked)?
{
    "server": ["[::0]", "0.0.0.0"],
    "server_port": **,
    "local_port": 8089,
    "password": "****",
    "timeout": 600,
    "method": "aes-128-gcm"
}
/usr/local/bin/ss-server -a root -c /etc/shadowsocks-libev/config.json -u

**Comment by madeye** [comment]
To identify if it's a problem of shadowsocks-libev, you may try this port: https://github.com/shadowsocks/go-shadowsocks2

**Comment by debiansid** [comment]
It is caused by iOS client

**Comment by maddie** [comment]
@debiansid If I understand SIP004 correctly, `aes-128-gcm` is considered to be AEAD cipher thus will communicate in a different fashion under 3.0.1 server side.

Shadowrocket seems to be based on 2.5.x client, so it's not supported.

**Comment by debiansid** [comment]
@maddie agreed

**Comment by alexyangjie** [comment]
@madeye I've tested with go-shadowsocks2, and it still has issues. Looks like it is an issue with shadowrocket. I will close this issue now. Thanks for help.

**Comment by riobard** [comment]
AFAIK no client other than `shadowsocks-libev` and `go-shadowsocks2` support AEAD ciphers (which is still in developing stage; see https://github.com/shadowsocks/shadowsocks-org/issues/42) 

Please wait for official announcement.

**Comment by SquirrelCoder** [comment]
@riobard AES-*-GCM and ChaCha20-Poly1305 is implemented in Android-Client.
The go version is pretty interesting, though very hard to use.
I have to open the CMD every time I want to connect to server :D. Though works great ;).
It would be great, if there a wiki page, tracing SS clients, that which one has implement the AEAD ciphers.

**Comment by riobard** [comment]
@SquirrelCoder https://github.com/shadowsocks/shadowsocks-org/wiki/Implementations
