### ISSUE TITLE
如何在config.json中添加simple-obfs参数？

### ISSUE THREAD

**Issue by Aniark** [shadowsocks/shadowsocks-libev#1232]
### What version of shadowsocks-libev are you using?
3.0.1-1

### What operating system are you using?
debian 8 x64

### What did you do?
编译安装了simple-obfs和shadowsocks-libev

在https://github.com/shadowsocks/simple-obfs 中没有看到具体如何在config.json中添加参数，遂提问

**Comment by rampageX** [comment]
```
范例：
{
  "server": "xxx.xxx.xxx.xxx",
  "server_port": 10086,
  "password": "fuckyougfw",
  "key": "QmF0dGxlLkxvcy5BbmdlbGVzLjIwMTEuMTA4MHAuQmx1UmF5LngyNjQuRFRTLUhEQ2hpbmEK",
  "method": "aes-128-gcm",
  "plugin": "obfs-local",
  "plugin_opts": "obfs=http;obfs-host=www.bing.com",
  "remarks": "SS-OBFS",
  "mode": "tcp_and_udp"
}
```

服务端替换 `"plugin": "obfs-server",`

**Comment by zhou0** [comment]
請問樓上這個key 有什麼用？ 如果沒有key 不是會自動derive嗎？

**Comment by Aniark** [comment]
@rampageX 添加参数后出现了一些问题，已开issue，劳驾解答 

issue地址：https://github.com/shadowsocks/shadowsocks-libev/issues/1234
