### ISSUE TITLE
3.0.1的shadowsocks-libev是不是不能使用kcptun加速？

### ISSUE THREAD

**Issue by lingbaoboy** [shadowsocks/shadowsocks-libev#1235]
我使用2.*.*的shadowsocks-libev可以正常使用kcptun加速，今天蛋疼升级到了3.0.1的shadowsocks-libev，ss的配置没变使用的是chacha20加密，没有用AEAD加密，没有启用混淆插件，在PC测试，结果ss可以正常使用，kcptun却不能加速了，kcptun的配置没变。
kcptun老版本和最新版本都试过了，使用kcptun加速打开网页会出现

```
此网站无法提供安全连接
www.google.com 使用了不受支持的协议。
ERR_SSL_VERSION_OR_CIPHER_MISMATCH
```
有没有使用3.0.1的shadowsocks-libev，同时kcptun正常使用的？

另外安卓的最新客户端4.0.2，kcptun插件怎么设置啊？都没有kcptun的端口设置的地方。

**Comment by triaqu** [comment]
在安卓上能正常使用。

**Comment by lingbaoboy** [comment]
@triaqu  你的SS 和手机ss分别是什么版本？

**Comment by triaqu** [comment]
@lingbaoboy 都是最新的，3.0.1和4.0.2。

**Comment by lingbaoboy** [comment]
@triaqu 
能截图让我看看怎么设置吗？
我怎么搞都不能加速……
1、你用的什么加密协议？
2、是否混淆了？
3、kcptun手机上是怎么设置的？
4、远程端口是不是设置成kcp的端口？

**Comment by triaqu** [comment]
@lingbaoboy

 File: /etc/shadowsocks-libev/config.json                    
{
    "server":"0.0.0.0",
    "local_port":1080,
    "timeout":300,
    "method":"chacha20",
    "fast_open": false,
    "server_port":xxxx,
    "password":"xxxxxx",
    "auth":false,
"plugin":"obfs-server",
"plugin_opts":"obfs=http"
}

手机端ss 远程端口连接kcp设的端口，kcp插件我只用了mode=normal参数。

**Comment by lingbaoboy** [comment]
以确定兼容了。
可能是我使用kcaptun脚本安装的原因，手工安装kcptun完美使用。
