### ISSUE TITLE
Default cipher choice

### ISSUE THREAD

**Issue by zhou0** [shadowsocks/shadowsocks-libev#1236]
### What version of shadowsocks-libev are you using?

3.0.1

### What operating system are you using?

Fedora

### What did you do?

try to use the AES-256-GCM method, the default encryption method 

### What did you expect to see?

expect it to work

### What did you see instead?

It does not work

### What is your config in detail (with all sensitive info masked)?

Support for AES256-GCM requires a CPU with the aesni and pclmul extensions.  My CPU does not meed this requirement.  So as suggested by libsodium " There are no plans to support non hardware-accelerated implementations of AES-GCM. If portability is a concern, use ChaCha20-Poly1305 instead.", why not make ChaCha20-Poly1305 as the new default cipher?

**Comment by madeye** [comment]
I think the default cipher is still rc4-md5.

**Comment by zhou0** [comment]
I mean the default among the new recommended ciphers, It defaults to AES256-GCM. no?

**Comment by madeye** [comment]
Nope, actually no default cipher in shadowsocks protocol.
