### ISSUE TITLE
ss-local不会发送数据包到ss-server

### ISSUE THREAD

**Issue by hysgit** [shadowsocks/shadowsocks-libev#1237]
shadowsocks-libev版本:3.0.1
系统:ubuntu 14.04, ubuntu 16.04, debian 8.5, centos 6, centos 7
以上系统全部试过,全部不行.
从源码安装shadowsocks-libev,运行ss-server,运行ss-local作为代理:
ss-server -s 0.0.0.0 -p 18388 -k 123456 -m aes-256-cfb -u
ss-local -s 127.0.0.1 -p 18388 -k 123456 -m aes-256-cfb -l 1080 -b 0.0.0.0  -vv -u

通过抓包,可以看到ss-local开启的1080端口能接收到数据,但是ss-local从开始运行,从来不会给ss-server发送任何数据包.没有看到ss-local发送任何数据包给ss-server.
用windows下的ss客户端能连接到ss-server,能通过ss-server上网.

服务端和客户端在同一台机器上.

$ ss-local -s 0.0.0.0 -p 18388 -k 123456 -m aes-256-cfb -l 1080 -b 0.0.0.0  -vv -u
 2017-02-11 22:59:05 INFO: initializing ciphers... aes-256-cfb
 2017-02-11 22:59:05 INFO: udprelay enabled
 2017-02-11 22:59:05 INFO: listening at 0.0.0.0:1080

浏览器设置ss-local的端口为代理,浏览器请求的时候,在ss-local端输出:
 2017-02-11 22:59:07 INFO: udp assc request accepted
但ss-local就是没有任何请求发送给ss-server

有没有人遇到过相同的问题,或者有谁知道这怎么解决.

**Comment by kevinzu007** [comment]
问题解决了吗？
我现在用最新的编译安装也一样出现这个问题，shadowsocks-libev 3.08，“ss-local is not working on Linux system #1391” 这个并不能解决问题

**Comment by sylinuxhy** [comment]
现在怎么样了  ？ 还是这个问题

**Comment by WEAKwind** [comment]
同样遇到了这个问题
