### ISSUE TITLE
shadowsocks-libev 3.0.1 build problem

### ISSUE THREAD

**Issue by KarlM256** [shadowsocks/shadowsocks-libev#1238]
### What version of shadowsocks-libev are you using?
3.0.1

### What operating system are you using?
Cygwin 64 bit on Windows 10 64

### What did you do?
I installed libsodium-devel and libev-devel in Cygwin, built libudns and libmbedtls.
Then I did a ./configure --disable-documentation followed by make

### What did you expect to see?
A clean build.

### What did you see instead?
user@host /c/Users/user/Desktop/shadowsocks-libev-3.0.1/shadowsocks-libev-3.0.1
$ make
make  all-recursive
make[1]: Entering directory '/c/Users/user/Desktop/shadowsocks-libev-3.0.1/shadowsocks-libev-3.0.1'
Making all in libcork
make[2]: Entering directory '/c/Users/user/Desktop/shadowsocks-libev-3.0.1/shadowsocks-libev-3.0.1/libcork'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/c/Users/user/Desktop/shadowsocks-libev-3.0.1/shadowsocks-libev-3.0.1/libcork'
Making all in libipset
make[2]: Entering directory '/c/Users/user/Desktop/shadowsocks-libev-3.0.1/shadowsocks-libev-3.0.1/libipset'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/c/Users/user/Desktop/shadowsocks-libev-3.0.1/shadowsocks-libev-3.0.1/libipset'
Making all in src
make[2]: Entering directory '/c/Users/user/Desktop/shadowsocks-libev-3.0.1/shadowsocks-libev-3.0.1/src'
  CCLD     ss-local.exe
/usr/lib/libudns.la: line 6: $'\r': command not found
/usr/lib/libudns.la: line 9: $'\r': command not found
/usr/lib/libudns.la: line 12: $'\r': command not found
/usr/lib/libudns.la: line 15: $'\r': command not found
/usr/lib/libudns.la: line 18: $'\r': command not found
/usr/lib/libudns.la: line 21: $'\r': command not found
/usr/lib/libudns.la: line 24: $'\r': command not found
/usr/lib/libudns.la: line 29: $'\r': command not found
/usr/lib/libudns.la: line 32: $'\r': command not found
/usr/lib/libudns.la: line 35: $'\r': command not found
/usr/lib/libudns.la: line 39: $'\r': command not found
/usr/lib/libudns.la: line 6: $'\r': command not found
/usr/lib/libudns.la: line 9: $'\r': command not found
/usr/lib/libudns.la: line 12: $'\r': command not found
/usr/lib/libudns.la: line 15: $'\r': command not found
/usr/lib/libudns.la: line 18: $'\r': command not found
/usr/lib/libudns.la: line 21: $'\r': command not found
/usr/lib/libudns.la: line 24: $'\r': command not found
/usr/lib/libudns.la: line 29: $'\r': command not found
/usr/lib/libudns.la: line 32: $'\r': command not found
/usr/lib/libudns.la: line 35: $'\r': command not found
/usr/lib/libudns.la: line 39: $'\r': command not found
/usr/lib/libudns.la: line 6: $'\r': command not found
/usr/lib/libudns.la: line 9: $'\r': command not found
/usr/lib/libudns.la: line 12: $'\r': command not found
/usr/lib/libudns.la: line 15: $'\r': command not found
/usr/lib/libudns.la: line 18: $'\r': command not found
/usr/lib/libudns.la: line 21: $'\r': command not found
/usr/lib/libudns.la: line 24: $'\r': command not found
/usr/lib/libudns.la: line 29: $'\r': command not found
/usr/lib/libudns.la: line 32: $'\r': command not found
/usr/lib/libudns.la: line 35: $'\r': command not found
/usr/lib/libudns.la: line 39: $'\r': command not found
'ibtool: link: cannot find the library `' or unhandled argument `/c/Users/user/Desktop/shadowsocks-libev-3.0.1/shadowsocks-libev-3.0.1/libipset/
make[2]: *** [Makefile:660: ss-local.exe] Error 1
make[2]: Leaving directory '/c/Users/user/Desktop/shadowsocks-libev-3.0.1/shadowsocks-libev-3.0.1/src'
make[1]: *** [Makefile:467: all-recursive] Error 1
make[1]: Leaving directory '/c/Users/user/Desktop/shadowsocks-libev-3.0.1/shadowsocks-libev-3.0.1'
make: *** [Makefile:375: all] Error 2

user@host /c/Users/user/Desktop/shadowsocks-libev-3.0.1/shadowsocks-libev-3.0.1
$

**Comment by KarlM256** [comment]
Building shadowsocks-libev 2.5.6 with mbedtls workd fine.

**Comment by hellofwy** [comment]
You may need to initialize git submodules, third part codes have been change to git submodules.
Just an advice, may be wrong.

**Comment by cokebar** [comment]
看起来是换行符问题

**Comment by KarlM256** [comment]
Cokebar...

You are correct. It was a line ending problem. I fooled myself by eliminating almost all of the line ending issues and it made no difference. So I stopped thinking about line endings. But when I eliminated all of line ending issues shadowsocks-libev 3.0.1 builds fine.

I'm surprised that this was never an issue before.

Thanks,

...Karl

**Comment by KarlM256** [comment]
Hellofwy...

I understand your comment. Thanks.

However, this causes me concern. If we are building everything from the latest git that is fine. But if I build a shadowsocks-libev release, I should be using released versions of the other dependencies. Otherwise reproducing a problem will be more difficult. For example Madeye's linudns is not released, so it is difficult to describe what I used to build.

**Comment by hosiet** [comment]
@KarlM256
* I believe libudns is versioned with latest version 0.4, released on 2014.
* I believe libudns is not owned by madeye.

**Comment by cokebar** [comment]
@KarlM256 Maybe the line issue is caused by some software on windows, which converted all the "\n" to “\r\n". You can try to download the source again, using cygwin's bash. Do not let any other software touch the files.

**Comment by KarlM256** [comment]
Hi Cokebar...

The cause is that I built it on my desktop (Windows) instead of in my home (Cygwin) directory. I have a text mount on my cygdrive. Once I moved to my home directory for building, all was good.

I'm just surprised it never caused me a problem before.

Thanks,

...Karl

**Comment by cokebar** [comment]
@KarlM256 Strange bug.

**Comment by KarlM256** [comment]
Hi Hosiet...

I agree that it is version 0.4. However madeye has changed/enhanced the build system. So madeye's version is now unique. It is different than grabbing the 0.4 source. I think that grabbing the head version from git as a long term practice will make it hard to identify what code is in a build. This may make duplicating problems more difficult.

I was just wishing that madeye would do a release so the version in git has a named version. 

***Madeye, could you please do an initial release of your modified libudns?***

Then if there is a problem, I can say I built with shadowsocks-libev nnn and mbedtls mmm and libudns qqq. The previous shadowsocks-libev releases contained all of the major pieces so the release version number told more about the built code.

Thanks,

...Karl

**Comment by hqvv** [comment]
you should put the sources in ~ folder, but not in a windows folder .
Use git clone or tar , but not winzip.
Use vim to modify the code but not notepad. 
Windows subsystem for Linux could not work with applications in win10

**Comment by hosiet** [comment]
I found a libudns repository [here](https://github.com/shadowsocks/libudns) but the only change is inside build system. No source code was touched. This is not very meaningful for those using libudns provided by distribution, which has nothing to do with forked version.

**Comment by madeye** [comment]
You'd better fetch the latest libudns here: http://www.corpit.ru/mjt/udns.html.

The udns forked to shadowsocks is only for shadowsocks-android, please don't use it when building on other platforms.

**Comment by KarlM256** [comment]
Thanks to all.
