### ISSUE TITLE
cannt find "config.json" file.

### ISSUE THREAD

**Issue by peteratchifeng** [shadowsocks/shadowsocks-libev#1244]
### What version of shadowsocks-libev are you using?

3.0.1
### What operating system are you using?

openwrt
### What did you do?

ive installed shadowsocks-libev_3.0.0-1_ar71xx.ipk. didnt install the server.xx.ipk.
### What did you expect to see?
wanna know how to config. i cannt find the config.json, when i check opkg list. ss-libev has already installed.

### What did you see instead?
i have found the usr/bin ss-local redir tunnel. but i cannt find the config file.

### What is your config in detail (with all sensitive info masked)?
i cant find it. what should i do. thanks.

**Comment by DevinXian** [comment]
you should edit your own config file, for example: 
  {
    "server": "**.com",
    "server_port": 8002,
    "local": "0.0.0.0",
    "local_port": 1081,
    "password": "********",
    "timeout": 300,
    "method": "aes-256-cfb",
    "fast_open": true
  }

**Comment by peteratchifeng** [comment]
the question is " i cant find the "config.json" file." sth is wrong.
