### ISSUE TITLE
 header checking done wrong

### ISSUE THREAD

**Issue by zhou0** [shadowsocks/shadowsocks-libev#1245]
### What version of shadowsocks-libev are you using?

2.5 

### What operating system are you using?

Fedora

### What did you do?

testing compatibility of my perl shadowsocks client with shadowsocks-libev server.

### What did you expect to see?

It works.

### What did you see instead?

server dropped client connection.

### What is your config in detail (with all sensitive info masked)?

the https://metacpan.org/release/Net-Shadowsocks client does not forward the connect command header to server immediately. Instead, It sends the connect header combined with the first client request. In this way it saves one socket IO operation.  Meanwhile, libev server checks for incomplete header.  But the checking is done wrong.  it compares the length of this data in buffer, which equals to the length of header plus the length of request,   usually a lot more bigger than 80, with 80 , if the buffer length is more than 80, then libev server will drop the client connection.     I think the Net::Shadowsocks::Client behaviour makes sense and should be handled properly.

**Comment by madeye** [comment]
Try 9716eed.

**Comment by madeye** [comment]
After revisiting the code, I don't see anything related to your description. All the data after the handshake header is handled properly in shadowsocks-libev:

https://github.com/shadowsocks/shadowsocks-libev/blob/master/src/server.c#L770

BTW, you may test your code with shadowsocks-python instead. It's the reference design for other implementations.

**Comment by SilverBut** [comment]
Found same bug. Will open a ticket later.

**Comment by zhou0** [comment]
it happens before the handshake.   the following is from server.c of version 2.5

     // handle incomplete header part 2
    if (server->stage == 0) {
        if (is_header_complete(server->buf)) {
            bfree(server->header_buf);
            ss_free(server->header_buf);
            server->stage = 2;
        } else {
            server->stage = 1;
        }
    }

but the is_header_complete call fails  and it causes the perl module client connection being dropped.   The problem is with libev server version 2.5 and up and not present in python version or previous libev version    I  find it because previously working perl client no longer works since libev 2.5. I only find it after testing with version 3.0

**Comment by madeye** [comment]
Interesting. But all the checks have been removed now...
