### ISSUE TITLE
Different behavior under several protocols 

### ISSUE THREAD

**Issue by SilverBut** [shadowsocks/shadowsocks-libev#1247]
### What version of shadowsocks-libev and operating system are you using?

Server A: Ubuntu 16.04 with custom compiled .deb package according to README.md, test under version 3.0.1, 3.0.2 and main branch. AES-256-GCM/CFB, CHACHA20-IETF/IETF-POLY1305 is running on four ports.

Server B: shadowsocks/shadowsocks 2.8.2 with AES-256-CFB

Phone: shadowsocks/shadowsocks-android 3.3.1 from Play Store

Pad: Shadowrocket 2.1.2(300) from AppStore

Computer: Shadowsocks-libev 3.0.0 on Arch Linux with all latest version packages

Problems:

* Phone can not connect to Server A under ANY protocol, but can connect with server B. Error log from server A:
```
SERVERA ss-server[12104]:  2017-02-13 11:24:12 ERROR: failed to handshake with PHONE-IP: invalid host name length
SERVERA ss-server[12104]:  2017-02-13 11:24:13 ERROR: failed to handshake with PHONE-IP: invalid address type
SERVERA ss-server[12104]:  2017-02-13 11:24:13 ERROR: failed to handshake with PHONE-IP: invalid address type
SERVERA ss-server[12104]:  2017-02-13 11:24:13 ERROR: failed to handshake with PHONE-IP: invalid host name length
SERVERA ss-server[12104]:  2017-02-13 11:24:13 ERROR: failed to handshake with PHONE-IP: invalid host name
SERVERA ss-server[12104]:  2017-02-13 11:24:25 ERROR: failed to handshake with PHONE-IP: invalid address type
SERVERA ss-server[12104]:  2017-02-13 11:24:26 ERROR: failed to handshake with PHONE-IP: invalid address type
SERVERA ss-server[12104]:  2017-02-13 11:24:26 ERROR: failed to handshake with PHONE-IP: invalid address type
SERVERA ss-server[12104]:  2017-02-13 11:24:26 ERROR: failed to handshake with PHONE-IP: invalid address type
SERVERA ss-server[12104]:  2017-02-13 11:24:26 ERROR: failed to handshake with PHONE-IP: invalid address type
SERVERA ss-server[12104]:  2017-02-13 11:24:26 ERROR: failed to handshake with PHONE-IP: invalid address type
SERVERA ss-server[12104]:  2017-02-13 11:24:26 ERROR: failed to handshake with PHONE-IP: invalid address type
SERVERA ss-server[12104]:  2017-02-13 11:24:26 ERROR: failed to handshake with PHONE-IP: invalid host name length
SERVERA ss-server[12104]:  2017-02-13 11:24:28 ERROR: failed to handshake with PHONE-IP: invalid address type
SERVERA ss-server[12104]:  2017-02-13 11:24:30 ERROR: failed to handshake with PHONE-IP: invalid address type
SERVERA ss-server[12104]:  2017-02-13 11:24:30 ERROR: failed to handshake with PHONE-IP: invalid address type
SERVERA ss-server[12104]:  2017-02-13 11:29:09 ERROR: failed to handshake with PHONE-IP: invalid address type
SERVERA ss-server[12104]:  2017-02-13 11:29:09 ERROR: failed to handshake with PHONE-IP: invalid address type
```

* Pad and Computer cannot connect with server A under any AEAD protocol. Log from server A:

```
SERVERA ss-server[12111]:  2017-02-13 11:18:07 ERROR: failed to handshake with PC-IP: authentication error
```

* Open a client on server A and connect to itself, okay.

* Open a client on server A and connect to server B, okay.

**Comment by SilverBut** [comment]
BTW, the libsodium and mbedtls is compiled using "Prerequisites" paragraph of README.md, the deb package is using reference from "Build deb package from source" paragraph, and source code is download from "releases/*-source-code.tar.gz"

**Comment by madeye** [comment]
> Server A: Ubuntu 16.04 with custom compiled .deb package according to README.md, test under version 3.0.1, 3.0.2 and main branch. AES-256-GCM/CFB, CHACHA20-IETF/IETF-POLY1305 is running on four ports.

Make sure only use the latest version. There is known bugs in the previous versions.

> Computer: Shadowsocks-libev 3.0.0 on Arch Linux with all latest version packages

Update to the latest version.

**Comment by madeye** [comment]
> Pad: Shadowrocket 2.1.2(300) from AppStore

It's a known bug of shadowrocket. https://github.com/shadowsocks/shadowsocks-libev/issues/1231

**Comment by SilverBut** [comment]
Considering the stability, I'll not care about the version on my computer until Arch's package have been upgarded. Just ignore that.
However the phone using shadowsocks-android still have problems using AES256-CFB, even under 3.0.2

**Comment by madeye** [comment]
> However the phone using shadowsocks-android still have problems using AES256-CFB, even under 3.0.2

Double check your config. I cannot reproduce your issue with 3.3.1 android client and 4.0.2 server.

**Comment by SilverBut** [comment]
Seems strange. Succeed after changing both end's password to '123123123', but failed again after changing it to 'qPlNnACnWzQDw60Y'....let me try to debug it, wait for a while...

**Comment by SilverBut** [comment]
Solved.

 A small bug in my personal patched version of glibc caused when using fread to read 'CnWzQD', it will decode all following characters as base64, and return decoded string to caller. 

Not a problem of ss-libev. Ticket closed.
