### ISSUE TITLE
 host name length checking done wrong

### ISSUE THREAD

**Issue by zhou0** [shadowsocks/shadowsocks-libev#1249]
### What version of shadowsocks-libev are you using?
3.0.1

### What operating system are you using?
Fedora

### What did you do?

use shadowsocks perl client with libev server

### What did you expect to see?

successful connection

### What did you see instead?

 2017-02-13 20:46:22 INFO: tcp server listening at [localhost]:1895
 2017-02-13 20:46:35 INFO: accept a connection
 2017-02-13 20:46:35 INFO: 169
 2017-02-13 20:46:35 INFO: 80
 2017-02-13 20:46:35 ERROR: failed to handshake with ::1: invalid host name length

### What is your config in detail (with all sensitive info masked)?

code from 3.0.1 server.c 

            if (name_len + 4 <= server->buf->len) {
                memcpy(host, server->buf->data + offset + 1, name_len);
                offset += name_len + 1;
            } else {
                report_addr(server->fd, MALFORMED, "invalid host name length");
                close_and_free_server(EV_A_ server);
                return;
            }

169 is client data length, 80 is libev server buffer length.  when client data length is longer than libev server buffer, libev server thinks the client host name is invalid and drops client connection. actually, the client is sending a connect command combined with first request, which is way longer than 80.

**Comment by madeye** [comment]
I don't think there is anything wrong. By the client data length, what do you mean here?

Also, you may try if your client works with  https://github.com/shadowsocks/shadowsocks/tree/master

**Comment by madeye** [comment]
You can also try to print the name_len here.

**Comment by zhou0** [comment]
The client is sending the the target host address type  + host name + port  and the first request ( HTTP or HTTPS , for example ) to server socket buffer in one shot.  Libev server should handle this correctly.

**Comment by madeye** [comment]
I don't think it's your issue. Could you print the name_len here?

**Comment by madeye** [comment]
@zhou0 Actually, every shadowsocks client (Python, Golang, C#) sends the first request as you said.

It's important to send shadowsocks header with the first client request to make sure there is no length pattern for the first packet of shadowsocks protocol.

**Comment by zhou0** [comment]
caused by  incompatibility between cryptographic algorithms . closing it now.
