### ISSUE TITLE
"IP_TRANSPARENT: Operation not permitted", but CAP_NET_ADMIN is enabled.

### ISSUE THREAD

**Issue by enihcam** [shadowsocks/shadowsocks-libev#1252]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
3.0.2

### What operating system are you using?
Archlinux

### What did you do?
-pacman update
-enable reuse_port

### What did you expect to see?
-ss-redir starts in systemd

### What did you see instead?

Feb 14 08:09:19 archnet ss-redir[900]:  2017-02-14 08:09:19 ERROR: [udp] setsockopt IP_TRANSPARENT: 
Feb 14 08:09:19 archnet systemd[1]: shadowsocks-libev-redir@r0.service: Main process exited, code=ex
Feb 14 08:09:19 archnet systemd[1]: Failed to start Shadowsocks-Libev Client Service Redir Mode.

### What is your config in detail (with all sensitive info masked)?
{
    "server":"____",
    "server_port":12345,
    "local_address":"0.0.0.0",
    "local_port":1234,
    "nameserver":"_____",
    "password":"",
    "timeout":60,
    "method":"chacha20-ietf",
    "fast_open":true,
    "reuse_port":true,
    "nofile":16384,
    "mode":"tcp_and_udp"
}

[Unit]
Description=Shadowsocks-Libev Client Service Redir Mode
After=network.target

[Service]
Type=simple
User=nobody
CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
ExecStart=/usr/bin/ss-redir -c /etc/shadowsocks/%i.json

[Install]
WantedBy=multi-user.target

**Comment by enihcam** [comment]
root can start the service, but that is not what we want, right?

**Comment by enihcam** [comment]
would it be more flexible to use socket-base activation?
e.g. shadowsocks-libev-redir.socket

**Comment by madeye** [comment]
`ss-redir` requires ROOT permission to access IP_TRANSPARENT. It's expected.

**Comment by rogers0** [comment]
@enihcam @madeye seems it just need to add a cmd to setcap CAP_NET_ADMIN for ss-redir.

**Comment by enihcam** [comment]
@rogers0, are you saying 'CapabilityBoundingSet=CAP_NET_ADMIN' in the .service does not work?

**Comment by rogers0** [comment]
@enihcam It won't work if you just change that service file.
Please refer:
- https://github.com/shadowsocks/shadowsocks-libev/blob/master/debian/shadowsocks-libev.postinst
We need to change the setcap part of above postinst script.

**Comment by enihcam** [comment]
@rogers0 according to
https://git.archlinux.org/svntogit/community.git/tree/trunk/shadowsocks-libev.install?h=packages/shadowsocks-libev

the setcap step has run already.

**Comment by enihcam** [comment]
@rogers0 could you make the change? @madeye

**Comment by rogers0** [comment]
@enihcam I fixed it by debian postinst script.
seems you're using arch, problem is still there. but you can do it locally by yourself after every install/upgrade:
```shell
sudo setcap cap_net_bind_service,cap_net_admin+ep /usr/bin/ss-redir
````

**Comment by enihcam** [comment]
Thank you @rogers0 . I'm trying to contact the arch package owner to update the post-install script.

**Comment by ky0ncheng** [comment]
echo 3 > /proc/sys/net/ipv4/tcp_fastopen

**Comment by ysy** [comment]
sudo setcap cap_net_bind_service,cap_net_admin+ep /usr/local/bin/ss-redir
