### ISSUE TITLE
Openwrt crypto api 部分 module 移除导致部分算法无法使用

### ISSUE THREAD

**Issue by oxguy** [shadowsocks/shadowsocks-libev#1254]
### What version of shadowsocks-libev are you using?
shadowsocks-libev	3.0.1-1

### What operating system are you using?
ZBT-WG3526  mt7621a
OpenWrt Designated Driver 50104 / LuCI Master (git-17.043.31277-e28660c)  kernel 4.4.14
使用glibc而不是musl
### What did you do?
正常交叉编译后安装

### What did you expect to see?
从openwrt r46483 r46820版本开始，kmod-crypto-aes,kmod-crypto-arc4,kmod-crypto-core不再作为单独的软件包提供，而是在kernel中提供，目前测试下来，在mt7621的dd trunk版本中，wifi的wpa2的aes加密未受到影响，但是shadowsocks似乎受到了影响，aes和rc4-md5相关算法均会报cipher not found 的错误导致不能使用。只能使用chacha20或者salsa20的算法，后者是基于libsodium包的，实测未受到影响。

### What did you see instead?
Mon Feb 13 08:41:52 2017 user.info ss-redir[2005]: initializing ciphers... rc4-md5
Mon Feb 13 08:41:52 2017 user.err ss-redir[2005]: Cipher rc4-md5 not found in crypto library
Mon Feb 13 08:41:52 2017 user.err ss-redir[2005]: Cannot initialize cipher
Mon Feb 13 08:41:52 2017 user.info ss-tunnel[2107]: initializing ciphers... rc4-md5
Mon Feb 13 08:41:52 2017 user.err ss-tunnel[2107]: Cipher rc4-md5 not found in crypto library
Mon Feb 13 08:41:52 2017 user.err ss-tunnel[2107]: Cannot initialize cipher

Mon Feb 13 08:43:12 2017 user.info ss-redir[2459]: initializing ciphers... aes-256-cfb
Mon Feb 13 08:43:12 2017 user.err ss-redir[2459]: Cipher aes-256-cfb not found in crypto library
Mon Feb 13 08:43:12 2017 user.err ss-redir[2459]: Cannot initialize cipher
Mon Feb 13 08:43:12 2017 user.err shadowsocks: ss-redir not running.
Mon Feb 13 08:43:12 2017 user.info ss-tunnel[2490]: initializing ciphers... aes-256-cfb
Mon Feb 13 08:43:12 2017 user.err ss-tunnel[2490]: Cipher aes-256-cfb not found in crypto library
Mon Feb 13 08:43:12 2017 user.err ss-tunnel[2490]: Cannot initialize cipher

Tue Feb 14 00:47:32 2017 user.info ss-redir[6670]: initializing ciphers... chacha20
Tue Feb 14 00:47:32 2017 user.info ss-redir[6670]: UDP relay enabled
Tue Feb 14 00:47:32 2017 user.info ss-redir[6670]: listening at 0.0.0.0:1180
Tue Feb 14 00:47:32 2017 user.info ss-redir[6670]: running from root user
Tue Feb 14 00:47:33 2017 user.info ss-tunnel[6778]: initializing ciphers... chacha20
Tue Feb 14 00:47:33 2017 user.info ss-tunnel[6778]: UDP relay enabled
Tue Feb 14 00:47:33 2017 user.info ss-tunnel[6778]: listening at 0.0.0.0:5151
Tue Feb 14 00:47:33 2017 user.info ss-tunnel[6778]: running from root user

**Comment by madeye** [comment]
It's not an issue of shadowsocks. You may cross-compile your own library here to get those missing ciphers back. If not, try `aes-xxx-ctr` and `aes-xxx-gcm` instead.

**Comment by wongsyrone** [comment]
ss的加密不是由内核模块提供的，是由mbedtls和libsodium共同提供的，你应该是用了没修改过的libmbedtls，那个默认会干掉很多加密，你应该安装 @aa65535 编译的libmbedtls.

**Comment by cod1ingcoding** [comment]
shadowsocks-libev应该用的是libmbedtls、libsodium，和内核的Cryptographic API modules（kmod-crypto-*）没有关系吧？
我是这么理解的
