### ISSUE TITLE
Can I use some of these codes for an open-source project?

### ISSUE THREAD

**Issue by beckno9** [shadowsocks/shadowsocks-libev#1255]
### What version of shadowsocks-libev are you using?
> Well, it's not about my question, so I have nothing to say about that.

### What operating system are you using?
> Windows 10 with Linux Subsystem for Windows

### What did you do?
> I want to use some of these codes in one of my opensource project.

### Details
My project is using GNU LGPL v3, but seems this project is using GNU GPL v3, I need to use some codes from this project without changing my license, so I opened this issue to ask the permission from the developers. I will use a dual-license for some of the code I used from this project, so is it okay?
(But seems I have to change some of the code which I am going to use into C++)
 @riobard @cyfdecyf @lixin9311 @madeye @clowwindy

**Comment by rogers0** [comment]
@beckno9 each src file in one project is not necessarily the same as others.
This project also contains some code under BSD license.
You can take a look at https://github.com/shadowsocks/shadowsocks-libev/blob/master/debian/copyright

So you simply can take one or more src file from this project, and keep it's original license.

**Comment by madeye** [comment]
Not problem from my side.

**Comment by beckno9** [comment]
Thanks! I'll keep the license of the original code.
