### ISSUE TITLE
jessie-backports 安装版本古老不是最新的

### ISSUE THREAD

**Issue by mytts** [shadowsocks/shadowsocks-libev#1262]
Please answer these questions before submitting your issue. Thanks!
jessie-backports 安装版本古老不是最新的
(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What operating system are you using?
debian

### What did you do?

install from jessie-backports
### What did you expect to see?

最新的版本
### What did you see instead?

2.6.3

**Comment by mspencer08** [comment]
In the readme: "Note: The repositories doesn't always contain the latest version. Please build from source if you want the latest version (see below)"

**Comment by mytts** [comment]
thanks @mspencer08  ,please close this issue

**Comment by hellofwy** [comment]
@mytts you can close it yourself.

**Comment by rogers0** [comment]
actually it's not upstream issue, you should ask in debian BTS.

long story short, it's frozen stage for Debian Stretch, so we cannot upgrade stretch version any more, neither for jessie-backports.

I‘ll do it *after* Stretch gets release. Thanks for your patience and support!

**Comment by rogers0** [comment]
try **build_deb.sh** script described in https://github.com/shadowsocks/shadowsocks-libev#build-deb-package-from-source

**Comment by resol341** [comment]
@rogers0 I am assuming you are maintaining the package in jessie-backports. Now that Debian Stretch is released. Could you please help update it? Thanks for your time! Really appreciate it!

**Comment by rogers0** [comment]
@resol341 it's already uploaded, but get stalled in new queue [0]
BTW. It will be put into jessie-backports-sloppy, not jessie-backports, according to Debian's backports rule [1]

[0] https://ftp-master.debian.org/backports-new.html
[1] https://backports.debian.org/Contribute/#index6h3

**Comment by resol341** [comment]
@rogers0 Great! Thanks for your work!
