### ISSUE TITLE
编译deb出错

### ISSUE THREAD

**Issue by zekehao** [shadowsocks/shadowsocks-libev#1267]
谢谢提供的好东西，辛苦了大家。
### What version of shadowsocks-libev are you using?
3.02

### What operating system are you using?
Debian 8 x64

### What did you do?
编译deb出错

### What did you expect to see?
下午都还是好的，手动安装libmbedtls和libsodium后。
在单位编译好了，回到家rebuild vps重新搞，按readme。
但是发现好像这一两个小时更新了，按新命令出错。。
能恢复或提供个旧的么？

### What did you see instead?

> dpkg-checkbuilddeps: Unmet build dependencies: debhelper (>= 10) libsodium-dev (>= 1.0.8~) pkg-config
> dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting

**Comment by rogers0** [comment]
for jessie, please install from jessie-backports repo.

**Comment by zekehao** [comment]
backports repo 上面是老的2.65，没有更新

**Comment by rogers0** [comment]
You choose stable distro, so stay in stable.
Please be consistent.

**Comment by rogers0** [comment]
@zekehao try **build_deb.sh** script described in https://github.com/shadowsocks/shadowsocks-libev#build-deb-package-from-source
