### ISSUE TITLE
Shadowsocks is not reconnecting while ppp0 is lost and re-gains carrier.

### ISSUE THREAD

**Issue by enihcam** [shadowsocks/shadowsocks-libev#1273]
We know this is a very common scenario, but shadowsocks is not reconnecting while ppp0 is lost and re-gains carrier.

Somehow restarting the ss-* service is heavy in my router, so this can be an enhancement if shadowsocks itself can be more persistent (e.g. re-establish the connection internally maybe?)

**Comment by madeye** [comment]
Actually, there is no "reconnecting" in shadowsocks, since it's designed to be a stateless protocol. 

So, I don't think it's an issue of shadowsocks. If you're using scripts to setup transparent proxy, double check the scripts instead.

**Comment by rogers0** [comment]
Actually it's not an issue here. You should report to Debian by command:
```shell
reportbug shadowsocks-libev
```
https://www.debian.org/Bugs/Reporting

Finally we may add a ppp up/down hook script to handle this.

**Comment by rogers0** [comment]
@enihcam I think there's no problem for ss-server, because it should bind to 0.0.0.0, should work for whatever IP address got from PPPoE.

So you problem is only for ss-local, right?

**Comment by enihcam** [comment]
@rogers0 ss-redir actually. any suggestions except restart the service?

**Comment by rogers0** [comment]
@enihcam if you use debian, you can add a post-up entry in /etc/network/interfaces
or add a script under /etc/ppp/ip-up.d/

ubuntu should be similar

**Comment by enihcam** [comment]
thank you @rogers0 , in that case i will need to separate iptable part from ss-* script.
i'll just leave it there because the case is rarely happened.
