### ISSUE TITLE
Reject (instead of ignore) the OTA option, now it's no longer supported

### ISSUE THREAD

**Issue by henrypijames** [shadowsocks/shadowsocks-libev#1275]
Shadowsocks is moving away from OTA towards AEAD, and that's fine. But as a casual observer of the protocol development, I only knew about the addition of AEAD, but didn't realize that OTA has been removed as a consequence. After installing the latest version of shadowsocks-libev, I spend a considerable amount of time debugging why the `auth: true` line in my `config.json` no longer has any effect, until I finally did a `ss-server --help` and saw that `-A` no longer exists.

In order to make clear to older users of OTA that this is no longer supported, I propose that instead of silently ignoring the now obsolete OTA option, shadowsocks-libev immediately terminate if the OTA option is activated (either per command-line, config file, or by any other means). and output an error message stating clearly that OTA is no longer supported.

**Comment by madeye** [comment]
Try c46f10b.

**Comment by henrypijames** [comment]
Reading the code, it seems that you only get the error message with `auth: true` in config file, but not with the `-A` command line parameter - at least not the specific message about OTA being deprecated.
