### ISSUE TITLE
"failed to resolve server name" issues

### ISSUE THREAD

**Issue by blackgear** [shadowsocks/shadowsocks-libev#1278]
### What version of shadowsocks-libev are you using?
2.5.6

### What operating system are you using?
OSX 10.12.3

### What did you do?
Using ACL, bypass a domain without A records

### What did you expect to see?
 2017-02-19 19:26:28 ERROR: getaddrinfo: nodename nor servname provided, or not known

### What did you see instead?
 2017-02-19 18:47:02 ERROR: failed to resolve server name, wait 2 seconds
 2017-02-19 18:47:06 ERROR: failed to resolve server name, wait 4 seconds
 2017-02-19 18:47:14 ERROR: failed to resolve server name, wait 8 seconds
....

### What is your config in detail (with all sensitive info masked)?
ACL:

```
[bypass_all]

[proxy_list]
91.108.4.0/22
91.108.56.0/22
109.239.140.0/24
149.154.160.0/20

(^|\.)appspot\.com$
(^|\.)blogblog\.com$
```

This problem happens when ss-local using ACL and a domain is bypass and without A records.

When the hostname cannot be resolved(i.e., a webpage used a source from an invalid domain like tui.cnzz.net), ss-local will enter "blocking retry" mode, which block the whole program.

If we run ss-local with deamon, it's clear that we have nothing to do unless killall ss-local, and we can not browse that kind of web page anymore. Every time when we click the link, boom~

> when shadowsocks-libev is started by OS (e.g. a daemon service) and network is not ready, shadowsocks-libev will try several times and wait until the network is up.
via https://github.com/shadowsocks/shadowsocks-libev/issues/349,

So the `int keep_resolving` should be set to 0 once it connect to ss-server, or many webpages will block our web.

**Comment by madeye** [comment]
First of all, make sure you're using the latest version.

If you see this log when starting shadowsocks, it's expected. It means your network is not ready.

**Comment by blackgear** [comment]
```
 2017-02-19 18:47:00 INFO: connect to tui.cnzz.net:80
 2017-02-19 18:47:00 INFO: bypass tui.cnzz.net:80
 2017-02-19 18:47:02 ERROR: failed to resolve server name, wait 2 seconds
 2017-02-19 18:47:06 ERROR: failed to resolve server name, wait 4 seconds
 2017-02-19 18:47:14 ERROR: failed to resolve server name, wait 8 seconds
```

This problem happens when ss-local using ACL and bypass a domain without A records. My acl using bypass_all, then https://github.com/shadowsocks/shadowsocks-libev/blob/master/src/local.c#L683 called get_sockaddr tui.cnzz.net and then ss-local keep retrying and block all the program.

Using 2.5.6 but the code is same as 3.0.2

ACL:
```
[bypass_all]

[proxy_list]
91.108.4.0/22
91.108.56.0/22
109.239.140.0/24
149.154.160.0/20

(^|\.)appspot\.com$
(^|\.)blogblog\.com$
```

**Comment by blackgear** [comment]
Seems fixed with this patch:

```
diff --git a/src/local.c b/src/local.c
index cebb951..c10bb0b 100644
--- a/src/local.c
+++ b/src/local.c
@@ -81,7 +81,7 @@
 #endif
 
 int verbose        = 0;
-int keep_resolving = 1;
+int keep_resolving = 0;
 
 #ifdef ANDROID
 int vpn        = 0;
@@ -632,6 +632,7 @@ server_recv_cb(EV_P_ ev_io *w, int revents)
                     }
                     struct sockaddr_storage storage;
                     int err;
+                    keep_resolving = 0;
                     memset(&storage, 0, sizeof(struct sockaddr_storage));
                     if (atyp == 1 || atyp == 4) {
                         err = get_sockaddr(ip, port, &storage, 0);

```

**Comment by madeye** [comment]
It's an old bug caused by this line https://github.com/shadowsocks/shadowsocks-libev/blob/d6c377df9c8053b10276dd2dddf9aceda5f1faf5/src/local.c#L639.

So, first of all, make sure you're using the latest version.

**Comment by ss-plus** [comment]
keep_resolving is a stupid option to cause process lost.
