### ISSUE TITLE
在Xubuntu 16.10为HG255D编译openwrt 15.05的shadowsocks-libev 出错

### ISSUE THREAD

**Issue by daiaji** [shadowsocks/shadowsocks-libev#1279]
homo@homo-VirtualBox:~/OpenWrt-SDK-15.05.1-ramips-rt288x_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64$ git clone https://github.com/aa65535/openwrt-feeds.git package/feed
正克隆到 'package/feed'...
remote: Counting objects: 35, done.
remote: Total 35 (delta 0), reused 0 (delta 0), pack-reused 35
展开对象中: 100% (35/35), 完成.
检查连接... 完成。
homo@homo-VirtualBox:~/OpenWrt-SDK-15.05.1-ramips-rt288x_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64$ git clone https://github.com/shadowsocks/openwrt-shadowsocks.git package/shadowsocks-libev
正克隆到 'package/shadowsocks-libev'...
remote: Counting objects: 1064, done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 1064 (delta 5), reused 0 (delta 0), pack-reused 1048
接收对象中: 100% (1064/1064), 453.51 KiB | 265.00 KiB/s, 完成.
处理 delta 中: 100% (599/599), 完成.
检查连接... 完成。
homo@homo-VirtualBox:~/OpenWrt-SDK-15.05.1-ramips-rt288x_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64$ make menuconfig
make -s -C scripts/config all CC=cc: build failed. Please re-run make with -j1 V=s to see what's going on
/home/homo/OpenWrt-SDK-15.05.1-ramips-rt288x_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/include/toplevel.mk:89: recipe for target 'scripts/config/mconf' failed
make: *** [scripts/config/mconf] Error 1

**Comment by hellofwy** [comment]
https://github.com/shadowsocks/openwrt-shadowsocks

**Comment by daiaji** [comment]
从SDK的名称上来看应该是uClibc SDK啦
于是我按照https://github.com/shadowsocks/openwrt-shadowsocks
来做了
`git clone https://github.com/aa65535/openwrt-feeds.git package/feeds
git clone https://github.com/shadowsocks/openwrt-shadowsocks.git package/shadowsocks-libev
make menuconfig`
就那样报错了
