### ISSUE TITLE
请问什么时候更新Homebrew上的版本

### ISSUE THREAD

**Issue by iciness** [shadowsocks/shadowsocks-libev#1281]
Homebrew上版本还停留在2.6.3，请问何时更新？谢谢

**Comment by maddie** [comment]
This is a Homebrew related question, I guess it's better ask the recipe maintainer which appears to be @ilovezfs or @haodong

**Comment by haodong** [comment]
I'll upload the updates whenever a new stable version is published.

**Comment by madeye** [comment]
Right, please don't submit pre-releases to homebrew.
