### ISSUE TITLE
make & make install 出错

### ISSUE THREAD

**Issue by pingink** [shadowsocks/shadowsocks-libev#1286]
redir.c: 在函数‘main’中:
redir.c:777:11: 错误：未使用的变量‘plugin_args’ [-Werror=unused-variable]
     char *plugin_args = NULL;
           ^
cc1: all warnings being treated as errors
make[2]: *** [ss_redir-redir.o] 错误 1
make[2]: 离开目录“/opt/github/shadowsocks-libev/src”
make[1]: *** [all-recursive] 错误 1
make[1]: 离开目录“/opt/github/shadowsocks-libev”
make: *** [all] 错误 2

**Comment by madeye** [comment]
Update to the latest version.
