### ISSUE TITLE
connect exception

### ISSUE THREAD

**Issue by geekyzk** [shadowsocks/shadowsocks-libev#1287]
### What version of shadowsocks-libev are you using?
wget –no-check-certificate https://raw.githubusercontent.com/teddysun/shadowsocks_install/master/shadowsocks-libev.sh

### What operating system are you using?
centos6.4

### What did you do?
installed,but when use shudownsock connect ,  look google page, it say 
Your client has issued a malformed or illegal request.

### What did you expect to see?
not found log

### What is your config in detail (with all sensitive info masked)?
default config

**Comment by madeye** [comment]
Double check your config. It means your password or cipher is incorrect.

**Comment by geekyzk** [comment]
{
    "server":"0.0.0.0",
    "server_port":8989,
    "local_address":"127.0.0.1",
    "local_port":1080,
    "password":"em.com",
    "timeout":600,
    "method":"aes-256-cfb"
}

in shadowsocket, passwod used em.com. But still prompt the error

**Comment by hellofwy** [comment]
Try to contact the author of the install script you used for help.
Or provide more details about your server and client environment and try to find some log.
