### ISSUE TITLE
支持xchacha20的加密方式吗？

### ISSUE THREAD

**Issue by diaochaju** [shadowsocks/shadowsocks-libev#1289]
这里提到：https://github.com/shadowsocks/shadowsocks-org/wiki/AEAD-Ciphers

**Comment by madeye** [comment]
It depends on what version of libsodium you are using. AFAIK, xchacha20-ietf-poly1305 has not been added into any stable version of libsodium.

**Comment by jedisct1** [comment]
But it's really easy to implement using released versions: https://download.libsodium.org/doc/key_derivation/#nonce-extension
