### ISSUE TITLE
error: required file 'libbloom/Makefile.in' not found

### ISSUE THREAD

**Issue by Eintler** [shadowsocks/shadowsocks-libev#1290]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
3.0.1

### What operating system are you using?
Ubuntu 16.04.2 LTS

### What did you do?
./autogen.sh && ./configure && make

### What did you expect to see?
build correctly

### What did you see instead?

root@default:~/shadowsocks-libev# ./autogen.sh && ./configure && make
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'auto'.
libtoolize: copying file 'auto/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
configure.ac:10: installing 'auto/compile'
configure.ac:12: installing 'auto/missing'
configure.ac:231: error: required file 'libbloom/Makefile.in' not found
libcork/Makefile.am: installing 'auto/depcomp'
autoreconf: automake failed with exit status: 1

**Comment by hillwah** [comment]
`git submodule update --init --recursive`

**Comment by jonwinters** [comment]
@hillwah  submodule increse complexity of compile job , plz consider to remove it .
