### ISSUE TITLE
Compiler error(Couldn't find libev. Try installing libev-dev[el])

### ISSUE THREAD

**Issue by cjl3230** [shadowsocks/shadowsocks-libev#1291]
### What version of shadowsocks-libev are you using?
857bb8def744a1c158056d03194cf1ee78184985

### What operating system are you using?
CentOS release 6.8 (Final)

### What did you do?
git clone https://github.com/shadowsocks/shadowsocks-libev.git
cd shadowsocks-libev
git submodule update --init --recursive
export LIBSODIUM_VER=1.0.11
export MBEDTLS_VER=2.4.0
wget https://github.com/jedisct1/libsodium/releases/download/1.0.11/libsodium-$LIBSODIUM_VER.tar.gz
tar xvf libsodium-$LIBSODIUM_VER.tar.gz
pushd libsodium-$LIBSODIUM_VER
./configure --prefix=/usr && make
sudo make install
popd
wget https://tls.mbed.org/download/mbedtls-$MBEDTLS_VER-gpl.tgz
tar xvf mbedtls-$MBEDTLS_VER-gpl.tgz
pushd mbedtls-$MBEDTLS_VER
make SHARED=1 CFLAGS=-fPIC
sudo make DESTDIR=/usr install
popd

./autogen.sh(I compiled Autoconf 2.69)
./configure --prefix=/usr/local/ss

### What did you expect to see?
No error.

### What did you see instead?
checking for udns.h... yes
checking for dns_dnlen in -ludns... yes
checking ev.h usability... no
checking ev.h presence... no
checking for ev.h... no
configure: error: Couldn't find libev. Try installing libev-dev[el].
(I found  ev.h , but it on path /usr/include/libev/ev.h)

### What is your config in detail (with all sensitive info masked)?
Autoconf 2.69(compiled by sources)
asciidoc 8.4.5(yum)
udns-devel(yum)
libev-devel(yum)
gcc 4.4.7(yum)

**Comment by asmadeus08** [comment]
Try this script https://teddysun.com/357.html It's doing all on the autopilot way.

**Comment by maplesky** [comment]
if installed libev-devel in yum repository, try copy /usr/include/libev/*.* to /usr/include and rebuild shadowsocks-libev project!

**Comment by cjl3230** [comment]
@maplesky I copy /usr/include/libev/ev.h and  /usr/include/libev/ev++.h to /usr/include and rebuild shadowsocks-libev, It's work ok. If project can search the header file directory of libev, It will be better.

**Comment by wongsyrone** [comment]
Background: https://bugzilla.redhat.com/show_bug.cgi?id=985610

> These 2 changes only exist in Fedora: upstream didn't accept them, and other distributions preferred following upstream's decision.
