### ISSUE TITLE
build_deb.sh not working on Ubuntu 16.10 (yakkety)

### ISSUE THREAD

**Issue by Hexcles** [shadowsocks/shadowsocks-libev#1295]
### What version of shadowsocks-libev are you using?
The head of master as of today (44b0eae3efe5a0ba0e4d36b1c4af5a459ca74a5d).

### What operating system are you using?
Ubuntu 16.10 Yakkety AMD64
No third-party repos or manually installed packages (other than the previous version of shadowsocks).

### What did you do?
Run `build_deb.sh` in an empty directory as instructed by the README.

### What did you expect to see?
shadowsocks-libev.deb successfully built.

### What did you see instead?
Error regarding libcork-dev not found. See below for the full output of the script:

```
Hit:1 http://mirrors.digitalocean.com/ubuntu yakkety InRelease
Get:2 http://mirrors.digitalocean.com/ubuntu yakkety-updates InRelease [102 kB]
Get:3 http://security.ubuntu.com/ubuntu yakkety-security InRelease [102 kB]
Get:4 http://mirrors.digitalocean.com/ubuntu yakkety-backports InRelease [102 kB]
Fetched 306 kB in 1s (286 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
equivs is already the newest version (2.0.9+nmu1).
git-buildpackage is already the newest version (0.7.5).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Already on 'master'
Your branch is up-to-date with 'origin/master'.
dh_testdir
dh_testroot
dh_prep
dh_testdir
dh_testroot
dh_install
dh_installdocs
dh_installchangelogs
dh_compress
dh_fixperms
dh_installdeb
dh_gencontrol
dh_md5sums
dh_builddeb
dpkg-deb: building package 'shadowsocks-libev-build-deps' in '../shadowsocks-libev-build-deps_3.0.2+ds-1~exp2_all.deb'.

The package has been created.
Attention, the package has been created in the current directory,
not in ".." as indicated by the message above!
Selecting previously unselected package shadowsocks-libev-build-deps.
(Reading database ... 114078 files and directories currently installed.)
Preparing to unpack shadowsocks-libev-build-deps_3.0.2+ds-1~exp2_all.deb ...
Unpacking shadowsocks-libev-build-deps (3.0.2+ds-1~exp2) ...
Reading package lists...
Building dependency tree...
Reading state information...
Correcting dependencies...Starting pkgProblemResolver with broken count: 1
Starting 2 pkgProblemResolver with broken count: 1
Investigating (0) shadowsocks-libev-build-deps:amd64 < 3.0.2+ds-1~exp2 @iU mK Nb Ib >
Broken shadowsocks-libev-build-deps:amd64 Depends on libcork-dev:amd64 < none | 0.15.0+ds-6 @un uH > (>= 0.15.0+ds-8)
  Removing shadowsocks-libev-build-deps:amd64 because I can't find libcork-dev:amd64
Done
 Done
Starting pkgProblemResolver with broken count: 0
Starting 2 pkgProblemResolver with broken count: 0
Done
The following packages will be REMOVED:
  shadowsocks-libev-build-deps
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 9,216 B disk space will be freed.
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 114082 files and directories currently installed.)
Removing shadowsocks-libev-build-deps (3.0.2+ds-1~exp2) ...
mk-build-deps: Unable to install shadowsocks-libev-build-deps at /usr/bin/mk-build-deps line 402.
mk-build-deps: Unable to install all build-dep packages
gbp:error: Pristine-tar couldn't checkout "shadowsocks-libev_3.0.2+ds.orig.tar.xz": xz: /tmp/pristine-tar.Eu7vAheUy4/shadowsocks-libev_3.0.2+ds.orig.tar.xz.tmp: Cannot allocate memory
pristine-xz: command failed: xz --check=crc64 -z -9 /tmp/pristine-tar.Eu7vAheUy4/shadowsocks-libev_3.0.2+ds.orig.tar.xz.tmp
pristine-tar: command failed: pristine-xz --no-verbose --no-debug --no-keep genxz /tmp/pristine-tar.UHyKid9LGY/wrapper /tmp/pristine-tar.Eu7vAheUy4/shadowsocks-libev_3.0.2+ds.orig.tar.xz.tmp
pristine-tar: failed to generate tarball
HEAD is now at 7386c11 Prepare to release 3.0.2+ds-1~exp2 in experimental
/home/robot/ss-build
dpkg: error: cannot access archive 'shadowsocks-libev_*.deb': No such file or directory
Reading package lists...
Building dependency tree...
Reading state information...
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package shadowsocks-libev-build-deps
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package libcork-build-deps
E: Unable to locate package libcorkipset-build-deps
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package mbedtls-build-deps
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package libsodium-build-deps
Reading package lists...
Building dependency tree...
Reading state information...
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

**Comment by Hexcles** [comment]
`apt search libcork` does find both libcork-dev and libcorkipset-dev.

Besides, I noticed the log said "unable to allocate memory", which is weird as I have more than enough free memory on my VM. I guess it might be a cascading error.

**Comment by rogers0** [comment]
@Hexcles thanks for your report.
If possible, please kindly try to patch the build script as below, then build again.

```patch
index 18ff0de..42c7746 100755
--- a/scripts/build_deb.sh
+++ b/scripts/build_deb.sh
@@ -145,6 +145,8 @@ jessie)
     ;;
 stretch|unstable|sid|yakkety)
     apt_init "git-buildpackage equivs"
+    build_install_libcork debian
+    build_install_libcorkipset debian
     build_install_sslibev
     apt_clean
     ;;
```

**Comment by Hexcles** [comment]
I imagine that would work (sorry I don't have my ssh at the moment and will test later).

Yet I believe the original intention was to use libcork[ipset] from the repo, as the latest Debian/Ubuntu do have them in the official repo. I thought the problem was the version requirement here: https://anonscm.debian.org/git/collab-maint/shadowsocks-libev.git/tree/debian/control#n9

Is there any reason we even need to specify the patch level (`>=ds-8`)? Ubuntu 16.10 only has `ds-6` in the repo, which caused the dependency unmet.

BTW, I see a mismatch between the aforementioned repo on Debian Git (extracted from the script) and the repo here on Github. Is that intentional? Sorry I have been away from this project for a while and am unfamiliar with these recent changes in infrastructure.

**Comment by rogers0** [comment]
@Hexcles you're right.

> Is there any reason we even need to specify the patch level (>=ds-8)? Ubuntu 16.10 only has ds-6 in the repo, which caused the dependency unmet.

Because the soname is bump to libcork16 after ds-8.

> BTW, I see a mismatch between the aforementioned repo on Debian Git (extracted from the script) and the repo here on Github. Is that intentional? Sorry I have been away from this project for a while and am unfamiliar with these recent changes in infrastructure.

Yes, intentional.
I maintain the libcork libcorkipset in Debian, which supports much larger range of systems:
- https://buildd.debian.org/status/package.php?p=shadowsocks-libev

I add a few patches to make it able to build on all ARCHs.

**Comment by Hexcles** [comment]
Hi @rogers0 , I dug into the Debian bug tracker to read a bit more about the SONAME bumping (which seemed a bit absurd to me at first). It was quite a mess. Hats off to you volunteers. And as there are a bunch of hard-coded filenames (libcork16.deb etc.) in the scripts, I see your point to require a newer libcork to avoid possible errors.

The following patch might be more appropriate:

```patch
--- build_deb.sh.orig   2017-02-24 14:53:15.723475795 -0800
+++ build_deb.sh        2017-02-24 15:26:45.495501696 -0800
@@ -143,7 +143,7 @@
        build_install_sslibev
        apt_clean
        ;;
-stretch|unstable|sid|yakkety)
+stretch|unstable|sid)
        apt_init "git-buildpackage equivs"
        build_install_sslibev
        apt_clean
@@ -163,6 +163,13 @@
        build_install_libcork debian
        build_install_libcorkipset debian
        build_install_sslibev
+       apt_clean
+       ;;
+yakkety)
+       apt_init "git-buildpackage equivs"
+       build_install_libcork debian
+       build_install_libcorkipset debian
+       build_install_sslibev
        apt_clean
        ;;
 *)
```

In case I was not clear enough, I was asking about the difference between the shadowsocks-libev repo here and the one on Debian Alioth. Were you talking about libcork or shadowsocks-libev (or both)?

**Comment by Hexcles** [comment]
I've verified 12c4344a420b230be8c5c286176081d4628c0eed fixed this issue. Hence closing this issue for now (but feel free to add any comments).

However, I realized the "unable to allocate memory" error was indeed a separate issue. I was able to circumvent it by adding swap to my VM. I've created a new issue #1300 regarding the memory requirement. @rogers0 , I'd appreciate if you could take a look. Thanks!
