### ISSUE TITLE
Shadowsocks does not treat local SOCKS data as a stream

### ISSUE THREAD

**Issue by sticnarf** [shadowsocks/shadowsocks-libev#1296]
### What version of shadowsocks-libev are you using?

3.0.3, the current HEAD (661429e)

### What operating system are you using?

Ubuntu 16.04.02 LTS x86-64

### What did you do?

As described in [shadowsocks/shadowsocks#769](https://github.com/shadowsocks/shadowsocks/issues/769), I launch a local client of shadowsocks and use a python interactive shell as a socks client.

```bash
$ ./ss-local -s $HOST -p $PORT -k $PASSWD -m chacha20 -l 1080 -v
 2017-02-24 06:59:21 INFO: initializing ciphers... chacha20
 2017-02-24 06:59:21 INFO: listening at 127.0.0.1:1080
```

And the python code:

```python
>>> import socket
>>> s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
>>> s.connect(('127.0.0.1', 1080))
>>> s.send(b'\x05\x01\x00') # Send the connection message
3
>>> s.recv(2) # Successfully received the METHOD selection message
b'\x05\x00'
>>> s.send(b'\x05') # Send the VER part of the request message only
1
```

Then, the shadowsocks client prints out an error message:

```
2017-02-24 07:01:25 ERROR: unsupported addrtype: 101
```

I haven't read the code of shadowsocks-libev, but the cause seems the same.

### What did you expect to see?

The shadowsocks client should wait for more data coming instead of displaying an error message.

### What did you see instead?

An error message, as stated above.

### What is your config in detail (with all sensitive info masked)?

No config file used. All configurations are passed by command line arguments.

**Comment by madeye** [comment]
Unfortunately, it's expected. ss-local works as a local SOCKS5 proxy listening on the loopback, which assume no fragmentation at all for your TCP requests.

**Comment by sticnarf** [comment]
I am aware of the implementation of ss-local. 

I mean, however, TCP is a stream protocol, so doesn't your assumption of no fragmentation seem unreasonable?

**Comment by madeye** [comment]
The fix should be trivial here. But in shadowsocks project, for all the shadowsocks local clients, we just assume no fragmentation on loopback in the handshake stage. Even it looks unreasonable...

**Comment by huashengdun** [comment]
You should check how modern browsers talk to sslocal in real world.
