### ISSUE TITLE
cannot find the library `/usr/lib/libsodium.la' or unhandled argument `/usr/lib/libsodium.la'

### ISSUE THREAD

**Issue by registe** [shadowsocks/shadowsocks-libev#1297]
### What version of shadowsocks-libev are you using?
3.0.3

### What operating system are you using?
CentOS Linux release 7.3.1611

### What did you do?
build rpm package

### What did you expect to see?
https://copr-be.cloud.fedoraproject.org/results/registe/shadowsocks/epel-7-x86_64/00516989-shadowsocks-libev/build.log.gz

```
  CCLD     libshadowsocks-libev.la
  CCLD     ss-local
libtool: link: cannot find the library `/usr/lib/libsodium.la' or unhandled argument `/usr/lib/libsodium.la'
make[2]: *** [libshadowsocks-libev.la] Error 1
make[2]: *** Waiting for unfinished jobs....
libtool: link: cannot find the library `/usr/lib/libsodium.la' or unhandled argument `/usr/lib/libsodium.la'
make[2]: *** [ss-local] Error 1
make[2]: Leaving directory `/builddir/build/BUILD/shadowsocks-libev-3.0.3/src'
make[1]: Leaving directory `/builddir/build/BUILD/shadowsocks-libev-3.0.3'
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
RPM build errors:
error: Bad exit status from /var/tmp/rpm-tmp.kje9Sv (%build)
    Bad exit status from /var/tmp/rpm-tmp.kje9Sv (%build)
Child return code was: 1
EXCEPTION: [Error()]
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/mockbuild/trace_decorator.py", line 89, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.5/site-packages/mockbuild/util.py", line 578, in do
    raise exception.Error("Command failed. See logs for output.\n # %s" % (command,), child.returncode)
mockbuild.exception.Error: Command failed. See logs for output.
 # bash --login -c /usr/bin/rpmbuild -bb --target x86_64 --nodeps /builddir/build/SPECS/shadowsocks-libev.spec
```

I have already installed [libsodium-devel-1.0.11](https://copr-be.cloud.fedoraproject.org/results/registe/shadowsocks/epel-7-x86_64/00509892-libsodium/libsodium-devel-1.0.11-1.el7.centos.x86_64.rpm)

**Comment by registe** [comment]
my mistake, i need to repackage libsodium-devel

**Comment by registe** [comment]
I have repackaged the libsodium-devel which containing **libsodium.la** in the path `/usr/lib64/` on CentOS 7, and still got the error `cannot find the library `/usr/lib/libsodium.la' or unhandled argument `/usr/lib/libsodium.la'`

build log:
[epel 7](https://copr-be.cloud.fedoraproject.org/results/registe/shadowsocks/epel-7-x86_64/00517238-shadowsocks-libev/build.log.gz), [fedora 26 x86_64](https://copr-be.cloud.fedoraproject.org/results/registe/shadowsocks/fedora-26-x86_64/00517238-shadowsocks-libev/build.log.gz), [fedora 26 i386](https://copr-be.cloud.fedoraproject.org/results/registe/shadowsocks/fedora-26-i386/00517238-shadowsocks-libev/build.log.gz), [fedora 25 x86_64](https://copr-be.cloud.fedoraproject.org/results/registe/shadowsocks/fedora-25-x86_64/00517238-shadowsocks-libev/build.log.gz), [fedora 25 i386](https://copr-be.cloud.fedoraproject.org/results/registe/shadowsocks/fedora-25-i386/00517238-shadowsocks-libev/build.log.gz)

**Comment by dover** [comment]
What version of shadowsocks-libev are you using?

3.0.3

What operating system are you using?

Ubuntu 16.10 (GNU/Linux 4.9.4-040904-generic x86_64)

What did you do?

编译安装文件

What did you expect to see?

dpkg-shlibdeps: error: no dependency information found for /usr/lib/libsodium.so.18 (used by debian/shadowsocks-libev/usr/bin/ss-tunnel)
Hint: check if the library actually comes from a package.
dh_shlibdeps: dpkg-shlibdeps -Tdebian/shadowsocks-libev.substvars debian/shadowsocks-libev/usr/bin/ss-server debian/shadowsocks-libev/usr/bin/ss-tunnel debian/shadowsocks-libev/usr/bin/ss-redir debian/shadowsocks-libev/usr/bin/ss-manager debian/shadowsocks-libev/usr/bin/ss-local returned exit code 2
debian/rules:27: recipe for target 'binary' failed
make: *** [binary] Error 2
dpkg-buildpackage: error: debian/rules binary gave error exit status 2

**Comment by librehat** [comment]
It can be reproduced on my fedora with `%configure` macro which expands to
```
./configure --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu         --program-prefix=         --disable-dependency-tracking         --prefix=/usr         --exec-prefix=/usr         --bindir=/usr/bin         --sbindir=/usr/sbin         --sysconfdir=/etc         --datadir=/usr/share         --includedir=/usr/include         --libdir=/usr/lib64         --libexecdir=/usr/libexec         --localstatedir=/var         --sharedstatedir=/var/lib         --mandir=/usr/share/man         --infodir=/usr/share/info
```

If I do `./configure && make -j4` then there is no such error.

**Comment by madeye** [comment]
@librehat Could you try a clean build? Also, please update your `config.log` and output of `make V=99`.

**Comment by librehat** [comment]
I suspect there is some files left from some builds. I can confirm `make clean && make` can solve this issue.

For the record, it should be
```
%configure
make clean
%make_build
```
to make sure the build is clean

But then, `make clean` is not usually required before the first time make...
