### ISSUE TITLE
尝试安装3.0.3版本，安装成功仍为3.0.2版本

### ISSUE THREAD

**Issue by PaPerseller** [shadowsocks/shadowsocks-libev#1298]
### What version of shadowsocks-libev are you using?
3.0.2

### What operating system are you using?
Ubuntu 16.04

### What did you do?
Try to install 3.0.3 version. Run `./build_deb.sh` and install sucessfully. But run `apt-cache show shadowsocks-libev` shows the version is still 3.0.2. And the files named with shadowsocks-libev in `~/build-area` are all shadowsocks-libev_3.0.2*

### What did you expect to see?
Run  `apt-cache show shadowsocks-libev` shows the version is 3.0.3.

**Comment by rogers0** [comment]
@PaPerseller actually 3.0.3 hasn't been supported by build_deb.sh script yet.

**Comment by PaPerseller** [comment]
@rogers0 But if I  build and install directly from source, there will be a dependence problem of debhelper. Ubuntu 16.04 cannot install debhelper 10 and can only install debhelper 9.

**Comment by rogers0** [comment]
@PaPerseller so just be patient to wait for a few days.
or you can also join, to send pull request

**Comment by eastmalon** [comment]
＠PaPerseller
> Ubuntu 16.04 cannot install debhelper 10 and can only install debhelper 9.
so dont go to build debs, `make && sudo make install`

**Comment by simonsmh** [comment]
Please don't misunderstanding other's aim.
Try to use `exp1` branch or `upstream/3.0.3+ds` tag to build package instead of `master` branch.
https://github.com/shadowsocks/shadowsocks-libev/blob/master/scripts/build_deb.sh#L119

**Comment by PaPerseller** [comment]
@simonsmh I will try it. Thank you.

**Comment by simonsmh** [comment]
Wait.
Try https://github.com/shadowsocks/shadowsocks-libev/pull/1299/files first thx.

**Comment by PaPerseller** [comment]
@simonsmh It's work. Thank you.
