### ISSUE TITLE
ss-redir not working with ipv6

### ISSUE THREAD

**Issue by Blaok** [shadowsocks/shadowsocks-libev#130]
I'm running `ss-redir` on an OpenWRT router. I tried to redirect ipv6 packets using `ss-redir` but got such error message:
`2014-xx-xx xx:xx:x ERROR: getdestaddr: No such file or directory`
I tried `root@BlaokWRT:~# curl -6 google.com -v`
And I got:

```
> GET / HTTP/1.1
> User-Agent: curl/7.38.0
> Host: google.com
> Accept: */*
>
```

Then it will timeout. Seems that `ss-redir` can receive but can not deal with ipv6 packets.

ipv4 works fine.
`ss-local` works fine with both ipv4 and ipv6.

Appreciate it if this can be solved.

**Comment by riobard** [comment]
@madeye there's now `IP6T_SO_ORIGINAL_DST`. Guess `ss-redir` can work with IPv6 now?

**Comment by madeye** [comment]
@riobard It should work. But never test.
