### ISSUE TITLE
请问mac端surge如何配置simple-obfs

### ISSUE THREAD

**Issue by Chandler-Lu** [shadowsocks/shadowsocks-libev#1301]
### What version of shadowsocks-libev are you using?
shadowsocks-libev 3.0.3

### What operating system are you using?
MacOS 10.12.3

### What did you do?
使用surge开启simple-obfs，已经按surge作者说的配置了obfs参数，但是服务端未配置obfs的服务器依然可以正常连接。

### What is your config in detail (with all sensitive info masked)?
不知道配置是否正确，obfs是否起效
![1](https://cloud.githubusercontent.com/assets/18322610/23328092/c701d7b8-fb54-11e6-9204-329e0a3c3d45.jpg)
我也尝试了另一种方法来配置：custom,139.xxxxxxx,23333,chacha20,123456,http://proxy.sofi.sh/SSEncrypt.module,obfs = http,obfs-host = www.iqiyi.com，这个配置好像也没有起效果

**Comment by GitHubUi** [comment]
custom,139.xxxxxxx,23333,chacha20,123456,http://proxy.sofi.sh/SSEncrypt.module,obfs=http,obfs-host=bing.com
这个就是对的，至于起没起效果并不是觉得，你去查查浏览记录就知道了。

**Comment by Chandler-Lu** [comment]
额？浏览记录？怎么说0.0

**Comment by GitHubUi** [comment]
用抓包软件看是否生效呀。

**Comment by Chandler-Lu** [comment]
搞定～刚刚用wshark搜bing的时候选错选项了。。我说怎么没有包含bing的包233333
