### ISSUE TITLE
Add option to disable some crypto features

### ISSUE THREAD

**Issue by was4444** [shadowsocks/shadowsocks-libev#1303]
I just fail to compile latest versions(v3.0.x) on my rhel 7 due to some missing crypto dependencies.

It's great that shadowsocks supports so many crypto methods, but it can still work well without some of them, right?

I just wonder, can we add options to disable some crypto features to make it more easily compiled?

**Comment by madeye** [comment]
No plan for this. Please follow the instructions in the README.md to solve all the dependency issues.
