### ISSUE TITLE
libsodium just added support in AVX2 hardware acceleration of chacha20. Please upgrade

### ISSUE THREAD

**Issue by enihcam** [shadowsocks/shadowsocks-libev#1305]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
Git version of shadowsocks-libev, not the package managed by OS.

### What operating system are you using?
Server: Ubuntu
Client: Archlinux

### What did you do?
I found the issue of an enhancement request in adding AVX2 support (https://github.com/jedisct1/libsodium/issues/358) was resolved.

### What did you expect to see?
upgrade of libsodium

### What is your config in detail (with all sensitive info masked)?
method: chacha20-ietf

**Comment by wongsyrone** [comment]
You should wait for next release: v1.0.12
