### ISSUE TITLE
implicit declaration of function 'posix_memalign' when cross compiling for tomato shibby v138 K26RT-N

### ISSUE THREAD

**Issue by oglops** [shadowsocks/shadowsocks-libev#1306]
### What version of shadowsocks-libev are you using?
3.0.3

### What operating system are you using?
centos 7.0 x64

### What did you do?
cross compiling for tomato shibby v138

### What did you expect to see?
correctly compiled

### What did you see instead?
utils.c: In function 'ss_align':
utils.c:237:11: error: implicit declaration of function 'posix_memalign' [-Werror=implicit-function-declaration]
     err = posix_memalign(&tmp, sizeof(void *), size);
           ^
cc1: all warnings being treated as errors
make[1]: *** [libshadowsocks_libev_la-utils.lo] Error 1
make: *** [install-recursive] Error 1

### What is your config in detail (with all sensitive info masked)?
I used a ct-ng toolchain compiled by myself, which works fine for all older versions including 3.0.2, it breaks on 3.0.3 and latest commit. I set
```
# UCLIBC_HAS_ADVANCED_REALTIME is not set
```
in uclibc config when compiling my toolchain, because with this config turned on, 2.6.3 or later compiles fine but when used on router, as soon as client connects, server quits and restart itself, log shows
```
/jffs/ss/ss-server: can't resolve symbol 'posix_memalign' in lib '/jffs/ss/ss-server'.
```

**Comment by madeye** [comment]
Try 5b122d4

**Comment by oglopss** [comment]
Thanks! It seems working.

**Comment by oglops** [comment]
Thanks! It seems working.
