### ISSUE TITLE
HAProxy with ss-manager

### ISSUE THREAD

**Issue by SquirrelCoder** [shadowsocks/shadowsocks-libev#1310]
### What version of shadowsocks-libev are you using?

shadowsocks-libev 2.5.5 with OpenSSL 1.0.1e 11 Feb 2013

### What operating system are you using?

CentOS 7

### What is your config in detail (with all sensitive info masked)?
```
{
    "server":"0.0.0.0",
    "port_password": {
        "1443": "pass1",
        "1444": "pass2",
        "1445": "pass3"
    },
    "timeout":300,
    "method":"chacha20",
    "fast_open": false,
    "workers":1
}

```
my haproxy config

```
global
    ulimit-n    51200
    log         127.0.0.1 local2
    chroot      /var/lib/haproxy
    pidfile     /var/run/haproxy.pid
    user        haproxy
    group       haproxy
    daemon

defaults
    mode                    tcp
    log                     global
    option                  dontlognull
    timeout connect         5s
    timeout client          1m
    timeout server          1m

frontend ss-8888
        bind *:8888
        default_backend ss-1443
backend ss-1443
        server server1 US_VPS_IP:1443  maxconn 20480
```
this is my scenario 
`client <-> Japan VPS <-> US VPS`
I've installed HAProxy on Japan VPS, and Shadowsocks-libev on US VPS, haproxy works perfectly when there is only one connection (e.g. US_VPS_IP:1443), but unfortunately I can't find a way to add the other ports to HAProxy (1444 and 1445), when I add these two lines:

        server server2 US_VPS_IP:1444  maxconn 20480
        server server3 US_VPS_IP:1445  maxconn 20480

to the end of haproxy config, then I can't open any websites.
Is there anyway to use HAProxy with multiple server ports?

Thanks a lot.

**Comment by haodong** [comment]
Drop Haproxy.
Try to use my iptables-forward script: [NATctl](https://github.com/haodong/hdility)
It even support UDP.

**Comment by SquirrelCoder** [comment]
Wow, that's interesting Sir. 
Thanks a lot for sharing. 
Though, I am not sure if it works on CentOS 7 too. Because yours use iptables, but CentOS uses firewalld. 
Habe you tried it on CentOS 7?

Thanks a lot.

**Comment by haodong** [comment]
I just installed a CentOS x64 7 in my VM Machine. With the minimum installation, it brings iptables internally.
If yours has not, try [this](https://www.digitalocean.com/community/tutorials/how-to-migrate-from-firewalld-to-iptables-on-centos-7) and [that](http://stackoverflow.com/questions/24756240/how-can-i-use-iptables-on-centos-7)

**Comment by wxyzh** [comment]
dos port 1443,1444,1445 use the same passoword ?

**Comment by SquirrelCoder** [comment]
@wxyzh no Sir, different password.

**Comment by hellofwy** [comment]
Just add more different `frontend` `backend` pairs.

**Comment by SquirrelCoder** [comment]
@hellofwy did that already, doesn't work :(.
Like this:

```
frontend ss-8889
        bind *:8889
        default_backend ss-1444
backend ss-1444
        server server1 US_VPS_IP:1444  maxconn 20480

```

**Comment by hellofwy** [comment]
Works for me.

May be you have some errors in your configurations. Try confirm if it works without the haproxy.

**Comment by SquirrelCoder** [comment]
@hellofwy I definitely will test again. Thanks.
just to make sure, you mean like this? right?

```
frontend ss-8888
        bind *:8888
        default_backend ss-1443
backend ss-1443
        server server1 US_VPS_IP:1443  maxconn 20480

frontend ss-8889
        bind *:8889
        default_backend ss-1444
backend ss-1444
        server server1 US_VPS_IP:1444  maxconn 

```

Thanks a lot.

**Comment by hellofwy** [comment]
You missed the `maxconn 20480` part, everything else are fine.

My HAProxy version is 1.5.8, and from the Debian 8 repository. If not sure you should check the HAProxy document.

**Comment by SquirrelCoder** [comment]
Okay, thank you all for the replies. It's fixed now. 
The problem was with the Shadowsocks-Qt5 client, unfortunately this client doesn't support this kind of relay. with Shadowsocks-Windows there is no problem, but with shadowsocks-qt5 I get Latency Error!
(For e.g. for about 2 seconds I get a response from server and then latency error!)

If anyone is wondering how to configure properly ss-manager with HAProxy (thanks to @hellofwy)
Scenario

```
client1 <-> Japan VPS <-> US VPS
client2 <-> Japan VPS <-> US VPS

```
this the Shadowsocks-libev config on your US VPS. (you have to change somethings in /lib/systemd/system/shadowsocks-libev.service  so it can reflect the multi user Shadowsocks)
```

{
    "server":"0.0.0.0",
    "port_password": {
        "US_Server_Port_1": "your_password_1",
        "US_Server_Port_2": "your_password_2"
    },
    "timeout":300,
    "method":"encryption_method_goes_here",
    "fast_open": false,
    "workers":1
}
```

now we SSH into the JAPAN VPS, and configure it!
install haproxy on it.
copy & paste the following into the terminal.

`apt update; apt install haproxy
`
first backup the haproxy.cfg:

```
cd /etc/haproxy/
cp haproxy.cfg backup.haproxy.cfg
```
and now empty the haproxy.cfg file (I don't know exactly how haproxy works, if you using haproxy for other things, then do NOT do the following, instead read the docs/tutorials)

echo "" > haproxy.cfg
nano haproxy.cfg

and paste the following (make the necessary changes!)
```

global
        ulimit-n  51200

defaults
        log global
        mode    tcp
        option  dontlognull
        contimeout 1000
        clitimeout 150000
        srvtimeout 150000

frontend ss-CHANGE1
        bind *:CHANGE1
        default_backend ss-CHANGE2
backend ss-CHANGE2
        server server1 CHANGE3:CHANGE2 maxconn 20480


frontend ss-CHANGE1_2
        bind *:CHANGE1_2
        default_backend ss-CHANGE2_2
backend ss-8389
        server server1 CHANGE3:CHANGE2_2 maxconn 20480

```
changes you have to make:

CHANGE1 -> Enter the port you wish to use in your SS-Client.  (FOR THE 1ST Client)
e.g. 1234
CHANGE2 -> Enter the port, your shadowsocks-libev on your US VPS is using. (THE 1ST CLIENT'S PORT!)
e.g. 8388
CHANGE3 -> your US VPS IP goes here. (Obviously the public IP-the one you use to SSH into it!)
e.g. 1.2.3.4
CHANGE1_2 -> Enter the port you wish to use in your SS-Client. (FOR THE 2ND Client)
e.g. 1235
CHANGE2_2 -> Enter the port, your shadowsocks-libev on your US VPS is using. (the first client). (THE 2ND CLIENT'S PORT!)
e.g. 8389

That's all.
I will update the port, If made any mistakes or if I have to make any changes.
