### ISSUE TITLE
don't support i386 architecture

### ISSUE THREAD

**Issue by registe** [shadowsocks/shadowsocks-libev#1312]
### What version of shadowsocks-libev are you using?
version 3.0.3

### What operating system are you using?
fedora 25 i386, fedora 25 x86_64,

### What did you do?
build rpm package

### What is your config in detail (with all sensitive info masked)?

on fedora 25 i386, [detail here...](https://copr-be.cloud.fedoraproject.org/results/registe/shadowsocks/fedora-25-i386/00519856-shadowsocks-libev/build.log.gz)

```
  CCLD     libshadowsocks-libev.la
  CCLD     ss-local
/usr/bin/ld: i386:x86-64 architecture of input file `../libbloom/.libs/libbloom.a(libbloom_la-bloom.o)' is incompatible with i386 output
/usr/bin/ld: i386:x86-64 architecture of input file `../libbloom/.libs/libbloom.a(libbloom_la-MurmurHash2.o)' is incompatible with i386 output
collect2: error: ld returned 1 exit status
Makefile:668: recipe for target 'ss-local' failed
make[2]: *** [ss-local] Error 1
make[2]: *** Waiting for unfinished jobs....
```

on fedora 25 x86_64, there are other errors, [detail here...](https://copr-be.cloud.fedoraproject.org/results/registe/shadowsocks/fedora-25-x86_64/00519856-shadowsocks-libev/build.log.gz)

```
  CCLD     libshadowsocks-libev.la
  CCLD     ss-local
/usr/bin/ld: ../libbloom/.libs/libbloom.a(libbloom_la-bloom.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:669: ss-local] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/builddir/build/BUILD/shadowsocks-libev-3.0.3/src'
make[1]: *** [Makefile:467: all-recursive] Error 1
make[1]: Leaving directory '/builddir/build/BUILD/shadowsocks-libev-3.0.3'
make: *** [Makefile:375: all] Error 2
```

**Comment by wongsyrone** [comment]
https://github.com/jvirkki/libbloom/blob/master/Makefile#L13

**Comment by alanwonder** [comment]
same situation here. anyone can spicifiy  what i should do to avoid this error

**Comment by rogers0** [comment]
> https://github.com/jvirkki/libbloom/blob/master/Makefile#L13

I still have no idea how to add this 32-bit system support to debian/rules
Currently my packaged version only support 64-bit:
- https://github.com/rogers0/libbloom/tree/exp1

Please kindly help if you can. Thanks!

**Comment by Hexcles** [comment]
@rogers0 could you elaborate a bit more what problems you are having? Probably open a new issue to track.

I took a quick look at the Makefile. It seems to me all the `BITS` does is to control the `-m32`/`-m64` argument of the compiler, which is not necessary if you compile on the target platform (say if you compile on i386, then it defaults to `-m32`, while the default on x86_64 is `-m64`), which is why the forked version shadowsocks/libbloom removed the related set-up altogether and used a rather simple automake (Makefile.am).

Are you trying to build the 32bit package on a 64bit machine?

**Comment by rogers0** [comment]
upstream issue: https://github.com/jvirkki/libbloom/issues/6
my packaging (fix): https://github.com/rogers0/libbloom -b mentors

short answer:
-m32/-m64 is for solaris
linux doesn't need it actually
