### ISSUE TITLE
Please add support for Ubuntu 16.04

### ISSUE THREAD

**Issue by jingw222** [shadowsocks/shadowsocks-libev#1314]

**Comment by hellofwy** [comment]
https://github.com/shadowsocks/shadowsocks-libev#debian--ubuntu

**Comment by jingw222** [comment]
But if I remember right It does say "Ubuntu 16.10 and later derivatives", right?

**Comment by hellofwy** [comment]
You need to compile it yourself, or use other's deb package. 
It's not in the official repository, this doesn't mean it doesn't support Ubuntu 16.04.

**Comment by rogers0** [comment]
Just follow the instruction about build_deb.sh script.
