### ISSUE TITLE
在windows上是否有支持AEAD的带GUI客户端？

### ISSUE THREAD

**Issue by fjsmnikola** [shadowsocks/shadowsocks-libev#1315]
are there any client in windows can support AEDE

### What version of shadowsocks-libev are you using?
shadowsocks-libev 3.0.3

### What operating system are you using?
server ubuntu 16.04 LTS
client windows 10 RS2

**Comment by asmadeus08** [comment]
No. Shadowsocks gui that released at 11 JAN support for now only classic ciphers but they are working on it.

**Comment by wxyzh** [comment]
No, you can use  [go-shadowsocks2](https://github.com/shadowsocks/go-shadowsocks2)
