### ISSUE TITLE
Foreign CDNs seem to hang with UDP redirection

### ISSUE THREAD

**Issue by mklnz** [shadowsocks/shadowsocks-libev#1316]
### What version of shadowsocks-libev are you using?
2.6.3

### What operating system are you using?
Raspbian

I'm noticing pages seem to hang or load very slowly whenever there is a CDN involved, For example, https://static.ads-twitter.com/oct.js

DNS lookup does seem to work and it is going through 8.8.8.8 via the method detailed on the README under # Add any UDP rules. Is ss-redir still the recommended way to passthrough DNS or should I be using ss-tunnel instead?

Going to the resource directly or using curl to download it seems completely normal. It also seems very inconsistent. I'm not familiar with iptables enough to be able to diagnose this, so I'm wondering if anyone else have had the same issue and can point me in the right direction.

**Comment by madeye** [comment]
Maybe try `ss-tunnel` to forward all the DNS queries to the remote server.
