### ISSUE TITLE
gbp:error: Couldn't checkout "libbloom_1.4.orig.tar.xz": execution failed: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by dover** [shadowsocks/shadowsocks-libev#1320]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
3.0.3

### What operating system are you using?
Debian 8 x64 (jessie) 

### What did you do?
Build deb package from source

### What did you see instead?
gbp:error: Couldn't checkout "libbloom_1.4.orig.tar.xz": execution failed: [Errno 2] No such file or directory
gbp:error: Couldn't checkout "shadowsocks-libev_3.0.3+ds.orig.tar.xz": execution failed: [Errno 2] No such file or directory

**Comment by rogers0** [comment]
@dover I guess your libbloom clone is not latest
try to do it again in a clean place, please.

**Comment by dover** [comment]
@rogers0 你好

我把系统重装了，然后用./build_deb.sh，仍然是报：

gbp:error: Couldn't checkout "libbloom_1.4.orig.tar.xz": execution failed: [Errno 2] No such file or directory

gbp:error: Couldn't checkout "shadowsocks-libev_3.0.3+ds.orig.tar.xz": execution failed: [Errno 2] No such file or directory

**Comment by rogers0** [comment]
If other ppl can reproduce this pristine-tar related issue, kindly let me know.

**Comment by rogers0** [comment]
@dover maybe you met the same issue as #1382?
check the workaround there. thanks.
