### ISSUE TITLE
希望增加支持中继代理功能

### ISSUE THREAD

**Issue by qiuzi** [shadowsocks/shadowsocks-libev#1321]
公网部署redsocks，本地数据包经过redsocks中继再到SS服务器

ss-load>>>>>>>HK(redsocks)>>>>>>>ss-server

**Comment by Liqianyu** [comment]
目前我用 iptables 转发

**Comment by wxyzh** [comment]
目前我用的haproxy，有个vxtrans做备用。只是不支持UDP

**Comment by qiuzi** [comment]
@Liqianyu  如何实现？

**Comment by Liqianyu** [comment]
@qiuzi 
`echo 1 > /proc/sys/net/ipv4/ip_forward
iptables -t nat -A PREROUTING -p tcp --dport [端口] -j DNAT --to-destination [目标IP:端口]
iptables -t nat -A PREROUTING -p udp --dport [端口] -j DNAT --to-destination [目标IP:端口]
iptables -t nat -A POSTROUTING -p tcp -d [目标IP] --dport [端口] -j SNAT --to-source [本地服务器公网IP]
iptables -t nat -A POSTROUTING -p udp -d [目标IP] --dport [端口] -j SNAT --to-source [本地服务器公网IP]`

**Comment by qiuzi** [comment]
@Liqianyu 这肯定不行 更改麻烦 还必须IP形式 扩展槽也差

**Comment by qiuzi** [comment]
最简单的就是在ss客户端加个中继功能 -T xxx.xxx.xxx.x:10086

**Comment by lixingcong** [comment]
> 最简单的就是在ss客户端加个中继功能 -T xxx.xxx.xxx.x:10086

什么叫最简单。。。写代码都很简单么？

**Comment by qiuzi** [comment]
@lixingcong 思路简单

**Comment by qiuzi** [comment]
@haodong 目标地址不能用域名吗？ 觉得配置起来需要太对变量，可以借鉴系统用户名进行数据拦截转发

**Comment by nadoo** [comment]
https://github.com/nadoo/glider
proxy chain
