### ISSUE TITLE
关于Server使用DNS端口的问题

### ISSUE THREAD

**Issue by KlansyMsniv** [shadowsocks/shadowsocks-libev#1330]
### What version of shadowsocks-libev are you using?
3.0.3 latest version

### What operating system are you using?
CentOS 7.0 x64

### What did you do?
set ss-server listen port to 53 (DNS)

### What did you expect to see?
长期使用该非常规端口，加密流量较大，想问会不会被GFW盯上封IP？

### What did you see instead?
校园网免登录，穿透性增强，延迟降低，限速解除

### What is your config in detail?
{
	"server" : "##.##.##.##" ,
	"server_port" : 53 ,
	"password" : "################" ,
	"method" : "aes-256-gcm" ,
	"timeout" : 30 ,
	"user" : "shadowsocks" ,
	"fast_open" : false ,
	"nameserver" : "8.8.8.8" ,
	"mode" : "tcp_and_udp"
}

**Comment by asmadeus08** [comment]
I have see little but another problem and. Skype portable doesn't connect and show the problem about dns.

**Comment by KlansyMsniv** [comment]
此issue关闭，因为：
短期使用DNS隧道效果较好，但据长期观察，经常会出现TCP被关闭（这次是FIN，非GFW惯用的RST）的情况，偶尔会出现数据包被修改导致AEAD解密失败的情况。
该端口长期稳定性较差，已更换至433（TLS）端口，到目前为止未出现问题，相对于其他端口出奇的稳定，延迟、网速也不差，先用着吧 。

**Comment by KlansyMsniv** [comment]
不能修改评论吗，手误，TLS端口443
