### ISSUE TITLE
Debian 8编译报错 求指导

### ISSUE THREAD

**Issue by moerfutin** [shadowsocks/shadowsocks-libev#1332]
make[2]: Leaving directory /root/shadowsocks-libev-3.0.3/src'
Making all in doc
make[2]: Entering directory /root/shadowsocks-libev-3.0.3/doc'
  GEN      shadowsocks-libev.xml
  File "/usr/bin/asciidoc", line 101
    except KeyError, k: raise AttributeError, k
                   ^
SyntaxError: invalid syntax
make[2]: *** [shadowsocks-libev.xml] Error 1
make[2]: Leaving directory /root/shadowsocks-libev-3.0.3/doc'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory /root/shadowsocks-libev-3.0.3'
make: *** [all] Error 2

Shadowsocks-libev install failed

### What version of shadowsocks-libev are you using?
Shadowsocks 3.0.3

### What operating system are you using?
Debian 8 x64

**Comment by maddie** [comment]
This is an error caused by `asciidoc` calling Python 3 instead of Python 2. You'll have to fix your system's Python environment, or have `/usr/bin/asciidoc` executabled explicitly with Python 2 by editing the file (not recommended).
