### ISSUE TITLE
感觉这里理论上是可能内存泄漏的代码

### ISSUE THREAD

**Issue by tim-le** [shadowsocks/shadowsocks-libev#1334]
https://github.com/tim-le/shadowsocks-libev/blob/master/src/udprelay.c#L462

    if (rp == NULL) {
        LOGE("[udp] cannot bind");
        return -1;
    }

    freeaddrinfo(result);

---------------------
    if (result)
        freeaddrinfo(result);

    if (rp == NULL) {
        LOGE("[udp] cannot bind");
        return -1;
    }

**Comment by madeye** [comment]
https://github.com/tim-le/shadowsocks-libev/blob/master/src/udprelay.c#L1333

It will cause a FATAL exit. So, we're safe here.

Anyway, it should be fixed.

**Comment by tim-le** [comment]
我看到你最后改成这样：
    freeaddrinfo(result);

    return server_sock;

我觉得不对。最后返回的server_sock可能在循环的最后一句里被close(server_sock);了
