### ISSUE TITLE
要求增加前置socks5功能

### ISSUE THREAD

**Issue by qiuzi** [shadowsocks/shadowsocks-libev#1337]

**Comment by terrytw** [comment]
你说话这么霸气，是把自己当产品经理了吗？

**Comment by hqvv** [comment]
try https://github.com/semigodking/redsocks/

**Comment by qiuzi** [comment]
@hqvv 希望能在内部解决

**Comment by pexcn** [comment]
你说话这么霸气，是把自己当产品经理了吗？

**Comment by hqvv** [comment]
你说话这么霸气，是把自己当产品经理了吗？

**Comment by qiuzi** [comment]
TPROXY没法使用OUTPUT链 udp不能转发 @hqvv

**Comment by madeye** [comment]
No plan for this.

**Comment by rule2c** [comment]
你说话这么霸气，是把自己当产品经理了吗？

**Comment by lixingcong** [comment]
上次还嫌iptables转发中转**麻烦**。

**Comment by nadoo** [comment]
https://github.com/nadoo/glider
proxy chain support socks5
