### ISSUE TITLE
Move some default options from systemd service to config file

### ISSUE THREAD

**Issue by vfreex** [shadowsocks/shadowsocks-libev#1339]
The current version of shadowsocks-libev specifies default user 'nobody', group 'nogroup', and udp_relay in systemd service file.
I think it is much harder for an ordinary user to modify the service file.
Since we are able to specify those options in a config file, should we move them to the default config file?

**Comment by madeye** [comment]
They are totally different settings. `nobody` and `nogroup` in the service files means in which user the systemd should start the shadowsocks.

**Comment by vfreex** [comment]
But it has a similar effect as starting with root then switch to another user.
Options defined in this service file will definitely have priority over those in a config file.
Just a thought to centralize the config options.

**Comment by madeye** [comment]
There is always security concern run a program in root even we can drop the privilege after binding the port.

A better way here is using `setcap`, that's what we are doing in the post install script: https://github.com/shadowsocks/shadowsocks-libev/blob/e63de4ce233be4459e3b2ebd116adcf0f6793348/debian/shadowsocks-libev.postinst#L23

**Comment by vfreex** [comment]
I understand your concern. Safety and convenience are always conflicting with each other and we need trade-off.
