### ISSUE TITLE
build newest shadowsocks-libev package for Archlinux

### ISSUE THREAD

**Issue by debiansid** [shadowsocks/shadowsocks-libev#1340]
### What version of shadowsocks-libev are you using?
https://github.com/shadowsocks/shadowsocks-libev/commit/6e069c7edbb495121bf221416a19ce27ced5c1cf

### What operating system are you using?
archlinux 
$ lsb_release -a
LSB Version:	1.4
Distributor ID:	Arch
Description:	Arch Linux
Release:	rolling
Codename:	n/a

### What did you do?
makepkg

### What did you expect to see?
package built successfuly
### What did you see instead?
```
 CC       libshadowsocks_libev_la-tls.lo
  CC       libshadowsocks_libev_la-rule.lo
make[2]: *** No rule to make target '../libbloom/libbloom.la', needed by 'libshadowsocks-libev.la'.  Stop.
make[2]: Leaving directory '/home/ezhang/community/shadowsocks-libev/trunk/src/shadowsocks-libev/src'
make[1]: *** [Makefile:478: all-recursive] Error 1
make[1]: Leaving directory '/home/ezhang/community/shadowsocks-libev/trunk/src/shadowsocks-libev'
make: *** [Makefile:387: all] Error 2
```

### What is your config in detail (with all sensitive info masked)?
the change I made in PKGBUILD
```
pkgname=shadowsocks-libev
pkgver=3.0.3
_commit=6e069c7edbb495121bf221416a19ce27ced5c1cf
pkgrel=1
```
```
prepare() {
  cd  shadowsocks-libev
  git submodule update --init --recursive
}

build() {
  cd "$srcdir/$pkgname"
  sed -i 's|AC_CONFIG_FILES(\[libcork/Makefile libipset/Makefile libbloom/Makefile\])||' configure.ac
  ./autogen.sh
  ./configure --prefix=/usr --enable-shared --enable-system-shared-lib
  make
}

```

**Comment by debiansid** [comment]
prepare() {
  cd  shadowsocks-libev
  git submodule update --init --recursive
}

**Comment by hosiet** [comment]
You are supposed to file a bug report to Arch Linux.

**Comment by debiansid** [comment]
@hosiet 
I have no idea if it is code related.so I am asking here first.
