### ISSUE TITLE
Possibility to lower the required debhelper version for older debian/ubuntu?

### ISSUE THREAD

**Issue by rlei** [shadowsocks/shadowsocks-libev#1344]
### What version of shadowsocks-libev are you using?

master / 3.0.3

### What operating system are you using?

Ubuntu 16.04.02 LTS x64

### What did you do?

Build `.deb` package with `dpkg-buildpackage -b`

### What did you expect to see?

dpkg building completes successfully

### What did you see instead?

`dpkg-buildpackage` failed with

> dpkg-checkbuilddeps: error: Unmet build dependencies: debhelper (>= 10)
> dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
> dpkg-buildpackage: warning: (Use -d flag to override.)

### What is your config in detail (with all sensitive info masked)?

`debhelper` and all other required build deps are already installed, with the exception that `debhelper` of Ubuntu 16.04 is still 9.x while ss-libev's debian package config requires >= 10.

I can still build the deb successfully by overriding with `dpkg-buildpackage -b -d`, and the package seems to be working fine on Ubuntu 16.04.02 LTS. I'm just wondering if it would be possible to lower the version requirement for `debhelper` so that building ss-libev deb for 16.04 LTS would be really painless. Thanks!

**Comment by hosiet** [comment]
@rogers0 You said Ubuntu 16.04 all had backports repository enabled, but this seems not the case.

**Comment by madeye** [comment]
@rogers0 Any thoughts?

**Comment by rogers0** [comment]
I remember I have explained this in other thread.
My new installed 16.04 have backports repo already, but maybe some user upgrade their system from previous ubuntu releases, so there's possibility that some 16.04 user don't have backports repo.
So I already add the backports repo in my build script:
 - https://github.com/shadowsocks/shadowsocks-libev/blob/master/scripts/build_deb.sh#L62

14.04 LTS support will be ended soon, so there's no reason we use debhelper 9.

**Comment by lxyu** [comment]
the backports is set to `manual` mode by default, to enable it, ensure these lines in `/etc/apt/preferences`

```
Package: *
Pin: release a=xenial-backports
Pin-Priority: 500
```

Or install `debhelper` using backports manually:

```
$ sudo aptitude install debhelper/xenial-backports
```

**Comment by rlei** [comment]
Thanks to @rogers0 and @lxyu 's comments. Building deb using `build_deb.sh` worked just fine for me (I should have RTFM more thoroughly). Also, installing `debhelper/xenial-backports` solves the `debhelper` version issue when I just want to use `dpkg-buildpackage` to build the main package.

Therefore I'm closing this ticket now.

**Comment by xiasonming** [comment]
为什么我执行命令sudo aptitude install debhelper/xenial-backports后debhelper版本还是 9.20160115啊？我的运行系统是搬瓦工ubuntu 16.04 。
