### ISSUE TITLE
Debian 8编译成功生成多个deb，是要安装哪个？

### ISSUE THREAD

**Issue by c1024** [shadowsocks/shadowsocks-libev#1346]
### What version of shadowsocks-libev are you using?

3.0.3
### What operating system are you using?
Debian 8 x86_64

我参考 Read.md里面的说明编译deb成功：
但是编译结果有多个deb，请问应该安装哪个？

编译结果如下：
~/build-area$ ls
build_deb.sh
libbloom
libbloom-dev_1.4-1~exp1_amd64.deb
libbloom1_1.4-1~exp1_amd64.deb
libbloom_1.4-1~exp1.debian.tar.xz
libbloom_1.4-1~exp1.dsc
libbloom_1.4-1~exp1_amd64.build
libbloom_1.4-1~exp1_amd64.changes
libbloom_1.4.orig.tar.xz
libshadowsocks-libev-dev_3.0.3+ds-1~exp1_amd64.deb
libshadowsocks-libev2_3.0.3+ds-1~exp1_amd64.deb
shadowsocks-libev
shadowsocks-libev_3.0.3+ds-1~exp1.debian.tar.xz
shadowsocks-libev_3.0.3+ds-1~exp1.dsc
shadowsocks-libev_3.0.3+ds-1~exp1_amd64.build
shadowsocks-libev_3.0.3+ds-1~exp1_amd64.changes
shadowsocks-libev_3.0.3+ds-1~exp1_amd64.deb
shadowsocks-libev_3.0.3+ds.orig.tar.xz
simple-obfs
simple-obfs_0.0.2-1.debian.tar.xz
simple-obfs_0.0.2-1.dsc
simple-obfs_0.0.2-1_amd64.build
simple-obfs_0.0.2-1_amd64.changes
simple-obfs_0.0.2-1_amd64.deb
simple-obfs_0.0.2.orig.tar.gz

**Comment by bdfish** [comment]
*.deb

**Comment by zhou0** [comment]
shadowsocks-libev_3.0.3+ds-1exp1_amd64.deb

**Comment by c1024** [comment]
@zhou0 其他deb有用吗

**Comment by zhou0** [comment]
有用的。

**Comment by c1024** [comment]
@zhou0 simple-obfs是新增的混淆功能用的，其他是做什么用的，知道吗？
