### ISSUE TITLE
想要一个windows的程序！

### ISSUE THREAD

**Issue by xingezhang** [shadowsocks/shadowsocks-libev#1347]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
3.0.3

### What operating system are you using?
windows 10 x64

### What did you expect to see?
我想要一个windows下的ss-local

**Comment by zhou0** [comment]
短的回答：Shadowsocks-libev不支持Windows。
长的回答：你需要Cygwin或者MSYS才能编译Shadowsocks-libev， 而且编译成功了也没用。 我成功编译了但是一运行就崩溃。本来想自己debug然后才提交pull request， 但是主要开发者似乎并不想支持windows也就作罢。

如果你一定要在windows上运行， 试试Python 版 或者 Perl 版。  
Perl 0.9.1 版开始支持Windows。 详见 https://github.com/zhou0/shadowsocks-perl/releases/tag/0.9.1-2

**Comment by madeye** [comment]
Try https://github.com/riobard/go-shadowsocks2/releases/tag/v0.0.6

**Comment by cuteribs** [comment]
ss-libev 从3.0版开始就无法在windows 上编译成功了. 唉.. 作者懒得支持win了?

**Comment by ragnaroks** [comment]
不是有子系统么,可以在那个里面运行,而且吃的资源可以忽略不计

**Comment by necan** [comment]
madeye的只支持Cygwin，Windendless的可以成功在MSYS2-MingW上编译成功，亲测。[https://github.com/Windendless/shadowsocks-libev](https://github.com/Windendless/shadowsocks-libev)
![mark](http://oletc9qyg.bkt.clouddn.com/blog/170920/J7CGIKAeIF.png?imageslim)
