### ISSUE TITLE
Table cipher support

### ISSUE THREAD

**Issue by ValdikSS** [shadowsocks/shadowsocks-libev#1348]
### What version of shadowsocks-libev are you using?

v3.0.3

### What operating system are you using?

Linux

### What did you do?

Use `-m table`

### What did you expect to see?

Shadowsocks starts with table cipher

### What did you see instead?

`ERROR: Table is deprecated`

-----

I'm using shadowsocks on a low-end Linux embedded device where any encryption can significantly affect the throughput. Right now I use v2.5.6 with `-m table` for a simple obfuscation just to circumvent DPI HTTP headers detection and it works fine. However in v3.0.3 I can no longer use `-m table` probably because of recent migration to mbedTLS. Is there a plan to bring back `-m table` support or has it been explicitly dropped?

**Comment by zhou0** [comment]
table is gone,bro.

**Comment by zhou0** [comment]
performance shoul not be a bottleneck here.  rc4 costs about 0.1% cpu on  low-end netbook with atom processors and i also tested the new rc4 replacement cipher called spritz, it costs about 0.3% cpu.  you can give chacha20-ietf a shot and see how it goes. it is said to be only 10% slower than rc4.

**Comment by ValdikSS** [comment]
@zhou0 
>rc4 costs about 0.1% cpu on low-end netbook with atom processors

I'm talking about 200 MHz MIPS device without FPU.

**Comment by ValdikSS** [comment]
@madeye so table cipher is explicitly discouraged? Would you merge it if I reintroduce it again?
