### ISSUE TITLE
How wo listen both IPV6 & IPV4 using command line?

### ISSUE THREAD

**Issue by starleafs** [shadowsocks/shadowsocks-libev#1349]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
3.0.3

### What operating system are you using?
docker

### What did you do?
ss-server -s :: -p 8838 -k test -m aes-256-cfb
ss-server -s ["[::0]", "0.0.0.0"] -p 8838 -k test -m aes-256-cfb

### What did you expect to see?
Cannot listen to both IPV6 and Ipv4, using "::" only listen to IPV6.
 Previous post suggested using "server":["[::0]", "0.0.0.0"] in configure file, however, it does not work under command line.

**Comment by bazingaterry** [comment]
-s :: -s 0.0.0.0

**Comment by qiuzi** [comment]
@bazingaterry  ss-redir ？
