### ISSUE TITLE
Mac OS X 3.0.3版本会报TCP connection timeout，这是正常还是bug?

### ISSUE THREAD

**Issue by c1024** [shadowsocks/shadowsocks-libev#1350]
### What version of shadowsocks-libev are you using?
3.0.3

### What operating system are you using?
Mac Os x 10.11.6

新版使用中发现有时打开网页很慢。我测试服务器是Google cloud的，ping平均60ms,基本不丢包。用chacha20-ietf-poly1305加密，超时设300.测试最高速度可以达到30mbps以上。
用/usr/local/opt/shadowsocks-libev/bin/ss-local -c /usr/local/etc/shadowsocks-libev.json -v运行会发现日志信息经常有TCP connection timeout.这是正常还是bug?

**Comment by debiansid** [comment]
路由器装个 对比下？

**Comment by c1024** [comment]
路由器没这个问题
