### ISSUE TITLE
ss-server can not resolve Domain Name

### ISSUE THREAD

**Issue by mpco** [shadowsocks/shadowsocks-libev#1351]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
v3.0.3

### What operating system are you using?
User Mode Linux in Debian 7.0 x86 

### What did you do?
ss-server -p 12345 -k xxxxx -m chacha20 -v

### What did you expect to see?
it work.

### What did you see instead?
ss-server can not resolve  Domain Name:
 2017-03-12 13:38:31 INFO: IPv6 resolv: temporary failure in name resolution
 2017-03-12 13:38:31 INFO: IPv4 resolv: temporary failure in name resolution
 2017-03-12 13:38:31 ERROR: unable to resolve xxx.com

While I can download file using wget.
The DNS same to be OK.

**Comment by madeye** [comment]
Try `ss-server -p 12345 -k xxxxx -m chacha20 -v -d 8.8.8.8`
