### ISSUE TITLE
chacha20-ietf-poly1305和go版本的AEAD_CHACHA20_POLY1305是同一种cipher吗

### ISSUE THREAD

**Issue by xqdoo00o** [shadowsocks/shadowsocks-libev#1353]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
3.0.3

### What operating system are you using?
ubuntu 16.04LTS

### What did you do?
用iperf3测试cipher性能 如标题所示两种

### What did you expect to see?
cipher 测试

### What did you see instead?
两个都用AES加密的话，iperf 测试没什么差异。
但libev版的chacha20-ietf-poly1305和go版本的AEAD_CHACHA20_POLY1305，iperf测试后者是前者两倍以上。
### What is your config in detail (with all sensitive info masked)?

**Comment by suikatomoki** [comment]
https://github.com/shadowsocks/shadowsocks-org/issues/61
