### ISSUE TITLE
ss-redir on openwrt/lede cannot visit remote internal address.

### ISSUE THREAD

**Issue by zjufrankzhang** [shadowsocks/shadowsocks-libev#1358]
还是用中文说吧
我在远程的服务器上开了一个shadowsocks-libev服务，具有一个内网IP。在远程的公网网关上做了端口映射，所以可以直接访问到ss服务。远程服务器所在的内网IP段为192.168.1.0/24。本地是lede稳定版17.01，安装openwrt-shadowsocks-libev，本地内网IP段为192.168.51.0/24。远程和本地的ss均为v3.0.3。

现在用windows/mac/android客户端，都可以在选择全局代理的情况下，访问192.168.1.0/24这个子网下的网页，公网访问也都显示为远程公网网关的IP，说明服务端配置正常。

问题是，在lede下使用shadowsocks-libev的透明代理功能，访问公网IP时，确实是走的远程公网网关IP。但在访问远程内网IP时，无法联通。已选择代理模式为全局代理，代理自身也是全局代理，甚至添加192.168.1.0/24为强制走代理IP列表，都无法连接到192.168.1.0/24下的任何网页。不论是在路由器本地wget http://192.168.1.1 还是在电脑上用浏览器打开网页，都不行。

因为无法使用ping和traceroute之类的命令，无法得知进一步调试信息。但因为使用客户端时能访问远程内网IP，在使用透明代理时也能访问公网IP，所以初步推测问题出现在透明代理服务这里。希望有人能提供进一步解决问题的思路。如果是故意为之，那能否在强制走代理列表指定的时候，可以依从列表的设置。

**Comment by suikatomoki** [comment]
@aa65535

**Comment by aa65535** [comment]
因为这些保留 IP 端默认是都绕过的，参见[这里](https://github.com/shadowsocks/luci-app-shadowsocks/blob/c27f1ff/files/root/usr/bin/ss-rules#L133-L151), 如果需要 `192.168.1.0/24` 这个网段走 ss ，可以试试:
```
iptables -t nat -I SS_SPEC_LAN_DG 1 -p tcp -d 192.168.1.0/24 -j SS_SPEC_LAN_AC
```

**Comment by zjufrankzhang** [comment]
唉，果然是ipset的问题，这个配置是直接模块调用的吧。试了上面的修改iptables没有用，难道只能重新编译，有没有配置文件之类的修改那些预定义内网IP段？

**Comment by aa65535** [comment]
上面命令应该是在 ss 启动后执行才有效果。

可以修改 `/usr/bin/ss-rules` 对应的部分，去掉 `192.168.0.0/16` 这行，但是不建议去这样做，可能会导致无法访问路由器。

**Comment by zjufrankzhang** [comment]
OK，搞定。确实是修改ss-rules那里就好。然后以我这个情况，我删掉192.168.0.0/16，替换为192.168.32.0/19;192.168.64.0/18;192.168.128.0/17三行，相当于对于192.168.0.0192.168.31.0这32个子网不代理。问题解决
