### ISSUE TITLE
VPN speed connection with SS-libev/SSR cut double!

### ISSUE THREAD

**Issue by asmadeus08** [shadowsocks/shadowsocks-libev#1359]
### What version of shadowsocks-libev are you using?
3.0.3-1

### What operating system are you using?
Ubuntu 16.10

### What did you do?
Installed SS-libev and SSR

### What did you expect to see?
Using SS-libev as proxy for SSR and SSR as proxy for openvpn to cover all internet traffic to system. Cause only with that way skype (last versions) working is normal. Proxifier and ProxyCap is blocking Skype/Line/Viber audio/video call feature. And skype doesnt login with proxifier/proxycap

### What did you see instead?
I wanna see full speed connection as it must to be (650-950KB/s) but when i'm using socks proxy for openvpn it's cut my connection twice.

### What is your config in detail (with all sensitive info masked)?
Standard user config on server and client side as for SS/SSR as for VPN

**Comment by madeye** [comment]
Sorry, but I cannot understand what your problem is. It looks not an issue of shadowsocks-libev at all.

**Comment by asmadeus08** [comment]
Tried to say that shadowsocks slice internet connection speed when i use it as proxy for vpn (need vpn to cover all internet traffic on system). It must to be 900kb/s. And when i'm using ss-libev + proxifier there is full speed but not with ss-libev + openvpn.

**Comment by madeye** [comment]
If so, it should be a problem of OpenVPN. It could be either a TCP over TCP issue or a UDP QoS issue

**Comment by asmadeus08** [comment]
Thought about the same problem. But On server side ss-libev using UDP and Openvpn using TCP. So it's UDP over TCP. UDP pass all speed bandwidth. And i tried also to use this recommendations
socks-proxy 127.0.0.1 1080
route SHADOWSOCKS_SERVER_IP 255.255.255.255 net_gateway 

That's what i got Wed Mar 15 20:05:55 2017 Route: Waiting for TUN/TAP interface to come up...
And doesnt connect.

**Comment by madeye** [comment]
UDP over TCP could be even worse. I don't think you can achieve good performance with your setup.

**Comment by asmadeus08** [comment]
So how to fix problem with skype when i'm using ss-libev + proxifeir cause it's dont wanna work and login. Telling me that there is problem with dns service but all other app works perfect.

**Comment by madeye** [comment]
Try `ss-redir` on a router instead, or just setup a TLS VPN, such as openconnect.

**Comment by asmadeus08** [comment]
My router doesnt support that way. Cause this is tp-link 8968 and doesnt support openwrt.

**Comment by Angel0726** [comment]
> Try `ss-redir` on a router instead, or just setup a TLS VPN, such as openconnect.

how to do it
