### ISSUE TITLE
Key or Password ?

### ISSUE THREAD

**Issue by tporwx** [shadowsocks/shadowsocks-libev#1362]
### What version of shadowsocks-libev are you using?

3.0.3
### What operating system are you using?

Debian8
### What did you do?

add "-- key"
### What is your config in detail (with all sensitive info masked)?

加了key之后还有必要用password吗？
两者应该同时启用还是优先用哪个？

**Comment by madeye** [comment]
When using `--key`, any `--password` would be ignored.
