### ISSUE TITLE
openwrt-shadowsocks-libev can not start after installing v3.0.4

### ISSUE THREAD

**Issue by zjufrankzhang** [shadowsocks/shadowsocks-libev#1364]
The error logs said:
Thu Mar 16 17:36:32 2017 daemon.err uhttpd[941]: Error relocating /usr/bin/ss-redir: crypto_aead_xchacha20poly1305_ietf_decrypt: symbol not found
Thu Mar 16 17:36:32 2017 daemon.err uhttpd[941]: Error relocating /usr/bin/ss-redir: crypto_aead_xchacha20poly1305_ietf_encrypt: symbol not found
Thu Mar 16 17:36:32 2017 daemon.err uhttpd[941]: Error relocating /usr/bin/ss-tunnel: crypto_aead_xchacha20poly1305_ietf_decrypt: symbol not found
Thu Mar 16 17:36:32 2017 daemon.err uhttpd[941]: Error relocating /usr/bin/ss-tunnel: crypto_aead_xchacha20poly1305_ietf_encrypt: symbol not found

注：运行环境,联想y1,mt7620核心
下载方式：直接用opkg install shadowsocks-libev
使用下列软件源安装（公网已用ss代理，能正常访问源），http://openwrt-dist.sourceforge.net/packages/LEDE/base/mipsel_24kc/

已安装下列依赖：
libmbedtls_2.4.2-1_mipsel_24kc.ipk
libudns_0.4-1_mipsel_24kc.ipk

**Comment by zjufrankzhang** [comment]
@aa65535

**Comment by aa65535** [comment]
需要同时安装 libsodium_1.0.12-1

**Comment by zjufrankzhang** [comment]
OK,发现已经安装，不过LEDE17.01稳定版源的libsodium还是1.0.11-2，是因为这个导致的么？发现lede的trunk源也是1.0.11-2，你说的最新版去哪里下载？

**Comment by aa65535** [comment]
@zjufrankzhang 已经上传到 http://openwrt-dist.sourceforge.net/packages/LEDE/base/

**Comment by zjufrankzhang** [comment]
OK，问题解决

**Comment by cokebar** [comment]
@aa65535 同样Ubuntu libsodium是1.0.8 却没有这个问题， 是1.0.11版本有问题？

**Comment by aa65535** [comment]
@cokebar 因为 openwrt-dist 上的 ss 是依赖 libsodium 1.0.12 编译的。

**Comment by cokebar** [comment]
@aa65535 openwrt-dist上libsodium和libmbedtls的可以改成使用lede官方feeds么？

**Comment by aa65535** [comment]
@cokebar 至少 libmbedtls 不能，因为缺少部分加密。

**Comment by cokebar** [comment]
@aa65535 OpenWrt可能不行，但是LEDE是可以的吧，官方版本已经是2.4.2了

**Comment by aa65535** [comment]
@cokebar 不支持 camellia-xxx-cfb 的。

**Comment by cokebar** [comment]
@aa65535 你的哪个patch跟官方的不一样。想起来了之前好想去官方哪里发issue讨论过，rc4/cfb加回来了camellia没有，不知道记错了没。
这就没办法了，不过libsodium我觉得还是降一下比较好，这个已经影响启动程序了比较严重。mbedtls使用官方源的包也不影响启动 顶多用不了这几个加密方式，这几个用的人也不多

**Comment by cokebar** [comment]
@aa65535 已经好多个人问我这个issue的问题了

**Comment by aa65535** [comment]
@cokebar https://github.com/shadowsocks/openwrt-feeds/commit/3c37b2bc67bffea608c791b2f2979952c3527093 降级并不是一个好主意。或许可以等官方升级。

**Comment by cokebar** [comment]
@aa65535 也行吧 lede的package倒是升的蛮快的

**Comment by liaoyangyang** [comment]
@aa65535 今天我用xiaomi mini使用LEDE ss-local还是不行，报一样的错误，我在http://openwrt-dist.sourceforge.net/packages/LEDE/base/mipsel_24kc/没有找到到libsodium_1.0.12-1的包，系统安装的是1.0.11-2，倒是http://openwrt-dist.sourceforge.net/packages/OpenWrt/base/ramips/下面有1.0.12-1，不过不能用，帮忙解决一下吧

附opkg.conf
dest root /
dest ram /tmp
lists_dir ext /var/opkg-lists
option overlay_root /overlay
#option check_signature 1
src/gz openwrt_dist http://openwrt-dist.sourceforge.net/packages/LEDE/base/mipsel_24kc
src/gz openwrt_dist_luci http://openwrt-dist.sourceforge.net/packages/LEDE/luci

**Comment by cokebar** [comment]
@liaoyangyang Try using package in LEDE snapshot:
http://downloads.lede-project.org/snapshots/packages/mipsel_24kc/packages/libsodium_1.0.12-1_mipsel_24kc.ipk

**Comment by liaoyangyang** [comment]
@cokebar Ok，thank you， it works fun
