### ISSUE TITLE
Can ss-libev 3.0.4 run with libsodium lower than 1.0.12?

### ISSUE THREAD

**Issue by cokebar** [shadowsocks/shadowsocks-libev#1365]
### What version of shadowsocks-libev are you using?
3.0.4

### What operating system are you using?
LEDE snapshot

### What did you do?
/etc/init.d/shadowsocks start

### What did you expect to see?
ss-redir starts normally

### What did you see instead?
Error relocating /usr/bin/ss-redir: crypto_aead_xchacha20poly1305_ietf_decrypt: symbol not found

xchacha is implemented by libsodium in v1.0.12. It was only 3 days ago. Most OS's repository haven't update to this version. If  I don't use xchacha20, could ss-libev run without the newest libsodium?

**Comment by simonsmh** [comment]
Yes. It can run on my Debian testing with libsodium 1.0.11.
