### ISSUE TITLE
可以提供一份新版的配置文件参数说明吗？

### ISSUE THREAD

**Issue by millionart** [shadowsocks/shadowsocks-libev#1366]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
3.03

### What operating system are you using?
ubuntu 16.04

### What is your config in detail (with all sensitive info masked)?

从2.5x版本升级以后不知什么原因，shadowsocks服务端完全失效了，但是全程没有任何错误提示……

**Comment by millionart** [comment]
错误查明了，是OTA……
还是希望能有一份完整的config.json的说明，谢谢

**Comment by haodong** [comment]
https://github.com/shadowsocks/shadowsocks-libev/blob/0b9b8d65cede4f15bc056f54ef690a73f3843461/doc/shadowsocks-libev.asciidoc#config-file
