### ISSUE TITLE
Will SS influence the package from OVPN in "OVPN over SS" mode?

### ISSUE THREAD

**Issue by haodong** [shadowsocks/shadowsocks-libev#1367]
Sorry to interrupt, this question may not be very appropriate to be placed here. But I'm wondering that how can I let users of OpenVPN be not able to visit some websites. The reason I put it here is because it's an "OVPN over SS over KcpTun" mode and noticed your (@madeye) [answer](https://www.v2ex.com/t/49630). But that implement did not work on my server. Maybe you can give me more hint about that? Thanks!

### What version of shadowsocks-libev are you using?
NA

### What operating system are you using?
Debian

### What did you do?
OVPN over SS over KcpTun

### What did you expect to see?
Let users of OpenVPN be not able to visit some websites.

### What did you see instead?
The existing iptables action has no effect.

### What is your config in detail (with all sensitive info masked)?
NA

**Comment by madeye** [comment]
I don't think it's related to shadowsocks-libev. For iptables rules, stackoverflow is the best place to ask questions.
