### ISSUE TITLE
ss-redir can not run under nobody on ArchLinux

### ISSUE THREAD

**Issue by debiansid** [shadowsocks/shadowsocks-libev#1369]
### What version of shadowsocks-libev are you using?
3.0.4

### What operating system are you using?
ArchLinux

### What did you do?
systemctl start shadowsocks-libev-redir@config

### What did you expect to see?
ss-redir running

### What did you see instead?
```
Mar 17 09:33:17 archlinux systemd[1]: shadowsocks-libev-redir@config.service: Unit entered failed state.
```

### What is your config in detail (with all sensitive info masked)?
```
[Unit]
Description=Shadowsocks-Libev Client Service Redir Mode
After=network.target

[Service]
Type=simple
User=nobody
CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
ExecStart=/usr/bin/ss-redir -c /etc/shadowsocks/%i.json -b 0.0.0.0 -u

[Install]
WantedBy=multi-user.target
```
after I changed `User=nobody_` into `User=root` , it can be started.

**Comment by debiansid** [comment]
btw,my ss-redir running at  port 1080

**Comment by rogers0** [comment]
@debiansid you need to run something similar to:
- https://github.com/shadowsocks/shadowsocks-libev/blob/master/debian/shadowsocks-libev.postinst#L23

**Comment by debiansid** [comment]
more shadowsocks-libev-server\@config.service 
[Unit]
Description=Shadowsocks-Libev Server Service
After=network.target

[Service]
Type=simple
User=root
CapabilityBoundingSet=CAP_NET_BIND_SERVICE
ExecStart=/usr/bin/ss-server -c /etc/shadowsocks/%i.json

[Install]
WantedBy=multi-user.target

[root@archlinux-vultr multi-user.target.wants]#

**Comment by debiansid** [comment]
You mean I need run it manually,right?

**Comment by rogers0** [comment]
@debiansid yes, but only run that setcap part of postinst script under root , others are not relevant.

**Comment by debiansid** [comment]
@rogers0 
that fixed by my problem, thanks.
why `CapabilityBoundingSet=CAP_NET_BIND_SERVICE` in @service file did not work?
