### ISSUE TITLE
 从源代码构建deb包怎麽解决   debhelper（> = 10）问题

### ISSUE THREAD

**Issue by xiasonming** [shadowsocks/shadowsocks-libev#1371]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
3.04

### What operating system are you using?
Ubuntu 16.04 LTS x64

### What did you do?
./autogen.sh && dpkg-buildpackage -b -us -uc
和
sudo aptitude install debhelper/xenial-backports

### What did you expect to see?
源代码构建deb包成功完成

### What did you see instead?
pkg-source --before-build shadowsocks-libev
dpkg-checkbuilddeps: 错误: Unmet build dependencies: debhelper (>= 10)
dpkg-buildpackage: 警告: build dependencies/conflicts unsatisfied; aborting

root@localhost:~# sudo aptitude install debhelper/xenial-backports
无法找到存档“xenial-backports”，该存档用于软件包“debhelper”
无法找到存档“xenial-backports”，该存档用于软件包“debhelper”
将不会安装，升级或者删除任何软件包。
0 个软件包被升级，新安装 0 个， 0 个将被删除， 同时 104 个将不升级。
需要获取 0 B 的存档。 解包后将要使用 0 B。

### What is your config in detail (with all sensitive info masked)?
debhelper和所有其他必需的build deps已经安装，除了debhelperUbuntu 16.04仍然是9.20160115，而ss-libev的debian软件包配置需要> = 10，  执行命令`sudo aptitude install debhelper/xenial-backports`后提示‘无法找到存档“xenial-backports”，该存档用于软件包“debhelper”’

**Comment by guochunyang** [comment]
从源码开始编译吧。。。

我用的也是 Ubuntu 16.04 
```
cd shadowsocks-libev
sudo apt-get install --no-install-recommends devscripts equivs
mk-build-deps --root-cmd sudo --install --tool "apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends -y"
./autogen.sh && dpkg-buildpackage -b -us -uc
cd ..
sudo dpkg -i shadowsocks-libev*.deb
```

最后一步时有些小问题，确实两个依赖，用 apt-get 安装一下然后重新执行就好了

**Comment by xiasonming** [comment]
我下的是最新源码进行编译的，你说的是用apt-get安装哪两个依赖？

**Comment by cokebar** [comment]
@guochunyang 
`mk-build-deps --root-cmd sudo --install --tool "apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends -y"`这一步就会报错：
```
mk-build-deps --root-cmd sudo --install --tool "apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends -y"
dh_testdir
dh_testroot
dh_prep
dh_testdir
dh_testroot
dh_install
dh_installdocs
dh_installchangelogs
dh_compress
dh_fixperms
dh_installdeb
dh_gencontrol
dh_md5sums
dh_builddeb
dpkg-deb: building package 'shadowsocks-libev-build-deps' in '../shadowsocks-libev-build-deps_3.0.4-1_all.deb'.

The package has been created.
Attention, the package has been created in the current directory,
not in ".." as indicated by the message above!
Selecting previously unselected package shadowsocks-libev-build-deps.
(Reading database ... 211814 files and directories currently installed.)
Preparing to unpack shadowsocks-libev-build-deps_3.0.4-1_all.deb ...
Unpacking shadowsocks-libev-build-deps (3.0.4-1) ...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Correcting dependencies...Starting pkgProblemResolver with broken count: 1
Starting 2 pkgProblemResolver with broken count: 1
Investigating (0) shadowsocks-libev-build-deps [ amd64 ] < 3.0.4-1 > ( devel )
Broken shadowsocks-libev-build-deps:amd64 Depends on debhelper [ amd64 ] < 9.20160115ubuntu3 | 10.2.2ubuntu1~ubuntu16.04.1 > ( devel ) (>= 10)
  Considering debhelper:amd64 3 as a solution to shadowsocks-libev-build-deps:amd64 -2
  Removing shadowsocks-libev-build-deps:amd64 rather than change debhelper:amd64
Done
 Done
Starting pkgProblemResolver with broken count: 0
Starting 2 pkgProblemResolver with broken count: 0
Done
The following packages will be REMOVED:
  shadowsocks-libev-build-deps
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 9,216 B disk space will be freed.
(Reading database ... 211817 files and directories currently installed.)
Removing shadowsocks-libev-build-deps (3.0.4-1) ...
mk-build-deps: Unable to install shadowsocks-libev-build-deps at /usr/bin/mk-build-deps line 402.
mk-build-deps: Unable to install all build-dep packages
```

**Comment by debiansid** [comment]
Lower that number in Debian/control

**Comment by xiasonming** [comment]
@debiansid 值得一试，谢谢你的帮助！

**Comment by xiasonming** [comment]
@cokebar 
确实是这样。
