### ISSUE TITLE
ss-server does not start

### ISSUE THREAD

**Issue by khumarahn** [shadowsocks/shadowsocks-libev#1372]
### What version of shadowsocks-libev are you using?
3.0.4

### What operating system are you using?
gentoo arm

### What did you do?
```
$ ss-server -v -i eth0 -s "127.0.0.1" -p 1080 -l 1081 -k "abcd"
 2017-03-17 00:16:23 INFO: initializing ciphers... rc4-md
```

### What did you expect to see?
ss-server working

### What did you see instead?
ss-server does not work and does not respond to ctrl+c or kill. Can be killed with kill -9.

### What is your config in detail (with all sensitive info masked)?
no config used

I would be happy to provide any other info.

**Comment by khumarahn** [comment]
It is tough to use github on the phone. Sorry for the mess that was here.

**Comment by rogers0** [comment]
@khumarahn you need to run something similar to:
- https://github.com/shadowsocks/shadowsocks-libev/blob/master/debian/shadowsocks-libev.postinst#L23

**Comment by khumarahn** [comment]
Hi, I ran the script setting capabilities.
```
# getcap /usr/bin/ss-*
/usr/bin/ss-local = cap_net_bind_service+ep
/usr/bin/ss-redir = cap_net_bind_service,cap_net_admin+ep
/usr/bin/ss-server = cap_net_bind_service+ep
/usr/bin/ss-tunnel = cap_net_bind_service+ep
```

But nothing changed.

**Comment by rogers0** [comment]
run:
```shell
sudo netstat -npl|grep 1080
```
to check whether port 1080 is already used.

**Comment by khumarahn** [comment]
output of `netstat -npl|grep 1080` is empty

**Comment by rogers0** [comment]
@khumarahn I run out of idea. maybe other developer here can help you.

**Comment by debiansid** [comment]
nothing in log?

**Comment by khumarahn** [comment]
nothing in dmesg or /var/log/messages

**Comment by debiansid** [comment]
try  archlinuxarm , see where it goes

**Comment by khumarahn** [comment]
arch linux arm is not an option at the moment.

I added some more logging, and can see that the program gets stuck in `sodium_init()`

I have no idea what to do.

**Comment by khumarahn** [comment]
Apparently libsodium fails basic tests on my system. I reproduced it in a very basic case and created an issue: https://github.com/jedisct1/libsodium/issues/513

**Comment by khumarahn** [comment]
I got help with libsodium. It turned out that  libsodium could not init because of the lack of entropy. It has been solved by running haveged. Now shadowsocks works too.

**Comment by jedisct1** [comment]
Code similar to [this check](https://github.com/jedisct1/dnscrypt-proxy/blob/a255d2908305739b54dafb01ae0285f6016869ab/src/proxy/app.c#L342) could be added to shadowsocks-libev.

**Comment by debiansid** [comment]
@khumarahm
Glad you sorted it out

**Comment by wongsyrone** [comment]
@jedisct1 Added via https://github.com/shadowsocks/shadowsocks-libev/commit/1e91b6a1f68baea5ffc90dfaa45bb7d4c37bba55 and https://github.com/shadowsocks/shadowsocks-libev/commit/836d2f3859b643f76b50eb85e272ea54ea03f6e5

**Comment by rogers0** [comment]
@wongsyrone thanks for the fix!
