### ISSUE TITLE
ss-server can not be started

### ISSUE THREAD

**Issue by pigpigabc123** [shadowsocks/shadowsocks-libev#1373]
**What version of shadowsocks-libev are you using?**

3.0.4
build from source follow suggested commond using CentOS 7.3.1611 x64:

yum install epel-release -y
yum install gcc gettext autoconf libtool automake make pcre-devel asciidoc xmlto udns-devel libev-devel -y

export LIBSODIUM_VER=1.0.12
wget https://download.libsodium.org/libsodium/releases/libsodium-$LIBSODIUM_VER.tar.gz
tar xvf libsodium-$LIBSODIUM_VER.tar.gz
pushd libsodium-$LIBSODIUM_VER
./configure --prefix=/usr && make
sudo make install
popd
sudo ldconfig

export MBEDTLS_VER=2.4.2
wget https://tls.mbed.org/download/mbedtls-$MBEDTLS_VER-gpl.tgz
tar xvf mbedtls-$MBEDTLS_VER-gpl.tgz
pushd mbedtls-$MBEDTLS_VER
make SHARED=1 CFLAGS=-fPIC
sudo make DESTDIR=/usr install
popd
sudo ldconfig

./autogen.sh && ./configure && make
sudo make install

**What operating system are you using?**

CentOS 7.3.1611 x64

**What did you do?**

auto start via supervisor
my supervisor conf file:
[program:shadowsocks]
user=root
command=/usr/local/bin/ss-server -c /etc/shadowsocks.json
process_name=%(program_name)s
autostart=true
redirect_stderr=true
stdout_logfile=/var/log/shadowsocks.log
stdout_logfile_maxbytes=1MB
stdout_logfile_backups=0

/etc/shadowsocks.json:
{
    "server":"0.0.0.0",
    "server_port":12457,
    "local_address": "127.0.0.1",
    "local_port":1080,
    "password":"0998988743",
    "timeout":60,
    "method":"chacha20",
    "fast_open": false
}

**What did you expect to see?**

ss-server auto start when the OS start

**What did you see instead?**

ss-server does not seem to work 
the "shadowsocks.log" shows:
 2017-03-17 13:07:15 INFO: initializing ciphers... chacha20
nothing else.

**Comment by madeye** [comment]
Try the latest version.

**Comment by pigpigabc123** [comment]
Problem solved via installing “haveged”
[https://github.com/jedisct1/libsodium/issues/513](url)
