### ISSUE TITLE
Problem about plugin in config file.

### ISSUE THREAD

**Issue by mpco** [shadowsocks/shadowsocks-libev#1374]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
20170318 git clone version

### What operating system are you using?
Debian 8

### What did you do?
ss-server -c  /etc/shadowsocks-libev/config.json -v

{
    "server":"VPS IP",
    "server_port":8123,
    "local_port":1080,
    "password":"xxx",
    "timeout":60,
    "method":"chacha20",
    **"plugin":"obfs-server",**
    **"plugin-opts":"obfs=http"**
}

### What did you expect to see?
It work.

### What did you see instead?

2017-03-17 15:57:08 ERROR: failed to handshake with 127.0.0.1: invalid address type
 2017-03-17 15:57:08 INFO: current server connection: 0
 2017-03-17 15:57:08 [simple-obfs] ERROR: remote recv: Connection reset by peer

But, when the plugin config is:

{
    "server":"VPS IP",
    "server_port":8123,
    "local_port":1080,
    "password":"xxx",
    "timeout":60,
    "method":"chacha20",
    **"plugin":"obfs-server --obfs http"**
}
work very well.

**Comment by suikatomoki** [comment]
plugin-opts to plugin_opts

**Comment by Sakura3754** [comment]
I also have this mistake in my config file , and I take hours to resolve it
