### ISSUE TITLE
使用apt install shadowsocks-libev最新的版本才2.4.8？

### ISSUE THREAD

**Issue by yjqiang** [shadowsocks/shadowsocks-libev#1375]
如题。是否该更新了呢？

**Comment by lixingcong** [comment]
https://github.com/shadowsocks/shadowsocks-libev#install-from-repository

**Comment by rogers0** [comment]
apt install -t jessie-backports shadowsocks-libev

**Comment by rogers0** [comment]
I see, you must use yakkety, not jessie.
 - https://launchpad.net/ubuntu/+source/shadowsocks-libev

So you need to compile yourself if you need newer packages

**Comment by yjqiang** [comment]
Got it. Thank you.

**Comment by debiansid** [comment]
This is why I am going to arch

**Comment by hosiet** [comment]
The reason is simple: there is a Debian Maintainer actively maintaining ss-libev in Debian and an Arch Linux Developer maintaining ss-libev in Arch Linux, but no Ubuntu Developer is doing that for Ubuntu. 

In Ubuntu, ss-libev is migrated permissively from Debian with no further updates.
