### ISSUE TITLE
当 ss-redir 开启 TCP Fast Open 的时候下载文件不完整

### ISSUE THREAD

**Issue by pexcn** [shadowsocks/shadowsocks-libev#1376]
每次下载一个文件，下载到大概 15MB 的时候就提示下载完整了。(OpenWrt 版本)

**Comment by niclau** [comment]
I have the same issue on Openwrt.

**Comment by madeye** [comment]
Try cfe8304.

**Comment by pexcn** [comment]
已测试，现在没问题了。

**Comment by cokebar** [comment]
@pexcn 我也准备尝试tfo。问个问题，当服务器端开启tfo时，客户端是否必须开启tfo才能连接？还是说存在向下兼容：客户端不开启tfo也能连接？

**Comment by pexcn** [comment]
客户端不开也能

**Comment by suikatomoki** [comment]
@cokebar 兼容 同时开启才会使用

**Comment by cokebar** [comment]
@pexcn @suikatomoki 谢谢两位的说明 回头我就打开

**Comment by enihcam** [comment]
Please update version number, since this is critical but many distros are not willing to backport the fix.

**Comment by rogers0** [comment]
If you know a specific patch (or a few patches) that can fix a specific issue, just let me know.
I can backport it to debian stretch. 2.6.3-ds will be supported for years.

**Comment by enihcam** [comment]
@rogers0 I wish if you are working for Archlinux. :P
