### ISSUE TITLE
Ubuntu编译错误

### ISSUE THREAD

**Issue by Galaxy0419** [shadowsocks/shadowsocks-libev#1378]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
3.0.4

### What operating system are you using?
Ubuntu 16.10 

### What did you see instead?
ss_local-aead.o: In function `aead_cipher_decrypt':
/root/shadowsocks-libev/src/aead.c:246: undefined reference to `crypto_aead_xcha                                                                                                                     cha20poly1305_ietf_decrypt'
ss_local-aead.o: In function `aead_cipher_encrypt':
/root/shadowsocks-libev/src/aead.c:207: undefined reference to `crypto_aead_xcha                                                                                                                     cha20poly1305_ietf_encrypt'
collect2: error: ld returned 1 exit status
Makefile:677: recipe for target 'ss-local' failed
make[2]: *** [ss-local] Error 1
make[2]: Leaving directory '/root/shadowsocks-libev/src'
Makefile:479: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/root/shadowsocks-libev'
Makefile:388: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by triaqu** [comment]
我也遇到这个问题，因为是install和编译安装libsodium-dev了多次，在apt-get purge  libsodium-dev后尽然就通过了。

**Comment by lixingcong** [comment]
apt-get purge libsodium-dev
	git clone https://github.com/jedisct1/libsodium
	cd libsodium
	./autogen.sh
	./configure
	sudo make install

**Comment by rogers0** [comment]
"make install" is the way not maintainable.
What to do if suddenly there's a security hole found in this package?

Don't do dirty hack.
