### ISSUE TITLE
build_deb.sh can not built the shadowsocks-libev.deb in Ubuntu 16.10 

### ISSUE THREAD

**Issue by juneszh** [shadowsocks/shadowsocks-libev#1382]
root@vu:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:  Ubuntu 16.10
Release:  16.10
Codename: yakkety
root@vu:~/build-area# ./build_deb.sh
Hit:1 http://archive.ubuntu.com/ubuntu yakkety InRelease
Get:2 http://security.ubuntu.com/ubuntu yakkety-security InRelease [102 kB]
Get:3 http://archive.ubuntu.com/ubuntu yakkety-updates InRelease [102 kB]          
Get:4 http://archive.ubuntu.com/ubuntu yakkety-backports InRelease [102 kB]
Fetched 306 kB in 1s (279 kB/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
equivs is already the newest version (2.0.9+nmu1).
git-buildpackage is already the newest version (0.7.5).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
Switched to branch 'debian'
Your branch is up-to-date with 'origin/debian'.
dh_testdir
dh_testroot
dh_prep
dh_testdir
dh_testroot
dh_install
dh_installdocs
dh_installchangelogs
dh_compress
dh_fixperms
dh_installdeb
dh_gencontrol
dpkg-gencontrol: warning: File::FcntlLock not available; using flock which is not NFS-safe
dh_md5sums
dh_builddeb
dpkg-deb: building package 'libcork-build-deps' in '../libcork-build-deps_0.15.0+ds-11_all.deb'.

The package has been created.
Attention, the package has been created in the current directory,
not in ".." as indicated by the message above!
(Reading database ... 101067 files and directories currently installed.)
Preparing to unpack libcork-build-deps_0.15.0+ds-11_all.deb ...
Unpacking libcork-build-deps (0.15.0+ds-11) over (0.15.0+ds-11) ...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Starting pkgProblemResolver with broken count: 0
Starting 2 pkgProblemResolver with broken count: 0
Done
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up libcork-build-deps (0.15.0+ds-11) ...
**gbp:error: Pristine-tar couldn't checkout "libcork_0.15.0+ds.orig.tar.xz":** 
HEAD is now at 46b7c76 Merge tag 'debian/0.15.0+ds-10_bpo8+1'
/root/build-area
**dpkg: error: cannot access archive 'libcork-dev_*.deb': No such file or directory**
Switched to branch 'debian'
Your branch is up-to-date with 'origin/debian'.
dh_testdir
dh_testroot
dh_prep
dh_testdir
dh_testroot
dh_install
dh_installdocs
dh_installchangelogs
dh_compress
dh_fixperms
dh_installdeb
dh_gencontrol
dpkg-gencontrol: warning: File::FcntlLock not available; using flock which is not NFS-safe
dh_md5sums
dh_builddeb
dpkg-deb: building package 'libcorkipset-build-deps' in '../libcorkipset-build-deps_1.1.1+20150311-7_all.deb'.

The package has been created.
Attention, the package has been created in the current directory,
not in ".." as indicated by the message above!
Selecting previously unselected package libcorkipset-build-deps.
(Reading database ... 101067 files and directories currently installed.)
Preparing to unpack libcorkipset-build-deps_1.1.1+20150311-7_all.deb ...
Unpacking libcorkipset-build-deps (1.1.1+20150311-7) ...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Correcting dependencies...Starting pkgProblemResolver with broken count: 1
Starting 2 pkgProblemResolver with broken count: 1
Investigating (0) libcorkipset-build-deps:amd64 < 1.1.1+20150311-7 @iU mK Nb Ib >
Broken libcorkipset-build-deps:amd64 Depends on libcork-dev:amd64 < 0.15.0+ds-6 @ii mK > (>= 0.15.0+ds-8)
  Removing libcorkipset-build-deps:amd64 because I can't find libcork-dev:amd64
Done
 Done
Starting pkgProblemResolver with broken count: 0
Starting 2 pkgProblemResolver with broken count: 0
Done
The following packages will be REMOVED:
  libcorkipset-build-deps
0 upgraded, 0 newly installed, 1 to remove and 1 not upgraded.
1 not fully installed or removed.
After this operation, 9,216 B disk space will be freed.
(Reading database ... 101071 files and directories currently installed.)
Removing libcorkipset-build-deps (1.1.1+20150311-7) ...
mk-build-deps: Unable to install libcorkipset-build-deps at /usr/bin/mk-build-deps line 402.
mk-build-deps: Unable to install all build-dep packages
**gbp:error: Pristine-tar couldn't checkout "libcorkipset_1.1.1+20150311.orig.tar.xz":** 
HEAD is now at 4e09f31 Merge tag 'debian/1.1.1+20150311-6_bpo8+1'
/root/build-area
**dpkg: error: cannot access archive 'libcorkipset-dev_*.deb': No such file or directory**
^CTraceback (most recent call last):
  File "/usr/bin/gbp", line 9, in <module>
    load_entry_point('gbp==0.7.5', 'console_scripts', 'gbp')()
  File "/usr/lib/python2.7/dist-packages/gbp/scripts/supercommand.py", line 144, in supercommand
    return module.main(args)
  File "/usr/lib/python2.7/dist-packages/gbp/scripts/clone.py", line 94, in main
    auto_name=auto_name,reference=options.reference)
  File "/usr/lib/python2.7/dist-packages/gbp/git/repository.py", line 1942, in clone
    capture_stderr=True)
  File "/usr/lib/python2.7/dist-packages/gbp/git/repository.py", line 184, in __git_inout
    (stdout, stderr) = popen.communicate(input)
  File "/usr/lib/python2.7/subprocess.py", line 800, in communicate
    return self._communicate(input)
  File "/usr/lib/python2.7/subprocess.py", line 1417, in _communicate
    stdout, stderr = self._communicate_with_poll(input)
  File "/usr/lib/python2.7/subprocess.py", line 1471, in _communicate_with_poll
    ready = poller.poll()

**Comment by juneszh** [comment]
I have try 
`apt-get install Pristine-tar`
then it fixed this problem.

**Comment by rogers0** [comment]
glad to hear your report!

I think it's because you set apt preference as not to install recommends.
I'll try to fix this case on next release. thanks!

**Comment by mrkschan** [comment]
I can reproduce the issue and confirm that `apt-get install pristine-tar` is the missing build dependency.
