### ISSUE TITLE
APKBUILD for alpine linux

### ISSUE THREAD

**Issue by debiansid** [shadowsocks/shadowsocks-libev#1383]
### What version of shadowsocks-libev are you using?
3.0.4

### What operating system are you using?
alpine linux 3.5 

### What did you do?
abuild -r

### What did you expect to see?
package built

### What did you see instead?
because unlike archlinux, alpine is lack of libipcorkipset , it failed to build.
and I fount this file https://github.com/shadowsocks/shadowsocks-libev/blob/master/docker/alpine/Dockerfile
so, how to convert this into APKBUILD for alpine , then I can build 3.0.4 or even newest commit version of shadowsocks-libev?

**Comment by registe** [comment]
source="${pkgname}-${pkgver}.tar.gz::https://github.com/shadowsocks/${pkgname}/releases/download/v${pkgver}/${pkgname}-${pkgver}.tar.gz"

then follow the wiki page: [Creating an Alpine package](https://wiki.alpinelinux.org/wiki/Creating_an_Alpine_package)

**Comment by XiaoxiaoPu** [comment]
Here is an APKBUILD for shadowsocks-libev 3.0.4

```
# Maintainer: Natanael Copa <ncopa@alpinelinux.org>
pkgname=shadowsocks-libev
pkgver=3.0.4
pkgrel=0
pkgdesc="lightweight secured SOCKS5 proxy"
url="https://shadowsocks.org/en/download/servers.html"
arch="all"
license="GPLv3"
depends=""
makedepends="asciidoc autoconf automake libev-dev libtool linux-headers udns-dev libsodium-dev mbedtls-dev pcre-dev"
install=""
subpackages="$pkgname-dev $pkgname-doc"
source="shadowsocks-libev-$pkgver.tar.gz::https://github.com/shadowsocks/shadowsocks-libev/releases/download/v$pkgver/shadowsocks-libev-$pkgver.tar.gz"
builddir="$srcdir/shadowsocks-libev-$pkgver"

build() {
    cd "$builddir"
    ./configure \
        --build=$CBUILD \
        --host=$CHOST \
        --prefix=/usr \
        --sysconfdir=/etc \
        --mandir=/usr/share/man \
        --localstatedir=/var \
        || return 1
    make || return 1
}

package() {
    cd "$builddir"
    make DESTDIR="$pkgdir" install || return 1
}

md5sums="4423129a2a838cf8884075551ce14a36  shadowsocks-libev-$pkgver.tar.gz"
sha256sums="1c30646bc716c18c5e425011712632983af7c942e6157aed55a3452a30cdc07e  shadowsocks-libev-$pkgver.tar.gz"
sha512sums="a6f6f906c30575e7fa0ed3812993c6f9666f4d3ed8e539dc8a75ea22cf0abdc89498c1ed95dccb50fcc59e04c3160da58412b0c56d3a4bb8e6247ee6db3edec0  shadowsocks-libev-$pkgver.tar.gz"
```

**Comment by debiansid** [comment]
Ok, then simple-obfs has another issue.
https://github.com/shadowsocks/simple-obfs/issues/62

**Comment by debiansid** [comment]
@XiaoxisoPu @registe 
Thanks , how to checkout newest commit in APKBUILD ?

**Comment by registe** [comment]
https://wiki.alpinelinux.org/wiki/APKBUILD_examples:Git_checkout

**Comment by whour** [comment]
https://pkgs.alpinelinux.org/package/edge/testing/x86/shadowsocks-libev
Flag out of date.
