### ISSUE TITLE
ss-server提示This system doesn't provide enough entropy to quickly generate high-quality ...

### ISSUE THREAD

**Issue by sergio13848** [shadowsocks/shadowsocks-libev#1384]
### What version of shadowsocks-libev are you using?
3.0.4

### What operating system are you using?
debian  4.9.14-040914-generic(AWS开的服务器)

### What did you do?
ss-server运行命令提示如下：
This system doesn't provide enough entropy to quickly generate high-quality random numbers
Installing the rng-utils/rng-tools or haveged packages may help.
On virtualized Linux environments, also consider using virtio-rng.
The service will not start until enough entropy has been collected.

**Comment by madeye** [comment]
As it said,

> This system doesn't provide enough entropy to quickly generate high-quality random numbers
Installing the rng-utils/rng-tools or haveged packages may help.
On virtualized Linux environments, also consider using virtio-rng.
The service will not start until enough entropy has been collected.

**Comment by Galaxy0419** [comment]
Just install the rng-tool and use command rngd -r /dev/urandom

**Comment by rogers0** [comment]
I'd like to recommend haveged, rather than rng-tool

**Comment by slrslr** [comment]
Following command should work on Debian and Redhat based systems:
`yum install haveged -y 2>/dev/null||sudo apt-get install haveged -y 2>/dev/null`
SInce i am having redhat based (CentOS), it used yum package manager. After it was installed i no longer see the error.

**Comment by damodaranudas** [comment]
The alert message is gone when I set a paranoid long password
