### ISSUE TITLE
建议加一个 gcc -O3 编译选项

### ISSUE THREAD

**Issue by pexcn** [shadowsocks/shadowsocks-libev#1387]
via: https://github.com/fuckshadows/fuckshadows-libev/commit/07ecd51d95f3f86e54b0ced810bd37aef583b569

**Comment by wongsyrone** [comment]
If there is no objection on changed AM_CFLAGS, I can submit as PR.

**Comment by rogers0** [comment]
Much easier to decide if there's perf comparison data

**Comment by wongsyrone** [comment]
Just personal taste. No comparison data available.

**Comment by madeye** [comment]
We'd better keep using `-O2` as the default optimization level.

Actually, all the code in shadowsocks-libev are not on the critical path. For better performance, make sure your mbedtls and libsodium are compiled with proper compiler options.

**Comment by pexcn** [comment]
libsodium 用了 `--enable-opt` 这应该在有相应指令集的机器上比原来的好吧？

**Comment by debiansid** [comment]
@wongsyrone
What is purpose of fuckshadow fork?

**Comment by wongsyrone** [comment]
personal usage and for fun
