### ISSUE TITLE
请问libev版本如何在多IP的VPS上使用指定IP代理

### ISSUE THREAD

**Issue by triaqu** [shadowsocks/shadowsocks-libev#1388]
如VPS有a,b,c三个IP，默认是a的情况下，连接b或c代理上网返回的IP都是默认a的地址。
在ssr的python上连接某个IP则返回的IP就连接的IP地址。

我试过把server_host设为需连接IP，但返回的还是默认IP，请问一下libev版本如何在多IP机器上实现指定IP代理呢。

**Comment by lixingcong** [comment]
无解，VPS只有一个WAN物理interface，那个WAN就是Main IP。

**Comment by Windendless** [comment]
命令行参数-s <server_host> 或 配置文件中的server配置项中，指定你要使用的IP。

**Comment by Windendless** [comment]
从代码分析，你可以指定命令行参数-b <local_address>为你要使用的IP。

**Comment by Windendless** [comment]
Connections to remote servers always use Specified IP, try this：
[-b <local_address>]       Local address to bind.

**Comment by triaqu** [comment]
@Windendless  
 2017-03-20 23:59:53 ERROR: bind: Cannot assign requested address
 2017-03-20 23:59:53 ERROR: Could not bind
 2017-03-20 23:59:53 ERROR: bind() error

-b是屏蔽客户机上的IP吧。

**Comment by Windendless** [comment]
@triaqu see also:
ss-server -h

**Comment by triaqu** [comment]
找到命令-i,但 -i eth0可以绑定，但-i eth0:0就提示 ERROR: setinterface: No such device。

**Comment by hellofwy** [comment]
应该是使用 -s 指定

**Comment by madeye** [comment]
Try `-b <local_addr>`, you may need to run your server as root to bind specific address.

**Comment by triaqu** [comment]
@madeye 谢谢，可以绑定了。

-b的说明里local address to bind,not available in server mode
以为在服务器端ss-server不能用-b命令。
