### ISSUE TITLE
ss_server close failed.

### ISSUE THREAD

**Issue by LSsoftware** [shadowsocks/shadowsocks-libev#1390]
### What version of shadowsocks-libev are you using?
3.0.5

### What operating system are you using?
macos

### What did you do?
start & close ss_server through code.

### What did you expect to see?
Don't shut down my program when i close ss_server.

### What did you see instead?
Program crash point to ev_select.c 170

### What is your config in detail (with all sensitive info masked)?
in shadowsocks.h
```
// To stop the service on posix system, just kill the daemon process
// kill(pid, SIGKILL);
// Otherwise, If you start the service in a thread, you may need to send a signal SIGUSER1 to the thread.
// pthread_kill(pthread_t, SIGUSR1);
```

start:
```
ss_thread = NULL;
int err = pthread_create(&ss_thread, NULL, start_worker, NULL);
pthread_detach(ss_thread);
```

and stop:
```
struct ev_loop *loop = EV_DEFAULT;
ev_break(loop, EVBREAK_ALL);    // has nothing to do with error,
pthread_kill(ss_thread, SIGUSR1);
pthread_join(ss_thread, NULL);
```

@madeye

**Comment by madeye** [comment]
I didn't get any useful information from your description. If you plan to integrate shadowsocks-libev with your app, the best practice is forking a new process instead of using pthread.

**Comment by LSsoftware** [comment]
in shadowsocks.h
```
// To stop the service on posix system, just kill the daemon process
// kill(pid, SIGKILL);
// Otherwise, If you start the service in a thread, you may need to send a signal SIGUSER1 to the thread.
// pthread_kill(pthread_t, SIGUSR1);
```

According to shadowsocks.h, I used second methods, using pthread to start server.

**Comment by madeye** [comment]
Could you post your source code here? Without it, no one can reproduce your issue.

**Comment by LSsoftware** [comment]
@interface SSLocalRunner ()

@end

static pthread_t ss_thread;

static int isrunning = 0;

static pthread_mutex_t mutex = PTHREAD_MUTEX_INITIALIZER;

static SRError_Type ss_local_error = SRError_NoError;

static listen_ctx_t * SS_Local__listen;


int sock_port (int fd) {
    struct sockaddr_in sin;
    socklen_t len = sizeof(sin);
    if (getsockname(fd, (struct sockaddr *)&sin, &len) < 0) {
        DLog(@"getsock_port(%d) error: %s",
             fd, strerror (errno));
        return 0;
    } else {
        return ntohs(sin.sin_port);
    }
}

NSString* sock_host (int fd) {
    
    
    struct sockaddr_in sin;
    socklen_t len = sizeof(sin);
    if (getsockname(fd, (struct sockaddr *)&sin, &len) < 0) {
        DLog(@"getsock_host(%d) error: %s",
             fd, strerror (errno));
        return nil;
    } else {
        char ip[20] = {0};
        inet_ntop(AF_INET, &sin.sin_addr, ip, sizeof(ip));
        NSString* strIPAddress = [NSString stringWithUTF8String:ip];
        return strIPAddress;
    }
}


int LocalSocksBlock_callback(void *listener)
{
    listen_ctx_t * listen_ctx = listener;
    SS_Local__listen = listener;
    DLog(@"SS_Local_ status:%@ listening(%@:%@)", listen_ctx->fd > 0 ? @"start" : @"failed", sock_host(listen_ctx->fd), @(sock_port(listen_ctx->fd)));
    if (listen_ctx->fd > 0) {
        isrunning = true;
        return SRError_NoError;
    }else {
        isrunning = false;
        return SRError_CreateLocalServerFailed;
    }
}

int sslocal_isrunning()
{
    return (isrunning == 1);
}


void *start_worker(void * p)
{
    Proxy * proxy = [Proxy defaultProxy];
    if (!proxy) {
        ss_local_error = SRError_NoProxy;
        return 0;
    }
    profile_t profile;
    memset(&profile, 0, sizeof(profile_t));
    profile.mode = 0;
    profile.remote_host = strdup([proxy.server UTF8String]);
    profile.remote_port = (int)proxy.server_port;
    profile.password = strdup([proxy.password UTF8String]);
    profile.method = strdup([proxy.method UTF8String]);
    profile.local_addr = strdup([MacConfig defaultConfig].proxyhost.UTF8String);
    profile.local_port = [[MacConfig defaultConfig].proxyport intValue];
    profile.timeout = (int)proxy.timeout;
#ifdef MacVPN
    profile.log = strdup([[BaseMacApp serviceLogFileUrl] UTF8String]);
#endif
    DLog(@"start proxy: remote_host is %s:%d \n", profile.remote_host, profile.remote_port);
    DLog(@"start proxy: local_addr is %s:%d \n", profile.local_addr, profile.local_port);
    DLog(@"start proxy: method: %s, \n", profile.method);
    ss_local_error = start_ss_local_server(profile, LocalSocksBlock_callback);
    isrunning = false;
    DLog(@"close proxy------");
    return 0;
}



void start_SS_Local__server()
{
    ss_thread = NULL;
    int err = pthread_create(&ss_thread, NULL, start_worker, NULL);
    
    pthread_detach(ss_thread);
    if (err) {
        ss_local_error = SRError_NoPThreadError;
    }
}


@implementation SSLocalRunner

+ (void)startSSLocal:(SSLocalEnableCompletion)completion
{
    DLog(@"start proxy");
    
    start_SS_Local__server();
    if (completion) {
        if (ss_local_error == SRError_NoError) {
            DLog(@"start proxy finished");
            completion(true, ss_local_error);
        } else {
            DLog(@"start proxy failed");
            completion(false, ss_local_error);
        }
    }
    return;
}

+ (BOOL)isRunProxy
{
    return isrunning;
}

+ (int)stopProxy
{
    if (isrunning) {
        
        pthread_kill(ss_thread, SIGUSR1);
        if (1)
        {
            pthread_join(ss_thread, NULL);
        }
        return 1;
    }
    return 0;
}

@end

**Comment by madeye** [comment]
>  ss_local_error = start_ss_local_server(profile, LocalSocksBlock_callback);

I don't think you can do the callback here. shadowsocks-libev is totally non-thread-safe.

Here is an example how to integrate shadowsocks-libev: https://github.com/cs17899219/shadowsocks-Mac/blob/3fbcf0d9691095914f2f5221a0adbc5e759e15af/ShadowsocksX-NG/SSLocalManager.c#L96

**Comment by LSsoftware** [comment]
no. It is called before the libev and the output is correct.
```
    // block return status
    int errorType = statusBlock(&listen_ctx);
    if (errorType != 0) {
        return errorType;
    }
    
    // Enter the loop
    ev_run(loop, 0);
```

**Comment by madeye** [comment]
I think you have to debug it yourself. First of all, try to figure out where the crash happen exactly, dumping the full call stack would be helpful.

**Comment by LSsoftware** [comment]
You are right. I just got an interrupted when i copied SSLocalManager to my project. This may be a  thread source error, but I still can't find it.
