### ISSUE TITLE
ss-local is not working on Linux system

### ISSUE THREAD

**Issue by linuxur** [shadowsocks/shadowsocks-libev#1391]
### What version of shadowsocks-libev are you using?
Using V2.5.0 on both server and client ends.

### What operating system are you using?
Server: Ubuntu server 16.04 with kernel version 4.4.55
Client 1: tomato-K26-1.28.RT-N5x-MIPSR2-132 with kernel 2.6.22
Cient 2: Ubuntu destop 16.04 with kernel 4.4.0-57

### What did you do?
I manually compiled ss and installed on server and two clients.  Server end is working find and verified from window PCs. The issue is ss-local is not working on Linux clients.

### What did you expect to see?
I expected web browser (firefox) is able to surf some website, like google.com, through local sock5 proxy which is ss-local.

### What did you see instead?
I have seen: 
ss is compiled, installed and running normally without error messages or logs.

sudo ss-local -c ./conf01.json -f ./ss-local.pid -a nobody

cat /var/log/syslog | grep ss-local
Mar 21 12:36:19  ss-local[20999]: onetime authentication enabled
Mar 21 12:36:19  ss-local[20999]: initializing ciphers... aes-256-cfb
Mar 21 12:36:19  ss-local[20999]: tcp port reuse enabled
Mar 21 12:36:19  ss-local[20999]: listening at 127.0.0.1:1080

ps aux | grep ss-
nobody   20999  0.0  0.1  31272  3428 ?        Ss   12:36   0:00 ss-local -c ./conf01.json -f ./ss-local.pid -a nobody

When browsing website, the tcp session was established between web browser and ss-local.
 netstat -na | grep 1080
tcp        0      0 127.0.0.1:1080          0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:36532         127.0.0.1:1080          TIME_WAIT  
tcp        0      0 127.0.0.1:36524         127.0.0.1:1080          TIME_WAIT  
tcp        0      0 127.0.0.1:36522         127.0.0.1:1080          TIME_WAIT  
tcp        0      0 127.0.0.1:36518         127.0.0.1:1080          TIME_WAIT  
tcp        0      0 127.0.0.1:1080          127.0.0.1:36520         ESTABLISHED
tcp        0      0 127.0.0.1:36534         127.0.0.1:1080          TIME_WAIT  
tcp        0      0 127.0.0.1:36528         127.0.0.1:1080          TIME_WAIT  
tcp        0      0 127.0.0.1:36530         127.0.0.1:1080          TIME_WAIT  
tcp        0      0 127.0.0.1:36526         127.0.0.1:1080          TIME_WAIT  
tcp        0      0 127.0.0.1:36520         127.0.0.1:1080          ESTABLISHED

However, there is no tcp session from ss-local to ss server.
~$ netstat -na | grep 8080
~$ netstat -na | grep 8080

I tried to capture traffic heading to server from tcpdump and found packet is zero. 

This might be same issue in following links.
https://github.com/shadowsocks/shadowsocks/issues/776
https://github.com/shadowsocks/shadowsocks-libev/issues/1237
https://github.com/shadowsocks/shadowsocks-libev/issues/741

### What is your config in detail (with all sensitive info masked)?
cat ./conf01.json 
{
"server":"xxxxxxx",
"server_port":8080,
"local_port":1080,
"password":"xxxxx",
"timeout":60,
"method":"aes-256-cfb",
"auth":true,
"fast_open": false,
"workers":1
}

If issue is resolved, I will close this post.

**Comment by madeye** [comment]
> Using V2.5.0 on both server and client ends.

Update to the latest version.

> "auth":true,

Set "auth" to false.

**Comment by linuxur** [comment]
Thanks for response.
I disabled OTA, but it didn't fix issue. 
What Linux did you use to replicate this issue? I like to give it try and see if I will still run into it.

**Comment by linuxur** [comment]
I'm concerned more that ss-local doesn't kick in TCP 3 way handshake with ss server. My understanding is -i/b is used to bind internal NIC. Then how does ss-locla choose the external NIC?

**Comment by linuxur** [comment]
BTW, iptables is accepting and passing all traffic.

**Comment by kevinzu007** [comment]
i come from  “https://github.com/shadowsocks/shadowsocks-libev/issues/1237”，this still not resolve the problem

**Comment by sylinuxhy** [comment]
i come from “https://github.com/shadowsocks/shadowsocks-libev/issues/1237”，this still not resolve the problem

**Comment by blueardour** [comment]
any progress on this?
