### ISSUE TITLE
启动时报错但是等一会能正常启动

### ISSUE THREAD

**Issue by Galaxy0419** [shadowsocks/shadowsocks-libev#1392]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
3.0.4

### What operating system are you using?
Debian 8

### What did you do?
setsid ss-server -c /etc/shadowsocks.json -u

### What did you see instead?

This system doesn't provide enough entropy to quickly generate high-quality random numbers
Installing the rng-utils/rng-tools or haveged packages may help.
On virtualized Linux environments, also consider using virtio-rng.
The service will not start until enough entropy has been collected.

**Comment by aa65535** [comment]
#1384

**Comment by Galaxy0419** [comment]
And how to use rng-tools to generate high-quality random numbers

**Comment by Galaxy0419** [comment]
Problem solved. Just install the rng-tool and use command rngd -r /dev/urandom

**Comment by rogers0** [comment]
I'd like to recommend haveged, rather than rng-tool

**Comment by wongsyrone** [comment]
> Administrator recommendations

> "You really, really want to run rngd", Peter said. It should be started as early as possible during system boot-up, so that the applications have early access to the randomness that it provides.

> One thing you should not do is the following:

 >   rngd -r /dev/urandom
> Peter noted that he had seen this command in several places on the web. Its effect is to connect the output of the kernel's RNG back into itself, fooling the kernel into believing it has an endless supply of entropy.

> HAVEGE (HArdware Volatile Entropy Gathering and Expansion) is a piece of user-space software that claims to extract entropy from CPU nondeterminism. Having read a number of papers about HAVEGE, Peter said he had been unable to work out whether this was a "real thing". Most of the papers that he has read run along the lines, "we took the output from HAVEGE, and ran some tests on it and all of the tests passed". The problem with this sort of reasoning is the point that Peter made earlier: there are no tests for randomness, only for non-randomness.

> One of Peter's colleagues replaced the random input source employed by HAVEGE with a constant stream of ones. All of the same tests passed. In other words, all that the test results are guaranteeing is that the HAVEGE developers have built a very good PRNG. It is possible that HAVEGE does generate some amount of randomness, Peter said. But the problem is that the proposed source of randomness is simply too complex to analyze; thus it is not possible to make a definitive statement about whether it is truly producing randomness. (By contrast, the HWRNGs that Peter described earlier have been analyzed to produce a quantum theoretical justification that they are producing true randomness.) "So, while I can't really recommend it, I can't not recommend it either." If you are going to run HAVEGE, Peter strongly recommended running it together with rngd, rather than as a replacement for it.

https://lwn.net/Articles/525459/
