### ISSUE TITLE
Can't compile with documentation

### ISSUE THREAD

**Issue by Old-Pussy** [shadowsocks/shadowsocks-libev#1395]
### What version of shadowsocks-libev are you using?
The current version  (3.0.5)
### What operating system are you using?
armbian ubuntu 16.04
### What did you do?
make
### What did you expect to see?
success
### What did you see instead?
Can't compile successfully unless pass in `--disable-documentation` when `./configure`
### What is your config in detail (with all sensitive info masked)?

> make[2]: Entering directory '/home/damiao/shadowsocks-libev/doc'
  GEN      shadowsocks-libev.xml
  GEN      shadowsocks-libev.8
xmlto: /home/damiao/shadowsocks-libev/doc/shadowsocks-libev.xml does not validate (status 3)
xmlto: Fix document syntax or use --skip-validation option
file:///etc/xml/catalog:1: parser error : Document is empty
I/O error : Attempt to load network entity http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd
/home/damiao/shadowsocks-libev/doc/shadowsocks-libev.xml:2: warning: failed to load external entity "http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd"
D DocBook XML V4.5//EN" "http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd"
                                                                               ^
I/O error : Attempt to load network entity http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd
warning: failed to load external entity "http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd"
validity error : Could not load the external subset "http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd"
Document /home/damiao/shadowsocks-libev/doc/shadowsocks-libev.xml does not validate
Makefile:633: recipe for target 'shadowsocks-libev.8' failed
make[2]: *** [shadowsocks-libev.8] Error 13
rm shadowsocks-libev.xml
make[2]: Leaving directory '/home/damiao/shadowsocks-libev/doc'
Makefile:479: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/damiao/shadowsocks-libev'
Makefile:388: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by qiuzi** [comment]
https://github.com/shadowsocks/openwrt-shadowsocks

**Comment by Yewenyu** [comment]
Can anyone solve this problem？
