### ISSUE TITLE
release 中的 tar.gz 源码未包含 libbloom libcork libipset 引用，无法直接用来打包

### ISSUE THREAD

**Issue by lvii** [shadowsocks/shadowsocks-libev#1397]
使用 release 提供的 tar.gz 尝试打包，提示缺失 libbloom libcork libipset 相关的引用：

https://github.com/shadowsocks/shadowsocks-libev/releases

源码中的引用如果无法找到对应发行版中的 **依赖包**，希望能像 2.5.6 版之前，将依赖包含在源码包中

rpm 打包 SPEC 文件有指定 **编译依赖软件包** 的选项 `BuildRequires`：

    BuildRequires: make gcc pcre-devel asciidoc xmlto automake libtool mbedtls-devel libsodium-devel >= 1.0.4 libev-devel udns-devel

谢谢！

**Comment by madeye** [comment]
Read the document and install all the dependencies first.
