### ISSUE TITLE
希望优化高延迟连接质量

### ISSUE THREAD

**Issue by Galaxy0419** [shadowsocks/shadowsocks-libev#1398]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?

3.0.4
### What operating system are you using?
Debian8

### What did you expect to see?

希望优化如中国连接美国服务器这样的高延迟连接质量，看YouTube的时候发现有些视频快，有些视频慢，还有些视频一开始很慢但是之后却越来越快，希望优化后能开始时就能提至最高速。

**Comment by pexcn** [comment]
我想这个 issues 可以 close 掉了

**Comment by qiuzi** [comment]
@pexcn 你应该理解错他的意思 优化并不是不可能  前提条件是得付出更多成本

**Comment by pexcn** [comment]
这跟链路有关吧，跟 ss 本身没什么关系

**Comment by qiuzi** [comment]
间接关系肯定是有的 直接关系到不会
之前我也提过增加链路方面的优化想法
