### ISSUE TITLE
TFO和obfs是否有冲突或者不可兼得？

### ISSUE THREAD

**Issue by Typhonling** [shadowsocks/shadowsocks-libev#1399]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
3.0.5

### What operating system are you using?
Debian 8 & LEDE 17.01

### What did you do?
同时使用TFO&obfs

### What did you expect to see?
两者能同时工作

### What did you see instead?
当打开obfs后TFO失效，表现为TCPFastOpenPassive值不增长

### What is your config in detail (with all sensitive info masked)?
{
"server":["0.0.0.0"],
"port_password":{
	},
"method":"chacha20-ietf-poly1305",
"plugin":"obfs-server",
"plugin_opts":"obfs=http",
"timeout":60,
"fast_open":true,
"mode":"tcp_and_udp",
"nofile":51200
}

**Comment by madeye** [comment]
Try `"plugin_opts":"obfs=http;fast-open"`.

**Comment by suikatomoki** [comment]
@madeye 
same as nofile?
"plugin_opts":"obfs=http;fast-open;nofile=51200"

**Comment by Typhonling** [comment]
@madeye Works,thx a lot! 必须服务端和客户端同时启用"plugin_opts":"fast-open"，参数--fast-open与"fast_open":true均无效。

**Comment by suikatomoki** [comment]
@Typhonling  nofile也需要在obfs插件中重新设置吗？

**Comment by Typhonling** [comment]
@suikatomoki 这个没有关注，我只是随手把nofile加上了。
