### ISSUE TITLE
contos7 上面编译安装,不能启动

### ISSUE THREAD

**Issue by ooogooo** [shadowsocks/shadowsocks-libev#1400]
出现这个问题,这是什么原因啊

● shadowsocks.service
   Loaded: error (Reason: Bad message)
   Active: failed (Result: exit-code) since Fri 2017-03-24 17:26:20 UTC; 9h ago
 Main PID: 6860 (code=exited, status=203/EXEC)

Mar 24 17:26:20 oo systemd[1]: Started ShadowSocks service.
Mar 24 17:26:20 oo systemd[1]: Starting ShadowSocks service...
Mar 24 17:26:20 oo systemd[1]: shadowsocks.service: main process exited, code=exited, status=203/EXEC
Mar 24 17:26:20 oo systemd[1]: shadowsocks.service: control process exited, code=exited status=1
Mar 24 17:26:20 oo systemd[1]: Unit shadowsocks.service entered failed state.
Mar 24 17:26:20 oo systemd[1]: shadowsocks.service failed.
Mar 24 17:28:41 oo systemd[1]: [/usr/lib/systemd/system/shadowsocks.service:19] Assignment outside of section. Ignoring.
Mar 24 17:28:41 oo systemd[1]: [/usr/lib/systemd/system/shadowsocks.service:23] Invalid section header '[ ${NETWORKING} ="yes" ] || exit 0'

**Comment by Galaxy0419** [comment]
从源码包手动安装，然后用setsid启动

**Comment by whour** [comment]
不应该是 shadowsocks-libev-server@config.service么
config.json 在 /etc/shadowsocks-libev中。
