### ISSUE TITLE
服务端不遵循/etc/hosts

### ISSUE THREAD

**Issue by dynos01** [shadowsocks/shadowsocks-libev#1402]
某些服务必须走ipv6，于是在/etc/hosts中指定了地址。以前使用ss python可以正常工作，切换到libev后发现ss libev并不遵循hosts

**Comment by bazingaterry** [comment]
试试 `-6`

**Comment by dynos01** [comment]
仅仅是部分域名需要走ipv6，直接-6会导致全局v6吧

**Comment by madeye** [comment]
Try installing bind9 and adding `-d 127.0.0.1` to your shadowsocks command line.

**Comment by h2y** [comment]
-d 是守护模式，这个命令不对呀。

`Exception: unsupported daemon command 127.0.0.1`

**Comment by ayaseruri** [comment]
> Try installing bind9 and adding `-d 127.0.0.1` to your shadowsocks command line.

I tried installing bind9 and adding `-d 127.0.0.1`，but not work.

Then I found anthor way:
1、install dnsmasq, for debian you can use command :'apt-get install dnsmasq';
2、adding `-d 127.0.0.1` to your shadowsocks command line

maybe you need to restart your shadowsocks, then it just work.
