### ISSUE TITLE
疑似被GWF已经发现特征

### ISSUE THREAD

**Issue by Galaxy0419** [shadowsocks/shadowsocks-libev#1404]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
3.0.5

### What operating system are you using?
Centos7

### What did you expect to see?
刚刚从网上购买的vps看youtube可以达到27000kb/s但用了5天后看视频只有2000kb/s，希望能继续改进吧

### What is your config in detail (with all sensitive info masked)?
{
    "server":"×××××××",
    "server_port":8388,
    "local_address": "127.0.0.1",
    "local_port":1080,
    "password":"×××××××",
    "timeout":300,
    "method":"chacha20-ietf",
    "fast_open": true
}

**Comment by Galaxy0419** [comment]
顺便请教如何正确开启ss-server 使用setsid？还有如何正确关闭ss-server 使用killall?

**Comment by lcdtyph** [comment]
You might try to set ```server_port``` larger, like 40000+
```setsid``` needs root permission.
```killall ss-server``` always runs perfectly.

**Comment by kevinzu007** [comment]
的确这样，刚买时用它上网很快，后面就很慢了，是故意的吗？
