### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by Galaxy0419** [shadowsocks/shadowsocks-libev#1406]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?

3.0.5
### What operating system are you using?

centos 7
### What did you do?
安装了net-speeder

### What did you see instead?
crypto: stream: repeat IV detected

**Comment by madeye** [comment]
I don't think it's related to shadowsocks.
