### ISSUE TITLE
Response came from ss-manager is confused.

### ISSUE THREAD

**Issue by bazingaterry** [shadowsocks/shadowsocks-libev#1408]
### What version of shadowsocks-libev are you using?

master branch

### What operating system are you using?

Ubuntu 14.04 x64

### What did you do?

Add some port, password and method to ss-manager. After that, I sent a 'ping' to ss-manager.

### What did you expect to see?

stat: {"8001":11370}

### What did you see instead?

stat: {"@\xc2\xb4\x81\xac\x7f":7848056,"":80,"":78...\xcew":32,"\xeb\xcfw":0,"":96,"":96}

### What is your config in detail (with all sensitive info masked)?

`ss-manager --manager-address 0.0.0.0:8839`

**Comment by lcdtyph** [comment]
So sorry about this ...
Please try the latest commit on this fork https://github.com/lcdtyph/shadowsocks-libev
If it works I'll send a pr.
