### ISSUE TITLE
UDP  ERROR: [udp] remote_recv_bind: Address already in use (Even when nothing else is bound to the port)

### ISSUE THREAD

**Issue by terrytw** [shadowsocks/shadowsocks-libev#1412]
### What version of shadowsocks-libev are you using?
3.0.5 on both sides

### What operating system are you using?
server: debian 8 
client: raspbian

### What did you do?
ss-redir -U -c /etc/shadowsocks-libev/config.json

### What did you see instead?
![image1](http://i.imgur.com/dNaycFe.png)

### What is your config in detail (with all sensitive info masked)?
![img2](http://i.imgur.com/aI2zp2l.png)

As you can see there is no other process binding to this port, yet error message keeps poping up. 

Can anyone please tell me why?

Thank you!

P.S. other stuff like ss-redir tcp relay works perfectly fine.

**Comment by lixingcong** [comment]
try another port, not 1080

**Comment by terrytw** [comment]
@lixingcong 
Same result.  
I modified config.json and iptables rules, changed port to 1081. Same error pops up.

**Comment by terrytw** [comment]
I think I figured it out. 

Seems like if you build shadowsocks yourself and install as readme suggested, shadowsocks-libev service will be automatically initiated using /etc/shadowsocks-libev/config.json as configuration file, running ss-server at startup. 

Despite the fact that this service does not initiate properly during boot sequence (enter fail state; exited bla, bla, bla), somehow the port is still marked as occupied somewhere (at least you can't see it using netstat |grep command). UDP relay seems to be running, but you get error message flying around. 

After I changed config.json to config1.json, those error message finally stopped. What a weird bug.
