### ISSUE TITLE
服务器端会忽略系统HOSTS

### ISSUE THREAD

**Issue by pstandard** [shadowsocks/shadowsocks-libev#1413]
服务器：Amzon AMI系统 Linux version 4.4.5-15.26.amzn1.x86_64
在服务器的/etc/hosts里面屏蔽了一些adobe的认证DNS，但是ss还是可以访问，无法被屏蔽，帮忙看一下。原先使用Phyton版本可以正常屏蔽。

测试网址：http://acroipm.adobe.com/11/acropro/CHS/win/nooem/shrink/message.zip；hosts里面的设置：
127.0.0.1    acroipm.adobe.com

**Comment by vfreex** [comment]
I think it is designed to ignore /etc/hosts entries.
As far as I know, shadowsocks-libev uses libudns to resolve hostnames, which sends DNS queries directly to specified DNS resolver without looking up /etc/hosts.

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks-libev/issues/1402#issuecomment-289206923
