### ISSUE TITLE
Is it possible to make Ubnt edgeOS package?

### ISSUE THREAD

**Issue by debiansid** [shadowsocks/shadowsocks-libev#1414]
### What version of shadowsocks-libev are you using?
2.6.2

### What operating system are you using?
edgeOS AKA. Debian wheezy for mild

### What did you do?
Cross-build on debian8

### What did you expect to see?
https://help.ubnt.com/hc/en-us/articles/204976234-EdgeRouter-How-can-I-add-new-packages-and-features-to-EdgeOS-

### What is your config in detail (with all sensitive info masked)?

**Comment by debiansid** [comment]
Now I can only make deb at 2.6.2 on qemu based on debian wheezy for mips, is there any way to make deb package of 3.0.5 on that platform? I've noticed there is 3.0.3 for Debian Jessie mips architecture.

**Comment by debiansid** [comment]
And deb for simple-obfs please

**Comment by rogers0** [comment]
@debiansid I think it's already done.
see scripts/build_deb.sh

**Comment by debiansid** [comment]
As long as you can run it on Debian wheezy. Have you tried it on wheezy?

**Comment by rogers0** [comment]
@debiansid no, but since jessie work is done, it's quite the similar.
patch is welcome, all the time.

**Comment by rogers0** [comment]
@debiansid you mentioned Debian 8, which is jessie

**Comment by debiansid** [comment]
My qemu host is Jessie, virtual machine is wheey for mips. So I need to build deb for wheezy.  shadowsocks-libev 2.6.2 takes about 10 hours to build. I will try it later.

**Comment by rogers0** [comment]
@debiansid https://buildd.debian.org/status/package.php?p=shadowsocks-libev&suite=jessie-backports
there's mips build already done for jessie-backports.
avoid building locally if possible.

**Comment by debiansid** [comment]
yeah, I mentioned that before.but I doubt that we can install it onto wheezy although.

**Comment by rogers0** [comment]
No. jessie-backports can only be installed to jessie.
Wheezy is in LTS stage, which is maintained by paid maintainers :-P

**Comment by debiansid** [comment]
I will let you know if build_deb.sh works on wheezy or not

**Comment by debiansid** [comment]
it did not work even after I enabled wheezy in script

**Comment by rogers0** [comment]
@debiansid thanks for your trying.

> @debiansid no, but since jessie work is done, it's quite the similar.
> patch is welcome, all the time.

I mentioned "similar" / "patch", so it need some work, but feasible from tech side.

**Comment by debiansid** [comment]
@rogers0 I am not able to do that, I am not programmer, so appreciate if you could do that.

**Comment by debiansid** [comment]
after install dependency packages from jessie to wheezy, I can make deb package now. so this should be closed.
thanks
