### ISSUE TITLE
question about haproxy

### ISSUE THREAD

**Issue by Typhonling** [shadowsocks/shadowsocks-libev#1415]
不知道能不能问个题外话，关于haproxy。
使用情景为ss-redir/ss-local > haproxy > ss-server，ss-redir/ss-local与haproxy均运行在client上。haproxy已使用USE_TFO=1编译并在监听端口加上tfo参数。
实际状况为TFO好像并未生效，server有大量TCPFastOpenCookieReqd增长而TCPFastOpenPassive无变化。
是否意味着带TFO cookie的SYN经haproxy转发后无法被server正确识别？在haproxy的文档里貌似写着tfo只适用于client与haproxy监听端之间的通信。
另外想问一下当下有无能正常转发TFO的负载均衡软件呢？

**Comment by madeye** [comment]
It requires HAProxy runs as TFO client as well as TFO server.

There are some related discussions here: http://www.serverphorums.com/read.php?10,850064

**Comment by Typhonling** [comment]
谢谢，去学习下。
我的需求其实是路由器上的多服务器负载均衡和故障转移，就是ss客户端经haproxy转发后貌似TFO失效。ss客户端与服务端直连是没什么问题的。

**Comment by Typhonling** [comment]
> I'm realizing that it's sad that openssl uses write() to send data, because
we wont be able to use TFO with it.
>I think that your patch should work correctly provided that :
- there is no SSL to the server
- there is no "send-proxy" on the server line

Find these，and try to use **haproxy-nossl**，still not working.
且罢，只不过是一个强迫症希望发掘所有可能性而已^^
