### ISSUE TITLE
找不到configure这个目录

### ISSUE THREAD

**Issue by holyen** [shadowsocks/shadowsocks-libev#1417]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
最新master

### What operating system are you using?
centos

### What did you do?
it

### What did you expect to see?
install successed

### What did you see instead?

[root@localhost ~]# git clone git://github.com/madeye/shadowsocks-libev.git
正克隆到 'shadowsocks-libev'...
remote: Counting objects: 10484, done.
remote: Total 10484 (delta 0), reused 0 (delta 0), pack-reused 10484
接收对象中: 100% (10484/10484), 8.81 MiB | 5.57 MiB/s, done.
处理 delta 中: 100% (6853/6853), done.
[root@localhost ~]# cd shadowsocks-libev
[root@localhost shadowsocks-libev]# ./configure
-bash: ./configure: 没有那个文件或目录

**Comment by lixingcong** [comment]
./autogen.sh
