### ISSUE TITLE
从github拉下来的总是3.0.3版本

### ISSUE THREAD

**Issue by HankAviator** [shadowsocks/shadowsocks-libev#1418]
### What version of shadowsocks-libev are you using?
3.0.3 （无关）

### What operating system are you using?
Ubuntu 16.10

### What did you do?
使用`wget`下载最新release或首页git方式下载源代码，编译后均只能得到3.0.3版本。

### What did you expect to see?
获得的是最新版本。

### What did you see instead?
编译后均只能得到3.0.3版本

### What is your config in detail (with all sensitive info masked)?
（无关）

**Comment by madeye** [comment]
`./autogen.sh`
