### ISSUE TITLE
请教在window10 linux子系统ubuntu  xenia安装问题

### ISSUE THREAD

**Issue by iciness** [shadowsocks/shadowsocks-libev#1419]
自己在ubuntu下打包的deb安装没有问题
但是在windows子系统下安装出现如下提示
sudo dpkg -i shadowsocks-libev_3.0.5-1_amd64.deb
Selecting previously unselected package shadowsocks-libev.
(Reading database ... 34866 files and directories currently installed.)
Preparing to unpack shadowsocks-libev_3.0.5-1_amd64.deb ...
Unpacking shadowsocks-libev (3.0.5-1) ...
Setting up shadowsocks-libev (3.0.5-1) ...
Failed to set capabilities on file `/usr/bin/ss-local' (Invalid argument)
The value of the capability argument is not permitted for a file. Or the file is not a regular (non-symlink) file
dpkg: error processing package shadowsocks-libev (--install):
 subprocess installed post-installation script returned error exit status 1
Processing triggers for systemd (229-4ubuntu16) ...
Processing triggers for ureadahead (0.100.0-19) ...
Processing triggers for man-db (2.7.5-1) ...
Errors were encountered while processing:
 shadowsocks-libev

请问要如何解决，谢谢

**Comment by madeye** [comment]
You may open an issue here: https://github.com/Microsoft/BashOnWindows
