### ISSUE TITLE
Can't use UDP relay with ss-server

### ISSUE THREAD

**Issue by OnionJuice** [shadowsocks/shadowsocks-libev#1420]
shadowsocks-libev 3.0.5, CentOS
command: ss-server -u --fast-open -c /etc/shadowsocks.conf

i cant use UDP relay, when i use it the program show this error
ERROR: crypto: stream: repeat IV detected
am i wrong in command?

**Comment by madeye** [comment]
Make sure you're not using any tool like net-speeder.

**Comment by OnionJuice** [comment]
i use it on game proxy and it work normally on shadowsocks-python

**Comment by madeye** [comment]
What's your client?

**Comment by OnionJuice** [comment]
SocksCap64 3.9

**Comment by madeye** [comment]
It looks a bug of your client software, which is generating repeat IVs.

**Comment by madeye** [comment]
You'd better report this issue to the maintainer instead.

**Comment by OnionJuice** [comment]
ok, thank you

**Comment by V-E-O** [comment]
you choosed rc4? that would cause error like this repeat IVs.
