### ISSUE TITLE
ss-manager and obfs issue

### ISSUE THREAD

**Issue by hdid** [shadowsocks/shadowsocks-libev#1422]
### What version of shadowsocks-libev are you using?
shadowsocks-libev 3.0.5

### What operating system are you using?
Debian 8

### What did you do?
ran ss-manager with command:
./ss-manager -c config.json --executable ./ss-server -v

obfs-server is within the same path that ss-manager and ss-server are in.

### What did you expect to see?
Running normally. I tested without ss-manager and everything works well!

### What did you see instead?
At server side nothing special; But client side got these:
 2017-04-01 12:53:18 [simple-obfs] ERROR: getpeername: Transport endpoint is not connected
 2017-04-01 12:53:18 [simple-obfs] ERROR: getpeername: Transport endpoint is not connected
 2017-04-01 12:53:18 [simple-obfs] ERROR: getpeername: Transport endpoint is not connected
 2017-04-01 12:53:19 [simple-obfs] ERROR: getpeername: Transport endpoint is not connected

### What is your config in detail (with all sensitive info masked)?
This is server conf:
{
    "server":"0.0.0.0",
    "port_password":{
        "4481":"password",
        "8212":"password",
        "6483":"password",
        "1154":"password",
        "2455":"password",
        "5526":"password"
    },
    "local_port":10888,
    "timeout":300,
    "mode":"tcp_and_udp",
    "plugin":"obfs-server",
    "plugin_opts":"obfs=http",
    "method":"aes-128-gcm"
}

And client:
{
    "server": "server.ip",
    "server_port": 4481,
    "local_address": "0.0.0.0",
    "local_port": 10801,
    "password": "password",
    "timeout": 300,
    "method": "aes-128-gcm",
    "mode": "tcp_and_udp",
    "plugin": "obfs-local",
    "plugin_opts": "obfs=http;obfs-host=www.google.com",
    "fast_open": true
}

**Comment by madeye** [comment]
Try absolute path for obfs-server

**Comment by hdid** [comment]
Tested and your solution is right  :+1:.
