### ISSUE TITLE
Conflict between /etc/default/shadowsocks-libev and /etc/shadowsocks-libev/config.json

### ISSUE THREAD

**Issue by kkkkke** [shadowsocks/shadowsocks-libev#1423]
### What version of shadowsocks-libev are you using?
V3.0.5
### What operating system are you using?
Debian 8
### What did you do?
I used a dedicated user for shadowsocks-libev, such as "shadowsocks". (useradd -r shadowsocks;)
But that crushed the server.
My solution is change the /etc/default/shadowsocks-libev. I don't think that is a good idea.
### What did you see instead?
no server response.
### What is your config in detail (with all sensitive info masked)?
my config.json:
{
    "server": "0.0.0.0",
    "server_port": 443,
    "local_address": "0.0.0.0",
    "local_port": 1080,
    "password": "password",
    "timeout": 300,
    "method":"aes-256-gcm",
    "mode": "tcp_and_udp",
    "nameserver": "8.8.8.8",
    "user": "shadowsocks",
    "fast_open": true
}
/etc/default/shadowsocks-libev:
USER=nobody
GROUP=nogroup

**Comment by madeye** [comment]
They are totally different. `user` in the config file means the user you want to run as, even if you start shadowsocks as root for binding ports < 1024.

**Comment by kkkkke** [comment]
Sorry for the stupid < 1024 fault. However, I tested the port  8888 and that still not work. @madeye 
As always, if i remove the "user": "shadowsocks" option, all works.
Here is my config
{
"server": "0.0.0.0",
"server_port": 8888,
"local_address": "0.0.0.0",
"local_port": 1080,
"password": "password",
"timeout": 300,
"method":"aes-256-gcm",
"mode": "tcp_and_udp",
"nameserver": "8.8.8.8",
"user": "shadowsocks"
"fast_open": true
}
useradd -r shadowsocks;
iptables -t nat -A PREROUTING -p tcp --dport 443 -j REDIRECT --to-ports 8888
iptables --append INPUT --protocol tcp --dport 8888 -j ACCEPT
