### ISSUE TITLE
xmlto is not found

### ISSUE THREAD

**Issue by vinqon** [shadowsocks/shadowsocks-libev#1424]
I tried to install and build this project on OSX, however, when I used the command 'brew install xmlto' to install the dependency, it got failed.
The below is the error message.

```
$ brew install xmlto
Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
==> Downloading https://fedorahosted.org/releases/x/m/xmlto/xmlto-0.0.26.tar.bz2
==> Downloading from https://fedoraproject.org/wiki/Infrastructure/Fedorahosted-retirement
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: b5a45e210a2796dd1bd2be687f4eba7391d41dee7430b49c42dff1019efc9262
Actual: 50ee1d471365c68012fad618f92396e65c7e10cc165e8a43d9ba96e880a3dae1
Archive: /Library/Caches/Homebrew/xmlto-0.0.26.tar.bz2
To retry an incomplete download, remove the file above.
```

What's more, I found that the download link had been redirected to `https://fedoraproject.org/wiki/Infrastructure/Fedorahosted-retirement`, which is a webpage and announces that the host services is not maintained any more.

So, do I have any other way to install the xmlto on OSX?

**Comment by lcdtyph** [comment]
brew install xmlto --build-from-source
