### ISSUE TITLE
ss-server reports many errors

### ISSUE THREAD

**Issue by muronghan** [shadowsocks/shadowsocks-libev#1425]
### What version of shadowsocks-libev are you using?
3.0.5

### What operating system are you using?
on both Debian 8 and Ubuntu 16.04

### What did you do?
run ss-server (with /etc/shadowsocks-libev/config.json)

### What did you expect to see?
smooth running as past version

### What did you see instead?
a lot errors:
1.  ERROR: getpeername: Transport endpoint is not connected
2.  ERROR: [udp] remote_recv_recvfrom fragmentation
3.  ERROR: remote recv: Connection reset by peer
4.  ERROR: server recv: Connection reset by peer
.......
Meanwile, LEDE client also reported same errors in system.log.

### What is your config in detail (with all sensitive info masked)?

{
    "server": "0.0.0.0",
    "server_port": xxxx,
    "local_port": 1080,
    "password": "xxxxxx",
    "timeout": 60,
    "method":"chacha20-ietf",
    "fast_open": true
}

**Comment by madeye** [comment]
Just ignore them. Network errors happen all the time.
