### ISSUE TITLE
Any patch for 2.6.3+ds, the version for Debian Stretch?

### ISSUE THREAD

**Issue by rogers0** [shadowsocks/shadowsocks-libev#1426]
Dear ss-libev developers & users,

If you want to see any patch applied for 2.6.3+ds, the version in Debian Stretch, just feel free to let me know.
Since Stretch is in deep freeze stage, each release need to go through release manager, so please specify the issue to resolve for each patch. Thank you!

= edited =
Here's the commit list backport to stretch:
[done with 2.6.3+ds-2]
 - 9c7add7
 - a0d38b3 (manpage, with bit change)

[done with 2.6.3+ds-3]
 - adbc0be (manpage)
 - ba7824b (ACL update)
 - 9ee82a9 (out of bound access)
 - d252da8 (out of bound access)

Roger

**Comment by terrytw** [comment]
Hi Roger, i'm just curious: is the frozen phase going to end any time soon?

**Comment by debiansid** [comment]
Rogers0
Where can I get wheezy mips 3.0.5?

**Comment by terrytw** [comment]
@rogers0 
OK, looks like we are slowly getting there, although by the looks of it the progression have slowed down significantly after Feburary. 

And thank you, it's very kind of you. 
Also I really appreciate your work to get ss onto debian repository!

**Comment by rogers0** [comment]
@terrytw we can still upload to experimental in deep freeze stage (now)
e.g., I have uploaded kcptun and its dependencies recently.

PS. for libbloom and simple-obfs, I'm still wait for sponsor (seems DD are all busy these days)
that's why I cannot release 3.0.4 nor 3.0.5, which depends on libbloom package.

**Comment by debiansid** [comment]
@rogers0 you just need qemu to run wheezy for mips64 , that's it.

**Comment by terrytw** [comment]
Oh, thats new to me. I thought you cant upload at all, so its actually the
dependency thats the problem. One way or the other, we'll have to wait.⊙_⊙

2017年4月3日 21:27，"Roger Shimizu" <notifications@github.com>写道：

**Comment by simonsmh** [comment]
`adbc0be628bdc65cea7d1602141ac36d1f7951c9` 🤣

**Comment by rogers0** [comment]
@simonsmh yeah, it will be included on next release.
Thanks for your help!

**Comment by hosiet** [comment]
@rogers0 Just FYI, I found you a sponsor for `libbloom` and it is already uploaded. He might review `simple-obfs` as well, but I'm not sure.

These packages should enter `stretch-backports` after the release of Debian 9.

**Comment by hosiet** [comment]
* ba7824b032329e932d085433ca8dbf4eb661c502 (ACL update)
* 9ee82a9a89a78436efa2f34c0ba9c792cc7c11af
* d252da8d8376975ca1d84004c63e41d5b384a37d

**Comment by rogers0** [comment]
@hosiet thanks! appended to the list.

**Comment by GitHubNemo170216** [comment]
Debian 9 is released and the installed version is still 2.6.3+ds-3, just curious, are we still in deep freeze?

**Comment by hosiet** [comment]
With the release of Debian Stretch (Debian 9), we are walking out from deep freeze. Works towards backporting `ss-libev` 3.x may start now, though it may take a while before available since several dependency libraries need to get backported in advance.

Meanwhile, patches on top of ss-libev 2.6.3 are still highly appreciated and welcomed.

**Comment by GitHubNemo170216** [comment]
Thank you very much!

**Comment by madeye** [comment]
It'd not be irrelevant any more.

Thanks for patches here. Closing the issue.
