### ISSUE TITLE
无法使用AEAD算法

### ISSUE THREAD

**Issue by ccboxes** [shadowsocks/shadowsocks-libev#1427]
### What version of shadowsocks-libev are you using?
3.0.5
### What operating system are you using?
Ubuntu 16.10 x64
### What did you do?
按照教程使用包管理器安装了最新版shadowsocks-libev。
### What did you expect to see?
使用AEAD算法进行连接。
### What did you see instead?
配置为AEAD算法后可以正常启动服务，客户端也可连接到服务器，但无法翻墙。使用chacha20，AES-256-CFB时一切正常。
### What is your config in detail (with all sensitive info masked)?
配置文件如下
{
   "server"="0.0.0.0",
   "server_port"=8388,
   "local_port"=1080,
   "password"="******",
   "timeout"=60,
   "method"="aes-256-gcm"
}

**Comment by asmadeus08** [comment]
The same for me. Installed SS-libev (last version) on Ubuntu 16.10 x64 and change mode to aes-128-gcm. Also i choose aes-128-gcm on windows side with new version of client 4.0. But that's what i got on server side
ERROR: failed to handshake with 95.47.57.68: authentication error
Restart service and other things doesnt help at all

**Comment by madeye** [comment]
Post the output of `ss-server -h` here.

**Comment by asmadeus08** [comment]
@madeye sorry i dont understand what do you mean, can you explain?

**Comment by ccboxes** [comment]
@madeye 谢谢帮助，我找到了问题，似乎包管理器上的SS-libev很旧，为2.4.8，不支持AEAD。请问是否能更新其版本？或者能写一下更详细的编译教程，我使用脚本编译后报错

**Comment by asmadeus08** [comment]
I have last version of SS-libev and it's still doesnt work. So problem on another thing..

**Comment by asmadeus08** [comment]
@madeye my config is
{
"server":"0.0.0.0",
"server_port":995,
"local_address":"127.0.0.1",
"local_port":1080,
"password":"****",
"timeout":120,
"method":"aes-128-gcm",
"fast_open":true
}

**Comment by asmadeus08** [comment]
Solved. That's what i did:
1 apt-get remove shadowsocks-libev and apt purge shadowsocks-libev
2 wget --no-check-certificate -O shadowsocks-libev-debian.sh https://raw.githubusercontent.com/teddysun/shadowsocks_install/master/shadowsocks-libev-debian.sh
chmod +x shadowsocks-libev-debian.sh
./shadowsocks-libev-debian.sh 2>&1 | tee shadowsocks-libev-debian.log
3 changed config file
4 /etc/init.d/shadowsocks restart and then checked status /etc/init.d/shadowsocks status. Now all is working fine.

**Comment by ccboxes** [comment]
@madeye 请问编译时为何出现以下错误？
collect2: error: ld returned 1 exit status
Makefile:677: recipe for target 'ss-local' failed
make[2]: *** [ss-local] Error 1
make[2]: Leaving directory '/root/shadowsocks-libev/src'
Makefile:479: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/root/shadowsocks-libev'
Makefile:388: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by lcdtyph** [comment]
@ccboxes 请把错误信息截全

**Comment by ccboxes** [comment]
谢谢所有人的回复，在换用CentOS7编译之后，问题已经解决，很可能是因为我的VPS自带Ubuntu系统有问题。
