### ISSUE TITLE
通过pip方式安装

### ISSUE THREAD

**Issue by holyen** [shadowsocks/shadowsocks-libev#1429]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?

最新
### What operating system are you using?
centos7

### What did you do?
ss-manager -m aes-256-cfb -u --manager-address 127.0.0.1:4000

### What did you expect to see?
success

### What did you see instead?
-bash: ss-manager: 未找到命令

### What is your config in detail (with all sensitive info masked)?
通过如下方式安装的:

curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"

python get-pip.py

pip install --upgrade pip

pip install shadowsocks

**Comment by wxyzh** [comment]
[shadowsocks-libev](https://github.com/shadowsocks/shadowsocks-libev)
[shadowsocks](https://github.com/shadowsocks/shadowsocks/tree/master)

**Comment by haodong** [comment]
1. 这不是这个版本的问题
2. 这不是ss本身的问题
3. 这很可能是安装失败，所以系统里不存在ss的问题
4. 未提供安装log，无法帮助解决
