### ISSUE TITLE
How to upgrade shadowsocks-libev installed from repository to the latest version?

### ISSUE THREAD

**Issue by azgh** [shadowsocks/shadowsocks-libev#1431]
### What version of shadowsocks-libev are you using?
2.6.3

### What operating system are you using?
debian

### What did you do?
[Install ss from repository](https://github.com/shadowsocks/shadowsocks-libev#install-from-repository)
apt-get update & upgrade

### What did you expect to see?
upgrade ss to v3.0.5

### What did you see instead?
ss-erver -h, still v2.6.3

### What is your config in detail (with all sensitive info masked)?
as normal

How can I upgrade ss to the latest version(3.0.5) from repo?

**Comment by lixingcong** [comment]
https://github.com/shadowsocks/shadowsocks-libev#build-deb-package-from-source
