### ISSUE TITLE
Unmet build dependencies: debhelper (>= 10) libev-dev libmbedtls-dev libsodium-dev (>= 1.0.8~) libudns-dev

### ISSUE THREAD

**Issue by eimo** [shadowsocks/shadowsocks-libev#1432]
### What version of shadowsocks-libev are you using?

3.0.5

### What operating system are you using?

Wheezy for cross compile for UBNT EdgeRouter X
 
### What did you do?

cross compile ShadowSocks on Wheezy which is downloaded from https://people.debian.org/~aurel32/qemu/mipsel/
### What did you expect to see?

Compile successes

### What did you see instead?

Unmet build dependencies: debhelper (>= 10) libev-dev libmbedtls-dev libsodium-dev (>= 1.0.8~) libudns-dev

> root@debian-mipsel:/home/user/shadowsocks-libev# dpkg-buildpackage -us -uc -i
> dpkg-buildpackage: source package shadowsocks-libev
> dpkg-buildpackage: source version 3.0.5-1
> dpkg-buildpackage: source changed by Max Lv <max.c.lv@gmail.com>
> dpkg-buildpackage: host architecture mipsel
>  dpkg-source -i --before-build shadowsocks-libev
> dpkg-checkbuilddeps: Unmet build dependencies: debhelper (>= 10) libev-dev libmbedtls-dev libsodium-dev (>= 1.0.8~) libudns-dev
> dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
> dpkg-buildpackage: warning: (Use -d flag to override.)
> root@debian-mipsel:/home/user/shadowsocks-libev#  Unmet build dependencies: debhelper (>= 10) libev-dev libmbedtls-dev libsodium-dev (>= 1.0.8~) libudns-dev
> bash: syntax error near unexpected token `('

### What is your config in detail (with all sensitive info masked)?
following the steps below

`# Clear out "no public key available" error
apt-get install -y --force-yes debian-keyring debian-archive-keyring  
# Re-update
apt-get update  
# Added backports to sources.list
echo "deb http://ftp.debian.org/debian wheezy-backports main" >> /etc/apt/sources.list  
# Install git in order to clone shadowsocks-libev 
apt-get install -y git  
# Install shadowsocks-libev build dependencies
apt-get install -y build-essential autoconf libtool libssl-dev gawk debhelper dh-systemd init-system-helpers pkg-config  
git clone https://github.com/shadowsocks/shadowsocks-libev.git  
cd shadowsocks-libev  
git submodule update --init --recursive
dpkg-buildpackage -us -uc -i  `

**Comment by rogers0** [comment]
Maybe you can modify scripts/build_deb.sh, copy the part to support jessie to make wheezy work.
I didn't try, so good luck!

**Comment by debiansid** [comment]
I believe @rogers0 disable it for wheezy. The version I am using is 2.6.2.

**Comment by rogers0** [comment]
if you don't know how to enable wheezy, here it is.
as I said, I don't have the environment. so just try it, and report the log if you meet error.

https://github.com/rogers0/shadowsocks-libev/blob/test_wheezy/scripts/build_deb.sh

**Comment by debiansid** [comment]
@rogers0 
I am running it on mips64, let's see where it goes.

**Comment by debiansid** [comment]
and Surge just update to support AHEAD, so it would be great if I could build deb for my ubnt usg.

**Comment by debiansid** [comment]
```
./build_deb.sh: 98: ./build_deb.sh: gbp: not found
./build_deb.sh: 99: cd: can't cd to libbloom
fatal: Not a git repository (or any of the parent directories): .git
Usage:
    mk-build-deps --help|--version

    mk-build-deps [*options*] *control file* | *package name* ...

./build_deb.sh: 104: ./build_deb.sh: gbp: not found
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
/home/ezhang/libsodium-1.0.11
dpkg: error processing libbloom-dev_*.deb (--install):
 cannot access archive: No such file or directory
dpkg: error processing libbloom1_*.deb (--install):
 cannot access archive: No such file or directory
Errors were encountered while processing:
 libbloom-dev_*.deb
 libbloom1_*.deb
./build_deb.sh: 211: ./build_deb.sh: gbp: not found
./build_deb.sh: 212: cd: can't cd to shadowsocks-libev
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
/home/ezhang
./build_deb.sh: 98: ./build_deb.sh: gbp: not found
./build_deb.sh: 99: cd: can't cd to shadowsocks-libev
fatal: Not a git repository (or any of the parent directories): .git
Usage:
    mk-build-deps --help|--version

    mk-build-deps [*options*] *control file* | *package name* ...

./build_deb.sh: 104: ./build_deb.sh: gbp: not found
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
/home/ezhang/libsodium-1.0.11
dpkg: error processing shadowsocks-libev_*.deb (--install):
 cannot access archive: No such file or directory
Errors were encountered while processing:
 shadowsocks-libev_*.deb
Reading package lists... Done
Building dependency tree
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 74 not upgraded.
Cloning into 'simple-obfs'...
remote: Counting objects: 914, done.
remote: Total 914 (delta 0), reused 0 (delta 0), pack-reused 914
Receiving objects: 100% (914/914), 1.38 MiB | 499 KiB/s, done.
Resolving deltas: 100% (269/269), done.
Branch exp1_trusty set up to track remote branch exp1_trusty from origin.
Switched to a new branch 'exp1_trusty'
Use of uninitialized value $fullname in concatenation (.) or string at /usr/bin/equivs-build line 210.
dh_testdir
dh_testroot
dh_prep
dh_testdir
dh_testroot
dh_install
dh_installdocs
dh_installchangelogs
dh_compress
dh_fixperms
dh_installdeb
dh_gencontrol
dh_md5sums
dh_builddeb
dpkg-deb: building package `simple-obfs-build-deps' in `../simple-obfs-build-deps_1.0_all.deb'.

The package has been created.
Attention, the package has been created in the current directory,
not in ".." as indicated by the message above!
Selecting previously unselected package simple-obfs-build-deps.
(Reading database ... 89337 files and directories currently installed.)
Unpacking simple-obfs-build-deps (from simple-obfs-build-deps_1.0_all.deb) ...
Reading package lists... Done
Building dependency tree
Reading state information... Done
Correcting dependencies...Starting
Starting 2
Done
 Done
Starting
Starting 2
Done
```

**Comment by debiansid** [comment]
@rogers0 
https://trello.com/c/BTr0vG1O/47-ss-libev
Would you please check on it? Thanks

**Comment by rogers0** [comment]
> ./build_deb.sh: 98: ./build_deb.sh: gbp: not found

I guess you don't have git-buildpackage package, or you installed a very old version.
That's quite normal, because you need at least upgrade to jessie.
Is there any reason you have to stick on wheezy?

**Comment by debiansid** [comment]
https://github.com/ld0891/ubnt-shadowsocks-libev

**Comment by debiansid** [comment]
@rogers0 , my router is ubnt usg3, it is based on wheezy. But you can check my last comment, someone has compiled deb package of 3.0.5 for mips, but I doubt it would work coz lack of libcork libudns and other dependences.but I would try to run it.

**Comment by debiansid** [comment]
I just installed dependency packages from jessie,after that I can install 3.0.5 for mips from https://github.com/ld0891/ubnt-shadowsocks-libev.hope it would help someone

**Comment by debiansid** [comment]
now, I am trying to make binary of simple-obfs for mips
