### ISSUE TITLE
关于超时的疑问

### ISSUE THREAD

**Issue by pexcn** [shadowsocks/shadowsocks-libev#1433]
如果服务端超时不设置，默认60秒，客户端设置超时600秒，那么实际上超时是多少？

**Comment by lixingcong** [comment]
服务端和客户端都开 -v 哆嗦模式不就看到结果了么

**Comment by fiercebead** [comment]
60

**Comment by suikatomoki** [comment]
我问一下 超时 是啥意思？是客户端无响应超时吗？还是有其他意思？

**Comment by fiercebead** [comment]
@suikatomoki 用来上网什么的基本没啥影响, 我也不是懂得很深入, 表面现象就是一个连接如果一段时间没有数据经过,就会断开, 超时就是控制的那个时间. 你要是用ss代理网络游戏, 有些游戏在选择角色的界面 服务端和客户端是没有数据交换的, 如果你在选角色的界面停留时间超过了 ss的超时, 你就掉线了. 这时候就需要把超时设置的高一些. 比如tera就是这样, aion好像也是, 记不清了.

**Comment by suikatomoki** [comment]
@fiercebead 那windows客户端 默认就5秒 这个5秒也太短了吧

**Comment by fiercebead** [comment]
我平时不怎么用Windows客户端, Windows客户端经过几次改朝换代 我也没有一直关注他们怎么改的, 那个有可能是单位是分钟? 还有就是前段时间我在测试Windows客户端包括SSR的客户端的时候发现好像即使超时很短也不会掉线, 当时只是随便测试一些零碎的东西, 我也不确定准确性了, 我只是想说有些客户端可能在超时这个机制上已经和libev版本有区别了.
libev版本的机制就是像我前面描述的那也那样, ss最开始就是那个样子的.

**Comment by suikatomoki** [comment]
@fiercebead thx
