### ISSUE TITLE
Confused by the -a option

### ISSUE THREAD

**Issue by kkkkke** [shadowsocks/shadowsocks-libev#1435]
### What version of shadowsocks-libev are you using?
V3.0.5

### What operating system are you using?
debian 8

### What did you do?
As you mensioned in [https://github.com/shadowsocks/shadowsocks-libev/issues/1423](url), I changed the port to > 1024. But that dose not work. 

### What did you expect to see?
shadowsocks works without root priority.

### What did you see instead?
if i remove the "user": "shadowsocks" option, all works. 

### What is your config in detail (with all sensitive info masked)?
{
    "server": "0.0.0.0",
    "server_port": 8888,
    "local_address": "0.0.0.0",
    "local_port": 1080,
    "password": "password",
    "timeout": 300,
    "method":"aes-256-gcm",
    "mode": "tcp_and_udp",
    "nameserver": "8.8.8.8",
    "user": "shadowsocks"
    "fast_open": true
}
useradd -r shadowsocks;
iptables -t nat -A PREROUTING -p tcp --dport 443 -j REDIRECT --to-ports 8888
iptables --append INPUT --protocol tcp --dport 8888 -j ACCEPT

**Comment by debiansid** [comment]
setcap
