### ISSUE TITLE
dont know how to install obfs

### ISSUE THREAD

**Issue by asmadeus08** [shadowsocks/shadowsocks-libev#1437]
### What version of shadowsocks-libev are you using?
3.0.5-1

### What operating system are you using?
Ubuntu 16.10 x86

### What did you do?
Want to install obfs-proxy (standalone version) for ubuntu and windows 10

### What did you expect to see?
Wanna working version from both side

### What did you see instead?
Dont know how to do that properly

### What is your config in detail (with all sensitive info masked)?
Standard config

**Comment by asmadeus08** [comment]
Also i'm using ss-csharp version on windows10

**Comment by asmadeus08** [comment]
@madeye Please help to me!

**Comment by cokebar** [comment]
windows的版本我有一个编译好的，是用libev版本在windows上用cygwin便宜的：
https://cokebar.info/archives/1988
ubuntu上按照README上的步骤编译即可

**Comment by asmadeus08** [comment]
@cokebar is it for server or for client? But what to do on server side?

**Comment by cokebar** [comment]
@asmadeus08 那个链接里的是客户端 windows上服务端我也有编译不过没放进去
服务端按照simple-obfs的readme就行了，这里也有说明：
http://shadowsocks.org/en/spec/Plugin.html

**Comment by asmadeus08** [comment]
@cokebar Thanks but
Still dont understand. That's what i did:
git clone https://github.com/shadowsocks/simple-obfs.git
cd simple-obfs
git submodule update --init --recursive
./autogen.sh
./configure && make
sudo make install

Then use that ss-server -c /etc/shadowsocks-libev/config.json --plugin obfs-server --plugin-opts "obfs=http"

And that's what i got
 2017-04-09 10:27:31 INFO: plugin "obfs-server" enabled
 2017-04-09 10:27:31 INFO: initializing ciphers... aes-256-cfb
 2017-04-09 10:27:31 INFO: tcp server listening at 127.0.0.1:44639
 2017-04-09 10:27:31 INFO: running from root user
 2017-04-09 10:27:31 [simple-obfs] INFO: obfuscating enabled
 2017-04-09 10:27:31 [simple-obfs] INFO: tcp port reuse enabled
 2017-04-09 10:27:31 [simple-obfs] ERROR: bind: Address already in use
 2017-04-09 10:27:31 [simple-obfs] ERROR: Could not bind
 2017-04-09 10:27:31 [simple-obfs] ERROR: bind() error
 2017-04-09 10:27:31 ERROR: plugin service exit unexpectedly

And that's what i have on server config right now
"server":"0.0.0.0",
"server_port":995,
"local_address":"127.0.0.1",
"local_port":1080,
"password":"",
"timeout":600,
"method":"aes-256-cfb",
"plugin":"obfs-local",
"plugin_opts":"obfs=http"

**Comment by cokebar** [comment]
端口号占用了 换一个

**Comment by asmadeus08** [comment]
@cokebar So what to do? Can you setup it properly if i will give you access to my server side and on client side, please! I need it so much right now but failed few times already.

**Comment by cokebar** [comment]
@asmadeus08 Sorry. But I have no time helping you doing that.

**Comment by asmadeus08** [comment]
@cokebar But maybe you can tell me what need to fix on server side, please

**Comment by asmadeus08** [comment]
On client side i'm sure that all is right but error on server side and trying to find problem but dont see it.

**Comment by cokebar** [comment]
modify another port number in config.json.
and server side config.json shouldn't have `local_address` and `local_port`, these two is for client side. And `plugin` should be `obfs-server`
and if you set `plugin` and `plugin_opts` in `config.json`, there's no need to specify `--plugin obfs-server --plugin-opts "obfs=http" when running `ss-server`.

Here's my example:
```
#config.json on server side
{
	"server":"x.x.x.x",
	"server_port":995,
	"password":"pass",
	"method":"aes-128-gcm",
	"plugin":"obfs-server",
	"plugin_opts":"obfs=http",
}
# Start server side:
ss-server -c /path/to/config.json -u

#config.json on client side
{
	"server":"x.x.x.x",
	"server_port":995,
	"local_port":1080,
	"password":"passw",
	"method":"aes-128-gcm",
	"plugin":"obfs-local",
	"plugin_opts":"obfs=http;obfs-host=cloudfront.net",
}
# Start client side:
ss-local -c /path/to/config.json -u
```

**Comment by asmadeus08** [comment]
@cokebar Yeah i applied the same on both side and changed port of ss-libev from 995 to 996 and now that's what i got

 2017-04-09 10:59:14 INFO: plugin "obfs-server" enabled
 2017-04-09 10:59:14 INFO: initializing ciphers... aes-256-cfb
 2017-04-09 10:59:14 INFO: tcp server listening at 127.0.0.1:50283
 2017-04-09 10:59:14 INFO: running from root user
 2017-04-09 10:59:14 [simple-obfs] INFO: obfuscating enabled
 2017-04-09 10:59:14 [simple-obfs] INFO: tcp port reuse enabled
 2017-04-09 10:59:14 [simple-obfs] INFO: listening at 0.0.0.0:995
 2017-04-09 10:59:14 [simple-obfs] INFO: running from root user

But when i'm checking ss-libev status with that /etc/init.d/shadowsocks status it's show that server is stopped and doesnt work at all. Trying to get back and it's still doesnt work. So strange.

**Comment by cokebar** [comment]
it is because you start with cmd, instead of init script.( `/etc/init.d/shadowsocks-libev start` or `service shadowsocks-libev start`)
In Ubuntu, you can start ss using `service shadowsocks-libev start`. Then you can use `server shadowsocks-libev status` to check status.

**Comment by cokebar** [comment]
@asmadeus08 I'd better study more about Ubuntu

**Comment by cokebar** [comment]
@asmadeus08 You'd better study more about Ubuntu & Linux.

**Comment by asmadeus08** [comment]
@cokebar Now that's what i have
{
"server":"0.0.0.0",
"server_port":996,
"password":"",
"timeout":600,
"method":"aes-256-cfb",
"plugin":"obfs-server",
"plugin_opts":"obfs=http",
}

And ss-libev working now. Just missed one detail. There was "plugin":"obfs-local" instead of "plugin":"obfs-server" on the server side. Now obfs and ss-libev working.
And now client side doesnt work at all with that config

      "server":"*****",
      "server_port":995,
	  "local_port":1080,
      "password":"",
      "method":"aes-256-cfb",
	  "plugin":"obfs-local",
	  "plugin_opts":"obfs=http"

**Comment by asmadeus08** [comment]
I will try again from the beginning and let' what will happened then cause i think that miss something.

**Comment by asmadeus08** [comment]
@cokebar Still the same error

And now client side doesnt work at all with that config

  "server":"*****",
  "server_port":995,
  "local_port":1080,
  "password":"",
  "method":"aes-256-cfb",
  "plugin":"obfs-local",
  "plugin_opts":"obfs=http"

**Comment by asmadeus08** [comment]
@madeye Working without obfs but i need exactly with obfs cause from 10-20 minutes youtube and other same sites stop loading. So i need obfs-plugin mode to hide my traffic flow. Can you tell me how properly setup this. Tried all steps described below but failed.

**Comment by asmadeus08** [comment]
Done. Problem was in http so changed "plugin_opts":"obfs=http" to "plugin_opts":"obfs=tls" on both side.
