### ISSUE TITLE
iptables该如何设置

### ISSUE THREAD

**Issue by 860git** [shadowsocks/shadowsocks-libev#1439]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
shadowsocks-libev 2.6.2 with OpenSSL 1.0.2k

### What operating system are you using?
gentoo linux

### What did you do?
/etc/shadowsocks-libev/shadowsocks.json
```
{
        "server":"x.x.x.x",
        "server_port":8888,
        "password":"xxx",
        "timeout":600,
        "method":"aes-128-cfb"
}
```
`service iptables start`
`iptables -P INPUT DROP`
`iptables -P OUTPUT DROP`
`iptables -P FORWARD DROP`
`iptables -A INPUT -p tcp --dport 8888 -j ACCEPT`
and many `ACCEPT`s  
`service shadowsocks.server start`

### What did you expect to see?
run shadowsocks with iptables is opened

### What did you see instead?
因为linux莫名有很多流出的数据包导致被digitalocean封了我的网络,所以就有后来开了iptables,特别开了OUTPUT过滤
有点类似这个https://github.com/shadowsocks/shadowsocks-libev/issues/1361

现在情况是,我要把INPUT过滤关闭才能正常使用shadowsocks (也就是设成ACCEPT才能正常使用)
我比较netstat的信息,发现shadowsocks正常时比不正常时多了下面这条连接
`tcp        0      0 [源IP地址]:46714   [目的IP地址]:443       ESTABLISHED 4181/ss-server`
似乎告诉我们,开启INPUT过滤后,shadowsocks无法访问客户端请求的网站?

**Comment by 860git** [comment]
啊,才发现github的shadowsocks版本高很多,可能是这个问题吧

**Comment by haodong** [comment]
iptables -A OUTPUT -p tcp --dport 8888 -j ACCEPT

**Comment by kkkkke** [comment]
一些微小的工作
#清空所有链
iptables --flush
iptables --delete-chain
iptables --table mangle --flush
iptables --table mangle --delete-chain
#设定默认规则
iptables --policy INPUT   DROP
iptables --policy OUTPUT  ACCEPT
iptables --policy FORWARD DROP
#允许SSH
iptables --append INPUT --protocol tcp --dport 22-j ACCEPT
#允许Shadowsocks端口
iptables --append INPUT --protocol tcp --dport 8888 -j ACCEPT
#允许合法接入链接
iptables --append INPUT  --match conntrack --ctstate ESTABLISHED,RELATED --jump ACCEPT
#永久化
iptables-save > /etc/iptables_rules
echo "/sbin/iptables-restore < /etc/iptables_rules"  >> /etc/rc.local

**Comment by 860git** [comment]
之前忘了,其实output规则我也添加允许了
-A OUTPUT -p tcp -m tcp --sport 8888 -j ACCEPT

**Comment by candledragle** [comment]
thks

**Comment by 860git** [comment]
thks2

**Comment by songxin1990** [comment]
擦，iptables --policy INPUT DROP这一条不能直接命令行输入的，导致VPS直接连不上了。

**Comment by Dongzzzz** [comment]
> 擦，iptables --policy INPUT DROP这一条不能直接命令行输入的，导致VPS直接连不上了。
意思是这一行就不要输入了？ 还是说等所有的都设置完成了再输入？

**Comment by Dongzzzz** [comment]
> 擦，iptables --policy INPUT DROP这一条不能直接命令行输入的，导致VPS直接连不上了。

什么意思，这一行不能输入是么？

**Comment by songxin1990** [comment]
> > 擦，iptables --policy INPUT DROP这一条不能直接命令行输入的，导致VPS直接连不上了。
> 
> 什么意思，这一行不能输入是么？

就是说不能直接在控制台，shell窗口中输入，要编辑配置文件模式下输入。
如果vps连接不上了，可以尝试linode管理台重启vps或者用linode的控制台连接vps。
shadowsocks现在端口老是被封，被封后通过linode控制台上去改端口，或者直接开telnet吧，，不怕的话。
