### ISSUE TITLE
如何实现linux客户端使用ss-local共享代理

### ISSUE THREAD

**Issue by Galaxy0419** [shadowsocks/shadowsocks-libev#1441]
如题，给局域网内设备共享。

**Comment by whour** [comment]
https://github.com/shadowsocks/shadowsocks-libev/blob/master/doc/ss-local.asciidoc

**Comment by Galaxy0419** [comment]
@whour so just change the local adress to 0.0.0.0

**Comment by whour** [comment]
@Galaxy0419 yeah,config.json
`"local_address": "0.0.0.0"`

**Comment by Galaxy0419** [comment]
@whour And use socks5 app to connect? What about the ip adress and port? the computer’s adress and port?

**Comment by whour** [comment]
```
{
    "server":"you ip address",
    "server_port":you port,
    "local_address": "0.0.0.0",
    "local_port":1080,
    "password":"you password",
    "timeout":300,
    "method":"chacha20",
    "fast_open": true,
    "workers": 1
}
```
fast_open make sure you server is enable and you linux client kernel >3.7
 connect youip:youport with socks5 app or plugin.

**Comment by Galaxy0419** [comment]
@whourThanks

**Comment by whour** [comment]
You can use [Privoxy](https://wiki.archlinux.org/index.php/Privoxy) forward socks5 to http.

**Comment by Galaxy0419** [comment]
@whour顺便请问，改为local_address0.0.0.0后是不是等于开启了全局模式?
