### ISSUE TITLE
Question: what's the error of 'ERROR: [udp] remote_recv_sendto fragmentation' and how to avoid this?

### ISSUE THREAD

**Issue by siuond** [shadowsocks/shadowsocks-libev#1442]
### What version of shadowsocks-libev are you using?
`shadowsocks-libev 3.0.5`

### What operating system are you using?
`Debian 8`

### What did you do?
start ss-server with
`ss-server -s 0.0.0.0 -p 9172 -k somepwd -m aes-128-gcm -t 180 -u --fast-open -v`

### What did you expect to see?
refer below

### What did you see instead?
Log:

 2017-04-11 04:21:37 INFO: [udp] remote receive a packet
 2017-04-11 04:21:37 INFO: [udp] remote receive a packet
 2017-04-11 04:21:37 INFO: [udp] remote receive a packet
***2017-04-11 04:21:37 ERROR: [udp] remote_recv_sendto fragmentation***
 2017-04-11 04:21:37 INFO: [udp] server receive a packet
 2017-04-11 04:21:37 INFO: sockaddr_cmp: sin_family equal? 1
 2017-04-11 04:21:37 INFO: sockaddr_cmp: sin_port equal? 1
 2017-04-11 04:21:37 INFO: [udp] cache hit: 172.199.89.201:9306 <-> xxx.xxx.xxx.xxx:39375
 2017-04-11 04:21:37 INFO: [udp] server receive a packet
 2017-04-11 04:21:37 INFO: sockaddr_cmp: sin_family equal? 1
 2017-04-11 04:21:37 INFO: sockaddr_cmp: sin_port equal? 1

### What is your config in detail (with all sensitive info masked)?
`ss-server -s 0.0.0.0 -p 9172 -k somepwd -m aes-128-gcm -t 180 -u --fast-open -v`

Question here is :
What's the error of 'ERROR: [udp] remote_recv_sendto fragmentation' and how to avoid this?

**Comment by madeye** [comment]
It means you received a large UDP packet that shadowsocks cannot forward.

It's just a warning. You can safely ignore it.

**Comment by siuond** [comment]
Thanks for the reply. I want to classify a bit more about this question.

This error/warning may do cause some issues when playing Uncharted 4 online on PS4 via shadowsocks-libev with UDP relay. I keep receiving `ERROR: [udp] remote_recv_sendto fragmentation` when searching for a match or starting a match. 

After I got a match to play then there comes the issues:
* Most of time, it's simply just can't start the match.
* I can't re-spawn if I died in a match if I start the match successfully.
* Other players can't re-spawn either sometimes if I start the match successfully.
* Other players become invisible sometimes after they re-spawn if I start the match successfully.

When encountering above issues, I can always find the message`ERROR: [udp] remote_recv_sendto fragmentation`  on the log, so I suspect this UDP error/warning did cause some issues.

**Comment by madeye** [comment]
It's a known issue for PS4 multi-player play, which is related to MTU settings. I suggest to set a relatively small MTU on your router, e.g. 1460 for both LAN and WAN interfaces.

**Comment by siuond** [comment]
I tried to set a smaller MTU 1460/1400 on PS4, router and ss-server, but the issue still remain.
BTW, Battlefield 1, Diablo  3, Street fighter 5 work fine without changing MTU setting.

**Comment by madeye** [comment]
Could you try also tuning MSS? http://lartc.org/howto/lartc.cookbook.mtu-mss.html

**Comment by siuond** [comment]
Thanks for the kind suggestion, but as per my understanding, MSS is for TCP only because there is no way to negotiate this during the handshake as UDP is a connectionless protocol. And I think this error is related to UDP datagram size.

`ERROR: [udp] remote_recv_sendto fragmentation`

**Comment by leeecho** [comment]
这个问题怎么解决的？我也遇到了，有些游戏会报错
ERROR: [udp] remote_recv_sendto fragmentation
