### ISSUE TITLE
请问 ss 支持这些特性吗？

### ISSUE THREAD

**Issue by pexcn** [shadowsocks/shadowsocks-libev#1444]
https://github.com/phuslu/goproxy/issues/1470 这里的，好像不是同一种类型的代理… ss会支持多路复用什么的这些听起来不错的特性吗？
![screenshot_20170413-010329](https://cloud.githubusercontent.com/assets/4590439/24969920/11825956-1f78-11e7-9e84-a599677014c5.png)

**Comment by DarienRaymond** [comment]
隔壁的 V2Ray 支持多路复用，欢迎体验 https://www.v2ray.com/chapter_02/mux.html

**Comment by pexcn** [comment]
v2ray部署太麻烦了…

**Comment by madeye** [comment]
Nope.

Shadowsocks is designed to be "connection-is-a-connection" from the very beginning. You may try other solutions if you really need "mux" feature.

**Comment by pexcn** [comment]
原来如此，谢谢大佬～
