### ISSUE TITLE
dd-wrt support?

### ISSUE THREAD

**Issue by rogers0** [shadowsocks/shadowsocks-libev#1445]
I know there's openwrt support for ss-libev, but how about dd-wrt?

dd-wrt is also quite active, with frequent updates:
 - http://download1.dd-wrt.com/dd-wrtv2/downloads/betas/2017/

**Comment by madeye** [comment]
I don't think there will be any official support of dd-wrt or OpenWRT from this repo.

You may create a new repo for dd-wrt with specific makefile and patches, I'm glad to add its link to our website.

**Comment by rogers0** [comment]
OK. actually I'm just asking for best practice to support dd-wrt. If there's not, it's also fine. I'll ask on -openwrt project.
Thanks!

**Comment by suikatomoki** [comment]
http://blog.bluerain.io/p/SS-Redir-For-Router.html
