### ISSUE TITLE
请问下当前shadowsocks-libev如何升级到最新版本？

### ISSUE THREAD

**Issue by ispwd** [shadowsocks/shadowsocks-libev#1446]
我在ubuntu下通过以下方式安装出现错误，提示一些依赖未安装，但安装这些依赖库时又出现一些其他的问题，请问当前正确的更新方式应该是怎样的？
sudo apt-get install autoconf
sudo apt-get install automake
sudo apt-get install libtool  

cd shadowsocks-libev
sudo apt-get install --no-install-recommends devscripts equivs
mk-build-deps --root-cmd sudo --install --tool "apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends -y"
./autogen.sh && dpkg-buildpackage -b -us -uc
cd ..
sudo dpkg -i shadowsocks-libev*.deb

--------------------------------------------

**Comment by debiansid** [comment]
Ubuntu版本？

**Comment by ispwd** [comment]
Ubuntu 15.10

**Comment by rogers0** [comment]
seems you're using a product already end of life [0]
Ubuntu 15.10 Wily Werewolf Rel October 22, 2015 July 28, 2016

[0] https://wiki.ubuntu.com/Releases

**Comment by ispwd** [comment]
已经更新到了Ubuntu 16.04.2，编译出现了以下错误，请问应该如何解决。
ss_local-aead.o: In function `aead_cipher_decrypt':
/home/shadowsocks-libev/src/aead.c:246: undefined reference to `crypto_aead_xchacha20poly1305_ietf_decrypt'
ss_local-aead.o: In function `aead_cipher_encrypt':
/home/shadowsocks-libev/src/aead.c:207: undefined reference to `crypto_aead_xchacha20poly1305_ietf_encrypt'
collect2: error: ld returned 1 exit status
Makefile:677: recipe for target 'ss-local' failed
make[2]: *** [ss-local] Error 1
make[2]: Leaving directory '/home/shadowsocks-libev/src'
Makefile:479: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/shadowsocks-libev'
Makefile:388: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by debiansid** [comment]
Libsodium version?

**Comment by ispwd** [comment]
libsodium-1.0.12
