### ISSUE TITLE
curl: (56) SSLRead() return error -9845

### ISSUE THREAD

**Issue by droid-Q** [shadowsocks/shadowsocks-libev#1447]
### What version of shadowsocks-libev are you using?
latest release
### What operating system are you using?
Ubuntu 16.04.2 LTS

### What did you do?
hombrew update

### What did you expect to see?

no issues.
### What did you see instead?

curl: (56) SSLRead() return error -9845
### What is your config in detail (with all sensitive info masked)?
Aliyun and google cloud same issues.
{
    "server":["[::0]","0.0.0.0"],
    "server_port":54670,
    "local_address":"127.0.0.1",
    "local_port":1080,
    "password":"*********",
    "timeout":600,
    "workers":10,
    "fast_open": false,
    "nameserver":"8.8.8.8",
    "plugin":"obfs-server",
    "plugin_opts":"obfs=http",
    "method":"chacha20-ietf-poly1305"
}
My client is Surge for mac.
<img width="995" alt="screen shot 2017-04-14 at 9 39 29 pm" src="https://cloud.githubusercontent.com/assets/708277/25044782/0dd6f5c0-215b-11e7-80dc-78ccb8d46dcd.png">

Without obfs it is ok.

**Comment by madeye** [comment]
Closed due to inactivity.
