### ISSUE TITLE
centos 7 no package matched: shadowsocks-libev

### ISSUE THREAD

**Issue by DavidHuang61** [shadowsocks/shadowsocks-libev#1449]
### What version of shadowsocks-libev are you using?
no version

### What operating system are you using?
centos 7

### What did you do?
yum install shadowsocks-libev 
dnf install shadowsocks-libev
### What did you expect to see?
Successful installation

### What did you see instead?
no package matched: shadowsocks-libev
没有可用软件包 shadowsocks-libev。

**Comment by zhou0** [comment]
things dont happen out of magic, some one have to create that rpm on centos for you.

**Comment by DavidHuang61** [comment]
@zhou0 So, what should I do?

**Comment by hekate2639** [comment]
@DavidHuang61 https://copr.fedorainfracloud.org/coprs/librehat/shadowsocks/

**Comment by DavidHuang61** [comment]
@hekate2639 Thank you very mush!
