### ISSUE TITLE
使用ss-redir透明代理之后telnet任何ip任何端口都是开放状态

### ISSUE THREAD

**Issue by shirakun** [shadowsocks/shadowsocks-libev#1454]
使用ss-redir透明代理之后telnet任何ip任何端口都是开放状态
在openwrt上用luci设置的透明代理,转发了udp
然后就这个样子了,有办法解决吗
http://ws1.sinaimg.cn/large/005X3Vdhgy1feph9utietj30it0ax74e.jpg

**Comment by madeye** [comment]
It's expected. You need to wait up to 10 seconds before the connection is timeout.

**Comment by shirakun** [comment]
http://ws3.sinaimg.cn/large/005X3Vdhly1feti75x4njj30it0ax0t6.jpg
就算使用不合法的端口,仍然会提示端口开放,并且超过10秒

**Comment by madeye** [comment]
> 并且超过10秒

I don't see this in your screenshot.

**Comment by miku-sama** [comment]
http://wx4.sinaimg.cn/large/005X3Vdhgy1feu2i93p7ng312x0eb4qr.gif
我录制了gif表示它已经超过10秒

**Comment by madeye** [comment]
It's tcp-ping, not telnet. You may try telnet instead.

**Comment by miku-sama** [comment]
telnet可以在10秒后断开连接,这种情况下我如何判断一个ip的端口是否打开呢

**Comment by madeye** [comment]
Telnet a port and wait 10 seconds.
