### ISSUE TITLE
ss-redir telnet x.x.x.x 22 端口，没有响应数据

### ISSUE THREAD

**Issue by ptpt52** [shadowsocks/shadowsocks-libev#1455]
正常情况应该是TCP连接建立后，服务器首先返回数据
比如：

> telnet a.b.c.d 22
Trying a.b.c.d...
Connected to a.b.c.d.
Escape character is '^]'.
SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu2.1  <-- got this line from server first

这种情况的TCP建立后，是服务器首先发回来数据
但是通常的HTTP(S)，是客户端先发数据

目测 ss 的代码，假设了客户端先发数据
导致被ss代理后的 ssh数据，telnet 过去，没有收到 SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu2.1

**Comment by madeye** [comment]
What's your version of shadowsocks-libev?

**Comment by madeye** [comment]
I cannot reproduce your issue. Make sure you're using the latest client and server.
