### ISSUE TITLE
Question:  One Time Auth feature was abandoned?

### ISSUE THREAD

**Issue by arthurkiller** [shadowsocks/shadowsocks-libev#1457]
Im trying to update the shadowsocks-go project .

And I found that seems OTA was abandoned?

Why I can not see the detail about this in any document?

**Comment by madeye** [comment]
Right.

https://github.com/shadowsocks/shadowsocks-libev/blob/master/Changes#L39

**Comment by arthurkiller** [comment]
@madeye  how can I found more infomation about the shadowsocks protocol ,dude ? shadowsocks.org is leak of documents

**Comment by madeye** [comment]
> shadowsocks.org is leak of documents

All the specs are on shadowsocks.org. For the manual of shadowsocks-libev, just type `man shadowsocks-libev` in your command line.

**Comment by arthurkiller** [comment]
@madeye  thx alot
