### ISSUE TITLE
ss-redir sometimes 100% cpu on my Linksys WRT1900ACS

### ISSUE THREAD

**Issue by pass86** [shadowsocks/shadowsocks-libev#1458]
OpenWrt Chaos Calmer 15.05.1 / LuCI 15.05-142-gb6330a1 Release (git-15.363.78009-956be55)
/usr/bin/ss-redir -c /etc/shadowsocks.json -b 0.0.0.0
I download ipk from https://dl.bintray.com/aa65535/opkg/shadowsocks-libev/3.0.3/OpenWrt/mvebu/

**Comment by madeye** [comment]
Make sure you set the iptables rules correctly. Some circular routes would get your shadowsocks hanging forever.

**Comment by ptpt52** [comment]
@pass86 
hi I can provide you the latest version of ss binary
or LEDE/OpenWrt firmware binary which built from my code https://github.com/ptpt52/lede-source

**Comment by pigpigabc123** [comment]
Maybe  the BT downloading caused the 100% cpu usage，use iptables option“ -m multiport --dports 80...” will solve this problem.

**Comment by pass86** [comment]
I am trying a new version.
