### ISSUE TITLE
ChaCha AEAD, no error output but not working 

### ISSUE THREAD

**Issue by zhou0** [shadowsocks/shadowsocks-libev#1459]
### What version of shadowsocks-libev are you using?

3.0.2 to 3.0.5

### What operating system are you using?

FreeBSD

### What did you do?

using https://github.com/zhou0/mysocks client  program mysocks-wolfssl with libev server with chacha20-ietf-poly1305 method to visit HTTPS URL

for example:

ssclient-wolfssl -k fuckgfw -m chacha20-ietf-poly1305 -p 2194 -s localhost -l 1895
ss-server -k fuckgfw -m chacha20-ietf-poly1305 -p 2194 -s localhost -v
curl -v -x socks5h://localhost:1895 https://cn.bing.com

### What did you expect to see?

get HTTPS reply correctly

### What did you see instead?

* Rebuilt URL to: https://cn.bing.com/
*   Trying ::1...
* connect to ::1 port 1895 failed: Connection refused
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 1895 (#0)
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /usr/local/share/certs/ca-root-nss.crt
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-SHA384
* Server certificate:
*  subject: CN=www.bing.com
*  start date: Nov  4 17:10:22 2016 GMT
*  expire date: May  4 17:10:22 2018 GMT
*  subjectAltName: host "cn.bing.com" matched cert's "*.bing.com"
*  issuer: C=US; ST=Washington; L=Redmond; O=Microsoft Corporation; OU=Microsoft IT; CN=Microsoft IT SSL SHA2
*  SSL certificate verify ok.
> GET / HTTP/1.1
> Host: cn.bing.com
> User-Agent: curl/7.49.0
> Accept: */*
> 
* TLSv1.2 (OUT), TLS alert, Server hello (2):
* SSL read: error:1408F119:SSL routines:SSL3_GET_RECORD:decryption failed or bad record mac, errno 0
* Closing connection 0
* TLSv1.2 (OUT), TLS alert, Client hello (1):
curl: (56) SSL read: error:1408F119:SSL routines:SSL3_GET_RECORD:decryption failed or bad record mac, errno 0

### What is your config in detail (with all sensitive info masked)?

There are no error message from libev or mysocks, but curl fails to get HTTPS URL.  If you test with plain HTTP URL, it works as expected.

**Comment by madeye** [comment]
Could you try shadowsocks-libev, shadowsocks-python, or any other official shadowsocks implementation as the client?

**Comment by zhou0** [comment]
offical python has no aead, official ss-libev does not support non-unix, ss-go  replys on installing a go-distribution, ss-qt5 is for dummy.   mysocks is based on libuv and is multi-platform and can run with either openssl or wolfssl, and if no crypto library is available it can atill run with built-in RC4-MD5 cipher.

**Comment by madeye** [comment]
shadowsocks-python has AEAD support: https://github.com/shadowsocks/shadowsocks/commit/445a3c9c7e34116c47718ebbcb6e07820e8963f0

go-shadowsocks2 also has AEAD support: https://github.com/shadowsocks/go-shadowsocks2. You can even download pre-built win32 binaries from here: https://github.com/riobard/go-shadowsocks2/releases/tag/v0.0.8

**Comment by zhou0** [comment]
Dockerfile of mysocks is only 2.9MB. Can any one beat that?

**Comment by madeye** [comment]
I think you're already off-topic. No one is suggesting other implementations are better than yours.

The point here is just let you know it's not an issue of shadowsocks-libev or any other shadowsocks implementations.

What you should do is debugging your code, make sure it's compatible with other implementations.
