### ISSUE TITLE
er-x 上安装shadowsocks-libev_3.0.5-1出错

### ISSUE THREAD

**Issue by root20000** [shadowsocks/shadowsocks-libev#1464]
在er-x （固件1.91）上安装shadowsocks-libev_3.0.5-1出错，
提示Failed to set capabilities on file `/usr/bin/ss-local' (Operation not supported)，
请问是什么问题？

`ubnt@ubnt:/config$ sudo dpkg -i shadowsocks-libev_3.0.5-1_mipsel.deb
(Reading database ... 34429 files and directories currently installed.)
Preparing to replace shadowsocks-libev 3.0.5-1 (using shadowsocks-libev_3.0.5-1_mipsel.deb) ...
Unpacking replacement shadowsocks-libev ...
Setting up shadowsocks-libev (3.0.5-1) ...
Failed to set capabilities on file `/usr/bin/ss-local' (Operation not supported)

dpkg: error processing shadowsocks-libev (--install):
subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
shadowsocks-libev`

**Comment by debiansid** [comment]
…setcap没有？

**Comment by root20000** [comment]
没有，请问如何setcap，Operation not supported是不是说不支持。那该怎么办？
