### ISSUE TITLE
not working on raspberry Pi 1 model B

### ISSUE THREAD

**Issue by wt8164** [shadowsocks/shadowsocks-libev#1467]
### What version of shadowsocks-libev are you using?
latest 

### What operating system are you using?
raspbian kernel 3.18

### What did you do?
download the source code from github and compiled and try to run

### What did you expect to see?
illegal instruction

**Comment by terrytw** [comment]
Raspbian is based on debian, so follow the instructions for debian.
When it is all set and done, service should be automatically initiated. If you encounter any error, you should post more details. I have no problem running ss on my pi3b.

**Comment by fbi007130** [comment]
http://www.dfrobot.com.cn/community/thread-25868-1-1.html   try it
