### ISSUE TITLE
ss-redir with udp relay can not work properly

### ISSUE THREAD

**Issue by kdrx** [shadowsocks/shadowsocks-libev#1468]
### What version of shadowsocks-libev are you using?
shadowsocks-libev 3.0.5

### What operating system are you using?
 Debian 8 Jessie

### What did you do?
server :
![server](https://cloud.githubusercontent.com/assets/6695752/25261516/c28cfa5e-2684-11e7-94c8-eb192ff96677.jpg)
client:
![ss-redir](https://cloud.githubusercontent.com/assets/6695752/25261525/ceb5f4c0-2684-11e7-85dc-97288a92f3d6.jpg)
![iptables](https://cloud.githubusercontent.com/assets/6695752/25261509/b5fcc12a-2684-11e7-80e8-1b1f521011ff.jpg)

### What did you expect to see?
ss-redir udp relay can work with no errors.

### What did you see instead?
see above.

### What is your config in detail (with all sensitive info masked)?
see above.

**Comment by debiansid** [comment]
2053 for what

**Comment by kdrx** [comment]
@debiansid 
I start ss-redir -U listening on udp port 2053 for tproxy to proxy dns query (udp port 53) trancparently

**Comment by debiansid** [comment]
Why not ss-tunnel for dns

**Comment by madeye** [comment]
It looks an iptables setting issue. Please try https://github.com/shadowsocks/shadowsocks-libev/blob/master/src/ss-nat
