### ISSUE TITLE
IP Fragmentation Packets Issue

### ISSUE THREAD

**Issue by ttys001** [shadowsocks/shadowsocks-libev#1469]
### What version of shadowsocks-libev are you using?

3.0.5 for openwrt with luci-app-shadowsocks 1.6.3

### What operating system are you using?

openwrt chaos calmer 15.05.1

### What did you do?

Shadowssocks transparent proxy with UDP-Relay, globally. PS4 wired connects to router.

### What did you expect to see?

PS4 with NAT2 without other issue.

### What did you see instead?

PS4 detects network type NAT2, but warning with ip fragmentation packets due to router setting.

Today I upgraded from 15.05 to 15.05.1, and reinstalled every app needed in openwrt with exactly the same config files by restoring backup, before upgrade, my openwrt ver was latest till 2016 May. Also, luci-app-shadowsocks had no specific setting for MTU in transparent proxy, my PS4 works perfectly in NAT2, no other issue. After upgrade, transparent proxy asks for MTU to be specified, so I used default 1492, then PS4 pops up the above-mentioning problem.
Game test: TLoU and Bloodborne cannot find people online. Other games are fine
NATTYPETESTER: public ip is shadowsocks server ip, NAT is port restricted.

I tried to find the MTU of the internet provider by connecting directly to my laptop without router, it shows 1472 when it works, then I tried both 1472 and 1500 to be set as the Overried MTU in transparent Proxy, the situation remains the same.(tried PS4 MTU set to both auto and 1500 as well)

Thanks!

**Comment by ttys001** [comment]
I know a number of people has posted similar questions before, but I don't really get how to solve this. Sorry to bother again.😢

**Comment by madeye** [comment]
It's not a real problem. Just ignore it.

**Comment by mickzjq** [comment]
https://github.com/shadowsocksr/shadowsocksr-libev/commit/fabd00241b8b7e449251a1742f6773c3607a8e77#diff-16e785d1e31449b5b01ca4bf377bf970

in SSR project after this commit apply my PS4'network test the "fragmentation packets" not appear anymore
