### ISSUE TITLE
[question] if nofile is unset, will it honor 'DefaultLimitNOFILE=' in systemd/system.conf?

### ISSUE THREAD

**Issue by enihcam** [shadowsocks/shadowsocks-libev#1470]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
3.0.5

### What operating system are you using?
Arch

### What did you do?
n/a

### What did you expect to see?
if nofile is unset, will it honor 'DefaultLimitNOFILE=' in systemd/system.conf?

### What did you see instead?
n/a

**Comment by madeye** [comment]
Yes.
