### ISSUE TITLE
ss-local doesn't work

### ISSUE THREAD

**Issue by joeshae** [shadowsocks/shadowsocks-libev#1472]
Hi @madeye I'm using this on my server (the server_ip:443 is accessible for client):
ss-server -s 0.0.0.0 -k my_password -p 443 -t 600 -m rc4-md5 -u -v

And I'm using this on my Ubuntu client (system firewall disabled):
ss-local -s [server_ip] -p 443 -b 127.0.0.1 -l 12345 -k my_password -m rc4-md5 -u -v

Then I configure the Firefox's http proxy settings on the same Ubuntu client to 127.0.0.1:12345.
Finally I'm trying to browse baidu.com, but it shows proxy server refuses to connect. 
While there is no logs for both ss-server & ss-local.

Could you tell what's the problem? Is there anything wrong with the command usage?
Thank you!

**Comment by madeye** [comment]
Try socks5 proxy.

**Comment by joeshae** [comment]
My fault! Sorry for that!
