### ISSUE TITLE
局域网内多设备连接同一服务器 ss 服务冲突，仅一台可连

### ISSUE THREAD

**Issue by Jaspr987** [shadowsocks/shadowsocks-libev#1473]
### What version of shadowsocks-libev are you using?
3.0.5

### What operating system are you using?
CentOS 7

### What did you do?
局域网内多个设备同时连接同一服务器的 ss 服务

### What did you expect to see?
多设备同时连接并可同时科学上网

### What did you see instead?
设备之间互相冲突，仅一台设备可连接 ss 服务，其他设备连接后无流量经过

### What is your config in detail (with all sensitive info masked)?
ss-server -s 0.0.0.0 -p 1080 -k password -m aes-256-gcm -u

在两个不同运营商、不同路由器下的局域网内试过，遇到同样的问题（无论是不是连接同一服务器的多个端口）。非局域网内多个设备连接没问题。将 ss 服务挂在路由器时也一样，只要局域网内另一台试图连接，路由器的 ss 服务也会挂。

**Comment by Galaxy0419** [comment]
局域网建ss-server有什么意义么?

**Comment by madeye** [comment]
Closed due to inactivity.

**Comment by antonchen** [comment]
我有同样的问题，这个问题持续有一段时间了，升级到最新版本同样存在。简单的说就是：同一局域网只能连接一个客户端。

版本：

shadowsocks-libev 3.1.1
simple-obfs 0.0.5

访问代理时会打印如下错误：

```
Feb 22 20:48:33 Extended ss-local[28310]: 2018-02-22 20:48:33 [simple-obfs] ERROR: getpeername: Transport endpoint is not connected
```
