### ISSUE TITLE
发明那么多复杂加密算法是否多余

### ISSUE THREAD

**Issue by ptpt52** [shadowsocks/shadowsocks-libev#1478]
ss的作用只是个搬运工，只需要对数据简单加密，加入混淆，避免被识别就能达到目的
加密的安全性不是那么重要，对不对？

client----proxy(搬运工)-------real_target_server

是否安全，由 client 和 server 两端通信决定就足够了，比如 https 就是安全的。

**Comment by madeye** [comment]
Actually not, they are necessary.
