### ISSUE TITLE
Using latest version of shadowrocket with aes-128-gcm, ss-server crashes

### ISSUE THREAD

**Issue by alexyangjie** [shadowsocks/shadowsocks-libev#1480]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
v3.0.5

### What operating system are you using?
CentOS 7

### What did you do?
I used Shadowrocket latest release for iOS and select the aes-128-gcm cipher, no obfs. 

### What did you expect to see?
Server connected without problem

### What did you see instead?
Server connected without problem at first. But after a period of time (1 hour), the ss-server just crashed. Below are the logs.

Apr 26 04:00:10 aspdrse2 ss-server: *** Error in `/usr/local/bin/ss-server': corrupted double-linked list: 0x0000000001769cd0 ***
Apr 26 04:00:10 aspdrse2 ss-server: ======= Backtrace: =========
Apr 26 04:00:10 aspdrse2 ss-server: /lib64/libc.so.6(+0x7ada4)[0x7f3195cbada4]
Apr 26 04:00:10 aspdrse2 ss-server: /lib64/libc.so.6(+0x7de41)[0x7f3195cbde41]
Apr 26 04:00:10 aspdrse2 ss-server: /lib64/libc.so.6(__libc_calloc+0xb4)[0x7f3195cc0a14]
Apr 26 04:00:10 aspdrse2 ss-server: /lib/libmbedcrypto.so.0(+0x382ab)[0x7f31964b62ab]
Apr 26 04:00:10 aspdrse2 ss-server: /lib/libmbedcrypto.so.0(mbedtls_md_setup+0x35)[0x7f31964b40c5]
Apr 26 04:00:10 aspdrse2 ss-server: /lib/libmbedcrypto.so.0(mbedtls_md_hmac+0x55)[0x7f31964b47e7]
Apr 26 04:00:10 aspdrse2 ss-server: /usr/local/bin/ss-server[0x41404b]
Apr 26 04:00:10 aspdrse2 ss-server: /usr/local/bin/ss-server[0x414300]
Apr 26 04:00:10 aspdrse2 ss-server: /usr/local/bin/ss-server[0x4146a6]
Apr 26 04:00:10 aspdrse2 ss-server: /usr/local/bin/ss-server[0x4153d8]
Apr 26 04:00:10 aspdrse2 ss-server: /usr/local/bin/ss-server[0x410d98]
Apr 26 04:00:10 aspdrse2 ss-server: /lib64/libev.so.4(ev_invoke_pending+0x57)[0x7f3196b60587]
Apr 26 04:00:10 aspdrse2 ss-server: /lib64/libev.so.4(ev_run+0x7ad)[0x7f3196b6378d]
Apr 26 04:00:10 aspdrse2 ss-server: /usr/local/bin/ss-server[0x4045ea]
Apr 26 04:00:10 aspdrse2 ss-server: /lib64/libc.so.6(__libc_start_main+0xf5)[0x7f3195c61b35]
Apr 26 04:00:10 aspdrse2 ss-server: /usr/local/bin/ss-server[0x405559]
Apr 26 04:00:10 aspdrse2 ss-server: ======= Memory map: ========
Apr 26 04:00:10 aspdrse2 ss-server: 00400000-0042c000 r-xp 00000000 fd:01 29139                              /usr/local/bin/ss-server
Apr 26 04:00:10 aspdrse2 ss-server: 0062b000-0062c000 r--p 0002b000 fd:01 29139                              /usr/local/bin/ss-server
Apr 26 04:00:10 aspdrse2 ss-server: 0062c000-0062d000 rw-p 0002c000 fd:01 29139                              /usr/local/bin/ss-server
Apr 26 04:00:10 aspdrse2 ss-server: 0062d000-00632000 rw-p 00000000 00:00 0
Apr 26 04:00:10 aspdrse2 ss-server: 01746000-01787000 rw-p 00000000 00:00 0                                  [heap]
Apr 26 04:00:10 aspdrse2 ss-server: 7f3190000000-7f3190021000 rw-p 00000000 00:00 0
Apr 26 04:00:10 aspdrse2 ss-server: 7f3190021000-7f3194000000 ---p 00000000 00:00 0
Apr 26 04:00:10 aspdrse2 ss-server: 7f3195660000-7f3195675000 r-xp 00000000 fd:01 397                        /usr/lib64/libgcc_s-4.8.5-20150702.so.1
Apr 26 04:00:10 aspdrse2 ss-server: 7f3195675000-7f3195874000 ---p 00015000 fd:01 397                        /usr/lib64/libgcc_s-4.8.5-20150702.so.1
Apr 26 04:00:10 aspdrse2 ss-server: 7f3195874000-7f3195875000 r--p 00014000 fd:01 397                        /usr/lib64/libgcc_s-4.8.5-20150702.so.1
Apr 26 04:00:10 aspdrse2 ss-server: 7f3195875000-7f3195876000 rw-p 00015000 fd:01 397                        /usr/lib64/libgcc_s-4.8.5-20150702.so.1
Apr 26 04:00:10 aspdrse2 ss-server: 7f3195876000-7f3195882000 r-xp 00000000 fd:01 4718                       /usr/lib64/libnss_files-2.17.so
Apr 26 04:00:10 aspdrse2 ss-server: 7f3195882000-7f3195a81000 ---p 0000c000 fd:01 4718                       /usr/lib64/libnss_files-2.17.so
Apr 26 04:00:10 aspdrse2 ss-server: 7f3195a81000-7f3195a82000 r--p 0000b000 fd:01 4718                       /usr/lib64/libnss_files-2.17.so
Apr 26 04:00:10 aspdrse2 ss-server: 7f3195a82000-7f3195a83000 rw-p 0000c000 fd:01 4718                       /usr/lib64/libnss_files-2.17.so
Apr 26 04:00:10 aspdrse2 ss-server: 7f3195a83000-7f3195c40000 rw-p 00000000 00:00 0
Apr 26 04:00:10 aspdrse2 ss-server: 7f3195c40000-7f3195df6000 r-xp 00000000 fd:01 4700                       /usr/lib64/libc-2.17.so
Apr 26 04:00:10 aspdrse2 ss-server: 7f3195df6000-7f3195ff6000 ---p 001b6000 fd:01 4700                       /usr/lib64/libc-2.17.so
Apr 26 04:00:10 aspdrse2 ss-server: 7f3195ff6000-7f3195ffa000 r--p 001b6000 fd:01 4700                       /usr/lib64/libc-2.17.so
Apr 26 04:00:10 aspdrse2 ss-server: 7f3195ffa000-7f3195ffc000 rw-p 001ba000 fd:01 4700                       /usr/lib64/libc-2.17.so
Apr 26 04:00:10 aspdrse2 ss-server: 7f3195ffc000-7f3196001000 rw-p 00000000 00:00 0
Apr 26 04:00:10 aspdrse2 ss-server: 7f3196001000-7f3196018000 r-xp 00000000 fd:01 4726                       /usr/lib64/libpthread-2.17.so
Apr 26 04:00:10 aspdrse2 ss-server: 7f3196018000-7f3196217000 ---p 00017000 fd:01 4726                       /usr/lib64/libpthread-2.17.so
Apr 26 04:00:10 aspdrse2 ss-server: 7f3196217000-7f3196218000 r--p 00016000 fd:01 4726                       /usr/lib64/libpthread-2.17.so
Apr 26 04:00:10 aspdrse2 ss-server: 7f3196218000-7f3196219000 rw-p 00017000 fd:01 4726                       /usr/lib64/libpthread-2.17.so
Apr 26 04:00:10 aspdrse2 ss-server: 7f3196219000-7f319621d000 rw-p 00000000 00:00 0
Apr 26 04:00:10 aspdrse2 ss-server: 7f319621d000-7f319627d000 r-xp 00000000 fd:01 5104                       /usr/lib64/libpcre.so.1.2.0
Apr 26 04:00:10 aspdrse2 ss-server: 7f319627d000-7f319647c000 ---p 00060000 fd:01 5104                       /usr/lib64/libpcre.so.1.2.0
Apr 26 04:00:10 aspdrse2 ss-server: 7f319647c000-7f319647d000 r--p 0005f000 fd:01 5104                       /usr/lib64/libpcre.so.1.2.0
Apr 26 04:00:10 aspdrse2 ss-server: 7f319647d000-7f319647e000 rw-p 00060000 fd:01 5104                       /usr/lib64/libpcre.so.1.2.0
Apr 26 04:00:10 aspdrse2 ss-server: 7f319647e000-7f31964dd000 r-xp 00000000 fd:01 28970                      /usr/lib/libmbedcrypto.so.0
Apr 26 04:00:10 aspdrse2 ss-server: 7f31964dd000-7f31966dc000 ---p 0005f000 fd:01 28970                      /usr/lib/libmbedcrypto.so.0
Apr 26 04:00:10 aspdrse2 ss-server: 7f31966dc000-7f31966df000 r--p 0005e000 fd:01 28970                      /usr/lib/libmbedcrypto.so.0
Apr 26 04:00:10 aspdrse2 systemd: shadowsocks-libev.service: main process exited, code=killed, status=6/ABRT
Apr 26 04:00:10 aspdrse2 ss-server: 7f31966df000-7f31966e0000 rw-p 00061000 fd:01 28970                      /usr/lib/libmbedcrypto.so.0
Apr 26 04:00:10 aspdrse2 ss-server: 7f31966e0000-7f31966e3000 rw-p 00000000 00:00 0
Apr 26 04:00:10 aspdrse2 ss-server: 7f31966e3000-7f319674e000 r-xp 00000000 fd:01 27554                      /usr/lib/libsodium.so.18.2.0
Apr 26 04:00:10 aspdrse2 ss-server: 7f319674e000-7f319694d000 ---p 0006b000 fd:01 27554                      /usr/lib/libsodium.so.18.2.0
Apr 26 04:00:10 aspdrse2 ss-server: 7f319694d000-7f319694e000 r--p 0006a000 fd:01 27554                      /usr/lib/libsodium.so.18.2.0
Apr 26 04:00:10 aspdrse2 ss-server: 7f319694e000-7f319694f000 rw-p 0006b000 fd:01 27554                      /usr/lib/libsodium.so.18.2.0
Apr 26 04:00:10 aspdrse2 ss-server: 7f319694f000-7f319695a000 r-xp 00000000 fd:01 28842                      /usr/lib64/libudns.so.0
Apr 26 04:00:10 aspdrse2 ss-server: 7f319695a000-7f3196b5a000 ---p 0000b000 fd:01 28842                      /usr/lib64/libudns.so.0
Apr 26 04:00:10 aspdrse2 ss-server: 7f3196b5a000-7f3196b5b000 r--p 0000b000 fd:01 28842                      /usr/lib64/libudns.so.0
Apr 26 04:00:10 aspdrse2 ss-server: 7f3196b5b000-7f3196b5c000 rw-p 0000c000 fd:01 28842                      /usr/lib64/libudns.so.0
Apr 26 04:00:10 aspdrse2 ss-server: 7f3196b5c000-7f3196b69000 r-xp 00000000 fd:01 22000                      /usr/lib64/libev.so.4.0.0
Apr 26 04:00:10 aspdrse2 ss-server: 7f3196b69000-7f3196d68000 ---p 0000d000 fd:01 22000                      /usr/lib64/libev.so.4.0.0
Apr 26 04:00:10 aspdrse2 ss-server: 7f3196d68000-7f3196d69000 r--p 0000c000 fd:01 22000                      /usr/lib64/libev.so.4.0.0
Apr 26 04:00:10 aspdrse2 ss-server: 7f3196d69000-7f3196d6a000 rw-p 0000d000 fd:01 22000                      /usr/lib64/libev.so.4.0.0
Apr 26 04:00:10 aspdrse2 ss-server: 7f3196d6a000-7f3196e6a000 r-xp 00000000 fd:01 4708                       /usr/lib64/libm-2.17.so
Apr 26 04:00:10 aspdrse2 ss-server: 7f3196e6a000-7f319706a000 ---p 00100000 fd:01 4708                       /usr/lib64/libm-2.17.so
Apr 26 04:00:10 aspdrse2 ss-server: 7f319706a000-7f319706b000 r--p 00100000 fd:01 4708                       /usr/lib64/libm-2.17.so
Apr 26 04:00:10 aspdrse2 ss-server: 7f319706b000-7f319706c000 rw-p 00101000 fd:01 4708                       /usr/lib64/libm-2.17.so
Apr 26 04:00:10 aspdrse2 ss-server: 7f319706c000-7f319708c000 r-xp 00000000 fd:01 4693                       /usr/lib64/ld-2.17.so
Apr 26 04:00:10 aspdrse2 ss-server: 7f31970c5000-7f3197281000 rw-p 00000000 00:00 0
Apr 26 04:00:10 aspdrse2 ss-server: 7f3197289000-7f319728b000 rw-p 00000000 00:00 0
Apr 26 04:00:10 aspdrse2 ss-server: 7f319728b000-7f319728c000 r--p 0001f000 fd:01 4693                       /usr/lib64/ld-2.17.so
Apr 26 04:00:10 aspdrse2 systemd: Unit shadowsocks-libev.service entered failed state.
Apr 26 04:00:10 aspdrse2 ss-server: 7f319728c000-7f319728d000 rw-p 00020000 fd:01 4693                       /usr/lib64/ld-2.17.so
Apr 26 04:00:10 aspdrse2 ss-server: 7f319728d000-7f319728e000 rw-p 00000000 00:00 0
Apr 26 04:00:10 aspdrse2 ss-server: 7fff14aef000-7fff14b10000 rw-p 00000000 00:00 0                          [stack]
Apr 26 04:00:10 aspdrse2 ss-server: 7fff14b55000-7fff14b57000 r--p 00000000 00:00 0                          [vvar]
Apr 26 04:00:10 aspdrse2 ss-server: 7fff14b57000-7fff14b59000 r-xp 00000000 00:00 0                          [vdso]
Apr 26 04:00:10 aspdrse2 ss-server: ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
Apr 26 04:00:10 aspdrse2 systemd: shadowsocks-libev.service failed.

### What is your config in detail (with all sensitive info masked)?

{
    "server": ["[::0]", "0.0.0.0"],
    "server_port": [hidden],
    "local_port": 8089,
    "password": "[hidden]",
    "timeout": 600,
    "method": "aes-128-gcm"
}

/usr/local/bin/ss-server -a root -c /etc/shadowsocks-libev/config.json -u

**Comment by madeye** [comment]
Could you try the latest commit of shadowsocks-libev?

It looks the same bug with https://github.com/shadowsocks/shadowsocks-libev/issues/1465

**Comment by alexyangjie** [comment]
Thanks. Will try that out. Will comment if there is any further issue.
