### ISSUE TITLE
Connection reset

### ISSUE THREAD

**Issue by hybtoy** [shadowsocks/shadowsocks-libev#1481]
### What version of shadowsocks-libev are you using?
3.0.5

### What operating system are you using?
Ubuntu 16.04.2 LTS

### What did you do?
trying to reach *.google.com

### What did you expect to see?
working site

### What did you see instead?
Connection reset

### What is your config in detail (with all sensitive info masked)?
{
    "server":server_address,
    "server_port":server_port,
    "local_address":"127.0.0.1",
    "local_port":1080,
    "password":"password",
    "timeout":600,
    "method":"chacha20-ietf-poly1305"
}

I understand that connection reset is caused by network route, DPI and etc. 

I tried all versions of simple shadowsocks (Python, libev and go-shadowsocks2) and on all of them I am receiving "connection reset" only on *.google.com for now, everything else is working. 

Maybe I am doing something wrong?

**Comment by madeye** [comment]
> I understand that connection reset is caused by network route, DPI and etc.

Actually not, Shadowsocks uses TCP reset to close connections. It has nothing to do with route, DPI and etc.

**Comment by madeye** [comment]
> Maybe I am doing something wrong?

You did nothing wrong. What you should do is just ignore the TCP reset messages. They're expected.

**Comment by hybtoy** [comment]
@madeye I can ignore messages but I can't ignore that I can not reach google sites

**Comment by madeye** [comment]
@hybtoy I don't think it's related to shadowsocks. Make sure your server's IP is not blocked by Google.

You may also try other server providers' server.

**Comment by hybtoy** [comment]
@madeye I am sure that they are blocked by google, because I tried several providers till now. With SSR everything is OK but with simple ss not. Sometimes google sites are working and sometimes not. I am trying to understand what is the reason.

**Comment by madeye** [comment]
I cannot reproduce your issue locally. If there is any other solution works for you, you may try them instead.

**Comment by hybtoy** [comment]
@madeye Maybe there is an app or program that can trace my requests to google site and explain us what is the problem

**Comment by hybtoy** [comment]
@madeye Simple Shadowsocks is very fast in comparison to SSR. Thats why I am testing simple ss now.

**Comment by madeye** [comment]
> Simple Shadowsocks is very fast in comparison to SSR. Thats why I am testing simple ss now.

SS and SSR should have the same speed. No one is faster than others.

> Maybe there is an app or program that can trace my requests to google site and explain us what is the problem

You can add `-v` to both your server and your client's command line and post all the log here.

**Comment by hybtoy** [comment]
@madeye Could you tell me please, where I can find the logs of ss-libev on the server?

**Comment by madeye** [comment]
Run this command line in your console:

```
ss-server -c /path/to/config.json -v
```

Copy and paste the output here.

**Comment by hybtoy** [comment]
@madeye I am a Windows (10) user

**Comment by madeye** [comment]
I mean get the output on your server. As you said, your server is Ubuntu.

**Comment by hybtoy** [comment]
@madeye 
![aead](https://cloud.githubusercontent.com/assets/12900872/25425481/8ef207de-2a85-11e7-92ba-60ef91123238.png)

**Comment by madeye** [comment]
Everything works well. I didn't see any issue in your log. You are successfully connected to mail.google.com

**Comment by hybtoy** [comment]
@madeye actually not
![aead51](https://cloud.githubusercontent.com/assets/12900872/25425890/d7f8660c-2a86-11e7-954e-a5b575ae4da1.png)
![aead52](https://cloud.githubusercontent.com/assets/12900872/25425891/d84dd970-2a86-11e7-830a-11bedd7eb8da.png)

**Comment by madeye** [comment]
According to your log, your client successfully connected to `mail.google.com` and closed the connection then.

What's your client?

**Comment by hybtoy** [comment]
@madeye Shadowsocks 4.0.1 for Windows

**Comment by madeye** [comment]
Also try this client:

https://github.com/riobard/go-shadowsocks2/releases/download/v0.0.9/shadowsocks2-win64.exe.zip

**Comment by madeye** [comment]
For shadowsocks-windows, enable `Help->Verbose Logging`, visit `www.google.com` and click `Help->Show Logs...`.

**Comment by hybtoy** [comment]
@madeye the same issue

**Comment by madeye** [comment]
BTW, what's your `server_port` in your config file?

**Comment by hybtoy** [comment]
@madeye 995

**Comment by madeye** [comment]
Could you try `443` and `8838` instead?

**Comment by madeye** [comment]
And also try `"method":"chacha20"`.

**Comment by hybtoy** [comment]
@madeye 
chacha20-ietf-poly1305 + 443 = the same, not working
chacha20 + 443 = working, but can not watch youtube videos (siteis working)

**Comment by hybtoy** [comment]
@madeye I am not able not connect to server on port 8838

**Comment by madeye** [comment]
>chacha20-ietf-poly1305 + 443 = the same, not working
> chacha20 + 443 = working, 

It means it should be a bug of shadowsocks-windows. It may related to its AEAD implementation.

> but can not watch youtube videos (siteis working)

I don't think it's related. You may try disabling QUIC: chrome://flags/#enable-quic

**Comment by hybtoy** [comment]
@madeye 
`[2017-04-26 14:11:16] connect to www.google.nl:443
[2017-04-26 14:11:16] Socket connected to ss server: aead (ip:995)
[2017-04-26 14:11:19] connect to live.github.com:443
[2017-04-26 14:11:19] Socket connected to ss server: aead (ip:995)
[2017-04-26 14:11:23] connect to live.github.com:443
[2017-04-26 14:11:23] Socket connected to ss server: aead (ip:995)
`

**Comment by madeye** [comment]
Try this command line client in your windows: https://github.com/riobard/go-shadowsocks2/releases/download/v0.0.9/shadowsocks2-win64.exe.zip

**Comment by zhou0** [comment]
@hybtoy  try mysocks https://github.com/zhou0/mysocks/releases/tag/0.5.2

**Comment by hybtoy** [comment]
@madeye tried that command line client - the same issue.

**Comment by madeye** [comment]
Post the log of that command line client here.

**Comment by hybtoy** [comment]
@zhou0 AEAD is not supported.

**Comment by zhou0** [comment]
@hybtoy  no, mysocks-wolfssl supports chacha20 AEAD.

**Comment by hybtoy** [comment]
@madeye 
![aead6](https://cloud.githubusercontent.com/assets/12900872/25427694/c85a7306-2a8c-11e7-996d-03106b7ac391.png)

**Comment by madeye** [comment]
Interesting. What's your ISP and network?

**Comment by hybtoy** [comment]
@madeye can I write you an email?

**Comment by madeye** [comment]
Yes, you can send an email.

**Comment by zhou0** [comment]
@hybtoy  I just tested mysocsks-wolfssl again using chacha20-ietf-poly1305 method with ss-libev 3.0.6 and it is good.

**Comment by hybtoy** [comment]
@madeye check your inbox please. 

@zhou0 
![ss](https://cloud.githubusercontent.com/assets/12900872/25428197/8c32a4b4-2a8e-11e7-92ed-b90f23458a32.png)

**Comment by madeye** [comment]
It turns out that @hybtoy's ISP resets all the unknown TCP connections.

You may need to use https://github.com/shadowsocks/simple-obfs or https://github.com/xtaci/kcptun with shadowsocks.

SSR's obfuscation should also work for you.

**Comment by hybtoy** [comment]
@madeye The problem is only with google. Other site are working normally. This is very strange.

**Comment by zhou0** [comment]
@hybtoy  did you enable remote DNS via socks5?

**Comment by zhou0** [comment]
@hybtoy  looks like ss-libev server problem.  You can try perl server.  on Ubuntu host, issue these 2 commands

sudo cpan -T AnyEvent::AIO Crypt::NaCl::Sodium EV IO::AIO Net::Shadowsocks
ssserver.pl -s localhost -p 1491 -k whatever -m chacha20-ietf-poly1305
