### ISSUE TITLE
When will you guys update it to lastest version on debian main repository?

### ISSUE THREAD

**Issue by makingworld** [shadowsocks/shadowsocks-libev#1482]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
2.6

### What operating system are you using?
debian8.7

### What did you do?
nothing

### What did you expect to see?
can install lastest version by apt-get directly

### What did you see instead?
cannot

### What is your config in detail (with all sensitive info masked)?
noneed

**Comment by jnaskali** [comment]
I'm using 3.0.5 from the official Debian 8 repo.  It gets updated pretty fast, it's just that the latest version stays experimental for quite a long time.

Add `deb http://ftp.debian.org/debian experimental main contrib non-free` to your /etc/apt/sources.list and install with `apt-get update && apt-get -t experimental install deluge`

**Comment by makingworld** [comment]
@jnaskali thx for your help, that's useful to me
