### ISSUE TITLE
ss-manager can't auto open firewall port

### ISSUE THREAD

**Issue by danywheeler** [shadowsocks/shadowsocks-libev#1488]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
shadowsocks-libev 2.5.5 with OpenSSL 1.0.1e 11 Feb 2013

### What operating system are you using?
centos 7

### What did you do?
not relevant

### What did you expect to see?
auto open firewall port

### What did you see instead?
I have to config firewall to open a port section for this to work!

### What is your config in detail (with all sensitive info masked)?
not relevant

**Comment by madeye** [comment]
It's expected. You need to open the ports manually.

**Comment by danywheeler** [comment]
can implement something like ftp ? a kernel mod work between ss-manager and netfilter so we can only open the ports we need ?
