### ISSUE TITLE
Dropping UDP packets in global mode

### ISSUE THREAD

**Issue by michaelzzj** [shadowsocks/shadowsocks-libev#1489]
### What version of shadowsocks-libev are you using?
Server: 3.0.6
Client: 3.0.5

### What operating system are you using?
Server: CentOS 6
Client: OpenWrt

### What did you do?
Enabled UDP relay on both sides.
Set the ignore list to empty, i.e., global mode.

### What did you expect to see?
Forwarding DNS packets correctly.

### What did you see instead?
All DNS packets are dropped.

### What is your config in detail (with all sensitive info masked)?
---

I figured out the problem happens when the gateway IP is not in the ignore list. As long as the gate IP (e.g., x.x.x.x/24) is in the list, DNS packets can be forwarded as expected. TCP connections are fine in this case.

**Comment by madeye** [comment]
I don't think it's an issue of shadowsocks-libev. Double check your iptables rules.

**Comment by michaelzzj** [comment]
But I don't know what kind of rules can cause this issue. Can you give me some hints?

**Comment by madeye** [comment]
No idea. You have to debug yourself for your own network configurations.
