### ISSUE TITLE
[Feature request] ss-local UDP relay: Could you please let the fd used to get sock_addr to be the real udp socket fd?

### ISSUE THREAD

**Issue by happyfire** [shadowsocks/shadowsocks-libev#1491]
In local.c, server_recv_cb():
```
if (request->cmd == 3) {
                udp_assc = 1;
                socklen_t addr_len = sizeof(sock_addr);
                getsockname(server->fd, (struct sockaddr *)&sock_addr,
                            &addr_len);
                if (verbose) {
                    LOGI("udp assc request accepted");
                }
            }
``` 
In the call of getsockname, the server->fd is the TCP accepted fd, here we should use the udp listen fd, which is get in init_udprelay() (in udprelay.c):
```
// Bind to port
    int serverfd = create_server_socket(server_host, server_port);
    if (serverfd < 0) {
        FATAL("[udp] bind() error");
    }
```

**Comment by madeye** [comment]
We're assuming both UDP and TCP are using the same `addr:port`. So, it's not a bug here.

**Comment by happyfire** [comment]
But the port assigned can be 0, in this situation, it is wrong. And just from code, it is wrong for misuse the wrong fd.

**Comment by madeye** [comment]
> But the port assigned can be 0.

You should not do this. This kind of usage is not supported.

> And just from code, it is wrong for misuse the wrong fd.

As I said, there is an assumption.

**Comment by happyfire** [comment]
hey, If you embed ss-local in a client app in platform such as Android or iOS, we can not use a well-known port, so use 0 is meaningful.

**Comment by madeye** [comment]
> hey, If you embed ss-local in a client app in platform such as Android or iOS, we can not use a well-known port, so use 0 is meaningful.

Unfortunately, ss-local doesn't support that way of usage. Of course, any pull request is welcome.
