### ISSUE TITLE
求教

### ISSUE THREAD

**Issue by Galaxy0419** [shadowsocks/shadowsocks-libev#1492]
请问AEAD中的xchacha20-ietf-poly1305和aes gcm加密系列那个更好，速度更快

**Comment by zhou0** [comment]
@Galaxy0419 if cpu supports AES-NI, aes gcm. if not, xchacha20-ietf-poly1305.

**Comment by lixingcong** [comment]
怎么都3年过去了还有人问这个问题。。。

我不考虑哪个加密，掏钱买线路

**Comment by Galaxy0419** [comment]
@lixingcong 加密方式和速度也有一定关系好么？我只是在问那种加密在对应平台上加密效率高.

**Comment by suikatomoki** [comment]
chacha20快
https://github.com/shadowsocks/luci-app-shadowsocks/wiki/Bandwidth-of-encrypt-method
