### ISSUE TITLE
APT源的版本略旧...而且编译安装完还是旧版本...

### ISSUE THREAD

**Issue by LBYPatrick** [shadowsocks/shadowsocks-libev#1496]
### What version of shadowsocks-libev are you using?
2.4.8

### What operating system are you using?
Ubuntu 16.10

### What did you do?
```
Apt-get install shadowsocks-libev
```
### What did you expect to see?
A higher version available in APT repository ( i.e. 3.0.x)

### What did you see instead?
2.4.8...

**Comment by hosiet** [comment]
Ubuntu 16.10 will reach EOL within 2 months. You are encouraged to upgrade to Ubuntu 17.04 and get a newer version (2.6.3).

Ss-libev 3.x requires several extra dependencies and might not be available in official repository before Ubuntu 17.10.

If you decide to compile and install a newer version, you will need to sort out the problems by yourself.

**Comment by debiansid** [comment]
You can even install 3.0.6 on wheezy

**Comment by LBYPatrick** [comment]
I won't upgrade to 17.04 just because the DNS service has changed, causing some weird problems with my bind9. Are there any performance improvements in 3.x?

**Comment by rogers0** [comment]
@LBYPatrick scripts/build_deb.sh
