### ISSUE TITLE
能否实现本地端口映射到VPS对应端口？

### ISSUE THREAD

**Issue by akaneko252** [shadowsocks/shadowsocks-libev#1497]
本人新手请教一个问题，现有一台网件的NAS需要连接至墙外官网激活，实际就是让官网检测NAS的21/22/443/80几个端口。因NAS无法独立获得IP必须连接至路由进行激活，同网段电脑经过ss-openwrt能访问官网，但在电脑上运行激活程序时提示连接不通。

运行官网的端口测试页http://support.stora.hipserv.com/en/router/testportforward.html ，显示为：
You have 0 out of 4 ports open (going to your Stora from the Internet). See details below.
Your External IP Address is: My VPS External IP
Port 21 (FTP access): This port is closeed.（已在iptable开放对应端口，否则为blocked）
Port 22 (Support): A device other than your Stora is listening on this port.
Port 443 (Secure Web access): This port is closeed.
Port 80 (Web access): This port is closeed.

网络实例较为复杂，本地ISP为小区宽带没有公网IP（按常理外网无法访问NAS，因为无法让ISP路由做端口映射），VPS为google cloud，因为有Internal IP和External IP，不清楚VPS内是否也有路由，所以网络大致如下：
NAS——家庭路由——ISP路由——VPS——NETGEAR官网

请问本次情况可以使用ss/svpn结合端口映射解决吗？还是因为没有公网IP导致激活无解？

谢谢！

**Comment by madeye** [comment]
No plan for this. A possible solution is `SSH -R` over shadowsocks.
