### ISSUE TITLE
Considering add repository to openSUSE

### ISSUE THREAD

**Issue by runapp** [shadowsocks/shadowsocks-libev#1498]
```
zypper addrepo http://download.opensuse.org/repositories/home:runapp/openSUSE_Leap_42.2/home:runapp.repo
zypper refresh
zypper install shadowsocks-libev
```

Currently only openSUSE_Leap_42.2 is supported. More release versions will be added later.

**Comment by madeye** [comment]
Please Open a pull request instead.

**Comment by runapp** [comment]
Will the personal repository be OK?

**Comment by madeye** [comment]
Make sure your repo is hosted on OpenSUSE, then it's OK.

**Comment by madeye** [comment]
Closed due to inactivity.
