### ISSUE TITLE
libsodium多版本？导致的编译失败

### ISSUE THREAD

**Issue by akaneko252** [shadowsocks/shadowsocks-libev#1501]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
事前已.deb安装好3.05 
本次操作为源码编译升级至3.06

### What operating system are you using?
ubuntu 16.10

### What did you do?
分别用不同方法3次安装libsodium，每次安装完成后编译源码均失败，第4次apt-get remove卸载后编译成功。

 ## 第1次安装libsodium：
export LIBSODIUM_VER=1.0.12
wget https://download.libsodium.org/libsodium/releases/libsodium-$LIBSODIUM_VER.tar.gz
tar xvf libsodium-$LIBSODIUM_VER.tar.gz
pushd libsodium-$LIBSODIUM_VER
./configure --prefix=/usr && make
sudo make install
popd
sudo ldconfig

**安装成功后，./configure不通过，提示：**
configure: error: Wrong libsodium: version >= 1.0.4 required

 ## 第2次安装libsodium：
wget https://github.com/jedisct1/libsodium/releases/download/1.0.12/libsodium-1.0.12.tar.gz
tar xf libsodium-1.0.12.tar.gz && cd libsodium-1.0.12
./configure && make -j2 && make install
ldconfig

**安装成功后，./configure通过，make失败，提示同： #1177**

 ## 第3次安装libsodium：
root@vps:~# apt-get install libsodium-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  libsodium-dev
0 upgraded, 1 newly installed, 0 to remove and 6 not upgraded.
Need to get 0 B/163 kB of archives.
After this operation, 968 kB of additional disk space will be used.
Selecting previously unselected package libsodium-dev:amd64.
(Reading database ... 83248 files and directories currently installed.)
Preparing to unpack .../libsodium-dev_1.0.11-1_amd64.deb ...
Unpacking libsodium-dev:amd64 (1.0.11-1) ...
Setting up libsodium-dev:amd64 (1.0.11-1) ...

**安装成功后，结果同第2次**

 ## 第4次卸载libsodium：
root@vps:~# apt-get remove libsodium-dev -y
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages will be REMOVED:
  libsodium-dev
0 upgraded, 0 newly installed, 1 to remove and 6 not upgraded.
After this operation, 968 kB disk space will be freed.
(Reading database ... 83312 files and directories currently installed.)
Removing libsodium-dev:amd64 (1.0.11-1) ...
dpkg: warning: while removing libsodium-dev:amd64, directory '/usr/include/sodium' not empty so not removed

**./configure通过，make成功，安装后ss显示为3.0.6版**

## **疑问：**
1、为什么第1次安装成功系统却不能识别？
2、为什么第2次能通过configure却不能make
3、为什么第3次能成功安装1.0.11-1版，不应该是检测到有高版本而安装失败吗？
4、为什么第4次卸载后没有其他额外操作就能make成功，当然前3次每次完成后都有update && upgrade
5、卸载libsodium时提示：directory '/usr/include/sodium' not empty so not removed，对以后会存在其他影响吗？

## **谢谢解答！**

**Comment by changyp6** [comment]
你用的是Ubuntu系统，Ubuntu系统的包管理用的是DEB包，你在系统里面已经安装了Ubuntu自带的老版本的libsodium，系统自带的libsodium的安装prefix是/usr。
你自己编译安装的libsodium安装路径是/usr/local，系统在编译的时候，会按照一定的搜索路径来查找你当前系统中已经安装的library，先找到了Ubuntu自带的老版本，所以就直接报错。

当你把系统自带的版本删掉后，编译的时候，查找到的就是你安装的libsodium的版本了。

你的这种在自带包管理的系统中自己编译源码安装相同软件的作法，是错误的。这样会导致系统中的library出现冲突。
建议你把最新的libsodium打包成deb包，然后直接升级系统的libsodium。
这个根本不是bug，是你自己对Linux系统的理解错误导致的。

**Comment by akaneko252** [comment]
谢谢指教！

**Comment by akaneko252** [comment]
我想应该是作者说明里的Installation/Linux，先是给出apt-get install方式安装依赖里有libsodium，

#Installation of basic build dependencies
##Debian / Ubuntu
sudo apt-get install --no-install-recommends gettext build-essential autoconf libtool libpcre3-dev asciidoc xmlto libev-dev libudns-dev automake libmbedtls-dev  **libsodium-dev**

然后又用源码编译的方式说明了怎样安装libsodium 1.0.12 导致，

#Installation of Libsodium
export **LIBSODIUM_VER=1.0.12**
......
./configure --prefix=/usr && make

不知“系统自带的libsodium的安装prefix是/usr”是举例还是实例，因为作者说明编译1.0.12版方法时，也指定了编译路径为/usr，如果是实例的话按理不应该出错才是。

**Comment by Galaxy0419** [comment]
先apt purge libsodium-dev然后把新版编译安装到/usr下就好

**Comment by yaoguaishou** [comment]
我也遇到这个问题，我已经添加了ubuntu14.04的ppa，想要更新。最后删掉所有libsodium和shadowsocks的ppa才能正常编译deb包

**Comment by younasiqw** [comment]
我centos7libsodium 安装失败 !求解

**Comment by wpvsyou** [comment]
me too > <!!!
