### ISSUE TITLE
SOCKS5 UDP ASSOCIATE terminates TCP connection prematurely

### ISSUE THREAD

**Issue by arvidn** [shadowsocks/shadowsocks-libev#1502]
I'm filing this on behalf of a user of my library.

### What version of shadowsocks-libev are you using?

Problem is present in current master by inspection of [source code](https://github.com/shadowsocks/shadowsocks-libev/blob/72622a3e3df0d8b66f005717ecc48264275f453c/src/local.c#L559).

### What did you do?

Connect a SOCKS5 client to the SOCKS5 interface and sent a UDP ASSOCIATE command.

### What did you expect to see?

I expected to receive a SOCKS5 response (which I did) and have the TCP connection **left open**. 

### What did you see instead?

The TCP connection was immediately terminated after the UDP ASSOCIATE response was received. This causes my client to consider the UDP proxy port to be closed ([per specification](https://tools.ietf.org/html/rfc1928#page-7)) and try again.

One of my problems is that I retry too soon, but the fundamental problem is that since the connection is closed immediately from the SOCKS server side, the client never has any opportunity to send UDP packets.

Specifically, the part of the SOCKS5 specification I would like to highlight is:

> A UDP association terminates when the TCP connection that the UDP
> ASSOCIATE request arrived on terminates.

My understanding of a (very cursory) reading of the code, you open a UDP proxy unconditionally and allow anyone to use it. When someone sends a UDP ASSOCIATE command, you simply refer them to this proxy and disconnects.

In order to be compliant, I would suggest you leave the TCP connection open until the _client_ disconnects, indicating that it no longer need the proxy.

The issue where this was reported to me is [here](https://github.com/arvidn/libtorrent/issues/1987).

**Comment by happyfire** [comment]
The tcp connection for udp relay is closed after fake replay, but strongly why the browser works fine under socks5 proxy to ss-local, because of the browser not  abide by the RFC? I am not sure. For my situation, I only use ss-local as my socks5 server, so I will not do anyting when the tcp connectiojnj is closed, after the udp handshake response I get the UDP port, I will use this port until the application closed.

**Comment by arvidn** [comment]
I see, I may have misunderstood the purpose of the socks5 interface then. @kc1212 was under the impression that it was a generic socks5 interface to hook up any application to, not just the one you use.

**Comment by kc1212** [comment]
This is certainly news to me, I've always been under the impression that shadowsocks should have a generic SOCKS5 interface. The man page says "Shadowsocks-libev is a lightweight and secure socks5 proxy". If it's not generic, what application does shadowsocks support?

**Comment by arvidn** [comment]
> I use ss-local as my only socks5 server, so I will not do anything when the tcp connection is closed

I take it "I" in that sentence refer to some program. Is it the case that this is expected to be the only client of the "socks5" interface? i.e. it's for internal use only.

**Comment by happyfire** [comment]
> I take it "I" in that sentence refer to some program. Is it the case that this is expected to be the only client of the "socks5" interface? i.e. it's for internal use only.
Yes, I have a program use ss-libev as a library, so it's for internal use only.
