### ISSUE TITLE
为什么把mbedtls安装在其他目录会失败?

### ISSUE THREAD

**Issue by Galaxy0419** [shadowsocks/shadowsocks-libev#1504]
安装到/usr/local/后把bin目录添加到PATH变量，并且把lib目录添加到ld.so.conf后执行ldconfig。但是编译时候还是报错，但是直接装/usr默认位置就不会报错,求教为什么难道是include文件夹的问题?

**Comment by caobug** [comment]
连个类似于manve,gradle,pod的包管理工具都没有，我的天。我连续编译了两天在XCODE中都运行不起来来，天哪，我该怎么办？

**Comment by happyfire** [comment]
@caobug 作者不提供ios平台的支持的，而且这个东西真不是一个pod能解决的，他依赖太多的库，这些库都是一些c的底层库，都没有Pod。不过放到xcode中编译是没问题的。。麻烦点了就是

**Comment by caobug** [comment]
@happyfire Git clone并导入Idea后调用start_ss_local_server()函数若能提示Host错误，就算整个环境OK。现在的问题是各种依赖错误，解决一堆还有一堆，永无止境。如果部署文档更详细点，我们也能快速上手新增特性和修正缺陷。

**Comment by happyfire** [comment]
@caobug 你是要做mac平台还是ios，如果是mac跟着readme就可以编译出来，难度和问题其实和linux一样，看你要用xcode编译，估计是要搞ios吧，那些依赖库就只能手工来了，有的库可以交叉编译出.a，有的编译出来.a还用不了最后直接包含代码编译搞定，反正我最终是成功了，过程就已经忘了，结论是可以的，所以慢慢来吧

**Comment by caobug** [comment]
@happyfire 对，确实是要搞IOS，被你发现了哈哈。目前卡在libmbedtls和libopenssl两个依赖包上，总报一些莫名其妙的错误，不仅不能定位到某行还没有用的文本提示。一句not found for architecture x86_64让我分不清东西南北。兄弟，你有时间写篇基于xcode编译 shadowsocks-libev-ios 的文章吗？

**Comment by happyfire** [comment]
@caobug libmbedtls直接把代码加进去编译吧，交叉编译出来不好使我最终也没解决，openssl现在好像已经不依赖了吧

**Comment by caobug** [comment]
@happyfire  恩，我等会试一下直接用libmbedtls源码。shadowsocks-libev/src/utils.h有#include <openssl/opensslv.h>哦，不知道到底依赖不依赖呢

**Comment by happyfire** [comment]
新版已经改用mbedtls了，你定义USE_CRYPTO_MBEDTLS就可以了。

**Comment by caobug** [comment]
@happyfire 谢谢兄弟，我又开始重头折腾。解决了一堆 "duplicate symbols for architecture x86_64" 依赖问题后，又出新错：
```
Undefined symbols for architecture x86_64:
  "_dns_pton", referenced from:
      _parse_udprealy_header in udprelay.o
      _bind_to_address in netutils.o
      _get_sockaddr in netutils.o
      _dns_add_serv in udns_resolver.o
  "_dns_ntop", referenced from:
      _server_recv_cb in local.o
      _parse_udprealy_header in udprelay.o
      _get_addr_str in udprelay.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
也不知什么原因，你有遇到过吗？

**Comment by happyfire** [comment]
@caobug 没遇过这问题。似乎在这个issue里面讨论不太合适，要么你加这个qq群私聊3851896
