### ISSUE TITLE
Can not install shadowsocks-libev-openwrt

### ISSUE THREAD

**Issue by nishuo** [shadowsocks/shadowsocks-libev#1510]
### What version of shadowsocks-libev are you using?
3.0.6-1

### What operating system are you using?
LEDE Reboot 17.01-SNAPSHOT r3199-0a26490 / LuCI lede-17.01 branch (git-17.047.46165-f535090)

### What did you expect to see?
I would like to install shadowsocks-libev on the LEDE firmware.

root@LEDE:~# opkg install shadowsocks-libev_3.0.6-1_mipsel_24kc.ipk 
Installing shadowsocks-libev (3.0.6-1) to root...
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for shadowsocks-libev:
 * 	libev * 	libpcre * 
 * opkg_install_cmd: Cannot install package shadowsocks-libev.

**Comment by suikatomoki** [comment]
see: `http://openwrt-dist.sourceforge.net/`

**Comment by madeye** [comment]
Contact the downstream maintainer for the support.
