### ISSUE TITLE
新bug

### ISSUE THREAD

**Issue by Galaxy0419** [shadowsocks/shadowsocks-libev#1511]
使用nohup启动时加-f以自定义路径储存时，日志无法记录。
启动命令nohup nice -n -20 /usr/local/bin/ss-server -c /root/config.json -f /root/ss.pid -vu -a nobody > ss.log 2>&1 &
用cat查看ss.log无内容！

**Comment by Galaxy0419** [comment]
而且会莫名导致速度降低,去掉-f后就没事

**Comment by madeye** [comment]
Check your system log.

**Comment by Galaxy0419** [comment]
@madeye how to check system bug

**Comment by madeye** [comment]
https://www.google.com/search?q=how+to+check+system+log+on+ubuntu

**Comment by rule2c** [comment]
你要装个syslogd
