### ISSUE TITLE
support ipv6 fallback to ipv4

### ISSUE THREAD

**Issue by mghadam** [shadowsocks/shadowsocks-libev#1512]
When the ss-server is running with -6 parameter I see on http://ipv6-test.com/ that no ipv4 fallback is set, it would be good to have setting to set the fallback timeout for ipv6 to ipv4 in the config file. 

I see an ipv6 to ipv4 fallback of 1sec when using ssh tunnel instead. 

tested on shadowsocks-libev 3.0.6

**Comment by madeye** [comment]
See https://github.com/shadowsocks/shadowsocks-libev/issues/942

**Comment by whour** [comment]
http://ipip.net  test you ipv4 address
http://ipv6test.google.com/ test you ipv6 address
