### ISSUE TITLE
请问xchacha20-ietf-poly1305是怎样的一个算法

### ISSUE THREAD

**Issue by Galaxy0419** [shadowsocks/shadowsocks-libev#1513]
在我的vps上使用这种算法速度最佳，但是网上文献资料好像很少,他和普通chacha20系列什么区别?求教

**Comment by wtlusvm** [comment]
[Google](https://download.libsodium.org/doc/secret-key_cryptography/xchacha20-poly1305_construction.html)一下不就知道了吗

**Comment by Galaxy0419** [comment]
Google几乎搜不到，现在xchacha20还没有规范
wtlusvm <notifications@github.com>于2017年6月2日 周五上午9:48写道：

**Comment by wtlusvm** [comment]
那个Google你没有注意到是蓝色的吗……是超链接啊

**Comment by Galaxy0419** [comment]
好吧。。。但是这个算法有什么特点？为什么会快速？
wtlusvm <notifications@github.com>于2017年6月2日 周五上午11:14写道：

**Comment by speeedturtle** [comment]
在libsodium.org 有详细说明
