### ISSUE TITLE
Upgrade to latest version?

### ISSUE THREAD

**Issue by scegg** [shadowsocks/shadowsocks-libev#1517]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
shadowsocks-libev/zestry, 2.6.3+ds-1 amd64

### What operating system are you using?
Ubuntu Server 17.04

### What did you do?
sudo apt update
sudo apt install shadowsocks-libev

### What did you expect to see?
N/A

### What did you see instead?
N/A

### What is your config in detail (with all sensitive info masked)?
N/A

---

Hello.

Sorry for this interruption.
The version I installed shadowsocks-libev using apt, is 2.6.3+ds-1 amd64. Is that the latest one?
If not, what's the correct way to install and keep using the latest version?

Thanks a lot.

**Comment by hosiet** [comment]
#1496 
Thanks

**Comment by scegg** [comment]
@hosiet Thanks for your reply. It seems that this is a known issue and will be resolved later?

**Comment by hosiet** [comment]
Upgrading in official repository is unlikely to happen on published non-LTS Ubuntu (e.g., Ubuntu 16.10, Ubuntu 17.04, etc).

**Comment by scegg** [comment]
Yep, so just waiting for the release of 17.10 lol.

**Comment by odkrys** [comment]
`apt-get update && apt-get install --no-install-recommends git gettext build-essential autoconf libtool libpcre3-dev asciidoc xmlto libev-dev libudns-dev automake`

`git clone https://github.com/shadowsocks/shadowsocks-libev.git`
`cd shadowsocks-libev`
`git submodule update --init --recursive`

`export LIBSODIUM_VER=1.0.12`
`wget https://download.libsodium.org/libsodium/releases/libsodium-$LIBSODIUM_VER.tar.gz`
`tar xvf libsodium-$LIBSODIUM_VER.tar.gz`
`pushd libsodium-$LIBSODIUM_VER`
`./configure --prefix=/usr && make`
`make install`
`popd`
`ldconfig`

`export MBEDTLS_VER=2.4.2`
`wget https://tls.mbed.org/download/mbedtls-$MBEDTLS_VER-gpl.tgz`
`tar xvf mbedtls-$MBEDTLS_VER-gpl.tgz`
`pushd mbedtls-$MBEDTLS_VER`
`make SHARED=1 CFLAGS=-fPIC`
`make DESTDIR=/usr install`
`popd`
`ldconfig`

`./autogen.sh && ./configure --prefix=/usr && make`
`make install`

`mkdir -p /etc/shadowsocks-libev`
`cp ./debian/shadowsocks-libev.init /etc/init.d/shadowsocks-libev`
`cp ./debian/shadowsocks-libev.default /etc/default/shadowsocks-libev`
`cp ./debian/shadowsocks-libev.service /lib/systemd/system/`
`cp ./debian/config.json /etc/shadowsocks-libev/config.json`
`chmod +x /etc/init.d/shadowsocks-libev`

`update-rc.d shadowsocks-libev defaults`
`update-rc.d shadowsocks-libev enable`

Set your server configuration.

`nano /etc/shadowsocks-libev/config.json`

If you need simple-obfs.

`git clone https://github.com/shadowsocks/simple-obfs.git`
`cd simple-obfs`
`git submodule update --init --recursive`
`./autogen.sh && ./configure --prefix=/usr && make`
`make install`

`service shadowsocks-libev start`

**Comment by scegg** [comment]
Thanks @odkrys.
I guess I just leave it, waiting for 17.10 released.
Compiling manually will start a new repeat task chain to keep upgrading by one self. I'd like to do that with apt upgrade.

**Comment by odkrys** [comment]
`sudo add-apt-repository ppa:max-c-lv/shadowsocks-libev`
`sudo apt-get update`
`sudo apt install shadowsocks-libev`

Were you tried this?
It works on my 16.04 vps.

**Comment by scegg** [comment]
It's not work for me. 17.04.
Error while apt update:
http://ppa.launchpad.net/max-c-lv/shadowsocks-libev/ubuntu zesty Release
  404  Not Found

**Comment by odkrys** [comment]
`add-apt-repository "deb http://archive.ubuntu.com/ubuntu artful universe"`
`apt-get update`
`apt-get -t artful install shadowsocks-libev`

**Comment by scegg** [comment]
Hmm, it may lead to some error for OS further upgrading. Thanks for your commands provided, but I just want to wait for 17.10 released.

**Comment by odkrys** [comment]
It comes form 17.10 repo. I don't think it will make compatible issue.
Anyway, it's up to you. Good luck.

**Comment by ky0ncheng** [comment]
collect2: error: ld returned 1 exit status
Makefile:677: recipe for target 'ss-local' failed
make[2]: *** [ss-local] Error 1
make[2]: Leaving directory '/root/shadowsocks-libev/src'
Makefile:479: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/root/shadowsocks-libev'
Makefile:388: recipe for target 'all' failed
make: *** [all] Error 2
