### ISSUE TITLE
[请教]AEAD 类算法在Google Compute Engine和UML中都无法完成握手鉴权

### ISSUE THREAD

**Issue by zhfreal** [shadowsocks/shadowsocks-libev#1529]
### What version of shadowsocks-libev are you using?
latest

### What operating system are you using?
Ubuntu 16.04 x64

### What did you do?
modify the method to aes-256-gcm/chacha20-ietf-poly1305/xchacha20-ietf-poly1305

### What did you expect to see?
work normally

### What did you see instead?
2017-06-14 16:07:14 ERROR: failed to handshake with xxxx: malicious fragmentation
 2017-06-14 16:07:21 ERROR: failed to handshake with xxxxx: authentication error

### What is your config in detail (with all sensitive info masked)?
    "server":["0.0.0.0"],
    "server_port":8100,
    "password":"xxxxxxxxxx",
    "timeout":60,
    "mtu":1024,
    "method":"aes-256-gcm",
    "fast_open":false

**Comment by zhfreal** [comment]
@madeye ， libsodium、libmbed和shadowsocks-libev已经编译了最新的版本，环境是Ubuntu 16.04 x64

**Comment by zhfreal** [comment]
配置之类的，大概就是这样
    "server":["0.0.0.0"],
    "server_port":8100,
    "password":"xxxxx",
    "timeout":60,
    "mtu":1024,
    "method":"aes-256-gcm",
    "fast_open":false

**Comment by zhfreal** [comment]
@madeye ，这事儿有点奇怪。我手上还有一个VPS，AEAD之类的协议完全没有问题。UML和Google的VPS不同之处可能是使用了 NAT之类的网络，难道是因为这个原因导致无法完成握手？

**Comment by zhfreal** [comment]
@madeye ，已经按模板写了。。。。

**Comment by madeye** [comment]
Tried on GCE with aes-128-gcm, aes-256-gcm, chacha20-ietf-poly1305. Everything works well.

So, double check your configurations.

BTW, NAT has nothing to do with your problem.

```
2017-06-14 16:07:21 ERROR: failed to handshake with xxxxx: authentication error
```

This log means you have set a wrong password or cipher name.

**Comment by zhfreal** [comment]
@madeye ， 可能是其他客户端没有改参数导致“authentication error”。 
另外，请教一下 “block all requests from 10.0.0.1”这种情况是不是所有从10.0.0.1发过来连接本端口的都会被block

**Comment by madeye** [comment]
@zhfreal Right, you can add this IP address to the white list. Search the issue tracker for more details.

**Comment by zhfreal** [comment]
@madeye ，我大概知道是什么问题了。程序没有问题，可能是因为我的客户端比较多，来不及改所有客户端参数的情况下，特别是又因为可能使用kcptun的原因，导致大量出现鉴权失败，而服务端block了连接，对应UML和GCE这种情况可能就被封掉了所有连接，参数正常的客户端也无法连接了。
