### ISSUE TITLE
no ss-server created using ss-manager when runing as another user

### ISSUE THREAD

**Issue by RunningCool** [shadowsocks/shadowsocks-libev#1531]
### What version of shadowsocks-libev are you using?
3.0.6

### What operating system are you using?
Linux rick 2.6.32-042stab120.18 #1 SMP Fri Jan 13 10:32:04 MSK 2017 x86_64 x86_64 x86_64 GNU/Linux

### What did you do?
`sudo ss-manager -c /etc/shadowsocks.json -a shadowsocks `

### What did you expect to see?
When I run the above command without `-a shadowsocks`, several `ss-server` instances were started, and I can see them in `ps -A | grep ss-`. 

### What did you see instead?
When the `-a shadowsocks` is present, no `ss-server` is started. No additional error information was shown in the console.

### What is your config in detail (with all sensitive info masked)?
The config file is placed at `/etc/shadowsocks.json`, as a convention from the python version of shadowsocks. All the ports are greater than 1024.

`{
    "server":"xx.xx.xx.xx",
    "port_password": {
        "6666": "password1",
        "7777": "password2",
        "8888": "password3"
},
    "timeout":300,
    "method":"rc4-md5",
    "fast_open": false,
    "mode": "tcp_and_udp"
}
`

**Comment by madeye** [comment]
Try babc9c4
