### ISSUE TITLE
[udp] server_recv_sendto fragmentation

### ISSUE THREAD

**Issue by enihcam** [shadowsocks/shadowsocks-libev#1534]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
3.0.6

### What operating system are you using?
Archlinux

### What did you do?
Skype with friends overseas

### What did you expect to see?
Continuous video experience

### What did you see instead?
Video was clear and continuous but sometimes the connection was disconnected, and I see this:

`
Jun 20 07:45:36 archnet ss-redir[408]:  2017-06-20 07:45:35 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:45:36 archnet ss-redir[413]:  2017-06-20 07:45:36 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:45:36 archnet ss-redir[413]:  2017-06-20 07:45:36 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:45:36 archnet ss-redir[413]:  2017-06-20 07:45:36 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:45:36 archnet ss-redir[415]:  2017-06-20 07:45:36 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:45:37 archnet ss-redir[413]:  2017-06-20 07:45:37 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:45:37 archnet ss-redir[408]:  2017-06-20 07:45:37 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:45:38 archnet ss-redir[389]:  2017-06-20 07:45:38 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:45:38 archnet ss-redir[389]:  2017-06-20 07:45:38 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:45:39 archnet ss-redir[389]:  2017-06-20 07:45:38 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:45:39 archnet ss-redir[413]:  2017-06-20 07:45:39 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:45:39 archnet ss-redir[415]:  2017-06-20 07:45:39 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:45:39 archnet ss-redir[389]:  2017-06-20 07:45:39 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:45:39 archnet ss-redir[415]:  2017-06-20 07:45:39 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:45:40 archnet ss-redir[415]:  2017-06-20 07:45:40 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:45:40 archnet ss-redir[415]:  2017-06-20 07:45:40 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:45:40 archnet ss-redir[389]:  2017-06-20 07:45:40 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:45:40 archnet ss-redir[413]:  2017-06-20 07:45:40 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:45:41 archnet ss-redir[413]:  2017-06-20 07:45:41 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:45:41 archnet ss-redir[413]:  2017-06-20 07:45:41 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:45:41 archnet ss-redir[389]:  2017-06-20 07:45:41 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:45:41 archnet ss-redir[413]:  2017-06-20 07:45:41 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:45:41 archnet ss-redir[413]:  2017-06-20 07:45:41 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:45:41 archnet ss-redir[389]:  2017-06-20 07:45:41 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:45:41 archnet ss-redir[413]:  2017-06-20 07:45:41 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:45:41 archnet ss-redir[413]:  2017-06-20 07:45:41 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:45:41 archnet ss-redir[415]:  2017-06-20 07:45:41 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:45:41 archnet ss-redir[413]:  2017-06-20 07:45:41 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:45:41 archnet ss-redir[389]:  2017-06-20 07:45:41 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:45:42 archnet ss-redir[413]:  2017-06-20 07:45:42 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:45:42 archnet ss-redir[413]:  2017-06-20 07:45:42 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:45:42 archnet ss-redir[413]:  2017-06-20 07:45:42 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:45:42 archnet ss-redir[389]:  2017-06-20 07:45:42 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:45:42 archnet ss-redir[413]:  2017-06-20 07:45:42 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:45:44 archnet ss-redir[413]:  2017-06-20 07:45:44 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:45:44 archnet ss-redir[413]:  2017-06-20 07:45:44 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:45:44 archnet ss-redir[389]:  2017-06-20 07:45:44 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:45:44 archnet ss-redir[413]:  2017-06-20 07:45:44 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:45:48 archnet ss-redir[413]:  2017-06-20 07:45:48 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:45:48 archnet ss-redir[413]:  2017-06-20 07:45:48 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:45:48 archnet ss-redir[389]:  2017-06-20 07:45:48 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:45:48 archnet ss-redir[408]:  2017-06-20 07:45:48 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:45:48 archnet ss-redir[389]:  2017-06-20 07:45:48 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:45:48 archnet ss-redir[408]:  2017-06-20 07:45:48 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:45:49 archnet ss-redir[413]:  2017-06-20 07:45:49 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:45:49 archnet ss-redir[389]:  2017-06-20 07:45:49 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:45:49 archnet ss-redir[408]:  2017-06-20 07:45:49 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:45:49 archnet ss-redir[413]:  2017-06-20 07:45:49 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:45:49 archnet ss-redir[413]:  2017-06-20 07:45:49 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:45:49 archnet ss-redir[413]:  2017-06-20 07:45:49 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:45:49 archnet ss-redir[389]:  2017-06-20 07:45:49 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:45:49 archnet ss-redir[408]:  2017-06-20 07:45:49 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:45:50 archnet ss-redir[413]:  2017-06-20 07:45:50 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:45:50 archnet ss-redir[413]:  2017-06-20 07:45:50 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:45:50 archnet ss-redir[413]:  2017-06-20 07:45:50 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:45:51 archnet ss-redir[389]:  2017-06-20 07:45:51 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:45:51 archnet ss-redir[408]:  2017-06-20 07:45:51 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:45:51 archnet ss-redir[413]:  2017-06-20 07:45:51 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:45:53 archnet ss-redir[415]:  2017-06-20 07:45:53 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:45:53 archnet ss-redir[415]:  2017-06-20 07:45:53 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:45:54 archnet ss-redir[415]:  2017-06-20 07:45:54 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:45:54 archnet ss-redir[415]:  2017-06-20 07:45:54 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:45:55 archnet ss-redir[415]:  2017-06-20 07:45:55 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:46:47 archnet ss-redir[408]:  2017-06-20 07:46:47 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:46:47 archnet ss-redir[389]:  2017-06-20 07:46:47 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:46:48 archnet ss-redir[389]:  2017-06-20 07:46:47 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:46:48 archnet ss-redir[408]:  2017-06-20 07:46:47 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:46:48 archnet ss-redir[389]:  2017-06-20 07:46:48 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:46:48 archnet ss-redir[408]:  2017-06-20 07:46:48 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:46:48 archnet ss-redir[389]:  2017-06-20 07:46:48 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:46:48 archnet ss-redir[408]:  2017-06-20 07:46:48 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:46:50 archnet ss-redir[408]:  2017-06-20 07:46:50 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:46:50 archnet ss-redir[389]:  2017-06-20 07:46:50 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:47:43 archnet ss-redir[408]:  2017-06-20 07:47:43 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:47:43 archnet ss-redir[408]:  2017-06-20 07:47:43 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:47:44 archnet ss-redir[408]:  2017-06-20 07:47:44 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:47:45 archnet ss-redir[408]:  2017-06-20 07:47:45 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:47:46 archnet ss-redir[408]:  2017-06-20 07:47:46 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:48:06 archnet ss-redir[389]:  2017-06-20 07:48:06 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:48:06 archnet ss-redir[389]:  2017-06-20 07:48:06 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:48:07 archnet ss-redir[389]:  2017-06-20 07:48:07 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:48:08 archnet ss-redir[389]:  2017-06-20 07:48:08 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:48:08 archnet ss-redir[389]:  2017-06-20 07:48:08 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:48:08 archnet ss-redir[389]:  2017-06-20 07:48:08 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:48:08 archnet ss-redir[389]:  2017-06-20 07:48:08 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:48:09 archnet ss-redir[389]:  2017-06-20 07:48:09 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:48:09 archnet ss-redir[389]:  2017-06-20 07:48:09 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:48:09 archnet ss-redir[389]:  2017-06-20 07:48:09 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:48:09 archnet ss-redir[389]:  2017-06-20 07:48:09 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:48:09 archnet ss-redir[389]:  2017-06-20 07:48:09 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:48:10 archnet ss-redir[389]:  2017-06-20 07:48:10 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:48:11 archnet ss-redir[389]:  2017-06-20 07:48:11 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:48:11 archnet ss-redir[389]:  2017-06-20 07:48:11 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:48:12 archnet ss-redir[413]:  2017-06-20 07:48:12 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:48:12 archnet ss-redir[413]:  2017-06-20 07:48:12 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:48:12 archnet ss-redir[413]:  2017-06-20 07:48:12 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:48:12 archnet ss-redir[413]:  2017-06-20 07:48:12 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:48:12 archnet ss-redir[413]:  2017-06-20 07:48:12 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:48:13 archnet ss-redir[413]:  2017-06-20 07:48:13 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:48:13 archnet ss-redir[413]:  2017-06-20 07:48:13 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:48:13 archnet ss-redir[413]:  2017-06-20 07:48:13 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:48:14 archnet ss-redir[413]:  2017-06-20 07:48:14 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:48:15 archnet ss-redir[413]:  2017-06-20 07:48:15 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:49:49 archnet ss-redir[413]:  2017-06-20 07:49:49 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:49:49 archnet ss-redir[413]:  2017-06-20 07:49:49 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:49:50 archnet ss-redir[413]:  2017-06-20 07:49:50 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:49:51 archnet ss-redir[413]:  2017-06-20 07:49:51 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:49:52 archnet ss-redir[413]:  2017-06-20 07:49:52 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:49:52 archnet ss-redir[389]:  2017-06-20 07:49:52 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:49:52 archnet ss-redir[413]:  2017-06-20 07:49:52 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:49:52 archnet ss-redir[389]:  2017-06-20 07:49:52 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:49:52 archnet ss-redir[413]:  2017-06-20 07:49:52 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:49:52 archnet ss-redir[413]:  2017-06-20 07:49:52 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:49:52 archnet ss-redir[389]:  2017-06-20 07:49:52 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:49:53 archnet ss-redir[413]:  2017-06-20 07:49:53 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:49:53 archnet ss-redir[389]:  2017-06-20 07:49:53 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:49:54 archnet ss-redir[413]:  2017-06-20 07:49:54 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:49:54 archnet ss-redir[389]:  2017-06-20 07:49:54 ERROR: [udp] server_recv_sendto fragmentation
Jun 20 07:50:26 archnet ss-redir[415]:  2017-06-20 07:50:26 ERROR: server recv: Connection reset by peer
Jun 20 07:50:27 archnet ss-redir[408]:  2017-06-20 07:50:27 ERROR: server recv: Connection reset by peer
Jun 20 07:50:27 archnet ss-redir[413]:  2017-06-20 07:50:27 ERROR: server recv: Connection reset by peer

`

### What is your config in detail (with all sensitive info masked)?
`
{
    "server":"_________",
    "server_port":18388,
    "local_address":"0.0.0.0",
    "local_port":1080,
    "nameserver":"127.0.0.1",
    "password":"__________",
    "timeout":60,
    "method":"chacha20-ietf-poly1305",
    "plugin":"obfs-local",
    "plugin_opts":"obfs=tls;obfs-host=www.bing.com",
    "fast_open": true,
    "reuse_port":true,
    "nofile":16384,
    "mode":"tcp_and_udp"
}
`

**Comment by enihcam** [comment]
server side config:
`
{
    "server":"0.0.0.0",
    "server_port":18388,
    "local_address": "127.0.0.1",
    "local_port":1080,
    "nameserver": "_______",
    "password":"_______",
    "timeout":60,
    "method":"chacha20-ietf-poly1305",
    "plugin":"obfs-server",
    "plugin_opts":"obfs=tls",
    "fast_open":true,
    "reuse_port":true,
    "mode":"tcp_and_udp"
}
`

**Comment by madeye** [comment]
Try the latest commit.

https://github.com/shadowsocks/shadowsocks-libev/issues/1524

**Comment by enihcam** [comment]
Yes I can try that, but to benefit more people, can you please also trigger a new release? Thanks.

**Comment by madeye** [comment]
The change doesn't "benefit" anybody, which just decreased the log visibility. You won't see that log without verbose option in the latest commit, but it still happens.

And as mentioned in that issue, you can just ignore the fragmentation logs.

**Comment by enihcam** [comment]
I see. However increasing -mtu did not help. Any suggestions to avoid UDP fragmentation?

**Comment by madeye** [comment]
When you have a large enough MTU, you won't see that warning again.

And you don't need to avoid UDP fragmentation, the application using UDP protocol can detect the increasing packet loss rate and tune the packet sizes automatically.
