### ISSUE TITLE
PR: Dockerfile, env variable to pass additional arguments

### ISSUE THREAD

**Issue by wacky6** [shadowsocks/shadowsocks-libev#1535]
### Modification
alpine/Dockerfile: add a new `ARGS` environment variable to pass additional arguments.

### Use case
```shell
# start a ss-server that prefers IPv6
docker run -e PASSWORD=password -e ARGS='-6' shadowsocks-libev
```

### Commit
https://github.com/wacky6/shadowsocks-libev/commit/5059a0cdef19aa25f42df89f047e5d0bf7a95437

**Comment by madeye** [comment]
Please open a pull request instead.

**Comment by wacky6** [comment]
Merged in https://github.com/shadowsocks/shadowsocks-libev/pull/1537. Closing issue.
