### ISSUE TITLE
对connection reset by peer的思考

### ISSUE THREAD

**Issue by Sherlock-Holo** [shadowsocks/shadowsocks-libev#1536]
shadowsocks日记里面一堆connection rest by peer是因为gfw在TCP握手时乱搞，如果咱们对TCP魔改一下，在握手时只受理通过验证的握手包，gfw发来的捣乱的握手包不理他，这样会不会减缓connection reset by peer嗯问题呢

**Comment by madeye** [comment]
TCP reset has nothing to do with GFW. It's a design choice of shadowsocks for closing TCP connections.

Search the issue tracker for more details.
