### ISSUE TITLE
Cannot recognized the cipher method name in Debian 9

### ISSUE THREAD

**Issue by demonlaplace** [shadowsocks/shadowsocks-libev#1538]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
3.0.6

### What operating system are you using?
Debian 9

### What did you do?
Run by systemctl with config.json use AEAD cipher
For aes-128-gcm or aes-256-gcm, all of them is nOK
but for original cipher method such as chacha20, chacha20-ietf, etc are OK

### What did you expect to see?
Success....

### What did you see instead?
● shadowsocks-libev.service - Shadowsocks-libev Default Server Service
   Loaded: loaded (/lib/systemd/system/shadowsocks-libev.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2017-06-22 12:15:04 UTC; 6min ago
     Docs: man:shadowsocks-libev(8)
 Main PID: 4640 (ss-server)
    Tasks: 1 (limit: 4915)
   CGroup: /system.slice/shadowsocks-libev.service
           └─4640 /usr/bin/ss-server -c /etc/shadowsocks-libev/config.json -u

Jun 22 12:15:04 instance-1 systemd[1]: Started Shadowsocks-libev Default Server Service.
Jun 22 12:15:04 instance-1 ss-server[4640]:  2017-06-22 12:15:04 INFO: using tcp fast open
Jun 22 12:15:04 instance-1 ss-server[4640]:  2017-06-22 12:15:04 INFO: UDP relay enabled
Jun 22 12:15:04 instance-1 ss-server[4640]:  2017-06-22 12:15:04 INFO: initializing ciphers... chacha20-ietf-poly1305
Jun 22 12:15:04 instance-1 ss-server[4640]:  2017-06-22 12:15:04 ERROR: Invalid cipher name: chacha20-ietf-poly1305, use rc4-md5 instead

### What is your config in detail (with all sensitive info masked)?
{
    "server":"0.0.0.0",
    "server_port":****,
    "local_port":1080,
    "password":"*****",
    "timeout":600,
    "method":"chacha20-ietf-poly1305",
    "fast_open":true,
    "mode":"tcp_and_udp"
}

**Comment by madeye** [comment]
Update your libsodium to latest and rebuild shadowsocks-libev.

**Comment by demonlaplace** [comment]
@madeye I've already updated the libsodium, need to rebuild shadowsocks-libev? I'll try.

**Comment by demonlaplace** [comment]
Solved

**Comment by fakhamatia** [comment]
How build shadowsocks-libev in ubuntu 20.04 ?
