### ISSUE TITLE
How to have ipv6 connectivity for ipv6-capable hosts on the ipv4 Internet?

### ISSUE THREAD

**Issue by cogisum** [shadowsocks/shadowsocks-libev#1539]
### What version of shadowsocks-libev are you using?
3.0.6

### What operating system are you using?
Arch Linux

### What did you do?
I have a vps with both ipv4 and ipv6 connectivity, I have started ss-server, ss-redir and set up iptables correctly for ipv4 connection.

### What did you expect to see?
Works for ipv6 as well, e.g. `curl -v ipv6.google.com`.

### What did you see instead?
Only works for ipv4, `curl -v ipv6.google.com` gives me:
```plain
* Rebuilt URL to: ipv6.google.com/
*   Trying 2404:6800:4006:803::200e...
* TCP_NODELAY set
* Immediate connect fail for 2404:6800:4006:803::200e: Network is unreachable
* Closing connection 0
curl: (7) Couldn't connect to server
```

### What is your config in detail (with all sensitive info masked)?
Server side:
```shell
/usr/local/bin/ss-server -u -c /etc/shadowsocks-libev/config.json -f /var/run/shadowsocks-libev.pid
```
config.json
```plain
{
    "server":["[::0]","0.0.0.0"],
    "server_port":8080,
    "local_address":"127.0.0.1",
    "local_port":1080,
    "password":"thisisthepassword",
    "timeout":600,
    "method":"aes-256-cfb"
}
```

Client side:
```shell
ss-redir -c /path/to/config.json -v &
iptables -t nat -A SHADOWSOCKS -p tcp --dport 8080 -j RETURN
iptables -t nat -A SHADOWSOCKS -d 0.0.0.0/8 -j RETURN
iptables -t nat -A SHADOWSOCKS -d 10.0.0.0/8 -j RETURN
iptables -t nat -A SHADOWSOCKS -d 127.0.0.0/8 -j RETURN
iptables -t nat -A SHADOWSOCKS -d 169.254.0.0/16 -j RETURN
iptables -t nat -A SHADOWSOCKS -d 172.16.0.0/12 -j RETURN
iptables -t nat -A SHADOWSOCKS -d 192.168.0.0/16 -j RETURN
iptables -t nat -A SHADOWSOCKS -d 224.0.0.0/4 -j RETURN
iptables -t nat -A SHADOWSOCKS -d 240.0.0.0/4 -j RETURN
iptables -t nat -A SHADOWSOCKS -p tcp -j REDIRECT --to-port 1080
iptables -t nat -A OUTPUT -p tcp -j SHADOWSOCKS
```
config.json
```plain
{
    "server":"<ipv4_address_of_server>",
    "server_port":8080,
    "local_address": "127.0.0.1",
    "local_port":1080,
    "password":"thisisthepassword",
    "timeout":300,
    "method":"aes-256-cfb",
}
```

**Comment by lcdtyph** [comment]
Add ```"ipv6_first": true``` to server side config.json

**Comment by cogisum** [comment]
I tried, but still the same problem.

**Comment by lcdtyph** [comment]
Have you set proxy for curl ?
'''curl -x socks5://127.0.0.1:1080 ipv6.google.com'''
-x requires latest curl.

**Comment by cogisum** [comment]
`curl -x socks5://127.0.0.1:1080 ipv6.google.com` gave me
```plain
curl: (7) Unable to receive initial SOCKS5 response.
```
The curl package I installed is curl-7.54.1-1, while `curl --version` returns
```plain
curl 7.52.1 (x86_64-pc-linux-gnu) libcurl/7.52.1 OpenSSL/1.0.2k zlib/1.2.8
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP UnixSockets HTTPS-proxy
```

**Comment by lcdtyph** [comment]
Well, that's weird...
I got the same output as yours at first.
Then I run curl again immediately, and everything is ok...

**Comment by madeye** [comment]
You cannot do that with ss-redir. It's designed to be transparent proxy, which is impossible to route your IPv4 traffic to IPv6 destination.

**Comment by lcdtyph** [comment]
Oh I didn't notice it's ss-redir...

**Comment by cogisum** [comment]
Well, can I make it with ss-local? I can visit ipv6.google.com in Windows with [shadowsocks-windows](https://github.com/shadowsocks/shadowsocks-windows).

**Comment by cogisum** [comment]
I tried ss-local, it worked with ipv6. But with ss-local, can I divide the traffic according to domain names like what dnsmasq+ipset+iptables+ss-redir do?

**Comment by madeye** [comment]
@cogisum Nope, you can't. `ss-local` is a SOCKS5 proxy.
