### ISSUE TITLE
Feature Request: An option to use gethostbyname() instead of libudns

### ISSUE THREAD

**Issue by Blankwonder** [shadowsocks/shadowsocks-libev#1542]
When I use shadowsocks as a secure tunnel for home or company access tunnel, I need use some internal domains. ss-server is now using libudns so I have to start dnsmasq or bind to configure the host records. Is it possible that add an option to let ss-server simply use gethostbyname(). Then I can just add a record in /etc/hosts. It's much easily and reliably.

Thanks.

**Comment by madeye** [comment]
Unfortunately, this "feature" won't be implemented from my side.

The reason we are using libudns is to provide a simple async wrapper of local DNS resolver. Replacing it with `gethostbyname()` would hurt the performance a lot.

BTW, setting up a local resolver is really easy. In Ubuntu and Debian, just execute`apt install bind9`. 

Then, without any configuration, you can have a local DNS resolver listening on `127.0.0.1:53`.

**Comment by madeye** [comment]
And both dnsmasq and bind would parse your settings in `/etc/hosts`.

**Comment by vfreex** [comment]
`getaddrinfo_a` is probably an option.

**Comment by Blankwonder** [comment]
Thanks for explanation.
But using POSIX call to resolve hostname may have a better compatibility. For example, under macOS `gethostbyname() ` can be used to resolve a Bonjour network name (mDNS). And under some scenarios performance is not important.

**Comment by madeye** [comment]
@vfreex Not a POSIX API, only works on Linux.

@Blankwonder Pull request is welcome. But I don't have any plan to implement this.
