### ISSUE TITLE
udp rule break openvpn server

### ISSUE THREAD

**Issue by odkrys** [shadowsocks/shadowsocks-libev#1544]
when I add this line to relay udp packet, openvpn server feature is not working properly.

`ip route add local 0.0.0.0/0 dev lo table 100`

external pc  (openvpn client)  -----> router (openvpn server, ss-redir) -----> ss-server (VPS)

ss-redir is not full transparent mode, I set it to access some geo-blocking sites with ipset, dnsmasq.

Any solution?

**Comment by madeye** [comment]
I don't think it's an issue of shadowsocks-libev.

You have to figure out these kind of routing setup by yourself.
