### ISSUE TITLE
ss-redir not working with UDP

### ISSUE THREAD

**Issue by ticonci** [shadowsocks/shadowsocks-libev#1546]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
2.6.0

### What operating system are you using?
OpenWRT

### What did you do?
I set the DNS with 103.6.51.210 (a HK DNS server) on my console with a IP 192.168.1.181.
i am running ss-redir on the OpenWRT and it is with '-u' option, local port is 20000
iptables: iptables -t nat -I PREROUTING -s 192.168.1.181/32 -p udp -j REDIRECT --to-port 20000

### What did you expect to see?
I thought it would redirect all the UDP traffic from 192.168.1.181 to the remote server, but it didn't. Nothing happened and my console can't resolve  domain names any more.
that policy works fine with TCP traffic if I replace the UDP with TCP. 

### What did you see instead?
my xbox  can't resolve any domain names. 
I tried tcpdump on the remote server, and didn't see any coming UDP packets. 

### What is your config in detail (with all sensitive info masked)?
ss-redir -c ss.conf -u
iptables -t nat -I PREROUTING -s 192.168.1.181/32 -p udp -j REDIRECT --to-port 20000

**Comment by madeye** [comment]
UDP transparent proxy only works TPROXY, not REDIRECT.

Read the advanced usage section of README for details. https://github.com/shadowsocks/shadowsocks-libev#advanced-usage

**Comment by ticonci** [comment]
it works. thanks a lot;)
