### ISSUE TITLE
ss-redir --acl doesn't work

### ISSUE THREAD

**Issue by xrain0610** [shadowsocks/shadowsocks-libev#1547]
I use --acl parameter with ss-local can work well,
but when i use ss-redir with --acl,
it report error: Unrecognized option: (null)

**Comment by madeye** [comment]
There is no ACL function for `ss-redir`. Read the document here: 

https://github.com/shadowsocks/shadowsocks-libev/blob/master/doc/ss-redir.asciidoc

https://github.com/shadowsocks/shadowsocks-libev/blob/master/doc/shadowsocks-libev.asciidoc

**Comment by xrain0610** [comment]
@madeye I think you should remove help text in ss-redir...
