### ISSUE TITLE
shadowsocks隐蔽性不再可靠了么？

### ISSUE THREAD

**Issue by Galaxy0419** [shadowsocks/shadowsocks-libev#1549]
在bwg自己搭建了一个vps，就使用shadowsocks-libev，今天下午就无法登录ssh和ss，官网也显示ip在blacklist上！加密协议：chacha20-ietf-poly1305难道是协议问题?

_Sent from my Xiaomi MI 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Biercenter** [comment]
我的也是chacha20-ietf-poly1305，bwg,用了很久了，一切正常。唯一不同的是我是只允许ssh密钥文件登陆。

**Comment by Galaxy0419** [comment]
测试发现是客户端ip被墙，换IP后可以正常上网，我之前用Ubuntu上的ss-local连接用chorme看YouTube然后过半小时被封，请问难道是ss-local有漏洞?之前用其他客户端也没问题

_Sent from my Xiaomi MI 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Galaxy0419** [comment]
测试发现是客户端ip被墙，换IP后可以正常上网，我之前用Ubuntu上的ss-local连接用chorme看YouTube然后过半小时被封，请问难道是ss-local有漏洞?之前用其他客户端也没问题

_Sent from my Xiaomi MI 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Galaxy0419** [comment]
@Biercenter 你有没有设置iptables?

_Sent from my Xiaomi MI 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Biercenter** [comment]
@Galaxy0419 没设置，就debian8 x64 minimal新系统修改时区和ssh，然后安装shadowsocks-libev好了

**Comment by Biercenter** [comment]
@Galaxy0419 我用shadowsocks 4.0.4 Windows版，经常看Y2B，看到不错的还下载，一直好好的，没问题

**Comment by Galaxy0419** [comment]
问题解决，经过半小时墙自动解封我的本地ip可以ssh和ss了，难道墙之前在禁后分析我的流量？然后没有发现可疑然后放行？

_Sent from my Xiaomi MI 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Galaxy0419** [comment]
经测试使用ss-local就会遭短暂封锁，local日志如下:
2017-07-01 17:58:39 INFO: using tcp fast open
 2017-07-01 17:58:39 INFO: initializing ciphers... chacha20-ietf-poly1305
 2017-07-01 17:58:39 INFO: tcp port reuse enabled
 2017-07-01 17:58:39 INFO: udprelay enabled
 2017-07-01 17:58:39 INFO: udp port reuse enabled
 2017-07-01 17:58:39 INFO: listening at 0.0.0.0:23333
 2017-07-01 17:58:39 INFO: running from root user
 2017-07-01 18:06:32 ERROR: getpeername: Transport endpoint is not connected
 2017-07-01 18:06:32 ERROR: getpeername: Transport endpoint is not connected
 2017-07-01 18:06:32 ERROR: getpeername: Transport endpoint is not connected
 2017-07-01 18:06:32 ERROR: getpeername: Transport endpoint is not connected
 2017-07-01 18:06:32 ERROR: getpeername: Transport endpoint is not connected
 2017-07-01 18:06:32 ERROR: getpeername: Transport endpoint is not connected
 2017-07-01 18:06:32 ERROR: getpeername: Transport endpoint is not connected
 2017-07-01 18:06:32 ERROR: getpeername: Transport endpoint is not connected
 2017-07-01 18:06:32 ERROR: getpeername: Transport endpoint is not connected
 2017-07-01 18:06:36 ERROR: getpeername: Transport endpoint is not connected
 2017-07-01 18:06:40 ERROR: getpeername: Transport endpoint is not connected

_Sent from my Xiaomi MI 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by kimw** [comment]
看现象，应该是运营商的问题。可以用这个方法测试确认—用手机或隔壁老王的网络试试。如确认，可以试试换网络接入运营商根治。

**Comment by McContax** [comment]
想问下各位如何确定自己的IP被墙

**Comment by Galaxy0419** [comment]
@McContax ping不通(未禁用icmp的情况下)

_Sent from my Xiaomi MI 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Galaxy0419** [comment]
@kimw 是的换ip可以，等一段时间也可以，不知道什么情况，现在换一个IP以后又稳定了。

_Sent from my Xiaomi MI 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by madeye** [comment]
Which version of your shadowsocks-libev?

And please follow the template to provide all the necessary information.

**Comment by wongsyrone** [comment]
> provide all the necessary information

实际上如果真是短暂屏蔽，会不停出现 connection reset by peer
我这里一般是持续几分钟恢复

**Comment by Galaxy0419** [comment]
@madeye 3.0.7 之前3.0.6以前不会出现的状况

_Sent from my Xiaomi MI 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Galaxy0419** [comment]
@wongsyrone 实际上是ip封锁任何链接都被拒绝，日志上没有东西，握手都被拒绝。但是换ip可以。

_Sent from my Xiaomi MI 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by celeron533** [comment]
长时间大流量的不明内容境外VPS IP段数据传输很可能触发ISP的自律系统？

**Comment by Galaxy0419** [comment]
还出现了一个状况，Linux的ss-local建立本地socks5共享的速度比安卓的shadowsocks软件速度快了将近3倍，而且拉动视频响应速度也快了很多，是不是安卓客户端被检测限速了?

_Sent from my Xiaomi MI 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by kimw** [comment]
@celeron533 
> 长时间大流量的不明内容境外VPS IP段数据传输很可能触发ISP的自律系统？

基本不可能。理由是技術成本太高+失誤率過大。打個比方：假設牆外有 100萬個 IP 地址，牆內只有 100 個 IP 地址。實時統計所有點對點之間的流量，共需要 1000000^100=1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 條實時統計實時更新的記錄。如果牆內有 10 萬台終端……抱歉我的 PC CPU 太爛，半天沒算出來被我 CTRL+C 了……

**Comment by kimw** [comment]
@Galaxy0419 
> 还出现了一个状况，Linux的ss-local建立本地socks5共享的速度比安卓的shadowsocks软件速度快了将近3倍，而且拉动视频响应速度也快了很多，是不是安卓客户端被检测限速了?

有沒有可能是網絡鏈路的差異造成的？比如手機是 wifi 鏈路，linux 是 wired 鏈路？

**Comment by Galaxy0419** [comment]
@kimw 本地局域网情况下差距也不可能这么大而且我手机配置是算比较好的快接近于那台电脑了。

_Sent from my Xiaomi MI 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by kimw** [comment]
@Galaxy0419 詳細原理參見七層結構。簡單的說，網絡性能只有在完全相同的鏈路上才有比較的可能性。比如，都使用 WiFi，又或者都使用有線連接。

**Comment by Galaxy0419** [comment]
@kimw 笔记本在WiFi测试下结果相同

_Sent from my Xiaomi MI 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Galaxy0419** [comment]
还发现一个现象在gcm加密模式下安卓客户端开全局后无法ping通并且无法使用qq等中国软件也无法上百度

_Sent from my Xiaomi MI 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Galaxy0419** [comment]
经过多次测试发现连接重置问题主要原因出现在如下：1.第一次连接打开网页。2.加载YouTube。3.视频跳转。

_Sent from my Xiaomi MI 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by pexcn** [comment]
不要见得风是得雨啊，你们本身也要判断…

**Comment by madeye** [comment]
IMO, it looks like an issue of your ISP.

To verify this, please run MTR when your IP gets blocked, and post the results here.

**Comment by odkrys** [comment]
what port are you using ? If you use 443 port now, try to change non-standard port.

**Comment by Galaxy0419** [comment]
@odkrys 23333

_Sent from my Xiaomi MI 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by madeye** [comment]
Closed due to inactivity.
