### ISSUE TITLE
tcp fast open可能会导致ss被发现？

### ISSUE THREAD

**Issue by hrimfaxi** [shadowsocks/shadowsocks-libev#1552]
### What version of shadowsocks-libev are you using?
shadowsocks-libev 3.0.5

### What operating system are you using?
Ubuntu 16.04.2 LTS和Archlinux均受影响
客户端内核：Linux  4.10.12-041012-generic
服务器端内核： 4.10.12-041012-generic

### What did you do?
打开tcp_fastopen功能:
echo 3 > /proc/sys/net/ipv4/tcp_fastopen
并在配置文件中开启或关闭fast open
测试十次：

curl --socks5-hostname localhost:1080 news.google.com -v -L

### What did you see instead?
不带fastopen组均能正常通信
带了fastopen组会有一定机率会被卡住在通信到一半的过程中（如果有一次卡住，那有90%机率请求会被连续卡住）

### What is your config in detail (with all sensitive info masked)?
```
{
	"server":"xxx.xxx.xxx.xxx",
	"server_port":xxxx,
	"local_address":"0.0.0.0",
	"local_port":1080,
	"password":"xxxx",
	"timeout":300,
	"method":"aes-256-cfb",
	"fast_open":true
}
```

sysctl.conf:
```
#
# Kernel sysctl configuration
#

# Disable packet forwarding
#net.ipv4.ip_forward=1

# Disable the magic-sysrq key (console security issues)
kernel.sysrq = 0

# Enable TCP SYN Cookie Protection
net.ipv4.tcp_syncookies = 0

# See evil packets in your logs.
# net.ipv4.conf.all.log_martians = 1

# Tweak the port range used for outgoing connections.
net.ipv4.ip_local_port_range = 32768 61000

# Reboot 60 seconds after kernel panic
kernel.panic = 60
net.ipv4.conf.all.promote_secondaries=1

# Congestion
net.ipv4.tcp_allowed_congestion_control = bbr
net.ipv4.tcp_congestion_control = bbr

# Memory
net.ipv4.tcp_wmem = 4096	65536 16777216
net.ipv4.tcp_rmem = 4096	327680 16777216
net.ipv4.tcp_mem = 327680 327680 16777216
net.core.rmem_default = 327680
net.core.wmem_default = 65536
net.core.rmem_max = 16777216
net.core.wmem_max = 16777216

# Misc
net.ipv4.tcp_ecn = 2
net.ipv4.tcp_rfc1337 = 1
net.ipv4.tcp_tw_recycle = 0
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_frto = 2
net.ipv4.tcp_fastopen = 3
net.ipv4.tcp_window_scaling = 1
net.ipv4.ip_no_pmtu_disc = 0
net.ipv4.tcp_keepalive_probes = 3

net.ipv4.tcp_slow_start_after_idle=0

vm.dirty_background_ratio = 20

vm.swappiness = 2
```

由于除SS外的应用程序使用tfo较少，有无可能会因为tfo在tcp option中设置了相关cookie和tcp选项而提高被防火墙判定为SS服务的机率？

**Comment by madeye** [comment]
I don't think so. It looks like some kind of bug of NAT devices, ISPs or your server provider's firewall.

To verify if your connection got blocked, try to run `mtr` when you have connection issues and post the results here.

**Comment by madeye** [comment]
I also noticed that you've enabled `bbr`. Could you disable `bbr` and try again?

**Comment by Galaxy0419** [comment]
有相同状况，我测试关闭tfo以后,连接重置几率大大减少，开启时候会比较频繁出现连续重置连接，关闭后十分钟只出现一次，并且载入速度增加。

_Sent from my Xiaomi MI 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by wongsyrone** [comment]
> 测试关闭tfo以后,连接重置几率大大减少

初始跟随SYN发送的数据不应该超过MSS，如果超过了，很可能出现你说的链接重置

**Comment by wongsyrone** [comment]
有种情况是，初始的数据超出了，下层只发送了一部分，但是ss认为这部分全部发出去了，会因为解密失败直接重置链接。
你看看出问题的时候有没有解密失败的错误日志。

**Comment by wongsyrone** [comment]
在 rfc里面有对tfo场景的描述，https://tools.ietf.org/html/rfc7413#section-6.1
其实是有可能发送重复带有数据的SYN的，因为初始数据包含 Salt/IV + AddrBuffer，一旦重复的话，就会被防重放的检测拦下来。尤其是中间各种NAT和设备鱼龙混杂。

为了佐证我上面的猜想

> If the client
   sends more data in the SYN packet than the server will accept, this
   will likely require the client to retransmit some or all of the data.

https://tools.ietf.org/html/rfc7413#section-4.1.3

**Comment by Galaxy0419** [comment]
建议停用tfo！经测试如开启tfo，fb会无限报错连接443端口，but not with tls handshake！虽然关闭后还是有，但是循环几次以后会恢复正常传输！

_Sent from my Xiaomi MI 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by pexcn** [comment]
估计你是开了TFO又装了锐速

**Comment by Galaxy0419** [comment]
@pexcn 肯定不是锐速，锐速4.x版本无法支持

_Sent from my Xiaomi MI 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by changyp6** [comment]
有人已经在网监那里看到ss被拦的情况了。
具体操作不知道是怎么回事。
所以需要引起注意！

**Comment by changyp6** [comment]
@hrimfaxi 你是不是在北京？据说北邮已经开发出block SS的算法。看到截图了。不知道是真是假。

**Comment by madeye** [comment]
Closed due to no response from requester.
