### ISSUE TITLE
未开启obfs的ss-local也可以连上开启了obfs的ss-server

### ISSUE THREAD

**Issue by cranetht** [shadowsocks/shadowsocks-libev#1553]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
3.0.7

### What operating system are you using?
Ubuntu 16.04 LTS

### What did you do?
ss-server配置并开启了obfs＝TLS，ss-local未开启obfs

### What did you expect to see?
客户端未开启obfs时无法连接服务器

### What did you see instead?
客户端在未开启obfs或开启obfs=TLS时正常连接服务器，开启obfs=http时无法连接服务器

**Comment by madeye** [comment]
It's a feature not bug...

**Comment by asasuou** [comment]
Is it possible to switch this feature ON/OFF?
Maybe someone would like to access with obfs=tls only.

**Comment by madeye** [comment]
@asasuou Try '--failover' option.
