### ISSUE TITLE
why can not update to 3.0.7 by git resource ? ppa only support 3.0.6 

### ISSUE THREAD

**Issue by sosmygirl** [shadowsocks/shadowsocks-libev#1555]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
3.0.6

**Comment by hosiet** [comment]
I don't really get your meaning. What Linux distribution are you using and how do you want to install shadowsocks-libev? Please answer those questions by filling in the predefined issue template.
