### ISSUE TITLE
编译mbedtls的报错

### ISSUE THREAD

**Issue by liaoran** [shadowsocks/shadowsocks-libev#1556]
### What version of shadowsocks-libev are you using?
3.0.6-1~ppalx

### What operating system are you using?
ubuntu-16.04-x86_64

### What did you do?
我是按照文档上的步骤进行的mbedtls编译操作：
export MBEDTLS_VER=2.5.1
wget https://tls.mbed.org/download/mbedtls-$MBEDTLS_VER-gpl.tgz
tar xvf mbedtls-$MBEDTLS_VER-gpl.tgz
pushd mbedtls-$MBEDTLS_VER
make SHARED=1 CFLAGS=-fPIC
sudo make DESTDIR=/usr install
popd
sudo ldconfig
# Start building
./autogen.sh && ./configure && make
sudo make install
### 报错信息：
 ./autogen.sh && ./configure && make
-bash: ./autogen.sh: No such file or directory

**Comment by madeye** [comment]
You'd follow the instructions to build mbedtls.

```
make SHARED=1 CFLAGS=-fPIC
sudo make DESTDIR=/usr install
```

**Comment by liaoran** [comment]
sudo make DESTDIR=/usr install之后就结束了？我显示直接进入新的命令行了，是不是这表示已经正常安装了？

**Comment by liaoran** [comment]
还有两个问题，在高级用法中：
一、iptables -t nat -A SHADOWSOCKS -d 123.123.123.123 -j RETURN，这个123.123.123.123是不是指的我的服务器的IP地址？
二、iptables -t nat -A SHADOWSOCKS -p tcp -j REDIRECT --to-ports 12345，ss的本地端口不是1080吗，是写1080，还是写这个12345？

**Comment by terrytw** [comment]
一、是的
二、SS的本地端口可以随意指定，只要各种设置都一致就行

**Comment by liaoran** [comment]
谢谢
