### ISSUE TITLE
求教timeout参数设置

### ISSUE THREAD

**Issue by Galaxy0419** [shadowsocks/shadowsocks-libev#1557]
请问服务端和客户端一定要一样么还有，大好还是小好？

_Sent from my Xiaomi MI 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Galaxy0419** [comment]
还有最近Facebook发现加载奇慢，日志中重复出现以下日志：
2017-07-05 17:38:29 INFO: connect to 93.46.8.89:443
 2017-07-05 17:38:29 INFO: Request did not begin with TLS handshake.
请问怎么解决，还有出现tcp timeout算正常么？

_Sent from my Xiaomi MI 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Galaxy0419** [comment]
还有遇到2017-07-06 00:03:24 ERROR: getpeername: Transport endpoint is not connected错误时会卡住加载不出

_Sent from my Xiaomi MI 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by chenhw2** [comment]
[93.46.8.89] is a typical dns problem

**Comment by Galaxy0419** [comment]
@chenhw2 So how to slove that problem？

_Sent from my Xiaomi MI 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
