### ISSUE TITLE
openwrt 客户端莫名其妙失效

### ISSUE THREAD

**Issue by millionart** [shadowsocks/shadowsocks-libev#1558]
### What version of shadowsocks-libev are you using?
从 ppa 升级显示服务器版本 3.06 ，但是ppa上不是写着3.07么

### What operating system are you using?
openwrt 3.07

### What did you do?
睡了一觉

### What did you expect to see?
正常翻墙

### What did you see instead?
翻不了

### What is your config in detail (with all sensitive info masked)?
加密方式从rc4-md5换成chacha20也不行
只有openwrt版本连不上，其他都可以

------------------
线路上海移动

用了一年多了，今天刚出现的问题，先是上午大约一小段时间上不去，然后从今天傍晚开始就持续失效，但是

- 手机和 Mac 开启 surge
- pc开 shadowsocks 客户端

都可以正常翻，路由这边就怎么都不行
一年多以前也曾经出过类似问题，过一阵就恢复，但是后来换了日本线路这一年来都没事

 @aa65535

**Comment by millionart** [comment]
已经确认不是gfw的问题，因为我建了个新的vps用surge可以连，openwrt仍然上不去，重启也没用

**Comment by millionart** [comment]
经测试，SOCKS5代理 可用，透明代理无效

**Comment by millionart** [comment]
排查了一晚上，刚发现是chinadns无法启用了，可能错怪shadowsocks了
换成dnsmasq-china-list方案就解决了，虽然还有一些问题
最奇怪的是chinadns重装也无法启用……

**Comment by suikatomoki** [comment]
dns查询出了问题 即运营商丢包udp丢的厉害
SOCKS5正常使用是因为基本都是tcp包 dns查询也是tcp到远端的
官方解决方案  换udp友好的线路 运营商
民间解决方案 udp to tcp https://github.com/aa65535/openwrt-dns-forwarder
