### ISSUE TITLE
/etc/init.d/下没有相关文件无法运行

### ISSUE THREAD

**Issue by millionart** [shadowsocks/shadowsocks-libev#1559]
### What version of shadowsocks-libev are you using?
shadowsocks-libev_3.0.7-2_arm_cortex-a9_vfpv3.ipk

### What operating system are you using?
LEDE Reboot 17.01.2 r3435-65eec8bd5f

### What did you do?
安装

### What did you expect to see?
运行

### What did you see instead?
不运行

服务端没问题，客户端无论是 @aa65535 提供的或者自编译的安装后在 /etc/init.d/ 下都没有 shadowsocks 相关文件

**Comment by millionart** [comment]
3.06 安装后也没有

**Comment by chenhw2** [comment]
/etc/init.d/shadowsocks is in [luci-app-shadowsocks](https://github.com/shadowsocks/luci-app-shadowsocks)

**Comment by millionart** [comment]
luci-app-shadowsocks | 1.6.3-1
shadowsocks-libev | 3.0.7-2

均已安装，服务器配置正确，无法启动

透明代理
未运行
SOCKS5代理
未运行
端口转发
未运行

**Comment by millionart** [comment]
lede 官方源里的 shadowsocks-libev | 2.6.1-1 可以执行

**Comment by millionart** [comment]
找到问题了，默认安装的libsodium版本低了，安装libsodium_1.0.12-1_arm_cortex-a9_vfpv3.ipk后解决
