### ISSUE TITLE
求教这个错误是什么

### ISSUE THREAD

**Issue by Galaxy0419** [shadowsocks/shadowsocks-libev#1562]
2017-07-11 02:11:13 ERROR: getpeername: Transport endpoint is not connected
每次碰到必定卡住

_Sent from my Xiaomi MI 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by tianlichunhong** [comment]
都没有说自己做了什么，你没有告知环境是什么。别人咋知道你干啥了。
