### ISSUE TITLE
Check `sudo` first in `build_deb.sh`

### ISSUE THREAD

**Issue by henrypijames** [shadowsocks/shadowsocks-libev#1563]
Apparently, the standard Ubuntu_[14.04|16.04]_LTS_minimal install comes without sudo, which triggers `sudo: not found` errors in `build_deb.sh`. Please add a check for that.

**Comment by gyteng** [comment]
Same problem when I build it in docker

**Comment by madeye** [comment]
`build_deb.sh` is maintained by @rogers0.

For Ubuntu 14.04 and 16.04 users, please install from PPA:

```
sudo add-apt-repository ppa:max-c-lv/shadowsocks-libev
sudo apt-get update
sudo apt install shadowsocks-libev
```

**Comment by rogers0** [comment]
@henrypijames @gyteng Personally I don't use minimal installed ubuntu nor docker. So it'd be appreciated if you can fix it and submit a pull request. Thanks!

**Comment by madeye** [comment]
No response from the requester.

Closing the issue.
