### ISSUE TITLE
ss-manager下打开的UDP转发无效

### ISSUE THREAD

**Issue by sijidou** [shadowsocks/shadowsocks-libev#1566]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
3.07

### What operating system are you using?
centos 7.3，ubuntu 17.04

### What did you do?
在使用ss--manager指令时，新打开的端口上UDP转发不稳定。
端口本身没有问题，使用ss-server启动时就一切正常。

启动进程是：
ss-server -m aes-256-gcm --manager-address 127.0.0.1:4000 -f /root/.shadowsocks/.shadowsocks_51001.pid -c /root/.shadowsocks/.shadowsocks_51001.conf -t 60 -u --fast-open -s 0.0.0.0 --reuse-port
tcp部分完全没问题，但是UDP大概不是很稳定。

我在路由器上安装了ss，并开启了端口转发。
然后
 dig google.com @127.0.0.1 -p5300
常常会返回
 connection timed out; no servers could be reached
这个结果，但又有大概1/5的时候又返回正常数值。

这和服务器或者端口完全应该没有关系，因为同一台服务器下，如果我使用
/usr/bin/ss-server -u -c /etc/shadowsocks-libev/config.json去启动的话，就不会出现问题。我反复测试过，但是找不出问题的原因。

**Comment by madeye** [comment]
I cannot reproduce your issue locally.

One possible issue is you're using different ports in manager mode and standalone mode.

In manage mode, a random port will be picked to support multiple user, which would suffers QoS problems for some ISPs or service provider.

In standalone mode, it looks that you're using special port that would not have QoS issue.

My suggestion is to use standalone mode if you find any QoS issue for high port numbers.

**Comment by madeye** [comment]
No response from the requester.

Closing the issue.

**Comment by sijidou** [comment]
应该和高端口没有关系，因为我尝试开启过同样的端口，以独立模式就运行无误。

我尝试了-v，在服务端和客户端，服务端没有错误反馈。
客户端，
ss-tunnel -c /var/etc/shadowsocks.cfg0a4a8f.json -u -l 5300 -L 8.8.8.8:53 --mtu 1492 -v
当dig google.com @127.0.0.1 -p5300不能返回数值时，,得到的错误信息是:

2017-07-31 19:01:40 INFO: [udp] cache miss: 8.8.4.4:53 <-> 127.0.0.1:58457
 2017-07-31 19:01:45 INFO: [udp] connection timeout
 2017-07-31 19:01:45 INFO: [udp] one connection freed
 2017-07-31 19:01:45 INFO: [udp] server receive a packet
 2017-07-31 19:01:45 INFO: sockaddr_cmp: sin_family equal? 1
 2017-07-31 19:01:45 INFO: sockaddr_cmp: sin_port equal? 1
 2017-07-31 19:01:45 INFO: [udp] cache hit: 8.8.4.4:53 <-> 

但依然和之前一样，在同一分钟内，有时候没问题，有时候有。
我几乎可以排除线路上的干扰，因为独立启动libev的时候，成功解析的概率接近100%..而使用Manager后就只剩下一半不到。
这应该不是不可重现的问题，因为不止是我遇到这个问题，我也在不同的服务器/客户端上尝试过，都得到同样的结果。

![photo_2017-07-31_19-21-55](https://user-images.githubusercontent.com/16715966/28778191-e1b957e6-7630-11e7-8514-9111c00f0c61.jpg)

**Comment by madeye** [comment]
To verify it's not related to QoS. You can start a `ss-tunnel` on your server and dig a hostname then.

**Comment by madeye** [comment]
You'd expect that `ss-tunnel` on the server would resolve domains without any problem.

However, if it's a problem of ss-manager, you would observe failures as well.

**Comment by sijidou** [comment]
我尝试在服务器上运行ss-tunnel，依然会出错，和先前一样，概率性出错。看来这似乎是ss-manager的错误？
我不是很明白这里的ss-manager是指ss-[local|redir|server|tunnel|manager] 还是指 Shadowsocks-manager？

![default](https://user-images.githubusercontent.com/16715966/28810444-627481e0-76bc-11e7-8e56-f079127cfcf5.png)

**Comment by madeye** [comment]
What's your `tunnel.json` in details?

**Comment by madeye** [comment]
Is it possible that you have multiple `ss-server` on your server?

Please check: `/usr/bin/ss-server` and `/usr/local/bin/ss-server`.

**Comment by sijidou** [comment]
服务端进程为
ss-server -m chacha20-ietf-poly1305 --manager-address 127.0.0.1:4000 -f /root/.shadowsocks/.shadowsocks_51011.pid -c /root/.shadowsocks/.shadowsocks_51011.conf -t 60 -u --fast-open -d 8.8.8.8 -s 0.0.0.0 --reuse-port

[root@24q ~]# cat /root/.shadowsocks/.shadowsocks_51011.conf                 
{                                                                            
"server_port":51011,                                                         
"password":"******"                                                      
}                                                                            

[root@24q ~]# cat tunnel.json                                                
{                                                                            
    "server": "104.149.164.53",                                              
    "server_port": 51011,                                                    
    "password": "******",                                                
    "method": "chacha20-ietf-poly1305",                                      
    "local_address": "0.0.0.0",                                              
    "timeout": 60,                                                           
    "reuse_port": true                                                       
}                                                                            
 
ss-manager是
/usr/local/bin/ss-manager -u --manager-address 127.0.0.1:4000 -c /root/config.json -d 8.8.8.8

[root@24q ~]# cat config.json                                  
{                                                              
    "server":"0.0.0.0",                                        
    "method":"chacha20-ietf-poly1305",                         
    "fast_open": true                                          
}                                                              

ss-server只存在于/usr/local/bin

![screenshot_20170801-155436](https://user-images.githubusercontent.com/16715966/28814863-e16e923c-76d1-11e7-977b-504285d5b2c3.png)

**Comment by madeye** [comment]
1. In your issue description, the command line for `ss-server` is 

```
/usr/bin/ss-server -u -c /etc/shadowsocks-libev/config.json
```

2. Change your `tunnel.json`'s server to `127.0.0.1` and try again.

3. Remove all the MTU options and try again.

4. Update to the latest 3.0.8 and try again.

**Comment by madeye** [comment]
Please also try change `-L 8.8.8.8:53` to `-L 114.114.114.114.53`.

**Comment by sijidou** [comment]
1.
确实只安装到了/usr/local/bin下，进程应该是没显示绝对路径。
[root@24q ~]# cat /usr/bin/ss-server                           
cat: /usr/bin/ss-server: No such file or directory
[root@24q bin]# ls /usr/bin/ | grep ss-                        
nl-class-add                                                   
nl-class-delete                                                
nl-class-list
目录下，没有ss
2.修改成127.0.0.1后，依然存在这个问题
3.移出后同样存在
4.git更新的时候就更新上去了，忘了说，后来一直是3.0.8版本下测试的
5.我在本地和境外服务器上都测试过，应该和dns污染无关
5.这个问题我和 “shadosocks-manager”的维护者反馈过，他排查后认为我应该向上游反馈，或者您可以试试安装一次shadowsocks-manager？

**Comment by madeye** [comment]
1. Generally, `ss-server` processes are forked by `ss-manager`. It has no difference from starting `ss-server` in your bash.
2. If it's not a QoS issue (as you still see packet loss on loopback), it would be related to OS settings like scheduling priority.
3. What's the spec and configuration of your VPS? Is it a OpenVZ based VPS?
4. If you have a linux machine or virtual machine locally, you can try `ss-manager` locally as well.

BTW, I cannot reproduce your issue both on a local machine and on a KVM based VPS.

**Comment by sijidou** [comment]
先前用的3个服务器都是，centos 7.3,KVM，512M
嗯，我再次尝试了重建服务器，这次建立了ubunut，问题依然存在。
"shadowsocks/shadowsocks-manager"和"shadowsocks/shadowsocks-libev"生成的进程依然不能正常使用ss-tunnel，这应该不是我一个人样本，因为我在其他使用者那里也得到了同样的结果。
这期间有人建议试试 Python 版本的shadwsocks，结果他确实正常运行了.....

感谢回复，但是以我的认知，可能提供不了更多的信息了。
谢谢。

**Comment by madeye** [comment]
Could you try this branch?

**Comment by madeye** [comment]
Please try the latest commit on master branch.

**Comment by sijidou** [comment]
哇，好快。
我更新了，看起来好像修复了。
但是变得极其不稳定？在运行大概几分钟后：
在单独启动libev是没问题的，但是如果以manager启动的那个，似乎遇到了更多大的问题..
现在不止是tunnel，似乎tcp也发生了问题，难以链接。
目前生成的进程，安卓端也无法正常使用了，路由器端
![screenshot_20170803-101835](https://user-images.githubusercontent.com/16715966/28903036-3e3d035e-7835-11e7-8810-176e47369b34.png)

**Comment by sijidou** [comment]
不好意思，可能是我网络问题。现在好像又正常了，我再试一试😂

**Comment by afyji** [comment]
我这边测试，依然发现这个问题。请问是如何解决的？

**Comment by afyji** [comment]
1

**Comment by Sky891028** [comment]
same issue ,
What version of shadowsocks-libev are you using?
Master 

What operating system are you using?

centos 6.5

@sijidou 按照这里的方案我做了尝试 并没有解决 请问你那里解决了没

**Comment by cndanili** [comment]
The same issue has been encounterd by me. I have ss-manager running on 3 instaces and the operating systems are Ubuntu 17.10, Google version of Ubuntu 17.10 and digitalOcean verison ofUbuntu 14.04.

SS-manager has been running perfectly on Ubuntu 14.04, not the others. One of the differences is, directly "apt installed" does not ahve "--port-reuse" parameter when "ss-server" commanded by ss-manager. I can confirm that all udp ports and tcp ports are un blocked by firewall.

So I am going to rollback my OS from 17.10 to 16.04 to see if it going to work.

**Comment by cndanili** [comment]
Same issue has been encountered. I've set up 3 instances. 1 failed to work on my router at home. TCP works  smoothly, UDP not good. Sometimes it failed to transfer, sometimes OK

**Comment by KoKaiJuu** [comment]
确认到和sijidou一样状况的同一问题。用ssmgr启动ss-server时udp端口 连续转发时会偶然丢失。 用setsid运行的ss-server并没有该问题，而且tcp并没有受到影响

**Comment by KoKaiJuu** [comment]
Centos 7.3 和libev 3.1.1版本

**Comment by cndanili** [comment]
I have resloved my issue. The ss-server on Ubunt 17.10 does not have -reuse-port parameter. So I just downgraded my OS to Ubuntu 16.04 and got it fixed.
