### ISSUE TITLE
Regression: no way to bind to :: with dual stack.

### ISSUE THREAD

**Issue by jackyyf** [shadowsocks/shadowsocks-libev#1568]
### What version of shadowsocks-libev are you using?
shadowsocks-libev 3.0.7 (Debian package version: 3.0.7+ds-1~bpo9+1)

### What operating system are you using?
Debian stretch (9.0), with Linux Kernel 4.9.11 running in UML mode.

### What did you do?
Start server with `ss-server -c config.json`

### What did you expect to see?
Listen on "::" with dual stack available.

### What did you see instead?
Listen on "0.0.0.0", no ipv6 support.

### What is your config in detail (with all sensitive info masked)?
```json
{
	"server_port": 8080,
	"password": "some-password",
	"timeout": 120,
	"method": "chacha20"
}
```

This is actually a regression introduced by commit 3f1337540e2e2c2ed68b9574b36769cbf25820d4 ,which changed default `server_address[0]` from `NULL` to `0.0.0.0`, and in function `create_and_bind` at line 396, it sets `IPV6_V6ONLY` option to socket **unless** host is NULL, which is not possible after the commit.

Did the `IPV6_V6ONLY` option really needed? Or at least, make an exception for this if bind address is `::`.

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks-libev/issues/1349

**Comment by jackyyf** [comment]
Thanks :)
