### ISSUE TITLE
Shadowsocks COPR for Fedora 26

### ISSUE THREAD

**Issue by oszi** [shadowsocks/shadowsocks-libev#1570]
The [librehat/shadowsocks](https://copr.fedorainfracloud.org/coprs/librehat/shadowsocks/) copr is mentioned in the README so I assume it is official.
Fedora 26 has been released recently. Can you please update the repo to support it?
Thanks!

**Comment by madeye** [comment]
Please contact @librehat for copr related issues. This repo is not maintained by us.

**Comment by librehat** [comment]
I'll update it in a few days
