### ISSUE TITLE
Build failed (Couldn't find libudns)

### ISSUE THREAD

**Issue by surpassing** [shadowsocks/shadowsocks-libev#1572]
### What version of shadowsocks-libev are you using?
latest version - 3.0.7

### What operating system are you using?
CentOS-7-X86_64 with bbr installed (KVM)

### What did you do?
Install shadowsocks-libev
1. 
git clone https://github.com/shadowsocks/shadowsocks-libev.git
cd shadowsocks-libev
git submodule update --init --recursive

2.
yum install epel-release -y
yum install gcc gettext autoconf libtool automake make pcre-devel asciidoc xmlto udns-devel libev-devel libsodium-devel mbedtls-devel -y

"for this one, it throws out some errors":

"No package udns-devel available.
Package libev-devel-4.15-6.el7.x86_64 already installed and latest version
No package libsodium-devel available.
No package mbedtls-devel available."

"So I tried Step3"

3. 
all commands listed in https://github.com/shadowsocks/shadowsocks-libev#linux

4. 
Start building
./autogen.sh && ./configure && make

### What did you expect to see?
successfully configure and make

### What did you see instead?
...
...
checking for malloc... yes
checking for memset... (cached) yes
checking for posix_memalign... yes
checking for socket... yes
checking udns.h usability... no
checking udns.h presence... no
checking for udns.h... no
configure: error: Couldn't find libudns. Try installing libudns-dev or udns-devel.

### What is your config in detail (with all sensitive info masked)?

I tried all the methods that I learned from other similar issues, which all failed.

[root@host shadowsocks-libev]# ls /usr/local/lib/libsodium.*
/usr/local/lib/libsodium.a   /usr/local/lib/libsodium.so.18
/usr/local/lib/libsodium.la  /usr/local/lib/libsodium.so.18.2.0
/usr/local/lib/libsodium.so  /usr/local/lib/libsodium.so.18.3.0

[root@host shadowsocks-libev]# ls /usr/lib/libsodimu.*
ls: cannot access /usr/lib/libsodimu.*: No such file or directory

Thanks

**Comment by chenhw2** [comment]
try ```yum install epel-release -y``` again, then redo the process

**Comment by surpassing** [comment]
@chenhw2 Do I need to remove everything before I redo the process?

I tried 'yum install epel-release -y' and then redo the process, but still got 
'configure: error: Couldn't find libudns. Try installing libudns-dev or udns-devel.'

and in step 2, i still got 
'
"No package udns-devel available.
Package libev-devel-4.15-6.el7.x86_64 already installed and latest version
No package libsodium-devel available.
No package mbedtls-devel available."
'

**Comment by Galaxy0419** [comment]
build from source code

_Sent from my Xiaomi MI 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
