### ISSUE TITLE
启动不成功但是也没有报错

### ISSUE THREAD

**Issue by MingElf** [shadowsocks/shadowsocks-libev#1573]
### What version of shadowsocks-libev are you using?
3.0.6

### What operating system are you using?
CentOS 7 x64

### What did you do?
setsid ss-server -c /etc/shadowsocks-libev/config.json -u

### What did you expect to see?
maybe something like 'started'

### What did you see instead?
A long help message

`
[root@vultr ~]# setsid ss-server -c /etc/shadowsocks-libev/config.json -u
[root@vultr ~]#
shadowsocks-libev 3.0.6

  maintained by Max Lv <max.c.lv@gmail.com> and Linus Yang <laokongzi@gmail.com>

  usage:

    ss-server

       -s <server_host>           Host name or IP address of your remote server.
       -p <server_port>           Port number of your remote server.
       -l <local_port>            Port number of your local server.
       -k <password>              Password of your remote server.
       -m <encrypt_method>        Encrypt method: rc4-md5,
                                  aes-128-gcm, aes-192-gcm, aes-256-gcm,
                                  aes-128-cfb, aes-192-cfb, aes-256-cfb,
                                  aes-128-ctr, aes-192-ctr, aes-256-ctr,
                                  camellia-128-cfb, camellia-192-cfb,
                                  camellia-256-cfb, bf-cfb,
                                  chacha20-ietf-poly1305,
                                  salsa20, chacha20 and chacha20-ietf.
                                  The default cipher is rc4-md5.

       [-a <user>]                Run as another user.
       [-f <pid_file>]            The file path to store pid.
       [-t <timeout>]             Socket timeout in seconds.
       [-c <config_file>]         The path to config file.
       [-n <number>]              Max number of open files.
       [-i <interface>]           Network interface to bind.
       [-b <local_address>]       Local address to bind.

       [-u]                       Enable UDP relay.
       [-U]                       Enable UDP relay and disable TCP relay.
       [-6]                       Resovle hostname to IPv6 address first.

       [-d <addr>]                Name servers for internal DNS resolver.
       [--reuse-port]             Enable port reuse.
       [--fast-open]              Enable TCP fast open.
                                  with Linux kernel > 3.7.0.
       [--acl <acl_file>]         Path to ACL (Access Control List).
       [--manager-address <addr>] UNIX domain socket address.
       [--mtu <MTU>]              MTU of your network interface.
       [--mptcp]                  Enable Multipath TCP on MPTCP Kernel.
       [--key <key_in_base64>]    Key of your remote server.
       [--plugin <name>]          Enable SIP003 plugin. (Experimental)
       [--plugin-opts <options>]  Set SIP003 plugin options. (Experimental)

       [-v]                       Verbose mode.
       [-h, --help]               Print this message.

`

### What is your config in detail (with all sensitive info masked)?
{
 "server":"::",
 "server_port":8388,
 "local_address": "127.0.0.1",
 "local_port":1080,
  "port_password": {
     "****": "****",
     "****": "****"
 },
 "timeout":300,
 "method":"aes-256-cfb",
 "fast_open": false
}

**Comment by MingElf** [comment]
I just found the solution. **The config was written in a wrong way.** I mistakenly copied the settings of shadowsocks python.

**Comment by MingElf** [comment]
I rewrote the config file and 

`{
    "server":["[::0]","0.0.0.0"],
    "server_port":****,
    "local_address":"127.0.0.1",
    "local_port":1080,
    "password":"******",
    "timeout":300,
    "method":"aes-256-cfb"
}`

Then I started it again and error occured.

`
[root@vultr ~]# setsid ss-server -c /etc/shadowsocks-libev/config.json -u
[root@vultr ~]#  2017-07-19 15:29:23 INFO: UDP relay enabled
 2017-07-19 15:29:23 INFO: initializing ciphers... aes-256-cfb
 2017-07-19 15:29:23 ERROR: bind: Address already in use
 2017-07-19 15:29:23 ERROR: bind() error

`

**Comment by Galaxy0419** [comment]
@MingElf killall -9 ss-server

_Sent from my Xiaomi MI 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by MingElf** [comment]
Thanks! @Galaxy0419
