### ISSUE TITLE
The version of shadowsocks-libev installed via "yum install shadowsocks-libev" is only 2.5.5

### ISSUE THREAD

**Issue by dubu45** [shadowsocks/shadowsocks-libev#1576]
The version of shadowsocks-libev installed via "yum install shadowsocks-libev" is only 2.5.5, please upgrade, thank you.

### What version of shadowsocks-libev are you using?
2.5.5
### What operating system are you using?
Centos 6 x86_64
### What did you do?
yum update
### What did you expect to see?
Upgrade to the latest version
### What did you see instead?
Only to upgrade to 2.5.5
### What is your config in detail (with all sensitive info masked)?
normal

**Comment by pexcn** [comment]
更新你的源

**Comment by dubu45** [comment]
thank you
