### ISSUE TITLE
[Question] Can i get help about how to configure ss and kcptun on transit server

### ISSUE THREAD

**Issue by imMMX** [shadowsocks/shadowsocks-libev#1577]
### What version of shadowsocks-libev are you using?

shadowsocks-libev 3.0.7

### What operating system are you using?
Target Server:
&nbsp;&nbsp;Ubuntu 16.04 LTS
&nbsp;&nbsp;kernel 4.10.0-24-generic

Transit Server:
&nbsp;&nbsp;Ubuntu 16.04 LTS
&nbsp;&nbsp;kernel 4.10.15-041015-generic
#### Plan:
Client -> Kcptun Client (On transit server without iptables) -> Kcptun Server (On Target Server) -> SS-Server (On Target Server)

all this above were installed and configured.

### What did you expect to see?
How to let this work:
ss-client --TCP--> transit server -> kcptun (transit server) --UDP--> kcptun (target server) -> ss-server

Do I need to install ss-redir on transit server or use iptables to redirect to ss-local[local port]?
##### kcptun log:
```bash
2017/07/20 17:01:23 main.go:363: remote address: [transit server ip]:[random port]
2017/07/20 17:01:23 main.go:89: stream opened
2017/07/20 17:01:23 main.go:106: stream closed
2017/07/20 17:02:06 main.go:75: broken pipe
2017/07/20 17:07:42 main.go:363: remote address:  [transit server ip]:[random port]
2017/07/20 17:07:42 main.go:89: stream opened
2017/07/20 17:07:42 main.go:106: stream closed
```

it seems works but I do not know if I'm right.

##### Client config:

```
server address: [transit server ip]
server port: "443"
```

##### Transit server config (only kcptun):

```
"localaddr": ":443",
"remoteaddr": "[Target server ip]:4444",
```

###### kcptun config:

```
"listen": ":4444",
 "target": "127.0.0.1:443"
```

###### ss-server config:

```
"server": "0.0.0.0",
"server_port": 443,
"local_port": 1080,
```

with acl file "local.acl" which only allow LAN ip and [transit server ip] in the white list.

---
if i post this issue to the wrong place, let me know and i will close it as soon as possible.

**Comment by terrytw** [comment]
Try "target": "0.0.0.0:443" in target server kcptun config

**Comment by imMMX** [comment]
@terrytw Thanks for your help.
will try to use "0.0.0.0" replace "127.0.0.1". 
I didn't post this parameters here because I think it relevant to package transmission instead of network connectivity. I've set the FEC to 30:15 and make sure "crypt" and "password" are both correct.
I want to know if my plan is correct.

**Comment by terrytw** [comment]
Your setup sounds about right to me, which is why I suggested you to double check the parameters. Also in some of the kcptun variants like openwrt-kcptun by bettermanbao, you have to disable compression which means put "true" in "nocomp" on both sides, otherwise it would not work. 

Anyway why don't you do a few more experiments, like put shadowsocks and kcptun on both your client and see if it works? With more information it will be easier for others to help you.

**Comment by imMMX** [comment]
Thx for the reply.
I will do more tests and try to figure it out.
