### ISSUE TITLE
centos6下的repo为啥只有2.5版本，最新版的没有打包吗？

### ISSUE THREAD

**Issue by yanest** [shadowsocks/shadowsocks-libev#1579]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

**Comment by Shadowhack0419** [comment]
自己用checkinstall把编译好的源码打包

_Sent from my Xiaomi MI 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by librehat** [comment]
I've just updated it on COPR. Try `yum upgrade`
