### ISSUE TITLE
能否在Openwrt上通过iptables将指定数据包转发到局域网某Linux PC的ss-redir 1080端口

### ISSUE THREAD

**Issue by linshixiong** [shadowsocks/shadowsocks-libev#1581]
由于路由器性能限制，在路由器上运行ss-redir性能达不到要求，我的想法是，在路由器中设置iptables，将匹配gfwlist的数据包转发到局域网中某台PC的ss-redir 1080端口，该如何操作？

**Comment by bazingaterry** [comment]
不能，ss-redir 的原理限制了。不过你可以尝试用那台 PC 做路由器。

**Comment by lixingcong** [comment]
用那台 PC 做网关。

**Comment by linshixiong** [comment]
谢谢大家的回复，我也是了解到ss-redir的原理实现不了，但是还是来确认一下。
另外，PC做网关的形式我一直在使用，没有任何问题，只是不太希望这台PC一旦关机就导致整个网络中断，所以才想尝试上面的方法。

**Comment by ToughGuy1** [comment]
@linshixiong 

路由器IP：192.168.1.1
内网redirIP:  192.168.1.20

`
iptables -A PREROUTING -p tcp -m set --match-set gfwlist dst -j DNAT --to-destination 192.168.1.20:1080
iptables -A POSTROUTING -p tcp -d 192.168.1.20  -j SNAT --to-source 192.168.1.1
`

**Comment by ohyeah521** [comment]
@linshixiong  买一个APC-UPS

**Comment by jack2007** [comment]
这样子做，真实的目的ip地址和端口就丢了。
