### ISSUE TITLE
obfs plugin service exit unexpectedly

### ISSUE THREAD

**Issue by msdurex** [shadowsocks/shadowsocks-libev#1582]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
shadowsocks-libev 3.0.7
obfs plugin:0.0.3  
### What operating system are you using?
Debian 9

### What did you do?
ss-server -c /etc/shadowsocks-libev/config.json   to test the connections

### What did you expect to see?
Everything works fine

### What did you see instead?
 2017-07-22 15:39:46 INFO: plugin "obfs-server" enabled
 2017-07-22 15:39:46 INFO: initializing ciphers... chacha20-ietf-poly1305
 2017-07-22 15:39:46 INFO: This system doesn't provide enough entropy to quickly generate high-quality random numbe
rs
Installing the rng-utils/rng-tools or haveged packages may help.
On virtualized Linux environments, also consider using virtio-rng.
The service will not start until enough entropy has been collected.
 2017-07-22 15:39:46 INFO: tcp server listening at 127.0.0.1:44753
 2017-07-22 15:39:46 INFO: running from root user
 2017-07-22 15:39:46 [simple-obfs] INFO: obfuscating enabled
 2017-07-22 15:39:46 [simple-obfs] INFO: tcp port reuse enabled
 2017-07-22 15:39:46 [simple-obfs] ERROR: listen() error
 2017-07-22 15:39:46 ERROR: plugin service exit unexpectedly

### What is your config in detail (with all sensitive info masked)?
“server":"0.0.0.0",
"server_port":443,
"local_port":1080,
"password":"fuckgfw",
"timeout":3600,
"method":"chacha20-ietf-poly1305",
"plugin":"bfs-server",
"plugin_opts":"obfs=http"

Everytime I change to different server port. it works fine for few seconds. And than [simple-obfs] ERROR: listen() error again. Plz help.

**Comment by msdurex** [comment]
好了，obfs 默认不是用 root 权限运行的，给予root权限就搞定了。另外一个问题TCP Fast Open 不支持从config.json 里配置了吗？

**Comment by simonsmh** [comment]
"fast_open": true
"plugin_opts": "***;fast-open"

**Comment by 13025309325** [comment]
[simple-obfs] ERROR: listen() error 这个问题你是怎么解决的？我默认就是在root用户安装的

**Comment by msdurex** [comment]
Server 改成0.0.0.0

**Comment by bbxg** [comment]
>           [simple-obfs] ERROR: listen() error 这个问题你是怎么解决的？我默认就是在root用户安装的
不止在root操作，可以在
/lib/systemd/system/shadowsocks-libev.service
把nobody和nogroup都改成root，应该就好了
