### ISSUE TITLE
请问如何通过编辑config file达成多用户的目的

### ISSUE THREAD

**Issue by gyx99** [shadowsocks/shadowsocks-libev#1583]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
ppa源最新

### What operating system are you using?
搬瓦工VPS UBUNTU16.04 OVZ

**Comment by msdurex** [comment]
SS-libev不支持多用户模式。

**Comment by pexcn** [comment]
```
[-f <pid_file>]            the file path to store pid
```

**Comment by Shadowhack0419** [comment]
使用shell脚本日志分别重定向到不同文件

**Comment by josh233** [comment]
我使用了几个配置文件，多进程...... supervisor启动

2017年7月28日 22:30，"Max Lv" <notifications@github.com>写道：
