### ISSUE TITLE
更新后版本信息显示有误

### ISSUE THREAD

**Issue by sergio13848** [shadowsocks/shadowsocks-libev#1585]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
shadowsocks-libev 3.0.3

### What operating system are you using?
debian 8

### What did you do?
root@debian-512mb-sfo1-01:~# ss-server -h
shadowsocks-libev 3.0.3
用此命令查看版本信息，前几天才用git更新重新编译过的但是版本信息还是3.0.3，版本号没更改过来还是升级更新有问题？

**Comment by lixingcong** [comment]
```
./autogen.sh
```

**Comment by omaidb** [comment]
ss-server -h 是显示版本的？误怎么记得是ss-server --version
