### ISSUE TITLE
听说深圳地区shadowsocks已经开始被大量侦测,是真的吗

### ISSUE THREAD

**Issue by cjl3230** [shadowsocks/shadowsocks-libev#1586]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
github最新版

### What operating system are you using?
centos 6

### What did you do?
想咨询下可能用到的侦测技术,能否从自身防止被侦测,从而导致ip被封

### What did you expect to see?
不被侦测

### What did you see instead?
无

### What is your config in detail (with all sensitive info masked)?
无

**Comment by tianlichunhong** [comment]
这个没有深喉，估计回答不了你这个问题。

**Comment by teddy5253** [comment]
假的，，，

**Comment by xcjiang** [comment]
真的，而且不止深圳，广州的也有。初期肯定是杀鸡儆猴了，所以大部分人还没事，但预计未来肯定是要全面严打。
