### ISSUE TITLE
Compile failed on Centos 7: can not find installed libsodium-1.0.5-1.el7.x86_64

### ISSUE THREAD

**Issue by citaret** [shadowsocks/shadowsocks-libev#1587]
### What version of shadowsocks-libev are you using?
shadowsocks-libev-3.0.7

### What operating system are you using?
CentOS Linux release 7.3.1611 (Core) 

### What is your config in detail (with all sensitive info masked)?

    ./configure

### What did you do?
The system has salt-minion pre-installed, which depends on zeromq, libsodium, the version of libsodium is 1.0.5-1.el7 from epel repos, so libsodium 1.0.5 is in the system.

When I run ./configure from shadowsocks-libev source, there is an error as:

    checking for sodium_init in -lsodium... no
    configure: error: The Sodium crypto library libraries not found.

I check the pre-installed libsodium package, only two files in the lib path:

    /usr/lib64/libsodium.so.13
    /usr/lib64/libsodium.so.13.3.0

I add a soft link /usr/lib64/libsodium.so to /usr/lib64/libsodium.so.13.3.0, and run configure again, the error change to:

    checking for sodium_init in -lsodium... yes
    configure: error: Wrong libsodium: version >= 1.0.4 required

Since the version of installed libsodium is 1.0.5, I wonder what causes the problem.

BTW: I have tried to uninstall the libsodium package, and compile and install libsodium 1.0.12 from source, then there is no problem to compile shadowsocks-libev, however, after that, I can not install salt-minion due to the dependency problem.

**Comment by ToughGuy1** [comment]
干嘛不仔细看看README先呢。

> # Installation of basic build dependencies
## Debian / Ubuntu
sudo apt-get install --no-install-recommends gettext build-essential autoconf libtool libpcre3-dev asciidoc xmlto libev-dev libudns-dev automake libmbedtls-dev libsodium-dev
## CentOS / Fedora / RHEL
sudo yum install gettext gcc autoconf libtool automake make asciidoc xmlto udns-devel libev-devel
## Arch
sudo pacman -S gettext gcc autoconf libtool automake make asciidoc xmlto udns libev

# Installation of Libsodium
export LIBSODIUM_VER=1.0.12
wget https://download.libsodium.org/libsodium/releases/libsodium-$LIBSODIUM_VER.tar.gz
tar xvf libsodium-$LIBSODIUM_VER.tar.gz
pushd libsodium-$LIBSODIUM_VER
./configure --prefix=/usr && make
sudo make install
popd
sudo ldconfig

# Installation of MbedTLS
export MBEDTLS_VER=2.5.1
wget https://tls.mbed.org/download/mbedtls-$MBEDTLS_VER-gpl.tgz
tar xvf mbedtls-$MBEDTLS_VER-gpl.tgz
pushd mbedtls-$MBEDTLS_VER
make SHARED=1 CFLAGS=-fPIC
sudo make DESTDIR=/usr install
popd
sudo ldconfig

# Start building
./autogen.sh && ./configure && make
sudo make install

**Comment by changyp6** [comment]
run "sudo yum -y install libsodium-devel"
then ./configure
I suggest you upgrade your libsodium to the latest libsodium-1.0.13 version.

**Comment by citaret** [comment]
Hi, changyp6,

The problem is solved after installing libsodium-devel. Thanks.
