### ISSUE TITLE
How to turn on the TFO with the config.json?

### ISSUE THREAD

**Issue by msdurex** [shadowsocks/shadowsocks-libev#1591]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
3.0.7 simple-obis 0.0.3

### What operating system are you using?
Debian 9

**Comment by terrytw** [comment]
"plugin_opts":"obfs=http;fast-open"

**Comment by rogers0** [comment]
With the simple-obfs hit jessie/stretch through backports, I think now it's the time to add a default working config for it. Could anyone volunteer to write one and send a PR? Thanks!

**Comment by suikatomoki** [comment]
{
    "server":"0.0.0.0",  
    "server_port":443, 
    "password":"pwd",
    "timeout":600,
    "method":"chacha20-ietf-poly1305",
    "mode":"tcp_and_udp",
    "fast_open":true,
    "plugin":"obfs-server",
    "plugin_opts":"obfs=tls;failover=127.0.0.1:8443;fast-open"
}

{
    "server":"223.3.3.3",
    "server_port":443,
    "local_address":"0.0.0.0",
    "local_port":1080,
    "password":"pwd",
    "timeout":600,
    "method":"chacha20-ietf-poly1305",
    "mode":"tcp_and_udp",
    "fast_open":true,
    "plugin":"obfs-local",
    "plugin_opts":"obfs=tls;obfs-host=www.taobao.com;fast-open"
}

**Comment by rogers0** [comment]
@suikatomoki thanks!
since the config seems breaks original shadowsocks-libev, maybe it's better to split shadowsocks-libev into shadowsocks-libev-standalone and shadowsocks-libev-obfs?

@madeye @hosiet
It's just an idea, which I want to hear feedback from real users.
It's better to have some consensus before I start to work. Thanks!

**Comment by rogers0** [comment]
@suikatomoki @madeye 
to share the same default config with shadowsocks-libev as much as possible, I changed a bit and here's the config I'm going to put it into simple-obfs package:

{
    "server":"127.0.0.1",
    "server_port":8388,
    "local_port":1080,
    "password":"barfoo!",
    "timeout":60,
    "method":"chacha20-ietf-poly1305",
    "mode":"tcp_and_udp",
    "fast_open":true,
    "plugin":"obfs-server",
    "plugin_opts":"obfs=tls;failover=127.0.0.1:8443;fast-open"
}
