### ISSUE TITLE
是否可以更改一下  libipset 里面的部分文件

### ISSUE THREAD

**Issue by hillwoodroc** [shadowsocks/shadowsocks-libev#1592]
libipset 里面不少文件的名称和 ipset 是相同，在同时需要安装两者时是会造成冲突，是否可以考虑重命名以下文件名？

**Comment by madeye** [comment]
These headers would not be installed to your system. So, I don't think there is any conflict.

**Comment by hillwoodroc** [comment]
Problem files are at least,
pkgconfig/libipset.pc libipset.so*
For the moment the headers do not conflict.

There is the filelist for ipset:

%_sbindir/ipset
%_mandir/man*/*
%_libdir/libipset.so.3*
%_libdir/libipset.so
%_libdir/pkgconfig/libipset.pc

Some of them are same as in libipset.

**Comment by madeye** [comment]
Could you follow the debian distribution to port these libraries?

https://packages.debian.org/search?keywords=libcorkipset-dev
