### ISSUE TITLE
2017-07-27 05:12:18 ERROR: unable to resolve static.tieba.baidu.com 容器内部域名解析出错

### ISSUE THREAD

**Issue by xuhuigithub** [shadowsocks/shadowsocks-libev#1593]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?

SS_VER=3.0.8
### What operating system are you using?
Centos 7.3
from docker image alpine 

### What did you do?
我用 这个https://github.com/shadowsocks/shadowsocks-libev/tree/master/docker/alpine地址创建了一个docker image 
并使用如下命令运行了他
docker run -dti -p 8389:8388 -e PASSWORD=123456 -e DNS_ADDR=114.114.114.114 -e DNS_ADDR_2=202.106.0.20 images.xuhui.com/library/shadowsocks-libev
### What did you expect to see?
我用dokcer logs 查看到了如下报错
2017-07-27 05:12:18 ERROR: fast open is not supported on this platform

**Comment by xuhuigithub** [comment]
并且 在顺利运行镜像后 我使用客户端连接后
打开百度异常缓慢，并发现如下报错
（docker logs）
2017-07-27 05:18:55 ERROR: unable to resolve static.tieba.baidu.com
 2017-07-27 05:18:55 ERROR: unable to resolve static.tieba.baidu.com
 2017-07-27 05:18:55 ERROR: unable to resolve static.tieba.baidu.com

容器内部运行nslookup 发现如下报错
~ $ nslookup www.baidu.com
nslookup: can't resolve '(null)': Name does not resolve

Name:      www.baidu.com
Address 1: 119.75.216.20
Address 2: 119.75.213.61

**Comment by madeye** [comment]
Add `-d 8.8.8.8` to your server's command line.

**Comment by xuhuigithub** [comment]
General options:
  -d start/stop/restart  daemon mode

**Comment by madeye** [comment]
```
docker run -dti -p 8389:8388 -e PASSWORD=123456 -e DNS_ADDR=8.8.8.8 -e DNS_ADDR_2=202.106.0.20 images.xuhui.com/library/shadowsocks-libev
```
