### ISSUE TITLE
请问这样的日志是什么情况？

### ISSUE THREAD

**Issue by rule2c** [shadowsocks/shadowsocks-libev#1597]
### What version of shadowsocks-libev are you using?
3.0.8

### What operating system are you using?
debian 8

### What did you do?
正常上网

### What did you expect to see?
正常日志

### What did you see instead?
ERROR: crypto: AEAD: repeat salt detected

### What is your config in detail (with all sensitive info masked)?
默认的配置，加密方式为chacha20-ietf-poly1305

**Comment by madeye** [comment]
It means there is an illegal request to the server.

It's expected when you deploy your server on a well known port number, e.g. 80 and 443.

**Comment by rule2c** [comment]
thanks. @madeye
