### ISSUE TITLE
编译安装时报错

### ISSUE THREAD

**Issue by lizhaode** [shadowsocks/shadowsocks-libev#1602]
在执行命令 `./autogen.sh && ./configure && make`时，报错，错误如下
```
ss_local-aead.o: In function `aead_cipher_decrypt':
/root/shadowsocks-libev/src/aead.c:219: undefined reference to `crypto_aead_xchacha20poly1305_ietf_decrypt'
ss_local-aead.o: In function `aead_cipher_encrypt':
/root/shadowsocks-libev/src/aead.c:180: undefined reference to `crypto_aead_xchacha20poly1305_ietf_encrypt'
collect2: error: ld returned 1 exit status
Makefile:677: recipe for target 'ss-local' failed
make[2]: *** [ss-local] Error 1
make[2]: Leaving directory '/root/shadowsocks-libev/src'
Makefile:479: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/root/shadowsocks-libev'
Makefile:388: recipe for target 'all' failed
make: *** [all] Error 2
```

出错时，已经安装了LIBSODIUM和MBEDTLS，VPS是搬瓦工的KVM机器。内核版本是 Linux ubuntu 4.12.0-041200-generic ，操作系统是 Ubuntu 16.04.2 LTS

**Comment by Shadowhack0419** [comment]
你是不是按照教程装了libsodium-dev然后又源码安装了一遍?是的话重载系统，下次不要装dev包直接从教程上装完源码的就好

_Sent from my Xiaomi MI 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by lizhaode** [comment]
@Shadowhack0419 
他之前不是说安装这些依赖吗？
`sudo apt-get install --no-install-recommends gettext build-essential autoconf libtool libpcre3-dev asciidoc xmlto libev-dev libudns-dev automake libmbedtls-dev libsodium-dev`

我是先执行了这个，然后又按照他写的，下载了LIBSODIUM和MBEDTLS，编译安装了，然后make ss-libev就报错了

**Comment by Shadowhack0419** [comment]
@lizhaode 这边是作者写错的一点地方，当初装也卡了很久，libsodium-dev和mbedtls-dev就是教程中要求安装的libsodium1.0.13和mbedtls2.5.1如果事先装过dev再源码安装，会有问题。


_Sent from my Xiaomi MI 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by lizhaode** [comment]
@Shadowhack0419 原来如此，多谢

**Comment by DrawLi** [comment]
重载系统有点粗暴，看问题应该可以：
apt-get purge libsodium-dev
apt-get autoclean
之类，然后再手动安装
