### ISSUE TITLE
A lot of "crypto: AEAD: repeat salt detected" error

### ISSUE THREAD

**Issue by dutonttie** [shadowsocks/shadowsocks-libev#1603]
### What version of shadowsocks-libev are you using?
3.0.8

### What operating system are you using?
  debian 7 32bit or centos 6.9  32bit

### What did you do?
Running net-speeder result in lot of  "crypto: AEAD: repeat salt detected" error.

Stop net-speeder error disapears.

The client function is working properly

### What did you expect to see?
Is this normal?

### What did you see instead?

A lot of "crypto: AEAD: repeat salt detected" error in log.

### What is your config in detail (with all sensitive info masked)?
"server":"0.0.0.0",
    "server_port":xxx,
    "local_port":1080,
    "password":"xxxxxxxx",
    "timeout":60,
    "method":"aes-128-gcm",
    "workers":5,
    "plugin":"obfs-server",
    "plugin_opts":"obfs=http"

![2017-07-29 19-42-42](https://user-images.githubusercontent.com/9409003/28744561-3c3949ec-7429-11e7-83c9-b682b68679cd.png)

**Comment by madeye** [comment]
It's expected if you double sending packets with net-speeder.

Disable net-speeder or just ignore the logs.

**Comment by dutonttie** [comment]
OK~~~

**Comment by siwind** [comment]
```
 ERROR: crypto: AEAD: repeat salt detected
 ERROR: failed to handshake with 12x.2xx.4xx.1x: authentication error
```

If thost suspicious addresses(lik '**12x.2xx.4xx.1x**' ) was found in systemctl log,   write a shell to block  it by firewall rules, which works **fine** for your **shadowsock server**.
