### ISSUE TITLE
shadowsocks-libev installed by yum can not start

### ISSUE THREAD

**Issue by dubu45** [shadowsocks/shadowsocks-libev#1604]
### What version of shadowsocks-libev are you using?
3.0.8-1

### What operating system are you using?
CentOS 7

### What did you do?
yum install shadowsocks-libev
……
systemctl start shadowsocks-libev

### What did you expect to see?
shadowsocks-libev normal boot and work.

### What did you see instead?
systemctl start shadowsocks-libev
Job for shadowsocks-libev.service failed because a configured resource limit was exceeded. See "systemctl status shadowsocks-libev.service" and "journalctl -xe" for details.

systemctl status shadowsocks-libev
● shadowsocks-libev.service - Shadowsocks-libev Default Server Service
   Loaded: loaded (/usr/lib/systemd/system/shadowsocks-libev.service; enabled; vendor preset: disabled)
   Active: failed (Result: resources)
     Docs: man:shadowsocks-libev(8)

Jul 30 11:01:29 **** systemd[1]: Failed to load environment files: No such file or directory
Jul 30 11:01:29 **** systemd[1]: shadowsocks-libev.service failed to run 'start' task: No such file or directory
Jul 30 11:01:29 **** systemd[1]: Failed to start Shadowsocks-libev Default Server Service.
Jul 30 11:01:29 **** systemd[1]: shadowsocks-libev.service failed.
Jul 30 11:01:29 **** systemd[1]: Starting Shadowsocks-libev Default Server Service...
Jul 30 11:07:33 **** systemd[1]: Failed to load environment files: No such file or directory
Jul 30 11:07:33 **** systemd[1]: shadowsocks-libev.service failed to run 'start' task: No such file or directory
Jul 30 11:07:33 **** systemd[1]: Failed to start Shadowsocks-libev Default Server Service.
Jul 30 11:07:33 **** systemd[1]: shadowsocks-libev.service failed.
Jul 30 11:07:33 **** systemd[1]: Starting Shadowsocks-libev Default Server Service...

### What is your config in detail (with all sensitive info masked)?
{
    "server":["[::0]", "0.0.0.0"],
    "server_port":****,
    "local_port":****,
    "password":"**********",
    "timeout":300,
    "method":"chacha20-ietf-poly1305",
}

**Comment by Shadowhack0419** [comment]
Try to install from source code

_Sent from my Xiaomi MI 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by librehat** [comment]
Can you start it manually via command-line?

**Comment by hosiet** [comment]
While we can set `EnvironmentFile` as optional, this won't fix the problem from the root.

To debug the problem, please provide with the following information in detail:

1. How did you install shadowsocks-libev on CentOS 7? (e.g., from copr, a random `.rpm` file or any third-party repository, plus its URL on the Internet?)
2. Please provide the content of file `/lib/systemd/system/shadowsocks-libev.service`.
3. Please provide the output of following comands:
```shell
ls -l /etc/default/
ls -l /etc/sysconfig/
```

**Comment by dubu45** [comment]
@librehat Yes, it can be started from the command line.

**Comment by dubu45** [comment]
@hosiet 
1. I used the following installation method, you can view the details from the "https://github.com/shadowsocks/shadowsocks-libev"

Install from repository
download yum repo on Fedora Copr and put it inside /etc/yum.repos.d/.
Then, install shadowsocks-libev via yum:
su -c 'yum update'
su -c 'yum install shadowsocks-libev'

2. vi /lib/systemd/system/shadowsocks-libev.service

#  This file is part of shadowsocks-libev.
#
#  Shadowsocks-libev is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 3 of the License, or
#  (at your option) any later version.
#
#  This file is default for Debian packaging. See also
#  /etc/sysconfig/shadowsocks-libev for environment variables.

[Unit]
Description=Shadowsocks-libev Default Server Service
Documentation=man:shadowsocks-libev(8)
After=network.target

[Service]
Type=simple
EnvironmentFile=/etc/sysconfig/shadowsocks-libev
User=nobody
Group=nobody
LimitNOFILE=32768
ExecStart=/usr/bin/ss-server -c $CONFFILE $DAEMON_ARGS

[Install]
WantedBy=multi-user.target

3. [root@**** ~]# ls -l /etc/default/
total 24
-rw-r--r--  1 root root  228 Jul 30 08:58 grub
-rw-r--r--  1 root root 1756 Jul 17 13:04 nss
-rw-r--r--  1 root root  605 Jul 29 11:00 shadowsocks-libev
-rw-r--r--  1 root root  605 Jul 29 11:00 shadowsocks-libev.rpmnew
-rw-r--r--  1 root root  617 Jul 30 10:31 shadowsocks-libev.rpmsave
-rw-r--r--. 1 root root  119 Nov  4  2016 useradd

[root@digitalocean-sfo2 ~]# ls -l /etc/sysconfig/
total 120
-rw-r--r--. 1 root root  429 Jun 19 23:01 authconfig
drwxr-xr-x. 2 root root 4096 Jun 19 22:57 cbq
drwxr-xr-x. 2 root root 4096 Apr 12 20:24 console
-rw-r--r--  1 root root  150 Jul  4 15:35 cpupower
-rw-------. 1 root root  110 Mar 31  2016 crond
-rw-------. 1 root root 1390 Nov  5  2016 ebtables-config
-rw-r--r--. 1 root root   73 May 25 20:21 firewalld
lrwxrwxrwx. 1 root root   17 Jun 19 22:58 grub -> /etc/default/grub
-rw-r--r--. 1 root root  798 Apr 12 20:24 init
-rw-------  1 root root  824 Jul 30 09:33 ip6tables
-rw-------  1 root root  635 Jul 22 06:19 ip6tables.bak
-rw-------. 1 root root 1988 Nov  5  2016 ip6tables-config
-rw-------  1 root root  816 Jul 30 09:33 ip6tables.save
-rw-------  1 root root  815 Jul 30 09:12 iptables
-rw-------  1 root root  550 Jul 22 05:51 iptables.bak
-rw-------. 1 root root 1974 Nov  5  2016 iptables-config
-rw-------  1 root root  781 Jul 30 09:12 iptables.save
-rw-r--r--. 1 root root  903 Apr 12 13:26 irqbalance
-rw-r--r--. 1 root root 1460 Nov  7  2016 kdump
-rw-r--r--. 1 root root  180 Jun 19 23:00 kernel
-rw-r--r--. 1 root root  200 Mar 17  2014 man-db
drwxr-xr-x. 2 root root 4096 Apr 12 20:24 modules
-rw-r--r--. 1 root root  634 Apr 12 20:24 netconsole
-rw-r--r--. 1 root root   42 Jul 22 02:32 network
drwxr-xr-x. 2 root root 4096 Jul 30 11:27 network-scripts
-rw-r--r--. 1 root root   15 Nov  7  2016 rdisc
-rw-r--r--. 1 root root  755 Apr 12 20:24 readonly-root
-rw-r--r--. 1 root root   12 Nov 20  2015 rsyncd
-rw-r--r--. 1 root root  196 Nov  4  2016 rsyslog
-rw-r--r--. 1 root root    0 Jun  9  2014 run-parts
lrwxrwxrwx. 1 root root   17 Jun 19 22:58 selinux -> ../selinux/config
-rw-r-----. 1 root root  506 Apr 12 14:05 sshd
-rw-r--r--. 1 root root  610 Mar  3 08:56 wpa_supplicant

**Comment by hosiet** [comment]
@librehat I believe it is your problem. The environment file should be at `/etc/sysconfig/shadowsocks-libev` but you used `/etc/default/shadowsocks-llibev`.

**Comment by librehat** [comment]
It seems they've updated the path of that file. I'll fix the rpmspec

**Comment by librehat** [comment]
@vfreex We should find a better way to handle this systemd service patch. I can't find a way to apply this patch with automated build with Copr. In the end, I still used manual upload for this build. But it'd be much easier if we can trigger the build from `git`.

@dubu45 You can do an update after https://copr.fedorainfracloud.org/coprs/librehat/shadowsocks/build/585224/ is finished. The problem should then be solved.

**Comment by dubu45** [comment]
@Shadowhack0419 @librehat @hosiet Thank you very much !

**Comment by vfreex** [comment]
@librehat Agreed.
I used Copr a lot of times. It seems to me that it is not easy to automate Copr builds (unless you are using tito). e.g. If mock build is used, source files specified by URL in the spec file will not be downloaded.
I am thinking build RPMs with Travis then push the resulting RPMs to GitHub releases or packagecloud. What do you think?

**Comment by librehat** [comment]
@vfreex I would prefer to have them built in Copr. RPMs should be built for different distributions individually. I don't think it is a good practice to have one RPM for all. If we want to provide a binary package for all Linux distributions, maybe we can consider AppImage or flatpak. 
Back to the RPM topic, how about maintaining a separate set of systemd files for RPM distributions? It's quite unlikely that they get changed very often.

**Comment by vfreex** [comment]
@librehat OK with me.

**Comment by yangzhl** [comment]
> @librehat I believe it is your problem. The environment file should be at `/etc/sysconfig/shadowsocks-libev` but you used `/etc/default/shadowsocks-llibev`.

It works for centos
