### ISSUE TITLE
windows下编译问题

### ISSUE THREAD

**Issue by leeecho** [shadowsocks/shadowsocks-libev#1605]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What did you do?

请问，shadowsocks-libev支持在windows编译local吗？

**Comment by madeye** [comment]
Try cygwin or WSL (https://msdn.microsoft.com/en-us/commandline/wsl/install_guide)
