### ISSUE TITLE
Stale files contained in release tarballs

### ISSUE THREAD

**Issue by yousong** [shadowsocks/shadowsocks-libev#1608]
This was first observed with v3.0.7 by phase2 buildbots of LEDE CI systems and temporarily fixed by deleting those stale files with commit : https://github.com/openwrt/packages/commit/b7f69c063370f87a15f4e47cda394f6f90c3bd5e

The issue is still present in v3.0.8

```
    ➜  shadowsocks-libev-3.0.7 git:(master) find . -name '*.o' -o -name '*.lo'
    ./libbloom/murmur2/libbloom_la-MurmurHash2.o
    ./libbloom/murmur2/libbloom_la-MurmurHash2.lo
    ./libbloom/libbloom_la-bloom.lo
    ./libbloom/libbloom_la-bloom.o
    ➜  shadowsocks-libev-3.0.7 git:(master) ls -l libbloom/murmur2
    total 24
    -rw-r--r-- 1 yousong yousong  324 Jun 27 14:17 libbloom_la-MurmurHash2.lo
    -rw-r--r-- 1 yousong yousong 4168 Jun 27 14:17 libbloom_la-MurmurHash2.o
    -rw-r--r-- 1 yousong yousong 1344 Feb 17 08:47 MurmurHash2.c
    -rw-r--r-- 1 yousong yousong  142 Feb 17 08:47 murmurhash2.h
    -rw-r--r-- 1 yousong yousong  213 Feb 17 08:47 README
    ➜  shadowsocks-libev-3.0.7 git:(master) file ./libbloom/murmur2/libbloom_la-MurmurHash2.o
    ./libbloom/murmur2/libbloom_la-MurmurHash2.o: ELF 64-bit LSB relocatable, x86-64, version 1 (SYSV), not stripped
    ➜  shadowsocks-libev-3.0.7 git:(master)
```

**Comment by yousong** [comment]
By release tarballs, I mean those tar.gz files manually uploaded by maintainers of this project, not those generated automatically by github.

**Comment by madeye** [comment]
Thanks for the report. You may use the zip file generated by github as a workaround.

**Comment by yousong** [comment]
The problem with github generated files are that
 - Github does not guarantee that the generated file will have consistent hash value across different download requests
 - The auto-generated zip/tar.gz files do not have git submodules like libbloom, libipset bundled...
