### ISSUE TITLE
Adding framework NoiseSocket

### ISSUE THREAD

**Issue by asmadeus08** [shadowsocks/shadowsocks-libev#1609]
Any idea about how to add or connect NoiseSocket Protocol to SS-libev?
http://noiseprotocol.org/specs/noisesocket.html
https://github.com/noisesocket/spec
http://noiseprotocol.org/noise.html

**Comment by puxxustc** [comment]
@asmadeus08 Seems not much benefit. Besides, `A Noise protocol begins with two parties exchanging handshake messages`, handshakes may make it more easily to be detected.

**Comment by madeye** [comment]
I don't think it's related to shadowsocks-libev.

You can always use any obfuscating tools as a SIP003 plugin for shadowsocks.
