### ISSUE TITLE
Strange IP Block

### ISSUE THREAD

**Issue by SXKDZ** [shadowsocks/shadowsocks-libev#1611]
### What version of shadowsocks-libev are you using?
3.0.8-1~ppa1x (server side)
ShadowsocksX-NG 1.5.1 (client side)

### What operating system are you using?
Ubuntu 16.04

### What did you do?
normal connect to ss, but received "Block all requests from IP xxxxxx" when i failed to browse Google and checked systemctl status out

### What did you expect to see?
prevent me from normal connection

### What did you see instead?
after restarting the server, it turns out to be normal
but two days later, the same issue happened again

### What is your config in detail (with all sensitive info masked)?
{
    "server":"45.xxx.xxx.xxx",
    "server_port":9999,
    "local_port":1080,
    "password":"xxx.xxx.xxx",
    "timeout":60,
    "method":"chacha20-ietf-poly1305"
}

**Comment by madeye** [comment]
Please post the full logs before your IP got blocked.

**Comment by Joey0904** [comment]
I've  encounter and solve this one just minutes ago.
This situation occurred when I was trying to change my encryption method from rc4-md5 to chacha20-ietf-poly1305.
took me a while to figure it out.

please check if there's any device/shadowsocks-client in your LAN is trying to set up a connection to your ss-server with wrong configuration( eg. encryption method)

**Comment by SXKDZ** [comment]
solved ...
i also faced such situation whereas i did not change the configuration in my virtual pc system accordingly
