### ISSUE TITLE
请问shadowsocks-libev-dbgsym是否需要安装

### ISSUE THREAD

**Issue by triaqu** [shadowsocks/shadowsocks-libev#1617]
今天在debian下编译生成了个shadowsocks-libev-dbgsym_3.0.8-1_amd64.deb文件，请问这个文件是否需要安装，具体是什么功能呢？

**Comment by changyp6** [comment]
不用装。
Debug symbol而已。

triaqu <notifications@github.com>于2017年8月7日周一 11:47写道：

**Comment by triaqu** [comment]
谢谢。因为教程安装命令是 sudo dpkg -i shadowsocks-libev*.deb ，以为有什么新功能。
