### ISSUE TITLE
从2.4.0升级到3.0.8之后ss-redir的包不走/etc/hosts解析

### ISSUE THREAD

**Issue by reusu** [shadowsocks/shadowsocks-libev#1623]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
2.4.0 => 3.0.8

### What operating system are you using?
Ubuntu 14.04.3

### What did you do?
本来我都是用hosts强行劫持解析到自己的一个缓存服务器来加速某些资源的
ss-redir客户端更新到3.0.8之后
发现包会不经过本地解析的IP

### What did you expect to see?
我希望可以像2.4.0那样
可以兼容/etc/hosts 劫持解析

### What did you see instead?
然而这边走服务端的时候直接解析到了真正的目标
并没有解析到我的hosts指定的服务器

### What is your config in detail (with all sensitive info masked)?
ss-redir -s x.x.x.x -p xxxx -k ******* -m chacha20 -u -f /var/run/ss-redir.pid

**Comment by reusu** [comment]
ss-redir -s x.x.x.x -p xxxx -k ******* -m chacha20 -t 300 -l 10800 -u -f /var/run/ss-redir.pid

**Comment by madeye** [comment]
It's expected.

1. Try ipset and dnsmasq to bypass all the domains.
2, Or try add `disable_sni:true` to your config file.

**Comment by reusu** [comment]
配置文件添加disable_sni成功了
感谢madeye大大回复
顺带请问下这个参数不能以命令行（非配置文件）方式启用么

**Comment by madeye** [comment]
Nope, it's a hidden feature for some special use cases. Just use config file to disable sni.
