### ISSUE TITLE
Encryption Failed

### ISSUE THREAD

**Issue by txfengj** [shadowsocks/shadowsocks-libev#1627]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
Version: 2.6.3+ds-1

### What operating system are you using?
Ubuntu 17.04 the same problem also appears on CentOS 7

### What did you do?
Normally install shadowsocks-libev

### What did you expect to see?
Normally Function

### What did you see instead?
● shadowsocks-libev.service - Shadowsocks-libev Default Server Service
   Loaded: loaded (/lib/systemd/system/shadowsocks-libev.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2017-08-11 04:07:33 UTC; 2s ago
     Docs: man:shadowsocks-libev(8)
  Process: 2259 ExecStart=/usr/bin/ss-server -c $CONFFILE $DAEMON_ARGS (code=exited, status=255)
 Main PID: 2259 (code=exited, status=255)
      CPU: 1ms

Aug 11 04:07:33 vultr.guest systemd[1]: Started Shadowsocks-libev Default Server Service.
Aug 11 04:07:33 vultr.guest systemd[1]: shadowsocks-libev.service: Main process exited, code=exited, status=255/n/a
Aug 11 04:07:33 vultr.guest systemd[1]: shadowsocks-libev.service: Unit entered failed state.
Aug 11 04:07:33 vultr.guest systemd[1]: shadowsocks-libev.service: Failed with result 'exit-code'.

### What is your config in detail (with all sensitive info masked)?
{
    "server":"45.32.73.173",
    "server_port":8388,
    "local_port":1080,
    "password":"diDG13djornu",
    "timeout":300,
    "method":aes-256-cfb
}

**Comment by madeye** [comment]
You missed the pair of `"` in your json config file:

```
"method":"aes-256-cfb"
```
