### ISSUE TITLE
能指定日志文件吗？

### ISSUE THREAD

**Issue by lizhaode** [shadowsocks/shadowsocks-libev#1630]
就像以前Python版本的ss一样，可以在配置文件中指定log日志的级别和路径

**Comment by madeye** [comment]
Nope, you can redirect the log file or find the log in syslog by enabling `use_syslog` in the configuration file.

**Comment by lizhaode** [comment]
为啥不提供单独的日志输出了呢？

**Comment by lizhaode** [comment]
而且，好像在Ubuntu上，就是输出到 /var/log/syslog 这个文件中的？

**Comment by Shadowhack0419** [comment]
不要-f参数然后用nohup加上&，再重定向到一个日志文件，例如：nohup ss-server -…… > file.log 2>&1 &

_Sent from my Xiaomi MI 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yyuurrii34** [comment]
安装一个rsyslog，如centos 7系统
`yum install rsyslog -y && systemctl start rsyslog`
可以在/var/log/messages中找到所有systemd的日志(包括*ss-server*)。
