### ISSUE TITLE
what is the difference between ss-tunnel and ss-local?

### ISSUE THREAD

**Issue by heraclitusq** [shadowsocks/shadowsocks-libev#1631]
Just wondering what the difference is between ss-tunnel and ss-local. What's the difference between the typical usage scenario of them? I tried to understand it before implementing it on my server. The documentation doesn't help a lot. Most of them are the same. Googling for a while doesn't return useful info either.
Thanks.

**Comment by chenhw2** [comment]
One of ```ss-tunnel``` usage: Clean DNS
```ss-tunnel -c config.json -l :5300 -L 8.8.8.8:53 -u```

One of ```ss-local``` usage: Socks Proxy
```ss-tunnel -c config.json -l :1080```

**Comment by heraclitusq** [comment]
Thanks mate for the example. I guess I kind of understand it. Correct me if I interpreted it wrong:

ss-local acts like ssh -D, while ss-tunnel acts like ssh -L
That to say, ss-tunnel directs all the packages to one destination, but ss-local directs packages to where they intend to go after they reach the server.
So ss-tunnel is used when I would like to map the remote service port to local.
ss-local is used when the destinations are dynamic.

For the examples given by @chenhw2 above, can I say ss-local will achieve the same effect if I properly setup the DNS server and redirect the DNS query to port 1080?

**Comment by chenhw2** [comment]
Yes, U can setup the DNS server and redirect the DNS query to port 1080, but why not use ss-tunnel?

**Comment by heraclitusq** [comment]
Just try to understand the difference. `ss-tunnel` obviously is perfect for this purpose. Thanks. I am going to close this ticket. In the mean time, if more explanation about the `ss-tunnel` could be added into the documentation, that will be awesome.
