### ISSUE TITLE
Is there any tool/module in ss-libev which can map local service port to remote?

### ISSUE THREAD

**Issue by heraclitusq** [shadowsocks/shadowsocks-libev#1634]
This would rather be a question/feature request than an issue. Now that I understand `ss-local` acts like `ssh -D` and `ss-tunnel` acts like `ssh -L` in #1631, I can't help thinking if there is tool/module in ss-libev that similar to `ssh -R`, which maps local service port to the remote.
Thanks.

**Comment by chenhw2** [comment]
https://github.com/ginuerzh/gost

**Comment by heraclitusq** [comment]
Thanks for recommending `gost`. I am aware of other tools which can accomplish this task, but I am still interested to know if ss-libev has this function / will have it in the future. It simplifies the work by avoiding another layer and reducing the learning cost so that people don't have to learn how to use another tool. As we already have `ss-tunnel` with `-L`, I presume it can be fairly easy to implement an `R`.

**Comment by madeye** [comment]
No plan for this.

Aactually it's hard to implement remote port forwarding in shadowsocks, since we never keep a long connection.
