### ISSUE TITLE
Help on setting up a ubuntu ^^CLIENT^^

### ISSUE THREAD

**Issue by imacks** [shadowsocks/shadowsocks-libev#1635]
I am tearing my hair out trying to setup Ubuntu server as the client. Is ss-redir and ss-tunnel the only things that I need to have a working connection? What about running the entire client as a docker image?

I am trying to run ss-redir with local address/port 0.0.0.0:12345, and ss-tunnel with local address/port 0.0.0.0:5353, both inside the alpine linux container. We expose these two ports using docker run, then modify the host etc/resolv.conf to listen to 127.0.0.1:5353, and modify iptables on host to route traffic to 127.0.0.1:12345.

But I get connection timeout or poisoned IPs when doing `nslookup xxxx.com 127.0.0.1 -port=5353`, and timeouts with `curl -L xxxx.com`

Here's my Dockerfile (alpine-shadowsocks:3.0.8 is a build on alpine linux...it should be okay since the server runs off it too):

```
FROM alpine-shadowsocks:3.0.8

ENV SERVER_IP="" \
	SERVER_PORT="52100" \
	PSK="" \
	CRYPTO="aes-256-cfb" \
	REDIR_LOCAL_PORT="10850" \
	REDIR_LOCAL_ADDRESS="0.0.0.0" \
	REDIR_TIMEOUT="60" \
	REDIR_RELAY_MODE="tcp_and_udp" \
	REDIR_IPV6_PRIORITY="false" \
	TUNNEL_LOCAL_PORT="5353" \
	TUNNEL_LOCAL_ADDRESS="0.0.0.0" \
	TUNNEL_TIMEOUT="10" \
	TUNNEL_RELAY_MODE="tcp_and_udp" \
	TUNNEL_IPV6_PRIORITY="false" \
	TUNNEL_NETADAPTER_NAME="*" \
	TUNNEL_DNS_SERVER="8.8.8.8:53" \
	ENABLE_PORT_REUSE="true" \
	MAX_TRANSMIT_UNIT="" \
	ENABLE_MULTIPATH_TCP="false" \
	RUNAS="ssclient" 

# 680 is just arbitrary
RUN addgroup -g 680 shadowsocks && \
	adduser -D -G shadowsocks -s /bin/false -u 680 -h /home/$RUNAS $RUNAS

ADD rootfs /
```
Rootfs contains scripts that launches ss-tunnel and ss-redir using these environment variables when the container starts...

It seems strange that we have such nice clients on consumer platforms but only tedious instructions on the very os that it is developed on.

**Comment by madeye** [comment]
If you're looking for a transparent proxy solution, please figure out how to setup iptables rules first.

Please look into the `ss-nat` script for more details.

**Comment by imacks** [comment]
yes I have examined ss-nat. Without bothering with udp, here is the script executed on the host. Am I doing something wrong? My ss-redir listens on 10800

```
# create new chain under nat: SHADOWSOCKS
iptables -t nat -N SHADOWSOCKS

# ignore server
iptables -t nat -A SHADOWSOCKS -d xxx -j RETURN

# do not proxy private ip ranges
iptables -t nat -A SHADOWSOCKS -d 0.0.0.0/8 -j RETURN
iptables -t nat -A SHADOWSOCKS -d 10.0.0.0/8 -j RETURN
iptables -t nat -A SHADOWSOCKS -d 127.0.0.0/8 -j RETURN
iptables -t nat -A SHADOWSOCKS -d 169.254.0.0/16 -j RETURN
iptables -t nat -A SHADOWSOCKS -d 172.16.0.0/12 -j RETURN
iptables -t nat -A SHADOWSOCKS -d 192.168.0.0/16 -j RETURN
iptables -t nat -A SHADOWSOCKS -d 224.0.0.0/4 -j RETURN
iptables -t nat -A SHADOWSOCKS -d 240.0.0.0/4 -j RETURN

# everything else redir to localhost:10800
iptables -t nat -A SHADOWSOCKS -p tcp -j REDIRECT --to-ports 10800

iptables -t nat -A OUTPUT -p tcp -j SHADOWSOCKS
```

**Comment by madeye** [comment]
```
iptables -t nat -A SHADOWSOCKS -p tcp -j REDIRECT --to-ports 10800
```

This line only works if your `ss-redir` runs on the same host.

Since you're using docker, please try `PREROUTING` rules and set your docker as a router first.

You may try https://github.com/shadowsocks/openwrt-shadowsocks instead, as it's not easy to set up routes and NAT rules manually.

**Comment by yangxuan8282** [comment]
You didn't give your full scripts content, so not sure what caused your issues, but dockerize ss client is possible, just use `ss-redir` and `ss-nat` is enough.   
You can check this [repo](https://github.com/yangxuan8282/ss-docker/blob/master/ss-client/amd64/Dockerfile), basically it' based on shadowsocks official Dockerfile, add obfs plugins and iptables. With this [docker-compose.yml](https://github.com/yangxuan8282/ss-docker/blob/master/docker-compose/ss-client/docker-compose.yml), simply edit your ss server info then `docker-compose up` then the transparent proxy is running, as easy as on other platform. And use scripts like [create_ap](https://github.com/oblique/create_ap) you can share your relay with other devices.    
You may need to run this once:

```
sudo sysctl net.ipv4.ip_forward=1
```

before start the container, and ensure udp forward is enable on your ss server. I'm using raspbian, seems it's enable forward by default, so I didn't include it in container.

**Comment by imacks** [comment]
Thanks. I'll try it out and share my work...if it work...
