### ISSUE TITLE
docker not open udp port

### ISSUE THREAD

**Issue by qjebbs** [shadowsocks/shadowsocks-libev#1636]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
v3.0.8 docker installation following README.md

### What operating system are you using?
openwrt

### What did you do?
openwrt redirect dns resolving to ss

### What did you expect to see?
DNS OK

### What did you see instead?
DNS failed

### What is your config in detail (with all sensitive info masked)?
Irrelevant

### How you solve it ?
docker run -d -e METHOD=aes-256-cfb -e PASSWORD=9MLSpPmNt -p 8388:8388/tcp -p 8388:8388/udp --restart always shadowsocks-libev

**Comment by madeye** [comment]
It's expected. UDP relay is disabled by default in shadowsocks-libev.

**Comment by qjebbs** [comment]
Got it. but why? Is UDP easier to detect, should I disable UDP? But I need it to relay QUIC connections.
Thanks for your time.
