### ISSUE TITLE
修改README文件

### ISSUE THREAD

**Issue by Shadowhack0419** [shadowsocks/shadowsocks-libev#1637]
请求删除Ubuntu/Debian依赖安装中的libsodium-dev和mbedtls-dev，前者安装后再安装最新libsodium会编译错误，后者不存在此deb包，这两者教程中已注明从源码安装。另外CentOS请注明yum无法直接安装udns，请自行从repo安装。

_Sent from my Xiaomi MI 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by hosiet** [comment]
Please open a PR for it and we will see if the new words could be easier to understand. Anyway, installing from PPA/Official repo is always recommended.
