### ISSUE TITLE
some problem

### ISSUE THREAD

**Issue by jcyongqin** [shadowsocks/shadowsocks-libev#1638]
When I open ss-server and check its status. It show as down.
>This system doesn't provide enough entropy to quickly generate high-quality random numbers.
>Installing the rng-utils/rng-tools or haveged packages may help.
>On virtualized Linux environments, also consider using virtio-rng.
>The service will not start until enough entropy has been collected.
>
### and ###
>**server recv: Connection reset by peer**

**Comment by lixingcong** [comment]
Q1:
https://github.com/shadowsocks/shadowsocks-libev/issues/1384

Q2:
https://github.com/shadowsocks/shadowsocks-libev/issues/282
https://github.com/shadowsocks/shadowsocks-libev/issues/1536
