### ISSUE TITLE
http://shadowsocks.org/debian/1D27208A.gpg 404

### ISSUE THREAD

**Issue by highcapital** [shadowsocks/shadowsocks-libev#1639]
The gpg file is no longer available at the location:
http://shadowsocks.org/debian/1D27208A.gpg

Any fixes? Thanks

**Comment by madeye** [comment]
For Ubuntu, please follow the instruction in README and use PPA instead.

For Debian, just type `apt install shadowsocks-libev`, as shadowsocks-libev is already in official repo.

**Comment by highcapital** [comment]
Thanks  @madeye  , the instruction in README worked for me. 
Shouldn't have followed some old posts on Internet ...
