### ISSUE TITLE
大量vps公网端口连接ss端口

### ISSUE THREAD

**Issue by xxmali** [shadowsocks/shadowsocks-libev#1643]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
3.0.8

### What operating system are you using?
Ubuntu 14.04

### What did you see instead?
假设{ip}是vps的公网ip，ss端口是1020。
朋友在用小米手机，已让他关闭迅雷加速引擎。

今天出现大量{ip}的其它端口连接{ip}:1020，高峰期12879个tcp连接.
netstat命令看是这样的，iptables显示上传了8G流量，下载300M.
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
...
tcp        0      0 {ip}:1020     {ip}:44861    TIME_WAIT   -
tcp        0      0 {ip}:1020     {ip}:44862    TIME_WAIT   -
tcp        0      0 {ip}:1020     {ip}:44863    TIME_WAIT   -
...
tcp        0      0 {ip}:44864    {ip}:1020     TIME_WAIT   -
tcp        0      0 {ip}:44865    {ip}:1020     TIME_WAIT   -
tcp        0      0 {ip}:44866    {ip}:1020     TIME_WAIT   -
...
tcp        0      0 {ip}:1020     client:50355    FIN_WAIT2   -
tcp        0      1 {ip}:1020     client:50348    FIN_WAIT1   -
tcp        0      1 {ip}:1020     client:50351    FIN_WAIT1   -
/var/log/syslog大量下面的信息
Aug 22 08:11:11 my /usr/local/bin/ss-server[1255]: failed to handshake with {ip}: invalid length for ipv4 address
Aug 22 08:11:11 my /usr/local/bin/ss-server[1255]: remote recv: Connection reset by peer
日志持续了2min.
他说当时在上班没玩手机。奇怪的是为什么会有大量的本地端口作为Foreign Address连ss端口？

**Comment by madeye** [comment]
```
Aug 22 08:11:11 my /usr/local/bin/ss-server[1255]: failed to handshake with {ip}: invalid length for ipv4 address
```

What's the `(ip)` here?

**Comment by xxmali** [comment]
vps的公网ip.

**Comment by madeye** [comment]
If the `(ip)` of `failed to handshake with {ip}` is your VPS's IP, it means there is some misconfigured or malicious software running on your VPS.

I don't think it's related to shadowsocks-libev itself. Double check your VPS and configuration.

**Comment by xxmali** [comment]
我检查没有可疑进程，/etc/rc*.d也没有可以自启项。我的vps都用两年了，就给朋友个号后出现这情况，而且不只一次出现，每隔几天的早晨8点左右发生，给他换过端口，然后新端口依然这样。。
iptables 统计的8G入口流量可能是公网其它端口到ss端口的流量。
netstat显示公网其它端口到ss端口的tcp连接数非常大，上万了，而客户端到ss端口的连接数却很少，只有几个。
想问下大佬，假设vps没有恶意程序的情况下，客户端的上网行为有没有可能导致出现这种奇怪的tcp连接现象？
我的理解，客户端流量进ss端口后会通过其它端口连接目的网站，再通过ss端口传给客户端。这样不可能出现下面的连接呀
...
tcp 0 0 {ip}:1020 {ip}:44861 TIME_WAIT -
tcp 0 0 {ip}:1020 {ip}:44862 TIME_WAIT -
tcp 0 0 {ip}:1020 {ip}:44863 TIME_WAIT -
...
tcp 0 0 {ip}:44864 {ip}:1020 TIME_WAIT -
tcp 0 0 {ip}:44865 {ip}:1020 TIME_WAIT -
tcp 0 0 {ip}:44866 {ip}:1020 TIME_WAIT -

**Comment by dongdongdu** [comment]
仅仅说些大体建议啊~
1. ssh 改22为其他端口
2. fail2ban 启动 记得改ssh配置为新端口
3. 安装 ufw， 仅仅开放 ssh 和 ss 端口
4. ss配置里的 timeout 设置低些比如 60；   密码、端口再修改一遍； 

看看能否先排除VPS被攻破，然后再看看是否ss的问题， 更新到最新版~ 

实在不行，VPS 重新装吧， 一般我会备份个初始镜像~

**Comment by paperbag** [comment]
我喜欢用 `lsof -i` 查看网络连接，`netstat` 看不到具体的进程，难受。

**Comment by lunarjoll** [comment]
会不会是tor

**Comment by paperbag** [comment]
可以用 `lsof -i` 看下44864，44865 那几个端口是哪个进程在用啊。

**Comment by xxmali** [comment]
vps拿到手就改ssh端口了。lsof命令第一次见，学到了，谢谢。目前已重刷手机rom，重装vps系统，暂未复现。
