### ISSUE TITLE
ubuntu cannot modify "/etc/shadowsocks-libev/config.json"      

### ISSUE THREAD

**Issue by angoen** [shadowsocks/shadowsocks-libev#1649]
operating system: | Ubuntu 16.04 x86_64
follow the tutorial installation shadowsock-libev
input：sudo vim /etc/shadowsocks-libev/config.json Error occurred："/etc/shadowsocks-libev/config.json" E212: Can't open file for writing
but,i'm is root
root@localhost:~# this is root?
command as:sudo vim /etc/shadowsocks-libev/config.json

**Comment by gongzelong0718** [comment]
Could you share the way to fix it?
