### ISSUE TITLE
为什么我用supervisor不能正确开机自启动ss-libev

### ISSUE THREAD

**Issue by akatong** [shadowsocks/shadowsocks-libev#1650]
Debian 8 x86，
手动输入ss-server -c ./shadowsocks-libev/config.json -f proxy.pid -u，可以正常运行。

而用supervisor，自启动失败，使用命令：supervisorctl status，查看状态显示：
ssuser_1                         FATAL     Exited too quickly (process log may have details)

我的supervisord.conf配置如下：
[program:ssuser_1]
command=ss-server -c ./shadowsocks-libev/config.json -u
autostart=true
autorestart=true
startretries = 3
user=root
log_stderr=true
logfile=/var/log/ssuser1.log

查看supervisord.log，三次启动失败，cat /tmp/supervisord.log
 INFO exited: ssuser_1 (exit status 255; not expected)
 INFO spawned: 'ssuser_1' with pid 807
 INFO exited: ssuser_1 (exit status 255; not expected)
 INFO spawned: 'ssuser_1' with pid 808
 INFO exited: ssuser_1 (exit status 255; not expected)
 INFO gave up: ssuser_1 entered FATAL state, too many start retries too quickly

ss配置文件：（路径： ./shadowsocks-libev/config.json）
 {
    "server":"0.0.0.0",
    "server_port":2000,
    "password":"xxxxxxxxx",
    "timeout":"5",
    "method":"chacha20-ietf-poly1305",
    "mode":"tcp_and_udp"
}

实在不解。请求帮助。

******************************************************************************************
非常感谢大家的帮助，经过多方修改，发现将原来kcptun的include跟自启动配置命令换的位置。即可恢复正常。

![image](https://user-images.githubusercontent.com/20764318/29749920-eb667c9a-8b68-11e7-8558-cc4113ad2cc6.png)

**Comment by Amankwah** [comment]
ss-server用绝对路径试试？或者怀疑配置文件有误。

**Comment by tony1016** [comment]
用绝对路径

2017年8月27日 下午3:53，"Amankwah" <notifications@github.com>写道：

**Comment by akatong** [comment]
我先通过type查询绝对路径，得到
ss-server is /usr/local/bin/ss-server

修改supervisord.conf为：
[program:ssuser_1]
command= /usr/local/bin/ss-server -c ./shadowsocks-libev/config.json -u
autostart=true
autorestart=true
startretries = 3
user=root

重启服务器，查询状态，问题依旧存在。提示：
ssuser_1                         FATAL     Exited too quickly (process log may have details)

**Comment by tennfy** [comment]
配置文件路径也用绝对路径试试

**Comment by buggysoul** [comment]
Correct the ss configuration file path with absolute path and retry. Here's mine, leaving most settings default,  simple but works.

```
[program:shadowsocks]
command=/usr/local/bin/ss-server -c /etc/shadowsocks-libev/ss_server.json -f /etc/shadowsocks-libev/ss.pid -u -v
user=alphax
priority=2
stderr_logfile=/etc/shadowsocks-libev/supervisor.stderr.log
stdout_logfile=/etc/shadowsocks-libev/supervisor.stdout.log
```

**Comment by Y2k38** [comment]
实际上，你需要重新启动supervisor
