### ISSUE TITLE
How to monitor ss service  from librenms

### ISSUE THREAD

**Issue by debiansid** [shadowsocks/shadowsocks-libev#1651]
### What version of shadowsocks-libev are you using?
3.0.8

### What operating system are you using?
Alpine Linux/Ubnt EdgeOS

### What did you do?
trying to monitor from librenms

### What did you expect to see?
add service monitor from librenms and check if service is up.

### What did you see instead?
Have no idea how

**Comment by madeye** [comment]
Closed due to inactivity.
