### ISSUE TITLE
ss-local could no connect to ss-server (but windows shadowsocks could connect to )

### ISSUE THREAD

**Issue by kevinzu007** [shadowsocks/shadowsocks-libev#1652]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
v3.08
git clone  https://github.com/shadowsocks/shadowsocks-libev.git

### What operating system are you using?
centos 7 x64

### What did you do?
cd /usr/local/src
git clone  https://github.com/shadowsocks/shadowsocks-libev.git
cd shadowsocks-libev/
git submodule update --init --recursive
yum install gettext gcc autoconf libtool automake make asciidoc xmlto udns-devel libev-devel
yum  remove libsodium-devel
export LIBSODIUM_VER=1.0.13
wget https://download.libsodium.org/libsodium/releases/libsodium-$LIBSODIUM_VER.tar.gz
tar xvf libsodium-$LIBSODIUM_VER.tar.gz
pushd libsodium-$LIBSODIUM_VER
/configure --prefix=/usr && make
sudo make install
popd
sudo ldconfig
export MBEDTLS_VER=2.5.1
wget https://tls.mbed.org/download/mbedtls-$MBEDTLS_VER-gpl.tgz
tar xvf mbedtls-$MBEDTLS_VER-gpl.tgz
pushd mbedtls-$MBEDTLS_VER
make SHARED=1 CFLAGS=-fPIC
sudo make DESTDIR=/usr install
popd
sudo ldconfig
./autogen.sh && ./configure && make
sudo make install

### What did you expect to see?
ss-local connect to ss-server

### What did you see instead?
windows shadowsocks can connect to ss-server
but ss-local can not connect to ss-server ，ss-server no log output

### What is your config in detail (with all sensitive info masked)?
ss-server -c  ss-server.json 
cat ss-server.json 
{
    "server":"0.0.0.0",
    "server_port":7xxx,
    "password":"12345678x",
    "timeout":300,
    "method":"aes-256-cfb",
    "verbose": 1
}

ss-local -c ss-local.json
cat  ss-local.json 
{
    "server":"47.52.xx.xx",
    "server_port":7xxx,
    "password":"12345678x",
    "local_address":"127.0.0.1",
    "local_port":1080,
    "timeout":300,
    "method":"aes-256-cfb",
    "fast_open":false,
    "workers":1
}

#==========================
环境：
阿里云香港vps，centos7.4 x64，经典网络，已开放阿里云规则，linux防火墙默认未开启，selinux默认disabled，shadowsocks3.08官方编译安装
(
uname -a
Linux xgvps 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
)

现象1：
windows server 2008 R2 x64 下，客户端shadowsocks 4.05，可以正常连接香港vps，可以正常上网

现象2：
centos 7 x64，
shadowsocks3.08官方编译安装，ss-local 连接服务器，无错误提示，香港server端无任何连接日志信息（正常情况下是有的），浏览器设置代理不能上网，用wireshark抓包香港ip，完全没有数据，香港vps也无数据日志，但是telnet 香港ip ss-server端口 ，香港服务器有日志反映

现象3：
ubuntu 16.04（elementary os 0.41），
$ uname -a
Linux Pad-S5-2nd-Gen 4.10.0-32-generic #36~16.04.1-Ubuntu SMP Wed Aug 9 09:19:02 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
现象同2一样，不能上网

现象4：
香港vps本机ss-local连接本机ss-server侦听端口一样没有反映

以上可以判断香港服务器是没有问题的，windows客户端没有问题，linux客户端，不论是centos下，还是ubutnu下都不行，什么原因？
ss-local完全没有连接服务器的动作（已排除selinux、客户端防火墙、国家防火墙相关问题）

**Comment by kevinzu007** [comment]
telnet  47.52.xx.xx  7xxx  , and quit
------ss-server log:
 2017-08-28 16:11:35 INFO: accept a connection
 2017-08-28 16:11:42 INFO: server_recv close the connection
 2017-08-28 16:11:42 INFO: current server connection: 0

ss-local -c ss-local.json ，nothing out put（on ss-server log）

**Comment by kevinzu007** [comment]
when browser
ss-local log :
 2017-08-29 11:13:43 INFO: udp assc request accepted
 2017-08-29 11:14:13 INFO: udp assc request accepted

ss-server log:  nothing

**Comment by kevinzu007** [comment]
browser status bar ：
Performing a TLS handshake to  www.xxx.com

**Comment by madeye** [comment]
Make sure you're using ss-local as a SOCKS5 proxy, not a HTTP proxy.

**Comment by kevinzu007** [comment]
how to sure?
mine:
firefox 55  --> connection settings --> Manual proxy configuration --> 
HTTP Proxy: ip x.x.x.x Port : 1080
v   use this proxy server for all protocols
v  Proxy DNS when using SOCKS v5

**Comment by kevinzu007** [comment]
can i give my server's username and password to you ? you try it

**Comment by Mr-indescribable** [comment]
@kevinzu007  https://5socks.net/Manual/browser_en.html

**Comment by kevinzu007** [comment]
o ，shit，this is ok，please allow me to kiss u once
thank u very mush @Mr-indescribable and @madeye 

otherwise：
why ss-local donot support  http proxy？
it Can be used before ？
in  linux , wget could not use socks proxy, very inconvenient！

**Comment by kevinzu007** [comment]
ok，tks
是我 “孤陋寡闻”
谢谢了！
@madeye @Mr-indescribable

**Comment by kevinzu007** [comment]
socks5 to http_proxy
http://droidyue.com/blog/2016/04/04/set-shadowsocks-proxy-for-terminal/index.html

**Comment by cyqsimon** [comment]
I have already wasted a whole week troubleshooting this issue... Finally found this post and yeah, it seems to work now. Thanks so so much to all
