### ISSUE TITLE
Shadowsocks can't auto start after router reboot

### ISSUE THREAD

**Issue by Balanky** [shadowsocks/shadowsocks-libev#1653]
### What version of shadowsocks-libev are you using?
3.0.8

### What operating system are you using?
openwrt

### What did you do?
router reboot

### What did you expect to see?
shadowsocks auto start after router reboot and works fine.

### What did you see instead?
Shadowsocks does not  start properly after router reboot. You should issue command "/etc/init.d/shadowsocks restart" to get it works.

### What is your config in detail (with all sensitive info masked)?
config servers
        option auth '0'
        option fast_open '1'
        option server 'xxx.xxx.xxx.xxx.'
        option server_port '443'
        option timeout '60'
        option password '*************'
        option encrypt_method 'chacha20-ietf-poly1305'
        option plugin 'obfs-local'
        option alias 'VPS1'
        option plugin_opts 'obfs=http;obfs-host=www.baidu.com'

Here is the LOG:
Mon Aug 28 20:43:30 2017 kern.info ss-redir[1098]: tcp port reuse enabled
Mon Aug 28 20:43:30 2017 kern.info ss-redir[1098]: UDP relay enabled
Mon Aug 28 20:43:30 2017 kern.err ss-redir[1098]: [udp] getaddrinfo: ai_family not supported
Mon Aug 28 20:43:30 2017 kern.err ss-redir[1098]: [udp] bind() error
Mon Aug 28 20:43:30 2017 kern.info ss-redir[1105]: initializing ciphers... chacha20-ietf-poly1305
Mon Aug 28 20:43:30 2017 kern.info ss-redir[1105]: tcp port reuse enabled
Mon Aug 28 20:43:30 2017 kern.info ss-redir[1105]: UDP relay enabled
Mon Aug 28 20:43:30 2017 kern.err ss-redir[1105]: [udp] getaddrinfo: ai_family not supported
Mon Aug 28 20:43:30 2017 kern.err ss-redir[1105]: [udp] bind() error

**Comment by wongsyrone** [comment]
> Mon Aug 28 20:43:30 2017 kern.err ss-redir[1098]: [udp] getaddrinfo: ai_family not supported
Mon Aug 28 20:43:30 2017 kern.err ss-redir[1098]: [udp] bind() error

确保你固件的内核支持ipv6，或者不要绑定v6监听

**Comment by Balanky** [comment]
支持IPv6的

**Comment by wongsyrone** [comment]
没猜错的话应该是在

https://github.com/shadowsocks/shadowsocks-libev/blob/ede744ae7c79dfc91e93c3eca31b00fd6f951fc6/src/udprelay.c#L394

报错的。

你可以试试LEDE，C库选择最新musl或者uClibc-ng

**Comment by madeye** [comment]
Closed due to inactivity.
