### ISSUE TITLE
Memory Leakage Problem

### ISSUE THREAD

**Issue by fsgmhoward** [shadowsocks/shadowsocks-libev#1654]
### What version of shadowsocks-libev are you using?

Version: 3.0.8+ (custom build, dev version, forgot at which commit but I will confirm it with 
3.0.8-28-g9c26318 which is the latest commit)

### What operating system are you using?

I am running ss-libev on Ubuntu Xenial LTS, using ss-manager to coordinate multiple servers.

### What did you do?

Using ss-manager to run multiple servers

### What did you expect to see?

A consistant memory usage

### What did you see instead?

In 6 days' time, memory consumed by each ss-server process increases from about 25000/2700/2400 (virt/res/shr) to 32000/10000/1000 and they drain all available memory of the server which causes it to hang totally.

### What is your config in detail (with all sensitive info masked)?

No config 'coz I just use command to add server. ss-manager is started without any parameters.

Sorry I didn't follow the template at first because my Github client didn't show the placeholder.

**Comment by madeye** [comment]
`10000` means 10MB memory usage, which is expected.

I don't think it's a problem, unless you started hundreds of ss-server on one server.

**Comment by fsgmhoward** [comment]
If you say like this, when I run a SINGLE server on a low end box with 64MiB RAM, all available memory will be drained in few weeks' time easily and forced the server to hang. This is no longer considered to be lightweighted.

Anyway thanks for the response. I will see whether I can figure out the problem by myself.

**Comment by madeye** [comment]
1. 10MB memory usage of ss-server is expected, when the workload become stable. It should not grow to 64MB after days of usage.
2. To verify if there is memory leak, you can try run ss-server with valgrind.
