### ISSUE TITLE
Connection reset by peer on specific resource

### ISSUE THREAD

**Issue by GreenVine** [shadowsocks/shadowsocks-libev#1657]
Hello,

I was trying to set up a server in mainland China to access the resources that only available for mainlanders. However, there are certain resources have their connections reset (stuck on the HTTP 206 Partial Content).

### What version of shadowsocks-libev are you using?
shadowsocks-libev 3.0.8

### What operating system are you using?
CentOS 7.2 / Ubuntu 16.04

### What did you do?
To replicate the issue, choose any video from bilibili.com, e.g. https://www.bilibili.com/video/av7531383/.

The browser will send a request to CDN to fetch FLV video resource, the sample URL is similar to:

```
Request URL:https://cn-gdfs4-dx-v-01.acgvideo.com/vg5/d/ec/12322682-1.flv?expires=1504196400&platform=pc&ssig=SObsrvD9F_T1_wKIJmHwBg&oi=1998000233&nfa=iKQJtLw3Fy5f05Q/mDvFYw==&dynamic=1&hfa=2073771533&hfb=Yjk5ZmZjM2M1YzY4ZjAwYTMzMTIzYmIyNWY4ODJkNWI=
Request Method:GET
Status Code:206 Partial Content
```

This issue persists on the fresh installations of multiple OSes, as well as multiple data centers in mainland China.

### What did you expect to see?
A working example (also tested on other proxy providers) is the aforementioned request will download a complete video (at least larger than 4MB).

### What did you see instead?
The request hangs when the download reaches exactly 4MB. Occasionally, the server-side will return the message stating "connection reset by peer".

### What is your config in detail (with all sensitive info masked)?
```json
{
        "server":"0.0.0.0",
        "server_port": 41234,
        "local_address":"127.0.0.1",
        "local_port":1080,
        "password":"removed",
        "timeout":300,
        "method":"aes-256-cfb",
        "fast_open":false,
        "dns_ipv6": false
}
```

Cheers
GreenVine

**Comment by chenhw2** [comment]
Tested, and it works.
```
ss-v3.0.8
obfs-v0.0.3
```

```
ss-server -p 55555 -m aes-128-gcm -k removed \
    -d 119.29.29.29 -d 223.6.6.6 \
    --plugin obfs-server --plugin-opts 'obfs=http'
```

**Comment by GreenVine** [comment]
Apologise, however this issue is limited to bilibili.com only. I believe they intentionally close the socket when an IP from cloud computing service provider is detected.

**Comment by chenhw2** [comment]
@GreenVine  Test URL is: ```https://www.bilibili.com/video/av7531383/``` as you provided.
