### ISSUE TITLE
ss-server 能代理 QUIC 协议吗？

### ISSUE THREAD

**Issue by pexcn** [shadowsocks/shadowsocks-libev#1660]
在 windows 下用 chrome + switchyomega + wireshark 抓包看了下，quic 是直连的喔？

**Comment by madeye** [comment]
`ss-server` of course supports QUIC as it's a UDP protocol.

**Comment by pexcn** [comment]
谢谢.

**Comment by PeachSix** [comment]
ss-server启用UDP转发的情况下，访问一个使用QUIC协议的网站，发现实际为http2协议，不使用代理后为正常的quic协议。请问如何在开启代理的情况下，也使用QUIC协议。
