### ISSUE TITLE
ss-server not return atyp 3 response

### ISSUE THREAD

**Issue by kyze8439690** [shadowsocks/shadowsocks-libev#1663]
### What version of shadowsocks-libev are you using?

3.0.8

### What operating system are you using?

ubuntu

### What did you do?

In the client side, I encapsulate the target **domain**(**not ipv4/ipv6 format address**) in socks5 format, and send **udp** data to `ss-local` socks5 port, ss-local can recognize the correct target domain and send it to `ss-server` side.

But when I get udp response from `ss-local`, the target domain has been replaced with a ipv4 address, which will cause my validate process failed.

### What did you expect to see?

If I send a socks5 udp data to `ss-local` with `atyp` is `3`, `ss-local` should return a udp response with `atyp` is 3 also.

### What did you see instead?

When I get udp response from `ss-local`, the target domain has been replaced with a ipv4 address, which will cause my validate process failed.

### Something more

It seem that the issue is in `udprelay.c`, https://github.com/shadowsocks/shadowsocks-libev/blob/master/src/udprelay.c#L197, the construct_udprelay_header only handle ipv4 and ipv6, but not domain type.

**Comment by madeye** [comment]
Not actually.

As per https://github.com/shadowsocks/shadowsocks-libev/blob/master/src/udprelay.c#L762, ss-server only reconstructs the header for responses that the `af` equals `AF_INET` or `AF_INET6".

**Comment by kyze8439690** [comment]
So it doesn't meet the rfc standard.

**Comment by madeye** [comment]
@kyze8439690 I think you misunderstood the code. Current implementation always send back the addr header according to the RFC
