### ISSUE TITLE
Use ss-redir udp replay on Android

### ISSUE THREAD

**Issue by misakayao** [shadowsocks/shadowsocks-libev#1667]
### What version of shadowsocks-libev are you using?
3.0.8

### What operating system are you using?
Android 7.1.1

### What did you do?
I want to use Android phone implement the function of router, so I'm going to use ss-redir to implement udp relay

### What did you expect to see?
udp packet can relay to vps server

### What did you see instead?
udp packet never go to ss-redir,no udp replay log print

#### ss-redir

`"-v", "-u",
                "-b", "0.0.0.0",
                "-l", "1081",
                "-t", "600",
                "-c",  "path of ss-redir.conf"`

#### iptable
* TCP
```
iptables -t nat -N SHADOWSOCKS_TCP    
iptables -t nat -A SHADOWSOCKS_TCP -d serviceIP -j RETURN    
iptables -t nat -A SHADOWSOCKS_TCP -d 0.0.0.0/8 -j RETURN    
iptables -t nat -A SHADOWSOCKS_TCP -d 10.0.0.0/8 -j RETURN
iptables -t nat -A SHADOWSOCKS_TCP -d 169.254.0.0/16 -j RETURN
iptables -t nat -A SHADOWSOCKS_TCP -d 172.16.0.0/12 -j RETURN
iptables -t nat -A SHADOWSOCKS_TCP -d 127.0.0.0/8 -j RETURN
iptables -t nat -A SHADOWSOCKS_TCP -d 192.168.0.0/16 -j RETURN
iptables -t nat -A SHADOWSOCKS_TCP -d 10.8.0.0/16 -j RETURN
iptables -t nat -A SHADOWSOCKS_TCP -d 224.0.0.0/4 -j RETURN
iptables -t nat -A SHADOWSOCKS_TCP -d 240.0.0.0/4 -j RETURN
iptables -t nat -A SHADOWSOCKS_TCP -d 192.168.0.0/16 -j RETURN
iptables -t nat -A SHADOWSOCKS_TCP -p tcp -j REDIRECT --to-ports 1081
iptables -t nat -A PREROUTING  -p tcp -j SHADOWSOCKS_TCP
```
* UDP
```
iptables -t mangle -N SHADOWSOCKS_UDP
iptables -t mangle -A SHADOWSOCKS_UDP -d 0.0.0.0/8 -j RETURN    
iptables -t mangle -A SHADOWSOCKS_UDP -d 10.0.0.0/8 -j RETURN
iptables -t mangle -A SHADOWSOCKS_UDP -d 169.254.0.0/16 -j RETURN
iptables -t mangle -A SHADOWSOCKS_UDP -d 172.16.0.0/12 -j RETURN
iptables -t mangle -A SHADOWSOCKS_UDP -d 127.0.0.0/8 -j RETURN
iptables -t mangle -A SHADOWSOCKS_UDP -d 192.168.0.0/16 -j RETURN
iptables -t mangle -A SHADOWSOCKS_UDP -d 10.8.0.0/16 -j RETURN
iptables -t mangle -A SHADOWSOCKS_UDP -d 224.0.0.0/4 -j RETURN
iptables -t mangle -A SHADOWSOCKS_UDP -d 240.0.0.0/4 -j RETURN
iptables -t mangle -A SHADOWSOCKS_UDP -d 192.168.0.0/16 -j RETURN
ip rule add fwmark 0x01/0x01 table 100
ip route add local 0.0.0.0/0 dev lo table 100
iptables -t mangle -A SHADOWSOCKS_UDP -p udp --dport 53 -j TPROXY --on-port 1081 --tproxy-mark 0x01/0x01
iptables -t mangle -A PREROUTING  -p udp -j SHADOWSOCKS_UDP
```
I use almost the same iptable as #1514 
and have tried both of ip rule / route in #1666 
and tried to set sysctl `net.ipv4.ip_forward=1`

Is there any possible for Android to use ss-redir udp replay?

**Comment by misakayao** [comment]
### Update:
When I change UDP iptables to REDIRECT(should be wrong way), such as:
#### 1. use ss-redir
```
iptables -t nat -A SHADOWSOCKS_TCP -p udp -j REDIRECT --to-ports 1080
iptables -t nat -A PREROUTING  -p udp -j SHADOWSOCKS_TCP
```
#### log:
```
09-05 15:53:55.927 14367-14367/? D/shadowsocks: [udp] server receive a packet
09-05 15:53:55.927 14367-14367/? D/shadowsocks: [udp] cache miss: 100.50.58.105:25650 <-> 192.168.43.106:7359
09-05 15:53:55.928 14367-14367/? E/shadowsocks: [udp] drop a message since frag is not 0, but 58
09-05 15:53:58.154 14367-14367/? D/shadowsocks: [udp] server receive a packet
09-05 15:53:58.154 14367-14367/? E/shadowsocks: [udp] invalid header with addr type 0
09-05 15:54:00.160 14367-14367/? D/shadowsocks: [udp] server receive a packet
09-05 15:54:00.160 14367-14367/? E/shadowsocks: [udp] invalid header with addr type 0
09-05 15:54:02.163 14367-14367/? D/shadowsocks: [udp] server receive a packet
09-05 15:54:02.163 14367-14367/? E/shadowsocks: [udp] invalid header with addr type 0
09-05 15:54:04.163 14367-14367/? D/shadowsocks: [udp] server receive a packet
09-05 15:54:04.164 14367-14367/? E/shadowsocks: [udp] invalid header with addr type 0
09-05 15:54:06.167 14367-14367/? D/shadowsocks: [udp] server receive a packet
09-05 15:54:06.167 14367-14367/? E/shadowsocks: [udp] invalid header with addr type 0
09-05 15:54:10.928 14367-14367/? D/shadowsocks: [udp] server receive a packet
09-05 15:54:10.928 14367-14367/? D/shadowsocks: [udp] cache miss: 100.50.58.105:25650 <-> 192.168.43.106:1040
09-05 15:54:10.928 14367-14367/? E/shadowsocks: [udp] drop a message since frag is not 0, but 58
```
Error occurs when udp replay `[udp] invalid header with addr type 0`

#### 2. use ss-tunnel(port 1153)
```
iptables -t nat -A SHADOWSOCKS_TCP -p udp -j REDIRECT --to-ports 1153
iptables -t nat -A PREROUTING  -p udp -j SHADOWSOCKS_TCP
```
#### log:
```
09-05 15:46:15.895 5324-5324/? D/shadowsocks: [udp] server receive a packet
09-05 15:46:15.895 5324-5324/? D/shadowsocks: [udp] cache hit: 8.8.8.8:53 <-> 192.168.43.106:7359
09-05 15:46:16.752 5324-5324/? D/shadowsocks: [udp] server receive a packet
09-05 15:46:16.752 5324-5324/? D/shadowsocks: [udp] cache miss: 8.8.8.8:53 <-> 192.168.43.106:52800
09-05 15:46:16.942 5324-5324/? D/shadowsocks: [udp] remote receive a packet
09-05 15:46:16.949 5324-5324/? D/shadowsocks: [udp] server receive a packet
```
log seems right,but DNS still can't  resolve properly

**Comment by zw963** [comment]
没看明白你的问题 ....

下面这篇文章也许对你有帮助, https://icymind.com/learn-from-gfw/

**Comment by misakayao** [comment]
@zw963 
我是想在Android平台上实现类似路由器的功能，为了能够实现加速功能就编译了ss-redir、ss-tunnel，但是通过设置iptables、ip rule以及ip router，没有办法实现UDP转发（UDP没有走到ss-redir里面），现在还不清楚是不是系统原因。

现在尝试使用dnsmasq将DNS转发到ss-tunnel，可以转发成功，但是DNS解析仍然存在问题，而且手机自带的2.5.1版本的dnsmasq存在单个 CPU100%占用的问题。

目前还在寻找可能的原因，如果不能解决下一步准备尝试将DNS的UDP REDIRECT到DNS2SOCKS上来

**Comment by baggiogogo** [comment]
只是用作解析dns吗，想法把dns改为tcp查询就可以了，ss-tunnel都不用开。
试试overture或者dns-forwarder

**Comment by misakayao** [comment]
目前，通过如下方案解决了这个问题：
> 1. 使用iptables在PREROUTING时将TCP redirct到ss-redir的1081端口
> 2. 在访问gfwlist中的网址时，DNS通过dnsmasq发送到DNS2SOCKS的端口5353
> 3. DNS2SOCKS将DNS包发送到ss-local的1080端口的socks5 server上

问题:
>1. 有没有类似DNS2SOCKS的工具或方法，可以将DNS查询直接转为TCP后再发送到ss-redir，从而不需要再额外开启ss-local？
>2. ss-tunnel在Android平台上使用时似乎没有起作用，日志输出始终是Update中写的那样，但是DNS仍然被污染

**Comment by baggiogogo** [comment]
iptables -t nat -N SHADOWSOCKS

iptables -t nat -A SHADOWSOCKS -d (服务器地址） -j RETURN
iptables -t nat -A SHADOWSOCKS -d 0.0.0.0/8 -j RETURN
iptables -t nat -A SHADOWSOCKS -d 10.0.0.0/8 -j RETURN
iptables -t nat -A SHADOWSOCKS -d 127.0.0.0/8 -j RETURN
iptables -t nat -A SHADOWSOCKS -d 169.254.0.0/16 -j RETURN
iptables -t nat -A SHADOWSOCKS -d 172.16.0.0/12 -j RETURN
iptables -t nat -A SHADOWSOCKS -d 192.168.0.0/16 -j RETURN
iptables -t nat -A SHADOWSOCKS -d 224.0.0.0/4 -j RETURN
iptables -t nat -A SHADOWSOCKS -d 240.0.0.0/4 -j RETURN
#iptables -t nat -A SHADOWSOCKS -d 100.100.2.138 -p tcp --dport 53 -j REDIRECT --to-port 1080
#iptables -t nat -A SHADOWSOCKS -d 108.61.10.10 -p tcp --dport 53 -j REDIRECT --to-port 1080
#iptables -t nat -A SHADOWSOCKS -d 8.8.8.8 -p tcp --dport 53 -j REDIRECT --to-port 1080
iptables -t nat -A SHADOWSOCKS -m set --match-set chnroute dst -j RETURN
iptables -t nat -A SHADOWSOCKS -p tcp -j REDIRECT --to-port 1080

iptables -t nat -A OUTPUT -p tcp -j SHADOWSOCKS
iptables -t nat -A PREROUTING -p tcp -j SHADOWSOCKS

自家用iptables,带#号的加不加无所谓，最后都会中外分流，加了（心理上）会感觉快一丢丢。
去看看overture这个软件，就在github，@madeye好像编译过安卓版本直接用就可以了，同时具备chinadns以及dnsmasq的功能，支持tcp查询。

这样的话，实际上只需开ss-redir和overture就可以了，甚至dnsmaq都不用开（当然开了搭配使用也无妨），可以去了解下overture先。

备选dns-forwarder，作用只是将dns转为tcp查询。

**Comment by tony1016** [comment]
我觉得你们为了解决DNS问题好麻烦，中科大DNS自带无污染和国内外分流，杠杠的

**Comment by guliujian** [comment]
pdnsd也都可以把dns转为tcp查询

2017年9月7日 01:49，"misakayao" <notifications@github.com>写道：

**Comment by pexcn** [comment]
国内的 dns 怎么可能无污染？

**Comment by misakayao** [comment]
这几天又研究了一下，发现还是目前这样解决比较稳妥
1、Android手机开启热点之后会自动开启dnsmasq进程，所以直接用dnsmasq进行分流最简单直接，当然对dnsmasq进行配置必须在root的前提下
2、通过将DNS转为TCP之后，需要在iptables中OUTPUT进行REDIRECT，但是这样会增加在程序未开启时不能够正常上网的风险，所以暂时不使用这个方法
