### ISSUE TITLE
cannot ssh to server after being connected to it (openwrt)

### ISSUE THREAD

**Issue by tbronchain** [shadowsocks/shadowsocks-libev#1672]
Hey guys,
I'm having an issue with shadowsocks on openwrt (actually more of an openwrt issue).
After being connected, it turns out that I am not able to ssh to my ss server anymore. I'm pretty sure that's an iptable rule to configure, but I cannot figure out what to do (and it seems the ip bypass list in the config part doesn't work).
Oh and, I understand this is an openwrt related issue, but it seems I cannot submit an issue on that project (https://github.com/shadowsocks/openwrt-shadowsocks), so any help on that would be highly appreciated!
Cheers.

related issue: https://github.com/shadowsocks/shadowsocks/issues/949
version used: shadowsocks libev 3.0.8-1, luci app shadowsocks 1.8.1-1, openwrt 15.05

**Comment by madeye** [comment]
Closed due to inactivity.
