### ISSUE TITLE
为什么开启kcptun速度反而变慢了？

### ISSUE THREAD

**Issue by onlyJinx** [shadowsocks/shadowsocks-libev#1679]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What did you do?
提高网速
Speed up the network

### What is your config in detail (with all sensitive info masked)?

Why open kcptun after the speed dropped

为什么用kcptun后网速不升反降？是配置出问题了吗？服务器参数是这个
./server_linux_amd64 -t "127.0.0.1:443" -l ":8838" -mode fast2

![dfdfdf](https://user-images.githubusercontent.com/21324835/30247502-e79904bc-9648-11e7-8bf2-de08b14836cd.png)

![default](https://user-images.githubusercontent.com/21324835/30247464-1d9d019a-9648-11e7-81e9-23cf72629074.png)

**Comment by boris1993** [comment]
建议到kcptun的issues里提问

**Comment by guliujian** [comment]
kcptun不一定能提高网速，取决于你的isp 你的isp对udp的限制，你的网络到服务器之间udp连接情况等等因素，kcptun不是万金油

2017年9月11日 14:56，"Boris Zhao" <notifications@github.com>写道：
