### ISSUE TITLE
ss_server-resolv.o: In function resolv_init': /shadowsocks-libev/src/resolv.c:165: undefined reference toares_set_servers_ports_csv'

### ISSUE THREAD

**Issue by ky0ncheng** [shadowsocks/shadowsocks-libev#1682]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
3.0.8

### What operating system are you using?

Ubuntu 16.04.3 LTS
4.12.1-041201-generic

### What did you do?
CC

### What is your config in detail (with all sensitive info masked)?
  CC       ss_server-resolv.o
resolv.c: In function ‘resolv_init’:
resolv.c:157:13: error: ‘ARES_OPT_NOROTATE’ undeclared (first use inthis function)
             ARES_OPT_NOROTATE | ARES_OPT_TIMEOUTMS | ARES_OPT_TRIES
             ^
resolv.c:157:13: note: each undeclared identifier is reported only once for each function it appears in
Makefile:1599: recipe for target 'ss_server-resolv.o' failed
make[2]: *** [ss_server-resolv.o] Error 1
make[2]: Leaving directory '/root/shadowsocks-libev/src'
Makefile:480: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/root/shadowsocks-libev'
Makefile:389: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by wongsyrone** [comment]
https://github.com/c-ares/c-ares/blob/cares-1_12_0/RELEASE-NOTES#L5

**Comment by ky0ncheng** [comment]
c-ares 1.13 is working.
Thx.

**Comment by debiansid** [comment]
My problem is Debian wheezy only support libc-ares2 1.9.1, not sure how to upgrade it coz it is mips.

**Comment by debiansid** [comment]
or it just needs >=1.12 to compile?

**Comment by ky0ncheng** [comment]
@debiansid In my another pc, try to compile again, this error occurred. 

  CCLD     ss-server
ss_server-resolv.o: In function `resolv_init':
/root/shadowsocks-libev/src/resolv.c:165: undefined reference to `ares_set_servers_ports_csv'
collect2: error: ld returned 1 exit status
Makefile:690: recipe for target 'ss-server' failed
make[2]: *** [ss-server] Error 1
make[2]: Leaving directory '/root/shadowsocks-libev/src'
Makefile:480: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/root/shadowsocks-libev'
Makefile:389: recipe for target 'all' failed
make: *** [all] Error 2
