### ISSUE TITLE
shadowsocks-libev V3.1.0 install fail

### ISSUE THREAD

**Issue by Lixian2** [shadowsocks/shadowsocks-libev#1688]
### What version of shadowsocks-libev are you using?

V3.1.0

### What operating system are you using?

CentOS7

### What did you do?

I want to set up my ss according to this blog（  https://teddysun.com/357.html）

It says that this method will automatically catch the latest ss-libev in github.

But I cannot install it. I could do it use the same way yesterday with the last version of ss-libev.

what should I do now?

many thanks

**Comment by tennfy** [comment]
As 3.1.0 uses libc-ares instead of libudns, and teddysun's script is still using libudns, so  it does not work now. Pls wait for update of the script or try other script.

**Comment by chenhw2** [comment]
U can use [docker](https://hub.docker.com/search/?isAutomated=0&isOfficial=0&page=1&pullCount=0&q=ss-obfs&starCount=0) as well.

**Comment by bigtan** [comment]
静态编译的脚本

https://gist.github.com/bigtan/9196c10a849b1cd27360b18636c65d77

**Comment by waeart** [comment]
@bigtan 请问编译完以后再如何操作？

**Comment by bigtan** [comment]
@waeart 用systemd做成系统服务呀。

**Comment by bigtan** [comment]
https://gist.github.com/bigtan/1997db1aad65ab9d1cd4d77c210af7b9

**Comment by waeart** [comment]
@bigtan 谢谢。
