### ISSUE TITLE
是否libev和obsf的fast open都需要打开？

### ISSUE THREAD

**Issue by tianlichunhong** [shadowsocks/shadowsocks-libev#1689]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
shadowsocks-libevv3.0.8，simple bofs0.0.3

### What operating system are you using?
centos 7.0

### What did you do?
libev的服务器配置如下
{
    "server":"XXXXXX", 
    "local_address": "127.0.0.1",
    "local_port":1080,
    "server_port":80,
    "password":"XXXXXXX",
    "timeout":600,
    "method":"chacha20-ietf-poly1305", 
    "fast_open": true,
    "nameserver":"8.8.8.8",
    "plugin":"obfs-server",
    "plugin_opts":"obfs=http; fast-open"

}

我只想知道，是否两个fast open都需要打开？如上面配置 "fast_open": true,和"plugin_opts":"obfs=http; fast-open"。

**Comment by iliuyuyang** [comment]
其实没差别，在obfs内使用--fast-open不过是将这个参数传递给ss-server，所以你开启其中一个也行，开两格也没影响。

**Comment by debiansid** [comment]
内核必须打开tfo 否则不会传输数据

**Comment by tianlichunhong** [comment]
内核必须打开tfo？原因能否说详细一些？另外告知如何打开？

**Comment by tianlichunhong** [comment]
知道怎么打开TFO了，如下：
以root权限执行一下命令
echo 3 > /proc/sys/net/ipv4/tcp_fastopen
在/etc/sysctl.conf中添加
net.ipv4.tcp_fastopen = 3
重启，然后查询是否已经打开，运行下面命令，如果 TCPFastOpenPassive 在增长，表示接受到了fast open的tcp连接：
grep '^TcpExt:' /proc/net/netstat | cut -d ' ' -f 91-96 | column -t
