### ISSUE TITLE
simple-obfs doesn't work when configured in .json file

### ISSUE THREAD

**Issue by Amankwah** [shadowsocks/shadowsocks-libev#1694]
### What version of shadowsocks-libev are you using?
shadowsocks-libev:
82694c8f19a9cc39f4a7647c9e8764e5cc5a39bd
simple-obfs:
2955a57624add482588b41fad68bbcd4c632fff5

### What operating system are you using?
CentOS 7

### What did you do?
add plugin and plugin-opts in shadowsocks' .json configure

### What did you expect to see?
obfscating works well

### What did you see instead?
ss-local -vc shadowsocks.json
 2017-09-19 01:16:50 INFO: plugin "/path/to/installed/simple-obfs/obfs-local" enabled
 2017-09-19 01:16:50 INFO: resolving hostname to IPv6 address first
 2017-09-19 01:16:50 INFO: initializing ciphers... xchacha20-ietf-poly1305
 2017-09-19 01:16:50 INFO: tcp port reuse enabled
 2017-09-19 01:16:50 INFO: udprelay enabled
 2017-09-19 01:16:50 INFO: udp port reuse enabled
 2017-09-19 01:16:50 INFO: listening at 0.0.0.0:8388

simple-obfs 0.0.3

  maintained by Max Lv <max.c.lv@gmail.com>

  usage:

    obfs-local

       -s <server_host>           Host name or IP address of your remote server.
       -p <server_port>           Port number of your remote server.
       -l <local_port>            Port number of your local server.
       --obfs <http|tls>          Enable obfuscating: HTTP or TLS (Experimental).
       --obfs-host <host_name>    Hostname for obfuscating (Experimental).

       [-a <user>]                Run as another user.
       [-f <pid_file>]            The file path to store pid.
       [-t <timeout>]             Socket timeout in seconds.
       [-c <config_file>]         The path to config file.
       [-n <number>]              Max number of open files.
       [-b <local_address>]       Local address to bind.

       [--fast-open]              Enable TCP fast open.
                                  with Linux kernel > 3.7.0.
       [--mptcp]                  Enable Multipath TCP on MPTCP Kernel.

       [-v]                       Verbose mode.
       [-h, --help]               Print this message.

 2017-09-19 01:16:50 ERROR: plugin service exit unexpectedly
 2017-09-19 01:16:50 INFO: closed gracefully

but it works well when i using in command line
ss-local -vc shadowsocks.json --plugin /path/to/installed/simple-obfs/obfs-local --plugin-opts "obfs=http;obfs-host=paper.people.com.cn"

### What is your config in detail (with all sensitive info masked)?
{
    "server":"0.0.0.0",
    "server_port":8080,
    "local_address":"0.0.0.0",
    "local_port":8388,
    "password":"passphrase",
    "timeout":300,
    "method":"xchacha20-ietf-poly1305",
    "fast_open":false,
    "reuse_port":true,
    "mode":"tcp_and_udp",
    "mtu":1350,
    "mptcp":false,
    "ipv6_first":true,
    "plugin":"/path/to/installed/simple-obfs/obfs-local",
    "plugin-opts":"obfs=http;obfs-host=paper.people.com.cn",
    "workers":1
}

**Comment by rogers0** [comment]
@Amankwah please try to install debian version:
- https://tracker.debian.org/pkg/simple-obfs

**Comment by madeye** [comment]
Your JSON file is incorrect, which should be:

```
{
"server":"0.0.0.0",
"server_port":8080,
"local_address":"0.0.0.0",
"local_port":8388,
"password":"passphrase",
"timeout":300,
"method":"xchacha20-ietf-poly1305",
"fast_open":false,
"reuse_port":true,
"mode":"tcp_and_udp",
"mtu":1350,
"mptcp":false,
"ipv6_first":true,
"plugin":"/path/to/installed/simple-obfs/obfs-local",
"plugin_opts":"obfs=http;obfs-host=paper.people.com.cn",
"workers":1
}
```

**Comment by Amankwah** [comment]
@rogers0 This might be for the deb based system? but I'm on CentOS, so using alien to convert the package is possible? it seems @madeye found the error in my JSON file sovled the problem.

**Comment by Amankwah** [comment]
@madeye Thank you very much, it works. I didn't find the different arg between cmd line and JSON.
