### ISSUE TITLE
Need Command-line argument for keeping TCP_CORK

### ISSUE THREAD

**Issue by enihcam** [shadowsocks/shadowsocks-libev#1695]
> Your data transmission needs won't always conform neatly to one option or the other. In that case, you may want to take advantage of a more flexible approach for controlling a network connection: Set TCP_CORK before sending a series of data that should be considered as a single message and set TCP_NODELAY before sending short messages that should be sent immediately.
[http://www.techrepublic.com/article/tcp-ip-options-for-high-performance-data-transmission/](http://www.techrepublic.com/article/tcp-ip-options-for-high-performance-data-transmission/)

### What version of shadowsocks-libev are you using?
3.0.8

### What operating system are you using?
Archlinux

### What did you do?
Nothing

### What did you expect to see?
command-line argument for TCP_CORK

### What did you see instead?
nothing about TCP_CORK

**Comment by madeye** [comment]
No plan for this. And we shouldn't do this in shadowsocks.
