### ISSUE TITLE
3.1.0 ss-server 响应速度很慢

### ISSUE THREAD

**Issue by loveguag** [shadowsocks/shadowsocks-libev#1696]
### What version of shadowsocks-libev are you using?
3.1.0

### What operating system are you using?
client mac osx 10.12.6   server ubuntu 16.04

### What did you do?
正常使用

### What did you expect to see?
ss-server 响应速度（从输完网页回车到出现页面）不慢于3.0.8

### What did you see instead?
相同的客户端和网络环境，3.1.0的 ss-server 响应速度明显慢于3.0.8

### What is your config in detail (with all sensitive info masked)?
两个版本完全一样

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks-libev/issues/1690

**Comment by loveguag** [comment]
got it
