### ISSUE TITLE
如何检查 服务器端udp转发的状态，是否开启？ss-libev+ProxyCap/Proxifier玩lol日服失败

### ISSUE THREAD

**Issue by dragon100a** [shadowsocks/shadowsocks-libev#1697]
先给结论
https://github.com/shadowsocks/shadowsocks-libev/issues/1697#issuecomment-331034686
-------------------以下是过程------------------------------------------------------------------------------------
如题。
我想知道ss-libev服务器端的udp转发是否正常工作。该怎么办？

详细过程如下。

### What version of shadowsocks-libev are you using?
teddysun的脚本，根据他的脚本应该获取的是当前最新版的

### What operating system are you using?
ubuntu 17.04

### What did you do?
安装了bbr：https://teddysun.com/489.html
接下来安装ss-libev：https://teddysun.com/358.html

上述完成后，我在win10下的客户端是4.0.5.0，配置好之后，启动系统代理（全局，蓝色）是可以打开谷歌和y2b的，可见服务器端与客户端都是成功的。

接下来配置ProxyCap（规则是参考Proxifier）
添加本地sock5代理
![a1](https://user-images.githubusercontent.com/5362072/30593663-ff4240c4-9d7d-11e7-937b-98a4bc4757c1.png)
接下来定义规则，其实是照搬Proxifier的
![a2](https://user-images.githubusercontent.com/5362072/30593727-2a644342-9d7e-11e7-8246-2e1f4dd8e560.png)
优先级是从上到下，先判断是不是lol日服的文件，如果是应用规则；不是则下一条。
lol-jp-login表示经过ss代理
这里绿色箭头表示直连不经过代理（direct）
ss当然也是直连
其他非上述2条规则提到的（即除了ss和lol日服）全部直连

进入lol-jp-login规则
![b0](https://user-images.githubusercontent.com/5362072/30594037-2f39d408-9d7f-11e7-8f28-c1754ed3394b.png)
这里的ss即上文提到的配置好的代理
包括这样几个文件，且忽略路径的
![b1](https://user-images.githubusercontent.com/5362072/30593857-9b260692-9d7e-11e7-9a00-6f7aa4cb6c4d.png)
传输（transports）包括tcp和udp
![b2](https://user-images.githubusercontent.com/5362072/30593900-bbcf60b4-9d7e-11e7-8e4d-7ecbe0f3faad.png)
端口、ip地址、主机全部是所有（all）

我经过上述折腾完毕之后，lol日服可以正常登录。但开局就掉线，没法开局，具体就是选英雄之后，确定，然后倒计时结束，游戏开始。
正常情况下，此处应该是载入游戏显示进度，然后所有人进度都100%则开打。但现在这个地方就是没法继续，提示重连，但无论怎么重连都没法成功。
这个vps装有l2tp的vpn，本机vpn拨号后，可以正常游戏。

之前别处提到 游戏和udp转发有关，那么此处ProxyCap已经设置过udp传输了。

我 现在怀疑 是不是 ss-libev 服务器端的 udp转发 没开。
那么，我 现在 该 如何 知道ss-libev服务器端的udp转发的状态？

或者，我还有其他的地方做的不对，才导致失败的？

**Comment by tangshiba** [comment]
服务端udp需要设置，多看一下ss的参数吧。
这个问题应该能谷歌的到的。
默认是第三个，只有tcp。

"mode": "tcp_and_udp"
"mode": "udp_only"
"mode": "tcp_only"

**Comment by suikatomoki** [comment]
teddysun脚本默认开启udp
玩游戏建议路由器
或者尝试sstap
https://www.sockscap64.com/sstap

**Comment by madeye** [comment]
Try https://github.com/icymind/VRouter.

**Comment by eastmalon** [comment]
测试udp是否开启有个很简单的方法，安卓客户端打开dns转发，看能不能打开网页。
或者查看shadowsocks配置文件以及ps -ef | grep ss-server，看看option里有没有 -u。
shadowsocks不适合用来代理游戏。

**Comment by dragon100a** [comment]
先给结论，根据前面的提示，以及多处检查的结果来看，这个脚本确实启用了 udp转发。
@suikatomoki 
sstap，这个基本上成功。
首先添加一个新代理，然后通过ss客户端产生的分享链接，可以直接引入代理。
之后代理模式选“不代理中国ip”。然后点连接，这个时候他建立起了一个 tap windows adapter v9，看起来好像是个隧道？这个情况就和迅游的前3个模式差不多。
是不是中国ip，看起来是这个软件自己区分。我们并没有更多选项来定义。
迅游的模式4就是代理模式，这是我真正希望实现的效果。
那个网站还提供了sockscap64我明天打算试一试，不过感觉可能会失败。


VRouter那一套，我也装过了。结果搞得电脑无法上网，后来都删之后，发现dns被改为10开头的，去除之后好了。这东西我没搞明白。

**Comment by dragon100a** [comment]
问题已经算是解决了。
总结：
0.顶楼是用错了软件。Proxifier适合用来检查连接。ProxyCap不成功我是理解不了的，按说他已经给了足够多的选项了。
1.teddysun脚本默认开启udp，这毫无疑问，可以用多个软件验证。
代理游戏的基础已经完成。
2.sstap，引入ss，使用tap方式的方式代理游戏，排除中国的ip。
3.sockscap64，引入ss，添加日服lol的登录器，然后在代理中运行，则登录器启动的后续进程看起来都被代理了。这是我期待的方式。
