### ISSUE TITLE
3.10版本ss-server握手时间和3.08版本差不多，但是响应时间很长

### ISSUE THREAD

**Issue by chunh** [shadowsocks/shadowsocks-libev#1698]
### What version of shadowsocks-libev are you using?
3.10

### What operating system are you using?
Server：Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-62-generic x86_64)
Client：Surge in Mac and iPhone

### What did you do?
可以使用，但是响应速度很慢

### What did you expect to see?
更新至3.10版本后响应速度与3.08一致

### What did you see instead?
TCP握手时间和3.08差不多，但是响应时间非常长，香港服务器ping 35ms左右的时候，响应时间大于3000ms

### What is your config in detail (with all sensitive info masked)?
"server": "0.0.0.0",
"server_port": "8389",
"local_port": "8389",
"password": "xx",
"timeout": 3600,
"method": "aes-256-gcm",
"plugin": "obfs-server",
"plugin_opts": "obfs=tls;fast-open;obfs-host=msn.com"

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks-libev/issues/1690
