### ISSUE TITLE
shadowsocks-libev LEDE error

### ISSUE THREAD

**Issue by diigu** [shadowsocks/shadowsocks-libev#1699]
我的路由是极路由1s，使用LEDE 17.01系统。
cpu是mt7620, 型号HC5661
我应该使用mips_24kc/ 或 mipsel_24kc/这两种，但是二者opkg install 会报错。google之无解决办法，求指点。

root@LEDE:~ # opkg install https://dl.bintray.com/aa65535/opkg/shadowsocks-libev/3.0.5/LEDE/mips_24kc/:shadowsocks-libev_3.0.5-1_mips_24kc.ipk
Package shadowsocks-libev version 3.1.0-1 has no valid architecture, ignoring.
Illegal instruction
root@LEDE:~#

cpu信息。
root@LEDE:~# cat /proc/cpuinfo
system type		: MediaTek MT7620A ver:2 eco:6
machine			: HiWiFi HC5661
processor		: 0
cpu model		: MIPS 24KEc V5.0
BogoMIPS		: 385.84
wait instruction	: yes
microsecond timers	: yes
tlb_entries		: 32
extra interrupt vector	: yes
hardware watchpoint	: yes, count: 4, address/irw mask: [0x0ffc, 0x0ffc, 0x0ffb, 0x0ffb]
isa			: mips1 mips2 mips32r1 mips32r2
ASEs implemented	: mips16 dsp
shadow register sets	: 1
kscratch registers	: 0
package			: 0
core			: 0
VCED exceptions		: not available
VCEI exceptions		: not available
`

**Comment by debiansid** [comment]
自己编译

**Comment by tony1016** [comment]
一般不想奉献，不过我也是做了个镜像，http://openwrt-dist.tonylee.name/
