### ISSUE TITLE
debian 9每次安装都卡在96%

### ISSUE THREAD

**Issue by sjdjfcu** [shadowsocks/shadowsocks-libev#1701]
...
3 packages can be upgraded. Run 'apt list --upgradable' to see them.
W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/backports.list:1 and /etc/apt/sources.list.d/stretch-backports.list:1
Selecting previously unselected package libcap2-bin.
Preparing to unpack .../02-libcap2-bin_1%3a2.25-1_amd64.deb ...
Unpacking libcap2-bin (1:2.25-1) ...
Selecting previously unselected package libcork16:amd64.
Preparing to unpack .../03-libcork16_0.15.0+ds-11_amd64.deb ...
Unpacking libcork16:amd64 (0.15.0+ds-11) ...
Selecting previously unselected package libcorkipset1:amd64.
Preparing to unpack .../04-libcorkipset1_1.1.1+20150311-7_amd64.deb ...
Unpacking libcorkipset1:amd64 (1.1.1+20150311-7) ...
Selecting previously unselected package libmbedcrypto0:amd64.
Preparing to unpack .../05-libmbedcrypto0_2.4.2-1+deb9u1_amd64.deb ...
Unpacking libmbedcrypto0:amd64 (2.4.2-1+deb9u1) ...
Selecting previously unselected package libpam-cap:amd64.
Preparing to unpack .../06-libpam-cap_1%3a2.25-1_amd64.deb ...
Unpacking libpam-cap:amd64 (1:2.25-1) ...
Selecting previously unselected package libsodium18:amd64.
Preparing to unpack .../07-libsodium18_1.0.13-1~bpo9+1_amd64.deb ...
Unpacking libsodium18:amd64 (1.0.13-1~bpo9+1) ...
Selecting previously unselected package libudns0:amd64.
Preparing to unpack .../08-libudns0_0.4-1+b1_amd64.deb ...
Unpacking libudns0:amd64 (0.4-1+b1) ...
Selecting previously unselected package libev4.
Preparing to unpack .../09-libev4_1%3a4.22-1+b1_amd64.deb ...
Unpacking libev4 (1:4.22-1+b1) ...
Selecting previously unselected package shadowsocks-libev.
Preparing to unpack .../10-shadowsocks-libev_3.0.8+ds-2~bpo9+1_amd64.deb ...
Unpacking shadowsocks-libev (3.0.8+ds-2~bpo9+1) ...
Setting up libev4 (1:4.22-1+b1) ...
Setting up libpam-cap:amd64 (1:2.25-1) ...
Setting up libcork16:amd64 (0.15.0+ds-11) ...
Setting up libcap2-bin (1:2.25-1) ...
Setting up libbloom1:amd64 (1.5-1~bpo9+1) ...
Setting up apg (2.2.3.dfsg.1-4+b1) ...
Setting up libmbedcrypto0:amd64 (2.4.2-1+deb9u1) ...
Processing triggers for libc-bin (2.24-11+deb9u1) ...
Processing triggers for systemd (232-25+deb9u1) ...
Setting up libcorkipset1:amd64 (1.1.1+20150311-7) ...
Processing triggers for man-db (2.7.6.1-2) ...
Setting up libsodium18:amd64 (1.0.13-1~bpo9+1) ...
Setting up libudns0:amd64 (0.4-1+b1) ...
Setting up shadowsocks-libev (3.0.8+ds-2~bpo9+1) ...
          
Progress: [ 96%] [########################################################################################################################################################################################################################........]

**Comment by rogers0** [comment]
@sjdjfcu looks like debian specific issue, so could you kindly using "reportbug" tool to report this to Debian?

if you don't know how to set up reportbug, you can refer:
- https://wiki.debian.org/reportbug

after that, you can use command below, then follow the instruction:
```
$ reportbug -b shadowsocks-libev
```

**Comment by sjdjfcu** [comment]
@rogers0 我发现 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u3 (2017-08-06) x86_64 可以正常安装，升级内核开启BBR后再安装就会卡在96%

**Comment by debiansid** [comment]
4.9就有bbr的

**Comment by hosiet** [comment]
If you think it is a Debian-specific issue, please submit a bug report in Debian using `reportbug` tool with detailed description.

**Comment by sjdjfcu** [comment]
@hosiet 可能不是Debian的问题。Ubuntu 17.04被换成4.13内核开BBR后安装也会卡住，这个内核是通用的。

**Comment by rogers0** [comment]
@sjdjfcu Please use reportbug tool because it provides more info to us.

**Comment by madeye** [comment]
Closed due to inactivity.
