### ISSUE TITLE
Many "Connection reset by peer" 

### ISSUE THREAD

**Issue by qantnull** [shadowsocks/shadowsocks-libev#1702]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
Client:  Merlin: shadowsocks-libev 3.0.7
Server: shadowsocks-libev 3.0.8

### What operating system are you using?
Client: Linux RT-AC3200-289F 2.6.36.4brcmarm #4 SMP PREEMPT Tue Dec 6 18:37:48 CST 2016 armv7l GNU/Linux
Server: CentOS 7

### What did you do?
Because rackspace ping is slow and loss highly, I switched to AliYun Server.

### What did you expect to see?
I can open web page.

### What did you see instead?
 web page show "unexpectedly closed the connection."
I see many "[Errno 104] Connection reset by peer" in the server and merlin system.

### What is your config in detail (with all sensitive info masked)?
server config: 
{
    "server":"0.0.0.0",
    "server_port":8390,
    "local_port":1080,
    "password":"****",
    "timeout":600,
    "method":"aes-256-cfb",
}

merlin ss-redir config:
{
    "server":"****",
    "server_port":8390,
    "local_port":3333,
    "password":"****",
    "timeout":600,
    "method":"aes-256-cfb"
}

**Comment by madeye** [comment]
Double check your configs. Make sure the password and cipher name are matched.

**Comment by qantnull** [comment]
I'm sure that password is correct. And the network just ok a while and failed a while.

**Comment by asmadeus08** [comment]
wget --no-check-certificate -O shadowsocks-libev-debian.sh https://raw.githubusercontent.com/teddysun/shadowsocks_install/master/shadowsocks-libev-debian.sh
chmod +x shadowsocks-libev-debian.sh
./shadowsocks-libev-debian.sh 2>&1 | tee shadowsocks-libev-debian.log

sudo apt-get install --no-install-recommends build-essential autoconf libtool libssl-dev libpcre3-dev libc-ares-dev libev-dev asciidoc xmlto automake
git clone https://github.com/shadowsocks/simple-obfs.git
cd simple-obfs
git submodule update --init --recursive
./autogen.sh
./configure && make
sudo make install

{
    "server":"any",
    "server_port":any,
    "password":"any",
    "timeout":200,
    "method":"aes-128-cfb",
    "plugin":"obfs-server",
    "plugin_opts":"obfs=tls;obfs-host=www.google.com"
}

/etc/init.d/shadowsocks restart
/etc/init.d/shadowsocks status

ss-server -c /etc/shadowsocks-libev/config.json -u --mtu 1480 --no-delay --reuse-port -v

It must to work with that config. Tested on Ubuntu 17.04 x32

**Comment by asmadeus08** [comment]
On PC you must to do next:
1 Download last windows client
2 go to the https://github.com/imgk/simple-obfs-Cygwin/releases and download next files:
msys-2.0.dll
obfs-local.exe
obfs-local.exe and msys-2.0.dll then put it on your SS folder

create shortcut of obfs-local.exe with the next command line after path: obfs-local -c user-config.json --plugin obfs-local --plugin-opts "obfs=tls;obfs-host=www.google.com"
shadowsocks client for PC:
obfs-local
obfs=tls;obfs-host=www.google.com

**Comment by madeye** [comment]
Closed due to inactivity.
