### ISSUE TITLE
rebooted to ss-redir noruning

### ISSUE THREAD

**Issue by 873578156** [shadowsocks/shadowsocks-libev#1703]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
2.5.6-1

### What operating system are you using?
PandoraBox 17.01 2017-01-03-git-6c24a7a / LuCI Master (git-16.354.35264-23d1dc7) on Phicomm K2 

### What did you do?
use

### What did you expect to see?
rebooted to ss-redir runing

### What did you see instead?
rebooted to ss-redir noruning

**Comment by madeye** [comment]
I don't think it's related to shadowsocks-libev.

Report it to the downstream maintainer.

**Comment by 873578156** [comment]
But when I restart the service, I can use it. Once the router is rebooted, it will again show that it has not run,

**Comment by madeye** [comment]
Closed due to inactive.
