### ISSUE TITLE
Expose more APIs to make this project as a communication library

### ISSUE THREAD

**Issue by WANG-lp** [shadowsocks/shadowsocks-libev#1704]
Hi,
Thanks for this beautiful project.

I am wondering whether we can expose more APIs to use this project as an underlying communication library. 

For example, can we extract some APIs like send() or sendPackage() on the client side?
It will be easier to use this project as a library to implement a VPN-like service.

 We already have a start server function in the `src/shadowsocks.h` file. I think we can achieve this with minor changes.

**Comment by madeye** [comment]
No plan for this.

BTW, I don't think we can expose anything like `send()` from shadowsocks-libev.
