### ISSUE TITLE
Shadowsocks-libev server no reply

### ISSUE THREAD

**Issue by no1be4me** [shadowsocks/shadowsocks-libev#1707]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
3.0.8+DS-2~bpo8+1

### What operating system are you using?
Debian 8
Shadowsocks version 0.3.2(REV3) by Linus Yang on JB iPhone from cydia 
Windows 4.0.6 client.

### What did you do?
Logged into server sitting in another country.
Start server  ss-server -c /etc/shadowsocks-libev/config.json -d 8.8.8.8 start -v
Start client in visiting country and go to https://dnsleaktest.com, 

### What did you expect to see?
Clients received reply from server.

### What did you see instead?
Saw client request on server, but no reply from server on clients.

### What is your config in detail (with all sensitive info masked)?
{
    "server":["::0","0.0.0.0"],
    "server_port":12345,
    "local_address":"127.0.0.1",
    "local_port":1080,
    "password":"password",
    "reuse_port":true,
    "timeout":600,
    "method":"aes-256-cfb"
}
nameserver 8.8.8.8
iptables -I INPUT -p tcp --dport 12345 -j ACCEPT

**Comment by madeye** [comment]
I cannot reproduce your issue locally. Double check your configs.

**Comment by no1be4me** [comment]
Can you see if all is installed correctly?

root@Lenova:~# apt-cache showpkg shadowsocks-libev
Package: shadowsocks-libev
Versions: 
3.0.8+ds-2~bpo8+1 (/var/lib/apt/lists/deb.debian.org_debian_dists_jessie-backports-sloppy_main_binary-amd64_Packages) (/var/lib/dpkg/status)
 Description Language: 
                 File: /var/lib/apt/lists/deb.debian.org_debian_dists_jessie-backports-sloppy_main_binary-amd64_Packages
                  MD5: 2af159ade6a64ba56baee53dbd758b00
 Description Language: en
                 File: /var/lib/apt/lists/deb.debian.org_debian_dists_jessie-backports-sloppy_main_i18n_Translation-en
                  MD5: 2af159ade6a64ba56baee53dbd758b00

2.6.3+ds-1~bpo8+1 (/var/lib/apt/lists/deb.debian.org_debian_dists_jessie-backports_main_binary-amd64_Packages)
 Description Language: 
                 File: /var/lib/apt/lists/deb.debian.org_debian_dists_jessie-backports_main_binary-amd64_Packages
                  MD5: 3f53db35c732b49dafb9af75120c0acc
 Description Language: en
                 File: /var/lib/apt/lists/deb.debian.org_debian_dists_jessie-backports_main_i18n_Translation-en
                  MD5: 3f53db35c732b49dafb9af75120c0acc


Reverse Depends: 
  shadowsocks-libev:i386,shadowsocks-libev
  libshadowsocks-libev2:i386,shadowsocks-libev 2.4.0
  libshadowsocks-libev-dev:i386,shadowsocks-libev 2.4.0
  simple-obfs,shadowsocks-libev 3.0.5
  libshadowsocks-libev2,shadowsocks-libev 2.4.0
  libshadowsocks-libev-dev,shadowsocks-libev 2.4.0
  shadowsocks-libev:i386,shadowsocks-libev
  libshadowsocks-libev2:i386,shadowsocks-libev 2.4.0
  libshadowsocks-libev-dev:i386,shadowsocks-libev 2.4.0
  libshadowsocks-libev2,shadowsocks-libev 2.4.0
  libshadowsocks-libev-dev,shadowsocks-libev 2.4.0
Dependencies: 
3.0.8+ds-2~bpo8+1 - apg (16 (null)) pwgen (0 (null)) libcap2-bin (0 (null)) lsb-base (2 3.0-6) init-system-helpers (2 1.18~) libbloom1 (0 (null)) libc6 (2 2.14) libcork16 (0 (null)) libcorkipset1 (0 (null)) libev4 (2 1:4.04) libmbedcrypto0 (2 2.0) libpcre3 (2 1:8.35) libsodium18 (2 1.0.12) libudns0 (2 0.4) haveged (0 (null)) kcptun (0 (null)) simple-obfs (0 (null)) shadowsocks (3 1.5.3-2) shadowsocks:i386 (3 1.5.3-2) shadowsocks (3 1.5.3-2) shadowsocks:i386 (3 1.5.3-2) shadowsocks-libev:i386 (0 (null)) 
2.6.3+ds-1~bpo8+1 - apg (0 (null)) libcap2-bin (0 (null)) lsb-base (2 3.0-6) init-system-helpers (2 1.18~) libc6 (2 2.14) libcork16 (0 (null)) libcorkipset1 (0 (null)) libev4 (2 1:4.04) libmbedcrypto0 (2 2.0) libpcre3 (2 1:8.35) libsodium18 (2 1.0.8) libudns0 (2 0.4) shadowsocks (3 1.5.3-2) shadowsocks:i386 (3 1.5.3-2) shadowsocks (3 1.5.3-2) shadowsocks:i386 (3 1.5.3-2) shadowsocks-libev:i386 (0 (null)) 
Provides: 
3.0.8+ds-2~bpo8+1 - 
2.6.3+ds-1~bpo8+1 - 
Reverse Provides:

**Comment by no1be4me** [comment]
I checked my json.config at the validator it passed.

**Comment by madeye** [comment]
Closed due to inactivity.

**Comment by no1be4me** [comment]
Madeye you know shadowsocks-libev better than anyone on the planet, there must be a reason why I cannot get the server reply.

I have another server in another country, bought were made exactly the same time and using the same machines, both were then on 2.6.3+..... I upgrade both before sending them out, on 3.0.8+...and shadowsocks-libev stopped working on both.

I wiped the drives and loaded back 2.6.3+.... Now I upgraded one back again, same it cannot will not work. The other is still working.

I can see the request reaching the server fine, I see the server resolved the DNS but then I see request closed. On the other server I get the reply back.

**Comment by no1be4me** [comment]
The second server is on 2.6.3+... still

**Comment by madeye** [comment]
One observation is your command line is incorrect:

`ss-server -c /etc/shadowsocks-libev/config.json -d 8.8.8.8 start -v`

You should not put `start` here. The correct CLI would be:

`ss-server -c /etc/shadowsocks-libev/config.json -d 8.8.8.8 -v`

**Comment by no1be4me** [comment]
Okay will login the server now and stop / start it, as you recommended.

**Comment by no1be4me** [comment]
![server_1](https://user-images.githubusercontent.com/18052570/31872387-9709908e-b7cc-11e7-98ad-27f17133af11.png)

**Comment by no1be4me** [comment]
remote connected
 2017-10-23 08:31:40 INFO: server_recv close the connection
 2017-10-23 08:31:40 INFO: current remote connection: 0
 2017-10-23 08:31:40 INFO: current server connection: 1
 2017-10-23 08:31:41 INFO: accept a connection
 2017-10-23 08:31:41 INFO: connect to forum.lede-project.org:443
 2017-10-23 08:31:41 INFO: successfully resolved forum.lede-project.org
 2017-10-23 08:31:41 INFO: remote connected

**Comment by no1be4me** [comment]
this constant what is happening to the remote remote server

**Comment by no1be4me** [comment]
and on my side not reply, I see the request from the log, I see the server get the request sent to it, I see the server resolved the DNS then the close the request in the log no inbound signals.
