### ISSUE TITLE
autogen.sh not found

### ISSUE THREAD

**Issue by mdrights** [shadowsocks/shadowsocks-libev#1710]
### What version of shadowsocks-libev are you using?
3.1.0

### What operating system are you using?
GNU/Linux

### What did you do?
Compiling

### What did you expect to see?
Success compilation

### What did you see instead?
I can't find autogen.sh (and I found it doesn't need it )

### What is your config in detail (with all sensitive info masked)?
(No need for this :)

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks-libev/blob/master/autogen.sh
