### ISSUE TITLE
ss-server -a命令不对插件obfs-server生效

### ISSUE THREAD

**Issue by xxmali** [shadowsocks/shadowsocks-libev#1712]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?

3.1.0
### What operating system are you using?

Ubuntu 14.04
### What did you do?

ss-server -c config.conf -a ss -f ss.pid
### What did you expect to see?

ss-server和obfs-server均以ss身份运行
### What did you see instead?

ss-server以ss身份运行，而obfs-server以root身份运行。
### What is your config in detail (with all sensitive info masked)?
{
    "server": "0.0.0.0",
    "timeout": 300,
    "method": "aes-256-gcm",
    "server_port": "1234",
    "password": "password",
    "plugin": "obfs-server",
    "plugin_opts": "obfs=tls"
}

另，如果加载obfs-server，那大佬在#717 用iptables限制访问127.0.0.1的方法将失效。

**Comment by madeye** [comment]
Add 'a=user;' to your plugin_opts.

**Comment by xxmali** [comment]
谢谢大佬
