### ISSUE TITLE
Error "sendto: Operation not supported" when fast_open enabled

### ISSUE THREAD

**Issue by clippit** [shadowsocks/shadowsocks-libev#1713]
### What version of shadowsocks-libev are you using?
Client: 3.1.0
Server: 3.0.8

### What operating system are you using?
Client: UBNT EdgeOS  v1.9.7+hotfix.3 (it's based on debian wheezy and my device uses mipsel arch)
Server: Debian stretch

### What did you do?
When fast_open enabled, ss-local shows `ERROR: sendto: Operation not supported` and no Internet through proxy. It works well after removing this line in config file.
ss-redir doesn't work neither but no error output.

I compiled from source code on a qemu mipsel emulator and copied necessary lib and bin to my device because on-board storage is too small for a building environment.

Here's `uname -a` output on client:
```
Linux ubnt 3.10.14-UBNT #1 SMP Wed Aug 30 02:34:16 PDT 2017 mips GNU/Linux
```

### What is your config in detail (with all sensitive info masked)?
```
{
    "server":"xxx.xxx.xxx.xxx",
    "server_port":xxxx,
    "local_address":"0.0.0.0",
    "local_port":xxxx,
    "password":"xxxxxxxxxxxxxxxxx",
    "timeout":60,
    "method":"chacha20-ietf-poly1305",
    "user_name": "nobody",
    "reuse_port": true
    "fast_open": true  // <-- this failed
}
```

**Comment by madeye** [comment]
Make sure your router's OS support fast_open correctly.

**Comment by clippit** [comment]
Ah.. I forget to set net.ipv4.tcp_fastopen=1 😂
Thanks for the reminding! This could be closed now.
