### ISSUE TITLE
RETURN target

### ISSUE THREAD

**Issue by QiXianPu** [shadowsocks/shadowsocks-libev#1717]
`iptables -t nat -I PREROUTING -p tcp -d server_ip_address -j RETURN`
我试过如果不设置这项规则好像就无法进行透明代理(ss-redir)，比如打不开网站。但是我不知道为什么会这样？这项规则应该是不让访问服务器的流量走代理，应该不至于影响别的数据包吧？麻烦大神分析一下。

**Comment by eastmalon** [comment]
避免死循环。

**Comment by eastmalon** [comment]
这个问题和shadowsocks无关

**Comment by QiXianPu** [comment]
谢谢
