### ISSUE TITLE
按照说明配置google vps，不成功！输出“sudo /etc/init.d/shadowsocks-libev status”结果如下

### ISSUE THREAD

**Issue by amdth** [shadowsocks/shadowsocks-libev#1718]
● shadowsocks-libev.service - Shadowsocks-libev Default Server Service
   Loaded: loaded (/lib/systemd/system/shadowsocks-libev.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2017-10-05 15:27:16 UTC; 2min 6s ago
     Docs: man:shadowsocks-libev(8)
  Process: 1859 ExecStart=/usr/bin/ss-server -c $CONFFILE $DAEMON_ARGS (code=exited, status=255)
 Main PID: 1859 (code=exited, status=255)

Oct 05 15:27:16 instance-1 ss-server[1859]:  2017-10-05 15:27:16 INFO: initializing ciphers... chacha20-ietf-poly1305
Oct 05 15:27:16 instance-1 ss-server[1859]:  2017-10-05 15:27:16 INFO: This system doesn't provide enough entropy to quickly generate high-quality random numbers
Oct 05 15:27:16 instance-1 ss-server[1859]: Installing the rng-utils/rng-tools or haveged packages may help.
Oct 05 15:27:16 instance-1 ss-server[1859]: On virtualized Linux environments, also consider using virtio-rng.
Oct 05 15:27:16 instance-1 ss-server[1859]: The service will not start until enough entropy has been collected.
Oct 05 15:27:16 instance-1 ss-server[1859]:  2017-10-05 15:27:16 ERROR: bind: Cannot assign requested address
Oct 05 15:27:16 instance-1 ss-server[1859]:  2017-10-05 15:27:16 ERROR: bind() error
Oct 05 15:27:16 instance-1 systemd[1]: shadowsocks-libev.service: Main process exited, code=exited, status=255/n/a
Oct 05 15:27:16 instance-1 systemd[1]: shadowsocks-libev.service: Unit entered failed state.
Oct 05 15:27:16 instance-1 systemd[1]: shadowsocks-libev.service: Failed with result 'exit-code'.

**Comment by ContactFront** [comment]
https://github.com/shadowsocks/shadowsocks-libev/issues/1384

**Comment by amdth** [comment]
@ContactFront  已经安装了rng-tools 还是不成功，能具体提示一点吗
