### ISSUE TITLE
Client connects to Shadowsocks, but won't work on user end

### ISSUE THREAD

**Issue by rhazor** [shadowsocks/shadowsocks-libev#1721]
### What version of shadowsocks-libev are you using?
I don't know how to check, I followed this guide https://www.linode.com/docs/networking/create-a-socks5-proxy-server-with-shadowsocks-on-ubuntu-and-centos7

### What operating system are you using?
Ubuntu 16.04

### What did you do?
I followed the guide above. Looks like Shadowsocks is running, because the Windows client connects to it and it can be seen in the logs.

### What did you expect to see?
I expected it to work on browsers, load pages, etc.

### What did you see instead?
Nothing. Default no connection message.

### What is your config in detail (with all sensitive info masked)?
I just copy pasted it from https://www.linode.com/docs/networking/create-a-socks5-proxy-server-with-shadowsocks-on-ubuntu-and-centos7

Anyway, when trying to visit a website you can see on the log it shows it connects to server with no errors, but website won't load.

![untitled-1](https://user-images.githubusercontent.com/22996586/31346745-c4014014-ad22-11e7-97c3-352d7e59a715.jpg)

Windows firewall disabled. In program settings e.g. Firefox/Chrome SOCKS5 set to 127.0.0.1:1080

edit: there's also some blue symbol blinking on the Shadowsocks system tray icon when refreshing pages on the browser,  but I'm not sure what it indicates.

**Comment by luxin88** [comment]
I have the same issue too, but if I reboot server system, it well be okay

**Comment by iminto** [comment]
Stop struggling! The nineteenth National People's Congress of PRC is watching you!

**Comment by hldh214** [comment]
life is short, i use baicai

**Comment by rhazor** [comment]
what is this spam. what baicai.

**Comment by madeye** [comment]
Please don't post off-topic comments here.

**Comment by rhazor** [comment]
I did a hard restart on my Vultr server, but no change. @madeye what's the command to check the version of shadowsocks-libev on ubuntu 16.04?

**Comment by rogers0** [comment]
> what's the command to check the version of shadowsocks-libev on ubuntu 16.04?

method0:
```$ dpkg -l|grep shadowsocks```
method1:
```$ ss-server -h|head -n2```

**Comment by rhazor** [comment]
shadowsocks-libev 3.1.0

**Comment by luxin88** [comment]
@rhazor I've change a port and restart both server and client, it okay now, i'm using chacha20-ietf-poly1305 now, but I'm using SSX-NG as client

**Comment by rhazor** [comment]
You changed the default 8388 or the 1080?

**Comment by madeye** [comment]
Closed due to inactivity.

**Comment by rhazor** [comment]
Seriously dude. This is fucking useful.
