### ISSUE TITLE
Specify network card with non-root user: error setinterface: Operation not permitted

### ISSUE THREAD

**Issue by myliyifei** [shadowsocks/shadowsocks-libev#1724]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
2.5.X 3.0.X

### What operating system are you using?
Ubunut 16.04 14.04

### What did you do?
specify the network card using -i parameter 

### What did you expect to see?
no error, access internet

### What did you see instead?
3.0.X versions many errors in logs: setinterface: Operation not permitted,  can't access internet
2.5.X versions same  errors in logs: but can access internet.

### What is your config in detail (with all sensitive info masked)?
whether sudo -u xxx or  ss-server -a xxx 

sudo ss-server -s 0.0.0.0 -p 8000 -k xxx -t 600 -f /var/run/shadowsocks-libev/xxx.pid -u -v -a xxx

Is this a bug or the correct behaviour?

**Comment by madeye** [comment]
It's expected. You can never bind to specific interface without privilege.
