### ISSUE TITLE
How to get old versions

### ISSUE THREAD

**Issue by myliyifei** [shadowsocks/shadowsocks-libev#1725]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
would like to use old versions

### What operating system are you using?
Ubuntu 14.04 and 16.04

### What did you do?
There are not old versions deb in PPA
use build_deb.sh script to get the latest code always. BTW, compile is failed.

### What did you expect to see?
Archive the history versions in the repository.

**Comment by rogers0** [comment]
@myliyifei if you use debian:
- http://snapshot.debian.org/package/shadowsocks-libev/

**Comment by myliyifei** [comment]
but I use Ubuntu. With these deb, I must install related dependences by
myself :(

2017-10-10 21:23 GMT+08:00 Roger Shimizu <notifications@github.com>:

**Comment by gaoyifan** [comment]
Maybe you can try to use docker version. I packed libev version from 2.4.8:
https://hub.docker.com/r/gaoyifan/shadowsocks-libev/tags/
