### ISSUE TITLE
The server should not respond anything to the client closeSocket was respond too

### ISSUE THREAD

**Issue by tutorde** [shadowsocks/shadowsocks-libev#1729]
The client's authentication has a specific length
we should threadSleep(random) then closeSocket
or make the authentication length random
like:
randomStr = get random length of "@"
pwdMd5Base64 = base64(md5(password+prot))
or for Single port multiuser
pwdMd5Base64 = base64(md5(password+username))
authentication = encrypt(randomStr + pwdMd5Base64)

server got the authentication decrypt and remove all the "@" in the head
pwdMd5Base64  has a specific length 

is this any issues if doing like this:
client has tow password  the password for port and the password for user
when send authentication use the password for port
server search in passwordDictionary use the key with pwdMd5Base64 and got passwordForUser
then server change password to passwordForUser
maybe too complicated
just saying not coding

**Comment by madeye** [comment]
Closed due to inactivity.
