### ISSUE TITLE
The client's authentication has a specific length we should threadSleep(random) then closeSocket

### ISSUE THREAD

**Issue by tutorde** [shadowsocks/shadowsocks-libev#1730]
just a Suggest
The client's authentication has a specific length
The server should not respond anything to the client
closeSocket was respond too
we should threadSleep(random) then closeSocket
or make the authentication length random
like:
randomStr = get random length of "@"
pwdMd5Base64 = base64(md5(password+prot))
or for Single port multiuser
pwdMd5Base64 = base64(md5(password+username))
authentication = encrypt(randomStr + pwdMd5Base64)

server got the authentication decrypt and remove all the "@" in the head
pwdMd5Base64 has a specific length

**Comment by madeye** [comment]
Duplicate with #1729
