### ISSUE TITLE
Sending images through WhatsApp fails

### ISSUE THREAD

**Issue by threalcsr** [shadowsocks/shadowsocks-libev#1731]
### What version of shadowsocks-libev are you using?

3.0.8, installed from the repos

### What operating system are you using?

Centos 7 x86_64 running on a VPS

### What did you do?

On the server: ss-server -p 8800 -k my_password -u
On the client: Using Wingy (for iOS) to connect to the server, I tried sending an image through WhatsApp. Text messages work fine.

### What did you expect to see?

Image sent/received confirmation.

### What did you see instead?

WhatsApp fails to send the image. The verbose output of ss-server is:

 2017-10-13 06:06:41 INFO: accept a connection
 2017-10-13 06:06:42 INFO: connect to mms.whatsapp.net:443
 2017-10-13 06:06:42 INFO: IPv6 resolv: valid domain but no data of requested type
 2017-10-13 06:06:42 INFO: successfully resolved mms.whatsapp.net

Despite the this output, the "sending" gif from WhatsApp plays endlessly.

### What is your config in detail (with all sensitive info masked)?

{
    "server":"127.0.0.1",
    "server_port":8800,
    "local_port":1080,
    "password":"my_password",
    "timeout":60,
    "method":"rc4-md5"
}

**Comment by madeye** [comment]
I don't think it's an issue of shadowsocks-libev. It looks a bug of Wingy instead.

To verify this, you may try shadowsocks-android with WhatsApp on an Android phone, or change your server to go-shadowsocks2 or shadowsocks-python.

**Comment by threalcsr** [comment]
Thank you! go-shadowsocks2 worked like a charm.
I still don't know why the problem arose in the first place, however. Wingy seems not to be at fault.
