### ISSUE TITLE
What is the best choice when it comes to proxy game traffic ?

### ISSUE THREAD

**Issue by QiXianPu** [shadowsocks/shadowsocks-libev#1733]
Dear owner of this repository,

I want to use some tools to proxy game traffic. I now have two choices: 
        
        Shadowsocks-libev (ss-redir feature) and the openvpn

I have already read parts of the official document of the openvpn. I find that the deployment of openvpn on a server is much harder than the Shadowsocks-libev. So I wonder which one of these two proxy tools works better when it comes to proxy game traffic (PUBG) ?

Thanks

**Comment by chenhw2** [comment]
BUT openvpn faces risk of getting blocked.

**Comment by leonshaw** [comment]
I'd recommend trivial SOCKS proxies, since you are not requiring extra security.

**Comment by QiXianPu** [comment]
Thanks, guys : ) @chenhw2 @leonshaw 

I will use a tunnel to carry those traffic that traverse through the openvpn if the openvpn can be blocked.

And what is the trivial SOCKS proxies? Any useful information about it?

**Comment by leonshaw** [comment]
@QiXianPu You could use softwares like dante, or simply use "ssh -D" (as a loop on the server, to avoid being blocked).

**Comment by lewisxy** [comment]
https://github.com/shadowsocks/shadowsocks/wiki/Connect-to-OpenVPN-over-Shadowsocks

**Comment by QiXianPu** [comment]
thank all of you.
