### ISSUE TITLE
常驻后台后出现failed to set nameservers 

### ISSUE THREAD

**Issue by hsfy19091** [shadowsocks/shadowsocks-libev#1737]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?

3.1.0
### What operating system are you using?

centos 7
### What did you do?

ss-server -c ~/config -d start  
### What did you expect to see?
INFO: tcp server listening at 74.***.149.161:9***

### What did you see instead?
ERROR: failed to set nameservers

### What is your config in detail (with all sensitive info masked)?
{
    "server":"74.***.149.161",
    "server_port":9011,
    "local_address": "127.0.0.1",
    "local_port":1080,
    "password":"******",
    "timeout":300,
    "method":"aes-256-gcm",
    "fast_open": false
}

**Comment by madeye** [comment]
`-d start` means you set the name server to `start`.

**Comment by anamewing** [comment]
We should update the wikipage to remove "-d start".
https://github.com/shadowsocks/shadowsocks/wiki/Configuration-via-Config-File
