### ISSUE TITLE
Why are there so many udp listening port be opened after running ss-redir on the OpenWRT

### ISSUE THREAD

**Issue by QiXianPu** [shadowsocks/shadowsocks-libev#1738]
Hi,

I run the shadowsocks-libev client (ss-redir feature) on the OpenWRT and below is my config file of it:
```
{
    "server":"X.X.X.X",
    "server_port":46000,
    "local_address":"0.0.0.0",
    "local_port":1080,
    "password":"passwords",
    "timeout":300,
    "method":"aes-128-gcm"
}
```
There are two listening udp ports just after I run the ss-redir command. Then after some time of use, the number of the opened udp ports increasing dramatically as shown in the screenshot below: 
![question_2](https://user-images.githubusercontent.com/31722393/31585201-a7936790-b1f0-11e7-86f5-03884aa87a7a.PNG)

**Comment by madeye** [comment]
It's expected.

The maximum number of UDP ports opened is hard coded as 1024 currently.
