### ISSUE TITLE
daemon运行模式的时候没有LOG输出

### ISSUE THREAD

**Issue by myliyifei** [shadowsocks/shadowsocks-libev#174]
现在版本是不是加上了-f就进入daemon运行? 哪怕是从命令行直接执行ss-server.

我自己加了-v 和  >$logfie 2>&1 

在 /etc/default/shadowsocks-libev DAEMON_ARGS="-v >/var/log/shadowsocks.log 2>&1"中，连

日志文件都不会自动生成。

**Comment by lo0446** [comment]
Could you please clarify this in English? I'm using this inside the GFW and also need some extensive logging. Is there an option for verbose logging?

**Comment by kxmp** [comment]
@lo0446
He said he run ss in daemon mode and can't got log.

**Comment by myliyifei** [comment]
you must use -f option to specify pid file. and then you can  get the log .

2015-06-09 14:16 GMT+08:00 kxmp <notifications@github.com>:

**Comment by lo0446** [comment]
Thanks

**Comment by rule2c** [comment]
那么最后是如何解决的？

**Comment by zsqbb** [comment]
ref from：[https://github.com/shadowsocks/shadowsocks-go/blob/master/deb/etc/init.d/shadowsocks](url) u can solve the prob

line 77
` sudo -u $USER $BIN -c $CONFIG_FILE >>$LOG_FILE &`

**Comment by kid1412621** [comment]
I use `systemctl start shadowsocks-libev` to boot, how I can I set the log file?
According to [this thread](https://github.com/shadowsocks/shadowsocks-libev/issues/1630) is to set `use_syslog` in config file. However [this thread ](https://github.com/shadowsocks/shadowsocks-libev/issues/2247) said there is no such option.
