### ISSUE TITLE
Multiple vulnerabilities in shadowsocks

### ISSUE THREAD

**Issue by OneHappyForever** [shadowsocks/shadowsocks-libev#1741]
Have anyone seen these audits? @madeye 

https://x41-dsec.de/lab/advisories/x41-2017-008-shadowsocks/

What do you think?

EDIT: sorry, didn’t notice the other thread... thought I didn’t press the submit button... please close this issue

**Comment by terrytw** [comment]
https://github.com/shadowsocks/shadowsocks/issues/995

**Comment by terrytw** [comment]
https://github.com/shadowsocks/shadowsocks/issues/995

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks-libev/issues/1740
