### ISSUE TITLE
package for pfsense #wishlist

### ISSUE THREAD

**Issue by imacks** [shadowsocks/shadowsocks-libev#1745]
I wish there is a package for [pfsense](http://www.pfsense.org), which is based on FreeBSD. Right now I have to put an OpenWRT router before my firewall, which doesn't make a lot of sense other than for `ss-redir`.

**Comment by madeye** [comment]
The bad news is `ss-redir` doesn't support FreeBSD.

So, I don't think you would have shadowsocks-libev working as expected on pfsense.
