### ISSUE TITLE
configure: error: The c-ares library libraries not found.

### ISSUE THREAD

**Issue by yongyanghz** [shadowsocks/shadowsocks-libev#1746]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
3.1.0 

### What operating system are you using?
CentOS 7

### What did you do?

```
yum update && yum upgrade -y
yum install epel-release -y
yum install -y gcc gettext autoconf libtool automake make pcre-devel asciidoc xmlto udns-devel libev-devel libsodium-devel mbedtls-devel git m2crypto

git clone https://github.com/shadowsocks/shadowsocks-libev.git
cd shadowsocks-libev
git submodule update --init --recursive

./autogen.sh
./configure
```

### What did you expect to see?
I expected to see configure successfully.

### What did you see instead?
configure: error: The c-ares library libraries not found.

### What is your config in detail (with all sensitive info masked)?

>

**Comment by chenhw2** [comment]
U have not follow the README

**Comment by onlyJinx** [comment]
yum install gcc gettext autoconf libtool automake make pcre-devel asciidoc xmlto c-ares-devel libev-devel libsodium-devel mbedtls-devel -y

![1](https://user-images.githubusercontent.com/21324835/31847155-be46111a-b649-11e7-8436-8c88220473ef.png)

**Comment by yongyanghz** [comment]
Yes, you're right. After 
`yum install c-ares-devel`
The problem is solved.
Thank you. @onlyJinx
