### ISSUE TITLE
The right way to start/stop shadowsocks-libev

### ISSUE THREAD

**Issue by ghuiii** [shadowsocks/shadowsocks-libev#1747]
### What version of shadowsocks-libev are you using?
3.1.0

### What operating system are you using?
SMP Debian 4.9.51-1 (2017-09-28) x86_64 GNU/Linux

### What did you do?
I found two method to start ss:
way1: 
```bash
sudo /etc/init.d/shadowsocks-libev start    # for sysvinit, or
```
this way doesn't work for me, but it replied [ok]

way2:
```
sudo ss-server -c /etc/shadowsocks-libev/config.json -f .ss.pid
```
This way worked for me , but I can't find the way to stop it(expect kill the_process, there isn't a way something like `ss-server stop`.
### What did you expect to see?
I just want to know which way is the better one?
If the first one is the better one, but why it doesn't work for me? any configeration I missed?
If the 2nd is the choice, Is there a good way to stop the ss-server, I found that if I run `sudo ss-server -c /etc/shadowsocks-libev/config.json -f .ss.pid` repeatedly , then a lot of process will be created.
That's not what I want, obviously.

### What did you see instead?
way1 doen't work for me.
for way2 can't found a good way to stop the ss-server process.

### What is your config in detail (with all sensitive info masked)?
![image](https://user-images.githubusercontent.com/5203798/31848374-0c5df226-b5f7-11e7-84fd-a7c937ee8ee1.png)

### End
Thanks so much for what your team did!

**Comment by ghuiii** [comment]
I Had read https://github.com/shadowsocks/shadowsocks-libev/issues/1580 , but didn't worked for me.

**Comment by onlyJinx** [comment]
#1640

**Comment by eastmalon** [comment]
1. `sudo /etc/init.d/shadowsocks-libev stop`
2. `sudo kill -9 $(cat .ss.pid)`

**Comment by ghuiii** [comment]
I think it would be great If there was a command like ` ss-server start/stop/status/restart/log ` .

**Comment by hosiet** [comment]
ss-libev already provides systemd service and sysvinit service for users to use when installed from distribution package. I think implementing another start/stop layer is unnecessary.

If you find any difficulties when using ss-libev as system service, feel free to submit issues here and describe your problem.

**Comment by ghuiii** [comment]
`sudo /etc/init.d/shadowsocks-libev start` doesn't work for me. I don't know why? Any else information need to be provided ?

**Comment by hosiet** [comment]
If you are one Debian 9: stop using things inside `/etc/init.d/`. This file only exists for compatibility purposes with old init system.

Please use `systemctl` command to manage ss-libev's service as described in "Configure and start the service" part in README.md. You will need basic knowledges about systemd.

**Comment by ghuiii** [comment]
@hosiet  Thx for your patient explain, I'll try later, and let you know the result!

**Comment by ghuiii** [comment]
@hosiet I executed `sudo systemctl start shadowsocks-libev` , but ss didn't started successfully!
Any advice?

![image](https://user-images.githubusercontent.com/5203798/31894176-4010ad2e-b7d3-11e7-9190-dc2fd80331c2.png)

**Comment by lxx4380** [comment]
try 
''''
sudo systemctl start shadowsocks-libev@config
''''

**Comment by ghuiii** [comment]
@lxx4380 `Failed to start shadowsocks-libev@config.service: Unit shadowsocks-libev@config.service not found.`

**Comment by ghuiii** [comment]
@madeye @hosiet I still want to recommand that ss-libev should has the commands  `ss-server start/stop/status/restart/log`  just like shadowsocks-python . Since the commands are easy to understand and use.

**Comment by hosiet** [comment]
Personally I'm not for this idea. Anyway, this decision should be made by the main maintainer here.

**Comment by lxx4380** [comment]
@hosiet You're right. I wrote a wrong command. However obfs works really well on my server:
```
~# systemctl status shadowsocks-libev -l
● shadowsocks-libev.service - Shadowsocks-libev Default Server Service
   Loaded: loaded (/lib/systemd/system/shadowsocks-libev.service; disabled)
   Active: active (running) since Tue 2017-10-24 15:13:53 UTC; 7min ago
     Docs: man:shadowsocks-libev(8)
 Main PID: 14484 (ss-server)
   CGroup: /system.slice/shadowsocks-libev.service
           ├─14484 /usr/bin/ss-server -c /etc/shadowsocks-libev/config.json -u
           └─14485 obfs-server
```
 @ghuiii Can you provide full log of shadowsocks-libev.service?

**Comment by ghuiii** [comment]
![image](https://user-images.githubusercontent.com/5203798/31952696-d759b940-b8a6-11e7-9b99-754bc7a6bbf0.png)
@lxx4380

**Comment by leonshaw** [comment]
@ghuiii It's almost always better to manage services in the way distro provides.

**Comment by lxx4380** [comment]
I don't think the picture you provided has enough information to find out what's wrong.
You may need to provide more detailed information like this:
![screenshot_20171025_114235](https://user-images.githubusercontent.com/12570880/31979840-5ff8c118-b97b-11e7-82d2-43352ba79a17.png)

**Comment by ghuiii** [comment]
@lxx4380 That's all , I checked it again.
`ss-server` works well for me, currently I gived up the systemctl command.
And Killed by `sudo kill`.

**Comment by leonshaw** [comment]
Try shadowsocks-libev-server@config.service

**Comment by hosiet** [comment]
There's no fundamental difference between shadowsocks-libev.service and shadowsocks-libev-server@config.service.

If you want to debug and find out the problem, please provide **complete** screenshot of output of `systemctl status shadowsocks-libev.service`.Previous screenshot missed some critical part of the log thus I cannot tell you the reason of problem.

**Comment by lxx4380** [comment]
There must be some text after "[simple-obfs]", and that is just what we need.

**Comment by ghuiii** [comment]
@lxx4380 You're right, I missed the important part.

![image](https://user-images.githubusercontent.com/5203798/31987621-ffebfec8-b931-11e7-983e-ed89c79a90a9.png)

**Comment by debug18** [comment]
Try `sudo setcap 'cap_net_bind_service=+ep' /path/to/obfs-server`.

**Comment by lxx4380** [comment]
Or use port larger than 1024, or run this service with root user.

**Comment by ghuiii** [comment]
@debug18 Still doesn't work
![image](https://user-images.githubusercontent.com/5203798/31989624-7725c874-b938-11e7-88ff-2e3fe95fdd98.png)

**Comment by lxx4380** [comment]
/usr/local/bin/obfs-server

**Comment by debiansid** [comment]
You should not install from source. Coz you are not so familiar with Linux.

**Comment by chaoli46** [comment]
[supervisorctl](https://github.com/shadowsocks/shadowsocks/wiki/Setting-Up-Shadowsocks-on-Linode) works, or just write a simple shell script:

```bash
#!/bin/bash

if [[ $1 == "on" ]]; then
  ss-server -c /etc/shadowsocks.json -u -f /etc/sss.pid
  echo "Shadowsocks turned on"
elif [[ $1 == "off" ]]; then
  kill -9 $(cat /etc/sss.pid)
  echo "Shadowsocks turned off"
else
  echo "Usage: on/off"
fi
```
