### ISSUE TITLE
run error with mips/debian7

### ISSUE THREAD

**Issue by shom** [shadowsocks/shadowsocks-libev#1748]
### What version of shadowsocks-libev are you using?
3.1.0

### What operating system are you using?
debian7.11/mips

### What did you do?
run it

### What did you see instead?
 2017-10-23 10:06:32 INFO: initializing ciphers... chacha20-ietf-poly1305
 2017-10-23 10:06:32 INFO: listening at 0.0.0.0:1080
 2017-10-23 10:06:32 INFO: running from root user
Illegal instruction

### What is your config in detail (with all sensitive info masked)?
{
    "server": "10.0.0.6",
    "server_port": 3389,
    "local_address":"0.0.0.0",
    "local_port":1080,
    "password": "*********",
    "method": "chacha20-ietf-poly1305",
}

**Comment by madeye** [comment]
`Illegal instruction` means there is a problem with your cross compilation.

**Comment by shom** [comment]
@madeye I build it in mips machine.

**Comment by madeye** [comment]
If so, double check your compiler options.

Incorrect compiler options would cause this kind of issue as well, e.g. floating ops on a MIPS device without floating number support.

**Comment by debiansid** [comment]
build it on Qemu mips again

**Comment by madeye** [comment]
Closed due to inactive.
