### ISSUE TITLE
An error occured when using shadowsocks-libev

### ISSUE THREAD

**Issue by afatpig** [shadowsocks/shadowsocks-libev#1750]
My shadowsocks-libev server is often wrong after several hours' work.
I have client A with IPv4 address and client B with IPv6 address in another computer. Both of them are run in windows. After client A work several hours, it wouldn't work anyway. But client B works normally. And after restart the ss-server, both client A and B work normally, but some error info would be printed by ss-server. Just like this:
```
 2017-10-24 15:16:54 ERROR: failed to handshake with xxx.xxx.xxx.xxx: invalid host name
 2017-10-24 15:16:55 ERROR: failed to handshake with xxx.xxx.xxx.xxx: invalid host name
 2017-10-24 15:16:56 ERROR: failed to handshake with xxx.xxx.xxx.xxx: invalid host name
 2017-10-24 15:16:57 ERROR: failed to handshake with xxx.xxx.xxx.xxx: invalid host name
```
And the same error will apear again after several hours...
I have seen the issue #1188, and updated the ss-server, but it couldn't solve this problem.
My server info:
    CentOS(el7) in DigitalOcean.
    shadowsocks-libev version 3.1.0
My ss config:
```
{
    "server":["[::0]", "0.0.0.0"],
    "server_port":7777,
    "password":"******",
    "method":"aes-256-cfb",
    "timeout":60
}
```
Please help me.

**Comment by madeye** [comment]
According to your log, your client A is blocked due to too many handshake failures.

**Comment by afatpig** [comment]
@madeye 
So, what can I do to make client A work for a long time? Is it clientA or server caused this problem?

**Comment by madeye** [comment]
It means there is an client on your A network is configured incorrectly. Double check your client's configs.

**Comment by afatpig** [comment]
@madeye 
Thanks, but I couldn't find it.
```
{
"configs" : [
  {
"server" : "xx.xx.xx.xx",
"server_port" : 7777,
"password" : "******",
"method" : "aes-256-cfb",
"remarks" : ""}
],
"strategy" : null,
"index" : 1,
"global" : true,
"enabled" : false,
"shareOverLan" : true,
"isDefault" : false,
"localPort" : 1080,
"pacUrl" : null,
"useOnlinePac" : false,
"availabilityStatistics" : false}
```
Is there anything wrong?
Client A works good when it just been started, but it would be wrong after several hours.

**Comment by madeye** [comment]
Closed due to inactive.

**Comment by afatpig** [comment]
That's OK.
It's OK with IPv6.
That wrong on IPv4 network was caused by GFW.

**Comment by CXOldStar** [comment]
@afatpig Hello, I have meet the same problem.Can you tell me how to deal with it?Is it a configure error of server side?
Thanks!
