### ISSUE TITLE
Can I measure the network latency from ss-server to dest host in ss-local or even in socks5-client?

### ISSUE THREAD

**Issue by bxwllzz** [shadowsocks/shadowsocks-libev#1751]
根据目前的代码，在不配置目标主机服务的情况下，是否可以在socks5 client或者在ss-local上实现测量ss-server到目标主机的TCP连接耗时的功能？

对于shadowsocks用作游戏加速服务来说，这样的功能特别有意义。
HTTP服务器有明确的请求响应模型，可以很方便地测试延迟信息。
而游戏服务器，其通讯协议是未知的，而且很有可能禁止ping，这时一般使用tcp ping，也就是测量tcp连接建立的耗时，达到测试网络延迟的目的。

我对Shadowsocks连接过程的理解是这样的：
client <--[socks5]--> ss-local <--[shadowsocks]--> ss-server <--[TCP]--> host
1. client请求连接ss-local；
2. ss-local接受请求，建立socks5连接，并开始连接ss-server；
3. client发送host IP给ss-local；
（此处只考虑目标主机直接给定的IP地址，而非域名）
4. ss-local接收到host IP，等待到ss-server的连接建立成功，（_**A. 此时立刻通过socks5回复连接建立成功**_？）；
3. ss-local到ss-server的连接建立成功，ss-local将host IP发送至ss-server，（_**B. 通过socks5回复连接建立成功**_？）；
3. ss-server接收到host IP，开始连接host；
4. ss-server到host的连接建立成功，~~通知ss-local连接成功~~；
5. ~~ss-local接收到连接成功通知~~，（_**C. 通过socks5通知client连接建立成功**_？）；
6. 开始双向通讯转发...

我的疑问是，ss-local究竟是在何时向socks5客户端响应连接成功，A处、B处或是C处？
- 如果是A处，那么在client上通过计算发送host IP到被响应连接成功之间的时间差，得到的延迟实际是client到ss-local的延迟。必须要修改ss-local的代码，才可以在client上测量client到host的TCP连接耗时。
- 如果是B处，那么在client上通过计算发送host IP到被响应连接成功之间的时间差，得到的延迟实际是client到ss-server的延迟。必须要修改ss-local的代码，才可以在client上测量client到host的TCP连接耗时。
- 如果是C处，那么在client上通过计算发送host IP到被响应连接成功之间的时间差，得到的延迟实际是client到host的延迟。

**更新**
看了一下shadowsocks Python中tcprelay.py的源码，发现ss-server根本不会通知ss-local什么时候连接建立成功。只有host发出数据的时候，才会把数据转发到ss-local。
这么说，如果ss-server连接host成功，而host根本不发数据，从ss-local完全无从判断ss-server到host是什么时候连接成功？？？

**建议**
是否有可能修改ss-server的程序，在兼容当前实现的前提，提醒ss-local连接建立成功？（比如发送0字节数据包）

**Comment by madeye** [comment]
I don't think It's necessary.

Instead, it would be a very dangerous feature that provides obvious protocol characters.

Try TCP ping, if you are only care about the server latency.

**Comment by bxwllzz** [comment]
在本地进行TCP Ping只能测量本地到ss-server的延迟, 以及本地直连目标主机的延迟。无法估计ss-server到目标主机的延迟。
不过这确实是一个很危险的特征, 可以在时间上进行统计分析? 
如果想要隐藏这种特征, 是否可以在目标服务器发回响应时, 顺带把ss-server测量到的TCP连接耗时, 一并打包到响应中?

**Comment by madeye** [comment]
No plan for this.

**Comment by bxwllzz** [comment]
只是考虑一下在实现这种功能, 同时避免暴露特征的可行性。
