### ISSUE TITLE
host name is not avilable, ip address is avilable

### ISSUE THREAD

**Issue by FreeVicto** [shadowsocks/shadowsocks-libev#1752]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?

3.1.0-1

### What operating system are you using?

 OpenWrt Barrier Breaker 14.07

### What did you expect to see?

"host name or ip address of your remote server"

### What did you see instead?

host name is not avilable, ip address is avilable

**Comment by chenhw2** [comment]
It's not a bug, it's a feature.

**Comment by madeye** [comment]
Double check your local DNS settings. Make sure your hostname can be resolved correctly.

**Comment by lixingcong** [comment]
duplicate https://github.com/shadowsocks/luci-app-shadowsocks/issues/61
