### ISSUE TITLE
Again！crypto_aead_xchacha20poly1305_ietf_decrypt: symbol not found

### ISSUE THREAD

**Issue by liaoyangyang** [shadowsocks/shadowsocks-libev#1754]
我已经看了`https://github.com/shadowsocks/shadowsocks-libev/issues/1364`，不过已经close了，就新开个。

错误

```bash
root@OpenWrt:~# ss-local 
Error relocating /usr/bin/ss-local: crypto_aead_xchacha20poly1305_ietf_decrypt: symbol not found
Error relocating /usr/bin/ss-local: crypto_aead_xchacha20poly1305_ietf_encrypt: symbol not found
```

@aa65535 今天我用xiaomi mini使用LEDE ss-local还是不行，报一样的错误issues1364，我在`http://openwrt-dist.sourceforge.net/packages/LEDE/base/mipsel_24kc/`没有找到到libsodium_1.0.12-1的包，系统安装的是1.0.11-2，倒是`http://openwrt-dist.sourceforge.net/packages/OpenWrt/base/ramips/`下面有1.0.12-1，不过不能用，帮忙解决一下吧

附opkg.conf

```bash
dest root /
dest ram /tmp
lists_dir ext /var/opkg-lists
option overlay_root /overlay
#option check_signature 1
src/gz openwrt_dist http://openwrt-dist.sourceforge.net/packages/LEDE/base/mipsel_24kc
src/gz openwrt_dist_luci http://openwrt-dist.sourceforge.net/packages/LEDE/luci
```

**Comment by aa65535** [comment]
到这了安装 http://downloads.lede-project.org/snapshots/packages/mipsel_24kc/packages/

**Comment by liaoyangyang** [comment]
非常感谢，今天刚接触LEDE，好像刷的是release的，话说snapshot是稳定版的吗？是的话我直接刷就行，话说lede有没有直接更新系统的，连内核都直接更新的命令？

**Comment by aa65535** [comment]
我只是建议你安装里面的软件包作为替代。

2017年10月26日 22:02，Liaoyangyang <notifications@github.com>写道：

非常感谢，今天刚接触LEDE，好像刷的是release的，话说snapshot是稳定版的吗？是的话我直接刷就行，话说lede有没有直接更新系统的，连内核都直接更新的命令？

**Comment by joshdrsfsg** [comment]
The version of Shadowsocks in the LEDE "Release" package repositories is very old, but the LUCI interface is very easy to use.  The version of Shadowsocks in the LEDE "SNAPSHOT" package repository is much newer, but more difficult to configure and setup. The advantage of the "SNAPSHOT" packages is that they support the new encryption ciphers as well as many other new features.

OPTION: I've also heard from a friend that the OpenWRT Packages are better maintained than the LEDE packages. You can try to manually install the OpenWRT IPK file: 
[OpenWRT Snapshot Packages for mt7620](https://downloads.openwrt.org/snapshots/trunk/ramips/mt7620/packages/packages/)
[OpenWRT Snapshot Packages for mt7620 - Direct Link to Shadowsocks-Client]
(https://downloads.openwrt.org/snapshots/trunk/ramips/mt7620/packages/packages/shadowsocks-client_0.6-b59d754f838213d60b908aed0b7d4d5a81f273e2_ramips.ipk)

**Comment by joshdrsfsg** [comment]
P.S. The stand-alone Libsodium package for the mt7620 processor is available here in the OpenWRT repository:
https://downloads.openwrt.org/snapshots/trunk/ramips/mt7620/packages/packages/libsodium_1.0.12-1_ramips.ipk
It should be compatible with LEDE Release/Snapshot editions.

**Comment by liaoyangyang** [comment]
@joshdrsfsg Thanks very much，I compiled  libsodium_1.0.12-1 with the release LEDE sdk yesterday，and @aa65535 also pointed the right ipk。

PS： Yesterday I download OPENWRT libsodium_1.0.12-1，but can not install，so I compiled LEDE  libsodium_1.0.12-1，it works。
