### ISSUE TITLE
Bug in socks5 protocol 

### ISSUE THREAD

**Issue by iterprise** [shadowsocks/shadowsocks-libev#1756]
./ss-local -s 127.0.0.1 -p 8388 -k XXX -m chacha20-ietf-poly1305 -l 4443 -v
 2017-10-27 12:17:31 INFO: initializing ciphers... chacha20-ietf-poly1305
 2017-10-27 12:17:31 INFO: listening at 127.0.0.1:4443

The cipher isn't matter.
Try to use the curl 

curl https://google.com/ --socks5 127.0.0.1:4443
curl: (35) gnutls_handshake() failed: The TLS connection was non-properly terminated.    

LOG:
 2017-10-27 12:19:26 ERROR: server_recv_cb: 0
 2017-10-27 12:19:26 ERROR: server_recv_cb: 1
 2017-10-27 12:19:26 ERROR: Resp size: 10
 2017-10-27 12:19:26 ERROR: server_recv_cb: 2
 2017-10-27 12:19:26 INFO: connect to google.com:443
 2017-10-27 12:19:26 ERROR: server_recv_cb: 5

It happens because 'curl' sends socks5 packages by parts. And ss-local reads it wrongly (lose the server stage).
Can you fix it?

**Comment by madeye** [comment]
I cannot reproduce your issue.

What's the version of your curl and shadowsocks-libev?

**Comment by iterprise** [comment]
shadowsocks-libev 3.0.8

curl 7.47.0 (x86_64-pc-linux-gnu) libcurl/7.47.0 GnuTLS/3.4.10 zlib/1.2.8 libidn/1.32 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets

**Comment by madeye** [comment]
Please update your shadowsocks-libev to 3.1.0 and curl to 7.56.

I didn't see any issue with the latest versions of these two software.

**Comment by iterprise** [comment]
I updated to shadowsocks-libev to 3.1.0

curl still curl 7.47.0 you need to fix it anyway.
curl https://google.com/ --socks5 127.0.0.1:4443                                                                                                                                                                                             
curl: (35) gnutls_handshake() failed: The TLS connection was non-properly terminated.   

I happens when client send 0x05, 0x01, 0x00, 0x03 and then send another data (hostName.length and length). If client send it in one time the problem has gone. You can try it without curl

**Comment by madeye** [comment]
> I happens when client send 0x05, 0x01, 0x00, 0x03 and then send another data (hostName.length and hostName, port). If client send it in one time the problem has gone. You can try it without curl

We always handle partial SOCKS5 request correctly, which is handled here: https://github.com/shadowsocks/shadowsocks-libev/blob/master/src/local.c#L504. So, I don't think it's the problem. 

To verify it's not a specific issue for curl 7.47.0, I also tried shadowsocks-libev 3.1.0 with curl 7.47.0. It just works well.

**Comment by iterprise** [comment]
it's strange. I have the problem with curl and my java client. I'll try to get more information

**Comment by madeye** [comment]
In fact, curl always sends the whole request. You can verify this by adding `-v` to your curl command line.

**Comment by madeye** [comment]
And according to your log,

```
2017-10-27 12:19:26 INFO: connect to google.com:443
2017-10-27 12:19:26 ERROR: server_recv_cb: 5
```

It means the SOCKS5 header is already parsed successfully and connection is being established.

**Comment by iterprise** [comment]
SS parsed correctly, but returns extra bytes

**Comment by iterprise** [comment]
`# -*- coding: utf-8 -*-

import socket
import time

sock = socket.socket()
sock.connect(('localhost', 4443))

sock.send(bytearray([0x05, 0x01, 0x00]))
data = sock.recv(2)
print repr(data) 

sock.send(bytearray([0x05, 0x01, 0x00, 0x03]))



sock.send(bytearray([0x0a]))
sock.send('google.com')
sock.send(bytearray([0x00, 0x50]))

data = sock.recv(4) # read
print repr(data) 

data = sock.recv(4) # read ip
print repr(data) 

data = sock.recv(2) # read port
print repr(data) 


data = sock.recv(300) # read extra
print repr(data) 


sock.close()
`

Try this client (python). You can see, i read the socks5 answer two times

**Comment by Mr-indescribable** [comment]
@iterprise 
I tested your Python code, it works as you said. And maybe there are some issues in the code.
When you merge your 2nd socks5 request, ss-local will not reply double time.

Here is my code:

```python
#!/usr/bin/python3.6
#coding: utf-8

import struct
import socket
import time

sock = socket.socket()
sock.connect(('localhost', 36725))

sock.send(b'\x05\x01\x00')
print(sock.recv(128))

d2s = b'\x05\x01\x00\x03www.google.com' + struct.pack('H', 443)
sock.send(d2s)
print(sock.recv(128))

time.sleep(0.1)
print('--------------')
print(sock.recv(128))

sock.close()
```

------------------------

output:
```
$ ./socks5.py
b'\x05\x00'
b'\x05\x00\x00\x01\x00\x00\x00\x00\x00\x00'
--------------

```

------------

BTW. The 2nd request in your code is not correct. There is one extra byte in the stream.
> sock.send(bytearray([0x0a]))

Here is the doc from rfc1928:

```
   The SOCKS request is formed as follows:

        +----+-----+-------+------+----------+----------+
        |VER | CMD |  RSV  | ATYP | DST.ADDR | DST.PORT |
        +----+-----+-------+------+----------+----------+
        | 1  |  1  | X'00' |  1   | Variable |    2     |
        +----+-----+-------+------+----------+----------+

     Where:

          o  VER    protocol version: X'05'
          o  CMD
             o  CONNECT X'01'
             o  BIND X'02'
             o  UDP ASSOCIATE X'03'
          o  RSV    RESERVED
          o  ATYP   address type of following address
             o  IP V4 address: X'01'
             o  DOMAINNAME: X'03'
             o  IP V6 address: X'04'
          o  DST.ADDR       desired destination address
          o  DST.PORT desired destination port in network octet
             order

```

**Comment by madeye** [comment]
Please try 26ae365.

**Comment by iterprise** [comment]
I doesn't work. Extra data has gone but i can read data from google.com

```
# -*- coding: utf-8 -*-

import socket
import time

sock = socket.socket()
proxy = False
if proxy:
    sock.connect(('localhost', 4443))

    sock.sendall(bytearray([0x05, 0x01, 0x00]))
    data = sock.recv(2)
    print repr(data) 
    sock.sendall(bytearray([0x05, 0x01, 0x00, 0x03]))
    sock.sendall(bytearray([0x0a]))
    sock.sendall('google.com')
    sock.sendall(bytearray([0x00, 0x50]))

    data = sock.recv(4) # read
    print repr(data) 

    data = sock.recv(4) # read ip
    print repr(data) 

    data = sock.recv(2) # read port
    print repr(data) 
else:
    sock.connect(('google.com', 80))

sock.sendall("GET / HTTP/1.1\r\nHost: google.com\r\n\r\n")

data = sock.recv(20) # response
print repr(data) 

sock.close()
```
if proxy = False 
'HTTP/1.1 302 Found\r\n'
else 
''

May be it's my falt but it looks like a bag

**Comment by madeye** [comment]
I can get right response when enabling proxy:

```
'\x05\x00'
'\x05\x00\x00\x01'
'\x00\x00\x00\x00'
'\x00\x00'
'HTTP/1.1 301 Moved Permanently\r\nLocation: http://www.google.com/\r\nContent-Type: text/html; charset=UTF-8\r\nDate: Mon, 30 Oct 2017 11:49:00 GMT\r\nExpires: Wed, 29 Nov 2017 11:49:00 GMT\r\nCache-Control: public, max-age=2592000\r\nServer: gws\r\nContent-Length: 219\r\nX-XSS-Protection: 1; mode=block\r\nX-Frame-Options: SAMEORIGIN\r\n\r\n<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">\n<TITLE>301 Moved</TITLE></HEAD><BODY>\n<H1>301 Moved</H1>\nThe document has moved\n<A HREF="http://www.google.com/">here</A>.\r\n</BODY></HTML>\r\n'
```

Without proxy

```
'HTTP/1.1 301 Moved Permanently\r\nLocation: http://www.google.com/\r\nContent-Type: text/html; charset=UTF-8\r\nDate: Mon, 30 Oct 2017 11:49:33 GMT\r\nExpires: Wed, 29 Nov 2017 11:49:33 GMT\r\nCache-Control: public, max-age=2592000\r\nServer: gws\r\nContent-Length: 219\r\nX-XSS-Protection: 1; mode=block\r\nX-Frame-Options: SAMEORIGIN\r\n\r\n<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">\n<TITLE>301 Moved</TITLE></HEAD><BODY>\n<H1>301 Moved</H1>\nThe document has moved\n<A HREF="http://www.google.com/">here</A>.\r\n</BODY></HTML>\r\n'
```

**Comment by madeye** [comment]
What's your server's version?

**Comment by madeye** [comment]
Since curl never sent partial SOCKS5 request, I think the problem is on your server side.

**Comment by iterprise** [comment]
You are right. I just restarted my server. Now it works fine, thank you.

**Comment by sijidou** [comment]
ss-manager 不支持 --no-delay参数诶。
