### ISSUE TITLE
QUESTIONS: Reuse-Port Settings on Ubuntu Server

### ISSUE THREAD

**Issue by greenbambooaaron** [shadowsocks/shadowsocks-libev#1758]
**QUESTION:** I'm investigating all of the options for shadowsocks and I have some newbie questions about REUSE-PORT. (I'm not sure how to post questions versus issues, so if someone has some guidance on that, it would be welcome as well)

1. Is _reuse-port_ enabled by default? (Meaning, if I don't specify it in the config file, it is enabled)
2. Do I have to adjust anything _in the OS_ for port reuse to work properly?  For example, on Ubuntu do I need to change the following TCP Setting: **net.ipv4.tcp_tw_reuse = 1**
3. Under what scenario would I _disable_ reuse-port? Just troubleshooting? Or on an old unsupported OS?

**--reuse-port**
Enable port reuse.
_Only available with Linux kernel > 3.9.0._

### What version of shadowsocks-libev are you using?
3.1.0

### What operating system are you using?
Ubuntu 16.04.3

### What did you do?
Enabled reuseport in the config file

### What did you expect to see?
...I don't know...

### What did you see instead?
-

**Comment by madeye** [comment]
https://lwn.net/Articles/542629/

Don't enable it if you don't know how it works. It's disabled by default.

**Comment by greenbambooaaron** [comment]
Thank you Max! I'll research it and see if it's useful to me.
