### ISSUE TITLE
ubuntu 17.10 error using shadowsocks-libev 

### ISSUE THREAD

**Issue by shurview** [shadowsocks/shadowsocks-libev#1760]
### What version of shadowsocks-libev are you using?

3.0.8
### What operating system are you using?

ubuntu 17.10
### What did you do?

apt install shadowsocks-libev
### What did you expect to see?

It works.
### What did you see instead?
Oct 30 12:14:04 vultr systemd[1]: Started Shadowsocks-libev Default Server Service.
Oct 30 12:14:04 vultr ss-server[31081]: /usr/bin/ss-server: symbol lookup error: /usr/bin/ss-server: undefined symbol: crypto_aead_xchacha20poly1305_ietf_encrypt
Oct 30 12:14:04 vultr systemd[1]: shadowsocks-libev.service: Main process exited, code=exited, status=127/n/a
Oct 30 12:14:04 vultr systemd[1]: shadowsocks-libev.service: Unit entered failed state.
Oct 30 12:14:04 vultr systemd[1]: shadowsocks-libev.service: Failed with result 'exit-code'.

**Comment by greenbambooaaron** [comment]
Is libsodium-dev installed?

https://packages.ubuntu.com/search?keywords=libsodium-dev

**Comment by shurview** [comment]
libsodium18 is installed, but libsodium-dev is not.

**Comment by greenbambooaaron** [comment]
Can you post the contents of your /etc/shadowsock-libev/config.json file with the IP address and password masked?  I just installed 17.10 server (64 bit) from scratch, installed the shadowsocks-libev package and I can initialize chacha20-ietf-poly1305 and xchacha20-ietf-poly1305 without errors.

Some other quick comments:
1. If your error message is verbose, then you've inputed the cipher name incorrectly, there is no xchacha20poly1305_ietf.
2. I ran sudo apt dist-upgrade during my initial setup by habit, you might try that if you think your config file is correct.

P.S. - I'm a newbie at this, so I'm just trying to be helpful until someone with more knowledge responds.

**Comment by shurview** [comment]
{
    "server":["[::0]", "0.0.0.0"],
    "server_port":***,
    "local_address": "127.0.0.1",
    "local_port":***,
    "password":"***",
    "timeout":300,
    "method":"chacha20-ietf-poly1305",
    "plugin":"obfs-server",
    "plugin_opts":"obfs=http"
}

1.There it is [https://download.libsodium.org/doc/secret-key_cryptography/xchacha20-poly1305_construction.html](url)

2.It doesn't work.

**Comment by terrytw** [comment]
You need to install libsodium. (version >=1.0.12)

**Comment by shurview** [comment]
libsodium has already installed.

**Comment by terrytw** [comment]
Double check the version. And you need libsodium-dev.

**Comment by shurview** [comment]
Actually both were installed.Version is 1.0.13

**Comment by terrytw** [comment]
I'm baffled. It is definitely related to libsodium. Try apt-get purge libsodium-dev and install it again.

**Comment by shurview** [comment]
I reinstalled libsodium-dev libsodium18 shadowsocks-libev, got nothing better.

**Comment by terrytw** [comment]
Sorry, I can't help. But I believe it is definitely related to libsodium.

**Comment by shurview** [comment]
Absolutely.

**Comment by greenbambooaaron** [comment]
Hi Shurview,

Sorry to hear it's still not working for you.  From other issue points, it seems to be working for others on 17.10, so I also suspect it's something with your server.

To eliminate LIBSODIUM, you can build the latest LIBSODIUM from source.  This blog post's work for me on most versions of Ubuntu: [HOW TO: Build Libsodium from source on Ubuntu 16.04 LTS](https://enterpriseadmins.blogspot.com/2017/10/how-to-build-libsodium-from-source-on.html)

Some other troubleshooting:
1. Install Shadowsocks-libev from source (3.0.8 is not the latest). [BLOG](https://enterpriseadmins.blogspot.com/2017/10/how-to-build-shadowsock-libev-from.html)
2. I would also temporarily remove the SIMPLE-OBFS options from your config.  I installed a new 17.10 server, ran the apt install for shadowsocks-libev, setup the config, and my proxy started immediately - but I didn't use OBFS)
