### ISSUE TITLE
manual compile with libsodium 1.0.5 no problem?

### ISSUE THREAD

**Issue by manjuprajna** [shadowsocks/shadowsocks-libev#1761]
### What version of shadowsocks-libev are you using?
3.1.0

### What operating system are you using?
CentOS 7.4.1708 kernel 4.13.10 
libsodium-1.0.5 libsodium-devel-1.0.5 mbedtls-2.6.0 
### What did you do?
manul compile 

### What did you expect to see?
see some error message

### What did you see instead?
compiled successfully

### What is your config in detail (with all sensitive info masked)?
normal as readme listed

according to readme: **"If your system is too old to provide libmbedtls and libsodium (later than v1.0.8), you will need to either install those libraries manually or upgrade your system."**
but acctually I just installed libsodium 1.0.5 by yum from epel-release, than compile succeed, no error message, and then I used for two days, nothing unusual, no problem at all.

so I doubt why you recommend libsodium 1.08 and newer?

**Comment by terrytw** [comment]
Which encryption method are you using right now?

**Comment by manjuprajna** [comment]
@terrytw chacha20-ietf
do you mean if I use any aead encryption will cause problem?
but why no error message while I was compiling using libsodium 1.0.5?

**Comment by madeye** [comment]
It can build but won't work with latest AEAD ciphers.

**Comment by manjuprajna** [comment]
@madeye I tested just now, chacha20-ietf-poly1305 and aes-256-gcm both working, but xchacha20-ietf-poly1305 can't work.
thank you!
