### ISSUE TITLE
Shadowsocks libev node cannot be connected with Windows version, but ok with Android ones

### ISSUE THREAD

**Issue by Choutouketsu** [shadowsocks/shadowsocks-libev#1762]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
Shadowsocks libev 3.1.0

### What operating system are you using?
Win 7

### What did you do?
I was connecting the Shadowsocks libev node with my Shadowsocks windows, Sockscap64 and an Android client

### What did you expect to see?
I was hoping I could make it to surf Google on Windows PCs

### What did you see instead?
Only android verison can get correct connection and surf Google Facebook and Twitter

### What is your config in detail (with all sensitive info masked)?
My config is correct, as I could still surf with android clients. Most importantly, some days ago, I could also surf with my Windows PCs. I rebooted my Debian server but still the same issue. How interesting, can anybody help troubleshoot?

**Comment by madeye** [comment]
Closed due to inactivity.
