### ISSUE TITLE
ubuntu 17.10 building error from source

### ISSUE THREAD

**Issue by moonwater** [shadowsocks/shadowsocks-libev#1764]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
Current version: 3.1.0 
git glog
cc1bb4c - (HEAD -> master, origin/master, origin/HEAD) format with .uncrustify.cfg (#1759) 

### What operating system are you using?
ubuntu 17.10

### What did you do?
git clone https://github.com/shadowsocks/shadowsocks-libev.git
cd shadowsocks-libev
git submodule update --init --recursive

mkdir -p ~/build-area/
cp ./scripts/build_deb.sh ~/build-area/
cd ~/build-area
./build_deb.sh

### What did you expect to see?
expect a successful build.
actually it works for ubuntu 17.04

### What did you see instead?
Here is the logs begin with errors:
Setting up libxml-parser-perl (2.44-2build3) ...
Setting up libxml-sax-expat-perl (0.40-2) ...
update-perl-sax-parsers: Registering Perl SAX parser XML::SAX::Expat with priority 50...
update-perl-sax-parsers: Updating overall Perl SAX parser modules info file...
Replacing config file /etc/perl/XML/SAX/ParserDetails.ini with new version
Processing triggers for libc-bin (2.26-0ubuntu2) ...
Your system ubuntu/artful is not supported yet.
Please report issue:
    https://github.com/shadowsocks/shadowsocks-libev/issues/new
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package 'libbloom-dev' is not installed, so not removed
Package 'libcork-dev' is not installed, so not removed
Package 'libcorkipset-dev' is not installed, so not removed
Package 'libmbedtls-dev' is not installed, so not removed
Package 'libsodium-dev' is not installed, so not removed
The following packages were automatically installed and are no longer required:
  cowbuilder cowdancer dctrl-tools debootstrap devscripts diffstat dput libapt-pkg-perl libarchive-cpio-perl libarchive-zip-perl
  libauthen-sasl-perl libb-hooks-endofscope-perl libcgi-fast-perl libcgi-pm-perl libclass-accessor-perl libclass-method-modifiers-perl
  libclass-xsaccessor-perl libclone-perl libdata-optlist-perl libdevel-globaldestruction-perl libdigest-hmac-perl libdistro-info-perl
  libemail-valid-perl libencode-locale-perl libexporter-tiny-perl libfcgi-perl libfile-basedir-perl libfile-chdir-perl
  libfile-homedir-perl libfile-listing-perl libfile-stripnondeterminism-perl libfile-which-perl libfont-afm-perl
  libgetopt-long-descriptive-perl libgit-wrapper-perl libhtml-form-perl libhtml-format-perl libhtml-parser-perl libhtml-tagset-perl
  libhtml-tree-perl libhttp-cookies-perl libhttp-daemon-perl libhttp-date-perl libhttp-message-perl libhttp-negotiate-perl
  libimport-into-perl libio-html-perl libio-pty-perl libio-socket-inet6-perl libio-socket-ssl-perl libio-string-perl libio-stringy-perl
  libipc-run-perl libipc-system-simple-perl liblist-compare-perl liblist-moreutils-perl liblwp-mediatypes-perl liblwp-protocol-https-perl
  libmailtools-perl libmodule-implementation-perl libmodule-runtime-perl libmoo-perl libnamespace-clean-perl libnet-dns-perl
  libnet-domain-tld-perl libnet-http-perl libnet-ip-perl libnet-smtp-ssl-perl libnet-ssleay-perl libnumber-compare-perl
  libnumber-range-perl libpackage-stash-perl libpackage-stash-xs-perl libparams-classify-perl libparams-util-perl libparams-validate-perl
  libparse-debianchangelog-perl libpath-iterator-rule-perl libpath-tiny-perl libperlio-gzip-perl libpod-constants-perl librole-tiny-perl
  libsocket6-perl libsort-key-perl libsort-versions-perl libstrictures-perl libstring-copyright-perl libstring-escape-perl
  libsub-exporter-perl libsub-exporter-progressive-perl libsub-identify-perl libsub-install-perl libsub-name-perl libsub-quote-perl
  libtext-glob-perl libtext-levenshtein-perl libtimedate-perl libtry-tiny-perl libunicode-utf8-perl liburi-perl libvariable-magic-perl
  libwww-perl libwww-robotrules-perl libxdelta2 libxml-libxml-perl libxml-namespacesupport-perl libxml-parser-perl libxml-sax-base-perl
  libxml-sax-expat-perl libxml-sax-perl libxml-simple-perl libyaml-libyaml-perl licensecheck lintian patchutils pbuilder pbzip2
  perl-openssl-defaults python-dateutil python3-magic python3-unidiff t1utils unzip xdelta
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  debhelper* dh-autoreconf* dh-strip-nondeterminism* equivs* git-buildpackage* pristine-tar*
0 upgraded, 0 newly installed, 6 to remove and 0 not upgraded.
After this operation, 6201 kB disk space will be freed.
(Reading database ... 78660 files and directories currently installed.)
Removing equivs (2.1.0) ...
Removing git-buildpackage (0.8.18) ...
Removing pristine-tar (1.41) ...
Removing debhelper (10.7.2ubuntu2) ...
Removing dh-autoreconf (14) ...
Removing dh-strip-nondeterminism (0.038-1) ...
Processing triggers for man-db (2.7.6.1-2) ...
(Reading database ... 77759 files and directories currently installed.)
Purging configuration files for git-buildpackage (0.8.18) ...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libcork-build-deps
E: Unable to locate package libcorkipset-build-deps
E: Unable to locate package libsodium-build-deps
E: Unable to locate package mbedtls-build-deps
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libbloom-build-deps
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package simple-obfs-build-deps
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package shadowsocks-libev-build-deps
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be REMOVED:
  cowbuilder cowdancer dctrl-tools debootstrap devscripts diffstat dput libapt-pkg-perl libarchive-cpio-perl libarchive-zip-perl
  libauthen-sasl-perl libb-hooks-endofscope-perl libcgi-fast-perl libcgi-pm-perl libclass-accessor-perl libclass-method-modifiers-perl
  libclass-xsaccessor-perl libclone-perl libdata-optlist-perl libdevel-globaldestruction-perl libdigest-hmac-perl libdistro-info-perl
  libemail-valid-perl libencode-locale-perl libexporter-tiny-perl libfcgi-perl libfile-basedir-perl libfile-chdir-perl
  libfile-homedir-perl libfile-listing-perl libfile-stripnondeterminism-perl libfile-which-perl libfont-afm-perl
  libgetopt-long-descriptive-perl libgit-wrapper-perl libhtml-form-perl libhtml-format-perl libhtml-parser-perl libhtml-tagset-perl
  libhtml-tree-perl libhttp-cookies-perl libhttp-daemon-perl libhttp-date-perl libhttp-message-perl libhttp-negotiate-perl
  libimport-into-perl libio-html-perl libio-pty-perl libio-socket-inet6-perl libio-socket-ssl-perl libio-string-perl libio-stringy-perl
  libipc-run-perl libipc-system-simple-perl liblist-compare-perl liblist-moreutils-perl liblwp-mediatypes-perl liblwp-protocol-https-perl
  libmailtools-perl libmodule-implementation-perl libmodule-runtime-perl libmoo-perl libnamespace-clean-perl libnet-dns-perl
  libnet-domain-tld-perl libnet-http-perl libnet-ip-perl libnet-smtp-ssl-perl libnet-ssleay-perl libnumber-compare-perl
  libnumber-range-perl libpackage-stash-perl libpackage-stash-xs-perl libparams-classify-perl libparams-util-perl libparams-validate-perl
  libparse-debianchangelog-perl libpath-iterator-rule-perl libpath-tiny-perl libperlio-gzip-perl libpod-constants-perl librole-tiny-perl
  libsocket6-perl libsort-key-perl libsort-versions-perl libstrictures-perl libstring-copyright-perl libstring-escape-perl
  libsub-exporter-perl libsub-exporter-progressive-perl libsub-identify-perl libsub-install-perl libsub-name-perl libsub-quote-perl
  libtext-glob-perl libtext-levenshtein-perl libtimedate-perl libtry-tiny-perl libunicode-utf8-perl liburi-perl libvariable-magic-perl
  libwww-perl libwww-robotrules-perl libxdelta2 libxml-libxml-perl libxml-namespacesupport-perl libxml-parser-perl libxml-sax-base-perl
  libxml-sax-expat-perl libxml-sax-perl libxml-simple-perl libyaml-libyaml-perl licensecheck lintian patchutils pbuilder pbzip2
  perl-openssl-defaults python-dateutil python3-magic python3-unidiff t1utils unzip xdelta
0 upgraded, 0 newly installed, 124 to remove and 0 not upgraded.
After this operation, 24.3 MB disk space will be freed.
(Reading database ... 77757 files and directories currently installed.)
Removing cowbuilder (0.85) ...
Removing cowdancer (0.85) ...
Removing dctrl-tools (2.24-2build1) ...
Removing pbuilder (0.228.9) ...
Removing debootstrap (1.0.91ubuntu1) ...
Removing devscripts (2.17.9build1) ...
Removing lintian (2.5.55) ...
Removing diffstat (1.61-1build1) ...
Removing dput (0.9.6.4ubuntu4) ...
Removing libapt-pkg-perl (0.1.33) ...
Removing libarchive-cpio-perl (0.10-1) ...
Removing libfile-stripnondeterminism-perl (0.038-1) ...
Removing libarchive-zip-perl (1.59-1) ...
Removing libauthen-sasl-perl (2.1600-1) ...
Removing licensecheck (3.0.30-1) ...
Removing libnamespace-clean-perl (0.27-1) ...
Removing libb-hooks-endofscope-perl (0.21-1) ...
Removing libcgi-fast-perl (1:2.12-1) ...
Removing libparse-debianchangelog-perl (1.2.0-12) ...
Removing libcgi-pm-perl (4.36-1) ...
Removing libclass-accessor-perl (0.34-1) ...
Removing libmoo-perl (2.003002-1) ...
Removing librole-tiny-perl (2.000005-1) ...
Removing libclass-method-modifiers-perl (2.12-1) ...
Removing libclass-xsaccessor-perl (1.19-2build7) ...
Removing libclone-perl (0.38-2build2) ...
Removing libgetopt-long-descriptive-perl (0.100-1) ...
Removing libsub-exporter-perl (0.986-1) ...
Removing libdata-optlist-perl (0.110-1) ...
Removing libdevel-globaldestruction-perl (0.14-1) ...
Removing libemail-valid-perl (1.202-1) ...
Removing libnet-dns-perl (1.10-2) ...
Removing libdigest-hmac-perl (1.03+dfsg-1) ...
Removing libdistro-info-perl (0.17) ...
Removing libxml-simple-perl (2.24-1) ...
Removing libxml-sax-expat-perl (0.40-2) ...
update-perl-sax-parsers: Unregistering Perl SAX parser XML::SAX::Expat with priority 50...
update-perl-sax-parsers: Updating overall Perl SAX parser modules info file...
Replacing config file /etc/perl/XML/SAX/ParserDetails.ini with new version
Removing libxml-parser-perl (2.44-2build3) ...
Removing libhtml-form-perl (6.03-1) ...
Removing liblist-moreutils-perl (0.416-1build3) ...
Removing libstring-copyright-perl (0.003005-1) ...
Removing libexporter-tiny-perl (0.042-1) ...
Removing libfcgi-perl (0.78-2build1) ...
Removing libfile-basedir-perl (0.07-1) ...
Removing libgit-wrapper-perl (0.047-1) ...
Removing libfile-chdir-perl (0.1008-1) ...
Removing libfile-homedir-perl (1.00-1) ...
Removing libfile-which-perl (1.21-1) ...
Removing libhtml-format-perl (2.12-1) ...
Removing libfont-afm-perl (1.20-2) ...
Removing libhttp-daemon-perl (6.01-1) ...
Removing libimport-into-perl (1.002005-1) ...
Removing libipc-run-perl (0.96-1) ...
Removing libio-pty-perl (1:1.08-1.1build4) ...
Removing libio-socket-inet6-perl (2.72-2) ...
Removing libmailtools-perl (2.18-1) ...
Removing libnet-smtp-ssl-perl (1.04-1) ...
Removing libio-string-perl (1.08-3) ...
Removing libio-stringy-perl (2.111-2) ...
Removing libipc-system-simple-perl (1.25-3) ...
Removing liblist-compare-perl (0.53-1) ...
Removing libparams-validate-perl (1.29-1) ...
Removing libpackage-stash-perl (0.37-1) ...
Removing libmodule-implementation-perl (0.09-1) ...
Removing libmodule-runtime-perl (0.014-2) ...
Removing libnet-domain-tld-perl (1.75-1) ...
Removing libnet-ip-perl (1.26-1) ...
Removing libpath-iterator-rule-perl (1.009-1) ...
Removing libnumber-compare-perl (0.03-1) ...
Removing libnumber-range-perl (0.12-1) ...
Removing libpackage-stash-xs-perl (0.28-3build2) ...
Removing libparams-classify-perl (0.013-8build1) ...
Removing libparams-util-perl (1.07-3build3) ...
Removing libpath-tiny-perl (0.100-1) ...
Removing libperlio-gzip-perl (0.19-1build3) ...
Removing libpod-constants-perl (0.19-1) ...
Removing libsocket6-perl (0.27-1build2) ...
Removing libsort-key-perl (1.33-1build5) ...
Removing libsort-versions-perl (1.62-1) ...
Removing libstrictures-perl (2.000003-1) ...
Removing libstring-escape-perl (2010.002-1) ...
Removing libsub-exporter-progressive-perl (0.001013-1) ...
Removing libsub-identify-perl (0.12-2build3) ...
Removing libsub-install-perl (0.928-1) ...
Removing libsub-name-perl (0.21-1build1) ...
Removing libsub-quote-perl (2.004000-1) ...
Removing libtext-glob-perl (0.10-1) ...
Removing libtext-levenshtein-perl (0.13-1) ...
Removing libtry-tiny-perl (0.28-1) ...
Removing libunicode-utf8-perl (0.60-1build4) ...
Removing libvariable-magic-perl (0.61-1build1) ...
Removing xdelta (1.1.3-9.1ubuntu1) ...
Removing libxdelta2 (1.1.3-9.1ubuntu1) ...
Removing libxml-libxml-perl (2.0128+dfsg-3) ...
update-perl-sax-parsers: Unregistering Perl SAX parser XML::LibXML::SAX::Parser with priority 50...
update-perl-sax-parsers: Unregistering Perl SAX parser XML::LibXML::SAX with priority 50...
update-perl-sax-parsers: Updating overall Perl SAX parser modules info file...
Replacing config file /etc/perl/XML/SAX/ParserDetails.ini with new version
Removing libxml-sax-perl (0.99+dfsg-2ubuntu1) ...
update-perl-sax-parsers: Unregistering Perl SAX parser XML::SAX::PurePerl with priority 50...
update-perl-sax-parsers: Updating overall Perl SAX parser modules info file...
Removing libxml-namespacesupport-perl (1.11-1) ...
Removing libxml-sax-base-perl (1.07-1) ...
Removing libyaml-libyaml-perl (0.63-2build1) ...
Removing patchutils (0.3.4-2) ...
Removing pbzip2 (1.1.9-1) ...
Removing python-dateutil (2.6.0-1) ...
Removing python3-magic (1:5.32-1) ...
Removing python3-unidiff (0.5.4-1) ...
Removing t1utils (1.40-2) ...
Removing unzip (6.0-21ubuntu1) ...
Removing libwww-perl (6.15-2) ...
Removing libfile-listing-perl (6.04-1) ...
Removing libhtml-tree-perl (5.03-2) ...
Removing libhtml-parser-perl (3.72-3build1) ...
Removing libhtml-tagset-perl (3.20-3) ...
Removing libhttp-cookies-perl (6.01-1) ...
Removing libhttp-negotiate-perl (6.00-2) ...
Removing libwww-robotrules-perl (6.01-1) ...
Removing liblwp-protocol-https-perl (6.07-2) ...
Removing libhttp-message-perl (6.11-1) ...
Removing libencode-locale-perl (1.05-1) ...
Removing libhttp-date-perl (6.02-1) ...
Removing libio-html-perl (1.001-1) ...
Removing libio-socket-ssl-perl (2.050-1) ...
Removing liblwp-mediatypes-perl (6.02-1) ...
Removing libnet-http-perl (6.16-1) ...
Removing libnet-ssleay-perl (1.80-1build1) ...
Removing libtimedate-perl (2.3000-2) ...
Removing liburi-perl (1.72-1) ...
Removing perl-openssl-defaults:amd64 (3) ...
Processing triggers for mime-support (3.60ubuntu1) ...
Processing triggers for libc-bin (2.26-0ubuntu2) ...
Processing triggers for man-db (2.7.6.1-2) ...

**Comment by rogers0** [comment]
Yes, build script need to update to support "Artful Aardvark".

**Comment by greenbambooaaron** [comment]
It's true that the script might need to be updates, nevertheless I was able to build from source and run ss-server on Ubuntu 17.10 x64 with the following commands:

_Update Ubuntu Server_
**sudo apt update && sudo apt dist-upgrade**

_Install Core APKs (not all required, but my favorite set)_
**sudo apt install --no-install-recommends build-essential autoconf libtool libssl-dev gawk debhelper dh-systemd init-system-helpers pkg-config asciidoc xmlto apg libpcre3-dev zlib1g-dev libev-dev libsodium-dev vim git automake libmbedtls-dev mtr dnscrypt-proxy fail2ban sendmail ufw libc-ares-dev**

_Clone and Make_
**cd /tmp && git clone https://github.com/shadowsocks/shadowsocks-libev.git && cd shadowsocks-libev && git submodule update --init --recursive && ./autogen.sh && ./configure && make && sudo make install && cd .. && rm shadowsocks-libev -r -f**

**sudo mkdir /etc/shadowsocks-libev && sudo vim /etc/shadowsocks-libev/config.json**

_Enter config info, save, and then run ss-server. Tada! Proxy is up and running._

**Comment by moonwater** [comment]
Hi, greenbambooaaron
Thanks for the solution, it works on my new ubuntu 17.10 box.
But for the scripts:
 
```
mkdir -p ~/build-area/
cp ./scripts/build_deb.sh ~/build-area/
cd ~/build-area
./build_deb.sh
```
it is different, it makes the deb packages.
The Issue is still open.

**Comment by rogers0** [comment]
@moonwater please try the patch below.
you can use "git am 0001-xxx.txt" to apply the patch.

[0001-scripts-build_deb.sh-Support-ubuntu-artful-and-bioni.txt](https://github.com/shadowsocks/shadowsocks-libev/files/1434367/0001-scripts-build_deb.sh-Support-ubuntu-artful-and-bioni.txt)

**Comment by moonwater** [comment]
@rogers0 
Thanks a lot, it works.
