### ISSUE TITLE
How to compiled libsodium_1.0.12-1 with the release LEDE sdk?

### ISSUE THREAD

**Issue by SuperSuperSuperSuper5** [shadowsocks/shadowsocks-libev#1765]
### What version of shadowsocks-libev are you using?

shadowsocks-libev_3.1.0-1_arm_cortex-a53_neon-vfpv4.ipk

### What operating system are you using?

LEDE.

### What did you do?

I want to start the shadowsocks but it throw many errors like this:

```
root@LEDE:/etc/init.d# ./shadowsocks start
Error relocating /usr/bin/ss-redir: crypto_aead_xchacha20poly1305_ietf_decrypt: symbol not found
Error relocating /usr/bin/ss-redir: crypto_aead_xchacha20poly1305_ietf_encrypt: symbol not found
Error relocating /usr/bin/ss-local: crypto_aead_xchacha20poly1305_ietf_decrypt: symbol not found
Error relocating /usr/bin/ss-local: crypto_aead_xchacha20poly1305_ietf_encrypt: symbol not found
```

and I google the solution, and in

https://github.com/shadowsocks/shadowsocks-libev/issues/1754

the @aa65535 say: we need to install libsodium_1.0.12-1 instead of libsodium_1.0.11-5

but I can NOT found the libsodium_1.0.12-1 install package suit for `Raspberry 3B`

Also in the https://github.com/shadowsocks/shadowsocks-libev/issues/1754 last, they say should compiled libsodium_1.0.12-1 with the release LEDE sdk, but I don't know how to compiled

### What did you expect to see?

Success.

### What did you see instead?

Errors.

### What is your config in detail (with all sensitive info masked)?

Have this thing?

**Comment by terrytw** [comment]
LOL. If you use raspbian, then you can find it here: 
https://packages.debian.org/stretch-backports/armhf/libsodium-dev/download
https://packages.debian.org/stretch-backports/armhf/libsodium18/download

Unfortunately you've decided to go a rather unusual route to install LEDE on raspberry. 
This may help: https://github.com/shadowsocks/openwrt-shadowsocks
(It is a guide about how to compile shadowsocks with openwrt SDK)

**Comment by SuperSuperSuperSuper5** [comment]
@terrytw Thanks for you answer, I had looked the page at
https://packages.debian.org/stretch-backports/armhf/libsodium-dev/download
and
https://packages.debian.org/stretch-backports/armhf/libsodium18/download

And I found  the install package named `.deb` are suit for the rasbian...
The LEDE operating system need the `.ipk` package, so...
Maybe it not suit for my question...
Thanks again~

**Comment by terrytw** [comment]
Dude you really need to read carefully.

I said "If you use raspbian, then you can find it here"
"Unfortunately you've decided to go a rather unusual route to install LEDE on raspberry."
Also please read the "my opinion" part, for I do have a raspberry myself.

**Comment by SuperSuperSuperSuper5** [comment]
@terrytw Yeah...I had read about it...
But I just want to know is anybody met the same problem as me, and how to compile the source code with ... SDK ... rather than ...make route to reinstall the raspbian OS...^ - ^

**Comment by terrytw** [comment]
I listed a link https://github.com/shadowsocks/openwrt-shadowsocks
about how to cross compile shadowsocks on openwrt. 
Instead of openwrt SDK, you'll just have to find and download LEDE SDK, and instead of shadowsocks source code, you'll have to download libsodium source code. 

Also, I think raspberry has enough computing power that you can simply compile instead of cross compile. See this:
https://download.libsodium.org/doc/installation/
