### ISSUE TITLE
[Question] Is it possible to define custom logging level?

### ISSUE THREAD

**Issue by fsgmhoward** [shadowsocks/shadowsocks-libev#1768]
### What version of shadowsocks-libev are you using?
Latest commit (`cc1bb4c`)

### What operating system are you using?
Ubuntu Xenial 16.04.3 LTS

### What did you do?
Trying to log all info of connections (source & target IP addr. /domain name) without the verbose information.

### What did you expect to see? / What did you see instead?
When `-v` is not added, connection info (source & target IP addr. /domain name) is not shown in the log. 
When `-v` is added, too much verbose info is in the output (such as the info of updating traffic count to the ss-manager) which makes the log unreadable.

### What is your config in detail (with all sensitive info masked)?
`ss-manager -t 185 -u` / `ss-manager -v -t 185 -u`
ss-servers are added via manager port.

**Comment by madeye** [comment]
No plan for this.

By default, we suggest not to save any access log.

**Comment by fsgmhoward** [comment]
Thanks for the reply and your suggestion. I would like to preserve the access log because I wanted to use it as a secure proxy for accessing intranet resources. I will try to figure out if there is an alternative way to filter the log by myself.
