### ISSUE TITLE
Timeout with IPv4

### ISSUE THREAD

**Issue by nroskill** [shadowsocks/shadowsocks-libev#1771]
### What version of shadowsocks-libev are you using?
Shadowsocks-libev 3.1.0-1~ppa2x

### What operating system are you using?
Ubuntu 16.04.1 TLS

### What did you do?
I connected shadowsocks server with client on Windows, but it showed timeout with IPv4 address, it worked successfully with IPv6 address.

### What did you expect to see?
It worked with both IPv6 and IPv4 address.

### What did you see instead?
Timeout

### What is your config in detail (with all sensitive info masked)?
{
         "server":["[::0]", "0.0.0.0"],
         "server_port":*****,
         "local_address":"127.0.0.1",
         "local_port":****,
         "password":"********",
         "timeout":300,
         "method":"rc4-md5",
         "fast_open":false
 }

**Comment by terrytw** [comment]
You can try remove "[::0]" and connect to IPV4 address, see if it works.

**Comment by nroskill** [comment]
@terrytw It didn't work. But I tried another server_port and it worked successfully, maybe this port was blocked by my isp. Thanks for your help.
