### ISSUE TITLE
Wang et al.根据对GFW状态机的新分析提出了新的TCP层穿墙方法，经过广泛测试成功率高达98%

### ISSUE THREAD

**Issue by ztechie** [shadowsocks/shadowsocks-libev#1773]
Wang et al.根据对GFW状态机的新分析提出了新的TCP层穿墙方法，经过广泛测试成功率高达98%
https://github.com/seclab-ucr/INTANG

**Comment by ccsexyz** [comment]
98% 这个数字是如何计算出来的？

**Comment by paperbag** [comment]
@ztechie 
你发在这里不太好吧，这里是 ss-libev 的问题。

@ccsexyz 
这个是最近ACM IMC 2017会议的论文，_Your State is Not Mine: A Closer Look at Evading Stateful Internet Censorship_（[PDF](https://conferences.sigcomm.org/imc/2017/papers/imc17-final59.pdf)，[PPT](https://conferences.sigcomm.org/imc/2017/slides/IMC17.pdf)）。
ref: https://conferences.sigcomm.org/imc/2017/program/#collapse_session04

**Comment by ccsexyz** [comment]
@paperbag 至少从论文上看，我认为这个 98% 是没有任何价值的。

**Comment by paperbag** [comment]
> 至少从论文上看，我认为这个 98% 是没有任何价值的。

这只是你没有意识到它的价值而已。当然，它和西厢计划一样，并不能解决ip-blocking的问题。@ccsexyz
ref. https://twitter.com/gfwrev/status/926243253531369473

**Comment by kpxupc** [comment]
You can read the full paper here: http://www.cs.ucr.edu/~krish/imc17.pdf. We really need to look into how to further improve our protocols. Any ideas how to take things forward? Please contribute.

**Comment by madeye** [comment]
Please don't post general discussion here.
