### ISSUE TITLE
3.1.0安装报错

### ISSUE THREAD

**Issue by zyf2008Neptune** [shadowsocks/shadowsocks-libev#1775]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
3.1.0

### What operating system are you using?
debian 9

### What did you do?
从源代码编译安装

### What did you see instead?
报错，如图所示，将aead.c代码中报错部分删掉才能正常编译。

![capture](https://user-images.githubusercontent.com/16064492/32404402-1118c068-c18a-11e7-8419-d52f7f846a09.PNG)

**Comment by terrytw** [comment]
1. It should be libsodium-related. 

2. You can install from stretch-backports instead of compiling from source.
