### ISSUE TITLE
ACL supported syntax

### ISSUE THREAD

**Issue by myliyifei** [shadowsocks/shadowsocks-libev#1776]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?

3.10
### What operating system are you using?

ubuntu 14.04

### What is your config in detail (with all sensitive info masked)?

I would like to know that how to write the correct ACL syntax. Does it support the fqdn or regular expression？what's about all section title and its function? such as [bypass_all], [proxy_list], and else？

hope to get the full documentation. thanks.

**Comment by madeye** [comment]
It's a private feature for shadowsocks-android, no public document.

There is an ACL folder in this project, which contains some examples.
