### ISSUE TITLE
Is it possible to use shadowsocks-libev with and without KCPTUN in the same time?

### ISSUE THREAD

**Issue by Hopecrisy** [shadowsocks/shadowsocks-libev#1778]
### What version of shadowsocks-libev are you using?

3.1.0

### What operating system are you using?

Server：Ubuntu 16.04 x86_64   
Client: ShadowsocksX-NG 1.6.1(1)  and Surge 2.7.0

### What did you do?

As first I set SS-libev as follows:

```
{
    "server":"<server IP>",
    "server_port":7748,
    "local_port":1080,
}
```

And then I set up kcptun as follows：
```
{
    "listen": ":29900",
    "target": "<Server IP:7748>",
    "mode": "fast2"
}
```

### What did you expect to see?

I connected the KCPTUN port <Server IP:29900>with shadowsocksX-NG on my mac,
meanwhile I tried to connect the original SS port <Server IP:7748> on my iPhone.

### What did you see instead?

SS with KCPTUN works perfectly on my mac. 

But the connection between original SS port  <Server IP:7748> and my phone works poorly, I can't receive anything through proxy.

Is there anything wrong in my config, or does anyone else have the same problem of my own?

Any help?

**Comment by madeye** [comment]
Start kcptun in standalone mode.

https://github.com/shadowsocks/shadowsocks-libev#shadowsocks-over-kcp

**Comment by Hopecrisy** [comment]
Sorry... But I don't understand what is _Standalone_ mode.

**Comment by madeye** [comment]
Look into the link above for more details.
