### ISSUE TITLE
Please consider add auto test script

### ISSUE THREAD

**Issue by rogers0** [shadowsocks/shadowsocks-libev#1782]
Debian supports continuous integration or auto test years ago.
The test is run by tool called autopkgtest, and the result shows on https://ci.debian.net/ (only if the package support the test, which is requested by this ticket).

The purpose of the test is to confirm the package, shadowsocks-libev, still runs well after the dependency packages, such as libcork/libsodium/mbedtls, get upgraded.

I think the test script can start connection of ss-server and ss-local by a few popular ciphers and send some packets, then confirm whether the packets reach on the other side and it's correctness. It should also check both tcp and udp protocols.

Please add the script (or scripts) to tests/ folder.

Any ideas?

**Comment by madeye** [comment]
You may try these scripts: https://github.com/shadowsocks/shadowsocks/tree/master/tests

**Comment by rogers0** [comment]
@madeye I tried the tests. But seems it fails *always*.

Try to make it simple, and to use only 1 test as example.
```
$ python tests/test.py  -c tests/rc4-md5.json
...
; <<>> DiG 9.10.3-P4-Debian <<>> @127.0.0.1 -p1082 www.google.com
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached
```

I think the starting a few curl based http tests passed, but the last dig based DNS test failed.
I also tried to use root, but the result is the same.

May I know what's your result? Thanks!

**Comment by rogers0** [comment]
@madeye after #1786, I can pass all tests.
Thanks!
