### ISSUE TITLE
Which kernel shadowsocks-libev support?

### ISSUE THREAD

**Issue by draculaw** [shadowsocks/shadowsocks-libev#1784]
I run the ss-redir on android 3.18.44 it is ok,
but on android 3.0.21 it could not works.

**Comment by madeye** [comment]
I don't think it's related to Linux kernel.

Shadowsocks-libev even works with old 2.6 kernels on many old routers.

**Comment by draculaw** [comment]
I run the 
/usr/sbin/ss-redir -s "ip" -p "port" -l "1080" -m "aes-256-cfb" -k "key" -f "/data/ss.pid"
it report that...

FATAL: kernel too old
Segmentation fault

**Comment by madeye** [comment]
Double check your tool chain. The error you provided is actually report by glibc

https://stackoverflow.com/questions/6941332/anticipate-kernel-too-old-errors-between-2-6-16-and-2-6-26-kernel-versions

**Comment by draculaw** [comment]
thanks a lot.
