### ISSUE TITLE
Fedora Copr repository is unavaliable for Fedora 27

### ISSUE THREAD

**Issue by 126ium** [shadowsocks/shadowsocks-libev#1787]
### What operating system are you using?
Fedora release 27 x86_64

### What did you do?
Try to install shadowsocks-libev from copr repository librehat/shadowsocks
Step I. `sudo dnf copr enable librehat/shadowsocks`
Step II. `sudo dnf update`
Step III. `dnf install shadowsocks-libev`

### What did you expect to see?
Installation succeeded.

### What did you see instead?
Failed to synchronize cache for repo 'librehat-shadowsocks', disabling.
Last metadata expiration check: 0:04:35 ago on Thu 16 Nov 2017 04:11:14 PM CST.
No match for argument: shadowsocks-libev
Error: Unable to find a match

Actually, url 'https://copr-be.cloud.fedoraproject.org/results/librehat/shadowsocks/fedora-27-x86_64/
' is not existed now. Could you help to make a build for Fedora 27? Thank you.
Also, I'm willing to help to maintain this repository :)

**Comment by librehat** [comment]
I'll enable it for Fedora 27 later today

**Comment by madeye** [comment]
@librehat Great!

**Comment by librehat** [comment]
Enabled
