### ISSUE TITLE
"brew services start shadowsocks-libev" seems didnt work while using simple-obfs in MacOS

### ISSUE THREAD

**Issue by xayane** [shadowsocks/shadowsocks-libev#1793]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
3.1.0

### What operating system are you using?
mac os 10.13

### What did you do?
I install shadowsocks-libev and simple-obfs by brew.

### What did you expect to see?
When I use "brew services start shadowsocks-libev" with obfs plugin, chrome can use 127.0.0.1:1080 for socks5 proxy.
我配置了obfs混淆，使用“brew services start shadowsocks-libev”启动后，socks5代理能正常工作。

### What did you see instead?
Actually, when I use "brew services start shadowsocks-libev", the echo shows success but the proxy is not work. Well now, I use "/usr/local/opt/shadowsocks-libev/bin/ss-local -c /usr/local/etc/shadowsocks-libev.json", there is no port bind error, and the socks5 proxy is working. I am puzzled. And I checked the file "/Library/LaunchAgents/homebrew.mxcl.shadowsocks-libev.plist". There is nothing wrong. I use “brew doctor” for checking, and there is no errors too.
What should I do?
It seems the "brew services start shadowsocks-libev" with plugin obfs didn't work but the command "/usr/local/opt/shadowsocks-libev/bin/ss-local -c /usr/local/etc/shadowsocks-libev.json" works.
By the way, if I clear the "plugin" and "plugin_opts" in the shadowsocks-libev.json,  "brew services start shadowsocks-libev" worked and socks5 proxy is working .
实际上，配置了obfs混淆，使用“brew services start shadowsocks-libev”启动后，显示的是服务启动成功，但是代理实际没用工作。同时，我再用命令行启动"/usr/local/opt/shadowsocks-libev/bin/ss-local -c /usr/local/etc/shadowsocks-libev.json"启动代理，居然成功，而且没有端口绑定报错。我检查过"~/Library/LaunchAgents/homebrew.mxcl.shadowsocks-libev.plist"，没有错误。我用“brew doctor”检测，brew也没有报错。
似乎，如果配置了plugin obfs，"brew services start shadowsocks-libev" 就没法启动服务，敲命令行用“ss-local -c xxx.json”又可以启动服务。
如果，我删除了配置文件中的 "plugin"和"plugin_opts”，"brew services start shadowsocks-libev" 又正常了。

### What is your config in detail (with all sensitive info masked)?
{
   "server":"vps ip",
    "server_port":8153,
    "local_port":1080,
    "password":"password",
    "timeout":600,
    "method":"chacha20-ietf-poly1305",
    "plugin":"obfs-local",
    "plugin_opts":"obfs=tls;obfs-host=cloudfront.net"
}

**Comment by lcdtyph** [comment]
Try absolute path of the obfs-plugin in this case.

**Comment by xayane** [comment]
Thanks! 
It works! Cheers!

**Comment by zhe-zhao** [comment]
Great help! 
For people who's looking for same thing: in my case I installed obfs plugin via Home brew and the config looks like:
```
{
    "server":  "xxxxxx",
    ...
    "plugin":  "/usr/local/bin/obfs-local",
    "plugin_opts":  "obfs=tls;obfs-host=iosapps.itunes.apple.com"
}
```

> Try absolute path of the obfs-plugin in this case.
