### ISSUE TITLE
How to get UDP work when shadowsocks is behind HAProxy?

### ISSUE THREAD

**Issue by brglng** [shadowsocks/shadowsocks-libev#1796]
### What version of shadowsocks-libev are you using?
3.1.0-1~ppa2x

### What operating system are you using?
Ubuntu Server 16.04

### What did you do?
I have deplyed shadowsocks-libev behind the reverse proxy HAProxy. HAProxy, who routes several different protocols: HTTPS, AnyConnect and Shadowsocks, listens on 443, and shadowsocks-libev listens on 8388. I am now trying to get UDP work. I don't know how to get it work because the client uses port 443 and expects UDP on 443, but it is actually on 8388.

### What did you expect to see?
I expect UDP to work but I don't know what to do.

### What did you see instead?
The UDP does not work.

### What is your config in detail (with all sensitive info masked)?

    {
        "server":["::0", "0.0.0.0"],
        "server_port":8388,
        "local_port":1080,
        "password":"xxxx",
        "timeout":60,
        "method":"chacha20-ietf-poly1305",
        "fast_open": true,
        "mode": "tcp_and_udp",
        "plugin": "obfs-server",
        "plugin_opts": "obfs=tls;obfs-host=cloudfront.net;failover=cloudfront.net;fast-open"
    }

Thank you for your help!

**Comment by madeye** [comment]
I don't think HAProxy supports UDP load balancing.

**Comment by brglng** [comment]
No, it does not. So I guess I need some UDP reverse proxy or forwarding...

**Comment by madeye** [comment]
Just run multiple `ss-server`. One serves TCP, the other serves UDP.

**Comment by brglng** [comment]
That's a good idea. Thanks!
