### ISSUE TITLE
集成 Xcode 报：duplicate symbol 异常

### ISSUE THREAD

**Issue by caobug** [shadowsocks/shadowsocks-libev#1799]
引用 http.c 或 tls.c 在 xcode 中会报 tls_protocol/http_protocol 重复定义报错。后来谷歌找到一篇文章：https://mnikn.github.io/2017/04/07/Duplicate-Symbol%E9%94%99%E8%AF%AF%E7%9A%84%E5%8E%9F%E5%9B%A0%E5%92%8C%E8%A7%A3%E5%86%B3/ 解决了问题。

http.h：

```
#ifndef HTTP_H
#define HTTP_H

#include <stdio.h>
#include "protocol.h"

// const protocol_t *const http_protocol;

#endif
```

http.c：

`const protocol_t* http_protocol = &http_protocol_st;`

tls.h 和 tls.c 同样做了以上变更。local.c 在顶部定义了以下两行代码，之后就正常了：

```
extern protocol_t* http_protocol;
extern protocol_t* tls_protocol;
```

是我使用姿势不对，还是代码设计有问题？

**Comment by madeye** [comment]
I don't think it's an issue related to shadowsocks-libev. You always need to take care of your own code structure when integrating third-party code.

BTW, make sure you understand the requirement of GPL before integrating any code from this project.
