### ISSUE TITLE
New TFO API

### ISSUE THREAD

**Issue by wongsyrone** [shadowsocks/shadowsocks-libev#1800]
The new API [added](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=19f6d3f3c8422d65b5e3d2162e30ef07c6e21ea2) in Linux 4.11 only requires setting a socket option
before connecting, without the whole sento() machinery.

Notably, this makes it possible to use TFO with SSL connections on Linux
as well, without the need to mess around with OpenSSL (or whatever other
SSL library) internals.

ref implementation: https://github.com/curl/curl/commit/979b012eeb1908e7e3ad13c736fb1dbc73187780

**Comment by wongsyrone** [comment]
I planned to send PR, it seems the code structure is complex than I thought.

**Comment by madeye** [comment]
No plan for now as we need to ensure backward compatibility.

**Comment by wongsyrone** [comment]
curl的实现就维持了兼容性，因为他的代码结构很好

**Comment by manjuprajna** [comment]
@wongsyrone will it cause losing backward compatibility? like openwrt with kernel 3.xx or even lede with kernel 4.9, will these new code make client side lose TFO?

**Comment by wongsyrone** [comment]
条件编译，自动适配

**Comment by wongsyrone** [comment]
@madeye 

Find a critical issue on Android. The unified header has these TFO symbols defined, even including TCP_FASTOPEN_CONNECT, while most Android phones are using kernel 3.10, and it seems Google will not backport this new API to older kernels, it will cause issues when users enable TFO on these devices.

**Comment by wongsyrone** [comment]
https://android.googlesource.com/platform/prebuilts/ndk/+/ndk-r16/platform/sysroot/usr/include/linux/tcp.h#87

**Comment by madeye** [comment]
Thanks to @Mygod, on Android, we have a run time check for TFO support.

So, don't worry about it. The TFO code path won't be executed on a non-supported kernel.

**Comment by wongsyrone** [comment]
OK.

**Comment by debiansid** [comment]
how to make sure TFO is working ?

**Comment by wongsyrone** [comment]
@debiansid 

No such feedback, even with new API.

**Comment by sorz** [comment]
But if it was complied with new headers but ran with old kernel…exit with error.
It's possible when user install it from distros' precompiled package but somehow stuck in old kernel.
