### ISSUE TITLE
Help to setup stunnel + ss-libev

### ISSUE THREAD

**Issue by asmadeus08** [shadowsocks/shadowsocks-libev#1804]
Someone can jelp to me setup stunnel + ss-libev on both Linux-Windows side. Cause my ISP start to limit speed by DPI. Before it was fine and i use ss-libev to bypass speed throttling by DPI but few days ago ISP catch me somehow and now it's limit speed very strict but i still can bypass censorship. I suppose that stunnel can help me fight against speed limit of my ISP if it's possible of course. Any advice or help from someone who can setup this? Maybe it's a bu but when i choose on speedtest internet point inside my country it's show to me full 20mbps speed but internet point outside my country is limited by speed.

**Comment by madeye** [comment]
Try https://github.com/shadowsocks/simple-obfs

**Comment by asmadeus08** [comment]
Yes, I tried. It's doesnt help to bypass speed throttling. And even without this ss-libev bypass censorship.

**Comment by madeye** [comment]
If so, I don't think it's related to QoS based throttling.

Maybe you can try stunnel directly. It makes no sense to use stunnel with shadowsocks together.

https://www.stunnel.org/socksvpn.html

**Comment by asmadeus08** [comment]
Yeah seems like QoS throttling but that's the problem i dont know how to setup stunnel on both side directly or with shadowsocks. But i think better will be with stunnel with ss-libev together to make it more secure. That's why i created this thread to get someone who can setup this all.

**Comment by TasinmazhaberCom** [comment]
Antwell Life Care Residence 
https://www.tasinmazhaber.com/
