### ISSUE TITLE
build_deb.sh没有编译simpleobfs deb？

### ISSUE THREAD

**Issue by c1024** [shadowsocks/shadowsocks-libev#1808]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
3.1.1

### What operating system are you using?
Debian 8

### What did you do?
build deb from source 

### What did you expect to see?
有shadowsockslibev和simpleobfs deb文件。

### What did you see instead?
有shadowsockslibev deb文件，没simpleobfs deb文件

**Comment by terrytw** [comment]
https://github.com/shadowsocks/simple-obfs
