### ISSUE TITLE
编译 3.0.8等老版本失败

### ISSUE THREAD

**Issue by myliyifei** [shadowsocks/shadowsocks-libev#1809]
### What version of shadowsocks-libev are you using?
3.0.8

### What operating system are you using?
ubuntu14.04

### What did you do?
mkdir -p ~/build-area/
cp ./scripts/build_deb.sh ~/build-area/
cd ~/build-area
./build_deb.sh

### What did you expect to see?

编译出旧的版本。

### What did you see instead?

编译失败，simple-obfs等编译成功，但是shadowsocks-libev_xxx.deb 没有生成，使用build_deb.sh拉取的代码还是v3.0.8的

如何编译旧版本，或者直接提供老的版本下载的？想回退老版本测试 这个issue #1801

**Comment by myliyifei** [comment]
3.0.8 编译失败，os ubuntu 14.04

编译日志：

dpkg-deb: building package `shadowsocks-libev-build-deps' in `../shadowsocks-libev-build-deps_3.0.8+ds-2_all.deb'.

The package has been created.
Attention, the package has been created in the current directory,
not in ".." as indicated by the message above!
Selecting previously unselected package shadowsocks-libev-build-deps.
(Reading database ... 137046 files and directories currently installed.)
Preparing to unpack shadowsocks-libev-build-deps_3.0.8+ds-2_all.deb ...
Unpacking shadowsocks-libev-build-deps (3.0.8+ds-2) ...
Reading package lists... Done
Building dependency tree
Reading state information... Done
Correcting dependencies...Starting pkgProblemResolver with broken count: 1
Starting 2 pkgProblemResolver with broken count: 1
Investigating (0) shadowsocks-libev-build-deps [ amd64 ] < 3.0.8+ds-2 > ( devel )
Broken shadowsocks-libev-build-deps:amd64 Depends on debhelper [ amd64 ] < 9.20131227ubuntu1 > ( devel ) (>= 10)
  Removing shadowsocks-libev-build-deps:amd64 because I can't find debhelper:amd64


已经安装 debhelper
sudo aptitude show debhelper
Package: debhelper
State: not installed
Multi-Arch: foreign
Version: 9.20131227ubuntu1
Priority: optional
Section: devel
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: all


编译libev失败
dpkg-checkbuilddeps: Unmet build dependencies: debhelper (>= 10) libsodium-dev (>= 1.0.12) libudns-dev
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)
debuild: fatal error at line 1364:
dpkg-buildpackage -rfakeroot -D -us -uc -i -I failed
gbp:error: Couldn't run 'debuild -i -I -us -uc': debuild -i -I returned 29

**Comment by debiansid** [comment]
`State: not installed`

**Comment by myliyifei** [comment]
哦，这个是粘贴错误，实际是安装了这个包的。只是运行完整个脚步，会自动remove相关依赖，所以这里看起来not installed

是这个版本不对么？看出错信息是对的啊。

2017-11-29 13:50 GMT+08:00 debiansid <notifications@github.com>:

**Comment by hosiet** [comment]
Take a look at https://github.com/shadowsocks/shadowsocks-libev/blob/master/scripts/build_deb.sh#L235 . To build ss-libev on **old** systems where `debhelper (>= 10)` does not exist, this function must be called to patch `debian/control` file and lossen version requirement of `debhelper` package (as well as adding extra build-dependencies `dh-systemd` and `dh-autoreconf`).

I couldn't find any clue if this shell function has been called from your codebase. Anyway please recheck and make sure version requirement has been adjusted.

**Comment by myliyifei** [comment]
+ cd shadowsocks-libev
+ '[' -n '' ']'
+ sed -i 's/dh $@/dh $@ --with systemd,autoreconf/' debian/rules
+ sed -i 's/debhelper (>= 10)/debhelper (>= 9), dh-systemd, dh-autoreconf/'
debian/control
+ echo 9
+ git add -u
+ git commit -m 'Patch to work with ubuntu trusty (14.04)'
[detached HEAD b6b9090] Patch to work with ubuntu trusty (14.04)
 3 files changed, 3 insertions(+), 3 deletions(-)





Selecting previously unselected package shadowsocks-libev-build-deps.
(Reading database ... 137046 files and directories currently installed.)
Preparing to unpack shadowsocks-libev-build-deps_3.0.8+ds-2_all.deb ...
Unpacking shadowsocks-libev-build-deps (3.0.8+ds-2) ...
Reading package lists... Done
Building dependency tree
Reading state information... Done
Correcting dependencies...Starting pkgProblemResolver with broken count: 1
Starting 2 pkgProblemResolver with broken count: 1
Investigating (0) shadowsocks-libev-build-deps [ amd64 ] < 3.0.8+ds-2 > (
devel )
Broken shadowsocks-libev-build-deps:amd64 Depends on debhelper [ amd64 ] <
9.20131227ubuntu1 > ( devel ) (>= 10)
  Removing shadowsocks-libev-build-deps:amd64 because I can't find
debhelper:amd64
Done
 Done

2017-11-29 14:24 GMT+08:00 Boyuan Yang <notifications@github.com>:

**Comment by hosiet** [comment]
Not sure why it's trying to find `debhelper:amd64` instead of `debhelper:all`. Have you modified the previous script? A full script together with full build log would help with the investigation.

@rogers0 Any idea?

**Comment by rogers0** [comment]
http://snapshot.debian.org/package/shadowsocks-libev/

**Comment by myliyifei** [comment]
@rogers0 这个deb可以给ubuntu使用吗？ 
3.0.8+ds-2
3.0.8+ds-2~bpo9+1
3.0.8+ds-2~bpo8+1
3.0.8+ds-1

小版本号有什么区别呢？ 特别是bpo指的是？

**Comment by rogers0** [comment]
@myliyifei it's for debian only
bpo9 stands for backports for stretch
bpo8 is for jessie

for ubuntu you, can try madeys's ppa repository.

**Comment by myliyifei** [comment]
描述一下我的编译过程， os ubuntu 14.04
git clone master之后，checkout v3.0.8（也测试过master最新版本的build_deb.sh)
然后执行
mkdir -p ~/build-area/
cp ./scripts/build_deb.sh ~/build-area/
cd ~/build-area
./build_deb.sh

其中 build_deb.sh 修改了如下。（加粗显示）
依据的是这里的tags  https://anonscm.debian.org/git/collab-maint/shadowsocks-libev.git/refs/tags
也试过这些tags
3.0.8+ds-2
3.0.8+ds-2~bpo9+1
3.0.8+ds-2~bpo8+1
3.0.8+ds-1


[ $BUILD_LIB -eq 1 -o $BUILD_BIN -eq 1 ] && case "$OSVER" in
wheezy|precise)
	echo Sorry, your system $OSID/$OSVER is not supported.
	;;
jessie|stretch|unstable|sid|zesty)
	build_install_libbloom
	build_install_sslibev
	build_install_simpleobfs
	;;
trusty)
	build_install_libcork trusty
	build_install_libcorkipset trusty
	build_install_libmbedtls debian/jessie-backports
	build_install_libsodium
	build_install_libbloom trusty
	patch_sslibev_dh9
	build_install_sslibev **"debian/3.0.8+ds-2_bpo8+1"**
	build_install_simpleobfs trusty
	;;
xenial|yakkety)
	build_install_libcork debian
	build_install_libcorkipset debian
	build_install_libbloom
	build_install_sslibev
	build_install_simpleobfs
	;;
*)
	echo Your system $OSID/$OSVER is not supported yet.
	echo Please report issue:
	echo "    https://github.com/shadowsocks/shadowsocks-libev/issues/new"
	;;
esac

**Comment by myliyifei** [comment]
@rogers0 ppa里面并没有老版本的deb下载。[https://launchpad.net/~max-c-lv/+archive/ubuntu/shadowsocks-libev/+packages?field.name_filter=&field.status_filter=&field.series_filter=](url)

**Comment by myliyifei** [comment]
patch_sslibev_dh9 **"debian/3.0.8+ds-2_bpo8+1"**
build_install_sslibev **"debian/3.0.8+ds-2_bpo8+1"**

这两行都增加相同都tags也没用
