### ISSUE TITLE
crypto: stream: repeat IV detected

### ISSUE THREAD

**Issue by leeecho** [shadowsocks/shadowsocks-libev#1815]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?

 3.1.0
### What operating system are you using?

centos7
### What did you see instead?
日志中一直出现如下错误：

Dec  1 21:01:21 localhost ss-server[70133]: crypto: stream: repeat IV detected
Dec  1 21:01:21 localhost ss-server[70133]: crypto: stream: repeat IV detected
Dec  1 21:01:21 localhost ss-server[70133]: crypto: stream: repeat IV detected
Dec  1 21:01:21 localhost ss-server[70133]: crypto: stream: repeat IV detected
Dec  1 21:01:21 localhost ss-server[70133]: crypto: stream: repeat IV detected
Dec  1 21:01:21 localhost ss-server[70133]: crypto: stream: repeat IV detected
Dec  1 21:01:21 localhost ss-server[70133]: crypto: stream: repeat IV detected
Dec  1 21:01:21 localhost ss-server[70133]: crypto: stream: repeat IV detected
Dec  1 21:01:21 localhost ss-server[70133]: crypto: stream: repeat IV detected
Dec  1 21:01:21 localhost ss-server[70133]: crypto: stream: repeat IV detected
Dec  1 21:01:21 localhost ss-server[70133]: crypto: stream: repeat IV detected
Dec  1 21:01:21 localhost ss-server[70133]: crypto: stream: repeat IV detected
Dec  1 21:01:21 localhost ss-server[70133]: crypto: stream: repeat IV detected
Dec  1 21:01:21 localhost ss-server[70133]: crypto: stream: repeat IV detected
Dec  1 21:01:21 localhost ss-server[70133]: crypto: stream: repeat IV detected
Dec  1 21:02:18 localhost ss-server[70129]: crypto: stream: repeat IV detected
Dec  1 21:02:23 localhost ss-server[70115]: crypto: stream: repeat IV detected
Dec  1 21:03:03 localhost ss-server[70147]: crypto: stream: repeat IV detected
Dec  1 21:04:07 localhost ss-server[70123]: crypto: stream: repeat IV detected
Dec  1 21:06:18 localhost ss-server[70117]: crypto: stream: repeat IV detected
Dec  1 21:06:18 localhost ss-server[70147]: remote recv: Connection reset by peer
Dec  1 21:06:19 localhost ss-server[70141]: crypto: stream: repeat IV detected
Dec  1 21:06:52 localhost ss-server[70129]: crypto: stream: repeat IV detected
Dec  1 21:07:57 localhost ss-server[70119]: crypto: stream: repeat IV detected
Dec  1 21:08:05 localhost ss-server[70121]: crypto: stream: repeat IV detected
Dec  1 21:09:21 localhost ss-server[70117]: crypto: stream: repeat IV detected
Dec  1 21:09:37 localhost ss-server[70145]: crypto: stream: repeat IV detected
Dec  1 21:09:47 localhost ss-server[70115]: failed to handshake with 10.240.23.20: invalid address type
Dec  1 21:10:17 localhost ss-server[70115]: crypto: stream: repeat IV detected
Dec  1 21:10:17 localhost ss-server[70115]: failed to handshake with 10.240.23.20: authentication error
Dec  1 21:10:48 localhost ss-server[70115]: crypto: stream: repeat IV detected
Dec  1 21:10:48 localhost ss-server[70115]: failed to handshake with 10.240.23.20: authentication error
Dec  1 21:11:03 localhost ss-server[70133]: crypto: stream: repeat IV detected
Dec  1 21:11:12 localhost ss-server[70127]: crypto: stream: repeat IV detected
Dec  1 21:13:55 localhost ss-server[70123]: crypto: stream: repeat IV detected

**Comment by leeecho** [comment]
尝试了3.1.1也会有一样的报错。

**Comment by madeye** [comment]
Double check your client. It's either broken or misconfigured.

**Comment by xlliu** [comment]
2017-12-18 11:36:17 ERROR: failed to handshake with 111.199.187.170: authentication error
 2017-12-18 11:36:17 ERROR: crypto: stream: repeat IV detected
 2017-12-18 11:36:17 ERROR: failed to handshake with 111.199.187.170: authentication error
 2017-12-18 11:36:17 ERROR: crypto: stream: repeat IV detected
 2017-12-18 11:36:17 ERROR: failed to handshake with 111.199.187.170: authentication error
 2017-12-18 11:36:17 ERROR: crypto: stream: repeat IV detected
 2017-12-18 11:36:17 ERROR: failed to handshake with 111.199.187.170: authentication error
 2017-12-18 11:36:50 ERROR: crypto: stream: repeat IV detected
 2017-12-18 11:36:50 ERROR: failed to handshake with 111.199.187.170: authentication error
 2017-12-18 11:37:20 ERROR: crypto: stream: repeat IV detected
 2017-12-18 11:37:20 ERROR: failed to handshake with 111.199.187.170: authentication error

我也会有同样的错误， 地址是我的ip， 但是我还是可以正常使用ss

**Comment by yuankui** [comment]
怎么关闭了啊？

**Comment by UMU618** [comment]
ERROR: crypto: stream: repeat IV detected
ERROR: crypto: AEAD: repeat salt detected

**Comment by UMU618** [comment]
ERROR: crypto: stream: repeat IV detected
ERROR: crypto: AEAD: repeat salt detected
这两个都不是大问题，Bloom filter（libbloom）本身就存在误报。
