### ISSUE TITLE
I have build ss-libev for EdgeRouterX based on mipsel, whether do i need make a PR or not

### ISSUE THREAD

**Issue by imMMX** [shadowsocks/shadowsocks-libev#1817]
### What version of shadowsocks-libev are you using?
3.1.1.

### What operating system are you using?

ubuntu 16.04 cross-complier for mipsel.

### What did you do?
build ss-libev for EdgeRouterX beased on mipsel.

whether do i need make a PR to upload these files or not?

**Comment by debiansid** [comment]
you need update libsodium libcares libmcrypt ... for debian wheezy on mips which edgerouteX is running I guess.

**Comment by debiansid** [comment]
I am not updater of this repo, but I would suggest you setup a new repo for all of your projects.

**Comment by madeye** [comment]
Nope, you can maintain it as a downstream project.
