### ISSUE TITLE
1 如何开启日志？ 2 是否可以判断GFW主动刺探SS？

### ISSUE THREAD

**Issue by wulongji2016** [shadowsocks/shadowsocks-libev#1818]
1 -shadowsocks-libev 如何开启日志记录运行情况和出错信息？ 
和Python版本一样的命令么？还是不支持？
网上查了一下，说不支持日志。请各位指教！谢谢

2 另外 如何判断gfw是否主动发来连接试探ss?

**Comment by deeporist** [comment]
1.自己重定向
2.用tcpdump抓包

**Comment by lizhaode** [comment]
@deeporist 
讲讲怎么重定向呗，没找到哪块能重定向

**Comment by suikatomoki** [comment]
@lizhaode 
https://github.com/shadowsocks/simple-obfs#coexist-with-an-actual-web-server

obfs-server -s server_ip -p 80 --obfs http -r 127.0.0.1:8388 --failover 127.0.0.1:8080
obfs-server -s server_ip -p 443 --obfs tls -r 127.0.0.1:8388 --failover 127.0.0.1:8443

**Comment by lizhaode** [comment]
@suikatomoki 
这个是重定向日志吗？我怎么看的是与webserver共存呢？没看懂

**Comment by suikatomoki** [comment]
@lizhaode
看错了 请忽略
