### ISSUE TITLE
In game voice chat is not working 

### ISSUE THREAD

**Issue by leeecho** [shadowsocks/shadowsocks-libev#1819]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?

3.1.1
### What operating system are you using?
win10

### What did you do?
使用shadowsocks-libev玩游戏， 游戏声音使用的是vivox（http://vivox.com/）解决方案，在游戏中听不到队友的声音和发不出声音，应该是voip没有正常代理。客户端和服务器都没有报错。不知道是哪里的问题，请求给予分析，谢谢。

**Comment by imMMX** [comment]
Set iptables and ss-redir (UDP relay enabled) on your router to proxy UDP packet or use SSTAP as a PC client instead of  shadowsocks-libev.

**Comment by leeecho** [comment]
UDP已经被正常proxy，其他udp包是正常的。

**Comment by madeye** [comment]
Try to bypass the VOIP packets.

It's a known issue that most VOIP software won't work well with TPROXY mode of shadowsocks.

**Comment by leeecho** [comment]
sorry，我不知道如何分辨出VOIP packets，然后进行bypass。

**Comment by madeye** [comment]
Bypass the IP or port for VOIP.

**Comment by leeecho** [comment]
测试发现，udp出现cache miss:，然后就没有声音了，是不是udp包处理有问题？
cache miss: 13.58.219.253:6250  <-> 127.0.0.1:64072
