### ISSUE TITLE
Can't resolve DNS on Laptop using ss-redir debian router

### ISSUE THREAD

**Issue by FoleyX90** [shadowsocks/shadowsocks-libev#1820]
### What version of shadowsocks-libev are you using?
Should be the newest version (just installed yesterday)

### What operating system are you using?
Debian Jessie

### What did you do?
Set up ss-server on debian server in a datacenter (public IP 12.35.70.131)
Set up ss-redir on a debian device on my LAN (running dnsmasq & hostapd so device acts as a wifi router. confirmed everything works fine over plain ethernet) (local IP 192.168.8.1 [serves as gateway for laptop])
Have windows laptop connected to device via WI-FI (local IP 192.168.8.111)

### What did you expect to see?
Laptop should resolve DNS, be able to browse web pages & show the debian server in datacenter's IP Address when visiting ipchicken.com

### What did you see instead?
Laptop is unable to resolve DNS (I can ping 8.8.8.8 but not google.com). Confirmed shadowsocks connection is working because I can use Lynx on debian to browse web pages & device obtains datacenter server's IP address.

### What is your config in detail (with all sensitive info masked)?
ss-server:
{
    "server":"0.0.0.0",
    "server_port":8388,
    "local_port":1080,
    "timeout":60,
    "method": "rc4-md5",
    "password": "1234",
    "verbose": 5
}

ss-redir:
{
    "server":"12.35.70.131",
    "server_port":8388,
    "local_port": 12345,
    "password":"1234",
    "timeout":5,
    "method": "rc4-md5",
    "verbose": 2
}

Screenshot: http://prntscr.com/hk52yr

**Comment by madeye** [comment]
None of rules and configs are related to DNS resolving. It looks you only forwarded the TCP traffic.

So, I suggest to check your dnsmasq settings instead, as shadowsocks won't forward your DNS packets (UDP packets).

**Comment by FoleyX90** [comment]
Just wanted to let you know I figured out the issue. On the ss-redir client, I needed to set the local ip to 192.168.8.1 instead of 127.0.0.1
