### ISSUE TITLE
无法访问中文版维基百科

### ISSUE THREAD

**Issue by lizhaode** [shadowsocks/shadowsocks-libev#1823]
### What version of shadowsocks-libev are you using?

shadowsocks-libev 3.1.1

### What operating system are you using?

Ubuntu 17.10

### What did you do?

我的电脑访问维基百科 https://zh.wikipedia.org/zh/Wikipedia:首页 提示无法打开，查看ss-server的log如下
```
Dec  8 19:25:12 minecloudvps ss-server[848]:  2017-12-08 19:25:12 ERROR: getpeername: Transport endpoint is not connected
Dec  8 19:25:30 minecloudvps ss-server[848]:  2017-12-08 19:25:30 ERROR: getpeername: Transport endpoint is not connected
Dec  8 19:25:31 minecloudvps ss-server[848]:  2017-12-08 19:25:31 ERROR: getpeername: Transport endpoint is not connected
```
但是，在vps上使用 curl 来访问这个地址是正常的

配置文件如下

```
{
	"server": "0.0.0.0",
	"server_port": "隐去",
	"password": "隐去",
	"method": "chacha20-ietf-poly1305",
	"timeout": "300",
	"fast_open": true,
	"plugin": "obfs-server",
	"plugin_opts": "obfs=tls"
}
```

**Comment by terrytw** [comment]
访问别的网站正常吗？
提示无法打开，截个图看看？

**Comment by lizhaode** [comment]
@terrytw 
其他网站正常，chrome就是正常的打不开网页的界面，vps上ss的log就是问题中粘贴的那个

**Comment by lizhaode** [comment]
之前看到说Ubuntu的17.10的resove.conf里dnsnameserver配置有问题，于是我换成了16.04版本的，发现问题依旧，也就是说，这个问题与操作系统版本无关

**Comment by lixingcong** [comment]
问题在我的机子上可以复现：
只要打开了 ```"fast_open": true``` ，维基百科偶尔在Chrome打不开，换IE 11打开成功。
关闭fast_open就没有这个奇怪现象

**Comment by madeye** [comment]
1. Disable IPv6 on your VPS and try again.
2. Remove any IPv6 DNS server in your /etc/resolv.conf.

**Comment by lizhaode** [comment]
@madeye 
VPS 已经关闭了ipv6，resolve.conf 只是指定了ipv4的dns server，没有其他的

**Comment by lizhaode** [comment]
@lixingcong 
我也试了一下，确实关闭fast_open 能打开。fast open 有啥实际的好处吗？比如能加快速度等等

**Comment by debiansid** [comment]
客户端打开tfo

**Comment by lizhaode** [comment]
@debiansid 
客户端本来就是打开的

**Comment by debiansid** [comment]
```”plugin_opts": "obfs=http;obfs-host=cloudfront.net;fast
-open",
    "mode": "tcp_and_udp",
    "fast_open": true,
```
服务器客户端的内核确认加载tfo. 我这里可以打开那个网站

**Comment by terrytw** [comment]
https://github.com/shadowsocks/shadowsocks-libev/issues/1399

**Comment by lizhaode** [comment]
@debiansid @terrytw 
竟然是需要在obfs中设置打开
