### ISSUE TITLE
CentOS stuck at starting up when staring shadowsocks-server

### ISSUE THREAD

**Issue by seisgo** [shadowsocks/shadowsocks-libev#1824]
### What version of shadowsocks-libev are you using?
- shadowsocks-libev 3.1.0

### What operating system are you using?
- RHEL 6.5 with yum installed

### What did you do?
- I updated system by "yum update" and installed both python-version and libev-version shadowsocks. 
- I started shadowsocks by commanding "sudo /etc/init.d/shadowsocks-libev start", but I can't connect to website like google.com. 
- Then, I reboot my computer, but got stuck with screen showing: 
*Starting shadowsocks-server: ip6_tables: (C) 2000-2006 Netfilter Core Team [OK]*
*lo: Disabled Privacy Extensions*

### What did you expect to see?
- As I expected, the system should be start correctly.

### What did you see instead?
- The system stick with screen showing as said in **What did you do?**

### What is your config in detail (with all sensitive info masked)?
- Actually, I am not sure my installing of shadowsocks.

**My primary concern is to make system starting regularly conquering the “Disabled Privacy Extensions” stuck. 
What's more, if any suggestion about installation and operation about shadowsocks, it will be better. Thanks very much!**

**Comment by madeye** [comment]
I don't think we have downstream support on CentOS 6.5.

You need to send any distribution specific problem to the downstream maintainers instead.
