### ISSUE TITLE
Too many TIME_WAIT

### ISSUE THREAD

**Issue by FlowerWrong** [shadowsocks/shadowsocks-libev#1825]
### What version of shadowsocks-libev are you using?

`shadowsocks-libev 3.1.1`

### What operating system are you using?

`archlinux`

### What did you do?

1. start shadowsocks-libev with udp relay.
`ss-local -s x.x.x.x -p 5353 -b 0.0.0.0 -l 1080 -k pass -m aes-256-cfb -u -v`
2. start [FlowerWrong/tun2socks](https://github.com/FlowerWrong/tun2socks).
3. test `wrk -t12 -c400 -d30s http://google.com`

### What did you expect to see?

All tcp connections are closed.

### What did you see instead?

Too many `TIME_WAIT` to `127.0.0.1:1080`, no `TIME_WAIT` from `127.0.0.1:1080`
See `netstat -an | grep '127.0.0.1'`

```bash
tcp        0      0 127.0.0.1:53482         127.0.0.1:1080          TIME_WAIT  
tcp        0      0 127.0.0.1:53834         127.0.0.1:1080          TIME_WAIT  
tcp        0      0 127.0.0.1:54026         127.0.0.1:1080          TIME_WAIT
......
```

### What is your config in detail (with all sensitive info masked)?

No special.

**Comment by madeye** [comment]
It's expected.. Please search google to understand what is `TIME_WAIT` and how to tune TCP/IP on Linux.

For example: http://www.lognormal.com/blog/2012/09/27/linux-tcpip-tuning/
