### ISSUE TITLE
编译安装错误

### ISSUE THREAD

**Issue by zhangpfly** [shadowsocks/shadowsocks-libev#1826]
make  all-recursive
make[1]: 进入目录“/root/shadowsocks-libev”
Making all in libcork
make[2]: 进入目录“/root/shadowsocks-libev/libcork”
make[2]: 对“all”无需做任何事。
make[2]: 离开目录“/root/shadowsocks-libev/libcork”
Making all in libipset
make[2]: 进入目录“/root/shadowsocks-libev/libipset”
make[2]: 对“all”无需做任何事。
make[2]: 离开目录“/root/shadowsocks-libev/libipset”
Making all in libbloom
make[2]: 进入目录“/root/shadowsocks-libev/libbloom”
make[2]: 对“all”无需做任何事。
make[2]: 离开目录“/root/shadowsocks-libev/libbloom”
Making all in src
make[2]: 进入目录“/root/shadowsocks-libev/src”
  CCLD     ss-local
ss_local-aead.o: In function `aead_cipher_decrypt':
/root/shadowsocks-libev/src/aead.c:219: undefined reference to `crypto_aead_xchacha20poly1305_ietf_decrypt'
ss_local-aead.o: In function `aead_cipher_encrypt':
/root/shadowsocks-libev/src/aead.c:180: undefined reference to `crypto_aead_xchacha20poly1305_ietf_encrypt'
collect2: error: ld returned 1 exit status
make[2]: *** [ss-local] 错误 1
make[2]: 离开目录“/root/shadowsocks-libev/src”
make[1]: *** [all-recursive] 错误 1
make[1]: 离开目录“/root/shadowsocks-libev”
make: *** [all] 错误 2

**Comment by lizhaode** [comment]
是不是libsodium这个没装？

**Comment by zhangpfly** [comment]
#### 我是按照下面的顺序在CentOS 7上安装的（yum使用dnf命令失败，找不到dnf安装包）
用的是root用户，安装目录在/root下面

## CentOS / Fedora / RHEL
```
sudo yum install gettext gcc autoconf libtool automake make asciidoc xmlto c-ares-devel libev-devel
```
>**下面的Libsodium和MbedTLS都下载解压在/root/shadowsocks-libev下面**
# Installation of Libsodium
```
export LIBSODIUM_VER=1.0.13
wget https://download.libsodium.org/libsodium/releases/libsodium-$LIBSODIUM_VER.tar.gz
tar xvf libsodium-$LIBSODIUM_VER.tar.gz
pushd libsodium-$LIBSODIUM_VER
./configure --prefix=/usr && make
sudo make install
popd
sudo ldconfig
```
# Installation of MbedTLS
```
export MBEDTLS_VER=2.6.0
wget https://tls.mbed.org/download/mbedtls-$MBEDTLS_VER-gpl.tgz
tar xvf mbedtls-$MBEDTLS_VER-gpl.tgz
pushd mbedtls-$MBEDTLS_VER
make SHARED=1 CFLAGS=-fPIC
sudo make DESTDIR=/usr install
popd
sudo ldconfig
```
# Start building
```
./autogen.sh && ./configure && make   # 执行到这一行报错
sudo make install
```
报错信息没有变化。

**Comment by zhangpfly** [comment]
![default](https://user-images.githubusercontent.com/17722518/33824492-808b89a4-de99-11e7-86d2-b9a07763b941.png)

**Comment by AsterOcclu** [comment]
你应该是系统自带或者通过yum、apt-get的方式安装过低版本的libsodium了，所以建议先remove掉，比如`yum remove libsodium`，然后再按照原来教程里的方式编译安装新版libsodium，然后再尝试编译ss-libev吧。

**Comment by zhangpfly** [comment]
OK.可以了。谢谢。 @AsterOcclu @lizhaode
