### ISSUE TITLE
Speed slow down regularly when watching videos on bilibili.com

### ISSUE THREAD

**Issue by MingElf** [shadowsocks/shadowsocks-libev#1828]
### What version of shadowsocks-libev are you using?
shadowsocks-libev-3.0.6-1.el7.centos.x86_64

### What operating system are you using?
centos.x86_64

I'm using proxifer to send data to shadowsocks-windows, but sometimes (not a certain time of a day) the traffic would slow down suddenly and then rise up again in a few mintues. 
The traffic graph in proxifer is following:
![traffic](https://user-images.githubusercontent.com/30290883/33885135-59d3a0be-df7d-11e7-9a37-f396b18fecf6.png)
I checked the connections, and found that traffic of the target "tx.acgvideo.com:443" of chrome.exe would be suddenly blocked after it received over 3.0MB. 
![bilibili](https://user-images.githubusercontent.com/30290883/33885428-4236700c-df7e-11e7-9de5-3ad850fb384f.png)

I don't know if it is a shadowsocks-libev question, could someone just give me an advice? Thanks a lot.

**Comment by madeye** [comment]
I don't think it's related to shadowsocks-libev. Double check your VPS server is not blocked / QoSed by Bilibili.
