### ISSUE TITLE
部分网页无法打开 SSredir

### ISSUE THREAD

**Issue by jackwangshanghai** [shadowsocks/shadowsocks-libev#1830]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
3.1.1 ss-redir

### What operating system are you using?
Win

### What did you do?
OpenWeb

### What did you expect to see?
Open the Web

### What did you see instead?
Cannot Open

### What is your config in detail (with all sensitive info masked)?
using chacha20-ietf-plot

同时配置了 SSRedir 的TCP和UDP。大多数网页能正常打开 但是部分网页不行，譬如 Facebook的 Message，Netflix（整个网页都打不开，任何内容都无法打开） Windows商店，在树莓派 配置了 SSREDIR转发 Windows GateWay设置为 树莓派 地址，绝大多数都能打开 Youtube Google Twitter，但是 部分网页 就是打不开 ，但是相同的服务器 在Win本地使用 Socks Http代理 是正常的，但是使用透明代理就是无法访问。 什么原因可能会导致类似问题。

**Comment by jackwangshanghai** [comment]
DNS 使用DNSCrypt-Proxy 配置的 iptable 没有绕过中国（全局）

**Comment by jackwangshanghai** [comment]
Wget 能正常 下载到网页 但是浏览器 就不行 测试了 IE和Chrome的隐私模式 都无法获取 别的电脑也这样。 刚刚发现 github 发表 comment 也会出问题（我发送这个信息时候）

**Comment by madeye** [comment]
Double check you DNS settings. It's a typical DNS pollution issue.

**Comment by jackwangshanghai** [comment]
I Checked I can get the correct ip, If I using normal gateway I can open the website(Netflix, but I said Location not in service), if open with normal gateway and local proxy everything correct, If open with Pi(The server install ss-redir) as gateway I cannot open Netflix.(Google Youtube works as normal). But I cannot create the link to Netflix. if I press F12 there is no connection. But I can download web page via wget(the page is correct, do not tell location not in service), I open this ip(ip reslove when using wget) via brower. Https connection can created, but 404 shown.

**Comment by jackwangshanghai** [comment]
iptables -t nat -N SHADOWSOCKS
iptables -t mangle -N SHADOWSOCKS


ip rule add fwmark 0x01/0x01 table 100
ip route add local 0.0.0.0/0 dev lo table 100

iptables -t mangle -A SHADOWSOCKS -d 45.76.239.145  -j RETURN
iptables -t mangle -A SHADOWSOCKS -d 101.78.183.200  -j RETURN
iptables -t mangle -A SHADOWSOCKS -d 208.67.220.220  -j RETURN
iptables -t mangle -A SHADOWSOCKS -d 61.244.19.103  -j RETURN

iptables -t nat -A SHADOWSOCKS -d SERVER_IP  -j RETURN
iptables -t nat -A SHADOWSOCKS -d DNSCrypt_Server_ip  -j RETURN

iptables -t nat -A SHADOWSOCKS -d 0.0.0.0/8 -j RETURN
iptables -t nat -A SHADOWSOCKS -d 10.0.0.0/8 -j RETURN
iptables -t nat -A SHADOWSOCKS -d 127.0.0.0/8 -j RETURN
iptables -t nat -A SHADOWSOCKS -d 169.254.0.0/16 -j RETURN
iptables -t nat -A SHADOWSOCKS -d 172.16.0.0/12 -j RETURN
iptables -t nat -A SHADOWSOCKS -d 192.168.0.0/16 -j RETURN
iptables -t nat -A SHADOWSOCKS -d 224.0.0.0/4 -j RETURN
iptables -t nat -A SHADOWSOCKS -d 240.0.0.0/4 -j RETURN

iptables -t mangle -A SHADOWSOCKS -d 0.0.0.0/8 -j RETURN
iptables -t mangle -A SHADOWSOCKS -d 10.0.0.0/8 -j RETURN
iptables -t mangle -A SHADOWSOCKS -d 127.0.0.0/8 -j RETURN
iptables -t mangle -A SHADOWSOCKS -d 169.254.0.0/16 -j RETURN
iptables -t mangle -A SHADOWSOCKS -d 172.16.0.0/12 -j RETURN
iptables -t mangle -A SHADOWSOCKS -d 192.168.0.0/16 -j RETURN
iptables -t mangle -A SHADOWSOCKS -d 224.0.0.0/4 -j RETURN
iptables -t mangle -A SHADOWSOCKS -d 240.0.0.0/4 -j RETURN

iptables -t nat -A SHADOWSOCKS -p tcp -j REDIRECT --to-ports 1080
iptables -t mangle -A SHADOWSOCKS -p udp -j TPROXY --on-port 1080 --tproxy-mark 0x01/0x01

iptables -t nat -A OUTPUT -p tcp -j SHADOWSOCKS
iptables -t nat -A PREROUTING -p tcp -j SHADOWSOCKS
iptables -t mangle -A PREROUTING -p udp -j SHADOWSOCKS

**Comment by jackwangshanghai** [comment]
iptables -t nat -N SHADOWSOCKS
iptables -t mangle -N SHADOWSOCKS

ip rule add fwmark 0x01/0x01 table 100
ip route add local 0.0.0.0/0 dev lo table 100

iptables -t mangle -A SHADOWSOCKS -d 208.67.220.220  -j RETURN
iptables -t mangle -A SHADOWSOCKS -d  SERVER_IP  -j RETURN

iptables -t nat -A SHADOWSOCKS -d SERVER_IP  -j RETURN
iptables -t nat -A SHADOWSOCKS -d 208.67.220.220  -j RETURN

iptables -t nat -A SHADOWSOCKS -d 0.0.0.0/8 -j RETURN
iptables -t nat -A SHADOWSOCKS -d 10.0.0.0/8 -j RETURN
iptables -t nat -A SHADOWSOCKS -d 127.0.0.0/8 -j RETURN
iptables -t nat -A SHADOWSOCKS -d 169.254.0.0/16 -j RETURN
iptables -t nat -A SHADOWSOCKS -d 172.16.0.0/12 -j RETURN
iptables -t nat -A SHADOWSOCKS -d 192.168.0.0/16 -j RETURN
iptables -t nat -A SHADOWSOCKS -d 224.0.0.0/4 -j RETURN
iptables -t nat -A SHADOWSOCKS -d 240.0.0.0/4 -j RETURN

iptables -t mangle -A SHADOWSOCKS -d 0.0.0.0/8 -j RETURN
iptables -t mangle -A SHADOWSOCKS -d 10.0.0.0/8 -j RETURN
iptables -t mangle -A SHADOWSOCKS -d 127.0.0.0/8 -j RETURN
iptables -t mangle -A SHADOWSOCKS -d 169.254.0.0/16 -j RETURN
iptables -t mangle -A SHADOWSOCKS -d 172.16.0.0/12 -j RETURN
iptables -t mangle -A SHADOWSOCKS -d 192.168.0.0/16 -j RETURN
iptables -t mangle -A SHADOWSOCKS -d 224.0.0.0/4 -j RETURN
iptables -t mangle -A SHADOWSOCKS -d 240.0.0.0/4 -j RETURN

iptables -t nat -A SHADOWSOCKS -p tcp -j REDIRECT --to-ports 1080
iptables -t mangle -A SHADOWSOCKS -p udp -j TPROXY --on-port 1080 --tproxy-mark 0x01/0x01

iptables -t nat -A OUTPUT -p tcp -j SHADOWSOCKS
iptables -t nat -A PREROUTING -p tcp -j SHADOWSOCKS
iptables -t mangle -A PREROUTING -p udp -j SHADOWSOCKS

**Comment by jackwangshanghai** [comment]
发现好像Facebook登入也有问题，用的是树莓派 不做路由器 相当于旁路（设置 GateWay为树莓派就 走代理 否则 默认）树莓派是 Debian系统 官网默认的 下载后 安装了 ipset 和 ss dnscrypt-proxy dnsmasq。应该没有干扰，forward也打开了。不知道还有哪里能有问题

**Comment by madeye** [comment]
As I mentioned above, it's a typical DNS poisoning issue. A quick check is blocking any out-going packets to port 53 on your router.

**Comment by jackwangshanghai** [comment]
Netflix 没有 DNS污染，但是链接不正常 Google 有DNS污染 但是链接正常，我尝试 让树莓派 通过openvpn链接 然后 做 NAT 给内网，是可以链接Netflix 所以感觉是 Netflix 对透明代理的Socks不太友好

**Comment by terrytw** [comment]
我在树莓派和路由器上部署的SS-REDIR都正常的，你提到的所有服务都完全没有任何问题
如果是这种基础的功能出问题的话早就ISSUE满天飞了
肯定不是所谓的某些网站对透明代理不友好
检查一下你自己的各项设置吧！

**Comment by jackwangshanghai** [comment]
所以说可以检查哪方面 我Netflix 死活打不开

**Comment by jackwangshanghai** [comment]
Problem Solved by update Kernel via rpi-update on raspberrypi

**Comment by jackwangshanghai** [comment]
I dont't what happen it seem still has problem with netflix connection
