### ISSUE TITLE
How to allow only OBFS links|如何只允许obfs链接

### ISSUE THREAD

**Issue by shirakun** [shadowsocks/shadowsocks-libev#1831]
Use OBFS by plug-in
But the discovery that the client does not use OBFS can also link
How do you only allow the use of OBFS links, with parameters or examples
通过插件的方式使用obfs
但是发现客户端不使用obfs也可以链接
如何只允许使用obfs链接,有参数或者示例吗

**Comment by madeye** [comment]
Try `--failover`.

**Comment by shirakun** [comment]
@madeye 
add command `--failover`
`ss-server -h` No this parameter
Starting Shadowsocks-libev failed

**Comment by madeye** [comment]
It's an option of simple-obfs.

**Comment by shirakun** [comment]
@madeye 
Thank you for answering

I just looked at the description of simple-obfs
The example given by simple-obfs is that obfs-server runs alone
I want obfs-server to run as a plug-in for ss-server
How do you pass the `--failover` parameter

**Comment by madeye** [comment]
Follow SIP003's parameters. e.g.

`obfs=http;failover=127.0.0.1:8080`
