### ISSUE TITLE
Shadowsocks服务器运行时，有log文件么？

### ISSUE THREAD

**Issue by alexya** [shadowsocks/shadowsocks-libev#1836]
(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
3.1.1

### What operating system are you using?
Ubuntu 14.04

### What did you do?
使用 ss-server to 运行 shadowsocks-libv.
`ss-server -s 0.0.0.0 -p 1777 -m aes-256-cfb -k barfoo! --fast-open`

### What did you expect to see?
看了一下帮助文档，发现没有参数是设置log文件的
想知道，ss-server运行时，有没有error log能够用来帮助查看服务器无法工作时，是什么原因失败的。

### What did you see instead?
无法工作，不清楚原因。

### What is your config in detail (with all sensitive info masked)?
`ss-server -s 0.0.0.0 -p 1777 -m aes-256-cfb -k barfoo! --fast-open`

**Comment by kxy09** [comment]
![qq 20171215191603](https://user-images.githubusercontent.com/30567845/34037536-804c2904-e1cc-11e7-8352-4d0159d702b7.png)
用终端保持前台运行的话会输出，保存为.log就不知道了

**Comment by smarxpan** [comment]
你运行的时候可以前面加nohup命令，这样就会输出到nohup.out文件了

**Comment by evenardo** [comment]
According to my experience , maybe you lost a argument -l , a local port , it's be 1080 generally . 

-l 1080

**Comment by evenardo** [comment]
Don't know why , happened before . set server listen ip address 0.0.0.0 worse then delete line in config.json .
or must be accurate fill ip , not a broadcast address . Not to matter , it's no longer happened , when I try to write a issue . :P

**Comment by alexya** [comment]
@evenardo @smarxpan 你们的ss-server运行后是什么样子的？
例如，我的ss-server运行后，我到container里面去看，这个样子的`[ss-server]`，我认为有问题，但我不知道是什么问题？
```
bash-4.4# ps aux | grep ss-server
    5 root       0:00 [ss-server]
   13 root       0:00 grep ss-server
```

正常应该是类似这样子的吧，例如：
```
bash-4.4# ps aux | grep ss-server
    5 root       0:00 ss-server -s 0.0.0.0 -p 8388 -m aes-256-cfb -k barfoo! --fast-open
   11 root       0:00 grep ss-server
```

**Comment by evenardo** [comment]
@alexya I'm setup with /etc/shadowsocks-libev/config.json
and start with /etc/init.d/shadowsocks-libev start

nobody    2443  0.0  0.5  31848  5484 ?        Ss   13:45   0:02 /usr/bin/ss-server -c /etc/shadowsocks-libev/config.json -u
root      5016  0.0  0.1  14628  1076 pts/0    S+   15:47   0:00 grep --color=auto ss-server

@alexya
plz frome original appearance :
s-server -s 0.0.0.0 -p 8388 -m aes-256-cfb -k barfoo! --fast-open
to add argument ' -l 1080 ' like this 
s-server -s 0.0.0.0 -p 8388 -l 1080 -m aes-256-cfb -k barfoo! --fast-open

**Comment by rickyzhan** [comment]
/var/log/shadowsocks.log

**Comment by ewgasdf** [comment]
如果你是通过官方包管理器默认安装的话(也就是通过systemd的方式管理ss-libev启动项的话），可以这样：
journalctl -u shadowsocks-libev.service 
这会以less的方式从头到尾列出所有日志，你也可以通过加其他参数加以限定，可以自行搜索看看
