### ISSUE TITLE
build_deb.sh 无法工作

### ISSUE THREAD

**Issue by t123yh** [shadowsocks/shadowsocks-libev#1837]
curl https://raw.githubusercontent.com/shadowsocks/shadowsocks-libev/master/scripts/build_deb.sh | sudo sh - 1>log.txt 2>&1

http://paste.ubuntu.com/26188479/

**Comment by rogers0** [comment]
please retry in a clean environment

**Comment by t123yh** [comment]
@rogers0 It's a fresh Ubuntu 16.04 LTS installed from a netinstall CDROM.

**Comment by rogers0** [comment]
@t123yh "error: Git command failed: Error running git clone: fatal: destination path 'libcork' already exists and is not an empty directory."

**Comment by t123yh** [comment]
@rogers0 On an empty directory, the problem still exists. http://paste.ubuntu.com/26193825/

**Comment by rogers0** [comment]
"curl: (22) The requested URL returned error: 404 Not Found
dget: curl libsodium_1.0.15-1.dsc http://deb.debian.org/debian/pool/main/libs/libsodium/libsodium_1.0.15-1.dsc failed"

it's because debian maintainer of libsodium released the new version 1.0.15-2, but forgot to put his latest tag to git repo.
Please report this issue at https://github.com/gcsideal/debian-libsodium

**Comment by rogers0** [comment]
@t123yh please kindly try the following patch.

```
diff --git a/scripts/build_deb.sh b/scripts/build_deb.sh
index 126dc63..ceb6bc6 100755
--- a/scripts/build_deb.sh
+++ b/scripts/build_deb.sh
@@ -196,6 +196,10 @@ if [ $BUILD_LIB -eq 1 -o $BUILD_BIN -eq 1 ]; then
         git clone https://github.com/gcsideal/debian-libsodium.git libsodium
         cd libsodium; LIBSODIUM=$(dpkg-parsechangelog --show-field Version); cd -
         dget -ud http://deb.debian.org/debian/pool/main/libs/libsodium/libsodium_${LIBSODIUM}.dsc
+        if [ $? -ne 0 ]; then
+            dsc_build http://deb.debian.org/debian/pool/main/libs/libsodium/libsodium_1.0.13-1~bpo8+1.dsc
+            return
+        fi
         DHVER=$(dpkg -l debhelper|grep debhelper|awk '{print $3}'|head -n1)
         cd libsodium
         if dpkg --compare-versions $DHVER lt 10; then
```

**Comment by rogers0** [comment]
@t123yh any feedback?

**Comment by t123yh** [comment]
@rogers0 
Sorry for the late response. Tried your patch and got the following (on Debian 9, not the previous Ubuntu):  
http://paste.debian.net/1007815/

**Comment by rogers0** [comment]
@t123yh why brother to compile? it's easier to install from stretch-backports?
- https://github.com/shadowsocks/shadowsocks-libev#install-from-repository

**Comment by t123yh** [comment]
@rogers0 I have already installed from there. I just want to know what's the problem and solve it. Thanks for your help.

**Comment by rogers0** [comment]
@t123yh 
816 gbp:error: Pristine-tar couldn't checkout "shadowsocks-libev_3.1.3+ds.orig.tar.xz": fatal: Path 'shadowsocks-libev_3.1.3+ds.orig.tar.xz.delta' does not exist in 'refs/heads/pristine-tar'

my bad, that forgot to git push pristine-tar branch to debian's alioth repo

**Comment by t123yh** [comment]
@rogers0 It's working now. Thank you!
