### ISSUE TITLE
What ports should I open?

### ISSUE THREAD

**Issue by tetroider** [shadowsocks/shadowsocks-libev#1838]
I have shadowsocks server behind my router's firewall. So to get access to the server from internet I need to forward ports of shadowsocks server. In server logs It says, that server listening on 8388 TCP and 8388 UDP ports. So, that port is the main and that shoud I open? Or maybe both of them simultaniously?
By the way, I want to know, then i connect to udp port through shadowsocks from my client machine, it goes by ss-server 8388 udp or tcp port?

**Comment by tetroider** [comment]
Forget about it. I already have figured out my problem.

**Comment by tetroider** [comment]
Forget about it. I already have figured out my problem.

**Comment by ralphrmartin** [comment]
How about posting the answers for others to see?
