### ISSUE TITLE
服务端怎么添加acl控制？

### ISSUE THREAD

**Issue by joviqiao** [shadowsocks/shadowsocks-libev#1841]
### What version of shadowsocks-libev are you using?
shadowsocks-libev 3.1.1

### What operating system are you using?
Ubuntu 17.10 (GNU/Linux 4.13.5-041305-generic x86_64)

### What did you do?
服务器端如果加入acl控制？我运行 ss-server -c /etc/shadowsocks.json --acl /opt/acl.acl 
只是显示acl初始化 然后就是帮助信息

### What is your config in detail (with all sensitive info masked)?
{"server":"0.0.0.0","timeout":600,"fast_open": true,"local_address": "127.0.0.1","local_port":1080,"method":"aes-256-cfb","port_password":{"70":"test001"}}

**Comment by smarxpan** [comment]
`ss-server -c /etc/shadowsocks.json --acl 你的acl文件`

而acl文件的填写方式，以项目中提供的local.acl文件为例

你就在[white_list]下面填写你需要加入白名单的ip

```
[reject_all]

[white_list]
127.0.0.1
# 这里填写ip
::1
10.0.0.0/8
172.16.0.0/12
192.168.0.0/16
fc00::/7
```

**Comment by joviqiao** [comment]
我试过了，没有成功启动，只是显示帮助信息 ，感觉我安装的问题，我再看下
