### ISSUE TITLE
How to check what SS version is installed on Debian?

### ISSUE THREAD

**Issue by 4044ever** [shadowsocks/shadowsocks-libev#1845]
How to check what SS version is installed on Debian?

**Comment by tetroider** [comment]
dpkg -l | grep shadowsocks

**Comment by 4044ever** [comment]
I don't get any return:

pi@raspberrypi:~ $ dpkg -l | grep shadowsocks
pi@raspberrypi:

ss-server doesn't work either. What now?

**Comment by debiansid** [comment]
ss-server -v

**Comment by 4044ever** [comment]
dpkg -l | grep ss-server -v
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)

pi@raspberrypi:~ $ dpkg -l | grep shadowsocks -v
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)

...then I get 100+ lines of output, without anything obvious SS related.

What next?

Anyway, I found a line "_shadowsocks-2.8.2_" - seems my version is about 1 year old. 

Can it be updated or I need a new install?

**Comment by hosiet** [comment]
shadowsocks-2.8.2 is **not** shadowsocks-libev, the previous one is the python version and does not relate to this project (ss-libev).

If `dpkg` cannot return any results, that means you didn't install shadowsocks/shadowsocks-libev via deb package management system. You might have installed softwares using something like copy-paste or directly from source code.

If you (correctly) installed shadowsocks-libev via Debian's package management system, you are supposed to get results like this:

```bash
dpkg -l | grep shadowsocks      
ii  libqtshadowsocks1:amd64                                     1.11.0-2                             amd64        Lightweight and ultra-fast shadowsocks library written in C++/Qt
ii  shadowsocks                                                 2.9.0-2                              all          Fast tunnel proxy that helps you bypass firewalls
ii  shadowsocks-libev                                           3.1.1+ds-4                           amd64        lightweight and secure socks5 proxy
ii  simple-obfs                                                 0.0.5-2                              amd64        simple obfusacting plugin for shadowsocks-libev
```

If you sticks to manually-installed shadowsocks-related software, we cannot really effectively help you. You must sort out the status of your system on your own.

**Comment by debiansid** [comment]
```
ss-server -v |more

shadowsocks-libev 3.1.1

  maintained by Max Lv <max.c.lv@gmail.com> and Linus Yang <laokongzi@gmail.com>

```

**Comment by terrytw** [comment]
man page usually has version info at the bottom.

**Comment by evenardo** [comment]
~# dpkg -l | grep shadow
ii  shadowsocks-libev                          3.0.8+ds-2

~# ss-server -v |more  
(not work at 3.0.8)

**Comment by 4044ever** [comment]
@hosiet
> shadowsocks-2.8.2 is not shadowsocks-libev, the previous one is the python version and does not relate to this project (ss-libev).

Doh, you are right on that. I certainly did something with Python. Was a year ago, really forgot the details. No further questions then and sorry for the confusion.

**Comment by cateyes99** [comment]
I installed **shadowsocks-libev** on **Debian 11** from **snap**, the following command works for me:
``` shell
~$ snap list | grep shadowsocks
shadowsocks-libev  3.3.5-1    799    latest/edge    max-c-lv    -
```
The following 2 won't work in this case, but works for the case if SS-libev is installed from the repository `sudo apt install shadowsocks-libev`
```shell
~# dpkg -l | grep shadow

~# ss-server -v | more
```
