### ISSUE TITLE
What actually is HTTP/SNI parser? [Question]

### ISSUE THREAD

**Issue by tetroider** [shadowsocks/shadowsocks-libev#1847]
In changelog i see:
* Add HTTP/SNI parser for ss-local/ss-redir
But socks should not analyse traffic, it simply works as transmitter and do not manipulate with original tcp/udp traffic. So what does that parser actually do and why I simply can't disable it?

**Comment by madeye** [comment]
Please search the issue tracker before asking a question that has.been asked so many times.
