### ISSUE TITLE
`--no-delay` 参数的疑问

### ISSUE THREAD

**Issue by pexcn** [shadowsocks/shadowsocks-libev#1848]
请问是不是必须在 server 和 client 两端都开启 `--no-delay` 这个参数，才会生效？

**Comment by madeye** [comment]
`--no-delay` in client means sending any data from client to server with no delay.

`--no-delay` in server means sending any data from server to client with no delay.

**Comment by pexcn** [comment]
知道了，谢谢

**Comment by Love4Taylor** [comment]
说起来对 simple-obfs 没用吧
