### ISSUE TITLE
Does it matter what is my password length?

### ISSUE THREAD

**Issue by tetroider** [shadowsocks/shadowsocks-libev#1849]
So, the question is not about security. It about technical limitation.
That is lowest lenth? As I understand, the key generating happens by transforming password into key byte by byte. But if my password is 1 byte, for example "a". Is it enough to generate, for example aes-256 key?

By the way, is here an error in the code? https://github.com/shadowsocks/shadowsocks-libev/blob/master/src/crypto.c#L231
 for (i = 0; i < mds; i++, j++) {
 if (j >= key_len)
 break;
 key[j] = md_buf[i];
 }
Maybe it should be like:
 for (i = 0; i < mds; i++, j++) {
 if (j >= key_len) {
 break;
}
 key[j] = md_buf[i];
 }

**Comment by madeye** [comment]
There is no issue of the code. Consult the protocol document for more details: https://shadowsocks.org/en/spec/Stream-Ciphers.html

**Comment by tetroider** [comment]
Please, try to understand. I am not good at cryptography but i am very big paranoic. Currently I try to understand.
Currently I try to understand stream cipher mode of shadowsocks. I cant't understand deviring key process.  On SS site it says, that deviring key followed by https://wiki.openssl.org/index.php/Manual:EVP_BytesToKey(3). But in real SS code you don`t use this function. On the OpenSSL page there is no info about minimum password lenth too.

**Comment by madeye** [comment]
The longer the better. You can even input a key directly.

**Comment by tetroider** [comment]
CanI use one-symbol password, for example 'p' and will long password (32 symbols) affect on speed?
