### ISSUE TITLE
Port no response

### ISSUE THREAD

**Issue by qifei** [shadowsocks/shadowsocks-libev#1850]
### What version of shadowsocks-libev are you using?
3.1.0-1

### What operating system are you using?
CentOS 7 x64

### What did you do?
nothing

### What did you expect to see?
it works

### What did you see instead?
connection failed

### What is your config in detail (with all sensitive info masked)?
{
    "server":"******",
    "server_port":4****,
    "local_port":1080,
    "password":"******",
    "timeout":600,
    "method":"aes-256-cfb",
    "protocol":"origin",
    "protocol_param":"",
    "obfs":"http_simple_compatible",
    "obfs_param":"",
    "redirect":"",
    "fast_open":true,
}

Cannot connect to Internet through SS since last night.
昨晚开始不能上网了，ping 了一下发现端口无回应，只有22端口正常。

**Comment by madeye** [comment]
According to your config file, I don't think you're using shadowsocks-libev.

**Comment by qifei** [comment]
{
    "server":"36.58.85.20",
    "server_port":56235,
    "local_port":1080,
    "password":"password123",
    "timeout":600,
    "method":"aes-256-cfb",
    "protocol":"origin",
    "protocol_param":"",
    "obfs":"http_simple_compatible",
    "obfs_param":"",
    "redirect":"",
    "fast_open":true,
}
It has been like this, and run smoothly for 2 months.
