### ISSUE TITLE
Cannot upgrade from PPA for lack of "Release" file

### ISSUE THREAD

**Issue by netheril96** [shadowsocks/shadowsocks-libev#1856]
### What version of shadowsocks-libev are you using?
3.0.7

### What operating system are you using?
Ubuntu 17.04

### What did you do?
```bash
sudo add-apt-repository ppa:max-c-lv/shadowsocks-libev
sudo apt update
```
Ubuntu 17.04 has `ss-libev` in its default repository, but the version is too old (2.6.3). So I resort to the PPA.

### What did you expect to see?
No errors. And ready to upgrade my `shadowsocks-libev` installation to the latest.

### What did you see instead?
Error log.
```
E: The repository 'http://ppa.launchpad.net/max-c-lv/shadowsocks-libev/ubuntu zesty Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by madeye** [comment]
Only 14.04 and 16.04 are supported in PPA.

On 17.04 and above, please install from the official repo.

**Comment by netheril96** [comment]
But the official repo is too old (2.6.3).

**Comment by hosiet** [comment]
Please upgrade your Ubuntu version.

Also keep in mind that Ubuntu 17.04 will reach end of support(EOL) **very** **soon** (on January 2018). You are encouraged to upgrade to Ubuntu 17.10 or use Ubuntu LTS.

**Comment by netheril96** [comment]
So the official repo in Ubuntu 17.10 has the latest version for ss-libev?

**Comment by crysislinux** [comment]
It's 3.0.8+ds-2 on Ubuntu 17.10, also not update to date.
