### ISSUE TITLE
Failed to handshake when simple-obfs is enabled

### ISSUE THREAD

**Issue by nicolo01** [shadowsocks/shadowsocks-libev#1858]
### What version of shadowsocks-libev are you using?
Shadowsocks-libev v3.1.1
simple-obfs v0.0.5

### What operating system are you using?
Raspbian Stretch Lite

### What did you expect to see?
No errors

### What did you see instead?

> 2017-12-17 05:49:36 ERROR: failed to handshake with 127.0.0.1: invalid host name
2017-12-17 05:49:36 [simple-obfs] ERROR: remote recv: Connection reset by peer
2017-12-17 05:49:45 ERROR: failed to handshake with 127.0.0.1: invalid host name
2017-12-17 05:49:45 [simple-obfs] ERROR: remote recv: Connection reset by peer
2017-12-17 05:49:45 ERROR: failed to handshake with 127.0.0.1: invalid address type
2017-12-17 05:49:45 [simple-obfs] ERROR: remote recv: Connection reset by peer

### What is your config in detail (with all sensitive info masked)?

> 	"server": "0.0.0.0",
	"server_port": "8388",
	"password": "****",
	"method": "chacha20-ietf-poly1305",
	"timeout": "300",
	"plugin": "obfs-server",
	"plugin_opts": "obfs=http"

It only happens when simple-obfs is enabled

EDIT: That was an old log, this is the correct one
> Dec 27 14:24:24 raspberrypi ss-server[425]:  2017-12-27 14:24:24 ERROR: failed to handshake with 127.0.0.1: authentication error
Dec 27 14:24:24 raspberrypi ss-server[425]:  2017-12-27 14:24:24 [simple-obfs] ERROR: remote recv: Connection reset by peer
Dec 27 14:24:27 raspberrypi ss-server[425]:  2017-12-27 14:24:27 ERROR: failed to handshake with 127.0.0.1: authentication error
Dec 27 14:24:27 raspberrypi ss-server[425]:  2017-12-27 14:24:27 [simple-obfs] ERROR: remote recv: Connection reset by peer

**Comment by madeye** [comment]
Double check your client's config.

**Comment by nicolo01** [comment]
Checked, it's correct.
I encounter this error only when I enable simple-obfs client side so authentication is not the problem.

**Comment by nicolo01** [comment]
I think this is the same issue of #1575

**Comment by madeye** [comment]
1. Post your client's config here.
2. Try TLS mode.

**Comment by nicolo01** [comment]
I am using the android client, however my settings are:
server "myddns.ddns.net", remote port "8388", local port "1080", encryption method "chacha20-ietf-poly1305", remote dns "8.8.8.8", obfuscation wrapper "http", obfuscation hostname "www.bing.com"

TLS doesn't work either

**Comment by madeye** [comment]
It looks you're behind a SNI proxy or something similar. It's a limitation of simple-obfs that it cannot work with a SNI proxy.

As it's not an issue of shadowsocks-libev, I suggest to use other plugins, e.g. kcptun, instead.
