### ISSUE TITLE
What is the sssniff?

### ISSUE THREAD

**Issue by tetroider** [shadowsocks/shadowsocks-libev#1859]
https://github.com/madeye/sssniff
1) In readme I can see ss(r)Sniff and sssniff. So, that is the ShadowSocksR? Is it a modification of Shadowsocks?
2) "Finally, browse the web via your SS proxy. When the script detects more than 15 suspicious connections to/from one source, it will flag it to be a ShadowSocks server and print to the terminal." - but computer generate a lot of traffic. How does it relate with ShadowSocks. And what means suspicious?
3) "ShadowSocks is famous for its randomness feature" - is it about randomly generated IV?
4) "however, the first packet of a connection is usually not expected to be random. Even in a TLS session, we expect to see some plaintext sections in the handshake stage." - but SS encrypt data by long key and randomply generated IV, so data from client to SS will be totally encrypted, without plain text.
5) "Therefore, one can detect ShadowSocks traffic by simply looking at the first few packets and calculating their entropy (as a measure of randomness). Together with some minor adjustments, this method suffices to detect the current ShadowSocks protocol at a high accuracy." - that do you mean? If you will look at first packets you will see encrypted data. Moreover you can't know, that cipher type is used, so it is imposible to cut encrypted data from IV. So how can you calculate entropy, if every connection encrypted by random IV?
So I can`t understand, where sssniff must work - on ISP, client or server side? How it will calculate entropy of randomly encrypted data? What difference between SSR and SS?

**Comment by madeye** [comment]
Please don't post general questions here. This issue tracker is for tracking bugs of shadowsocks-libev.
