### ISSUE TITLE
build_deb.sh does not work when git user is not set

### ISSUE THREAD

**Issue by hefanbo** [shadowsocks/shadowsocks-libev#1862]
There are `git commit` command in build_deb.sh
When git user name/email is not set, the script fails to build.
Fix: either set git user name/email in the script, or tell user to set them in the README file.

### What operating system are you using?
Ubuntu 16.04

### What did you do?
Run build_deb.sh

### What did you expect to see?
Get shadowsocks-libev*.deb

### What did you see instead?
Fails to build

**Comment by rogers0** [comment]
@hefanbo you can patch it to make it complete/better.
