### ISSUE TITLE
google.com can not be accessed,  however the google.com.hk and other websites such as facebook, twitter  can

### ISSUE THREAD

**Issue by yincu** [shadowsocks/shadowsocks-libev#1863]
### What version of shadowsocks-libev are you using?
server: shadowsocks-libev 3.1.0    centos7
client：shadowsocks-libev   3.1.1-1  installed in my router.

### What operating system are you using?
Model | Linksys WRT1900ACS
Firmware Version | LEDE Reboot 17.01.4 r3560-79f57e422d / LuCI lede-17.01 branch (git-17.290.79498-d3f0685)

### What did you do?
The website google.com can not be accessed,  however the google.com.hk and other websites such as facebook, twitter  can.

Moreover,  the google.com can be accessed through  the shadowsocks client of Windows version.  This proves that the server is all right.

### What did you expect to see?
The google.com can be accessed correctly!

**Comment by yincu** [comment]
## **The shadowsocks only run the "Transparent Proxy"  subprogram. The configuration is below:**
=============================
![image](https://user-images.githubusercontent.com/31179226/34427103-3b516992-ec79-11e7-8b4c-a12d1d3d9bd2.png)

## **And more:**
=============================
![image](https://user-images.githubusercontent.com/31179226/34427148-c6408286-ec79-11e7-9b14-3dc222010dfe.png)

===============================
## **I installed DNS-Forwarder and ChinaDNS packages.  Now I have disabled both ,and  it makes no differences.**
## 
**The DHCP and DNS configurations is as below:**
=================================
![image](https://user-images.githubusercontent.com/31179226/34427265-5e75595e-ec7b-11e7-8133-76fb0fcb8840.png)
![image](https://user-images.githubusercontent.com/31179226/34427296-dee0c54c-ec7b-11e7-8d5b-6dd1dabd2e61.png)

==================================
**Other configurations are default values. 
Is the information above enough ?**

**Comment by yincu** [comment]
Log in the router through ssh, I got this:

root@LEDE:~# ps | grep ss-
10876 root      1992 S    ss-redir -c /var/etc/shadowsocks.cfg024a8f.json -l 1234 --mtu 1492 -f /var/run/ss-redir-cfg024a8f.pid
root@LEDE:~# cat /var/etc/shadowsocks.cfg024a8f.json 
{
    "server": "xxx.xx.xxx.xxx",
    "server_port":  3641,
    "password": "********",
    "method": "aes-256-cfb",
    "local_address": "0.0.0.0",
    "timeout": 60,
    "reuse_port": true
}

**Comment by madeye** [comment]
It's a typical DNS poisoning issue. You may try any safe DNS resolving solution like https://dnscrypt.org/

**Comment by yincu** [comment]
Thanks a lot.  I would  reference  it.
