### ISSUE TITLE
the gfw banned my ip using default setttings.

### ISSUE THREAD

**Issue by youxiaojie** [shadowsocks/shadowsocks-libev#1866]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
3.1.1 by debian jessie-backports-sloppy

### What operating system are you using?
debian jessie

### What did you do?
setting up server

### What did you see instead?
the gfw banned my ip

### What is your config in detail (with all sensitive info masked)?
all by default 0.0.0.0:8388, chacha20-ietf-poly1305

I am in beijing

**Comment by madeye** [comment]
First of all, you need to make sure if your IP is banned. You may try this tool: http://www.17ce.com/mtr

Also, I don't think your issue is related to shadowsocks-libev, unless you can provide more info.

**Comment by youxiaojie** [comment]
OK butbefore I use SS the cac host can be ssh and ping when I use it for days could not ssh and ping directly but through vpn it can ssh and ping.change IP I find the C sub net is banned. maybe the default port 8388 29000 makes GFW get final decision. So now I reinstall vps to get another ip with different sub net with 8080 port and use simple obfs plugin with tls setting.
