### ISSUE TITLE
I've always got the problem"option -d not recognized" once I use the option -d

### ISSUE THREAD

**Issue by LeonLH** [shadowsocks/shadowsocks-libev#1867]
### What version of shadowsocks-libev are you using?
shadowsocks-libev 3.1.2

### What operating system are you using?
Ubuntu16.04.3 LTS

### What did you do?
Once I add the option -d to "sudo ssserver(or sslocal) -c /etc/shadowsocks-libev/config.json" I got a problem "option -d not recognized".When I remove the option  "-d" It seems run normally(not very certain).

### What is your config in detail (with all sensitive info masked)?
![snap_screen_20180102175431](https://user-images.githubusercontent.com/17843410/34480214-01b8ccaa-efe6-11e7-8af0-2f80c7c815eb.png)

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks-libev/blob/master/doc/shadowsocks-libev.asciidoc

**Comment by hosiet** [comment]
Neither `ssserver` nor `sslocal` is provided by shadowsocks-libev. They are provided by python version of shadowsocks.

**Comment by LeonLH** [comment]
@hosiet Thank you ! 
So how can I boot shadowsocks-libev backgroud in my ubuntu.I find an answer it says using "-f " and then I tried some time but I couldn't find the path to pidfile.
Is using "-f " is right? or could you advice me some more commander?

**Comment by hosiet** [comment]
You are supposed to use systemd to manage ss-libev as a system service. To accomplish that, you need some basic knowledge around systemd on Linux.

Besides that, all standard UNIX ways of daemonizing processes are applicable to ss-libev server.

**Comment by LeonLH** [comment]
@hosiet Ok,thank you very much and have a good day~

**Comment by LeonLH** [comment]
At last I use "&>>" to put the infos into a file named ss.log and add a "&" in the end to make the process working in the backgroud.
