### ISSUE TITLE
debian 的 simple-obfs 包安完后会多出一个配置文件 是否要改名覆盖原来的？

### ISSUE THREAD

**Issue by youxiaojie** [shadowsocks/shadowsocks-libev#1869]
debian 的 simple-obfs 包安完后会多出一个配置文件config-obfs.json 是否要改名覆盖原来的config.json？

**Comment by heiybb** [comment]
obfs.josn提供了一个在你需要启用obfs插件时的参考sample
根据自己需求修改后在启动时指定该文件即可

**Comment by rogers0** [comment]
@youxiaojie you can change the config filename in /etc/default/shadowsocks-libev

**Comment by youxiaojie** [comment]
我是改名了 原来的config.json 删掉 可否？

**Comment by hosiet** [comment]
As long as you don't think this file is necessary, it's on your own.
