### ISSUE TITLE
about mode:tcp_and_udp (-u)

### ISSUE THREAD

**Issue by rogers0** [shadowsocks/shadowsocks-libev#1870]
In default debian packaging (before I started to maintain), mode:tcp_and_udp is set in hidden.
I mean, it's not in config.json, but with the command line "-u" in /etc/default/shadowsocks-libev.
I don't think it's a good, and want to move it to config.json.

Sorry, I don't understand the internals, so I have questions:
 - is mode:tcp_and_udp usually a must option for common user?
 - is it related to nameserver option (-d)?
 - I guess mode:tcp_and_udp is a must for user to use nameserver option. But if user doesn't use nameserver option can safely set mode as tcp_only. Am I right?
 - If above is true, it's better to state it clear in asciidoc/manpage.

Thanks!

**Comment by madeye** [comment]
- Nope. It'd be optional.
- Nope. `-d` is a server only option that configure the DNS server for any `addrtype == 3` requests.
- Actually not. By default we disable UDP relay because it's not necessary for a normal proxy usage.

**Comment by rogers0** [comment]
@madeye Thanks for your confirm!
So I think it's safe to remove "-u" from /etc/default/shadowsocks-libev
I'll do it on next debian release.

**Comment by rogers0** [comment]
@madeye I tested on my android client, seems not as you said.
After disabling the UDP port ss-libev uses in firewall rules of the server side, the android client cannot connect anymore.

Maybe the "DNS forwarding" option in android client depends on "-u" on the server side?

**Comment by madeye** [comment]
@rogers0 That's why we keep "DNS forwarding" disabled by default.

Actually, UDP relay doesn't work well in many situations due to NAT issues.

**Comment by rogers0** [comment]
@madeye Thanks for your info!
But "DNS forwarding" seems necessary in DNS poisoning network, which is not rare on this planet.
If "DNS forwarding" of client side rely on mode:tcp_and_udp of server side, I think:
 - default config need to include mode:tcp_and_udp
 - it's better to add this info in asciidoc/manpage

**Comment by madeye** [comment]
> But "DNS forwarding" seems necessary in DNS poisoning network

Actually not, without UDP relay, remote DNS resolving can be performed in TCP.

**Comment by rogers0** [comment]
>> But "DNS forwarding" seems necessary in DNS poisoning network

> Actually not, without UDP relay, remote DNS resolving can be performed in TCP.

Good to know.
So I think the situation is as following. Please help to confirm my understanding.

case A: android client enables "DNS forwarding", server side sets as mode:tcp_and_udp
  => depends on NAT of UDP packet, if it fails it'll fallback to case C.
case B: android client enables "DNS forwarding", server side sets as mode:tcp_only
  => cannot connect at all
case C: android client disables  "DNS forwarding", server side sets as mode:tcp_and_udp
  => can access normally, but may slower than case A if it connects well.
case D: android client disables "DNS forwarding", server side sets as mode:tcp_only
  => same as case C.

Thanks!

**Comment by madeye** [comment]
Correct.

**Comment by hybtoy** [comment]
@madeye 
Is it safe to resolve dns requests localy?
I mean, if I will resolve google.com through 8.8.8.8 localy or send it to remote server with udp relay.
