### ISSUE TITLE
Is "-U" available in local mode?

### ISSUE THREAD

**Issue by initrider** [shadowsocks/shadowsocks-libev#1871]
https://github.com/shadowsocks/shadowsocks-libev/blob/master/README.md :
> [-U]  nable UDP relay and disable TCP relay,
> not available in local mode

https://github.com/shadowsocks/shadowsocks-libev/blob/master/doc/ss-local.asciidoc :
> -U Enable UDP relay and disable TCP relay.

So is "-U" available in local mode or not. And if it is available, how it works? As I know, ss-local works as socks5 (https://tools.ietf.org/html/rfc1928) and if client want to send udp packet through socks5 server, it must to send udp assoc request on 1080 tcp port, but if I run ss-local with -U option it binds only 1080 udp port (SS 3.1.1).

**Comment by madeye** [comment]
When this option is enabled, ss-local won't follow RFC1928 any more and work as a UDP relay only.

**Comment by initrider** [comment]
Well. Sorry for my meticulousness :satisfied:
1) Change readme.md - in future it can became big misunderstanding.
2) `Shadowsocks-libev consists of five components. ss-local(1) works as a standard socks5 proxy on local machines to proxy TCP traffic.` - why only TCP, it can UDP - as follow manual.
3) Maybe I don't know something, but who needs -U option? If it not follow RFC1928 no one application will be able to work with that.

**Comment by initrider** [comment]
So, as I understand, if i enable **-u**, on every **udp assoc** request, ss-local will reply with **bnd.port = 1080**, that means client must send udp packet to 1080 UDP port, or ss-local will open random udp port for every udp assoc request?

**Comment by madeye** [comment]
Yes,  only port 1080.
