### ISSUE TITLE
ss-local delayed connect when SOCKS request come with app data

### ISSUE THREAD

**Issue by sorz** [shadowsocks/shadowsocks-libev#1872]
### What version of shadowsocks-libev are you using?
3.1.2 

### What operating system are you using?
Linux x86_64 4.14

### What did you do?
1. Run `ss-local` with TCP relay and `--fast-open` on.
2. Do normal SOCKSv5 handshaking with `ss-local`, then send a TCP DNS request over it.
3. Measuring the total waiting time between request sent and DNS reply got.
4. Repeat step 2 & 3. But on step 2, instead of waiting for SOCKS reply, **send SOCKS request and DNS request together within one single `send()`**.

### What did you expect to see?
Two time measurements have roughly equivalent result (1 RTT, ~50ms in my case).

### What did you see instead?
First measurement got 50ms delay.
The second one got around 100ms delay.

I guess the extra 50ms was introduced by the `delayed_connect_watcher`.
In step 4, no event tigger the server to do connect, unitl the watcher timed out in 50ms.

### What is your config in detail (with all sensitive info masked)?
Provide on request.

**Comment by madeye** [comment]
As you mentioned, it's a expected behavior.

If you are really care about this delay, please change the numbers in the source code.

**Comment by sorz** [comment]
Can we somehow tigger the server to do connect inside here?

https://github.com/shadowsocks/shadowsocks-libev/blob/cba94db423caa4c590fd679e722c983908bb35e3/src/local.c#L795-L798

**Comment by madeye** [comment]
Of course you can. You can immediately establish the connection here which would not cause any problem.

**Comment by madeye** [comment]
Please try afce1b3.

**Comment by sorz** [comment]
It works, thank you!
