### ISSUE TITLE
shadowsocks-libev And FreeRadius

### ISSUE THREAD

**Issue by BenYamin313** [shadowsocks/shadowsocks-libev#1873]
Hello
simple question, How to connect shadowsocks-libev to the FreeRadius server
Can you help me ?

**Comment by bloggervista** [comment]
Yes, i am also finding same trouble to connect to free radius server based on ubuntu.

**Comment by rogers0** [comment]
I think it's a wishlist feature request.
It's not so "simple".

**Comment by BenYamin313** [comment]
@bloggervista 
Hello,
Did you find the solution? ،How did you do this based on ubuntu ?

**Comment by BenYamin313** [comment]
@rogers0  One of the shortcomings of this program is not having a radius , Your thought is wrong !

**Comment by BenYamin313** [comment]
@madeye  
Please join discussion and help 
Thank you.

**Comment by madeye** [comment]
I don't think it's related to shadowsocks. If you're looking for an authentication solution for shadowsocks. Please refer to https://github.com/shadowsocks/shadowsocks-manager
