### ISSUE TITLE
A long-standing bug in HTTP/SNI

### ISSUE THREAD

**Issue by qwIvan** [shadowsocks/shadowsocks-libev#1876]
### What version of shadowsocks-libev are you using?
Any versions with HTTP/SNI.

### What operating system are you using?
ArchLinux

### What did you do?
Send a HTTP request separated by LF(`'\n'`) instead of CRLF(`'\r\n'`) through ss-redir proxy with HTTP/SNI.

### What did you expect to see?
Receive a HTTP response.

### What did you see instead?
Lost the last character of domain while `src/http.c` parse the HOST header, unless I disable HTTP/SNI.

### What is your config in detail (with all sensitive info masked)?
Any case if I enable HTTP/SNI.
`"disable_sni": false`

You can try to do this for testing:
```
#!/bin/sh
cat > request << EOF
GET /translate_a/single?client=gtx&ie=UTF-8&oe=UTF-8&dt=bd&dt=ex&dt=ld&dt=md&dt=rw&dt=rm&dt=ss&dt=t&dt=at&dt=qca&sl=auto&tl=zh-CN&hl=zh-CN&q=man HTTP/1.1
Host: translate.googleapis.com
Connection: close
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/602.1 (KHTML, like Gecko) Version/8.0 Safari/602.1 Epiphany/3.18.2

EOF
nc translate.googleapis.com 80 < request
```
You can see:
```
connect to translate.googleapis.co:80
failed to lookup v4 address Domain name not found
failed to lookup v6 address Domain name not found
unable to resolve translate.googleapis.co
```
on logs of ss-server(enable Verbose mode), unless you encounter DNS hijacking.
If you using v2.5.1(before [this commit](https://github.com/shadowsocks/shadowsocks-libev/commit/5ee00d2647e150dc6429fd01954ecef15b115fd6)), similar logs can also be seen on ss-redir(enable Verbose mode). Can be seen through the logs, the last character of domain `translate.googleapis.com`, `m` has been lost.

This bug will cause [translate-shell](https://github.com/soimort/translate-shell) can not work with ss-redir, so I already created a [pull-request](https://github.com/soimort/translate-shell/pull/207) to fix CRLF problem. I also created a pull-request for compatible with LF(`'\n'`) mode, hope can be merged because this is not a special case.

**Comment by qwIvan** [comment]
BTW, default to enable SNI is a bad design.
Same with  #1503 

> I can understand that this is an appreciated feature when DNS requests are poisoned ( as stated here : #944 )
But it's kind of annoying for users on the local network to see their requests being 'wrongly' redirected despite their own specific DNS configuration

I suggest disable SNI by default.
For some feature to resolve DNS poison, you can even create a standalone branch.
Shouldn't to do this dirty hack, It interferes with the normal TCP flow.

**Comment by madeye** [comment]
Could you list any application that follows the behavior you mentioned here?

**Comment by madeye** [comment]
Fixed via 539bf6e.

**Comment by qwIvan** [comment]
It seems that SNI is completely closed

**Comment by PantherJohn** [comment]
@qwIvan `http.c` and `tls.c` are maintained by @dlundquist. Please submit issues [here](https://github.com/dlundquist/sniproxy/issues).
