### ISSUE TITLE
ss-local doesn't work after installed

### ISSUE THREAD

**Issue by David3310273** [shadowsocks/shadowsocks-libev#1880]
### What version of shadowsocks-libev are you using?
just add the repository key to install as the wiki describes, so I guess it's a recent version.

### What operating system are you using?
ubuntu 16.04-LTS

### What did you do?
I just iunstalled the libev and modified the config.json file as follows:
```
{
    "server":"remote server name",
    "server_port":"remote server port",
    "local_port":1080,
    "password":"password",
    "timeout":60,
    "method":"chacha20-ietf-poly1305"
}

```
then I started the ss-local command as follows:
```
ss-local -c /path/to/my/config.json
```
it shows the following content and it doesn't work when I access google on my chromium, the content does not changed even if the accessing procedure.
```
 2018-01-10 00:57:06 INFO: initializing ciphers... chacha20-ietf-poly1305
 2018-01-10 00:57:06 INFO: listening at 127.0.0.1:1080
 2018-01-10 00:57:06 INFO: running from root user
```

### What did you expect to see?
it works when I access youtube and etc.

### What did you see instead?
it not works

### What is your config in detail (with all sensitive info masked)?
```
{
    "server":"remote server name",
    "server_port":"remote server port",
    "local_port":1080,
    "password":"password",
    "timeout":60,
    "method":"chacha20-ietf-poly1305"
}
```

**Comment by sylinuxhy** [comment]
how ？

**Comment by google9002** [comment]
Got the same problem，how did you fix it？

**Comment by sunduda** [comment]
Same here, haven’t fix it yet.

**Comment by google9002** [comment]
@sunduda Solved this for me. My config.json has this line ["local_address": 127.0.0.1]. I deleted this line and it works well. Don't know why. It now even works with obfs.
