### ISSUE TITLE
disable_sni选项在新版本中取消了？

### ISSUE THREAD

**Issue by reusu** [shadowsocks/shadowsocks-libev#1881]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
3.1.2

### What operating system are you using?
Ubuntu 16.04

### What did you do?
参考之前的issue
https://github.com/shadowsocks/shadowsocks-libev/issues/1623
请问下disable_sni在新版本中取消了
那么现在的版本还会不会自动走sni解析呢
如果会的化要达成之前的功能需要怎么操作

**Comment by madeye** [comment]
SNI is removed from ss-redir. There is still a SNI parser in ss-local for ACL only.
