### ISSUE TITLE
forbid other port access to ss-server

### ISSUE THREAD

**Issue by gr01d** [shadowsocks/shadowsocks-libev#1884]
### What version of shadowsocks-libev are you using?
3.1.1+ds-1~bpo9+1

### What operating system are you using?
Debian 9 (Raspbian)

### What did you do?
normal installation of shadowsocks run with custom user(ssuser), attempt to blocking port access to server (which ss-server is installed), attempt block brute force attackers  using the ff:
https://github.com/shadowsocks/shadowsocks/wiki/Securing-Public-Shadowsocks-Server
https://github.com/shadowsocks/shadowsocks/wiki/Block-Connection-to-localhost
https://github.com/shadowsocks/shadowsocks/wiki/Ban-Brute-Force-Crackers
### What did you expect to see?
blocking of access to non-http/https sites
The server with the shadowsocks is installed has other services such as mysql and other localhost only services but if I connect to the server using shadowsocks-client, the client appears to have access to the server so it can conenct to mysql and other-not-supposed-to-be-connectable outside of server localhost.

### What did you see instead?
no blocking to any port or IP

### What is your config in detail (with all sensitive info masked)?
```
$ sudo su ssuser -c nohup /usr/bin/ss-server -c /etc/shadowsocks-libev/config.json -v > /var/log/ss.log

{
    "server":"0.0.0.0",
    "server_port":PORT,
    "local_address": "127.0.0.1",
    "local_port":1080,
    "password":"PASSWORD",
    "timeout":150,
    "method":"chacha20-ietf-poly1305"
}

```
Also, I cannot find the log file of shadowsocks so I cant block potential brute forcers.

**Comment by madeye** [comment]
shadowsocks-libev has a built-in blocking mechanism for brute force attack.

**Comment by gr01d** [comment]
@madeye What about blocking access to server's localhost ports preferably mysql port. The link https://github.com/shadowsocks/shadowsocks/wiki/Block-Connection-to-localhost does not work
