### ISSUE TITLE
getaddrinfo block and return "nodename nor servname provided, or not known"

### ISSUE THREAD

**Issue by Contextualist** [shadowsocks/shadowsocks-libev#1885]
### What version of shadowsocks-libev are you using?
3.1.2 ss-local

### What operating system are you using?
macOS 10.12.6

### What did you do?
I started ss-local with an ACL whitelisting the China IPs. Then I went visiting some foreign websites such as GitHub.

### What did you expect to see?
The response latency should be similar to that with ACL disabled (i.e. forced server-side resolve)

### What did you see instead?
* For the first-time visit or if I hadn’t visited a domain for minutes, the response (before page loading) took a long time (more than 10s; much longer than with ACL disabled or without proxy). (p.s. When I visited Chinese websites, there is no significant delay.)
* `ss-local.log` output showed `ERROR: getaddrinfo: nodename nor servname provided, or not known`.

### What is your config in detail (with all sensitive info masked)?
```
{
  "method" : "aes-128-gcm",
  "server" : "***",
  "password" : "***",
  "local_address" : "127.0.0.1",
  "server_port" : 9527,
  "timeout" : 60,
  "local_port" : 1086
}
```

Seemingly my local DNS resolving for foreign website is very slow so `getaddrinfo` often timeout, and that timeout is quite large. However, every time I do `dig github.com` (before or after I visited in browser), it returned the cached result instantly. What causes the problem? What else should I do to narrow down the problem?

I found that `getaddrinfo` is a quite generic function and lack of any timeout setting. Is there any better alternative so that the name resolving strategy can be robust when local resolving for some domain is slow? I notice that ss-local does not adapt c-ares like ss-server does. Will c-ares solve the problem for ss-local? Or will it be unnecessary?

**Comment by madeye** [comment]
Please don't use IP blocks in ACL rules. It's expected to be slow.

**Comment by madeye** [comment]
Find more details here: https://github.com/shadowsocks/shadowsocks-libev/pull/1474

**Comment by Contextualist** [comment]
I see. Thanks for the information. But is it possible to have a `-d <addr>` flag for ss-local, where the user can provide a *clean* local DNS and do forced local resolve? When the flag is set, all `addr type 3` is resolved locally (probably with c-ares) and acl-matched. The proxied ones are converted to type 1 or 4 before sending to the server.

**Comment by madeye** [comment]
> When the flag is set, all addr type 3 is resolved locally (probably with c-ares) and acl-matched.

As a SOCKS5 proxy, actually we're trying out best to avoid this. If you really need IP based ACL, try `ss-redir` with `ipset` instead.

And using PACs in your browser is always a better choice.

**Comment by Contextualist** [comment]
OK. Seem like it's impossible to do port redirection on macOS. Maybe a router solution (like VRouter) is what I am looking for.
