### ISSUE TITLE
Server can't start automatically when using an ipv6 address

### ISSUE THREAD

**Issue by changhexiong** [shadowsocks/shadowsocks-libev#1886]
### What version of shadowsocks-libev are you using?
3.0.8, from repository.

### What operating system are you using?
Ubuntu 17.10 (GNU/Linux 4.13.0-25-generic x86_64)

### What did you do?
Used an ipv6 address in config.json
systemctl enable shadowsocks-libev.service

### What did you expect to see?
ss-server start when system boot up

### What did you see instead?

shadowsocks-libev.service failed with error code 255 when system boot up
ERROR: bind: Cannot assign requested address
ERROR: bind() error
shadowsocks-libev.service: Main process exited, code=exited, status=255/n/a
shadowsocks-libev.service: Unit entered failed state.
shadowsocks-libev.service: Failed with result 'exit-code'.

But when I restart it (systemctl restart shadowsocks-libev.service), no error occured.

### What is your config in detail (with all sensitive info masked)?

{
    "server":"0:0:0:0:0:0:0:0",
    "server_port":8000,
    "local_port":1080,
    "password":"password",
    "timeout":60,
    "method":"aes-256-cfb"
}

**Comment by whour** [comment]
`"server":["0.0.0.0","::0"]`
