### ISSUE TITLE
newest commit's deb package can't be installed 

### ISSUE THREAD

**Issue by debiansid** [shadowsocks/shadowsocks-libev#1889]
### What version of shadowsocks-libev are you using?

3.1.2
### What operating system are you using?

debian wheezy
### What did you do?

install newest deb file
### What did you expect to see?
installation goes well

### What did you see instead?
```
dpkg -i shadowsocks-libev_3.1.2-1_mips.deb
(Reading database ... 31976 files and directories currently installed.)
Preparing to replace shadowsocks-libev 3.1.2-1 (using shadowsocks-libev_3.1.2-1_mips.deb) ...
Unpacking replacement shadowsocks-libev ...
dpkg: dependency problems prevent configuration of shadowsocks-libev:
 shadowsocks-libev depends on libsodium; however:
  Package libsodium is not installed.

dpkg: error processing shadowsocks-libev (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 shadowsocks-libev
vbash-4.1# dpkg -l |grep libsodium
ii  libsodium23:mips                 1.0.16-1                            mips         Network communication, cryptography and signaturing library
```

**Comment by debiansid** [comment]
during shadowsocks-libev deb building process I fount this
```
libtool: warning: library '/usr/lib/libsodium.la' was moved.
```

**Comment by debiansid** [comment]
I switched libsodium23-1.0.16 back to libsodium18-1.0.13-1~bpo8+1. everything is back working.

@Rogers0
how to upgrade wheezy libsodium to newest?

**Comment by rogers0** [comment]
@debiansid wheezy lts will be ended in less than 3 months.
I think you shouldn't spend time on wheezy anymore.

**Comment by debiansid** [comment]
@rogers0  I have no choice, ubnt usg is based on debian wheezy.
