### ISSUE TITLE
tcp_fastopen error on debian wheezy 

### ISSUE THREAD

**Issue by debiansid** [shadowsocks/shadowsocks-libev#1890]
### What version of shadowsocks-libev are you using?
3.1.2 release

### What operating system are you using?
debian wheezy

### What did you do?
enable tfo in config.json

### What did you expect to see?
ss-redir running

### What did you see instead?
```
Jan 14 15:17:27 usg-3p /usr/bin/ss-redir[18954]: tcp fast open is not supported on this platform
```
### other info
```
vbash-4.1# cat /proc/sys/net/ipv4/tcp_fastopen
3
vbash-4.1# uname -a
Linux usg-3p 3.10.20-UBNT #1 SMP Fri Jun 23 08:31:09 MDT 2017 mips64 GNU/Linux
```

3### What is your config in detail (with all sensitive info masked)?
{
        "server": "xxxxxxxxxx",
        "server_port": 1234,
        "local_port": 1080,
        "password": "xxxx",
        "plugin": "obfs-local",
        "plugin_opts": "obfs=http;obfs-host=cloudfront.net;fast-open;a=nobody",
        "mode": "tcp_and_udp",
        "fast_open": true,
        "timeout": 60,
        "method": "chacha20-ietf-poly1305"
}

**Comment by debiansid** [comment]
I just found 3.1.2 changes have this "Add new TFO API support."
is it possible that broke my tfo?

**Comment by debiansid** [comment]
I can confirm TFO on 3.1.1 is working! 
```
etc/init.d/ss-redir restart                    
ss-redir is stopped                                        
 2018-01-14 17:40:50 INFO: plugin "obfs-local" enabled     
 2018-01-14 17:40:50 INFO: using tcp fast open             
Starting ss-redir success 
```

**Comment by madeye** [comment]
Build from source code and try again.

**Comment by madeye** [comment]
Make sure you have TFO related headers when building the source code.

**Comment by debiansid** [comment]
@madeye I build 3.1.1 and 3.1.2 on same machine.

**Comment by debiansid** [comment]
```
sudo dpkg -l |grep linux-headers
ii  linux-headers-3.16.0-0.bpo.4-5kc-malta        3.16.7-ckt25-2~bpo70+1            mips         Header files for Linux 3.16.0-0.bpo.4-5kc-malta
ii  linux-headers-3.16.0-0.bpo.4-common           3.16.7-ckt25-2~bpo70+1            mips         Common header files for Linux 3.16.0-0.bpo.4
```
This is build machine.

You mean on the target I will run 3.1.2?

**Comment by madeye** [comment]
Make sure `/usr/include/linux` has TFO headers.

**Comment by debiansid** [comment]
```
sudo ls  /usr/include/linux/tcp*
/usr/include/linux/tcp.h  /usr/include/linux/tcp_metrics.h
```

**Comment by madeye** [comment]
`grep TCP_FASTOPEN /usr/include/linux/tcp.h`

**Comment by debiansid** [comment]
```
grep TCP_FASTOPEN /usr/include/linux/tcp.h
#define TCP_FASTOPEN            23      /* Enable FastOpen on listeners */
```

**Comment by madeye** [comment]
If so, try rebuild from source code.

**Comment by debiansid** [comment]
@madeye I don’t quite understand why it is working, you changed any code?

**Comment by debiansid** [comment]
But it is not stable.after about 1 hour, ss-redir crashed.
here is my /var/log/messages
```
Jan 15 21:43:13 usg-3p dhcpd: data: hardware: raw packet not available
Jan 15 22:14:00 usg-3p /usr/bin/ss-redir[19907]: tcp fast open is not supported on this platform
```

**Comment by madeye** [comment]
According to your log, your build didn't find any valid TFO headers.

That's why I suggest rebuilding your program and make sure you have valid TFO headers.

**Comment by madeye** [comment]
You have to figure out the building environment issue by yourself. Or you could try pre-built binaries from third-party.

**Comment by debiansid** [comment]
Why 3.1.1 is working with TFO?  I will try to build on another qemu mips instance.

**Comment by debiansid** [comment]
I compiled 3.1.3 again. it is runing with TFO so far
```
nobody   17949     1  0 14:14 ?        00:00:00 /usr/bin/ss-redir -c /etc/shadowsocks-libev/config.json -f /var
nobody   17950 17949  0 14:14 ?        00:00:00 obfs-local
```
let's see how long it will last.

**Comment by debiansid** [comment]
It crashed again.
```
Jan 16 18:10:39 usg-3p /usr/bin/ss-redir[17949]: tcp fast open is not supported on this platform
```

**Comment by madeye** [comment]
It's not a crash. As mentioned above, it means you have a broken header for TFO support.

Try `grep MSG_FASTOPEN /usr/include/linux/tcp.h"

**Comment by debiansid** [comment]
```
user@debian-mips:~$ grep MSG_FASTOPEN /usr/include/linux/tcp.h
user@debian-mips:~$
```
nothing shows up.
I tried this on debian9/alpine linux with newer kernel header, still nothing.

**Comment by madeye** [comment]
It's likely caused by broken headers in your building environment.

You can also try `find /usr/include -type f | xargs grep MSG_FASTOPEN` to check if you have TFO headers in your include path.

The easiest way to check if you have a good environment is building and running ss-local in your building environment.

You may keep using old versions, as we used pre-defined headers in our source code.

**Comment by debiansid** [comment]
I managed to add 
'''
#define MSG_FASTOPEN    0x20000000
'''
into tcp.h

**Comment by debiansid** [comment]
I just start running ss-redir with TFO enabled. I thought this should be the fix.

**Comment by 0neday** [comment]
@madeye 
`[hongs@dnsmasq OpenWrt-SDK-15.05.1-omap_gcc-4.8-linaro_uClibc-0.9.33.2_eabi.Linux-x86_64]$ find . -name tcp.h
./build_dir/target-arm_cortex-a9+vfpv3_uClibc-0.9.33.2_eabi/linux-omap/linux-3.18.23/include/linux/tcp.h
./build_dir/target-arm_cortex-a9+vfpv3_uClibc-0.9.33.2_eabi/linux-omap/linux-3.18.23/include/net/tcp.h
./build_dir/target-arm_cortex-a9+vfpv3_uClibc-0.9.33.2_eabi/linux-omap/linux-3.18.23/include/uapi/linux/tcp.h
./build_dir/target-arm_cortex-a9+vfpv3_uClibc-0.9.33.2_eabi/linux-omap/linux-3.18.23/include/config/atm/tcp.h
./staging_dir/toolchain-arm_cortex-a9+vfpv3_gcc-4.8-linaro_uClibc-0.9.33.2_eabi/include/linux/tcp.h
./staging_dir/toolchain-arm_cortex-a9+vfpv3_gcc-4.8-linaro_uClibc-0.9.33.2_eabi/include/netinet/tcp.h
[hongs@dnsmasq OpenWrt-SDK-15.05.1-omap_gcc-4.8-linaro_uClibc-0.9.33.2_eabi.Linux-x86_64]$ grep TCP_FASTOPEN ./build_dir/target-arm_cortex-a9+vfpv3_uClibc-0.9.33.2_eabi/linux-omap/linux-3.18.23/include/linux/tcp.h
#define TCP_FASTOPEN_COOKIE_MIN 4       /* Min Fast Open Cookie size in bytes */
#define TCP_FASTOPEN_COOKIE_MAX 16      /* Max Fast Open Cookie size in bytes */
#define TCP_FASTOPEN_COOKIE_SIZE 8      /* the size employed by this impl. */
        u8      val[TCP_FASTOPEN_COOKIE_MAX];
[hongs@dnsmasq OpenWrt-SDK-15.05.1-omap_gcc-4.8-linaro_uClibc-0.9.33.2_eabi.Linux-x86_64]$ grep TCP_FASTOPEN ./staging_dir/toolchain-arm_cortex-a9+vfpv3_gcc-4.8-linaro_uClibc-0.9.33.2_eabi/include/netinet/tcp.h
[hongs@dnsmasq OpenWrt-SDK-15.05.1-omap_gcc-4.8-linaro_uClibc-0.9.33.2_eabi.Linux-x86_64]$ grep MSG_FASTOPEN ./build_dir/target-arm_cortex-a9+vfpv3_uClibc-0.9.33.2_eabi/linux-omap/linux-3.18.23/include/linux/tcp.h
[hongs@dnsmasq OpenWrt-SDK-15.05.1-omap_gcc-4.8-linaro_uClibc-0.9.33.2_eabi.Linux-x86_64]$
`

**Comment by 0neday** [comment]
@madeye 
What version of shadowsocks-libev are you using?
3.3.4 

What operating system are you using?
huawei ONT, omap, 3.10 kernel

What did you do?
enable tfo in config.json

ss-redir carsh when using tfo

![WeChat Image_20200229142850](https://user-images.githubusercontent.com/15697803/75602433-12195880-5b00-11ea-9004-e0d79fae8a56.png)

**Comment by 0neday** [comment]
> The easiest way to check if you have a good environment is building and running ss-local in your building environment.

```
[root@wg-quick armv5-eabi-uclibc-gcc9]# grep MSG_FASTOPEN ./arm-buildroot-linux-uclibcgnueabi/sysroot/usr/include/linux/tcp.h
[root@wg-quick armv5-eabi-uclibc-gcc9]# find ./arm-buildroot-linux-uclibcgnueabi/sysroot/usr/include  -type f | xargs grep MSG_FASTOPEN
./arm-buildroot-linux-uclibcgnueabi/sysroot/usr/include/bits/socket.h:    MSG_FASTOPEN  = 0x20000000, /* Send data in TCP SYN.  */
./arm-buildroot-linux-uclibcgnueabi/sysroot/usr/include/bits/socket.h:#define MSG_FASTOPEN      MSG_FASTOPEN
[root@wg-quick armv5-eabi-uclibc-gcc9]#

```
