### ISSUE TITLE
Ver 3.1.3 breaks macOS 10.13.x , not working!!!

### ISSUE THREAD

**Issue by Wyvern** [shadowsocks/shadowsocks-libev#1892]

**Comment by Wyvern** [comment]
Ver. 3.1.2 works perfect on macos, but after upgrade to 3.1.3 yesterday, all HSTS ssl websites cannot establish connections such as google twitter and facebook, but non-https and non HSTS https can be accessed such as github etc. It's a serious bug...

**Comment by Wyvern** [comment]
Or, could you give me a way to install older version of ss@3.1.2 on macos through brew package manager? thanks...

**Comment by changyp6** [comment]
I installed shadowsocks-libev 3.1.3 from brew, and it works perfectly as usual.
