### ISSUE TITLE
I can not get a connection with my VPS with simple-obfs used

### ISSUE THREAD

**Issue by MrMatttw** [shadowsocks/shadowsocks-libev#1894]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?

shadowsocks-libev 3.1.3

### What operating system are you using?

Ubuntu 16.04.3 LTS

### What did you do?
//These are on my VPS server

//Install shadowsocks-libev
$ sudo apt-get install --no-install-recommends build-essential autoconf libtool libssl-dev gawk debhelper dh-systemd init-system-helpers pkg-config asciidoc  xmlto apg libpcre3-dev zlib1g-dev libev-dev libudns-dev libsodium-dev libmbedtls-dev libc-ares-dev automake
$ git clone https://github.com/shadowsocks/shadowsocks-libev.git
$ cd shadowsocks-libev
$ git submodule update --init
$ ./autogen.sh && ./configure --prefix=/usr/local/shadowsocks
$ sudo make && sudo make install && sudo make clean
$ sudo ln -s /usr/local/shadowsocks/bin/* /usr/local/bin

//Install simple-obfs
$ sudo apt-get install --no-install-recommends build-essential autoconf libtool libssl-dev libpcre3-dev libev-dev asciidoc xmlto automake
$ git clone https://github.com/shadowsocks/simple-obfs.git
$ cd simple-obfs
$ git submodule update --init --recursive
$ ./autogen.sh
$ ./configure --prefix=/usr/local/simple-obfs
$ sudo make && sudo make install && sudo make clean
$ sudo ln -s /usr/local/simple-obfs/bin/* /usr/local/bin

//Create config file
$ touch /home/ubuntu/shadowsocks.json

//These are on my Windows Client
Download software from https://github.com/shadowsocks/shadowsocks-windows/releases/download/4.0.7/Shadowsocks-4.0.7.zip
Download plugin from https://github.com/shadowsocks/simple-obfs/releases/download/v0.0.5/obfs-local.zip
Decompress the Shadowsocks-4.0.7.zip file and Run shadowsocks.exe
Decompress the obfs-local.zip file in the directory which is same as shadowsocks

### What did you expect to see?

Shadowsocks can run normally with plugin simple-obfs

### What did you see instead?

On my server:

2018-01-20 11:18:09 INFO: plugin "obfs-server" enabled
 2018-01-20 11:18:09 INFO: initializing ciphers... aes-256-gcm
 2018-01-20 11:18:09 INFO: tcp server listening at 127.0.0.1:35497
 2018-01-20 11:18:09 INFO: running from root user
 2018-01-20 11:18:09 [simple-obfs] INFO: tcp port reuse enabled
 2018-01-20 11:18:09 [simple-obfs] INFO: listening at 0.0.0.0:8388
 2018-01-20 11:18:09 [simple-obfs] INFO: running from root user
 2018-01-20 11:18:20 ERROR: failed to handshake with 127.0.0.1: authentication error
 2018-01-20 11:18:20 [simple-obfs] ERROR: remote recv: Connection reset by peer

On my client:
I can not use shadowsocks to use google.com and other website

### What is your config in detail (with all sensitive info masked)?

//On my server:

{
    "server_port":8388,
    "local_address": "127.0.0.1",
    "local_port":1080,
    "password":"xxxxxxxx",
    "timeout":300,
    "method":"aes-256-gcm",
    "plugin":"obfs-server",
    "plugin-opts":"obfs=http",
    "fast_open": false
}

//On my client:
{
  "configs": [
    {
      "server": "52.xxx.xxx.163",
      "server_port": 8388,
      "password": "xxxxxxxx",
      "method": "aes-256-gcm",
      "plugin": "obfs-local",
      "plugin_opts": "obfs=http;obfs-host=www.baidu.com",
      "remarks": "",
      "timeout": 5
    }
}

**Comment by fu1crum** [comment]
Double check your server config. Looks like it is missing a "server” property which needs to be the server IP address. Also "local_address" property is not needed/meaningless.

**Comment by madeye** [comment]
Closed due to inactivity.
