### ISSUE TITLE
shadowsocks protocol detectability

### ISSUE THREAD

**Issue by firestorm99** [shadowsocks/shadowsocks-libev#1896]
### What version of shadowsocks-libev are you using?
shadowsocks-libev 3.1.2

### What operating system are you using?
Linux version 3.16.0-4-amd64 (debian-kernel@lists.debian.org) (gcc version 4.8.4 (Debian 4.8.4-1) ) #1 SMP Debian 3.16.51-3 (2017-12-13)
= Debian Jessie

I don't know if this is the right place to ask: I did some online research regarding the security or detectability of shadowsocks and I came accross the results of an audit, a paper of a Chinese university and a tool to detect ss traffic. 
The results of the securtity audit ( https://x41-dsec.de/security/news/2017/12/18/x41-shadow-on-the-wall/ ---> https://github.com/Shadowsocks/Shadowsocks/issues/995 ) seem to have reached the developers, but can we do something about the fingerprinting mentioned in the paper https://www.loli.ren/wp-content/uploads/2017/10/10.1109@IHMSC.2017.132.pdf ?

The tool I was talking about is sssniff https://github.com/madeye/sssniff . Does this still work?

Are connections using the simple-obfs plugin prone to the same detection method or is this a different story (is there a difference between http and tls mode?)?

Thanks for your answers!

**Comment by madeye** [comment]
Here is the issue tracker of shadowsocks-libev.

Given it's a general question, please post your questions here: https://github.com/shadowsocks/shadowsocks-org. As well, you will find all of your questions have been well discussed there.
