### ISSUE TITLE
Something wrong about verbose mode and stderr/stdout

### ISSUE THREAD

**Issue by catscarlet** [shadowsocks/shadowsocks-libev#1897]
### What version of shadowsocks-libev are you using?
3.1.3

### What operating system are you using?
Ubuntu 16.04 64bit

### What did you do?
Built by myself, not installed it from repository.
Start with './ss-server -p ... -k ... -m aes-256-gcm -t 45 -v 2>> /var/log/shadowsocks-libev.log &'

### What did you expect to see?
Got full log in `/var/log/shadowsocks-libev.log`, and can `tail -f /var/log/shadowsocks-libev.log`

### What did you see instead?
The long isn't very real time.

### Actually here is what I did and I want to do:

I used 3.0.8 for a long time, and always use `-v` and `2>>logfile.log` to collect logs. Today I updated it to v3.1.3, and it seems v3.1.3's verbose mode is no longer output to stderr but to stdout.

The  `2>>logfile.log` was no longer working so I changed to  `1>>logfile.log` but the logfile.log is'nt very real time. It only writes a 4096 blocks at one time.  `tail -f` couldn't work well.

I found [this](https://www.turnkeylinux.org/blog/unix-buffering): 
```
By default writes to stdout pass through a 4096 byte buffer, unless stdout happens to be a terminal/tty in which case it is line buffered.
```

So is there a way to help me still using verbose mode and stderr/stdout to collect logs?

**Comment by madeye** [comment]
I don't think this question is related to shadowsocks. As a general Linux usage question, please ask it on stackoverflow instead

**Comment by madeye** [comment]
Closed due to inactivity.
