### ISSUE TITLE
Pre-compiled static Binaries for MacOS

### ISSUE THREAD

**Issue by kooroshh** [shadowsocks/shadowsocks-libev#1898]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What operating system are you using?
MacOS

### What did you expect to see?
Pre-Compiled Binary package

### What is your config in detail (with all sensitive info masked)?

is there any precompiled static binary package available for macos ? 
is there anyway to embedded ShadowSocks in another application (without brew or ... )

**Comment by madeye** [comment]
Closed due to inactivity.
