### ISSUE TITLE
Shadowsocks-libev has been ported to FreeBSD ports system

### ISSUE THREAD

**Issue by xiaoding** [shadowsocks/shadowsocks-libev#19]
# Notes for FreeBSD users

As the title tells, FreeBSD users are able to enjoy free internet surfing via shadowsocks proxy. For installation, just type the following commands:

>  $ su
>  # cd /usr/ports/net/shadowsocks-libev
>  # make install

Then add your configuration into /etc/rc.conf file:

>  # RECOMMENDED
>  shadowsocks_libev_enable="YES"
>  shadowsocks_libev_flags="-c /PATH/TO/CONFIG.JSON"

or you can omit the config.json file, specify arguments directly:

>  shadowsocks_libev_enable="YES"
>  shadowsocks_libev_password="YOUR PASSWORD"
>  shadowsocks_libev_port="1080"
>  shadowsocks_libev_localport="7070"

Start the shadowsocks server:

>  # service shadowsocks_libev start

Enjoy!

**Comment by hazdzz** [comment]
HELP! When I start shadowsocks_libev on my FreeBSD Server, it shows "ERROR: 7:15: Unknown value". What should I do?

**Comment by teacherpan** [comment]
Wonderful!

**Comment by mergenchik** [comment]
how to enable logging or where to find log file?
