### ISSUE TITLE
Some warnings when cross complie shadowsocks-libev for mipsel

### ISSUE THREAD

**Issue by imMMX** [shadowsocks/shadowsocks-libev#1900]
### What version of shadowsocks-libev are you using?
3.1.3

### What operating system are you using?
ubuntu 16.04

### What did you do?
There are some warnings when cross complie shadowsocks-libev for mipsel. Can I get help to fix this issue here? Thank you guys. My [script](https://github.com/imMMX/ubnt-erx-shadowsocks-libev/blob/master/build_ss.sh) 

### What did you see instead?
ss_manager-utils.o: In function `run_as':  
/usr/local/ss/shadowsocks-libev/src/utils.c:142: warning: Using 'initgroups' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
ss_manager-manager.o: In function `main':  
/usr/local/ss/shadowsocks-libev/src/manager.c:1110: warning: Using 'getpwuid' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
ss_manager-utils.o: In function `run_as':  
/usr/local/ss/shadowsocks-libev/src/utils.c:130: warning: Using 'getpwnam_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/local/ss/shadowsocks-libev/src/utils.c:130: warning: Using 'getpwuid_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
ss_manager-netutils.o: In function `get_sockaddr':  
/usr/local/ss/shadowsocks-libev/src/netutils.c:148: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking

**Comment by madeye** [comment]
Closed due to inactivity.
