### ISSUE TITLE
Question about rtt and  timeout

### ISSUE THREAD

**Issue by akalennox** [shadowsocks/shadowsocks-libev#1902]
### What version of shadowsocks-libev are you using?
shadowsocks-libev 3.1.3

### What operating system are you using?
ArchLinux

### What did you do?
host a network proxy for myself

### What did you expect to see?
No error report

### What did you see instead?
ERROR: server recv: Connection reset by peer

### What is your config in detail (with all sensitive info masked)?
{
"server": "my.domain",
"server_port": "8888",
"local_address": "127.0.0.1",
"local_port": 1081,
"password": "mypasswd",
"no_delay": true,
"timeout": 400,
"method": "aes-256-cfb",
"fast_open": false,
"workers": 1
}

### I want to know about that:
if the packet loss when it is transferred from my client to server, the error message would appear in the logs?
I found some issues in this project and knows about that set the timeout to a larger number can reduce the frequency of the error message, so I set my timeout to 400 after I test the ping from my client to my server. And is it useful that I set my timeout to a much larger number? or I should change a method for my connections between my client and server?

There are information about ping from my client to server:
112 packets transmitted, 106 received, 5% packet loss, time 111296ms
rtt min/avg/max/mdev = 282.182/312.518/537.040/48.990 ms

**Comment by madeye** [comment]
It has nothing to do with packet loss. A typical timeout should be larger than 600 second.
