### ISSUE TITLE
rngd -r /dev/urandom Permission denied

### ISSUE THREAD

**Issue by X0xYEb7m** [shadowsocks/shadowsocks-libev#1903]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
3.1.3

### What operating system are you using?
centos. 7 kernel 2.6.32-042stab126.2

### What did you do?
rngd -r /dev/urandom

### What did you expect to see?
unable to adjust write_wakeup_threshold: Permission denied

### What did you see instead?

This system doesn't provide enough entropy to quickly generate high-quality random numbers
Installing the rng-utils/rng-tools or haveged packages may help.
On virtualized Linux environments, also consider using virtio-rng.
The service will not start until enough entropy has been collected.

### What is your config in detail (with all sensitive info masked)?
{
    "server”:”0.0.0.0”,
    "server_port":443,
    "local_address":"127.0.0.1",
    "local_port":1080,
    "password":"password",
    "timeout":300,
    "method":"chacha20-ietf-poly1305",
    "plugin":"obfs-server",
    "plugin_opts":"obfs=tls"
}

**Comment by fu1crum** [comment]
It seems you are using a single kernel OpenVZ/container, thus the write_wakeup is not applicable. Try the virtio-rng package.
