### ISSUE TITLE
ss-redir add remote dns resolve support

### ISSUE THREAD

**Issue by MonwF** [shadowsocks/shadowsocks-libev#1904]
all domains are  resolved to a fixed fake ip. 
ss-server resovles domain again and replaces the fake ip with a correct ip, can it work？most like surge

### What version of shadowsocks-libev are you using?
3.1.3

### What operating system are you using?
lede

### What did you do?
set local dns map google.com to 1.2.3.4. config iptables redirect 1.2.3.4 to ss-redir service.

### What did you expect to see?
can visit google.com in chrome 

### What did you see instead?
error timeout or else

### What is your config in detail (with all sensitive info masked)?
xxx

**Comment by madeye** [comment]
You don't need this, since ss-redir works as a transparent proxy, which takes advantage of Linux kernel to do NAT.

**Comment by MonwF** [comment]
ss-redir must work with ss-tunnel or something else now.
if remote resolve is supported, it can reduce latency without ss-tunnel
