### ISSUE TITLE
gbp:error: Pristine-tar couldn't checkout "shadowsocks-libev_3.1.3+ds.orig.tar.xz"

### ISSUE THREAD

**Issue by moonwater** [shadowsocks/shadowsocks-libev#1907]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
"shadowsocks-libev_3.1.3

### What operating system are you using?
Description:    Ubuntu 17.10
Release:        17.10
Codename:       artful

### What did you do?

git submodule update --init --recursive
mkdir -p ~/build-area/
cp ./scripts/build_deb.sh ~/build-area/
cd ~/build-area
./build_deb.sh

### What did you expect to see?
build without error
and have the latest ss-server version.

### What did you see instead?

Setting up libcorkipset-dev:amd64 (1.1.1+20150311-7) ...
Setting up libmbedtls10:amd64 (2.5.1-1ubuntu1) ...
Setting up libmbedtls-dev:amd64 (2.5.1-1ubuntu1) ...
Setting up shadowsocks-libev-build-deps (3.1.3+ds-1) ...
Processing triggers for libc-bin (2.26-0ubuntu2.1) ...
gbp:error: Pristine-tar couldn't checkout "shadowsocks-libev_3.1.3+ds.orig.tar.xz": fatal: Path 'shadowsocks-libev_3.1.3+ds.orig.tar.xz.delta' does not exist in 'refs/heads/pristine-tar'
pristine-tar: git show refs/heads/pristine-tar:shadowsocks-libev_3.1.3+ds.orig.tar.xz.delta failed
HEAD is now at 22befa6 Prepare to release 3.1.3+ds-1
/home/user1/build-area
dpkg: error: cannot access archive 'shadowsocks-libev_*.deb': No such file or directory
Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Cloning into 'simple-obfs'...
remote: Counting objects: 1215, done.
remote: Compressing objects: 100% (776/776), done.
remote: Total 1215 (delta 525), reused 1085 (delta 407)
Receiving objects: 100% (1215/1215), 1.39 MiB | 758.00 KiB/s, done.
Resolving deltas: 100% (525/525), done.
Use of uninitialized value $fullname in concatenation (.) or string at /usr/bin/equivs-build line 223.
dh_testdir
dh_testroot

### What is your config in detail (with all sensitive info masked)?

standard config generated from current version

**Comment by rogers0** [comment]
@moonwater fixed.
PS. it's not a bug in upstream, so it's better to report it to debian, by bugreport command.

**Comment by moonwater** [comment]
@rogers0 Thanks a lot, it works.
