### ISSUE TITLE
MD API deprecation in mbedtls causing error in ss-libev

### ISSUE THREAD

**Issue by fsgmhoward** [shadowsocks/shadowsocks-libev#1908]
### What version of shadowsocks-libev are you using?
Latest 5b06f83

### What operating system are you using?
Ubuntu Xenial (Ubuntu Trusty also having the same problem)

### What did you do?
Using latest (development branch) version of mbedtls(libmbedcrypto0) and that leads to an error.

### Brief description
Ref: https://github.com/ARMmbed/mbedtls/pull/1294

mbedtls_md5 is set to be deprecated in mbedtls in this pull request. If the machine has installed the libmbedcrypto0 (commit ARMmbed/mbedtls@005239e and the versions after this), ss-libev will not be functional.

```
root@ubuntu:/tmp# ss-local
ss-local: symbol lookup error: ss-local: undefined symbol: mbedtls_md5
```

Although this version of mbedtls has not been released yet, it will be good if a patch is ready for this.

**Comment by madeye** [comment]
Let's wait for the official release. And of course, pull request is always welcome.

**Comment by wongsyrone** [comment]
It seems trivial to implement, have to wait for API finalization.

**Comment by fsgmhoward** [comment]
[The change of API has been released](https://tls.mbed.org/tech-updates/releases/mbedtls-2.7.0-2.1.10-and-1.3.22-released).

However, I tested the latest version of ss-libev(de504c9) built with  ARMmbed/mbedtls@b7f6086 (2.7.0-67), such error didn't come out again. Maybe further tests are required to see whether there are any other problems related to this.

```
root@ubuntu:/# ss-local -c /etc/shadowsocks-libev/config.json -l 1090 -v
 2018-02-26 20:38:57 INFO: initializing ciphers... chacha20-ietf-poly1305
 2018-02-26 20:38:57 INFO: listening at 127.0.0.1:1090
 2018-02-26 20:38:57 INFO: running from root user
 2018-02-26 20:38:59 INFO: connect to www.google.com:443
 2018-02-26 20:39:00 INFO: connect to www.google.co.in:443
 2018-02-26 20:39:01 INFO: connect to ssl.gstatic.com:443
 2018-02-26 20:39:01 INFO: connect to www.gstatic.com:443
 2018-02-26 20:39:01 INFO: connect to capi.grammarly.com:443
 2018-02-26 20:39:02 INFO: connect to mtalk.google.com:5228
^C 2018-02-26 20:39:04 INFO: closed gracefully
```
