### ISSUE TITLE
[Question] don't understand how to compile for armhf (Raspberry Pi 1)

### ISSUE THREAD

**Issue by PavelLJ** [shadowsocks/shadowsocks-libev#1909]
### What version of shadowsocks-libev are you using?
2.5.6 (so old because i have patch for exactly this version)

### What operating system are you using?
Ubuntu 17.10/Raspbian Stretch lite

### What did you do?
[On ubuntu]
*Installed all the dependencies*
./autogen.sh
./configure --host=armhf (tried also arm-linux, arm-linux-gnueabi, but they did some errors, for example "can't find pcre library" while packets, including dev are installed)
dpkg-buildpackage -b -us -uc --target-arch=armhf (fucked up immediantly because of dependencies)
dpkg-buildpackage -b -us -uc --target-arch=arm (still stopping at some moment)
[On raspbian]
./autogen.sh && ./configure && make (doing smth for ages, then stops because of errors in code it can't handle (can't copy full log, something encryption and keyword "evp"-related

### What did you expect to see?
Builded binaries or package

### What did you see instead?
Errors

### What is your config in detail (with all sensitive info masked)?
I don't know what to write here.

P.S I think there is an error because i don't know exact way to cross-compile, so it's more question than bug report or something. Can you please make a little guide about building for armhf, but not on armhf (it's pain). Sorry for not full and "blurred" report, i just can't get things work properly. Thanks!

**Comment by madeye** [comment]
The best place to ask general questions is https://stackoverflow.com/

**Comment by PavelLJ** [comment]
It's logical, but i tried that already, and got nothing more than "ask in GitHub issues". I know how to cross-compile in general, but it doesn't seem to be working with shadowsocks. It's annoying to answer stupid questions, but it will be really helpful if you would hint me about this. Thanks!

**Comment by imMMX** [comment]
shadowsocks-libev depends on multiple libraries. You need cross complie these first.

**Comment by PavelLJ** [comment]
imMMX, " know exact way to cross-compile". But thanks for the answer anyway. All dependencies has been compiled on Raspberry itself, so there is no need to recompile this on PC
