### ISSUE TITLE
Please have a separate configure argument for man pages

### ISSUE THREAD

**Issue by yurivict** [shadowsocks/shadowsocks-libev#1910]
The reason I ask: on FreeBSD, manpages are always installed, but documentation is predicated on DOCS port option. Currently they are disabled together.

**Comment by yurivict** [comment]
Need to control manpages with a separate variable. Currently, --disable-documentation disables manpages.

**Comment by madeye** [comment]
No plan for it.

If this a FreeBSD specific issue, you may open a pull request for it.
