### ISSUE TITLE
使用最新master分支编译的ss导致客户端无法连接，Connection closed by peer

### ISSUE THREAD

**Issue by jiawei-zheng** [shadowsocks/shadowsocks-libev#1912]
### What version of shadowsocks-libev are you using?
[5fa98a](https://github.com/shadowsocks/shadowsocks-libev/commit/5fa98a669312bf7e4271bc125581138551974ddf)

### What operating system are you using?
Android 7.1/Windows 7

### What did you do?
跟以往一样git pull更新代码，然后重新编译后重启ss-server
`/usr/local/bin/ss-server -uv -c /root/ssuser/5293.json -f /var/run/shadowsocks-5293.pid`

### What did you expect to see?
正常连接及正常使用

### What did you see instead?
Android端连接后点击测试显示“Connection closed by peer”，使用回release版正常。Android客户端用的是最新的v4.4.6

### What is your config in detail (with all sensitive info masked)?
```
{
    "server":"0.0.0.0",
    "server_port":5293,
    "local_address":"127.0.0.1",
    "local_port":1080,
    "password":"owen5293",
    "timeout":600,
    "method":"aes-256-gcm",
    "fast_open":true
}
```

**Comment by madeye** [comment]
`"local_address":"127.0.0.1",`

You're binding your server to `127.0.0.1`

**Comment by jiawei-zheng** [comment]
@madeye 原来这样配都是没问题的啊，为啥更新后不行了？？

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks-libev/issues/1911

**Comment by jiawei-zheng** [comment]
@madeye 理论上，配置成127.0.0.1也不应该有问题吧，代表的是本地ip

**Comment by chenhw2** [comment]
@Matrix6677 那是下游脚本的问题
