### ISSUE TITLE
iOS 11 build failure

### ISSUE THREAD

**Issue by albertolalama** [shadowsocks/shadowsocks-libev#1918]
### What version of shadowsocks-libev are you using?
3.1.3

### What operating system are you using?
iOS

### What did you do?
Cross-compile shadowsocks-libev for iOS.

### What did you expect to see?
A successful build. The project built successfully until the release of Xcode 9 (iOS 11). 

### What did you see instead?
```
manager.c:497:9: error: 'system' is unavailable: not available on iOS
    if (system(cmd) == -1) {
        ^
/Applications/Xcode9.2.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk/usr/include/stdlib.h:195:6: note: 'system' has been explicitly marked unavailable here
int      system(const char *) __DARWIN_ALIAS_C(system);
         ^
1 error generated.
```

As noted above, the iOS 11 SDK has deprecated the `system` API, hence the build fails. I'm happy to submit a PR that disables the call for iOS (via Apple's TargetConditionals.h), but wanted to understand what the side effects would be. For reference, this is the [offending line](https://github.com/shadowsocks/shadowsocks-libev/blob/master/src/manager.c#L506).

**Comment by madeye** [comment]
I don't think you can build shadowsocks-libev for iOS which is not supported.

**Comment by albertolalama** [comment]
It is possible - I use ss-local in an iOS application. ss-manager, I believe, would have less of a use case in mobile. That said, would be okay for me to submit a PR that excludes the `system` call in iOS so the rest of the project builds?

**Comment by madeye** [comment]
Keep your change in a fork instead. `ss-local` also needs to call `exec()` to support SIP003 plugin.
