### ISSUE TITLE
能在IOS上使用么？

### ISSUE THREAD

**Issue by shawwokou123** [shadowsocks/shadowsocks-libev#1919]
系统：iOS5.1.1  已 越狱      system:    ios5.1.1【JB】
工具：mobile terminal        tools:        mobile terminal 
问题： 
在已经越狱的ios5.1.1机器上，如何通过mobile terminal 使用  shadowsocks-libev
question:
ios 5.1.1 jailbreaked, how though mobile terminal  to use  shadowsocks-libev on ipad1 ios 5.1.1 jailbreaked,

**Comment by madeye** [comment]
Nope.
