### ISSUE TITLE
Create a ss-manager Systemd Service Permalink

### ISSUE THREAD

**Issue by new1web** [shadowsocks/shadowsocks-libev#1926]
### What version of shadowsocks-libev are you using?
3.1.3

### What operating system are you using?
centos 7 

### What did you do?
I used this command to listen multiple users :
ss-manager -c /etc/shadowsocks-libev/manager.json --manager-address 127.0.0.1:8000 -u
manager.json

### What did you expect to see?
I want to stop or start , but not possible. after running this command I can only stop it by killing pid.
I want to use this for running many users . 

### What is your config in detail (with all sensitive info masked)?
 File: /etc/shadowsocks-libev/manager.json

{
    "server":"212.32.245.42",
    "local_address": "212.32.245.42",
    "local_port":1080,
    "timeout":300,
    "method":"aes-128-cfb",
    "workers": 1,
    "fast_open": false,

        "port_password": {
                "8001": "password1",
                 "8001": "password6",
                 "8001": "password5",
                 "8001": "password4",
        }
}

**Comment by madeye** [comment]
Any systemd related question. please open an issue with downstream instead.
