### ISSUE TITLE
multiple password on same port 

### ISSUE THREAD

**Issue by new1web** [shadowsocks/shadowsocks-libev#1927]
### What version of shadowsocks-libev are you using?
3.1.3

### What operating system are you using?
Centos 7

### What did you expect to see?
I want to know how can I use multiple password and same port ?
because i want run many users I can use one port for each and want to use same port for all. it is possible ?
there is no any way to use standard radius? 

### What is your config in detail (with all sensitive info masked)?
I wish to have something like this : 
{
    "server":"212.32.245.42",
    "local_address": "212.32.245.42",
    "local_port":1080,
    "timeout":300,
    "method":"aes-128-cfb",
    "workers": 1,
    "fast_open": false,

        "port_password": {
                "8022": "password1","password2",
        }
}

**Comment by studentmain** [comment]
Maybe you need do port fowarding with iptables? I'm not sure, you can try forwarding (e.g.) 3389,1521 ... to your current port8022. I never try this method.

**Comment by debiansid** [comment]
libev does not have this feature I believe

**Comment by madeye** [comment]
As @debiansid mentioned, it's not supported.
