### ISSUE TITLE
How to install on SUSE locally?

### ISSUE THREAD

**Issue by tengerye** [shadowsocks/shadowsocks-libev#1931]
I am working on a server of Linux version 3.0.101-108.21-xen (SUSE Linux), and unfortunately, I don't have root access. I have successfully installed Python 2.6, but could not progress any further. It seems I don't have pip command as well. This is my first time to install shadowsocks, is there any easy way for me please?

Thank you in advance.

**Comment by tengerye** [comment]
I managed to install with Anaconda, yet encountered a little problem while running. The full track displays as follows:
`Traceback (most recent call last):
  File "anaconda3/bin/ssserver", line 11, in <module>
    sys.exit(main())
  File "/users/capg/tengqiye/anaconda3/lib/python3.6/site-packages/shadowsocks/server.py", line 68, in main
    tcp_servers.append(tcprelay.TCPRelay(a_config, dns_resolver, False))
  File "/users/capg/tengqiye/anaconda3/lib/python3.6/site-packages/shadowsocks/tcprelay.py", line 582, in __init__
    server_socket.bind(sa)
PermissionError: [Errno 13] Permission denied`

Can anyone help please? Thank you in advance.

**Comment by hosiet** [comment]
ssseever is **not** provided by shadowsocks-libev. It is part of shadowsocks (Python version).

Please open the issue at the corresponding project instead.

**Comment by tengerye** [comment]
Thank you @hosiet . Apologize for my mistake, I am new to shadowsock.
