### ISSUE TITLE
Lots of "SYN_RECV" when do netstat --tcp on server side

### ISSUE THREAD

**Issue by manjuprajna** [shadowsocks/shadowsocks-libev#1932]
### What version of shadowsocks-libev are you using?
shadowsocks-libev 3.13 and commits afterwards on both server and clients side

### What operating system are you using?
server: CentOS 7.4
client: lede 1701

### What did you do?
normal use

### What did you expect to see?
working as usual

### What did you see instead?
since last month, I found that my shadowsocks-libev connection will be blocked by my isp after hours of use, no response at all, but can ping and tcping server (my shadowsocks port is not blocked), but can not open any websites, nslookup to ss-tunnel time out, when I go check my shadowrocket on my iphone, use tcp-latency check method, I see red request time out. so I ssh into my server, use netstat --tcp --numeric |grep my shadowsocks port, see lots of "SYN_RECV",  it seems like my shadowsocks port was blocked, but tcping still gets response.  
so I changed my shadowsocks port, working again, but after some time, blocked again. then I found when I do pppoe redial and changed my wan IP address, even this blocked port can work again.
so it seems that isp did some black magic and interfere tcp 3 step shakehands? or the GFW deployed some black magic equipments on isp data center?
and I noticed that every time when such kind of situation occurs, I check my iphone shadowrocket, always more than one server get problem, like this morning when I had problem connecting to one HK server, then I see red request time out on another two HK servers, but when I did pppoe redial, all server can connect again.

so I guess GFW might already have some way to sniff out shadowsocks and do some "trick" to interfere.
maybe it's not shadowsocks problem, they just interfere and block all suspicious connection.

Happy new year to all!

**Comment by zhao-kun** [comment]
I have the same problem as you. From the server, I see lots of TCP 
 status is `SYNC_RECV`. At first I suspect it's problem of the cloud vendor, but I can connect the server from a Korea server. But in the Wall(in the china), I changed all ISP (China Telecom, China UniCom), It still can't connect the Server.

**Comment by zhao-kun** [comment]
I start my ss-server with `ss-server -s {ip_addr} -p {port_number} -k {password} -m chacha20-ietf-poly1305`

For avoiding  being sniffed, I changed my listening port every day  (leverage crontab task), but this morning, I found my new port doesn't work

**Comment by edenpan** [comment]
I also meet the same problem but after I changed another port it works again. I am wondering why this happened.

**Comment by sunyanwei** [comment]
I also met the same problem, and I haven't addressed it until now.

**Comment by zhao-kun** [comment]
The issue should be related to Chinese GFW. If you don't make traffic camouflage, the GFW will block your port even your IP.  So upgrading to V2Ray maybe another best choice.

This a reference about 科学上网: https://github.com/haoel/haoel.github.io

**Comment by edenpan** [comment]
Thanks, I will try.

**Comment by puppylpg** [comment]
> I also meet the same problem but after I changed another port it works again. I am wondering why this happened.

The same as you. Change to another ss port and it works.

**Comment by piersonpeng** [comment]
I'm changed the port and the encryption method, It‘s worked.
