### ISSUE TITLE
Invalid cipher name: chacha20-ietf-poly1305, use rc4-md5 instead

### ISSUE THREAD

**Issue by raulmd** [shadowsocks/shadowsocks-libev#1933]
### What version of shadowsocks-libev are you using?
3.1.3
### What operating system are you using?
Debian (raspbian 9)
### What did you do?
Run the client on raspbian by calling:
ss-local -s server ip -p server port -k password -m chacha20-ietf-poly1305 -l 1080 -b 127.0.0.1 &

### What did you expect to see?
Not an error

### What did you see instead?
 ERROR: Invalid cipher name: chacha20-ietf-poly1305, use rc4-md5 instead

**Comment by manjuprajna** [comment]
you need to install libsodium 1.0.12 or above

**Comment by raulmd** [comment]
I installed libsodium-1.0.16 but still the cypher is unknown.

**Comment by manjuprajna** [comment]
@raulmd when you run ss-local --help, what do you see?
you need to install libsodium-devel too. then after install libsodium and libsodium-devel then compile ss-local

**Comment by raulmd** [comment]
ss-local --help
@manjuprajna  I only see the following Encrypt methods:

       -m <encrypt_method>        Encrypt method: table, rc4, rc4-md5,
                                  aes-128-cfb, aes-192-cfb, aes-256-cfb,
                                  aes-128-ctr, aes-192-ctr, aes-256-ctr,
                                  bf-cfb, camellia-128-cfb, camellia-192-cfb,
                                  camellia-256-cfb, cast5-cfb, des-cfb,
                                  idea-cfb, rc2-cfb, seed-cfb, salsa20 and
                                  chacha20.
                                  The default cipher is rc4-md5.

**Comment by manjuprajna** [comment]
@raulmd here's mine

ss-local --help

shadowsocks-libev 3.1.3

  maintained by Max Lv <max.c.lv@gmail.com> and Linus Yang <laokongzi@gmail.com>

  usage:

    ss-local

            -m <encrypt_method>        Encrypt method: rc4-md5,
                                  aes-128-gcm, aes-192-gcm, aes-256-gcm,
                                  aes-128-cfb, aes-192-cfb, aes-256-cfb,
                                  aes-128-ctr, aes-192-ctr, aes-256-ctr,
                                  camellia-128-cfb, camellia-192-cfb,
                                  camellia-256-cfb, bf-cfb,
                                  chacha20-ietf-poly1305,
                                  xchacha20-ietf-poly1305,
                                  salsa20, chacha20 and chacha20-ietf.
                                  The default cipher is rc4-md5.

**Comment by raulmd** [comment]
Well, i followed the process to build from source.

`sudo apt-get install --no-install-recommends gettext build-essential autoconf libtool libpcre3-dev asciidoc xmlto libev-dev libc-ares-dev automake libmbedtls-dev libsodium-dev`
Installed LIBSODIUM_VER=1.0.16 and MBEDTLS_VER=2.6.0

However, during `./autogen.sh && ./configure && make` I have an error related to Poly1305

Maybe I am being too clever and should not be using libsodium 1.0.16 but 1.0.13?


ss_local-aead.o: In function `aead_cipher_decrypt':
/home/pi/shadowsocks-libev/src/aead.c:219: undefined reference to `crypto_aead_x                                                 **chacha20poly1305_ietf_decrypt**'
ss_local-aead.o: In function `aead_cipher_encrypt':
/home/pi/shadowsocks-libev/src/aead.c:180: undefined reference to `crypto_aead_x                                                 **chacha20poly1305_ietf_encrypt**'
collect2: error: ld returned 1 exit status
Makefile:677: recipe for target 'ss-local' failed
make[2]: *** [ss-local] Error 1
make[2]: Leaving directory '/home/pi/shadowsocks-libev/src'
Makefile:480: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/pi/shadowsocks-libev'
Makefile:389: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by manjuprajna** [comment]
@raulmd either you install libsodium-devel above 1.0.12 or you manully compile libsodium, then you compile shadowsocks-libev.
you can not install libsodium-devel and compile libsodium at the same time.

**Comment by eromoe** [comment]
Does the python version support this ?
