### ISSUE TITLE
Can not use port below 1024 in service, but can use it in CLI

### ISSUE THREAD

**Issue by fudaguang** [shadowsocks/shadowsocks-libev#1934]
### What version of shadowsocks-libev are you using?
shadowsocks-libev 3.1.3
simple-obfs 0.03
### What operating system are you using?
 Ubuntu 16.04.2 LTS
### What did you do?
install shadowsocks-libev and simple-obfs on my server
### What did you expect to see?
i want use port 443 or 80 to start shadowsocks-libev and simple-obfs in service mode 
### What did you see instead?
it can not start service with port 443 or 80, but it can work in CLI mode.
In service mode, the process UID is "nobody" and in CLI mode, the process UID is root. 
### What is your config in detail (with all sensitive info masked)?
    "server":"123.456.789.012",
    "server_port":443,
    "local_port":1080,
    "password":"123456789",
    "timeout":60,
    "method":"chacha20-ietf-poly1305",
    "plugin":"obfs-server",
    "plugin_opts":"obfs=tls"

###
what i want to know is how can i use the port 443 or 80 at service mode, thanks a lot.

**Comment by manjuprajna** [comment]
to run as a service below port 1024, you should modify systemd service file to run as root.

**Comment by fudaguang** [comment]
Thanks a lot , it have been done!
According to my experiment on the ss and obfs on ubuntu these days, it can be divided into two categories.
First, the ss can automatically run as service mode as user nobody above port 1024, and the /var/run/shadowsocks-libev (/run/shadowsocks-libev) directory can be created by /etc/init.d/shadowsocks-libev. It just need to change the parameters in the file /etc/default/shadowsocks-libev, from "USER=nobody" to "USER=root" and from "GROUP=nogroup" to "GROUP=root", then reboot. The ss and obfs then can run as service automatically below port 1024 at boot as user root。
Second, the ss can NOT automatically run as service mode as user nobody above port 1024, and the /var/run/shadowsocks-libev (/run/shadowsocks-libev) directory can NOT be created by /etc/init.d/shadowsocks-libev (i do not know why. :( ). It need to change the parameters in TWO files /etc/default/shadowsocks-libev AND /lib/systemd/system/shadowsocks-libev.service,  ALSO from "USER=nobody" to "USER=root" and from "GROUP=nogroup" to "GROUP=root", then ADD "service shadowsocks-libev start" to the FILE /etc/rc.local, then reboot. it will work.

**Comment by firestorm99** [comment]
you can also use iptables to get around this: 
iptables -t nat -A PREROUTING -p tcp --dport [portbelow1024] -j REDIRECT --to-port [ss port]
iptables -t nat -A PREROUTING -p udp --dport [portbelow1024] -j REDIRECT --to-port [ss port]
