### ISSUE TITLE
Can't build a statically linked binary file.

### ISSUE THREAD

**Issue by fourstring** [shadowsocks/shadowsocks-libev#1936]
### What version of shadowsocks-libev are you using?
3.1.3

### What operating system are you using?
Ubuntu 16.04(docker baseimage)

### What did you do?
Build shadowsocks-libev and get a statically linked binary file.

### What did you expect to see?
A statically linked binary file.

### What did you see instead?
configure: error: The Sodium crypto library libraries not found.(so does PCRE mbedtls c-ares)

### What is your config in detail (with all sensitive info masked)?
```dockerfile
FROM ubuntu AS build
ARG MBEDTLS_VER=2.4.2
ARG LIBSODIUM_VER=1.0.15
ARG C_ARES_VER=1.13.0
ARG PCRE_VER=8.41
ENV CFLAGS="-static"
ENV LDFLAGS="-static"
RUN apt -y update &&  \
    apt-get -y install --no-install-recommends tree build-essential wget autoconf git libtool automake libssl-dev gawk debhelper dh-systemd init-system-helpers pkg-config asciidoc xmlto apg  zlib1g-dev libev-dev libudns-dev && \
    apt-get -y purge libsodium-dev && \
    cd /usr/local/src && \
   wget --no-check-certificate https://download.libsodium.org/libsodium/releases/libsodium-$LIBSODIUM_VER.tar.gz && \
   tar xzf libsodium-$LIBSODIUM_VER.tar.gz &&  \
   cd libsodium-$LIBSODIUM_VER &&  \
   
   ./configure  --prefix=/usr/local/libsodium &&  \
   make -j2 && make install &&  \
   cp /usr/local/libsodium/include/sodium/* /usr/local/libsodium/include && \
   cd .. && \
    wget --no-check-certificate https://tls.mbed.org/download/mbedtls-$MBEDTLS_VER-gpl.tgz && \
    tar xzf mbedtls-$MBEDTLS_VER-gpl.tgz && \
    cd mbedtls-$MBEDTLS_VER &&  \
    
    make  && \
    make  DESTDIR=/usr/local/mbedtls install  && cd .. && \
    wget --no-check-certificate https://c-ares.haxx.se/download/c-ares-$C_ARES_VER.tar.gz && \
    tar xzf c-ares-$C_ARES_VER.tar.gz && \
    cd c-ares-$C_ARES_VER && \
    ./buildconf && \
    ./configure --prefix=/usr/local/libc-ares && \
    make -j2 && make install && \
    cd .. && \
    wget --no-check-certificate https://ftp.pcre.org/pub/pcre/pcre-$PCRE_VER.tar.gz && \
    tar xzf pcre-$PCRE_VER.tar.gz && \
    cd pcre-$PCRE_VER && \
    ./configure --prefix=/usr/local/libpcre && \
    make && make install && \
    apt -y install ca-certificates && \
    ldconfig && \
    cd .. && \
    git clone https://github.com/shadowsocks/shadowsocks-libev.git && \
    cd shadowsocks-libev && \
    git submodule update --init --recursive && \
    ./autogen.sh && ./configure  --with-sodium=/usr/local/libsodium --with-mbedtls=/usr/local/mbedtls --with-cares=/usr/local/libc-ares --with-pcre=/usr/local/libpcre  && make  && make install
```

I have checked /usr/local/libsodium,like this:
```
/usr/local/libsodium
|--include/
|----sodium/
|--------some files...
|----sodium.h
|--lib/
|----libsodium.a
```

(so does other libraries)

How can I build a statically linked binary file?Thanks a lot.

**Comment by debiansid** [comment]
https://darknode.in/linux/static-pack-apps/

**Comment by fourstring** [comment]
@debiansid Thanks sincerely for your help.But I met a new problem.This time ./configure told me it couldn't find libpcre.
I have read your passage and build libpcre like this:
```bash
wget --no-check-certificate https://ftp.pcre.org/pub/pcre/pcre-$PCRE_VER.tar.gz && \
    tar xzf pcre-$PCRE_VER.tar.gz && \
    cd pcre-$PCRE_VER && \
    ./configure --prefix=/usr  \
        --enable-jit \
        --enable-utf8 \
        --enable-unicode-properties \
        --enable-shared=false && \
     make install
```
And configure shadowsocks:
```bash
./configure --with-pcre=/usr
```

However,it doesn't work.How can I know why the error happended?

```dockerfile
ENV CFLAGS="-static"
ENV LDFLAGS="-static"
```

Thanks again.

**Comment by AnyoeDove** [comment]
@debiansid I tried to build a binary file like https://darknode.in/system/static-pack-apps/ did, but the binary I built can't run in Debian.

**Comment by debiansid** [comment]
Any error ?

**Comment by AnyoeDove** [comment]
No. I made some change in the build script to build c-ares. 
https://gist.github.com/AnyoeDove/6fd08172839bee537021451606d0592f

but form the binary size it doesn't look like a statically linked binary file...
![image](https://user-images.githubusercontent.com/10519576/37516479-37663b16-2949-11e8-856e-9fccf8daf9a2.png)
![image](https://user-images.githubusercontent.com/10519576/37516573-861089d8-2949-11e8-913a-25f16a7875cd.png)

**Comment by debiansid** [comment]
You have to build it on clean system like here.
https://darknode.in/system/static-pack-apps/

**Comment by debiansid** [comment]
```
-rwxr-xr-x    1 root     root       2113120 Mar 16 14:58 ss-tunnel
-rwxr-xr-x    1 root     root       3636568 Mar 16 14:58 ss-server
-rwxr-xr-x    1 root     root       2120664 Mar 16 14:58 ss-redir
-rwxr-xr-x    1 root     root          5498 Mar 16 14:58 ss-nat
-rwxr-xr-x    1 root     root        526312 Mar 16 14:58 ss-manager
-rwxr-xr-x    1 root     root       3536512 Mar 16 14:58 ss-local
```

**Comment by debiansid** [comment]
and you shouldn’t forget to apt install musl on debian, or it will not run.

**Comment by AnyoeDove** [comment]
I read this https://wiki.alpinelinux.org/wiki/Installing_Alpine_Linux_in_a_chroot to install my chroot system so it's clean.
And I didn't install musl on debian so thats why.
emmmm but still the binary size is smaller than yours, I will try to work this out.
Thank you ~

**Comment by AnyoeDove** [comment]
Yeah, I mean, it works in Alpine and Debian, but my binary size are smaller than yours.
