### ISSUE TITLE
Forward accepted connections to HTTP Proxy

### ISSUE THREAD

**Issue by shadowsocks-user** [shadowsocks/shadowsocks-libev#1937]
### What version of shadowsocks-libev are you using?
shadowsocks-libev 2.6.3 with mbed TLS 2.4.2

### What operating system are you using?
Debian 9

I haven't tried anything yet regarding my issue, but I saw: https://github.com/shadowsocks/shadowsocks-libev/issues/1766

I have setup shadowsocks in both client and server. It is running fine. But I want to know if it's possible that in my server I transfer all the accepted connections to HTTP Proxy ? It will be like this:

User -> shadowsocks client proxy -> shadowsocks server -> http server (e.g. squid) in same server as of shadowsocks server.

**Comment by madeye** [comment]
Nope, it's not supported.
