### ISSUE TITLE
start ss-manager on boot

### ISSUE THREAD

**Issue by new1web** [shadowsocks/shadowsocks-libev#1942]
### What operating system are you using?
Centos 6

### What did you do?
3.1.3

Each time I reboot server I have to run this command :

`ss-manager -c /etc/shadowsocks-libev/manager.json --manager-address 127.0.0.1:8000 -u`
How can I start ss-manager on startup?

**Comment by new1web** [comment]
I have tried to run this command by /etc/rc.d/rc.local and crontab but it works only if I insert  manually. why ?

**Comment by gyteng** [comment]
Maybe u can use 'nohup' like this:

```nohup sudo ss-manager -m aes-256-cfb -u --manager-address 0.0.0.0:1234 >> /dev/null 2>&1 &```
