### ISSUE TITLE
IP lookup failure

### ISSUE THREAD

**Issue by HankAviator** [shadowsocks/shadowsocks-libev#1943]
### What version of shadowsocks-libev are you using?
3.1.3

### What operating system are you using?
Ubuntu Bionic Beaver 

### What did you do?
Build shadowsocks-libev on ubuntu BB due to #1861 , all runs well except after a server reboot, ss says it cannot resolve ipv4 / v6 hostnames (i don't need ipv6 tho).

shadowsocks writes these lines to syslog (partially):
```
Feb 24 10:36:59 ubuntu ss-server[978]:  2018-02-24 10:36:59 INFO: failed to lookup v6 address Could not contact DNS servers
Feb 24 10:36:59 ubuntu ss-server[978]:  2018-02-24 10:36:59 INFO: failed to lookup v4 address Could not contact DNS servers
Feb 24 10:36:59 ubuntu ss-server[978]:  2018-02-24 10:36:59 INFO: current server connection: 3
Feb 24 10:36:59 ubuntu ss-server[978]:  2018-02-24 10:36:59 INFO: accept a connection
Feb 24 10:36:59 ubuntu ss-server[978]:  2018-02-24 10:36:59 INFO: connect to mail.google.com:443
Feb 24 10:36:59 ubuntu ss-server[978]:  2018-02-24 10:36:59 INFO: failed to lookup v6 address Could not contact DNS servers
Feb 24 10:36:59 ubuntu ss-server[978]:  2018-02-24 10:36:59 IN 2018-02-24 10:36:59 ERROR: unable to resolve mail.google.com
Feb 24 10:36:59 ubuntu ss-server[978]:  2018-02-24 10:36:59 ERROR: unable to resolve calendar.google.com
Feb 24 10:37:00 ubuntu ss-server[978]:  2018-02-24 10:37:00 ERROR: unable to resolve calendar.google.com
```
and ss client doesn't work (ERR_CONNECTION_CLOSED on browser).

While autostart doesn't resolve addresses, running `service shadowsocks-libev restart` will fix the problem (with user **`root`**).

ss-libev on ubuntu 16.04.3 LTS, ss 3.1.1, no such issue.
### What did you expect to see?
Same behavior (no resolve failure) as previous versions.

### What is your config in detail (with all sensitive info masked)?
` /etc/resolv.conf`:
```
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
# 127.0.0.53 is the systemd-resolved stub resolver.
# run "systemd-resolve --status" to see details about the actual nameservers.

nameserver 127.0.0.53
```
`/etc/default/shadowsocks-libev`: 
...
`DAEMON_ARGS="-uv"`
...

`/etc/shadowsocks-libev/config.json`:
```
{
    "server":"0.0.0.0",
    "server_port":[REDACTED],
    "local_port":1080,
    "password":"[REDACTED]",
    "timeout":60,
    "method":"rc4-md5",
    "fast_open":true
}
```

**Comment by madeye** [comment]
Add `-d 8.8.8.8` to your command line and try again.

**Comment by HankAviator** [comment]
Workaround valid, suspecting `systemd-resolve` may have caused it.
