### ISSUE TITLE
unsafe stripping of port from hostname in http.c (incompatibility SNI sniffing with IPv6)

### ISSUE THREAD

**Issue by starter48** [shadowsocks/shadowsocks-libev#1945]
### What version of shadowsocks-libev are you using?
Latest
### What operating system are you using?
Linux
### What did you do?
I've send the following request to [2001:470:1:18::119]:
`GET /ip/?callback=?&testdomain=test-ipv6.com&testname=test_ipv6 HTTP/1.1\r\nHost: [2001:470:1:18::119]\r\n\r\n`
with `atyp=4` (IPv6)
### What did you expect to see?
**INFO connect to [2001:470:1:18::119]:80**
### What did you see instead?
Pure IPv6 address truncated:
**INFO connect to [2001:470:1:18::80**
### What is your config in detail (with all sensitive info masked)?
No matter. Problem in SNI sniffing (`parse_http_header()` func in **http.c**).
IPv6 address without port has been truncated by the last colon.
[I've described it and proposed a patch here](https://github.com/dlundquist/sniproxy/issues/279)

**Comment by madeye** [comment]
Please open a pull request instead.

**Comment by starter48** [comment]
@dlundquist has fixed it:
https://github.com/dlundquist/sniproxy/blob/master/src/http.c
please update your repo
