### ISSUE TITLE
Possible way to bypass repeated-salt check

### ISSUE THREAD

**Issue by DarienRaymond** [shadowsocks/shadowsocks-libev#1948]
### What version of shadowsocks-libev are you using?
Source code

### What operating system are you using?
N/A

### What did you do?
If I read correctly, it is possible to bypass salt checking with the following case:
1. There are 2 connections that use the same salt.
2. The first connection sends the salt, plus less than 18 bytes. This is enough to pass salt check at [aead.c#L614](https://github.com/shadowsocks/shadowsocks-libev/blob/master/src/aead.c#L614), but not enough to decrypt the first 'len' bytes. Then aead_decrypt returns CRYPTO_NEED_MORE at [aead.c#L636](https://github.com/shadowsocks/shadowsocks-libev/blob/master/src/aead.c#L636).
3. In the meantime, the second connection sends the same data as the first connection, which leads to the same state in the step above.
4. At this stage, both connections bypass repeated salt checking. They can continue to send the rest of the data.

### What did you expect to see?
The second connection get blocked due to repeated salt usage.

### What did you see instead?
It doesn't get blocked.

**Comment by wongsyrone** [comment]
How about adding to bloom filter after received?

**Comment by madeye** [comment]
Yes, it's possible. It's important to check bloom filter again after authentication.
