### ISSUE TITLE
Build shadowsocks-libev v3.1.3 on Raspberry PI success, but run error Illegal instruction

### ISSUE THREAD

**Issue by HenryHo2006** [shadowsocks/shadowsocks-libev#1951]
### What version of shadowsocks-libev are you using?
3.1.3

### What operating system are you using?
raspberrypi 4.1.19+ 

### What did you do?
step by step with readme (section "Other Linux")

### What did you see instead?
run ss-local ss-server ss-redir ss-tunnel, all are error : Illegal instruction

### What is your config in detail (with all sensitive info masked)?
compile on raspberry pi, without cross compilation

**Comment by HenryHo2006** [comment]
install from [stretch-backports](https://backports.debian.org/Instructions/) success.
apt-get -t stretch-backports install shadowsocks-libev

**Comment by mvanaltvorst** [comment]
I have the same problem here. Both the stretch-backports version and the version I built myself don't work on my Raspberry Pi Zero W. It's probably got to do with the fact that the Raspberry Pi Zero is based on ARMv6. Does anyone have experience with this?

**Comment by plutoid** [comment]
> I have the same problem here. Both the stretch-backports version and the version I built myself don't work on my Raspberry Pi Zero W. It's probably got to do with the fact that the Raspberry Pi Zero is based on ARMv6. Does anyone have experience with this?

same issue on old pi with below cpuinfo:
```
root@raspberrypi:/tmp/shadowsocks-libev-3.1.3# cat /proc/cpuinfo
processor       : 0
model name      : ARMv6-compatible processor rev 7 (v6l)
BogoMIPS        : 697.95
Features        : half thumb fastmult vfp edsp java tls
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xb76
CPU revision    : 7

Hardware        : BCM2835
Revision        : 000e
Serial          : 00000000a22963c3
```
