### ISSUE TITLE
Is it useful to add SOCKS4 and HTTP proxy support into ss-local?

### ISSUE THREAD

**Issue by starter48** [shadowsocks/shadowsocks-libev#1953]
I plan to improve **ss-local** by implementing SOCKS4 and _simplified_ HTTP proxy protocol.
I believe it is useful for low-end gateways (such as home routers) to discard the fatty **privoxy** as an HTTP->SOCKS5 translator. And SOCKS4 support is useful for Internet Explorer browser.
I.e. after my improvements **ss-local** could accept from client not only SOCKS5 connections, but also SOCKS4 and HTTP.

**Comment by debiansid** [comment]
Can you consider to make it work behind reverse proxy like Nghttpx?

**Comment by starter48** [comment]
Tell me how to test.
Is it compatible with **privoxy** at least? :)
The alpha version of simple HTTP support is almost ready:
On CONNECT it just establish a connection through SOCKS5.
On other commands (GET, POST, etc) it does the following:
- cut (and ignore) "Proxy-Connection" header;
- check the version of HTTP protocol from request, and if HTTP prior to 1.1 and no explicit "Connection" header then it add "Connection: close" header (for compatibility with HTTP 1.0 default connection style);
- cut hostname and port from request, and thus reduce request to normal HTTP request;
- establish a connection through SOCKS5 and send normalized HTTP request.
It doesn't parse remote response, i.e. it just forward response to client.

**Comment by debiansid** [comment]
ss-[redir/local]—>nghttpx—>ss-server

**Comment by starter48** [comment]
So nghttpx is just a transport for encrypted SS-protocol?
I don't expect any influence. If it can work now then it will continue to work.
How does it relate to privoxy? :)
I thought you plan to connect client to ss-local through nghttpx.
My improvement is a front-end subroutine of **ss-local** to convert HTTP protocol to SOCKS5.
Original ss-local:
[client]->{SOCKS5 protocol}->[ss-local]->{encrypted protocol}->[ss-server]
After my improvement it can work this way also:
[client]->{HTTP protocol}->[my subroutine->{SOCKS5 protocol}->ss-local]->{encrypted protocol}->[ss-server]
Everything after ss-local stay without changes.

**Comment by madeye** [comment]
Thanks for the proposal. But we don't have any plan to support any other local proxy protocol.

Try Privoxy if you need to support more local proxy protocols.
