### ISSUE TITLE
无法从 json 配置中读取 mtu 设置？

### ISSUE THREAD

**Issue by pexcn** [shadowsocks/shadowsocks-libev#1956]
### config
```json
{
    "server":"xx.xx.xx.xx",
    "server_port":11,
    "local_port":1080,
    "password":"xxxxxxxxxx",
    "timeout":300,
    "method":"chacha20-ietf-poly1305",
    "mode":"tcp_and_udp",
    "nofile":65535,
    "dscp":46,
    "mtu":1480
}
```

使用 `ss-local -c config.json` 启动的时候，没有看到 MTU 相关的日志输出。
使用 `ss-local -c config.json --mtu 1480` 启动的时候，可以看到 MTU 的日志 `2018-03-05 14:32:38 INFO: set MTU to 1480`

**Comment by kimw** [comment]
Read the manpage, please.

There's no `mtu` in manpage which means, it's *NOT SUPPORTED*.

**Comment by pexcn** [comment]
不是应该要既支持 json 又支持命令行才显得合理吗？

**Comment by lixingcong** [comment]
ss-local有MTU选项的

**Comment by madeye** [comment]
This option is only for debug, which is planed to remove in the future release.
