### ISSUE TITLE
部分google域名访问不了

### ISSUE THREAD

**Issue by lingo169** [shadowsocks/shadowsocks-libev#1957]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
shadowsocks-libev3.1.3

### What operating system are you using?
centos 7

### What did you do?
部分google域名访问不了，例如 www.google.com.sg

### What did you expect to see?
www.google.com就能跳转到对应的google页面（各个国家）

### What is your config in detail (with all sensitive info masked)?
shadowsocks-libev 配置如下：
{
    "server":"0.0.0.0",
    "server_port":18388,
    "local_port":1080,
    "password":"barfoo!",
    "timeout":60,
    "method":"chacha20-ietf-poly1305"
}

问题如下：
我服务器在新加坡，浏览器：Google Chrome 64.0.3282.186,客户端是shadowsocks-win 4.0.8
服务器：shadowsocks-libev3.1.3

在浏览器中输入查询信息时，直接跳转到www.google.com.sg 且无法访问，但是我访问https://www.google.co.uk/却能查询，而且https://www.facebook.com/,youtube都能访问，请问这是怎么回事？？？

**Comment by madeye** [comment]
Double check your local PACs.

**Comment by asmca** [comment]
shadowsocks-libev-3.1.3-1.fc26.x86_64

same problems

**Comment by asmca** [comment]
w/r,  just downgrade shadowsocks-libev to lower version.

mbedtls-2.5.1-2.fc26.x86_64.rpm               
libsodium-1.0.12-1.fc26.x86_64.rpm            
shadowsocks-libev-3.1.0-1.fc26.x86_64.rpm     


it now works.

**Comment by lingo169** [comment]
我启动服务后，过一个小时（时间不定），就会自动挂了，这是怎么回事？
执行命令
/usr/local/bin/ss-server -c /root/soft/config1.json -u &

**Comment by lingo169** [comment]
我刚刚测试了下，基本上大部分google都不能访问，这个应该不是第三方bug吧，我猜测可能是算法问题，然后给墙干扰，后者墙已经开始对chacha20-ietf-poly1305算法起部分作用了，不知道我的想法是不是正确的？
不能访问的google包括：
http://www.google.fr/
https://www.google.com.sg
http://www.google.se/
http://www.google.com.tw/
http://www.google.co.il/
http://www.google.ch/
http://www.google.com.ar/
等等

**Comment by madeye** [comment]
It's a typical PAC issue, that some domains are not proxied correctly. Try system wide proxy without PAC in your windows client.

**Comment by lingo169** [comment]
我是菜鸟，我按照 @asmca 的方法，减低了ss-libev版本3.1.0,结果还是访问不了新加坡的google(https://www.google.com.sg),我的服务器也是在新加坡，您标签那里标记的是第三方bug(third-party bug)，有没有什么方法能解决我这个问题呢？
求助，求救。

**Comment by pexcn** [comment]
墙干扰 chacha20-ietf-poly1305 了吗？不要听风就是雨啊，我在路由器上用 rc4-md5 这么久没出过问题 (

**Comment by lingo169** [comment]
现在是我的ss-libev 老是不定时挂了，不知道怎么回事？又没有日志可查看

**Comment by lingo169** [comment]
加 -v参数打印出来的日志基本上正常
