### ISSUE TITLE
[Feature Request] Allow set DSCP via command line arguments

### ISSUE THREAD

**Issue by pexcn** [shadowsocks/shadowsocks-libev#1958]
看到在 https://github.com/shadowsocks/shadowsocks-libev/blob/master/src/jconf.c#L273 , 好像已经是可以用 json 配置来设置了，希望可以通过命令行来设置。

**Comment by madeye** [comment]
Send a pull request instead.

**Comment by pexcn** [comment]
还没怎么学过 c 语言…，打算以后再折腾下这个~
