### ISSUE TITLE
相同vps上部署ss和ss-libev，后者会被间歇性断开

### ISSUE THREAD

**Issue by mickeyandkaka** [shadowsocks/shadowsocks-libev#1960]
### What version of shadowsocks-libev are you using?
最新版本

### What operating system are you using?
ubuntu

### What did you do?
ss-libev + kcptun + simple-obfs

### What did you expect to see?
与SS一样稳定不断

在相同GCE上部署，后者会间歇性被断开，看日志似乎请求没有被打倒服务端。是不是ss-libev的流量有什么明显特征呢？

### What did you see instead?
在看pxxnhub, yxxtube 的时候会timeout

### What is your config in detail (with all sensitive info masked)?
ss-libev
ss-server -s 0.0.0.0 -p 6443 -m aes-256-cfb -k whatever --plugin obfs-server --plugin-opts obfs=http
kcptun
./server_linux_amd64 -t 127.0.0.1:6443 -l :myport --mode fast2 --log kcp_server.log

补充一点：ss-libev在搬瓦工也有部署，当不可用的时候，两个libev的ss都不可用，过一段时间后可用。

**Comment by stucash** [comment]
想请教一个题外话, 我正在尝试在DO和搬瓦工上编译ss-libev, 但一直遇到dependency unmet error. 想请问一下, 您在编译的时候没有遇到这样的问题吗? 我在搬瓦工上装的是ubuntu16.04, 遇到了libsodium版本过低的问题, 目前没有办法解决. 万分感谢!

**Comment by pexcn** [comment]
1. 如果装了锐速，关掉试试。
2. 确保你的 ISP 没有屏蔽 UDP.

**Comment by mickeyandkaka** [comment]
@stucash 我好像没遇到。。
@pexcn 1确定没有，是重新安装系统后做的， 2并不清楚，用的北京移动网。我本人也怀疑是不是ISP做了什么手脚，因为每次大概5分钟后又可以访问了。不过好奇的是流量特征和SS一样么？GCE的SS从来没遇到过。

一个特殊的地方是因为装了kcptun， 用ss-libev + kcptun会看大流量视频，而SS因为速度原因从来没看高清过。

**Comment by madeye** [comment]
It's nothing to do with shadowsocks. UDP based protocol like KCP is expected to have problems with firewalls or NAT devices.

**Comment by mickeyandkaka** [comment]
@madeye Thanks.
