### ISSUE TITLE
[已解决]在lede 17.01上，openwrt-shadowsocks 3.1.3透明代理无法访问Google网页。

### ISSUE THREAD

**Issue by wukaisky** [shadowsocks/shadowsocks-libev#1961]
### What version of shadowsocks-libev are you using?
openwrt-shadowsocks 3.1.3

### What operating system are you using?
LEDE 17.01 git-2ae9ebf
libsodium=1.0.11
mbedtls=2.6.0

### What did you do?
我把openwrt-shadowsocks 3.1.3编译进路由器，开透明代理。

### What did you expect to see?
我希望Google全家桶能正常访问。

### What did you see instead?
中国移动宽带。
Google网页无法打开，提示“您的连接不是私密连接”。
libsodium替换为1.0.16,问题依旧。
openwrt-shadowsocks 降级为 3.1.2，能够正常访问Google网页。

### What is your config in detail (with all sensitive info masked)?

服务器配置：

{
    "server":["[::0]","0.0.0.0"],
    "server_port":xxxx,
    "local_address":"127.0.0.1",
    "local_port":1080,
    "password":"xxxxxxxxxx",
    "timeout":600,
    "method":"chacha20-ietf-poly1305"
}

---------------------------------------------------------------------------------------
客户端配置：

config general
	option startup_delay '0'

config transparent_proxy
	option local_port '1234'
	option mtu '1492'
	list main_server 'cfg0a4a8f'
	option udp_relay_server 'same'

config socks5_proxy
	list server 'nil'
	option local_port '1080'
	option mtu '1492'

config port_forward
	list server 'nil'
	option local_port '5300'
	option destination '208.67.222.222:443'
	option mtu '1492'

config servers
	option fast_open '0'
	option no_delay '0'
	option alias 'debian-512mb-jp-01'
	option server 'xx.xx.xx.xx'
	option server_port 'xxxx'
	option password 'xxxxxxxxxx'
	option encrypt_method 'chacha20-ietf-poly1305'
	option timeout '600'

config access_control
	option self_proxy '1'
	option lan_target 'SS_SPEC_WAN_AC'
	list wan_bp_ips '47.90.92.56'
	list wan_bp_ips '117.131.204.40'
	option wan_bp_list '/etc/chnroute.txt'

config lan_hosts
	option enable '1'
	option host '192.168.1.239'
	option type 'b'

config lan_hosts
	option enable '1'
	option host '192.168.1.125'
	option type 'b'

config servers
	option alias 'debian-512m-jp-kcptun'
	option fast_open '0'
	option no_delay '0'
	option server '127.0.0.1'
	option server_port 'xxxx'
	option timeout '600'
	option password 'xxxxxxxxxx'
	option encrypt_method 'chacha20-ietf-poly1305'

config lan_hosts
	option enable '1'
	option host '192.168.1.142'
	option type 'b'

**Comment by madeye** [comment]
It's expected. You should solve DNS poisoning issue first.

**Comment by Biercenter** [comment]
老实用dns-forwarder，稳如狗

**Comment by pexcn** [comment]
加个 chinadns

**Comment by wukaisky** [comment]
谢谢，我试试看。
Thanks!

**Comment by wukaisky** [comment]
我给openwrt-shadowsocks搭配上ChinaDNS后，可以正常访问Google网站了。
openwrt-shadowsocks v3.1.3开始，又要依赖ChinaDNS来防止DNS投毒了。

**Comment by signigelchan** [comment]
我也遇到了同样的问题，按照解答步骤，使用了dns-forwarder及chinadns，问题依然没有被解决，求助！（参考链接：https://github.com/aa65535/openwrt-chinadns/wiki/Use-DNS-Forwarder）

**Comment by frc123** [comment]
dns问题导致的
定位问题可以先手动在网络适配器中设置个静态的8.8.4.4试试，别忘改ipv6或者直接关掉。然后再看看google能不能用。能用的话就定位到了。装了chinadns
