### ISSUE TITLE
openwrt-shadowsocks 3.1.3 透明代理 是否存在BUG？

### ISSUE THREAD

**Issue by osdu** [shadowsocks/shadowsocks-libev#1964]
升级到 3.1.3 后 ss-redir 无法代理，替换为同样配置参数编译的 3.1.2和3.1.1 的二进制 ss-redir 文件后恢复正常。

![qq 20180309131315](https://user-images.githubusercontent.com/2067880/37191603-a6c59fa0-239b-11e8-886c-b713bf3b0d79.png)

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks-libev/issues/1961

**Comment by osdu** [comment]
这个我看过貌似不是这个问题，我是用的 ipsets，什么配置都不修改，用旧版 ss-redir 替换新版就恢复正常了。

域名是由 dnsmasq 查询 8.8.8.8#53 返回

iptables -t nat -A PREROUTING -p tcp -m set --match-set shadowsocks dst -j REDIRECT --to-port 1089
iptables -t nat -A OUTPUT     -p tcp -m set --match-set shadowsocks dst -j REDIRECT --to-port 1089

**Comment by madeye** [comment]
It's expected. You should solve DNS poisoning issue first.

**Comment by osdu** [comment]
ipsets list 中的 ip 没有任何改改，新版就不能代理这个跟 DNS 没关系吧，新版直接用正常的 ip 地址访问也不行啊

**Comment by osdu** [comment]
搞不明白，退回 3.1.2 了。
