### ISSUE TITLE
error while loading shared libraries: libmbedcrypto.so.0

### ISSUE THREAD

**Issue by CovMat** [shadowsocks/shadowsocks-libev#1966]
Dear developer

I am using CentOS 7 x64:
```
$ uname -a
Linux localhost.localdomain 3.10.0-693.17.1.el7.x86_64 #1 SMP Thu Jan 25 20:13:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

I update the shadowsocks-libev to latest version ```shadowsocks-libev-3.1.3-1.el7.centos.x86_64``` from yum

but when I try start ```ss-local```, a error returns:
```
$ ss-local
ss-local: error while loading shared libraries: libmbedcrypto.so.0: cannot open shared object file: No such file or directory
```

It is very strange because I can normally use old version ```ss-local``` before updating.  Could you please check if there is any bug in ```shadowsocks-libev-3.1.3-1.el7.centos.x86_64```?

Many thanks

**Comment by AnyoeDove** [comment]
yum install mbedtls-devel -y

**Comment by CovMat** [comment]
@AnyoeDove 
```
Package mbedtls-devel-2.7.0-1.el7.x86_64 already installed and latest version
Nothing to do
```

I have tried.

**Comment by AnyoeDove** [comment]
Try 
> ldconfig

**Comment by CovMat** [comment]
@AnyoeDove 

still couldn't work

**Comment by AnyoeDove** [comment]
emmmmmmmmmmmmm......
 Try `find /usr/ -name 'libmbedcrypto.so.0'` and post your output here

**Comment by CovMat** [comment]
@AnyoeDove 

return nothing. It seems there is not such file in my system.

**Comment by whour** [comment]
I have the same problem.
`mbedtls  2.7.0-1.el7` has no ` libmbedcrypto.so.0`
`cd /usr/lib64`
```
ls |grep mbed
libmbedcrypto.so.1
libmbedcrypto.so.2.7.0
libmbedtls.so.10
libmbedtls.so.2.7.0
libmbedx509.so.0
libmbedx509.so.2.7.0
```
link this.
`ln -sf libmbedcrypto.so.1 libmbedcrypto.so.0`
Temporary solution.

**Comment by AnyoeDove** [comment]
[mbedtls-devel-2.7.0-1.el7.x86_64](https://centos.pkgs.org/7/epel-x86_64/mbedtls-devel-2.7.0-1.el7.x86_64.rpm.html) dont have libmbedcrypto.so.0 actually... soft link some file might work

**Comment by CovMat** [comment]
@whour @AnyoeDove 
Creating soft link makes it work, thanks.

**Comment by hosiet** [comment]
While soft link might work, you should know that this is **unsafe** and will probably lead to crashing due to ABI incompatibility.

The canonical approach is to consult with ss-libev binary's provider (definitely a third party provider since upstream did not provide such binary on CentOS 7) and ask them why they have built ss-libev against a different libmbedtls (different SONAME).

**Comment by CovMat** [comment]
@hosiet 

Thanks. but is ss-local in epel provided by @madeye (author)? Sorry I am a fresh man and I have no idea with it.

**Comment by hosiet** [comment]
Taking a look at README.md, it is maintained externally by @librehat . You should read the instructions in README.md and report the problem in his repository.

**Comment by manjuprajna** [comment]
it's not a bug.
since the rpm package you install from yum is compiled under mbedtls 2.6.0, while a week ago when you do yum update it will upgrade to mbedtls 2.7.0, different libs name.
so either you keep mbedtls 2.6.0 in your system or you manully compile shadowsocks-libev under mbedtls 2.7.0.

**Comment by atxiu** [comment]
```
cd /usr/lib64/
cp libmbedcrypto.so.1 libmbedcrypto.so.0
```

**Comment by atxiu** [comment]
这样就可以正常工作

**Comment by ihacklog** [comment]
my installed pkg:
```
Arch        : i686
Version     : 3.1.3
Release     : 1.el6
Size        : 3.1 M
Repo        : installed
```

solution:
compile and install 2.7.1 

```
yum install "Development tools"
yum install cmake
wget https://github.com/ARMmbed/mbedtls/archive/mbedtls-2.7.1.tar.gz
tar xvzf mbedtls-2.7.1.tar.gz
cd mbedtls-2.7.1*
mkdir build && cd build
cmake -DENABLE_TESTING=Off -DUSE_SHARED_MBEDTLS_LIBRARY=On ../
make
make install
```
after that , we have installed mbedtls-2.7.1 to /usr/local/lib
and then:
```
ln -sf /usr/local/lib/libmbedcrypto.so.2.7.1  /usr/lib/libmbedcrypto.so.0
```
everything is OK now.

**Comment by PantherJohn** [comment]
Awesome. Note that under x86_64 system exec
`ln -sf /usr/local/lib/libmbedcrypto.so.2.7.1  /usr/lib64/libmbedcrypto.so.0`

**Comment by marktrue** [comment]
yum install mbedtls
ln -sf /usr/lib64/libmbedcrypto.so.2.7.1 /usr/lib64/libmbedcrypto.so.0
OS: Centos 7.4

**Comment by digititus** [comment]
On Centos 7.5:
`
cd /usr/lib64/`
`cp libmbedcrypto.so.2 libmbedcrypto.so.1`

**Comment by kid1412621** [comment]
Fedora:
`ss-local: error while loading shared libraries: libmbedcrypto.so.2: cannot open shared object file: Error 40`

**Comment by khazaddim** [comment]
on Ubuntu 20.04

 cd /usr/lib64/
 cd /usr/lib/x86_64-linux-gnu/
 sudo cp libmbedcrypto.so.3 libmbedcrypto.so.0
 dislocker

seems to be working
