### ISSUE TITLE
It`s not work.

### ISSUE THREAD

**Issue by xclidongbo** [shadowsocks/shadowsocks-libev#1971]
Debian 9.
Install from repository
when I run this code in the terminal:
```
sudo /etc/init.d/shadowsocks-libev status -l
```
some error:

Mar 11 19:11:08 xclidongbo systemd[1]: shadowsocks-libev.service: Main process exited, code=exited, status=255/n/a
Mar 11 19:11:08 xclidongbo systemd[1]: shadowsocks-libev.service: Unit entered failed state.
Mar 11 19:11:08 xclidongbo systemd[1]: shadowsocks-libev.service: Failed with result 'exit-code'.

**Comment by atxiu** [comment]
```
ss-server -c config.json 
```
看看返回

**Comment by xclidongbo** [comment]
@atxiu  not server. just shadowsocks client.

**Comment by atxiu** [comment]
ss-local -c config.json

**Comment by atxiu** [comment]
@xclidongbo ss-local -c config.json

**Comment by hosiet** [comment]
Do *not* directly invoke anything inside `/etc/init.d` on Debian 9 with systemd enabled. Please use systemd service instead.

If you encounter any errors with systemd service, please paste detailed configuration and outputs.
