### ISSUE TITLE
Error relocating /usr/bin/ss-redir: mbedtls_md5: symbol not found

### ISSUE THREAD

**Issue by s7lx** [shadowsocks/shadowsocks-libev#1973]
LEDE 环境，收到了libmbedtls 升级到2.7.0的升级包，安装后提示找不到libmbedcrypto.so.0
在/usr/lib 目录下 将libmbedcrypto.so.0 用libmbedcrypto.so.2.7.0 ln 过去后，发现会报这个错
`Error relocating /usr/bin/ss-redir: mbedtls_md5: symbol not found`
已经在#1966 里看到这个问题了，其方案并不适用于 openwrt/LEDE 。

今天已经遇到好几个了 @aa65535

**Comment by manjuprajna** [comment]
@s7lx 你说的收到了mbedtls升级包是啥意思？是指openwrt-feeds吗？
lede1701官方已经更新了medtls2.7.0，你重新编译一下即可。因为ss编译的时候依赖于mbedtls和libsodium，所以如果你更新了这两个包，就要重新编译ss。不然会因为库文件名字不同而报错。
mbedtls 2.6.0的是libmbedcrypto.so.0，而2.7.0的是libmbedcrypto.so.1。
