### ISSUE TITLE
QUESTION: ss-tunnel port fowarding to remote backends

### ISSUE THREAD

**Issue by PantherJohn** [shadowsocks/shadowsocks-libev#1977]
is it OK to use ‘-L 127.0.0.1’ tunneling traffic to the remote server?
```
ss-tunnel on :80 <—> (REMOTE) ssserver on :<server_port> <—-> (localhost 127.0.0.1) SNIPROXY on :16880(note that I want all the traffic to be encapsulated in localhost interface ONLY) 
```
The configuration that works:
```
ss-tunnel -v -u -c /etc/shadowsocks/shadowsocks.json -b 0.0.0.0 -l 80 -L <server_public_address>:16880 

{
    "server":<server_public_address>,
    "server_port":*****,
    "local_address":"0.0.0.0",
    "local_port":1081,
    "password":"****",
    "timeout":300,
    "method":"rc4-md5",
    "no_delay": false
}
```
```
ss-tunnel -v -u -c /etc/shadowsocks/shadowsocks.json -b 0.0.0.0 -l 80 -L 127.0.0.1:16880 
```
Why does this not work???

**Comment by PantherJohn** [comment]
ha got it 
https://github.com/shadowsocks/shadowsocks/wiki/Block-Connection-to-localhost

> From 2.6.7, localhost is blocked by default. If you don't want it, use --forbidden-ip="". (not this actually; it should be `--forbidden-ip ""` )
> From 2.6.3, you can prevent the server from connecting to some IP like 127.0.0.1.
I think we better off disable this feature -- performance suffers (every connection is strictly checked according to the ACL rule). :(

**Comment by madeye** [comment]
It's an important security feature. By default, 127.0.0.1 is blocked.

**Comment by PantherJohn** [comment]
@madeye What is the implication of enabling 127.0.0.1? im just curious...
