### ISSUE TITLE
经常打开网页出现连接中断，查看server端log里有很多错误

### ISSUE THREAD

**Issue by ted-dev-42** [shadowsocks/shadowsocks-libev#198]
类似下面的
Dec 30 15:18:00 140707-lin-105 /usr/bin/ss-server[15403]: socket: Too many open files
Dec 30 15:18:00 140707-lin-105 /usr/bin/ss-server[15403]: connect error.
Dec 30 15:18:00 140707-lin-105 /usr/bin/ss-server[15403]: accept: Too many open files

请问这个是否有问题？

**Comment by xcjiang** [comment]
按官网的说明，把limit改到了51200，使用了一天后，还是出现了同样的问题。
ulimit -n 返回51200，所以修改应该是生效了。

**Comment by xcjiang** [comment]
出现too many open files的时候，用lsof看了一下
lsof | grep 'ss-server' -c
返回值大概在8000多，比51200少很多啊，为什么会too many open files呢？
ss-server是用root执行的，所以我也过滤了一下root：
lsof | grep 'root' -c
返回值大概在10000左右，也比51200少很多。
彻底搞不懂了。

**Comment by kxmp** [comment]
Increase fs.file-max then increase nofile

**Comment by myliyifei** [comment]
我的系统修改后 软限制还是1024， 但是我看在ss的init已经加上了 ulimit -n ${MAXFD}的语句，我还用设置软限制吗？

#ulimit -Sn
1024

**Comment by xcjiang** [comment]
init脚本里写的是
ulimit -n ${MAXFD}
但ubuntu下面根本没有MAXFD这个变量，所以无效。
修改为直接写数值后问题解决。

**Comment by myliyifei** [comment]
作者在/etc/default/shadowsocks里面定义了

在 2015年5月23日 上午11:07，tedjiang <notifications@github.com>写道：

**Comment by xcjiang** [comment]
这我就不清楚了，反正我改了那里就好了，再没出现过问题。
