### ISSUE TITLE
ss-redir tcp流量透明转发不支持tproxy+mangle打标

### ISSUE THREAD

**Issue by tenwx** [shadowsocks/shadowsocks-libev#1982]
### What version of shadowsocks-libev are you using?
3.1.3

### What operating system are you using?
merlin

### What did you do?
目前ss-redir可以针对udp流量采用tproxy+mangle打标方式进行透明转发，但目前不支持tcp流量走tproxy+mangle方式，只能通过nat。这样就会导致在纯ipv6场景下比较尴尬，因为路由器下面的所有设备都是ipv6公网，所以也就自然不存在nat转发，这时候只能通过tproxy+mangle打标方式处理。我测试了下tcp无法工作在这上面。

### What did you expect to see?
希望tcp流量也能支持tproxy+mangle打标，以支持纯ipv6网络环境

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks-libev/pull/131

**Comment by madeye** [comment]
http://mirrors.deepspace6.net/Linux+IPv6-HOWTO/nat-netfilter6..html

**Comment by madeye** [comment]
Try NAT6 instead.

**Comment by tenwx** [comment]
merlin's kernel version is 2.6 ...

**Comment by manjuprajna** [comment]
@tenwx 请问ss-redir怎样可以udp透明转发？我用下面两条
iptables -t nat -A PREROUTING -p udp -m set --match-set shadowsocks dst -j REDIRECT --to-port 1080
iptables -t nat -A OUTPUT -p udp -m set --match-set shadowsocks dst -j REDIRECT --to-port 1080
发现udp还是不行的。

**Comment by tenwx** [comment]
@manjuprajna 参考README，Transparent proxy那节，nap透明转发不支持udp流量

**Comment by manjuprajna** [comment]
@tenwx 谢谢，但是如果我仅仅只是一个特定的ipset里的ip才进行udp转发呢？

**Comment by tenwx** [comment]
`ip rule add fwmark 0x01/0x01 table 111
ip route add local 0.0.0.0/0 dev lo table 111
iptables -t mangle -A PREROUTING -p udp -m set --match-set gfwlist dst -j TPROXY --on-port 1080 --tproxy-mark 0x01/0x01`

**Comment by manjuprajna** [comment]
@tenwx 非常感谢！

**Comment by manjuprajna** [comment]
@tenwx 我按照您的方法配置如下
ipset -N gfwlist iphash
ip rule add fwmark 0x01/0x01 table 111
ip route add local 0.0.0.0/0 dev lo table 111
iptables -t mangle -A PREROUTING -p udp -m set --match-set gfwlist dst -j TPROXY --on-port 1080 --tproxy-mark 0x01/0x01
iptables -t nat -A PREROUTING -p tcp -m set --match-set gfwlist dst -j REDIRECT --to-port 1080
iptables -t nat -A OUTPUT -p tcp -m set --match-set gfwlist dst -j REDIRECT --to-port 1080

然后用一个nat检测工具测试，先把那个ip添加进ipset，之后测试，之前是显示udp blocked，现在显示Symmetric，
然而我用luci-app-shadowsocks测试是显示PortRestrictedCone，跟不走ss一样，我不知道我漏掉或者哪一步做错了？
请指教！

**Comment by tenwx** [comment]
@manjuprajna 如果是Symmetric态，说明网络已经通了，至于luci-app-shadowsocks我没有用过，表示不好判断原因

**Comment by debiansid** [comment]
我的lede on 703N v1 照抄规则 手机客户端不能翻
