### ISSUE TITLE
can't find user logs

### ISSUE THREAD

**Issue by new1web** [shadowsocks/shadowsocks-libev#1983]
### What version of shadowsocks-libev are you using?
3.1.3

### What operating system are you using?
Centos 6.5

### What did you expect to see?
When each user connect to server, where the logs saved ? At least I want to have the user IP and port and error logs.

the is no such file or directory here :  /var/log/shadowsocks.log 
and there is no logs that related to user connection here :  /var/log/messages

I run ss-manager this way : 
ss-manager -c /etc/shadowsocks-libev/manager.json --manager-address 127.0.0.1:8000 -u

### What is your config in detail (with all sensitive info masked)?
{

        "server":"1.2.3.4",
        "local_address": "1.2.3.4",
        "local_port":1080,
        "timeout":300,
        "method":"aes-128-cfb",
        "workers": 1,
        "fast_open": false,
        "port_password":{

                "850":"850"
        }
}

**Comment by madeye** [comment]
It's expected. Shadowsocks-libev wouldn't log any user connection by default.
