### ISSUE TITLE
LEDE 17.01.4 openwrt-shadowsocks-3.1.3 透明代理ss-redir无法访问Google网页，SOCKS代理ss-local使用正常。

### ISSUE THREAD

**Issue by signigelchan** [shadowsocks/shadowsocks-libev#1986]
### What version of shadowsocks-libev are you using?
**Package:** shadowsocks-libev
**Version:** 3.1.3-2

**Package:** libsodium
**Version:** 1.0.16-1

**Package:** libmbedtls
**Version:** 2.7.0-2

### What operating system are you using?
LEDE Reboot (17.01.4, r3560-79f57e422d)

### What did you do?
正常更新 openwrt-shadowsocks-3.1.2 为 openwrt-shadowsocks-3.1.3。

### What did you expect to see?
能够像  openwrt-shadowsocks-3.1.2 一样正常访问Google网页及其他服务。

### What did you see instead?
**_无法访问此网站
www.google.com.hk 的响应时间过长。_**

卸载当前版本(3.1.3)，重装回上一个版本(3.1.2)，即恢复正常访问。
已根据此 Issue #1961 及[Use DNS Forwarder](https://github.com/aa65535/openwrt-chinadns/wiki/Use-DNS-Forwarder) 配置dns-forwarder和chinadns ，问题依然存在。

### What is your config in detail (with all sensitive info masked)?
**服务器配置:**
{
    "server": "xxx.xxx.xxx.xxx",
    "server_port": xxxx,
    "password": "xxxxxxxxxx",
    "method": "chacha20",
    "local_address": "0.0.0.0",
    "timeout": 120,
    "reuse_port": true
}

**客户端配置:**
config servers
        option alias 'xxxxxx'
        option fast_open '0'
        option server 'xxx.xxx.xxx.xxx'
        option server_port 'xxxx'
        option timeout '120'
        option password 'xxxxxxxxxx'
        option encrypt_method 'chacha20'

config servers
        option fast_open '0'
        option alias 'xxxxxx'
        option server 'xxx.xxx.xxx.xxx'
        option server_port 'xxxx'
        option timeout '120'
        option password 'xxxxxxxxxx'
        option encrypt_method 'chacha20'

config general
        option startup_delay '0'

config transparent_proxy
        option udp_relay_server 'nil'
        option local_port '1098'
        option mtu '1492'
        list main_server 'cfg024a8f'

config socks5_proxy                     
        option local_port '1099'        
        option mtu '1492'               
        list server 'cfg024a8f'         
                                        
config port_forward                     
        list server 'nil'               
        option local_port '5300'        
        option destination '8.8.4.4:53' 
        option mtu '1492'              
                                       
config access_control                  
        option lan_target 'RETURN'     
        option self_proxy '1'          
        option wan_bp_list '/etc/chinadns_chnroute.txt'
                                                       
config lan_hosts                                       
        option enable '1'                              
        option macaddr '50:7B:9D:F4:75:7F'             
        option type 'n'                                
                                                       
config lan_hosts                                       
        option enable '1'                              
        option macaddr '50:7B:9D:A0:A2:B0'             
        option type 'n'

**ChinaDNS配置:**
config chinadns
        option enable '1'
        option bidirectional '0'
        option chnroute '/etc/chinadns_chnroute.txt'
        option port '5327'
        option server '114.114.114.114,127.0.0.1#5323'

**DNS-Forwarder配置:**
config dns-forwarder
        option enable '1'
        option listen_port '5323'
        option dns_servers '8.8.8.8'
        option listen_addr '0.0.0.0'

**dnsmasq配置:**
config dnsmasq
        option domainneeded '1'
        option boguspriv '1'
        option localise_queries '1'
        option rebind_protection '1'
        option rebind_localhost '1'
        option domain 'lan'
        option expandhosts '1'
        option authoritative '1'
        option readethers '1'
        option leasefile '/tmp/dhcp.leases'
        option localservice '1'
        option nonwildcard '0'
        option noresolv '1'
        option nohosts '1'
        option local '127.0.0.1#5327'

config dhcp 'lan'
        option interface 'lan'
        option ignore '1'     
                         
config dhcp 'wan'
        option interface 'wan'
        option ignore '1'     
                         
config odhcpd 'odhcpd'
        option maindhcp '0'
        option leasefile '/tmp/hosts/odhcpd'
        option leasetrigger '/usr/sbin/odhcpd-update'

**Comment by madeye** [comment]
You need to solve DNS poisoning issue first. And I don't think you need ChinaDNS as you already have the dns-forwarder.

Also try

```
option local '208.67.222.222:443'
```

**Comment by signigelchan** [comment]
@madeye 
1. 尝试将option local '127.0.0.1#5327' 修改为 option local '208.67.222.222:443'，尝试失败，仍提示"无法访问此网站 www.google.com.hk 的响应时间过长。"
2. 尝试只使用 DNS-Forwarder ，仍没有达到预期结果。

请问有相关的 solve DNS poisoning 解决方案么，求解决。

**Comment by debiansid** [comment]
你的dns的端口都不一致啊，
```option server '114.114.114.114,127.0.0.1#5323'
```
5323 改成5300

**Comment by signigelchan** [comment]
@debiansid 这个 127.0.0.1#5323 监听的是DNS_Forwarder的端口，5300 监听的是哪个端口？？

**Comment by chenhw2** [comment]
Recommend my repo ```dnsmasq-extra``` + ```ChinaDNS```
https://github.com/chenhw2/openwrt-dnsmasq-extra

**Comment by signigelchan** [comment]
@chenhw2 How to use ?

**Comment by debiansid** [comment]
```
config port_forward
list server 'nil'
option local_port '5300'
option destination '8.8.4.4:53'
option mtu '1492'
```
你自己的配置啊 你似乎对linux不熟悉

**Comment by chenhw2** [comment]
@signigelchan just installed into Urom, it will take place itself.

**Comment by debiansid** [comment]
dns端口必须加密出去才不会被污染 你用ss-tunnel就可以了 dns-forward干啥用的啊

**Comment by signigelchan** [comment]
@debiansid 本人只是普通的使用者，是根据[这篇文章](https://cokebar.info/archives/664)的流程步骤操作的。

**Comment by signigelchan** [comment]
有自己见解或个人在LEDE中已实现新版(3.1.3)正常使用的或已解决像我这样的问题的，欢迎致 [我的邮箱](mailto:signigelchan@163.com)。
另外感谢热心向我解答疑惑的各位！

**Comment by tony1016** [comment]
有这种问题的多数都是DNS问题，实在不会处理DNS，就用中科大的防污染

**Comment by debiansid** [comment]
没有必要装china-dns;
dnsmasq-full+ss-tunnel 可以防止污染。
你没有仔细读https://cokebar.info/archives/664
dnsmasq 把污染了的域名解析指到ss-tunnel去解析。

**Comment by tony1016** [comment]
还是有必要的，否则没办法做到国内CDN最优化

**Comment by signigelchan** [comment]
暂时没找到合适的解决方法，暂时先使用之前版本(openwrt-shadowsocks-libev-3.1.2)。
再次非常感谢各位的解答！
