### ISSUE TITLE
求教mptcp和ss怎么配合使用

### ISSUE THREAD

**Issue by milebye** [shadowsocks/shadowsocks-libev#1987]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
shadowsocks-libev 3.1.3

### What operating system are you using?
debian 9

### What did you do?
new deiban 9 install mptcp shadowsocks-libev

### What did you expect to see?
使用mptcp 配合ss 保持 tcp 长链接不中断

### What did you see instead?
没有看到mptcp实现

### What is your config in detail (with all sensitive info masked)?
mptcp 这方面的资料少，配合ss有内容的我也就找到过2-3篇，现在还搞不懂ss的--mptcp 选项

1. 是否双向都要使用，或是一边使用，如一边就可，是否在客户端这边就行？

2. ss client 的 config.json 到底要怎么写，是一个配置文件中，写不同远程地址，或还是正常写一个，让mptcp自己在配置多wan口后，自由使用不同接口访问同一ip？

在尝试过程中发现2，配置多个远程地址，好像是实现负载均衡。

实验环境是，一个VPS，一个本地Linux  通过openvpn实现双wan口 测试。
双ip config.json 中  一个写vps 公网ip 一个写 vpn 内网ip

求指点迷津

**Comment by pexcn** [comment]
server 和 client 的内核都要支持 mptcp, 而且都要开启 `--mptcp` 才能生效。

**Comment by milebye** [comment]
@pexcn      今天我又实验了一下，在双nat wan口，我只安装了内核，然后配置路由，去打开他们的测试网站下载文件，但任然没有实现mptcp， 是因为我直接apt安装没有安装专门的内核算法的原因吗？ 还是nat这种模式下无法实现，必须要真正的公网ip?  

还有对于我的问题2，ss的配置文件需要特别修改吗？  还是就是一个remote server 就行，如果mptcp 成功，会自动使用备用网关也去跟remote产生连接？
谢谢！

**Comment by pexcn** [comment]
net.mptcp.mptcp_enabled 开启了吗？
https://multipath-tcp.org/pmwiki.php/Users/ConfigureMPTCP

**Comment by debiansid** [comment]
服务器要有多wan 我猜测

**Comment by milebye** [comment]
@pexcn  @debiansid    mptcp 开启了，应该是 不是直接wan口（or 公网Ip）的原因，我通过socks连接到vps(换mptcp内核) 打开mptcp的测试网站，双向之间已用ipv6实现mptcp. 

但我想实现的是多链路与vps之间的mptcp。。  完全没头绪了

**Comment by debiansid** [comment]
vps多买一个公网ipv4或者你有本地v6就测试v4/v6连接ss-server

**Comment by milebye** [comment]
@debiansid  不是  因为某个运营商到ss之间会断，所以我想实现 多线多运营商之间通过mptcp与vps连接，保证不断线，关键是我想实现tcp长链接不能出现中断。

**Comment by debiansid** [comment]
@milebye check ovh/overthebox

**Comment by milebye** [comment]
@debiansid   只有只能一条线，原来是打算租云，用vpn 创建多个wan 来实现的。

**Comment by debiansid** [comment]
overthebox支持多个接入的

**Comment by david9991** [comment]
我基于 WireGuard 现在是配成这个样子的，我的目的是使用多个服务器中转提高稳定性和动态使用最优线路。如果你有多线就简单的多，只要配置所有出口的路由规则，让任意 source 都可以到达目标主机就可以了。
至于 ss 的 --mptcp 在这里起到什么作用，我也没研究过。XD

![untitled](https://user-images.githubusercontent.com/123219/51802359-3747f180-2284-11e9-8927-ff0ca7f45ba2.png)

**Comment by Super-Ivan** [comment]
> @debiansid 不是 因为某个运营商到ss之间会断，所以我想实现 多线多运营商之间通过mptcp与vps连接，保证不断线，关键是我想实现tcp长链接不能出现中断。

请问后来解决了吗，我也有类似需求

**Comment by debiansid** [comment]
https://www.openmptcprouter.com/

**Comment by Super-Ivan** [comment]
> https://www.openmptcprouter.com/ Sent from Mobile
> […](#)
> On Apr 28, 2020, at 17:27, Super-Ivan ***@***.***> wrote: ﻿ @debiansid 不是 因为某个运营商到ss之间会断，所以我想实现 多线多运营商之间通过mptcp与vps连接，保证不断线，关键是我想实现tcp长链接不能出现中断。 请问后来解决了吗，我也有类似需求 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

谢谢！我看下这项目

**Comment by Super-Ivan** [comment]
> https://www.openmptcprouter.com/ Sent from Mobile
> […](#)
> On Apr 28, 2020, at 17:27, Super-Ivan ***@***.***> wrote: ﻿ @debiansid 不是 因为某个运营商到ss之间会断，所以我想实现 多线多运营商之间通过mptcp与vps连接，保证不断线，关键是我想实现tcp长链接不能出现中断。 请问后来解决了吗，我也有类似需求 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

貌似overthbox主要是mptcp在openwrt上的实现，但如果我只是本地Centos系统直接运行ss或v2ray，有无方法呢

**Comment by david9991** [comment]
你本地物理网卡数要与远程网卡数一致才有意义，比如你本地有3家运营商的线，通过3条分别优化的线路连到同一台服务器的3个口上去才行。用 VPN 建多个 veth 是没任何意义，也不会提速，我之前试过。我留下点笔记是关于配路由表的，你可以参考下，应该是在客户端配的。配完可以上 http://amiusingmptcp.de 测试一下。

```
ip rule add from 192.168.73.37 table 1
ip rule add from 192.168.72.37 table 2
ip route add 192.168.73.0/24 dev ens33 scope link table 1
ip route add 192.168.72.0/24 dev ens37 scope link table 2
ip route add default via 192.168.73.1 dev ens33 table 1
ip route add default via 192.168.72.1 dev ens37 table 2
ip route add default scope global nexthop via 192.168.72.1 dev ens37
```

**Comment by Super-Ivan** [comment]
> 你本地物理网卡数要与远程网卡数一致才有意义，比如你本地有3家运营商的线，通过3条分别优化的线路连到同一台服务器的3个口上去才行。用 VPN 建多个 veth 是没任何意义，也不会提速，我之前试过。我留下点笔记是关于配路由表的，你可以参考下，应该是在客户端配的。配完可以上 http://amiusingmptcp.de 测试一下。
> 
> ```
> ip rule add from 192.168.73.37 table 1
> ip rule add from 192.168.72.37 table 2
> ip route add 192.168.73.0/24 dev ens33 scope link table 1
> ip route add 192.168.72.0/24 dev ens37 scope link table 2
> ip route add default via 192.168.73.1 dev ens33 table 1
> ip route add default via 192.168.72.1 dev ens37 table 2
> ip route add default scope global nexthop via 192.168.72.1 dev ens37
> ```

另一种情况，本地连接到多个作为代理服务器的vps节点，这些节点再分别连至目标服务器，这种有可能实现吗？楼主要实现的，应该就是多条代理线路同时负载，tcp长连接切成多个子连接再本地排序重组，报障长连接不断

**Comment by david9991** [comment]
我当时用的 wireguard 可以的。

**Comment by david9991** [comment]
不过还不如用 haproxy 做负载均衡不是更方便。为啥一定要用 mptcp。

**Comment by Super-Ivan** [comment]
> 不过还不如用 haproxy 做负载均衡不是更方便。为啥一定要用 mptcp。

不知我对haproxy的理解和使用是不是不太对，它实现的负载均衡应该是一条in的tcp连接对应一条out的连接，出现故障的时候再自动切换out出口。对于一条tcp长连接没法拆分成多条out来同时负载对吗，我比较想实现后者这种模式

**Comment by david9991** [comment]
一条长链接如果里面是多个 HTTP 请求 haproxy 是可以做7层负载均衡的，4层肯定是不行的。话说我还真不知道 ss 可以 tcp 长连接不中断，按道理 ss 应该是可以负载均衡的……
wireguard 肯定是好用的，我以前用过，你可以试试。就是套的套数有点多，不知道能否达到你想要的效果。

**Comment by Super-Ivan** [comment]
> 一条长链接如果里面是多个 HTTP 请求 haproxy 是可以做7层负载均衡的，4层肯定是不行的。话说我还真不知道 ss 可以 tcp 长连接不中断，按道理 ss 应该是可以负载均衡的……
> wireguard 肯定是好用的，我以前用过，你可以试试。就是套的套数有点多，不知道能否达到你想要的效

> 一条长链接如果里面是多个 HTTP 请求 haproxy 是可以做7层负载均衡的，4层肯定是不行的。话说我还真不知道 ss 可以 tcp 长连接不中断，按道理 ss 应该是可以负载均衡的……
> wireguard 肯定是好用的，我以前用过，你可以试试。就是套的套数有点多，不知道能否达到你想要的效果。

好嘞，那我看下wireguard，套多一层也无所谓。谢谢大佬指点~

**Comment by xiaoxinmm** [comment]
我前来观看怎样实现MPTCP结果发现大佬们说话我一句也看不懂
