### ISSUE TITLE
Shadowsocks libev client does NOT support TFO???

### ISSUE THREAD

**Issue by PantherJohn** [shadowsocks/shadowsocks-libev#1988]
### What version of shadowsocks-libev are you using?
3.1.0 

### What operating system are you using?
CentOS 7 x86_64 (Client & Server)

### What did you do?
Server side (Shadowsocks: ssserver):
`grep '^TcpExt:' /proc/net/netstat | cut -d ' ' -f 87-92  | column -t`
Client side (ss-tunnel)

### What did you expect to see?
successful outbound TFO connections on the server side

### What did you see instead?
```
TCPFastOpenPassiveFail  TCPFastOpenListenOverflow  TCPFastOpenCookieReqd  TCPFastOpenBlackhole  TCPSpuriousRtxHostQueues  BusyPollRxPackets
0                       0                          0                      0                     7                         0
```

### What is your config in detail (with all sensitive info masked)?

TFO enabled in ssserver’s config file.
ss-tunnel simply doesn’t seem to have this option 🤣 enabled tcp_fast_open = 3  in sysctl.conf by default.

**Comment by madeye** [comment]
As you mentioned, `ss-tunnel` doesn't support TFO.

Ref: https://github.com/shadowsocks/shadowsocks-libev/blob/master/doc/ss-tunnel.asciidoc

**Comment by PantherJohn** [comment]
Wondering if ss-redir supports this feature. Why not then, I s confused.

**Comment by PantherJohn** [comment]
The speed and low latency is in high demand.... that s the problem

**Comment by madeye** [comment]
Both `ss-local` and `ss-redir` support TFO. Please read the document first.

**Comment by PantherJohn** [comment]
Will it be ok if I send a pull request on this?
Just pass `TCP_FASTOPEN` to `setsockopt()`
Since ss-tunnel is commonly used to proxy DNS, TFO might be necessary to reduce latency. But I’m using it to secure SNIPROXY connections

**Comment by PantherJohn** [comment]
Hah no need of that at all
```
tcp_fastopen - INTEGER
0x400/0x800: Enable Fast Open on all listeners regardless of the
	   TCP_FASTOPEN socket option. The two different flags designate two
	   different ways of setting max_qlen without the TCP_FASTOPEN socket
```

**Comment by PantherJohn** [comment]
Thanks anyway
