### ISSUE TITLE
Google Jigsaw's product "Outline" used code from shadowsocks-libev but used an incompatible license

### ISSUE THREAD

**Issue by PeterCxy** [shadowsocks/shadowsocks-libev#1991]
Dear contributors of shadowsocks-libev,

Recently a team at Google published a new "VPN" tool called "Outline" (https://getoutline.org/en/home). As it turned out, it was only another GUI wrapper around shadowsocks, and specifically, shadowsocks-libev. The client side of their software (https://github.com/Jigsaw-Code/outline-client) directly included source code from shadowsocks-libev and other related projects, some of which licensed under GNU General Public License version 3. However, the `outline-client` was licensed under Apache 2.0, which is not a compatible license with GPLv3.

Since the source code are directly included to the repository, I'm afraid that this could be a copyright offence. However, I haven't looked into whether it could actually be a derivative work of the Shadowsocks project. I am writing here for attention of you, the Shadowsocks contributors, who have done great work on fighting censorship, in case that further action should be taken on this issue.

Regards.

**Comment by BroncoTc** [comment]
Interesting.

**Comment by linusyang** [comment]
I am no expert in License. But I doubt if this project is ever worth trying. For example, why still use [Cygwin](https://github.com/Jigsaw-Code/outline-client/blob/master/third_party/shadowsocks-libev/windows_action.sh) to build the project, as we have a much better, highly efficient (IOCP-based), plugin-enabled [full Windows port](https://github.com/shadowsocks/shadowsocks-libev#windows-mingw)?

**Comment by greenbambooaaron** [comment]
Hopefully it means that "Jigsaw" will work to improve the code and contribute back to the community...

**Comment by madeye** [comment]
Generally, I'm happy to see more forks from our project. I described the detailed reason in an old post: https://maxlv.net/open-source-and-forking/

As long as Outline runs shadowsocks-libev in a separate process, I don't think there is any serious violation of GPL. However, their current code structure of their project doesn't follow GPL well.

Hope we'll see more direct contributions from them in the future.

**Comment by xiuluo** [comment]
Hope it's not the second ssr

**Comment by anthonywong** [comment]
Apache 2.0 is **compatible** with GPL v3, see https://www.gnu.org/licenses/license-list.en.html#apache2.

**Comment by xiuluo** [comment]
@anthonywong But GPL v3 is not compatible with  Apache 2.0，so you can't fork this project then change license to Apache 2.0.

**Comment by anthonywong** [comment]
@PeterCxy @xiuluo Right, both of you are correct. Looks like Outline does not fork and change the license, but includes shadowsocks-libev and runs it as a separate process (https://github.com/Jigsaw-Code/outline-client/blob/master/cordova-plugin-outline/android/java/org/outline/shadowsocks/Shadowsocks.java#L40. Not saying this is okay, but just wants to point out how Outline works with shadowsocks-libev is debatable.

**Comment by RedL0tus** [comment]
@anthonywong 
Outline‘s maintainer says they are contacting their legal counsel to verify that they are complying or not. See https://github.com/Jigsaw-Code/outline-client/issues/14#issuecomment-375728834

**Comment by xnoreq** [comment]
@linusyang 
>we have a much better, highly efficient (IOCP-based), plugin-enabled full Windows port? 

Do you mean the code that was merged into the forked libev and reverted again last week?
I don't know the reasons for that but libev's paradigm is not really compatible with IOCP ... but libev is needed for Linux with its [messy and broken](https://idea.popcount.org/2017-02-20-epoll-is-fundamentally-broken-12/) polling and event mechanisms.

**Comment by linusyang** [comment]
@xnoreq We recently re-add MinGW support (w/ TCP Fast Open). See #1962 #1965.

We use [wepoll](https://github.com/piscisaureus/wepoll) to provide epoll-like backend for libev on Windows. The patched libev doesn't go upstream yet and is in the customized [`mingw` branch](https://github.com/shadowsocks/libev/tree/mingw), not the master branch (which was a mistake when merging the wepoll patches).

Please refer to the latest [readme document](https://github.com/shadowsocks/shadowsocks-libev#windows-mingw) on building the MinGW port.

**Comment by Per0x** [comment]
Is there currently an advantage to using Outline compared to shadowsocks-libev ?

**Comment by studentmain** [comment]
@Per0x Server side or client side? They're optimized for different scenario.

**Comment by rogers0** [comment]
I'm regular shadowsocks(-libev) user.
I'm wondering whether we can use shadowsocks-libev on server side, and use outline as client side.

If it's feasible, could anyone kindly share the detailed steps? Thank you!

**Comment by studentmain** [comment]
@rogers0 You need generate access key from ss-libev config by yourself.

http://shadowsocks.org/en/spec/SIP002-URI-Scheme.html

**Comment by rogers0** [comment]
@studentmain Thanks so much!
I think we need to add a script to generate the access key automatically, in shadowsocks-libev package.

Any volunteer to do the work? :-P

**Comment by studentmain** [comment]
@rogers0 Maybe also QRCode. Maybe I'll write one, but probably in C...

**Comment by studentmain** [comment]
@Per0x 

Outline Client:
- Use ss-libev
- Pros:
  - Easy to use (copy url and click connect)
  - Full VPN on Windows
- Cons:
  - No plugin
  - Can only configure via ss url
  - Only full VPN mode, no pac mode
  - Server should support UDP.

Outline Server:
- Use outline-ss-server (modified ss-go2)
- Pros:
  - Multi key on one port
  - Built-in monitoring
  - Auto update
  - Easy to deploy
- Cons:
  - You need Outline Manager, which require GUI
  - No plugin support too.
  - Require Docker, sometimes too heavy.

IMO, Outline is optimized for bussiness scenario, their target user is not IT professional, just like their website said. Shadowsocks is designed for personal use (when it born, there is only one user, that's why ss haven't "user name").

**Comment by Per0x** [comment]
@studentmain Thank you !

**Comment by fortuna** [comment]
@studentmain nice comparison!

A few things I'd like to clarify:

* The Outline Client no longer requires the server to support UDP. It will work even if the network blocks non-DNS UDP traffic. The downside is that you won't be able to proxy UDP traffic. DNS falls back to TCP.
* The Outline Server does not require a UI. You can manage it using the [server management REST API](https://github.com/Jigsaw-Code/outline-server/tree/master/src/shadowbox#access-keys-management-api)
* If you don't want to run Docker, you can run [outline-ss-server](https://github.com/Jigsaw-Code/outline-ss-server) directly, which is based on a configuration file ([example](https://github.com/Jigsaw-Code/outline-ss-server/blob/master/config_example.yml)). You will lose the automatic secret generation when creating keys, but that may work for you.

**Comment by jhoneybee** [comment]
> 我不是许可证专家。但我怀疑这个项目是否值得尝试。例如，为什么仍然使用[Cygwin](https://github.com/Jigsaw-Code/outline-client/blob/master/third_party/shadowsocks-libev/windows_action.sh)来构建项目，因为我们有一个更好，更高效（基于IOCP），插件启用的[完整Windows端口](https://github.com/shadowsocks/shadowsocks-libev#windows-mingw)？为什么包含[Cygwin DLL二进制文件](https://github.com/Jigsaw-Code/outline-client/tree/master/third_party/cygwin)而不包含其他预先构建的第三方应用程序？为什么不使用Git子模块但直接复制源代码？这更像是由一群非专业开发人员创建的项目，而不是基于Google的公司。

KIP products ?

**Comment by jhoneybee** [comment]
> I am no expert in License. But I doubt if this project is ever worth trying. For example, why still use [Cygwin](https://github.com/Jigsaw-Code/outline-client/blob/master/third_party/shadowsocks-libev/windows_action.sh) to build the project, as we have a much better, highly efficient (IOCP-based), plugin-enabled [full Windows port](https://github.com/shadowsocks/shadowsocks-libev#windows-mingw)? Why contain the [Cygwin dll binaries](https://github.com/Jigsaw-Code/outline-client/tree/master/third_party/cygwin) but not other pre-built third party apps? Why not use Git submodule but directly copy the source code? This is more like a project created by a group of unprofessional developers but not a Google-based company.

KIP products ?
