### ISSUE TITLE
 Failed to connect to anonscm.debian.org port 443

### ISSUE THREAD

**Issue by imess** [shadowsocks/shadowsocks-libev#2002]
Is the server down ? It complained about 'Connection refused' for almost a whole day. What's going on?

**Comment by rogers0** [comment]
@imess I guess you're trying to use build_deb.sh.
Yes, alioth/anonscm has been migrated to salsa (gitlab instance):
- https://salsa.debian.org/bridges-team/shadowsocks-libev.git

So the script need to be updated, the new git repo address is https://salsa.debian.org/bridges-team/shadowsocks-libev.git

**Comment by imess** [comment]
Never mind, it's working now. Thanks for clarification anyway.
