### ISSUE TITLE
能否直接提供shadowsocks-libev的binary?

### ISSUE THREAD

**Issue by llpub** [shadowsocks/shadowsocks-libev#2004]
shadowsocks-libev的依赖挺多的, 安装了不少包才编译成功(debian 8死活不成功, 因为apt没有mbedtls的包, 实在懒得编译mbedtls了). 
在这种情况下用debian backports安装shadowsocks-libev的话, 所装的依赖过多, 极有可能搞坏系统, 能否麻烦直接提供shadowsocks-libev的 binary for debian/ubuntu/centos/fedora?
以上均为个人所见, 不当之处还请指出.

**Comment by hosiet** [comment]
The official Debian backports repository ( `jessie-backports-sloppy` ) is especially meant for Debian 8 users. If you encounter any problems with dependency with jessie-bpo-sl, please consider it a bug and report the problem to package maintainers.

**Comment by chenhw2** [comment]
I build a docker to make statically linked linux-amd64 binary.
https://hub.docker.com/r/chenhw2/libev-build/
