### ISSUE TITLE
The SS is not working after the update today.

### ISSUE THREAD

**Issue by liu-lulin** [shadowsocks/shadowsocks-libev#2006]
The SS is not working after the update today.

___Bandwagon OpenVZ VPS Debian9

~# systemctl status shadowsocks-libev.service 
● shadowsocks-libev.service - Shadowsocks-libev Default Server Serv
ice
Loaded: loaded (/lib/systemd/system/shadowsocks-libev.service; enabled; vendor preset: enabled)
Active: failed (Result: exit-code) since Fri 2018-03-30 15:12:5
3 CST; 23min ago
Docs: man:shadowsocks-libev(8)
Process: 214 ExecStart=/usr/bin/ss-server -c $CONFFILE $DAEMON_ARGS
(code=exited, status=237/KEYRING)
Main PID: 214 (code=exited, status=237/KEYRING)

Mar 30 15:12:53 localhost systemd[1]: Started Shadowsocks-libev Default Server Service.
Mar 30 15:12:53 localhost systemd[214]: shadowsocks-l
ibev.service: Failed to change ownership of session keyring: Permission denied
Mar 30 15:12:53 localhost systemd[214]: shadowsocks-l
ibev.service: Failed to set up kernel keyring: Permission denied
Mar 30 15:12:53 localhost systemd[214]: shadowsocks-l
ibev.service: Failed at step KEYRING spawning /usr/bin/ss-server: Permission denied
Mar 30 15:12:53 localhost systemd[1]: shadowsocks-lib
ev.service: Main process exited, code=exited, status=237/KEYRING
Mar 30 15:12:53 localhost systemd[1]: shadowsocks-lib
ev.service: Failed with result 'exit-code'.

**Comment by liu-lulin** [comment]
VPS will be automatically updated every day.




:~#   cat /etc/cron.d/update

SHELL=/bin/bash

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

0 4 * * *  root  apt update &&apt full-upgrade -y

30 4 * * *  root  apt -t stretch-backports upgrade shadowsocks-libev -y &&cp -f /root/config.json /etc/shadowsocks-libev/config.json

0 5 * * *  root systemctl reboot

**Comment by vipzrx** [comment]
debian 9 使用新的版本 3.1.3 无法连接 
在windows电脑上确认过帐号可用

**Comment by rogers0** [comment]
what version do you use?
I cannot reproduce your issue under debian stretch-backports.
I guess it's a config issue. Please post your config as suggested by the issue template.
