### ISSUE TITLE
some question of ss-redir

### ISSUE THREAD

**Issue by angusding** [shadowsocks/shadowsocks-libev#201]
I found some questons when enable redirect to some sites by ss-redir:
v1.6.2 & v1.6.3
youtube.com can't play videos online(but no problem v1.4.6).
ifanqiang.com can't open sometimes at v1.4.7 & v1.6.x.
but no problem found to visit sites above by ss-local mode.

**Comment by madeye** [comment]
Make sure your DNS works correctly.
