### ISSUE TITLE
云盾安骑士报告所有只运行ss-libev服务的VPS存在“疑似病毒外连行为”

### ISSUE THREAD

**Issue by totemofwolf** [shadowsocks/shadowsocks-libev#2012]
### What version of shadowsocks-libev are you using?
3.1.3

### What operating system are you using?
centos6-x86_64

### What did you do?

云盾安骑士报告所有只运行ss-libev服务的VPS存在“疑似病毒外连行为”：

-- | -- | -- | -- | -- | -- | --
云盾态势感知系统检测到您的服务器：10.140.0.2（${instanceName}）出现了提醒安全事件：可疑病毒外连行为 ，建议您立即登录云盾-态势感知控制台查看详情和处理。

10.140.0.2 | 可疑病毒外连行为 | 恶意进程（云查杀） | 中危 | 待处理 | 2018-04-03 15:16:05 | 一键修复\|忽略本次\|确认事件\|标记为误报\|查看
-- | -- | -- | -- | -- | -- | --

检测到ECS上存在恶意病毒，正在尝试主动外连，可能是在尝试连接中控CnC服务器或者对外发起攻击

### What did you expect to see?
NULL

### What did you see instead?
NULL

### What is your config in detail (with all sensitive info masked)?
{
    "server":"0.0.0.0",
    "server_port":25,
    "password":"",
    "timeout":600,
    "method":"chacha20-ietf-poly1305",
    "fast-open":true,
    "reuse-port":true,
    "number":10240,
    "interface":"eth0",
    "no-delay":true,
    "user":"nobody"
}

**Comment by rogers0** [comment]
https://lists.debian.org/debian-project/2018/03/msg00007.html

**Comment by totemofwolf** [comment]
“病毒行为”详情：
-- | -- | -- | -- | -- | -- | --
矿池IP： 8.8.8.8 矿池端口： 53 进程路径： /usr/bin/ss-server 进程id： 26967 命令行参数： /usr/bin/ss-server -u -c /etc/shadowsocks-libev/config.json -f /var/run/shadowsocks-server/pid 外连URL： 8.8.8.8:53 事件说明： 检测到ECS上存在恶意病毒，正在尝试主动外连，可能是在尝试连接中控CnC服务器或者对外发起攻击 解决方案： 建议立即KILL该恶意进程以及删除对应磁盘文件
-- | -- | -- | -- | -- | -- | --

**Comment by studentmain** [comment]
预期行为，忽略警告即可

wonglend <notifications@github.com> 于 2018年4月5日周四 08:58写道：

**Comment by madeye** [comment]
Obviously, it's not a problem of shadowsocks.
