### ISSUE TITLE
怎么还不支持websocket啊

### ISSUE THREAD

**Issue by xuiv01** [shadowsocks/shadowsocks-libev#2013]
websocket是现在最常用的协议，有个websockify只能把socket转为websocket，不能在本地侦听socket并连接远端websocket，现在只有一个shadowsocks-heroku可以用，但是nodejs写的，路由器没有fpu，无法运行。

**Comment by Biercenter** [comment]
如果支持websocket的话是不是就可以套CDN了？那倒是很期待。然后一墙的话又要换v2ray,一般的路由器跑起来很吃力

**Comment by madeye** [comment]
No plan for this.
