### ISSUE TITLE
ss-tunnel failed to start with config file

### ISSUE THREAD

**Issue by zhboner** [shadowsocks/shadowsocks-libev#2018]
### What version of shadowsocks-libev are you using?
3.1.3

### What operating system are you using?
centos

### What did you do?
`ss-tunnel -c  config.json` output the usage help instead starting the service.
`ss-tunnel -p xxx -s xxx ....` works as expected

### What did you expect to see?
ss-tunnel -c works as well as explicit arguments

### What did you see instead?
ss-tunnel can't load config file but work well with explicit arguments.

**Comment by madeye** [comment]
Since you're talking about configs, you have to submit your configs here.

**Comment by zhboner** [comment]
In my case, if I start ss-tunnel with the following command:
`
ss-tunnel -s "server_ip" -p server_port -l 1080 -m "chacha20-ietf-poly1305" -k "password" -L "dest_ip:dest_port"
`
Everything is fine. tunnel started and listening the port.
However, if I use the config file:
`
"server": "server_ip",
"server_port": server_port,
"local_port":1080,
"addr:port":"dest_ip:dest_port",
"password":"password",
"method":"chacha20-ietf-poly1305"
`
Start the tunnel with command `ss-tunnel -c config.json`, usage information will be print and app stopped.
Can you help me inspect this?
Thank you.

**Comment by zhboner** [comment]
I figured out the issues, thank you.

**Comment by icymind** [comment]
> I figured out the issues, thank you.

how dit you fix the issue?

**Comment by blue007ms** [comment]
i think you just need to use ss-local instead of ss-tunnel
