### ISSUE TITLE
ss-local cant send packet to server

### ISSUE THREAD

**Issue by zx3860795** [shadowsocks/shadowsocks-libev#2021]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
shadowsocks-libev 2.6.3 with mbed TLS 2.4.2

### What operating system are you using?
Linux raspberrypi 4.9.80-v7+ #1098 SMP Fri Mar 9 19:11:42 GMT 2018 armv7l GNU/Linux

### What did you do?
{
    "server": "xxx.xxx.xx.101",
    "server_port": 443,
    "local_address": "192.168.2.8",
    "local_port": 1080,
    "password": "xxx",
    "timeout": 60,
    "method": "aes-256-cfb",
    "fast_open": false,
    "workers": 100
}

### What is your config in detail (with all sensitive info masked)?
i use "curl -x http://192.168.2.8:1080 www.google.com", but dont have packet sent to server,i use "tcpdump -i eth0  host  xxx.xxx.xxx.xxx &", and "netstat -ap |grep -n "443""  ,have nothing,
log ：
 root@raspberrypi:/home/pi#  2018-04-15 12:40:23 INFO: initializing ciphers... aes-256-cfb
 2018-04-15 12:40:23 INFO: tcp port reuse enabled
 2018-04-15 12:40:23 INFO: listening at 192.168.2.8:1080
 2018-04-15 12:40:23 INFO: running from root user

**Comment by sophauer** [comment]
export http_proxy="http://yourip:1080/"
export https_proxy="http://yourip:1080/"

**Comment by lcdtyph** [comment]
I think the curl command should be ```curl -x socks5h://192.168.2.8:1080 www.google.com```.
Here socks5h means perform hostname query through the socks5 proxy.

**Comment by zx3860795** [comment]
ss-local‘s local port only support sock5 proxy？

**Comment by zx3860795** [comment]
ss-local‘s local port only support sock5 proxy？

**Comment by thg303** [comment]
I end up using proxychains

**Comment by PantherJohn** [comment]
@thg303 nah. Simply use
```
export ALL_PROXY=socks5h://<socks5_server_address>:<socks5_port>
```
