### ISSUE TITLE
thanks! this is a green hands'question!

### ISSUE THREAD

**Issue by BenfenYU** [shadowsocks/shadowsocks-libev#2028]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
3.1.3

### What operating system are you using?
ubuntu 16.04

### What did you do?
student

### What did you expect to see?
i am a new one and i want to  run shadowsocks-libev on my ubuntu

### What did you see instead?
![image](https://user-images.githubusercontent.com/33017944/39186140-174cabb8-47fc-11e8-8450-a777d759234c.png)
you can see the png.

### What is your config in detail (with all sensitive info masked)?
except server、port and password，anything is default.

**Comment by imess** [comment]
Make sure the config file path is correct if you intend to use the default service file.  You can confirm the default config path using 'cat /etc/default/shadowsocks-libev' . If things still go wrong, post the whole log after running "journalctl -f -u shadowsocks-libev> someOutPutfile"

**Comment by BenfenYU** [comment]
ok，i will try ，thanks for your help～～
