### ISSUE TITLE
udp relay not work with kcptun

### ISSUE THREAD

**Issue by feilongfl** [shadowsocks/shadowsocks-libev#2029]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
shadowsocks-libev 3.1.3

#### client
raspbian
```
pi@routerpi ~> uname -a
Linux routerpi 4.14.34-v7+ #1110 SMP Mon Apr 16 15:18:51 BST 2018 armv7l GNU/Linux
```
#### server
kvm vps in L.A.
debian 9
```
root@la ~# uname -a
Linux la.feilong.fl 4.9.0-4-amd64 #1 SMP Debian 4.9.65-3+deb9u1 (2017-12-23) x86_64 GNU/Linux
```
### What did you do?
I setup shadowsocks-libev and kcptun with the document written in [here](https://github.com/shadowsocks/shadowsocks-libev#shadowsocks-over-kcp).  

[https://i.imgur.com/1oUhZ0m.jpg](https://i.imgur.com/1oUhZ0m.jpg)

but udp relay is not work,then I found that -U is not avilible in ss-local.
```
 [-U]                       enable UDP relay and disable TCP relay,
                              not available in local mode
```

finally I use `socat` to listen the port which kcptun listen,it works.

**Comment by imess** [comment]
It's expected. kcptun can only tunnel tcp traffic.

**Comment by feilongfl** [comment]
I know kcptun only listen tcp port.what I want say is that setup like the document say can't proxy udp.

**Comment by imess** [comment]
Of course it can't. According to the example codes above, the udp traffic from ss-local is forwarded directly to ss-server, not through kcpun. If you inspect the third line closely you will find out.

**Comment by feilongfl** [comment]
I mean that the third line not work at all.

**Comment by imess** [comment]
Yeh, I noticed. Maybe an deprecated manner. It's unusual to use ss-local in this way.

**Comment by feilongfl** [comment]
So I think he should modify it to be like this.

···
server_linux_amd64 -l :21 -t 127.0.0.1:443 --crypt none --mtu 1200 --nocomp --mode normal --dscp 46 &
ss-server -s 0.0.0.0 -p 443 -k passwd -m chacha20 -u
···

···
client_linux_amd64 -l 127.0.0.1:1090 -r <server_ip>:21 --crypt none --mtu 1200 --nocomp --mode normal --dscp 46 &
socat UDP4-LISTEN:1090,reuseaddr,fork UDP4:<server_ip>:443 &
ss-local -s 127.0.0.1 -p 1090 -k passwd -m chacha20 -l 1080 -b 0.0.0.0
···
