### ISSUE TITLE
High cpu load

### ISSUE THREAD

**Issue by xnoreq** [shadowsocks/shadowsocks-libev#2031]
### What version of shadowsocks-libev are you using?
v3.1.3 or latest master, doesn't make a difference

### What operating system are you using?
Arch Linux 4.15.15

### What did you do?
Using shadowsocks-windows, and firefox configured to use that as a socks 5 proxy (+ resolve dns through proxy).
ss-server is run inside an Arch Linux VM on the same machine.

Now, if I open/refresh a couple of tabs in firefox then ss-server CPU usage goes to 100%. This does not always happen, but when it happens then firefox has problems loading pages.

The CPU usage drops to normal after a couple of seconds and then firefox can load pages normally again.

### What did you expect to see?
ss-server CPU load normally is about 0.5% to 2% max.
Firefox keeps loading pages quickly.

### What did you see instead?
ss-server using 100% CPU, firefox stops loading pages.

### What is your config in detail (with all sensitive info masked)?
timeout: 60
method: rc4-md5
nameserver: 127.0.0.1
fast_open: true
reuse_port: false
mtu: 1400

One more thing, I've run strace on ss-server. Whenever the CPU load goes to 100% I see a lot of these lines:

```
epoll_wait(3, [{EPOLLOUT, {u32=53, u64=17179869237}}], 64, 1) = 1
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=2335, ...}) = 0
write(2, "\33[01;35m 2018-04-28 18:05:44 ERR"..., 80) = 80
close(32)                               = 0
epoll_wait(3, [{EPOLLOUT, {u32=53, u64=17179869237}}], 64, 1561) = 1
epoll_wait(3, [{EPOLLOUT, {u32=53, u64=17179869237}}], 64, 1561) = 1
epoll_wait(3, [{EPOLLOUT, {u32=53, u64=17179869237}}], 64, 1561) = 1
epoll_wait(3, [{EPOLLOUT, {u32=53, u64=17179869237}}], 64, 1560) = 1
epoll_wait(3, [{EPOLLOUT, {u32=53, u64=17179869237}}], 64, 1560) = 1
epoll_wait(3, [{EPOLLOUT, {u32=53, u64=17179869237}}], 64, 1560) = 1
epoll_wait(3, [{EPOLLOUT, {u32=53, u64=17179869237}}], 64, 1560) = 1
epoll_wait(3, [{EPOLLOUT, {u32=53, u64=17179869237}}], 64, 1560) = 1
epoll_wait(3, [{EPOLLOUT, {u32=53, u64=17179869237}}], 64, 1560) = 1
epoll_wait(3, [{EPOLLOUT, {u32=53, u64=17179869237}}], 64, 1560) = 1
epoll_wait(3, [{EPOLLOUT, {u32=53, u64=17179869237}}], 64, 1559) = 1
epoll_wait(3, [{EPOLLOUT, {u32=53, u64=17179869237}}], 64, 1559) = 1
epoll_wait(3, [{EPOLLOUT, {u32=53, u64=17179869237}}], 64, 1559) = 1
epoll_wait(3, [{EPOLLOUT, {u32=53, u64=17179869237}}], 64, 1559) = 1
epoll_wait(3, [{EPOLLOUT, {u32=53, u64=17179869237}}], 64, 1559) = 1
epoll_wait(3, [{EPOLLOUT, {u32=53, u64=17179869237}}], 64, 1559) = 1
epoll_wait(3, [{EPOLLOUT, {u32=53, u64=17179869237}}], 64, 1559) = 1
epoll_wait(3, [{EPOLLOUT, {u32=53, u64=17179869237}}], 64, 1559) = 1
epoll_wait(3, [{EPOLLOUT, {u32=53, u64=17179869237}}], 64, 1559) = 1
epoll_wait(3, [{EPOLLOUT, {u32=53, u64=17179869237}}], 64, 1559) = 1
epoll_wait(3, [{EPOLLOUT, {u32=53, u64=17179869237}}], 64, 1559) = 1
epoll_wait(3, [{EPOLLOUT, {u32=53, u64=17179869237}}], 64, 1558) = 1
epoll_wait(3, [{EPOLLOUT, {u32=53, u64=17179869237}}], 64, 1558) = 1
epoll_wait(3, [{EPOLLOUT, {u32=53, u64=17179869237}}], 64, 1558) = 1
epoll_wait(3, [{EPOLLOUT, {u32=53, u64=17179869237}}], 64, 1558) = 1
epoll_wait(3, [{EPOLLOUT, {u32=53, u64=17179869237}}], 64, 1558) = 1
epoll_wait(3, [{EPOLLOUT, {u32=53, u64=17179869237}}], 64, 1558) = 1
epoll_wait(3, [{EPOLLOUT, {u32=53, u64=17179869237}}], 64, 1558) = 1
epoll_wait(3, [{EPOLLOUT, {u32=53, u64=17179869237}}], 64, 1558) = 1
epoll_wait(3, [{EPOLLOUT, {u32=53, u64=17179869237}}], 64, 1558) = 1
epoll_wait(3, [{EPOLLOUT, {u32=53, u64=17179869237}}], 64, 1558) = 1
...
epoll_wait(3, [{EPOLLOUT, {u32=53, u64=17179869237}}], 64, 2) = 1
epoll_wait(3, [{EPOLLOUT, {u32=53, u64=17179869237}}], 64, 1) = 1
epoll_wait(3, [{EPOLLOUT, {u32=53, u64=17179869237}}], 64, 1) = 1
epoll_wait(3, [{EPOLLOUT, {u32=53, u64=17179869237}}], 64, 1) = 1
epoll_wait(3, [{EPOLLOUT, {u32=53, u64=17179869237}}], 64, 1) = 1
epoll_wait(3, [{EPOLLOUT, {u32=53, u64=17179869237}}], 64, 1) = 1
epoll_wait(3, [{EPOLLOUT, {u32=53, u64=17179869237}}], 64, 1) = 1
epoll_wait(3, [{EPOLLOUT, {u32=53, u64=17179869237}}], 64, 1) = 1
epoll_wait(3, [{EPOLLOUT, {u32=53, u64=17179869237}}], 64, 1) = 1
epoll_wait(3, [{EPOLLOUT, {u32=53, u64=17179869237}}], 64, 1) = 1
epoll_wait(3, [{EPOLLOUT, {u32=53, u64=17179869237}}], 64, 1) = 1
epoll_wait(3, [{EPOLLOUT, {u32=53, u64=17179869237}}], 64, 1) = 1
epoll_wait(3, [{EPOLLOUT, {u32=53, u64=17179869237}}], 64, 1) = 1
epoll_wait(3, [{EPOLLOUT, {u32=53, u64=17179869237}}], 64, 1) = 1
epoll_wait(3, [{EPOLLOUT, {u32=53, u64=17179869237}}], 64, 1) = 1
epoll_wait(3, [{EPOLLOUT, {u32=53, u64=17179869237}}], 64, 1) = 1
epoll_wait(3, [{EPOLLOUT, {u32=53, u64=17179869237}}], 64, 1) = 1
epoll_wait(3, [{EPOLLOUT, {u32=53, u64=17179869237}}], 64, 1) = 1
epoll_wait(3, [{EPOLLOUT, {u32=53, u64=17179869237}}], 64, 1) = 1
epoll_wait(3, [{EPOLLOUT, {u32=53, u64=17179869237}}], 64, 1) = 1
epoll_wait(3, [{EPOLLOUT, {u32=53, u64=17179869237}}], 64, 1) = 1
epoll_wait(3, [{EPOLLOUT, {u32=53, u64=17179869237}}], 64, 1) = 1
epoll_wait(3, [{EPOLLOUT, {u32=53, u64=17179869237}}], 64, 1) = 1
epoll_wait(3, [{EPOLLOUT, {u32=53, u64=17179869237}}], 64, 1) = 1
epoll_wait(3, [{EPOLLOUT, {u32=53, u64=17179869237}}], 64, 1) = 1
epoll_wait(3, [{EPOLLOUT, {u32=53, u64=17179869237}}], 64, 1) = 1
epoll_wait(3, [{EPOLLOUT, {u32=53, u64=17179869237}}], 64, 1) = 1
epoll_wait(3, [{EPOLLOUT, {u32=53, u64=17179869237}}], 64, 1) = 1
epoll_wait(3, [{EPOLLOUT, {u32=53, u64=17179869237}}], 64, 1) = 1
```

And ss-server outputs every couple of seconds:
`ERROR: unable to resolve www.google-analytics.com`
or some other domain.

The used nameserver is dnsmasq running inside the same VM.

**Comment by madeye** [comment]
It looks an issue of dnsmasq. Try some other name servers like 8.8.8.8.

**Comment by xnoreq** [comment]
It has nothing to do with dnsmasq. Dnsmasq just forwards to 8.8.8.8. (I've also tested without dnsmasq, same problem.)

My suspicion is that when using VPN, the provider redirects to their own DNS servers which fail for some domains. And indeed, tcpdump shows for some domains:
`8.8.8.8.53 > myip.port: [udp sum ok] 62960 ServFail q: A? somedomain.com.`

Even so, shadowsocks-server's service should not in any way be negatively impacted by that.

This could even be considered a security problem, because it could be used in a DoS attack.

**Comment by madeye** [comment]
Try c61736e

**Comment by xnoreq** [comment]
Still goes to 100% cpu load and tabs that are loading in firefox fail slowly one after the other.
c-ares version is 1.13.

Btw, the cpu load goes down again after a while after closing firefox (or after all pages have loaded/failed I guess). It looks like ss-server is busy-waiting for some (dns?) result.

**Comment by madeye** [comment]
Add -v to your server command line and post the detailed log here.

**Comment by madeye** [comment]
I cannot reproduce your issue locally with same library and setup. It should be related to your environment or configurations.

I suggest to try:

1. Downgrade your Linux kernel
2. Disable TCP fast open
3. Other local DNS resolver.

**Comment by xnoreq** [comment]
[log](https://github.com/shadowsocks/shadowsocks-libev/files/1977087/ss2.log)
100% cpu load from about 22:57:11 to 22:57:40.
TCP fast open is disabled. (That's not the problem.)
No local DNS resolver is used. (Again, dnsmasq is not the problem.)

**Comment by madeye** [comment]
1. Try a invalid DNS like 4.5.6.7 to see if CPU is always 100%.
2. Try build and run shdowsocks-libev with https://github.com/c-ares/c-ares/releases/tag/cares-1_14_0
3. Post your resolv.conf here.

**Comment by xnoreq** [comment]
Tried invalid DNS. Works as expected: CPU load stays low and loading the site just fails in firefox.
Log:
```
 2018-05-06 12:53:56 INFO: accept a connection
 2018-05-06 12:53:56 INFO: connect to domain.com:443
 2018-05-06 12:54:02 INFO: failed to lookup v4 address Timeout while contacting DNS servers
 2018-05-06 12:54:04 INFO: failed to lookup v6 address Timeout while contacting DNS servers
 2018-05-06 12:54:04 ERROR: unable to resolve domain.com
 2018-05-06 12:54:04 INFO: current server connection: 0
```

resolv.conf is irrelevant, because I've explicitly specified the DNS server that ss-server should use.
But here it is anyway:
```
domain lan
nameserver <ip>
```
Where <ip> is any of the previously used IPs.

**Comment by xnoreq** [comment]
CPU load also goes to 100% with no nameserver in server.json and just `nameserver 8.8.8.8` in resolv.conf.

**Comment by xnoreq** [comment]
Updated c-ares to 1.14.0, CPU usage still jumps to 100%.

**Comment by xnoreq** [comment]
Can't you tell me how to debug it to find out what is causing this tight loop (in libev?).

**Comment by xnoreq** [comment]
Here's a link to a stackoverflow question with a similar issue:
https://stackoverflow.com/questions/41019277/100-cpu-usage-with-libev

**Comment by xnoreq** [comment]
Yes, the problem is in ev_io_set(... EV_WRITE).
Without this and `if (write) ev_feed_event(default_loop, &ctx->io, EV_WRITE)` CPU load stays low.

**Comment by xnoreq** [comment]
Yes, the problem is in `resolv_sock_state_cb`.

After a bit of research I stumbled upon this in libev documentation: 

> As long as your watcher is active (has been started but not stopped) you must not touch the values stored in it. Most specifically you must never reinitialise it or call its ev_TYPE_set macro.

In case `io_active` and  `ctx->io.fd == s` you don't `io_ev_stop` before doing `ev_io_set` again. I think this is the root cause of the bug.
I can write a patch to fix this if you want.

**Comment by madeye** [comment]
Good catch! Could you try 8d3ce8b? Thanks.

**Comment by xnoreq** [comment]
Yes, the CPU load is fixed.
The timeouts still aren't, but I've created a pull request that fixes this as well.

**Comment by wongsyrone** [comment]
> To only process possible timeout conditions without a socket event occurring, one may pass NULL as the values for both read_fds and write_fds for ares_process, or ARES_SOCKET_BAD for both read_fd and write_fd for ares_process_fd(3).

**Comment by xnoreq** [comment]
>A more elegant way is to avoid ares_timeout(), utilize socket state change callbacks instead.

Those are not mutually exclusive, and we already do the latter.

>A reusable resolve context collection prevents malloc/free

My pull request is more efficient and also has no extra malloc/frees.

>The code in this repo forgets to keep processing fds

No, it doesn't. It does timeout handling in `resolv_timeout_cb`.

>I never have the CPU load and timeout issue.

The code before 8d3ce8b clearly had a bug which I've hit regularly.

**Comment by xnoreq** [comment]
I've also improved the timeout handling, as suggested in the c-ares source code ([ares_timeout.c#L33](https://github.com/c-ares/c-ares/blob/a5b2e99207fd12d1e9d0413f4a6cdc8d0d9bdda3/ares_timeout.c#L33)) plus being smarter about ev timer usage:
https://github.com/xnoreq/shadowsocks-libev/commit/14b6261b403aa4db53badbba126def0d9f510a42

**Comment by xnoreq** [comment]
Thanks for the merge. It really works well now. Low CPU usage and no more timeouts.
