### ISSUE TITLE
Add the support to use system-wide libev, libsodium

### ISSUE THREAD

**Issue by JiajunW** [shadowsocks/shadowsocks-libev#204]
It is acceptable to bundle the required libs with the program itself. However it is better to provide an option to link the executable with the system-wide libs.

Gentoo has the convention to not bundling dependencies [1]. There are also some efforts to use the system libs on Archlinux user repo [2]. The packager hacked some files to get it work, but not compiling with clang.

[1] http://wiki.gentoo.org/wiki/Why_not_bundle_dependencies
[2] https://aur.archlinux.org/packages/sh/shadowsocks-libev/PKGBUILD

**Comment by madeye** [comment]
No plan for this.
