### ISSUE TITLE
Sharing proxy for lan clients

### ISSUE THREAD

**Issue by Erhesar** [shadowsocks/shadowsocks-libev#2042]
Hello!

I'm interesting in launch ss-client on device like raspberry pi or something like that for sharing proxy to my lan network. Windows gui client have a option "allow clients from lan", and I can use this pc (and his ip) for configuring proxy for all devices in my network.  This way is more simple than installing client on every device. Besides, its not energy-effectively, and I want try to realize this feature on Debian/Ubuntu on (as I said) raspberry pi or something. There is any option for this? Or maybe someone can give me some info where I can read about it?

**Comment by Erhesar** [comment]
I never used iptables for redirect, only for drop on my vps…
If it is not so hard can you show couple examples, please?
Thank you.

**Comment by studentmain** [comment]
https://gist.github.com/wen-long/8644243

You may want look at this. ss-redir transparent proxy config. IP addresses in this article seems too old, so use iptables geoip module instead.

Set it on your router, you even needn't change proxy config on your device.

**Comment by Erhesar** [comment]
It is look like using ss for any upcoming traffic, this is what i'm exactly do no want.
I chose model of using rbpi as lan proxy server because i want to use normal way to all traffic except what i manually set to use (like browsers or some another software where i can add proxy in configuration)

**Comment by xnoreq** [comment]
Just run ss-local on your Pi in the LAN.  What's the problem?

**Comment by xnoreq** [comment]
Why?!
The `-b <local_address>` to ss-local parameter lets you specify where to bind to. By default its 127.0.0.1 (loopback). 
Simply set it to the right IP of your LAN interface or for example 0.0.0.0 to listen on all interfaces.

Have you even taken a look into the manual?

**Comment by Erhesar** [comment]
lol! 
It was not worked with real local ip address, but it is works with 0.0.0.0...
And now i ask myself why...
Thank you so much.

**Comment by golosoff** [comment]
Hi @Erhesar can you show your config?
Already 10 days, I can't adjust this.
Thx in advance

**Comment by golosoff** [comment]
@Erhesar 

{
    "server":"my_white_ip",
    "server_port":8388,
    "local_address":"0.0.0.0",
    "local_port":1080,
    "password":"my_password",
    "timeout":60,
    "method":"aes-256-cfb",
}
if i try connect from local network, I receive "The proxy server is refusing connections" but from outside when i connect to my "white IP" all perfect

**Comment by Zloi78** [comment]
> 
> 
> @Erhesar
> 
> {
> "server":"my_white_ip",
> "server_port":8388,
> "local_address":"0.0.0.0",
> "local_port":1080,
> "password":"my_password",
> "timeout":60,
> "method":"aes-256-cfb",
> }
> if i try connect from local network, I receive "The proxy server is refusing connections" but from outside when i connect to my "white IP" all perfect

Add this on your device with ss-local:
iptables -A INPUT -s 192.168.1.0/24 -m state --state NEW -p tcp --dport 1080 -j ACCEPT

**Comment by lokiiart** [comment]
I'm facing the same problem, and I've set the "local_address" to "0.0.0.0", my iptables is off by default. and I used a macbook to share the socks, everything works fine. but now, I use the archlinux to share, it doesn't work. someone help, please.
