### ISSUE TITLE
ss-tunnel segfault after random time

### ISSUE THREAD

**Issue by dimzon** [shadowsocks/shadowsocks-libev#2043]
### What version of shadowsocks-libev are you using?

3.1.3 (ubuntu18.04 official repo)

### What operating system are you using?
me@nb:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04 LTS
Release:	18.04
Codename:	bionic
me@nb:~$ uname -a
Linux nb 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:15:38 UTC 2018 i686 i686 i686 GNU/Linux

### What did you do?
I'm running ss-tunnel to provide encrypted tunnel between Privoxy running at VPS and my notebook. For some reasons I prefer such way (ss-tunnel->ss-server->privoxy) instead just (ss-local->ss-server).

### What did you see instead?
sometimes it segfaults:
May  5 17:23:15 nb kernel: ss-tunnel[25981]: segfault at b90bf71c ip b7dd5aac sp bfc584a0 error 4 in libev.so.4.0.0[b7dd2000+d000]

sometimes it tryes allocate 2GB(!) memory:
May  5 17:12:29 nb ss-tunnel[25908]: (libev) cannot allocate 2147483632 bytes, aborting.

### What is your config in detail (with all sensitive info masked)?
/usr/bin/ss-tunnel -c /etc/shadowsocks-libev/config.json -v -s xx.xx.xx.xxx -p 6666 -l 8118 -L 127.0.0.1:8118 -f /var/run/cl-shadowsocks-libev.pid

me@nb:~$ cat /etc/shadowsocks-libev/config.json 
{
    "server":"0.0.0.0",
    "server_port":8989,
    "local_address":"127.0.0.1",
    "local_port":1080,
    "password":"yyyyyyyyyyyy",
    "timeout":600,
    "method":"aes-256-cfb"
}

**Comment by madeye** [comment]
Please try to run it with valgrind and post the output here.

**Comment by madeye** [comment]
BTW, how many concurrent connections in your setup?

**Comment by madeye** [comment]
Also try this commit 204037b100d7ea8341f062790793538c48ecb8ae

**Comment by madeye** [comment]
I think it'd be fixed now.

**Comment by dimzon** [comment]
seems like fixed, uptime=6 days without faults
