### ISSUE TITLE
openwrt-shadowsocks  ss-redir can't run xchacha20-ietf-poly1305

### ISSUE THREAD

**Issue by wukaisky** [shadowsocks/shadowsocks-libev#2044]
### What version of shadowsocks-libev are you using?
openwrt-shadowsocks v3.1.3-4

### What operating system are you using?
LEDE Reboot 17.01-SNAPSHOT r3881-999bb66b20
libsodium 1.0.14

### What did you do?
xchacha20-ietf-poly1305

### What did you expect to see?
initializing ciphers xchacha20-ietf-poly1305

### What did you see instead?
 initializing ciphers... xchacha20-ietf-poly1305
 invalid cipher name: xchacha20-ietf-poly1305
 failed to initialize ciphers

**Comment by madeye** [comment]
Rebuild your binary with latest libsodium.

**Comment by wukaisky** [comment]
up to the latest libsodium,He said no find libsodium.so.18 (now is libsodium.so.23)

**Comment by tkisme** [comment]
in openwrt-shadowsocks release page. [link](https://github.com/shadowsocks/openwrt-shadowsocks/releases)
then click openwrt-dist [link](http://openwrt-dist.sourceforge.net/archives/shadowsocks-libev/3.1.3-4/)
go to legacy and install libsodium_xxx.ipk could fix your problem

**Comment by wukaisky** [comment]
I am compiling openwrt myself

**Comment by wukaisky** [comment]
openwrt-18.06 is OK
