### ISSUE TITLE
TCP Fastopen (TFO) doesn't work in openwrt ss-redir

### ISSUE THREAD

**Issue by tkisme** [shadowsocks/shadowsocks-libev#2046]
### What version of shadowsocks-libev are you using?
v3.1.3-4 in openwrt-shadowsocks

### What operating system are you using?
openwrt kernel 3.18.23 

### What did you do?
upgrade ss to 3.1.3 previous is 3.1.0
3.1.0 has no error
run ss-redir with tcp fast open

### What did you expect to see?
no error

### What did you see instead?
tcp fast open is not supported on this platform

### What is your config in detail (with all sensitive info masked)?
local:
set 
"fast_open": true,
"mode": "tcp_only"

server:
"fast_open": true,
"mode": "tcp_and_udp"

**Comment by madeye** [comment]
Double check the environment you cross compile the package. Make sure it has the TCP_FASTOPEN related headers.
