### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by 823639792** [shadowsocks/shadowsocks-libev#2047]
将请求伪装成http（websokcet）请求理论上是否可行？

大概思路  shadowsocks client<->http<->shadowsocks server
所有人都访问80或者443端口。
这样是不是就不容易被封了呢？

**Comment by chenhw2** [comment]
https://github.com/shadowsocks/simple-obfs

**Comment by studentmain** [comment]
已有现有产品(simple-obfs, obfs4, ssrr, v2ray......)，而且正用得风生水起，但务必正确部署，不要挂个
cloudflare.com
的假证就跑(推荐部署方案：真正建一个https网站，然后申请一张真正的证书，用真正的web服务器转发特定路径的请求到后端服务器)。

823639792 <notifications@github.com> 于 2018年5月10日周四 22:25写道：

**Comment by choicky** [comment]
@studentmain v2ray 可以配置 web server 特定路径转发。ss （simple-obfs）怎么配呢？ 之前捣鼓过 caddy server，不知道怎么配置……

**Comment by jiuqianyuan** [comment]
用simple-obfs伪装tls或http后，怎么配置caddy转发请求，试了好久都弄不出来
