### ISSUE TITLE
How can I grep the stdout of ss-local in realtime?

### ISSUE THREAD

**Issue by Campanula** [shadowsocks/shadowsocks-libev#2048]
### What version of shadowsocks-libev are you using?
shadowsocks-libev 3.1.3

### What operating system are you using?
Manjaro Linux 17.1.10 Hakoila
x86_64 Linux 4.16.7-1-MANJARO

### What did you do?
I can't grep the stdout of ss-local in realtime
```
ss-local -c config.json -v | tail -f
```
OR
```
ss-local -c config.json -v > ss-local.log 2>&1
tail -f ss-local.log
```
I want to wrap ss-local with python, but I can't get the log in realtime, then I find `tail -f ` can not also.

### What did you expect to see?
see stdout output from PIPE in realtime
see stdout log redirect to file in realtime

### What did you see instead?
there is no output in terminal or file that redirect to, until I kill the ss-local process.
I found a workaround, but it's not elegant.
```
ss-local -c config.json -v -f /tmp/ss-local.pid
journalctl -f | grep ss-local
```
I have searched in issues, the similar issues:
https://github.com/shadowsocks/shadowsocks-libev/issues/1999

It seems like a fix had been applied. `fflush(stdout)`.
but it dose't help.
Maybe, something goes wrong in my brains... 🙀

### What is your config in detail (with all sensitive info masked)?
like this, a normal config
```
{
    "server": "12.34.56.78",
    "server_port": "43210",
    "local_port": "1080",
    "password": "******",
    "method": "aes-256-cfb"
}
```

**Comment by xnoreq** [comment]
Why do you run `ss-local -c config.json -v | tail -f`? What do you expect to see from a `tail -f`?
`tail` seeks until it found the end of the file, which will never happen... and then it outputs the last lines.
See `man 1 tail`.

Even more curiously is that you don't even want tail according to your own words:
"I can't **grep** the stdout of ss-local in realtime"

Then why don't you pipe ss-local into grep?!

**Comment by Campanula** [comment]
@xnoreq thanks, I realized I mistook `tail`.
but it still makes me confused, when I type `ss-local -c config.json -v | grep INFO`, I still get nothing.
it seems like I can't get ouput after redirect stdout to **PIPE or FILE**. Is it possible to do that?

```
ss-local -c config.json -v > ss-local.log 2>&1
tail -f ss-local.log  # nothing in ss-local.log
```

```
journalctl -f > /tmp/j.tmp
tail -f /tmp/j.tmp  # log into file in realtime
```
what's the diffrence?

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
I don't want to ask a XY problem, I just want to do this:
python code:
```
with subprocess.Popen(
    ['ss-local', '-c', 'config.json', '-v'],,
    stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
    encoding='utf-8'
) as process:
    for line in iter(process.stdout.readline, ''):
        sys.stdout.write(line)
```
readline() blocked, replace the cmd to `['journalctl', '-f']`, it's ok.

**Comment by Campanula** [comment]
Thank you ~
a little busy these days so such a late reply.
After updating to the latest code, I get what I expected.
I thought the `fflush(stdout)` was already there in v3.1.3, then I found it has not even been released yet.
thanks for your help 😊

**Comment by Campanula** [comment]
Thank you ~
a little busy these days so such a late reply.
After updating to the latest code, I get what I expected.
I thought the fflush(stdout) was already there in v3.1.3, then I found it has not even been released yet.
thanks for your help 😊
