### ISSUE TITLE
i have a error

### ISSUE THREAD

**Issue by chainofhonor** [shadowsocks/shadowsocks-libev#2050]
centos 7    1708 minimal

wget https://copr.fedorainfracloud.org/coprs/librehat/shadowsocks/repo/epel-7/librehat-shadowsocks-epel-7.repo
mv librehat-shadowsocks-epel-7.repo /etc/yum.repos.d/
yum -y install epel-release
yum install -y shadowsocks-libev
ss-local -s 1.1.1.1 -p 1281 -k password -m aes-256-cfb -l 1080 -b 0.0.0.0

There is an error prompt that there is a .so file wrong

**Comment by xnoreq** [comment]
Ask your distribution/packager. Here's a hint though: nobody will be able to help if all the information you provide is that some error occurred.

**Comment by chainofhonor** [comment]
#ln -s /usr/lib/libmbedcrypto.so.1 /usr/lib/libmbedcrypto.so.0
ln -s /usr/lib64/libmbedcrypto.so.1 /usr/lib64/libmbedcrypto.so.0
