### ISSUE TITLE
make failed

### ISSUE THREAD

**Issue by 3xpert** [shadowsocks/shadowsocks-libev#2052]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
shadowsocks-libev 3.1.3 21fb6e6

### What operating system are you using?
cento6

### What did you do?
upate to 21fb6e6 and make

### What did you expect to see?
make completed

### What did you see instead?
config.status: executing depfiles commands
config.status: executing libtool commands
make  all-recursive
make[1]: Entering directory `/opt/shadowsocks-libev'
Making all in libcork
make[2]: Entering directory `/opt/shadowsocks-libev/libcork'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/opt/shadowsocks-libev/libcork'
Making all in libipset
make[2]: Entering directory `/opt/shadowsocks-libev/libipset'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/opt/shadowsocks-libev/libipset'
Making all in libbloom
make[2]: Entering directory `/opt/shadowsocks-libev/libbloom'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/opt/shadowsocks-libev/libbloom'
Making all in src
make[2]: Entering directory `/opt/shadowsocks-libev/src'
  CCLD   ss-local
ss_local-crypto.o: In function `crypto_md5':
/opt/shadowsocks-libev/src/crypto.c:110: undefined reference to `mbedtls_md5'
collect2: ld returned 1 exit status
make[2]: *** [ss-local] Error 1
make[2]: Leaving directory `/opt/shadowsocks-libev/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/opt/shadowsocks-libev'
make: *** [all] Error 2

**Comment by yanqiyu** [comment]
Something wrong libmbedtls.
Check the shared lib file

**Comment by neveroldmilk** [comment]
The shadowsocks-libev author has updated mbedtls-devel to version 2.8.0+ in the most-updated git version, and the source of shadowsocks-libev does not update with this change. So either install mbedtls-devel version 2.8.0, or use the older shadowsocks-libev (older than release version 3.1.3).

export MBEDTLS_VER=2.8.0
wget https://tls.mbed.org/download/mbedtls-$MBEDTLS_VER-gpl.tgz
tar xvf mbedtls-$MBEDTLS_VER-gpl.tgz
pushd mbedtls-$MBEDTLS_VER
make SHARED=1 CFLAGS=-fPIC
sudo make DESTDIR=/usr install
popd
sudo ldconfig
