### ISSUE TITLE
bind: Address already in use

### ISSUE THREAD

**Issue by Unbinilium** [shadowsocks/shadowsocks-libev#2053]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
https://github.com/shadowsocks/shadowsocks-libev/commit/21fb6e639e7becba00cbc27a2d2e6a8181ee9c5f

### What operating system are you using?
Ubuntu 18.04

### What did you do?
`/usr/local/bin/ss-server -u -c /etc/shadowsocks-libev/config.json -f /var/run/shadowsocks-libev.pid`

### What did you expect to see?
Running Correctly

### What did you see instead?
2018-05-18 02:28:04 INFO: resolving hostname to IPv6 address first
 2018-05-18 02:28:04 INFO: using tcp fast open
 2018-05-18 02:28:04 INFO: UDP relay enabled
 2018-05-18 02:28:04 INFO: enable TCP no-delay
 2018-05-18 02:28:04 INFO: initializing ciphers... xchacha20-ietf-poly1305
 2018-05-18 02:28:04 INFO: using nameserver: 8.8.8.8,8.8.4.4,208.67.222.222,208.67.220.220
 2018-05-18 02:28:04 INFO: tcp server listening at 0.0.0.0:53
 2018-05-18 02:28:04 INFO: tcp port reuse enabled
 2018-05-18 02:28:04 ERROR: bind: Address already in use
 2018-05-18 02:28:04 ERROR: bind() error

### What is your config in detail (with all sensitive info masked)?
```
{
    "server":["0.0.0.0","[::0]"],
    "server_port":53,
    "password":"Password",
    "method":"xchacha20-ietf-poly1305",
    "fast_open":true,
    "reuse_port":true,
    "nofile":512000,
    "nameserver":"8.8.8.8,8.8.4.4,208.67.222.222,208.67.220.220",
    "mode":"tcp_and_udp",
    "mptcp":false,
    "ipv6_first":true,
    "use_syslog":false,
    "no_delay":true,
}
```

**Comment by madeye** [comment]
As the error message said, UDP port 53 is being used by other application, typically a local name server.

**Comment by Unbinilium** [comment]
TCP 53 and UDP 53 which the ss-server is using are conflict with systemd-resolved service since upgraded system to Ubuntu 18.04, is there anyway to solve it without disabling systemd-resolved service?

**Comment by madeye** [comment]
Change your ss-server's port or change 'systemd-resolved`'s port.

**Comment by Unbinilium** [comment]
Thanks for reply. I also got some useful information here https://askubuntu.com/questions/898605/how-to-disable-systemd-resolved-and-resolve-dns-with-dnsmasq. I found that difficult to change system-resolved port so I tried to switch the default name resolve service to dnsmasq, and it works. Comment here may did some help. Close now.
