### ISSUE TITLE
ss-server not working with -c parameter on CentOS

### ISSUE THREAD

**Issue by peyotll** [shadowsocks/shadowsocks-libev#2060]
### What version of shadowsocks-libev are you using?
3.1.3

### What operating system are you using?
CentOS 7.5

### What did you do?
ss-server -c /etc/shadowsocks-libev/config.json

### What did you expect to see?
running server

### What did you see instead?
the same as if I did ss-server -h

### What is your config in detail (with all sensitive info masked)?
{
    "server":"0.0.0.0",
    "port":8666,
    "local_port":1080,
    "password":"****************",
    "timeout":60,
    "method":"chacha20-ietf-poly1305"
}

**Comment by madeye** [comment]
```
{
"server":"0.0.0.0",
"serer_port":8666,
"local_port":1080,
"password":"****************",
"timeout":60,
"method":"chacha20-ietf-poly1305"
}
```

**Comment by peyotll** [comment]
Thanks! did it change recently? I am using "port" in a config file on another server I setup a few months ago and didn't have any problem.

**Comment by madeye** [comment]
It's never changed: https://github.com/shadowsocks/shadowsocks-libev/blob/master/doc/shadowsocks-libev.asciidoc#config-file
