### ISSUE TITLE
To support multiple users with single port

### ISSUE THREAD

**Issue by oklnk** [shadowsocks/shadowsocks-libev#2062]
This is a feature request; if the feature is existing, please show how to use the feature and close this item.

By using this feature, more than one user(ss client) can share one single port to connect ss server, while ss manager should still be able to add/remove single or multiple users, and receive usage statistics for each user.

### What version of shadowsocks-libev are you using?
v3.1.3

### What operating system are you using?
CentOS

**Comment by madeye** [comment]
It's a design choice of shadowsocks protocol.

You may find other projects that would support your purposed feature like v2ray.
