### ISSUE TITLE
ERR_SSL_VERSION_INTERFERENCE frequently occurred

### ISSUE THREAD

**Issue by cnyyk** [shadowsocks/shadowsocks-libev#2067]
### What version of shadowsocks-libev are you using?
3.1.3

### What operating system are you using?
macOS 10.13.4 (17E202)

### What did you do?
Visit https site via Chrome (Version: 66.0.3359.181 (Official Build) (64-bit) macOS)

### What did you expect to see?
Normal page content

### What did you see instead?
This site can’t be reached
ERR_SSL_VERSION_INTERFERENCE

### What is your config in detail (with all sensitive info masked)?
ss is running in LEDE 17.01.4 with luci-app-shadowsocks (http://openwrt-dist.sourceforge.net/packages/base/arm_cortex-a9_vfpv3/shadowsocks-libev_3.1.3-4_arm_cortex-a9_vfpv3.ipk)

When disable the "TLS 1.3" via chrome://flags, everything's OK.
If TLS 1.3 is enabled, this error occurred very frequently.

Found a link from Chromium project official site mentioned this problem:
https://sites.google.com/a/chromium.org/dev/Home/tls13

**Comment by cnyyk** [comment]
And the LibreSSL SSL_ERROR_SYSCALL occurred frequently.

```
==> Upgrading memcached 
==> Downloading https://homebrew.bintray.com/bottles/memcached-1.5.8.high_sierra.bottle.tar.gz

curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to homebrew.bintray.com:443 
Error: Failed to download resource "memcached"
Download failed: https://homebrew.bintray.com/bottles/memcached-1.5.8.high_sierra.bottle.tar.gz
Warning: Bottle installation failed: building from source.
```

**Comment by cnyyk** [comment]
```
➜  ~ /usr/bin/ssserver --version
Shadowsocks 2.8.2
➜  ~ uname -a
Linux twins.im 2.6.32-042stab127.2 #1 SMP Thu Jan 4 16:41:44 MSK 2018 i686 i686 i386 GNU/Linux
➜  ~ cat /etc/redhat-release 
CentOS release 6.9 (Final)
```

**Comment by cnyyk** [comment]
```
/usr/bin/ssserver -s ::0 -p 22 -k helloworldcrossthewall -m bf-cfb -user nobody --workers 2 -d start
```

**Comment by madeye** [comment]
Try shadowsocks-libev as your server.

**Comment by cnyyk** [comment]
Ok, I'll try to use the latest version. Thanks for your help.
