### ISSUE TITLE
build_deb.sh don't bump version to 3.2.0

### ISSUE THREAD

**Issue by vcarus** [shadowsocks/shadowsocks-libev#2069]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
git version

### What operating system are you using?
ubuntu 18.04

### What did you do?
build from build_deb.sh

### What did you expect to see?
new version

### What did you see instead?
still 3.1.3

**Comment by madeye** [comment]
It's expected. Wait until the downstream is updated.
