### ISSUE TITLE
shadowsocks-libev2.0.1 polarssl1.3.9 Windows 7(32位) MinGW 编译错误 

### ISSUE THREAD

**Issue by Springchendg** [shadowsocks/shadowsocks-libev#207]
gcc版本4.9.2，错误信息：

Making all in src
make[2]: Entering directory `/home/user/shadowsocks-libev-2.0.1/src'
  CC     libshadowsocks_la-utils.lo
  CC     libshadowsocks_la-jconf.lo
  CC     libshadowsocks_la-json.lo
  CC     libshadowsocks_la-encrypt.lo
  CC     libshadowsocks_la-udprelay.lo
udprelay.c: In function 'parse_udprealy_header':
udprelay.c:191:21: error: implicit declaration of function 'inet_pton' [-Werror=
implicit-function-declaration]
                     inet_pton(AF_INET, host, &(addr->sin_addr));
                     ^
udprelay.c: In function 'server_recv_cb':
udprelay.c:609:5: error: implicit declaration of function 'bzero' [-Werror=impli
cit-function-declaration]
     bzero(&src_addr, sizeof(struct sockaddr_storage));
     ^
udprelay.c:609:5: error: incompatible implicit declaration of built-in function
'bzero' [-Werror]
cc1.exe: all warnings being treated as errors
make[2]: *** [libshadowsocks_la-udprelay.lo] Error 1
make[2]: Leaving directory `/home/user/shadowsocks-libev-2.0.1/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/user/shadowsocks-libev-2.0.1'
make: *** [all] Error 2

**Comment by madeye** [comment]
Fixed via 64c494e18f9059258675d2df2c95c595918777c8
