### ISSUE TITLE
为什么安卓客户端都有绕过局域网和中国大陆，PC端却没有。。

### ISSUE THREAD

**Issue by 17301008** [shadowsocks/shadowsocks-libev#2074]
这个功能非常好用，国外的所有网站都走代理，速度会比不开代理打开快，STEAM也可以快速打开，
但是为什么PC端没有这个功能，我也看过支持ACL规则，但是尝试启用过，可是没有效果，
为什么PC端不加个绕过局域网和中国大陆地址，如果有其他办法，请告诉我，谢谢。

中国的IP地址库可以在这里找到http://www.ipdeny.com/ipblocks/data/aggregated/cn-aggregated.zone
经常更新的，

**Comment by SharerMax** [comment]
Hi，please move to https://github.com/shadowsocks/shadowsocks-windows/issues
