### ISSUE TITLE
PPA for ubuntu bionic

### ISSUE THREAD

**Issue by al2389** [shadowsocks/shadowsocks-libev#2078]
When will the PPA for ubuntu bioinc be available ? 

I am going to upgrade my server (x86_64) server from xenial to bionic, but hesitated to do so as the ppa is not available now.

**Comment by madeye** [comment]
https://launchpad.net/ubuntu/+source/shadowsocks-libev

**Comment by al2389** [comment]
> https://launchpad.net/ubuntu/+source/shadowsocks-libev

Thanks, although that is an older version 3.1.3, not so update as the PPA 3.2.0.

**Comment by noname8964** [comment]
yep, the official repo is still 3.1.3
