### ISSUE TITLE
Merge stream.c and aead.c

### ISSUE THREAD

**Issue by YegorIevlev** [shadowsocks/shadowsocks-libev#2081]
What do you think about merging stream.c and aead.c to reduce confusion? Why have a separate set of functions for AEAD ciphers?

**Comment by madeye** [comment]
You shouldn't do that. They are two different protocols.

https://shadowsocks.org/en/spec/AEAD-Ciphers.html

https://shadowsocks.org/en/spec/Stream-Ciphers.html
