### ISSUE TITLE
Send UDP traffic over shadowsocks

### ISSUE THREAD

**Issue by YegorIevlev** [shadowsocks/shadowsocks-libev#2082]
How can I run all UDP traffic over shadowsocks on a Linux machine? I only see instructions for running DNS over it, and they seem incomplete (port is 12345).

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks-libev#transparent-proxy

**Comment by YegorIevlev** [comment]
@madeye Is the port supposed to be 12345?

**Comment by madeye** [comment]
12345 is just a random port used for demonstration

**Comment by YegorIevlev** [comment]
@madeye Should I set it to a port ss-redir is running on?

**Comment by madeye** [comment]
Yes.

**Comment by serverlinuxit** [comment]
can I use this transparent proxy at shadowsocksR?
