### ISSUE TITLE
Is there a way to route traffic on the server side?

### ISSUE THREAD

**Issue by flipphos** [shadowsocks/shadowsocks-libev#2083]
I have been thinking about this for quite some time and am hoping someone can shed some lights on me. After an internet traffic hits ss-server, is there a way to redirect  it to another VPS (or another backend) based on its target domain, after the decryption? This is useful to watch Netflix, for instance, as only some VPS with certain IPs can stream Netflix. Thanks!

**Comment by madeye** [comment]
Try iptables or HAProxy.

**Comment by flipphos** [comment]
Could you enlighten me by giving examples on iptables on the server side? Thanks a lot!

**Comment by madeye** [comment]
A guide in Chinese: https://doub.io/ss-jc34/

**Comment by flipphos** [comment]
Thanks! But I meant to redirect only the target domains or IPs, e. g. the domains and/or IPs relevant for streaming Netflix. 
Say:
 *.netflix.com
*.netflix.net
*.nflxext.com
*.nflximg.com
*.nflximg.net
these (and only these) target domains should be diverted to another VPS whose IP is capable of streaming Netflix.

**Comment by DarienRaymond** [comment]
Welcome to use Project V: https://www.v2ray.com/en/configuration/routing.html

**Comment by madeye** [comment]
If so, try HAProxy instead.
