### ISSUE TITLE
I set up the ss server, but I still cant ping with google

### ISSUE THREAD

**Issue by nefiend** [shadowsocks/shadowsocks-libev#2085]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
shadowsocks-libev 3.2.0

### What operating system are you using?
Linux nefiend-Aspire-4830TG 4.13.0-43-generic #48~16.04.1-Ubuntu SMP Thu May 17 12:56:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### What did you do?
nefiend@nefiend-Aspire-4830TG ~ $ ss-local -c /etc/shadowsocks-libev/config.json 
 2018-06-09 01:47:29 INFO: initializing ciphers... chacha20-ietf-poly1305
 2018-06-09 01:47:31 INFO: listening at 127.0.0.1:8080

### What did you expect to see?
i ping with www.google.com, but i failed

### What did you see instead?
ping failed
nefiend@nefiend-Aspire-4830TG ~ $ ping www.google.com
PING www.google.com (93.46.8.89) 56(84) bytes of data.
^C
--- www.google.com ping statistics ---
4 packets transmitted, 0 received, 100% packet loss, time 3065ms

### What is your config in detail (with all sensitive info masked)?
{
    "server":"w2.bigfield.link",
    "server_port":993,
    "local_port":8080,
    "password":"********",
    "timeout":60,
    "method":"chacha20-ietf-poly1305",
    "local_address":"127.0.0.1"
}

**Comment by Love4Taylor** [comment]
shadowsocks only support TCP/UDP

**Comment by nefiend** [comment]
but i cant access to www.google.com either

**Comment by studentmain** [comment]
You mean from browser? Please post logs here.

nefiend <notifications@github.com> 于 2018年6月10日周日 01:31写道：

**Comment by xnoreq** [comment]
If you can't ping google then your interface/routes aren't set up properly and you don't have proper Internet access. This has nothing to do with shadowsocks.
Fix your Internet connection first, then add shadowsocks.

**Comment by nefiend** [comment]
sry, I forgot to reply, I found the reason why I can’t access to google, that is cause I didn’t set my browser proxy😂
Thanks for answering me!
