### ISSUE TITLE
This project does not work well with simple-obfs when using shell params

### ISSUE THREAD

**Issue by zpf124** [shadowsocks/shadowsocks-libev#2089]
### What version of shadowsocks-libev are you using?
shadowsocks-libev 3.2.0

### What operating system are you using?
CentOS Linux release 7.5.1804 Kernel 2.6.32-042stab127.2
but this project was running in docker 

### What did you do?
first time I run with this command:
` ss-server -s 0.0.0.0 -p 8388 -k * -m * -t 300 --fast-open -u --plugin obfs-server --plugin-opts "obfs=tls"`
but I can connect to the server, It always reports the error that is below this section,  
then I found [this issue](https://github.com/shadowsocks/shadowsocks-libev/issues/1924) . I guess I may have encountered this problem too, so I changed my command with `config.json` 
like this:
`ss-server -c /etc/shadowsocks-libev/config.json -u`
this time, It's working.

---------- repeat  in Chinese -------------------
我发现 目前版本的项目 通过命令行参数和 json 来启动的效果有些奇怪的差异，导致了 simple-obfs不能正常工作了。
一开始 我使用 `-s`、`-p`、`--plugin`  这样命令行传参的方式启动 ss 服务端，结果simple-obfs的校验一直报错。
仔细一看好像是 simple-obfs 连不上 ss 的端口了，错误日志我贴在下面了，主要就那两句一直在刷屏。
后来我搜到了那个 关于 local_address local_port 问题，觉得是不是我也是这个问题，
然后我一开始还不死心想用命令行指定一个 local_address 看看能不能行 -l 端口这里不知道该指定啥了就没写 -l，
` ss-server -s 0.0.0.0 -p 8388 -b 0.0.0.0 --plugin ....`
结果还是不行， 最后 我用 -c 指定配置文件的方式 结果项目好使了...

### What did you see instead?
```
ss_1 |  2018-06-09 13:22:56 INFO: using tcp fast open
ss_1 |  2018-06-09 13:22:56 INFO: plugin "obfs-server" enabled
ss_1 |  2018-06-09 13:22:56 INFO: UDP relay enabled
ss_1 |  2018-06-09 13:22:56 INFO: initializing ciphers... aes-256-gcm
ss_1 |  2018-06-09 13:22:56 INFO: using nameserver: 8.8.4.4
ss_1 |  2018-06-09 13:22:56 INFO: tcp server listening at 127.0.0.1:29614
ss_1 |  2018-06-09 13:22:56 INFO: udp server listening at 0.0.0.0:8388
ss_1 |  2018-06-09 13:22:56 ERROR: fast open is not supported on this platform
ss_1 |  2018-06-09 13:22:56 [simple-obfs] INFO: tcp port reuse enabled
ss_1 |  2018-06-09 13:22:56 [simple-obfs] INFO: listening at 0.0.0.0:8388
ss_1 |  2018-06-09 13:23:03 ERROR: failed to handshake with 127.0.0.1: authentication error
ss_1 |  2018-06-09 13:23:03 [simple-obfs] ERROR: remote recv: Connection reset by peer
ss_1 |  2018-06-09 13:23:17 ERROR: failed to handshake with 127.0.0.1: authentication error
ss_1 |  2018-06-09 13:23:17 [simple-obfs] ERROR: remote recv: Connection reset by peer
ss_1 |  2018-06-09 13:23:18 ERROR: failed to handshake with 127.0.0.1: authentication error
ss_1 |  2018-06-09 13:23:18 [simple-obfs] ERROR: remote recv: Connection reset by peer
ss_1 |  2018-06-09 13:23:20 ERROR: failed to handshake with 127.0.0.1: authentication error
ss_1 |  2018-06-09 13:23:20 [simple-obfs] ERROR: remote recv: Connection reset by peer
```

### What is your config in detail (with all sensitive info masked)?
```
{
    "server":"0.0.0.0",
    "server_port":8388,
    "password":"",
    "timeout":300,
    "method":"",
    "plugin":"obfs-server",
    "plugin_opts":"obfs=tls",
    "fast_open":true
}
```

**Comment by madeye** [comment]
Is there any special character in your password?

**Comment by madeye** [comment]
I tried following command lines locally. It works well:

```
ss-server -s 0.0.0.0 -k 1234 -m aes-128-gcm -p 8190 --plugin obfs-server --plugin-opts "obfs=tls" &
ss-local -s 127.0.0.1 -p 8190 -l 1081 -k 1234 -m aes-128-gcm --plugin obfs-local --plugin-opts "obfs=tls" &
curl --socks5-hostname 127.0.0.1:1081 www.baidu.com
```

**Comment by zpf124** [comment]
No, My password is a number string。

Maybe it is the problem of parameter passing?

My boot command is like this

`docker run -it -e "-s 0.0.0.0 -k 1234 -m aes-128-gcm -p 8190 --plugin obfs-server --plugin-opts \"obfs=tls\"" shadowsocks-libev`

[this is my docker image](https://hub.docker.com/r/zpf124/shadowsocks-libev/) and  [this is my dockerfile](https://github.com/zpf124/dockerfile/tree/master/shadowsocks-libev)

**Comment by madeye** [comment]
If it's a docker specific problem, you have to figure out it yourself.

Generally, you can follow the above command lines to test if it works in a regular shell.
