### ISSUE TITLE
请问有无办法把详细log印出

### ISSUE THREAD

**Issue by jerry74** [shadowsocks/shadowsocks-libev#209]
因为现在跑个几分钟就挂掉 想找原因
syslog里也看不到错误
请问有无办法把详细log印出？

启动方式为/etc/init.d/shadowsocks start

**Comment by madeye** [comment]
加参数 `-v`，在命令行中启动。

**Comment by dutonttie** [comment]
我也发现了这个问题，我以为是我的Vps内存太少所致(64M)。

**Comment by jerry74** [comment]
你可以查看看sysctl.d net.ipv4.tcp_tw_recycle=1
这样好像会让shadowsocks-libev的挂掉
同台机器同时跑python版没这挂掉问题

**Comment by dutonttie** [comment]
我的是值0，应该和它没关系，我回到1.6.4版本就正常。

**Comment by LazyZhu** [comment]
duende-ng可以把output转换到syslog中:
https://github.com/samboy/MaraDNS/blob/master/tools/duende-ng.c
