### ISSUE TITLE
ss-libev如何启用ACL分流，本地客户端怎么设置。我按WIKI设置了没效果

### ISSUE THREAD

**Issue by 17301008** [shadowsocks/shadowsocks-libev#2090]
--acl /etc/init.d/chn.acl    使用此命令，ACL已经在服务端正确加载，

https://raw.githubusercontent.com/shadowsocks/shadowsocks-libev/master/acl/chn.acl
使用的上面这个ACL，

http://www.ipdeny.com/ipblocks/data/aggregated/cn-aggregated.zone
根据上面这个大陆IP地址，更新了ACL里面的大陆IP，

但是重启SS后，还是没效果，只是想实现除了大陆IP外的全部地址，都走代理，无论是否被墙，
这样可以大大提高国外网站的访问速度（PAC不行，因为GFW外的国外地址不会走代理）

明明支持ACL的，但设置完就是没效果，有没有大佬告知下应该怎么设置服务端和客户端，

服务器，Debian 7.8，服务端版本3.2.0，客户端版本4.0.10
我的启动命令是 ss-server -uv -c /etc/shadowsocks-libev/config.json -f /shadowsocks-libev.pid --acl /etc/init.d/chn.acl

**Comment by debiansid** [comment]
ss-local 才有用啊

**Comment by 17301008** [comment]
@debiansid 那请问我可以在哪里找到教程。。需要怎么设置。。。客户端也需要设置吗，

**Comment by madeye** [comment]
ACL is not for ss-server.

**Comment by 17301008** [comment]
@madeye   what can i do?  i need help~

**Comment by debiansid** [comment]
https://darknode.in/network/acl-geoip-proxy/

**Comment by kimw** [comment]
> ACL is not for ss-server.

@madeye ss-server supports ACL with only `[outbound_block_list]` section.

See https://github.com/shadowsocks/shadowsocks-libev/blob/167b510053c89947242001bf7d4e3e2ad1e44b92/acl/server_block_chn.acl

https://github.com/shadowsocks/shadowsocks-libev/blob/167b510053c89947242001bf7d4e3e2ad1e44b92/acl/server_block_chn.acl#L1-L6

**Comment by 17301008** [comment]
@kimw 但是这个是阻止访问，并不是不走代理。。。。且国外的所有网站，还是只会走黑名单，不在黑名单的不会走代理。。。
