### ISSUE TITLE
Can't install shadowsocks-libev from PPA

### ISSUE THREAD

**Issue by billysingo** [shadowsocks/shadowsocks-libev#2091]
### What version of shadowsocks-libev are you using?
none

### What operating system are you using?
ubuntu 14.04 LTS

### What did you do?
follow the instructions:
```
sudo apt-get install software-properties-common -y
sudo add-apt-repository ppa:max-c-lv/shadowsocks-libev -y
sudo apt-get update
sudo apt install shadowsocks-libev
```

### What did you expect to see?
install the latest shadowsocks-libev 

### What did you see instead?
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package shadowsocks-libev
```
### What is your config in detail (with all sensitive info masked)?
none

**Comment by madeye** [comment]
Please try again.

**Comment by billysingo** [comment]
thanks. solved.
