### ISSUE TITLE
TLS connection setup works only on 2nd attempt on ss-server, causing delay

### ISSUE THREAD

**Issue by knxhm** [shadowsocks/shadowsocks-libev#2094]
### Topology:
https windows client with firefox -> wifi -> linux router Debian 8/kernel 4.9.87/MPTCP/shadowsocks  ->  3 parallel wireless WAN links (using MPTCP) -> linux router Debian 9/kernel 4.9.87/MPTCP/shadowsocks -> internet connection  -> https server in internet

### What version of shadowsocks-libev are you using?
shadowsocks-libev  2.6.3+ds-3+deb9u1 with mbed TLS 2.4.2

### What operating system are you using?
Debian 8/9 + kernel 4.9.87 + MPTCP

### What did you do?
browse from client a https site

### What did you expect to see?
the web page should build up fast

### What did you see instead?
sometimes the web page builds up slow because TLS procedure is aborted/repeated by proxy, 
see wireshark traces.

### What is your config in detail (with all sensitive info masked)?
ss-redir
{
    "server" : ["serverip"],
    "server_port" : xxx,
    "local_address" : "0.0.0.0",
    "local_port" : 1080,
    "password" : "xxxxxxxxxxxxxx",
    "timeout" : 300,
    "method" : "aes-256-cfb",
    "fast_open" : true,
}

ss-server
{
    "server":"0.0.0.0",
    "server_port":xxxx,
    "local_address": "0.0.0.0",
    "local_port":1203,
    "password":"xxxxxxxxxxxxxx",
    "timeout":300,
    "method":"aes-256-cfb",
    "fast_open": true
}

### 1. Packet traces - session establishment to 193.99.144.85 with 2nd attempt
packet trace on client when client browses the web page https://www.heise.de. Extracted only one TCP connections out of many, there are more with the same behaviour:
1045_193.99.144.85_client.pcapng     there is a 13sec delay between pkt 5 and 8 (6,7 are keepalive)

packet trace on server interface, internet facing side
1045_193.99.144.85_tls_1try_fail.pcapng    the 1 attempt to establish the session failed, TCP is closed
1045_193.99.144.85_tls_2retry_ok.pcapng    the 2nd attempt to to establish the session works and after it is established the client session setup proceeds (client pkt 8 in client trace)

From client point of view there is only one session establishment but with a long pause in between.
The problem does not always happen, it is random. But it looks like it only happens when there is more  load on the proxy, when there are about 20-30 users with a total WAN bandwidth of roughly 50Mbit/sec.

### 2. Packet traces - session establishment to 1.f.ix.de (193.99.144.87) with 2nd attempt ok and some attempts even lost, in client trace are more TCP connection setups as on server interface trace
see waterfall flow1.JPG, many attempt to 1.f.ix.de are unanswered (grey lock with red line)
1045_193.99.144.87_client.pcapng
1045_193.99.144.87_server.pcap
[sockstlsfiles.zip](https://github.com/shadowsocks/shadowsocks-libev/files/2102699/sockstlsfiles.zip)

**Comment by madeye** [comment]
Unfortunately, MPTCP is not officially supported yet, which is contributed by OVH.

You may have to debug the problem yourself.

**Comment by knxhm** [comment]
Hm, I did not activate the MPTCP option in shadowsocks, and the proxy actually does not know that there is MPTCP activated between ss-redir and ss-server, MPTCP is handling the multiple links on its own, this should be completely transparent to shadowsocks.
When I look into the shadowsocks code I see that shadowsocks makes a difference for http and https to get the host name. In the https case which I have traced, the hostname extension in the packet exists, but the string is empty. 
Can it be that this makes trouble ?
*      Handshake Protocol: Server Hello
            Handshake Type: Server Hello (2)
            Length: 87
            Version: TLS 1.2 (0x0303)
            Random: 100a235b1718ced6c9668d5a5ab976e0ff38986f7916dc23...
            Session ID Length: 32
            Session ID: 0e14710f2319a5b2765c3bc00ae1ccba8aeeda2be7f8b8e3...
            Cipher Suite: TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (0xc030)
            Compression Method: null (0)
            Extensions Length: 15
            Extension: renegotiation_info (len=1)
                Type: renegotiation_info (65281)
                Length: 1
                Renegotiation Info extension
            Extension: server_name (len=0)
                Type: server_name (0)
                Length: 0
            Extension: ec_point_formats (len=2)
                Type: ec_point_formats (11)
                Length: 2
                EC point formats Length: 1
                Elliptic curves point formats (1)
*      TLSv1.2 Record Layer: Change Cipher Spec Protocol: Change Cipher Spec
        Content Type: Change Cipher Spec (20)
        Version: TLS 1.2 (0x0303)
        Length: 1
        Change Cipher Spec Message

**Comment by madeye** [comment]
It looks you're using an old version. Try the latest one first.

**Comment by knxhm** [comment]
Still working to prepare a test with the latest version.

**Comment by knxhm** [comment]
I look like I found the problem. In the systemd config file for the ss-server service not just LimitNOFILE=99999 has to be specified but also LimitNPROC=99999. By default only 4000 open files were allowed for the ss-server process and this led to lost connection attempts.
