### ISSUE TITLE
Make ss-local to act as a socket proxy provider for other clients, for outside LAN access

### ISSUE THREAD

**Issue by galaxy001** [shadowsocks/shadowsocks-libev#2095]
The situation is running `ss-local` behind a NAT-ed LAN, and I need to ssh onto other LAN servers outside that LAN. 
Only the `ss-server` have a public IP, both clients cannot make conections directly.

For `ssh`, it can be achieved by `ssh SERVER.IP -R9999:127.0.0.1:22`, then everyone can `ssh -p9999 SERVER.IP` to connect to that local machine. 
And `ssh -p9999 SERVER.IP -D11111` will forward port 11111 to that local machine with dynamic application protocol. 
Now, it is possible to access my LAN server with `ssh -o ProxyCommand='nc -x 127.0.0.1:11111 %h %p' 192.168.1.3`.

I hope `ss-local` can forward port 11111 directly and making the last command possible, with the help of a centeral `ss-server`.

And it will be safer if `ss-server` acts as a virtual hub without listerning on  `SERVER.IP:9999`.

ShadowVPN have `user_token` settings, we may use same way to distinguish clients. 
For most application, a socket proxy is enough, and the TUN from ShadowVPN will be overhead.

**Comment by madeye** [comment]
No plan for this.
