### ISSUE TITLE
Can't Refresh Instagram Home Page

### ISSUE THREAD

**Issue by john8862** [shadowsocks/shadowsocks-libev#2098]
### What version of shadowsocks-libev are you using?
3.2.0

### What operating system are you using?
Server: CentOS 7.4
Client: iOS 11.4 w/ Wingy V1.2(2) (Chinese version Wingy w/ purple bird icon)

### What did you do?
Force refresh Instagram home page

### What did you expect to see?
Refresh Instagram Feed

### What did you see instead?
Error message: Couldn't Refresh Feed
Tailed log in /var/log/message and didn't find any deny connection error
Could load user profile and picture normally
VPS firewall rule for port 5508 has been created and other programs can load the information correctly

### What is your config in detail (with all sensitive info masked)?
`{
    "server":"0.0.0.0",
    "server_port":5508,
    "password":"{Password_Marked}",
    "timeout":300,
    "user":"nobody",
    "method":"aes-256-cfb",
    "fast_open":true,
    "nameserver":"8.8.8.8",
    "mode":"tcp_and_udp"
}`

If didn't provide enough information please let me know. I'll try my best to find anything necessary. Thanks in advance.

**Comment by john8862** [comment]
VPS firewall rule for port 5508 has been created and other programs can load the information correctly.

**Comment by madeye** [comment]
It looks a client's problem.

Try the latest Outline on iOS.

**Comment by john8862** [comment]
@madeye Seems Outline client can only support access key to configure the server information. May I ask how to do it with SS-libev?

**Comment by madeye** [comment]
Ask the clients' developerw for help.

You can also try other versions of shadowsocks as your server.

go-shadowsocks2, shadowsocks-go, shadowsocks-python, and shadowsocks-rust.

**Comment by debiansid** [comment]
Try surge/shadowrocket
