### ISSUE TITLE
ss-redir is quite slow on openwrt trunk with 4.14.50

### ISSUE THREAD

**Issue by debiansid** [shadowsocks/shadowsocks-libev#2099]
### What version of shadowsocks-libev are you using?
3.2.0

### What operating system are you using?
ss-sever debian 9
ss-redir openwrt trunk with 4.15.50 

### What did you do?
Install 3.2.0 from back ports 

### What did you expect to see?
normal speed on ss-redir 

### What did you see instead?
Only around 8000 kbps from youtube

### What is your config in detail (with all sensitive info masked)?
ss-redir is very slow on lan client of openwrt  or openwrt itself.but it is normal for another linux box which is not through openwrt's ss-redir to same VPS.

**Comment by jibon57** [comment]
You can follow this: https://askubuntu.com/a/428778

**Comment by debiansid** [comment]
http://http.us.debian.org/debian/pool/main/s/shadowsocks-libev/

**Comment by debiansid** [comment]
I found it is interesting that iptables could effect speed of ss-redir on openwrt. 
https://github.com/shadowsocks/shadowsocks-libev#transparent-proxy
I followed here , it is quite slow on openwrt 4.14.50.

**Comment by manjuprajna** [comment]
@debiansid 
 root@Linksys:~# uname -r
4.14.50
 cat /etc/openwrt_release
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='18.06-SNAPSHOT'
DISTRIB_REVISION='r7058-2af5cfe'
DISTRIB_TARGET='mvebu/cortexa9'
DISTRIB_ARCH='arm_cortex-a9_vfpv3'
DISTRIB_DESCRIPTION='OpenWrt 18.06-SNAPSHOT r7058-2af5cfe'
DISTRIB_TAINTS='no-all'

<a href="https://imgchr.com/i/CzI92D"><img src="https://s1.ax1x.com/2018/06/20/CzI92D.png" alt="CzI92D.png" border="0" /></a>

**Comment by manjuprajna** [comment]
@debiansid top speed 96Mbps, average around 75Mbps. nothing unusual.

**Comment by debiansid** [comment]
what? Would u please paste your iptables which is handling transparent proxy？  thanks

**Comment by debiansid** [comment]
```
 cat /etc/openwrt_release 
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='SNAPSHOT'
DISTRIB_REVISION='r7275-512c57e7f3'
DISTRIB_TARGET='x86/64'
DISTRIB_ARCH='x86_64'
DISTRIB_DESCRIPTION='OpenWrt SNAPSHOT r7275-512c57e7f3'
DISTRIB_TAINTS='no-all'
```
Mine is x86-64

**Comment by manjuprajna** [comment]
@debiansid turn on flow offload and try again.

**Comment by debiansid** [comment]
There is no flow offload for x86-64 here under firewall.

**Comment by debiansid** [comment]
`Intel(R) Core(TM)2 Duo CPU U7600 @ 1.20GHz`
is my cpu too slow for ss-redir?

**Comment by debiansid** [comment]
from linux box behind openwrt with/without local ss-redir running on linux box itself.
```
wget http://mirror.sfo12.us.leaseweb.net/archlinux/iso/2018.06.01/archlinux-2018.06.01-x86_64.iso
--2018-06-21 19:15:01--  http://mirror.sfo12.us.leaseweb.net/archlinux/iso/2018.06.01/archlinux-2018.06.01-x86_64.iso
Resolving mirror.sfo12.us.leaseweb.net (mirror.sfo12.us.leaseweb.net)... 209.58.135.187, 2605:fe80:2100:b001::5187
Connecting to mirror.sfo12.us.leaseweb.net (mirror.sfo12.us.leaseweb.net)|209.58.135.187|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 598736896 (571M) [application/octet-stream]
Saving to: ‘archlinux-2018.06.01-x86_64.iso’

archlinux-2018.06.01-x86_64   9%[===>                                       ]  54.01M   878KB/s    eta 10m 22s

```
```
 wget http://mirror.sfo12.us.leaseweb.net/archlinux/iso/2018.06.01/archlinux-2018.06.01-x86_64.iso
--2018-06-21 19:17:57--  http://mirror.sfo12.us.leaseweb.net/archlinux/iso/2018.06.01/archlinux-2018.06.01-x86_64.iso
Resolving mirror.sfo12.us.leaseweb.net (mirror.sfo12.us.leaseweb.net)... 209.58.135.187, 2605:fe80:2100:b001::5187
Connecting to mirror.sfo12.us.leaseweb.net (mirror.sfo12.us.leaseweb.net)|209.58.135.187|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 598736896 (571M) [application/octet-stream]
Saving to: ‘archlinux-2018.06.01-x86_64.iso’

archlinux-2018.06.01-x86_64   6%[=>                                         ]  36.66M  4.95MB/s    eta 1m 56s


```

**Comment by debiansid** [comment]
@manjuprajna 
option flow_offloading '1'
I enabled it , but speed is still slow.

**Comment by madeye** [comment]
If you look into the commit history of ss-redir, there is no change to the network part from 3.1.3.

https://github.com/shadowsocks/shadowsocks-libev/commits/master/src/redir.c

So, your problem should have nothing to do with ss-redir.

**Comment by madeye** [comment]
To avoid misleading other users, closing the issue.

**Comment by debiansid** [comment]
I tried 3.1.2/3.1.3 on client side, but there is no way to rollback ss-server back to 3.1.3.

Now I am trying to compiling openwrt cc 15.05 with 3.2.0. 

Let’s see what will happen.

**Comment by madeye** [comment]
We didn't touch ss-server's network part either.

https://github.com/shadowsocks/shadowsocks-libev/commits/master/src/server.c

**Comment by debiansid** [comment]
I found the root cause
```
curl -o /dev/null  http://mirror.sfo12.us.leaseweb.net/archlinux/iso/2018.06.01/archlinux-2018.06.01-x86_64.iso
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  571M  100  571M    0     0  15.7M      0  0:00:36  0:00:36 --:--:-- 16.1M
```
