### ISSUE TITLE
Invalid argument

### ISSUE THREAD

**Issue by mcmxciv** [shadowsocks/shadowsocks-libev#2101]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?

3.2.0
### What operating system are you using?

CentOS 7
### What did you do?
启动systemctl status shadowsocks -l
[root@]# systemctl status shadowsocks -l
● shadowsocks.service - Shadowsocks.service
   Loaded: loaded (/etc/systemd/system/shadowsocks.service; enabled; vendor preset: disabled)
   Active: active (running) since Fri 2018-06-22 05:28:34 UTC; 10s ago
 Main PID: 1555 (ss-server)
   CGroup: /system.slice/shadowsocks.service
           └─1555 /root/shadowsocks-libev/src/ss-server -c /usr/local/bin/config.json -u /dev/null 2>&1

Jun 22 05:28:34  systemd[1]: Starting Shadowsocks.service...
Jun 22 05:28:34  ss-server[1555]: 2018-06-22 05:28:34 INFO: UDP relay enabled
Jun 22 05:28:34  ss-server[1555]: 2018-06-22 05:28:34 INFO: initializing ciphers... aes-256-cfb
Jun 22 05:28:34  ss-server[1555]: 2018-06-22 05:28:34 INFO: This system doesn't provide enough entropy to quickly generate high-quality random numbers.
Jun 22 05:28:34  ss-server[1555]: Installing the rng-utils/rng-tools, jitterentropy or haveged packages may help.
Jun 22 05:28:34  ss-server[1555]: On virtualized Linux environments, also consider using virtio-rng.
Jun 22 05:28:34  ss-server[1555]: The service will not start until enough entropy has been collected.
Jun 22 05:28:34  ss-server[1555]: 2018-06-22 05:28:34 INFO: tcp server listening at 0.0.0.0:443
Jun 22 05:28:34  ss-server[1555]: 2018-06-22 05:28:34 INFO: udp server listening at 0.0.0.0:443
Jun 22 05:28:34  ss-server[1555]: 2018-06-22 05:28:34 INFO: running from root user

随后安装rng-tools
[root@]# yum install -y rng-tools

Installed:
  rng-tools.x86_64 0:5-13.el7                                                   

Complete!
[root@]# systemctl daemon-reload
[root@]# systemctl enable shadowsocks
[root@]# systemctl start shadowsocks
[root@]# systemctl status shadowsocks -l
● shadowsocks.service - Shadowsocks.service
   Loaded: loaded (/etc/systemd/system/shadowsocks.service; enabled; vendor preset: disabled)
   Active: active (running) since Fri 2018-06-22 05:28:34 UTC; 13min ago
 Main PID: 1555 (ss-server)
   CGroup: /system.slice/shadowsocks.service
           └─1555 /root/shadowsocks-libev/src/ss-server -c /usr/local/bin/config.json -u /dev/null 2>&1

Jun 22 05:41:16  ss-server[1555]: 2018-06-22 05:41:16 ERROR: connect: Invalid argument
Jun 22 05:41:17  ss-server[1555]: 2018-06-22 05:41:17 ERROR: connect: Invalid argument
Jun 22 05:41:18  ss-server[1555]: 2018-06-22 05:41:18 ERROR: connect: Invalid argument
Jun 22 05:41:18  ss-server[1555]: 2018-06-22 05:41:18 ERROR: connect: Invalid argument
Jun 22 05:41:19  ss-server[1555]: 2018-06-22 05:41:19 ERROR: connect: Invalid argument
Jun 22 05:41:19  ss-server[1555]: 2018-06-22 05:41:19 ERROR: connect: Invalid argument
Jun 22 05:41:20  ss-server[1555]: 2018-06-22 05:41:20 ERROR: connect: Invalid argument
Jun 22 05:41:21  ss-server[1555]: 2018-06-22 05:41:21 ERROR: connect: Invalid argument
Jun 22 05:41:28  ss-server[1555]: 2018-06-22 05:41:28 ERROR: connect: Invalid argument
Jun 22 05:41:29  ss-server[1555]: 2018-06-22 05:41:29 ERROR: connect: Invalid argument
[root@]# 
仍旧提示有错误

config.json的配置

{
    "server":"0.0.0.0",
    "server_port":443,
    "local_address": "127.0.0.1",
    "local_port":1080,
    "password":"****",
    "timeout":600,
    "method":"aes-256-cfb"
}

 /etc/systemd/system/shadowsocks.service的配置

[Unit]
Description=Shadowsocks
After=network-online.target

[Service]
TimeoutStartSec=0
ExecStart= /root/shadowsocks-libev/src/ss-server -c /usr/local/bin/config.json -u /dev/null 2>&1

[Install]
WantedBy=multi-user.target
问题出在哪？

**Comment by mcmxciv** [comment]
另外，我是从源码编译的，编译过后发现没有在/usr/local/bin下生成ss-server，只有两处有这个文件
/root/shadowsocks-libev/completions/bash/ss-server
/root/shadowsocks-libev/src/ss-server

**Comment by madeye** [comment]
Remove `"local_address": "127.0.0.1",` from your config.

**Comment by mcmxciv** [comment]
问题解决，谢谢
