### ISSUE TITLE
如何使用docker-compose来设置多用户？

### ISSUE THREAD

**Issue by xgz123** [shadowsocks/shadowsocks-libev#2103]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
docker image latest

### What operating system are you using?
centos 7

### What did you do?
不知道如何下手。我知道如何使用json配置。
当然启动多个docker container也是可以的, 应该有更好的方案把

### What did you expect to see?
设置多用户的 docker-compose.yml 的例子；或者 在命令行设置多用户的方法也可以

### What did you see instead?
目前只设置了单用户。

### What is your config in detail (with all sensitive info masked)?
shadowsocks:
  image: shadowsocks/shadowsocks-libev
  ports:
    - "8388:8388"
  environment:
    - METHOD=aes-256-cfb
    - PASSWORD=9MLSpPmNt
  restart: always

**Comment by xgz123** [comment]
为啥close了。。。

**Comment by madeye** [comment]
Any question without follow-up response will be closed.
