### ISSUE TITLE
why ss didn't generate /etc/shadowsocks/config.json when i installed it though pacman

### ISSUE THREAD

**Issue by Creedowl** [shadowsocks/shadowsocks-libev#2104]
### What version of shadowsocks-libev are you using?
3.2.0-1 according to aur

### What operating system are you using?

manjaro
### What did you do?

i installed shadowsocks-libev and try to use systemctl to startup according to [aur](https://wiki.archlinux.org/index.php/Shadowsocks_(%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87)) but i failed to find shadowsocks.service and /etc/shadowsocks
### What did you expect to see?
shadowsocks.service

### What did you see instead?
nothing

**Comment by madeye** [comment]
Consult the downstream maintainer instead.

**Comment by Creedowl** [comment]
that's ok

**Comment by xclidongbo** [comment]
@Creedowl  How to solve it?

**Comment by Creedowl** [comment]
@xclidongbo sorry but I've totally forgot this issue, maybe you can turn to arch wiki for more information
