### ISSUE TITLE
如何避免服务器下载的文件所属用户被修改？

### ISSUE THREAD

**Issue by qianbinbin** [shadowsocks/shadowsocks-libev#2106]
### What version of shadowsocks-libev are you using?
shadowsocks-libev 3.2.0

### What operating system are you using?
CentOS 7 64位

### What did you do?
以shadowsocks用户运行ss-manager
```sh
# ps axu | grep ss-
shadows+ 28358  0.0  0.1  23324   296 ?        Ss   6月25   0:00 /usr/bin/ss-manager -c /etc/shadowsocks-libev/manager.json -u
shadows+ 28361  0.0  1.0  25196  2820 ?        Ss   6月25   0:16 ss-server --manager-address 127.0.0.1:8839 -f /var/lib/shadowsocks/.shadowsocks/.shadowsocks_44444.pid -c /var/lib/shadowsocks/.shadowsocks/.shadowsocks_44444.conf -t 60 -u -s 0.0.0.0
shadows+ 28364  0.0  0.9  25028  2464 ?        Ss   6月25   0:19 ss-server --manager-address 127.0.0.1:8839 -f /var/lib/shadowsocks/.shadowsocks/.shadowsocks_44445.pid -c /var/lib/shadowsocks/.shadowsocks/.shadowsocks_44445.conf -t 60 -u -s 0.0.0.0
```
以root用户登录服务器后，使用wget下载一个tar包，tar包是root用户的，但解压后的文件用户都是shadowsocks：
```sh
# ls -l
drwxr-xr-x 11 shadowsocks shadowsocks    4096 3月  22 2014 mldonkey-3.1.5
-rw-r--r--  1 root        root        2847382 3月  22 2014 mldonkey-3.1.5.tar.bz2
```

### What did you expect to see?
解压后的文件用户为root

### What did you see instead?
解压后的文件用户为shadowsocks

### What is your config in detail (with all sensitive info masked)?
```json
{
    "port_password":{
        "44444":"xxx",
        "44445":"yyy"
    },
    "timeout": 60,
    "method": "aes-256-cfb",
    "mode": "tcp_and_udp"
}
```

**Comment by studentmain** [comment]
手动chown一下就是了。或者你看看tar的说明书。

Binbin Qian <notifications@github.com> 于 2018年6月26日周二 02:50写道：

**Comment by qianbinbin** [comment]
这跟tar没关系啊，chown也不能从根本上解决问题。
问题是以root用户执行wget和tar后，得到的文件用户为shadowsocks。

**Comment by hosiet** [comment]
Tar archive stores uid information by default. You should examine your tar extraction command again and ensure that you are preserving it.

**Comment by madeye** [comment]
Please ask general Linux questions on https://stackoverflow.com/ instead.

**Comment by studentmain** [comment]
那是默认值，出于用户隔离的需要使用了一个独立的用户，自己按需chown改改就是

Binbin Qian <notifications@github.com> 于 2018年6月26日周二 10:23写道：

**Comment by qianbinbin** [comment]
找到原因了：
https://unix.stackexchange.com/questions/281591/change-user-id-and-group-id-ownership-of-files-within-a-tarball
> The person who created the tar file had an effective user ID and group ID (UID:GID) of 1001:1001. Since tar, by default, preserves the ownerships and permissions, when you expand it, you inherit these values. If you have a user with UID:GID 1001:1001 on your system, these files would have been owned by that user.

tar如果不指定--no-same-owner，解压默认得到的用户是打包时的用户。这个没有问题。
但是tar中的uid:gid如果在系统中存在，解压得到的就是这个用户。

现在这个包中的uid:gid与我自己建立的shadowsocks完全相同，于是撞车了。
