### ISSUE TITLE
cres failed to resolve hostnames in Tencent Cloud enviroment

### ISSUE THREAD

**Issue by march1993** [shadowsocks/shadowsocks-libev#2107]
The case happened when the server was running on a Tencent Cloud Shanghai region II machine.

The /etc/resolv.conf reads
```
nameserver 10.236.158.106
nameserver 10.236.158.114
options timeout:1 rotate
```

An interesting finding is that these two default servers won't send TCP connection rejection packet back. So I guess this would lead to a TCP timeout, i.e., failing to resolve the hostname.

**Comment by madeye** [comment]
1. Try the latest libc-ares.
2. Remove `rotate` from `/etc/resolv.conf`.

**Comment by march1993** [comment]
@madeye    Remove rotate does not help.     I'll try libc-ares and update here.

**Comment by madeye** [comment]
If still now work, please report to c-ares instead: https://github.com/c-ares/c-ares
