### ISSUE TITLE
ss-local Windows 10 timeout question and fast_open help

### ISSUE THREAD

**Issue by VirtualSmile** [shadowsocks/shadowsocks-libev#2110]
### What version of shadowsocks-libev are you using?
Ss-server and ss-local 3.2.0

### What operating system are you using?
Windows 10 x64 build 1803 (ss-local)
Debian 9 x64 latest (ss-server)

### What did you do?
Ran ss-server on Debian box. Ran ss-local from  "shadowsocks-libev-win" on GitHub and successfully connected. Routed game traffic through the socks proxy. 

### What did you expect to see?
The game traffic being forwarded normally.

### What did you see instead?
The game traffic tunnels being closed after set timeout in client config.

### What is your config in detail (with all sensitive info masked)?
Minimal config with fastopen, no delay and salsa20 as method. 

### Question here:
Is shadowsocks meant to kill the connection after the specified timeout? I had interpreted it as "timeout after X seconds if there is no longer any data coming through it". Especially since using the "shadowsocks-windows" client doesn't cause the connection to be killed after the specified timeout period. 

I can't get fastopen to work in windows 10, even on build 1709/1803. It says "operating system does not support it". I've disabled fallback and manually enabled fastopen. I have only tried with the "shadowsocks-libev-win" ss-local though, since I'm having troubles compiling with cygwin.

Thanks!

**Comment by madeye** [comment]
1. For timeout issue, try the latest commit.
2. I think you need to compile shadowsocks-libev from source code in MinGW to ensure fast-open is enabled. You may ask @linusyang for more details.

**Comment by linusyang** [comment]
@VirtualSmile Install docker, run `docker\mingw\make.bat` (Windows) or `make -C docker/mingw` (Unix-like).

**Comment by VirtualSmile** [comment]
@linusyang Unfortunately docker can't run on my Windows 10 Home edition. I will however try to compile it Unix-like! Just out of curiosity of wanting to build it from source (having ss-local/tunnel/redir/manager/server), is it possible to build it using mingw-w64 shell, msys2 and toolchain?

**Comment by linusyang** [comment]
@VirtualSmile You need to use Docker. This is the only officially supported MinGW compiling method. You can use Docker Toolbox if Docker for Windows is not supported. Or just use a Linux virtual machine with Docker. It is faster and more reliable.

It is highly not recommended to use emulated Unix environment on Windows (e.g. Cygwin=Msys2) to compile the sources. It is painfully slow.

**Comment by VirtualSmile** [comment]
@linusyang I see.. Thank you for the information. One final question. I'm fairly new to docker and don't understand it too well. If I wanted to pass SS to my friends to use, do they need to have docker installed as well? Or would it be compiled into .exe's that they can just run normally? 

Thank you!

**Comment by linusyang** [comment]
@VirtualSmile No. Docker is only needed for compilation. The generated binaries are fully portable, and support Windows Vista or above.

**Comment by VirtualSmile** [comment]
@linusyang That is absolutely amazing! I will do that now. Please mark this issue as closed and I'll do my best to work out any issues I have with docker! Thank you to both you and madeye ^^.

**Comment by VirtualSmile** [comment]
@linusyang I was able to get it compiled and running! However I have another issue. I'm trying to compile shadowsocks-libev-nocrypto using docker, but it isn't properly applying/allowing the "none" cipher. If I compile it for unix using make && make install the "none" cipher works fine. Is it because the docker make.bat/makefile isn't updated on that git project? 

I also tried adding his commits into crypto.c and stream.c and then running docker (after cloning shadowsocks-libev) but to no success. It will build, but it still doesn't support the "none" cipher. Do you know any way around this?

**Comment by linusyang** [comment]
@VirtualSmile It seems you removed your previous comment. Let me answer that question.

The MinGW docker script by default compiles the **master** branch of **default repo**. If you want to compile another branch, simply modify `docker/mingw/Makefile` (for Linux) or `docker\mingw\make.bat` (for Windows) and change the `REPO` and `REV` variables.

`REPO` stands for the Github repo that you want to clone, namely `https://github.com/REPO/shadowsocks-libev.git`. `REV` stands for the Git revision that you want to use, by default `master`.

**Comment by VirtualSmile** [comment]
Sorry guys, I'm not sure if I should create a new issue or follow up on this one. I'm encountering issues again, but this time it gives me an error code:
`remote recv_cb recv: [10054] An existing connection was forcibly closed by the remote host.`

After the specified timeout. I googled another issue but @madeye said it was normal. However, whenever this error pops up, my game gets disconnected like before. This seems to only be happening on one of my VPS's though. But my other VPS (Debian 9 x64, up to date, both by Microsoft Azure) doesn't encounter this issue. IPTables is reset/open to all and the firewall has allow all in bound and outbound rules. Do you know what could be causing this? 

Thanks!

**Comment by madeye** [comment]
It's a normal behavior.

Enlarge the timeout settings on your server and check with your ISP / VPS providers.

**Comment by VirtualSmile** [comment]
@madeye Thanks for the reply! Hmm.. if it's working with other VPS's I assume it's not on my ISP end. The provider is Microsoft Azure (Where the timeout is happening). I'll try enlarging the timeout settings and trying again! What exactly am I looking for/asking about when I talk to the VPS providers? The timeout of connections made by the VPS?

**Comment by madeye** [comment]
No idea.

It looks related to network connection, like a broken NAT device.

**Comment by VirtualSmile** [comment]
Hmm it seems the issue is only on my end (from my home). My friends use the setup perfectly fine with no errors popping up or disconnects. I've tried changing modems and even modem firmware (merlin/vortex, ddwrt, tomato). Seems like it has something to do with my ISP. Which is strange because a few of my friends are on the same ISP and live barely 2 minutes away. Thank you and I'll try to keep this updated if I fix the problem!
