### ISSUE TITLE
build resource run autogen.sh error?

### ISSUE THREAD

**Issue by syzh** [shadowsocks/shadowsocks-libev#2111]
[root@localhost shadowsocks-libev]# ./autogen.sh
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, `auto'.
libtoolize: copying file `auto/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: copying file `m4/libtool.m4'
libtoolize: copying file `m4/ltoptions.m4'
libtoolize: copying file `m4/ltsugar.m4'
libtoolize: copying file `m4/ltversion.m4'
libtoolize: copying file `m4/lt~obsolete.m4'
configure.ac:244: error: required file 'libbloom/Makefile.in' not found
configure.ac:244: error: required file 'libcork/Makefile.in' not found
configure.ac:244: error: required file 'libipset/Makefile.in' not found
autoreconf: automake failed with exit status: 1

system: Linux localhost.localdomain 4.4.6 #1 Thu Jun 14 22:48:18 EDT 2018 x86_64 x86_64 x86_64 GNU/Linux
why?

**Comment by VergeDX** [comment]
Just do `git submodule update --init --recursive`
