### ISSUE TITLE
WARNING at net/ipv4/inet_hashtables.c:602 in ss-server

### ISSUE THREAD

**Issue by knxhm** [shadowsocks/shadowsocks-libev#2112]
Topology:
many clients -> wifi -> linux router Debian 8/kernel 4.9.87/MPTCP/shadowsocks -> 3 parallel wireless WAN links (using MPTCP) -> linux router Debian 9/kernel 4.9.87/MPTCP/shadowsocks -> internet connection -> server in internet

What version of shadowsocks-libev are you using?
shadowsocks-libev 2.6.3+ds-3+deb9u1 with mbed TLS 2.4.2

What operating system are you using?
Debian 8/9 + kernel 4.9.87 + MPTCP

What did you do?
clients generate TCP traffic through proxy

What did you expect to see?

What did you see instead?
WARNING + stack dump in kernel log, see below

What is your config in detail (with all sensitive info masked)?

ss-redir
{
"server" : ["serverip"],
"server_port" : xxx,
"local_address" : "0.0.0.0",
"local_port" : 1080,
"password" : "xxxxxxxxxxxxxx",
"timeout" : 300,
"method" : "aes-256-cfb",
"fast_open" : true,
}

ss-server
{
"server":"0.0.0.0",
"server_port":xxxx,
"local_address": "0.0.0.0",
"local_port":1203,
"password":"xxxxxxxxxxxxxx",
"timeout":300,
"method":"aes-256-cfb",
"fast_open": true
}

[Mon Jul  2 21:08:36 2018] WARNING: CPU: 3 PID: 596 at net/ipv4/inet_hashtables.c:602 __inet_hash_connect+0x904/0xac0
[Mon Jul  2 21:08:36 2018] Modules linked in: xt_multiport iptable_filter nf_conntrack_ipv4 nf_defrag_ipv4 nf_conntrack sb_edac edac_core coretemp crct10dif_pclmul crc32_pclmul ghash_clmulni_intel aesni_intel aes_x86_64 lrw gf128mul snd_pcm glue_helper snd_timer snd soundcore pcspkr serio_raw evdev vmw_balloon ablk_helper cryptd sg shpchp vmwgfx ttm drm_kms_helper drm tpm_tis tpm_tis_core ac tpm button vmw_vsock_vmci_transport vsock vmw_vmci mptcp_balia ip_tables x_tables autofs4 ext4 crc16 jbd2 mbcache sr_mod cdrom sd_mod ata_generic crc32c_intel ata_piix vmw_pvscsi libata psmouse vmxnet3 scsi_mod i2c_piix4 floppy
[Mon Jul  2 21:08:36 2018] CPU: 3 PID: 596 Comm: ss-server Not tainted 4.9.87+ #2
[Mon Jul  2 21:08:36 2018] Hardware name: VMware, Inc. VMware Virtual Platform/440BX Desktop Reference Platform, BIOS 6.00 09/21/2015
[Mon Jul  2 21:08:36 2018]  0000000000000000 ffffffff81878b83 0000000000000000 0000000000000000
[Mon Jul  2 21:08:36 2018]  ffffffff8113e378 1ffff1000000025a ffff8801bbf39480 dffffc0000000000
[Mon Jul  2 21:08:36 2018]  ffffc90000dc11f0 ffffffff8296b9c0 0000000000005f38 ffffffff834a99c0
[Mon Jul  2 21:08:36 2018] Call Trace:
[Mon Jul  2 21:08:36 2018]  [<ffffffff81878b83>] ? dump_stack+0x5c/0x79
[Mon Jul  2 21:08:36 2018]  [<ffffffff8113e378>] ? __warn+0x168/0x1a0
[Mon Jul  2 21:08:36 2018]  [<ffffffff81eb4354>] ? __inet_hash_connect+0x904/0xac0
[Mon Jul  2 21:08:36 2018]  [<ffffffff81eafa70>] ? inet_unhash+0x500/0x500
[Mon Jul  2 21:08:36 2018]  [<ffffffff81eb3a50>] ? inet_hash+0x90/0x90
[Mon Jul  2 21:08:36 2018]  [<ffffffff81d9cb60>] ? secure_ipv6_port_ephemeral+0x3b0/0x3b0
[Mon Jul  2 21:08:36 2018]  [<ffffffff81e7d430>] ? ip_rt_update_pmtu+0x960/0x960
[Mon Jul  2 21:08:36 2018]  [<ffffffff814fab42>] ? save_stack+0x32/0xb0
[Mon Jul  2 21:08:36 2018]  [<ffffffff814fab42>] ? save_stack+0x32/0xb0
[Mon Jul  2 21:08:36 2018]  [<ffffffff81f2f30f>] ? tcp_v4_connect+0xa4f/0x1e00
[Mon Jul  2 21:08:36 2018]  [<ffffffff814f0000>] ? run_store+0x40/0x6f0
[Mon Jul  2 21:08:36 2018]  [<ffffffff814f5000>] ? rmap_walk_ksm+0x4d0/0x570
[Mon Jul  2 21:08:36 2018]  [<ffffffff814fab42>] ? save_stack+0x32/0xb0
[Mon Jul  2 21:08:36 2018]  [<ffffffff814fab42>] ? save_stack+0x32/0xb0
[Mon Jul  2 21:08:36 2018]  [<ffffffff81f87929>] ? __inet_stream_connect+0x239/0xb40
[Mon Jul  2 21:08:36 2018]  [<ffffffff814fab42>] ? save_stack+0x32/0xb0
[Mon Jul  2 21:08:36 2018]  [<ffffffff814fab42>] ? save_stack+0x32/0xb0
[Mon Jul  2 21:08:36 2018]  [<ffffffff814fab42>] ? save_stack+0x32/0xb0
[Mon Jul  2 21:08:36 2018]  [<ffffffff814fab42>] ? save_stack+0x32/0xb0
[Mon Jul  2 21:08:36 2018]  [<ffffffff814fab42>] ? save_stack+0x32/0xb0
[Mon Jul  2 21:08:36 2018]  [<ffffffff814fab42>] ? save_stack+0x32/0xb0
[Mon Jul  2 21:08:36 2018]  [<ffffffff814fab42>] ? save_stack+0x32/0xb0
[Mon Jul  2 21:08:36 2018]  [<ffffffff814fab42>] ? save_stack+0x32/0xb0
[Mon Jul  2 21:08:36 2018]  [<ffffffff81f876f0>] ? inet_bind+0x7d0/0x7d0
[Mon Jul  2 21:08:36 2018]  [<ffffffff814f7d9e>] ? kmem_cache_alloc_trace+0xbe/0x4d0
[Mon Jul  2 21:08:36 2018]  [<ffffffff81ed196d>] ? tcp_sendmsg+0x13ed/0x3930
[Mon Jul  2 21:08:36 2018]  [<ffffffff814fab42>] ? save_stack+0x32/0xb0
[Mon Jul  2 21:08:36 2018]  [<ffffffff814fab42>] ? save_stack+0x32/0xb0
[Mon Jul  2 21:08:36 2018]  [<ffffffff814fab42>] ? save_stack+0x32/0xb0
[Mon Jul  2 21:08:36 2018]  [<ffffffff814fab42>] ? save_stack+0x32/0xb0
[Mon Jul  2 21:08:36 2018]  [<ffffffff814fab42>] ? save_stack+0x32/0xb0
[Mon Jul  2 21:08:36 2018]  [<ffffffff814fab42>] ? save_stack+0x32/0xb0
[Mon Jul  2 21:08:36 2018]  [<ffffffff814fab42>] ? save_stack+0x32/0xb0
[Mon Jul  2 21:08:36 2018]  [<ffffffff814fab42>] ? save_stack+0x32/0xb0
[Mon Jul  2 21:08:36 2018]  [<ffffffff814fab42>] ? save_stack+0x32/0xb0
[Mon Jul  2 21:08:36 2018]  [<ffffffff814fab42>] ? save_stack+0x32/0xb0
[Mon Jul  2 21:08:36 2018]  [<ffffffff814fab42>] ? save_stack+0x32/0xb0
[Mon Jul  2 21:08:36 2018]  [<ffffffff814fab42>] ? save_stack+0x32/0xb0
[Mon Jul  2 21:08:36 2018]  [<ffffffff814fab42>] ? save_stack+0x32/0xb0
[Mon Jul  2 21:08:36 2018]  [<ffffffff814fab42>] ? save_stack+0x32/0xb0
[Mon Jul  2 21:08:36 2018]  [<ffffffff814fab42>] ? save_stack+0x32/0xb0
[Mon Jul  2 21:08:36 2018]  [<ffffffff814fab42>] ? save_stack+0x32/0xb0
[Mon Jul  2 21:08:36 2018]  [<ffffffff814fab42>] ? save_stack+0x32/0xb0
[Mon Jul  2 21:08:36 2018]  [<ffffffff814fab42>] ? save_stack+0x32/0xb0
[Mon Jul  2 21:08:36 2018]  [<ffffffff814fab42>] ? save_stack+0x32/0xb0
[Mon Jul  2 21:08:36 2018]  [<ffffffff81ed0580>] ? tcp_sendpage+0x1d30/0x1d30
[Mon Jul  2 21:08:36 2018]  [<ffffffff814fab42>] ? save_stack+0x32/0xb0
[Mon Jul  2 21:08:36 2018]  [<ffffffff814fab42>] ? save_stack+0x32/0xb0
[Mon Jul  2 21:08:36 2018]  [<ffffffff814fab42>] ? save_stack+0x32/0xb0
[Mon Jul  2 21:08:36 2018]  [<ffffffff814fab42>] ? save_stack+0x32/0xb0
[Mon Jul  2 21:08:36 2018]  [<ffffffff814fab42>] ? save_stack+0x32/0xb0
[Mon Jul  2 21:08:36 2018]  [<ffffffff814fab42>] ? save_stack+0x32/0xb0
[Mon Jul  2 21:08:36 2018]  [<ffffffff814fab42>] ? save_stack+0x32/0xb0
[Mon Jul  2 21:08:36 2018]  [<ffffffff814fab42>] ? save_stack+0x32/0xb0
[Mon Jul  2 21:08:36 2018]  [<ffffffff814fab42>] ? save_stack+0x32/0xb0
[Mon Jul  2 21:08:36 2018]  [<ffffffff814fab42>] ? save_stack+0x32/0xb0
[Mon Jul  2 21:08:36 2018]  [<ffffffff814fab42>] ? save_stack+0x32/0xb0
[Mon Jul  2 21:08:36 2018]  [<ffffffff814fab42>] ? save_stack+0x32/0xb0
[Mon Jul  2 21:08:36 2018]  [<ffffffff814fab42>] ? save_stack+0x32/0xb0
[Mon Jul  2 21:08:36 2018]  [<ffffffff814fab42>] ? save_stack+0x32/0xb0
[Mon Jul  2 21:08:36 2018]  [<ffffffff814fab42>] ? save_stack+0x32/0xb0
[Mon Jul  2 21:08:36 2018]  [<ffffffff814fab42>] ? save_stack+0x32/0xb0
[Mon Jul  2 21:08:36 2018]  [<ffffffff814fab42>] ? save_stack+0x32/0xb0
[Mon Jul  2 21:08:36 2018]  [<ffffffff814fab42>] ? save_stack+0x32/0xb0
[Mon Jul  2 21:08:36 2018]  [<ffffffff814fab42>] ? save_stack+0x32/0xb0
[Mon Jul  2 21:08:36 2018]  [<ffffffff814fab42>] ? save_stack+0x32/0xb0
[Mon Jul  2 21:08:36 2018]  [<ffffffff814fab42>] ? save_stack+0x32/0xb0
[Mon Jul  2 21:08:36 2018]  [<ffffffff814fab42>] ? save_stack+0x32/0xb0
[Mon Jul  2 21:08:36 2018]  [<ffffffff814fab42>] ? save_stack+0x32/0xb0
[Mon Jul  2 21:08:36 2018]  [<ffffffff814fab42>] ? save_stack+0x32/0xb0
[Mon Jul  2 21:08:36 2018]  [<ffffffff814fab42>] ? save_stack+0x32/0xb0
[Mon Jul  2 21:08:36 2018]  [<ffffffff814fab42>] ? save_stack+0x32/0xb0
[Mon Jul  2 21:08:36 2018]  [<ffffffff814fab42>] ? save_stack+0x32/0xb0
[Mon Jul  2 21:08:36 2018]  [<ffffffff814fab42>] ? save_stack+0x32/0xb0
[Mon Jul  2 21:08:36 2018]  [<ffffffff814fab42>] ? save_stack+0x32/0xb0
[Mon Jul  2 21:08:36 2018]  [<ffffffff814fab42>] ? save_stack+0x32/0xb0
[Mon Jul  2 21:08:36 2018]  [<ffffffff814fab42>] ? save_stack+0x32/0xb0
[Mon Jul  2 21:08:36 2018]  [<ffffffff814fab42>] ? save_stack+0x32/0xb0
[Mon Jul  2 21:08:36 2018]  [<ffffffff814fab42>] ? save_stack+0x32/0xb0
[Mon Jul  2 21:08:36 2018]  [<ffffffff81f8ef40>] ? inet_recvmsg+0x360/0x360
[Mon Jul  2 21:08:36 2018]  [<ffffffff81d593c3>] ? sock_sendmsg+0xb3/0xf0
[Mon Jul  2 21:08:36 2018]  [<ffffffff81d5a057>] ? SYSC_sendto+0x257/0x2b0
[Mon Jul  2 21:08:36 2018]  [<ffffffff81d59e00>] ? SYSC_connect+0x280/0x280
[Mon Jul  2 21:08:36 2018]  [<ffffffff81ec89e3>] ? do_tcp_setsockopt.isra.41+0x583/0x1f30
[Mon Jul  2 21:08:36 2018]  [<ffffffff8153a592>] ? alloc_file+0x22/0x370
[Mon Jul  2 21:08:36 2018]  [<ffffffff8158b55c>] ? __fd_install+0x6c/0x2d0
[Mon Jul  2 21:08:36 2018]  [<ffffffff81d53a50>] ? sock_splice_read+0x130/0x130
[Mon Jul  2 21:08:36 2018]  [<ffffffff8156a570>] ? SyS_fcntl+0x5c0/0xae0
[Mon Jul  2 21:08:36 2018]  [<ffffffff81d5b4d3>] ? SyS_socket+0xe3/0x180
[Mon Jul  2 21:08:36 2018]  [<ffffffff81bb96f0>] ? rand_initialize_disk+0xc0/0xc0
[Mon Jul  2 21:08:36 2018]  [<ffffffff81569fb0>] ? f_getown+0xa0/0xa0
[Mon Jul  2 21:08:36 2018]  [<ffffffff81d5bc10>] ? SyS_getpeername+0x10/0x10
[Mon Jul  2 21:08:36 2018]  [<ffffffff81006eb1>] ? do_syscall_64+0x191/0x3a0
[Mon Jul  2 21:08:36 2018]  [<ffffffff810048c8>] ? exit_to_usermode_loop+0xa8/0x100
[Mon Jul  2 21:08:36 2018]  [<ffffffff821e1fce>] ? entry_SYSCALL_64_after_swapgs+0x58/0xc6
[Mon Jul  2 21:08:36 2018] ---[ end trace 15812a7c647272fd ]---
[

**Comment by madeye** [comment]
It's typically a kernel issue, caused by either misconfiguration or kernel bug.

**Comment by madeye** [comment]
I mean misconfiguration of kernel parameters.

As I mentioned above, you should report a kernel crash to kernel maintainer instead of to the application developer.
