### ISSUE TITLE
Make shadowsocks like a vpn for all through pfsense

### ISSUE THREAD

**Issue by SoGooDFR** [shadowsocks/shadowsocks-libev#2114]
Hi,
I've actually a VPS with Shadowsock (ss-server). In my home, i use shadowsocks-windows. Prettier work !
Now i would like to install shadowsocks localy on a dedicated server to work as a proxy with my pfsense.

Example : Me --> pfSense (rules tcp/udp redirect to shadowsocks client) --> SSH Tun --------> VPS --> Yeah !

### What version of shadowsocks-libev are you using?
> shadowsocks-libev 2.6.3 with mbed TLS 2.4.2

### What operating system are you using?
> Debian 9 server

### What did you do?
Install shadowsock on my debian, edit the default config and launch : 
> ss-redir -c /etc/shadowsocks-libev/config.json -u -v

### What did you expect to see?
Pass my request and load my internet page :)

### What did you see instead?
Timeout and my browser

### What is your config in detail (with all sensitive info masked)?
```
{
    "server":"X.X.X.X",
    "server_port":8388,
    "local_address":"0.0.0.0",
    "local_port":1080,
    "password":"XXXXX",
    "timeout":600,
    "method":"aes-128-cfb"
}
```

**Comment by madeye** [comment]
Follow https://github.com/shadowsocks/shadowsocks-libev#transparent-proxy

**Comment by SoGooDFR** [comment]
Thx for the answer, but in windows network settings, i set the sock proxy to my ss-redir machine (192.168.1.xx:1080) and all my requests return timeout in my browser.

This is the ss-redir logs : 

> shadowsocks systemd[1]: Started Shadowsocks-libev Default Server Service.
> shadowsocks ss-redir[980]:  2018-07-06 14:38:43 INFO: initializing ciphers... aes-128-cfb
> shadowsocks ss-redir[980]:  2018-07-06 14:38:43 INFO: tcp port reuse enabled
> shadowsocks ss-redir[980]:  2018-07-06 14:38:43 INFO: UDP relay enabled
> shadowsocks ss-redir[980]:  2018-07-06 14:38:43 INFO: udp port reuse enabled
> shadowsocks ss-redir[980]:  2018-07-06 14:38:43 INFO: listening at 0.0.0.0:1080
> shadowsocks ss-redir[980]:  2018-07-06 14:38:43 INFO: running from root user
> shadowsocks ss-redir[980]:  2018-07-06 14:39:20 INFO: redir to 192.168.1.XX:1080, len=267, recv=267
> shadowsocks ss-redir[980]:  2018-07-06 14:39:24 INFO: redir to 192.168.1.XX:1080, len=240, recv=240
> shadowsocks ss-redir[980]:  2018-07-06 14:39:24 INFO: redir to 192.168.1.XX:1080, len=240, recv=240
> shadowsocks ss-redir[980]:  2018-07-06 14:39:24 INFO: redir to 192.168.1.XX:1080, len=254, recv=254
> shadowsocks ss-redir[980]:  2018-07-06 14:39:24 INFO: redir to 192.168.1.XX:1080, len=254, recv=254
> shadowsocks ss-redir[980]:  2018-07-06 14:39:24 INFO: redir to 192.168.1.XX:1080, len=254, recv=254
> shadowsocks ss-redir[980]:  2018-07-06 14:39:24 INFO: redir to 192.168.1.XX:1080, len=254, recv=254
> shadowsocks ss-redir[980]:  2018-07-06 14:39:24 INFO: redir to 192.168.1.XX:1080, len=254, recv=254
> shadowsocks ss-redir[980]:  2018-07-06 14:39:24 INFO: redir to 192.168.1.XX:1080, len=254, recv=254
> shadowsocks ss-redir[980]:  2018-07-06 14:39:24 INFO: redir to 192.168.1.XX:1080, len=272, recv=272
> shadowsocks ss-redir[980]:  2018-07-06 14:39:24 INFO: redir to 192.168.1.XX:1080, len=272, recv=272
> shadowsocks ss-redir[980]:  2018-07-06 14:39:24 INFO: redir to 192.168.1.XX:1080, len=272, recv=272
> shadowsocks ss-redir[980]:  2018-07-06 14:39:24 INFO: redir to 192.168.1.XX:1080, len=272, recv=272
> shadowsocks ss-redir[980]:  2018-07-06 14:39:24 INFO: redir to 192.168.1.XX:1080, len=272, recv=272

**Comment by madeye** [comment]
Please make sure you understand what is transparent proxy first.

ss-redir provides a transparent proxy, not a socks5 proxy.
