### ISSUE TITLE
Cannot connect when using 80 port in mobile network(only) mode

### ISSUE THREAD

**Issue by oklnk** [shadowsocks/shadowsocks-libev#2117]
Cannot connect when using 80 port in mobile network(only) mode
But using other port like 8080 works, can connect server without problems
And if using wifi, 80 port can also work without problems
Not sure if this problem happens to every mobile in every ISP.
Looks to me new mobiles will be more likely to have this issue.
Hopefully, this issue can be fixed in SS server side

### What version of shadowsocks-libev are you using?
3.1.3

### What operating system are you using?
Client: Android 8.1 with shadowsocks-android 4.5.7
Server: CentOS 7

### What did you do?
Setup a SS server with ss-libev using 80 port
Turn on Android mobile network(roaming, cellular)
Turn off Android mobile WIFI
Connect the server with the android client shadowsocks-android 4.5.7

### What did you expect to see?
Connect to SS server successfully

### What did you see instead?
Cannot connect to SS server, connecting timeout

### What is your config in detail (with all sensitive info masked)?
Port: 80
Method: chacha20-ietf-poly1305
Fast open: false
Mode: tcp_and_udp

**Comment by madeye** [comment]
It probably means there is a revserse proxy on your local network, or on your server provides.

**Comment by madeye** [comment]
And I cannot reproduce your problem locally.
