### ISSUE TITLE
PPA支持Ubuntu18.04

### ISSUE THREAD

**Issue by fanck0605** [shadowsocks/shadowsocks-libev#2119]
Ubuntu18.04已经是最新稳定版本，PPA中预编译的Shadowsocks能否支持一下呢。

**Comment by madeye** [comment]
You can install shadowsocks-libev from official repo in Ubuntu 18.04

**Comment by fanck0605** [comment]
Ubuntu官方的源不会经常更新，现在已经落后一个版本，过段时间就落后不止一个版本了

**Comment by fanck0605** [comment]
经测试ubuntu18.04用ubuntu16.04的源可以正常使用。
但是由于该预编译的版本默认用的是SysVinit的脚本来自启动，然而ubuntu18.04貌似已经把这个移除了，所以默认配置在18.04上不能成功自启动。只能手动用systemd开启自启动。

鉴于ubuntu16.04也已经支持了systemd，建议默认的自启动方式使用systemd。

**Comment by xcjiang** [comment]
官方的源还是3.1，落后了一个大版本
