### ISSUE TITLE
many DNS failures from ss-server under higher load.

### ISSUE THREAD

**Issue by knxhm** [shadowsocks/shadowsocks-libev#2123]
Topology:
many clients -> wifi -> linux router Debian 8/kernel 4.9.87/MPTCP/shadowsocks -> 3 parallel wireless WAN links (using MPTCP) -> linux router Debian 9/kernel 4.9.87/MPTCP/shadowsocks -> internet connection -> server in internet

What version of shadowsocks-libev are you using?
shadowsocks-libev  3.2.0 from git

What operating system are you using?
Debian 8/9 + kernel 4.9.87 + MPTCP

What did you do?
clients generate TCP traffic through proxy

What did you expect to see?

What did you see instead?

many DNS failures from ss-server under higher load.
Example:
Jul 11 10:51:03 ts03 ss-server[13742]:  2018-07-11 10:51:03 ERROR: unable to resolve ssl.connextra.com
But the query was resolved, see it in packet trace

What is your config in detail (with all sensitive info masked)?

root@ts03:/home/nsn# systemctl status sockst03-2
● sockst03-2.service - Shadowsocks-libev Default Server Service
   Loaded: loaded (/etc/systemd/system/sockst03-2.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2018-07-10 23:23:59 CEST; 10h ago
     Docs: man:shadowsocks-libev(8)
 Main PID: 13742 (ss-server)
   CGroup: /system.slice/sockst03-2.service
           └─13742 /usr/bin/ss-server -d 8.8.8.8 -c /etc/shadowsocks-libev/sockst03-2.json

ss-redir
{
"server" : ["serverip"],
"server_port" : xxx,
"local_address" : "0.0.0.0",
"local_port" : 1080,
"password" : "xxxxxxxxxxxxxx",
"timeout" : 300,
"method" : "aes-256-cfb",
"fast_open" : true,
}

ss-server
{
"server":"0.0.0.0",
"server_port":xxxx,
"local_address": "0.0.0.0",
"local_port":1203,
"password":"xxxxxxxxxxxxxx",
"timeout":300,
"method":"aes-256-cfb",
"fast_open": true
}

High Limits are set.
root@ts03:/home/nsn# cat /proc/13
13/    13597/ 13742/ 13766/ 138/
root@ts03:/home/nsn# cat /proc/13742/limits
Limit                     Soft Limit           Hard Limit           Units
Max cpu time              unlimited            unlimited            seconds
Max file size             unlimited            unlimited            bytes
Max data size             unlimited            unlimited            bytes
Max stack size            8388608              unlimited            bytes
Max core file size        0                    unlimited            bytes
Max resident set          unlimited            unlimited            bytes
Max processes             99999                99999                processes
Max open files            99999                99999                files
Max locked memory         65536                65536                bytes
Max address space         unlimited            unlimited            bytes
Max file locks            unlimited            unlimited            locks
Max pending signals       13827                13827                signals
Max msgqueue size         819200               819200               bytes
Max nice priority         0                    0
Max realtime priority     0                    0
Max realtime timeout      unlimited            unlimited            us

root@ts03:/home/nsn# cat /proc/sys/fs/file-nr
2272    0       99999

I see this DNS errors only under high load, like 20 or more parallel users. I observed the "advanced" hints. When only few users are using the ss-server, the log is quiet.
Attached is part of log and parallel TCPdump filtering for DNS.
What reason it could be that I got so many DNS errors? Is this indicating that some connections may be lost ? Is there still some overload maybe ?

[ss-server4.log](https://github.com/shadowsocks/shadowsocks-libev/files/2184613/ss-server4.log)

[dns4.pcap.zip](https://github.com/shadowsocks/shadowsocks-libev/files/2184614/dns4.pcap.zip)

**Comment by madeye** [comment]
1. Remove `"local_address": "0.0.0.0",` from your config.
2. Update your c-ares library to the latest.
3. Try setup a local DNS resolver, e.g. bind9.

**Comment by knxhm** [comment]
Thanks. Will try that.

**Comment by knxhm** [comment]
deleting "local_address": "0.0.0.0" did not help.
c-ares is already the latest 1.14.0
local DNS resolver did not try yet, will still take me a few days. But the response time of 8.8.8.8 is really fast, can a local DNS resolver really make a difference in this case ? Couldn't it be some hard resource limit?

**Comment by knxhm** [comment]
The local DNS resolver has definitely brought improvment. Thank you for the advise.
The remaining DNS errors are mostly really non resolveable domains, quite often quite weired strings. But I still wonder how this can happen. The users in behind ss-redir they do DNS requests and try to set up connections only to existing domains. When the ss-server does a revers lookup there shouldn't be so many errors. Or is it more or less normal that reverse lookup often goes wrong ?

**Comment by madeye** [comment]
> The users in behind ss-redir they do DNS requests and try to set up connections only to existing domains.

It depends on how the local resolver works in their LANs. For example, users may access some sites that cannot be resolved correctly with a public resolver.

**Comment by knxhm** [comment]
Yes thats clear. But here the ss-redir clients are using the same resolver as the ss-server. (8.8.8.8).

**Comment by madeye** [comment]
If so, upgrade ss-redir to the latest. It should not send any domain name to server in the latest version.
