### ISSUE TITLE
dns forwarding is still broken for version 3.2.0 in lede/openwrt

### ISSUE THREAD

**Issue by islercn** [shadowsocks/shadowsocks-libev#2124]
### What version of shadowsocks-libev are you using?
3.2.0

### What operating system are you using?
lede (pentium4 version)

### What did you do?
use my x86 router as a proxy server for my iphones (potatso 2)

### What did you expect to see?
visit google.com var cellular network

### What did you see instead?
if the version of ss-server is 3.1.0-3.2.0, when potatso 2 is started, i cannot visit all websites by urls but it is ok if i use IPs.
if the version of ss-server is less than 3.0.8 (include), no problem with the same config.

### What is your config in detail (with all sensitive info masked)?
{
    "server":["[::0]", "0.0.0.0"],
    "server_port":11111,
    "local_port":11112,
    "password":"password",
    "timeout":600,
    "method":"rc4-md5"
}

**Comment by madeye** [comment]
Report it to Potatso instead.

Or try Outline on your phone

**Comment by af-moonbow** [comment]
I could use Potatso 2 on my iPhone. So you might configured something wrong.
