### ISSUE TITLE
sometimes called the ss-manager add port api twice may cause the port being shutdown

### ISSUE THREAD

**Issue by Roll8ack** [shadowsocks/shadowsocks-libev#2126]
sometimes called the ss-manager add port api twice may cause the port being shutdown and  "port is not available" message.

What version of shadowsocks-libev are you using?
3.2.0 From Fedora Copr

What operating system are you using?
server: CentOS 6

What did you do?
running ss-manger like:
/usr/bin/ss-manager -u -c /etc/shadowsocks-libev/config.json -f /var/run/shadowsocks-manager/pid -a shadowsocks --manager-address 0.0.0.0:6001
and called the ss-manager add port api twice.

What did you expect to see?
port still listening.

What did you see instead?
sometimes port 20000 was down.
information in system log.
Jul 20 09:30:07 mylinux /usr/bin/ss-manager[57005]: try to bind interface: 0.0.0.0, port: 20000
Jul 20 09:30:07 mylinux /usr/bin/ss-manager[57005]: bind: Address already in use
Jul 20 09:30:07 mylinux /usr/bin/ss-manager[57005]: Could not bind
Jul 20 09:30:07 mylinux /usr/bin/ss-manager[57005]: port is not available, please check.
Jul 20 09:30:07 mylinux /usr/bin/ss-manager[57005]: add_sendto: Bad file descriptor

What is your config in detail (with all sensitive info masked)?
ss-manager config.json
{
    "password":"mypassowrd",
    "timeout":300,
    "method":"chacha20"
}

**Comment by madeye** [comment]
Try https://github.com/shadowsocks/shadowsocks-manager

**Comment by madeye** [comment]
And you cannot add same port twice.

**Comment by Roll8ack** [comment]
OK, Thank you.
