### ISSUE TITLE
ss-redir，配置UDP转发后，失败

### ISSUE THREAD

**Issue by ninechung** [shadowsocks/shadowsocks-libev#2128]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
3.2.0

### What operating system are you using?
OpenWRT

### What did you do?
隐藏IP，在路由器中禁止 WebRTC。
我现在配置了 TCP/UDP 都是走 ss，但是还是会被 WebRTC 检测出真实 IP

### What is your config in detail (with all sensitive info masked)?

**Comment by slovecrypto** [comment]
UDP redirecting failure can mainly related to your ISP, both client network and server network.
