### ISSUE TITLE
如何应对gfw的tcp阻断？

### ISSUE THREAD

**Issue by jasonbohan** [shadowsocks/shadowsocks-libev#2130]
ss是支持tcp和udp的，现在我的vps被gfw采用tcp阻断的方式，导致无法使用ss服务。但是使用sockscap64对节点进行udp测试时，测试可以通过，说明udp服务没有收到gfw影响。另外被tcp阻断的机器可以ping通过，说明icmp服务也正常。
我想问一下开发大佬，如何让ss在tcp被阻断的时候，可以让ss使用udp模式来提供服务。
或者在后期开放时，可否考虑让ss可以在udp模式下提供数据传输服务。
因为目前ss的在建立握手阶段时使用tcp传输的。

**Comment by madeye** [comment]
First of all, prove your connection issue is caused by GFW.

You can also try KCPTUN plugin: https://github.com/shadowsocks/kcptun

**Comment by jasonbohan** [comment]
为什么说是tcp阻断？
1.使用国内IP时，可以ping通vps，说明ICMP包正常，但是无法使用ss服务，包括ssh服务也无法使用，使用sockscap64测试ss节点，通过tcp方式测试提示出错；使用udp方式测试时，数据包可以通过。具体抓图我还不会。
2.使用国外IP地址，可以正常使用ssh服务，和ss服务。
![image](https://user-images.githubusercontent.com/41893237/43398066-8a590528-9439-11e8-99c4-09d6cacce406.png)

**Comment by madeye** [comment]
Not necessary, KCP is already the best open source reliable UDP transfer protocol.

**Comment by jasonbohan** [comment]
谢谢。已经部署了kcptun，来解决tcp阻断的问题。这个issue可以关闭了。谢谢您！

**Comment by aihidao** [comment]
> 谢谢。已经部署了kcptun，来解决tcp阻断的问题。这个issue可以关闭了。谢谢您！

这个东西对tcp阻断有效吗？

**Comment by NewCheung** [comment]
v2ray的KCP协议应该也是可以连接的，不过我没试过，因为还没有一台被墙的机。

**Comment by good-and-more** [comment]
> v2ray的KCP协议应该也是可以连接的，不过我没试过，因为还没有一台被墙的机。

我刚刚试成功了，用的virmach的最便宜的机器，被tcp阻断，表现为可以ping通，但是端口从国内连接全都关闭，换了v2ray一键脚本安装，用mkcp，系统是debian8，现在可以扶墙出去

**Comment by ACG-MM** [comment]
万一udp也阻断了呢。有什么办法全部用websocket监听端口连接么

**Comment by aihidao** [comment]
> 万一udp也阻断了呢。有什么办法全部用websocket监听端口连接么

1、试试加cloudflare 改为代理 dns，我第一次使用cloudflare时候很卡取消了，有天服务器似乎被墙了，现在cloudflare的速度很快，有时候甚至比直接访问我的服务器还快。
2、提前看看v2ray吧，我之前用的ss，每到不可描述时期就封了，自从转了v2ray 已经安稳运行一年了。
