### ISSUE TITLE
Configure shadowsocks to disable TLS on client side ?

### ISSUE THREAD

**Issue by randomsecguy** [shadowsocks/shadowsocks-libev#2131]
Hi. This is not an issue of shadowsocks. Just a general question but I do not know where else to put it. Hope someone can help. 

My setup is as follows:
Host----shadowsocks client--------shadowsocks server-----internet

To grab the traffic between the host and internet (all websites visited), I run wireshark and capture all TCP communication. This traffic is TLS and currently, I can decrypt it in wireshark using the master secret but there is no way of saving it as a decrypted pcap.

Is shadowsocks aware of the data being relayed? If so, is there a way to tell shadowsocks to disable encryption and use http when serving the host machine? The connection on the internet side can keep using TLS as required by most websites today.

**Comment by madeye** [comment]
Nope, you cannot do that with shadowsocks.

You may try some MITM proxy for this purpose.
