### ISSUE TITLE
Docker version support multi user ?

### ISSUE THREAD

**Issue by iamhaifeng** [shadowsocks/shadowsocks-libev#2134]
### What version of shadowsocks-libev are you using?
3.2.0

### What operating system are you using?
CentOS7+Docker

### What did you do?
#docker pull docker.io/shadowsocks/shadowsocks-libev
#docker run -dt --name ss_test \\
   -v /path/config.json:/etc/config.json \\
   -p 10001:10001 -p 10001:10001/udp \\
   -p 10002:10002 -p 10002:10002/udp \\
   shadowsocks/shadowsocks-libev \\
   ss-server -c /etc/config.json

### What you want?
I want use muli user configure.

### What did you see instead?
Can't run, exit immediate, and print ss-server help message.

### What is your config in detail (with all sensitive info masked)?
#more config.json 
{
	"server": "0.0.0.0",
	"port_password" : { 
		"10001": "foobar1",
		"10002": "foobar2"
	 },
	"timeout": 300,
	"method": "aes-256-cfb",
	"fast_open": true,
}

**Comment by madeye** [comment]
Nope, you configuration is not supported.
