### ISSUE TITLE
shadowsocks服务隔几分钟就不能连接了，但ss-server进程仍然在运行

### ISSUE THREAD

**Issue by lygoing** [shadowsocks/shadowsocks-libev#2137]
大佬你好，最近我在一台服务器上部署了ss服务，服务器配置比较低，CPU 1核 内存 1G。刚开始ss服务运行正常，但自从我在服务器上部署了个artifactory服务，内存非常紧张了，于是我开启了虚拟内存，但是发现ss服务一段时间之后就不能连接了，但通过ps查看ss进程在后台运行。请问有什么办法可以解决这个问题吗？不然我得隔几分钟就需要去重启一下ss服务。 谢谢！

### What version of shadowsocks-libev are you using?
版本：3.2.0
![image](https://user-images.githubusercontent.com/5944432/43673218-5e926afe-97f1-11e8-8f3c-c57fb163aaeb.png)

### What operating system are you using?

CentOS 7

![image](https://user-images.githubusercontent.com/5944432/43673225-808a5234-97f1-11e8-81b7-6cf837fc852e.png)

### What is your config in detail (with all sensitive info masked)?

![image](https://user-images.githubusercontent.com/5944432/43673244-f6e3433c-97f1-11e8-83d6-c37c9e1f682b.png)

**Comment by studentmain** [comment]
Any log?

lygoing <notifications@github.com> 于 2018年8月4日周六 14:21写道：

**Comment by lygoing** [comment]
@studentmain thank you for your reply.

**Comment by lygoing** [comment]
@studentmain 
I also want to check the logs of shadowsocks, but I don't know where to view them? Can you tell me? Thank you!

**Comment by lygoing** [comment]
@studentmain I use yum to install

**Comment by studentmain** [comment]
for example , `systemctl status shadowsocks-libev.service`

lygoing <notifications@github.com> 于 2018年8月4日周六 14:35写道：

**Comment by lygoing** [comment]
@studentmain It looks good, please wait.
![image](https://user-images.githubusercontent.com/5944432/43673394-2dd582e4-97f5-11e8-8a19-34197632442b.png)

**Comment by studentmain** [comment]
Is port listening? Nothing interesting in log? Maybe you need another machine...

**Comment by lygoing** [comment]
@studentmain Now the ss-server cannot be connected.

![image](https://user-images.githubusercontent.com/5944432/43673926-af942f3a-97fd-11e8-8b7f-b8ca8f21f608.png)

![image](https://user-images.githubusercontent.com/5944432/43673927-bbf84770-97fd-11e8-82ae-78d4e48c314c.png)

**Comment by lygoing** [comment]
@madeye  Help please.

**Comment by madeye** [comment]
No one would help unless you can provide more details.

**Comment by lygoing** [comment]
@madeye It seems that there are so many details that can be provided. Of course you can tell me what important details are needed. I think it might be a problem with the machine because it worked fine before. I may need to streamline some things, thank you very much again!
