### ISSUE TITLE
How can I get NAT type 2 when I run the ss-server in aliyun VPC?

### ISSUE THREAD

**Issue by anson0370** [shadowsocks/shadowsocks-libev#2138]
### What version of shadowsocks-libev are you using?
3.1.3

### What operating system are you using?
CentOS Linux release 7.4.1708

### What did you do?
Ran ss-server at an Aliyun ECS in VPC. configure my router to use this ss. connect my PS4 to my router.

### What did you expect to see?
NAT Type 2

### What did you see instead?
NAT Type failed

### What is your config in detail (with all sensitive info masked)?
{
    "server":"0.0.0.0",
    "server_port":xxxx,
    "local_port":xxxx,
    "password":"xxxxxxxxxx,
    "timeout":600,
    "method":"chacha20"
}

**Comment by anson0370** [comment]
Sorry for no response. Really busy the past few months and no time to play my PS4. 😢 

But I finally figured out this issue. The reason is a little stupid...I forgot add the UDP rule into VPC security group. I thought I added it and never did a check.

**Comment by Zhang21** [comment]
@anson0370  朋友，你之后能获取NAT吗？我在路由器上SS+UDP基本上都是获取NAT失败，偶尔又能获取到NAT2。怎么回事呢？

**Comment by anson0370** [comment]
@Zhang21 看我上面的回复 我在安全组里加了允许SS端口的UDP协议后就好了
