### ISSUE TITLE
Stuck on configure script when installing and there isn't enough entropy to generate a password

### ISSUE THREAD

**Issue by JixunMoe** [shadowsocks/shadowsocks-libev#2139]
### What version of shadowsocks-libev are you using?
3.1.3+ds-1ubuntu2

### What operating system are you using?
Ubuntu 18.04 LTS

### What did you do?
```
apt install shadowsocks-libev
```

### What did you expect to see?
It installs the package.

### What did you see instead?
Stuck on lines like "setting up `shadowsocks-libev`".

### What is your config in detail (with all sensitive info masked)?
N/A

I happen to be running on an ARM server with [low entropy](https://github.com/scaleway/image-ubuntu/issues/81), and `apg` refuses to generate anything:

```
$ cat /proc/sys/kernel/random/entropy_avail
12
$ apg -n 1 -M ncl
<no response>
```

I managed to workaround this by install [`haveged`](http://www.issihosts.com/haveged/):

```
$ sudo apt install haveged
...
$ cat /proc/sys/kernel/random/entropy_avail
1726
$ apg -n 1 -M ncl
UmFodfaigy
```

Maybe apply one of the following can be applied?

1. When the configure script has found to be in a "low entropy" environment, do not generate a random password and leave as it is.
2. Let the user type a password (like when installing mysql package you will be prompted for passwords).

**Comment by madeye** [comment]
Please report Debian related issues here: https://packages.debian.org/sid/shadowsocks-libev
