### ISSUE TITLE
从repos安装shadowsocks-libev，服务器端应当是正常运行的，但是无法使用。

### ISSUE THREAD

**Issue by cnnblike** [shadowsocks/shadowsocks-libev#214]
VPS：CentOS 7@DigitalOcean SGP机房
安装SS-libev的方式：源安装
服务器端SS状态：
[root@www ~]# systemctl status shadowsocks-libev
shadowsocks-libev.service - SYSV: lightweight secured scoks5 proxy
Loaded: loaded (/etc/rc.d/init.d/shadowsocks-libev)
Active: active (running) since Mon 2015-01-12 01:24:43 EST; 7s ago
Process: 9803 ExecStart=/etc/rc.d/init.d/shadowsocks-libev start (code=exited,
status=0/SUCCESS)
CGroup: /system.slice/shadowsocks-libev.service
.. └─9807 /usr/bin/ss-server -u -c /etc/shadowsocks-libev/config.json.
可以看到active (running)，服务应当是正确的加载了

使用ps aux | grep "ss"后输出了 root 9807 0.0 0.2 85560 1068 ? Ssl 01:24 0:00 /usr/bin/ss-ser
ver -u -c /etc/shadowsocks-libev/config.json -f /var/run/shadowsocks-server/pid
这一行，证明SS服务器端的确在正常工作

[root@www ~]# cat /etc/shadowsocks-libev/config.json
{
"server":"127.0.0.1",
"server_port":1,
"local_port":1080,
"password":"1a2b3c4d",[此处密码也被我修改了]
"timeout":60,
"method":"rc4-md5"
}
证明设置应当是没有问题的。

firewall-cmd --list-all后
输出的port中的确有prots: 1/tcp
但是问题来了，为什么我不能正常的链接到服务器呢？
我这里ping 服务器IP的地址ping值在82-91，平均为86，掉包率30%

客户端log：
System.Net.Sockets.SocketException (0x80004005): 由于目标计算机积极拒绝，无法连接。 [服务器IP地址]:1
   在 System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)

**Comment by madeye** [comment]
{
**"server":"0.0.0.0"**,
"server_port":1,
"local_port":1080,
"password":"1a2b3c4d",[此处密码也被我修改了]
"timeout":60,
"method":"rc4-md5"
}
