### ISSUE TITLE
The ss log shows  2018-08-08 ERROR: connect: Invalid argument

### ISSUE THREAD

**Issue by whzh01** [shadowsocks/shadowsocks-libev#2141]
### What version of shadowsocks-libev are you using?
The shadowsocks-libev's version is 'shadowsocks-libev 3.2.0'

### What operating system are you using?
Centos6.1

### What did you do?
When i use my client to connect, the server's log shows an errror(connect :Invalid argument);

### What is your config in detail (with all sensitive info masked)?
{
    "server":"0.0.0.0",
    "local_address":"127.0.0.1",
    "server_port":8083,
    "local_port":1080,
    "password":"*******",
    "timeout":60,
    "method":"aes-256-gcm",
    "fast_open":false
}

**Comment by madeye** [comment]
Remove `local_address` from your config.

**Comment by whzh01** [comment]
Thank you,it works .
