### ISSUE TITLE
Suggestion: Consider releasing with prebuilt executables? 

### ISSUE THREAD

**Issue by Yrr0r** [shadowsocks/shadowsocks-libev#2143]
If prebuilt executables is included in the release page, it would be possible to run the program directly after download and require no installing or compilling?

Suggesting release prebuilt executables on Mac, Windows and Linux (x86/64 and ARM).

_Please close this issue if solved or wontfix._

**Comment by madeye** [comment]
1. Mac: `brew install shadowsocks-libev`
2. Ubuntu: `sudo apt install shadowsocks-libev`
