### ISSUE TITLE
Lower log level

### ISSUE THREAD

**Issue by rgarrigue** [shadowsocks/shadowsocks-libev#2145]
Hello

I'ld just like to know how to lower the log level, while using the `shadowsocks/shadowsocks-libev` official docker image. INFO include periodical output which is flooding on the long run :-)

Best regards,

**Comment by madeye** [comment]
Remove `-v` from your docker files.

**Comment by rgarrigue** [comment]
@madeye sorry for the late answer. I've looked in the official Dockerfile ( in docker/alpine folder if I'm not mistaken), there's no verbose option set. Was it removed meanwhile ?
