### ISSUE TITLE
AES GCM really use of AES-NI extension on supported machine?

### ISSUE THREAD

**Issue by xqdoo00o** [shadowsocks/shadowsocks-libev#2147]
### What version of shadowsocks-libev are you using?
lastest build 3.2.0

### What operating system are you using?
debian 9 x86_64

### What did you do?
run iperf test.

### What did you expect to see?
iperf performance good

### What did you see instead?
On the same machine, when I use chacha20-ietf-poly1305, the iperf result is similar between ss-libev and go-ss2(install from lastest source).
But when I use aes-(256 or 128)-gcm, go-ss2 iperf result is **3~4 times** difference with ss-libev iperf result.

```
AES-128-GCM
ss-libev      go-ss2
130Mbps       600Mbps

AES-256-GCM
ss-libev      go-ss2
125Mbps       550Mbps
```

so I wonder if AES GCM really use AES-NI extension?

### What is your config in detail (with all sensitive info masked)?
libsodium 1.0.16 mbedTLS 2.12
**iperf-libev.sh**

#!/bin/bash
number=40960000
method='aes-256-gcm'

ss-tunnel -k test -m $method -l 8387 -L 127.0.0.1:8388 -s 127.0.0.1 -p 8389 &
ss_tunnel_pid=$!
ss-server -k test -m $method -s 127.0.0.1 -p 8389 &
ss_server_pid=$!

iperf -s -p 8388 &
iperf_pid=$!

sleep 1

iperf -c 127.0.0.1 -p 8387 -n $number

sleep 2

kill $ss_tunnel_pid
kill $ss_server_pid
kill $iperf_pid

sleep 1
echo "Test Finished"

**iperf-go.sh**

#!/bin/bash
number=40960000
method='AEAD_AES_256_GCM'

shadowsocks2 -c 'ss://'${method}':@:8389' -tcptun :8387=localhost:8388 &
ss_tunnel_pid=$!
shadowsocks2 -s 'ss://'${method}':@:8389' &
ss_server_pid=$!

iperf -s -p 8388 &
iperf_pid=$!

sleep 1

iperf -c 127.0.0.1 -p 8387 -n $number

sleep 2

kill $ss_tunnel_pid
kill $ss_server_pid
kill $iperf_pid

sleep 1
echo "Test Finished"

**Comment by madeye** [comment]
It's a known issue of libmbedtls: https://github.com/ARMmbed/mbedtls/issues/1189

Keep using chacha20 as it has the best performance across different platforms.

**Comment by xqdoo00o** [comment]
OK, I know

**Comment by xqdoo00o** [comment]
Sorry, but any chance using Libsodium implement for aes-256-gcm method?

**Comment by edsgerlin** [comment]
It is possible, seems to be a nice weekend project.

I am surprised to find out today that both libsodium and mbedTLS have no support for hardware AES on ARMv8, and mbedTLS is from ARM. So I am not using hardware AES on Android at all......

**Comment by xqdoo00o** [comment]
@edsgerlin ya. Looks like only Openssl and Golang internal cipher implements aes-ni on aarch64 platform.

**Comment by edsgerlin** [comment]
@xqdoo00o I submit a PR, do you know how to compile from source.

https://github.com/edsgerlin/shadowsocks-libev/releases/tag/3.2.0-sodium-aes

Could you help me benchmark this patch and provide your result on same machine?

BEWARE: Only `aes-256-gcm` is using `libsodium` so please use 256 bits AES for benchmark.

**Comment by edsgerlin** [comment]
Benchmark result on my laptop with Intel Broadwell processor: Some minor improvement.

Original: 164 Mbits/sec
Modified: 196 Mbits/sec

About 20% increase on Broadwell, should be more on newer processor with better AES-NI performance.

**Comment by edsgerlin** [comment]
@xqdoo00o Thank you very much for your benchmark!

Did you use the one in the link? It is older one without precomputation.

Please also help benchmark this one:

https://github.com/edsgerlin/shadowsocks-libev/releases/tag/3.2.0-aes-precomputation

This version is using precomputed AES key, it should be even faster.
Also the version with precomputation is merged into shadowsocks/shadowsocks-libev already!
Thanks @madeye !

**Comment by xqdoo00o** [comment]
@edsgerlin I use the lastest master repo with precomputation merged. The perf increase so much. 😄 Thanks for your good job 👍

**Comment by edsgerlin** [comment]
Glad to know that!
