### ISSUE TITLE
ss-redir 如何实现高可用负载均衡？

### ISSUE THREAD

**Issue by ninechung** [shadowsocks/shadowsocks-libev#2148]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
3.2.0

### What operating system are you using?
ubuntu

### What did you do?
在服务端用ss-manager启动了50个ss-server的进程
在路由器上用了ss-redir + HAproxy，haproxy同样配置了50个端口。
现目前有2台路由器，每台路由器4台电脑，每台电脑配置3-4台手机。也就是一台路由器大概会接入20个左右的设备。
网络非常的卡，延迟很高。请问如何解决这个问题？

服务器配置：
4C/8T
3.3Ghz Clock
8G RAM
1T * 1Ea SATA3
1TB Bandwidth
1Gbps Port Network

路由器是小米3G路由器，这路由器配置也不差吧。

### What is your config in detail (with all sensitive info masked)?
    SSLOCAL="[\"[::0]\",\"0.0.0.0\"]"
    PORT="443"
    PASSWORD="xxx"
    METHOD="aes-256-gcm"
    TIMEOUT="600"
    OBFS="tls"
    OBFSHOST="www.icloud.com"
    OBFSURI="/"
    FASTOPEN="true"
    REUSEPORT="true"
    DNS1="210.220.163.82"
    DNS2="8.8.8.8"
    DNSv6a="2001:4860:4860::8888"
    DNSv6b="2001:4860:4860::8844"
    DSCP="EF"
    MODE="tcp_and_udp"
    MTU=""
    MPTCP="false"
    IPV6FIRST="false"
    SYSLOG="true"
    NODELAY="true"
    FWS="enable"
    ABB="enable"
    BBR="enable"

**Comment by madeye** [comment]
Given you have only one server, running HAProxy and multiple ss-server is useless.

**Comment by ninechung** [comment]
服务器资源和路由器资源都没有用完，带宽也足够。怎样保持最大负载工作呢？

**Comment by madeye** [comment]
Shadowsocks is designed and optimized for low-end boxes and routers. It's expected to use very little resource on a high-end server.

**Comment by sophauer** [comment]
all you need is money and spend it on VPS

**Comment by jsvisa** [comment]
> 网络非常的卡，延迟很高 
你是指国外的慢，国内的不慢？

> 一台路由器大概会接入 20 个左右的设备
这个已经超过了家用路由器的处理能力了，可以可以用企业级的， AC + AP 方案

**Comment by nadoo** [comment]
@ninechung, You can try https://github.com/nadoo/glider , which has builtin support for multiple servers in rr/ha/dh modes.

**Comment by ninechung** [comment]
@nadoo i will try it, thanks you.
