### ISSUE TITLE
Is there any way to use pure TCP and disable listening on UDP?

### ISSUE THREAD

**Issue by PaleNeutron** [shadowsocks/shadowsocks-libev#2152]
### What version of shadowsocks-libev are you using?
3.2.0+ds-3~bpo9+1

### What operating system are you using?
 Debian GNU/Linux 9.5 (stretch)

### What did you do?
Try to connect to a server from a network which block all UDP connections by its firewall

### What did you expect to see?
Everything works well

### What did you see instead?
Could not connect successful

server lisening on both UDP and TCP
```
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 176.122.148.37:23443    0.0.0.0:*               LISTEN      7593/ss-server
udp        0      0 176.122.148.37:23443    0.0.0.0:*                           7593/ss-server
```
### What is your config in detail (with all sensitive info masked)?
ss-server:

```json
{
    "server":"*.*.*.*",
    "server_port":23443,
    "password":"*",
    "timeout":300,
    "method":"aes-256-gcm",
    "use_syslog": true
}
```

How can I force ss-local to use only TCP?

**Comment by madeye** [comment]
Remove any `-u` option from your command line or init scripts.
