### ISSUE TITLE
ERROR: [udp] sendto_remote: Network is unreachable

### ISSUE THREAD

**Issue by markcs** [shadowsocks/shadowsocks-libev#2154]
### What version of shadowsocks-libev are you using?
shadowsocks-libev 2.6.3 with mbed TLS 2.4.2

### What operating system are you using?
Debian

### What did you do?
I'm trying to get a udp application (in this case a voice call) routed using shadowsocks.  I get the following errors:
 2018-08-22 18:25:03 INFO: [udp] cache hit: xx.xx.xx.xx:59807 <-> yy.yy.yy.yy:32555
 2018-08-22 18:25:03 INFO: [udp] server receive a packet
 2018-08-22 18:25:03 INFO: [udp] cache miss: <ipv6 address I think><-> yy.yy.yy.yy:12206
 2018-08-22 18:25:03 ERROR: [udp] sendto_remote: Network is unreachable

Note I removed all iptables to ensure this was not the cause.

### What did you expect to see?
I would expect to not see these errors

### What is your config in detail (with all sensitive info masked)?
{
    "server":"serverip",
    "server_port":portnumber,
    "local_port":1080,
    "password":"mypassword",
    "timeout":60,
    "method":"chacha20",
    "mode":"tcp_and_udp",
    "fast_open":true
}

**Comment by madeye** [comment]
As described in your log, the destination address is unreachable from your server.

Typically it's a private address in your LAN.

**Comment by addohm** [comment]
I've got this same issue. Trying to route a Google hangouts/voice call through proxy from China.

**Comment by debiansid** [comment]
ss-redir转发udp从未成功过
