### ISSUE TITLE
不支持最新版的openwrt 18.06.1版本，请问是否能更新支持？

### ISSUE THREAD

**Issue by shmily103** [shadowsocks/shadowsocks-libev#2158]
不支持最新版的openwrt 18.06.1版本，请问是否能更新支持？

**Comment by madeye** [comment]
https://github.com/shadowsocks/luci-app-shadowsocks

**Comment by shmily103** [comment]
@madeye 
luci-app-shadowsocks配置编译没有问题，配置shadowsocks-libev时network下没有这个选项。
