### ISSUE TITLE
Does default DNS resolving works without systemd-resolv ?

### ISSUE THREAD

**Issue by lukasmrtvy** [shadowsocks/shadowsocks-libev#2161]
### What version of shadowsocks-libev are you using?

shadowsocks-libev 3.1.3

### What operating system are you using?

Ubuntu 18.04.1 LTS in Docker (its without systemd)

### What did you do?

ss-server -s 0.0.0.0 -p 8388 -m chacha20-ietf-poly1305 -k verysecret --fast-open -u -v 

### What did you expect to see?

ss-server .... without -d argument must dynamically look into /etc/resolv.conf for nameservers.
Ubuntu 18.04.1 LTS in Docker is without systemd, also without systemd-resolve.
Nameservers are explicitly specified in /etc/resolv.conf

### What did you see instead?

ss-local .. and SOCKSv5 works OK without DNS resolution. I can access only with IP addresses

### What is your config in detail (with all sensitive info masked)?

no need

**Comment by lukasmrtvy** [comment]
Closing. I had typo error.
Author can clarify this anyway.

**Comment by madeye** [comment]
Yes, it's handled by c-ares https://c-ares.haxx.se/
