### ISSUE TITLE
Fail to load service when enable IPv6 in config but on IPv4 only machine

### ISSUE THREAD

**Issue by rogers0** [shadowsocks/shadowsocks-libev#2162]
### What version of shadowsocks-libev are you using?
3.2.0+ds-3~bpo9+1

### What operating system are you using?
Debian Stretch

### What did you expect to see?
I want to enable IPv6 by default, with setting: "server": ["::0", "0.0.0.0"]
But on IPv4 only machine, this cause the service fails to load.

See Debian Bug #881847 
https://bugs.debian.org/881847

### What did you see instead?
Sep 01 18:35:39 ss-server[18386]:  2018-09-01 19:35:39 INFO: tcp server listening at [::0]:8388
Sep 01 18:35:41 ss-server[18386]:  2018-09-01 19:35:41 ERROR: failed to resolve server name, wait 2 seconds
Sep 01 18:35:45 ss-server[18386]:  2018-09-01 19:35:45 ERROR: failed to resolve server name, wait 4 seconds
Sep 01 18:35:53 ss-server[18386]:  2018-09-01 19:35:53 ERROR: failed to resolve server name, wait 8 seconds
Sep 01 18:36:09 ss-server[18386]:  2018-09-01 19:36:09 ERROR: failed to resolve server name, wait 16 seconds
Sep 01 18:36:41 ss-server[18386]:  2018-09-01 19:36:41 ERROR: failed to resolve server name, wait 32 seconds
Sep 01 18:37:45 ss-server[18386]:  2018-09-01 19:37:45 ERROR: failed to resolve server name, wait 64 seconds
Sep 01 18:39:53 systemd[1]: shadowsocks-libev.service: Main process exited, code=exited, status=255/n/a

### What is your config in detail (with all sensitive info masked)?
{
    "server": ["::0", "0.0.0.0"],
    "server_port":8388,
    "local_port":1080,
    "password":"<MASKED>",
    "timeout":60,
    "method":"chacha20-ietf-poly1305"
}

**Comment by madeye** [comment]
it's expected. You can not a bind an IPv6 address on IPv4 only host, which is an invalid IP address.

**Comment by rogers0** [comment]
I hope ss-server can just ignore such error and just bind IPv4 address.

**Comment by rogers0** [comment]
Thanks so much!

**Comment by rogers0** [comment]
I cherry-picked this commit to 3.2.0+ds-3, and found there still problem to start the service when disabling IPv6.

====
Sep  2 23:01:46 ss-server[19076]:  2018-09-02 23:01:46 INFO: UDP relay enabled
Sep  2 23:01:46 ss-server[19076]:  2018-09-02 23:01:46 INFO: initializing ciphers... chacha20-ietf-poly1305
Sep  2 23:01:46 ss-server[19076]:  2018-09-02 23:01:46 INFO: tcp server listening at [::0]:8388
Sep  2 23:01:46 ss-server[19076]:  2018-09-02 23:01:46 ERROR: failed to resolve server name ::0
Sep  2 23:01:46 ss-server[19076]:  2018-09-02 23:01:46 INFO: tcp server listening at 0.0.0.0:8388
Sep  2 23:01:46 ss-server[19076]:  2018-09-02 23:01:46 INFO: udp server listening at [::0]:8388
Sep  2 23:01:46 ss-server[19076]:  2018-09-02 23:01:46 ERROR: [udp] getaddrinfo: Address family for hostname not supported
Sep  2 23:01:46 ss-server[19076]:  2018-09-02 23:01:46 ERROR: [udp] bind() error
Sep  2 23:01:46 systemd[1]: shadowsocks-libev.service: Main process exited, code=exited, status=255/n/a
Sep  2 23:01:46 systemd[1]: shadowsocks-libev.service: Unit entered failed state.
Sep  2 23:01:46 systemd[1]: shadowsocks-libev.service: Failed with result 'exit-code'.
====

**Comment by madeye** [comment]
Please try 46ff0a8.

**Comment by rogers0** [comment]
@madeye yes, after cherry-pick both commits, problem solved.
I'll try to upload a version to unstable soon.
