### ISSUE TITLE
[Feature Request] Option for ss-server to listen on a static port when plugin is enabled

### ISSUE THREAD

**Issue by GreaterFire** [shadowsocks/shadowsocks-libev#2164]
I'm writing an SIP003 plugin based on my existing project [trojan](https://github.com/trojan-gfw/trojan). Now it supports the functionality like `ss-tunnel` (static port forwarding), which (hopefully you know) chooses which target server to visit on the client side, instead of the server side. If I was to implement SIP003 in this scenario, the client needs to know which port (on the server local interface) `ss-server` is listening on (`SS_LOCAL_HOST` and `SS_LOCAL_PORT` of the server), which, according to [the code](https://github.com/shadowsocks/shadowsocks-libev/blob/46ff0a8045f5a3f504294c85f5e5e19c813c3e52/src/server.c#L1839), is random. So after a restart of the `ss-server`, the client needs to modify its target port in accordance to the new "random" port `ss-server` is then listening on. I'm wondering if there could be an option for `ss-server` to listen on a static port even if plugin is enabled, so that client configuration would be easier.

**Comment by madeye** [comment]
No plan for this.

BTW, if plugin enabled, `ss-server` will only listen on local address.

**Comment by GreaterFire** [comment]
I made it work. It's just the client configuration is tedious. But nevermind if you do not want to include this feature. Thanks.

**Comment by GreaterFire** [comment]
In case you are interested, https://github.com/trojan-gfw/trojan/wiki/Shadowsocks-SIP003-Integration.
