### ISSUE TITLE
obtain request path for a http request with ss-local

### ISSUE THREAD

**Issue by yanggis** [shadowsocks/shadowsocks-libev#2165]
Dear all:
Firstly, thanks for the great app developed and maintained by you guys.
Now I have a question, hope you can give me some tips.

I know currently ss-local and obtain hostname or domain name for requests. For me, I also wanna obtain the path for a http request with ss-local.

For example:

For request: http://www.baidu.com/music/goodboy.mp3
Now ss-local can obtain the domain name: www.baidu.com

However, I dont know where I can insert some codes to get the path [/music/goodboy.mp3 for the example].

Could you give some tips, thanks very much!

**Comment by madeye** [comment]
Nope, you cannot do that. Try any MITM proxy instead.

**Comment by yanggis** [comment]
OK, anyway, thanks.
