### ISSUE TITLE
dpkg-buildpackage failure: dh_makeshlibs: failing due to earlier errors

### ISSUE THREAD

**Issue by fsgmhoward** [shadowsocks/shadowsocks-libev#2168]
### What version of shadowsocks-libev are you using?
Latest commit (3.2.0-37-g46ff0a8)

### What operating system are you using?
Ubuntu Xenial (Same problem with Trusty/Bionic/Precise)

### What did you do?
Build deb package from the source through Launchpad.net

### What did you expect to see?
Successful build

### What did you see instead?
Build failure: `dh_makeshlibs: failing due to earlier errors`

It seems that the problem is related to the outdated/missing symbol files.
```
dpkg-gensymbols: warning: some new symbols appeared in the symbols file: see diff output below
dpkg-gensymbols: warning: some symbols or patterns disappeared in the symbols file: see diff output below
dpkg-gensymbols: warning: debian/libshadowsocks-libev2/DEBIAN/symbols doesn't match completely debian/libshadowsocks-libev2.symbols
```

Since the log is very long I am not going to copy & paste it here. Full log for the build of xenial packages is here: https://launchpadlibrarian.net/387094697/buildlog_ubuntu-xenial-amd64.shadowsocks-libev_3.2.0-37-g46ff0a8+xenial+ixnet.work-1_BUILDING.txt.gz

### What is your config in detail (with all sensitive info masked)?
N/A

**Comment by hosiet** [comment]
My suggestion about dealing with the symbols files in upstream repo: please delete `debian/*.symbols` since they are of little use for those who are not distribution packagers. I will make a PR later for that.
