### ISSUE TITLE
compatibility with pfsense - new ideas

### ISSUE THREAD

**Issue by imacks** [shadowsocks/shadowsocks-libev#2170]
### What version of shadowsocks-libev are you using?
latest version from openwrt repo

### What operating system are you using?
- nano server 2016 on bare metal
- hyper-v on nano server
- openwrt as vm
- pfsense as vm

This is a revisit of #2114 #1745 [如何把shadowsocks和goagent打包成插件](https://forum.netgate.com/topic/59919/如何把shadowsocks和goagent打包成插件) and [reddit post](https://www.reddit.com/r/PFSENSE/comments/866ow8/shadowsocks_support/)

A little background info:

this is my current setup, which is only because I can't run ss-redir in pfsense.
```
---isp---[ openwrt ]---[pfsense]--- me
```
ISP box is attached to wan port of openwrt, and lan port of openwrt is attached to wan port of pfsense.
i link up to lan port of pfsense.

This is what I'm thinking now:

```
              [openwrt]
---isp         |  |
     +-----[pfsense]---me
```

isp box is attached to wan1 port of pfsense. openwrt wan port links to lan1 port of pfsense. openwrt lan port links to wan2 port of pfsense. i link up to lan2 port of pfsense.

This effectively creates 2 wan connections on pfsense (multi-wan). only traffic going through wan2 is shadowsocks-ed.

Unfortuantely, i couldn't get this setup to work properly. Can anyone try it too?

**Comment by imacks** [comment]
self update: i managed to get things to work. you need to uncheck "Block private networks and loopback addresses" on the pfsense side. now set firewall rules in pfsense to route traffic not in your private ip range to wan2 (which is openwrt lan port).

there is still a big issue with google only: whenever i visit google, there is a high chance of me being served with facebook's ip. then the certificate fails and i cannot visit google.

it only happens with google. what could be the issue?

**Comment by chenhw2** [comment]
@imacks 

> there is still a big issue with google only: whenever i visit google, there is a high chance of me being served with facebook's ip. then the certificate fails and i cannot visit google.

it is a typical DNS Poisoning problem.
