### ISSUE TITLE
dpkg-buildpackage: error: debian/rules binary gave error exit status 2

### ISSUE THREAD

**Issue by triaqu** [shadowsocks/shadowsocks-libev#2172]
### What version of shadowsocks-libev are you using?
9月9日 Fix a bug in bypassing 3.2.0版

### What operating system are you using?
Debian8.1

### What did you do?
git pull
git submodule update --init --recursive
mk-build-deps --root-cmd sudo --install --tool "apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends -y"
./autogen.sh && dpkg-buildpackage -b -us -uc后报错：

### What did you expect to see?
生成shadowsocks-libev 3。2。0

### What did you see instead?
............
`- keep_resolving@Base 2.4.7
+#MISSING: 3.2.0-1# keep_resolving@Base 2.4.7
  logfile@Base 2.4.7
  lookup_rule@Base 2.5.6
+ murmurhash2@Base 3.2.0-1
  new_rule@Base 2.5.6
  new_server_ctx@Base 2.4.7
  outbound_block_match_host@Base 2.5.6
@@ -90,6 +181,7 @@
  sockaddr_cmp@Base 2.4.7
  sockaddr_cmp_addr@Base 2.4.7
  ss_align@Base 3.0.2
+ ss_is_ipv6addr@Base 3.2.0-1
  ss_isnumeric@Base 2.6.3
  ss_itoa@Base 2.4.7
  ss_malloc@Base 2.4.7
@@ -97,6 +189,7 @@
  ss_strndup@Base 2.4.7
  start_plugin@Base 2.6.3
  start_ss_local_server@Base 2.4.7
+ start_ss_local_server_with_callback@Base 3.2.0-1
  stop_plugin@Base 2.6.3
  stream_cipher_ctx_init@Base 3.0.2
  stream_ctx_init@Base 3.0.2
dh_makeshlibs: failing due to earlier errors
debian/rules:24: recipe for target 'binary' failed
make: *** [binary] Error 255
dpkg-buildpackage: error: debian/rules binary gave error exit status 2
`

**Comment by fsgmhoward** [comment]
Ref #2168 
From my test, it should have been fixed in the latest commit.
