### ISSUE TITLE
won't automatically bind IPv6 addr using ss-manager

### ISSUE THREAD

**Issue by Mirr0ch1** [shadowsocks/shadowsocks-libev#2186]
### What version of shadowsocks-libev are you using?
3.2.0

### What operating system are you using?
CentOS7 CR

### What did you do?
Connect to a IPv6-enabled VPS using the latest version of shadowsocks-android on a IPv6 only network.

### What did you expect to see?
tcp connection established successfully 

### What did you see instead?
error message on android side: connection closed by peer. with no traffic transmitted.

### What is your config in detail (with all sensitive info masked)?
using shadowsocks-manager webGUI written by gyteng as the management system.
using shadowsocks-manager-tiny on slave-side nodes to have port:password sets distributed from master VPS running the webGUI.
the command `ssmgr` used to activate `ss-manager` is `ss-manager -m chacha20-ietf-poly1305 -u --manager-address 127.0.0.1:****`, which makes `ss-server` bind only IPv4 ( `-s 0.0.0.0` ). I was hoping to see it binding both `0.0.0.0` and `[0::]`. Thanks for your gracious.

**Comment by Mirr0ch1** [comment]
Since major municipalities in China has done some work getting IPv6 fully functional, it's time, I think, to have proper IPv6 support for shadowsocks-manager. Currently, typing `-s [0::]` manually under ss-manager options will led to nowhere.

**Comment by madeye** [comment]
Try ‘-s ::0’.

**Comment by Mirr0ch1** [comment]
> 
> 
> Try ‘-s ::0’.

Thanks, problem solved by using `-s 0.0.0.0` and `-s ::0` at the same time.
