### ISSUE TITLE
经常有人嗅探ss服务器

### ISSUE THREAD

**Issue by bloomsource** [shadowsocks/shadowsocks-libev#2187]
Please answer these questions before submitting your issue. Thanks!
当你访问以后,立刻另外一个ip紧接着就访问你的ss端口,距离时间非常短,通常在一秒以内,
这个跟随的ip地址的请求的通常解密头部出错.
有这种情况的朋友多吗? 国内有干网络设备这块的,知道这是什么情况吗? 
这跟随的程序一般是在干啥? 看你这个不常用端口是不是http?

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

**Comment by lizhaode** [comment]
不会是GFW吧

**Comment by PantherJohn** [comment]
@bloomsource It should be something like active probing. I'm not sure if adding [`local.acl`](https://github.com/shadowsocks/shadowsocks-libev/blob/master/acl/local.acl) rules for `ss-server` really helps. The syntax goes like this:
```
[reject_all]

[white_list]
# Add whitelisted client IP addresses/range (in CIDR format) here
```

**Comment by bloomsource** [comment]
今天加了日志看了一下,是个HTTP GET请求,估计是探测匿名http服务器端口

**Comment by bloomsource** [comment]
> @bloomsource @lizhaode Yes! It's **GFW**. It should be something like [`active probing`](https://blog.torproject.org/learning-more-about-gfws-active-probing-system). I'm not sure if adding [`local.acl`](https://github.com/shadowsocks/shadowsocks-libev/blob/master/acl/local.acl) rules for `ss-server` really helps. But you can try it anyway. The syntax goes like this:
> 
> ```
> [reject_all]
> 
> [white_list]
> # Add whitelisted client IP addresses/range (in CIDR format) here
> ```

i write a tool to generate iptables script from database.

**Comment by PantherJohn** [comment]
@bloomsource So did you solve the problem? I don’t think that’s possible.

**Comment by bloomsource** [comment]
> @bloomsource So did you solve the problem? I don’t think that’s possible.

block ip with iptables.

**Comment by bloomsource** [comment]
> > generate iptables script from database
> 
> @bloomsource Interesting, do you mean "geolocation ip database"?

no, the black ip is on mysql database, the script is php script.
i add it to crontab to run each half hour, when i want to block a ip, just add a record on database.
