### ISSUE TITLE
can not get static build of shadowsocks-libev（无法构建静态二进制文件）

### ISSUE THREAD

**Issue by tonyank** [shadowsocks/shadowsocks-libev#2188]
I tried to add an option _--enable-static_ to get a static build and found the same file with same md5 checksum. So I realized that maybe it's not the right place I've changed. So here is my question, how could I build a static version of shadowsocks-libev and run it in another machine with different environmet ?
Thanks in advance.

我想要构建一个静态版的 shadowsocks-libev 以便在另一台不同环境的机器上使用。
我尝试使用 --enable-static 进行编译配置，但是构建出来的二进制文件仍然无法在另一台机器上运行，总提示我缺少 xx 库。
我看了一下 configure 的 help，好像这个选项是用来导入第三方库的。
有什么好的建议吗？谢谢！

**Comment by chenhw2** [comment]
https://hub.docker.com/r/chenhw2/libev-build/

### Usage: get statically linked ELF 64-bit (If NOT sure, use glibc)
```
$ docker run --rm -v /tmp:/to chenhw2/libev-build:glibc sh -c 'cp /usr/bin/ss-* /to; cp /usr/bin/ssr-* /to; cp /usr/bin/obfs-* /to'
$ docker run --rm -v /tmp:/to chenhw2/libev-build:musl  sh -c 'cp /usr/bin/ss-* /to; cp /usr/bin/ssr-* /to; cp /usr/bin/obfs-* /to'
```

**Comment by tonyank** [comment]
> https://hub.docker.com/r/chenhw2/libev-build/
> 
> ### Usage: get statically linked ELF 64-bit (If NOT sure, use glibc)
> ```
> $ docker run --rm -v /tmp:/to chenhw2/libev-build:glibc sh -c 'cp /usr/bin/ss-* /to; cp /usr/bin/ssr-* /to; cp /usr/bin/obfs-* /to'
> $ docker run --rm -v /tmp:/to chenhw2/libev-build:musl  sh -c 'cp /usr/bin/ss-* /to; cp /usr/bin/ssr-* /to; cp /usr/bin/obfs-* /to'
> ```

any ideas without using docker ?

**Comment by chenhw2** [comment]
@tonyank U can learn from its Dockerfile

**Comment by chenhw2** [comment]
@tonyank  https://gist.github.com/chenhw2/e57359378cd4699d19d10eb34f8069b4#file-cross_and_static_compile_shadowsocks-libev-sh-L118
