### ISSUE TITLE
Shadowsocks-libev ban any ip address

### ISSUE THREAD

**Issue by Jihadist** [shadowsocks/shadowsocks-libev#2190]
### What version of shadowsocks-libev are you using?
3.2.0

### What operating system are you using?
Ubuntu 16.04.5 as server

### What did you do?
Connect to vps using the latest version of shadowsocks-android and outline

### What did you expect to see?
tcp connection established successfully

### What did you see instead?
Oct 10 12:16:24 ip-xxx-xxx-xxx-xxx ss-server[21512]:  2018-10-10 12:16:24 ERROR: Access denied from my_ip

### What is your config in detail (with all sensitive info masked)?
config.json
```
{
    "server":"xxx.xxx.xxx.xxx",
    "server_port":443,
    "local_port":1080,
    "password":"****************",
    "timeout":600,
    "method":"aes-256-cfb",
    "fast_open": false
}
```
ss-server.service
```
[Unit]
Description=Shadowsocks server
After=network.target

[Service]
LimitNOFILE=49152
ExecStart=/usr/local/bin/ss-server -c /etc/shadowsocks/s2.json --acl /etc/shadowsocks/local.acl -v
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
```
local.acl contains my home static ip address so this ip wasnt banned unlike any other ip. I think autoban block any requests from any ip's not included in  whitelist in local.acl. At first i had thought it's only bug in android client, but i tried shadowsocks-libev as a client too and my ip was banned. I'm really baffled by this and havent any ideas why smth went wrong.

**Comment by madeye** [comment]
Post you local.acl and full logs here.

If you're using white list mode in ACL file, it means any request from IPs not included in white list will be blocked.
