### ISSUE TITLE
environment variables DNS_ADDRS does not match between docker hub and Dockerfile/README.md

### ISSUE THREAD

**Issue by laris** [shadowsocks/shadowsocks-libev#2191]
Could update Dockerfile and README.md?

https://hub.docker.com/r/shadowsocks/shadowsocks-libev/
pull & docker run & docker inspect and grep DNS ENV
```
"DNS_ADDR=8.8.8.8",
"DNS_ADDR_2=8.8.4.4"
```

https://github.com/shadowsocks/shadowsocks-libev/blob/master/docker/alpine/README.md
`DNS_ADDRS: DNS servers to redirect NS lookup requests to, defaults to 8.8.8.8,8.8.4.4`

https://github.com/shadowsocks/shadowsocks-libev/blob/master/docker/alpine/Dockerfile
`ENV DNS_ADDRS    8.8.8.8,8.8.4.4`

Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
3.2.0

### What operating system are you using?
Ubuntu/Linux

**Comment by chenhw2** [comment]
It seems that https://hub.docker.com/r/shadowsocks is a offical maintained docker.

**Comment by laris** [comment]
Ohmm, this branch was forked from clowwind, but who is the maintainer for 
https://hub.docker.com/r/shadowsocks ?
Sounds like no upstream code now?
