### ISSUE TITLE
ss-manager: unable to create working directory

### ISSUE THREAD

**Issue by billzhong** [shadowsocks/shadowsocks-libev#2194]
### What version of shadowsocks-libev are you using?
3.2.0

### What operating system are you using?
CentOS 7 x64

### What did you do?
Running ss-manager under nobody:nobody

### What did you expect to see?
Successful running

### What did you see instead?
ERROR: mkdir: Permission denied
ERROR: unable to create working directory

### What is your config in detail (with all sensitive info masked)?
```json
{
    "server":"0.0.0.0",
    "server_port":8388,
    "password":"barfoo!",
    "timeout":60,
    "method":"chacha20-ietf-poly1305"
}
```
```
[Unit]
Description=Shadowsocks-libev Default Server Service
Documentation=man:shadowsocks-libev(8)
After=network.target network-online.target

[Service]
Type=simple
EnvironmentFile=/etc/sysconfig/shadowsocks-libev
User=nobody
Group=nobody
LimitNOFILE=32768
ExecStart=/usr/bin/ss-manager -c "$CONFFILE" $DAEMON_ARGS
CapabilityBoundingSet=CAP_NET_BIND_SERVICE

[Install]
WantedBy=multi-user.target
```
```
START=yes
CONFFILE="/etc/shadowsocks-libev/config.json"
DAEMON_ARGS="-u --manager-address 127.0.0.1:6001"
USER=nobody
GROUP=nobody
MAXFD=32768
```

Usually, user `nobody` doesn't have home directory. But [manager.c#L1134](https://github.com/shadowsocks/shadowsocks-libev/blob/master/src/manager.c#L1134) shows working directory is hardcoded to home directory. It will be great if working directory can fallback to something like /tmp. If possible, please add config or parameter to support custom working directory.

Thanks.

**Comment by madeye** [comment]
Please try 1acdb19

**Comment by madeye** [comment]
Keep in mind that running `ss-manager` is not designed for running in a user without home directory.

**Comment by axot** [comment]
The issue still happen.
