### ISSUE TITLE
可以访问YouTube，Google，但是无法在手机上使用Instagram软件

### ISSUE THREAD

**Issue by YuXiaoCoder** [shadowsocks/shadowsocks-libev#2195]
### What version of shadowsocks-libev are you using?

+ `shadowsocks-libev`: `3.2.0`，最新的git clone也尝试过
+ `kcptun`: `20181002`

### What operating system are you using?

+ `OS`: `Ubuntu 18.04.1 LTS`
+ `Kernel`: `4.15.0-36-generic`
+ `Docker`: `18.06.1-ce`

### What did you do?

+ 我使用`docker`部署了`shadowsocks-libev`，以及`kcptun`，可以正常访问`YouTube`、`Google`，但是无法使用`APP`访问`Instagram`，可以在浏览器中访问。

### What did you expect to see?

+ 希望能在安卓手机上正常使用`Instagram`的`APP`。

### What did you see instead?

```text
2018/10/16 14:13:18 stream closed
2018/10/16 14:13:18 stream closed
2018/10/16 14:13:18 stream opened
2018/10/16 14:13:18 stream opened
2018-10-16 14:13:18 ERROR: fast_open_connect: Address not available
2018-10-16 14:13:18 ERROR: getpeername: Socket not connected
```

### What is your config in detail (with all sensitive info masked)?

+ `Server`端：

```text
docker run -dt --restart always --name server-443 -p 6443:6443 -p 8443:8443/udp shadowsocks -x -m "ss-server" -c "-s 0.0.0.0 -p 6443 -m chacha20-ietf-poly1305 -k Xin&Xiao --fast-open -u" -X -M "kcp-server" -C "-t 127.0.0.1:6443 -l :8443 -mode fast2"
```

+ 相当于:

```text
ss-server -s 0.0.0.0 -p 6443 -m chacha20-ietf-poly1305 -k Xin&Xiao --fast-open -u
kcp-server -t 127.0.0.1:6443 -l :8443 -mode fast2
```

### Dockerfile

```text
FROM alpine:3.8

ENV TZ "Asia/Shanghai"
ENV SS_VERSION "3.2.0"
ENV KCP_VERSION "20181002"

RUN apk upgrade && \
  apk add bash tzdata libsodium rng-tools && \
  ln -sf /usr/share/zoneinfo/${TZ} /etc/localtime && \
  echo ${TZ} > /etc/timezone && \
  apk add --virtual .build-deps \
  build-base autoconf automake xmlto libtool linux-headers \
  c-ares-dev libev-dev udns-dev libsodium-dev mbedtls-dev pcre-dev \
  tar curl git && \
  curl -sSLO https://github.com/shadowsocks/shadowsocks-libev/releases/download/v${SS_VERSION}/shadowsocks-libev-${SS_VERSION}.tar.gz && \
  tar -zxf shadowsocks-libev-${SS_VERSION}.tar.gz && \
  cd shadowsocks-libev-${SS_VERSION} && \
  ./configure --prefix /usr/ --disable-documentation && \
  make install && \
  cd - && \
  git clone https://github.com/shadowsocks/simple-obfs.git && \
  cd simple-obfs && \
  git submodule update --init --recursive && \
  ./autogen.sh && ./configure --disable-documentation && \
  make && make install && \
  cd - && \
  curl -sSLO https://github.com/xtaci/kcptun/releases/download/v${KCP_VERSION}/kcptun-linux-amd64-${KCP_VERSION}.tar.gz && \
  tar -zxf kcptun-linux-amd64-${KCP_VERSION}.tar.gz && \
  mv server_linux_amd64 /usr/bin/kcp-server && \
  mv client_linux_amd64 /usr/bin/kcp-client && \
  runDeps="$( \
    scanelf --needed --nobanner /usr/bin/ss-* /usr/local/bin/obfs-* \
      | awk '{ gsub(/,/, "\nso:", $2); print "so:" $2 }' \
      | xargs -r apk info --installed \
      | sort -u \
  )" && \
  apk add --virtual .run-deps ${runDeps} && \
  apk del .build-deps && \
  rm -rf shadowsocks-libev-${SS_VERSION} && \
  rm -f shadowsocks-libev-${SS_VERSION}.tar.gz && \
  rm -rf kcptun-linux-amd64-${KCP_VERSION}.tar.gz && \
  rm -rf /var/cache/apk/*

ADD entrypoint.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
```

**Comment by YuXiaoCoder** [comment]
+ sysctl.conf

**Comment by madeye** [comment]
Disable IPv6 on your server.

**Comment by YuXiaoCoder** [comment]
/etc/sysctl.conf

**Comment by YuXiaoCoder** [comment]
root@SS:~# docker ps --no-trunc 
CONTAINER ID                                                       IMAGE               COMMAND                                                                                                                                                                                 CREATED             STATUS              PORTS                                            NAMES
f1a48fbc56b4f0c85d1b8c0d27ba249e9ac6283934de598c29abaea1069c7221   shadowsocks:1.0     "/entrypoint.sh -X -M kcp-client -C '-r 127.0.0.1:8163 -l :163 -mode fast2'"                                                                                                            18 minutes ago      Up 5 minutes                                                         client-163
fad974e831d159c0c205a1939045b863deea445b18ae6d66b458112202565dae   shadowsocks:1.0     "/entrypoint.sh -x -m ss-server -c '-s 0.0.0.0 -p 6163 -m chacha20-ietf-poly1305 -k M0ZmRXJtaGE= --fast-open -u' -X -M kcp-server -C '-t 127.0.0.1:6163 -l 0.0.0.0:8163 -mode fast2'"   18 minutes ago      Up 5 minutes        0.0.0.0:6163->6163/tcp, 0.0.0.0:8163->8163/udp   server-163

**Comment by YuXiaoCoder** [comment]
关闭安卓手机客户端的, IPV6 路由转发就好了
