### ISSUE TITLE
升级ss服务端后无法连接

### ISSUE THREAD

**Issue by pigpigabc123** [shadowsocks/shadowsocks-libev#2196]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
v3.2.0

### What operating system are you using?
centos 7

升级ss服务端后无法连接,日志报错：
 2018-10-16 15:40:38 ERROR: fast_open_connect: Invalid argument
 2018-10-16 15:40:38 ERROR: getpeername: Transport endpoint is not connected
关了fast_open后仍是无法连接，日志报错：
 2018-10-16 15:48:38 ERROR: Invalid argument

其他：用kcptun加速，上一版本ss服务端没问题

**Comment by PantherJohn** [comment]
@pigpigabc123 Have you even enabled TCP Fast Open in `sysctl.conf`? Post your server/client config in detail here.

**Comment by pigpigabc123** [comment]
> @pigpigabc123 Have you even enabled TCP Fast Open in `sysctl.conf`? Post your server/client config in detail here.

sysctl.conf:
net.ipv4.tcp_fastopen = 3

server:    vision: 3.2.0
{
    "server":"0.0.0.0",
    "server_port":9988,
    "local_address": "127.0.0.1",
    "local_port":1080,
    "password":"6666666",
    "timeout":60,
    "method":"chacha20",
    "fast_open":true
}

client:(luci-app，over kcptun)  vision: 3.2.0
config servers
	option auth '0'
	option server '127.0.0.1'
	option timeout '60'
	option alias 'do_kcp'
	option server_port '2236'        #kcptun port
	option password '6666666'
	option encrypt_method 'chacha20'
	option no_delay '0'
	option fast_open '1'

服务端重新编译安装3.1.3 版用恢复正常，客户端3.2.0 。配置文件不变。

**Comment by flipphos** [comment]
Remove the following two lines in your server config and try the v3.2.0 again. 
"local_address": "127.0.0.1",
"local_port":1080,



> 在 2018年10月17日，19:43，pigpigabc123 <notifications@github.com> 写道：
> 
> "local_address": "127.0.0.1",
> "local_port":1080,

**Comment by pigpigabc123** [comment]
> Remove the following two lines in your server config and try the v3.2.0 again. "local_address": "127.0.0.1", "local_port":1080,
> […](#)
> 在 2018年10月17日，19:43，pigpigabc123 ***@***.***> 写道： "local_address": "127.0.0.1", "local_port":1080,

It works.
