### ISSUE TITLE
如何在路由上透明代理到局域网其它IP上

### ISSUE THREAD

**Issue by foxconndmd** [shadowsocks/shadowsocks-libev#2201]
路由器性能较差，想在本地其它机器上运行ss-redir，然后在路由器上做规则匹配然后重定向到运行ss-redir的机器上，REDIRECT只支持在路由器上，试了DNAT好像不行，tcp端口转发性能差。
请问有什么好的方法可以实现？

**Comment by Gintoki1ku** [comment]
@foxconndmd 可以测试下 https://github.com/zfl9/ss-tproxy 这个项目，我昨天试了下部署在一台老电脑上，速度完全ok，跟本机跑没什么区别（部署的主机需要开启ipv4转发，然后把路由器上dhcp的dns和网关修改为该主机的内网ip）

**Comment by foxconndmd** [comment]
@Gintoki1ku 谢谢，看样子只有将安装ss-redir的主机当成默认路由了。

**Comment by babylon882004** [comment]
可以主路由上使用iproute2中的多路由表加ip rule把境外ip的路由指向另一台跑ss-redir的机器就好啦！

Max Lv <notifications@github.com> 于2018年11月7日周三 上午10:37写道：

**Comment by foxconndmd** [comment]
@babylon882004 
谢谢，这个方法好。
