### ISSUE TITLE
ss-local ss-redir ss-tunnel 如何指定侦听的 ipv6 地址？

### ISSUE THREAD

**Issue by quanmqiu** [shadowsocks/shadowsocks-libev#2204]
shadowsocks-libev 3.2.0
OpenWRT 18.06

ss 客户端，使用 .json 文件配合系统服务，json 文件正确无误。
给本地网卡配置了 `fe80::1234:1234:1234:1234` 的静态 link-local 地址
```
ss-local -b :: -c shadowsockslocal6.json
ss-redir -b :: -c shadowsocksredir6.json
ss-tunnel -b :: -c shadowsockstunnel6.json -L [2001:4860:4860::8888]:53 -u
```
以上三句工作正常，局域网内其它电脑使用 link-local 地址全部可以正常访问以上三个服务。

但是如果 -b 指定侦听 link-local 地址，则服务启动不起来。
如果运行
`ss-tunnel -b fe80::1234:1234:1234:1234 -c shadowsockstunnel6.json -L [2001:4860:4860::8888]:53 -u`
会显示如下错误：
```
INFO: listening at fe80::1234:1234:1234:1234:536
ERROR: bind: Invalid argument
ERROR: bind() error
```

如果运行
`ss-tunnel -b [fe80::1234:1234:1234:1234] -c shadowsockstunnel6.json -L [2001:4860:4860::8888]:53 -u`
会显示如下错误：
```
INFO: listening at [fe80::1234:1234:1234:1234]:536
INFO: getaddrinfo: Name does not resolve
ERROR: bind() error
```

请问 ss-local ss-redir ss-tunnel 这三个如何指定侦听的 ipv6 地址(global 或者 link-local 地址)，而不是侦听所有地址？

**Comment by madeye** [comment]
I cannot reproduce your issue locally.

First make sure the binding IPv6 address is valid.

**Comment by quanmqiu** [comment]
进一步尝试

使用 global 地址
`ss-tunnel -b [global] -c shadowsockstunnel6.json -L [2001:4860:4860::8888]:53 -u`
报错
```
INFO: getaddrinfo: Name does not resolve
ERROR: bind() error
```

使用不带 [] 括号的 global 地址则工作正常，于是可以确定几件事情：

1. -b 选项后面 ipv6 地址不能加 [] 括号，加 [] 会报 getaddrinfo: Name does not resolve 地址格式错误。
2. -b 加 global 地址和 :: 都工作正常；
3. -b 加 link-local 地址会报 bind: Invalid argument 错误。

现在问题在第3点上，搜了一下，找到一个[可能的原因](https://stackoverflow.com/questions/30984656/socket-programming-bind-invalid-argument)，即 link-local 地址因为多个 interface，需要指定 interface 才能成功 bind。

**Comment by quanmqiu** [comment]
原本的打算是只监听路由器内网的请求，所以才打算绑定到 link-local 地址上，没想到绑定 link-local 地址还需要程序特殊处理。

在不修改代码的前提下，有两个解决办法：
1、使用ULA地址，已经测试通过，可以正常工作。
2、继续使用 -b ::，然后利用 openwrt 的防火墙阻止外来访问。
