### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by LiveChief** [shadowsocks/shadowsocks-libev#2207]
How in the world do i turn this into a config???
ss-server -p 443 -k PASSWORD_HERE -m aes-256-gcm -t 60 -u --reuse-port --fast-open --no-delay --plugin obfs-server --plugin-opts "obfs=tls"

/etc/shadowsocks-libev/config.json  

    "server_port":443,
    "password":"PASSWORD_HERE",
    "timeout":60,
    "method":"aes-256-gcm",
    "fast_open":true,

**Comment by PantherJohn** [comment]
@LiveChief Take a look at [`this`](https://github.com/shadowsocks/shadowsocks-libev/blob/master/doc/shadowsocks-libev.asciidoc#config-file).

**Comment by LiveChief** [comment]
Thanks

**Comment by LiveChief** [comment]
{
    "server":["[::0]","0.0.0.0"],
    "server_port":443,
    "password":"PASSWORD_HERE",
    "timeout":300,
    "user":"nobody",
    "method":"aes-256-gcm",
    "fast_open":true,
    "reuse_port":true,
    "no_delay":true,
    "plugin":"obfs-server",
    "plugin-opts":"obfs=tls",
    "mode":"tcp_and_udp"
}
