### ISSUE TITLE
ss-manager多端口总是一段时间会掉线的问题

### ISSUE THREAD

**Issue by Splaser** [shadowsocks/shadowsocks-libev#2209]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
latest

### What operating system are you using?
debian 9

### What did you do?
using command line 
for single port 12345:
nohup /usr/local/bin/ss-server -uc /etc/shadowsocks-libev/config.json > /dev/null 2>&1 &
for multi ports 23456-23556:
nohup ss-manager -c /etc/shadowsocks-libev/manager.json --manager-address 0.0.0.0:6001 > /dev/null 2>&1 &

### What did you expect to see?
ports 23456-23556 working stably as the port 12345

### What did you see instead?
ports 23456-23556 got continuously lost connection with clients
port 12345 from ss-server works perfectly though
### What is your config in detail (with all sensitive info masked)?
manager.json:
{
        "server":"0.0.0.0",
        "port_password": {
         //masked
},       
"timeout": 300,
        "method": "aes-192-gcm",
        "mode":"tcp_and_udp",
        "reuse_port": true
}

singleport json:
{
    "server":"0.0.0.0",
    "server_port":12345,
    "password":"masked",
    "timeout":300,
    "user":"nobody",
    "method":"aes-192-gcm",
    "fast_open":false,
    "nameserver":"8.8.8.8",
    "mode":"tcp_and_udp"

}

**Comment by madeye** [comment]
Cannot reproduce locally. Please make sure sub-processes are not killed.

**Comment by Splaser** [comment]
Maybe I got tcp jammed by GFW, I guess? sub-processes were all active.

**Comment by madeye** [comment]
Abnormal traffic on high TCP ports are likely blocked by ISP or your service provider's firewall.

Try lower ports, like 1024 to 2048, instead.
