### ISSUE TITLE
ss-local hanging on listening

### ISSUE THREAD

**Issue by liyucun** [shadowsocks/shadowsocks-libev#2212]
### What version of shadowsocks-libev are you using?
3.2.0

### What operating system are you using?
OS X

### What did you do?
```
ss-local -s xx.xxx.xxx.xx -p 443 -l 1080 -k xxxx -m aes-256-cfb -v
```

### What did you expect to see?
ss-local should be able to receive connections and forward it to ss-server

### What did you see instead?
```
 2018-11-10 11:14:42 INFO: initializing ciphers... aes-256-cfb
 2018-11-10 11:14:42 INFO: listening at 127.0.0.1:1080
```
It's hanging on this state, and seems like it can't receive any connections. I tried to `lsof -i:1080`:
```
COMMAND    PID  USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
ss-local 24876 xxxx    6u  IPv4 0xb7655a3ec99b2f03      0t0  TCP localhost:socks (LISTEN)
```

### What is your config in detail (with all sensitive info masked)?
you can refer config i use in the command line tool. I have tried to use the same config in my phone and other computers, and it all works, but not sure why this does't work on my computers(well, there are two computers can't use it).

**Comment by SEER2** [comment]
I found the question almost the same as you described. My system is fedora 29.

I installed shadowsocks-libev by dnf install. And I try python shadowsocks, they all perform as you said. Then I try shadowsocks-go, which give me messages as below

Maybe the shadowsocks server side not supported ?

$ ./shadowsocks-local -c /etc/shadowsocks-libev/config.json
2018/11/28 20:14:29 available remote server ---.---.---.---:---
2018/11/28 20:14:29 starting local socks5 server at :1080 ...
2018/11/28 20:14:41 socks handshake: socks version not supported
2018/11/28 20:14:41 socks handshake: socks version not supported
2018/11/28 20:14:41 socks handshake: socks version not supported
2018/11/28 20:14:41 socks handshake: socks version not supported
