### ISSUE TITLE
How can I find the old release's api URL?

### ISSUE THREAD

**Issue by moerfutin** [shadowsocks/shadowsocks-libev#2214]
### What version of shadowsocks-libev are you using?
V3.2.1

### What operating system are you using?
DEBIAN 8 X64

### What did you do?
to leap over the GFW

### What did you expect to see?
to use it smoothly

I find the latest release v3.2.1  and the latest windows client 4.1.2 , they cant work together. So I need to downgrade, but I find the https://api.github.com/repos/shadowsocks/shadowsocks-libev/releases/latest 
for the latest version's tag. How can I find the V3.1.3's tag url? thanks.

**Comment by studentmain** [comment]
You should read github's document. Just change `latest` to version you want.

**Comment by studentmain** [comment]
> they cant work together

They should work together, maybe you misconfigured them, or it's just a bug.

**Comment by PantherJohn** [comment]
@moerfutin Are you using `ss-tunnel`? Copying n pasteing your server/cli conf and logs here may help us track issues. Why bother API releases anyway? for past releases are available (here)[https://github.com/shadowsocks/shadowsocks-libev/releases/tag/v3.1.3]

**Comment by madeye** [comment]
Remove any `local_addr` section from your config file.
