### ISSUE TITLE
Shadowsocks-libev 3.2.1 exit unexpectedly in 32bit Debian GNU/Linux 9 (stretch) 

### ISSUE THREAD

**Issue by jresins** [shadowsocks/shadowsocks-libev#2215]
Shadowsocks-libev 3.2.0 works great with the same config in 32bit Debian stretch, but when upgrade to 3.2.1, it will start successfully and then exit unexpectedly.  3.2.1 works great in 64bit Debian stretch.

libsodium-1.0.16
mbedtls-2.13.0

### What version of shadowsocks-libev are you using?
3.2.1

### What operating system are you using?
Debian GNU/Linux 9 (stretch)
Linux debian 4.9.0-8-686-pae #1 SMP Debian 4.9.110-3+deb9u6 (2018-10-08) i686 GNU/Linux

### What did you do?
upgrade shadowsocks-libev from v3.2.0 to v3.2.1

### What did you expect to see?
works well.

### What did you see instead?
ss-server start successfully and then exit with log such as:

> debian kernel: [87801.943862] traps: ss-server[29301] general protection ip:b771b9cc sp:bfbf1be0 error:0
> debian kernel: [87801.943970]  in libsodium.so.23.1.0[b76e3000+65000]

### What is your config in detail (with all sensitive info masked)?
    "server":"0.0.0.0",
    "server_port":20000,
    "password":"password string",
    "timeout":300,
    "user":"nobody",
    "method":"aes-256-gcm",
    "fast_open":false,
    "nameserver":"8.8.8.8",
    "mode":"tcp_and_udp",
    "plugin":"obfs-server",
    "plugin_opts":"obfs=http"

**Comment by madeye** [comment]
Please try to run it with valgrind and post the log here.

**Comment by madeye** [comment]
It looks a bug of libsodium. The library crashed at this line:

https://github.com/jedisct1/libsodium/blob/master/src/libsodium/crypto_aead/aes256gcm/aesni/aead_aes256gcm_aesni.c

I'm afraid libsodium may not test with 32bit before, as it's assuming AESNI is enabled.

**Comment by yousong** [comment]
I am confused.  Is this alignment requirement from libsodium on `aes256gcm_ctx`?  But libsodium docs explicitly stated that pointers alignment is not an requirement (https://libsodium.gitbook.io/doc/internals#alignment-and-endianness)

**Comment by madeye** [comment]
It's the alignment requirement for `crypto_aead_aes256gcm_state`, not for the plain/cipher text. 

https://github.com/jedisct1/libsodium-doc/blob/master/secret-key_cryptography/aes-gcm_with_precomputation.md#aes256-gcm-with-precomputation
