### ISSUE TITLE
Cannot install via apt-get in Debian 7

### ISSUE THREAD

**Issue by elvisw** [shadowsocks/shadowsocks-libev#222]
run `sudo apt-get install shadowsocks-libev` with error

>The following packages have unmet dependencies:
 shadowsocks-libev : Depends: libc6 (>= 2.14) but 2.13-38+deb7u6 is to be instal
led
>E: Unable to correct problems, you have held broken packages.

**Comment by elvisw** [comment]
已经恢复正常，多谢

**Comment by yywudi** [comment]
遇到同样问题，debian 7.8 64bit apt-get install shadowsocks-libev 还是会报同样的错
> shadowsocks-libev : Depends: libc6 (>= 2.14) but 2.13-38+deb7u6 is to be instal

但是debian 7.8 32bit 下有正常，不要求libc6 >=2.14
>dpkg --status shadowsocks-libev
>Package: shadowsocks-libev
>Architecture: i386
>Version: 2.0.7-1
>Replaces: shadowsocks (<< 1.5.3-2)
>Depends: libc6 (>= 2.9), libssl1.0.0 (>= 1.0.0)

**Comment by elvisw** [comment]
64位貌似还不行，不过64位的话内存肯定够，直接上Python版的好了。要不你重开一个Issue？ @yywudi

**Comment by yywudi** [comment]
hmm，很多lowendbox的VPS也只提供64位的debian。
不过64位的Debian 7 git了code自己用dpkg-buildpackage 又是好的，正常安装使用没报错。

不过话说我也是发现回个comment不会把这个issue re-open..

**Comment by elvisw** [comment]
貌似只有项目作者才能reopen?  @yywudi
