### ISSUE TITLE
arm 一堆的库,还编译不起来   解决办法:

### ISSUE THREAD

**Issue by ugksoft** [shadowsocks/shadowsocks-libev#2220]
实际还需要ev   c-ares, sodium 三个库

在arm上,根本编译不过

需要ev需要fences指令支持, 不可能因为装个软件, 去升级内核,升级std库等
/*
我是 arm-none-linux-gnueabi  -v
.....
gcc version 4.2.3 (Sourcery G++ Lite 2008q1-126)
)
*/

ev.c顶部,添加"#define ECB_AVOID_PTHREADS 1"
ev编译通过

libcork 需要 __sync_val_compare_and_swap_4  功能是比较值(4byte的类型),不同,就更新,并返回旧值
详见
https://www.jianshu.com/p/da1d69f0a6ad

在./libcork/include/libcork/threads/atomics.h中
自己去实现cork_int_cas cork_ptr_cas 一下

src/makefile中,删掉werror选项,避免因警告不能编译通过

./libcork/include/libcork/config/gcc.h中CORK_CONFIG_HAVE_GCC_ATOMICS 改成0

OK,现在编译全部通过 

肯定需要需要拷 libpcre.so.* libsodium.so.* libcares.so.* libev.so.*到 /lib或/usr/lib
  可能还需要zlib openssl的so看你的arm环境

 aes-128这类的运行正常

----------------------------------------------------------------

但是,方法设成chacha20,必然Segmentation fault.
gdb初步检查一下,确认在下面函数时,崩溃
./src/libsodium/crypto_aead/chacha20poly1305/sodium/aead_chacha20poly1305.c
crypto_aead_chacha20poly1305_ietf_decrypt_detached函数

因为arm条件有限,所以没有进一步细细的去查

老大,有空检查一下,吧, server的稳定性很重要的
安卓上,用SSR客户端,测试的

**Comment by rogers0** [comment]
it builds well on all architectures on debian, including armel, armhf, and arm64.
- https://buildd.debian.org/status/package.php?p=shadowsocks-libev

**Comment by ugksoft** [comment]
楼上啊, linux碎片化太过严重,就算对应版本号的发行版,也不能保证肯定支持, 库版本限制更新个库,要是kernel限制或是基础bash都要用到的库也去更新, 动静就太大了, ARM时,很多时候这些数据在rom区, 

我已经编译成功了,上面给出了如何编译成功的方法了

但是ss-libev有大bug, 客户端加密方法选错,服务端直接Segmentation fault,太严重了点

都是中国,就不要英文回复了吧, 就算你想为外国人也能看的懂, 但本身这个ss/ssr肯定是国人在用的

**Comment by studentmain** [comment]
> 但本身这个ss/ssr肯定是国人在用的

不见得，俄罗斯和伊朗的同志们也处于水深火热中。与此同时，欧美国家的开发者们也在此项目的基础上开发软件。

**Comment by PantherJohn** [comment]
@ugksoft The only word I can understand: `hellworld`

Instead of dumping cynical words here you can create pull requests. That would be appreciated for sure if you do it right.

**Comment by studentmain** [comment]
shadowsocks c#最新版本是两个月前的4.1.2，你哪搞到4.9.0的……
如果你是说shadowsocksr那一套，那肯定不兼容啊。
