### ISSUE TITLE
ERROR: getpeername: Socket not connected，只有部分https正常使用

### ISSUE THREAD

**Issue by mailshuxin** [shadowsocks/shadowsocks-libev#2221]
### What version of shadowsocks-libev are you using?
shadowsocks-libev-ss-server	3.1.3-2

### What operating system are you using?
OpenWrt 18.06.1

### What did you do?
使用ss-server安装在国外路由器上

### What did you expect to see?
访问https网站

### What did you see instead?
路由器ss-server日志错误，提示
ERROR: getpeername: Socket not connected

但是相当一部分的https网站可以正常使用，只有一部分提示错误

ERR_SSL_PROTOCOL_ERROR

### What is your config in detail (with all sensitive info masked)?
{
    "server":"0.0.0.0",
    "server_port":10001,
    "local_address": "0.0.0.0",
    "local_port":1081,
    "password":"*******",
    "timeout":300,
    "method":"rc4-md5"
}

**Comment by madeye** [comment]
Make sure you have setup DNS forwarding correctly.

**Comment by madeye** [comment]
"getpeername: Socket not connected" means the IP cannot be reached by your server.

Enable verbose log on your server to identify the IP that cannot be reached. Typically they would be LAN IPs that be forwarded to the server by mistake.

**Comment by madeye** [comment]
You tried to visit `www.****.com:27904`, and that IP and port cannot be connected from your server.

So, it has nothing to do with HTTPS.

**Comment by PantherJohn** [comment]
@mailshuxin To confirm this issue I suggest you run the following command on your `server` machine:
```
curl -s -o /dev/null -w "%{http_code}" <domain>:<port>
```
or straightforwardly 
```
curl <domain>:<port>
```
`27904`, this is not a common HTTP port. What service are you using then? Unmasking those domains may help if you will.

**Comment by mailshuxin** [comment]
CMD:
curl www.drymt.com:27904
Result:
curl: (7) Failed to connect to www.drymt.com port 27904: Connection refused

CMD:
curl -s -o /dev/null -w "%{http_code}" www.drymt.com:27904
Result:
000

The drymt is my own website, and hostloc.com is the same problem. 
I use nginx reverse proxy on my server.
When is change to  another router (OS:PandoraBox) and it's normal,  so i think my web server is fine. 
I use openwrt 18.06.1, this looks a bit like the ssl certificate is not working properly.

**Comment by PantherJohn** [comment]
@mailshuxin and use `netstat -l` on your **web server** www.***.com to check if it is still listening on port 27904 for **inbound** connections .

**Comment by MiltonLai** [comment]
I think I met the same problem, when run ss-redir in openwrt 18.06.1 as a transparent proxy, I cannot visit Google, Youtube, it says NET::ERR_CERT_COMMON_NAME_INVALID or ERR_TIMED_OUT.
I can visit Weibo Japan, but the speed is very slow 
When use ss-local as a socks5 proxy, all are normal.
