### ISSUE TITLE
Shadowsocks-libev的ss-manager命令是否可以快速开启--fast-open,

### ISSUE THREAD

**Issue by siriusfinex** [shadowsocks/shadowsocks-libev#2222]
Shadowsocks-libev是否可以使用ss-manger ***** --fast-open快捷开启fast open功能？还是说只能以ss-server开启fast open功能？

### What version of shadowsocks-libev are you using?
Shadowsocks-libev 3.2.0

### What operating system are you using?
Debian 9.6

### What is your config in detail (with all sensitive info masked)?
No custom config,only default config.

**Comment by madeye** [comment]
Yes.

**Comment by siriusfinex** [comment]
Thanks!
