### ISSUE TITLE
Cannot get latest version via official repository

### ISSUE THREAD

**Issue by Eintler** [shadowsocks/shadowsocks-libev#2234]
### What version of shadowsocks-libev are you using?
3.1.3

### What operating system are you using?
ubuntu 18.04

### What did you do?
apt update
apt upgrade shadowsocks-libev

### What did you expect to see?
Update ss to latest version

### What did you see instead?

Reading package lists... Done
Building dependency tree
Reading state information... Done
shadowsocks-libev is already the newest version (3.1.3+ds-1ubuntu2).
Calculating upgrade... Done

**Comment by madeye** [comment]
It's expected.

**Comment by PantherJohn** [comment]
@librehat

**Comment by Eintler** [comment]
Is there any progress :)

**Comment by madeye** [comment]
As mentioned in https://github.com/shadowsocks/shadowsocks-libev/issues/2234#issuecomment-442364191, it's expected, since the version in official repo of Ubuntu 18.04 is still 3.1.3.

Upgrade your Ubuntu or try build the project from source code.
