### ISSUE TITLE
someone was try scan the ss port ?

### ISSUE THREAD

**Issue by oneshu** [shadowsocks/shadowsocks-libev#2235]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?

shadowsocks-libev
### What operating system are you using?

ubuntu 18.04
### What did you see instead?

from the var/syslog file , I see a lot of records like:
-----------------------------------------------------------

> 
Nov 29 16:10:36 myserver ss-server[612]:  2018-11-29 16:10:36 ERROR: failed to handshake with 14.204.95.70: authentication error
Nov 29 16:10:37 myserver ss-server[612]:  2018-11-29 16:10:37 ERROR: failed to handshake with 36.5.184.180: authentication error
Nov 29 16:10:37 myserver ss-server[612]:  2018-11-29 16:10:37 ERROR: failed to handshake with 116.252.0.245: authentication error
Nov 29 16:10:37 myserver ss-server[612]:  2018-11-29 16:10:37 ERROR: failed to handshake with 124.88.64.219: authentication error
Nov 29 16:12:52 myserver ss-server[612]:  2018-11-29 16:12:52 ERROR: failed to handshake with 116.252.0.245: authentication error
Nov 29 16:12:52 myserver ss-server[612]:  2018-11-29 16:12:52 ERROR: failed to handshake with 14.204.95.70: authentication error
Nov 29 16:12:54 myserver ss-server[612]:  2018-11-29 16:12:54 ERROR: failed to handshake with 124.88.64.219: authentication error
Nov 29 16:13:01 myserver ss-server[612]:  2018-11-29 16:13:01 ERROR: failed to handshake with 14.204.95.70: authentication error
Nov 29 16:13:12 myserver ss-server[612]:  2018-11-29 16:13:12 ERROR: failed to handshake with 116.252.0.245: authentication error
Nov 29 16:13:33 myserver ss-server[612]:  2018-11-29 16:13:33 ERROR: failed to handshake with 124.88.64.219: authentication error
Nov 29 16:13:33 myserver ss-server[612]:  2018-11-29 16:13:33 ERROR: failed to handshake with 116.252.0.245: authentication error
Nov 29 16:13:38 myserver ss-server[612]:  2018-11-29 16:13:38 ERROR: failed to handshake with 14.204.95.70: authentication error
Nov 29 16:14:40 myserver ss-server[612]:  2018-11-29 16:14:40 ERROR: failed to handshake with 14.204.95.70: authentication error

> 

-----------------------------------------------------------
how to ban them~

**Comment by madeye** [comment]
They will be banned automatically.
