### ISSUE TITLE
Set up/Issues involving using local DNS resolver (Unbound) on server

### ISSUE THREAD

**Issue by sinclair8228** [shadowsocks/shadowsocks-libev#2237]
### What version of shadowsocks-libev are you using?
3.1.3+ds-1ubuntu2

### What operating system are you using?
Ubuntu 18.04 Server

### What did you do?
Tried to set ss-server to use local DNS resolver (Unbound, listening on interface 127.0.0.1) in config.json

### What did you expect to see?
Android client connects and uses local DNS resolver on server

### What did you see instead?
"Failed to connect, Invalid Address"
Works fine with dns set to 8.8.8.8
Also, this configuration used to work perfectly a few months ago

### What is your config in detail (with all sensitive info masked)?
{
    "server":"0.0.0.0",
    "server_port":32769,
    "local_port":1080,
    "password":"<PASSWORD>",
    "timeout":60,
    "fast_open": true,
    "nameserver":"127.0.0.1",
    "method":"chacha20-ietf-poly1305"
}

**Comment by madeye** [comment]
I don't think it's related to this project.

The remote DNS in Android app's setting is literally a "remote" DNS, any local DNS should not work.

**Comment by sinclair8228** [comment]
I could not get it to work with the remote DNS setting on or off. The most interesting part is, this exact configuration used to work perfectly around 6 months ago. Unbound is working for my other services that use it, which leads me to believe this is a Shadowsocks specific issue. What configuration changes can I try to resolve this issue? I considered setting DNS in the app to the IPv4 address of the server, but I am out of ideas otherwise. Tried setting up different listening interfaces in Unbound on different subnets, still the same issue.

**Comment by madeye** [comment]
Let your unbound listen on your server's public IP address, then set remote DNS to be that IP in your Android app.

**Comment by sinclair8228** [comment]
My unbound.conf, if that's helpful:

include: "/etc/unbound/unbound.conf.d/*.conf"
verbosity: 2
val-log-level: 1
max-udp-size: 3072
interface: 127.0.0.1
interface: 10.8.0.1
interface: 10.9.0.1
access-control: 127.0.0.1/32 allow
access-control: 10.8.0.0/16 allow
access-control: 10.9.0.0/16 allow
hide-identity: yes
hide-version: yes
use-caps-for-id: yes
prefetch: yes
prefetch-key: yes
harden-dnssec-stripped: yes
harden-referral-path: yes
unwanted-reply-threshold: 10000000
private-address: 10.0.0.0/8
private-address: 172.16.0.0/12
private-address: 192.168.0.0/16
private-address: 169.254.0.0/16
private-address: fd00::/8
private-address: fe80::/10
private-address: 127.0.0.0/8
private-address: ::ffff:0:0/96

**Comment by sinclair8228** [comment]
Worked perfectly, thank you

**Comment by sinclair8228** [comment]
worked perfectly, thank you
