### ISSUE TITLE
AES-128/192-GCM has no AES-NI support?

### ISSUE THREAD

**Issue by Originalimoc** [shadowsocks/shadowsocks-libev#2238]
### What version of shadowsocks-libev are you using?
3.2.3

### What operating system are you using?
Ubuntu 18.04 LTS w/ 4.15.0 x86_64 manually compiled with libsodium 1.0.16 w/ build-essential (Another issue you state mbedtls is the issue)

### What did you do?
Perform iperf.sh

### What did you expect to see?
AES-128-GCM performs the best on AES-NI machine

### What did you see instead?
It's the slowest

### What is your config in detail (with all sensitive info masked)?
N/A(default iperf.sh 5GiB [Ciphers])

chacha20/chacha20-ietf/salsa20/ 800Mbps
chacha20-ietf-poly1305/xchacha20-ietf-poly1305/aes-128-ctr 600Mbps
aes-128-cfb 540Mbps
aes-128-gcm 350Mbps

1024bytes openssl speedtest:
chacha20-2.1GiB
aes-128-gcm-2.2GiB

So I guess default one(c-i-p) is the best after all?

**Comment by Originalimoc** [comment]
aes-256-gcm 700Mbps _(:з」∠)_ this is the best one.

**Comment by Originalimoc** [comment]
why not use AES-NI on aes-128-gcm when possible?

**Comment by madeye** [comment]
It's a third party issue https://github.com/ARMmbed/mbedtls/issues/1189

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks-libev/issues/2147

**Comment by Originalimoc** [comment]
I know but doesn't libsodium support AES-128-GCM ??

**Comment by madeye** [comment]
Nope.

**Comment by Originalimoc** [comment]
(:з」∠)HA???????
