### ISSUE TITLE
系统日志怎么关

### ISSUE THREAD

**Issue by a-l-e-x-6** [shadowsocks/shadowsocks-libev#2240]
/var/log/message 和 journalctl 里好多ss的错误日志，可以关闭么

>Dec  5 17:38:22 instance-1 /usr/bin/ss-server[17441]: failed to handshake with 144.10.15.207: authentication error
Dec  5 17:38:23 instance-1 /usr/bin/ss-server[17441]: failed to handshake with 144.10.15.207: authentication error
Dec  5 17:38:23 instance-1 /usr/bin/ss-server[17441]: failed to handshake with 144.10.15.207: authentication error
Dec  5 17:38:23 instance-1 /usr/bin/ss-server[17441]: failed to handshake with 144.10.15.207: authentication error

shadowsocks-libev.service
>[Unit]
Description=Shadowsocks Server
After=network.target
[Service]
User=nobody
Group=nobody
Type=forking
PIDFile=/dev/shm/shadowsocks-libev.pid
ExecStart=/usr/bin/ss-server -c /etc/shadowsocks-libev/config.json -f /dev/shm/shadowsocks-libev.pid
TTYPath=null
[Install]
WantedBy=multi-user.target

**Comment by PantherJohn** [comment]
@a-l-e-x-6 A workaround is to redirect stderr messages to `/dev/null`; 

replace `ExecStart` with the following
```
ExecStart=/usr/bin/ss-server -c /etc/shadowsocks-libev/config.json -f /dev/shm/shadowsocks-libev.pid 2>&1
```

**Comment by a-l-e-x-6** [comment]
@PantherJohn 
no effect, still record error message

**Comment by cnJamesLucas** [comment]
ExecStart=/usr/bin/ss-server -c /etc/shadowsocks-libev/config.json -f /dev/shm/shadowsocks-libev.pid > /dev/null 2>&1

**Comment by PantherJohn** [comment]
@cnJamesLucas @a-l-e-x-6 That’s right. I kinda ignored `/dev/null` while typing.
