### ISSUE TITLE
现在ss-redir 支持TCP用TPROXY打标记做透明代理吗

### ISSUE THREAD

**Issue by kalagxw** [shadowsocks/shadowsocks-libev#2241]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
lastest

### What operating system are you using?

linux on arm router

**Comment by smtking** [comment]
No, It only support UDP traffics.
Please use REDIRECT for TCP traffics.
