### ISSUE TITLE
使用 systemctl 无法以守护进程启动 shdowsocks-libev

### ISSUE THREAD

**Issue by dianbanjiu** [shadowsocks/shadowsocks-libev#2242]
### What version of shadowsocks-libev are you using?

shadowsocks-libev 3.2.3

### What operating system are you using?

Arch Linux x86_64

### What did you do?

在自己的物理机上尝试以守护进程启动 shadowsocks-libev，配置文件存放位置 /etc/shadowsocks/config.json 运行了以下命令  
```shell
sudo systemctl start shadowsocks@config
```

### What did you expect to see?

期望成功启动  shadowsocks-libev 的守护进程

### What did you see instead?

```shell
Failed to start shadowsocks@config.service: Unit shadowsocks@config.service not found.
```

### What is your config in detail (with all sensitive info masked)?

```json
{
	"server":"server-adress",
	"server_port":443,
	"local_address":"127.0.0.1",
	"local_port":1080,
	"password":"passwd",
	"timeout":300,
	"method":"aes-256-cfb",
	"fast_open":false,
}

**Comment by hosiet** [comment]
It's shadowsocks-libev@config, not shadowsocks@config.

Besides, we already provides shadowsocks-libev.service on some distributions so you may not want to use shadowsocks-libev@config.service.

**Comment by dianbanjiu** [comment]
> It's shadowsocks-libev@config, not shadowsocks@config.
> 
> Besides, we already provides shadowsocks-libev.service on some distributions so you may not want to use [shadowsocks-libev@config.service](mailto:shadowsocks-libev@config.service).

This solved my problem.  
Thank you very much for your reply.
