### ISSUE TITLE
为什么 aes-256-gcm 比 aes-128-gcm 快这么多？

### ISSUE THREAD

**Issue by pexcn** [shadowsocks/shadowsocks-libev#2243]
使用的是 @madeye 的 https://gist.github.com/madeye/c046fc35e10a82154f4697fb316a7ac6 这个脚本测试的。

测了好几次，都能得到类似的结果：

```bash
$ ./iperf.sh aes-128-gcm
# ...
[  3]  0.0-10.0 sec   249 MBytes   208 Mbits/sec

$ ./iperf.sh aes-256-gcm
# ...
[  3]  0.0-10.0 sec  1.32 GBytes  1.13 Gbits/sec
```

请问这是因为 AES 硬件加速的原因吗？难道是 128 的没加速？

附上 CPU 信息：
![11](https://user-images.githubusercontent.com/4590439/49681326-e5cc8300-fada-11e8-8c7a-615f78992ae4.png)

补充一下：
```bash
mbedtls version: 2.14.1
libsodium version: 1.0.16
shadowsocks-libev version: master branch latest version
```

**Comment by pexcn** [comment]
好像是因为这个原因：https://github.com/shadowsocks/shadowsocks-libev/blob/master/src/aead.c#L169

**Comment by PHCSJC** [comment]
> 好像是因为这个原因：https://github.com/shadowsocks/shadowsocks-libev/blob/master/src/aead.c#L169

老哥，你是说这个吗？
case AES256GCM: // Only AES-256-GCM is supported by libsodium.

**Comment by chenhw2** [comment]
> the libsodium have support for AES-NI (although only for 256bit AES/GCM).

Refer: https://github.com/shadowsocks/shadowsocks-libev/pull/2176
