### ISSUE TITLE
Can not open some websites

### ISSUE THREAD

**Issue by tporwx** [shadowsocks/shadowsocks-libev#2245]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?

3.2.3

### What operating system are you using?

debian 9

### What did you do?

访问网站www.douban.com , www.hostloc.com

### What did you expect to see?

正常打开

### What did you see instead?

无法访问此网站

### What is your config in detail (with all sensitive info masked)?

{
    "server":["::0", "0.0.0.0"],
    "mode":"tcp_and_udp",
    "server_port":31574,
    "local_port":1080,
    "password":"*******",
    "plugin":"obfs-server",
    "plugin_opts":"obfs=http",
    "timeout":300,
    "method":"chacha20-ietf-poly1305"
}

**Comment by madeye** [comment]
It's probably a network issue of your server.

**Comment by tporwx** [comment]
It's a network issue of my server.
