### ISSUE TITLE
shadowsocks-libev  use_syslog option

### ISSUE THREAD

**Issue by fy-captain** [shadowsocks/shadowsocks-libev#2247]
### What version of shadowsocks-libev are you using?
shadowsocks-libev 3.2.0

### What operating system are you using?
CentOS Linux release 7.3.1611

### What did you do?
cat config.json
{
     ... ...

    "timeout":300,
    "method":"xxxx",
    "fast_open":true,
    "use_syslog":true,
}
or
/usr/bin/ss-server  ..... --fast-open --use_syslog 

 the above config is not work. I want to system  log  ss running records, such as communication with other intetnet sites.

Does shadowsocks-libev  support the Logging Function, or will be add the  Logging Function？

**Comment by madeye** [comment]
There is no `use_syslog` option.

Redirect the `stdout` log to any path you like or run shadowsocks in daemon mode with option `-f`.
