### ISSUE TITLE
能否支持直接通过命令行参数指定 acl 配置内容

### ISSUE THREAD

**Issue by sagan** [shadowsocks/shadowsocks-libev#2248]
目前 acl 参数只能通过 --acl <acl_file_path> 的方式设置。

通过 docker 方式部署时会比较麻烦。能否支持直接用命令行参数传入 acl 文件的内容？

### What version of shadowsocks-libev are you using?

shadowsocks-libev 3.2.1

### What operating system are you using?

Docker

**Comment by madeye** [comment]
`echo "acl rules" > /tmp/tmp.acl && ss-server --acl /tmp/tmp.acl ...`

**Comment by PantherJohn** [comment]
@sagan What about `mkfifo`?
