### ISSUE TITLE
请问 -d 选项是否支持指定端口？

### ISSUE THREAD

**Issue by linsui** [shadowsocks/shadowsocks-libev#2249]
### What version of shadowsocks-libev are you using?
3.23

### What operating system are you using?
Ubuntu 16.04

### What did you do?
我搭建了一个本地DNS服务器，监听10000端口，设置为 -d 127.0.0.1:10000

### What did you see instead?
Unable to resolve 

### What is your config in detail (with all sensitive info masked)?
ss-server 0.0.0.0 -u -6 -d 127.0.0.1:10000

**Comment by madeye** [comment]
Nope. Only port 53 will be used.

**Comment by linsui** [comment]
谢谢。请问是否有办法更改 DNS 端口？或者添加对 DoT 和 DoH 的支持？

**Comment by madeye** [comment]
Try https://github.com/shadowsocks/overture

**Comment by linsui** [comment]
使用 overture 仍然需要绑定 53 端口，也就必须有 root 权限。所以如果 ss 可以支持指定 dns 端口就最好了 :joy:

**Comment by madeye** [comment]
Tried ss-server with a local resolver, IPv6 addresses can be resolved as expected.

**Comment by linsui** [comment]
使用系统默认 DNS 可以正确解析，但这个结果会被污染所以我不得不搭建一个本地的 DNS 服务器通过 DoT 解析。我不知道是不是因为 DoT 需要更长时间所以 ss 会报错

**Comment by linsui** [comment]
经过验证确实是 timeout 的问题，之前我使用的是一个单线程的 DoT， 现在换了另一个 DoH 之后解析速度提高了很多，没有再报错。
