### ISSUE TITLE
ss-manager如何统计流量？

### ISSUE THREAD

**Issue by Andesome** [shadowsocks/shadowsocks-libev#2254]
### What version of shadowsocks-libev are you using?
3.2.0

### What operating system are you using?
centos 7.

### What did you do?
nothing

### What did you expect to see?
ss-manager开启了-v参数，可以看到每次请求的流量，能统计每个端口的流量总使用量吗？没找到文档。

### What did you see instead?
nothing

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks-manager
