### ISSUE TITLE
Redirect problem from NA to China.

### ISSUE THREAD

**Issue by oskneo** [shadowsocks/shadowsocks-libev#2255]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
3.2.3

### What operating system are you using?
asus-wrt merlin

### What did you do?

if iptables -t nat -N SHADOWSOCKS; then
        iptables -t mangle -N SHADOWSOCKS
        #  IP
        iptables -t nat -A SHADOWSOCKS -d ss-b.vnet.one -j RETURN
        iptables -t nat -A SHADOWSOCKS -d 0.0.0.0/8 -j RETURN
        iptables -t nat -A SHADOWSOCKS -d 10.0.0.0/8 -j RETURN
        iptables -t nat -A SHADOWSOCKS -d 127.0.0.0/8 -j RETURN
        iptables -t nat -A SHADOWSOCKS -d 169.254.0.0/16 -j RETURN
        iptables -t nat -A SHADOWSOCKS -d 172.16.0.0/12 -j RETURN
        iptables -t nat -A SHADOWSOCKS -d 192.168.0.0/16 -j RETURN
        iptables -t nat -A SHADOWSOCKS -d 224.0.0.0/4 -j RETURN
        iptables -t nat -A SHADOWSOCKS -d 240.0.0.0/4 -j RETURN
        #  IP
        iptables -t nat -A SHADOWSOCKS -p tcp -j REDIRECT --to-port 1080
        #iptables -t nat -A SHADOWSOCKS -p icmp -j RETURN
        #iptables -t nat -A SHADOWSOCKS -p udp -j REDIRECT --to-port 1080
        #iptables -t nat -A SHADOWSOCKS -p icmp -j REDIRECT --to-port 1080

        iptables -t nat -A OUTPUT -p tcp -j SHADOWSOCKS

        iptables -t nat -A PREROUTING -p tcp -j SHADOWSOCKS
        iptables -t mangle -A PREROUTING -j SHADOWSOCKS
        /opt/etc/init.d/S22shadowsocks restart
        /opt/etc/init.d/S22ss-tunnel restart

fi

### What did you expect to see?
I am in Canada.
I want to get back to China to watch shows on bilibili or iqiyi.
After executing these commands, I successfully connect to the ss server.
My ss service is a route which contains a server in US for entry and a server in China for exit.
When I check my ip in baidu, it shows it is in US. I also cannot use the service for bilibili.
Of course, all the faults are not from the ss provider.
Some ip checking sites which only having a China server shows it is in China.

I use the same setting on the ss windows client, the baidu ip page shows it is in China.
How to solve it?

I have tried use dnsmasq and ss-tunnel towards 114.114.114.114, still fails.
Thx.

**Comment by PantherJohn** [comment]
@oskneo https://github.com/shadowsocks/shadowsocks-libev/issues/2250#issuecomment-447545577
This is NOT what `ss-tunnel` should be used for. See https://github.com/shadowsocks/shadowsocks-libev#transparent-proxy

**Comment by PantherJohn** [comment]
#2250

**Comment by PantherJohn** [comment]
@oskneo Please mask your server address first
```
iptables -t nat -A SHADOWSOCKS -d s*.one -j RETURN
```

**Comment by oskneo** [comment]
> @oskneo Please mask your server address first
> 
> ```
> iptables -t nat -A SHADOWSOCKS -d s*.one -j RETURN
> ```

Yes, I did that. You can see my third command.
Actually I successfully connect to the ss server, but not in the correct place.

**Comment by oskneo** [comment]
Here are all my setting:
sstest.sh
`
#!/bin/sh

if iptables -t nat -N SHADOWSOCKS; then
        iptables -t mangle -N SHADOWSOCKS
        #  IP
        iptables -t nat -A SHADOWSOCKS -d ss-b.vnet.one -j RETURN
        iptables -t nat -A SHADOWSOCKS -d 0.0.0.0/8 -j RETURN
        iptables -t nat -A SHADOWSOCKS -d 10.0.0.0/8 -j RETURN
        iptables -t nat -A SHADOWSOCKS -d 127.0.0.0/8 -j RETURN
        iptables -t nat -A SHADOWSOCKS -d 169.254.0.0/16 -j RETURN
        iptables -t nat -A SHADOWSOCKS -d 172.16.0.0/12 -j RETURN
        iptables -t nat -A SHADOWSOCKS -d 192.168.0.0/16 -j RETURN
        iptables -t nat -A SHADOWSOCKS -d 224.0.0.0/4 -j RETURN
        iptables -t nat -A SHADOWSOCKS -d 240.0.0.0/4 -j RETURN
        #  IP
        iptables -t nat -A SHADOWSOCKS -p tcp -j REDIRECT --to-port 1080
        #iptables -t nat -A SHADOWSOCKS -p icmp -j RETURN
        #iptables -t nat -A SHADOWSOCKS -p udp -j REDIRECT --to-port 1080
        #iptables -t nat -A SHADOWSOCKS -p icmp -j REDIRECT --to-port 1080

        iptables -t nat -A OUTPUT -p tcp -j SHADOWSOCKS

        iptables -t nat -A PREROUTING -p tcp -j SHADOWSOCKS
        iptables -t mangle -A PREROUTING -j SHADOWSOCKS
        /opt/etc/init.d/S22shadowsocks restart
        /opt/etc/init.d/S22ss-tunnel restart

fi
`

**Comment by xingezhang** [comment]
GFWlist模式的反向操作，把所有中国大陆的ip放进gfwlist这个ipset集，我在openwrt上是ok的
