### ISSUE TITLE
Config error with simple-obfs

### ISSUE THREAD

**Issue by Nidhoggur1993** [shadowsocks/shadowsocks-libev#2256]
### What version of shadowsocks-libev are you using?
shadowsocks-libev 3.1.3

### What operating system are you using?
ubuntu 18.04

### What did you do?

> {
>     "server":"IPADDR",
>     "server_port":PORT,
>     "password":"PASS",
>     "timeout":60,
>     "method":"chacha20-ietf",
>     "nameserver": "8.8.8.8,8.8.4.4,2001:4860:4860::8888,2001:4860:4860::8844",
>     "mode": "tcp_and_udp",
>     "plugin":"obfs-server",
>     "plugin_opt":"obfs=http"
> }

config file like above will cause some issue like (IPADDR and PORT has been deleted)

>  2018-12-30 20:48:13 INFO: using nameserver: 8.8.8.8,8.8.4.4,2001:4860:4860::8888,2001:4860:4860::8844
>  2018-12-30 20:48:13 INFO: tcp server listening at 127.0.0.1:34115
>  2018-12-30 20:48:13 INFO: udp server listening at IPADDR:PORT
>  2018-12-30 20:48:13 INFO: running from root user
>  2018-12-30 20:48:13 [simple-obfs] INFO: tcp port reuse enabled
>  2018-12-30 20:48:13 [simple-obfs] INFO: listening at IPADDR:PORT
>  2018-12-30 20:48:13 [simple-obfs] INFO: running from root user
>  2018-12-30 20:48:41 ERROR: failed to handshake with 127.0.0.1: invalid address type
>  2018-12-30 20:48:41 [simple-obfs] ERROR: remote recv: Connection reset by peer
>  2018-12-30 20:48:41 ERROR: failed to handshake with 127.0.0.1: invalid address type
>  2018-12-30 20:48:41 [simple-obfs] ERROR: remote recv: Connection reset by peer
>  2018-12-30 20:48:42 ERROR: crypto: stream: repeat IV detected
>  2018-12-30 20:48:42 ERROR: failed to handshake with 127.0.0.1: authentication error
>  2018-12-30 20:48:42 [simple-obfs] ERROR: remote recv: Connection reset by peer
>  2018-12-30 20:48:42 ERROR: crypto: stream: repeat IV detected
>  2018-12-30 20:48:42 ERROR: failed to handshake with 127.0.0.1: authentication error
>  2018-12-30 20:48:42 [simple-obfs] ERROR: remote recv: Connection reset by peer
>  2018-12-30 20:48:42 ERROR: crypto: stream: repeat IV detected
>  2018-12-30 20:48:42 ERROR: failed to handshake with 127.0.0.1: authentication error
>  2018-12-30 20:48:42 [simple-obfs] ERROR: remote recv: Connection reset by peer
>  2018-12-30 20:48:42 ERROR: crypto: stream: repeat IV detected
>  2018-12-30 20:48:42 ERROR: failed to handshake with 127.0.0.1: authentication error
>  2018-12-30 20:48:42 [simple-obfs] ERROR: remote recv: Connection reset by peer
>  2018-12-30 20:48:43 ERROR: crypto: stream: repeat IV detected
>  2018-12-30 20:48:43 ERROR: failed to handshake with 127.0.0.1: authentication error
>  2018-12-30 20:48:43 [simple-obfs] ERROR: remote recv: Connection reset by peer
>  2018-12-30 20:48:43 ERROR: crypto: stream: repeat IV detected
>  2018-12-30 20:48:43 ERROR: failed to handshake with 127.0.0.1: authentication error

but if I run command `ss-server -u -c ss.conf --plugin obfs-server --plugin-opts "obfs=http"` with config like below, everything works fine

> {
>     "server":"IPADDR",
>     "server_port":PORT,
>     "password":"PASS",
>     "timeout":60,
>     "method":"chacha20-ietf",
>     "nameserver": "8.8.8.8,8.8.4.4,2001:4860:4860::8888,2001:4860:4860::8844"
> }

### What did you expect to see?
I want move all the options after `--plugin`  into the config file,
so the command will be like `ss-server -u -c ss.conf`

**Comment by Unbinilium** [comment]
Try `"plugin_opts"` in config file instead

**Comment by Nidhoggur1993** [comment]
> 
> 
> Try `"plugin_opts":"obfs=http",` in config file instead

@Unbinilium Thanks, it works.
