### ISSUE TITLE
TCP sessions stopping after 10 seconds with middle device squashing tcp_fast_open SYN options 

### ISSUE THREAD

**Issue by goohuu** [shadowsocks/shadowsocks-libev#2257]
### What version of shadowsocks-libev are you using?

shadowsocks-libev 3.0.4

### What operating system are you using?

Debian Stretch

### What did you do?

- laptop => ss-redir => firewall-removing-SYN-TCP-options => ss-server => web sevrer
- tcp_fast_open enabled on both ss-redir and ss-server

### What did you expect to see?

I was expecting to see ss-redir fall back into non tcp_fast_open mode if for some reason it cannot be done (for example if the TCP SYN fast_open header options are removed by a middle equipment).

### What did you see instead?

All TCP sessions are RST by ss-redir precisely after 10s. Before that, all goes well.
TCP sessions that last less than 10 seconds are not impacted.

### What is your config in detail (with all sensitive info masked)?

ss-redir and ss-server:
```
{
    "mode":"tcp_and_udp",
    "server":"<server_ip>",
    "server_port":<server_port>,
    "local_port":<local_port>,
    "password":"aes_password",
    "timeout":60,
    "method":"aes-256-cfb",
    "local_address":"0.0.0.0",
    "fast_open":true
}
```

**Comment by madeye** [comment]
First of all, update to the latest version.

**Comment by madeye** [comment]
Also try latest Linux kernel with different parameters: https://github.com/shadowsocks/shadowsocks-libev/issues/1669#issuecomment-414033982

**Comment by PantherJohn** [comment]
@madeye Actually I was wondering if packet encapsulation (like [kcptun](https://github.com/xtaci/kcptun)) would be a fix for this problem.

**Comment by madeye** [comment]
@PantherJohn  Try kctptun plugin, it's just a reliable UDP protocol.

**Comment by PantherJohn** [comment]
@madeye yep, that's exactly what I meant. : )
Maybe someone should add this to the "[TCP Fast Open](https://github.com/shadowsocks/shadowsocks/wiki/TCP-Fast-Open)" wiki page someday.

**Comment by madeye** [comment]
You won't need any "TCP Fast Open" on UDP connections...

**Comment by madeye** [comment]
You can simply use `ss-redir` with kcptun.

**Comment by PantherJohn** [comment]
@madeye 
>  use ss-redir with kcptun.

That's not going to prevent fastopen SYN packets from being dropped, instead it breaks TCP Fast Open -- as I mentioned above, the client won't receive a valid SYN ACK packet containing cookies if the server is confusing original client addresses with loopback addresses used by `kcptun`, which inevitably breaks the rules for cookie caching based on client IP addresses.

> TCP sessions stopped after 10 seconds with middle device squashing tcp_fast_open SYN options

**Comment by madeye** [comment]
I suggest you study how kcptun works. It's just a TCP relay proxy...

**Comment by PantherJohn** [comment]
@madeye Sorry I didn't read the source code. `kcptun` does not encapsulate TCP packets like `ssh`, instead it copies the data field (that's what you said, TCP relaying) directly because of the limitations of the KCP protocol itself. (replaced transmission control algorithms) I think this problem will be fixed if original source/destination addresses are sent along with the data. (at least `ss-redir` has already done this)
