### ISSUE TITLE
关于tcp in udp

### ISSUE THREAD

**Issue by kyalipay** [shadowsocks/shadowsocks-libev#226]
ss-redir是用tcp in tcp 的方式加密传输，下面这个好像是用tcp in udp

https://github.com/RoyalAliceAcademyOfSciences/DeltaProxyGateway

有没有可能为ss-redir增加tcp in udp 的传输方案？

**Comment by madeye** [comment]
1. ss-redir 只是一个 Proxy，并不所所谓的 TCP-over-TCP。
2. 所以也就不会支持所谓的 TCP-over-UDP。
3. 遇到 TCP 连接速度受限时，可以试试 https://github.com/clowwindy/shadowvpn

**Comment by kyalipay** [comment]
好的，谢谢，我是在这里看到的  http://www.w8dsci.org/viewtopic.php?f=7&t=610
