### ISSUE TITLE
ShadowSocks not working on College Wifi but working on Mobile data.

### ISSUE THREAD

**Issue by amazingshuttler** [shadowsocks/shadowsocks-libev#2260]
### What version of shadowsocks-libev are you using?
shadowsocks-libev 3.1.3

### What operating system are you using?
Linux Ubuntu 18.04, Android 7.0 - Client
Linux Ubuntu 18.04 - Server

### What did you do?
I have setup ShadowSocks server on AWS Lightsail instance using docker and latest image of shadowsocks. For the client side, I have used two devices, one is Android Smartphone with shadowsocks app installed on it and a Linux ss-local client program.
When I am connected to Mobile carrier data , the shadowsocks works just fine in both the devices but doesn't when connected to my College wifi which has CYBEROAM as network software security or firewall.

### What did you expect to see?
No errors.

### What did you see instead?
ERROR: getpeername: Transport endpoint is not connected.

### What is your config in detail (with all sensitive info masked)?
Server Config - 
docker run -e PASSWORD=* -e METHOD=aes-256-ctr -e TIMEOUT=1000 -p 81:8388 -p 81:8388/udp -d shadowsocks/shadowsocks-libev

Client Config - 
ss-local -s * -p 81 -l 9999 -k * -m aes-256-ctr --fast-open

**Comment by madeye** [comment]
Try setup your server port to 443.

**Comment by amazingshuttler** [comment]
> Try setup your server port to 443.

Okay it makes sense why you said that. Thanks, it's working.

**Comment by kokoronoinori** [comment]
### Similar Issue
#### config.json
{
    "server":"159.*",
    "mode":"tcp_and_udp",
    "server_port":443,
    "local_port":1080,
    "password":"*",
    "timeout":60,
    "method":"aes-256-cfb"
}
#### traceroute
traceroute to www.google.com (199.59.149.136), 30 hops max, 60 byte packets
 1  gateway (192.*
 2  116.*
 3  124.*
 4  61.*
 5  * * *
