### ISSUE TITLE
Thousands of ERROR : remote recv: Connection reset by peer lasts for 1-2 minutes

### ISSUE THREAD

**Issue by raysearcher1** [shadowsocks/shadowsocks-libev#2262]
### What version of shadowsocks-libev are you using?
3.2.0 installed from librehat-shadowsocks-epel-7.repo

### What operating system are you using?
CentOS 7.4 Kernel version 3.10.0-957

### What did you do?
Run ss-redir and minitor the logs.

### What did you expect to see?
I know the reset by peer error will show up intermittedly. But it's quite wired thoudsands of error coming up within 1-2 minutes. I hope this can be mitigated.

### What did you see instead?
Thousands of remote recv: Connection reset by peer. It lasts for 1-2 minutes and stops. But after some time, the problem happens again.

### What is your config in detail (with all sensitive info masked)?

{
    "server":"ss-server",
    "server_port":4444,
    "local_address":"0.0.0.0",
    "local_port":1080,
    "password":"session password",
    "timeout":60,
    "method":"chacha20-ietf-poly1305"
}

I tried to use tcpdump to capture the packet, and I can see lots of reset send from ss-server. Could it be interruppted by ISP or GFW?
<img width="347" alt="snipaste_2019-01-11_00-20-22" src="https://user-images.githubusercontent.com/9099234/51034709-bb9b4300-15fb-11e9-9dcd-8208012810ea.png">
<img width="429" alt="screen_shot_2019-01-11_at_12_19_07_am" src="https://user-images.githubusercontent.com/9099234/51034724-c524ab00-15fb-11e9-97c3-5d6c216b56ec.png">

**Comment by raysearcher1** [comment]
Anybody to help? @madeye

**Comment by madeye** [comment]
Double check your local network. It looks there are some port scanner or P2P soft running on your local machines

**Comment by raysearcher1** [comment]
@madeye Thanks for your reply. This is a VPS running in the alibaba cloud. I'm pretty sure there is neither port scannor nor P2P running on the VPS. Could it be something outside of VPS? Is there any suggestion to identify the source?  It's annoying as it happens every now and then. When it happens, everything gets stuck and nothing can be sent through ss-redir. I need to wait 1-2 minutes until the error becomes less.

**Comment by madeye** [comment]
As mentioned above, it's not from your vps, but from your local machines.

**Comment by raysearcher1** [comment]
@madeye The tcpdump shows the source IP of the reset packet is all from ss-server (sorry for not saying so in the first place). Can it be something wrong on ss-server?

**Comment by madeye** [comment]
To verify if it's a problem related to the server, you can dig into the server log or run tcpdump on your server instead.
