### ISSUE TITLE
--manager-address not listening on port

### ISSUE THREAD

**Issue by john-d13** [shadowsocks/shadowsocks-libev#2263]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
shadowsocks-libev 3.2.0

### What operating system are you using?
CentOS 7

### What did you do?
Install Shadowsocks complete and working.  Trying to connect shadowsocks manager API to manage multiple users.  Added --manager-address 127.0.0.1:6001 to startup.

https://devhub.io/repos/shadowsocks-shadowsocks-manager

### What did you expect to see?
Port 6001 listening

### What did you see instead?
NO listenter

### What is your config in detail (with all sensitive info masked)?

/usr/lib/systemd/system/shadowsocks-libev.service

[Unit]
Description=Shadowsocks-libev Default Server Service
Documentation=man:shadowsocks-libev(8)
After=network.target network-online.target

[Service]
Type=simple
EnvironmentFile=/etc/sysconfig/shadowsocks-libev
User=nobody
Group=nobody
LimitNOFILE=32768
ExecStart=/usr/bin/ss-server **--manager-address 127.0.0.1:6001** -c "$CONFFILE" $DAEMON_ARGS
CapabilityBoundingSet=CAP_NET_BIND_SERVICE

[Install]
WantedBy=multi-user.target

/etc/shadowsocks-libev/config.json

{
    "server": "0.0.0.0",
    "server_port": 10000,
    "password": "xxxxx",
    "method":"aes-256-cfb",
    "mode": "tcp_and_udp",
    "timeout":3600
}

[root@socks1-resi-us3 ~]# netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:3306            0.0.0.0:*               LISTEN      1559/mysqld
**tcp        0      0 0.0.0.0:10000           0.0.0.0:*               LISTEN      11142/ss-server**
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      1919/master
tcp        0      0 0.0.0.0:10010           0.0.0.0:*               LISTEN      2524/redsocks2
tcp        0      0 0.0.0.0:61313           0.0.0.0:*               LISTEN      1037/sshd
tcp        0      0 50.21.184.36:1025       0.0.0.0:*               LISTEN      1057/sockd
tcp        0      0 127.0.0.1:199           0.0.0.0:*               LISTEN      1044/snmpd
tcp6       0      0 ::1:25                  :::*                    LISTEN      1919/master
tcp6       0      0 :::61313                :::*                    LISTEN      1037/sshd
udp        0      0 0.0.0.0:36512           0.0.0.0:*                           826/dhclient
udp        0      0 0.0.0.0:161             0.0.0.0:*                           1044/snmpd
udp        0      0 0.0.0.0:60583           0.0.0.0:*                           770/avahi-daemon: r
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           770/avahi-daemon: r
udp        0      0 0.0.0.0:10000           0.0.0.0:*                           11142/ss-server
udp        0      0 127.0.0.1:323           0.0.0.0:*                           748/chronyd
udp        0      0 0.0.0.0:68              0.0.0.0:*                           826/dhclient
udp6       0      0 :::34534                :::*                                826/dhclient
udp6       0      0 ::1:323                 :::*                                748/chronyd
[root@socks1-resi-us3 ~]#

**Comment by Roll8ack** [comment]
Try to use ss-manager
ExecStart=/usr/bin/ss-manager --manager-address 127.0.0.1:6001 -c "$CONFFILE" $DAEMON_ARGS

**Comment by madeye** [comment]
`ss-server` will connect to that manager address, instead of listening on it.
