### ISSUE TITLE
[wish] give acl option in config file

### ISSUE THREAD

**Issue by sleeksorrow** [shadowsocks/shadowsocks-libev#2267]
### What version of shadowsocks-libev are you using?
3.1.3

### What operating system are you using?
Ubuntu 18.04

### What did you do?
Searching in man page, github issues and source code (jconf.c) for options how to activate acl in config file instead of command line option.

### What did you expect to see?
Finding a config file option like e.g. `"acl": [path to acl file]`

### What did you see instead?
Could not find a way to enable acl in config file

### What is your config in detail (with all sensitive info masked)?
Client:
```
{
    "server":["XXXXXXXXXXXXX"],
    "server_port":443,
    "local_port":1090,
    "password":"XXXXXXX",
    "timeout":360,
    "method":"chacha20-ietf-poly1305",
    "prefer_ipv6": true,
    "ipv6_first": true,
    "fast_open": true,
    "reuse_port": true,
    "no_delay": true
}
```
Server:
```
{
    "server":["XXXXXXXXXXXX"],
    "server_port":443,
    "local_port":1090,
    "password":"XXXXXXXXXX",
    "timeout":360,
    "method":"chacha20-ietf-poly1305",
    "prefer_ipv6": true,
    "ipv6_first": true,
    "mode": "tcp_and_udp",
    "no_delay": true,
    "fast_open": true,
    "reuse_port": true
}
```

Would be very convenient to configure acl path in json file. Thank you!

**Comment by PantherJohn** [comment]
@sleeksorrow It's already included. Read the [docs](https://github.com/shadowsocks/shadowsocks-libev/blob/master/doc/shadowsocks-libev.asciidoc#config-file) or `man shadowsocks-libev`.

**Comment by PantherJohn** [comment]
#2265

**Comment by PantherJohn** [comment]
@sleeksorrow 
https://github.com/shadowsocks/shadowsocks-libev/blob/7ad2df961505ecddb44984ce34ea86874cd2ecc4/src/server.c#L1757-L1820
Add 
```
        if (acl == NULL) {
            acl = conf->acl;
        }
```
should do the trick

**Comment by sleeksorrow** [comment]
> ;/ Well, looks like we need a pull request.

I'm not sure if that is a request towards me to create that PR. Up to now I never forked a repository and created PRs, but if you want me to do so, I'll learn that. Old dog and new tricks, eh? ;) Please give a holler in that case.

**Comment by PantherJohn** [comment]
@sleeksorrow Ask @madeye.
