### ISSUE TITLE
2.0.7 ipv6 listen problem

### ISSUE THREAD

**Issue by sadoneli** [shadowsocks/shadowsocks-libev#227]
编译了2.0.7 openwrt版本，发现ss-local不能监听ipv6地址
改成ipv4后，监听正常，本地socks5能使用
从2.0.3跳上来的，2.0.3无此问题。

**Comment by madeye** [comment]
你的配置文件和命令行是什么？

**Comment by sadoneli** [comment]
配置文件
{
    "server":"2400:8900::f03c:91ff:fe84:fa31",
    "server_port":443,
    "local_port":1081,
    "password":"secret",
    "timeout":300,
    "method":"rc4-md5"
}
命令：ss-local -c /etc/japan-ipv6.json -u -f ss-local-japan.pid

同样配置，ip地址换成相同vps的ipv4地址，就能成功，已经测试本地ipv6没有问题
电脑使用shadowsocks-gui，1.2.6版本，相同配置文件，可以监听ipv6地址并正常转发。
