### ISSUE TITLE
Mingw compiled but show Segmentation fault while run.

### ISSUE THREAD

**Issue by xseven007** [shadowsocks/shadowsocks-libev#2272]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
github last commit 

### What operating system are you using?
win10 mingw64 gcc 8.2.1 mbedtls-2.16.0 libsodium-1.0.17

### What did you do?
build with mingw

### What did you see instead?
MINGW64 ~/src/shadowsocks-libev/src
$ ./ss-local.exe -h
Segmentation fault

### What is your config in detail (with all sensitive info masked)?
I used the command in the mingw prepare.sh deps.sh build.sh.. Nothing go wrong. And it can also build from the source. But it can not run.

**Comment by madeye** [comment]
Make sure you're building with docker.

**Comment by xseven007** [comment]
I have found out witch the problem is the libsodium-1.0.17. Use the version 1.0.16 will not get the problem.

**Comment by madeye** [comment]
Please try this commit d7fe31e

**Comment by xseven007** [comment]
`
make[2]: Entering directory '/home/phoenix/src/shadowsocks-libev/src'
  CC       libshadowsocks_libev_la-local.lo
  CC       libshadowsocks_libev_la-utils.lo
  CC       libshadowsocks_libev_la-jconf.lo
  CC       libshadowsocks_libev_la-json.lo
utils.c: In function 'ss_align':
utils.c:256:8: error: 'err' is used uninitialized in this function [-Werror=uninitialized]
     if (err) {
        ^
cc1.exe: all warnings being treated as errors
make[2]: *** [Makefile:868: libshadowsocks_libev_la-utils.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/home/phoenix/src/shadowsocks-libev/src'
make[1]: *** [Makefile:479: all-recursive] Error 1
make[1]: Leaving directory '/home/phoenix/src/shadowsocks-libev'
make: *** [Makefile:388: all] Error 2

`

**Comment by madeye** [comment]
Try ba930dc

**Comment by xseven007** [comment]
Great. I can be completed. But another bug was found. The new ss-local.exe would not accept new connection after several connections. I can not see any log after 3 or 4 connect. and the browser show ERR_PROXY_CONNECTION_FAILED.

**Comment by madeye** [comment]
Try this 782311a
