### ISSUE TITLE
Failed to lookup v4 address timeout while contacting dns servers

### ISSUE THREAD

**Issue by flzyup** [shadowsocks/shadowsocks-libev#2273]
### What version of shadowsocks-libev are you using?
shadowsocks-libev 3.2.3

### What operating system are you using?
CentOS Linux release 7.6.1810 (Core)

### What did you do?
Use shadowsocks client to connect server, Dns lookup periodical failed

### What did you expect to see?
Doesn't have failure

### What did you see instead?
logs:
Jan 22 04:31:32 wow /usr/local/bin/ss-server[3187]: failed to lookup v4 address Timeout while contacting DNS servers
Jan 22 04:31:33 wow /usr/local/bin/ss-server[3187]: failed to lookup v6 address Timeout while contacting DNS servers
Jan 22 04:31:33 wow /usr/local/bin/ss-server[3187]: unable to resolve mtalk.google.com
Jan 22 04:31:33 wow /usr/local/bin/ss-server[3187]: current server connection: 9
Jan 22 04:31:33 wow /usr/local/bin/ss-server[3187]: failed to lookup v4 address Timeout while contacting DNS servers
Jan 22 04:31:33 wow /usr/local/bin/ss-server[3187]: failed to lookup v4 address Timeout while contacting DNS servers
Jan 22 04:31:33 wow /usr/local/bin/ss-server[3187]: failed to lookup v4 address Timeout while contacting DNS servers
Jan 22 04:31:34 wow /usr/local/bin/ss-server[3187]: server_recv close the connection
Jan 22 04:31:34 wow /usr/local/bin/ss-server[3187]: current remote connection: 3
Jan 22 04:31:34 wow /usr/local/bin/ss-server[3187]: current server connection: 8
Jan 22 04:31:34 wow /usr/local/bin/ss-server[3187]: failed to lookup v4 address Timeout while contacting DNS servers
Jan 22 04:31:35 wow /usr/local/bin/ss-server[3187]: failed to lookup v6 address Timeout while contacting DNS servers
Jan 22 04:31:35 wow /usr/local/bin/ss-server[3187]: unable to resolve api.facebook.com

### What is your config in detail (with all sensitive info masked)?
{
    "server":"0.0.0.0",
    "server_port":9777,
    "password":"xyzabc",
    "timeout":300,
    "user":"nobody",
    "method":"xchacha20-ietf-poly1305",
    "fast_open":true,
    "nameserver":"8.8.8.8",
    "mode":"tcp_and_udp",
    "plugin":"obfs-server",
    "plugin_opts":"obfs=http"
}

**Comment by flzyup** [comment]
When I use dig or nslookup command in vps, it always success and didn't failed

**Comment by flzyup** [comment]
Jan 22 04:07:08 wow /usr/local/bin/ss-server[3187]: failed to lookup v4 address Timeout while contacting DNS servers
Jan 22 04:07:09 wow /usr/local/bin/ss-server[3187]: failed to lookup v6 address Timeout while contacting DNS servers
Jan 22 04:07:09 wow /usr/local/bin/ss-server[3187]: failed to lookup v6 address Timeout while contacting DNS servers
Jan 22 04:07:10 wow /usr/local/bin/ss-server[3187]: failed to lookup v6 address Timeout while contacting DNS servers
Jan 22 04:07:11 wow /usr/local/bin/ss-server[3187]: failed to lookup v4 address Timeout while contacting DNS servers
Jan 22 04:07:12 wow /usr/local/bin/ss-server[3187]: failed to lookup v4 address Timeout while contacting DNS servers
Jan 22 04:07:13 wow /usr/local/bin/ss-server[3187]: failed to lookup v6 address Timeout while contacting DNS servers
Jan 22 04:07:16 wow /usr/local/bin/ss-server[3187]: failed to lookup v6 address Timeout while contacting DNS servers
Jan 22 04:07:17 wow /usr/local/bin/ss-server[3187]: failed to lookup v4 address Timeout while contacting DNS servers
Jan 22 04:09:08 wow /usr/local/bin/ss-server[3187]: TCP connection timeout
Jan 22 04:13:22 wow /usr/local/bin/ss-server[3187]: failed to lookup v4 address Timeout while contacting DNS servers
Jan 22 04:13:23 wow /usr/local/bin/ss-server[3187]: failed to lookup v4 address Timeout while contacting DNS servers
Jan 22 04:13:24 wow /usr/local/bin/ss-server[3187]: failed to lookup v4 address Timeout while contacting DNS servers
Jan 22 04:13:24 wow /usr/local/bin/ss-server[3187]: failed to lookup v6 address Timeout while contacting DNS servers
Jan 22 04:13:24 wow /usr/local/bin/ss-server[3187]: failed to lookup v6 address Timeout while contacting DNS servers
Jan 22 04:13:25 wow /usr/local/bin/ss-server[3187]: failed to lookup v4 address Timeout while contacting DNS servers
Jan 22 04:13:25 wow /usr/local/bin/ss-server[3187]: failed to lookup v6 address Timeout while contacting DNS servers
Jan 22 04:13:25 wow /usr/local/bin/ss-server[3187]: failed to lookup v4 address Timeout while contacting DNS servers
Jan 22 04:13:26 wow /usr/local/bin/ss-server[3187]: failed to lookup v4 address Timeout while contacting DNS servers
Jan 22 04:13:26 wow /usr/local/bin/ss-server[3187]: failed to lookup v6 address Timeout while contacting DNS servers
Jan 22 04:14:14 wow /usr/local/bin/ss-server[3187]: TCP connection timeout
Jan 22 04:19:16 wow /usr/local/bin/ss-server[3187]: TCP connection timeout
Jan 22 04:21:09 wow /usr/local/bin/ss-server[3187]: failed to lookup v4 address Timeout while contacting DNS servers
Jan 22 04:21:09 wow /usr/local/bin/ss-server[3187]: failed to lookup v6 address Timeout while contacting DNS servers
Jan 22 04:25:15 wow /usr/local/bin/ss-server[3187]: TCP connection timeout
Jan 22 04:25:40 wow /usr/local/bin/ss-server[3187]: TCP connection timeout
Jan 22 04:28:04 wow /usr/local/bin/ss-server[3187]: TCP connection timeout
Jan 22 04:28:47 wow /usr/local/bin/ss-server[3187]: TCP connection timeout
Jan 22 04:28:49 wow /usr/local/bin/ss-server[3187]: TCP connection timeout
Jan 22 04:30:03 wow /usr/local/bin/ss-server[3187]: TCP connection timeout
Jan 22 04:30:03 wow /usr/local/bin/ss-server[3187]: TCP connection timeout
Jan 22 04:31:32 wow /usr/local/bin/ss-server[3187]: failed to lookup v4 address Timeout while contacting DNS servers
Jan 22 04:31:33 wow /usr/local/bin/ss-server[3187]: failed to lookup v6 address Timeout while contacting DNS servers
Jan 22 04:31:33 wow /usr/local/bin/ss-server[3187]: failed to lookup v4 address Timeout while contacting DNS servers
Jan 22 04:31:33 wow /usr/local/bin/ss-server[3187]: failed to lookup v4 address Timeout while contacting DNS servers

**Comment by madeye** [comment]
Check your server log to make sure it is indeed using the `8.8.8.8` as the DNS server.

**Comment by flzyup** [comment]
yeah，it's 8.8.8.8 @madeye 

Jan 22 04:44:15 wow /usr/local/bin/ss-server[3187]: [18162] connect to 8.8.8.8:53
Jan 22 04:44:15 wow /usr/local/bin/ss-server[3187]: accept a connection
Jan 22 04:44:15 wow /usr/local/bin/ss-server[3187]: [18162] connect to 8.8.8.8:53
Jan 22 04:44:15 wow /usr/local/bin/ss-server[3187]: remote connected
Jan 22 04:44:15 wow /usr/local/bin/ss-server[3187]: server_recv close the connection

**Comment by flzyup** [comment]
latest  log screenshots:
![image](https://user-images.githubusercontent.com/158452/51528257-36245800-1e71-11e9-8096-94b7f4604b5a.png)

**Comment by flzyup** [comment]
the ping icmp requests to 8.8.8.8 were stable:
![image](https://user-images.githubusercontent.com/158452/51528460-b0ed7300-1e71-11e9-8894-96736bfec632.png)

**Comment by madeye** [comment]
Post the first lines of server log or the full log file here

**Comment by flzyup** [comment]
[ss_dump.log.zip](https://github.com/shadowsocks/shadowsocks-libev/files/2785437/ss_dump.log.zip)
This is all ss-server log. Last night, i reinstall vps with ubuntu 18.04. Still got timeout error but not so frequently as CentOS.

PS: I enable bbr kernel feature both in CentOS and Ubuntu

**Comment by madeye** [comment]
According to your log, it's just simply a timeout, which means your connection to Google's DNS server is not good.

Just try any other public DNS server instead, e.g. `1.1.1.1`.

**Comment by flzyup** [comment]
> According to your log, it's simply a timeout, which means your connection to Google's DNS server is not good.
> 
> Just try any other public DNS server instead, e.g. `1.1.1.1`.

ok, I'll try it. Does nameserver config support multiple servers?

**Comment by flzyup** [comment]
I have change config file to 1.1.1.1 and restart the service. It seems that ss still query from 8.8.8.8. 
Logs:
Jan 23 14:02:58 wow /usr/local/bin/ss-server[5592]: [9777] connect to 8.8.8.8:53
Jan 23 14:02:58 wow /usr/local/bin/ss-server[5592]: remote connected
Jan 23 14:02:58 wow /usr/local/bin/ss-server[5592]: server_recv close the connection
Jan 23 14:02:58 wow /usr/local/bin/ss-server[5592]: current remote connection: 20
Jan 23 14:02:58 wow /usr/local/bin/ss-server[5592]: current server connection: 20
Jan 23 14:02:58 wow /usr/local/bin/ss-server[5592]: accept a connection

**Comment by flzyup** [comment]
Thanks I got.

**Comment by bannedbook** [comment]
I found the same problem,
/etc/init.d/shadowsocks-libev restart ,Able to resolve temporarily
But it still appears from time to time
