### ISSUE TITLE
dpkg-buildpackage -b -us -uc : Unmet build dependencies: libsodium-dev (>= 1.0.12) pkg-config

### ISSUE THREAD

**Issue by cliusz** [shadowsocks/shadowsocks-libev#2276]
### What version of shadowsocks-libev are you using?
3.2.3-1

### What operating system are you using?
debian 9 64 bit on vultr VPS

### What did you do?
install libev by source:
1、Get the latest source code
2、Build and install with recent libsodium
3、Build deb package from source
cd shadowsocks-libev
sudo sh -c 'printf "deb http://deb.debian.org/debian jessie-backports main" > /etc/apt/sources.list.d/jessie-backports.list'
sudo sh -c 'printf "deb http://deb.debian.org/debian jessie-backports-sloppy main" >> /etc/apt/sources.list.d/jessie-backports.list'
sudo apt-get install --no-install-recommends devscripts equivs
mk-build-deps --root-cmd sudo --install --tool "apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends -y"
./autogen.sh && dpkg-buildpackage -b -us -uc

### What did you expect to see?
Successful installation and normal use.

### What did you see instead?
dpkg-buildpackage: info: host architecture amd64
 dpkg-source --before-build shadowsocks-libev
dpkg-checkbuilddeps: error: Unmet build dependencies: libsodium-dev (>= 1.0.12) pkg-config

### What is your config in detail (with all sensitive info masked)?
Follow the official guidelines completely. As
1、export LIBSODIUM_VER=1.0.17
2、export MBEDTLS_VER=2.16.0

root@libev:~/shadowsocks-libev# dpkg-buildpackage -b -us -uc
dpkg-buildpackage: info: source package shadowsocks-libev
dpkg-buildpackage: info: source version 3.2.3-1
dpkg-buildpackage: info: source distribution unstable
dpkg-buildpackage: info: source changed by Max Lv <max.c.lv@gmail.com>
dpkg-buildpackage: info: host architecture amd64
 dpkg-source --before-build shadowsocks-libev
dpkg-checkbuilddeps: error: Unmet build dependencies: libsodium-dev (>= 1.0.12) pkg-config
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)
root@libev:~/shadowsocks-libev# uname -a
Linux libev 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux

---
Thank you very much & Happy New Year!

**Comment by hosiet** [comment]
Debian 9 is not "jessie,", it's "stretch".

Please correct your typo and try again.

**Comment by bridgeable** [comment]
Yes, it is installed according to the stretch version.
Installed many times, always.
Thank you! @hosiet

**Comment by cliusz** [comment]
Yes, it is installed according to the stretch version.
Installed many times, always.
Thank you! @hosiet

**Comment by hosiet** [comment]
So you mean that your problem is solved? I guess you won't meet any issues if you do follow the instructions.

Besides, you can always run a one-liner "apt install shadowsocks-libev" after enabling `stretch-backports` repository. No need to mess up with compiling.

**Comment by cliusz** [comment]
Sorry！ The problem description (What did you do?) started above is incorrect. I am actually:
 ### What did you do?
install libev by source:
1、Get the latest source code
2、Build and install with recent libsodium
3、Build deb package from source

cd shadowsocks-libev
sudo sh -c 'printf "deb http://deb.debian.org/debian stretch-backports main" > /etc/apt/sources.list.d/stretch-backports.list'
sudo apt-get install --no-install-recommends devscripts equivs
mk-build-deps --root-cmd sudo --install --tool "apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends -y"
./autogen.sh && dpkg-buildpackage -b -us -uc

My question remains:
Because libev is not working properly through two methods of installing from the repository ("sudo apt install shadowsocks-libev" and "sudo apt -t jessie-backports-sloppy install shadowsocks-libev"), the source code is compiled and installed.
The source installation failed as described above.

Thank you for your care! @hosiet
