### ISSUE TITLE
3.2.3-1 version installed on Debian 9 error, prompt Main pro Cess exited, code=exited, status=218/CAPABILITIES

### ISSUE THREAD

**Issue by biliair** [shadowsocks/shadowsocks-libev#2279]
### What version of shadowsocks-libev are you using?
3.2.3

### What operating system are you using?
Debian 9 x64

### What did you do?
root@libev:~# history
0 apt update
1 apt upgrade
2 apt-get install openssh-server
3 service ssh start
4 apt-get install vim
5 vim /etc/sshd_config
6 PermitRootLogin yes
7 reboot
8 nano /etc/apt/sources.list
9 deb http://ftp.debian.org/debian stretch-backports main
10 apt -t stretch-backports install shadowsocks-libev
11 systemctl status shadowsocks-libev

root@hostname:~# service shadowsocks-libev status
● shadowsocks-libev.service - Shadowsocks-libev Default Server Service
   Loaded: loaded (/lib/systemd/system/shadowsocks-libev.service; enabled; vendo
r preset: enabled)
   Active: failed (Result: exit-code) since Mon 2019-02-11 06:38:26 U
TC; 5min ago
     Docs: man:shadowsocks-libev(8)
  Process: 3174 ExecStart=/usr/bin/ss-server -c $CONFFILE $DAEMON_ARGS (
code=exited, status=218/CAPABILITIES)
 Main PID: 3174 (code=exited, status=218/CAPABILITIES)

Feb 11 06:38:26 hostname systemd[1]: Started Shadowsocks-libev Default Server Se
rvice.
Feb 11 06:38:26 hostname systemd[3174]: shadowsocks-libev.service: Faile
d at step CAPABILITIES spawning /usr/bin/ss-server: Invalid argument
Feb 11 06:38:26 hostname systemd[1]: shadowsocks-libev.service: Main pro
cess exited, code=exited, status=218/CAPABILITIES
Feb 11 06:38:26 hostname systemd[1]: shadowsocks-libev.service: Unit ent
ered failed state.
Feb 11 06:38:26 hostname systemd[1]: shadowsocks-libev.service: Failed w
ith result 'exit-code'.

**Comment by biliair** [comment]
Is there a developer or any one who can answer this question? Thank you![](url)

**Comment by biliair** [comment]
Type the command line
  /usr/bin/ss-server -c /etc/shadowsocks-libev/config.json -u

  2019-02-16 07:45:33 INFO: UDP relay enabled
  2019-02-16 07:45:33 INFO: initializing ciphers... chacha20-ietf-poly1305
  2019-02-16 07:45:33 INFO: tcp server listening at 202.*.*.*:10000
  2019-02-16 07:45:33 INFO: udp server listening at 202.*.*.*:10000
  2019-02-16 07:45:33 INFO: running from root user

The SS service is running normally and the data transmission is normal.

Just exit the putty window and get an error

Process: 3174 ExecStart=/usr/bin/ss-server -c $CONFFILE $DAEMON_ARGS (
Code=exited, status=218/CAPABILITIES)

Already added the above content in the self-starting file rc.local, still starting the error

![2019-02-15 23 20 15](https://user-images.githubusercontent.com/47517159/52896578-0d3f7a80-3205-11e9-83b7-2aa9250cc6d4.png)

**Comment by alitime** [comment]
I also encountered the same problem.

**Comment by alitime** [comment]
@biliair Have you solved it?

**Comment by digititus** [comment]
Same error on Ubuntu 16.04 LTS. Solution?

**Comment by AndrewP-GH** [comment]
> 
> 
> Same error on Ubuntu 16.04 LTS. Solution?

I have it too(

**Comment by alitime** [comment]
3.2.4 Same error on debian & ubuntu

**Comment by AndrewP-GH** [comment]
I've found solution:
Open file `/lib/systemd/system/shadowsocks-libev.service` 
and remove/comment these lines:
`CapabilityBoundingSet=CAP_NET_BIND_SERVICE`
`AmbientCapabilities=CAP_NET_BIND_SERVICE`

**Comment by alitime** [comment]
> I've found solution:
> Open file `/lib/systemd/system/shadowsocks-libev.service`
> and remove/comment these lines:
> `CapabilityBoundingSet=CAP_NET_BIND_SERVICE`
> `AmbientCapabilities=CAP_NET_BIND_SERVICE`

The problem still exists!!!

**Comment by pjrobertson** [comment]
Seems like a problem on Openvz servers, that don't have the net bind capability.

The changes suggested by AndrewP work!
