### ISSUE TITLE
A suggestion about usage infomation 

### ISSUE THREAD

**Issue by angusding** [shadowsocks/shadowsocks-libev#228]
usage for ss-[local|redir|server|tunnel] :
[-L <addr>:<port>]         setup a local port forwarding tunnel,
                                     only available in tunnel mode
It's easy to become confused by these explanation.
suggest as the follow:
[-L <addr>:<port>]         Specify destination(or remote) address and port for forwarding tunnel,
                                     only available in tunnel mode

**Comment by madeye** [comment]
Do not think so. Before using ss-tunnel, you'd better understand what "local port forwarding" is.

http://en.wikipedia.org/wiki/Port_forwarding#Local_port_forwarding

**Comment by angusding** [comment]
I think "[-L <addr>:<port>] Specify destination server address and port for local port forwarding tunnel," is better than only "[-L :] setup a local port forwarding tunnel,".
That is the original text from your URL:
"Two important items in local port forwarding are the destination server, and two port numbers." means:
The destination server's  IP address is the <add> behind the parameter "-L". And one of the two port numbers is destination server port which is the parameter <port> behind the parameter "-L". Another port is the local forwarding port which set behind the parameter "-l".
Don't you think so?
