### ISSUE TITLE
shadowsocks-libev not working

### ISSUE THREAD

**Issue by ericcao95** [shadowsocks/shadowsocks-libev#2282]
What version of shadowsocks-libev are you using?

3.2.3

What operating system are you using?

centOS 7

What did you do?

configure shadowsocks-libev on my server according to teddysun's tutorial https://teddysun.com/357.html

 What did you expect to see?

shadowsocks works properly.

What did you see instead?

shadowsocks is not working, cannot load web pages.

 What is your config in detail (with all sensitive info masked)?

Congratulations, Shadowsocks-libev server install completed!
Your Server IP        :  ***************
Your Server Port      :  6666
Your Password         : -
Your Encryption Method:  aes-256-cfb

[root@vultr ~]# ss-server
 2019-02-15 01:51:52 INFO: using tcp fast open
 2019-02-15 01:51:52 INFO: UDP relay enabled
 2019-02-15 01:51:52 INFO: initializing ciphers... aes-256-cfb
 2019-02-15 01:51:52 INFO: using nameserver: 8.8.8.8
 2019-02-15 01:51:52 INFO: tcp server listening at 0.0.0.0:6666
 2019-02-15 01:51:52 ERROR: bind: Address already in use
 2019-02-15 01:51:52 ERROR: failed to listen on any address

**Comment by aweffr** [comment]
Log shows your port 6666 has been used.

Please `# sudo lsof -i:6666` to see which process has occpied your port.

You can try other ports.

**Comment by ericcao95** [comment]
@aweffr  i tried another port it's still occupied, and that command isn't working also.

**Comment by ericcao95** [comment]
@aweffr sudo: lsof: command not found

**Comment by xfort** [comment]
> @aweffr sudo: lsof: command not found

please install lsof

**Comment by ericcao95** [comment]
@aweffr COMMAND    PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
ssserver 22324 root    4u  IPv4 324578      0t0  TCP *:ircu-2 (LISTEN)
ssserver 22324 root    5u  IPv4 324579      0t0  UDP *:ircu-2

**Comment by ericcao95** [comment]
i changed the port to 9999 then restart 

[root@vultr ~]# ss-server
 2019-02-15 03:28:45 INFO: UDP relay enabled
 2019-02-15 03:28:45 INFO: initializing ciphers... aes-256-cfb
 2019-02-15 03:28:45 INFO: using nameserver: 8.8.8.8
 2019-02-15 03:28:45 INFO: tcp server listening at 0.0.0.0:9999
 2019-02-15 03:28:45 ERROR: bind: Address already in use
 2019-02-15 03:28:45 ERROR: failed to listen on any address
[root@vultr ~]# sudo lsof -i:9999
COMMAND    PID   USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
ss-server 3412 nobody    3u  IPv4 355062      0t0  TCP *:distinct (LISTEN)
ss-server 3412 nobody    4u  IPv4 355064      0t0  UDP *:distinct

**Comment by aweffr** [comment]
what about `sudo ps -ef | grep ss-server`?

seems that you have start ss-server at every process

**Comment by ericcao95** [comment]
@aweffr [root@vultr ~]# sudo ps -ef | grep ss-server
nobody    3412     1  0 03:28 ?        00:00:00 /usr/local/bin/ss-server -v -c /etc/shadowsocks-libev/config.json -f /var/run/shadowsocks-libev.pid
root      6240  6218  0 04:15 pts/1    00:00:00 grep --color=auto ss-server
