### ISSUE TITLE
ss-server  will stop after running for some time

### ISSUE THREAD

**Issue by haolly** [shadowsocks/shadowsocks-libev#2283]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
shadowsocks-libev 3.2.3

### What operating system are you using?
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04 LTS"

### What did you do?
install ss from ppa, then start ss

### What did you expect to see?
use ss client Shadowsocksx-ng could connect to google all the time

### What did you see instead?
could not connect to google after couples hours

### What is your config in detail (with all sensitive info masked)?
"server":["::0","0.0.0.0"],
    "server_port":6055,
    "local_port":1090,
    "password":"xxxxx",
    "timeout":60,
    "method":"chacha20-ietf-poly1305"

**Comment by haolly** [comment]
also, after restart ss-server, I could connect to google again.

**Comment by madeye** [comment]
Post your logs here.

**Comment by haolly** [comment]
@madeye  where is the log file ?

**Comment by haolly** [comment]
Shit, the log is not written to /var/log/shadowsocks, I have found it in /var/log/syslog

> /usr/bin/ss-server[2389]: message repeated 6 times: [ server recv: Connection reset by peer]
Feb 16 16:51:28 RoughDisfigured-VM /usr/bin/ss-server[2389]: failed to handshake with a.b.c.c: authentication error
Feb 16 16:52:43 RoughDisfigured-VM /usr/bin/ss-server[2389]: message repeated 32 times: [ failed to handshake with a.b.c.c: authentication error]
Feb 16 16:52:43 RoughDisfigured-VM /usr/bin/ss-server[2389]: block all requests from a.b.c.c
Feb 16 17:17:01 RoughDisfigured-VM CRON[4939]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Feb 16 17:37:54 RoughDisfigured-VM /usr/bin/ss-server[2389]: message repeated 820 times: [ block all requests from a.b.c.c]
Feb 16 17:37:54 RoughDisfigured-VM /usr/bin/ss-server[2389]: failed to handshake with 121.57.231.199: authentication error
Feb 16 17:37:54 RoughDisfigured-VM /usr/bin/ss-server[2389]: block all requests from a.b.c.c
Feb 16 17:37:56 RoughDisfigured-VM /usr/bin/ss-server[2389]: message repeated 15 times: [ block all requests from a.b.c.c]
Feb 16 17:37:56 RoughDisfigured-VM /usr/bin/ss-server[2389]: failed to handshake with 182.101.55.24: authentication error
Feb 16 17:37:56 RoughDisfigured-VM /usr/bin/ss-server[2389]: block all requests from a.b.c.c
Feb 16 17:37:59 RoughDisfigured-VM /usr/bin/ss-server[2389]: message repeated 10 times: [ block all requests from a.b.c.c]
Feb 16 17:37:59 RoughDisfigured-VM /usr/bin/ss-server[2389]: failed to handshake with 116.252.0.144: authentication error
Feb 16 17:38:00 RoughDisfigured-VM /usr/bin/ss-server[2389]: block all requests from a.b.c.c
Feb 16 17:38:02 RoughDisfigured-VM /usr/bin/ss-server[2389]: message repeated 13 times: [ block all requests from a.b.c.c]
Feb 16 17:38:02 RoughDisfigured-VM /usr/bin/ss-server[2389]: failed to handshake with 113.128.104.236: authentication error
Feb 16 17:38:02 RoughDisfigured-VM /usr/bin/ss-server[2389]: block all requests from a.b.c.c
Feb 16 17:38:02 RoughDisfigured-VM /usr/bin/ss-server[2389]: message repeated 2 times: [ block all requests from a.b.c.c]
Feb 16 17:38:03 RoughDisfigured-VM /usr/bin/ss-server[2389]: failed to handshake with 106.45.0.200: authentication error
Feb 16 17:38:03 RoughDisfigured-VM /usr/bin/ss-server[2389]: block all requests from a.b.c.c
Feb 16 17:38:22 RoughDisfigured-VM /usr/bin/ss-server[2389]: message repeated 82 times: [ block all requests from a.b.c.c]
Feb 16 17:38:22 RoughDisfigured-VM /usr/bin/ss-server[2389]: failed to handshake with 182.242.105.94: authentication error
Feb 16 17:38:22 RoughDisfigured-VM /usr/bin/ss-server[2389]: block all requests from a.b.c.c
Feb 16 17:38:26 RoughDisfigured-VM /usr/bin/ss-server[2389]: message repeated 29 times: [ block all requests from a.b.c.c]
Feb 16 17:38:27 RoughDisfigured-VM /usr/bin/ss-server[2389]: failed to handshake with 27.156.91.58: authentication error
Feb 16 17:38:27 RoughDisfigured-VM /usr/bin/ss-server[2389]: block all requests from a.b.c.c
Feb 16 17:38:27 RoughDisfigured-VM /usr/bin/ss-server[2389]: message repeated 6 times: [ block all requests from a.b.c.c]
Feb 16 17:38:28 RoughDisfigured-VM /usr/bin/ss-server[2389]: failed to handshake with 112.66.100.78: authentication error

**Comment by jiaokang** [comment]
```
block all requests from a.b.c.c

```
Is a.b.c.c  your client IP? If yes , then check your config , may be your client offer a wrong password or cipher.
