### ISSUE TITLE
多用户+obfs混淆

### ISSUE THREAD

**Issue by buptzyf** [shadowsocks/shadowsocks-libev#2284]
ss-manager加混淆怎么弄呢？  现在单用户+obfs可以了，怎么配置多用户obfs

**Comment by Ahaochan** [comment]
[基于 shadowsocks-libev+simple-obfs 的单机多用户搭建](https://ahaochan.github.io/posts/multi_user_of_shadowsocks_libev.html)

**Comment by buptzyf** [comment]
@Ahaochan 谢谢，可以用了，参考文中给出的步骤，贴一下。


配置文件：
{
  "port_password": {
    "10000":"***",
    "20000":"***"
  },
  "fast_open":true,
  "reuse_port":true,
  "no_delay":true,
  "timeout": 300,
  "mode":"tcp_and_udp",
  "method": "aes-256-cfb",
  "plugin":"obfs-server",
  "plugin_opts":"obfs=http;failover=apps.bdimg.com"
}

启动命令  nohup ss-manager -c /etc/shadowsocks-manager.json &

查看进程  ps -ef | grep -v grep | grep "server"

root      7389     1  0 03:48 ?        00:00:00 ss-server --manager-address 127.0.0.1:8839 -f /root/.shadowsocks/.shadowsocks_10088.pid -c /root/.shadowsocks/.shadowsocks_10088.conf -t 300 -u --fast-open --no-delay --plugin obfs-server --plugin-opts obfs=http;failover=apps.bdimg.com -s 0.0.0.0
root      7392  7389  0 03:48 ?        00:00:00 obfs-server --fast-open
root      7393     1  0 03:48 ?        00:00:00 ss-server --manager-address 127.0.0.1:8839 -f /root/.shadowsocks/.shadowsocks_20088.pid -c /root/.shadowsocks/.shadowsocks_20088.conf -t 300 -u --fast-open --no-delay --plugin obfs-server --plugin-opts obfs=http;failover=apps.bdimg.com -s 0.0.0.0
root      7394  7393  0 03:48 ?        00:00:00 obfs-server --fast-open

**Comment by buptzyf** [comment]
simple-obfs 现在过时了，目前用插件v2ray，但是考虑到mac下的shadowsocks-ng不支持v2ray，暂时用obfs代替

**Comment by Ahaochan** [comment]
@buptzyf 感谢提醒, 我回去研究下

**Comment by Ahaochan** [comment]
@buptzyf 
X-NG已集成V2RAY, [pull 1001](https://github.com/shadowsocks/ShadowsocksX-NG/pull/1001)

**Comment by buptzyf** [comment]
@Ahaochan  没有人review，a pity

**Comment by doublesixwings** [comment]
我吐个小槽，多用户多端口，用10000、20000这种非标端口，而不是80、443这种标准端口，混淆有何意义呢？

**Comment by kuaiyu168** [comment]
姐妹，看了您的混淆设置我还是不会用哦，看来教程链接中，配置服务器端 simple-obfs 混淆插件后，客户端的配置只能是win  和安卓手机端吗？
