### ISSUE TITLE
ss-server: IPv6 address parsing behaves differently when written in arrays

### ISSUE THREAD

**Issue by k9yyy** [shadowsocks/shadowsocks-libev#2285]
### Description
Not something urgent but a bit annoying.
In `ss-server`'s configuration file, an IPv6 address enclosed by brackets (i.e. `[::]`) works fine when written in an array; however, if it is directly written as a string without being put in an array, it does not work.

### What version of shadowsocks-libev are you using?
Current master branch

### What operating system are you using?
Ubuntu 16.04

### What did you do?
Using `ss-server`,
In `config.json`, set value of `server` as `[::]` (`"server":"[::]"`).

### What did you expect to see?
Listen to `::` as how it gets parsed when put in an array.

### What did you see instead?
```
 2019-02-17 01:35:42 INFO: tcp server listening at [[::]]:*****
 2019-02-17 01:35:42 ERROR: failed to resolve server name [::]
 2019-02-17 01:35:42 ERROR: failed to listen on any address
```

### What is your config in detail (with all sensitive info masked)?
```
{
    "server":"[::]",
    "server_port":*****,
    "password":"******",
    "timeout":300,
    "method":"aes-256-gcm"
}
```

### Proposed fix
In `jconf.c`:
Change lines 214-215: 
```
conf.remote_addr[0].host = to_string(value);
conf.remote_addr[0].port = NULL;
```
to: 
```
parse_addr(to_string(value), conf.remote_addr[0]);
```
so that the behaviors can be the same for addresses written in an array of strings vs. directly written in a string.

**Comment by madeye** [comment]
Submit a pull request instead.
