### ISSUE TITLE
请问如何理解iptables的tproxy模式了？

### ISSUE THREAD

**Issue by easonjim** [shadowsocks/shadowsocks-libev#2286]
请问如何理解iptables的tproxy模式了？主要是以下三个命令：
1、ip route add local default dev lo table 100
2、ip rule add fwmark 1 lookup 100
3、iptables -t mangle -A SHADOWSOCKS -p udp --dport 53 -j TPROXY --on-port 12345 --tproxy-mark 0x01/0x01
可以这样理解吗：DNS的查询服务转到本地127.0.0.1的DNS服务上？
但疑问是：为什么一定要指定本地的了？不能直接指向远端的服务器，比如直接指向8.8.8.8，或者自己搭建的DNS服务器了？

**Comment by lixingcong** [comment]
```ip route add local default dev lo table 100```创建策略路由表100

```ip rule add fwmark 1 lookup 100```标记了 1 的数据使用100路由表

```iptables -t mangle -A SHADOWSOCKS ....```目标53端口打标记1，并转发到本机端口12345

为什么一定要指定本地的了？本地的服务端是走加密ss-redir，防止污染

**Comment by easonjim** [comment]
@lixingcong 噢，可能明文传输过程中途可能会被篡改。那用了ss-redir之后还有必要用ss-tunnel进行53端口的映射吗？

**Comment by lixingcong** [comment]
防污染有两种，只能二选一

单使用ss-tunnel：指定本机DNS为127.0.0.1:xxxxx端口，不依赖ip rule和iptables

单使用ss-redir：指定本机为8.8.8.8，并使用ip rule和iptables进行redirect

**Comment by easonjim** [comment]
@lixingcong 明白了，感谢。另外如何理解iptables的透明代理TPROXY模式了？而不用原始的iptbles的snat记性udp的端口转发功能了？

**Comment by lixingcong** [comment]
http://fooy.github.io/blog/2016/06/17/how-udp-transparent-proxy-work/

随便找的，里面有一段：

> 代理服务一般都是处理多个连接的，tcp至少可以在每个连接建立时调用getsockopt(SO_ORIGINAL_DST)查找原始目的， 但是对于无连接的udp如果收到每个包都查一下，好像太消耗了..而且udp conn_track连接容易丢失.总之目前的内核网络架构不太适合udp转发..

**Comment by easonjim** [comment]
我这里又收集了一篇关于iptables tproxy模式的对比:
http://gsoc-blog.ecklm.com/iptables-redirect-vs.-dnat-vs.-tproxy/
