### ISSUE TITLE
为什么我按照文档操作后，连我的digtalOcean 服务器都上不去了？

### ISSUE THREAD

**Issue by niusz** [shadowsocks/shadowsocks-libev#2289]
{
    "server":["[::0]","0.0.0.0"],
    "server_port":1098,
    "password":"killgfw",
    "method":"chacha20-ietf-poly1305",
    "ipv6_first":true,
    "dns_ipv6":true,
    "fast_open":true,
    "timeout":600
}
我就是进入文件后，没有改原来文件的server_port ，其他的都按照上面的做了更改了。
### 连服务器时出现ssh: connect to host 159.89.130.118 port 22: Operation timed out

**Comment by buptzyf** [comment]
能ping通吗？  是不是被gfw干了？

**Comment by niusz** [comment]
> 能ping通吗？ 是不是被gfw干了？

不会ping，后来找到一个秋水逸冰的脚本重新装好了，不过还是很奇怪.

**Comment by jiaokang** [comment]
你这个问题跟shadowsocks服务没关系啊。你用ssh连的服务器，又不是shadowsocks
