### ISSUE TITLE
Bug report for brcm47xx serial routers

### ISSUE THREAD

**Issue by hduffddybz** [shadowsocks/shadowsocks-libev#229]
Recently, I port the openwrt to the ASUS RT-N16 router, which is brcm 47** serial. I try to use the shadowsocks client for openwrt(which version is shadowsocks_spec_2.0.7.ipk downloaded from sourceforge),I try to use the shadowsocks as the global proxy for the router and also use CHINADNS plus shadowsocks to cross the great wall, but almost all the time,it can only access to google and gmail, some websites such as facebook & twitter which is https version also blocked.Many people encounter this problem, any methods to solve it? In addition,It seems that Windows client did not have this problem.

**Comment by hduffddybz** [comment]
please read the comments on this site 
http://cokebar.info/archives/664
many people have problems that cannot access to facebook,twitter and dropbox

**Comment by madeye** [comment]
It's an issue of openwrt-shadowsocks, please open your issue here instead.
https://github.com/shadowsocks/openwrt-shadowsocks
