### ISSUE TITLE
Libsodium-dev >=1.0.12

### ISSUE THREAD

**Issue by biliair** [shadowsocks/shadowsocks-libev#2292]
### What version of shadowsocks-libev are you using?

3.2.3-1

### What operating system are you using?

VPS  Debian 9   OpenVZ  2.6.32

### What did you do?

mkdir shadowsocks-libev && cd shadowsocks-libev
apt-get install build-essential autoconf libtool libssl-dev \
  gawk debhelper dh-systemd init-system-helpers pkg-config git

git clone https://github.com/shadowsocks/shadowsocks-libev.git

cd shadowsocks-libev

dpkg-buildpackage -us -uc

### What did you see instead?

Unmet build dependencies: asciidoc-base | asciidoc libc-ares-dev libev-dev libmbedtls-dev libpcre3-dev libsodium-dev (>= 1.0.12) xmlto

and then 

apt-get install asciidoc-base | asciidoc libc-ares-dev libev-dev libmbedtls-dev libpcre3-dev libsodium-dev (>= 1.0.12) xmlto

dpkg-buildpackage -us -uc

but

![2019-02-23 17 59 00](https://user-images.githubusercontent.com/47517159/53285142-42fdd980-3798-11e9-9e34-095941221b0f.png)

**Comment by msg7086** [comment]
Incorrectly synced control file from Debian 10 causing unmet build dependencies libsodium-dev >= 1.0.12 against 1.0.11-2 from 24ecf4d.
