### ISSUE TITLE
the usability of the acl

### ISSUE THREAD

**Issue by updater1234** [shadowsocks/shadowsocks-libev#2294]
Please answer these questions before submitting your issue. Thanks!
# 请问现在的ss还可以使用这个acl吗？
> https://github.com/shadowsocks/shadowsocks-libev/blob/master/acl/chn.acl
(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?

4.6.5
### What operating system are you using?
Android

### What did you do?
Surfing the Internet

### What did you expect to see?
The acl  dosen' seem to work

**Comment by PantherJohn** [comment]
@updater1234 
It's not the latest ones. For updated lists please refer to the following links.
[ARIN database (including US, CA, and Puerto Rican IP addresses)](http://ftp.arin.net/pub/stats/arin/delegated-arin-extended-latest)
[APNIC database (Asian)](http://ftp.apnic.net/apnic/stats/apnic/delegated-apnic-latest)
Those are in CSV formats; you may also want the output to be in standard CIDR array format. A simple posix-compatible function should do the trick.
```
arin() {
    local authority
    local country="$1"; local version="$2"
    case ${country} in
        "US"|"CA"|"PR") authority='http://ftp.arin.net/pub/stats/arin/delegated-arin-extended-latest' ;;
        *) authority='http://ftp.apnic.net/apnic/stats/apnic/delegated-apnic-latest' ;;
    esac
    [ -z "${version}" ] && version="ipv4" 
    wget -qO- "${authority}" | grep "${version}" | grep "${country}" | awk -F'|' '{ printf("%s/%d\n", $4, 32-log($5)/log(2)) }'
}
```

Usage example
```
arin ipv6 US    # US ipv6 addresses
arin CN           # China ipv4 addresses
```

[ASN database](https://iptoasn.com/)
