### ISSUE TITLE
Missing instructions for plugin installation/activation

### ISSUE THREAD

**Issue by bugrabbit** [shadowsocks/shadowsocks-libev#2295]
The instructions in the readme/wiki do not feature any information on how to install plugins.

I just built the v2ray-plugin but do not know in which folder to place it or if it it needs to be installed otherwise.  Instructions on this cannot be found in the v2ray-plugin repository either and as I assume the procedure should be the same for every plugin - should be added to the shadowsocks-libev instructions.

### What version of shadowsocks-libev are you using?
3.2.3

### What operating system are you using?
Debian Stretch

### What did you do?
Built plugin

### What did you expect to see?
Instructions on how to install the plugin or reference it in the config file

### What did you see instead?
Nothing

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks-libev/blob/master/doc/shadowsocks-libev.asciidoc

**Comment by bugrabbit** [comment]
Thank you, but is it is still not clear to me. 
Does that mean the plugin should be placed in the same directory as the json file or can it be used like this:

`--plugin "absolute/path/to/plugin"`

Thanks!

**Comment by madeye** [comment]
Either should work.

**Comment by bugrabbit** [comment]
Thanks! It works! I needed to be sure to rule that out as a mistake as my configuration is not stable yet.
