### ISSUE TITLE
(aes-*-ctr) client connect (aes-*-cfb) server. Makes server blocking

### ISSUE THREAD

**Issue by tommyZZM** [shadowsocks/shadowsocks-libev#2297]
(aes-*-ctr) client connect (aes-*-cfb) server. Makes server blocking

### What version of shadowsocks-libev are you using?

lastest shadowsocks-libev download by apt install

### What operating system are you using?

Ubuntu 16

### What did you do?

Just start server and make a connection from client. Then the server totally blocking.

I found this happens only when I config a wrong encryption method in the client 

the client is (aes-*-ctr) and the server is (aes-*-cfb).

If I config a right method, every thing seems to be OK.

### What did you expect to see?

No server side blocking should happen? even client is using a wrong method in connection.

**Comment by madeye** [comment]
If you have the server misconfigured and try to connect it with the incorrect config for several times, your source IP will be blocked by the server.

Refer to your logs for more details.

**Comment by tommyZZM** [comment]
thx, The problem doesn't happen again. I think I should close the issue~
