### ISSUE TITLE
使用ss-redir，android google play 无法下载和更新软件，为什么?

### ISSUE THREAD

**Issue by endsock** [shadowsocks/shadowsocks-libev#2298]
### What version of shadowsocks-libev are you using?
3.2.3

### What operating system are you using?
ubuntu

### What did you do?
使用ss-redir做透明代理的时候，android google play 无法下载和更新软件
ss-redir已经开启了udp转发

### What is your config in detail (with all sensitive info masked)?
我的iptables配置如下
sudo iptables -t nat -N SHADOWSOCKS
sudo iptables -t mangle -N SHADOWSOCKS
sudo iptables -t nat -A SHADOWSOCKS -d 184.170.217.55 -j RETURN
sudo iptables -t nat -A SHADOWSOCKS -d 0.0.0.0/8 -j RETURN
sudo iptables -t nat -A SHADOWSOCKS -d 10.0.0.0/8 -j RETURN
sudo iptables -t nat -A SHADOWSOCKS -d 127.0.0.0/8 -j RETURN
sudo iptables -t nat -A SHADOWSOCKS -d 169.254.0.0/16 -j RETURN
sudo iptables -t nat -A SHADOWSOCKS -d 172.16.0.0/12 -j RETURN
sudo iptables -t nat -A SHADOWSOCKS -d 192.168.0.0/16 -j RETURN
sudo iptables -t nat -A SHADOWSOCKS -d 224.0.0.0/4 -j RETURN
sudo iptables -t nat -A SHADOWSOCKS -d 240.0.0.0/4 -j RETURN
sudo iptables -t nat -A SHADOWSOCKS -p tcp -j REDIRECT --to-ports 1085
sudo iptables -t nat -A SHADOWSOCKS -p udp -j REDIRECT --to-ports 1085
sudo iptables -t nat -A PREROUTING -p tcp -j SHADOWSOCKS
sudo iptables -t mangle -A PREROUTING -j SHADOWSOCKS

请问这是为什么？

**Comment by zmz125000** [comment]
DNS 过滤掉 AAAA records
https://www.google.com/search?q=unbound+filter+aaaa&safe=off
