### ISSUE TITLE
ss-redir crash

### ISSUE THREAD

**Issue by vpnrouter** [shadowsocks/shadowsocks-libev#230]
Hi there,I've ported ss-redir(1.6.1-1) on mt7620n chipset router one month ago,not openwrt platform，today one of my partners reported a rarely seen bug.It seems ss-redir opened too much sockets and not close them,this exceeded process resource limit.The system log keeps showing messages such as "ss-redir: accept:too many open files"  "kernel: TCP:too many of orphaned sockets".He had to reboot the router to work properly.
My partner didn't download huge amount of data via ss,just browse websites like youtube,and this bug happened randomly,the reason or in what condition caused this bug is totally unknown. Please work on this issue.And I wonder if you can make ss-server support multiple ports and passwords just like the original python version? 
Thanks for maintaining this C version ss project! 
Best regards!
I have a log screenshot from that partner as following:
![qq 20150118215842](https://cloud.githubusercontent.com/assets/10580073/5792656/efe13204-9f5e-11e4-87c4-364df75b7543.jpg)

**Comment by madeye** [comment]
Update to the latest version and try again.
