### ISSUE TITLE
IPv6 only server listens on IPv4 address only

### ISSUE THREAD

**Issue by bugrabbit** [shadowsocks/shadowsocks-libev#2300]
### What version of shadowsocks-libev are you using?
3.2.3

### What operating system are you using?
Debian Stretch

### What did you do?
execute `ss-server -c config.json`

### What did you expect to see?
Server starting up properly and listening on IPv6 address (as it is an IPv6 only server!)

### What did you see instead?

`INFO: plugin "v2ray-plugin" enabled`
`INFO: initializing ciphers... chacha20-ietf-poly1305`
`INFO: tcp server listening at 127.0.0.1:54269`
`ERROR: failed to resolve server name 127.0.0.1`
`ERROR: failed to listen on any address`

For somer reason the server listens on an IPv4 address even though it only has an IPv6 address.

### What is your config in detail (with all sensitive info masked)?
`{`
`    "server":"::1",`
`    "server_port":"443",`
`    "password":"mypassword",`
`    "timeout":60,`
`    "method":"chacha20-ietf-poly1305",`
`    "plugin":"v2ray-plugin",`
`    "plugin_opts":"server;tls;myserver.domain;cert=myserver.domain.cert;key=myserver.domain.key",`
`}`

Alternatively I tried `    "server":"[::1]",` with the same result.

**Comment by bugrabbit** [comment]
Specifying the network interface via `ss-server -i eth0 -c config.json` to avoid accidentally listening to the IPv4 loopback address of the lo device did not fix the problem, neither does adding the line `"ipv6_first": true` to the config.

**Comment by madeye** [comment]
Enable IPv4 on your loopback device.

Or run plug-in in standalone mode.

**Comment by madeye** [comment]
Also try 1441387.
