### ISSUE TITLE
ubuntu 16.04 shadowsocks-libev.service: Failed at step CAPABILITIES spawning /usr/bin/ss-server: Invalid argument

### ISSUE THREAD

**Issue by ptsa** [shadowsocks/shadowsocks-libev#2303]
ubuntu 16.04 
Current version:  3.24
shadowsocks-libev.service: Failed at step CAPABILITIES spawning /usr/bin/ss-server: Invalid argument

**Comment by ideal** [comment]
你的内核版本是？

**Comment by ptsa** [comment]
Ubuntu 16.04.6 LTS (GNU/Linux 2.6.32-042stab112.15 x86_64)

**Comment by ideal** [comment]
你的内核太老了。你把`/usr/lib/systemd/system/shadowsocks-libev@.service`里：
CapabilityBoundingSet=CAP_NET_BIND_SERVICE
这一行注释掉试试。

**Comment by CoolOppo** [comment]
Happens to me too.

**Comment by chenshaoju** [comment]
Note: In my case, The file at /lib/systemd/system/shadowsocks-libev.service

**Comment by reijin90** [comment]
> 你的内核太老了。你把`/usr/lib/systemd/system/shadowsocks-libev@.service`里：
> CapabilityBoundingSet=CAP_NET_BIND_SERVICE
> 这一行注释掉试试。

Would you mind translating this? I'd like to follow your advice :)

**Comment by ideal** [comment]
@reijin90 So it works now?

**Comment by reijin90** [comment]
Yes ;)
