### ISSUE TITLE
ss-manager didn't create ss-server process with my binding ports

### ISSUE THREAD

**Issue by Splaser** [shadowsocks/shadowsocks-libev#2306]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
latest

### What operating system are you using?
debian 9.5

### What did you do?
ss-manager can not create any ss-server processes

### What did you expect to see?
ss-manager with 11 ss-server processes

### What did you see instead?
![1](https://user-images.githubusercontent.com/9554026/53705749-9d1a3100-3e61-11e9-8526-13321c0cfeda.png)
But there is not any ss-server process opened by ss-manager.
I used ss-server to create one process. It worked fine.
![2](https://user-images.githubusercontent.com/9554026/53706179-f5eac900-3e63-11e9-85e0-474c0d6cceba.png)

### What is your config in detail (with all sensitive info masked)?
--manager.json
{
        "server":"0.0.0.0",
        "port_password": {
                "13800": "123456",
                "13801": "123456",
                "13802": "123456",
                "13803": "123456",
                "13804": "123456",
                "13805": "123456",
                "13806": "123456",
                "13807": "123456",
                "13808": "123456",
                "13809": "123456",
                "13810": "123456"
        },
        "timeout": 300,
        "method": "aes-192-gcm",
        "mode":"tcp_and_udp",
        "user":"nobody",
        "fast_open":true,
        "reuse_port": true
}

**Comment by madeye** [comment]
Remove `"user":"nobody",` from your config file. `ss-manager` should run within a user that has a home dir.

**Comment by Splaser** [comment]
OK.  Solved. Thanks.
