### ISSUE TITLE
3.2.4 breaks config parsing

### ISSUE THREAD

**Issue by felixonmars** [shadowsocks/shadowsocks-libev#2308]
### What version of shadowsocks-libev are you using?
3.2.4

### What operating system are you using?
Arch Linux x86_64

### What did you do?
Upgrade from 3.2.3 to 3.2.4 and start my ss-server as usual.

### What did you expect to see?
Server started normally.

### What did you see instead?
Port was wrong and the process won't listen correctly. The same config works correctly when passed with command line arguments, though.

### What is your config in detail (with all sensitive info masked)?
```
$ cat ss-test.json
{
    "server_host":"0.0.0.0",
    "server_port":1111,
    "password":"test",
    "method":"chacha20-ietf-poly1305"
}
$ ss-server -c ss-test.json
 2019-03-05 01:44:03 INFO: initializing ciphers... chacha20-ietf-poly1305
 2019-03-05 01:44:03 INFO: tcp server listening at 0.0.0.0:__vdso_getcpu
^C
$ ss-server -s 0.0.0.0 -p 1111 -k test -m chacha20-ietf-poly1305
 2019-03-05 01:44:40 INFO: initializing ciphers... chacha20-ietf-poly1305
 2019-03-05 01:44:40 INFO: tcp server listening at 0.0.0.0:1111
```

**Comment by madeye** [comment]
You config is incorrect. Replace 'server_host' to `server`.

Also try 14dd820

**Comment by felixonmars** [comment]
Sorry for the late response. I have tried to replace the config option and it works without the patch.

I haven't tried the commit yet.
