### ISSUE TITLE
在Ubuntu上怎么配置

### ISSUE THREAD

**Issue by miaoweiwei** [shadowsocks/shadowsocks-libev#2312]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

**Comment by tianlichunhong** [comment]
上面不是有安装教程和使用教程吗？晕
sudo apt-get install software-properties-common -y
sudo add-apt-repository ppa:max-c-lv/shadowsocks-libev -y
sudo apt-get update
sudo apt install shadowsocks-libev

**Comment by RayZhang** [comment]
之前的版本安装这个教程没问题，3.2.5版本用以上方法安装后服务不启动！

**Comment by miaoweiwei** [comment]
我配置了多个端口，但是有一个端口在链接时候的状态老是“SYN_SENT”，其他端口都正常
