### ISSUE TITLE
systemctl控制启动失败（带goquiet），提示找不到（goquiet的）配置文件

### ISSUE THREAD

**Issue by EricHerilan** [shadowsocks/shadowsocks-libev#2320]
### What version of shadowsocks-libev are you using?

> shadowsocks-libev 3.2.5

### What operating system are you using?

> 16.04.1-Ubuntu
> 4.10.0-42-generic 

### What did you do?
`$ sudo systemctl start shadowsocks-libev`
### What did you expect to see?

> ● shadowsocks-libev.service - Shadowsocks-libev Default Server Service
>    Loaded: loaded (/lib/systemd/system/shadowsocks-libev.service; disabled; vendor preset: enabled)
>    Active: active (running) since Tue 2019-03-12 06:36:50 UTC; 1s ago

### What did you see instead?

> ● shadowsocks-libev.service - Shadowsocks-libev Default Server Service
>    Loaded: loaded (/lib/systemd/system/shadowsocks-libev.service; disabled; vendor preset: enabled)
>    Active: failed (Result: exit-code) since Tue 2019-03-12 06:36:50 UTC; 1s ago
>      Docs: man:shadowsocks-libev(8)
>   Process: 3461 ExecStart=/usr/bin/ss-server -c $CONFFILE $DAEMON_ARGS (code=exited, status=255)
...
> Mar 12 06:36:50 Epic ss-server[3461]: On virtualized Linux environments, also consider using virtio-rng.
> Mar 12 06:36:50 Epic ss-server[3461]: The service will not start until enough entropy has been collected.
> Mar 12 06:36:50 Epic ss-server[3461]: 2019/03/12 06:36:50 gq-server.go:246: Configuration file error: open : no such file or directory
> Mar 12 06:36:50 Epic systemd[1]: shadowsocks-libev.service: Main process exited, code=exited, status=255/n/a

### What is your config in detail (with all sensitive info masked)?

```
{
	....
    "fast_open":false,
    "reuse_port":true,
    "no_delay":true,
    "plugin":"/etc/gqserver/gq-server-1.2.2",
    "plugin-opts":"/etc/gqserver/gqserver.json"
}
```
### 其他
但直接
`$ sudo ss-server -c /etc/shadowsocks-libev/config.json --plugin /etc/gqserver/gq-server-1.2.2 --plugin-opts /etc/gqserver/gqserver.json`
是能运行的
> 2019-03-12 06:43:08 INFO: plugin "/etc/gqserver/gq-server-1.2.2" enabled
>  2019-03-12 06:43:08 INFO: enable TCP no-delay
...
>  2019-03-12 06:43:08 INFO: running from root user
> 2019/03/12 06:43:08 gq-server.go:258: Listening on *********:*****
路径没错啊...

**Comment by madeye** [comment]
Make sure you're not run ss-server as nobody.

**Comment by EricHerilan** [comment]
Oh-yeah, @madeye you reminds me that I still use `shadowsocks-libev.service` as default set
I've try to change :
```
[Service]
...
User=root
```
But it till cannot fine the config files for goquiet.

> Mar 13 07:36:00 Epic ss-server[28943]:  2019-03-13 07:36:00 INFO: running from root user
> Mar 13 07:36:00 Epic ss-server[28943]: 2019/03/13 07:36:00 gq-server.go:246: Configuration file error: open : no such file or directory
> Mar 13 07:36:00 Epic ss-server[28943]:  2019-03-13 07:36:00 ERROR: plugin service exit unexpectedly

So I wondered if something wrong with ss-server then cannot read it's own config completely,
I changed `ExecStart=` as
```
[Service]
...
ExecStart=/usr/bin/ss-server -c /etc/shadowsocks-libev/config.json --plugin /etc/gqserver/gq-server-1.2.2 --plugin-opts /etc/gqserver/gqserver.json
```
than it worked 👍 

> ● shadowsocks-libev.service - Shadowsocks-libev Default Server Service
>    Loaded: loaded (/lib/systemd/system/shadowsocks-libev.service; enabled; vendor preset: enabled)
>    Active: active (running) since Wed 2019-03-13 07:50:39 UTC; 3s ago
>      Docs: man:shadowsocks-libev(8)
> ...
>    CGroup: /system.slice/shadowsocks-libev.service
>            ├─29093 /usr/bin/ss-server -c /etc/shadowsocks-libev/config.json --plugin /etc/gqserver/gq-server-1.2.2 --plugin-opts /etc/gqserver/gqserver.json
>            └─29094 /etc/gqserver/gq-server-1.2.2

Maybe I forgot some package when I install the shadowsocks-libev ...
By the way, I just used released goquiet's binary as a plugin directly.
