### ISSUE TITLE
More info on acl

### ISSUE THREAD

**Issue by imacks** [shadowsocks/shadowsocks-libev#2322]
### What version of shadowsocks-libev are you using?
3.2.5

### What operating system are you using?
linux alpine 3.9

I am looking at the acl feature on the server side. Am I right that `ss-server` only supports `[outbound_block_list]`? How can I make exceptions to a CIDR range? For example, I want 
clients to reach 10.10.123.123 on the server side through ss, but not the rest of the 10.0.0.0/8 range.

BTW, is there any doc on what these sections mean? I can't find an explanation anywhere:

```
[black_list]
[white_list]
[proxy_list]
[reject_all]
[bypass_all]
[accept_all]
```

**Comment by imacks** [comment]
Also, does ss-server support domain rewrite? For instance, when the client requests for `foo.bar.com` through shadowsocks, I would like ss-server to resolve the request from a predefined ip address. Or am I forced to use iptables?

**Comment by madeye** [comment]
They are internal features without any document.

And nope, you cannot do domain overwrite.

**Comment by imacks** [comment]
May I know whether `[outbound_block_list]` supports allow exceptions to its blocking cidr?

**Comment by madeye** [comment]
Nope.

**Comment by PantherJohn** [comment]
@imacks 
> Domain override
I assume you are referring to DNS resolution on the server side. It’s simple enough to install a caching nameserver (e.g. [`pdnsd`](http://members.home.nl/p.a.rombouts/pdnsd/)(caveat: NO LONGER MAINTAINED BUT STILL USEFUL FOR DNS CACHING), [`dnsmasq`]()(more syntax sugar, more extraneous features, included in most Linux distros)) on your server and force `ss-server` to redirect all DNS queries to it.
