### ISSUE TITLE
How to config firewall? Open tcp port, udp port or both?

### ISSUE THREAD

**Issue by dragon100a** [shadowsocks/shadowsocks-libev#2324]
### What version of shadowsocks-libev are you using?
Lastest

### What operating system are you using?
debian 9

### What did you do?
I installed shadowsocks-libev. It works.
Then I installed ufw. Ufw is short for uncomplicated firewall. It is a well-known firewall configuration tool.

So perhaps my port of ss is 12345. What ports should I open with the firewall? Tcp 12345, Udp 12345 or both?

**Comment by dragon100a** [comment]
It seems that tcp 12345 should be open, does it use udp 12345?

**Comment by RebelliousWhiz** [comment]
It depends what mode you are using. UDP mode —> 12345/udp, TCP mode —> 12345/TCP, both then both. Generally, you can open both ports, it’s fine.

**Comment by dragon100a** [comment]
> It depends on what mode you are using. UDP mode —> 12345/udp, TCP mode —> 12345/TCP, both then both. Generally, you can open both ports, it’s fine.

I check /etc/shadowsocks-libev/config.json.

`{
    "server":["[::0]","0.0.0.0"],
    "server_port":12345,
    "password":"abcde",
    "timeout":300,
    "user":"nobody",
    "method":"aes-256-gcm",
    "fast_open":true,
    "nameserver":"8.8.8.8",
    "mode":"tcp_and_udp"
}`

I find it is **"mode":"tcp_and_udp"**.
So just open both.

Thank you.
