### ISSUE TITLE
突然断流

### ISSUE THREAD

**Issue by 6cdh** [shadowsocks/shadowsocks-libev#2325]
System: Manjaro Linux 18.0.4

Shadowsocks-libev 3.2.5-1

使用 ss-local 时产生

```
Manjaro ss-local[575]:  INFO: initializing ciphers... chacha20-ietf-poly1305
Manjaro ss-local[575]:  INFO: This system doesn't provide enough entropy to quickly generate high-quality random numbers.
Manjaro ss-local[575]: Installing the rng-utils/rng-tools, jitterentropy or haveged packages may help.
Manjaro ss-local[575]: On virtualized Linux environments, also consider using virtio-rng.
Manjaro ss-local[575]: The service will not start until enough entropy has been collected.
```

开启 haveged 后可以使用了, 并且 haveged 工作正常.

随后使用过程中会随机断流一段时间, 查看日志没有任何异常, 手机端可以使用, 所以也不是服务器的问题. 等待一段时间后又突然可以使用. 断流期间重启 Shadowsocks-libev 服务没有效果. 

现象和未开启 haveged 服务一样

**Comment by flower-dog3** [comment]
i have meet this problem for a long time too after version of 3.2.4

**Comment by LBYPatrick** [comment]
那就试试rng-tools好了, 虽然我的机子什么都没装 (但原来也遇到过类似问题)...

> 我重装过机子之后就没这个问题了, 内核换到了``4.19.0-0.bpo.2-amd64``, 有兴趣可以试一下更新内核

> 曾经在某个地方看到过 "如果是比较现代的内核的话就什么都不用装，过一会儿就可以一直用了"

**Comment by 6cdh** [comment]
> 那就试试rng-tools好了, 虽然我的机子什么都没装 (但原来也遇到过类似问题)...
> 
> > 我重装过机子之后就没这个问题了, 内核换到了`4.19.0-0.bpo.2-amd64`, 有兴趣可以试一下更新内核
> 
> > 曾经在某个地方看到过 "如果是比较现代的内核的话就什么都不用装，过一会儿就可以一直用了"

即便不安装那几个工具, 而且系统熵池足够的情况下也会出现这种错误. 至于系统内核, 我现在的版本是 `4.19.28` , 显然并没有起到效果. 现在就在断流中, 不挂代理上 github 挺难受的...

**Comment by LBYPatrick** [comment]
> > 那就试试rng-tools好了, 虽然我的机子什么都没装 (但原来也遇到过类似问题)...
> > > 我重装过机子之后就没这个问题了, 内核换到了`4.19.0-0.bpo.2-amd64`, 有兴趣可以试一下更新内核
> > 
> > 
> > > 曾经在某个地方看到过 "如果是比较现代的内核的话就什么都不用装，过一会儿就可以一直用了"
> 
> 即便不安装那几个工具, 而且系统熵池足够的情况下也会出现这种错误. 至于系统内核, 我现在的版本是 `4.19.28` , 显然并没有起到效果. 现在就在断流中, 不挂代理上 github 挺难受的...

我有一个大胆的提议：你要不直接换成Debian 9吧

与Majero Linux (其实是Arch Linux的其中一个分支) 的高度精简相比，Debian很多东西都是提前装好的，况且Majero Linux是面向桌面用户的, 多装一个GUI界面意义不大。

> 我觉得开发者的shadowsocks-libev测试主机很有可能是Debian, Ubuntu, CentOS中的其中一个，所以三选一比较省事，用起来问题也少

**Comment by debiansid** [comment]
换一台ss-server

**Comment by LBYPatrick** [comment]
哦哦哦我明白了，你这个应该是被ISP拦的...解决方法包括但不限于:

- 用一个比较少见的端口(比如五位数的那种, 像80, 443这种肯定是重点盯的端口就不要选了)
- 把服务器端的超时时间拉长 (比如1440s)，减少连着连着突然就断了的可能性
- 把TCP Fast Open关掉(虽然开发者曾指出TFO如果无法使用的话会fallback回普通TCP连接，但试试也无妨)
- 换中国移动...

**Comment by 6cdh** [comment]
> 哦哦哦我明白了，你这个应该是被ISP拦的...解决方法包括但不限于:
> 
> * 用一个比较少见的端口(比如五位数的那种, 像80, 443这种肯定是重点盯的端口就不要选了)
> * 把服务器端的超时时间拉长 (比如1440s)，减少连着连着突然就断了的可能性
> * 把TCP Fast Open关掉(虽然开发者曾指出TFO如果无法使用的话会fallback回普通TCP连接，但试试也无妨)
> * 换中国移动...

我就是桌面用户, 图形环境还是需要的...系统换起来也太麻烦了, 以前用的 Arch 滚挂了, 再加上各种小问题, 于是换成了 Manjaro, Linux 的发行版太多, 选择困难症极其为难...

能用的方法大体都用过了, 排除下来可能是

- 操作系统问题
- 被墙识别

刚换了服务器, 先用一段时间看看

**Comment by 6cdh** [comment]
基本确定是被墙识别了, 识别方法可能与移动端的某些 APP 有关...也可能是使用过于频繁...
