### ISSUE TITLE
ss-redir 3.1.3开始失效

### ISSUE THREAD

**Issue by fooy** [shadowsocks/shadowsocks-libev#2326]
### What version of shadowsocks-libev are you using?
3.1.3

### What operating system are you using?
asus-merlin

### What did you do?
 反复测试，3.1.10工作正常，升级到3.1.13代码后透明代理就失效了 
自己编译的 ，难道是编译问题，
不断提示： ERROR: server recv: Connection reset by peer

服务器端3.x任意版本都能支持3.1.10的客户端，使用3.1.13客户端能看到服务器端收到了请求，但是代理的连接似乎卡在哪里了，页面无法打开

尝试git diff了一把，从3.1.10到3.1.13改动也很多，虽然redir.c没几行改动。。不知哪里入手

我是自己路由器上iptables + TPROXY 做了透明代理的，3.1.0之前一切正常，都很好用, 并且打开了-u参数同时转发udp/tcp .

**Comment by madeye** [comment]
Double check you have setup a local DNS forwarder correctly.

**Comment by fooy** [comment]
> Double check you have setup a local DNS forwarder correctly.

yes, nice suggestion 
the latest version worked after i change DNS servers to non-china IP.
i checked the diff between 3.1.2<->3.1.3 ,since youtube stopped loading after 'SNI' removed from the code , before that i just go with upstream DNS server provided by ISP. 
so seems before 3.1.2 it's the 'SNI' behind the scene keep doing the magic i just didn't aware of .

now it's been removed i have to think about how the DNS packets should be routed to avoid pollution or come up with some forwarder plan.
