### ISSUE TITLE
Build failure with latest self compiled libsodium

### ISSUE THREAD

**Issue by Amankwah** [shadowsocks/shadowsocks-libev#2328]
### What version of shadowsocks-libev are you using?
2254851e3f8476a7abfba986a04b69df7577919a

### What operating system are you using?
CentOS 7.6 with all package up to date

### What did you do?
$./autogen.sh
$./configure --prefix=/opt/shadowsocks --with-sodium=/usr/local/lib/libsodium --disable-documentation
...
checking whether mbedtls supports the Camellia block cipher or not... ok
checking for sodium_init in -lsodium... no
configure: error: The Sodium crypto library libraries not found.

### What did you expect to see?
configure success

### What did you see instead?
...
checking whether mbedtls supports the Camellia block cipher or not... ok
checking for sodium_init in -lsodium... no
configure: error: The Sodium crypto library libraries not found.

### What is your config in detail (with all sensitive info masked)?
/usr/local/lib/libsodium is the location where I install the libsodium from https://github.com/jedisct1/libsodium.git with commit 32e36af97ef2116179cf6489e1f95f31d6b14e95

the version value in version.h is below:
#ifndef sodium_version_H
#define sodium_version_H

#include "export.h"

#define SODIUM_VERSION_STRING "1.0.17"

#define SODIUM_LIBRARY_VERSION_MAJOR 10
#define SODIUM_LIBRARY_VERSION_MINOR 2
...

### The file list of /usr/local/lib/libsodium/lib
ibsodium.a   libsodium.so     libsodium.so.23.2.0
libsodium.la  libsodium.so.23  pkgconfig

### ------------
The build operation was always succeed but recently failed.

**Comment by madeye** [comment]
Add `--with-sodium-include=/usr/local/lib/libsodium/include`.

**Comment by Amankwah** [comment]
> Add `--with-sodium-include=/usr/local/lib/libsodium/include`.

I still got a failure with --with-sodium-include=/usr/local/lib/libsodium/include --with-sodium-lib=/usr/local/lib/libsodium/lib

**Comment by PantherJohn** [comment]
@Amankwah 
> /usr/local/lib/libsodium

Does this directory even exist on your machine?

**Comment by Amankwah** [comment]
@PantherJohn 
Yes, I had installed latest libsodium there.
