### ISSUE TITLE
ss-redir not in brew shadowsocks-libev

### ISSUE THREAD

**Issue by rsun-thoughtworks** [shadowsocks/shadowsocks-libev#2329]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
3.2.5

### What operating system are you using?
MacOS V10.13.6

### What did you do?
try to run ss-redir, but got not found error

### What did you expect to see?
work fine

### What did you see instead?
command not found: ss-redir

### What is your config in detail (with all sensitive info masked)?
brew install shadowsocks-libev

### How to configure macOS

can anyone help to translate
```
iptables -t nat -A SHADOWSOCKS -p tcp -j REDIRECT --to-ports 12345
```

to command that macOS support.

Great Thanks

**Comment by madeye** [comment]
macOS doesn't have `iptables`.

**Comment by rsun-thoughtworks** [comment]
> macOS doesn't have `iptables`.

I am aware of that and that's why I ask if anyone can help translate this from iptables to macOS compatible command.

Which, I am grateful of.

**Comment by madeye** [comment]
Nope, you can't. `ss-redir` relies on `iptables`, and won't work in macOS.

**Comment by rsun-thoughtworks** [comment]
> Nope, you can't. `ss-redir` relies on `iptables`, and won't work in macOS.

So I can not use ss-redir on macOS?

Please close this if macOS is not an option.

**Comment by rsun-thoughtworks** [comment]
> Nope, you can't. `ss-redir` relies on `iptables`, and won't work in macOS.

Another question, when we install from brew, we cannot found ss-redir.

**Comment by PantherJohn** [comment]
There SHOULD be a fix for this. 
The socket option `SO_ORIGINAL_DST` is only available in Linux (where iptables are present), while in other UNIX distros (e.g. *BSD which uses pf) it should be a bit more complicated than playing with options come in handy. 

https://github.com/shadowsocks/shadowsocks-libev/blob/3590860a997b92bf7af493601cc6f3827be57cd9/src/redir.c#L104-L118

A more comprehensive solution is [this](https://github.com/darkk/redsocks/blob/master/base.c)
Excerpted from the source code of [`redsocks`]() by @darkk

**Comment by madeye** [comment]
No plan to support PF.

**Comment by PantherJohn** [comment]
@madeye Well I don’t think adding code for PF comes at a large cost. Instead this increases portability.

**Comment by madeye** [comment]
Just try `redsocks` + `ss-local`.

**Comment by rsun-thoughtworks** [comment]
> Just try `redsocks` + `ss-local`.

Thanks, I can understand. Open source is hard. Besides, you need your own life.

It's totally ok. I'll close this then.
