### ISSUE TITLE
BUG Don't listen on ipv4 when both listen on v4 & v6

### ISSUE THREAD

**Issue by kxmp** [shadowsocks/shadowsocks-libev#233]
Newest ss only listen on ipv6 port when have this config file
"server":"0.0.0.0",
"server":"::",
.....
But if i use this config file,ss can listen both v4 & v6 port
"server":"::",
"server":"0.0.0.0",
....

I'm using debian v7 x64

**Comment by KrazyIvan-** [comment]
This is fixed in 2.1.1 build

**Comment by madeye** [comment]
Fixed via 70f17645defd2250b25b857105a2b0f4640ea5b5

**Comment by KrazyIvan-** [comment]
Not via 70f1764, previous one https://github.com/shadowsocks/shadowsocks-libev/commit/28b3793b23e6e65424903bef2ba144667bbe9818
