### ISSUE TITLE
SS-libev这种情况还需要部署fail2ban吗?

### ISSUE THREAD

**Issue by kang000feng** [shadowsocks/shadowsocks-libev#2333]
查看syslog 发现有 握手失败的IP连接请求,  然后该IP都被 block all respond
想请问

a) SS-libev真的是自带blocklist? 如果是这样的话还需要部署fail2ban吗?

b).SS-libev连接密码错误多少次进入block_list, 多久会释放出来?

c) 对于timeout没有接收到FIN包的ip会不会也被判为握手失败然后被打进block_list?  

 
谢谢各路大佬指点

**Comment by madeye** [comment]
Nope.
