### ISSUE TITLE
build failed on ubuntu 18.04

### ISSUE THREAD

**Issue by xcjiang** [shadowsocks/shadowsocks-libev#2336]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
3.2.5

### What operating system are you using?
ubuntu 18.04

### What did you do?
follow the instruction in README, run build_deb.sh

### What did you expect to see?
build success

### What did you see instead?
no shadowsocks deb, only libbloom.deb and simple-obfs deb.
and find this in stdout:

> gbp:info: Creating /root/build-area/shadowsocks-libev_3.2.5+ds.orig.tar.xz
> gbp:error: Error creating shadowsocks-libev_3.2.5+ds.orig.tar.xz: Pristine-tar couldn't checkout "shadowsocks-libev_3.2.5+ds.orig.tar.xz": fatal: Path 'shadowsocks-libev_3.2.5+ds.orig.tar.xz.delta' does not exist in 'refs/heads/pristine-tar'
> pristine-tar: git show refs/heads/pristine-tar:shadowsocks-libev_3.2.5+ds.orig.tar.xz.delta failed
> HEAD is now at 7321148 Prepare new upload (3.2.5+ds-1, unstable)
> /root/build-area
> dpkg: error: cannot access archive 'shadowsocks-libev_*.deb': No such file or directory

**Comment by JoshDaone** [comment]
Have the exactly same issue, Ubuntu 18.04

```
Setting up shadowsocks-libev-build-deps (3.2.5+ds-1) ...
Processing triggers for libc-bin (2.27-3ubuntu1) ...
gbp:info: Creating /root/build-area/shadowsocks-libev_3.2.5+ds.orig.tar.xz
gbp:error: Error creating shadowsocks-libev_3.2.5+ds.orig.tar.xz: Pristine-tar couldn't checkout "shadowsocks-libev_3.2.5+ds.orig.tar.xz": fatal: Path 'shadowsocks-libev_3.2.5+ds.orig.tar.xz.delta' does not exist in 'refs/heads/pristine-tar'
pristine-tar: git show refs/heads/pristine-tar:shadowsocks-libev_3.2.5+ds.orig.tar.xz.delta failed
HEAD is now at 7321148 Prepare new upload (3.2.5+ds-1, unstable)
/root/build-area
dpkg: error: cannot access archive 'shadowsocks-libev_*.deb': No such file or directory
Reading package lists... Done
Building dependency tree
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.
```
