### ISSUE TITLE
ss-manager does not start servers after restarting ss-manager process

### ISSUE THREAD

**Issue by nycterent** [shadowsocks/shadowsocks-libev#2337]
### What version of shadowsocks-libev are you using?
3.2.5

### What operating system are you using?

debian 9

### What did you do?

I want to use ss-manager to configure multiple ports/passwords

### What did you expect to see?

And I expect those provisioned servers to be started after ss-manager restart

### What did you see instead?

There are no servers provisioned and started, also list command returns empty list. Is this expected?

### What is your config in detail (with all sensitive info masked)?
{
    "server":"IP",
    "server_port":1300,
    "local_port":1080,
    "password":"ov",
    "port_password":"ov",
    "timeout":60,
    "method":"aes-256-cfb",
    "nameserver": "1.1.1.1",
}

**Comment by madeye** [comment]
Try https://github.com/shadowsocks/shadowsocks-manager
