### ISSUE TITLE
最新的ss-libev无法编译

### ISSUE THREAD

**Issue by fidowang** [shadowsocks/shadowsocks-libev#2341]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
v3.2.5

### What operating system are you using?
debian 9.8

### What did you do?
之前在vps自行编译安装libsodium和ss-libev都正常，一直使用到现在，
今天git pull 了libsodium和ss-libev，libsodium的编译安装过程正常
之后在ss-libev目录下 ./configure 则一直如下报错。

后来重新clone甚至把vpsrebuild并重新编译安装libsodium、shadowsocks-libev都是同样的报错

### What did you see instead?
checking for thread local storage (TLS) class... __thread
checking for mbedtls_cipher_setup in -lmbedcrypto... yes
checking whether mbedtls supports Cipher Feedback mode or not... ok
checking whether mbedtls supports the ARC4 stream cipher or not... ok
checking whether mbedtls supports the Blowfish block cipher or not... ok
checking whether mbedtls supports the Camellia block cipher or not... ok
checking for sodium_init in -lsodium... no
configure: error: The Sodium crypto library libraries not found.

### What is your config in detail (with all sensitive info masked)?
libsodium ss-libev都是重新clone 干净的版本。
libsodium 编译安装后

ls /usr/lib/libsodium*
ls: cannot access '/usr/lib/libsodium*': No such file or directory

ls /usr/local/lib/libsodium*
/usr/local/lib/libsodium.a   /usr/local/lib/libsodium.so.23
/usr/local/lib/libsodium.la  /usr/local/lib/libsodium.so.23.2.0
/usr/local/lib/libsodium.so

ldconfig -v
/usr/local/lib:
        libsodium.so.23 -> libsodium.so.23.2.0

**Comment by madeye** [comment]
Just test on a clean installed Debian 9.8. 

Everything works well with latest stable branch of libsodium.

**Comment by debiansid** [comment]
安装libsodium 加上 —prefix=/usr
