### ISSUE TITLE
Did shadowsoks-libev change code about dns resolving since 3.1.3?

### ISSUE THREAD

**Issue by AntiverX** [shadowsocks/shadowsocks-libev#2342]
I found a lot of issues about DNS problem when upgrading to 3.1.3. And they need to user China DNS  etc. to solve DNS posioning.

But DNS works well on 3.1.2 under same environment. So I think there must be some changes about DNS in the source code.

Can anyone explain the reason?

Thanks.

**Comment by AntiverX** [comment]
![QQ截图20190401143909](https://user-images.githubusercontent.com/22369960/55308036-fc348b00-548b-11e9-9042-ccce77a93112.jpg)

I download commits between 3.1.3 and 3.1.2 and compile then all.

I found that after this commit [https://github.com/shadowsocks/shadowsocks-libev/commit/d41508292f7df5aeac00bbd4867bc37e285a605e](url)

DNS problem happened on shadowsock-libev.

All the compile options are default.

**Comment by AntiverX** [comment]
My Bad. This is the right commit [539bf6e66d86533a0c39cc6aa8d5be51bf1ccba4](https://github.com/shadowsocks/shadowsocks-libev/commit/539bf6e66d86533a0c39cc6aa8d5be51bf1ccba4) resulting in DNS problem.

**Comment by madeye** [comment]
Don't rely on SNI to avoid DNS poisoning.

All SNI features are disabled for ss-redir now. Therefore, the behavior is expected.

**Comment by PantherJohn** [comment]
@madeye I don't think there are problems with the built-in support for SNI header parsing.
Here's a single file library that can extract hostname from HTTP, TLS, and QUIC packets.
https://github.com/PantherJohn/xt_tls/blob/master/src/dustin.h
originally written by @dlundquist @Lochnair
