### ISSUE TITLE
-f <pid_file> doesn't work with v2ray-plugin

### ISSUE THREAD

**Issue by Nidhoggur1993** [shadowsocks/shadowsocks-libev#2343]
### What version of shadowsocks-libev are you using?
Shadowsocks-libev 3.2.0
a605fd0b01cf44f6f69e343a7470deb0  v2ray-plugin_linux_amd64

### What operating system are you using?
CentOS Linux release 7.6.1810 (Core) 
Linux localhost 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 29 14:49:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### What did you do?
sudo ss-server -c /path/to/config.json -f /var/run/8388.pid

### What did you expect to see?
ss-server runs in background

### What did you see instead?
it doesn't runs in background, but if I run without -f <pid_file> using the same config.json, everything works fine

### What is your config in detail (with all sensitive info masked)?
{
    "server":["0.0.0.0"],
    "server_port":8388,
    "local_port":1082,
    "password":"passphrase",
    "timeout":30,
    "method":"chacha20",
    "nameserver": "8.8.8.8,8.8.4.4,2001:4860:4860::8888,2001:4860:4860::8844",
    "mode": "tcp_and_udp",
    "plugin":"/path/to/v2ray-plugin_linux_amd64",
    "plugin_opts":"server;quic;host=www.2345.com",
    "no_delay": true,
    "fast_open": false,
    "reuse_port": true
}

**Comment by chenhw2** [comment]
upgrade shadowsocks-libev to 3.2.5

**Comment by Nidhoggur1993** [comment]
> upgrade shadowsocks-libev to 3.2.5

seems like librehat-shadowsocks doesn't have 3.2.5, should I manual compile ?
