### ISSUE TITLE
最新的ss-libev版本3.2.5，似乎 Debian 9 (Stretch)上没有，能同步更新一下么

### ISSUE THREAD

**Issue by 2628202057** [shadowsocks/shadowsocks-libev#2344]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

**Comment by jhoneybee** [comment]
此项目负责源码的讨论,以及BUG的修复,Debian的软件包请咨询下Debian社区的DM 

## 维护小组名单

+ Roger Shimizu max.c.lv#gmail.com
+ Max Lv max.c.lv#gmail.com
+ Boyuan Yang 073plan@gmail.com

## 相关的链接地址

+ https://packages.debian.org/stretch/shadowsocks-libev

**Comment by LBYPatrick** [comment]
这个比较好解决，加一下stretch-backports源就可以了.

具体来说就是这样:

```
echo deb http://deb.debian.org/debian stretch-backports main >> /etc/apt/sources.list
apt update
apt -t stretch-backports install -y shadowsocks-libev
```

**Comment by terrytw** [comment]
https://packages.debian.org/sid/shadowsocks-libev
拉到最下面可以直接下载deb包
不知道为何这个版本推送到stable的速度比较慢

**Comment by troutperch** [comment]
> 不知道为何这个版本推送到stable的速度比较慢

https://github.com/shadowsocks/shadowsocks-libev/blob/master/README.md :

> 
> For **Debian 9 (Stretch)** users, please install it from `stretch-backports`:
> We strongly encourage you to install shadowsocks-libev from `stretch-backports`.
> For more info about backports, you can refer [Debian Backports](https://backports.debian.org).
> 
> ```bash
> sudo sh -c 'printf "deb http://deb.debian.org/debian stretch-backports main" > /etc/apt/sources.list.d/stretch-backports.list'
> sudo apt update
> sudo apt -t stretch-backports install shadowsocks-libev
> ```

**Comment by terrytw** [comment]
Shadowsocks-libev is still at 3.2.3 in "stretch-backports" if you are not
aware. We are discussing why devs have not updated it to the lastest 3.2.5.

troutperch <notifications@github.com> 于 2019年4月16日周二 23:01写道：

**Comment by terrytw** [comment]
原来是因为debian buster即将发布，package全部冻结的原因
急着升级就自己编译吧

**Comment by qwerttvv** [comment]
要是可以的话，更新及时就最好啦

**Comment by hosiet** [comment]
https://tracker.debian.org/pkg/shadowsocks-libev

We are providing v3.3.3 across Debian 9, Debian 10 and Debian Testing/Sid in Debian official repositories currently and will track upstream latest releases in the foreseeable future. You may need to enable the `buster-backports` and `stretch-backports-sloppy` repos to use them. Please refer to the introduction on https://backports.debian.org on how to use backport-related repos.
