### ISSUE TITLE
Decryption error

### ISSUE THREAD

**Issue by EricHerilan** [shadowsocks/shadowsocks-libev#2345]
### What version of shadowsocks-libev are you using?

shadowsocks-libev 3.2.5

### What operating system are you using?

16.04.6 LTS
4.10.0-42-generic

### What did you do?

Start client

### What did you expect to see?

> [/] connect to ###.#########.###:443
> [/] Socket connected to ss server: A (#############:#####)

### What did you see instead?

> **[/] [E] decryption error**
> **[/] [E] decryption error**

### What is your config in detail (with all sensitive info masked)?

> [2019-04-06 19:22:56] connect to ###.#########.###:443
> [2019-04-06 19:22:58] Started SIP003 plugin for #############:##### on 127.0.0.1:8455 - PID: 9704
> [2019-04-06 19:22:58] connect to ###.#########.###:443
> [2019-04-06 19:22:58] Started SIP003 plugin for #############:##### on 127.0.0.1:8459 - PID: 16608
> [2019-04-06 19:22:58] Socket connected to ss server: A (#############:#####)
> [2019-04-06 19:22:58] connect to ###.#########.###:443
>...
> [2019-04-06 19:22:59] Socket connected to ss server: B (#############:#####)
> **[2019-04-06 19:23:00] [E] decryption error**
> [2019-04-06 19:23:00] connect to ###.#########.###:443
>...
> [2019-04-06 19:23:00] Started SIP003 plugin for #############:##### on 127.0.0.1:8482 - PID: 3048
> [2019-04-06 19:23:00] connect to ###.#########.###:443
> [2019-04-06 19:23:00] Socket connected to ss server: B (#############:#####)
> **[2019-04-06 19:23:29] [E] decryption error**
> **[2019-04-06 19:23:30] [E] decryption error**
> **[2019-04-06 19:23:31] [E] decryption error**
> [2019-04-06 19:23:32] connect to ###.#########.###:443
>...
> [2019-04-06 19:24:30] Socket connected to ss server: C (#############:#####)
> **[2019-04-06 19:24:31] [E] decryption error**
> **[2019-04-06 19:24:31] [E] decryption error**

服务器方面没有报错。
然后就流量时有时无，负载均衡模式下，每个服务器使用了不同的插件，不知道是不是因为这个原因...
只连单个服务器是没问题的。

**Comment by studentmain** [comment]
加密是不是GCM，ss-windows有个类似的

**Comment by EricHerilan** [comment]
谢谢，的确是一样的问题，应该是客户端的事了
加密分别用的是`ChaCha20-Poly1305`和`xChaCha20-Poly1305`
密码改一样后就没再报错了
