### ISSUE TITLE
A large number of "spurious transmissions" have emerged.

### ISSUE THREAD

**Issue by jhoneybee** [shadowsocks/shadowsocks-libev#2346]
>> I know this is not a software problem, just to discuss the reasons for the situation.

## environment

| key       |value 
|-----       |-------
|Window 10 | version 10.0.17134 
|shadowsocks-windows| 4.1.5
|shadowsocks-libev | shadowsocks-libev 2.6.3 with mbed TLS 2.4.2

## questions
A large number of "spurious transmissions" have emerged.

![image](https://user-images.githubusercontent.com/24241052/55693710-241f7380-59e3-11e9-9a29-1747a8da5763.png)

**Comment by jhoneybee** [comment]
> I tracked TCP and found the following

![image](https://user-images.githubusercontent.com/24241052/55693852-d9eac200-59e3-11e9-9e2a-33b9fc7c642a.png)

**Comment by madeye** [comment]
Looks some issue related to your NAT devices.

**Comment by jhoneybee** [comment]
> Looks some issue related to your NAT devices.

But what is the general scenario of this problem? 

>This information is very vague to me. normal use of the network does not cause this problem

**Comment by jhoneybee** [comment]
> Looks some issue related to your NAT devices.

Because of network instability, network links can only be optimized.
