### ISSUE TITLE
Your system ubuntu/cosmic is not supported yet

### ISSUE THREAD

**Issue by luxin88** [shadowsocks/shadowsocks-libev#2350]
when I build build_deb.sh, it not success, and it say:

Your system ubuntu/cosmic is not supported yet.
Please report issue:
    https://github.com/shadowsocks/shadowsocks-libev/issues/new

**Comment by lastczj** [comment]
You should install from the official warehouse.
`https://packages.ubuntu.com/disco/shadowsocks-libev`

**Comment by R8s6** [comment]
https://packages.ubuntu.com/search?keywords=shadowsocks-libev&searchon=names

it is included in 18.10. 
https://packages.ubuntu.com/search?keywords=shadowsocks-libev&searchon=names

From the terminal, just enter:

sudo apt update && sudo apt upgrade -y
sudo apt install shadowsocks-libev
