### ISSUE TITLE
README文档能否提供一个启动命令样例

### ISSUE THREAD

**Issue by Zhan-Jie** [shadowsocks/shadowsocks-libev#2351]
建议

- 在README文档里，能否说明一下ss-local，ss-server，ss-redir等几个命令有什么区别？

- 能否提供一个像shadowsocks python版本那样的启动命令的参考样例，否则对新人不太友好，安装完后如何启动，应该使用哪个命令(ss-*)都不清楚

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks-libev/blob/master/doc/shadowsocks-libev.asciidoc
