### ISSUE TITLE
ss连接数量

### ISSUE THREAD

**Issue by ffbh** [shadowsocks/shadowsocks-libev#2352]
ss同时可以连接几个客户端呢，json文件里面好像没有类似**最大连接数量**的字段

**Comment by troutperch** [comment]
Please read https://github.com/shadowsocks/shadowsocks-libev/blob/master/README.md first:

> ## Security Tips
> [...] Although shadowsocks-libev can handle thousands of concurrent connections nicely, we still recommend setting up your server's firewall rules to limit connections from each user:
> 
>     # Up to 32 connections are enough for normal usage
>     iptables -A INPUT -p tcp --syn --dport ${SHADOWSOCKS_PORT} -m connlimit --connlimit-above 32 -j REJECT --reject-with tcp-reset

**Comment by timorpic** [comment]
Limit the number of connections

**Comment by PantherJohn** [comment]
@timorpic @troutperch ‘s answer is correct. You should add `iptables` rules via command line to limit the number of **concurrent** connections. (not the number of clients! Please note that there’s no way to implement client connection tracking without making thorough changes to the protocol)

If you still have no idea what all TCP/IP and iptables stuffs are about I suggest you take a tutorial on computer networking basics before submitting issues.
