### ISSUE TITLE
Define interface to bind in config file

### ISSUE THREAD

**Issue by amphineko** [shadowsocks/shadowsocks-libev#2353]
### What version of shadowsocks-libev are you using?
shadowsocks-libev 3.2.3

### What operating system are you using?
Debian Stretch @ 4.19.0-0.bpo.4-amd64

### What did you do?
Try to define the interface to bind in `config.json`.

### What did you expect to see?
An option equals to `-i` command argument.

### What did you see instead?
None.

### What is your config in detail (with all sensitive info masked)?
N/A.

**Comment by madeye** [comment]
It's expected. Just pass the device name in command line.

**Comment by amphineko** [comment]
If I have understood correctly, this means defining interface to bind via config file won't be implemented and should be configured via command line?

I have tried `ss-server -c /etc/shadowsocks-libev/config.json -i device` which works but sounds not good.

**Comment by madeye** [comment]
It you want to specify the output address in `ss-server`, try `local_address` instead.

If an option is not included in `config.json`, it's expected to be experimental or unstable.

**Comment by amphineko** [comment]
Thanks a lot! `-b local_address` solved my problem.

However, the description `Local address to bind.` for `-b` is confusing and sounds like the option `-s` but not the address to be used for outbound connections.

I think this could be improved. Should I make a pull request for it?

**Comment by madeye** [comment]
Yeah, please open a pull request.
