### ISSUE TITLE
ERROR: setinterface: Operation not permitted

### ISSUE THREAD

**Issue by amphineko** [shadowsocks/shadowsocks-libev#2354]
### What version of shadowsocks-libev are you using?
shadowsocks-libev 3.2.3

### What operating system are you using?
Debian Stretch @ 4.19.0-0.bpo.4-amd64

### What did you do?
Using `-i` option with `nobody` user.
e.g `ss-server -c /etc/shadowsocks-libev/config.json -a nobody -i somedevice`

### What did you expect to see?
Working perfectly.

### What did you see instead?
```
INFO: tcp server listening at x.x.x.x:x
ERROR: setinterface: Operation not permitted
```
Notably, `setinterface` failure occurs while an inbound connection happens, not immediately after the start.

**Comment by amphineko** [comment]
https://github.com/shadowsocks/shadowsocks-libev/blob/f35c1623576e0a084b1b2e07b1a77017ddb4e0ae/src/netutils.c#L81

Looks like `setsockopt` cannot be invoked when the process drops its root privilege.

**Comment by madeye** [comment]
It's expected.

If you want to bind any interface in `nobody`, make sure you've granted the executable `CAP_NET_RAW` permission.

**Comment by amphineko** [comment]
https://github.com/shadowsocks/shadowsocks-libev/blob/f35c1623576e0a084b1b2e07b1a77017ddb4e0ae/debian/shadowsocks-libev.service#L18

I have tried to grant `CAP_NET_RAW` by adding the capabilities in the service file.

```
CapabilityBoundingSet=CAP_NET_BIND_SERVICE CAP_NET_RAW
AmbientCapabilities=CAP_NET_BIND_SERVICE CAP_NET_RAW
```

This won't solve the problem and the server still giving `ERROR: setinterface: Operation not permitted`.

**Comment by madeye** [comment]
Not sure why it didn't work. You may refer to this: https://stackoverflow.com/questions/35229902/why-does-cap-net-raw-not-work-with-so-bindtodevice

**Comment by kimw** [comment]
It's just because of the systemd. Your systemd maybe outaged. But you're not done. Try `sudo setcap cap_net_bind_service,cap_net_raw=+ep /usr/bin/ss-server`, it brings shadowsocks back to you.

**Comment by amphineko** [comment]
@kimw I'm not sure if the problem is caused by systemd.

```
$ systemctl --version
systemd 241 (241)
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid
```

**Comment by kimw** [comment]
@amphineko,

1. 
    > I'm not sure if the problem is caused by systemd.

    Maybe yes, maybe no. It depends.

2. Dose the `sudo setcap cap_net_bind_service,cap_net_raw=+ep /usr/bin/ss-server` work?
