### ISSUE TITLE
The service seems to be running, however the clients I use can't connect.

### ISSUE THREAD

**Issue by ilovuxay** [shadowsocks/shadowsocks-libev#2356]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?

 shadowsocks-libev                                            x86_64                                            3.2.0-2.el7                                               librehat-shadowsocks                                          260 k
                                           

### What operating system are you using?

CentOS 7 x64

### What did you do?

systemctl stop firewalld.service #停止firewall
systemctl disable firewalld.service #禁止firewall开机启动
yum install shadowsocks-libev

### What did you expect to see?

Successfully connected to my own vps on my android phone, using ss 4.7.4 (downloaded in https://github.com/shadowsocks/shadowsocks-android/releases )

 just like those two servers in https://github.com/Alvin9999/new-pac/wiki/ss%E5%85%8D%E8%B4%B9%E8%B4%A6%E5%8F%B7 .

These two servers can be successfully connected both on my pc and phone.

### What did you see instead?

Can't resolve google.com ,etc...

### What is your config in detail (with all sensitive info masked)?

The default.
{
    "server":"127.0.0.1",
    "server_port":8388,
    "local_port":1080,
    "password":"barfoo!",
    "timeout":60,
    "method":"chacha20-ietf-poly1305"
}

### The service seems to be running, however the clients I use can't connect.
What could potential problems be?

![image](https://user-images.githubusercontent.com/17734954/56460603-b4908780-63d7-11e9-812a-7f3dcf24baef.png)

![image](https://user-images.githubusercontent.com/17734954/56460641-6def5d00-63d8-11e9-94a8-468085b10377.png)

**Comment by ilovuxay** [comment]
PS: I'm a completely novice on Linux system. .. And also my friends.

**Comment by ilovuxay** [comment]
oh, there's also a SSR server installed on this system, which is now running properly and we can use ssr client on PC to connect the VPS and visit google.  (The port is 443, not 8388 which ss-libev uses. )

**Comment by ilovuxay** [comment]
![image](https://user-images.githubusercontent.com/17734954/56467006-ecd1ad80-644b-11e9-8d47-d5bd5859cb32.png)

**Comment by lucifer0114** [comment]
Change your port. 
It has told you "Address already in use".

**Comment by ilovuxay** [comment]
![image](https://user-images.githubusercontent.com/17734954/56467350-4b008f80-6450-11e9-8a30-aee0f5a8ec1d.png)

![image](https://user-images.githubusercontent.com/17734954/56467356-58b61500-6450-11e9-8fb9-73defe8d94c6.png)

So could it be that the ss server service conflicts with the ssR server service ? Should I  reset and clean the VPS operating system?

**Comment by lucifer0114** [comment]
Perhaps.
Reinstalling in a clean operating system might be the best way.

**Comment by ilovuxay** [comment]
I reinstalled the OS, and then have merely done these orders:

yum install dnf
yum update
dnf install 'dnf-command(copr)  
dnf copr enable librehat/shadowsocks
yum install shadowsocks-libev
yum install vim
systemctl start shadowsocks-libev
systemctl status shadowsocks-libev


![image](https://user-images.githubusercontent.com/17734954/56467731-746fea00-6455-11e9-81fb-f49ea2e11477.png)

 2019-04-21 08:47:47 ERROR: bind: Address already in use
 2019-04-21 08:47:47 ERROR: bind() error

**Comment by lucifer0114** [comment]
"server":["[::0]", "0.0.0.0"]
NOT "server":"127.0.0.1"

**Comment by ilovuxay** [comment]
So it is ?

vim /etc/default/shadowsocks-libev
![image](https://user-images.githubusercontent.com/17734954/56468115-4345e880-645a-11e9-827a-9009648265a1.png)

systemctl restart shadowsocks-libev

![image](https://user-images.githubusercontent.com/17734954/56468125-6375a780-645a-11e9-927f-b28ac014b450.png)



> "server":["[::0]", "0.0.0.0"]
> NOT "server":"127.0.0.1"

**Comment by lucifer0114** [comment]
Then what happened? Still can not connect?

**Comment by ilovuxay** [comment]
Partially resolved the question.
The ss-windows client is now able to work
![image](https://user-images.githubusercontent.com/17734954/56468269-95880900-645c-11e9-9dc2-0853bc2ce731.png)

However 
The ss-android still not work... 
Unable to resolve host : www.google.com 

Now i'm testing with my friend which in one other province.

**Comment by lucifer0114** [comment]
You could choose another version (eg: download shadowsocks app from Google Play) to see if it will work.

**Comment by ilovuxay** [comment]
Thank you. Problem solved.
 Now I make a complete summary that how I do for CentOS 7 x86-64.

### Install those ss related
yum install dnf
yum update
dnf install 'dnf-command(copr)  
dnf copr enable librehat/shadowsocks
yum install shadowsocks-libev

### Install necessary tools
yum install vim
yum install net-tools

### Modify the config json
vim /etc/default/shadowsocks-libev
>Manually press arrow keys to change "server":"127.0.0.1" to "server":["[::0]", "0.0.0.0"]  ,and press Esc key , type ":wq" to save
>Do not modify any options you don't know.

###Shutdown the firewall on CentOS
systemctl stop firewalld.service 
systemctl disable firewalld.service 

### Start the Service
systemctl start shadowsocks-libev
systemctl status shadowsocks-libev

>Now you can leave X-shell and back to your devices.
>Use the newest client release of android or windows in https://github.com/shadowsocks/*.
>Config the server setting with which shows in json above. 
>Do not modify any options you don't know.

### Set the Switchy Omega
>Manually add a scene-mode, http - 127.0.0.1 - 1080,
>Then enjoy !

### Still Not Confirmed 
The SSR service may conflict with this, so carefully discriminate the SS from SSR .
Follow the above steps from a clean operating system.
