### ISSUE TITLE
unable to start ss-libev by using ss-server

### ISSUE THREAD

**Issue by OceanEyeFF** [shadowsocks/shadowsocks-libev#2357]
the server can be launched as a service
but when i tried to start it by ss-server 
it returns eror

### What version of shadowsocks-libev are you using?

ss-libev 3.2.5

### What operating system are you using?

ubuntu 14.04

### What did you do?

trying to start server service in
ss-server -c /path to config -d start -v

### What did you see instead?

 2019-04-21 08:59:15 ERROR: failed to set nameservers

### What is your config in detail (with all sensitive info masked)?

{
    "server":"0.0.0.0",
        "server_port":9921,
        "loacl_addrees":"127.0.0.1",
        "local_port":1080,
        "password":"meizifdc",
        "timeout":10,
        "method":"aes-128-cfb",

    "fast_open":false,
    "nameserver":"8.8.8.8",
    "mode":"tcp_and_udp"
}

**Comment by madeye** [comment]
Remove 'local_address'.

**Comment by OceanEyeFF** [comment]
well, the problem remains after i delete that line

**Comment by madeye** [comment]
Remove -d start from your command line.

**Comment by OceanEyeFF** [comment]
THX. it works

**Comment by thanhtruong1992** [comment]
> Remove -d start from your command line.

Thanks, it works

**Comment by anoduck** [comment]
Worked for me as well... to encourage detachment and logging use nohup and send to background with '&'.  
`nohup ss-server -c /etc/shadowsocks-libev/config.json &'

**Comment by recolic** [comment]
I would like to add a note: 
Some users are using the same command line arguments between `ssserver` and `ss-server`, but they are not the same. `ssserver` supports `-d start` but this option has different meaning in `ss-server`.

**Comment by joshuamwo** [comment]
Thanks guys, removing -d worked for me. @recolic -d allowed run sssever in the background, how do i do the same for ss-server?
