### ISSUE TITLE
Question: Why is server->buf encrypted before prepending server->abuf?

### ISSUE THREAD

**Issue by PantherJohn** [shadowsocks/shadowsocks-libev#2359]
@madeye Sooo I’m working on a fancy feature for TCP connections, and I’m a bit confused about the way shadowsocks handle its buffer. See, normally the address buffer should be prepended before `encrypt()` is called, and I can definitely verify it's true by swapping the sequence of `encrypt()` and `prepend()` being called. Below are the lines excerpted from the original source code. It looks counterintuitive but actually works, while the ones that I reproduced did NOT work as expected.
https://github.com/shadowsocks/shadowsocks-libev/blob/dc2c1e152aaeef48b6ce5b98fbd63b8100d52134/src/local.c#L649-L664

Reproduced version, `server.c` **LINE 1163**
```
    int err = crypto->encrypt(server->buf, server->e_ctx, BUF_SIZE);

    server->abuf->idx = 0;
    server->abuf->len = 0;
    memcpy(server->abuf->data, &remote->cfd, sizeof(uint32_t));
    server->abuf->len += sizeof(uint32_t);
    err = crypto->encrypt(server->abuf, server->e_ctx, BUF_SIZE);
    bprepend(server->buf, server->abuf, BUF_SIZE);
```
Can you please explain why the lines I added did not work and how exactly shadowsocks encrypts its buffer? Thanks in advance.

**Comment by madeye** [comment]
abuf is already encrypted, you should not encrypt it again.

**Comment by PantherJohn** [comment]
@madeye :) Nope `server->abuf` is encrypted only once. It’s not the source of the problem. The problem I’ve been struggling with is the concatenation of encrypted data (`buf` and `abuf`).

**Comment by madeye** [comment]
You cannot do that, Make sure abuf is encrypted before any buffer,

**Comment by PantherJohn** [comment]
@madeye
> Make sure abuf is encrypted before any buffer,
Thank you so much for your information. I’m completely new to cryptography so can you pls explain the reason whyyy 😂

**Comment by madeye** [comment]
You need to encrypt data in their original order.

abuf stores the shadowsocks header, which means you need to encrypt it first.

**Comment by PantherJohn** [comment]
@madeye 🤜 Gotcha, man.
