### ISSUE TITLE
吞吐性能不足

### ISSUE THREAD

**Issue by qiuzi** [shadowsocks/shadowsocks-libev#2360]
1000M网络 x86平台 无法满足95%吞吐速度
感觉是程序限制了只有380M速率，如何解除限制？

**Comment by pexcn** [comment]
会不会是服务端或者客户端加解密的性能跟不上？

**Comment by qiuzi** [comment]
@pexcn 试过用Windows版能跑满 更像是Linux有意限制 找不到原因

**Comment by pexcn** [comment]
Windows 版的是同一个硬件吗？

**Comment by qiuzi** [comment]
@qiuzi 不是libev 使用的是csharp 就算硬件有差异 换成Python版却没问题

**Comment by qiuzi** [comment]
@pexcn 怎么设置不加密算法

**Comment by pexcn** [comment]
不能设置无加密，试试 rc4-md5？

**Comment by qiuzi** [comment]
@pexcn rc4-md5还是不理想 仅提升20%左右

**Comment by madeye** [comment]
Try 38e83d6

**Comment by rampageX** [comment]
@madeye 这个提升有点大~

PHICOMM N1：
前： chacha20-ietf-poly1305 | 300 Mbits/sec；aes-128-gcm | 125Mbits/sec
后： chacha20-ietf-poly1305 | 470 Mbits/sec；aes-128-gcm | 144Mbits/sec

Asus RT-AC68P：
前： chacha20-ietf-poly1305 | 90 Mbits/sec；aes-128-gcm | 52Mbits/sec
后： chacha20-ietf-poly1305 | 140 Mbits/sec；aes-128-gcm | 70Mbits/sec

**Comment by qiuzi** [comment]
感觉还是受cpu性能限制了 @madeye 希望增加none模式做高速网络使用

**Comment by qiuzi** [comment]
@rampageX  chacha20-ietf 能跑满1000m网络 chacha20-ietf-poly1305却不行

**Comment by debiansid** [comment]
@qiuzi xchacha那个呢

**Comment by qiuzi** [comment]
@debiansid xchacha20-ietf-poly1305 比chacha20-ietf更消耗性能
