### ISSUE TITLE
能不能把B站加入白名单http://space.bilibili.com/

### ISSUE THREAD

**Issue by HaimmingYu** [shadowsocks/shadowsocks-libev#2361]
能不能把B站加入白名单http://space.bilibili.com/

**Comment by cupen** [comment]
这不是 proxy 该做的，你应该在上层用 pac 来决定是直连还是 proxy 。

**Comment by HaimmingYu** [comment]
哪里能设置 没找到

**Comment by jimmyhu517** [comment]
> 
> 
> 找到了
> 
> ```
> ! Put user rules line by line in this file.
> ! See https://adblockplus.org/en/filter-cheatsheet
> @@*.bilibili.com/*
> @@*.baidu.com/*
> ```

大兄弟，这是哪个文件呀
