### ISSUE TITLE
About TCP RST packets

### ISSUE THREAD

**Issue by SykieChen** [shadowsocks/shadowsocks-libev#2364]
Sorry for bothering. 
Several days ago I opened an issue at [the python version respority](https://github.com/shadowsocks/shadowsocks/issues/1446). Shadowsocks changes all the RST packages into FIN.
The behavior is exactly the same on libev version, both in ss-local and ss-redir.
Is this 'Yes But' method designed on purpose? If not, is there a workaround? Could you please explain the reason of this behavior?
Thank you and best wishes!

**Comment by madeye** [comment]
Yes, it's just by design.

**Comment by SykieChen** [comment]
Thanks for replying.
Is it for avoiding handshake failure due to high lag?

**Comment by madeye** [comment]
Shadowsocks is designed to avoid any kind of handshake.

Given shadowsocks works as a TCP proxy, RST to close a connection is just okay.

**Comment by SykieChen** [comment]
Got it, thanks a lot.
I tried to use shadowsocks to proxy a net-scanning tool, which depends on the RST packs to recognize if the port is open. I'll try using OpenVPN via shadowsocks instead.
