### ISSUE TITLE
为什么服务器端查看端口占用会发现客户端的连接数这么多，是干什么用的，可以设置为某个固定的端口吗？

### ISSUE THREAD

**Issue by ewgasdf** [shadowsocks/shadowsocks-libev#2370]
shadowsocks-libev 3.1.3
Ubuntu18.04

使用netstat 查看端口占用，发现了十几个来自我的ip的连接，端口号（本地机器）五千多到六千多不等

Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 10.140.0.5:107          <my-ip>:5395    ESTABLISHED 976/ss-server
tcp        0      0 10.140.0.5:107          <my-ip>:6306    ESTABLISHED 976/ss-server
tcp        0      0 10.140.0.5:107          <my-ip>:5380    ESTABLISHED 976/ss-server
tcp        0      0 10.140.0.5:107          <my-ip>:6368    ESTABLISHED 976/ss-server
tcp        0      0 10.140.0.5:107          <my-ip>:5529    ESTABLISHED 976/ss-server
tcp        0      0 10.140.0.5:107          <my-ip>:6376    ESTABLISHED 976/ss-server
tcp        0      0 10.140.0.5:107          <my-ip>:6366    ESTABLISHED 976/ss-server
tcp        0      0 10.140.0.5:107          <my-ip>:6275    ESTABLISHED 976/ss-server
tcp        0      0 10.140.0.5:107          <my-ip>:6313    ESTABLISHED 976/ss-server
tcp        0      0 10.140.0.5:107          <my-ip>:6295    ESTABLISHED 976/ss-server
tcp        0      0 10.140.0.5:107          <my-ip>:5372    ESTABLISHED 976/ss-server
tcp        0      0 10.140.0.5:107          <my-ip>:6203    ESTABLISHED 976/ss-server
tcp        0      0 10.140.0.5:107          <my-ip>:5533    ESTABLISHED 976/ss-server
tcp        0      0 10.140.0.5:107          <my-ip>:6291    ESTABLISHED 976/ss-server
tcp        0      0 10.140.0.5:107          <my-ip>:5376    ESTABLISHED 976/ss-server
tcp        0      0 10.140.0.5:107          <my-ip>:6284    ESTABLISHED 976/ss-server
tcp        0      0 10.140.0.5:107          <my-ip>:5391    ESTABLISHED 976/ss-server
tcp        0      0 10.140.0.5:107          <my-ip>:5433    TIME_WAIT   -

**Comment by madeye** [comment]
It's expected. The number of connections depends on the application you're using through shadowsocks.
