### ISSUE TITLE
Question: Is it okay to use GNU extensions?

### ISSUE THREAD

**Issue by PantherJohn** [shadowsocks/shadowsocks-libev#2371]
@madeye Extensions such as [statement expressions](http://gcc.gnu.org/onlinedocs/gcc/Statement-Exprs.html) are going to make life a lot easier especially when it comes to JSON config parser, and as the project only supports GCC compilers (well correct me if I'm wrong), there doesn't seem to be compatibility issues.

And by the way are there any contributor guide on coding formats and standards for this project?

**Comment by madeye** [comment]
This project follows C99 and can be compiled in any C compiler, including GCC and clang (LLVM).
