### ISSUE TITLE
Cannot start ss-local at startup time on Kubuntu 19.04

### ISSUE THREAD

**Issue by Sraw** [shadowsocks/shadowsocks-libev#2375]
### What version of shadowsocks-libev are you using?
shadowsocks-libev 3.2.5

### What operating system are you using?
Kubuntu 19.04

### What did you do?
Use systemd to start ss-local at startup time.

### What did you expect to see?
It works.

### What did you see instead?
It doesn't work because of temporary failure in name resolution.

### What is your config in detail (with all sensitive info masked)?
Used dns service: systemd-resolved

shadowsocks.service:
```
[Unit]
Description=Shadowsocks-libev Client
After=network.target

[Service]
User=nobody
Group=nogroup
ExecStart=/usr/bin/ss-local -c /etc/shadowsocks-libev/config.json

[Install]
WantedBy=multi-user.target
```
I've tried many other unit like `network-online.target`. But none of them works.

**Comment by QwertyJack** [comment]
Have u tried xenial & bionic ? Both are fine to me so I guess 19.04 should work.

**Comment by Sraw** [comment]
@QwertyJack I've tried 18.04, it works. But it doesn't work that well. There are still some errors such as "Failed to resolve domain, wait 2 seconds", "Failed to resolve domain, wait 4 seconds". And finally, it works.
So I think it looks like the same problem: `After=network.target` won't ensure DNS resolution. But the implementation on 18.04 will wait while the one on 19.04 won't and just crash.

**Comment by QwertyJack** [comment]
Then there must be some issue.
