### ISSUE TITLE
Verbose mode output

### ISSUE THREAD

**Issue by eddycat** [shadowsocks/shadowsocks-libev#2379]
### What version of shadowsocks-libev are you using?

shadowsocks-libev 3.2.5

### What operating system are you using?

Ubuntu 16.04

### What did you do?

Run ss-server in verbose mode

### What did you expect to see?

Verbose mode output content increases user IP. For example

> 2019-05-25 00:50:53 INFO: 111.111.111.111 [8388] connect to clients6.google.com:443

### What did you see instead?

> 2019-05-25 00:50:53 INFO: [8388] connect to clients6.google.com:443

### What is your config in detail (with all sensitive info masked)?

> ss-server -c /etc/shadowsocks-libev/config.json -u -v

/etc/shadowsocks-libev/config.json content
```
{
    "server":"0.0.0.0",
    "server_port":8388,
    "local_port":1080,
    "password":"sijhevso",
    "timeout":60,
    "method":"chacha20-ietf-poly1305"
}
```

**Comment by madeye** [comment]
Pull request is welcome.

**Comment by PantherJohn** [comment]
Doesn't look so good. It's way too verbose I think.

**Comment by madeye** [comment]
Yeah, I agree.

I think you can modify the logger code as you like, if you really need this feature.

**Comment by eddycat** [comment]
I won't modify the C code, I can try it.

When sharing a server, I want to know who accessed what.
