### ISSUE TITLE
I can't open any website when ss is turned off

### ISSUE THREAD

**Issue by betterMax** [shadowsocks/shadowsocks-libev#2382]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
ShadowsocksR-win-4.9.0

### What operating system are you using?
Win 10

### What did you do?
I am in China and use SS to open some website outside. Currently when SS is turned on I can open all kinds of website. However when SS is turned off, I can't even open those website I can open before I use SS. I have tried different wifi and browser. 

### What did you expect to see?
I would like to open the normal website when SS is turned off as usual.

**Comment by madeye** [comment]
I don't think this issue has anything to do with shadowsocks-libev.
