### ISSUE TITLE
06.01.2019.早上十一点,所有SS节点全drop

### ISSUE THREAD

**Issue by sophauer** [shadowsocks/shadowsocks-libev#2385]
如题,
具体表现是可以SSH,但是无法连接,应该不是技术问题,
同一节点,其他协议都正常,只有SS被drop并重置.
看来之前说SS可辨识是真的

**Comment by PantherJohn** [comment]
#2384

**Comment by sophauer** [comment]
什么都没做的情况下又恢复了..
真是神奇

**Comment by hfgj** [comment]
现在还能连吗？

**Comment by lirc572** [comment]
好像ip封了。。。都ping不上了。。。

**Comment by 148i** [comment]
我也是，ip被封了。国内ping不同，国外可以。我想知道以后用什么翻啊？
