### ISSUE TITLE
debian下编译ss-libev，发生redefinition of ***编译错误

### ISSUE THREAD

**Issue by t1935111** [shadowsocks/shadowsocks-libev#2387]
### What version of shadowsocks-libev are you using?
当前最新的master分支

### What operating system are you using?
Linux localhost 4.19.0-5-amd64 #1 SMP Debian 4.19.37-3 (2019-05-15) x86_64 GNU/Linux

### What did you do?

> set -e
export HOST=x86_64-linux-gnu
export CC=$HOST-gcc
export CXX=$HOST-g++
export AR=$HOST-ar
export LD=$HOST-ld
git clone --depth=1 https://github.com/shadowsocks/shadowsocks-libev
pushd shadowsocks-libev
git submodule update --init --recursive
./autogen.sh
./configure LIBS="-lpthread -lm" LDFLAGS="-static -static-libgcc -L$SS_BUILD/lib" CFLAGS="-I$SS_BUILD/include" --host=$HOST --prefix=/root/xiaomi/ss --disable-ssp --disable-documentation --with-mbedtls=$SS_BUILD/mbedtls --with-pcre=$SS_BUILD/pcre --with-sodium=$SS_BUILD/libsodium --with-cares=$SS_BUILD/c-ares --with-ev=$SS_BUILD/libev
make -j$(nproc) install

### What did you expect to see?
成功编译

### What did you see instead?

> make[1]: Leaving directory '/root/xiaomi/shadowsocks-libev/libbloom'
Making install in src
make[1]: Entering directory '/root/xiaomi/shadowsocks-libev/src'
  CC       ss_local-local.o
  CC       ss_local-utils.o
  CC       ss_local-jconf.o
  CC       ss_local-json.o
  CC       ss_local-udprelay.o
  CC       ss_local-cache.o
  CC       ss_local-netutils.o
  CC       ss_local-crypto.o
  CC       ss_local-aead.o
  CC       ss_local-stream.o
  CC       ss_local-ppbloom.o
  CC       ss_local-base64.o
  CC       ss_local-plugin.o
  CC       ss_local-http.o
  CC       ss_local-tls.o
  CC       ss_local-rule.o
  CC       ss_local-acl.o
In file included from /usr/include/netdb.h:27,
                 from netutils.h:39,
                 from acl.c:36:
/usr/include/netinet/in.h:31:8: error: redefinition of ‘struct in_addr’
 struct in_addr
        ^~~~~~~
In file included from /usr/include/linux/tcp.h:24,
                 from netutils.h:33,
                 from acl.c:36:
/usr/include/linux/in.h:85:8: note: originally defined here
 struct in_addr {
        ^~~~~~~
In file included from /usr/include/netinet/in.h:37,
                 from /usr/include/netdb.h:27,
                 from netutils.h:39,
                 from acl.c:36:
/usr/include/x86_64-linux-gnu/bits/in.h:149:8: error: redefinition of ‘struct ip_mreqn’
 struct ip_mreqn
        ^~~~~~~~
In file included from /usr/include/linux/tcp.h:24,
                 from netutils.h:33,
                 from acl.c:36:
/usr/include/linux/in.h:173:8: note: originally defined here
 struct ip_mreqn {
        ^~~~~~~~
In file included from /usr/include/netinet/in.h:37,
                 from /usr/include/netdb.h:27,
                 from netutils.h:39,
                 from acl.c:36:
/usr/include/x86_64-linux-gnu/bits/in.h:157:8: error: redefinition of ‘struct in_pktinfo’
 struct in_pktinfo
        ^~~~~~~~~~
In file included from /usr/include/linux/tcp.h:24,
                 from netutils.h:33,
                 from acl.c:36:
/usr/include/linux/in.h:222:8: note: originally defined here
 struct in_pktinfo {
        ^~~~~~~~~~
/usr/include/netinet/in.h:42:5: error: redeclaration of enumerator ‘IPPROTO_IP’
     IPPROTO_IP = 0,    /* Dummy protocol for TCP.  */
     ^~~~~~~~~~
/usr/include/linux/in.h:29:3: note: previous definition of ‘IPPROTO_IP’ was here
   IPPROTO_IP = 0,  /* Dummy protocol for TCP  */
   ^~~~~~~~~~
/usr/include/netinet/in.h:44:5: error: redeclaration of enumerator ‘IPPROTO_ICMP’
     IPPROTO_ICMP = 1,    /* Internet Control Message Protocol.  */
     ^~~~~~~~~~~~
/usr/include/linux/in.h:31:3: note: previous definition of ‘IPPROTO_ICMP’ was here
   IPPROTO_ICMP = 1,  /* Internet Control Message Protocol */
   ^~~~~~~~~~~~
/usr/include/netinet/in.h:46:5: error: redeclaration of enumerator ‘IPPROTO_IGMP’
     IPPROTO_IGMP = 2,    /* Internet Group Management Protocol. */
     ^~~~~~~~~~~~
/usr/include/linux/in.h:33:3: note: previous definition of ‘IPPROTO_IGMP’ was here
   IPPROTO_IGMP = 2,  /* Internet Group Management Protocol */
   ^~~~~~~~~~~~
/usr/include/netinet/in.h:48:5: error: redeclaration of enumerator ‘IPPROTO_IPIP’
     IPPROTO_IPIP = 4,    /* IPIP tunnels (older KA9Q tunnels use 94).  */
     ^~~~~~~~~~~~
/usr/include/linux/in.h:35:3: note: previous definition of ‘IPPROTO_IPIP’ was here
   IPPROTO_IPIP = 4,  /* IPIP tunnels (older KA9Q tunnels use 94) */
   ^~~~~~~~~~~~
/usr/include/netinet/in.h:50:5: error: redeclaration of enumerator ‘IPPROTO_TCP’
     IPPROTO_TCP = 6,    /* Transmission Control Protocol.  */
     ^~~~~~~~~~~
/usr/include/linux/in.h:37:3: note: previous definition of ‘IPPROTO_TCP’ was here
   IPPROTO_TCP = 6,  /* Transmission Control Protocol */
   ^~~~~~~~~~~
/usr/include/netinet/in.h:52:5: error: redeclaration of enumerator ‘IPPROTO_EGP’
     IPPROTO_EGP = 8,    /* Exterior Gateway Protocol.  */
     ^~~~~~~~~~~
/usr/include/linux/in.h:39:3: note: previous definition of ‘IPPROTO_EGP’ was here
   IPPROTO_EGP = 8,  /* Exterior Gateway Protocol  */
   ^~~~~~~~~~~
/usr/include/netinet/in.h:54:5: error: redeclaration of enumerator ‘IPPROTO_PUP’
     IPPROTO_PUP = 12,    /* PUP protocol.  */
     ^~~~~~~~~~~
/usr/include/linux/in.h:41:3: note: previous definition of ‘IPPROTO_PUP’ was here
   IPPROTO_PUP = 12,  /* PUP protocol    */
   ^~~~~~~~~~~
/usr/include/netinet/in.h:56:5: error: redeclaration of enumerator ‘IPPROTO_UDP’
     IPPROTO_UDP = 17,    /* User Datagram Protocol.  */
     ^~~~~~~~~~~
/usr/include/linux/in.h:43:3: note: previous definition of ‘IPPROTO_UDP’ was here
   IPPROTO_UDP = 17,  /* User Datagram Protocol  */
   ^~~~~~~~~~~
/usr/include/netinet/in.h:58:5: error: redeclaration of enumerator ‘IPPROTO_IDP’
     IPPROTO_IDP = 22,    /* XNS IDP protocol.  */
     ^~~~~~~~~~~
/usr/include/linux/in.h:45:3: note: previous definition of ‘IPPROTO_IDP’ was here
   IPPROTO_IDP = 22,  /* XNS IDP protocol   */
   ^~~~~~~~~~~
/usr/include/netinet/in.h:60:5: error: redeclaration of enumerator ‘IPPROTO_TP’
     IPPROTO_TP = 29,    /* SO Transport Protocol Class 4.  */
     ^~~~~~~~~~
/usr/include/linux/in.h:47:3: note: previous definition of ‘IPPROTO_TP’ was here
   IPPROTO_TP = 29,  /* SO Transport Protocol Class 4 */
   ^~~~~~~~~~
/usr/include/netinet/in.h:62:5: error: redeclaration of enumerator ‘IPPROTO_DCCP’
     IPPROTO_DCCP = 33,    /* Datagram Congestion Control Protocol.  */
     ^~~~~~~~~~~~
/usr/include/linux/in.h:49:3: note: previous definition of ‘IPPROTO_DCCP’ was here
   IPPROTO_DCCP = 33,  /* Datagram Congestion Control Protocol */
   ^~~~~~~~~~~~
/usr/include/netinet/in.h:64:5: error: redeclaration of enumerator ‘IPPROTO_IPV6’
     IPPROTO_IPV6 = 41,     /* IPv6 header.  */
     ^~~~~~~~~~~~
/usr/include/linux/in.h:51:3: note: previous definition of ‘IPPROTO_IPV6’ was here
   IPPROTO_IPV6 = 41,  /* IPv6-in-IPv4 tunnelling  */
   ^~~~~~~~~~~~
/usr/include/netinet/in.h:66:5: error: redeclaration of enumerator ‘IPPROTO_RSVP’
     IPPROTO_RSVP = 46,    /* Reservation Protocol.  */
     ^~~~~~~~~~~~
/usr/include/linux/in.h:53:3: note: previous definition of ‘IPPROTO_RSVP’ was here
   IPPROTO_RSVP = 46,  /* RSVP Protocol   */
   ^~~~~~~~~~~~
/usr/include/netinet/in.h:68:5: error: redeclaration of enumerator ‘IPPROTO_GRE’
     IPPROTO_GRE = 47,    /* General Routing Encapsulation.  */
     ^~~~~~~~~~~
/usr/include/linux/in.h:55:3: note: previous definition of ‘IPPROTO_GRE’ was here
   IPPROTO_GRE = 47,  /* Cisco GRE tunnels (rfc 1701,1702) */
   ^~~~~~~~~~~
/usr/include/netinet/in.h:70:5: error: redeclaration of enumerator ‘IPPROTO_ESP’
     IPPROTO_ESP = 50,      /* encapsulating security payload.  */
     ^~~~~~~~~~~
/usr/include/linux/in.h:57:3: note: previous definition of ‘IPPROTO_ESP’ was here
   IPPROTO_ESP = 50,  /* Encapsulation Security Payload protocol */
   ^~~~~~~~~~~
/usr/include/netinet/in.h:72:5: error: redeclaration of enumerator ‘IPPROTO_AH’
     IPPROTO_AH = 51,       /* authentication header.  */
     ^~~~~~~~~~
/usr/include/linux/in.h:59:3: note: previous definition of ‘IPPROTO_AH’ was here
   IPPROTO_AH = 51,  /* Authentication Header protocol */
   ^~~~~~~~~~
/usr/include/netinet/in.h:74:5: error: redeclaration of enumerator ‘IPPROTO_MTP’
     IPPROTO_MTP = 92,    /* Multicast Transport Protocol.  */
     ^~~~~~~~~~~
/usr/include/linux/in.h:61:3: note: previous definition of ‘IPPROTO_MTP’ was here
   IPPROTO_MTP = 92,  /* Multicast Transport Protocol  */
   ^~~~~~~~~~~
/usr/include/netinet/in.h:76:5: error: redeclaration of enumerator ‘IPPROTO_BEETPH’
     IPPROTO_BEETPH = 94,   /* IP option pseudo header for BEET.  */
     ^~~~~~~~~~~~~~
/usr/include/linux/in.h:63:3: note: previous definition of ‘IPPROTO_BEETPH’ was here
   IPPROTO_BEETPH = 94,  /* IP option pseudo header for BEET */
   ^~~~~~~~~~~~~~
/usr/include/netinet/in.h:78:5: error: redeclaration of enumerator ‘IPPROTO_ENCAP’
     IPPROTO_ENCAP = 98,    /* Encapsulation Header.  */
     ^~~~~~~~~~~~~
/usr/include/linux/in.h:65:3: note: previous definition of ‘IPPROTO_ENCAP’ was here
   IPPROTO_ENCAP = 98,  /* Encapsulation Header   */
   ^~~~~~~~~~~~~
/usr/include/netinet/in.h:80:5: error: redeclaration of enumerator ‘IPPROTO_PIM’
     IPPROTO_PIM = 103,    /* Protocol Independent Multicast.  */
     ^~~~~~~~~~~
/usr/include/linux/in.h:67:3: note: previous definition of ‘IPPROTO_PIM’ was here
   IPPROTO_PIM = 103,  /* Protocol Independent Multicast */
   ^~~~~~~~~~~
/usr/include/netinet/in.h:82:5: error: redeclaration of enumerator ‘IPPROTO_COMP’
     IPPROTO_COMP = 108,    /* Compression Header Protocol.  */
     ^~~~~~~~~~~~
/usr/include/linux/in.h:69:3: note: previous definition of ‘IPPROTO_COMP’ was here
   IPPROTO_COMP = 108,  /* Compression Header Protocol  */
   ^~~~~~~~~~~~
/usr/include/netinet/in.h:84:5: error: redeclaration of enumerator ‘IPPROTO_SCTP’
     IPPROTO_SCTP = 132,    /* Stream Control Transmission Protocol.  */
     ^~~~~~~~~~~~
/usr/include/linux/in.h:71:3: note: previous definition of ‘IPPROTO_SCTP’ was here
   IPPROTO_SCTP = 132,  /* Stream Control Transport Protocol */
   ^~~~~~~~~~~~
/usr/include/netinet/in.h:86:5: error: redeclaration of enumerator ‘IPPROTO_UDPLITE’
     IPPROTO_UDPLITE = 136, /* UDP-Lite protocol.  */
     ^~~~~~~~~~~~~~~
/usr/include/linux/in.h:73:3: note: previous definition of ‘IPPROTO_UDPLITE’ was here
   IPPROTO_UDPLITE = 136, /* UDP-Lite (RFC 3828)   */
   ^~~~~~~~~~~~~~~
/usr/include/netinet/in.h:88:5: error: redeclaration of enumerator ‘IPPROTO_MPLS’
     IPPROTO_MPLS = 137,    /* MPLS in IP.  */
     ^~~~~~~~~~~~
/usr/include/linux/in.h:75:3: note: previous definition of ‘IPPROTO_MPLS’ was here
   IPPROTO_MPLS = 137,  /* MPLS in IP (RFC 4023)  */
   ^~~~~~~~~~~~
/usr/include/netinet/in.h:90:5: error: redeclaration of enumerator ‘IPPROTO_RAW’
     IPPROTO_RAW = 255,    /* Raw IP packets.  */
     ^~~~~~~~~~~
/usr/include/linux/in.h:77:3: note: previous definition of ‘IPPROTO_RAW’ was here
   IPPROTO_RAW = 255,  /* Raw IP packets   */
   ^~~~~~~~~~~
In file included from /usr/include/netdb.h:27,
                 from netutils.h:39,
                 from acl.c:36:
/usr/include/netinet/in.h:92:5: error: redeclaration of enumerator ‘IPPROTO_MAX’
     IPPROTO_MAX
     ^~~~~~~~~~~
In file included from /usr/include/linux/tcp.h:24,
                 from netutils.h:33,
                 from acl.c:36:
/usr/include/linux/in.h:79:3: note: previous definition of ‘IPPROTO_MAX’ was here
   IPPROTO_MAX
   ^~~~~~~~~~~
In file included from /usr/include/netdb.h:27,
                 from netutils.h:39,
                 from acl.c:36:
/usr/include/netinet/in.h:237:8: error: redefinition of ‘struct sockaddr_in’
 struct sockaddr_in
        ^~~~~~~~~~~
In file included from /usr/include/linux/tcp.h:24,
                 from netutils.h:33,
                 from acl.c:36:
/usr/include/linux/in.h:232:8: note: originally defined here
 struct sockaddr_in {
        ^~~~~~~~~~~
In file included from /usr/include/netdb.h:27,
                 from netutils.h:39,
                 from acl.c:36:
/usr/include/netinet/in.h:264:8: error: redefinition of ‘struct ip_mreq’
 struct ip_mreq
        ^~~~~~~
In file included from /usr/include/linux/tcp.h:24,
                 from netutils.h:33,
                 from acl.c:36:
/usr/include/linux/in.h:168:8: note: originally defined here
 struct ip_mreq  {
        ^~~~~~~
In file included from /usr/include/netdb.h:27,
                 from netutils.h:39,
                 from acl.c:36:
/usr/include/netinet/in.h:273:8: error: redefinition of ‘struct ip_mreq_source’
 struct ip_mreq_source
        ^~~~~~~~~~~~~~
In file included from /usr/include/linux/tcp.h:24,
                 from netutils.h:33,
                 from acl.c:36:
/usr/include/linux/in.h:179:8: note: originally defined here
 struct ip_mreq_source {
        ^~~~~~~~~~~~~~
In file included from /usr/include/netdb.h:27,
                 from netutils.h:39,
                 from acl.c:36:
/usr/include/netinet/in.h:300:8: error: redefinition of ‘struct group_req’
 struct group_req
        ^~~~~~~~~
In file included from /usr/include/linux/tcp.h:24,
                 from netutils.h:33,
                 from acl.c:36:
/usr/include/linux/in.h:197:8: note: originally defined here
 struct group_req {
        ^~~~~~~~~
In file included from /usr/include/netdb.h:27,
                 from netutils.h:39,
                 from acl.c:36:
/usr/include/netinet/in.h:309:8: error: redefinition of ‘struct group_source_req’
 struct group_source_req
        ^~~~~~~~~~~~~~~~
In file included from /usr/include/linux/tcp.h:24,
                 from netutils.h:33,
                 from acl.c:36:
/usr/include/linux/in.h:202:8: note: originally defined here
 struct group_source_req {
        ^~~~~~~~~~~~~~~~
In file included from /usr/include/netdb.h:27,
                 from netutils.h:39,
                 from acl.c:36:
/usr/include/netinet/in.h:323:8: error: redefinition of ‘struct ip_msfilter’
 struct ip_msfilter
        ^~~~~~~~~~~
In file included from /usr/include/linux/tcp.h:24,
                 from netutils.h:33,
                 from acl.c:36:
/usr/include/linux/in.h:185:8: note: originally defined here
 struct ip_msfilter {
        ^~~~~~~~~~~
In file included from /usr/include/netdb.h:27,
                 from netutils.h:39,
                 from acl.c:36:
/usr/include/netinet/in.h:344:8: error: redefinition of ‘struct group_filter’
 struct group_filter
        ^~~~~~~~~~~~
In file included from /usr/include/linux/tcp.h:24,
                 from netutils.h:33,
                 from acl.c:36:
/usr/include/linux/in.h:208:8: note: originally defined here
 struct group_filter {
        ^~~~~~~~~~~~
make[1]: *** [Makefile:1293: ss_local-acl.o] Error 1
make[1]: Leaving directory '/root/xiaomi/shadowsocks-libev/src'
make: *** [Makefile:480: install-recursive] Error 1

**Comment by madeye** [comment]
Try 8d8b1cd

**Comment by t1935111** [comment]
it's work. thank you.
