### ISSUE TITLE
Does shadowsocks-libev 3.2.5 not support simple-obfs?

### ISSUE THREAD

**Issue by JACK-THINK** [shadowsocks/shadowsocks-libev#2389]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
3.2.5

### What operating system are you using?
ASUS Merlin, armv7sf-k2.6, Entware
ASUSWRT, aarch64-k3.10, Entware

### What did you do?
`ss-local -c config_local.json`

### What did you expect to see?
![58797342-5d1a4400-8632-11e9-8f2e-a7e756f5b6fc](https://user-images.githubusercontent.com/21015855/58845602-5df0bb80-86ae-11e9-9a98-74bb093e2dc5.png)

### What did you see instead?
![58796321-90a79f00-862f-11e9-9dc6-076e4fbe2a2b](https://user-images.githubusercontent.com/21015855/58845610-63e69c80-86ae-11e9-864b-f276896e18ab.png)

### What is your config in detail (with all sensitive info masked)?
```
{
    "server":"SERVER-DOMAIN",
    "server_port":"1NNNN",
    "local_address":"0.0.0.0",
    "local_port":"1NNNN",
    "password":"CCCCCCCC",
    "method":"aes-256-gcm",
    "timeout":60,
    "mode":"tcp_and_udp",
    "plugin":"obfs-local",
    "plugin_opts":"obfs=http;obfs-host=www.CCCCCCC.com"
}
```
> N represents a number and C represents a character.

### Additional Information
When I turn to shadowsocks-libev 3.2.3, everything works well.

I have already contacted the maintainer of Entware and he tells me that he compiled the ipk package with the source code from here directly and I have to contact the author of shadowsocks-libev on [this bug](https://github.com/Entware/Entware/issues/300).

I also tried to install **shadowsocks-libev_3.2.5-1_x86_64.ipk** from [here](https://github.com/shadowsocks/openwrt-shadowsocks/releases) and **simple-obfs_0.0.5-1_x86_64.ipk** from [here](https://github.com/aa65535/openwrt-simple-obfs/releases) on **OpenWRT-18.06.2-x86-64(with only one LAN and no WAN)** and everything works well.

**Comment by madeye** [comment]
I cannot reproduce your issue with the config you provided. It works well.

**Comment by JACK-THINK** [comment]
@madeye 

Could you tell me what your test platform is? Perhaps I can help you reproduce this issue.

If you have an ASUS router, no matter ASUSWRT or ASUS MERLIN runs on the router, just plug a **blank** USB flash drive in it and install [SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER](https://github.com/JACK-THINK/SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER) by invoking the code below, then you can reproduce this issue 100%. I've confronted this issue on both RT-AC68U and RT-AC86U.

```shell
cd /tmp && wget -O /tmp/install_online --no-check-certificate "https://raw.githubusercontent.com/JACK-THINK/SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER/master/script_bootloader/bin/install_online" && chmod 777 /tmp/install_online && /tmp/install_online
```

**Comment by madeye** [comment]
You can test your configuration on a LInux PC first. It should work.

Any router porting is not maintained by this project. You need to contact with the downstream maintainer instead.

**Comment by JACK-THINK** [comment]
In conclusion, it's a bug in the source code of shadowsocks-libev 3.2.5.

Solution is here. #2314
