### ISSUE TITLE
请问服务端经常出现的这些错误可能是由什么原因导致的？

### ISSUE THREAD

**Issue by azuis** [shadowsocks/shadowsocks-libev#239]
请问服务端经常出现的

invalid header with addr type 71
server recv: Connection reset by peer
remote recv: Connection reset by peer
invalid header with addr type -108

可能是由于什么原因导致的？

shadowsocks-libev 2.0.8

**Comment by madeye** [comment]
1. 密码/加密方式错误。
2. 端口扫描。
