### ISSUE TITLE
Sponsor link

### ISSUE THREAD

**Issue by jellycsc** [shadowsocks/shadowsocks-libev#2391]
When I clicked the `Sponsor` button on GitHub, the following error message poped up:
```
This file does not currently contain valid funding links. 
Add or modify links in order to display the "Sponsor" button.
```
I'm willing to donate some funds to this project, and I hope this feature can be set up properly soon. Thanks for this nice and fantastic project!

**Comment by madeye** [comment]
It's still a beta feature of GitHub. Wait patiently until GitHub enabled it for our project.

**Comment by jellycsc** [comment]
Thanks!
