### ISSUE TITLE
ss-server ERROR: [udp] remote_recv_sendto: Resource temporarily unavailable

### ISSUE THREAD

**Issue by enihcam** [shadowsocks/shadowsocks-libev#2394]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
3.2.5

### What operating system are you using?
Archlinux

### What did you do?
tried to optimize the performance of ss-server by tweaking sysctl.

### What did you expect to see?
No flooding error of `ss-server ERROR: [udp] remote_recv_sendto: Resource temporarily unavailable`
### What did you see instead?
tons of `ss-server ERROR: [udp] remote_recv_sendto: Resource temporarily unavailable`

### What is your config in detail (with all sensitive info masked)?

```
{
    "server":"0.0.0.0",
    "server_port":8388,
    "ipv6_first":false,
    "nameserver":"127.0.0.1",
    "password":"MASKED",
    "timeout":60,
    "method":"aes-256-gcm",
    "plugin":"v2ray-plugin",
    "plugin_opts":"loglevel=none;fast-open;host=MASKED.net;server;tls;cert=fullchain.cer;key=MASKED.net.key",
    "fast_open":true,
    "reuse_port":true,
    "no_delay":true,
    "nofile":65536,
    "mode":"tcp_and_udp"
}

```

```
 ~ $ cat /etc/sysctl.d/net.conf
## User defined
net.core.netdev_max_backlog = 65536
net.core.optmem_max = 1048576
net.core.somaxconn = 4096
net.core.rmem_default = 1048576
net.core.wmem_default = 1048576
net.core.rmem_max = 16777216
net.core.wmem_max = 16777216

net.ipv4.ip_forward = 0
net.ipv4.ip_local_port_range = 19100 65399

net.ipv4.tcp_rmem = 65536 262144 16777216
net.ipv4.tcp_wmem = 65536 262144 16777216

net.ipv4.tcp_ecn = 1
net.ipv4.tcp_fastopen = 3
net.ipv4.tcp_low_latency = 1
net.ipv4.tcp_max_syn_backlog = 4096
net.ipv4.tcp_slow_start_after_idle = 0
net.ipv4.tcp_synack_retries = 3
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_fin_timeout = 15
net.ipv4.tcp_keepalive_time = 60
net.ipv4.tcp_keepalive_intvl = 10
net.ipv4.tcp_keepalive_probes = 6
net.ipv4.tcp_mtu_probing = 1

net.ipv4.udp_rmem_min = 65536
net.ipv4.udp_wmem_min = 65536
```

**Comment by linxiaocong** [comment]
try to reproduce this issue and see what the output of this shell command is: "ss -anu | wc -l"

**Comment by enihcam** [comment]
@linxiaocong The issue occurs occasionally but once per day at least. I tried to repro the issue by stress test but unfortunately, the error did not happen.
So just wondering which sysctl entries are related to UDP remote_recv_sendto resources?

**Comment by linxiaocong** [comment]
there are several cases when you get an EAGAIN error when you call sendto, such as send buffer is full or no port number available for local endpoint. try increase net.ipv4.udp_wmem_min and net.ipv4.ip_local_port_range
