### ISSUE TITLE
我个人感觉chacha20-ietf-poly1305已经被识别。这几天连续换了IDCF，kagoya，阿里云等均在6小时内被封

### ISSUE THREAD

**Issue by cybmp3** [shadowsocks/shadowsocks-libev#2395]
我个人感觉chacha20-ietf-poly1305已经被识别。这几天连续换了IDCF，kagoya，阿里云等均在6小时内被封。
后来换了个AES-256-GCM到现在超过12小时了，还行。

**Comment by sllzwsgdsg** [comment]
How about now?

**Comment by cybmp3** [comment]
AES-256-GCM两台现在都活着，不过这占用CPU是真的高，两台E5 V3 KVM 1C1G 不同的服务商。一个有AES，一个没有AES指令的，一个跑50Mb/s 10%CPU 一个没指令的跑80Mb/s 80%CPU。。。。
我准备拿ALIYUN再开2台测试下

**Comment by jayluxx** [comment]
Xchacha 20 会不会好一些，一直用 没事

**Comment by gzshasha** [comment]
说实话，墙洞你强迫用户用ss并且加密强制定在chacha20-ietf-poly。这次被批量封是你活该。

**Comment by MikeNg2018** [comment]
早就被识别，换v2ray保平安

**Comment by JorinEdu** [comment]
没用，我的两个IP在本月1号和2号被辦。就是AES-256
应该是ss整个项目全都不能用了。
另外建议你不要用v2ray。因为ss排第一，v2可以排第二，下一个被干掉的就是它。
建议你找个没有客户端，只有命令行，且没有一键部署代码的小众代理软件。
