### ISSUE TITLE
version update in the api information

### ISSUE THREAD

**Issue by meliber** [shadowsocks/shadowsocks-libev#2396]
### What version of shadowsocks-libev are you using?
3.2.5

### What operating system are you using?
ubuntu 16.04

### What did you do?
get lastest release version via github api

### What did you expect to see?
as ver3.3.0 is released, "tag_name": "v3.2.5" should be "tag_name": "v3.3.0",

### What did you see instead?
"url": "https://api.github.com/repos/shadowsocks/shadowsocks-libev/releases/16011037",
  "assets_url": "https://api.github.com/repos/shadowsocks/shadowsocks-libev/releases/16011037/assets",
  "upload_url": "https://uploads.github.com/repos/shadowsocks/shadowsocks-libev/releases/16011037/assets{?name,label}",
  "html_url": "https://github.com/shadowsocks/shadowsocks-libev/releases/tag/v3.2.5",
  "id": 16011037,
  "node_id": "MDc6UmVsZWFzZTE2MDExMDM3",
  "tag_name": "v3.2.5",
  "target_commitish": "master",
  "name": "v3.2.5",
  "draft": false,
... ...

**Comment by madeye** [comment]
It's expected as v3.3.0 is a pre-release version.

The latest version is v3.2.5.

**Comment by meliber** [comment]
Thank you.
