### ISSUE TITLE
Can shadowsocks client on Windows machine help with `git` commands?

### ISSUE THREAD

**Issue by llinfeng** [shadowsocks/shadowsocks-libev#2399]
#### Server and Client
I used the following one-liner to setup the shadowsocks server on June 9 and have been using Windows client (4.1.6).
```
wget --no-check-certificate -O shadowsocks-libev.sh https://raw.githubusercontent.com/uxh/shadowsocks_bash/master/shadowsocks-libev.sh && bash shadowsocks-libev.sh
```

#### What I want to achieve
I would like to use Overleaf when I am in China, for work purpose. Yet, I have only managed to access the web-interface of Overleaf so far. I use WSL on Windows machine, and it can take forever to simply fetch the latest changes on a Git-repo. Here goes what I added to the `rules` variable:
```
  "||overleaf.com",
  "||git.overleaf.com",
```
Apparently, the second line did not help WSL to fecth the Git-repo.

#### Error message for now
One typical error I get from a simple `git push` command is:
```
fatal: unable to access 'https://git.overleaf.com/ID_of_the_Project/': Operation timed out after 300036 milliseconds with 0 out of 0 bytes received
```

#### Question:
Please advise if it is possible to set up something with the Shadowsocks client, or change something in my `~/.netrc` or `~/.gitconfig`, so that I can access the Git-repos on `git.overleaf.com` without VPN.

**Comment by madeye** [comment]
https://stackoverflow.com/questions/15227130/using-a-socks-proxy-with-git-for-the-http-transport

**Comment by llinfeng** [comment]
**Follow up question**: please advise extra settings that need to go into my VPS?

[The link](https://stackoverflow.com/questions/15227130/using-a-socks-proxy-with-git-for-the-http-transport) is relevant but incomplete. I tried to set up the local Shadowsocks client on my Windows 10 machine with the following setting.
![SOcks_Setting](https://user-images.githubusercontent.com/5890407/59729738-62060700-9272-11e9-9019-0a62e886f357.png)
However, with the checkbox active, no PAC traffic went through and here goes the logs:
```
[2019-06-19 09:11:37] System.Net.Sockets.SocketException (0x80004005): No connection could be made because the target machine actively refused it
   at Shadowsocks.Proxy.Socks5Proxy.EndConnectProxy(IAsyncResult asyncResult)
   at Shadowsocks.Controller.TCPHandler.ProxyConnectCallback(IAsyncResult ar)
```

After issuing the following command for Git, again, things did not go through.

* Git set up: `git config --global http.proxy 'socks5://127.0.0.1:7070'`.
* Git error when issuing a `git clone` command:
```
Cloning into 'Gig_Audit'...
fatal: unable to access 'https://git.overleaf.com/xxxxxxxx/': Failed to connect to 127.0.0.1 port 7070: Connection refused
```

**Comment by llinfeng** [comment]
I see that I was tuning the wrong settings for the Client. As it turns out, there does not require any additional settings on the Server side.

To begin with, one needs to change the Proxy Port in the **Edit Servers** window. This is where all other configurations of the clients were set. In my case, I changed my proxy port to be 7070. My settings for the client goes below:
![image](https://user-images.githubusercontent.com/5890407/59731186-b9f33c80-9277-11e9-9b00-1435df5fb1ec.png)

Lastly, on the `git` side, the following pair of commands will help. (Source: [Using a socks proxy with git
](https://stackoverflow.com/questions/15227130/using-a-socks-proxy-with-git-for-the-http-transport))

* To setup the proxy for git: `git config --global http.proxy 'socks5://127.0.0.1:7070'`
* To offset the proxy setting: `git config --global --unset http.proxy`
