### ISSUE TITLE
Error building  on Windows

### ISSUE THREAD

**Issue by Springchendg** [shadowsocks/shadowsocks-libev#240]
MinGW, PolarSSL, v2.1.1 

Making all in src
make[2]: Entering directory `/home/user/shadowsocks-libev-2.1.1-3/src'
  CC     libshadowsocks_la-utils.lo
  CC     libshadowsocks_la-jconf.lo
  CC     libshadowsocks_la-json.lo
  CC     libshadowsocks_la-encrypt.lo
  CC     libshadowsocks_la-udprelay.lo
udprelay.c: In function 'create_server_socket':
udprelay.c:322:22: error: 'AI_ALL' undeclared (first use in this function)
     hints.ai_flags = AI_ALL | AI_V4MAPPED | AI_PASSIVE | AI_ADDRCONFIG; /* For
wildcard IP address */
                      ^
udprelay.c:322:22: note: each undeclared identifier is reported only once for ea
ch function it appears in
udprelay.c:322:31: error: 'AI_V4MAPPED' undeclared (first use in this function)
     hints.ai_flags = AI_ALL | AI_V4MAPPED | AI_PASSIVE | AI_ADDRCONFIG; /* For
wildcard IP address */
                               ^
udprelay.c:322:58: error: 'AI_ADDRCONFIG' undeclared (first use in this function
)
     hints.ai_flags = AI_ALL | AI_V4MAPPED | AI_PASSIVE | AI_ADDRCONFIG; /* For
wildcard IP address */
                                                          ^
make[2]: *** [libshadowsocks_la-udprelay.lo] Error 1
make[2]: Leaving directory `/home/user/shadowsocks-libev-2.1.1-3/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/user/shadowsocks-libev-2.1.1-3'
make: *** [all] Error 2

**Comment by clowwindy** [comment]
@madeye 
I have created a build matrix for shadowsocks-libev. Now we can see if there's something wrong with any combination of (gcc, clang), (linux, freebsd, mingw).

https://jenkins.shadowvpn.org/job/Shadowsocks-libev/

**Comment by madeye** [comment]
Great!
