### ISSUE TITLE
ss-manager api bug?

### ISSUE THREAD

**Issue by perfect-network** [shadowsocks/shadowsocks-libev#2401]
### What version of shadowsocks-libev are you using?
V3.30 (install today by ```sudo apt install shadowsocks-libev```)

### What operating system are you using?
Ubuntu 19.04

### What did you do?
I want to receive data is transferred on Shadowsocks.

### What did you expect to see?
```
import socket

cli = socket.socket(socket.AF_UNIX, socket.SOCK_DGRAM)
cli.bind('/tmp/client.sock')  # address of the client
cli.connect('/var/run/shadowsocks-manager.sock')  # address of Shadowsocks manager

cli.send(b'ping')
print(cli.recv(1506))  # You'll receive 'pong'
while True:
    print(cli.recv(1506))  # when data is transferred on Shadowsocks, you'll receive stat info every 10 seconds
```
get the transferred traffic info every 10 seconds.
### What did you see instead?
I use the code .but can't get the transferred traffic info every 10 seconds.
the only output ``` 
b'stat: {"443":11383269}'
 ```
I write the code to ```
while True:
    cli.send(b'ping')
    print(cli.recv(1506))
    time.sleep(10)
```
then i get the transferred traffic info every 10 seconds.

**Comment by madeye** [comment]
It's expected. Shadowsocks-libev has a different behavior of updating the status info.

Please refer to the doc for more details: https://github.com/shadowsocks/shadowsocks-libev/blob/master/doc/ss-manager.asciidoc
