### ISSUE TITLE
Don't kill plugin process with signal SIGKILL

### ISSUE THREAD

**Issue by zhanhb** [shadowsocks/shadowsocks-libev#2402]
### What version of shadowsocks-libev are you using?
shadowsocks-libev 3.2.0(installed through dnf)

### What operating system are you using?
Linux 2.6.32-042stab127.2 # 1 SMP Thu Jan 4 16:41:44 MSK 2018 x86_64 x86_64 x86_64 GNU/Linux
NAME="CentOS Linux"
VERSION="7 (Core)"
### What did you do?
I wrote a plugin wrapper to support SIP003 protocol with a plugin [kcptun-sip003-wrapper](https://github.com/zhanhb/kcptun-sip003-wrapper). So ss-server will start my shell and the shell will start the plugin binary. Then I execute the command `killall ss-server`

### What did you expect to see?
ss-server can kill all the child process or ss-server not to kill my wrpper process with signal SIGKILL.

### What did you see instead?
Process `ss-server` got killed and leave the `kcptun` process still alive.

### What is your config in detail (with all sensitive info masked)?
```sh
ss-server --plugin kcptun --plugin-opts 'key=some_key_here'
```
Here is the command I executed. kcptun is a shell script in the repository mentioned  above. And binary file `server_linux_amd64` in the same directory.

I searched the source of this repository, and found this line
https://github.com/shadowsocks/shadowsocks-libev/blob/5e65dc0fb16a04024838f37663e58b55fe679a4b/src/plugin.c#L334
IMO, maybe something should changed here.

I have the control of signal, but When my wrapper process got signal SIGKILL, it has no chance to clean child process.

https://libcork.readthedocs.io/en/0.14.0/subprocess/#c.cork_subprocess_wait

**Comment by madeye** [comment]
I cannot reproduce your issue locally with any official SIP003 plugin, but it's better to wait for subprocess here.

Please check if your wrapper can handle `SIGTERM` well, as we didn't `SIGKILL` the subprocess.

**Comment by zhanhb** [comment]
I'm sure my script can handle signal SIGTERM, here is the log I execute my script directly.
```sh
[zhanhb@local ~]$ kcptun &
[1] 8478
[zhanhb@local ~]$ 2019/06/19 09:44:36 version: 20190611
2019/06/19 09:44:36 initiating key derivation
2019/06/19 09:44:36 listening on: [::]:29900
2019/06/19 09:44:36 target: 127.0.0.1:12948
2019/06/19 09:44:36 encryption: aes
... log of kcptun

[zhanhb@local ~]$ ps -ef | grep kcptun
zhanhb    8478  8388  0 09:44 pts/1    00:00:00 /bin/sh /usr/local/bin/kcptun
zhanhb    8494  8478  0 09:44 pts/1    00:00:00 /usr/local/bin/kcptun-server --listen :29900 --target 127.0.0.1:12948
zhanhb    8501  8388  0 09:44 pts/1    00:00:00 grep --color=auto kcptun
[zhanhb@local ~]$ kill -TERM 8478
[zhanhb@local ~]$ 
[1]+  Exit 143                kcptun
[zhanhb@local ~]$ ps -ef | grep kcptun
zhanhb    8503  8388  0 09:45 pts/1    00:00:00 grep --color=auto kcptun
[zhanhb@local ~]$ 
```

**Comment by zhanhb** [comment]
Here's the log I executed with `ss-server`
```sh
[zhanhb@local ~]$ ss-server -s 0.0.0.0 -p 1234 -m aes-256-cfb -k 1234 --plugin kcptun --plugin-opts 'key=123' &
[1] 8610
[zhanhb@local ~]$  2019-06-19 09:55:09 INFO: plugin "kcptun" enabled
 2019-06-19 09:55:09 INFO: initializing ciphers... aes-256-cfb
 2019-06-19 09:55:09 INFO: tcp server listening at 127.0.0.1:39973
2019/06/19 09:55:09 version: 20190611
2019/06/19 09:55:09 initiating key derivation
2019/06/19 09:55:09 listening on: [::]:1234
2019/06/19 09:55:09 target: 127.0.0.1:39973
2019/06/19 09:55:09 encryption: aes
...

[zhanhb@local ~]$ killall ss-server
[1]+  Done                    ss-server -s 0.0.0.0 -p 1234 -m aes-256-cfb -k 1234 --plugin kcptun --plugin-opts 'key=123'
[zhanhb@local ~]$ ps -ef|grep kcptun
zhanhb    8627     1  0 09:55 pts/1    00:00:00 /usr/local/bin/kcptun-server --listen 0.0.0.0:1234 --target 127.0.0.1:39973 --key 123
zhanhb    8637  8388  0 09:55 pts/1    00:00:00 grep --color=auto kcptun
```

**Comment by madeye** [comment]
To verify if it's an issue of shadowsocks-libev, please try any other plugin first.

For example, https://github.com/shadowsocks/kcptun

**Comment by madeye** [comment]
Also, please try the latest version of shadowsocks-libev.

**Comment by zhanhb** [comment]
This wont happen with other plugins, for each of them has only one child plugin process. But with my wrapper, there are two child plugin process. I don't think it will solve my problem to do with latest version shadowsocks-libev.

**Comment by madeye** [comment]
If so, you need to handle your child processes correctly.

It means handle the SIGTERM signal and kill the child processes 

Subprocess waiting is also added in the latest commit, you can compile the latest code and try again.

**Comment by zhanhb** [comment]
Unfortunately, the problem is still there when I execute the binary compiled with the source code of the master branch, latest commit id: 37ca6830adc6424584c9280c49a081d1a6c8b2f3.
```sh
[zhanhb@local shadowsocks-libev]$ ss-server --version
 2019-06-19 10:43:43 ERROR: Unrecognized option: (null)

shadowsocks-libev 3.3.0
...
```

**Comment by madeye** [comment]
Unfortunately, I think you have to figure out this by yourself.

Any child process of the plugin is not controlled by shadowsocks-libev.

BTW, why would you write a wrapper of kcptun, given we already have official plugin there.

**Comment by zhanhb** [comment]
I just want to upgrade to the latest version of kcptun, and make it easy to manager start scripts.

**Comment by lcdtyph** [comment]
@madeye 

I've noticed that libcork waits for child with NOHANG flag immediately after signal the child [here](https://github.com/shadowsocks/libcork/blob/8e37949dccae43bc9045bffea97fa6ac4e0305ce/src/libcork/posix/subprocess.c#L483).

This will cause `waitpid` returns zero and thus send a SIGKILL to child in most cases, because the child may have no time to handle the SIGTERM yet.

For a single process sip003 plugin, everything behaves ok but the plugin always has no time to do its own cleanup stuff. Is this behavior by design? Maybe we can add a timeout and then wait with NOHANG flag to see if the plugin hangs.

**Comment by madeye** [comment]
@lcdtyph LGTM, what about a pull request?

**Comment by lcdtyph** [comment]
@madeye 
Glade to open a PR but I'm very busy in the rest of this month... Since it's not simple to implement waitpid with timeout gracefully, I have to take time to think of good solution.
I'll keep working on this when available.

**Comment by madeye** [comment]
@zhanhb Try 05f4fe7

**Comment by zhanhb** [comment]
`ss-server` tested, work as expected. Thanks very much for your working!!!

**Comment by zhanhb** [comment]
There is another issue. I'm not sure if this is due this change.
`killall ss-server` will kill only the parent process, but not any plugin processes. @madeye

**Comment by madeye** [comment]
@zhanhb Your two comments look contradictory.

I just tested locally, `killall` also works correctly.

Add `-v` option your command line, and make sure you can see `closed gracefully` in the log, after `killall` the process.

**Comment by zhanhb** [comment]
I re-clone the repository and it worked fine with clean build.
