### ISSUE TITLE
Package in Ubuntu 18.04 Repo Is Outdated...

### ISSUE THREAD

**Issue by Aster-the-Med-Stu** [shadowsocks/shadowsocks-libev#2403]
### What version of shadowsocks-libev are you using?
3.1.3

### What operating system are you using?
Ubuntu 18.04 LTS Bionic Beaver

### What did you do?
```apt search shadowsocks-libev```

### What did you expect to see?
See the latest shadowsocks in the result.

### What did you see instead?
```
root@comic:~# apt search shadowsocks-libev
正在排序... 完成
全文搜索... 完成

shadowsocks-libev/bionic 3.1.3+ds-1ubuntu2 amd64
  lightweight and secure socks5 proxy
```

**Comment by madeye** [comment]
`sudo snap install shadowsocks-libev --edge`

**Comment by Aster-the-Med-Stu** [comment]
Oh thanks🤣
