### ISSUE TITLE
ss-manager restarting ss-server

### ISSUE THREAD

**Issue by yagigain** [shadowsocks/shadowsocks-libev#2407]
### What version of shadowsocks-libev are you using?
3.2.5

### What operating system are you using?
Debian 9 and Ubuntu 19 - Same Issue with Both

### What did you do?
ss-manager -u --manager-address /tmp/shadowsocks-manager.sock --fast-open -v

It runs ss-server ok, but only for a few minutes and then ss-server restarts with a graceful exit.   This interrupts the Shadowsocks client for several second each time and data usage accounting is reset.      I see the same issue with a current Debian and Ubuntu build.     ss-server can run on its ok without the issue.

Verbose output,
 2019-06-20 12:49:06 INFO: update traffic 61966 for port 8061
 2019-06-20 12:49:11 INFO: update traffic 0 for port 8106
 2019-06-20 12:49:11 INFO: try to bind interface: 0.0.0.0, port: 8061
 2019-06-20 12:49:11 INFO: cmd: ss-server --manager-address /tmp/shadowsocks-manager.sock -f /root/.shadowsocks/.shadowsocks_8061.pid -c /root/.shadowsocks/.shadowsocks_8061.conf -t 60 -v -u --fast-open -s 0.0.0.0

syslog
un 20 12:49:05 1net ss-server[3872]: successfully resolved r4---sn-5uaezn6d.gvt1.com
Jun 20 12:49:05 1net ss-server[3872]: remote connected
Jun 20 12:49:05 1net ss-server[3872]: remote_recv close the connection
Jun 20 12:49:05 1net ss-server[3872]: current remote connection: 3
Jun 20 12:49:05 1net ss-server[3872]: current server connection: 3
Jun 20 12:49:06 1net ss-server[3869]: update traffic stat: tx: 0 rx: 0
Jun 20 12:49:06 1net ss-server[3872]: update traffic stat: tx: 19109 rx: 42857
Jun 20 12:49:07 1net ss-server[3872]: server_recv close the connection
Jun 20 12:49:07 1net ss-server[3872]: current remote connection: 2
Jun 20 12:49:07 1net ss-server[3872]: current server connection: 2
Jun 20 12:49:07 1net ss-server[3872]: server_recv close the connection
Jun 20 12:49:07 1net ss-server[3872]: current remote connection: 1
Jun 20 12:49:07 1net ss-server[3872]: current server connection: 1
Jun 20 12:49:07 1net ss-server[3872]: server_recv close the connection
Jun 20 12:49:07 1net ss-server[3872]: current remote connection: 0
Jun 20 12:49:07 1net ss-server[3872]: current server connection: 0
Jun 20 12:49:10 1net ss-server[3872]: closed gracefully
Jun 20 12:49:11 1net ss-server[3869]: update traffic stat: tx: 0 rx: 0
Jun 20 12:49:11 1net ss-server[3876]: using tcp fast open
Jun 20 12:49:11 1net ss-server[3876]: UDP relay enabled
Jun 20 12:49:11 1net ss-server[3876]: initializing ciphers... chacha20
Jun 20 12:49:11 1net ss-server[3876]: tcp server listening at 0.0.0.0:8061
Jun 20 12:49:11 1net ss-server[3876]: udp server listening at 0.0.0.0:8061
Jun 20 12:49:11 1net ss-server[3876]: running from root user
Jun 20 12:49:15 1net ss-server[3876]: accept a connection
Jun 20 12:49:15 1net ss-server[3876]: [8061] connect to redirector.gvt1.com:80

**Comment by madeye** [comment]
Actually, `ss-manager` would not restart any child process, as it cannot do that.

Also from you log, everything works well.
