### ISSUE TITLE
after commit 37ca6830adc6424584c9280c49a081d1a6c8b2f3 error on terminating the plugin

### ISSUE THREAD

**Issue by manjuprajna** [shadowsocks/shadowsocks-libev#2408]
### What version of shadowsocks-libev are you using?
v3.3.0 commit after 37ca6830adc6424584c9280c49a081d1a6c8b2f3 

### What operating system are you using?
Centos 7.6 x86_64

### What did you do?
systemctl stop ss-libev

### What did you expect to see?
normally stop service

### What did you see instead?
error on terminating the plugin

### What is your config in detail (with all sensitive info masked)?

before no problem, after commit 37ca6830adc6424584c9280c49a081d1a6c8b2f3 see such error message

**Comment by madeye** [comment]
Just ignore that error message.

**Comment by manjuprajna** [comment]
okay,thank you!
