### ISSUE TITLE
Latest commit f0205e7f133051bf1cb0e2f7ca7764e71cd173d5  fails to compile on RPi Rasbian buster

### ISSUE THREAD

**Issue by kapitainsky** [shadowsocks/shadowsocks-libev#2417]
### What version of shadowsocks-libev are you using?

the latest commit f0205e7f133051bf1cb0e2f7ca7764e71cd173d5

### What operating system are you using?

# uname -a
Linux dbrpi01 4.19.56-v7+ #1242 SMP Wed Jun 26 17:31:47 BST 2019 armv7l GNU/Linux

#  lsb_release -a
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

### What did you do?

trying to build the latest version commit f0205e7f133051bf1cb0e2f7ca7764e71cd173d5

### What did you expect to see?

successful build

### What did you see instead?

local.c: In function ‘remote_recv_cb’:
local.c:1007:37: error: cast increases required alignment of target type [-Werror=cast-align]
 1007 |     remote_ctx_t *remote_recv_ctx = (remote_ctx_t *)w;
      |                                     ^
local.c: In function ‘remote_send_cb’:
local.c:1082:37: error: cast increases required alignment of target type [-Werror=cast-align]
 1082 |     remote_ctx_t *remote_send_ctx = (remote_ctx_t *)w;
      |                                     ^
  CC       ss_local-udprelay.o
  CC       ss_local-cache.o
udprelay.c: In function ‘remote_recv_cb’:
udprelay.c:711:32: error: cast increases required alignment of target type [-Werror=cast-align]
  711 |     remote_ctx_t *remote_ctx = (remote_ctx_t *)w;

### What is your config in detail (with all sensitive info masked)?
N/A

Reverting to commit ffad914dddb671c378e3060954d6d9fd6d492755 (last version bump) solves the issue

**Comment by madeye** [comment]
What's your compiler version?

**Comment by kapitainsky** [comment]
gcc version 9.1.0 (GCC)

**Comment by madeye** [comment]
Cannot reproduce with GCC 9.1.0 on Ubuntu 18.04.

Since there's not alignment requirement for `struct remote_ctx`, it looks a compiler issue instead.

**Comment by kapitainsky** [comment]
it is most likely due to Raspbian toolchain being 32bits - but I can't pinpoint what is causing it yet. All works fine with commit ffad914dddb671c378e3060954d6d9fd6d492755. So something changed later

**Comment by madeye** [comment]
`-Wcast-align` is introduced in recent commits to ensure no alignment issues on old ARM CPUs.

But I didn't see any alignment increasing in the reported lines. Both `ev_io *` and `remote_ctx_t *` should be 4 byte aligned.

**Comment by madeye** [comment]
Try d0285d6

**Comment by kapitainsky** [comment]
I have tried now with GCC 9.1 and default Raspbian buster compiler gcc version 8.3.0 (Raspbian 8.3.0-6+rpi1) - the latter is default compiler from latest stable release of Raspbian 

in both cases error remains:

 local.c: In function ‘remote_recv_cb’:
local.c:1007:37: error: cast increases required alignment of target type [-Werror=cast-align]
     remote_ctx_t *remote_recv_ctx = (remote_ctx_t *)w;
                                     ^
local.c: In function ‘remote_send_cb’:
local.c:1082:37: error: cast increases required alignment of target type [-Werror=cast-align]
     remote_ctx_t *remote_send_ctx = (remote_ctx_t *)w;
                                     ^
  CC       ss_local-udprelay.o
  CC       ss_local-cache.o
udprelay.c: In function ‘remote_recv_cb’:
udprelay.c:711:32: error: cast increases required alignment of target type [-Werror=cast-align]
     remote_ctx_t *remote_ctx = (remote_ctx_t *)w;
                                ^

**Comment by madeye** [comment]
Try 9aa46cb

**Comment by kapitainsky** [comment]
the commit 6c28add775ad4144412d936b4f53dce10f01ab93 introduced issues on latest Raspbian. I am testing now using Raspbian default gcc (to rule out issues with gcc 9.1)

6c28add775ad4144412d936b4f53dce10f01ab93 make:

`In file included from jconf.c:29:
utils.h:252:8: error: unknown type name ‘uint16_t’
 inline uint16_t load16_be(const void *s)
        ^~~~~~~~
utils.h: In function ‘load16_be’:
utils.h:254:11: error: unknown type name ‘uint8_t’
     const uint8_t *in = (const uint8_t *)s;
           ^~~~~~~
utils.h:254:32: error: unknown type name ‘uint8_t’
     const uint8_t *in = (const uint8_t *)s;
                                ^~~~~~~
utils.h:255:14: error: ‘uint16_t’ undeclared (first use in this function); did you mean ‘u_int16_t’?
     return ((uint16_t)in[0] << 8)
              ^~~~~~~~
              u_int16_t
utils.h:255:14: note: each undeclared identifier is reported only once for each function it appears in
utils.h:255:23: error: expected ‘)’ before ‘in’
     return ((uint16_t)in[0] << 8)
            ~          ^~
                       )
utils.h:256:22: error: expected ‘)’ before ‘in’
         | ((uint16_t)in[1]);
           ~          ^~
                      )
utils.h:254:20: error: unused variable ‘in’ [-Werror=unused-variable]
     const uint8_t *in = (const uint8_t *)s;
                    ^~
json.c: In function ‘new_value’:
json.c:152:45: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
             value->_reserved.object_mem = (*(char **) &value->u.object.values) + values_size;
                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
json.c: In function ‘json_parse_ex’:
make[2]: *** [Makefile:1083: ss_local-jconf.o] Error 1
make[2]: *** Waiting for unfinished jobs....
json.c:414:27: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
                         (*(json_char **) &top->u.object.values) += string_length + 1;
                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
local.c: In function ‘remote_recv_cb’:
local.c:1007:37: error: cast increases required alignment of target type [-Werror=cast-align]
     remote_ctx_t *remote_recv_ctx = (remote_ctx_t *)w;
                                     ^
local.c: In function ‘remote_send_cb’:
local.c:1082:37: error: cast increases required alignment of target type [-Werror=cast-align]
     remote_ctx_t *remote_send_ctx = (remote_ctx_t *)w;
                                     ^
cc1: all warnings being treated as errors
make[2]: *** [Makefile:1097: ss_local-json.o] Error 1
cc1: all warnings being treated as errors
make[2]: *** [Makefile:1055: ss_local-local.o] Error 1
`

In subsequent commits all error but " cast increases required alignment of target type" were fixed. Before this commit all compiles without any issues

**Comment by kapitainsky** [comment]
> Try [9aa46cb](https://github.com/shadowsocks/shadowsocks-libev/commit/9aa46cbc3f3110e812237008df13fdc103e9d0b4)

this one compiles without any issues either with gcc 9.1 or default gcc 8.3

**Comment by manjuprajna** [comment]
@madeye same issue here. I am compiling on openwrt1806 with commit f0205e7, mips no problem(ar71xx), but on mvebu target (cortex-a9 vfpv3) got such error message:

make[6]: Entering directory '/home/openwrt1806/build_dir/target-arm_cortex-a9+vfpv3_musl_eabi/shadowsocks-libev/shadowsocks-libev-3.3.0-f0205e7f133051bf1cb0e2f7ca7764e71cd173d5/src'
  CC       libshadowsocks_libev_la-local.lo
local.c: In function 'remote_recv_cb':
local.c:1007:37: error: cast increases required alignment of target type [-Werror=cast-align]
     remote_ctx_t *remote_recv_ctx = (remote_ctx_t *)w;
                                     ^
local.c: In function 'remote_send_cb':
local.c:1082:37: error: cast increases required alignment of target type [-Werror=cast-align]
     remote_ctx_t *remote_send_ctx = (remote_ctx_t *)w;
                                     ^
cc1: all warnings being treated as errors
make[6]: *** [Makefile:860: libshadowsocks_libev_la-local.lo] Error 1

now you've reverted by remove wcast align, but I think #2412 is still a problem. I also got such weird problem, some times it looks like it was stuck, or traffice jam.
a typical scenario is when I connect my iphone to a linksys mvebu(arm based) router wifi, and open Facebook APP,  some times willl open, but some times long time and got stuck, have to re-launch FB app, while at the same time use 4G with shadowrocket no problem at all. looks like merely a "fortune" problem. but after I read #2412 looks like same issue.

thank you!

**Comment by madeye** [comment]
Reverting `-Wcast-align` won't cause any regression for #2412, which is just a compiler warning option to avoid introducing similar issue for old ARM CPU in the future.

The most clean solution here is upgrading your old routers, `armeabi` (ARMv5) is a really old CPU arch.

**Comment by manjuprajna** [comment]
@madeye you mean this is kind of hardware issue that will never be fixed? they are still selling linksys wrt3200acm and wrt32x on the market.

**Comment by madeye** [comment]
#2412 should be already fixed. Also #2412 is only related to ss-server.
