### ISSUE TITLE
[Question] Do those variables have to be free()'d to prevent memory leaks?

### ISSUE THREAD

**Issue by PantherJohn** [shadowsocks/shadowsocks-libev#2420]
In fact I've already discovered issues in not just the source code of `server.c` but also other three or four modules. If it's not the [sanitizer](https://github.com/google/sanitizers) that reminded me of those bugs that [have been around](https://github.com/google/sanitizers/wiki/AddressSanitizer) since the initial release of the project I would probably be more than happy to live with them.
https://github.com/shadowsocks/shadowsocks-libev/blob/9aa46cbc3f3110e812237008df13fdc103e9d0b4/src/server.c#L116-L133

`crypto_t *crypto`, for instance, was never released for whatever reason, and other three folky wiggy string variables/char pointers just dangled there, never `free()`d.

@madeye Can you please come up with a specific function to `free` those naughty `crypto_t` structs once and for all? Thank you so much. :)

**Comment by madeye** [comment]
Nope, you cannot do that.

`crypto` is the global data structure used by current process, which has the same life cycle as its own process. In other words, you should not free it.

**Comment by PantherJohn** [comment]
@madeye I mean freeing it before the program exits. Well it does look pointless, as the OS will reclaim the memory anyway. I heard that some old OSes won't, but there's no harm not to `free()`. Nailed it! n Thanks for explaining. I'm gonna close the issue.
