### ISSUE TITLE
Could you please provide binary for Windows?

### ISSUE THREAD

**Issue by linsui** [shadowsocks/shadowsocks-libev#2423]
There has been some issues about this. Until now it's still difficult to bulid a binary on Windows. It won't take much time to provide a binary for Windows user, just like https://github.com/DDoSolitary/shadowsocks-libev-win/ , but it helps a lot. Could you please reconsider it? Thanks any way!

**Comment by madeye** [comment]
Nope, we only release source code for this project.

You need to build it by yourself or get the binaries from third-party.

**Comment by linsui** [comment]
Thanks.
