### ISSUE TITLE
shadowsocks-libev 3.2.5 使用经常无网络，不知道怎么改配置

### ISSUE THREAD

**Issue by CatSamaaa** [shadowsocks/shadowsocks-libev#2425]
### What version of shadowsocks-libev are you using?
3.2.5 

### What operating system are you using?
debian 9

按说明从stretch-backports安装了shadowsocks-libev服务端 ，版本是3.2.5的。
但是安卓手机上各种连上之后无网络，点击测速会报错。
报错如图
![photo6134366283114850449](https://user-images.githubusercontent.com/34727840/60884872-ac324500-a280-11e9-9af5-5d80c7a00505.jpg)
   
 
 
![photo6134461755942873289](https://user-images.githubusercontent.com/34727840/60884874-accadb80-a280-11e9-9495-e04775ecb67c.jpg)

本来说家里电脑上用没问题，后来发现想错了，家里是联通网络，手机是移动4G。
然后我手机移动热点开起来给电脑，再用电脑连，发现电脑上也连不上去了。确实，同一个节点我联通宽带可能是50ms的ping，在移动的4G热点下可能是200-300ms还丢包严重。但是我同一台VPS上同时有V2ray和shadowsocks，我手机连V2ray是没有问题的，可以连上并且带宽也没有很大影响，本身我手机上也不需求低延迟。
但是shadowsocks就完全没有网络，不知道是不是我服务端配置有问题。

{
    "server":["::1", "0.0.0.0"],
    "mode":"tcp_and_udp",
    "fast_open": false,
    "nameserver":"8.8.8.8",
    "server_port":443,
    "local_port":1080,
    "password":"*********",
    "timeout":300,
    "method":"aes-256-gcm"
}

这是我服务端配置，不知道该怎么改动下才好？

**Comment by CatSamaaa** [comment]
试了其他的端口好像好多了。

**Comment by dashenniuyiniu** [comment]
我的是miui10稳定版安卓9
