### ISSUE TITLE
A question about unix socket in android.c

### ISSUE THREAD

**Issue by larry19840909** [shadowsocks/shadowsocks-libev#2426]
I find the different between protect_path and stat_main。

the socket path of stat_main is passed by android，but the prefix of protect_path had been removed，the same of sock_path in tun2sock.c。

how does the protect_path connect to the NO_BACKUP/protect_path in android side。
https://github.com/shadowsocks/shadowsocks-libev/blob/b8e75b546364a3adeb5a4a5c1329d01cf393abca/src/android.c#L68

**Comment by madeye** [comment]
protect_path is the relative path to $PWD. So, both Android and native code access the same file path.

**Comment by larry19840909** [comment]
thanks for replay.

I found the code set working directory.
https://github.com/shadowsocks/shadowsocks-android/blob/45fea9407c3d85d96c18a8c5c337a9d6d82e9f02/core/src/main/java/com/github/shadowsocks/bg/GuardedProcessPool.kt#L56

But why stat_main still pass the absolute Path？

**Comment by madeye** [comment]
Just some legacy code, no special reason.

Both approaches should work.

**Comment by larry19840909** [comment]
thanks.
