### ISSUE TITLE
Proxy the UDP traffic

### ISSUE THREAD

**Issue by jeetu28** [shadowsocks/shadowsocks-libev#2428]
#1543 # What version of shadowsocks-libev are you using?
ans:- shadowsocks-libev 3.2.0

### What operating system are you using?
ans:- debian 8

### What did you do?
We tried running shadowsocks client in udp mode
/usr/bin/ss-redir -a nobody -U -n 99999 -c /etc/shadowsocks-libev/configudp.json
shadowsocks server
/usr/bin/ss-server -d 127.0.0.1 -U -c /etc/shadowsocks-libev/sockstudp52-1.json

### What did you expect to see?
UDP traffic from client will get proxy to server.

### What did you see instead?
we cant see UDP traffic going out towards shadowsocks server from client.

### What is your config in detail (with all sensitive info masked)?
Client:
{
    "server" : ["x.x.x.x"],
    "server_port" : 9152,
    "local_address" : "10.52.1.1",
    "local_port" : 2080,
    "password" : "xxxxxxxxxx",
    "timeout" : 300,
    "method" : "aes-256-cfb",
    "fast_open" : true,
}
Server:
{
    "server":"0.0.0.0",
    "server_port":9152,
    "local_address": "0.0.0.0",
    "local_port":2152,
    "password":"xxxxxxxxxxxx",
    "timeout":300,
    "method":"aes-256-cfb",
    "fast_open": true
}

-there is a case where we want to proxy the UDP traffic over socks. can this be done using shadowsocks?
-if yes, whether these datagram will be encapsulated in TCP stream and then will get proxy to  socks server?
-I hope shadowsocks comply to SOCKS5 protocol, Please confirm?

**Comment by larry19840909** [comment]
where is the --manager-address option?

if not set the manager-address，the traffic stat function will not be work

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks-libev#transparent-proxy

**Comment by jeetu28** [comment]
This is to transport the TCP traffic . My concern here is to transport the UDP traffic inside TCP packets.
