### ISSUE TITLE
Requests are received but nothing happen

### ISSUE THREAD

**Issue by mahyari** [shadowsocks/shadowsocks-libev#2429]
### What version of shadowsocks-libev are you using?

3.0.0
### What operating system are you using?

Docker image of Debian 10 inside Ubuntu 18.04
### What did you do?
I use a docker container as operating system. 
```
# docker run -it -p 8080:8080 --name debian debian /bin/bash
```
inside container:
```
# apt-get update
# apt-get install openssl
# apt-get install git
# apt-get install python-pip
# pip install git+https://github.com/shadowsocks/shadowsocks.git@master
# ssserver -s 0.0.0.0 -p 8080 -k something -m aes-256-cfb -vv -d start
```

### What did you expect to see?
I expected client can connect to server easily but when I tried to connect to proxy, client failed to resolve google.com and showed "Internet Unavailable" message.

### What did you see instead?
I checked `/var/log/shadowsocks.log` file that contained below lines:

```
... 12:38:23 INFO     starting server at 0.0.0.0:8896
... 12:38:23 DEBUG    using event model: epoll
... 12:38:24 VERBOSE  fd 4 POLL_IN
... 12:38:24 DEBUG    accept
... 12:38:25 VERBOSE  fd 4 POLL_IN
... 12:38:25 DEBUG    accept
... 12:38:25 VERBOSE  fd 4 POLL_IN
... 12:38:25 DEBUG    accept
... 12:38:25 VERBOSE  fd 4 POLL_IN
... 12:38:25 DEBUG    accept
... 12:38:25 VERBOSE  fd 4 POLL_IN
... 12:38:25 DEBUG    accept
... 12:38:25 VERBOSE  fd 4 POLL_IN
... 12:38:25 DEBUG    accept
... 12:38:25 VERBOSE  fd 4 POLL_IN
... 12:38:25 DEBUG    accept
... 12:38:25 VERBOSE  fd 4 POLL_IN
... 12:38:25 DEBUG    accept
... 12:38:26 VERBOSE  fd 4 POLL_IN
... 12:38:26 DEBUG    accept
... 12:38:27 VERBOSE  fd 4 POLL_IN
... 12:38:27 DEBUG    accept
```

### What is your config in detail (with all sensitive info masked)?
- Host firewall is deactivate

**Comment by madeye** [comment]
From the log, it's obviously not related to shadowsocks-libev.
