### ISSUE TITLE
is it possible to install shadowsocks server on android.

### ISSUE THREAD

**Issue by kevinwenyu** [shadowsocks/shadowsocks-libev#2432]
hi, 
i have a tv box sleeping in my dorm, is it possible to transplant the shadowsocks-libev to android platform and install it on the tv box?

**Comment by rayhu** [comment]
There is already shadowsocks on android. You can install via google play or download an apk from the mirrors.

https://play.google.com/store/apps/details?id=com.github.shadowsocks

**Comment by kevinwenyu** [comment]
> There is already shadowsocks on android. You can install via google play or download an apk from the mirrors.
> 
> https://play.google.com/store/apps/details?id=com.github.shadowsocks
i mean install the ss server on the tv box, not the client...

**Comment by PantherJohn** [comment]
@kevinwenyu then the TV box needs to be `root`ed, I guess.

**Comment by he852100** [comment]
Android上都有openwrt了…只要有ss编译包，应该都没问题。

**Comment by PantherJohn** [comment]
@he852100 what about using `termux` with `gcc`?

**Comment by he852100** [comment]
@PantherJohn arch.

**Comment by 0neday** [comment]
I have check this [guide ](https://forum.xda-developers.com/t/trouble-compiling-8-2-0-kernel-from-source-for-shieldtv-2017.4164027/)for cross-compiling a arm64 shadowsocks-libev binary statically. 
1. use repo sync tool-chains for android tv 
2. setup PATH
3. compile

**Comment by segfault-bilibili** [comment]
Probably I've got it working just now: https://github.com/segfault-bilibili/shadowsocks-android

**Comment by ade951** [comment]
> Probably I made it working just now: https://github.com/segfault-bilibili/shadowsocks-android

I download the apk and install on my Android phone, but connect fail, can you tell me what's wrong with that?

**Comment by cross-hello** [comment]
Android in itself is a Linux, so it maybe possible.
Download Termux[https://github.com/termux/termux-app], run the server, 
then try to reverse proxy the traffic inside NAT to public address. You 
could have a try for cloudflared tunnel.

----------------------------------------

*From: *Richie ***@***.***>
*To: *shadowsocks/shadowsocks-libev 
***@***.***>
*CC: *Subscribed ***@***.***>
*Date: *Nov 29, 2022 14:57:31
*Subject: *Re: [shadowsocks/shadowsocks-libev] is it possible to install 
shadowsocks server on android. (#2432)

**Comment by cross-hello** [comment]
But the more reason answer is you want to ask a shadowsock client running 
in Android, which should be OK.
After running, you could pick out arbitrary app which supports socks5 and 
listens the port.

----------------------------------------

*From: *Richie ***@***.***>
*To: *shadowsocks/shadowsocks-libev 
***@***.***>
*CC: *Subscribed ***@***.***>
*Date: *Nov 29, 2022 14:57:31
*Subject: *Re: [shadowsocks/shadowsocks-libev] is it possible to install 
shadowsocks server on android. (#2432)
