### ISSUE TITLE
如何升级到3.3.0新版本

### ISSUE THREAD

**Issue by lssmoon2019** [shadowsocks/shadowsocks-libev#2434]
我手工方式安装的3.2.5版本，如何升级到最新3.3.0
操作系统：CentOS7 x64

**Comment by PantherJohn** [comment]
@lssmoon2019 
```
# compile installation
git clone https://github.com/shadowsocks/shadowsocks-libev.git
cd shadowsocks-libev
git submodule update --init --recursive

# dependencies
sudo yum install gettext gcc autoconf libtool automake make asciidoc xmlto c-ares-devel libev-devel

# generate rpm binary package
sudo rpm/genrpm.sh -b
```
then you go to `rpm/RPMS/<target_platform>` and `yum install` the resulting package `shadowsocks-libev-3.3.0.*.centos.x86_64.rpm`.

**Comment by QWERT1984** [comment]
Seems not work. the following message shows when I enter the git clone https://github.com/shadowsocks/shadowsocks-libev.git into the terminal.

"Fatal: destination path 'shadowsocks-libev' already exists and is not an empty directory. "
