### ISSUE TITLE
Increase the robustness of DNS resolve

### ISSUE THREAD

**Issue by 8x8-64** [shadowsocks/shadowsocks-libev#2436]
### What version of shadowsocks-libev are you using?
3.2.5

### What operating system are you using?
别人集成在路由器固件的，arm版

### What did you do?
用aes-128-gcm加密做dns查询，客户端会向服务器端发起连接，典型的是发送一个130左右字节的包，又收到1个130左右字节的包就断开连接，特征太明显。对于连接53端口，我在服务器端（非libev版）返回的加密数据后面直接增加了一定长度随机数据。libev、android版客户端不能正常工作，但是c#版的可以。

### What did you expect to see?
这个类似发生了tcp粘包，第1个包是正确的，后面的包是错误的，我希望客户端收到这样的数据能正常工作。本来客户端就是读完第1个包结果后要主动断开连接的，后面的多余数据不应该产生影响。

**Comment by madeye** [comment]
Perform DNS queries in UDP, not in TCP.

**Comment by 8x8-64** [comment]
是吗？服务器端是我自己用python socketserver.ThreadingTCPServer写的，根本没实现udp功能

**Comment by 8x8-64** [comment]
去掉加的尾巴，客户端就正常

**Comment by 8x8-64** [comment]
aead.c中aead_decrypt函数里循环调用aead_chunk_decrypt解密，遇到返回错误码就跳出了。跳出前并没有检查之前是不是已经解密出了数据，比如已经解出2个，第3个被窜改了，就完全不管前2个的结果，导致我这种情况

**Comment by 8x8-64** [comment]
另外解密前面对了，后面出错也可以不马上断开连接，可以丢弃后面数据再次等待新数据。目前没有发现中间人伪造客户端tcp数据包的情况。就有了客户端自己发错数据包改变流量特征的机会

**Comment by madeye** [comment]
The behavior is expected and correct.

**Comment by 8x8-64** [comment]
断开连接的行为这个取决于开发者的判断。但是解密出来的数据因为后面接着的数据错误就丢掉，怎么是正确的呢？tcp本身存在粘包的可能，中间人插入一个伪造的tcp数据包，正好和前面真实的数据包在接收端粘上了，接收端就不要前面真实的数据？不是应该在不可靠的环境中尽量传输可靠的数据？

**Comment by 8x8-64** [comment]
目前解决办法是，服务器在后面发加密的随机数据就行，反正客户端收到第1个解密数据块后就会断开连接
