### ISSUE TITLE
在本地使用ss-local连接到ss-server，开放了ss-local地址为0.0.0.0:123，现在想有个连接规则

### ISSUE THREAD

**Issue by GoGoogle** [shadowsocks/shadowsocks-libev#2437]
### What version of shadowsocks-libev are you using?
shadowsocks-libev 2.6.3 with mbed TLS 2.4.2

### What operating system are you using?
debian9

### What did you do?
- 在本地192.168.0.2使用ss-local连接到ss-server1.2.3.4:333，开放了ss-local地址为0.0.0.0:123，现在想有个连接规则

- 在192.168.0.3上配置使用192.168.0.2:123即可连接到ss-server1.2.3.4:333

####  如果我想在192.168.0.2上设置相关连接规则，只让192.168.0.3，192.168.0.4，以及2.2.2.0/24段连接到192.168.0.2:123上，其它的连接都拒绝掉，该怎么办到？

 我测试过ss-local的acl配置，[reject_all]和[white_list]不能使用在ss-local的acl中，或者说是无效的。

**Comment by PantherJohn** [comment]
@GoGoogle the feature you requested hasn’t been implemented yet. Please keep in mind that ONLY the server version of shadowsocks is able to block clients from being connected to the listening socket.

**Comment by GoGoogle** [comment]
> @GoGoogle the feature you requested hasn’t been implemented yet. Please keep in mind that ONLY the server version of shadowsocks is able to block clients from being connected to the listening socket.

明白了，谢谢！

不知道是否还有别的方法来达到这个效果？

**Comment by PantherJohn** [comment]
@GoGoogle 
### `iptables`(recommended)
Use `ipset` and `iptables`.
### Hand-core users
There’s one way I can think of: If you are familiar with socket programming you may modify the source code directly. Below are files that need to be changed:

- `local.c` `accept_cb()`
- `acl.c` config parsing

**Comment by GoGoogle** [comment]
@PantherJohn 非常感谢您的帮助。

**Comment by GoGoogle** [comment]
```
iptables -I INPUT -p tcp --dport 123 -j DROP
iptables -I INPUT -s 127.0.0.1 -p tcp --dport 123 -j ACCEPT
iptables -I INPUT -s 192.168.0.2 -p tcp --dport 123 -j ACCEPT
iptables -I INPUT -s 192.168.0.3 -p tcp --dport 123 -j ACCEPT
iptables -I INPUT -s 192.168.0.4 -p tcp --dport 123 -j ACCEPT
iptables -I INPUT -s 2.2.2.0/24 -p tcp --dport 123 -j ACCEPT
```
