### ISSUE TITLE
ss-local segmentation fault 

### ISSUE THREAD

**Issue by GoGoogle** [shadowsocks/shadowsocks-libev#2439]
### What version of shadowsocks-libev are you using?
shadowsocks-libev 2.6.3 with mbed TLS 2.4.2

### What operating system are you using?
Debian9

### What did you do?
今天发现一件很有意思的事情，如果我在BTSync上使用ss-local出来的socks5代理，那么它就会崩溃。

- 会出现以下错误信息：
`segmentation fault  /usr/bin/ss-local -c /root/test.json`

试过好几回了，百试百灵。

原因不明。

### BTSync版本：
2.6.2(1330) For DSM

**Comment by madeye** [comment]
Try the latest version.

**Comment by GoGoogle** [comment]
@madeye Debian9源里面只有2.6.3

**Comment by GoGoogle** [comment]
> Try the latest version.

我切换到shadowsocks-libev 3.2.5做同样的测试之后，后台日志里面会大量出现：
`ERROR: remote_recv_cb_recv: Connection reset by peer`

但暂时不会崩溃，不知道时间长了后会不会崩溃，我打算测试12小时试试。

**Comment by z991238** [comment]
> > 试试最新版本。
> 
> 我切换到shadowsocks-libev 3.2.5做同样的测试之后，后台日志里面会大量出现：
> `ERROR: remote_recv_cb_recv: Connection reset by peer`
> 
> 但暂时不会崩溃，不知道时间长了后会不会崩溃，我打算测试12小时试试。


I have encountered this remote_recv_cb_recv: Connection reset by peer, but if the timeout is set to 60s, there will be no disconnection. But it is not clear what happens for this reason.

**Comment by PantherJohn** [comment]
@madeye @GoGoogle @z991238
Use [address sanitizer (`libasan`)](https://github.com/google/sanitizers/wiki/AddressSanitizer) together with GCC 4.9.3+ and recompile the binary. This will give you the detailed information on where exactly the segfault occurs.

**Comment by GoGoogle** [comment]
@PantherJohn thanks。
