### ISSUE TITLE
crash when posting a picture in telegram

### ISSUE THREAD

**Issue by netcaf** [shadowsocks/shadowsocks-libev#2440]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
shadowsocks-libev 3.1.3
simple-obfs 0.0.5

### What operating system are you using?
Ubuntu 18.04.2 LTS

### What did you do?
Set up a ss-server with simple-obfs enabled and connect to it with Shadowrocket in IOS.

### What did you expect to see?
Everything is OK.

### What did you see instead?
It works very well with browsers, WhatsApp, and normal Telegram operation, but when I tried to post one picture in any Telegram Group, the server-side crashed immediately. More precisely, in the log of journalctrl, obfs-server crashed. I'm not sure whether it is related to obfs or shadowsocks. 

Here is the log related:
Jul 27 14:42:57 kz-linux-vm ss-server[50350]:  2019-07-27 14:42:48 INFO: using tcp fast open
Jul 27 14:42:57 kz-linux-vm ss-server[50350]:  2019-07-27 14:42:48 INFO: plugin "obfs-server" enabled
Jul 27 14:42:57 kz-linux-vm ss-server[50350]:  2019-07-27 14:42:48 INFO: UDP relay enabled
Jul 27 14:42:57 kz-linux-vm ss-server[50350]:  2019-07-27 14:42:48 INFO: initializing ciphers... xchacha20-ietf-poly1305
Jul 27 14:42:57 kz-linux-vm ss-server[50350]:  2019-07-27 14:42:48 INFO: using nameserver: 8.8.4.4
Jul 27 14:42:57 kz-linux-vm ss-server[50350]:  2019-07-27 14:42:48 INFO: tcp server listening at 127.0.0.1:34907
Jul 27 14:42:57 kz-linux-vm ss-server[50350]:  2019-07-27 14:42:48 INFO: tcp port reuse enabled
Jul 27 14:42:57 kz-linux-vm ss-server[50350]:  2019-07-27 14:42:48 INFO: udp server listening at 0.0.0.0:443
Jul 27 14:42:57 kz-linux-vm ss-server[50350]:  2019-07-27 14:42:48 INFO: udp port reuse enabled
Jul 27 14:42:57 kz-linux-vm ss-server[50350]:  2019-07-27 14:42:48 INFO: accept a connection
Jul 27 14:42:57 kz-linux-vm ss-server[50350]:  2019-07-27 14:42:48 INFO: connect to 91.108.56.187:443
Jul 27 14:42:57 kz-linux-vm ss-server[50350]:  2019-07-27 14:42:48 INFO: accept a connection
Jul 27 14:42:57 kz-linux-vm ss-server[50350]:  2019-07-27 14:42:48 INFO: connect to 91.108.56.187:5222
Jul 27 14:42:57 kz-linux-vm ss-server[50350]:  2019-07-27 14:42:48 INFO: accept a connection
Jul 27 14:42:57 kz-linux-vm ss-server[50350]:  2019-07-27 14:42:48 INFO: connect to 149.154.171.5:443
Jul 27 14:42:57 kz-linux-vm ss-server[50350]:  2019-07-27 14:42:48 INFO: accept a connection
Jul 27 14:42:57 kz-linux-vm ss-server[50350]:  2019-07-27 14:42:48 INFO: connect to 149.154.171.5:5222
Jul 27 14:42:57 kz-linux-vm ss-server[50350]:  2019-07-27 14:42:48 INFO: accept a connection
Jul 27 14:42:57 kz-linux-vm ss-server[50350]:  2019-07-27 14:42:48 INFO: connect to 91.108.56.187:80
Jul 27 14:42:57 kz-linux-vm ss-server[50350]:  2019-07-27 14:42:49 INFO: remote connected
Jul 27 14:42:57 kz-linux-vm ss-server[50350]:  2019-07-27 14:42:49 INFO: server_recv close the connection
Jul 27 14:42:57 kz-linux-vm ss-server[50350]:  2019-07-27 14:42:49 INFO: current remote connection: 4
Jul 27 14:42:57 kz-linux-vm ss-server[50350]:  2019-07-27 14:42:49 INFO: current server connection: 4
Jul 27 14:42:57 kz-linux-vm ss-server[50350]:  2019-07-27 14:42:49 INFO: server_recv close the connection
Jul 27 14:42:57 kz-linux-vm ss-server[50350]:  2019-07-27 14:42:49 INFO: current remote connection: 3
Jul 27 14:42:57 kz-linux-vm ss-server[50350]:  2019-07-27 14:42:49 INFO: current server connection: 3
Jul 27 14:42:57 kz-linux-vm ss-server[50350]:  2019-07-27 14:42:49 INFO: server_recv close the connection
Jul 27 14:42:57 kz-linux-vm ss-server[50350]:  2019-07-27 14:42:49 INFO: current remote connection: 2
Jul 27 14:42:57 kz-linux-vm ss-server[50350]:  2019-07-27 14:42:49 INFO: current server connection: 2
Jul 27 14:42:57 kz-linux-vm ss-server[50350]:  2019-07-27 14:42:49 INFO: server_recv close the connection
Jul 27 14:42:57 kz-linux-vm ss-server[50350]:  2019-07-27 14:42:49 INFO: current remote connection: 1
Jul 27 14:42:57 kz-linux-vm ss-server[50350]:  2019-07-27 14:42:49 INFO: current server connection: 1
Jul 27 14:42:57 kz-linux-vm ss-server[50350]:  2019-07-27 14:42:49 INFO: server_recv close the connection
Jul 27 14:42:57 kz-linux-vm ss-server[50350]:  2019-07-27 14:42:49 INFO: current remote connection: 0
Jul 27 14:42:57 kz-linux-vm ss-server[50350]:  2019-07-27 14:42:49 INFO: current server connection: 0
Jul 27 14:42:57 kz-linux-vm ss-server[50350]:  2019-07-27 14:42:49 INFO: accept a connection
Jul 27 14:42:57 kz-linux-vm ss-server[50350]:  2019-07-27 14:42:49 INFO: connect to 91.108.56.187:443
Jul 27 14:42:57 kz-linux-vm ss-server[50350]:  2019-07-27 14:42:49 INFO: accept a connection
Jul 27 14:42:57 kz-linux-vm ss-server[50350]:  2019-07-27 14:42:49 INFO: connect to 91.108.56.187:443
Jul 27 14:42:57 kz-linux-vm ss-server[50350]:  2019-07-27 14:42:49 INFO: remote connected
Jul 27 14:42:57 kz-linux-vm ss-server[50350]:  2019-07-27 14:42:51 INFO: accept a connection
Jul 27 14:42:57 kz-linux-vm ss-server[50350]:  2019-07-27 14:42:51 INFO: connect to google.com:443
Jul 27 14:42:57 kz-linux-vm ss-server[50350]:  2019-07-27 14:42:51 INFO: found address name v4 address google.com
Jul 27 14:42:57 kz-linux-vm ss-server[50350]:  2019-07-27 14:42:51 INFO: found address name v6 address google.com
Jul 27 14:42:57 kz-linux-vm ss-server[50350]:  2019-07-27 14:42:51 INFO: successfully resolved google.com
Jul 27 14:42:57 kz-linux-vm ss-server[50350]:  2019-07-27 14:42:51 INFO: remote connected
Jul 27 14:42:57 kz-linux-vm ss-server[50350]:  2019-07-27 14:42:53 INFO: accept a connection
Jul 27 14:42:57 kz-linux-vm ss-server[50350]:  2019-07-27 14:42:53 INFO: connect to 104.250.205.197:443
Jul 27 14:42:57 kz-linux-vm ss-server[50350]:  2019-07-27 14:42:53 INFO: remote connected
Jul 27 14:42:57 kz-linux-vm ss-server[50350]:  2019-07-27 14:42:53 INFO: server_recv close the connection
Jul 27 14:42:57 kz-linux-vm ss-server[50350]:  2019-07-27 14:42:53 INFO: current remote connection: 3
Jul 27 14:42:57 kz-linux-vm ss-server[50350]:  2019-07-27 14:42:53 INFO: current server connection: 3
Jul 27 14:42:57 kz-linux-vm ss-server[50350]:  2019-07-27 14:42:54 INFO: server_recv close the connection
Jul 27 14:42:57 kz-linux-vm ss-server[50350]:  2019-07-27 14:42:54 INFO: current remote connection: 2
Jul 27 14:42:57 kz-linux-vm ss-server[50350]:  2019-07-27 14:42:54 INFO: current server connection: 2
Jul 27 14:42:57 kz-linux-vm ss-server[50350]:  2019-07-27 14:42:55 INFO: accept a connection
Jul 27 14:42:57 kz-linux-vm ss-server[50350]:  2019-07-27 14:42:55 INFO: connect to 104.250.205.197:443
Jul 27 14:42:57 kz-linux-vm ss-server[50350]:  2019-07-27 14:42:55 INFO: remote connected
Jul 27 14:42:57 kz-linux-vm ss-server[50350]:  2019-07-27 14:42:56 INFO: server_recv close the connection
Jul 27 14:42:57 kz-linux-vm ss-server[50350]:  2019-07-27 14:42:56 INFO: current remote connection: 2
Jul 27 14:42:57 kz-linux-vm ss-server[50350]:  2019-07-27 14:42:56 INFO: current server connection: 2
Jul 27 14:42:57 kz-linux-vm ss-server[50350]:  2019-07-27 14:42:56 INFO: server_recv close the connection
Jul 27 14:42:57 kz-linux-vm ss-server[50350]:  2019-07-27 14:42:56 INFO: current remote connection: 1
Jul 27 14:42:57 kz-linux-vm ss-server[50350]:  2019-07-27 14:42:56 INFO: current server connection: 1
Jul 27 14:42:57 kz-linux-vm ss-server[50350]:  2019-07-27 14:42:56 INFO: server_recv close the connection
Jul 27 14:42:57 kz-linux-vm ss-server[50350]:  2019-07-27 14:42:56 INFO: current remote connection: 0
Jul 27 14:42:57 kz-linux-vm ss-server[50350]:  2019-07-27 14:42:56 INFO: current server connection: 0
Jul 27 14:42:57 kz-linux-vm ss-server[50350]:  2019-07-27 14:42:56 INFO: accept a connection
Jul 27 14:42:57 kz-linux-vm ss-server[50350]:  2019-07-27 14:42:56 INFO: connect to 91.108.56.187:443
Jul 27 14:42:57 kz-linux-vm ss-server[50350]:  2019-07-27 14:42:56 INFO: remote connected
Jul 27 14:42:57 kz-linux-vm ss-server[50350]:  2019-07-27 14:42:57 INFO: accept a connection
Jul 27 14:43:06 kz-linux-vm kernel: obfs-server[50351]: segfault at 56078aa9a000 ip 00007f68383d9dbf sp 00007ffd3fe8ebe8 error 4 in libc-2.27.so[7f683824b000+1e7000]
Jul 27 14:43:06 kz-linux-vm kernel: Code: 0f 18 8e 00 01 00 00 0f 18 8e 40 01 00 00 0f 18 8e 80 01 00 00 0f 18 8e c0 01 00 00 c5 fe 6f 06 c5 fe 6f 4e 20 c5 fe 6f 56 40 <c5> fe 6f 5e 60 48 81 c6 80 00 00 00 48 81 ea 80 00 00 00 c5 fd e7 
Jul 27 14:43:06 kz-linux-vm ss-server[50350]:  2019-07 2019-07-27 14:43:06 ERROR: plugin service exit unexpectedly
Jul 27 14:43:06 kz-linux-vm ss-server[50350]: -27 14:42:57 INFO: connect to 91.108.56.187:443
Jul 27 14:43:06 kz-linux-vm ss-server[50350]:  2019-07-27 14:42:58 INFO: remote connected
Jul 27 14:43:06 kz-linux-vm ss-server[50350]:  2019-07-27 14:43:06 INFO: accept a connection
Jul 27 14:43:06 kz-linux-vm ss-server[50350]:  2019-07-27 14:43:06 INFO: connect to 91.108.56.187:443
Jul 27 14:43:06 kz-linux-vm ss-server[50350]:  2019-07-27 14:43:06 INFO: remote connected
Jul 27 14:43:06 kz-linux-vm ss-server[50350]:  2019-07-27 14:43:06 INFO: server_recv close the connection
Jul 27 14:43:06 kz-linux-vm ss-server[50350]:  2019-07-27 14:43:06 INFO: current remote connection: 2
Jul 27 14:43:06 kz-linux-vm ss-server[50350]:  2019-07-27 14:43:06 INFO: current server connection: 2
Jul 27 14:43:06 kz-linux-vm ss-server[50350]:  2019-07-27 14:43:06 INFO: server_recv close the connection
Jul 27 14:43:06 kz-linux-vm ss-server[50350]:  2019-07-27 14:43:06 INFO: current remote connection: 1
Jul 27 14:43:06 kz-linux-vm ss-server[50350]:  2019-07-27 14:43:06 INFO: current server connection: 1
Jul 27 14:43:06 kz-linux-vm ss-server[50350]:  2019-07-27 14:43:06 INFO: server_recv close the connection
Jul 27 14:43:06 kz-linux-vm ss-server[50350]:  2019-07-27 14:43:06 INFO: current remote connection: 0
Jul 27 14:43:06 kz-linux-vm ss-server[50350]:  2019-07-27 14:43:06 INFO: current server connection: 0
Jul 27 14:43:06 kz-linux-vm ss-server[50350]:  2019-07-27 14:43:06 INFO: closed gracefully

### What is your config in detail (with all sensitive info masked)?

{
    "server": "0.0.0.0",
    "server_port": "443",
    "password": "xxxx",
    "method": "xchacha20-ietf-poly1305",
    "reuse_port":true,
    "fast_open":true,
    "timeout": 600,
    "workers": 10,
    "mode":"tcp_and_udp",
    "plugin":"obfs-server",
    "plugin_opts":"obfs=tls",
    "nameserver": "8.8.4.4"
}

**Comment by madeye** [comment]
I don't think it's related to this project.

Also simple-obfs is already deprecated, try other plugins instead.

**Comment by netcaf** [comment]
Got it. Thanks!
