### ISSUE TITLE
LIB_ONLY issue when building libshadowsocks-libev.a by CMake

### ISSUE THREAD

**Issue by gopiedpiper** [shadowsocks/shadowsocks-libev#2443]
It seems that building libshadowsocks-libev.a by CMake with no LIB_ONLY defined. It makes no _start_ss_local_server when some EXE linking with libshadowsocks-libev.a. Locally I resolved it by updating src/CMakeLists.txt:184 to:
```
target_compile_definitions(shadowsocks-libev PUBLIC -DMODULE_LOCAL -DLIB_ONLY)
```

**Comment by madeye** [comment]
Please open a pull request.

**Comment by gopiedpiper** [comment]
@madeye Sorry, I can't. My environment is a mess now.
