### ISSUE TITLE
buid on Ubunt 16.04

### ISSUE THREAD

**Issue by maxchendt** [shadowsocks/shadowsocks-libev#2444]
on Ubuntu 16.04 `./build_deb.sh`, no deb is built.

Error messages:

> dpkg-checkbuilddeps: error: Unmet build dependencies: libc-ares-dev libev-dev libmbedtls-dev libpcre3-dev libsodium-dev (>= 1.0.12)
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)
debuild: fatal error at line 1376:
dpkg-buildpackage -rfakeroot -D -us -uc -i -I failed
gbp:error: 'debuild -i -I -us -uc' failed: it exited with 29

according to https://packages.ubuntu.com/search?keywords=libsodium-dev
> xenial (16.04LTS) (libdevel): Network communication, cryptography and signaturing library - headers [universe]
1.0.8-5: amd64 arm64 armhf i386 powerpc ppc64el s390x
xenial-updates (libdevel): Network communication, cryptography and signaturing library - headers
1.0.8-5: amd64 arm64 armhf i386 powerpc ppc64el s390x 

how to resolve these "Unmet build dependencies"?

**Comment by madeye** [comment]
Upgrade to Ubuntu 18.04 then try again.

**Comment by maxchendt** [comment]
It works on 18.04, but I have some vps still on 16.04
