### ISSUE TITLE
does it support multi client users 

### ISSUE THREAD

**Issue by cbdgftqs** [shadowsocks/shadowsocks-libev#2445]
like python version shadowsocks client config file
"port_password":{
    	"port1":"password1",
    	"port2":"password2",
    	"port3":"password3"
    },

**Comment by PantherJohn** [comment]
@cbdgftqs Nope. You should either try `reuse_port` or use a [modified](https://github.com/eLitetInc/shadowsocks-libev) version of shadowsocks-libev.

**Comment by madeye** [comment]
Use `ss-manager` for `port_password` configs.

**Comment by PantherJohn** [comment]
@madeye He’s asking for **client** config though.

**Comment by madeye** [comment]
`port_password` is only for server config. It's also true for shadowsocks-python.
