### ISSUE TITLE
Make ss-redir listen to both v4&v6 ports

### ISSUE THREAD

**Issue by dianlujitao** [shadowsocks/shadowsocks-libev#2446]
### What version of shadowsocks-libev are you using?
3.2.0

### What operating system are you using?
OpenWrt 18.06.1 r7258-5eb055306f

### What did you do?
By default `ss-redir` listens to only v4 port [(via 0.0.0.0)](https://github.com/shadowsocks/luci-app-shadowsocks/blob/master/files/root/etc/init.d/shadowsocks#L104) using the config generated by `luci-app-shadowsocks`, and `netstat -an|grep 1234` outputs:

```
tcp        0      0 0.0.0.0:1234            0.0.0.0:*               LISTEN
udp        0      0 0.0.0.0:1234            0.0.0.0:*
```

To make it listen to the v6 port as well, I changed the config.json to be `"local_address": "::"`. After that `netstat` output became:

```
tcp        0      0 :::1234                 :::*                    LISTEN
udp        0      0 :::1234                 :::*
```

Now I'm able to telnet to port 1234 from my PC via both 192.168.1.1 and the v6 counterpart. However, the telnet connection through v6 is closed **right after** established without manual cancellation, here's telnet's output:

```
Trying fd9c:c06:3377::1...
Connected to fd9c:c06:3377::1.
Escape character is '^]'.
Connection closed by foreign host.
```

Moreover, UDP relay (over v4) stopped working (verified using `dig google.com @8.8.8.8`), the corresponding iptable rule within mangle table looks like this:

```
Chain SS_SPEC_WAN_FW (3 references)
pkts bytes target     prot opt in     out     source               destination
1    79 TPROXY     udp  --  *      *       0.0.0.0/0            0.0.0.0/0            TPROXY redirect 0.0.0.0:1234 mark 0x1/0x1
```

There might be more breakages after the migration of `local_address` from `0.0.0.0` to `::`.

PS: Setting `local_address` to `["[::0]", "0.0.0.0"]` as `ss-server` doesn't work.

### What did you expect to see?

Proper support of dual stack for `ss-redir`, i.e., as `ss-server` behaves. With `"server":["[::0]", "0.0.0.0"]` for `ss-server`, `ss -an | grep 8388` outputs:

```
udp  UNCONN 0      0                                        0.0.0.0:8388                                           0.0.0.0:*
udp  UNCONN 0      0                                           [::]:8388                                              [::]:*
tcp  LISTEN 0      128                                      0.0.0.0:8388                                           0.0.0.0:*
tcp  LISTEN 0      128                                         [::]:8388                                              [::]:*
```

Where both `0.0.0.0` and `[::]` are listed.

### What did you see instead?

Preceding.

### What is your config in detail (with all sensitive info masked)?

```json
{
"server": "****",
"server_port": 12388,
"password": "hehehehe",
"method": "chacha20-ietf-poly1305",
"local_address": "0.0.0.0",
"timeout": 60,
"reuse_port": true
}
```

Started with `ss-redir -c /var/etc/shadowsocks.cfg054a8f.json -u --fast-open -l 1234 --mtu 1492`

**Comment by madeye** [comment]
Just open two `ss-redir` listening on `0.0.0.0` and `::0` separately.

**Comment by dianlujitao** [comment]
Thanks for the response, it works in this way, but is it sort of temporary workaround? If so can I expect it to be properly implemented in the future?

BTW, I added such rule:

```
ip6tables -t mangle -I PREROUTING -p {tcp,udp} -m set --match-set gfwv6 dst -j TPROXY --on-port 1234 --tproxy-mark 0x01/0x01
```

UDP redirecting works well while TCP doesn't (again verified using dig w/ or w/o `+tcp`) , is this a bug or misconfiguration?

**Comment by madeye** [comment]
Use `REDIRECT` rules to redirect TCP traffic.

Refer to the doc for more details.

**Comment by dianlujitao** [comment]
For sake of flexibility I don't use nat6 thus I can't use `REDIRECT`. I also tested v2ray for comparison. With exact the same ip(6)tables and ipset rules, `ss-redir` has working udp but broken tcp while `v2ray` (vmess, didn't test shadowsocks impl) has working tcp but broken udp under native ipv6 stack without NAT, see https://github.com/v2ray/v2ray-core/issues/1309 for v2ray configuration details.

I'm not a pro in computer networks, but does the preceding phenomenon prove that it IS possible to support both tcp/udp tproxy in native ipv6 stack without relying on nat6?

**Comment by madeye** [comment]
`NAT6` is required for redirecting TCP traffic. TCP redirecting using `TPROXY` is not supported.

It's expected and by design.

**Comment by dianlujitao** [comment]
Thanks a million for the clarification.
