### ISSUE TITLE
多用户下如何实现不同端口对应不同加密方式？

### ISSUE THREAD

**Issue by Aniark** [shadowsocks/shadowsocks-libev#2448]
目前使用的服务端版本是v3.3.0，搜索了一圈issues，只搜到多用户不同端口使用同一加密方式的config配置格式。

我想让不同端口对应不同加密方式，请问要如何配置？

2019.8.9更新：抱歉打错字了，应为“服务端”

**Comment by PantherJohn** [comment]
#2445

**Comment by PantherJohn** [comment]
@Aniark Nope. You should either try `reuse_port` or use a [modified](https://github.com/eLitetInc/shadowsocks-libev) version of shadowsocks-libev.

**Comment by madeye** [comment]
HAProxy + multiple `ss-server` is the suggested solution for your use case.

**Comment by PantherJohn** [comment]
@Aniark simply use `port_password` for `ss-manager`.
