### ISSUE TITLE
ss-server Abnormal high CPU usage

### ISSUE THREAD

**Issue by yku12cn** [shadowsocks/shadowsocks-libev#2449]
### What version of shadowsocks-libev are you using?
**ss-server version 3.3.0**

### What operating system are you using?
Ubuntu 18.04.2 LTS

### What did you do?
Run ss-server with following commands:
ss-server -6 --no-delay -s"0.0.0.0" -u -c ./config.json

### What did you expect to see?
Stable long term running with reasonable CPU usage

### What did you see instead?
note: I was not able to 100% reproduce this BUG, but it is happening quite frequently.
Once it happens, ss-server will saturate CPU to 100% until the process is killed manually.
This can only be triggered by paring with the Android SS client 4.7.4 (https://github.com/shadowsocks/shadowsocks-android).
If this issue is not triggered, such client will function just fine.

### What is your config in detail (with all sensitive info masked)?
**config.json:**
{
    "server_port":42000,
    "local_port":1080,
    "password":"asdfhringring",
    "timeout":300,
    "method":"xchacha20-ietf-poly1305",
    "fast_open": false,
    "plugin":"obfs-server",
    "plugin_opts":"obfs=http"
}

### Additional info
I also enabled verbose mode, but no unusual log captured when this issue occured. 

Any suggestions on what I should try to capture or trigger this bug? Thanks!

**Comment by madeye** [comment]
Try update the`libc-ares` on your system.

**Comment by yku12cn** [comment]
> Try update the`libc-ares` on your system.

which version are you referring to?

**Comment by madeye** [comment]
https://github.com/c-ares/c-ares/releases/tag/cares-1_15_0

**Comment by yku12cn** [comment]
Is there any previous discussion about this? I'd like to know the root cause.

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks-libev/issues/1690

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks-libev/issues/2107

**Comment by yku12cn** [comment]
I don't get it, why failing to resolve hostname will saturate cpu?

BTW, my current libc-ares is 1.14.0, is this the problematic version?

**Comment by madeye** [comment]
From your description, it's a typical issue related to hostname resolving, as only android client forces to resolve hostnames on the server.

In the async DNS resolving in `libc-ares`, some versions of `libc-ares` and `resolv.conf` would cause this kind of hanging.

So, first update your libc-ares and try again.

**Comment by madeye** [comment]
Tested on Ubuntu 18.04.2 locally, everything works well.

**Comment by yku12cn** [comment]
I also done a lot local tests before. This issue is not guaranteed to be triggered every time.
If this is really the bug you mentioned, is there any specific log that indicates it?

**Comment by madeye** [comment]
Since the hang happens in `libc-ares`, there's no specific log from shadowsocks-libev.

You can also try remove `-6`, `--no-delay` from your command line.

**Comment by yku12cn** [comment]
already tested without -6, --no-delay days ago. Issue still happens.

**Comment by madeye** [comment]
If you have interest to do some debug, run `ss-server` with `gdb` and break when the hang happens. From the call stack we can see where the hang happens.

**Comment by madeye** [comment]
BTW, you can also try add `-d 8.8.8.8` to your command line.

**Comment by yku12cn** [comment]
As for the gdb part, should I re-compile ss-server to support debug? If so, may you provide some more specific instructions?

will try -d 8.8.8.8... 

BTW, I do think we should make more use of config.json, instead of leaving all configuration to the commend line..

**Comment by madeye** [comment]
No special compiler options required.

Just make sure you can build ss-server from source code, and not using prebuilt binaries.

**Comment by yku12cn** [comment]
Yeah, I build with following commands:
    git clone https://github.com/shadowsocks/shadowsocks-libev.git
    cd shadowsocks-libev
    git submodule update --init --recursive
    ./autogen.sh && ./configure && make
    sudo make install

**Comment by yku12cn** [comment]
will -d 8.8.8.8 affects ipv6 hostname resolving?

**Comment by madeye** [comment]
> will -d 8.8.8.8 affects ipv6 hostname resolving?

Nope.

> sudo make install

Use the binaries in `src/` folder, not the installed binaries under `/usr/`

**Comment by yku12cn** [comment]
Thx
Will try with the latest libc-ares for a few days before dive into further debugging.

**Comment by yku12cn** [comment]
With cares-1_15_0 and -d 8.8.8.8, the problem is still there. Will run with gdb.

**Comment by yku12cn** [comment]
> No special compiler options required.
> 
> Just make sure you can build ss-server from source code, and not using prebuilt binaries.

I can run with following command:
gdb ss-server
run ss-server -6 -d 8.8.8.8 --no-delay -s"0.0.0.0" -u -c ~/config.json

But i'm not sure gdb can capture any issue in this way. Since this issue will not cause crash. Any instructions?

**Comment by PantherJohn** [comment]
@yku12cn
Make sure `-ggdb` is set and recompile
```
make CFLAGS='-ggdb'
```

**Comment by madeye** [comment]
As I mentioned, use the `src/ss-server` instead of `/usr/local/bin/ss-server`.

By default, the binary is compiled with `-g` option: https://github.com/shadowsocks/shadowsocks-libev/blob/9aa46cbc3f3110e812237008df13fdc103e9d0b4/src/Makefile.am#L3

**Comment by madeye** [comment]
BTW, please also try revert back to 3.2.5 to see if that issue still exits.

**Comment by madeye** [comment]
It turns out a bug introduced by https://github.com/shadowsocks/shadowsocks-libev/commit/a99c39c7dd314939082348d96d06727570b514a8

**Comment by yku12cn** [comment]
Glad you figure out what's going on.
Does that mean you know how to trigger this bug?
I'm willing to help verifying the fix if you already have one.

**Comment by yku12cn** [comment]
> The trick is that you need to send some random packets to the `ss-server`, then the auto-blocking mechanism would cause the hang.
> 
> In my test environment, this bug is not exposed as the client is always a "good behavior" one.

Interesting. That explain why I'm not able to 100% reproduce this, since my client is not always behave abnormally. 
So, is [https://github.com/shadowsocks/shadowsocks-libev/commit/1c4ddd37240c6a8946f3be18acbce188665ed5b7](url) a fix?

**Comment by yku12cn** [comment]
I see, I will run 3.3.1 for a few days and provide feedback asap.

**Comment by yku12cn** [comment]
It's been a week. I haven't seen any issue so far. I think the fix(1c4ddd3) is working.
It turns out that the client which kept triging this issue was a Samsung smartphone.  The smartphone come with an anti-malware-tool which somehow tends to send stange packages to the server.

Thanks again for the fix.
