### ISSUE TITLE
A strange problem,is it related to ss-redir?

### ISSUE THREAD

**Issue by vpnrouter** [shadowsocks/shadowsocks-libev#245]
Hi there!I have updated ss-redir and ss-tunnel to version 2.1.0 as in issue #230 you told me to.
It worked well at first.But today my partner found a strange problem.System log suggests too many sockets were not closed properly.Linux kernel print keeps printing "TCP:Too many of orphaned sockets".But this problem never happens to other people including me.I wonder if this has something to do with ss-reidr or not?Any advice is welcome!
I have a screenshot like below: 

![image](https://cloud.githubusercontent.com/assets/10580073/5891469/8185fd20-a4d2-11e4-8c71-94103f0bb9a3.png)

**Comment by madeye** [comment]
No, it's not related. Check your TCP related config first.

**Comment by kxmp** [comment]
Increase your tcp_max_orphans to 65536
>sysctl -w tcp_max_orphans=65536
