### ISSUE TITLE
Shadow socks not opening websites but open ip addresses

### ISSUE THREAD

**Issue by amirpiri** [shadowsocks/shadowsocks-libev#2451]
#1543 # What version of shadowsocks-libev are you using?
shadowsocks-libev 3.3.1

### What operating system are you using?
Centos 7

### What did you do?
I install it and my telegram works and also I can access 1.1.1.1 but no websites with domain address can accessed.

### What is your config in detail (with all sensitive info masked)?
{
    "server":"my-server-ip-address",
    "server_port":8488,
    "password":"xxxxxx",
    "timeout":300,
    "method":"aes-256-gcm",
    "fast_open": false,
    "nameserver":"1.1.1.1"
}

**Comment by yku12cn** [comment]
try delete "nameserver":"1.1.1.1"
add -d 1.1.1.1 in command line instead.
As far as I know, shadowsocks-libev doesn't read nameserver from .json file.

**Comment by yku12cn** [comment]
BTW, you need to allow both tcp and udp traffic for port 8488 on your server. If you are an android client, your dns requests may be sent over udp.

**Comment by PantherJohn** [comment]
@amirpiri make sure you have UDP enabled on both the client and the server (add `-u` to enable TCP and UDP). The `nameserver` option in your config file is valid, by the way.
