### ISSUE TITLE
请问如何在Ubuntu中使用PAC文件来规定firefox的代理行为？

### ISSUE THREAD

**Issue by hyf6661669** [shadowsocks/shadowsocks-libev#2452]
### What version of shadowsocks-libev are you using?
shadowsocks-libev 3.1.3

### What operating system are you using?
Ubuntu 18.04.2 LTS, Firefox版本：68.0.1esr (64 位)

### What did you expect to see?
我在用firefox浏览器上网(不想用Chrome，因为没有梯子的情况下无法同步我的账户信息)，我希望能在终端里边开启ss-local之后，firefox能根据我的PAC文件来决定哪些网站不走SS，哪些网站需要走SS。我的PAC文件是直接从windows下的shadowsocks客户端中复制过来的。

![图片](https://user-images.githubusercontent.com/18757974/62824791-4c0f2580-bbd5-11e9-995f-427a0e14ed85.png)
我在firefox中的设置如上图，这样设置的情况下，浏览国内网站也会通过SS，所以速度比较慢。。。
![图片](https://user-images.githubusercontent.com/18757974/62824807-6fd26b80-bbd5-11e9-8239-191ba67bc925.png)

如果我这样设置的话，又不能打开google, youtube之类的了，访问国内网站速度正常，效果跟没开SS一样。

**Comment by hyf6661669** [comment]
最后我用了switchyomega插件就OK了。。。

**Comment by newptcai** [comment]
> 最后我用了switchyomega插件就OK了。。。

能否详细介绍一下？

**Comment by newptcai** [comment]
If you are using shadowsocks-libev as a client on Ubuntu, you can use SwitchyOmega plugin with Firefox/chrome with PAC rules to reduce the traffic of your server.
Here's how -- https://vpnto.net/posts/firefox-shadowsocks/
