### ISSUE TITLE
snap安装ss-server后无法正常启动，需要额外安装core

### ISSUE THREAD

**Issue by Aniark** [shadowsocks/shadowsocks-libev#2456]
# What version of shadowsocks-libev are you using?
3.3.1，安装自snap

### What operating system are you using?
Debian 10

### What did you do?
apt install snapd && snap install shadowsocks-libev --edge

### What did you expect to see?
服务端能够正常运行

### What did you see instead?
服务端无法正常运行，log如下：
 ```
2019-08-16 09:36:09 INFO: enable TCP no-delay
 2019-08-16 09:36:09 INFO: UDP relay enabled
 2019-08-16 09:36:09 INFO: enable TCP no-delay
 2019-08-16 09:36:09 INFO: initializing ciphers... aes-256-gcm
 2019-08-16 09:36:09 INFO: tcp server listening at 0.0.0.0:6
 2019-08-16 09:36:09 INFO: tcp port reuse enabled
 2019-08-16 09:36:09 ERROR: listen(): Operation not permitted
 2019-08-16 09:36:09 ERROR: failed to listen on any address
```

### What is your config in detail (with all sensitive info masked)?
shadowsocks-libev.ss-server -s 0.0.0.0 -p myport -k mypasswd -m aes-256-gcm --reuse-port --no-delay -u

###以下为发现问题&解决问题的过程
`snap install shadowsocks-libev --edge`之后，snap自动安装了core18和shadowsocks-libev，如下：
```
Name               Version   Rev   Tracking  Publisher   Notes
core18             20190723  1074  stable    canonical✓  base
shadowsocks-libev  3.3.1-1   197   edge      max-c-lv    -
```
但是无法正常启动

Google了一圈，发现`snap install core`之后，便可正常启动ss-server，如下：
```
Name               Version   Rev   Tracking  Publisher   Notes
core               16-2.40   7396  stable    canonical✓  core
core18             20190723  1074  stable    canonical✓  base
shadowsocks-libev  3.3.1-1   197   edge      max-c-lv    -
```

我在本项目readme下及snap官方doc下都未见过有此步骤要求，遂发此issue

**Comment by zhangxu3486432** [comment]
same problem

**Comment by willy666rumster** [comment]
is it not solved

**Comment by yoloz** [comment]
helpful

**Comment by yoloz** [comment]
thank you

**Comment by Liang-KS** [comment]
解决啦 ，谢谢
