### ISSUE TITLE
Forward traffic to another proxy 

### ISSUE THREAD

**Issue by JanBoshoff** [shadowsocks/shadowsocks-libev#2459]
### What version of shadowsocks-libev are you using?
3.3.1

### What operating system are you using?
Ubuntu-19.04

I have a working shadowsocks-libev & v2ray plugin setup. Everything is working, no problems.
I currently have this:
```
Client \                        / Requests to public internet
Client - > Shadowsocks Server > - Requests to public internet
Client /                        \ Requests to public internet
```

I wish to expand this setup to forward the requests to another server like below:
```
Client \                                       / Requests to public internet
Client - > Shadowsocks Server > Proxy Server > - Requests to public internet
Client /                                       \ Requests to public internet
```
From issue #1937 it seems this is not supported in shadowsocks itself. How could this then be achieved?

**Comment by PantherJohn** [comment]
@JanBoshoff So do you mean you need to forward all traffic **blindly** to a proxy server? If so, please consider `iptables`.

**Comment by JanBoshoff** [comment]
@PantherJohn I guess blindly. Sorry I'm not very familiar with networking and these things. I imagine you mean that I could just forward outbound (TCP and UDP) traffic on port 80 & 443 to the proxy server right? But this is where I am confused. Shouldn't there be a client or something on the Shadowsocks server to receive the responses from the proxy server to send back to SS and then to the original client? And second, the shadowsocks server has an nginx server that is listening on 443 and doing a proxy pass to shadowsocks, so wouldn't that be a problem?

**Comment by PantherJohn** [comment]
@JanBoshoff okay then. 
> Shouldn't there be a client or something on the Shadowsocks server to receive the responses from the proxy server to send back to SS and then to the original client? 

This is where the thing got complicated, and I'm not going to explain to you in detail how the whole network stuff works. What you need to know is that shadowsocks is a lightweight [SOCKS](https://en.wikipedia.org/wiki/SOCKS)5 proxy. A proxy client is a translator that encodes the request you sent to a certain format, and a proxy server is responsible for translating the encoded (or sometimes encrypted) requests to the normal requests originally sent by you and delivering them to their original destination. 

> the shadowsocks server has an nginx server that is listening on 443 and doing a proxy pass to shadowsocks, so wouldn't that be a problem?

This is absolute possible (but I don't use `nginx`. I've been using `httpd` apache for like 3 years). But I'm still not sure what you want: do you need to distribute the traffic across different servers? What's the point of having a "proxy server" if you already got one?

**Comment by JanBoshoff** [comment]
@PantherJohn Thanks for the explanation. The idea is that I have a server running shadowsocks that is in a region close to my location. This has improved the latency of my connection considerably and the speed a little bit too. The idea was to then forward the traffic to another server that is supposedly directly linked to the data center of the first server and that is based in the US. In my mind this should improve the speed to US based services. But I hit the road block and could not experiment further. 

Does this make sense? Or should I be approaching the situation differently?

**Comment by nxtreaming** [comment]
I think your should change your dialog to:

Client \                                                                                     / Requests to public internet
Client - > Proxy Server(Local)   > Shadowsocks Server(US)   > - Requests to public internet
Client /                                                                                     \ Requests to public internet

And than setup packet forward by iptables in your Proxy Server.

**Comment by davidcava** [comment]
To do that, I install the shadowsocks server on the (final, US of you) target server, and then I set iptables redirections in the intermediate server toward the target server:

Fill in the IPs, replace ens18 with the interface name in the intermediate server and of course the port number with whatever suits you.

sysctl -w net.ipv4.ip_forward=1 #or update /etc/sysctl.conf then do: sysctl -p /etc/sysctl.conf
MYIP=<this intermediate server IP>
iptables -t nat -A PREROUTING -p tcp -i ens18 --dport 1995 -j DNAT --to-destination <target ip>:1995
iptables -t nat -A PREROUTING -p udp -i ens18 --dport 1995 -j DNAT --to-destination <target ip>:1995
iptables -t nat -A POSTROUTING -p tcp -o ens18 -d <target ip> --dport 1995 -j SNAT --to-source=$MYIP
iptables -t nat -A POSTROUTING -p udp -o ens18 -d <target ip> --dport 1995 -j SNAT --to-source=$MYIP

**Comment by JanBoshoff** [comment]
@nxtreaming and @davidcava thank you very much for the tips and suggestions. I appreciate it. I'll look into doing it this way over the next week. Thanks again for the information!

**Comment by kmahsi** [comment]
@davidcava 


> To do that, I install the shadowsocks server on the (final, US of you) target server, and then I set iptables redirections in the intermediate server toward the target server:
> 
> Fill in the IPs, replace ens18 with the interface name in the intermediate server and of course the port number with whatever suits you.
> 
> sysctl -w net.ipv4.ip_forward=1 #or update /etc/sysctl.conf then do: sysctl -p /etc/sysctl.conf
> MYIP=_this intermediate server IP_
> iptables -t nat -A PREROUTING -p tcp -i ens18 --dport 1995 -j DNAT --to-destination _target ip_:1995
> iptables -t nat -A PREROUTING -p udp -i ens18 --dport 1995 -j DNAT --to-destination _target ip_:1995
> iptables -t nat -A POSTROUTING -p tcp -o ens18 -d _target ip_ --dport 1995 -j SNAT --to-source=$MYIP
> iptables -t nat -A POSTROUTING -p udp -o ens18 -d _target ip_ --dport 1995 -j SNAT --to-source=$MYIP

Thanks for your explanation. My question is what about the authentication process on Proxy Server?
How should I put a password for the connections to the proxy server?
In other words, I don't get how I should set up connection to proxy server which redirects traffics to US server. For example, in shadow socks, you can setup a config file which accepts any connection on specific port and password but I don't know how to do this whit IP tables

**Comment by davidcava** [comment]
With this setup anything tcp and udp that is sent to the intermediate
server on port 1995 is blindly forwarded to the final server same port. So
you just need to point your ss client to the intermediate server instead of
the final server without any other change.

David

**Comment by kmahsi** [comment]
@davidcava 
So what if I want to add an authentication process on the intermediate server?
I think it's very insecure and illogical that I allow anyone to call the port 1995 of my server and use it as a proxy server. I really want to add an authentication process that limits the connections to the intermediate server.

**Comment by davidcava** [comment]
The unauthorized traffic will be rejected by the target server, same as if
the target server were called directly . That has never been a problem for
me.

If you want to stop the traffic in the intermediate server then you need to
have the ss-server running there. Then you can use iptables OUTPUT chain
with -m owner --uid-owner <ss-owner-id> to redirect the traffic from
ss-server to somewhere else.

David

**Comment by JanBoshoff** [comment]
Btw if anyone needs to do something similar, I ended up getting this sorted out without using IP tables. On the intermediate server I forward the traffic on to the SS server using socat (and redir also works).

`sudo socat -dd TCP4-LISTEN:8000,fork TCP4:Shadowsocks-server-ip:9000`
`sudo socat -dd UDP-LISTEN:8000,fork UDP:Shadowsocks-server-ip:9000`

You can use screen on the intermediate server to run these in the background.

**Comment by davidcava** [comment]
Yes I was using that too before iptables. Did not work that well to me with
udp - got some memory/thread issues after some time. So I switched to using
plain iptables and that was the successful option for me.

Le dim. 12 janv. 2020 à 11:07, Jan Boshoff <notifications@github.com> a
écrit :

**Comment by HengyueLi** [comment]
Hi @JanBoshoff, I have the same demand. I notice that you finally give a solution. I am not an expert on the network so I did not follow the last several comments. I have a question. Have you changed the structure of your original issue? I mean, is your final solution is suitable for  `->Shadowsocks Server > Proxy Server ->` or `> Proxy Server  -> Shadowsocks Server ->`?

**Comment by JanBoshoff** [comment]
Hi @HengyueLi. The final solution is to have the "proxy server" before the shadowsocks server ('> Proxy Server -> Shadowsocks Server ->') as nxtreaming suggested. I used the socat package to achieve this and not iptables, although I have noticed that it needs to be restarted from time to time. davidcava suggested that iptables was more successful, so I'm considering changing my setup in the future to use iptables too.

**Comment by HengyueLi** [comment]
> Hi @HengyueLi. The final solution is to have the "proxy server" before the shadowsocks server ('> Proxy Server -> Shadowsocks Server ->') as nxtreaming suggested. I used the socat package to achieve this and not iptables, although I have noticed that it needs to be restarted from time to time. davidcava suggested that iptables was more successful, so I'm considering changing my setup in the future to use iptables too.

I see. However, I am still curious about your original issue. It would be nice if someone gives a perfect answer to that.

**Comment by JanBoshoff** [comment]
@davidcava I had a quick go at setting up iptables as you described. I followed your rules from above and my iptables `iptables -t nat -L -v -n` output is as follow: 

SS Server: 1.1.1.1:1234
Intermediate Server: 2.2.2.2:1234   
(Both servers use the same port) - And the ports are open on both servers.

```
Chain PREROUTING (policy ACCEPT 2 packets, 120 bytes)
 pkts bytes target     prot opt in     out     source               destination         
  128  7680 DNAT       tcp  --  eth0   *       0.0.0.0/0            0.0.0.0/0            tcp dpt:1234 to:1.1.1.1:1234
    0     0 DNAT       udp  --  eth0   *       0.0.0.0/0            0.0.0.0/0            udp dpt:1234 to:1.1.1.1:1234

Chain INPUT (policy ACCEPT 2 packets, 120 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 10 packets, 1065 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain POSTROUTING (policy ACCEPT 10 packets, 1065 bytes)
 pkts bytes target     prot opt in     out     source               destination         
  128  7680 SNAT       tcp  --  *      eth0    0.0.0.0/0            1.1.1.1       tcp dpt:1234 to:2.2.2.2
    0     0 SNAT       udp  --  *      eth0    0.0.0.0/0            1.1.1.1       udp dpt:1234 to:2.2.2.2
```

This does not seem to work though, as when I try to browse to a site, it fails to connect. Is there more to this or is something setup incorrectly?

**Comment by davidcava** [comment]
Have you activated the routing on the intermediate server?

  sysctl -w net.ipv4.ip_forward=1

Le jeu. 30 janv. 2020 à 16:45, Jan Boshoff <notifications@github.com> a
écrit :

**Comment by JanBoshoff** [comment]
Yes, I have done that. Then added the iptables rules.

**Comment by davidcava** [comment]
Ok no sorry I see nothing wrong there


Le ven. 31 janv. 2020 à 06:48, Jan Boshoff <notifications@github.com> a
écrit :

**Comment by PantherJohn** [comment]
@JanBoshoff Elaborate on "it fails to connect."

**Comment by JanBoshoff** [comment]
@PantherJohn I haven't tried this in a while, so I don't remember the exact problems. I think the android shadowsocks client may have shown an error stating that it failed to connect to the internet and I think I was unable to visit any site through shadowsocks-libev on the laptop. The only change was how the intermediate server forwards the traffic to the shadowsocks server. Using redir and socat worked, but I was not able to get it to work with iptables yet.

**Comment by rampageX** [comment]
`udp` with `iptables` need `TPROXY`  mod, and it is not simple rules like `tcp`, check:

> https://github.com/zfl9/ss-tproxy/blob/master/ss-tproxy

or use `glider`  (https://github.com/nadoo/glider)

**Comment by PantherJohn** [comment]
@rampageX Sorry but that's not true. `tproxy` should only be used for transparent proxies.

**Comment by JanBoshoff** [comment]
Thanks @PantherJohn for the info. I'll have a look at it when I get time. Sorry for the slow responses, I am a bit busy now. But I'll get around to it sometime over the next couple of days probably.

**Comment by JReming85** [comment]
I would be interested in this as well.

My use case is, I have setup 3 rotating proxy servers all without auth.
localip:8000 -> 5000 residential USA proxies
localip:8001 -> 5000 residential UK proxies
localip:8003 -> 2Million residential worldwide proxies 

It works great for my local personal use, but I have been thinking of expanding my store and offering it for SEO/Data Scraping/etc and need a easy way to sell access that integrates with my current WHMCS setup.

example:
client1 buys 5 threads/concurrent connections and it forwards all connections from <publicip>:10000/1/2 to <localip>8000/1/2
Same with client2/3/4/5/etc

SS already has a WHMCS plugin so was looking into if it can do something like this easily
