### ISSUE TITLE
Please provide a clear document after the update of installation source

### ISSUE THREAD

**Issue by panbofeng** [shadowsocks/shadowsocks-libev#2460]
Firstly, thanks for the hard working to this project.

But, after you remove PPA from a choice of installation, I cannot install the ss-server normally because I am confused with the new snap management as a Linux beginner.

After I successfully installed shadowsocks-libev from snap, it seemed that the config.json was no longer in the directory /etc/shadowsocks-libev/config.json and another question is how can I run the shadowsocks-libev from snap since the sudo /etc/init.d/shadowsocks-libev start doesn't work.

I'm very appreciate if there is any reply. Thank you so much.

**Comment by Aniark** [comment]
解答问题1：config.json需要放在~目录下或/snap/bin目录下，例~/config.json或/snap/bin/config.json
解答问题2：使用命令shadowsocks-libev.ss-server启动服务端

**Comment by iDesperad0** [comment]
> 解答问题1：config.json需要放在 ~目录下或/snap/bin目录下，例 ~/config.json或/snap/bin/config.json
> 解答问题2：使用命令shadowsocks-libev.ss-server启动服务端

总结：snap真难用，systemd不好吗。

**Comment by Paddy888** [comment]
An updated configuration and installation instructions in English would be very welcome. I used to be able to install and get shadowsocks-libev running in a few minutes. Now for more than an hour I have been struggling to even find the config.json file.

**Comment by jearton** [comment]
> 解答问题1：config.json需要放在 ~目录下或/snap/bin目录下，例 ~/config.json或/snap/bin/config.json
> 解答问题2：使用命令shadowsocks-libev.ss-server启动服务端

这样改的话，和systemctl有什么区别，我想用snap start的命令启动
