### ISSUE TITLE
please support 'none' encrypt method for TLS based v2ray plugin use case

### ISSUE THREAD

**Issue by moralrebuild** [shadowsocks/shadowsocks-libev#2466]
As we all know V2ray is notorious for its performance. Furthermore V2ray plugin's already use the industry best  TLS mechanism to encrypt its websocket traffic, spending critical cpu and ram resource of most entry level or mid level routers on another layer of encryption is nonsense.

**Comment by madeye** [comment]
The cipher in shadowsocks is required, as it's also used for authentication.

**Comment by Sadrak** [comment]
Both the go and rust implementation have a dummy cipher (without encryption).
