### ISSUE TITLE
Command line arguments vs. config options

### ISSUE THREAD

**Issue by xnoreq** [shadowsocks/shadowsocks-libev#247]
Except for `-c <config_file>` can we have all command line arguments configurable in the config file?
For example,  I'd like to specify in the config: `"local_address":"127.0.0.1"`

Also, can the options be unified?
For example the command line option says `-s <server_host>`, but in the config file it is not `"server_host":"..."` but just `"server":"..."`.
I would think that "server" is not just the host name but a host:port combination.

**Comment by madeye** [comment]
1. Use local instead of local_address.it just works.
2. You can specify host:port in server section.
