### ISSUE TITLE
Autoban problem

### ISSUE THREAD

**Issue by rvalitov** [shadowsocks/shadowsocks-libev#2470]
### What version of shadowsocks-libev are you using?
3.2.5

### What operating system are you using?
Debian GNU/Linux 9.11 (stretch)

### What did you do?
I wanted to configure fail2ban to catch Shadowsocks authentication errors as described [here](http://blog.zedyeung.com/2018/08/14/Ubuntu-18-04-set-up-Shadowsocks-server-with-fail2ban/#Shadowsocks-libev-1). So, first I wanted to see what info Shadowsocks will print into syslog. I changed the password on client to wrong and saw the following errors:

```
/usr/bin/ss-server[14684]: failed to handshake with [IP]: authentication error
```

After that I saw:
```
/usr/bin/ss-server[14684]: block all requests from [IP]
```

After that I changed the password back to correct, but the client still has been blocked. Only restart of ss-server could solve the problem.

So, is it autoban? If yes, then does it have any timeout to automatic unban? Is it possible to configure or disable the ban mechanism?

I think that using specialized tools for ban control such as fail2ban is the best approach. Please, can you share your ideas how I can use it instead of the autoban? The main question is how to disable the autoban in this case in order to make fail2ban to work?

**Comment by HankAviator** [comment]
> So, is it autoban? 
Yes

> If yes, then does it have any timeout to automatic unban? 
No, it's permanent till you restart shadowsocks-libev

> Is it possible to configure or disable the ban mechanism?
It's possible to add IPs to ACL file's `[white_list]` section to whitelist them.

**Comment by madeye** [comment]
Autoban is removed in the latest version.

Update to v3.3.1 and try again.
