### ISSUE TITLE
Syslog daemon.log files become too large

### ISSUE THREAD

**Issue by rvalitov** [shadowsocks/shadowsocks-libev#2471]
### What version of shadowsocks-libev are you using?
3.2.5

### What operating system are you using?
Debian GNU/Linux 9.11 (stretch)

### What did you do?
My server became slow... and I found out it was out of disk space)) The syslog and daemon.log files are full of messages like below:
```
/usr/bin/ss-server[14684]: getpeername: Transport endpoint is not connected
```

I have dozens of lines of such messages every second. I tested the ss-server with -v option as suggested in other issues and it's true that this error means that the destination point is not reachable from the server. However, it seems that the client's software (in my case it was qBittorrent) is stupid and tries to connect to a server that is not responding multiple times per second. I suspect that there may exist other software with a similar stupid logic. But the problem is that such kind of software heavily increases the size of the log files on the server. In my case it was dozens of Gb, that's too much for my little VPS. Even a daily logrotate was not fast enough to clean it.

It would be great if shadowsocks would have any mechanism to control the log verbosity or ability to define a log file to use instead of syslog and deamon.log. These 2 options would help a lot to avoid such issues.

**Comment by madeye** [comment]
First try https://askubuntu.com/questions/184949/how-do-i-limit-the-size-of-my-syslog

If you want to control the log of shadowsocks separately, try `systemd` or `supervisord`. Here `supervisord` is recommended.
