### ISSUE TITLE
gpg error

### ISSUE THREAD

**Issue by malikshi** [shadowsocks/shadowsocks-libev#2472]
### What version of shadowsocks-libev are you using?
idk because failed to install

### What operating system are you using?
ubuntu 16.04 openvz

### What did you do?
failing to install shadowsocks-libev

### What did you expect to see?
no error
### What did you see instead?
`W: GPG error: http://ppa.launchpad.net/max-c-lv/shadowsocks-libev/ubuntu xenial InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY D5059C1FFCB15481
W: The repository 'http://ppa.launchpad.net/max-c-lv/shadowsocks-libev/ubuntu xenial InRelease' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.`

**Comment by madeye** [comment]
Try snap instead
