### ISSUE TITLE
Windows (MinGW) Installation failed with no docker image found or pulled

### ISSUE THREAD

**Issue by hexindent** [shadowsocks/shadowsocks-libev#2473]
### What version of shadowsocks-libev are you using?
3.3.1

### What operating system are you using?
Windows 7 x64 SP1

### What did you do?
run make.bat

### What did you expect to see?
compilation complete

### What did you see instead?
Sending build context to Docker daemon  14.85kB
Step 1/13 : FROM debian:testing
 ---> 09b4e47319f1
Step 2/13 : ARG REPO=shadowsocks
 ---> Using cache
 ---> c42ac0f9336f
Step 3/13 : ARG REV=master
 ---> Using cache
 ---> 62f80acf0ca3
Step 4/13 : ADD docker/mingw/prepare.sh /
ADD failed: stat /mnt/sda1/var/lib/docker/tmp/docker-builder790287159/docker/mingw/prepare.sh: no such file or directory
Unable to find image 'ss-build-mingw:latest' locally
docker: Error response from daemon: pull access denied for ss-build-mingw, repository does not exist or may require 'docker login'.
See 'docker run --help'.
Press any key to continue . . .

### What is your config in detail (with all sensitive info masked)?
Docker Toolbox v19.03.1

**Comment by stfzy** [comment]
have you resolve the problem ?

**Comment by hexindent** [comment]
> have you resolve the problem ?

No, I stopped using the Windows server and got ss running on an Ubuntu desktop.
