### ISSUE TITLE
cant compile on realtek_openwrt

### ISSUE THREAD

**Issue by wttat** [shadowsocks/shadowsocks-libev#2474]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?

the lastest just download 3.3.1
### What operating system are you using?
ubuntu 18.04

### What did you do?
compile the openwrt realtek sdk based on openwrt 14.07 linux kernel is v3.10.49 for realtek mipsel soc

### What did you expect to see?
comile the shadowsocks-libev into it

### What did you see instead?

the mbedtls module went wrong
### What is your config in detail (with all sensitive info masked)?

**make menuconfig**
![image](https://user-images.githubusercontent.com/29791466/65042575-b319ba00-d98b-11e9-93ee-603dfc955d06.png)

**make V=s**
make[3]: Leaving directory '/home/wt/Desktop/rtk_openwrt_sdk/package/base-files'
make[3]: Entering directory '/home/wt/Desktop/rtk_openwrt_sdk/package/feeds/base/mbedtls'
(cd /home/wt/Desktop/rtk_openwrt_sdk/build_dir/target-mipsel_24kec_uClibc-0.9.33.2/mbedtls-2.16.2; CFLAGS="-pipe -mno-branch-likely -mips32r2 -mtune=24kec -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -msoft-float -ffunction-sections -fdata-sections " CXXFLAGS="-pipe -mno-branch-likely -mips32r2 -mtune=24kec -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -msoft-float -ffunction-sections -fdata-sections " LDFLAGS="-L/home/wt/Desktop/rtk_openwrt_sdk/staging_dir/target-mipsel_24kec_uClibc-0.9.33.2/usr/lib -L/home/wt/Desktop/rtk_openwrt_sdk/staging_dir/target-mipsel_24kec_uClibc-0.9.33.2/lib -L/home/wt/Desktop/rtk_openwrt_sdk/staging_dir/toolchain-mipsel_24kec_gcc-4.8-linaro_uClibc-0.9.33.2/usr/lib -L/home/wt/Desktop/rtk_openwrt_sdk/staging_dir/toolchain-mipsel_24kec_gcc-4.8-linaro_uClibc-0.9.33.2/lib " cmake -DCMAKE_SYSTEM_NAME=Linux -DCMAKE_SYSTEM_VERSION=1 -DCMAKE_SYSTEM_PROCESSOR=mipsel -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_FLAGS_RELEASE="-DNDEBUG" -DCMAKE_CXX_FLAGS_RELEASE="-DNDEBUG" -DCMAKE_C_COMPILER="/home/wt/Desktop/rtk_openwrt_sdk/staging_dir/toolchain-mipsel_24kec_gcc-4.8-linaro_uClibc-0.9.33.2/bin/mipsel-openwrt-linux-uclibc-gcc" -DCMAKE_C_COMPILER_ARG1="" -DCMAKE_CXX_COMPILER="/home/wt/Desktop/rtk_openwrt_sdk/staging_dir/toolchain-mipsel_24kec_gcc-4.8-linaro_uClibc-0.9.33.2/bin/mipsel-openwrt-linux-uclibc-g++" -DCMAKE_CXX_COMPILER_ARG1="" -DCMAKE_EXE_LINKER_FLAGS:STRING="-L/home/wt/Desktop/rtk_openwrt_sdk/staging_dir/target-mipsel_24kec_uClibc-0.9.33.2/usr/lib -L/home/wt/Desktop/rtk_openwrt_sdk/staging_dir/target-mipsel_24kec_uClibc-0.9.33.2/lib -L/home/wt/Desktop/rtk_openwrt_sdk/staging_dir/toolchain-mipsel_24kec_gcc-4.8-linaro_uClibc-0.9.33.2/usr/lib -L/home/wt/Desktop/rtk_openwrt_sdk/staging_dir/toolchain-mipsel_24kec_gcc-4.8-linaro_uClibc-0.9.33.2/lib" -DCMAKE_MODULE_LINKER_FLAGS:STRING="-L/home/wt/Desktop/rtk_openwrt_sdk/staging_dir/target-mipsel_24kec_uClibc-0.9.33.2/usr/lib -L/home/wt/Desktop/rtk_openwrt_sdk/staging_dir/target-mipsel_24kec_uClibc-0.9.33.2/lib -L/home/wt/Desktop/rtk_openwrt_sdk/staging_dir/toolchain-mipsel_24kec_gcc-4.8-linaro_uClibc-0.9.33.2/usr/lib -L/home/wt/Desktop/rtk_openwrt_sdk/staging_dir/toolchain-mipsel_24kec_gcc-4.8-linaro_uClibc-0.9.33.2/lib" -DCMAKE_SHARED_LINKER_FLAGS:STRING="-L/home/wt/Desktop/rtk_openwrt_sdk/staging_dir/target-mipsel_24kec_uClibc-0.9.33.2/usr/lib -L/home/wt/Desktop/rtk_openwrt_sdk/staging_dir/target-mipsel_24kec_uClibc-0.9.33.2/lib -L/home/wt/Desktop/rtk_openwrt_sdk/staging_dir/toolchain-mipsel_24kec_gcc-4.8-linaro_uClibc-0.9.33.2/usr/lib -L/home/wt/Desktop/rtk_openwrt_sdk/staging_dir/toolchain-mipsel_24kec_gcc-4.8-linaro_uClibc-0.9.33.2/lib" -DCMAKE_AR="/home/wt/Desktop/rtk_openwrt_sdk/staging_dir/toolchain-mipsel_24kec_gcc-4.8-linaro_uClibc-0.9.33.2/bin/mipsel-openwrt-linux-uclibc-ar" -DCMAKE_RANLIB="/home/wt/Desktop/rtk_openwrt_sdk/staging_dir/toolchain-mipsel_24kec_gcc-4.8-linaro_uClibc-0.9.33.2/bin/mipsel-openwrt-linux-uclibc-ranlib" -DCMAKE_FIND_ROOT_PATH="/home/wt/Desktop/rtk_openwrt_sdk/staging_dir/target-mipsel_24kec_uClibc-0.9.33.2;/home/wt/Desktop/rtk_openwrt_sdk/staging_dir/toolchain-mipsel_24kec_gcc-4.8-linaro_uClibc-0.9.33.2" -DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM=BOTH -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY -DCMAKE_STRIP=: -DCMAKE_INSTALL_PREFIX=/usr -DDL_LIBRARY=/home/wt/Desktop/rtk_openwrt_sdk/staging_dir/target-mipsel_24kec_uClibc-0.9.33.2 -DCMAKE_PREFIX_PATH=/home/wt/Desktop/rtk_openwrt_sdk/staging_dir/target-mipsel_24kec_uClibc-0.9.33.2 -DUSE_SHARED_MBEDTLS_LIBRARY:Bool=ON -DENABLE_TESTING:Bool=OFF -DENABLE_PROGRAMS:Bool=ON . )
CMake Error at programs/ssl/CMakeLists.txt:37 (target_sources):
  Unknown CMake command "target_sources".

-- Configuring incomplete, errors occurred!
See also "/home/wt/Desktop/rtk_openwrt_sdk/build_dir/target-mipsel_24kec_uClibc-0.9.33.2/mbedtls-2.16.2/CMakeFiles/CMakeOutput.log".
See also "/home/wt/Desktop/rtk_openwrt_sdk/build_dir/target-mipsel_24kec_uClibc-0.9.33.2/mbedtls-2.16.2/CMakeFiles/CMakeError.log".
Makefile:120: recipe for target '/home/wt/Desktop/rtk_openwrt_sdk/build_dir/target-mipsel_24kec_uClibc-0.9.33.2/mbedtls-2.16.2/.configured_n' failed
make[3]: *** [/home/wt/Desktop/rtk_openwrt_sdk/build_dir/target-mipsel_24kec_uClibc-0.9.33.2/mbedtls-2.16.2/.configured_n] Error 1
make[3]: Leaving directory '/home/wt/Desktop/rtk_openwrt_sdk/package/feeds/base/mbedtls'
package/Makefile:173: recipe for target 'package/feeds/base/mbedtls/compile' failed
make[2]: *** [package/feeds/base/mbedtls/compile] Error 2
make[2]: Leaving directory '/home/wt/Desktop/rtk_openwrt_sdk'
package/Makefile:170: recipe for target '/home/wt/Desktop/rtk_openwrt_sdk/staging_dir/target-mipsel_24kec_uClibc-0.9.33.2/stamp/.package_compile' failed
make[1]: *** [/home/wt/Desktop/rtk_openwrt_sdk/staging_dir/target-mipsel_24kec_uClibc-0.9.33.2/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/wt/Desktop/rtk_openwrt_sdk'
/home/wt/Desktop/rtk_openwrt_sdk/include/toplevel.mk:171: recipe for target 'world' failed
make: *** [world] Error 2

**but while i only run the sh in a new window it works**
the comand:
cd /home/wt/Desktop/rtk_openwrt_sdk/build_dir/target-mipsel_24kec_uClibc-0.9.33.2/mbedtls-2.16.2; CFLAGS="-pipe -mno-branch-likely -mips32r2 -mtune=24kec -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -msoft-float -ffunction-sections -fdata-sections " CXXFLAGS="-pipe -mno-branch-likely -mips32r2 -mtune=24kec -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -msoft-float -ffunction-sections -fdata-sections " LDFLAGS="-L/home/wt/Desktop/rtk_openwrt_sdk/staging_dir/target-mipsel_24kec_uClibc-0.9.33.2/usr/lib -L/home/wt/Desktop/rtk_openwrt_sdk/staging_dir/target-mipsel_24kec_uClibc-0.9.33.2/lib -L/home/wt/Desktop/rtk_openwrt_sdk/staging_dir/toolchain-mipsel_24kec_gcc-4.8-linaro_uClibc-0.9.33.2/usr/lib -L/home/wt/Desktop/rtk_openwrt_sdk/staging_dir/toolchain-mipsel_24kec_gcc-4.8-linaro_uClibc-0.9.33.2/lib " cmake -DCMAKE_SYSTEM_NAME=Linux -DCMAKE_SYSTEM_VERSION=1 -DCMAKE_SYSTEM_PROCESSOR=mipsel -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_FLAGS_RELEASE="-DNDEBUG" -DCMAKE_CXX_FLAGS_RELEASE="-DNDEBUG" -DCMAKE_C_COMPILER="/home/wt/Desktop/rtk_openwrt_sdk/staging_dir/toolchain-mipsel_24kec_gcc-4.8-linaro_uClibc-0.9.33.2/bin/mipsel-openwrt-linux-uclibc-gcc" -DCMAKE_C_COMPILER_ARG1="" -DCMAKE_CXX_COMPILER="/home/wt/Desktop/rtk_openwrt_sdk/staging_dir/toolchain-mipsel_24kec_gcc-4.8-linaro_uClibc-0.9.33.2/bin/mipsel-openwrt-linux-uclibc-g++" -DCMAKE_CXX_COMPILER_ARG1="" -DCMAKE_EXE_LINKER_FLAGS:STRING="-L/home/wt/Desktop/rtk_openwrt_sdk/staging_dir/target-mipsel_24kec_uClibc-0.9.33.2/usr/lib -L/home/wt/Desktop/rtk_openwrt_sdk/staging_dir/target-mipsel_24kec_uClibc-0.9.33.2/lib -L/home/wt/Desktop/rtk_openwrt_sdk/staging_dir/toolchain-mipsel_24kec_gcc-4.8-linaro_uClibc-0.9.33.2/usr/lib -L/home/wt/Desktop/rtk_openwrt_sdk/staging_dir/toolchain-mipsel_24kec_gcc-4.8-linaro_uClibc-0.9.33.2/lib" -DCMAKE_MODULE_LINKER_FLAGS:STRING="-L/home/wt/Desktop/rtk_openwrt_sdk/staging_dir/target-mipsel_24kec_uClibc-0.9.33.2/usr/lib -L/home/wt/Desktop/rtk_openwrt_sdk/staging_dir/target-mipsel_24kec_uClibc-0.9.33.2/lib -L/home/wt/Desktop/rtk_openwrt_sdk/staging_dir/toolchain-mipsel_24kec_gcc-4.8-linaro_uClibc-0.9.33.2/usr/lib -L/home/wt/Desktop/rtk_openwrt_sdk/staging_dir/toolchain-mipsel_24kec_gcc-4.8-linaro_uClibc-0.9.33.2/lib" -DCMAKE_SHARED_LINKER_FLAGS:STRING="-L/home/wt/Desktop/rtk_openwrt_sdk/staging_dir/target-mipsel_24kec_uClibc-0.9.33.2/usr/lib -L/home/wt/Desktop/rtk_openwrt_sdk/staging_dir/target-mipsel_24kec_uClibc-0.9.33.2/lib -L/home/wt/Desktop/rtk_openwrt_sdk/staging_dir/toolchain-mipsel_24kec_gcc-4.8-linaro_uClibc-0.9.33.2/usr/lib -L/home/wt/Desktop/rtk_openwrt_sdk/staging_dir/toolchain-mipsel_24kec_gcc-4.8-linaro_uClibc-0.9.33.2/lib" -DCMAKE_AR="/home/wt/Desktop/rtk_openwrt_sdk/staging_dir/toolchain-mipsel_24kec_gcc-4.8-linaro_uClibc-0.9.33.2/bin/mipsel-openwrt-linux-uclibc-ar" -DCMAKE_RANLIB="/home/wt/Desktop/rtk_openwrt_sdk/staging_dir/toolchain-mipsel_24kec_gcc-4.8-linaro_uClibc-0.9.33.2/bin/mipsel-openwrt-linux-uclibc-ranlib" -DCMAKE_FIND_ROOT_PATH="/home/wt/Desktop/rtk_openwrt_sdk/staging_dir/target-mipsel_24kec_uClibc-0.9.33.2;/home/wt/Desktop/rtk_openwrt_sdk/staging_dir/toolchain-mipsel_24kec_gcc-4.8-linaro_uClibc-0.9.33.2" -DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM=BOTH -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY -DCMAKE_STRIP=: -DCMAKE_INSTALL_PREFIX=/usr -DDL_LIBRARY=/home/wt/Desktop/rtk_openwrt_sdk/staging_dir/target-mipsel_24kec_uClibc-0.9.33.2 -DCMAKE_PREFIX_PATH=/home/wt/Desktop/rtk_openwrt_sdk/staging_dir/target-mipsel_24kec_uClibc-0.9.33.2 -DUSE_SHARED_MBEDTLS_LIBRARY:Bool=ON -DENABLE_TESTING:Bool=OFF -DENABLE_PROGRAMS:Bool=ON

![image](https://user-images.githubusercontent.com/29791466/65042695-f542fb80-d98b-11e9-85d2-dc94c6a884f5.png)
really confused me 

**this is the CMakeError file :**
/usr/bin/make -f CMakeFiles/cmTryCompileExec2184826640.dir/build.make CMakeFiles/cmTryCompileExec2184826640.dir/build
make[5]: Entering directory '/home/wt/Desktop/rtk_openwrt_sdk/build_dir/target-mipsel_24kec_uClibc-0.9.33.2/mbedtls-2.16.2/CMakeFiles/CMakeTmp'
/home/wt/Desktop/rtk_openwrt_sdk/staging_dir/host/bin/cmake -E cmake_progress_report /home/wt/Desktop/rtk_openwrt_sdk/build_dir/target-mipsel_24kec_uClibc-0.9.33.2/mbedtls-2.16.2/CMakeFiles/CMakeTmp/CMakeFiles 1
Building C object CMakeFiles/cmTryCompileExec2184826640.dir/CheckFunctionExists.c.o
/home/wt/Desktop/rtk_openwrt_sdk/staging_dir/toolchain-mipsel_24kec_gcc-4.8-linaro_uClibc-0.9.33.2/bin/mipsel-openwrt-linux-uclibc-gcc   -pipe -mno-branch-likely -mips32r2 -mtune=24kec -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -msoft-float -ffunction-sections -fdata-sections   -Wall -Wextra -W -Wdeclaration-after-statement -Wwrite-strings -Wlogical-op -Wshadow -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTryCompileExec2184826640.dir/CheckFunctionExists.c.o   -c /home/wt/Desktop/rtk_openwrt_sdk/staging_dir/host/share/cmake-2.8/Modules/CheckFunctionExists.c
Linking C executable cmTryCompileExec2184826640
/home/wt/Desktop/rtk_openwrt_sdk/staging_dir/host/bin/cmake -E cmake_link_script CMakeFiles/cmTryCompileExec2184826640.dir/link.txt --verbose=1
/home/wt/Desktop/rtk_openwrt_sdk/staging_dir/toolchain-mipsel_24kec_gcc-4.8-linaro_uClibc-0.9.33.2/bin/mipsel-openwrt-linux-uclibc-gcc  -pipe -mno-branch-likely -mips32r2 -mtune=24kec -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -msoft-float -ffunction-sections -fdata-sections   -Wall -Wextra -W -Wdeclaration-after-statement -Wwrite-strings -Wlogical-op -Wshadow -DCHECK_FUNCTION_EXISTS=pthread_create   -L/home/wt/Desktop/rtk_openwrt_sdk/staging_dir/target-mipsel_24kec_uClibc-0.9.33.2/usr/lib -L/home/wt/Desktop/rtk_openwrt_sdk/staging_dir/target-mipsel_24kec_uClibc-0.9.33.2/lib -L/home/wt/Desktop/rtk_openwrt_sdk/staging_dir/toolchain-mipsel_24kec_gcc-4.8-linaro_uClibc-0.9.33.2/usr/lib -L/home/wt/Desktop/rtk_openwrt_sdk/staging_dir/toolchain-mipsel_24kec_gcc-4.8-linaro_uClibc-0.9.33.2/lib  CMakeFiles/cmTryCompileExec2184826640.dir/CheckFunctionExists.c.o  -o cmTryCompileExec2184826640 -rdynamic -lpthreads
/home/wt/Desktop/rtk_openwrt_sdk/staging_dir/toolchain-mipsel_24kec_gcc-4.8-linaro_uClibc-0.9.33.2/lib/gcc/mipsel-openwrt-linux-uclibc/4.8.3/../../../../mipsel-openwrt-linux-uclibc/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
CMakeFiles/cmTryCompileExec2184826640.dir/build.make:91: recipe for target 'cmTryCompileExec2184826640' failed
make[5]: Leaving directory '/home/wt/Desktop/rtk_openwrt_sdk/build_dir/target-mipsel_24kec_uClibc-0.9.33.2/mbedtls-2.16.2/CMakeFiles/CMakeTmp'
make[5]: *** [cmTryCompileExec2184826640] Error 1
Makefile:117: recipe for target 'cmTryCompileExec2184826640/fast' failed
make[4]: Leaving directory '/home/wt/Desktop/rtk_openwrt_sdk/build_dir/target-mipsel_24kec_uClibc-0.9.33.2/mbedtls-2.16.2/CMakeFiles/CMakeTmp'
make[4]: *** [cmTryCompileExec2184826640/fast] Error 2

**Comment by wttat** [comment]
the mbedtls version is 2.16.2

**Comment by DavHau** [comment]
Having the exact same problem here while trying to build some fork of OpenWrt. Any idea on how to solve this? I don't have a good understanding of the build pipeline.

**Comment by wttat** [comment]
try ss 3.2.3 with mbedtls 2.13.0 instead. it worked for me and i have no idea why

**Comment by wttat** [comment]
> Having the exact same problem here while trying to build some fork of OpenWrt. Any idea on how to solve this? I don't have a good understanding of the build pipeline.

dont use the latest one .
read my comment

**Comment by 0neday** [comment]
@wttat, nice answer! I use ./scripts/feeds uninstall mbedtls, and recompile it use [2.13.0](https://github.com/shadowsocks/openwrt-feeds/tree/80d36a1035e77a92d9e27c946ac6ad935b7aefec/base/mbedtls/), use 
make package/mbedtls/compile
makepackage/mbedtls/install

**Comment by 0neday** [comment]
or upgrade cmake version using [Reference] (https://blog.csdn.net/qq_22237829/article/details/74174322) here
