### ISSUE TITLE
stat_sendto: No such file or directory

### ISSUE THREAD

**Issue by jiaokang** [shadowsocks/shadowsocks-libev#2477]
# What version of shadowsocks-libev are you using?
3.3.1

### What operating system are you using?
centos-7

### What did you do?
from 3.2.5 update to 3.3.1

### What did you expect to see?
work fine.

### What did you see instead?
after start , I see many Error:
```
ss-manager[3550]: 2019-09-19 12:56:22 ERROR: stat_sendto: No such file or directory
```

### What is your config in detail (with all sensitive info masked)?
{
    "server":"0.0.0.0",
    "port_password":{
        "****":"*****"
    },
    "method":"****",
    "fast_open":false,
    "mode":"tcp_and_udp"
}

**Comment by jiaokang** [comment]
In verbose mode, every error comes after a traffic update:
```
2019-09-19 13:09:48 INFO: update traffic 14604 for port 8002
2019-09-19 13:09:48 ERROR: stat_sendto: No such file or directory

```
And these message appear once every five seconds.

**Comment by jiaokang** [comment]
I start server with common user. And special manager socket with user home.
```
/usr/local/bin/ss-manager --manager-address ~/shadowsocks-manager.sock --executable /usr/local/bin/ss-server -c /etc/ssmanger/manager-config.json

```
Start log show that wok directory has successfully point to user home.
I insert some log in code where print error above .And seems that  error occur because socket ```/tmp/shadowsocks-10012``` not create.

**Comment by medev0** [comment]
Hello, I am also experiencing the same problem with ss-manager 3.3.1: 
(ss-manager 3.2.5 is running properly on another machine)

**VER:**	shadowsocks-libev 3.3.1

**OS:**	Debian 10 (buster)

**SOURCE:**	compiled using "build_deb.sh" script


**COMAND:**  

 $ ss-manager -v --manager-address ~/manager.sock -c /etc/shadowsocks-libev/manager.json


**STDOUT:**

 2019-09-** **:**:39 INFO: using tcp fast open
 2019-09-** **:**:39 INFO: working directory points to /home/**/.shadowsocks
 2019-09-** **:**:24 INFO: try to bind interface: **.**.**.**, port: XXXX
 2019-09-** **:**:24 INFO: cmd: ss-server --manager-address /home/**/manager.sock -f /home/**/.shadowsocks/.shadowsocks_XXXX.pid -c /home/**/.shadowsocks/.shadowsocks_XXXX.conf --acl /etc/shadowsocks-libev/server_block_local.acl -t 60 -v --fast-open -s **.**.**.**
 2019-09-** **:**:24 INFO: initializing acl...
 2019-09-** **:**:24 INFO: try to bind interface: **.**.**.**, port: YYYY
 2019-09-** **:**:24 INFO: cmd: ss-server --manager-address /home/**/manager.sock -f /home/**/.shadowsocks/.shadowsocks_YYYY.pid -c /home/**/.shadowsocks/.shadowsocks_YYYY.conf --acl /etc/shadowsocks-libev/server_block_local.acl -t 60 -v --fast-open -s **.**.**.**
 2019-09-** **:**:24 INFO: initializing acl...
.
.
.
 2019-09-** **:**:04 INFO: update traffic ****6684 for port XXXX
 2019-09-** **:**:04 **ERROR**: stat_sendto: No such file or directory
 2019-09-** **:**:04 INFO: update traffic ****972 for port YYYY
 2019-09-** **:**:04 **ERROR**: stat_sendto: No such file or directory
.
.
.


**CONFIG FILE:**

{
    "server":"**.**.**.**",
    "port_password": {
        "XXXX":"*********",
        "YYYY":"*********"
    },
    "mode": "tcp_only",
    "timeout":60,
    "method":"***********",
    "fast_open": true,
    "acl": "/etc/shadowsocks-libev/server_block_local.acl"
}

**Comment by billzhong** [comment]
Hi @madeye ,

I have the same issue with version **3.3.1** running on CentOS 7 x86_64.

```
Sep 26 00:00:00 server ss-manager[1000]: 2019-09-26 00:00:00 ERROR: stat_sendto: No such file or directory
Sep 26 00:00:00 server ss-manager[1000]: 2019-09-26 00:00:00 ERROR: stat_sendto: No such file or directory
Sep 26 00:00:00 server ss-manager[1000]: 2019-09-26 00:00:00 ERROR: stat_sendto: No such file or directory
```

I am still able to get the stats via UDP, but the error messages are annoying.
Thanks.
