### ISSUE TITLE
Global mode does not work

### ISSUE THREAD

**Issue by kiddingl** [shadowsocks/shadowsocks-libev#2479]
### What version of shadowsocks-libev are you using?
v3.3.1
it is running on docker  

### What operating system are you using?
centos7, 

#### I run the command
```
docker run -d -v /tmp/test.json:/tmp/test.json --name=lib --privileged=true --user=root --net=host shadowsocks/shadowsocks-libev ss-server -c /tmp/test.json
```

#### I have three hosts
ss-client(windwos) : IP: 172.16.1.214

#### The picture of ss-client
![image](https://user-images.githubusercontent.com/36329336/65299215-32340b80-dba1-11e9-8f49-c49f5a6fc483.png)

nginx(centos7) is running on docker :      IP: 172.16.1.213
```
docker run -d --name=nginx --net=host nginx
```
ss-server(cnetos7) is running on docker:  IP: 172.16.1.11
```
docker run -d -v /tmp/test.json:/tmp/test.json --name=lib --privileged=true --user=root --net=host shadowsocks/shadowsocks-libev ss-server -c /tmp/test.json
```
#### Fill in the address of nginx server on Firefox browser
![image](https://user-images.githubusercontent.com/36329336/65299365-d7e77a80-dba1-11e9-913c-81c74549d516.png)
#### But I get logs of nginx:
![image](https://user-images.githubusercontent.com/36329336/65299426-1846f880-dba2-11e9-98b0-e90da10834d9.png)

### What did you expect to see?
I want to see address 172.16.1.11 in nginx logs

### What did you see instead?
address 172.16,1.214 in nginx logs

#### test.json:
```
{
 "local_port": "1080",
 "server": "0.0.0.0",
 "server_port": 443,
 "password": "123456",
 "timeout": 60,
 "method": "aes-256-gcm"
}
```

**Comment by lcdtyph** [comment]
This issue is related to [shadowsocks-windows](https://github.com/shadowsocks/shadowsocks-windows), and I don't think you should post here.

The root cause is that shadowsocks-windows sets the  "except address" field in the windows proxy configuration entry. You can delete the 172.16.0.0/12 manually at Settings -> Network & Internet -> Proxy, after you turn on global mode.

**Comment by kiddingl** [comment]
I had solved the probelm,  thanks for  your help
