### ISSUE TITLE
Continuous Retrainsmission and Connection Reset

### ISSUE THREAD

**Issue by StephenChips** [shadowsocks/shadowsocks-libev#2482]
### What version of shadowsocks-libev are you using?
Server: shadowsocks-libev 3.2.5
Client: Shadowsocks-Windows 4.1.6

### What operating system are you using?
Ubuntu 19.04

### What did you do?
Trying to access google.com

### What did you expect to see?
Successfully load the website.

### What did you see instead?
I cannot access the website often, cannot link SSH via putty, but I can ping to the proxy server successfully. I doesn't encounter such problem when I using shadowsocks via Potasto lite client on my iPhone SE and iPad (another network).

Through Wireshark, I find there are lots of retransmission between the client and the server, and some RST packets will occur from time to time, not often. 

I also cannot access my server's vendor's website (vultr.com).

What's the possible reason for such problem? Is the ISP interfering the network between the proxy and the client? Is my proxy server facing the RST attack? Or Is simply just the poor network condition that causing such problem?

P.S Sometimes this problem will suddenly solved for unknown reasons, which I can access the website, but usually I will enconter such problem later (sometimes few minutes later, sometimes few hours later).

### What is your config in detail (with all sensitive info masked)?
I think the config doesn't has problem.
```
root@vultr:~# vim /etc/shadowsocks-libev/config.json
{
    "server":"0.0.0.0",
    "mode":"tcp_and_udp",
    "server_port":23489,
    "local_port":1080,
    "password":"xxxxxxxx",
    "timeout":60,
    "method":"chacha20-ietf-poly1305"
}
```

**Comment by kaslr** [comment]
Seems your ISP is doing bad things.
Randomly resetting TCP is a well-known behavior of GFW. However, you do access the server using another network, which indicates likely something wrong with your ISP. (Is it China Mobile or any "second hand ISP"?)
