### ISSUE TITLE
How to disguise as a normal website

### ISSUE THREAD

**Issue by onlyJinx** [shadowsocks/shadowsocks-libev#2483]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
version: 3.3.1

### What operating system are you using?
CentOS7

### What did you do?
not

### What did you expect to see?
SS可以像SSR或者V2ray一样把一个端口(80)同时做成服务器端口和网页端口吗？比如我用浏览器访问域名时可以正常显示一个网页，使用SS-Client也可以连接…有个V2ray-plugin不知道可不可以实现，文档里好像没有提到

**Comment by kaslr** [comment]
Sure, but you may have to figure it out yourself.

It's somehow same as disguising website using v2ray. The only difference is that you need to change the v2ray with ss+v2-plugin behind the nginx(or other web server you like). [This](https://toutyrater.github.io/advanced/wss_and_web.html#websockettlsweb) link might help.

**Comment by onlyJinx** [comment]
> Sure, but you may have to figure it out yourself.
> 
> It's somehow same as disguising website using v2ray. The only difference is that you need to replace the v2ray with ss+v2-plugin behind the nginx(or other web server you like). [This](https://toutyrater.github.io/advanced/wss_and_web.html#websockettlsweb) link might help.

OK, Thank you!
