### ISSUE TITLE
Current version，does the server support "fast open"?

### ISSUE THREAD

**Issue by dragon100a** [shadowsocks/shadowsocks-libev#2484]
### What version of shadowsocks-libev are you using?
latest

### What operating system are you using?
debian 9

### What did you do?
/etc/sysctl.conf
I add a line.
`net.ipv4.tcp_fastopen = 3`

/etc/shadowsocks-libev/config.json
`"fast_open":false,`
I change false to true.

I heard that old version removed support of "fast open".
Does the current version support "fast open"?

**Comment by kaslr** [comment]
Yes, the latest release (3.3.1) supports tcp fast open
