### ISSUE TITLE
E: The value 'jessie-backports-sloppy' is invalid for APT::Default-Release as such a release is not available in the sources

### ISSUE THREAD

**Issue by GitatHub** [shadowsocks/shadowsocks-libev#2488]
### What version of shadowsocks-libev are you using?
3.2.0

### What operating system are you using?

Release:        8.11
Codename:       jessie

### What did you do?
sudo sh -c 'printf "deb http://deb.debian.org/debian jessie-backports main\n" > /etc/apt/sources.list.d/jessie-backports.list'
sudo sh -c 'printf "deb http://deb.debian.org/debian jessie-backports-sloppy main" >> /etc/apt/sources.list.d/jessie-backports.list'
sudo apt update
sudo apt -t jessie-backports-sloppy install shadowsocks-libev

### What did you expect to see?
install as described in the docs.

### What did you see instead?
sudo apt update

Err http://deb.debian.org jessie-backports/main amd64 Packages
  404  Not Found [IP: #### 80]
Err http://deb.debian.org jessie-backports-sloppy/main amd64 Packages
  404  Not Found [IP: #### 80]
W: Failed to fetch http://deb.debian.org/debian/dists/jessie-backports/main/binary-amd64/Packages  404  Not Found [IP: #### 80]

W: Failed to fetch http://deb.debian.org/debian/dists/jessie-backports-sloppy/main/binary-amd64/Packages  404  Not Found [IP: #### 80]

E: Some index files failed to download. They have been ignored, or old ones used instead.

sudo apt -t jessie-backports-sloppy install shadowsocks-libev

E: The value 'jessie-backports-sloppy' is invalid for APT::Default-Release as such a release is not available in the sources

### What is your config in detail (with all sensitive info masked)?
N/A here.

**Comment by rogers0** [comment]
jessie-backports-sloppy is closed [1].
Please kindly consider upgrade to stretch, and then buster.
At least you need to upgrade to stretch with backports.

[1] https://lists.debian.org/debian-backports-announce/2018/07/msg00000.html
