### ISSUE TITLE
help 提示缺少一些选项和内容

### ISSUE THREAD

**Issue by myliyifei** [shadowsocks/shadowsocks-libev#249]
比如缺少-a 选项 指定运行用户
              -f 选项还缺少说明，比如让进程以后台daemon运行，日志会写入syslog等。

ss-server 

shadowsocks-libev 2.1.0

  maintained by Max Lv <max.c.lv@gmail.com> and Linus Yang <laokongzi@gmail.com>

  usage:

    ss-[local|redir|server|tunnel]

          -s <server_host>           host name or ip address of your remote server
          -p <server_port>           port number of your remote server
          -l <local_port>            port number of your local server
          -k <password>              password of your remote server

          [-m <encrypt_method>]      encrypt method: table, rc4, rc4-md5,
                                     aes-128-cfb, aes-192-cfb, aes-256-cfb,
                                     bf-cfb, camellia-128-cfb, camellia-192-cfb,
                                     camellia-256-cfb, cast5-cfb, des-cfb, idea-cfb,
                                     rc2-cfb, seed-cfb, salsa20 and chacha20
          [-f <pid_file>]            file to store the pid
          [-t <timeout>]             socket timeout in seconds
          [-c <config_file>]         config file in json

          [-i <interface>]           network interface to bind,
                                     not available in redir mode
          [-b <local_address>]       local address to bind,
                                     not available in server mode
          [-u]                       enable udprelay mode
                                     not available in redir mode
          [-L <addr>:<port>]         setup a local port forwarding tunnel,
                                     only available in tunnel mode
          [-d <addr>]                setup name servers for internal DNS resolver,
                                     only available in server mode
          [-v]                       verbose mode

          [--fast-open]              enable TCP fast open,
                                     only available on Linux kernel > 3.7.0
          [--acl <acl_file>]         config file of ACL (Access Control List)

**Comment by myliyifei** [comment]
你是觉得我提的不对，还是不想写？
我补充提request pull也可以。但是我没有你清楚各选项的全部用途，我完全是黑盒在猜测。

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks-libev/blob/master/shadowsocks-libev.8

**Comment by madeye** [comment]
1. 所有未出现在 Usage 里的选项都是不被支持的。
2. 理解选项如何工作的唯一途径是阅读代码。

**Comment by myliyifei** [comment]
好的，那我在研读一下代码

2015-01-31 16:00 GMT+08:00 Max Lv <notifications@github.com>:
