### ISSUE TITLE
ss-manger 管理多用户最多只能开200个端口以内？

### ISSUE THREAD

**Issue by DearTanker** [shadowsocks/shadowsocks-libev#2490]
### What version of shadowsocks-libev are you using?

3.3.1

### What operating system are you using?

centos 7

### What did you do?

使用ss-manager运行config文件实现多端口多用户

### What did you expect to see?

config 内配置了 300 个端口来进行试验，要都能用才行。

### What did you see instead?

多次尝试发现最多只能开到 19* 这样。后面的端口都不成功

### What is your config in detail (with all sensitive info masked)?

```

{
	"server":"0.0.0.0",
	"port_password":{
        "29000":"1111111111",
         ....
        "29301":"1111111111"
	},
	"timeout":300,
	"method":"chacha20-ietf-poly1305",
	"mode":"tcp_and_udp",
	"fast_open": true,
	"plugin":"v2ray-plugin",
	"plugin_opts":"server;tls;fast-open;host=xx.com;cert=/etc/shadowsocks-libev/xx.com/fullchain.cer;key=/etc/shadowsocks-libev/xx.com/xx.com.key;loglevel=none"
}

```

所以，是我做错了什么，还是本身就不能有太多端口？

**Comment by DearTanker** [comment]
额。。看了一眼内存，是内存被耗尽了，这...

几个端口就创建几个进程，直到内存不够用吗。。

**Comment by madeye** [comment]
Try https://github.com/shadowsocks/shadowsocks-rust
