### ISSUE TITLE
使用 snap 安装存在诸多问题

### ISSUE THREAD

**Issue by invisprints** [shadowsocks/shadowsocks-libev#2491]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
3.3.1

### What operating system are you using?
ubuntu 18.04.3 aws

使用 `snap install shadowsocks-libev --edge` 安装完成后，无法从配置文件启动`shadow socks-libev.ss-manager`
按照 #2433 解决无法访问配置文件的问题后，遇到 #2485 同样的问题
Google 一下后以下面的命令解决上述问题，但是开启1024一下常用端口时（如443），显示 `permission denied`，只能开启非常用端口（如8388）
```sh
 snap install --devmode shadowsocks-libev --edge
```
但是在写入ss-manager的开机启动脚本时，又出现许多问题，以至于我现在已经连不上服务器了，没法详细说明问题。
开机启动用的是 systemctl

**Comment by invisprints** [comment]
重装了一下服务器，貌似之后就没有什么问题了，开机脚本那里应该是当时配置错了，Ubuntu 18.04.3的.service路径修改成 /lib/systemd/system就可开机启动

**Comment by littlesum** [comment]
你说的问题我没有 我现在的需要谁能帮写个 systemd 
snap services 脚本，让snap ss-libev 可以开机启动 ！现在我只能用 sudo shadowsocks-libev.ss-server && 后台运行

**Comment by invisprints** [comment]
你这网上一搜一大堆
```
[Unit]
Description=shadowsocks manager # 服务的描述
After=network-online.target # 该服务跟在哪个服务后启动

[Service]
Type=forking
ExecStart=/snap/bin/shadowsocks-libev.ss-server -c home/`whoami`/snap/shadowsocks-libev/config.json # 启动服务时执行的命令
PrivateTmp=true # 使用私有临时文件目录

[Install]
WantedBy=multi-user.target # 附挂在multi-user.target下
```
网上找的

**Comment by littlesum** [comment]
我回头试试这个脚本 对snap 脚本工作没搞明白，我参照 nextcloud 的service 脚本写了一个 一直报错 跑不起来！
比如你这个service 这段 根据snapcraft.yml 里面的说明 它可以直接读取 /var/snap/shadowsocks-libev/commmon/etc/shadowsocks-libev/config.json

我没搞明白 snap 的bin放在哪！我好像没看到snap下面有bin目录啊？ 这个应该跑不起来吧？

我用的 /usr/bin/snap run shadowsocks-libev.ss-server 这种写法 跑不起来

**Comment by littlesum** [comment]
我看你说 service 放在lib/systemd/system里面为啥我的ubuntu 18.04 还是在 /etc/systemd/system里面！ 你这个aws Ubuntu是改了的么？

**Comment by invisprints** [comment]
我的 ss 就安装在/sna/bin里， aws 的 system 就在/lib那里，我不清楚其他的是什么样的，但你只需找到对应的路径，把地址改到正确的位置即可

**Comment by redstoneleo** [comment]
我通过这种方式安装
sudo snap install shadowsocks-libev
然后找不到这个文件
/etc/shadowsocks-libev/config.json
怎么办呢？

**Comment by invisprints** [comment]
自己写一个即可，然后启动时指定配置文件的路径

**Comment by redstoneleo** [comment]
- 也没有这个目录/etc/shadowsocks-libev/
- shadowsocks-libev是安装在了/sna/下面，接下来是要把config.json建在/sna/bin/下面吗？

**Comment by invisprints** [comment]
软件默认调用配置文件的位置我也没有找到相关的说明文档，但软件提供了指定配置文件路径的方法，用这个方法你就可以随意指定配置文件的位置

**Comment by mixool** [comment]
@littlesum 我按照你说的 /var/snap/shadowsocks-libev/commmon/etc/shadowsocks-libev/位置自己编写一个config就可以运行了，默认没有
 /snap/bin/shadowsocks-libev.ss-server
