### ISSUE TITLE
密码越长，加解密速度会不会越慢？

### ISSUE THREAD

**Issue by 0x112** [shadowsocks/shadowsocks-libev#2492]
好奇想问下10位数的密码和100位数的密码用起来一样吗？
加解密速度会不会因为密码长度变长而变慢？

**Comment by kaslr** [comment]
不会影响加解密速度，无论密码有多长，在ss启动的时候都会生成一个**定长**的主密钥，如果使用 AEAD 那么每一条新连接会使用主密钥来再生成一个定长的会话密钥通信（取决于你选择的加密算法，如 aes-256-gcm 就会生成一个 256 bit 的会话密钥）。
但是密码越复杂越好，因为主密钥是直接又你的密码导出的。

**Comment by 0x112** [comment]
感谢解答
