### ISSUE TITLE
reuse port能不能根据IP分流？

### ISSUE THREAD

**Issue by 0x112** [shadowsocks/shadowsocks-libev#2493]
假如我有两个ss-local进程，绑定到1080端口，开启reuse port，并使用不同的服务器：
```shell
ss-local -s 111.111.111.111 -p 111 -l 1080 ... --reuse-port
ss-local -s 222.222.222.222 -p 111 -l 1080 ... --reuse-port
```

之后访问一个域名，假如这个域名的IP是123.123.123.123，我通过1080端口访问它，目前的情况是随机用111.111.111.111或者222.222.222.222来访问

请问能不能改成nginx负载均衡的ip-hash的方式？用固定一个服务器来固定访问一个IP

**Comment by madeye** [comment]
Try HAproxy.

**Comment by 0x112** [comment]
还要额外配置一个有点麻烦，能否把这个功能直接加到ss-libev里？
