### ISSUE TITLE
Snap install shadowsocks-libev service scripts on boot 

### ISSUE THREAD

**Issue by littlesum** [shadowsocks/shadowsocks-libev#2495]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?

Snap edge version 3.31
### What operating system are you using?

Ubuntu server 18.04
### What did you do?
Need snap services scripts on boot
Now I can only run 
# sudo shadowsocks-libev.ss-server 
# sudo shadowsocks-libev.ss-local 
Or 
# sudo snap run shadowsocks-libev.ss-server

### What did you expect to see?

Need scripts in that I can do such as
# sudo snap start shadowsocks-libev.ss-server
# sudo snap start shadowsocks-libev.ss-local

### What is your config in detail (with all sensitive info masked)?
I use systemd and write scripts, however they doesn’t work!

**Comment by ryenus** [comment]
This is what happened:

```
$ ls -l /snap/bin/shadowsocks-libev.ss-server
/snap/bin/shadowsocks-libev.ss-server -> /usr/bin/snap*
$ sudo snap start /snap/bin/shadowsocks-libev.ss-server
error: snap "/snap/bin/shadowsocks-libev" has no service "ss-server"
$
```

What expected is to be able to start ss-server installed via snap as a service, like the systemd one.

Thanks!

**Comment by willy666rumster** [comment]
still no answer?

**Comment by digglife** [comment]
So is this not an issue? If you install snap version on Ubuntu distro as the guide recommends, it is perfectly normal that you can't start the ss as a service?

**Comment by dpfg** [comment]
Just used /snap/bin/shadowsocks-libev.ss-server as a execStart for systemd unit to fix the issue
