### ISSUE TITLE
Shadowsocks-libev can't support Cloudflare CDN?

### ISSUE THREAD

**Issue by onlyJinx** [shadowsocks/shadowsocks-libev#2496]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
shadowsocks-libev 3.3.1

### What operating system are you using?
Centos7

### What did you do?
Use Cloudflare CDN

### What did you expect to see?
Use Cloudflare CDN Hide my original IP

### What is your config in detail (with all sensitive info masked)?

I can use my domain name to access my webpage normally.but i can't use the domain name connect to ss-server,If I use the original vps IP in client, I can connect,Is shadowsocks-libev not supporting CDN?
My client is Android shadowsocks+V2ray-plugin.

**Comment by celeron533** [comment]
I guess standard cloudflare supports websockets which is used in http
