### ISSUE TITLE
Not aggregating LTE connections properly in TCP multipath mode

### ISSUE THREAD

**Issue by danceboysf** [shadowsocks/shadowsocks-libev#2500]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
shadowsocks-libev 3.3.1

### What operating system are you using?
Ubuntu 18.04.2 LTS

### What did you do?
Did multipath mode from 2 Fiber connections and one LTE network.

### What did you expect to see?
All network connections fully utilized

### What did you see instead?
Both Fiber connections fully utilized and bonded well (about 75% efficiency), but LTE gets 10-20 mbps in that mix, from more than 200 mbps always available (sometimes up to 500, LTE-A on a high-end hardware router, working on 1800, 2100 and 2600 mhz together, nearly always no users on the base station about 50 meters away from me)

TCP Congestion Protocol used was BBR, with other protocols LTE is not used at all in the mix and multipath for the Fibers is greatly reduced in efficiency, down to 20%.

Fiber networks are 100 mbps each, together on multipath with shadowsocks-libdev they form around 150 mbps.

LTE alone gets over 250-280 mbps to VPS and to the Internet when used alone in shadowsocks-libev and without it.

OpenMPTCPRouter is used to manage the connections. 

### What is your config in detail (with all sensitive info masked)?
/etc/shadowsocks-libev/config.json
{
    "server": [
        "[::0]",
        "0.0.0.0"
    ],
    "server_port": 65101,
    "local_port": 1081,
    "mode": "tcp_and_udp",
    "key": "masked",
    "timeout": 600,
    "method": "chacha20",
    "verbose": 0,
    "ipv6_first": true,
    "prefer_ipv6": false,
    "fast_open": true,
    "no_delay": true,
    "reuse_port": true,
    "mptcp": true,
    "ebpf": false,
    "acl": "/etc/shadowsocks-libev/local.acl"
}

**Comment by madeye** [comment]
Consult the developer of OpenMPTCPRouter instead.
