### ISSUE TITLE
使用ss-local，使用curl测试，无法连到本地的服务

### ISSUE THREAD

**Issue by xuanzihao** [shadowsocks/shadowsocks-libev#2506]
### What version of shadowsocks-libev are you using?

shadowsocks-libev_3.3.1-1_ramips_24kec.ipk

### What operating system are you using?

openwrt 15.05 (mt7628)

### What is your config in detail (with all sensitive info masked)?

在一个终端里运行ss-local

2019-10-05 18:28:27 INFO: initializing ciphers... aes-256-cfb
2019-10-05 18:28:27 INFO: listening at 127.0.0.1:2000
2019-10-05 18:28:27 INFO: running from root user

另外一个终端执行

root@Widora:~# curl --socks5 127.0.0.1:2000 www.google.com
curl: (52) Empty reply from server

ss-local的终端没有发现有log

2019-10-05 18:28:27 INFO: initializing ciphers... aes-256-cfb
2019-10-05 18:28:27 INFO: listening at 127.0.0.1:2000
2019-10-05 18:28:27 INFO: running from root user

（只有上面的Log，并且在这里等待......）

netstat的状态，这个端口是有listen的...

root@Widora:~# netstat -tnlp | grep LISTEN
tcp        0      0 0.0.0.0:5002            0.0.0.0:*               LISTEN      1498/shairport
tcp        0      0 127.0.0.1:2000          0.0.0.0:*               LISTEN      10513/ss-local
10513/ss-local

ss-server是正常的，我用windows下的工具可以连上去....我是不是遗漏了什么东西?感觉好像访问不了这个端口....没有log....

**Comment by kaslr** [comment]
You need to add `-v` cli argument to ss-local to get verbose log.

Curl will perform dns lookup locally with `--socks5` option, and google has already been hijacked by you-know-who. So you'll get the wrong ip and thus get empty reply.
Try this `curl --socks5-hostname 127.0.0.1:2000 www.google.com` to force curl let the proxy resolve the hostnames.

**Comment by junjie2018** [comment]
> You need to add `-v` cli argument to ss-local to get verbose log.
> 
> Curl will perform dns lookup locally with `--socks5` option, and google has already been hijacked by you-know-who. So you'll get the wrong ip and thus get empty reply.
> Try this `curl --socks5-hostname 127.0.0.1:2000 www.google.com` to force curl let the proxy resolve the hostnames.

thank you
