### ISSUE TITLE
Log spam

### ISSUE THREAD

**Issue by altayhunter** [shadowsocks/shadowsocks-libev#2509]
### What version of shadowsocks-libev are you using?
3.3.1

### What operating system are you using?
Arch Linux

### What did you do?
Configured ss-manager with the v2ray-plugin. Everything's working as expected for the clients.

### What did you expect to see?
Normal log activity.

### What did you see instead?
ss-server logs the following messages every few seconds when one particular client is connected:
```
connect: Network is unreachable
connect error
```
The client appears to be configured correctly and the proxy works fine for them. I enabled verbose mode in an attempt to glean more details, but there's no additional information logged between those two messages.
The latter message appears to be logged by [server_recv_cb when connect_to_remote returns NULL](https://github.com/shadowsocks/shadowsocks-libev/blob/313b9a708602e82ec79b1d5ed6a76c8335d833ad/src/server.c#L921).
The former must be logged somewhere in connect_to_remote, [I'm guessing here](https://github.com/shadowsocks/shadowsocks-libev/blob/313b9a708602e82ec79b1d5ed6a76c8335d833ad/src/server.c#L595).

### What is your config in detail (with all sensitive info masked)?
```
{
  "server": "0.0.0.0",
  "port_password": {
    [REDACTED]
  },
  "reuse_port": true,
  "mode": "tcp_and_udp",
  "method": "chacha20-ietf-poly1305"
}
```

**Comment by hagiga-123** [comment]
Are you sure about your server address?

You config file is wrong, try this:

{
    "server": "YOUR_SERVER_ADDR",
    "server_port": "7373",
    "local_port": 1080,
    "password": "YOUR_SERVER_PASSWORD",
    "timeout": 300,
    "method": "chacha20-ietf-poly1305",
    "mode": "tcp_and_udp",
}

**Comment by altayhunter** [comment]
This is the server's config, not the client's. Does the server even use the `server` field? I'm not sure why it would need to be configured with its own public IP address.

Similarly, I don't see why I would set the `local_port` in the server configuration.

**Comment by hagiga-123** [comment]
@altayhunter sorry my mistake I did put a ss-local config but see your server config and compare it to this:
[https://github.com/shadowsocks/shadowsocks-libev/blob/master/doc/ss-server.asciidoc](url)
[https://wiki.archlinux.org/index.php/Shadowsocks](url)

It seems that the server config needs to have a server address and a local port, I would assume the server would listen and forward to local but I am unsure since I did not set a server at my configuration but rather a client.

Hope this helps...

**Comment by altayhunter** [comment]
No, adding the server address breaks the configuration and shadowsocks fails to start:
```
INFO: try to bind interface: <domain>, port: <port>
ERROR: getaddrinfo: Temporary failure in name resolution
ERROR: port is not available, please check.
```
If I use my external IP address instead of domain name, I get a similar set of errors and it still fails to start:
```
INFO: try to bind interface: <ip>, port: <port>
ERROR: bind: Cannot assign requested address
ERROR: Could not bind
ERROR: bind: Cannot assign requested address
ERROR: Could not bind
ERROR: port is not available, please check.
```
When I set the server address to `0.0.0.0` (which is the [default value](https://github.com/shadowsocks/shadowsocks-libev/blob/master/src/server.c#L1791)) it correctly binds the TCP ports at `127.0.0.1`.
```
INFO: try to bind interface: 0.0.0.0, port: <port>
plugin "v2ray-plugin" enabled
UDP relay enabled
initializing ciphers... chacha20-ietf-poly1305
tcp server listening at 127.0.0.1:<random>
udp server listening at 0.0.0.0:<port>
```
As for the local port, there are no processes on the server that need to proxy through shadowsocks, so I don't see the point in setting it in my server configuration.

The log spam I'm seeing is specific to a single user, so I expect it has something to do with their particular configuration, port, or device. It's particularly odd seeing `Network is unreachable` all over my logs when the user in question is able to connect without any issues.
