### ISSUE TITLE
使用编译脚本编译deb失败

### ISSUE THREAD

**Issue by ggg17226** [shadowsocks/shadowsocks-libev#2513]
### What version of shadowsocks-libev are you using?
commit id:29936626b2d206db1b3f7d4dcf2fbd0ee62d2e8c

### What operating system are you using?
ubuntu 18.04 server

### What did you do?
编译lib deb失败

### What did you see instead?
gbp:error: Error creating libbloom_1.6.orig.tar.gz: Pristine-tar couldn't checkout "libbloom_1.6.orig.tar.gz": fatal: Path 'libbloom_1.6.orig.tar.gz.delta' does not exist in 'refs/heads/pristine-tar'

### What is your config in detail (with all sensitive info masked)?
build_deb1.sh lib

**Comment by quickhot** [comment]
Same error, because of Pristine-tar

**Comment by ggg17226** [comment]
都这么久了还没动静。。。。
