### ISSUE TITLE
Obfs-simple hopes to continue to develop some suggestions

### ISSUE THREAD

**Issue by z991238** [shadowsocks/shadowsocks-libev#2514]
### What version of shadowsocks-libev are you using?
shadowsocks-libev3.3.2

### What operating system are you using?
debian9

### What did you do?
Hope to improve obfs-simple to confuse some mechanisms. The reason is that v2ray-plugin is too difficult for Xiaobai to deploy too much.

### What did you expect to see?
1: Different connections can increase or decrease the number of Extension fields when shaking hands.
2: The Cipher Suite and Signature Hash Algorithms field values for different connections are different when they are handshaked.
3: At the end of the connection, the server can send an Encrypted Alert packet.
4: Support TLS1.3
5: Or continue to develop with reference to mtprotoproxy's TLS masquerade

### What did you see instead?
I hope to accept the above suggestions

**Comment by madeye** [comment]
obfs-simple is already deprecated.
