### ISSUE TITLE
怎么开启多用户? / How to open multi-user?

### ISSUE THREAD

**Issue by sllzwsgdsg** [shadowsocks/shadowsocks-libev#2515]
### What version of shadowsocks-libev are you using?
shadowsocks-libev 3.3.2

### What operating system are you using?
Centos7

### What did you do?
我使用这些命令, 安装的程序 / Use the following command to install:
1. git clone https://github.com/shadowsocks/shadowsocks-libev.git
2. ./autogen.sh
3. ./autogen.sh
4. ./autogen.sh && make install

5. 我使用的config.json文件 / Useing config.json like this:
{
    "port_password": {
        "9998": "xxxxx",
        "9999": "xxxxx"
    },
    "server": "0.0.0.0",
    "timeout": 300,
    "method": "aes-256-gcm",
    "fast_open": true
}

6. ss-server -c config.json

### What did you see instead?
This command "ss-server -c config.json" can only print help information and does not work.

### What is your config in detail (with all sensitive info masked)?
我使用的config.json配置文件
config.json 
{
    "port_password": {
        "9998": "xxxxx",
        "9999": "xxxxx"
    },
    "server": "0.0.0.0",
    "timeout": 300,
    "method": "aes-256-gcm",
    "fast_open": true
}

请问这份配置文件有问题吗? libev版本不支持多用户am?
Can't this configuration file be used? Can't shadowsocks-libev support multiple users?
##############################################

**Comment by A-nameless-geek** [comment]
I have the same question like you

**Comment by madeye** [comment]
Try https://github.com/shadowsocks/shadowsocks-rust

**Comment by A-nameless-geek** [comment]
> Try https://github.com/shadowsocks/shadowsocks-rust

I have solve this problem ,there are some format error in my config file

**Comment by yiguihai** [comment]
[我写有一个多端口管理脚本](https://github.com/yiguihai/shadowsocks_install)

**Comment by Tangpeipei** [comment]
> I have the same question like you
> 
> command "ss-server -c config.json" can only print help information and does not work.

Me too!How you solve the problem.
