### ISSUE TITLE
ShadowSocks Doesn't Change IP

### ISSUE THREAD

**Issue by Aphrodites1995** [shadowsocks/shadowsocks-libev#2516]
### What version of shadowsocks-libev are you using?
Newest version

### What operating system are you using?
MacOS, Ubuntu 16.04

### What did you do?
Connected to multiple servers

### What did you expect to see?
The IP being changed, accessing blocked sites

### What did you see instead?
The IP not being changed, me not being able to access blocked sites

### What is your config in detail (with all sensitive info masked)?
Default

I used multiple servers from different sites, but when browsing using Firefox on both OSes, I am unable to access restricted sites and my IP remains unchanged asking for it on an unrestricted site. The latency test seemed to give valid results on Ubuntu.

**Comment by kaslr** [comment]
What's your client? ShadowsocksX-NG? SS-Qt5? brew installed shadowsocks-libev? or other ports?

Did you setup the system proxy?

**Comment by Aphrodites1995** [comment]
Shadowsocks X-NG for MacOS, Qt5 for Ubuntu. Installed libev. I don't think I setup the system proxy though, how do I do that?

**Comment by kaslr** [comment]
For ShadowsocksX-NG, click the menubar icon and select 'Global Mode' in the dropdown list, this will setup system proxy automatically. You can double check settings->network->advanced->proxies, at least one of the checkboxes should be set then.

For ubuntu, I don't have a gui environment so I have no advice...

NOTICE that those settings won't affect terminal programs, you need to set environment `all_proxy` manually. However, some commands would ignore this env variable, then you could check `proxychains` to force them go through proxy.

**Comment by Aphrodites1995** [comment]
But when I do that the check boxes are not set.

**Comment by grasslandgoat** [comment]
I just saw this discussion, It's about 5 years ago discussion :(
I also had this problem, some target sites think my request is from the proxy server, but other target sites still can get my original geolocation, I think they still can read my original Ip address, especially for the sites which are protected by cloudflare protection. I think maybe the original Ip was appended in the request, so it still can be read.

so I think is it possible  for Shadowsocks to remove or replace the ip address in the request? or V2-tray plugin can do this?
