### ISSUE TITLE
默认绑定ip是127.0.0.1，不读取配置文件的设定

### ISSUE THREAD

**Issue by moondigi** [shadowsocks/shadowsocks-libev#252]
配置文件里面有`"local_address" : "0.0.0.0"`，但是ss-local还是绑定127.0.0.1，需要用-b才行

**Comment by kxmp** [comment]
Use local instead of local_address

**Comment by aa65535** [comment]
`"local": "0.0.0.0",`

**Comment by smartepsh** [comment]
-b
