### ISSUE TITLE
apt source not updated

### ISSUE THREAD

**Issue by Nidhoggur1993** [shadowsocks/shadowsocks-libev#2520]
### What version of shadowsocks-libev are you using?
shadowsocks-libev 3.1.3

### What operating system are you using?
Ubuntu 18.04.3 LTS

### What did you do?
sudo apt update
sudo apt upgrade shadowsocks-libev

### What did you expect to see?
It should gives me an upgrade to v3.3.2 as the same in release, but it returns 

> shadowsocks-libev is already the newest version (3.1.3+ds-1ubuntu2).

Maybe something wrong with the apt sources?

**Comment by madeye** [comment]
It's expected. Try snap if you're looking for latest build.

**Comment by NeikuiColacat** [comment]
> It's expected. Try snap if you're looking for latest build.

I tried use the snap , but it's still not the latest version.

**Comment by Nidhoggur1993** [comment]
> > It's expected. Try snap if you're looking for latest build.
> 
> I tried use the snap , but it's still not the latest version.

Same for me.
It will install version 3.2.5-1 if I use `sudo snap install shadowsocks-libev`,
newer than apt install but still not the lastest.
