### ISSUE TITLE
shadowsocks paralysed under 5G circumstance

### ISSUE THREAD

**Issue by Mirr0ch1** [shadowsocks/shadowsocks-libev#2529]
### What version of shadowsocks-libev are you using?
3.3.3-1

### What operating system are you using?
Android 9/10 (client) and CentOS 7 with bbrplus TCM (host)

### What did you see instead?
under 4G network, everything works as should be. But under 5G network, instead, shadowsocks-android failed to establish the connection with pop-up-toasts like "unexpected end of stream on com.android.okhttp.Address@68483374" or a simple "connection closed by peer".

### What is your config in detail (with all sensitive info masked)?
shadowsocks-libev with chacha20-ietf-poly1305 deployed on VPSs with RAM from 768 MiB to 2048 MiB located in multiple countries. Using ssmgr as the management method.
Both TFO on/off (tcp_fast_open=1 or 3) are tested.

**Comment by madeye** [comment]
I don't think it has anything to do with this project.

**Comment by Mirr0ch1** [comment]
@madeye 经过排查，问题依旧出在 TFO，北京联通 5G 的网络设备对 TFO 的握手信息不太友好。 杭州联通 5G 和电信 5G 没有这个问题。
目前运营商设备对 TFO 的支持依旧不怎么好，我这里目前是在繁忙时段偶尔会遭遇因为 TFO cookie 丢失导致的断连。移动 4G 下当然是永远都用不了的啦。
可以考虑在 shadowsocks 的优化教程里移除开启 TFO 的条目或加入形目提示？
https://squeeze.isobar.com/2019/04/11/the-sad-story-of-tcp-fast-open/
（for your reference）
