### ISSUE TITLE
ss-server ERROR

### ISSUE THREAD

**Issue by lssmoon2019** [shadowsocks/shadowsocks-libev#2533]
### What version of shadowsocks-libev are you using?
shadowsocks-libev 3.3.3

### What operating system are you using?

CentOS 7 X64
### What did you do?

安装了这个最新版

### What did you expect to see?
稳定的上youtube

### What did you see instead?
 经常会出现看一段youtube视频后出现不能再使用，隔了5分钟时间不等又好了。一天有时会出现多次这种情况

### What is your config in detail (with all sensitive info masked)?

通过git clone原版编译安装。使用的是原版,。经过查询日志，节选部分

 ss-server[6941]: 2019-11-06 07:29:28 ERROR: server recv: Connection timed out

ss-server[6941]: 2019-11-06 07:31:39 ERROR: server recv: Connection reset by peer

 ss-server[6941]: 2019-11-06 07:58:56 ERROR: connect: Network is unreachable

ss-server[6941]: 2019-11-06 07:58:56 ERROR: connect error

**Comment by ofttryaj** [comment]
日志存在哪的，
