### ISSUE TITLE
不使用acl文件有个网站访问不了，使用acl文件后可以访问了。

### ISSUE THREAD

**Issue by juhuaguai** [shadowsocks/shadowsocks-libev#2534]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
v3.3.3

### What operating system are you using?
windows 7 sp1 x64

### What did you do?
配置好参数运行ss-local-x86.exe后，将流量转发给Local，当没有使用acl时，在中国大陆地区无法打开 steam社区：https://steamcommunity.com/home。但是使用了acl之后，acl里面可以设置为[proxy_all]，就能够顺利打开上述页面了。

### What did you expect to see?
同样的东西，仅仅不使用acl也能够访问：https://steamcommunity.com/home，而不是必须设置acl才能访问。

### What did you see instead?
必须设置了acl才能访问https://steamcommunity.com/home，但是我没有进一步分析具体问题。在local.c中有一处关于acl判断的语句 
if (sni_detected && acl
#ifdef __ANDROID__
            && is_remote_dns
#endif
            )
改为
if (sni_detected && 1
#ifdef __ANDROID__
            && is_remote_dns
#endif
            )
修改之后不设置acl文件也能够正常访问https://steamcommunity.com/home了。

**Comment by madeye** [comment]
It's expected, SNI detection is disabled by default.

To solve your problem, make sure you're using a secure DNS server, e.g. DNSCrypt.

**Comment by juhuaguai** [comment]
> It's expected, SNI detection is disabled by default.
> 
> To solve your problem, make sure you're using a secure DNS server, e.g. DNSCrypt.

thx
