### ISSUE TITLE
How do I get the physical address MAC of the local side on the server side in shadowsocks-libev?

### ISSUE THREAD

**Issue by cliusz** [shadowsocks/shadowsocks-libev#2535]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

**Comment by madeye** [comment]
Nope, you can't.

**Comment by cliusz** [comment]
@madeye THX!
About local ip address (maybe LAN ip)?
