### ISSUE TITLE
Shadowsocks is killed when ssh terminal is closed, or system reboot. (snap)

### ISSUE THREAD

**Issue by epm157** [shadowsocks/shadowsocks-libev#2538]
### What version of shadowsocks-libev are you using?
3.3.1

### What operating system are you using?
Ubuntu 19.10

### What did you do?
1. I run "shadowsocks-libev.ss-server -c /snap/shadowsocks-libev/config.json" command.
2. Shadowsocks starts.
3. I press Ctrl+C, or close ssh terminal (or reboot system),
4. Shadowsocks server is not running anymore.

### What did you expect to see?
I expect Shadowsocks to keep running even after the terminal is closed. It also should restart itself when the system is rebooted.

### What did you see instead?
Shadowsocks server is not running anymore.

### What is your config in detail (with all sensitive info masked)?

{
    "server":["::1", "server ip"],
    "mode":"tcp_and_udp",
    "server_port":443,
    "local_port":1080,
    "password":"password",
    "timeout":60,
    "method":"chacha20-ietf-poly1305"
}

**Comment by lssmoon2019** [comment]
你没配置开机启动

**Comment by epm157** [comment]
How can I enable boot startup for Shadowsocks-libev installed via snap?

**Comment by QiangZiBro** [comment]
You should use a `nohup` command in linux system to run in background.Usage:

`nohup your command 2>&1 &`
