### ISSUE TITLE
Last 3 commits have some problems about ss-manager

### ISSUE THREAD

**Issue by gyteng** [shadowsocks/shadowsocks-libev#2539]
### What version of shadowsocks-libev are you using?
3.3.3

### What operating system are you using?
Ubuntu 18.04

### What did you do?
ss-manager -m aes-256-cfb -u --manager-address 127.0.0.1:9090

### What did you see instead?
2019-11-10 19:03:01 INFO: try to bind interface: 0.0.0.0, port: 20000                                                                                      
2019-11-10 19:03:01 ERROR: Unrecognized option: (null)

### What is your config in detail (with all sensitive info masked)?

It only shows in commit
748e6f38246b858dccd8f76469ecb917321c1050
ce71f49af84db098ab6610a68df10c6af10e5eba
1ba753adaad5454eabf2315fc3a40b82ea732bfa
 
I will find more details.

**Comment by madeye** [comment]
There's no change in `ss-manager` via 1ba753adaad5454eabf2315fc3a40b82ea732bfa.

I cannot reproduce your issue locally, can you try again?

**Comment by gyteng** [comment]
I will try and post more messages here later

**Comment by madeye** [comment]
Okay, it's a bug introduced by https://github.com/shadowsocks/shadowsocks-libev/pull/2259.
