### ISSUE TITLE
ss-server指定监听“::”时，不能同时监听ipv4

### ISSUE THREAD

**Issue by BlackGear** [shadowsocks/shadowsocks-libev#254]
在原来的版本中，可以通过指定"server":"::"，来达到同时监听ipv4与ipv6的效果，在2.1.2版本中却只能监听ipv6，不能监听ipv4。（2.0.x版本似乎没有这个问题，1.6.4版本肯定没有这个问题，暂时不能确定具体上从哪个版本开始出现的问题）

netstat -npl返回：
tcp6       0      0 :::8080                  :::*                    LISTEN       2032/ss-server     
没有绑定0.0.0.0。

libev版本与C#版本的客户端在只支持ipv4的网络上也不能连接到这台服务器，推测这不是客户端的问题，而我在Debian 7和Ubuntu 14.04两个系统的两台VPS上均遇到了同样的问题，推测这也不是系统的问题。

bdwm论坛上有另外一人遇到了这一情况（倒数第二楼）：
http://www.bdwm.net/bbs/bbstcon.php?board=Networking&threadid=15358263&num=17425

推测这是一个服务端的bug，还请研究解决方案，多谢。

**Comment by aa65535** [comment]
70f17645defd2250b25b857105a2b0f4640ea5b5

**Comment by madeye** [comment]
`"server":["[::0]", "0.0.0.0"]`

**Comment by siwind** [comment]
ss-local 如果也能同时监听 IPv4 & IPv6 就完美了~~
