### ISSUE TITLE
The UDP packets cannot be captured by iptables

### ISSUE THREAD

**Issue by b39b332d** [shadowsocks/shadowsocks-libev#2544]
### What version of shadowsocks-libev are you using?
3.3.2

### What operating system are you using?
Linux raspberrypi 4.14.98-v7+ #1200 SMP Tue Feb 12 20:27:48 GMT 2019 armv7l GNU/Linux
or
Linux debian-stretch-1 4.9.0-11-amd64
### What did you do?
```
ip route add local default dev lo table 100
ip rule add fwmark 1 lookup 100
iptables -t mangle -A PREROUTING -p udp --dport 53 -j TPROXY --on-port 1080 --tproxy-mark 0x01/0x01
ss-redir -v -u -c /etc/shadowsocks-libev/config.json 
```
`nslookup www.google.com`

### What did you expect to see?
Several UDP packet have passed through the PREROUTING chain 
The exact amount should be shown in the first(pkts) and second(bytes) column

### What did you see instead?
```
pkts bytes target     prot opt in     out     source               destination         
    0     0 TPROXY     udp  --  *      *       0.0.0.0/0            0.0.0.0/0            udp dpt:53 TPROXY redirect 0.0.0.0:1080 mark 0x1/0x1
```
### What is your config in detail (with all sensitive info masked)?
/etc/shadowsocks-libev/config.json
```
{
    "server": "my.shadwsocks.server",
    "server_port": "12321",
    "local_address": "0.0.0.0",
    "local_port": "1080",
    "mode": "tcp_and_udp",
    "password": "password",
    "method": "rc4-md5",
    "timeout": 60,
    "plugin": "v2ray-plugin",
    "plugin_opts": "tls;host=my.shadowsocks.server"
}
```
```
root@User:~# cat /etc/resolv.conf
nameserver 8.8.8.8
```
```
root@User:~# netstat -ntulp
tcp        0      0 0.0.0.0:1080            0.0.0.0:*               LISTEN      3771/ss-redir   
tcp        0      0 127.0.0.1:42461         0.0.0.0:*               LISTEN      3773/v2ray-plugin       
udp        0      0 0.0.0.0:1080            0.0.0.0:*                           3771/ss-redir   
```
### What did you do then?

It seems that the DNS query destination port isn't 53, the packets were captured by wireshark indicate that the dport is 53 and the dest ip is 8.8.8.8.

So I added some other rules before that one in  PREROUTING chain:
```
iptables -t mangle -I PREROUTING --prot udp -d myserverip/32 -j RETURN
iptables -t mangle -I PREROUTING --prot udp -d 192.168.128.10/32 -j RETURN
iptables -t mangle -I PREROUTING --prot udp -d 127.0.0.0/24 -j RETURN
```
then run 
`nslookup www.google.com`
`iptables -t mangle -L -nv`

The output looks like this:
```
Chain PREROUTING (policy ACCEPT 90 packets, 6699 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    0     0   RETURN     udp  --  *      *       0.0.0.0/0             myserverip  
    1    29   RETURN     udp  --  *      *       0.0.0.0/0            127.0.0.0/24        
    0     0   RETURN     udp  --  *      *       0.0.0.0/0            192.168.128.10      
    0     0   TPROXY     udp  --  *      *       0.0.0.0/0            0.0.0.0/0            udp dpt:53 TPROXY redirect 0.0.0.0:1080 mark 0x1/0x1
```
UDP packets still does not pass ss-redir
This question is driving me crazy. Will someone help me?
Any advice is greatly appreciated.

Many thanks

**Comment by rampageX** [comment]
Test on LAN client not local, or put rules in OUTPUT chian.

**Comment by b39b332d** [comment]
> Test on LAN client not local, or put rules in OUTPUT chian.

Thank you. I really appreciate your help.

This is a LAN client and I just want to parsing dns instead of proxy TCP traffic.
Besides that "TPROXY target only usable from PREROUTING"

**Comment by b39b332d** [comment]
Ha,I got that! I really appreciate your help
I added the mask in OUTPUT chain,then the udp traffic was redirected to localhost.
`iptables -t mangle -A OUTPUT -p udp --dport 53 -j MARK  --set-mark 0x01`
thank you for your help @rampageX , otherwise I don't know how long I will be troubled by this problem.
