### ISSUE TITLE
在搭建之后发现运用在f/gcm链接之时会30s左右不断重连

### ISSUE THREAD

**Issue by lxsjgzs** [shadowsocks/shadowsocks-libev#2545]
### What version of shadowsocks-libev are you using?
3.3.3

### What operating system are you using?
CentOS 7

### What did you do?
设置 timeout

### What did you expect to see?
在手机的 client 端连接后会发现 Google 的推送服务 fcm/gcm 不断在断线重连，如图：
![IMG_20191118_084557](https://user-images.githubusercontent.com/42400748/69017323-33d35180-09e1-11ea-8f9b-02c33d38f9d1.jpg)

### What is your config in detail (with all sensitive info masked)?
![IMG_20191118_090107](https://user-images.githubusercontent.com/42400748/69017434-fd4a0680-09e1-11ea-9b85-4e6ccae8cbea.jpg)

P.S. 已经正确地在 config 中设置了 timeout 但是在本地的 fcm/gcm 的 log 中还是不断的输出 timeout 然后 reconnect 。请问到底是哪里配置出了问题？

**Comment by lxsjgzs** [comment]
具体使用的是 nginx反代＋ss-libev with v2ray-plugin

**Comment by madeye** [comment]
Check with your CDN provider about their timeout settings.

**Comment by lxsjgzs** [comment]
> Check with your CDN provider about their timeout settings.

Thank you, I'll check it.
