### ISSUE TITLE
How can I set a parent http proxy for ss-local?

### ISSUE THREAD

**Issue by NightMachinary** [shadowsocks/shadowsocks-libev#2546]
I live in Iran, and the gov has enacted a super Draconian firewall recently which blocks almost all connections. I have access to a http proxy (not my server) that enables me to escape the new firewall, but the old firewall (which is still quite aggressive) is still there. I want to be able to connect to my shadowsocks server (which is located in UK and is accessible from the said http proxy.). I.e., `client -> socks -> shadowsocks -> http proxy `.

**Comment by honwen** [comment]
recommend: [GOST](https://github.com/ginuerzh/gost/blob/master/README_en.md)

`gost -L=:8080 -F=ss2://xxxxx -F=http://xxxxxx`

**Comment by NightMachinary** [comment]
Thanks!
