### ISSUE TITLE
ss-server频繁出现：ERROR: failed to handshake with 10.64.13.6: invalid address type

### ISSUE THREAD

**Issue by chinaxd** [shadowsocks/shadowsocks-libev#2547]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
v3.3.3

### What operating system are you using?
centos 7

### What did you do?
ss-server日志中，频繁出现握手失败：较多的invalid address type ，偶尔会是invalid host name ，偶尔会是invalid length for ipv6 address。
具体的部分日志：
Nov 21 10:07:43 localhost ss-server: 2019-11-21 10:07:43 ERROR: failed to handshake with 10.67.16.8: invalid address type
Nov 21 10:07:43 localhost ss-server: 2019-11-21 10:07:43 ERROR: connect: Network is unreachable
Nov 21 10:07:43 localhost ss-server: 2019-11-21 10:07:43 ERROR: connect error
Nov 21 10:07:43 localhost ss-server: 2019-11-21 10:07:43 ERROR: failed to handshake with 10.67.16.8: invalid host name
Nov 21 10:07:43 localhost ss-server: 2019-11-21 10:07:43 ERROR: failed to handshake with 10.67.16.8: invalid address type
Nov 21 10:07:43 localhost ss-server: 2019-11-21 10:07:43 ERROR: failed to handshake with 10.67.16.8: invalid address type
Nov 21 10:07:43 localhost ss-server: 2019-11-21 10:07:43 ERROR: failed to handshake with 10.67.16.8: invalid address type
Nov 21 10:07:43 localhost ss-server: 2019-11-21 10:07:43 ERROR: failed to handshake with 10.67.16.8: invalid host name
Nov 21 10:07:43 localhost ss-server: 2019-11-21 10:07:43 ERROR: failed to handshake with 10.67.16.8: invalid address type
Nov 21 10:07:43 localhost ss-server: 2019-11-21 10:07:43 ERROR: failed to handshake with 10.67.16.8: invalid address type
Nov 21 10:07:43 localhost ss-server: 2019-11-21 10:07:43 ERROR: failed to handshake with 10.67.16.8: invalid host name length
Nov 21 10:07:43 localhost ss-server: 2019-11-21 10:07:43 ERROR: connect: Network is unreachable
Nov 21 10:07:43 localhost ss-server: 2019-11-21 10:07:43 ERROR: connect error
Nov 21 10:07:43 localhost ss-server: 2019-11-21 10:07:43 ERROR: failed to handshake with 10.67.16.8: invalid address type
Nov 21 10:07:43 localhost ss-server: 2019-11-21 10:07:43 ERROR: connect: Network is unreachable
Nov 21 10:07:43 localhost ss-server: 2019-11-21 10:07:43 ERROR: connect error
Nov 21 10:07:43 localhost ss-server: 2019-11-21 10:07:43 ERROR: failed to handshake with 10.67.16.8: invalid address type
Nov 21 10:07:43 localhost ss-server: 2019-11-21 10:07:43 ERROR: failed to handshake with 10.67.16.8: invalid address type
Nov 21 10:07:44 localhost ss-server: 2019-11-21 10:07:44 ERROR: failed to handshake with 10.67.16.8: invalid address type

### What did you expect to see?
这种情况，大概是哪个原因导致的？

**Comment by madeye** [comment]
One of your LAN devices is scanning your server's ports.

**Comment by chinaxd** [comment]
thx, that's right, problems due to protection.
