### ISSUE TITLE
请问怎么使用android-ndk编译ss-redir文件

### ISSUE THREAD

**Issue by cnddy** [shadowsocks/shadowsocks-libev#2548]
我需要在安卓手机上使用ss-redir来透明代理，能不能提供一份完整的android.mk文件
armeabi-v7a或者arm64-v8a都可以

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks-android/blob/master/core/src/main/jni/Android.mk

**Comment by cnddy** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/56773886/69323826-5cc64180-0c82-11ea-8fc3-50a7bf165f4e.png)
这个文件没有包括ss-redir，我之前试过自己编译这个文件，但是都报错了，实在是不会。

**Comment by cnddy** [comment]
请求添加ss-redir模块到android.mk

**Comment by cnddy** [comment]
> https://github.com/shadowsocks/shadowsocks-android/blob/master/core/src/main/jni/Android.mk

请求添加ss-redir模块到android.mk
