### ISSUE TITLE
itoa

### ISSUE THREAD

**Issue by maxchendt** [shadowsocks/shadowsocks-libev#255]
cygwin: uname -a
CYGWIN_NT-5.1 TeX-hk 1.7.34(0.285/5/3) 2015-02-04 12:12 i686 Cygwin

I use cygwin in windows, and compile the 2.12 version. I should comment the following line
//  char *	_EXFUN(itoa,(int, char *, int)); 
in /usr/include/stdlib.h:183, otherwise, will see the following error message when MAKE

In file included from utils.c:38:0:
utils.h:172:7: error: conflicting types for 'itoa'
 char *itoa(int i);
       ^
In file included from /usr/include/stdlib.h:11:0,
                 from utils.c:23:
/usr/include/stdlib.h:183:10: note: previous declaration of 'itoa' was here
   char * _EXFUN(itoa,(int, char *, int));
          ^
utils.c:67:7: error: conflicting types for 'itoa'
 char *itoa(int i)
       ^
In file included from /usr/include/stdlib.h:11:0,
                 from utils.c:23:
/usr/include/stdlib.h:183:10: note: previous declaration of 'itoa' was here
   char * _EXFUN(itoa,(int, char *, int));
          ^
Makefile:597: recipe for target 'libshadowsocks_la-utils.lo' failed
make[2]: *** [libshadowsocks_la-utils.lo] Error 1

**Comment by madeye** [comment]
Update your Cygwin and Windows

**Comment by maxchendt** [comment]
Thanks. I do not know why, but It works

On a computer with :CYGWIN_NT-6.1-WOW64 T06 1.7.9(0.237/5/3) 2011-03-29
10:10 i686 Cygwin", it works perfectly. Where an old Cygwin 1.7.9
(2011-03-29).

but for 1.7.34 (2015-02-04), the */usr/include/stdlib.h is changed from **8,328
** to **11,169 bytes.*
