### ISSUE TITLE
Use Socks5 as a parent for ss-server

### ISSUE THREAD

**Issue by parsanoori** [shadowsocks/shadowsocks-libev#2550]
I've got a VPS with a Socks5 listener on a local port and I want to use ShadowSocks to use that Socks5 local port in my home.
I short, I want to have Socks5 as a parent for ss-server.
Is there a way for that ?

**Comment by madeye** [comment]
https://linux.die.net/man/1/socksify

**Comment by vxray** [comment]
hello, I have the same problem ~

Have you got that ?

**Comment by vxray** [comment]
![image](https://user-images.githubusercontent.com/15797571/69893748-09728400-1351-11ea-9d17-56b6ab2081e1.png)
It seems like socksify can not work ~

**Comment by madeye** [comment]
Also try: https://github.com/darkk/redsocks

**Comment by vxray** [comment]
I find that https://github.com/shadowsocks/shadowsocks-libev/issues/1798#issuecomment-348725710 

But I can not understand what he said.

**Comment by vxray** [comment]
> Also try: https://github.com/darkk/redsocks

I have tried the redsocks. It works good over http. But failed https. The certificate of destination website has been replaced to *.extends.facebook.com. So it can not shown in the browser.

**Comment by vxray** [comment]
well, I got that. maybe you should use ss-tproxy. have fun.
