### ISSUE TITLE
编译后版本不正确

### ISSUE THREAD

**Issue by sssssweb** [shadowsocks/shadowsocks-libev#2557]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
shadowsocks-libev-3.3.3.tar.gz

### What operating system are you using?
Ubuntu 18.04 x86_64  

### What did you do?
mkdir -p ~/build-area/
cp ./scripts/build_deb.sh ~/build-area/
cd ~/build-area
./build_deb.sh

ss-server -v

### What did you expect to see?
3.3.3

### What did you see instead?
3.1.3

**Comment by lixingcong** [comment]
```./autogen.sh```
