### ISSUE TITLE
如何配置透明代理使用远端dns解析

### ISSUE THREAD

**Issue by pscj** [shadowsocks/shadowsocks-libev#2559]
### What version of shadowsocks-libev are you using?
3.3.2

### What operating system are you using?
linux router--padavan

### What did you do?
目前使用dns-forwarder并配置了iptable规则，走代理通道使用google dns(8.8.8.8)进行域名解析。
遇到了问题，ss服务端使用了流媒体DNS解锁服务，走google dns解析回来的IP会判断是代理，只能使用ss服务端配置的dns服务器进行解析。

### What did you expect to see?
希望使用ss-redir做透明代理的时候，能使用ss服务端配置的DNS进行解析。就如ss的windows客户端那样的逻辑，不进行本地DNS解析。

**Comment by debiansid** [comment]
ss-redir设置dns服务器为解锁的dns ip

**Comment by pscj** [comment]
> ss-redir设置dns服务器为解锁的dns ip

由于不同地区dns的ip不同 每个地区只有部分解锁机器需要走特定dns 这个clash配置好像不支持。想着能用fakeip解决一下 但试验过后貌似不行

**Comment by 0neday** [comment]
use dns-forward to convert udp query to tcp, then use ss-tunnel without -u option to get dns answer by tcp
