### ISSUE TITLE
ss-server 会随机监听一个 udp 协议的端口吗？

### ISSUE THREAD

**Issue by jkeylu** [shadowsocks/shadowsocks-libev#256]
我是直接从这里 git clone 下来的源码编译的，然后运行 ss-server 的时候，我发现它会随机监听一个 udp 协议的端口，这是正常的吗？还是我的服务器被黑了？

配置里我设置的 server_port 是 36006

![netstat -nlp](http://ww3.sinaimg.cn/large/67aed568gw1ep0k5qo9y3j20j3059jt6.jpg)

**Comment by madeye** [comment]
正常的

**Comment by alanwonder** [comment]
这是为什么呢？
