### ISSUE TITLE
How to do pressure test for shadowsocks-libev?

### ISSUE THREAD

**Issue by jiangangli69** [shadowsocks/shadowsocks-libev#2560]
It seems that apache benchmark doesn't work for this.

**Comment by qwerttvv** [comment]
1、Find a TG group with thousands of people
2、Send your SS links for free

**Comment by jiangangli69** [comment]
Hi @qwerttvv,

Thanks for your reply. I mean if there is any test tool to do this? e.g.: something like ab, speedTest etc.
