### ISSUE TITLE
openwrt porting compile fails in static link on MIPS

### ISSUE THREAD

**Issue by peter-tank** [shadowsocks/shadowsocks-libev#2561]
https://github.com/shadowsocks/shadowsocks-libev/blob/20a6ad6dfc3689ee831953321112c965d477460c/src/resolv.c#L125-L137
The [similar patch: MIPS: ftrace: Fix a microMIPS build problem](https://github.com/raspberrypi/linux/commit/758d807ab5750c86028acdafaaa4c503e9ccddbc) not needed in my building [kernel 4.14](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/arch/mips/include/asm/ftrace.h?h=v4.14)
- `grep CONFIG_SHADOWSOCKS_STATIC_LINK .config`
```
CONFIG_SHADOWSOCKS_STATIC_LINK=y
```

**Comment by madeye** [comment]
https://github.com/shadowsocks/openwrt-shadowsocks
