### ISSUE TITLE
ss-manager traffic statistics problem

### ISSUE THREAD

**Issue by FenghenHome** [shadowsocks/shadowsocks-libev#2562]
What is the total amount of traffic obtained through the ss-manage API? Can it be split into upload and download traffic, or give guidance on where to modify it

**Comment by madeye** [comment]
No, it's the sum of `upload` and `download` traffic.

**Comment by FenghenHome** [comment]
How do I need to split upload and download

**Comment by madeye** [comment]
Nope, you can't.

But you're free to fork the code and change the behavior here: https://github.com/shadowsocks/shadowsocks-libev/blob/master/src/server.c#L169

**Comment by FenghenHome** [comment]
Thank you, does the traffic calculation include udp traffic

**Comment by madeye** [comment]
Yep.

**Comment by FenghenHome** [comment]
Thank you, if I want to clear it after getting traffic, how do I modify it?

**Comment by FenghenHome** [comment]
`    } else if (strcmp(action, "stat") == 0) {
        char port[8];
        uint64_t traffic = 0;

        if (parse_traffic(buf, r, port, &traffic) == -1) {
            LOGE("invalid command: %s:%s", buf, get_data(buf, r));
            return;
        }

        update_stat(port, traffic);

    } else if (strcmp(action, "ping") == 0) {`
