### ISSUE TITLE
Unstable connection with "crypto repeat salt", "connection was reset by peer", etc

### ISSUE THREAD

**Issue by CooperMaxwell** [shadowsocks/shadowsocks-libev#2564]
### What version of shadowsocks-libev are you using?
3.1.3 with server usage, enhanced multiple user via ss-manager.

### What operating system are you using?
Ubuntu 18.04

### What did you do?
I settled up a ss-server, but the connection was unstable with error logs.

### What did you expect to see?
To see it is working properly with lesser errors...

### What did you see instead?
Error logs. They're in 3 types:
#1 crypto: AEAD: repeat salt detected
#2 failed to handshake with [IP] : authorization error (I am sure those in config matches with my client)
#3 recv: connection was reset by peer

### What is your config in detail (with all sensitive info masked)?
{         
"server": "**.***.***.**",
"port_password": {                                            "[port1]": "[pwd1]",                                                                                    "[port2]": "[pwd2]"                                                                                },  
"timeout": 300,                                   "method": "xchacha20-ietf-poly1305"
 }

Notice: ss-manager is used for supporting multiple user, and the command I launch shadowsocks-libev was: 

/usr/bin/ss-manager --manager-address /var/run/shadowsocks-manager.sock -c /etc/shadowsocks-libev/config.json -a root start
-------------------------------------------------------------------
Thanks for support!

**Comment by CooperMaxwell** [comment]
New error: Blocked all requests from [IP]

**Comment by madeye** [comment]
It looks you're using a broken client, which keeps sending repeated IVs to the server, then got blocked at last.

**Comment by CooperMaxwell** [comment]
> It looks you're using a broken client, which keeps sending repeated IVs to the server, then got blocked at last.

Well, my client is downloaded from Google Play, so I don't think there would be anything broken...
Thanks for replying, I will try to re-install the client then. 
PS : Some errors may happen when no any connection is established. Weird

**Comment by madeye** [comment]
```
Blocked all requests from [IP]
```

It this your client's IP or any random IP? If it's a random IP, it should be some port scanners or spiders, it's fine to block them.

**Comment by CooperMaxwell** [comment]
> ```
> Blocked all requests from [IP]
> ```
> 
> Is this your client's IP or any random IP? If it's a random IP, it should be some port scanners or spiders, it's fine to block them.

I am not sure about what my IP is, cos my ISP don't have a public IP for me. But as you said - some IPs were from Russia.

About the those errors above, I didn't met it today. Wondering if my ISP might have the server's IP banned for a while.

**Comment by CooperMaxwell** [comment]
> ```
> Blocked all requests from [IP]
> ```
> 
> Is this your client's IP or any random IP? If it's a random IP, it should be some port scanners or spiders, it's fine to block them.

New status:
The connection is unstable again. Error logs became clear this time.
My connection was suddenly dropped. I immediately tried it again, still no Internet. But I get the log from server:
---------------------------------------------
Crypto: AEAD: repeat salt detected
failed to handshake with [MyIP]: authorization failed
---------------------------------------------
Then, I rebooted server. Still no Internet, but this time the error is:
-----------------
server recv: Connection was reset by peer
-----------------

That was the last log. Thanks for replying, and hope you are having a good day.

**Comment by CooperMaxwell** [comment]
And I found my IP got banned by server after few tries...xD how to add a IP to whitelist? Thanks

**Comment by vk11223** [comment]
because bloom filter slot is not big enough.
https://github.com/shadowsocks/shadowsocks-libev/blob/master/src/crypto.h#L74-L88
make server setting the same as client setting and compile the modified ss.

**Comment by CooperMaxwell** [comment]
> because bloom filter slot is not big enough.
> https://github.com/shadowsocks/shadowsocks-libev/blob/master/src/crypto.h#L74-L88
> make server setting the same as client setting and compile the modified ss.

Guessed so...my server have a low performance. Settings are the same.

How do I use that head file? Should I compile them and replace the original?

Thanks for replying!

**Comment by vk11223** [comment]
> > because bloom filter slot is not big enough.
> > https://github.com/shadowsocks/shadowsocks-libev/blob/master/src/crypto.h#L74-L88
> > make server setting the same as client setting and compile the modified ss.
> 
> Guessed so...my server have a low performance. Settings are the same.
> 
> How do I use that head file? Should I compile them and replace the original?
> 
> Thanks for replying!

download source file
make the modification
compile and install ss with official instruction

**Comment by madeye** [comment]
There's nothing to do with bloom filter.

As I mentioned before, It's typically a client issue.
