### ISSUE TITLE
在json添加plugin参数后，systemctl启动失败

### ISSUE THREAD

**Issue by Aniark** [shadowsocks/shadowsocks-libev#2567]
### What version of shadowsocks-libev are you using?
`shadowsocks-libev 3.3.3`，作为服务端，安装自`buster-backports`

### What operating system are you using?
`Debian 10`

### What did you do?
在json添加plugin参数，如下
```
{
    "server_port":443,
    "password":"mypasswd",
    "plugin":"/root/v2ray-plugin_linux_amd64",
    "plugin_opts":"tls;fast-open;host=mydomain.com;server"
}
```
之后使用`systemctl start shadowsocks-libev.service`启动服务端，未果，
遂`systemctl status shadowsocks-libev.service`，显示
```
● shadowsocks-libev.service - Shadowsocks-libev Default Server Service
   Loaded: loaded (/lib/systemd/system/shadowsocks-libev.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2019-12-22 15:56:54 EST; 37ms ago
     Docs: man:shadowsocks-libev(8)
  Process: 511 ExecStart=/usr/bin/ss-server -c $CONFFILE $DAEMON_ARGS (code=exited, status=255/EXCEPTION)
 Main PID: 511 (code=exited, status=255/EXCEPTION)

Dec 22 15:56:54 debian systemd[1]: Started Shadowsocks-libev Default Server Service.
Dec 22 15:56:54 debian ss-server[511]:  2019-12-22 15:56:54 INFO: plugin "v2ray-plugin_linux_amd64" enabled
Dec 22 15:56:54 debian ss-server[511]:  2019-12-22 15:56:54 INFO: initializing ciphers... chacha20-ietf-poly1305
Dec 22 15:56:54 debian ss-server[511]:  2019-12-22 15:56:54 INFO: tcp server listening at 127.0.0.1:60549
Dec 22 15:56:54 debian ss-server[511]: No such file or directory
Dec 22 15:56:54 debian ss-server[511]:  2019-12-22 15:56:54 ERROR: plugin service exit unexpectedly
Dec 22 15:56:54 debian ss-server[511]:  2019-12-22 15:56:54 INFO: error on terminating the plugin.
Dec 22 15:56:54 debian systemd[1]: shadowsocks-libev.service: Main process exited, code=exited, status=255/EXCEPTION
Dec 22 15:56:54 debian systemd[1]: shadowsocks-libev.service: Failed with result 'exit-code'.

```
**问题排除过程：**
尝试`ss-server`直接启动，正常使用，排除配置问题
尝试去除plugin相关参数，正常使用，初步判断为添加plugin参数导致的systemctl启动失败

### What did you expect to see?
json添加plugin参数后，`systemctl start shadowsocks-libev.service`正常启动服务端

**Comment by madeye** [comment]
In your log, it says:

```
Dec 22 15:56:54 debian ss-server[511]: No such file or directory
```

It means the path of plugin (`/root/v2ray-plugin_linux_amd64`) is incorrect.

**Comment by Aniark** [comment]
@madeye 再次确认了一遍plugin路径，的确为`/root/v2ray-plugin_linux_amd64`

我重新安装了一遍ss，并重启，依旧报错，但这次log出现了一些变化
```
root@debian:~# systemctl status shadowsocks-libev.service
● shadowsocks-libev.service - Shadowsocks-libev Default Server Service
   Loaded: loaded (/lib/systemd/system/shadowsocks-libev.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2019-12-23 05:08:43 EST; 26s ago
     Docs: man:shadowsocks-libev(8)
  Process: 2909 ExecStart=/usr/bin/ss-server -c $CONFFILE $DAEMON_ARGS (code=exited, status=255/EXCEPTION)
 Main PID: 2909 (code=exited, status=255/EXCEPTION)

Dec 23 05:08:43 debian systemd[1]: Started Shadowsocks-libev Default Server Service.
Dec 23 05:08:43 debian ss-server[2909]:  2019-12-23 05:08:43 INFO: plugin "/root/v2ray-plugin_linux_amd64" enabled
Dec 23 05:08:43 debian ss-server[2909]:  2019-12-23 05:08:43 INFO: initializing ciphers... chacha20-ietf-poly1305
Dec 23 05:08:43 debian ss-server[2909]:  2019-12-23 05:08:43 INFO: tcp server listening at 127.0.0.1:44471
Dec 23 05:08:43 debian ss-server[2909]: Permission denied
Dec 23 05:08:43 debian ss-server[2909]:  2019-12-23 05:08:43 ERROR: plugin service exit unexpectedly
Dec 23 05:08:43 debian ss-server[2909]:  2019-12-23 05:08:43 INFO: error on terminating the plugin.
Dec 23 05:08:43 debian systemd[1]: shadowsocks-libev.service: Main process exited, code=exited, status=255/EXCEPTION
Dec 23 05:08:43 debian systemd[1]: shadowsocks-libev.service: Failed with result 'exit-code'.
```
同样的，使用`ss-server`命令却可以正常启动，如下
```
root@debian:~# ss-server
 2019-12-23 05:09:44 INFO: plugin "/root/v2ray-plugin_linux_amd64" enabled
 2019-12-23 05:09:44 INFO: initializing ciphers... chacha20-ietf-poly1305
 2019-12-23 05:09:44 INFO: tcp server listening at 127.0.0.1:39441
 2019-12-23 05:09:44 INFO: running from root user
2019/12/23 05:09:44 V2Ray 4.19.1 (Po) Custom
2019/12/23 05:09:44 A unified platform for anti-censorship.
2019/12/23 05:09:44 No TLS cert specified, trying /root/.acme.sh/mydomain.com/fullchain.cer
2019/12/23 05:09:44 No TLS key specified, trying /root/.acme.sh/mydomain.com/mydomain.com.key
2019/12/23 05:09:45 [Warning] v2ray.com/core: V2Ray 4.19.1 started
```

**Comment by Aniark** [comment]
我自己写了一份`shadowsocks-libev.service`，并替换掉原来的，如下
```
[Unit]
After=network-online.target

[Service]
ExecStart=/usr/bin/ss-server -c /etc/shadowsocks-libev/config.json

[Install]
WantedBy=multi-user.target
```
这一次服务端正常启动，日志如下
`root@debian:~# systemctl status shadowsocks-libev.service
● shadowsocks-libev.service
   Loaded: loaded (/lib/systemd/system/shadowsocks-libev.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2019-12-23 05:16:34 EST; 18s ago
 Main PID: 2979 (ss-server)
    Tasks: 8 (limit: 535)
   Memory: 15.8M
   CGroup: /system.slice/shadowsocks-libev.service
           ├─2979 /usr/bin/ss-server -c /etc/shadowsocks-libev/config.json
           └─2987 /root/v2ray-plugin_linux_amd64

Dec 23 05:16:34 debian systemd[1]: Started shadowsocks-libev.service.
Dec 23 05:16:34 debian ss-server[2979]:  2019-12-23 05:16:34 INFO: plugin "/root/v2ray-plugin_linux_amd64" enabled
Dec 23 05:16:34 debian ss-server[2979]:  2019-12-23 05:16:34 INFO: initializing ciphers... chacha20-ietf-poly1305
Dec 23 05:16:34 debian ss-server[2979]:  2019-12-23 05:16:34 INFO: tcp server listening at 127.0.0.1:40245
Dec 23 05:16:34 debian ss-server[2979]:  2019-12-23 05:16:34 INFO: running from root user
Dec 23 05:16:35 debian ss-server[2979]: 2019/12/23 05:16:35 V2Ray 4.19.1 (Po) Custom
Dec 23 05:16:35 debian ss-server[2979]: 2019/12/23 05:16:35 A unified platform for anti-censorship.
Dec 23 05:16:35 debian ss-server[2979]: 2019/12/23 05:16:35 No TLS cert specified, trying /root/.acme.sh/mydomain.com/fullc
Dec 23 05:16:35 debian ss-server[2979]: 2019/12/23 05:16:35 No TLS key specified, trying /root/.acme.sh/mydomain.com/mlgcpd
Dec 23 05:16:35 debian ss-server[2979]: 2019/12/23 05:16:35 [Warning] v2ray.com/core: V2Ray 4.19.1 started
lines 1-20/20 (END)...skipping...
● shadowsocks-libev.service
   Loaded: loaded (/lib/systemd/system/shadowsocks-libev.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2019-12-23 05:16:34 EST; 18s ago
 Main PID: 2979 (ss-server)
    Tasks: 8 (limit: 535)
   Memory: 15.8M
   CGroup: /system.slice/shadowsocks-libev.service
           ├─2979 /usr/bin/ss-server -c /etc/shadowsocks-libev/config.json
           └─2987 /root/v2ray-plugin_linux_amd64

Dec 23 05:16:34 debian systemd[1]: Started shadowsocks-libev.service.
Dec 23 05:16:34 debian ss-server[2979]:  2019-12-23 05:16:34 INFO: plugin "/root/v2ray-plugin_linux_amd64" enabled
Dec 23 05:16:34 debian ss-server[2979]:  2019-12-23 05:16:34 INFO: initializing ciphers... chacha20-ietf-poly1305
Dec 23 05:16:34 debian ss-server[2979]:  2019-12-23 05:16:34 INFO: tcp server listening at 127.0.0.1:40245
Dec 23 05:16:34 debian ss-server[2979]:  2019-12-23 05:16:34 INFO: running from root user
Dec 23 05:16:35 debian ss-server[2979]: 2019/12/23 05:16:35 V2Ray 4.19.1 (Po) Custom
Dec 23 05:16:35 debian ss-server[2979]: 2019/12/23 05:16:35 A unified platform for anti-censorship.
Dec 23 05:16:35 debian ss-server[2979]: 2019/12/23 05:16:35 No TLS cert specified, trying /root/.acme.sh/mydomain.com/fullc
Dec 23 05:16:35 debian ss-server[2979]: 2019/12/23 05:16:35 No TLS key specified, trying /root/.acme.sh/mydomain.com/mlgcpd
Dec 23 05:16:35 debian ss-server[2979]: 2019/12/23 05:16:35 [Warning] v2ray.com/core: V2Ray 4.19.1 started`

**Comment by AroKz** [comment]
权限问题，别放在root目录里，然后
`chmod o+x ./v2ray-plugin_linux_amd64`
或者你修改作者的service，
`user/group=nobody`改成`user/group=root`
建议前者

**Comment by Aniark** [comment]
@AroKz  赋权插件并放在了/usr/local/bin目录下，依旧报错


![批注 2020-01-14 173858](https://user-images.githubusercontent.com/10991795/72333118-42469c80-36f6-11ea-971d-2b988e4ca8f1.jpg)
