### ISSUE TITLE
dependency not installable

### ISSUE THREAD

**Issue by fmmajd** [shadowsocks/shadowsocks-libev#2568]
### What version of shadowsocks-libev are you using?
the latest version

### What operating system are you using?
Ubuntu 18.04

### What did you do?
I'm trying to install the package via stretch-backports, but I get a dependency error every time

### What did you expect to see?
I expected the dependencies to be installable.

### What did you see instead?
I see this error:
```bash
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 shadowsocks-libev : Depends: libmbedcrypto0 (>= 2.0) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

I tried to install the package libmbedcrypto0 manually, but apparently this package does not work with ubuntu18.4. there is another package libmbedcrypto1 for 18.4 but it did not work, obviously,

### What is your config in detail (with all sensitive info masked)?
ubuntu18.4, corei3, 16G ram. newly installed os

**Comment by madeye** [comment]
Try snap or docker.

**Comment by fmmajd** [comment]
@madeye yes. I installed it via snap. But the reported bug is still there
