### ISSUE TITLE
docker image fast open issue caused by different Kernel version between host and container

### ISSUE THREAD

**Issue by thirdteeth** [shadowsocks/shadowsocks-libev#2570]
### What version of shadowsocks-libev are you using?
docker images of shadowsocks/shadowsocks-libev:v3.3.3

### What operating system are you using?
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.6 (stretch)
Release:	9.6
Codename:	stretch
uname -r 4.9.0-8-amd64

### What did you do?
docker run -e PASSWORD=<password> -e ARGS=--fast-open -p<server-port>:8388 -p<server-port>:8388/udp -d shadowsocks/shadowsocks-libev:v3.3.3

### What did you expect to see?
fast open enabled

### What did you see instead?
ERROR: failed to set TCP_FASTOPEN_CONNECT

### some information about this issue
TCP_FASTOPEN_CONNECT is a new feature of Linux Kernel 4.11, from the Alpine wiki page https://en.wikipedia.org/wiki/Alpine_Linux, since Alpine 3.8, it starts to use Kernel 4.14.
If the host Linux version is under 4.11, we can see the issue and ss-server stoped. 
I tried to use Alpine 3.7.3 to build the image and it works fine in my host.
Hope to see if there is anything can do to fix this in code or provide different docker image for Linux Kernel that under 4.11 or above

**Comment by madeye** [comment]
Just remove `--fast-open` from your args.

**Comment by thirdteeth** [comment]
> Just remove `--fast-open` from your args.

I know how to fix it and I also know how to enable fast open in the docker container, as I described in the issue for me use Alpine 3.7.3 to build the image, fast open enabled in my server, I report this issue  to see if you can fix this in code or provide different docker image for Linux Kernel that under 4.11 or above, anyway your guys are the best
