### ISSUE TITLE
 libsodium-stable install failed !

### ISSUE THREAD

**Issue by aladaghlou** [shadowsocks/shadowsocks-libev#2572]
Hi.
First, I thank you for your helpful efforts.
But my problem:
I am trying install shadowsocks on CentOS 7 with this 3 lines command :

```
wget --no-check-certificate -O shadowsocks-libev.sh https://raw.githubusercontent.com/teddysun/shadowsocks_install/master/shadowsocks-libev.sh
chmod +x shadowsocks-libev.sh
./shadowsocks-libev.sh 2>&1 | tee shadowsocks-libev.log
```

when installing i get this error:

> checking for cc... no
> checking for cl.exe... no
> configure: error: in `/root/libsodium-stable':
> configure: error: no acceptable C compiler found in $PATH
> See `config.log' for more details
> [Error] libsodium-stable install failed.

Please help me for find better solution.

**Comment by HaskellZhangSong** [comment]
I think you did have proper C compiler and autotools installed on your machined. 
run
`$ sudo yum -y install gcc gcc-c++ autoconf automake make`
then try to build again.

**Comment by azatabd** [comment]
`sudo apt install gcc`

For ubuntu.

**Comment by azatabd** [comment]
> `sudo apt install gcc`
> 
> For ubuntu.

You also need to install the compiler package if you have not already done so

sudo apt install build-essential

Reboot after this.
