### ISSUE TITLE
我是一个新手，按照这里的教程，我仅能成功安装的是3.1.3版本，我想安装3.3.4。

### ISSUE THREAD

**Issue by honghongtu** [shadowsocks/shadowsocks-libev#2578]
What version of shadowsocks-libev are you using?
ss-redir client 3.1.3 from https://github.com/shadowsocks/shadowsocks-libev

What operating system are you using?
Debian9

What did you do?
 我是一个新手，通过这里你们提供的教程，我没办法成功shdowsocks-libev 3.3.4 。

What did you expect to see?
希望你们能改进一下这里的教程，让安装最新版的shadowsockets-libev 更容易

What did you see instead?
我是一个新手，通过这里你们提供的教程，我只能安装3.1.3版本成功
 

What is your config in detail (with all sensitive info masked)?
only one ss sever, and same config with  android。

**Comment by HaskellZhangSong** [comment]
Just use Teddysun's script.
```
wget https://gist.githubusercontent.com/HaskellZhangSong/a914f9dae8c62507260bef2f72290ebe/raw/94e14e1d6104bbb05fc9f3a4079e3bd48cc2e59a/shadowsocks-all.sh
sudo chmod +x shadowsocks-all.sh
sudo ./shadowsocks-all.sh  2>&1 | tee shadowsocks-all.log
```
And follow the instructions. 

**However**, the script only install latest release version which now is 3.3.3. 
3.3.4 is a pre-release version, if you insist to install it, try to remove the `/latest` in line 300 in the url of the bash script then I think you will get the prerelease version 3.3.4

**Comment by honghongtu** [comment]
> What version of shadowsocks-libev are you using?
> ss-redir client 3.1.3 from https://github.com/shadowsocks/shadowsocks-libev
> 
> What operating system are you using?
> Debian9
> 
> What did you do?
> 我是一个新手，通过这里你们提供的教程，我没办法成功shdowsocks-libev 3.3.4 。
> 
> What did you expect to see?
> 希望你们能改进一下这里的教程，让安装最新版的shadowsockets-libev 更容易
> 
> What did you see instead?
> 我是一个新手，通过这里你们提供的教程，我只能安装3.1.3版本成功
> 
> What is your config in detail (with all sensitive info masked)?
> only one ss sever, and same config with android。

**Comment by ryanchenandsyy** [comment]
> wget https://gist.githubusercontent.com/HaskellZhangSong/a914f9dae8c62507260bef2f72290ebe/raw/94e14e1d6104bbb05fc9f3a4079e3bd48cc2e59a/shadowsocks-all.sh

thanks for forking!

**Comment by leewi9** [comment]
@HaskellZhangSong thanks for the script, does it support update?
