### ISSUE TITLE
集成Brdgrd？

### ISSUE THREAD

**Issue by IlO0OlI** [shadowsocks/shadowsocks-libev#2579]
### What version of shadowsocks-libev are you using?
3.2.4

### What operating system are you using?
CentOS 7.6

[Shadowsocks是如何被检测和封锁的](https://gfw.report/blog/gfw_shadowsocks/zh.html)
[English Version: How China Detects and Blocks Shadowsocks](https://gfw.report/blog/gfw_shadowsocks)

是否考虑集成brdgrd？

**Comment by studentmain** [comment]
> ## Thanks
> We want to thank these people for research and helpful discussion on this topic:
>
> - Shadowsocks-libev developers

摘自第二个链接最下面，另外几个官方实现的惯例是只提供标准接口，不集成任何插件

**Comment by madeye** [comment]
Upgrade to the latest version and keep using AEAD ciphers.

Then everything should be fine.

**Comment by qwerttvv** [comment]
哪个正常的机器装Brdgrd？

我觉得Brdgrd更加容易识别，装上以后是此地无银三百两的意思啊

听了各位大佬的话，套上了cloak，目前稳的1b

另外，我自己之前的试验，感觉墙是不能识别AEAD的SS的，然而现在的策略是墙对于不能识别的流量，不会封服务端的IP，会直接干扰你的ip到服务端ip直接的连接，直接废你几分钟到几十分钟，然后在恢复，这个时间我观察来看是随机的……我当时一发现干扰就重拨号获取新的本地ip，后来太麻烦，找国内idc的机器中转，发现国内idc的ip出去到服务端，这一段儿墙不管的，我就本地干到国内idc，国内idc再干到国外服务端……

后来觉得听人劝吃饱饭，cloak大法好……
