### ISSUE TITLE
请问Ubuntu 16.04怎么从3.25版本升级呢？

### ISSUE THREAD

**Issue by myfenix** [shadowsocks/shadowsocks-libev#2580]
apt:
shadowsocks-libev is already the newest version (3.2.5-1~ppa2x).

snap:
snap "shadowsocks-libev" has no updates available

希望能有安全方便的方法能升级到当前3.34版本。
小白谢过。

**Comment by heiybb** [comment]
如果原来是apt安装的话可以自己手动编译安装新版本

**Comment by myfenix** [comment]
是说这四条script吗？
照做过一次，执行的时候花了好几分钟，翻江倒海了几百上千屏，什么也看不清，我不知道系统其他地方改动过什么没有，但shadowsocks-libev还是老样子。
所以没办法才到这里求助。

mkdir -p ~/build-area/
cp ./scripts/build_deb.sh ~/build-area/
cd ~/build-area
./build_deb.sh

**Comment by xcjiang** [comment]
优先用snap安装，readme里写的很清楚。

**Comment by qwerttvv** [comment]
https://packages.debian.org/search?keywords=shadowsocks-libev&searchon=names&suite=all&section=all

sid以及是334了，apt还是可以安装的，把sid加入源

**Comment by qwerttvv** [comment]
或者用snap也很方便，先卸载原来的
apt autoremove shadowsocks-libev

再安装snap
apt install snapd

在snap安装ss
snap install shadowsocks-libev --edge

其实都一样……

**Comment by qwerttvv** [comment]
不过我建议还是按照
https://github.com/shadowsocks/shadowsocks-libev#build-deb-package-from-source

自己编译自己装，紧随官方脚步，一有更新就马上自己来一发……盯住了commits，只要不是什么无关痛痒的，就必须来一发……强迫症

**Comment by myfenix** [comment]
感谢qwerttvv的帮助。

折腾四五个小时后，总算是成功升级了。

总结一下我的折腾过程：

1，使用snap，失败。

使用apt autoremove卸载老版本shadowsocks-libev后，还要再运行一次snap remove去除snap中的信息（因为以前尝试过用snap直接升级），之后snap提示安装成功，版本是3.33。

但问题是：snap安装的这个版本无法运行。systemctl找不到shadowsocks-libev的服务，直接运行ss-server也提示缺失组件无法运行。

而且翻看文档根本一头雾水不知道这个安装方法下，应该把config.json放在哪里。

可能和我的系统的具体情况有关。

没办法，snap remove shadowsocks-libev卸载。

2，使用apt，成功。

根据qwerttvv的提示，在debian.org找到以下地址，手动添加源到/etc/apt/sources.list文件：

deb http://ftp.debian.org/debian buster-backports main 
deb http://ftp.debian.org/debian stretch-backports-sloppy main
deb http://ftp.debian.org/debian bullseye main
deb http://ftp.debian.org/debian sid main

但是运行apt update提示新添加的这几个源缺少public key，无法使用。

----------------------------------------------
Err:13 http://ftp.debian.org/debian sid InRelease             
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 04EE7237B7D453EC  NO_PUBKEY 648ACFD622F3D138

W: GPG error: http://ftp.debian.org/debian sid InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 04EE7237B7D453EC  NO_PUBKEY 648ACFD622F3D138
E: The repository 'http://ftp.debian.org/debian sid InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
----------------------------------------------

使用Google找到几个答案，其中正确的解决方法是运行如下命令添加key:

apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 648ACFD622F3D138
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 04EE7237B7D453EC

再次运行apt install shadowsocks-libev，成功安装3.34。

复制config.json到/etc/shadowsocks-libev/config.json并成功运行。

systemctl status shadowsocks-libev 状态正常。

**Comment by qwerttvv** [comment]
我觉得apt和snap最简单，另外网上还有秋水的一键脚本，改一下获取版本就可以用最新beta，那个也行，就是得注意相关依赖，用那个不用看官方维护snap和debian，只要github上rls，马上就能装，完全不用等几天

不过官方这几个大佬很给力，snap和debian跟的也贼快，极友好
