### ISSUE TITLE
ubuntu 18.04 手动编译出错

### ISSUE THREAD

**Issue by xcjiang** [shadowsocks/shadowsocks-libev#2583]
第一步autogen.sh就报错了：
```
~/source/shadowsocks-libev# ./autogen.sh
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'auto'.
libtoolize: copying file 'auto/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
configure.ac:13: installing 'auto/ar-lib'
configure.ac:10: installing 'auto/compile'
configure.ac:21: installing 'auto/config.guess'
configure.ac:21: installing 'auto/config.sub'
configure.ac:12: installing 'auto/install-sh'
configure.ac:12: installing 'auto/missing'
configure.ac:244: error: required file 'libbloom/Makefile.in' not found
configure.ac:244: error: required file 'libcork/Makefile.in' not found
configure.ac:244: error: required file 'libipset/Makefile.in' not found
src/Makefile.am: installing 'auto/depcomp'
autoreconf: automake failed with exit status: 1

```

**Comment by qwerttvv** [comment]
这都7年前的一个老脚本啦哈哈

**Comment by Aniark** [comment]
`./autogen.sh`之前，先git` submodule update --init --recursive`

**Comment by quickhot** [comment]
可以编译通过。

**Comment by quickhot** [comment]
![image](https://user-images.githubusercontent.com/5475712/72505218-71861680-387a-11ea-9d79-8c4ae137d5e4.png)

**Comment by quickhot** [comment]
直接编译安装方法：
apt-get install --no-install-recommends build-essential autoconf libtool libssl-dev gawk debhelper init-system-helpers pkg-config asciidoc xmlto apg libpcre3-dev zlib1g-dev libev-dev libudns-dev libsodium-dev libmbedtls-dev libc-ares-dev libmbedtls-dev libc-ares-dev libsodium-dev automake

git clone https://github.com/shadowsocks/shadowsocks-libev.git

cd shadowsocks-libev/
**git submodule update --init**
./autogen.sh && ./configure && make
make install

**Comment by quickhot** [comment]
> `./autogen.sh`之前，先`git submodule update --init --recursive`

git submodule update --init

**Comment by twinfishxixi** [comment]
mark 一下！

**Comment by ryanchenandsyy** [comment]
> 直接编译安装方法：
> apt-get install --no-install-recommends build-essential autoconf libtool libssl-dev gawk debhelper init-system-helpers pkg-config asciidoc xmlto apg libpcre3-dev zlib1g-dev libev-dev libudns-dev libsodium-dev libmbedtls-dev libc-ares-dev libmbedtls-dev libc-ares-dev libsodium-dev automake
> 
> git clone https://github.com/shadowsocks/shadowsocks-libev.git
> 
> cd shadowsocks-libev/
> **git submodule update --init**
> ./autogen.sh && ./configure && make
> make install

thank you!

**Comment by mlgcpd** [comment]
> > `./autogen.sh`之前，先`git submodule update --init --recursive`
> 
> git submodule update --init

作者教程中带有`--recursive`
详见[https://github.com/shadowsocks/shadowsocks-libev/commit/3e8a57752a2e196a35cfcc8ac5d25ed7398d041f#diff-04c6e90faac2675aa89e2176d2eec7d8](url)
