### ISSUE TITLE
Need iOS build support

### ISSUE THREAD

**Issue by yzou** [shadowsocks/shadowsocks-libev#2584]
### What version of shadowsocks-libev are you using?
3.2.3

### What operating system are you using?
iOS 13

### What did you do?
I need to build tun2socks and shadowsocks-libev to iOS app

### What did you expect to see?
Works with tun2socks like on Android device

### What did you see instead?
Tun2socks has some Android only changes, can't work on iOS

### What is your config in detail (with all sensitive info masked)?
For example, the UDP handle is Android only, such as the --dnsgw option is only or Android, but the tun2socks code is using this option for none-Android device code.

shadowsocks-libev also need changes to work on iOS.

**Comment by qwerttvv** [comment]
be server？

**Comment by yzou** [comment]
> be server？

Integrate libev to iOS App
