### ISSUE TITLE
UDP中继功能没有正确的UDP NAT

### ISSUE THREAD

**Issue by lixin9311** [shadowsocks/shadowsocks-libev#259]
在给go版加udp relay功能的时候发现的。
每个udp请求ss-server都会新开一个端口转发到目的地址，这样虽然DNS没有问题，但是OpenVPN这样的应用就不行了。
ss-tunnel在udp模式下看起来每次也会用一个新端口与ss-server通讯。

**Comment by madeye** [comment]
所以 UDP Relay 部分需要有一个 LRU Cache 来缓存 NAT 记录，具体见 udprelay.c 和 cache.c 的相关实现。

**Comment by lixin9311** [comment]
现在我用的是1.6.1，不能用openvpn 难道后续版本有改动？changelog里面没见到

**Comment by lixin9311** [comment]
抱歉，编译了最新的2.1.4，有NAT的。
