### ISSUE TITLE
the implementation of QOS netfilter mark preservation is wrong

### ISSUE THREAD

**Issue by ghost** [shadowsocks/shadowsocks-libev#2591]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?

latest

### What operating system are you using?
ubuntu

### What did you do?
read the source code

### What did you expect to see?
remove QOS netfilter mark preservation implementation or rewrite it based on libpcap

### What did you see instead?
QOS netfilter mark preservation implementation is wrong.

Current implementation tries to get connmark with conntrack and set it to tos mark.

In my opnion, the author of this feature was confused about connmark and tos mark.

### What is your config in detail (with all sensitive info masked)?
average config

**Comment by babarosaM33** [comment]
program cannot get tos mark by libnetfilter_conntrack. conntrack-tools cannot get it either.
tos mark preservation should be developed based on libpcap. tcpdump can get tos mark from ingress package.
