### ISSUE TITLE
The connection kept being reset

### ISSUE THREAD

**Issue by yesme** [shadowsocks/shadowsocks-libev#2593]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
I have two versions of SS-libev installed on two AWS EC2 servers. The old one has v3.2.4 on it, while the new one has v3.3.3. I have no problem with 3.2.4, but 3.3.3 doesn't work for me.

### What operating system are you using?
Ubuntu Server 18.04.3

### What did you do?
I use Shadowsocks 4.8.7 on an Android device to connect to the SS server with obfs plugin enabled on both ends.

### What did you expect to see?
Everything should work smoothly as the log (/var/log/syslog) I've seen on the v3.2.4 server:
Jan 17 16:30:16 ip-172-3-3-80 /usr/local/bin/ss-server[789]: accept a connection
Jan 17 16:30:16 ip-172-3-3-80 /usr/local/bin/ss-server[789]: [53796] connect to 8.8.8.8:53
Jan 17 16:30:16 ip-172-3-3-80 /usr/local/bin/ss-server[789]: remote connected
Jan 17 16:30:16 ip-172-3-3-80 /usr/local/bin/ss-server[789]: accept a connection
Jan 17 16:30:16 ip-172-3-3-80 /usr/local/bin/ss-server[789]: [53796] connect to 8.8.8.8:53
Jan 17 16:30:16 ip-172-3-3-80 /usr/local/bin/ss-server[789]: remote connected
Jan 17 16:30:16 ip-172-3-3-80 /usr/local/bin/ss-server[789]: accept a connection
Jan 17 16:30:16 ip-172-3-3-80 /usr/local/bin/ss-server[789]: [53796] connect to 8.8.8.8:53
Jan 17 16:30:16 ip-172-3-3-80 /usr/local/bin/ss-server[789]: accept a connection
Jan 17 16:30:16 ip-172-3-3-80 /usr/local/bin/ss-server[789]: [53796] connect to 8.8.8.8:53
Jan 17 16:30:16 ip-172-3-3-80 /usr/local/bin/ss-server[789]: remote connected
Jan 17 16:30:16 ip-172-3-3-80 /usr/local/bin/ss-server[789]: remote connected
Jan 17 16:30:16 ip-172-3-3-80 /usr/local/bin/ss-server[789]: accept a connection
Jan 17 16:30:16 ip-172-3-3-80 /usr/local/bin/ss-server[789]: [53796] connect to 8.8.8.8:53
Jan 17 16:30:16 ip-172-3-3-80 /usr/local/bin/ss-server[789]: remote connected

### What did you see instead?
The connection kept on-and-off on the v3.3.3 server:
Jan 17 16:24:29 ip-172-2-7-136 /usr/local/bin/ss-server[1373]: [20061] connect to 8.8.8.8:53
Jan 17 16:24:29 ip-172-2-7-136 /usr/local/bin/ss-server[1373]: new connection to remote, 3 opened remote connections
Jan 17 16:24:29 ip-172-2-7-136 /usr/local/bin/ss-server[1373]: new connection from client, 4 opened client connections
Jan 17 16:24:29 ip-172-2-7-136 /usr/local/bin/ss-server[1373]: [20061] connect to 8.8.8.8:53
Jan 17 16:24:29 ip-172-2-7-136 /usr/local/bin/ss-server[1373]: new connection to remote, 4 opened remote connections
Jan 17 16:24:29 ip-172-2-7-136 /usr/local/bin/ss-server[1373]: close a connection to remote, 3 opened remote connections
Jan 17 16:24:29 ip-172-2-7-136 /usr/local/bin/ss-server[1373]: close a connection from client, 3 opened client connections
Jan 17 16:24:29 ip-172-2-7-136 /usr/local/bin/ss-server[1373]: new connection from client, 4 opened client connections
Jan 17 16:24:29 ip-172-2-7-136 /usr/local/bin/ss-server[1373]: [20061] connect to www.google.com:443
Jan 17 16:24:29 ip-172-2-7-136 /usr/local/bin/ss-server[1373]: found address name v4 address www.google.com
Jan 17 16:24:29 ip-172-2-7-136 /usr/local/bin/ss-server[1373]: found address name v6 address www.google.com
Jan 17 16:24:29 ip-172-2-7-136 /usr/local/bin/ss-server[1373]: successfully resolved www.google.com
Jan 17 16:24:29 ip-172-2-7-136 /usr/local/bin/ss-server[1373]: new connection to remote, 4 opened remote connections
Jan 17 16:24:31 ip-172-2-7-136 /usr/local/bin/ss-server[1373]: close a connection to remote, 3 opened remote connections
Jan 17 16:24:31 ip-172-2-7-136 /usr/local/bin/ss-server[1373]: close a connection from client, 3 opened client connections
Jan 17 16:24:31 ip-172-2-7-136 /usr/local/bin/ss-server[1373]: new connection from client, 4 opened client connections
Jan 17 16:24:31 ip-172-2-7-136 /usr/local/bin/ss-server[1373]: [20061] connect to 8.8.8.8:53
Jan 17 16:24:31 ip-172-2-7-136 /usr/local/bin/ss-server[1373]: new connection to remote, 4 opened remote connections
Jan 17 16:24:31 ip-172-2-7-136 /usr/local/bin/ss-server[1373]: close a connection to remote, 3 opened remote connections
Jan 17 16:24:31 ip-172-2-7-136 /usr/local/bin/ss-server[1373]: close a connection from client, 3 opened client connections
Jan 17 16:24:31 ip-172-2-7-136 /usr/local/bin/ss-server[1373]: new connection from client, 4 opened client connections

### What is your config in detail (with all sensitive info masked)?

{
    "server":"0.0.0.0",
    "server_port":20061,
    "password":"********",
    "timeout":3000,
    "user":"nobody",
    "method":"chacha20-ietf-poly1305",
    "fast_open":true,
    "nameserver":"8.8.8.8",
    "mode":"tcp_and_udp",
    "plugin":"obfs-server",
    "plugin_opts":"obfs=http"
}

**Comment by madeye** [comment]
From your log, everything thing works well. Several connections are established to google and no reset at all.

**Comment by yesme** [comment]
> From your log, everything thing works well. Several connections are established to google and no reset at all.

Thanks for the prompt reply. On 3.2.4, I saw the connection was quite stable (no close/reopen actions), while it's on-and-off on 3.3.3 - I didn't do anything on my phone so to speak.

Things works fine on my windows client though - a stable connection.
