### ISSUE TITLE
Is a bug at line 275 in the plugin.c?

### ISSUE THREAD

**Issue by larry19840909** [shadowsocks/shadowsocks-libev#2599]
Is a bug at line [275 ](https://github.com/shadowsocks/shadowsocks-libev/blob/03181689380e2a4f8c5cf93f36dab7196764e263/src/plugin.c#L275)in the plugin.c?

getcwd() will return NULL when it fails, and will not go to the code block in {} when it succeeds.

I did not understand the logical meaning here, but intuitively it should be wrong writing.

**Comment by madeye** [comment]
Thanks, this part of code is kind of dead as very few platform doesn't have `get_current_dir_name`.
