### ISSUE TITLE
update libev

### ISSUE THREAD

**Issue by EricMzky** [shadowsocks/shadowsocks-libev#2601]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
3.3.0

### What operating system are you using?
centos

### What did you do?
learnning

### What is your config in detail (with all sensitive info masked)?
The current version is 3.3.0, How do I upgrade to the latest version?

thanks

**Comment by qwerttvv** [comment]
old way, reinstall...that all
