### ISSUE TITLE
COULD NOT MAKE .deb ON DEBIAN 9

### ISSUE THREAD

**Issue by willy666rumster** [shadowsocks/shadowsocks-libev#2602]
### What version of shadowsocks-libev are you using?
shadowsocks-libev-3.3.4

### What operating system are you using?
Linux 4.9.0-11-amd64 #1 SMP Debian 4.9.189-3+deb9u2 (2019-11-11) x86_64 GNU/Linux

### What did you do?
 ~/build_deb.sh

### What did you expect to see?
Installed package
### What did you see instead?
gbp:error: 'debuild -i -I -us -uc' failed: it exited with 29

### What is your config in detail (with all sensitive info masked)?
don't have yet

**Comment by qwerttvv** [comment]
apt-get install --no-install-recommends devscripts equivs git gettext build-essential autoconf libtool libpcre3-dev asciidoc xmlto libev-dev libc-ares-dev automake libmbedtls-dev libsodium-dev libssl-dev gawk debhelper dh-systemd init-system-helpers pkg-config zlib1g-dev libudns-dev
    cd temp666
    git clone https://github.com/shadowsocks/shadowsocks-libev.git
    cd shadowsocks-libev
    git submodule update --init
    mk-build-deps --root-cmd sudo --install --tool "apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends -y"
    ./autogen.sh && dpkg-buildpackage -b -us -uc
    cd ..
    dir

**Comment by qwerttvv** [comment]
apt install lsb-release
    apt-get dist-upgrade -t $(lsb_release -sc)-backports -y

backports is better?

**Comment by qwerttvv** [comment]
actually, i just use this to myself, its the best way to use with debian....

    apt install -t sid shadowsocks-libev -y

of course, you shoud add the source first
