### ISSUE TITLE
ERROR: server recv: Connection reset by peer

### ISSUE THREAD

**Issue by qwerttvv** [shadowsocks/shadowsocks-libev#2603]
i have searched a lot about this error and tried to change the setting but did not improve it.

### What version of shadowsocks-libev are you using?
shadowsocks-libev 3.3.4 with cloak 2.1.3

### What operating system are you using?
debian-server
windows-client (for the test, there is only one client)

### What did you do?
try to set timeout for ss-client, ss-server, cloak-server, cloak-client

### What did you expect to see?
emmmm....no error, no stuck

### What did you see instead?
when i got this error, process(stream?) will get stuck.
when url AAA is stuck, you can open a new browser tab to browse a new url BBB, there is no problem browsing the url BBB, very fast, very smooth. but AAA still stuck

### What is your config in detail (with all sensitive info masked)?
SS server
```json
{
	"server":["127.0.0.1"],
	"mode":"tcp_only",
	"server_port":44444,
	"password":"$$$$",
	"timeout":300,
	"method":"xchacha20-ietf-poly1305",
	"fast_open":false,
	"nameserver":"8.8.8.8",
	"plugin": "/usr/local/bin/ck-server",
	"plugin_opts": "/usr/local/bin/ckserver.json"
}
```

Cloak server
```json
{
  "BypassUID": [
    "$$$$$$$$$$$$"
  ],
  "BindAddr":[":443",":80"],
  "RedirAddr": "$$$$$",
  "PrivateKey": "$$$$$$$$$$$$$$$",
  "AdminUID": "$$$$$$$",
  "DatabasePath": "/usr/local/bin/userinfo.db",
  "StreamTimeout": 300
}
```

ss client
timeout 30

cloak client
StreamTimeout=300

debian
/etc/sysctl.conf
net.ipv4.tcp_fin_timeout = 30
net.ipv4.tcp_keepalive_time = 1200

**Comment by DQLin** [comment]
Try to change the server ip to the public ip?
