### ISSUE TITLE
default error rate should be lower

### ISSUE THREAD

**Issue by babarosaM33** [shadowsocks/shadowsocks-libev#2607]
https://github.com/shadowsocks/shadowsocks-libev/blob/b6a83d94971e0cc5210584bbeb0fee47b7846d67/src/crypto.h#L75-L84

https://github.com/shadowsocks/shadowsocks-libev/blob/b6a83d94971e0cc5210584bbeb0fee47b7846d67/src/ppbloom.c#L43-L50

（1-1e-6）^5e5=0.606

**Comment by babarosaM33** [comment]
there are two seperate bloom filters.
Under default settings, if first is full, it would be checked 5e5 times before reset.
the false alarm rate of the full slot is 1e-6.
As a result, the possibility of one false alarm occurrence is （1-1e-6）^5e5=0.606.

**Comment by madeye** [comment]
According to your calculation, among 5e^5 connections, the possibility of one connection get closed incorrectoy is 0.6. So what's wrong here?

This is already much lower than a network error rate.

**Comment by babarosaM33** [comment]
because the possibility of connection get closed is still 1e-6.

the exact illustration of such process is Poisson process.

the connection rate is 3 per second.
the error rate of each connection is 1e-6.

the estimation of error occurence of 3 days is 1(1e-6*3*3600*24*3)=0.7777
