### ISSUE TITLE
安卓手机中 PAC模式下 无法打开Play商店 和youtube 等大部分APP

### ISSUE THREAD

**Issue by xidcn** [shadowsocks/shadowsocks-libev#2613]
安卓手机中 PAC模式下 无法打开Play商店 和youtube 等大部分APP，不知道是不是个例

**Comment by terrytw** [comment]
AFAIK, there is no PAC mode in the official shadowsocks android client. 
If you are using shadowsocks android, please report to https://github.com/shadowsocks/shadowsocks-android/issues
Otherwise, report to the developer of that app you are using.
