### ISSUE TITLE
Protocol being detected and blocked by the GFW

### ISSUE THREAD

**Issue by twifty** [shadowsocks/shadowsocks-libev#2617]
Over the last week I have noticed my connections (I'm using SurfShark servers) being dropped. The IPs are still pingable but packets sent from the server are not received. On most servers, this block will occur within 60 seconds, on others it may take a few hours.

There is an excellent article here (https://ntc.party/t/how-china-detects-and-blocks-shadowsocks/289) describing the problem.

Are the devs aware of the problem and are there any solutions in the works?

**Comment by madeye** [comment]
Read the report again, especially the "thanks" section.
