### ISSUE TITLE
ss不稳定，掉线unexpected end of stream on ...

### ISSUE THREAD

**Issue by k19421** [shadowsocks/shadowsocks-libev#2625]
### What version of shadowsocks-libev are you using?
shadowsocks-libev 3.3.3

### What operating system are you using?
Centos 6 x86 bbr 

### What did you do?
sudo nohup /usr/local/bin/ss-server -v -c /etc/shadowsocks-libev/config.json &

### What did you expect to see?
shadowsocks working stably

### What did you see instead?
掉线不稳定，使用一段时间后掉线，需要等待三四分钟再连接
点击测试时安卓客户端经常显示:
失败：unexpected end of stream on...
或者
失败： Read error: ssl=xxxxx: Failure in SSL library, usually a protocol error...

### What is your config in detail (with all sensitive info masked)?
{
    "server":"0.0.0.0",
    "server_port":1024,
    "password":"xxxx",
    "timeout":600,
    "user":"nobody",
    "method":"aes-256-gcm",
    "fast_open":false,
    "nameserver":"8.8.8.8",
    "mode":"tcp_and_udp"
}

**Comment by k19421** [comment]
17:51:09 INFO: UDP relay enabled
 17:51:09 INFO: initializing ciphers... aes-256-gcm
 17:51:09 INFO: using nameserver: 8.8.8.8
 17:51:09 INFO: tcp server listening at 0.0.0.0:1024
 17:51:09 INFO: udp server listening at 0.0.0.0:1024
 17:51:30 INFO: [udp] server receive a packet
 17:51:30 INFO: [1024] [udp] cache miss: dns.google:53 <-> 120.84.9.121:14007
 17:51:30 INFO: found address name v4 address dns.google
 17:51:30 INFO: found address name v6 address dns.google
 17:51:30 INFO: [udp] remote receive a packet
 17:51:31 INFO: new connection from client, 1 opened client connections
 17:51:31 INFO: [1024] connect to www.google.com:443
 17:51:31 INFO: found address name v4 address www.google.com
 17:51:31 INFO: found address name v6 address www.google.com
 17:51:31 INFO: successfully resolved www.google.com
 17:51:31 INFO: new connection to remote, 1 opened remote connections
 17:51:33 INFO: [udp] server receive a packet
 17:51:33 INFO: [1024] [udp] cache miss: dns.google:53 <-> 120.84.9.121:22064
 17:51:33 INFO: found address name v6 address dns.google
 17:51:33 INFO: found address name v4 address dns.google
 17:51:33 INFO: [udp] remote receive a packet
 17:51:35 INFO: [udp] server receive a packet
 17:51:35 INFO: [1024] [udp] cache miss: dns.google:53 <-> 120.84.9.121:10110
 17:51:35 INFO: found address name v4 address dns.google
 17:51:35 INFO: found address name v6 address dns.google
 17:51:35 INFO: [udp] remote receive a packet
 17:51:41 INFO: close a connection to remote, 0 opened remote connections
 17:51:41 INFO: close a connection from client, 0 opened client connections
 17:51:44 INFO: [udp] server receive a packet
 17:51:44 INFO: [1024] [udp] cache miss: dns.google:53 <-> 120.84.9.121:43081
 17:51:44 INFO: found address name v4 address dns.google
 17:51:44 INFO: found address name v6 address dns.google
 17:51:44 INFO: [udp] remote receive a packet
 17:52:19 INFO: [udp] server receive a packet
 17:52:19 INFO: [1024] [udp] cache miss: dns.google:53 <-> 120.84.9.121:13119
 17:52:19 INFO: found address name v6 address dns.google
 17:52:19 INFO: found address name v4 address dns.google
 17:52:19 INFO: [udp] remote receive a packet
 17:53:08 INFO: [udp] server receive a packet
 17:53:08 INFO: [1024] [udp] cache miss: dns.google:53 <-> 120.84.9.121:10849
 17:53:08 INFO: found address name v6 address dns.google
 17:53:08 INFO: found address name v4 address dns.google
 17:53:08 INFO: [udp] remote receive a packet
 17:59:16 INFO: [udp] server receive a packet
 17:59:16 INFO: [1024] [udp] cache miss: dns.google:53 <-> 120.84.9.121:62346
 17:59:16 INFO: found address name v4 address dns.google
 17:59:16 INFO: found address name v6 address dns.google
 17:59:16 INFO: [udp] remote receive a packet
 17:59:17 INFO: [udp] server receive a packet
 17:59:17 INFO: [1024] [udp] cache miss: dns.google:53 <-> 120.84.9.121:9977
 17:59:17 INFO: found address name v4 address dns.google
 17:59:17 INFO: found address name v6 address dns.google
 17:59:17 INFO: [udp] remote receive a packet
 18:01:00 INFO: [udp] server receive a packet
 18:01:00 INFO: [1024] [udp] cache miss: dns.google:53 <-> 120.84.9.121:10645
 18:01:00 INFO: found address name v6 address dns.google
 18:01:00 INFO: found address name v4 address dns.google
 18:01:00 INFO: [udp] remote receive a packet
 18:01:00 INFO: [udp] server receive a packet
 18:01:00 INFO: [1024] [udp] cache miss: dns.google:53 <-> 120.84.9.121:25706
 18:01:00 INFO: found address name v4 address dns.google
 18:01:00 INFO: found address name v6 address dns.google
 18:01:00 INFO: [udp] remote receive a packet
 18:01:30 INFO: [udp] connection timeout
 18:01:30 INFO: [udp] one connection freed
 18:01:33 INFO: [udp] connection timeout
 18:01:33 INFO: [udp] one connection freed
 18:01:35 INFO: [udp] connection timeout
 18:01:35 INFO: [udp] one connection freed
 18:01:44 INFO: [udp] connection timeout
 18:01:44 INFO: [udp] one connection freed
 18:02:19 INFO: [udp] connection timeout
 18:02:19 INFO: [udp] one connection freed
 18:03:08 INFO: [udp] connection timeout
 18:03:08 INFO: [udp] one connection freed

**Comment by k19421** [comment]
* [x IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Encrypt method:AES-256-GCM
* Route
  * [ ] All
  * [ ] Bypass LAN
  * [ ] Bypass China
  * [x] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Apps VPN mode
  * [ ] Bypass mode
* Remote DNS: dns.google
* [x] DNS over UDP
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open

安卓端配置：
![WechatIMG54](https://user-images.githubusercontent.com/3615533/74227521-98a8fa00-4cf9-11ea-889d-dc7a27729626.jpeg)

**Comment by vhp8rc7p** [comment]
same problem
latest release（apt install）on  Debian 4.9.189-3+deb9u2

**Comment by yiguihai** [comment]
你用的是国内1m服务器搭建的吗？😂
