### ISSUE TITLE
[connect error] While Conf is Correct

### ISSUE THREAD

**Issue by RebelliousWhiz** [shadowsocks/shadowsocks-libev#2632]
### What version of shadowsocks-libev are you using?

3.3.4

### What operating system are you using?

ubuntu 18.04

### What did you do?

**1. Set up shadowsocks-manager and shadowsocks-libev on main_server and second_server. Configs for ss-manager and ssmgr are exactly the same.**

Conf for ss-manager:

```
{
    "timeout":60,
    "method":"aes-256-gcm",
    "mode":"tcp_and_udp"
}
```

Conf for ssmgr:

```
{
  "type": "s",
  "shadowsocks": {
    "address": "127.0.0.1:2000"
  },
  "manager": {
    "address": "0.0.0.0:14600",
    "password": "password"
  },
  "db": "db.sqlite"
}
```
**2. Setup webgui on main_serever.**

**3. Connect second_server with main_server webgui.**

**4. create an account without a user at port 18600 for both servers.**

### What did you expect to see?

18600 port on both servers are working fine with normal logs

### What did you see instead?

main_server is working fine. The ss-server on second_server log keeps telling [connect: Invalid argument] and [connect error]s. **However, the second_server 18600 port can be connected without problem:**

```
● ss-manager.service - ss-manager
   Loaded: loaded (/etc/systemd/system/ss-manager.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2020-02-14 11:29:01 HKT; 29min ago
 Main PID: 809 (ss-manager)
    Tasks: 2 (limit: 1107)
   CGroup: /system.slice/ss-manager.service
           ├─809 /usr/bin/ss-manager -c /home/user/server/ss-manager/config.json --manager-address 127.0.0.1:2000
           └─964 ss-server --manager-address 127.0.0.1:2000 -f /home/user/.shadowsocks/.shadowsocks_18600.pid -c /home/user/.shadowsocks/.shadowsocks_18600.conf -t 60 -u -s 0.0.0.0

Feb 14 11:57:58 hk2 ss-server[964]: connect error
Feb 14 11:58:28 hk2 ss-server[964]: connect: Invalid argument
Feb 14 11:58:28 hk2 ss-server[964]: connect error
Feb 14 11:58:28 hk2 ss-server[964]: connect: Invalid argument
Feb 14 11:58:28 hk2 ss-server[964]: connect error
Feb 14 11:58:28 hk2 ss-server[964]: connect: Invalid argument
Feb 14 11:58:28 hk2 ss-server[964]: connect error
Feb 14 11:58:28 hk2 ss-server[964]: connect: Invalid argument
Feb 14 11:58:28 hk2 ss-server[964]: connect error
Feb 14 11:58:51 hk2 ss-server[964]: remote recv: Connection reset by peer
```

I checked the /home/user/.shadowsocks/.shadowsocks_18600.conf, it seems OK:

```
{
"server_port":18600,
"password":"password",
"method":"aes-256-gcm"
}
```

Please take a look at this, thanks!

**Comment by RebelliousWhiz** [comment]
As instructed by ss-manager maintainer @Gyteng, I used the command line instead of the config file for ss-manager. However, the problem persists:

`/usr/bin/ss-manager -m aes-256-gcm -u --manager-address "127.0.0.1:2000`

So I created a new conf for ss-server, and I found the problem is not because of the ss-manager but ss-server itself.

new_conf:

```
{
    "server":"0.0.0.0",
    "server_port":15777,
    "nameserver":"8.8.8.8",
    "mtu":1500,
    "password":"password",
    "timeout":30,
    "udp_timeout":30,
    "reuse_port":true,
    "dscp":"EF",
    "mode":"tcp_and_udp",
    "no_delay":true,
    "method":"aes-256-gcm"
}
```

I ran new_conf separately as a standalone process, and it appears the problem persists:

```
$ ss-server -c config.json
 2020-02-15 12:23:01 INFO: UDP relay enabled
 2020-02-15 12:23:01 INFO: enable TCP no-delay
 2020-02-15 12:23:01 INFO: initializing ciphers... aes-256-gcm
 2020-02-15 12:23:01 INFO: using nameserver: 8.8.8.8
 2020-02-15 12:23:01 INFO: tcp server listening at 0.0.0.0:15777
 2020-02-15 12:23:01 INFO: tcp port reuse enabled
 2020-02-15 12:23:01 INFO: udp server listening at 0.0.0.0:15777
 2020-02-15 12:23:01 INFO: udp port reuse enabled
 2020-02-15 12:23:19 ERROR: connect: Invalid argument
 2020-02-15 12:23:19 ERROR: connect error
 2020-02-15 12:23:19 ERROR: connect: Invalid argument
 2020-02-15 12:23:19 ERROR: connect error
 2020-02-15 12:23:19 ERROR: connect: Invalid argument
 2020-02-15 12:23:19 ERROR: connect error
 2020-02-15 12:23:19 ERROR: connect: Invalid argument
 2020-02-15 12:23:19 ERROR: connect error
 2020-02-15 12:23:49 ERROR: connect: Invalid argument
 2020-02-15 12:23:49 ERROR: connect error
 2020-02-15 12:23:49 ERROR: connect: Invalid argument
 2020-02-15 12:23:49 ERROR: connect error
 2020-02-15 12:23:49 ERROR: connect: Invalid argument
 2020-02-15 12:23:49 ERROR: connect error
 2020-02-15 12:23:49 ERROR: connect: Invalid argument
 2020-02-15 12:23:49 ERROR: connect error
...
```

I am using shadowsocks-windows 4.1.9.2 for the client.

And also, I use PPA from https://launchpad.net/~fsgmhoward/+archive/ubuntu/shadowsocks-libev. This repository uses the latest codes from GitHub, which shouldn't be an issue.

**Comment by madeye** [comment]
I cannot reproduce your problem with the same config.

It looks related to your system or environment. Try the same config on other environments.

**Comment by RebelliousWhiz** [comment]
OK, I know what's going on...

On my PC I use Proxifier to handle some connections. And there's a process called spoolsv.exe every once a while. Each time it tries to make a connection, the Proxifier redirects the connection to shadowsocks-windows.

I am not sure what's going on with that process, but after I removed it from the proxy list, there's no [connect error] anymore.

Thanks for your support!
