### ISSUE TITLE
shadowsocks-libev snap can't find custom downloaded plugin.

### ISSUE THREAD

**Issue by zeyangl** [shadowsocks/shadowsocks-libev#2633]
shadowsocks-libev snap can't find custom downloaded plugin.
I tried running it with v2ray-plugin binary downloaded from github, but the snap version of ss-server just doesn't seem to find v2ray-plugin anywhere. I tried putting the binary in /usr/local/bin, in ~/ or  in ~/snap/shadowsocks-libev. Just doesn't work.

**Comment by Frank94chan** [comment]
you should put v2ray-plugin in ~/snap/shadowsocks-libev/ANYPATH/v2ray-plugin then use aboslutely address in shadowsocks-libev config file.

in my case, the following works.

```
# ls ~/snap/shadowsocks-libev/ss-libev/v2ray-plugin 
/root/snap/shadowsocks-libev/ss-libev/v2ray-plugin

# cat ~/snap/shadowsocks-libev/ss-libev/v2ray-nginx.json
"plugin":"/root/snap/shadowsocks-libev/ss-libev/v2ray-plugin",

# systemctl status shadowsocks-libev-server@v2ray-nginx.service                                   
● shadowsocks-libev-server@v2ray-nginx.service - Shadowsocks-Libev Custom Server Service for v2ray/nginx
   Loaded: loaded (/lib/systemd/system/shadowsocks-libev-server@.service; indirect; vendor preset: enabled)
   Active: active (running) since Fri 2020-02-21 13:14:56 UTC; 16s ago
 Main PID: 5257 (ss-server)
    Tasks: 7 (limit: 1108)
   CGroup: /system.slice/system-shadowsocks\x2dlibev\x2dserver.slice/shadowsocks-libev-server@v2ray-nginx.service
           ├─5257 /snap/shadowsocks-libev/508/bin/ss-server -c /root/snap/shadowsocks-libev/ss-libev/v2ray-nginx.json
           └─5300 /root/snap/shadowsocks-libev/ss-libev/v2ray-plugin --fast-open
```

**Comment by zeyangl** [comment]
Thanks for the detailed explanation. This is definitely not obvious for
those not familia with snap peculiarities. Wish it could be in the
documentation.

**Comment by zeyangl** [comment]
Hate to reopen this but it's still not working for me. ubuntu 18.04 vps
Steps I did after a clean install, running as root:
snap install shadowsocks-libev
wget v2ray-plugin, copy it to /root/snap/shadowsocks-libev/common/v2ray-plugin
in ~/, run   
```shadowsocks-libev.ss-server -p port -k password --plugin /root/snap/shadowsocks-libev/common/v2ray --plugin-opts server```
this is what I get:
```
 2020-03-31 04:56:10 INFO: plugin "/root/snap/shadowsocks-libev/common/v2ray-plugin" enabled
 2020-03-31 04:56:10 INFO: initializing ciphers... chacha20-ietf-poly1305
 2020-03-31 04:56:10 INFO: tcp server listening at 127.0.0.1:43211
 2020-03-31 04:56:10 INFO: running from root user
Permission denied
 2020-03-31 04:56:10 ERROR: plugin service exit unexpectedly
 2020-03-31 04:56:10 INFO: error on terminating the plugin.
```

Note the error Permission denied, plugin service exit unexpectedly. I was able to run the v2ray-plugin indepednently with no problem. Very strange.

**Comment by zenmaster-cd** [comment]
@zeyangl mabye you path error  isn't /root/snap/shadowsocks-libev/common/v2ray ought /root/snap/shadowsockslibev/common/v2ray-plugin

**Comment by zenmaster-cd** [comment]
chmod +x /root/snap/shadowsocks-libev/common/v2ray-plugin

**Comment by zenmaster-cd** [comment]
@zeyangl  chmod +x /root/snap/shadowsocks-libev/common/v2ray-plugin

**Comment by kopstill** [comment]
I got the same problem, have you resolved this? thx

**Comment by kopstill** [comment]
> I got the same problem, have you resolved this? thx

@Frank94chan With you solution above I fixed this finally, thank you.
