### ISSUE TITLE
如何连入shadowsocks时同时保有Client本地LAN的连线能力？

### ISSUE THREAD

**Issue by MrFrankLiao** [shadowsocks/shadowsocks-libev#2638]
我目前本地有一些架在LAN的内部网站，但是连入远端的Shadowsocks Server後就无法连到了，有什麽设定可以解决这个问题呀？

**Comment by yiguihai** [comment]
选择绕过局域网

**Comment by MrFrankLiao** [comment]
具体上我需要从哪边下手呢？有什麽配置的关键字让小弟去研究一下吗？

是从shadowsocks设定下手吗

**Comment by LBYPatrick** [comment]
按照地址绕过就可以了，这个在客户端上操作 (同姓可就太骚了)

**Comment by milleyin** [comment]
`bypass-tun = 10.0.0.0/8, 127.0.0.0/24, 172.0.0.0/8, 192.168.0.0/16`
`[Rule]
DOMAIN-SUFFIX,www.xxxx.com,DIRECT`
