### ISSUE TITLE
Debian repo problem?

### ISSUE THREAD

**Issue by nodje** [shadowsocks/shadowsocks-libev#264]
Hi,

I just got 
```
W: Failed to fetch http://shadowsocks.org/debian/dists/wheezy/Release  Unable to find expected entry 'main/binary-armhf/Packages' in Release file (Wrong sources.list entry or malformed file)
```
while trying to install shadowsocks-libev on a Raspberry.

**Comment by madeye** [comment]
Raspberry is not supported.

**Comment by nodje** [comment]
Sorry, I based my assumption on https://github.com/shadowsocks/shadowsocks-libev/issues/163.
So I guess building from source still works, right?
