### ISSUE TITLE
编译的bug，及解决方法

### ISSUE THREAD

**Issue by tianlichunhong** [shadowsocks/shadowsocks-libev#2642]
最新的代码（2020年2月25日下载的）通过如下编译，出错：
git clone https://github.com/shadowsocks/shadowsocks-libev.git
cd shadowsocks-libev
./autogen.sh && ./configure && make
make install
编译会出错。提示找不到libbloom，libcork，libipset目录下的文件。
原因是该shadowsocks-libev下就没有这三个文件夹。
所以需要在目录下：
git clone https://github.com/shadowsocks/libbloom.git
另外的libcork，libipset两个文件夹不能用 https://github.com/shadowsocks/libcork.git，和 https://github.com/shadowsocks/libipset.git的，否则编译还是会出错。需要在旧的shadowsocks-libev原代码目录下找，拷贝过来。
这个可能随时作者在那个地方没有设置好导致的吧。供参考！

**Comment by lixingcong** [comment]
原本的README.md有一行

```
git submodule update --init --recursive
```

后来不知道为什么被删除了

**Comment by tianlichunhong** [comment]
> 原本的README.md有一行
> 
> ```
> git submodule update --init --recursive
> ```
> 
> 后来不知道为什么被删除了
> 
> [3e8a577#diff-04c6e90faac2675aa89e2176d2eec7d8](https://github.com/shadowsocks/shadowsocks-libev/commit/3e8a57752a2e196a35cfcc8ac5d25ed7398d041f#diff-04c6e90faac2675aa89e2176d2eec7d8)

确实运行这行就行了。感谢!
