### ISSUE TITLE
ss-redir代理是监听tcp、udp协议，做vpn的前置代理吗？

### ISSUE THREAD

**Issue by Angel0726** [shadowsocks/shadowsocks-libev#2644]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
3.1.3

### What operating system are you using?
kodachi base on xubuntu

### What did you do?
Successlly  implament  transparent proxy based on ss-redir with ss-tproxy 

### What did you expect to see?
i want implament the proxy chains ss-redir-->vpn--->tor

### What did you see instead?
I do not know how put ss-redir in first layer

**Comment by Angel0726** [comment]
环境：vmware安装kodachi
目标：使用多重代理，使用ss-redir做vpn与tor的前置代理。整个结构ss-redir---->vpn------>tor----->

**Comment by dujianchi** [comment]
@Angel0726 解决了吗？我也想搞一个前置代理，怎么操作啊？
