### ISSUE TITLE
ss-tunnel dns查询，能否走tcp协议

### ISSUE THREAD

**Issue by 0neday** [shadowsocks/shadowsocks-libev#2645]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
3.3.4

### What operating system are you using?
huawei ONT device, WAP(Dopra Linux) ,  with arm_cortex-a9+vfpv3 cpu

### What did you do?
ss-tunnel 走 tcp协议

### What is your config in detail (with all sensitive info masked)?
ss-tunnel  必须要加 -u 选项，才能查到dns解析。
日志显示udp connection

![WeChat Screenshot_20200229150828](https://user-images.githubusercontent.com/15697803/75602994-6a068e00-5b05-11ea-972f-862c07d0b67c.png)
### shadowsocks-windows client 测试结果
没有显示udp connection

![WeChat Screenshot_20200229164133](https://user-images.githubusercontent.com/15697803/75604391-26b31c00-5b13-11ea-8255-67658d0fe6bc.png)

如何让ss-tunnel 走 tcp 协议查询 dns 解析

**Comment by lixingcong** [comment]
与ss-tunnel无关

**Comment by 0neday** [comment]
@lixingcong  找到其他方法来解决dns udp查询问题， [dns over https](https://github.com/aarond10/https_dns_proxy)

**Comment by Angel0726** [comment]
> Please answer these questions before submitting your issue. Thanks!
> 
> (Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)
> 
> (PS, you can remove 3 lines above, including this one, before post your issue.)
> 
> ### What version of shadowsocks-libev are you using?
> 3.3.4
> 
> ### What operating system are you using?
> huawei ONT device, WAP(Dopra Linux) , with arm_cortex-a9+vfpv3 cpu
> 
> ### What did you do?
> ss-tunnel 走 tcp协议
> 
> ### What did you expect to see?
> ### What did you see instead?
> ### What is your config in detail (with all sensitive info masked)?
> ss-tunnel 必须要加 -u 选项，才能查到dns解析。
> 日志显示udp connection
> 
> ![WeChat Screenshot_20200229150828](https://user-images.githubusercontent.com/15697803/75602994-6a068e00-5b05-11ea-972f-862c07d0b67c.png)
> 
> ### shadowsocks-windows client 测试结果
> 没有显示udp connection
> 
> ![WeChat Screenshot_20200229164133](https://user-images.githubusercontent.com/15697803/75604391-26b31c00-5b13-11ea-8255-67658d0fe6bc.png)
> 
> 如何让ss-tunnel 走 tcp 协议查询 dns 解析

我的shaodowsocks一直没有日志输出是为什么

**Comment by 0neday** [comment]
-v

**Comment by 0neday** [comment]
Or use dns-forwarder to tranfer udp query to tcp, like this 

![image](https://user-images.githubusercontent.com/15697803/80800545-974fd680-8b5e-11ea-8e3c-a1d86ce2bc6b.png)

dns query  udp 53 port--> dnsmasq udp 5300 (for gfw ) --> dns-forwarder tcp 5353 --> ss-tunnel tcp 5353
