### ISSUE TITLE
could you please improve the dockerfile execution order?

### ISSUE THREAD

**Issue by rilyuuj** [shadowsocks/shadowsocks-libev#2647]
### What version of shadowsocks-libev are you using?
shadowsocks/shadowsocks-libev:latest

### What operating system are you using?
centos7

### What did you do
---could you please improve the docker file load order?---

I posted all config to json file and used docker shadowsocks-libev with following command:
`docker run -e ARGS="-c /etc/shadowsocks-libev/config.json"`
but I found the environment parameter still no change, because the $ARGS is put in last when I checked the dockerfile.
Could you please change the execution order, load $ARGS at first, if it is "empty" then running other $ENV.

**Comment by madeye** [comment]
Pull request is welcome.

**Comment by aueu** [comment]
`docker run -p PORT -v /path:/etc/shadowsocks-libev/ -d IMAGE  /usr/bin/ss-server -c /etc/shadowsocks-libev/config.json`

**Comment by rilyuuj** [comment]
> `docker run -p PORT -v /path:/etc/shadowsocks-libev/ -d IMAGE /usr/bin/ss-server -c /etc/shadowsocks-libev/config.json`

hello,
Great thanks for hints, this is my first time use docker,  so I don't know the command can be executed at last, your answer give much help, thanks.
the rest issue is how to grant privilege to 'nobody', the dockerfile include setcap command, I tried to use --cap-add=CAP_NET_BIND_SERVICE parameter but still cannot switch to run.

**Comment by rilyuuj** [comment]
> Pull request is welcome.

I'm very glad you can reply, I used your repo for long time, that's very helpful.
and sorry I'm not DEV still in learning, I know the best solution is create an own docker hub, when I have more knowledge I willing to pull.
