### ISSUE TITLE
Typo in OpenWrt Makefile

### ISSUE THREAD

**Issue by zxdavb** [shadowsocks/shadowsocks-libev#265]
Shouldn't line 60, which is currenlty:
`$(INSTALL_BIN) $(PKG_BUILD_DIR)/src/ss-{local,redir,tunnel} $(1)/usr/bin`

instead be (has **,server** added):
`$(INSTALL_BIN) $(PKG_BUILD_DIR)/src/ss-{local,redir,tunnel,server} $(1)/usr/bin`

If I make this change, then ss-server appears in /usr/bin, where it does not otherwise.

**Comment by madeye** [comment]
It's not a typo. Server mode is not supported on OpenWRT.
