### ISSUE TITLE
Can i route my  VOIP/SIP Traffic using this Plugin ?

### ISSUE THREAD

**Issue by hbtechnologia** [shadowsocks/shadowsocks-libev#2654]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
i have installed core python version.

### What operating system are you using?
CentOS 7

### What did you do?
Want to route sip traffic through shadowsocks

### What did you expect to see?
is there any solution to do that ?

### What did you see instead?
Looking for solution

### What is your config in detail (with all sensitive info masked)?
Need configuration

**Comment by RebelliousWhiz** [comment]
Hi mate!

Shadowsocks works at TCP/UDP layer, so the application layer (like VoIP/SIP) should work fine with the correct configuration.

You need to ensure two things:

1. The server enables UDP relay (which is pretty easy by adding "-u" to your command);

2. A proxy client routes UDP packages to your Shadowsocks client.

I think the main problem is finding a local proxy softer that routes local UDP.

I have tried many local proxy software on Windows, including Proxifier, SocksCap64, ProxyCap.

Proxifier only routes TCP packages, SocksCap64 is discontinued, that leaves ProxyCap the best option for me.

I have been using Skype with ProxyCap and Shadowsocks for some time now, and it works great for me.

If you are looking for a Linux solution, I suggest you use "ss-redir" command from shadowsocks with a router (like OpenWrt), it keeps you away from complicated firewall settings.

You also want to check and see if your local network has a good UDP connection to your server. If your network drops too many UDP packages, you might want to deploy solutions like [wangyu-udp2raw-tunnel](https://github.com/wangyu-/udp2raw-tunnel).

**Comment by RebelliousWhiz** [comment]
I saw the other issue that was saying you are having a problem with the Asterisk and you said Skype was working fine.

I doubt Skype is really working in your case. I think Skype is working in any area with the internet without any proxy since it's using P2P. Maybe you should check if Skype is really routed through your proxy. 🤔

**Comment by hbtechnologia** [comment]
Thanks for your reply really appreciated. 
can you please guide me how to enables UDP relay  in shadowsocks server ?

**Comment by hbtechnologia** [comment]
yeah i am looking for linux solution which as following:

(LAN Users) =>  Cisco Router =>SS_Client (CentOS_7)  => SS_Server (CentOS_7) => Internet 


I will setup all thing in Router but before that i have to confirm that ss_client is sending voip packets to server using any proxy on user machine as i currently using ShadowSocks  window based client and outline VPN client.

**Comment by RebelliousWhiz** [comment]
> Thanks for your reply really appreciated.
> can you please guide me how to enables UDP relay in shadowsocks server ?

You can find out how to enable UDP relay on the server here:
https://github.com/shadowsocks/shadowsocks-libev/blob/master/doc/ss-server.asciidoc

```
-u
Enable UDP relay.
```

You will also need to enable UDP forwarding on the client-side:
https://github.com/shadowsocks/shadowsocks-libev/blob/master/doc/ss-local.asciidoc

You can use a JSON file to store the configuration by following templates here:
https://github.com/shadowsocks/shadowsocks-libev/blob/master/doc/shadowsocks-libev.asciidoc

I am not familiar with CentOS, but for ubuntu, if you installed shadowsocks properly, the config file can be found at `/etc/shadowsocks-libev/config.json`.

shadowsocks-windows itself does not forward UDP packages, TCP only. You need things like ProxyCap to redirect UDP. So it will be:

Skype --> ProxyCap --> shadowsocks-windows --> shadowsocks server --> internet

You can disable system proxy for shadowsocks-windows, and set the proxy port in server settings, so shadowsocks-windows will work as a local socks5 server.

Maybe after you are sure it is working, then set up ss-local on your CentOS_7, then use Cisco Router to redirect all the LAN users' TCP and UDP packages to ss-local "local port (which is socks5 as well)".

Please do some debugs, and maybe paste your configs and logs, so I can see if you are doing it right.

**Comment by hbtechnologia** [comment]
Hi RebelliousWhiz !!!
  Hope so you are doing well in this covid situation.
Scenario: 
 LAN Traffic(Users) => shadowsocks_client(centos 7 placed locally) => shadowsocks_server(Centos_ in USA)

SS_Server is working fine for data with  Windows Based client.
But when i use shadowsocks _client linux base  both are communicating  means after authentication of client from server it gives  PUBLIC IP of  Server  but all  other traffic is not going  through it even i have setup ss_client as Router with 2 NIC (which means all traffic should goes through it)

**Comment by hbtechnologia** [comment]
LAN Traffic(Users) =>Cisco Router  => shadowsocks_client(centos 7 placed locally) => shadowsocks_server(Centos_ in USA)

**Comment by RebelliousWhiz** [comment]
Hey mate, I am doing alright, thanks for asking!

So I think you might need to set up ss_redir instead of ss_client.

ss_client only sets up local a socks5 client and doesn't direct other connections automatically.

If you need all LAN Traffic to go through shadowsocks, you might need things like iptables, ss-redir, and many tweaks.

The easiest way for me is to buy a router with OpenWrt firmware, then set up ss-redir.

However, if you are familiar with iptables, just try around and check the shadowsocks-libev documents. You will need to forward TCP and UDP in iptables, which is too much for me, I doubt I can assist you further with this...

**Comment by hbtechnologia** [comment]
Thanks buddy !!  appreciated your help  i  have  tested  redsocks over ss_client but it did not work for me.
But i have read your  nice words and searched about ss_redir hope so this will work for me..

Appreciated @RebelliousWhiz
