### ISSUE TITLE
Is the config works safely?

### ISSUE THREAD

**Issue by MuenYu** [shadowsocks/shadowsocks-libev#2655]
### What version of shadowsocks-libev are you using?
- server: shadowsocks-libev 3.3.4 from snap
- plugin: v2ray-plugin 1.3.0

### What operating system are you using?
- server: ubuntu 18.04 LTS

### What did you do?
just build the service presently and everything is fine, i just wonder if my config is safe.

### What did you expect to see?
i hope my config is in safe.

### What did you see instead?
i just wonder if my config is in safe.

### What is your config in detail (with all sensitive info masked)?
config.json
```json
{
 "server":"0.0.0.0",
 "nameserver":"1.1.1.1",
 "server_port": xxx,
 "password": "xxx",
 "method":"aes-256-gcm",
 "timeout":60,
 "fast_open":false,
 "reuse_port":true,
 "no_delay":true,
 "mode":"tcp_and_udp",
 "plugin":"v2ray-plugin",
 "plugin_opts":"server;host=xxx;path=/a_simple_path"
}
```

nginx
```nginx
	##http
	server 
	{
		listen 80;
		server_name xxx;
		return 301 https://xxx$request_uri;
	}
	
	##https
	server 
	{
		listen 443 ssl;
		server_name xxx;
		ssl_certificate xxx;
		ssl_certificate_key xxx;
		ssl_session_timeout 5m;
		ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
		ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:HIGH:!aNULL:!MD5:!RC4:!DHE;
		ssl_prefer_server_ciphers on;
		
		location = /a_simple_path {
			proxy_redirect off;
			proxy_pass http://127.0.0.1:xxx;
			proxy_http_version 1.1;
			proxy_set_header Upgrade $http_upgrade;
			proxy_set_header Connection "upgrade";
			proxy_set_header Host $http_host;
		}
		
		location / {
			default_type text/plain;
			return 400 'Bad Request\n';
		}
	}

```

### here are some question i wonder
1. is the config in safe ?
2. should i replace the simple path by a complex path ?
3. what differiences between a static website and just return 400 in nginx ?
4. can i use a simple encryption (such as `rc4-md5`) to replace `aes-256-gcm` when i use v2ray-plugin?

thanks for replying. i will close the issue after receive answers.

**Comment by wintertee** [comment]
You can use `"server":"127.0.0.1"` instead of `"server":"0.0.0.0"` to hide your `server_port` from outside.

**Comment by MuenYu** [comment]
> You can use `"server":"127.0.0.1"` instead of `"server":"0.0.0.0"` to hide your `server_port` from outside.

you mean like this? @wintertee 

```json
{
 "server":"127.0.0.1",
 "nameserver":"1.1.1.1",
 "server_port": xxx,
 "password": "xxx",
 "method":"aes-256-gcm",
 "timeout":60,
 "fast_open":false,
 "reuse_port":true,
 "no_delay":true,
 "mode":"tcp_and_udp",
 "plugin":"v2ray-plugin",
 "plugin_opts":"server;host=xxx;path=/a_simple_path"
}
```

**Comment by clementhk** [comment]
You also need this because you're using `"mode":"tcp_and_udp"`

```
stream {
	server {
		listen 443 udp;
		proxy_pass 127.0.0.1:xxx;
	}
}

```
