### ISSUE TITLE
ss-tunnel: remote port forwarding feature required

### ISSUE THREAD

**Issue by march1993** [shadowsocks/shadowsocks-libev#2656]
Like openssh, is there any possibility that remote port forwarding could also be supported by ss-tunnel? It might be quite useful to forward connection from the remote port to local application ports, for example, ssh, http, etc.

**Comment by madeye** [comment]
https://github.com/fatedier/frp

**Comment by march1993** [comment]
> https://github.com/fatedier/frp

I believe the project you recommended can achieve remote port forwaring together with ss-tunnel. 
Yet, it would be great that ss-tunnel has this feature integrated itself. May I ask whether a PR of this feature is welcomed or not? If it is welcomed, maybe I should spend some time working on it.

**Comment by madeye** [comment]
Yeah, any PR is welcome.

**Comment by mehdipourfar** [comment]
@march1993 Have you found any solution?
I have server A with config (password, plugins, ...) X and server B with config Y. I run ss-server with config X on server A and an ss-local also with config X on server B. Now I also want to run an ss-server with config Y on server B with condition that all requests go through the ss-local on the same server. Have you any idea?

**Comment by march1993** [comment]
> @march1993 Have you found any solution?
> I have server A with config (password, plugins, ...) X and server B with config Y. I run ss-server with config X on server A and an ss-local also with config X on server B. Now I also want to run an ss-server with config Y on server B with condition that all requests go through the ss-local on the same server. Have you any idea?

Would it help? https://github.com/shadowsocks/shadowsocks-libev/issues/1798

**Comment by mehdipourfar** [comment]
No it wouldn't. Because there is no option to set two different configs. At last, I tried to use server B only as a proxy with nginx as forwarder
