### ISSUE TITLE
RPM pakage bug

### ISSUE THREAD

**Issue by LukeXuan** [shadowsocks/shadowsocks-libev#266]
Every time I update the shadowsocks-libev, it overwrites my config file with the original config file.

**Comment by madeye** [comment]
@librehat

**Comment by madeye** [comment]
RPM package is maintained by @librehat, please contact him directly.

**Comment by librehat** [comment]
Fixed in latest srpm. Please let me know if this problem is fixed in `2.1.4-1`.
