### ISSUE TITLE
能否在安装有Asuswrt-Merlin的华硕RT-AC1900P路由器上部署shadowsocks-libev

### ISSUE THREAD

**Issue by wans10** [shadowsocks/shadowsocks-libev#2660]
作为小白刚开始学习使用shadowsocks-libev，有以下问题不知能否帮忙解答，不胜感激
1. 想要通过在路由器上安装shadowsocks-libev实现全局代理，请问是否有安装方法？
2. 符合实现GFWList？
谢谢。

**Comment by tianlichunhong** [comment]
装openwrt，应该就容易多了。很多梅林固件也有SS的安装包，但是感觉还是困难一些。

**Comment by Acris** [comment]
试试这个？
https://github.com/Acris/shadowsocks-asuswrt-merlin
