### ISSUE TITLE
When I update shadowsocks,An error occurred

### ISSUE THREAD

**Issue by richman167** [shadowsocks/shadowsocks-libev#2665]
make  all-recursive
make[1]: Entering directory '/root/shadowsocks-libev'
Making all in libcork
make[2]: Entering directory '/root/shadowsocks-libev/libcork'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/root/shadowsocks-libev/libcork'
Making all in libipset
make[2]: Entering directory '/root/shadowsocks-libev/libipset'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/root/shadowsocks-libev/libipset'
Making all in libbloom
make[2]: Entering directory '/root/shadowsocks-libev/libbloom'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/root/shadowsocks-libev/libbloom'
Making all in src
make[2]: Entering directory '/root/shadowsocks-libev/src'
  CC       libshadowsocks_libev_la-ppbloom.lo
ppbloom.c: In function ‘ppbloom_add’:
ppbloom.c:91:9: error: implicit declaration of function ‘bloom_reset’ [-Werror=implicit-function-declaration]
         bloom_reset(ppbloom + current);
         ^
cc1: all warnings being treated as errors
Makefile:939: recipe for target 'libshadowsocks_libev_la-ppbloom.lo' failed
make[2]: *** [libshadowsocks_libev_la-ppbloom.lo] Error 1
make[2]: Leaving directory '/root/shadowsocks-libev/src'
Makefile:480: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/root/shadowsocks-libev'
Makefile:389: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by hzqim** [comment]
git submodule init && git submodule update
