### ISSUE TITLE
snap installed ss does not support obfs-server?

### ISSUE THREAD

**Issue by GitatHub** [shadowsocks/shadowsocks-libev#2670]
snap installation of ss is recommended by ss developer
but many users report problems using snap installed ss
e.g., https://github.com/shadowsocks/shadowsocks-libev/issues/2456

It's obvious that snap installed ss has a different configuration way from that for apt-get installed.
However, ss-libev documentation page does not provide a guide for snap installed ss.
e.g., almost no body says that config.json file cannot be saved in /etc directory ...
like https://htyeim.com/2020/01/%E8%B4%AD%E4%B9%B0vultr-vps%E5%90%8E%E5%AE%89%E8%A3%85shadowsocks/  , 
There is neither a guide for setting auto-start ss-server service, except 
https://blog.chaos.run/dreams/debian-shadowsocks-libev-server/

My problem is snap installed ss v3.3.4 does not support the obsolete obfs-server plugin anymore?
The apt installed 3.2.0 ss support this plugin very well.

### What version of shadowsocks-libev are you using?
shadowsocks-libev 3.3.4

### What operating system are you using?
4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux

### What did you do?
sudo snap install core
sudo snap install shadowsocks-libev

cp /etc/shadowsocks-libev/config.json /snap/
 vi /snap/config.json

/snap/bin/shadowsocks-libev.ss-server -c /snap/config.json

### What did you expect to see?
should work as apt installed ss-server

### What did you see instead?

 2020-03-27 13:26:26 INFO: plugin "obfs-server" enabled
 2020-03-27 13:26:26 INFO: enable TCP no-delay
 2020-03-27 13:26:26 INFO: initializing ciphers... xxxxxxxx
 2020-03-27 13:26:26 INFO: tcp server listening at 127.0.0.1:39569
 2020-03-27 13:26:26 INFO: tcp port reuse enabled
 2020-03-27 13:26:26 INFO: running from root user
No such file or directory
 2020-03-27 13:26:26 ERROR: plugin service exit unexpectedly
 2020-03-27 13:26:26 INFO: error on terminating the plugin.

### What is your config in detail (with all sensitive info masked)?
```
{
    "server":["0.0.0.0","[::0]"],
    "server_port":443,
    "password":"ssssxxxx",
    "method":"aes-xxxxxx",
    "no_delay":true,
    "reuse_port":true,
    "plugin":"obfs-server",
    "plugin_opts":"obfs=tls"
}
```

**Comment by madeye** [comment]
Put any file to the sandbox if you want to access them in snap.

**Comment by GitatHub** [comment]
You mean to put all related files/binaries in /snap directory for e.g., ubuntu?
> Put any file to the sandbox if you want to access them in snap.

**Comment by KyleJKC** [comment]
I have the same problem, did you solved it?

**Comment by willy666rumster** [comment]
same with v2ray-plugin

what the "sandbox"??

**Comment by maidmeow4** [comment]
Hey guys, I figured it out, plugin binary files should put under the `shadowsocks-libev/common` directory, this directory acts like the `/` (root) directory on your real server, but it's sandboxed.
For instance, on Fedora, we can place the plugin binary under `/var/snap/shadowsocks-libev/common/etc` (as this directory already exists), then change your `config.json` like below:
```
...
"plugin":"/etc/shadowsocks-libev/obfs-server",
...
```
After this plugins should be loaded correctly.

```
/var/snap/shadowsocks-libev
├── 715
├── common
│   └── etc
│       └── shadowsocks-libev
│           ├── config.json
│           └── v2ray-plugin   <--- place the plugin here!
└── current -> 715
```
