### ISSUE TITLE
ppbloom.c:91:9: error

### ISSUE THREAD

**Issue by zzzshanghai** [shadowsocks/shadowsocks-libev#2671]
### What version of shadowsocks-libev are you using?
the latest

### What operating system are you using?
centos7 64bit

### What did you do?
git pull
./configure
make

### What did you see instead?
ppbloom.c: In function 'ppbloom_add':
ppbloom.c:91:9: error: implicit declaration of function 'bloom_reset' [-Werror=implicit-function-declaration]
         bloom_reset(ppbloom + current);
         ^
cc1: all warnings being treated as errors
make[2]: *** [libshadowsocks_libev_la-ppbloom.lo] Error 1
make[2]: Leaving directory `/root/shadowsocks-libev/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/root/shadowsocks-libev'
make: *** [all] Error 2

**Comment by starter48** [comment]
I believe you trying to compile with old version of **shadowsocks/libbloom** subdir.
I.e. that problem may occurs if you updated your copy of sources incompletely.
