### ISSUE TITLE
Cannot start after installing from snap now

### ISSUE THREAD

**Issue by happy201807** [shadowsocks/shadowsocks-libev#2677]
### What version of shadowsocks-libev are you using?
3.3.4-1

### What operating system are you using?
ubuntu 18.04 LTS

### What did you do?
sudo /snap/bin/shadowsocks-libev.ss-server -c /root/config.json

### What did you expect to see?
pin code

### What did you see instead?
ERROR: Invalid config path.

### What is your config in detail (with all sensitive info masked)?
ERROR: Invalid config path.

**Comment by Prajwal-Koirala** [comment]
anyone found a fix for this??
@happy201807

**Comment by happy201807** [comment]
This is not a bug, so there is no need to fix it.

Prajwal Koirala <notifications@github.com> 于2020年5月3日周日 上午11:27写道：

**Comment by Prajwal-Koirala** [comment]
Can u provide some instructions than

**Comment by happy201807** [comment]
Since it uses docker instead, the operation method is different from yours,
please refer to the wiki as much as possible.

Prajwal Koirala <notifications@github.com> 于2020年5月3日周日 下午4:28写道：

**Comment by timeneverdie** [comment]
Make sure you have config file at `/var/snap/shadowsocks-libev/common/etc/shadowsocks-libev/config.json`.
Use `/usr/bin/snap run shadowsocks-libev.ss-server` to run. But I don't know how to combine this to `systemctl`.
