### ISSUE TITLE
`invalid password or cipher` on OpenWRT

### ISSUE THREAD

**Issue by bingzhangdai** [shadowsocks/shadowsocks-libev#2678]
### What version of shadowsocks-libev are you using?
shadowsocks-libev 3.2.5 (installed by `opkg`)

### What operating system are you using?
Linux OpenWrt 4.14.171 #0 SMP Thu Feb 27 21:05:12 2020 x86_64 GNU/Linux

### What did you do?
Start shadowsocks proxy client by `ss-redir -c /var/etc/shadowsocks.cfg054a8f.json -u --fast-open -l 1080`

When I run command `wget -O /dev/null http://speedtest.wdc01.softlayer.com/downloads/test10.zip` for speed test, `wget` get interruped very often, showing
```log
2020-04-03 21:06:06 (228 KB/s) - Connection closed at byte 1698850. Retrying.
```

### What did you expect to see?
No errors. No interruption.

### What did you see instead?
I checked the system log, I see many errors like
```log
Fri Apr  3 21:02:30 2020 daemon.err ss-redir[6626]: invalid password or cipher
Fri Apr  3 21:05:55 2020 daemon.err ss-redir[6626]: invalid password or cipher
Fri Apr  3 21:05:58 2020 daemon.err ss-redir[6626]: invalid password or cipher
Fri Apr  3 21:06:06 2020 daemon.err ss-redir[6626]: invalid password or cipher
Fri Apr  3 21:06:11 2020 daemon.err ss-redir[6626]: invalid password or cipher
```
If I use shadowsocks-windows client, everything works fine.

I am pretty sure that there is nothing wrong with my password or cipher because I could connect to the server and `wget` do download the file with fast speed. The problem is that it is interrupted frequently.

Also, I checked the server-side log, there are no severe errors except that the client closes the connection. (see the forth line below)
```log
 2020/04/03 12:29:17 tcp:171.214.234.61:8537 accepted tcp:127.0.0.1:0
 2020-04-03 12:29:17 INFO: connect to 158.85.230.20:80
 2020-04-03 12:29:17 INFO: remote connected
 2020-04-03 12:29:25 INFO: remote_recv close the connection
 2020-04-03 12:29:25 INFO: current remote connection: 3
 2020-04-03 12:29:25 INFO: current server connection: 3
 2020-04-03 12:29:27 INFO: accept a connection
 2020/04/03 12:29:27 tcp:223.85.220.60:26887 accepted tcp:127.0.0.1:0
 2020-04-03 12:29:27 INFO: connect to api.vox.rocks:443
```
Hence, I belive the error results from the client side binary, that is, `ss-redir`. I tried `ss-local` and it shows the same error.

### What is your config in detail (with all sensitive info masked)?
The config file is (server and password are removed)
```json
{
    "server": "xxx.xxx.xxx.xxx",
    "server_port": 2333,
    "password": "******",
    "method": "chacha20-ietf-poly1305",
    "local_address": "0.0.0.0",
    "plugin": "/root/bin/v2ray-plugin_linux_amd64",
    "timeout": 300,
    "reuse_port": true
}
```

**Comment by madeye** [comment]
- Double check your password
- Disable TCP fast open

**Comment by bingzhangdai** [comment]
I cannot reproduce now. Reopen it if I encountered it later. Sorry.
