### ISSUE TITLE
请问这个支持在config.json中添加注释吗?

### ISSUE THREAD

**Issue by blog2i2j** [shadowsocks/shadowsocks-libev#268]
我想在config.json的配置文件中添加一些注释, 试了一下用#发现不对, 请教是不是不支持添加注释, 能否加上配置文件中允许添加注释呢? 谢谢

**Comment by madeye** [comment]
http://stackoverflow.com/questions/244777/can-i-comment-a-json-file

**Comment by blog2i2j** [comment]
谢谢, 看来是不支持. 最好能加上支持注释.
