### ISSUE TITLE
ss-local is running, but traffic is not go via shoadowsocks - openwrt

### ISSUE THREAD

**Issue by mimta** [shadowsocks/shadowsocks-libev#2681]
### What version of shadowsocks-libev are you using?
shadowsocks-libev-ss-local3.3.4-1

### What operating system are you using?
Openwrt on Raspberry Pi 4

### What did you do?
I have installed the shadowsocks-libev ss-local . in the admin is show ss-local is running. also in system log I can see

> Mon Apr  6 16:15:32 2020 daemon.info /usr/bin/ss-local[489]: initializing ciphers... aes-256-gcm
> Mon Apr  6 16:15:32 2020 daemon.info /usr/bin/ss-local[489]: listening at 0.0.0.0:1080
> Mon Apr  6 16:15:32 2020 daemon.info /usr/bin/ss-local[489]: running from root user

### What did you expect to see?
all traffic going via ss-local

### What did you see instead?
no traffic is going via ss-local

### What is your config in detail (with all sensitive info masked)?

```
config ss_local
	option disabled 1
	option server 'sss0'
	option local_address '0.0.0.0'
	option local_port '1080'
	option timeout '30'
```
note: I have tried 127.0.0.1 but no luck.

thank you

**Comment by RebelliousWhiz** [comment]
ss-local only opens up socks5 proxy on `1080` port, if you need the traffic to go through shadowsocks, you need to use `proxychains` or things like that to connect to the socks5 port `1080`. Or you can try ss-redir.
