### ISSUE TITLE
build_deb.sh does not work on Ubuntu 18.04.4 (with temporary solution)

### ISSUE THREAD

**Issue by allenhsu** [shadowsocks/shadowsocks-libev#2684]
### What version of shadowsocks-libev are you using?
I have v3.1.3 installed from the official repository. I'm going to install the latest version v3.3.4 from source code with `build_deb.sh`.

### What operating system are you using?
Ubuntu 18.04.4

### What did you do?
Copied `build_deb.sh` to a workspace and ran it.

### What did you expect to see?
v3.3.4 installed

### What did you see instead?
Failed to install the latest version

### What is your config in detail (with all sensitive info masked)?

I checked the output of `build_deb.sh` and noticed that the error was mainly caused by two dependencies, `debhelper` and `init-system-helpers`. The latest version of both packages has suffix of `ubuntu1~ubuntu18.04.1` preventing them being installed onto Ubuntu 18.04.4.

As a temporary solution, I removed `debhelper` from `apt_clean` step. And manually installed it with `apt-get install debhelper=12.1.1ubuntu1~ubuntu18.04.1`. Then I successfully built the deb file. However when installing the package, it's failed due to dependency on higher version of `init-system-helpers`:

```
dpkg: regarding shadowsocks-libev_3.3.4+ds-3_amd64.deb containing shadowsocks-libev, pre-dependency problem:
 shadowsocks-libev pre-depends on init-system-helpers (>= 1.54~)
  init-system-helpers is installed, but is version 1.51.

dpkg: error processing archive shadowsocks-libev_3.3.4+ds-3_amd64.deb (--install):
 pre-dependency problem - not installing shadowsocks-libev
```

Then I manually installed it with `apt install init-system-helpers=1.56+nmu1~ubuntu18.04.1`.

And manually installed the deb with `sudo dpkg -i shadowsocks-libev_*.deb`.

This is not quite an issue of this repo, but I hope those encountered same or similar problems can find this temporary solution.

**Comment by ctpxyza** [comment]
you can try to fix it with "apt-get install -f "

**Comment by dr-js** [comment]
Also tried to build deb on Ubuntu server `18.04.4 LTS (Bionic Beaver)` but failed.

For me the build error at:
```
- build_install_sslibev
  - gbp_build https://salsa.debian.org/bridges-team/shadowsocks-libev.git $BRANCH
    - mk-build-deps --root-cmd sudo --install --tool "apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends -y $BPO_REPO"
```

Related error log:
```
...
Unpacking shadowsocks-libev-build-deps (3.3.4+ds-4) ...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Correcting dependencies...Starting pkgProblemResolver with broken count: 1
Starting 2 pkgProblemResolver with broken count: 1
Investigating (0) shadowsocks-libev-build-deps:amd64 < 3.3.4+ds-4 @iU mK Nb Ib >
Broken shadowsocks-libev-build-deps:amd64 Depends on libjsonparser-dev:amd64 < none @un H >
  Removing shadowsocks-libev-build-deps:amd64 because I can't find libjsonparser-dev:amd64
Done
 Done
Starting pkgProblemResolver with broken count: 0
Starting 2 pkgProblemResolver with broken count: 0
Done
The following packages will be REMOVED:
  shadowsocks-libev-build-deps
...
```

And after checking: https://packages.ubuntu.com/search?keywords=libjsonparser-dev
Seems like `libjsonparser-dev` is not avaliable for `18.04`, it's for `19.10+`
