### ISSUE TITLE
Compilation on cygwin fails

### ISSUE THREAD

**Issue by xnoreq** [shadowsocks/shadowsocks-libev#269]
Compilation on cygwin fails in util.c, because itoa is already defined in <stdlib.h>.

If that is fixed, for example by renaming the function to ss_itoa and changing the function call in jconf.c everything compiles, but I've only tested ss-local so far.

**Comment by madeye** [comment]
Duplicate with #255

**Comment by xnoreq** [comment]
My Cygwin is up to date, uname -a says:
CYGWIN_NT-6.1 HOSTNAME 1.7.34(0.285/5/3) 2015-02-04 12:14 x86_64 Cygwin
(1.7.34 was released 4 Feb 2015.)

$ gcc --version
gcc (GCC) 4.9.2

**Comment by xnoreq** [comment]
Rebuilding right now..
