### ISSUE TITLE
ubuntu20.04 make fail.  *** 没有规则可以创建“ss_local-http.o”需要的目标“http.c”

### ISSUE THREAD

**Issue by ctpxyza** [shadowsocks/shadowsocks-libev#2693]
### What version of shadowsocks-libev are you using?

3.3.4
### What operating system are you using?
ubuntu 20.04，but works well on ubuntu 18.04

### What did you do?

just try to compile/
### What did you expect to see?

compile success.
### What did you see instead?
make[2]: *** 没有规则可以创建“ss_local-http.o”需要的目标“http.c”。 停止。
make[2]: Leaving directory `/project/personal/shadowsocks-libev/src'

### What is your config in detail (with all sensitive info masked)?

[config.zip](https://github.com/shadowsocks/shadowsocks-libev/files/4537117/config.zip)

**Comment by manjuprajna** [comment]
I've just compiled successfully on a Ubuntu 20.04 vps this morning, nothing unusual, working smoothly, check your enviroment, I think you missed some packages needed.

**Comment by ctpxyza** [comment]
> I've just compiled successfully on a Ubuntu 20.04 vps this morning, nothing unusual, working smoothly, check your enviroment, I think you missed some packages needed.
I'm sorry, i haven't compiled according to the file named README.md, just use "configure; make", It's ok when i follow the document.
