### ISSUE TITLE
It seems that some people are attacking my ss server 

### ISSUE THREAD

**Issue by GitatHub** [shadowsocks/shadowsocks-libev#2701]
the log shows that many machines from different places (mostly in China) are guessing the password of my ss server.
Is there a builtin protection method to ban those IPs with multiple failed attempts?
Or we have to use fail2ban to implement this like http://blog.zedyeung.com/2018/08/14/Ubuntu-18-04-set-up-Shadowsocks-server-with-fail2ban/  ?

part of my log:
daemon.log:date time hostname shadowsocks-libev.ss-server[31028]:  date time ERROR: failed to handshake with 223.166.74.189: invalid address type
daemon.log:date time hostname shadowsocks-libev.ss-server[31028]:  date time ERROR: failed to handshake with 124.90.55.34: invalid address type
daemon.log:date time hostname shadowsocks-libev.ss-server[31028]:  date time ERROR: failed to handshake with 112.66.101.41: authentication error
daemon.log:date time hostname shadowsocks-libev.ss-server[31028]:  date time ERROR: failed to handshake with 112.66.101.41: authentication error
daemon.log:date time hostname shadowsocks-libev.ss-server[31028]:  date time ERROR: failed to handshake with 175.152.111.112: authentication error
daemon.log:date time hostname shadowsocks-libev.ss-server[31028]:  date time ERROR: failed to handshake with 124.235.138.134: authentication error
daemon.log:date time hostname shadowsocks-libev.ss-server[31028]:  date time ERROR: failed to handshake with 119.118.5.227: authentication error
daemon.log:date time hostname shadowsocks-libev.ss-server[31028]:  date time ERROR: failed to handshake with 182.138.137.116: authentication error
daemon.log:date time hostname shadowsocks-libev.ss-server[31028]:  date time ERROR: failed to handshake with 220.200.161.199: authentication error
daemon.log:date time hostname shadowsocks-libev.ss-server[31028]:  date time ERROR: failed to handshake with 112.66.100.179: authentication error
daemon.log:date time hostname shadowsocks-libev.ss-server[31028]:  date time ERROR: failed to handshake with 123.158.60.219: invalid address type
daemon.log:date time hostname shadowsocks-libev.ss-server[31028]:  date time ERROR: failed to handshake with 211.97.19.160: invalid address type
daemon.log:date time hostname shadowsocks-libev.ss-server[31028]:  date time ERROR: failed to handshake with 119.39.47.115: invalid address type
daemon.log:date time hostname shadowsocks-libev.ss-server[31028]:  date time ERROR: failed to handshake with 119.39.47.115: invalid address type
daemon.log:date time hostname shadowsocks-libev.ss-server[31028]:  date time ERROR: failed to handshake with 106.45.1.156: invalid address type
daemon.log:date time hostname shadowsocks-libev.ss-server[31028]:  date time ERROR: failed to handshake with 175.152.28.119: authentication error
daemon.log:date time hostname shadowsocks-libev.ss-server[31028]:  date time ERROR: failed to handshake with 124.88.113.24: authentication error
daemon.log:date time hostname shadowsocks-libev.ss-server[31028]:  date time ERROR: failed to handshake with 124.88.113.24: invalid host name
daemon.log:date time hostname shadowsocks-libev.ss-server[31028]:  date time ERROR: failed to handshake with 119.118.12.116: authentication error

**Comment by studentmain** [comment]
Use an AEAD cipher to get avoid of replay attack.

**Comment by studentmain** [comment]
auto ban is somehow harmful in this situation.

**Comment by GitatHub** [comment]
OK. Has shifted to one of the four (five if include xchacha...) AEAD methods.
But log still says
`ERROR: failed to handshake with MY_IP: invalid address type`

All my devices on MY_IP are working normally, but I still see "failed to handshake" errors in daemon.log and syslog.
It's difficult to understand...

**Comment by starter48** [comment]
> the log shows that many machines from different places (mostly in China) are guessing the password of my ss server.

Just notice you: most Chinese internet users (I guess you've been attacked by some botnet) has dynamic IP with forced change every day or two, so it isn't efficient to ban them by individual IP.
Instead if you don't have customers from China, I would suggest to ban whole Chinese address space.

**Comment by PantherJohn** [comment]
Good news is that those malicious TCP connections were silently dropped (per my request from last year) to prevent further (OR potential) ddos attacks. But having a bunch of unknown users trying to hack a server not even made publically available seems alarming to me. Other than changing the encryption method DO CONSIDER changing the port as well, and keep the nice and neat firewall enabled as well. DROP ANY TCP CONNECTIONS TARGETING NON-SERVICING PORTS, that is, reject all connections except the ones containing the port in service in this case the port opened by your shadowsocks server.
