### ISSUE TITLE
Shadowsocks能否支援AES-CBC、AES-CBC-SHA1和AES-CBC-SHA256演算法？

### ISSUE THREAD

**Issue by okudayukiko** [shadowsocks/shadowsocks-libev#2712]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What did you expect to see?
Shadowsocks能否支援AES-CBC、AES-CBC-SHA1、AES-CBC-SHA256、AES-CFB-SHA1、AES-CFB-SHA256演算法？SHA1、SHA256作為HMAC。
CHACHA20-IETF-POLY1305演算法的SS在中國部分地區被封鎖。

**Comment by ArArgon** [comment]
CFB 不是 AEAD 吧，抵不住重放攻击. 不如切换成 AES-GCM

**Comment by okudayukiko** [comment]
> CFB 不是 AEAD 吧，抵不住重放攻击. 不如切换成 AES-GCM

電腦/手機處理器沒有AES指令集的情況下，用AES-GCM很耗電。雖然較新的手機都有AES指令集，但許多VPN App，如V2RayNG、AnyConnect，沒有調用AES指令集。我開了一個Issue提醒，shadowsocks-android才在最新版本加入了AES指令集支援。

**Comment by 960PRO** [comment]
AES-CBC这类加密算法已经过时，容易被GFW主动探测导致Shadowsocks服务端暴露。如果你的设备缺失AES指令集，请使用Chacha20-poly1305系列加密方式。

**Comment by okudayukiko** [comment]
> AES-CBC这类加密算法已经过时，容易被GFW主动探测导致Shadowsocks服务端暴露。如果你的设备缺失AES指令集，请使用Chacha20-poly1305系列加密方式。

Chacha20-ietf-poly1305在中國部分地方防火牆會被探測到。現在較新的手機都有AES指令集，但問題是許多軟體不使用AES指令集，如Igniter、V2RayNG都不會調用AES指令集。shadowsocks-android也是我開了個Issue，才在最新版加入AES指令集。

**Comment by yzou** [comment]
> > CFB 不是 AEAD 吧，抵不住重放攻击. 不如切换成 AES-GCM
> 
> 處理器沒有AES指令集的情況下，用AES-GCM很耗電。雖然較新的手機都有AES指令集，但許多VPN App，如V2RayNG、AnyConnect，卻沒有調用AES指令集。我開了一個Issue提醒，shadowsocks-android才在最新版本加入了AES指令集支援。

哪个 issu？

**Comment by shikkoku** [comment]
> > > CFB 不是 AEAD 吧，抵不住重放攻击. 不如切换成 AES-GCM
> > 
> > 
> > 處理器沒有AES指令集的情況下，用AES-GCM很耗電。雖然較新的手機都有AES指令集，但許多VPN App，如V2RayNG、AnyConnect，卻沒有調用AES指令集。我開了一個Issue提醒，shadowsocks-android才在最新版本加入了AES指令集支援。
> 
> 哪个 issu？

https://github.com/shadowsocks/shadowsocks-android/issues/2503

**Comment by TommyJerryMairo** [comment]
> AES-CBC这类加密算法已经过时，容易被GFW主动探测导致Shadowsocks服务端暴露。如果你的设备缺失AES指令集，请使用Chacha20-poly1305系列加密方式。

您好，我正在做網絡安全方面的研究。我記得16年前後在 shadowsocks 用戶圈子內廣泛地討論過 AES-CBC 與 AES-CFB 的對比並得出 AEC-CBC 更容易被 GFW 鑑別流量的結論。但是時過境遷，當初的討論組都已經不在了。您是否記得有哪些依舊可以訪問的博文記錄了當初的討論結果或過程？感激不盡。
