### ISSUE TITLE
可能的漏洞反馈

### ISSUE THREAD

**Issue by 960PRO** [shadowsocks/shadowsocks-libev#2713]
今天Github的V2ray翻墙项目发现严重漏洞，链接shttps://github.com/v2ray/v2ray-core/issues/2523
GFW可以利用这种漏洞探测出V2ray服务的存在，对翻墙流量进行封杀。
这种漏洞可能影响所有翻墙软件，Shadowsocks虽然支持AES GCM与Chacha20-poly1305反制主动TCP刺探。但建议排查一下Shadowsocks是否有这种缺陷。
谢谢，本人致谢您们这些开发者。

**Comment by studentmain** [comment]
`支持AES GCM与Chacha20-poly1305`就是因为曾经`有这种缺陷`......

**Comment by 1265578519** [comment]
总体来说，ss已经完全识别了，有个固定的头部特征，抓包看看就知道了非常明显
所以现在ss更新了加了个aead模式，就是去掉了特征
ss也是有这种固定的特征包，后面换了AEAD才解决
![image](https://user-images.githubusercontent.com/6442439/83417214-5cd6a380-a454-11ea-9788-b53f138a5ab4.png)
ss这个模式，抓包抓不到特征的
什么aes256cfb都有非常明显的固定特征轻松识别

**Comment by studentmain** [comment]
> ss也是有这种固定的特征包

不是特征包，SS的包特征如果有也很弱。问题是错误的接受了伪造数据，AEAD好处在于简洁的数据防伪造。
