### ISSUE TITLE
Requests sent by curl will time out if ss-local is on the same machine

### ISSUE THREAD

**Issue by xlfjn** [shadowsocks/shadowsocks-libev#2714]
### What version of softwares are you using?
shadowsocks-libev 3.3.4
curl 7.70.0

### What operating system are you using?
Arch Linux
Kernel 5.6.15
systemd 245.5

### What did you do?
I tried to instruct curl to use the SOCKS5 proxy provided by ss-local through passing `-x socks5h://127.0.0.1:1080` to it. However the request will time out after 300 seconds. If I tell curl to resolve the IP locally by passing `-x socks5://127.0.0.1:1080`, the response will be returned almost instantly.

### Steps to reproduce
1. Obtain the current Arch Linux live CD image (`archlinux-2020.06.01-x86_64.iso`) from [its website](https://www.archlinux.org/download/). Mirrors can be used to speed up the downloading.
2. Boot the live CD inside a VM or on a raw machine. For the latter case, manually [set up](https://wiki.archlinux.org/index.php/Installation_guide#Connect_to_the_internet) the network if necessary. It should be noted that I performed the following steps using a VM with networking in NAT mode.
3. Configure its package manager `pacman` to use a [nearby mirror](https://wiki.archlinux.org/index.php/Mirrors). Perform `pacman -Syy` to refresh package index, and install shadowsocks-libev with `pacman -S shadowsocks-libev`
4. Run `ss-server -s 127.0.0.1 -p 3871 -k password -m chacha20-ietf-poly1305 -v` and `ss-local -s 127.0.0.1 -p 3871 -l 1080 -k password -m chacha20-ietf-poly1305 -v` to set up shadowsocks-libev. The environment has GNU Screen pre-installed but you are free to choose other tools to have multiple terminals or just ssh into it.
5. Execute `curl -v -x socks5h://127.0.0.1:1080 https://www.baidu.com/`. (Or www.google.com if the network permits.) A sample log follows:
```
*   Trying 127.0.0.1:1080...
* SOCKS5 connect to www.baidu.com:443 (remotely resolved)
* Connection timed out after 300000 milliseconds
* Closing connection 0
curl: (28) Connection timed out after 300000 milliseconds
```
6. Execute `curl -v -x socks5://127.0.0.1:1080 https://www.baidu.com/`. This time curl should print the response immediately.

If ss-local runs on another machine, `curl -x socks5h://` also seems to work fine.

I'm not able to get any clue about this, hence the usage of a live CD. Sorry for the inconvenience.

**Comment by madeye** [comment]
Double check your local DNS settings. It looks your local ss-local cannot resolve domain names correctly.

**Comment by xlfjn** [comment]
Since only ss-server has the `-d` option for specifying the DNS server to use when resolving domain names in SOCKS5 requests, I assume you meant that feature of ss-server.

The live CD environment uses the systemd-resolved stub resolver system-wide (as configured in resolv.conf) by default. Following your advice, I tried configuring it to use some well-known public resolvers in China including 119.29.29.29 and 114.114.114.114, and global ones like Cloudflare DNS 1.0.0.1. Neither of them changes the outcome. Currently `ss-server -v` looks like this:
```
INFO: new connection from client, 1 opened client connections
INFO: [xxxx] connect to www.baidu.com:443
INFO: found address name v4 address www.a.shifen.com
INFO: failed to lookup v6 address DNS server returned answer with no data
INFO: successfully resolved www.baidu.com
INFO: new connection to remote, 1 opened remote connections

...[The client times out after a while]...

INFO: close a connection to remote, 0 opened remote connections
INFO: close a connection from client, 0 opened client connections
```

However, by examining the output of tcpdump, it seems ss-server does establish a TCP connection to the corresponding IP-port pair, however no data is transmitted in that TCP connection after handshake, and Baidu's server will terminate this connection after idling for 30 seconds. The closure of this connection seems propagated to ss-local and curl, but curl seems "unaware" of the status changes in SOCKS5.

Then I installed another network tool called `httpie` for its SOCKS5 support. It can use the SOCKS5 proxy exposed by ss-local without issue.

Therefore this interoperability issue seems to be curl-specific. I will try some other SOCKS5 servers to see if the curl in Arch Linux is problematic when I have more spare time.

**Comment by xlfjn** [comment]
This bug is no longer reproducible in latest Arch Linux. I peeked at [the changelog of curl](https://curl.haxx.se/changes.html#7_71_0) and found that curl/curl#5527 appears to be the culprit, so it's a third party bug, and only affects curl 7.69.0 - 7.70.0

Sorry for the inconvenience, and I'm glad it has been resolved there.
