### ISSUE TITLE
[feature request] SOCKS auth for clients running on remote server

### ISSUE THREAD

**Issue by unclenull** [shadowsocks/shadowsocks-libev#2715]
Now clients are only used in scenario where they accept socks request from the same machine. What if I wanna run the clients as a standard SOCKS server on a remote machine? So SOCKS auth is required.

User (machine A)  ->  ss-local (machine B)  ->  ss-server (machine C)

I assume this is a better solution than redirecting "ss-local" flow to "ss-server" blindly mentioned in this [issue](https://github.com/shadowsocks/shadowsocks-libev/issues/2459). No body has this demand Or am I missing something?

**Comment by madeye** [comment]
Try firewall instead.
