### ISSUE TITLE
Feature request: option to disable DNS forwarding on clients

### ISSUE THREAD

**Issue by ddvarpdd** [shadowsocks/shadowsocks-libev#2721]
If enabled, ss-local shall resolve DNS queries on a local machine, instead of fully forwarding request to server, which then resolves DNS on itself.

This might benefit users who run Shadowsocks client in their local networks, in which they set up their own resolvers with domain blocking (e.g. Pi-hole), resolving non-ICANN domains (e.g. Namecoin, Emercoin, OpenNIC) or something else that might be redundant to set up on a remote server as well.

Right now DNS termination can be done with combination of tun2socks and dante-sockd, but this creates some overhead, as well as requires additional privileges, and generally seems to be a hassle to set up.

As such, I'd like to request this option to be added in subsequent shadowsocks releases.

**Comment by madeye** [comment]
It has nothing to do with shadowsocks client. It's up to you that send IP address or hostname to ss-local, both are supported by SOCKS5 protocol.

**Comment by ddvarpdd** [comment]
> It has nothing to do with shadowsocks client. It's up to you that send IP address or hostname to ss-local, both are supported by SOCKS5 protocol.

Still, some programs (such as Privoxy) do not have any option to change such behaviour.

**Comment by vanyaindigo** [comment]
> some programs (such as Privoxy)

Use Proxifier instead

**Comment by ddvarpdd** [comment]
> Use Proxifier instead

This is completely different type of software (proxy wrapper instead of proxy server), moreover it's proprietary.

**Comment by vanyaindigo** [comment]
Well maybe this will not be a problem for you.  And it’s really more convenient. Another way to get around the restrictions is to organize your own DNS-resolver on the server side with the same domain blocking.

**Comment by Seanspt** [comment]
Use 'socks5h://127.0.0.1:1080' instead of 'sock5://127.0.0.1:1080' to enable server side resolving.
