### ISSUE TITLE
Can't visit internet when set socks5 proxy directly to shadowsocks

### ISSUE THREAD

**Issue by xspeed1989** [shadowsocks/shadowsocks-libev#2722]
version:shadowsocks-libev 3.3.4
windows:windows 10 2004
1. ss-local -s x.x.x.x -p 1314 -k pwd -b 0.0.0.0 -l 1082 -m rc4-md5 -u
2.set proxy (start menu->setting->network->proxy)
![image](https://user-images.githubusercontent.com/5162926/84996721-387f0480-b180-11ea-915f-09f926936172.png)
3. visit https://www.baidu.com/ in browser

but  when i use ss-tap,it works  fine
![image](https://user-images.githubusercontent.com/5162926/84997111-b6dba680-b180-11ea-8882-53bd04cc9f6a.png)
shadowsocks-windows works fine

**Comment by madeye** [comment]
It's expected. ss-local is a SOCKS5 proxy.
