### ISSUE TITLE
How to forward traffic from  1st sahdowsocks server to 2nd shadowsocks server  ?

### ISSUE THREAD

**Issue by hbtechnologia** [shadowsocks/shadowsocks-libev#2726]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
Latest one

### What operating system are you using?
CentOS 8

### What did you do?
I am trying to forward all traffic

### What did you expect to see?
Traffic should go to internet from 2nd SS Server

### What did you see instead?
Trying 

### What is your config in detail (with all sensitive info masked)?
all good. 
Using  Outline Client 
ShadowSocks Server 1  on AWS

**Comment by hbtechnologia** [comment]
Currently i have  case  like :
Client -> SS Server 1-> Internet 
but question is :

Client -> SS Server 1->SS Server 2-> Internet

is it possible ?

**Comment by madeye** [comment]
https://gist.github.com/monkeym4ster/0a8c4b955330478c1f1811794df91bae

**Comment by hbtechnologia** [comment]
@madeye  let me configure today i will respond back soon..

thanks for helping me out..

**Comment by OmiceyO** [comment]
Would this help circumvent GFW more, or it wouldnt matter?
