### ISSUE TITLE
server not receiving connections with iptables/selinux disabled

### ISSUE THREAD

**Issue by hexindent** [shadowsocks/shadowsocks-libev#2727]
### What version of shadowsocks-libev are you using?

3.2.0-2.el6

### What operating system are you using?

CentOS 6.10

### What did you do?

Installed and ran ss-server with iptables/selinux disabled

### What did you expect to see?

Receiving connection from client

### What did you see instead?

server listening with no incoming traffic

### What is your config in detail (with all sensitive info masked)?

```
{
    "server":"I.P.ADD.RESS",
    "server_port":8388,
    "local_address":"127.0.0.1",
    "local_port":1080,
    "password":"PASSWORD",
    "timeout":600,
    "method":"chacha20-ietf-poly1305",
    "http_proxy": false,
    "mode": "tcp_only"
}
```

My client is working because it can connect to a shadowsocks-libev server installed on an Ubuntu server which is in the same sub-network with the CentOS server. What else can be the factor that's blocking ss-server? The server is listening but can't hear.

**Comment by manjuprajna** [comment]
"server":"0.0.0.0,
remove local_address local_port

**Comment by hexindent** [comment]
> "server":"0.0.0.0,
> remove local_address local_port

Thank you for the suggestion, however, removing the local settings or changing the server ip (0.0.0.0, ::0, or external ip) didn't resolve this issue unfortunately.

**Comment by manjuprajna** [comment]
netstat -ntlp   to see if it's listenning to the port.
then use tcping on client side to see if server's port is accessible.

**Comment by hexindent** [comment]
> netstat -ntlp to see if it's listenning to the port.
> then use tcping on client side to see if server's port is accessible.

netstat shows the port is open
`tcp        0      0 1.2.3.4:8388         0.0.0.0:*                   LISTEN      31379/ss-server`

but I can't reach the port from my client (I'm using nc)
`nc -vz 1.2.3.5 8388
Connection to 1.2.3.5 8388 port [tcp/*] succeeded'
this is the Ubuntu server I mentioned
`nc -vz 1.2.3.4 8388`
just hangs there with no return

so I don't know what else is blocking it. iptables and selinux are turned off.
