### ISSUE TITLE
[Not a bug] What does the INSTALL file do?

### ISSUE THREAD

**Issue by xiaoyu2006** [shadowsocks/shadowsocks-libev#2734]
I don't think the [INSTALL](https://github.com/shadowsocks/shadowsocks-libev/blob/master/INSTALL) file should exist anymore. This project use `autotools` to build now, but not the configure file.

Consider to remove this file.

**Comment by madeye** [comment]
`autotools` is not necessary, if you're building from a release package, such as https://github.com/shadowsocks/shadowsocks-libev/releases/download/v3.3.4/shadowsocks-libev-3.3.4.tar.gz
