### ISSUE TITLE
How can I build from source with centos7

### ISSUE THREAD

**Issue by kirito-cwx** [shadowsocks/shadowsocks-libev#2735]
### What operating system are you using?
centos7

**Comment by xiaoyu2006** [comment]
Use the Qt one.

ShadowsocksX-NG is a macOS version.

**Comment by kirito-cwx** [comment]
Do you still need this one ,cent0s7&nbsp;precondition
If you are using CentOS 7, you need to install these prerequirements to build from source code:







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "shadowsocks/shadowsocks-libev"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月15日(星期三) 中午1:56
收件人:&nbsp;"shadowsocks/shadowsocks-libev"<shadowsocks-libev@noreply.github.com&gt;;
抄送:&nbsp;"kirito"<1349687131@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [shadowsocks/shadowsocks-libev] How can I build from source with centos7 (#2735)





 
Use the Qt client.
 
ShadowsocksX-NG is a macOS version.

**Comment by xiaoyu2006** [comment]
> Do you still need this one ,cent0s7&nbsp;precondition If you are using CentOS 7, you need to install these prerequirements to build from source code:
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "shadowsocks/shadowsocks-libev" <notifications@github.com&gt;; 发送时间:&nbsp;2020年7月15日(星期三) 中午1:56 收件人:&nbsp;"shadowsocks/shadowsocks-libev"<shadowsocks-libev@noreply.github.com&gt;; 抄送:&nbsp;"kirito"<1349687131@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [shadowsocks/shadowsocks-libev] How can I build from source with centos7 (#2735) Use the Qt client. ShadowsocksX-NG is a macOS version. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

No, I thought this was posted under ShadowsocksX-NG...
