### ISSUE TITLE
Shadowsocks-(libev) Cannot Allocate xxxx Bytes, Aborting . Aborted (core dumped)

### ISSUE THREAD

**Issue by soheilas** [shadowsocks/shadowsocks-libev#2737]
**╭━┳━╭━╭━╮╮
┃┈┈┈┣▅╋▅┫┃
┃┈┃┈╰━╰━━━━━━╮
╰┳╯┈┈┈┈┈┈┈┈┈◢▉◣
╲┃┈┈┈┈┈┈┈┈┈▉▉▉
╲┃┈┈┈┈┈┈┈┈┈◥▉◤
╲┃┈┈┈┈╭━┳━━━━╯
╲┣━━━━━━┫**﻿
### Hi guys 

I installed shadowsocks-libev on an empty server( just SS Installed) and I am using ss-server and connected to another server (tunnel)

And I connected that server to another proxy and gave the proxy link to my friends so that they could use the proxy, but sometimes or more often I get the following error

> shadowsocks-(libev) cannot allocate xxxxx bytes, aborting . Aborted  (core dumped)

**My CMD :** `ss-tunnel -s Proxy -p ssport-l 1080 -k 3tar -m aes-256-cfb -b 0.0.0.0 -L Proxy:Port`

**P.S :**  _This CMD has no problem and it works well, but after a few minutes, hours, it stops ..._
          ➣ _Number of Simultaneous Connections to My Server is About 80 to 120_

**My Operating System: Ubuntu 18.04x64 ( Ram : 1 Cpu : 1 Core )
shadowsocks-libev : 3.1.3+ds-1ubuntu2 amd64 lightweight**

**BTW** I saw the method in this section but did not understand how to do it and does this method solve my problem?
https://github.com/shadowsocks/shadowsocks-libev/issues/2043#issuecomment-386851495

**Comment by madeye** [comment]
Upgrade your shadowsocks-libev to the latest.
