### ISSUE TITLE
how connect to shadow socks  as  traditional socks 5 ?

### ISSUE THREAD

**Issue by miadz** [shadowsocks/shadowsocks-libev#2739]
hi

how connect to shadow socks  as  traditional socks 5 ?
any advise ?

thank you

**Comment by PantherJohn** [comment]
@miadz Shadowsocks lacks the "session establishment" portion of the traditional SOCKS5 protocol. So answer is **NO**. Shadowsocks and SOCKS5 are completely different protocols, and **what you are asking is not possible right now**, unless they decided to add a compatible layer between Shadowsocks and SOCKS5, which kind of defeats the whole purpose of this project.

**Comment by miadz** [comment]
thank you
