### ISSUE TITLE
when using domain as server address, ss-libev would directly exit if the domain cannot be resolved

### ISSUE THREAD

**Issue by zhou13** [shadowsocks/shadowsocks-libev#274]
For example, if I wrote
````
{
	"server":"example.com",
	......
}
````
and if my network is not available (e.g., when booting), `ss-server` will directly exit with 255 and output
````
 2015-03-05 11:25:19 ERROR: getaddrinfo: Temporary failure in name resolution
 2015-03-05 11:25:19 ERROR: failed to resolve the provided hostname
````

I wish it shadowsocks would retry to resolve the domain until the network becomes available.

**Comment by zhou13** [comment]
BTW, the python version of shadowsocks works under this situation.

**Comment by madeye** [comment]
1. Use IP address instead.
2. Test the network before start shadowsocks.

**Comment by zhou13** [comment]
Is there any good reason not to retry when the first domain resolution fails?

The reason I do not use IP address is that my server contain both IPv4 and IPv6 address.  I want to make shadowsocks to use IPv6 if ipv6 network is available and otherwise use ipv4.  Use IP address will lose this function.

The problem is that I want to start shadowsocks as a system daemon (in systemd), so it is not convenient for me to test the network before start shadowsocks.  Although I can make systemd to restart for me, it is not an elegant solution for me.

**Comment by perqin** [comment]
I recently encountered this issue on Arch Linux. The shadowsocks-libev systemd unit is started very first and network-online.target hasn't been pulled in. Using domain instead of IP address results in the error below:
```
Mar 17 18:01:31 perqin-nuc ss-local[485]:  2019-03-17 18:01:31 ERROR: getaddrinfo: Temporary failure in name resolution
Mar 17 18:01:31 perqin-nuc ss-local[485]:  2019-03-17 18:01:31 ERROR: failed to resolve the provided hostname
Mar 17 18:01:31 perqin-nuc systemd[1]: shadowsocks-libev@1080.service: Main process exited, code=exited, status=255/EXCEPTION
Mar 17 18:01:31 perqin-nuc systemd[1]: shadowsocks-libev@1080.service: Failed with result 'exit-code'.
```
Modifying `/usr/lib/systemd/system/shadowsocks-libev@.service` and adding `Wants` after `After` works well:
```
[Unit]
Description=Shadowsocks-Libev Client Service
After=network-online.target
# Add the line below
Wants=network-online.target

[Service]
Type=simple
User=nobody
CapabilityBoundingSet=CAP_NET_BIND_SERVICE
ExecStart=/usr/bin/ss-local -c /etc/shadowsocks/%i.json

[Install]
WantedBy=multi-user.target
```
Tested on Arch Linux with latest shadowsocks-libev and NetworkManager packages installed.

**Comment by PantherJohn** [comment]
@perqin If I remember correct the “modern” version of `shadowsocks-libev` uses `gethostbyname()` (or `getaddrinfo()` as can be seen in the error message?) for domain resolution. So if it says “failure in domain resolution” it basically means either your DNS server is unreachable (check internet connectivity) or the domain requested does NOT exist on servers specified in `/etc/resolv.conf`. (please double check the domain name you entered for spelling mistakes)

**Comment by perqin** [comment]
@PantherJohn It uses `getaddrinfo()`. The failure only happens during boot, and once I restart the service after having access to the terminal, it works properly. I am going to check the `/etc/resolv.conf` at failure some time later, but I think the issue is caused by no internet connection (because it starts before `network-online.target` is reached, as I mentioned before).

**Comment by eXtrem0us** [comment]
> I recently encountered this issue on Arch Linux. The shadowsocks-libev systemd unit is started very first and network-online.target hasn't been pulled in. Using domain instead of IP address results in the error below:
> 
> ```
> Mar 17 18:01:31 perqin-nuc ss-local[485]:  2019-03-17 18:01:31 ERROR: getaddrinfo: Temporary failure in name resolution
> Mar 17 18:01:31 perqin-nuc ss-local[485]:  2019-03-17 18:01:31 ERROR: failed to resolve the provided hostname
> Mar 17 18:01:31 perqin-nuc systemd[1]: shadowsocks-libev@1080.service: Main process exited, code=exited, status=255/EXCEPTION
> Mar 17 18:01:31 perqin-nuc systemd[1]: shadowsocks-libev@1080.service: Failed with result 'exit-code'.
> ```
> 
> Modifying `/usr/lib/systemd/system/shadowsocks-libev@.service` and adding `Wants` after `After` works well:
> 
> ```
> [Unit]
> Description=Shadowsocks-Libev Client Service
> After=network-online.target
> # Add the line below
> Wants=network-online.target
> 
> [Service]
> Type=simple
> User=nobody
> CapabilityBoundingSet=CAP_NET_BIND_SERVICE
> ExecStart=/usr/bin/ss-local -c /etc/shadowsocks/%i.json
> 
> [Install]
> WantedBy=multi-user.target
> ```
> 
> Tested on Arch Linux with latest shadowsocks-libev and NetworkManager packages installed.

Also add these lines to the [service] section. The systemd service would try every 10 seconds after each failure:
```
Restart=on-failure
RestartSec=10
```
finally:
```
[Unit]
Description=Shadowsocks-Libev Client Service
After=network-online.target
# Add the line below
Wants=network-online.target

[Service]
Type=simple
User=nobody
Restart=on-failure
RestartSec=10
CapabilityBoundingSet=CAP_NET_BIND_SERVICE
ExecStart=/usr/bin/ss-local -c /etc/shadowsocks/%i.json

[Install]
WantedBy=multi-user.target
```
