### ISSUE TITLE
Redirect wireguard traffic to shadowsocks server

### ISSUE THREAD

**Issue by villa4271** [shadowsocks/shadowsocks-libev#2740]
### What version of shadowsocks-libev are you using?

(3.1.3+ds-1ubuntu2
### What operating system are you using?

ubuntu
### What did you do?

I installed both wireguard and shadowsocks servers in the same VPS.
### What did you expect to see?

I want traffics coming from wireguard clients to the wireguard server to be redirected to the shadowsocks server port. So that it will be the shadowsocks server which will make request all over the world. should I use ss-local or ss-redir and how. Transparent proxy with port redirection. The clients know nothing about the shadowsocks server and are not configured. Thanks for the great works. 
### What is your config in detail (with all sensitive info masked)?
"server":"127.0.0.1",
    "server_port":8236,
    "local_port":1080,
    "password":"123467",
    "timeout":60,
    "method":"chacha20-ietf-poly1305"

**Comment by 0neday** [comment]
Not need to redirect to ss-server. Just open kernel forward and configure iptables forward and postrouting rule.

**Comment by maxisacoder** [comment]
you can check this 
https://www.reddit.com/r/WireGuard/comments/fzqj0f/wireguard_shadowsocks/

**Comment by 0neday** [comment]
I realise it sucessfully.
use iptables PREROUTING to redirect all wiregurad server data to 1234 port that is ss-redir listening. Just look your server as a router. 
# ss
ipset create gfw  hash:ip hashsize 4096
setenforce  0
service dnsmasq restart
service iptables restart
iptables -t nat -N GFW
iptables -t nat -A GFW  -p tcp -m set --match-set gfw  dst -j REDIRECT --to-ports 1234
iptables -t nat -I PREROUTING -p tcp -m multiport --dports 80,443 -j GFW

# allow all  wireguard client data
iptables -A INPUT -s 10.0.1.0/24 -j ACCEPT

# and set in dnsmasq.d like 
ipset=/gitbook.io/gfw
....
