### ISSUE TITLE
How can I use ss-manager to get access to internet？

### ISSUE THREAD

**Issue by sigongzi** [shadowsocks/shadowsocks-libev#2745]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?

3.3.4
### What operating system are you using?

Debian10
### What did you do?
wget --no-check-certificate https://raw.githubusercontent.com/teddysun/shadowsocks_install/master/shadowsocks-libev-debian.sh
chmod +x shadowsocks-libev-debian.sh
 ./shadowsocks-libev-debian.sh 2>&1 | tee shadowsocks-libev-debian.log

then I change my /etc/shadowsocks-manager/config.json to

![image](https://user-images.githubusercontent.com/18900591/90312004-88393c80-df33-11ea-882b-ba3b988e905a.png)

then I tape

![image](https://user-images.githubusercontent.com/18900591/90312001-6dff5e80-df33-11ea-9875-6cc60b1cceec.png)

### What did you see instead?

I can't connect to the internet through any port

but I can connect to the port I register on the beginning if I close ss-manager and just run ss-server

**Comment by tianlichunhong** [comment]
shadowsocks-libev does not support multi-ports. Not like shadowsocks.
