### ISSUE TITLE
ERROR: failed to handshake with 10.12.0.44: suspicious UDP packet

### ISSUE THREAD

**Issue by leeecho** [shadowsocks/shadowsocks-libev#2749]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
shadowsocks-libev 3.3.4

### What operating system are you using?
centos 7.6

### What did you do?

ss-server: 2020-09-10 14:16:38 ERROR: crypto: stream: repeat IV detected
ss-server: 2020-09-10 14:16:38 ERROR: failed to handshake with 10.12.0.44: suspicious UDP packet
ss-server: 2020-09-10 14:16:38 ERROR: crypto: stream: repeat IV detected
ss-server: 2020-09-10 14:16:38 ERROR: failed to handshake with 10.12.0.44: suspicious UDP packet
ss-server: 2020-09-10 14:16:38 ERROR: crypto: stream: repeat IV detected
ss-server: 2020-09-10 14:16:38 ERROR: failed to handshake with 10.12.0.44: suspicious UDP packet
ss-server: 2020-09-10 14:16:38 ERROR: crypto: stream: repeat IV detected
ss-server: 2020-09-10 14:16:38 ERROR: failed to handshake with 10.12.0.44: suspicious UDP packet
ss-server: 2020-09-10 14:16:38 ERROR: crypto: stream: repeat IV detected
ss-server: 2020-09-10 14:16:38 ERROR: failed to handshake with 10.12.0.44: suspicious UDP packet
ss-server: 2020-09-10 14:16:38 ERROR: crypto: stream: repeat IV detected
ss-server: 2020-09-10 14:16:38 ERROR: failed to handshake with 10.12.0.44: suspicious UDP packet
ss-server: 2020-09-10 14:16:38 ERROR: crypto: stream: repeat IV detected
ss-server: 2020-09-10 14:16:38 ERROR: failed to handshake with 10.12.0.44: suspicious UDP packet
ss-server: 2020-09-10 14:16:38 ERROR: crypto: stream: repeat IV detected
ss-server: 2020-09-10 14:16:38 ERROR: failed to handshake with 10.12.0.44: suspicious UDP packet
ss-server: 2020-09-10 14:16:38 ERROR: crypto: stream: repeat IV detected
ss-server: 2020-09-10 14:16:38 ERROR: failed to handshake with 10.12.0.44: suspicious UDP packet
ss-server: 2020-09-10 14:16:38 ERROR: crypto: stream: repeat IV detected
ss-server: 2020-09-10 14:16:38 ERROR: failed to handshake with 10.12.0.44: suspicious UDP packet
ss-server: 2020-09-10 14:16:38 ERROR: crypto: stream: repeat IV detected
ss-server: 2020-09-10 14:16:38 ERROR: failed to handshake with 10.12.0.44: suspicious UDP packet
ss-server: 2020-09-10 14:16:41 ERROR: server recv: Connection reset by peer
ss-server: 2020-09-10 14:16:45 ERROR: crypto: stream: repeat IV detected
ss-server: 2020-09-10 14:16:45 ERROR: failed to handshake with 10.12.0.44: suspicious UDP packet
ss-server: 2020-09-10 14:16:54 ERROR: remote recv: Connection reset by peer
ss-server: 2020-09-10 14:16:55 ERROR: remote recv: Connection reset by peer
ss-server: 2020-09-10 14:16:59 ERROR: crypto: stream: repeat IV detected
ss-server: 2020-09-10 14:16:59 ERROR: failed to handshake with 10.12.0.44: suspicious UDP packet
ss-server: 2020-09-10 14:17:01 ERROR: getpeername: Transport endpoint is not connected
ss-server: 2020-09-10 14:17:01 ERROR: getpeername: Transport endpoint is not connected

**Comment by madeye** [comment]
As it said, some suspicious UDP packets come from 10.12.0.44. It's probably a false alarm caused by some service discovery apps in your LAN.
