### ISSUE TITLE
ss-server[758]: [udp] cannot create socket: No buffer space available

### ISSUE THREAD

**Issue by GitatHub** [shadowsocks/shadowsocks-libev#275]
好像是 UDP 错误，请问怎么解决？

另外，发生这个情况的时候，ssh 远程登录也会被拒绝：
“ssh_exchange_identification: Connection closed by remote host” 或
“ssh_exchange_identification: read: Connection reset by peer”

通过控制台重启VPS之后，SHADOWSOCKS 就正常了，SSH也能登录了。
关于 SHADOWSOCKS的问题描述如下（如果信息不足，烦请告诉我还需提供哪些）：

日志 /var/log/syslog:
.........
成百上千行的错误, 内容都是
Mar  5 09:53:35 vpshost /usr/bin/ss-server[758]: [udp] cannot create socket: No buffer space available
Mar  5 09:53:35 vpshost /usr/bin/ss-server[758]: [udp] bind() error: No buffer space available
成百上千行的错误，重复以上两行
........

SHADOWSOCKS VERSION：
shadowsocks-libev 2.1.2
OS:
Description:	Ubuntu 14.04.2 LTS
Release:	14.04
Codename:	trusty

SHADOWSOCKS CONFIG：
{
    "server":["IPV4","[IPV6]"],
    "server_port":PORT,
    "local_port":PORT,
    "password":"PWD",
    "timeout":300,
    "method":"aes-192-cfb",
    "workers":2
}

**Comment by madeye** [comment]
It's not a bug of shadowsocks-libev.
