### ISSUE TITLE
关于UDP连接的NAT类型问题

### ISSUE THREAD

**Issue by Rakau** [shadowsocks/shadowsocks-libev#2751]
三种系统都使用过（ct8、ub20、db10），在正常使用过程中关闭系统的防火墙后NAT连接类型为Full Cone、但是一旦我开启防火墙后（端口已经放行）NAT类型就会降级到Port Restricted Cone，完全不知道该怎么做才能让开启防火墙的情况下让NAT为FullCone

**Comment by Rakau** [comment]
暂时解决了，用防火墙黑名单模式了，不过白名单模式不知道缺少了什么配置？才会导致NAT降级

**Comment by debiansid** [comment]
fullconenat 内核补丁
[Here](https://github.com/Chion82/netfilter-full-cone-nat)

**Comment by Rakau** [comment]
非常谢谢

debiansid <notifications@github.com> 于 2021年1月16日周六 15:16写道：
