### ISSUE TITLE
How do I solve the CPU usage problem?

### ISSUE THREAD

**Issue by MAHDITX** [shadowsocks/shadowsocks-libev#2754]
### What version of shadowsocks-libev are you using?
3.3.4+ds-2

### What operating system are you using?
Ubuntu 20.04.1 LTS 

### What did you do?
I tunneled two servers

![image](https://user-images.githubusercontent.com/13077837/94048127-e2a1a480-fddf-11ea-8a50-82068fc87b58.png)

### What did you expect to see?
To work properly, Like my other server

### What did you see instead?
This was working properly for a month but for a week now, this service has been consuming 100% of the CPU and when I restart this service (systemctl restart mtss) CPU consumption becomes about 2-3%

This 100% CPU consumption occurs almost once a day
How can I solve this problem?

### What is your config in detail (with all sensitive info masked)?
[Unit]
Description = Proxy Shadowsocks
StandardOutput = null
StandardError = null
After=network.target
[Service]
#LimitNOFILE=infinity
Type = simple
ExecStart = /usr/bin/ss-tunnel -s 1.1.1.1 -p 9378 -l 443 -k password -m chacha20-ietf-poly1305 -b 0.0.0.0 -L 1.1.1.1:443
StartLimitBurst=0
[Install]
WantedBy = multi-user.target

**Comment by madeye** [comment]
Increase the maximum number of open file descriptors:

http://shadowsocks.org/en/config/advanced.html
