### ISSUE TITLE
install with build_deb.sh failed with error:ppbloom.c:91:9: error: implicit declaration of function ‘bloom_reset’; did you mean ‘bloom_free’? 

### ISSUE THREAD

**Issue by clsycw** [shadowsocks/shadowsocks-libev#2757]
# What version of shadowsocks-libev are you using?

N/A, initial installation

### What operating system are you using?

Linux nems 4.4.167-1161-rockchip-ayufan-g6f1664023387 #1 SMP Fri Mar 22 23:03:38 UTC 2019 aarch64 GNU/Linux
root@nems:~/build-area$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

### What did you do?
 ran build_deb.sh script

### What did you see instead?
this is partial error message: ppbloom.c: In function ‘ppbloom_add’:
ppbloom.c:91:9: error: implicit declaration of function ‘bloom_reset’; did you mean ‘bloom_free’? [-Werror=implicit-function-declaration]
         bloom_reset(ppbloom + current);
         ^~~~~~~~~~~
         bloom_free
cc1: all warnings being treated as errors
make[3]: *** [Makefile:1141: ss_local-ppbloom.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: Leaving directory '/home/root/build-area/shadowsocks-libev/src'
make[2]: *** [Makefile:488: all-recursive] Error 1
make[2]: Leaving directory '/home/root/build-area/shadowsocks-libev'
make[1]: *** [Makefile:391: all] Error 2
make[1]: Leaving directory '/home/root/build-area/shadowsocks-libev'
dh_auto_build: make -j4 returned exit code 2
make: *** [debian/rules:47: binary] Error 2
dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2
debuild: fatal error at line 1182:
dpkg-buildpackage -us -uc -ui -i -I failed
gbp:error: 'debuild -i -I -us -uc' failed: it exited with 29
Removing .pc/

### What is your config in detail (with all sensitive info masked)?
N/A
[NEMS install shadowsocks-libev  with  build_deb.sh  script failed.txt](https://github.com/shadowsocks/shadowsocks-libev/files/5290331/NEMS.install.shadowsocks-libev.with.build_deb.sh.script.failed.txt)

**Comment by starter48** [comment]
I believe issue #2671 is same problem about. I.e. you have to update **libbloom** subdir.

**Comment by clsycw** [comment]
> I believe issue #2671 is same problem about. I.e. you have to update **libbloom** subdir.

The only thing I did is running build_deb.sh script. is it means build_deb.sh script need to be update?

**Comment by starter48** [comment]
I think you have to reinstall **shadowsocks-libev** sources before building it with **build_deb.sh** script.
Compare your local copy of **libbloom/bloom.c** and **libbloom/bloom.h** files with repository stored ones.
It seems **build_deb.sh** doesn't _update_ files correctly. I.e. it does work well only with fresh install and thus need to be improved.

**Comment by clsycw** [comment]
> I think you have to reinstall **shadowsocks-libev** sources before building it with **build_deb.sh** script.
> Compare your local copy of **libbloom/bloom.c** and **libbloom/bloom.h** files with repository stored ones. I believe your local copy of **libbloom/** subdir is outdated.
> It seems **build_deb.sh** doesn't _update_ files correctly. I.e. it does work well only with fresh install and thus need to be improved.

**Comment by clsycw** [comment]
There is not old version installed. It's fresh install. not upgrade. and I only upload build_deb.sh script to the single board computer to install. not any other files are transferred. all files downloaded by script. I believed build_deb.sh script will not working with fresh install as well.

**Comment by clsycw** [comment]
end up installed with the following step:
[NEMS install shadowsocks-libev.txt](https://github.com/shadowsocks/shadowsocks-libev/files/5301564/NEMS.install.shadowsocks-libev.txt)


root@nems:~$ sudo git clone --recurse-submodules https://github.com/shadowsocks/shadowsocks-libev.git

root@nems:~$ cd shadowsocks-libev/

root@nems:~/shadowsocks-libev$ sudo apt-get install --no-install-recommends autoconf automake
debhelper pkg-config asciidoc xmlto libpcre3-dev apg pwgen rng-tools
libev-dev libc-ares-dev dh-autoreconf libsodium-dev libmbedtls-dev

root@nems:~/shadowsocks-libev$ sudo apt install rng-tools

root@nems:~/shadowsocks-libev$ sudo apt-get install --no-install-recommends autoconf automake debhelper pkg-config asciidoc xmlto libpcre3-dev apg pwgen libev-dev libc-ares-dev dh-autoreconf libsodium-dev libmbedtls-dev

root@nems:~/shadowsocks-libev$ sudo ./autogen.sh && sudo dpkg-buildpackage -b -us -uc

root@nems:~/shadowsocks-libev$ cd ..

root@nems:~$ sudo dpkg -i shadowsocks-libev*.deb

root@nems:~$ sudo ss-server -v
