### ISSUE TITLE
build_deb.sh script does not download 3 submodules: libbloom, libcork, libipset

### ISSUE THREAD

**Issue by clsycw** [shadowsocks/shadowsocks-libev#2758]
There is not old version installed. It's fresh install. not upgrade. and I only upload build_deb.sh script to the single board computer to install. not any other files are transferred. all files downloaded by script. I believed build_deb.sh script will not working with fresh install as well.

_Originally posted by @clsycw in https://github.com/shadowsocks/shadowsocks-libev/issues/2757#issuecomment-700767288_

**Comment by clsycw** [comment]
end up installed with the following step:
[NEMS install shadowsocks-libev.txt](https://github.com/shadowsocks/shadowsocks-libev/files/5301545/NEMS.install.shadowsocks-libev.txt)


root@nems:~$ sudo git clone --recurse-submodules https://github.com/shadowsocks/shadowsocks-libev.git

root@nems:~$ cd shadowsocks-libev/

root@nems:~/shadowsocks-libev$ sudo apt-get install --no-install-recommends autoconf automake \
  debhelper pkg-config asciidoc xmlto libpcre3-dev apg pwgen rng-tools \
  libev-dev libc-ares-dev dh-autoreconf libsodium-dev libmbedtls-dev

root@nems:~/shadowsocks-libev$ sudo apt install rng-tools

root@nems:~/shadowsocks-libev$ sudo apt-get install --no-install-recommends autoconf automake  debhelper pkg-config asciidoc xmlto libpcre3-dev apg pwgen  libev-dev libc-ares-dev dh-autoreconf libsodium-dev libmbedtls-dev

root@nems:~/shadowsocks-libev$ sudo ./autogen.sh && sudo dpkg-buildpackage -b -us -uc

root@nems:~/shadowsocks-libev$ cd ..

root@nems:~$ sudo dpkg -i shadowsocks-libev*.deb

root@nems:~$ sudo ss-server -v

**Comment by joeytwiddle** [comment]
Thank you for the tips.

If you have already cloned the repo, you can fetch the extra folders with:

```
git submodule init
git submodule update
```

It might be nice if `autogen.sh` could give this tip along with the error message, if it notices one of the submodules is missing.
