### ISSUE TITLE
When use windows task scheduler to run ss-local with simple-obfs then access denied

### ISSUE THREAD

**Issue by ghost** [shadowsocks/shadowsocks-libev#2761]
### What version of shadowsocks-libev are you using?
shadowsocks-libev 3.3.4

  maintained by Max Lv <max.c.lv@gmail.com> and Linus Yang <laokongzi@gmail.com>

### What operating system are you using?
Windows 10 Professional 1909

### What did you do?
Im using windows task scheduler to run ss-local with simple-obfs then ss-local threw me access denied, im tried Administrator and even doesn't work.

If i remove simple-obfs from the ss-local commandline, then ss-local running successfully in task scheduler.

### What did you expect to see?
ss-local and simple-obfs work successfully.

### What did you see instead?
doesn't work, access denied.

### What is your config in detail (with all sensitive info masked)?
ss-local.exe -s myserverip -p myserverpassword -l 1080 -k mypassword -m xchacha20-ietf-poly1305 -u --plugin simple-obfs --plugin-opts obfs=http;obfs-host=www.bing.com

**Comment by feu164** [comment]
![Uploading 95479970-edeaf780-09bd-11eb-9902-c5e81f3f99ab.jpg…]()

**Comment by feu164** [comment]
![95479970-edeaf780-09bd-11eb-9902-c5e81f3f99ab](https://user-images.githubusercontent.com/71811661/95495352-e33a5d80-09d1-11eb-9a03-7c8eb1179b4c.jpg)

**Comment by studentmain** [comment]
https://stackoverflow.com/questions/447774/specifying-the-running-directory-for-scheduled-tasks-using-schtasks-exe
