### ISSUE TITLE
How to monitor connected devices?

### ISSUE THREAD

**Issue by samirmhsnv** [shadowsocks/shadowsocks-libev#2764]
I have configuration with v2ray plugin+shadowsocks-libev+nginx reverse proxy on DebianBuster. How can I list currently or previously connected devices ?

**Comment by OmiceyO** [comment]
Would also really like to know so far i can only see in netstat -a but its a pain to go looking for them. Let me know if you have a better way!

**Comment by samirmh-dev** [comment]
@OmiceyO 

actually I figured out problem by using HaProxy monitoring. I placed Shadowsocks server after pfSense and traffic is going through pfSense => HaProxy => Shadowsocks.  

It shows connected clients IPs and Ports as List. 

Not good solution by sometimes helps to recognize connected IP is trusted or not.

**Comment by OmiceyO** [comment]
@samirmh-dev Can you explain a bit how exactly did you achieve that?

**Comment by samirmh-dev** [comment]
@OmiceyO 

My Shadowsocks setup configured on Debian 10 VPS. Let's say it's IP is 10.9.8.7.

Request flow is below.  

## Flow

````
   +------+    +----------+    +----------+  +---------v------------+
   |Client+----+domain.com+----+CloudFlare+-->CloudFlare's DNS Proxy+--+
   +-+----+    +----------+    +----------+  +----------------------+  |
     ^                                                                 |
     |                                        +-------+    +-------+   |
     |                                        |HAProxy+----+pfSense+<--+
     |                                        +---+---+    +-------+
     |                                            |
     |                                       +----+---+  +-----------+
     |            +--------------+           |10.9.8.7+->+   nGinx   |
     |            |              |           +--------+  |     +     |
     +------------+   Internet   |                       |     +     |
Response to from  |           ^  |                       |   v2ray   |
server to client  +--------------+                       |     +     |  VPS
                              |                          |     +     |
                              |                          |  libev.   |
                              |                          |           |
                              |                          +----+------+
                              |                               |
                              +-------------------------------+
                                       Request of Client
````

## Setup

1) First you need pfSense configured on your VPS/VDS.
2) You need do HAProxy configured and connected to your domain which will be used for Shadowsocks.

I don't dive into how to configure pfSense + HaProxy and Shadowsocks. There is lots of tutorials on the web.

When everything is configured and Shadowsocks is working over pfSense you can configure HaProxy and add widget to Dashboard.

3) at your HaProxy Frontend for Shadowsocks domain you add Custom ACL on `Default Backend, access control list and actions tab`

ACL Type: Custom
Value: `http-request set-src hdr(x-forwarded-for)`

This will replace CloudFlare's IP with User's Real IP.

![image](https://user-images.githubusercontent.com/54883542/100577894-9ea8af80-32fa-11eb-82fa-ccbcbc291f40.png)

4) Then at the main page of pfSense you need to press + button on top right and Select HAProxy.

Then try to connect Shadowsocks. Connected users request IP:PID will be added LocalStats block. And will be updated dynamicly.

![image](https://user-images.githubusercontent.com/54883542/100577976-c861d680-32fa-11eb-9c68-848e8c34ee2b.png)

As I mentioned above this is not the best solution. But sometimes it helps to recognize connected IP is trusted or not.

**Comment by pundoo** [comment]
_somewhat helpful_ - `netstat -atun | grep <PORT>`

**Comment by pacal683** [comment]
On 03-Mar-21 04:28, pundoo wrote:
>
> /somewhat helpful/ - |netstat -atun | grep <PORT>|
>
I use monit on my ubuntu server on a RaspberryPi 4 with 4GB, I also
monitor using ss-manager and monit, but that's for adding extra ports
when connections on a single port exceed a set max limit on threads

check process shadowsocks-server with match "ss-server"
    start program = "/etc/init.d/shadowsocks-libev start"
    stop program  = "/etc/init.d/shadowsocks-libev stop"
    if failed host 127.0.0.1 port 8138 type TCP then restart
    if failed host 127.0.0.1 port 8138 type UDP then restart
    if 3 restarts within 5 cycles then timeout
    depends on shadowsocks-server_bin
    depends on shadowsocks-server_conf
    group proxy
    group server

check file shadowsocks-server_bin with path /usr/bin/ss-server
    if failed permission 755 then unmonitor
    if failed uid root then unmonitor
    group proxy
    group server

check file shadowsocks-server_conf with path
/etc/shadowsocks-libev/config.json
    if failed permission 640 then unmonitor
    if failed uid root then unmonitor
    group proxy
    group server


Cheers,
/pacal

**Comment by arkfalak** [comment]
show sorted ip list of live established connections at <port> :
`netstat -atun | awk '$4 ~ /:<port>$/ && $6 == "ESTABLISHED" {print $5}' | awk -F: '{print $1}' | sort | uniq`
Change <port> to shadowsocks port

**Comment by heibao2021** [comment]
> show sorted ip list of live established connections at `<port>` : `netstat -atun | awk '$4 ~ /:<port>$/ && $6 == "ESTABLISHED" {print $5}' | awk -F: '{print $1}' | sort | uniq` Change `<port>` to shadowsocks port

ty you for this. can verify this worked for me on Ubuntu. Can see all ips logged into the server. Ty again
