### ISSUE TITLE
window将代理设置为ss-local地址http报Error: socket hang up

### ISSUE THREAD

**Issue by ztgoto** [shadowsocks/shadowsocks-libev#2765]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
3.3.5

### What operating system are you using?
windows,linux

### What did you do?
想通过shadowsocks打通本地和k8s网络便于调试,将ss-local部署到linux服务器，ss-server部署到k8s中
本地环境windows通过设置代理地址到ss-local监听地址

### What did you expect to see?
希望window能正常访问k8spod ip

### What did you see instead?
通过 curl --socks5 ss-local-addr http://10.244.240.176:8080/actuator/prometheus 访问正常
可window访问报Error: socket hang up 或者 ERR_EMPTY_RESPONSE (chrome)

**Comment by madeye** [comment]
Try https://github.com/shadowsocks/shadowsocks-windows
