### ISSUE TITLE
How to bind a specific interface's port (ss-server) ?

### ISSUE THREAD

**Issue by tsaitung-n** [shadowsocks/shadowsocks-libev#2770]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
v3.3.5 pre-built package

### What operating system are you using?
Ubuntu 20.04 LTS

### What did you do?
I want to bind a specific interface's port.

### What did you expect to see?
Background: eth0 has Internet access, other interfaces not.
I want to connect to the server via eth0 port 53. Because of the occupation of other interfaces' port 53, I can't simply change the listen port.

### What did you see instead?
I used -i eth0 ,but the server doesn't work. Since I use Shadowsocks to connect to the server, it loses control.

### What is your config in detail (with all sensitive info masked)?
I can't retrive it since I lose the control of the server.

**Comment by madeye** [comment]
`-s <your_eth0_ip>`

**Comment by tsaitung-n** [comment]
> `-s <your_eth0_ip>`

thanks!
