### ISSUE TITLE
get_sockaddr in Acl handle will cause network hang

### ISSUE THREAD

**Issue by yzou** [shadowsocks/shadowsocks-libev#2772]
### What version of shadowsocks-libev are you using?
Latest

### What operating system are you using?
macOS 10.15.6

### What did you do?

1.  Run ss-local 
`./ss-local -s 122.x.x.x -p 3634 -b 0.0.0.0 -l 1080 -k 9d2e580c67a1f6f -m chacha20-ietf-poly1305 -t 300 -u -v --acl bypass-lan-china.acl
`
2. Set Chrome proxy to 127.0.0.1:1080
3. Open some websites, such as taobao.com
4. Web pages got hang for about 30 seconds sometimes

### What did you expect to see?
Browse without hang

### What did you see instead?
All proxis blocked if one of the request got hang.

From ss-local log, the request is blocked by getaddrinfo in get_sockaddr of acl processing.

![image](https://user-images.githubusercontent.com/1464693/99792024-77671b00-2b61-11eb-9b94-4643ce8b02ca.png)
![image](https://user-images.githubusercontent.com/1464693/99792054-84840a00-2b61-11eb-9c1e-3f80ff2f5095.png)

From Wireshark captured packets, the blocking happens when then DNS replies are dropped with ICMP port unreachable. It seems the local UDP ports of DNS requests are closed before the replies arrive.

The getaddrinfo request blocks all other proxy requests. The DNS request in Acl processing should use Asynchronous methods like in c-ares.

### What is your config in detail (with all sensitive info masked)?

`./ss-local -s 122.x.x.x -p 3634 -b 0.0.0.0 -l 1080 -k 9d2e580c67a1f6f -m chacha20-ietf-poly1305 -t 300 -u -v --acl bypass-lan-china.acl
`

**Comment by madeye** [comment]
It's expected.

Try https://github.com/shadowsocks/shadowsocks-rust for non-blocking ACL support.

**Comment by yzou** [comment]
Tried shadowsocks-rust, it consumes more memory on the mobile device, iOS has a 15MB limits.
