### ISSUE TITLE
ss-local only sending localhost traffic, not LAN traffic

### ISSUE THREAD

**Issue by please-be-nice** [shadowsocks/shadowsocks-libev#2777]
### What version of shadowsocks-libev are you using?
focal 3.3.4+ds-2 amd64

### What operating system are you using?
Ubuntu Focal Fossa 20.04

### What did you do?
set up ss-server on Ubuntu 20.04 in cloud. Installed Windows client, connected to cloud_ip:port and shared connection from 1080 on LAN so other LAN devices can use proxy. Worked as expected. I then set up ss-local on LAN Ubuntu 20.04 server and bound 0.0.0.0:1080 but ss-local won't send LAN traffic, only traffic from localhost.

### What did you expect to see?
from localhost -> curl --socks5 127.0.0.1:1080 https://www.wtfismyip.com/json RESPONSE
from LAN PC -> Invoke-WebRequest -Proxy http://192.168.22.21:1080 -Uri http://www.wtfismyip.com/json RESPONSE

### What did you see instead?
from localhost -> curl --socks5 127.0.0.1:1080 https://www.wtfismyip.com/json RESPONSE
from LAN PC -> Invoke-WebRequest -Proxy http://192.168.22.21:1080 -Uri http://www.wtfismyip.com/json "Error: connection was closed unexpectedly"

shadowsocks.service logs show connection from (LAN IP) , connect to (WAN IP), remote (SERVER IP) when curl from localhost, but logs only show connection from (LAN IP) twice and then nothing else when connecting from any other LAN device.

### What is your config in detail (with all sensitive info masked)?
local.json
{
     "server":"server_pub_ip",
     "server_port":"8388",
     "local_address":"0.0.0.0",
     "local_port":"1080",
     "password":"some_password",
     "method":"aes-256-gcm",
     "timeout":5
}

ufw status verbose:
Status: active
Logging: on (low)
Default: deny (incoming), allow (outgoing), disabled (routed)
New Profiles: skip

1080/tcp -> ALLOW IN -> Anywhere
1080/udp -> ALLOW IN -> Anywhere
1080/tcp (v6) -> ALLOW IN -> Anywhere (v6)
1080/udp (v6) -> ALLOW IN -> Anywhere (v6)

/etc/systemd/system/shadowsocks.service
[Service]
User=root
Group=root
Type=simple
ExecStart=/usr/local/bin/ss-local -c /etc/shadowsocks/local.json -a shadowsocks -v start

**Comment by madeye** [comment]
I cannot reproduce your problem locally. Double check your firewall rules and connections.

Without considering firewall rules, you can check shadowsocks's function like this:

```
ss-local -c your_config.json -b 127.0.0.2
curl --socks5 127.0.0.2 https://www.google.com
```

If it works, your problem should not be related to shadowsocks.

**Comment by please-be-nice** [comment]
Ok I tried this but after initializing ciphers and listening it said "Error: Bind: Address already in use". I left my config file same as above

**Comment by madeye** [comment]
It means you have some conflicts on port 1080.

Try other port like 1081 instead.

**Comment by madeye** [comment]
Also shadowsocks works as a socks5 proxy, not HTTP proxy. I see you're trying use it as a HTTP proxy on your LAN device.

**Comment by please-be-nice** [comment]
When I installed the windows client and shared the connection, then pointed my nintendo switch at my PC in proxy settings it worked exactly how I wanted it to. I was just trying to recreate that on a Ubuntu server

**Comment by madeye** [comment]
So it's nothing to do with shadowsocks-libev port binding.

What you're looking for is a HTTP proxy, which is not supported.

**Comment by please-be-nice** [comment]
Ah I see. Sorry for wasting your time, thanks for the help anyways

**Comment by please-be-nice** [comment]
would ss-redir do what I want as well?

**Comment by mfat** [comment]
You can use privoxy or polipo to share ss as http proxy.
