### ISSUE TITLE
Why ping stops when i connect to shadowsocks server using outline client? 

### ISSUE THREAD

**Issue by hbtechnologia** [shadowsocks/shadowsocks-libev#2778]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?

Latest
### What operating system are you using?
Centos 7
Linux 3.10.0-1160.6.1.el7.x86_64
### What did you do?
Connected with SS Server using outline client.

### What did you expect to see?
Ping should also work.

### What did you see instead?
But it gives "Request time out" after successful connection with server.

### What is your config in detail (with all sensitive info masked)?
{
    "server":"IP Address of Server",
    "server_port":1122,
    "password":"password",
    "local_port":1080,
    "timeout":300,
    "method":"cipher-name",
    "name_server":"8.8.8.8",
    "fast_open": true,
    "mode": "tcp_and_udp"
}

**Comment by hbtechnologia** [comment]
@dev4u  what u think ?

**Comment by dev4u** [comment]
> @dev4u  what u think ?

ping既不走tcp，也不走udp。

**Comment by hbtechnologia** [comment]
> > @dev4u  what u think ?
> 
> ping既不走tcp，也不走udp。

so what should i do to enable ping ?

**Comment by hbtechnologia** [comment]
https://stackoverflow.com/questions/5274934/use-ping-through-socks-server
https://www.reddit.com/r/outlinevpn/comments/axqay1/is_outline_a_real_vpn/
