### ISSUE TITLE
开启 ipv6_first 后，域名解析出错

### ISSUE THREAD

**Issue by jinliming2** [shadowsocks/shadowsocks-libev#2782]
### What version of shadowsocks-libev are you using?
shadowsocks-libev 3.2.5

### What operating system are you using?
Debian 10 (4.19.160-2)

### What did you do?
之前服务端用的 python 的 3.0.0 版（客户端一直用的 libev），今天做了个更新，替换到了 libev 版本，直接从 apt 源装的。

配置文件做了小改动，server 改成了数组，加了 mode、no_delay、nameserver 三个选项，ipv6_first 选项在旧版就一直开启着的，一直没有问题。

更新之后，如果 ipv6_first 开启会出现不支持 v6 的网站无法访问。

### What did you expect to see?
在开启 ipv6_first 后，访问不支持 v6 的网站会回退到 v4。

### What did you see instead?
开启 ipv6_first 后，支持 v6 的网站可以正常访问，不支持 v6 的网站被解析到错误的地址，如图，verbose 日志的解析记录地址后面被追加了一个域名后缀（已打码），导致解析到一个错误的 v6 地址。

![image](https://user-images.githubusercontent.com/10294977/102868671-6c135200-4475-11eb-8890-aa4de31bde75.png)

### What is your config in detail (with all sensitive info masked)?
配置文件（部分内容已省略）：
```json
{
    "server":["::", "0.0.0.0"],
    "mode":"tcp_and_udp",
    "server_port":<......>,
    "password":"<......>",
    "timeout":60,
    "fast_open":true,
    "no_delay":true,
    "ipv6_first":true,
    "nameserver":"8.8.8.8",
    "method":"<......>"
}
```

**Comment by madeye** [comment]
Post your `/etc/resolv.conf` here.

**Comment by jinliming2** [comment]
@madeye 
![image](https://user-images.githubusercontent.com/10294977/102870628-3d4aab00-4478-11eb-9c1e-e5a944b15ba7.png)

**Comment by madeye** [comment]
Try those things:

1. Update to 3.3.5.
2. Remove  `"nameserver":"8.8.8.8",` from your config.

It looks related to misconfiguration of your system IPv6 networks, which has a search domain for all the IPv6 resolvers.

**Comment by jinliming2** [comment]
升级到 3.3.5 、删除 nameserver 也是同样的问题。

测试访问一个不存在的域名，v4 解析时也会自动增加相同的后缀。看起来像是 DNS search domain，但是系统应该是没有配置过 search domain。

我再找找原因。

**Comment by jinliming2** [comment]
找到原因了，系统配置了 hostname，`sudo hostnamectl set-hostname ""` 清除掉就正常了。

**Comment by profection** [comment]
试过了不行，得配置多个nameserver才行，配置如下：
"nameserver":"8.8.8.8,2001:67c:2b0::4"
或者参数加-d 8.8.8.8,2001:67c:2b0::4
前一个负责解析ipv4，后一个ipv6
