### ISSUE TITLE
build failed after commit 7e5922a

### ISSUE THREAD

**Issue by manjuprajna** [shadowsocks/shadowsocks-libev#2797]
### What version of shadowsocks-libev are you using?
after commit 7e5922aa443ba7bc156bcdfe6ca58426d2a4c583

### What operating system are you using?
both ubuntu 18.04 & 20.04

### What did you do?
try to build

### What did you expect to see?
successful build

### What did you see instead?

configure.ac:26: error: possibly undefined macro: AC_MSG_ERROR
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:146: error: possibly undefined macro: AC_CHECK_HEADERS
configure.ac:256: error: possibly undefined macro: AC_SEARCH_LIBS
autoreconf: /usr/bin/autoconf failed with exit status: 1

before commit 7e5922a no problem.

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks-libev/runs/2083250155

**Comment by madeye** [comment]
double check if `pkg-config` package is missing

**Comment by madeye** [comment]
Also check the dependency list here: https://github.com/shadowsocks/shadowsocks-libev#linux

**Comment by manjuprajna** [comment]
> double check if `pkg-config` package is missing

exactly, miss pkg-config.

so I did a make clean but got such errors:

./configure: line 16343: syntax error near unexpected token `NETFILTER_CONNTRACK,'
./configure: line 16343: `          PKG_CHECK_MODULES(NETFILTER_CONNTRACK, libnetfilter_conntrack,,'
Makefile:418: recipe for target 'config.status' failed
make: *** [config.status] Error 2

can I ignore it?

I redo it, no error message anymore.

thank you and you may close it.

**Comment by xkszltl** [comment]
Actually you don't need to do `make clean` for a git repo, `git clean -dfx` will simply wipe our whatever built previously.
