### ISSUE TITLE
ERROR: remote recv: Connection reset by peer appeared frequently  

### ISSUE THREAD

**Issue by azuis** [shadowsocks/shadowsocks-libev#282]
In ss-redir mode, there are higher chance that "remote recv:  Connection reset by peer " error  appeared after daemon started for few hours. Also it is possible that all the connection between ss-redir and ss-server was reset. Once restart ss-redir, this problem will be solved temporarily. 

shadowsocks-libev 2.1.4

**Comment by madeye** [comment]
It just works well. 

The "error" here means the remote server close the TCP connection with a RESET, which can be caused by timeout or network issue.
