### ISSUE TITLE
[Feature Request]可不可以支持将 config 编译进 binary？

### ISSUE THREAD

**Issue by marguerite** [shadowsocks/shadowsocks-libev#283]
使用案例大概像这样：

我想给特定一类人群（比如某某 Linux 的用户）提供 shadowsocks，但又不想让他们继续 share 我的 config 信息给其他人。于是我想可不可以有一个机制，让你分发的 shadowsocks 的配置对一般用户是不可见的，但是这个客户端又是日常可用的。

marguerite

**Comment by madeye** [comment]
No plan for this.

**Comment by JohnnySun** [comment]
可以自己修改源代码编译

**Comment by JohnnySun** [comment]
修改local.c
