### ISSUE TITLE
ss-server --manager-address no effect

### ISSUE THREAD

**Issue by jearton** [shadowsocks/shadowsocks-libev#2849]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?

shadowsocks-libev 3.3.5

### What operating system are you using?
centos7

### What did you do?
 ss-server -c /etc/shadowsocks-libev/config.json -v --manager-address 127.0.0.1:6001

### What did you expect to see?
6001 port is on udp

### What did you see instead?
6001 port not startup

### What is your config in detail (with all sensitive info masked)?
```json
{
    "server": "0.0.0.0",
    "server_port": 8388,
    "password": "*******",
    "timeout": 60,
    "method": "chacha20-ietf-poly1305",
    "fast_open": true,
    "no_delay": true,
    "reuse_port": true,
    "mode": "tcp_and_udp",
    "plugin": "v2ray-plugin",
    "plugin_opts": "server;tsl;host=****;fast-open;cert=*****;key=*****"
}
```

**Comment by lixingcong** [comment]
Start ss-manager first, then start ss-server.

```
/usr/local/bin/ss-manager -c config1.json --manager-address 127.0.0.1:6001
/usr/local/bin/ss-server -c config2.json --manager-address 127.0.0.1:6001
```

**Comment by jearton** [comment]
@lixingcong You are right!
