### ISSUE TITLE
Key size for ciphers

### ISSUE THREAD

**Issue by iheartlasers** [shadowsocks/shadowsocks-libev#285]
Looking at the source code, I see blowfish has a 16 byte (128 bits) key.  It looks like that keylength is set in just one location in the encrypt.c file. If that number were changed from 16 bytes (128 bits) to 32 bytes (256 bits), would shadowsocks then use blowfish with a 256 bit key?

(I know that would break compatibility with other shadowsocks clients/servers that were not compiled with this change, but just want to know if I have identified all that would need to be done to have 256 bit blowfish keys used instead of the default 128 bit)

Thank you.

**Comment by madeye** [comment]
Yes, it should work.
