### ISSUE TITLE
[Feature request] is it possible to add support for shadowsocks-2022 ciphers?

### ISSUE THREAD

**Issue by sophauer** [shadowsocks/shadowsocks-libev#2905]
Please Add support for shadowsocks-2022 ciphers:

2022-BLAKE3-AES-128-GCM
2022-BLAKE3-AES-256-GCM
2022-BLAKE3-CHACHA20-IETF-POLY1305

best regards

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks-rust

**Comment by cary-sas** [comment]
so, shadowsocks-libev will not add this new feature anymore?

**Comment by cary-sas** [comment]
> 

 both I think, especially for the client support
