### ISSUE TITLE
shandowsocks-libev无法同时监听ipv4和ipv6端口了

### ISSUE THREAD

**Issue by maz-1** [shadowsocks/shadowsocks-libev#291]
RT，今天在vps上重新编译了shadowsocks-libev服务端，发现shadowsocks无法同时监听ipv4和ipv6端口了。以前只要填写
"server":"::",
就可以同时监听ipv4和ipv6端口。更新之后再这么填写就只会监听ipv6端口，ipv4无法访问。

**Comment by madeye** [comment]
Duplicate with #254
