### ISSUE TITLE
shadowsocks package doesn't appear in OpenWRT "make menuconfig"

### ISSUE THREAD

**Issue by jchia** [shadowsocks/shadowsocks-libev#294]
On r45248 of OpenWrt, on a clean repo, after I have git cloned the shadowsocks-libev git repo from the packages directory, when I run "make menuconfig", I can't find the shadowsocks package. It's not in 'Network' and I can't find it anywhere else either. I also git cloned ChinaDNS git repo but it doesn't have this problem.

**Comment by madeye** [comment]
Tested on the trunk and it works.

**Comment by jchia** [comment]
This is a fresh svn checkout. This is what I did. Is there any I missed? I can see ChinaDNS, so it's unlikely that I did something wrong.

```
17:10 openwrt$ svn info
Path: .
Working Copy Root Path: /home/jchia/svn/openwrt
URL: svn://svn.openwrt.org/openwrt/trunk
Relative URL: ^/trunk
Repository Root: svn://svn.openwrt.org/openwrt
Repository UUID: 3c298f89-4303-0410-b956-a3cf2f4a3e73
Revision: 45277
Node Kind: directory
Schedule: normal
Last Changed Author: blogic
Last Changed Rev: 45277
Last Changed Date: 2015-04-05 15:53:32 +0800 (Sun, 05 Apr 2015)

17:10 openwrt$ ls -d package/shadowsocks-libev/
package/shadowsocks-libev/
17:10 openwrt$ make menuconfig
```

**Comment by madeye** [comment]
![image](https://cloud.githubusercontent.com/assets/627917/6996461/5a966b0c-dbbc-11e4-884f-affba6af9d09.png)

Tried again, it just works. And yes, put `shadowsocks-libev` in `package/`

**Comment by jchia** [comment]
The interesting thing is that after I removed the ChinaDNS directory from the package directory, shadowsocks appears in menuconfig.
