### ISSUE TITLE
Hi， 请教下为什么ss-redir能够中转流量

### ISSUE THREAD

**Issue by bcheng049** [shadowsocks/shadowsocks-libev#296]
iptables redirect中转数据包的时候应该会修改掉数据包的目标端口，那ss-redir是怎样获取要访问的目标端口呢？这个问题始终没有明白，求教，万分感谢！

**Comment by madeye** [comment]
http://www.karlrupp.net/en/computer/nat_tutorial

https://github.com/shadowsocks/shadowsocks-libev/blob/master/src/redir.c#L91

**Comment by ownhere** [comment]
这是为何ss-redir必须运行在网关上的原因，因为内存里的conntrack记录了原始目的地址，如果是DNAT转发到其他机器做处理就得不到原始目的地址了，不过现代内核使用REDIRECT会有触发内核的安全机制容易失败，最好用DNAT转发到本机的非127.0.0.1地址上。

**Comment by bcheng049** [comment]
OK，明白了，感谢大神的指点，我再查下conn track的文档！看了 dnat和redirect的文档，会改变数据包，所以一直在思考ss-redir如何能取到源数据包的信息！经过指点之后有个学习的方向了！
