### ISSUE TITLE
Can't start shadowsocks-libev service via Snap

### ISSUE THREAD

**Issue by Keroronsk** [shadowsocks/shadowsocks-libev#2963]
Hello. I'm using:

shadowsocks-libev 3.3.4

Debian 11

Snap    2.58.2

After I did install shadowsocks-libev according to manual: sudo snap install shadowsocks-libev
and try to run it as service: snap start shadowsocks-libev.ss-server
I got error: snap "shadowsocks-libev" has no service "ss-server"

If I run /snap/bin/shadowsocks-libev.ss-server directly, it working as intended.

How to run shadowsocks-libev as service?

p.s. Shadowsocks-libev 3.3.5 with Snap 2.58.2 working on Debian 10 without any problem in both service and app mode.

**Comment by Keroronsk** [comment]
Upgraded shadowsocks-libev to version 3.3.5 via snap install shadowsocks-libev --edge and it started as Snap service too.

**Comment by cross-hello** [comment]
[Write system service](https://medium.com/@benmorel/creating-a-linux-service-with-systemd-611b5c8b91d6 ) yourself
