### ISSUE TITLE
ss-local是否可以在mac 下安装

### ISSUE THREAD

**Issue by huyinghuan** [shadowsocks/shadowsocks-libev#299]
因为ss-local使用命令非常方便，而且可以写到 crontab　里面让开机启动，让人感觉不到（GUI总有个图标在顶部的工具栏），但是在文档里面没有提到　在mac 下的安装。　请问下源码是否可以在mac下进行编译安装？

**Comment by madeye** [comment]
brew install shadowsocks-libev
