### ISSUE TITLE
开启tcp_fastopen后报错

### ISSUE THREAD

**Issue by rwzsycwan** [shadowsocks/shadowsocks-libev#301]
系统是debian8,在配置文件中开启"fast_open":true,重启进程后报错:
Message from syslogd@server at Apr 26 05:51:59 ...
 kernel:[  563.713277] CPU: 1 PID: 828 Comm: ss-local Not tainted 3.16.0-4-686-pae #1 Debian 3.16.7-ckt9-2

Message from syslogd@server at Apr 26 05:51:59 ...
 kernel:[  563.713277] Hardware name: Hewlett-Packard hp t5740/3641h, BIOS 786R8 v1.03S1 08/16/2010

Message from syslogd@server at Apr 26 05:51:59 ...
 kernel:[  563.713277] task: f47e8010 ti: f3070000 task.ti: f3070000

Message from syslogd@server at Apr 26 05:51:59 ...
 kernel:[  563.713277] Stack:

Message from syslogd@server at Apr 26 05:51:59 ...
 kernel:[  563.713277] Call Trace:

Message from syslogd@server at Apr 26 05:51:59 ...
 kernel:[  563.713277] Code: 00 89 83 50 04 00 00 e9 c6 fd ff ff 8b 93 40 04 00 00 89 d0 c1 e8 02 d1 ea 01 c2 8b 83 3c 04 00 00 39 c2 0f 43 c2 e9 72 ff ff ff <0f> 0b 89 d8 ba 01 00 00 00 e8 f9 ab ff ff 31 c0 83 fe 02 0f 45

Message from syslogd@server at Apr 26 05:51:59 ...
 kernel:[  563.713277] EIP: [<c13ea7a9>] tcp_transmit_skb+0x679/0x840 SS:ESP 0068:f3071b04
root@server:~# service shadowsocks-libev restart
root@server:~# 
Message from syslogd@server at Apr 26 05:52:25 ...
 kernel:[  590.360022] CPU: 1 PID: 848 Comm: ss-local Tainted: G      D       3.16.0-4-686-pae #1 Debian 3.16.7-ckt9-2

Message from syslogd@server at Apr 26 05:52:25 ...
 kernel:[  590.360022] Hardware name: Hewlett-Packard hp t5740/3641h, BIOS 786R8 v1.03S1 08/16/2010

Message from syslogd@server at Apr 26 05:52:25 ...
 kernel:[  590.360022] task: f6cb7560 ti: f3076000 task.ti: f3076000

Message from syslogd@server at Apr 26 05:52:25 ...
 kernel:[  590.360022] Stack:

Message from syslogd@server at Apr 26 05:52:25 ...
 kernel:[  590.360022] Call Trace:

Message from syslogd@server at Apr 26 05:52:25 ...
 kernel:[  590.360022] Code: 00 89 83 50 04 00 00 e9 c6 fd ff ff 8b 93 40 04 00 00 89 d0 c1 e8 02 d1 ea 01 c2 8b 83 3c 04 00 00 39 c2 0f 43 c2 e9 72 ff ff ff <0f> 0b 89 d8 ba 01 00 00 00 e8 f9 ab ff ff 31 c0 83 fe 02 0f 45

Message from syslogd@server at Apr 26 05:52:25 ...
 kernel:[  590.360022] EIP: [<c13ea7a9>] tcp_transmit_skb+0x679/0x840 SS:ESP 0068:f3077b04

**Comment by madeye** [comment]
It's a kernel bug. https://lists.debian.org/debian-kernel/2015/04/msg00279.html
