### ISSUE TITLE
It appears shadowsocks libev is running as root on my VPS. Not good, how to fix ?

### ISSUE THREAD

**Issue by lepasserby** [shadowsocks/shadowsocks-libev#302]
Hi!

I just checked htop (for non-shadowsocks related issue) and saw

/usr/bin/ss-server -c /etc/shadowsocks-libev/config.json -a root -u -f /var/run/shadowsocks-libev/shadowsocks-libev.pid

Do I understand correctly that shadowsocks is running as root?

If so, how do I run it as different user and what privileges should that user have / what groups should said user belong to ?

**Comment by madeye** [comment]
`/etc/default/shadowsocks-libev`
