### ISSUE TITLE
Connection reset when connected via ethernet

### ISSUE THREAD

**Issue by netheril96** [shadowsocks/shadowsocks-libev#303]
I am receiving many connection reset errors after a period of connection with shadowsocks. I initially thought that somehow GFW is interfering with the connection. Later I observed, however, this issue only appears when connected via ethernet. When I disconnect the cable and connect via WIFI, shadowsocks works just fine. What are the probable cause and fix for such a problem? (I need ethernet to access LAN).

**Comment by madeye** [comment]
1. Reset is not an "error". It only means one connection is closed passively.
2. When switching the network interface, it's normal to see many resets.

**Comment by yuchting** [comment]
You may change the server port to 443 to test again, maybe, better than before.

**Comment by netheril96** [comment]
@madeye 

Can you give me a chance to clarify the issue instead of closing it so quick? 

One or two connection reset is indeed common, but when every connection is reset and no websites can be opened, that **is** an error.

And the error is not when the network interface is switched. It happens when ethernet is on for a long period, and *solved* when network interface is switched to WiFi.

**Comment by netheril96** [comment]
@yuchting 

The server port was 443 when the problem first occurred. I then changed to a random port and it still happens.

**Comment by kxmp** [comment]
Maybe you are using wrong password

**Comment by netheril96** [comment]
@kxmp 

In that case, `shadowsocks` won't work from the beginning, and won't be magically fixed when the interface is switched to WiFi.
