### ISSUE TITLE
给tunnel改成了udp透明代理功能

### ISSUE THREAD

**Issue by nightcoffee** [shadowsocks/shadowsocks-libev#307]
配合内核模块
https://github.com/nightcoffee/udpdst
在openwrt上用
https://github.com/nightcoffee/openwrt-shadowsocks

对libev版修改如下：
https://github.com/nightcoffee/shadowsocks-libev-udp/commits/master

改的很粗暴……直接废了tunnel原有功能，看到作者在改TPROXY的方式，我改了一个仍然利用conntrack REDIRECT的方式……希望能帮到一点忙，因为写了太烂也没考虑IPV6所以就不pull request了

**Comment by madeye** [comment]
改的挺好，只是太dirty… 

有兴趣的话可以帮忙测试 TPROXY 分支，现在 UDP 的转发还无法正常工作，可以帮忙调试一下～

**Comment by nightcoffee** [comment]
^_^ TPROXY方式我还得先了解下原理

**Comment by madeye** [comment]
Fixed via 39f72a0545234063b2b884649e810da09b1d8b22

**Comment by zh99998** [comment]
@madeye 你个傲娇！
上次提 issue 要这个功能说 no plan for this，然后偷偷的加进来了！

**Comment by JohnnySun** [comment]
看到这个issue乐死我了 @zh99998 😂
