### ISSUE TITLE
iptables应设置禁止通过UDP到远端443端口，防止QUIC协议滥用UDP

### ISSUE THREAD

**Issue by nightcoffee** [shadowsocks/shadowsocks-libev#309]
UDP在国内很多地方是被QoS的，速度非常不理想……访问Youtube可能会让Chrome使用QUIC（基于UDP）访问视频数据，导致速度很慢还加重ss的UDP负担。

**Comment by madeye** [comment]
Just set up the firewall rules yourself.

**Comment by xcjiang** [comment]
QUIC我怀疑默认是不是已经开启的, 即便开启的话也可以在设置里关掉。
