### ISSUE TITLE
同时监听ipv4和ipv6

### ISSUE THREAD

**Issue by lhw365** [shadowsocks/shadowsocks-libev#310]
libev版从1.6.4以后的2x版本 不管是用 “server”:”::0″,或者 “server”:”::”, V4都无法连接，V6未测试 我用的是centos6 据这里另外一个ubuntu用户反映 ubuntu上也有问题 https://www.librehat.com/let-shadowsocks-server-listen-on-ipv4-and-ipv6-ports/

**Comment by madeye** [comment]
Duplicate with #254
