### ISSUE TITLE
貌似2.2版本 CPU 占用过高

### ISSUE THREAD

**Issue by jackytang** [shadowsocks/shadowsocks-libev#311]
今天发现上不了网, 看了下 linode 的服务器,CPU100%, ss-server 的 CPU 占用率达到了59%, 1G 内存也基本被用完了...

**Comment by madeye** [comment]
2.2 没有引入任何服务端的修改。

**Comment by cokebar** [comment]
同linode 出现too many open files 大量的未关闭的udp的socket CPU占用彪满100%
用户数量不多 且increase the maximum number of open file descriptors我也设置了
是socket泄露么？
另外一个香港服务器则无此现象 不知何故 @madeye 
2.2.1版本

**Comment by madeye** [comment]
打开的 UDP socket 在小于 1024 时都是正常的。
