### ISSUE TITLE
iptables issue

### ISSUE THREAD

**Issue by plutoid** [shadowsocks/shadowsocks-libev#313]
Hi,

I'm not familiar iptables rules, and I have executed the iptables rules step by step, I'm not sure what's issue for below WARNING, could you have a look? 

route version: Tomato Firmware 1.28.0000 MIPSR2-124 K26 USB Big-VPN

root@Road2Net:/opt# iptables -t nat -A SHADOWSOCKS -p tcp -j REDIRECT --to-ports 1080
iptables: No chain/target/match by that name

root@Road2Net:/opt# iptables -t mangle -A SHADOWSOCKS -p udp --dport 53 -j TPROXY --on-port 1080 --tproxy-mark 0x01/0x01
iptables v1.3.8: Unknown arg `(null)'
Try `iptables -h' or 'iptables --help' for more information.

Thanks in advance!

**Comment by madeye** [comment]
Tomato is not supported by shadosocks. Try OpenWRT instead.

**Comment by plutoid** [comment]
But the process does running, only iptables does not work..,so curiously :(

 1879 root      3036 S    ss-redir -u -c config.json -f /var/run/shadowsocks.pid

**Comment by houzi-** [comment]
@plutoid 你可以来看看这里http://www.router008.com/Tomato-ShadowSocks-Mipsel.html

**Comment by oglops** [comment]
@houzi I got the same error. what should I do?

**Comment by houzi-** [comment]
@oglops 
Look http://www.router008.com/Tomato-ShadowSocks-Mipsel.html
