### ISSUE TITLE
FreeBSD的port没人维护吗？

### ISSUE THREAD

**Issue by jiang42** [shadowsocks/shadowsocks-libev#314]
FreeBSD通过ports安装版本只有 1.6.4

Ubuntu上已经2.X了吧

**Comment by madeye** [comment]
Contact xiaoding+freebsd@xiaoding.org

**Comment by madeye** [comment]
http://portsmon.freebsd.org/portoverview.py?category=net&portname=shadowsocks-libev

**Comment by ykla** [comment]
同问
