### ISSUE TITLE
sslocale 端口没有被chome代理用上？

### ISSUE THREAD

**Issue by iampkuhz** [shadowsocks/shadowsocks-libev#315]
您好，我使用sslocale在本地登陆后，用chrome的SwitchyOmega代理，但是好像SwitchyOmega请求的端口不是sslocal 设置的1081，请问我是哪里做错了吗？

config.json文件如下

```json
{
"server":"104.131.139.138",
"server_port":8388,
"local_port":1081,
"password":"19920326",
"timeout":1000
}
```

使用 **sslocal -s config.json **链接后效果如下

> 2015-05-19 18:24:20 WARNING  warning: your timeout 1000 seems too long
> 2015-05-19 18:24:20 INFO     loading libcrypto from libcrypto.so.1.0.0
> 2015-05-19 18:24:20 INFO     starting local at 127.0.0.1:1081
> 2015-05-19 18:24:24 INFO     connecting www.google.co.jp:443 from 127.0.0.1:40232
> 2015-05-19 18:24:24 ERROR    unknown hostname config.json when handling connection from 127.0.0.1:40232
> 2015-05-19 18:24:24 INFO     connecting www.google.co.jp:443 from 127.0.0.1:40233
> 2015-05-19 18:24:24 ERROR    unknown hostname config.json when handling connection from 127.0.0.1:40233
> 2015-05-19 18:24:24 INFO     connecting www.google.co.jp:443 from 127.0.0.1:40234

**Comment by madeye** [comment]
Post your issue here: https://github.com/shadowsocks/shadowsocks/issues

**Comment by kxmp** [comment]
You might forgot to save your new setting.

**Comment by iampkuhz** [comment]
知道原因了，是客户端的加密方式写错了。服务器端是aes-256-cfb加密，客户端用成camellia-256-cfb

参考这个 https://github.com/cyfdecyf/cow/issues/263
