### ISSUE TITLE
Could you add a --log LOG_FILE option for logging when run as a daemon?

### ISSUE THREAD

**Issue by zeroxia** [shadowsocks/shadowsocks-libev#316]
It's very very inconvenient without logging on a server.

When something is wrong, logging may be of great help.

Preferably the -v --log LOG_FILE should enable verbose logging.

And it may even be preferable to add log rotating capability. Or just truncate log to a upper limit file size.

Thanks!

**Comment by madeye** [comment]
Duplicate with #174
