### ISSUE TITLE
Add OS X's Installation info to README.md

### ISSUE THREAD

**Issue by BlackGear** [shadowsocks/shadowsocks-libev#319]
### OS X
For OS X , use [homebrew](http://brew.sh) to install or build.

Install homebrew

```bash
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
```
Install shadowsocks-libev

```bash
brew install shadowsocks-libev
```

----

Here is the markdown codes:

<pre>
### OS X
For OS X , use [homebrew](http://brew.sh) to install or build.

Install homebrew

```bash
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
```
Install shadowsocks-libev

```bash
brew install shadowsocks-libev
```
</pre>

**Comment by madeye** [comment]
Please submit a pull request instead.
