### ISSUE TITLE
failed on a debian 7.0 amd64 vps

### ISSUE THREAD

**Issue by Huangdong2** [shadowsocks/shadowsocks-libev#321]
dear author:
i'm from china, harbin
i deployed the shadowsocks-libev server on a deabian 7.0 amd 64 vps as below:

========================================================================
sudo apt-get update
sudo apt-get install -y git build-essential autoconf libtool libssl-dev gawk nano debhelper
git clone https://github.com/shadowsocks/shadowsocks-libev.git
cd shadowsocks-libev
dpkg-buildpackage -us -uc
cd ..
sudo dpkg -i shadowsocks-libev*.deb
sudo nano /etc/shadowsocks-libev/config.json
sudo /etc/init.d/shadowsocks-libev start
sudo apt-get autoremove -y
========================================================================
but ss-server always gave me errors while attempted to start or restart, i have uploaded 2 screenshots,
hope will get your response, thx

**Comment by Huangdong2** [comment]
![shadows111](https://cloud.githubusercontent.com/assets/9297437/8076226/541b3d36-0f7c-11e5-89e0-7d995c615efa.png)
![shadows222](https://cloud.githubusercontent.com/assets/9297437/8076229/59291ce4-0f7c-11e5-9292-d17a4354a887.png)

**Comment by madeye** [comment]
```
"method": "rc4-md5"
```

**Comment by Huangdong2** [comment]
"method":"rc4-md5"
great! with quotations, i solved my problem!! thx again
