### ISSUE TITLE
NAT type after udp proxyed

### ISSUE THREAD

**Issue by sadoneli** [shadowsocks/shadowsocks-libev#323]
I am using ss-redir on my router, and I successfully redirect the udp package to the transparent port of ss-redir.
I use the chnroute file with ipset to distinguish the foreign traffic
And I was able to redirect the TCP through nat redirect and UDP thought TPROXY
I run test of:  nslookup twitter.com 8.8.8.8, and I get the right address of twitter which the initial ip is 199
And I tested the dota2 with South East Asia (my vps is in Singapore), the experience is great!
while I am playing dota2, i can see the udp traffic on my vps by using iptraf-ng
 
I have both python ssserver and libev ss-server installed on my CentOs 7,both works fine on nslookup and dota2
But when I try my playstation 4,
1  ss-redir connect to  libev ss-server, it showed NAT failed
2  ss-redir connect to python ssserver, it showed NAT3
both are bad for gaming

So I test the nat type with a windows software NAT类型测试(NAT type test)
1 connect to  libev ss-server: udp blocked, PS4 NAT failed
2 connect to python ssserver: full cone, PS4 NAT3
3  connect to go ssserver(with -u enabled): Symmetric, PS4 NAT3
4 shut down the ss-redir:Symmetric, PS4 NAT2

the test above is tested when udp is proxyed, which pre-test whith nslookup or dig
I shut down the firewall service on my CentOs7 during all the test and gaming.

**Comment by madeye** [comment]
1. I just tried`ss-server` and `ss-redir` with PS4, it works well.
2. NAT3 is expected.
3. For NAT2, you need VPN based solution.

**Comment by sadoneli** [comment]
Did you have any problem with establish UDP connection between player?

**Comment by madeye** [comment]
It depends. Bloodborne works well, Garden War (maybe all the EA games) have issues.
