### ISSUE TITLE
帮忙看一下这是什么错误。

### ISSUE THREAD

**Issue by apnic** [shadowsocks/shadowsocks-libev#324]
debian 8 kvm环境
启动后立即退出。
root@debian:/var/log# /etc/init.d/shadowsocks-libev start
[ ok ] Starting shadowsocks-libev (via systemctl): shadowsocks-libev.service.
日志里面就一条
Jun 15 00:52:00 debian shadowsocks-libev[1015]: 2015-06-15 00:52:00 ERROR: 3:18: Expected : before 1

root@debian:/var/log# cat /etc/shadowsocks-libev/config.json
{
    "server":"xxx.xxx.xxx.xxx",
    "server_port"119,
    "local_port":1080,
    "password":"xxxxxxx",
    "timeout":60,
    "method":"aes-256-cfb"
}

**Comment by madeye** [comment]
`"server_port":119,`

**Comment by apnic** [comment]
119端口有问题？另一台OpenVZ的vps同样配置一切正常啊

**Comment by apnic** [comment]
"server_port":3082,
更换端口无效，还是报
Jun 15 00:52:00 debian shadowsocks-libev[1015]: 2015-06-15 00:52:00 ERROR: 3:18: Expected : before 1

**Comment by dutonttie** [comment]
缺少冒号了
 2015年6月15日 13:07于 "apnic" <notifications@github.com>写道：

**Comment by apnic** [comment]
谢谢，可以启动了。
