### ISSUE TITLE
正确安装ss-libev后手机能上网，电脑不行

### ISSUE THREAD

**Issue by piscesmk2013** [shadowsocks/shadowsocks-libev#325]
正确安装ss-libev后手机能上网，电脑不行，试过换端口，换加密方式以及关闭防火墙了，电脑的客户端使用的是shadowsocks2.3.1

[2015-06-15 17:00:39] System.Net.Sockets.SocketException: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.Handler.PipeRemoteReceiveCallback(IAsyncResult ar)

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks-csharp

**Comment by rocren3** [comment]
同楼主，我从上周开始，家中所有win系统机器用ss均受阻。ping服务器地址延迟低于60ms，丢包率零，但一挂ss就基本上全time out，油管谷歌基本没法用。但同一路由下，用安卓手机挂ss体验正常，YouTube不卡。已经尝试还原台机系统，重启路由器，关防火墙，摘路由器直连电信网，重启ss服务器，更换ss服务器端口和密码，均无解。有哪位知道是什么缘故吗？ 在单位和另外居所使用均不受影响。

**Comment by yaoclee** [comment]
我也遇到这个问题，你们最后怎么解决的啊?

**Comment by tiamlhb** [comment]
DNS改为192.168.0.1就行了，之前我也遇见过这个问题。
