### ISSUE TITLE
shadowsocks-libev-spec 无法和最新版的shadowsocks-libev建立连接

### ISSUE THREAD

**Issue by regeditms** [shadowsocks/shadowsocks-libev#328]
shadowsocks-libev-spec是2.2.1-1 无法和最新版的shadowsocks-libev建立连接,但是用最新版的shadowsocksX 就可以.如果把server换成shadowsocks-pyton 也可以和shadowsocks-libev-spec 建立连接 这是什么问题?

**Comment by madeye** [comment]
检查配置。

**Comment by regeditms** [comment]
回复这么快?shadowsocks-libev配置有特殊性吗?我的shadowsocksX 都可以连上去.

**Comment by 70599** [comment]
shadowsocks-libev-spec也用最新版啊
