### ISSUE TITLE
Can I config all the short version options in config.json?

### ISSUE THREAD

**Issue by cattyhouse** [shadowsocks/shadowsocks-libev#334]
* Currently i have the following short version options configured in shadowsocks.json:

```` javascript
{
    "server":"5.6.7.8", // for -s 
    "server_port":9000, // for -p 
    "local_port":1922, // for -l
    "local":"127.0.0.1", // for -b
    "password":"vqri6odbdejlhdendjwoqfbjewqzrQ", // for -k
    "timeout":600, // for -t 
    "method":"aes-128-cfb" // for -m 
}

````

* What about these options? do they have appropriate options in config.json? if they do, what's the syntax?
  * `-d` to define DNS servers, of course only in server mode. 
  * `-v` to show debug
  * `--fast-open`
  * `-u` to enable udp reley

* Can I use more than one DNS server like this? 
`-d 8.8.8.8,8.8.4.4` (not sure if this is the right syntax.)

**Comment by madeye** [comment]
1. No, you can't.
2. Use multiple `-d` to define multiple DNS servers. For example, `-d 8.8.8.8 -d 8.8.4.4`. You should not touch this option unless you know what you are doing.

**Comment by cattyhouse** [comment]
thank you.
