### ISSUE TITLE
shadowsocks-libev for openwrt does not run on boot if configured with "-b 127.0.0.1" 

### ISSUE THREAD

**Issue by cattyhouse** [shadowsocks/shadowsocks-libev#335]
* If I change `/etc/init.d/shadowsock` from this:
```` bash
start() {
        service_start /usr/bin/ss-local -c $CONFIG -b 0.0.0.0
}
````
to:

```` bash
start() {
        service_start /usr/bin/ss-local -c $CONFIG -b 127.0.0.1
}
````
shadowsocks-libev does not run on boot, and yes, i have added it run level `/etc/init.d/shadowsocks enable`

* shadowsocks version, `ss-local -v | grep shadowsocks-libev`
> shadowsocks-libev 2.2.2

* Openwrt version, `cat /etc/openwrt_version`
> 14.07

* I also tried to keep `/etc/init.d/shadowsocks` unchanged, but configure `/etc/shadowsocks.json` with `"local":"127.0.0.1",` shadowsocks-libev still does not run on boot.

**Comment by madeye** [comment]
Open an issue to project openwrt-shadowsocks instead.
