### ISSUE TITLE
UDP source port issue

### ISSUE THREAD

**Issue by clowwindy** [shadowsocks/shadowsocks-libev#337]
Unlike TCP, a UDP client could send data to multiple addresses. For example, an online game could send data to different players from the same source port.

But if the game is behind Shadowsocks, other players will see different source ports. Some games won't work in this situation.

This is fixed in Python version by using only source address in cache keys:
https://github.com/shadowsocks/shadowsocks/commit/c34c99450f7d2410f005e6c81c1955a0c49d7c2e

We also need to use different keys for IPv4 and IPv6 as well:
https://github.com/shadowsocks/shadowsocks/commit/99b4121fd93f38e89354bca915e3ed620632d6fe

The test case for this issue:
https://github.com/shadowsocks/shadowsocks/blob/master/tests/test_udp_src.py#L7-L32

**Comment by madeye** [comment]
One stupid question, why use different keys for IPv4 and IPv6?

**Comment by clowwindy** [comment]
Because a UDP socket can send to either IPv4 or IPv6, not both. The Test 2 shows the problem: `sendto: nodename nor servname provided, or not known`
