### ISSUE TITLE
Could the project provide systemd service file as well?

### ISSUE THREAD

**Issue by hosiet** [shadowsocks/shadowsocks-libev#339]
An extra systemd service file can be benificial to distributions that prefer systemd service file, for example Archlinux.

An example file can be found in Archlinux AUR shadowsocks-libev (https://aur.archlinux.org/packages/shadowsocks-libev/) and the tarball can be found [here](https://aur.archlinux.org/packages/sh/shadowsocks-libev/shadowsocks-libev.tar.gz).

**Comment by madeye** [comment]
No plan for this. Of course, any pull request is welcome.

**Comment by hosiet** [comment]
Thank you. I may consider to send a pull request later.
