### ISSUE TITLE
NAT type failed on Playstation

### ISSUE THREAD

**Issue by sadoneli** [shadowsocks/shadowsocks-libev#341]
I compiled the newest shadowsocks-libev 2.2.3
Also upgrade the shadowsocks server to Shadowsocks 2.6.11 (pythoon)

however, when I play PS3 with udp relay mode through Tproxy (ss-redir)
It showed NAT failed.
I tried on my three VPS, all same result.

when I reconfigured the shadowsocks-libev  2.2.2
I get NAT3, which is expected.

Is there any chance to improve?

**Comment by madeye** [comment]
Verified on PS4.

@clowwindy Are we sure that the latest UDP relay change does not introduce side effects?

**Comment by madeye** [comment]
@sadoneli  Could you also test dota2 or any other online game to see if the new UDP relay works with them?

**Comment by sadoneli** [comment]
@madeye I will test dota2,see if it works

**Comment by sadoneli** [comment]
@madeye 
Getting into dota2 client is ok,
but when popup game accept, it fails.

I also test QUIC with google chrome, it works fine, the youtube video are streamed througt UDP.

**Comment by clowwindy** [comment]
> when I reconfigured the shadowsocks-libev 2.2.2 
I get NAT3, which is expected.

Does that mean shadowsocks-libev 2.2.2 client with shadowsocks 2.6.11 server works fine?

**Comment by sadoneli** [comment]
@clowwindy in my test, yes.

**Comment by clowwindy** [comment]
@sadoneli Can you also try shadowsocks-libev 2.2.3 with shadowsocks 2.6.10?

**Comment by sadoneli** [comment]
OK, I will test it
any convenient way to downgrade shadowsocks python server?
I installed ssserver through pip

**Comment by clowwindy** [comment]
pip install shadowsocks==2.6.10

**Comment by sadoneli** [comment]
I retest the dota2，it seem works fine 
shadowsocks-libev 2.2.3 with shadowsocks 2.6.11  OK
shadowsocks-libev 2.2.3 with shadowsocks 2.6.10  OK
shadowsocks-libev 2.2.2 with shadowsocks 2.6.11  OK

I monitor the udp traffic on vps, and I can see dota2 game port (27000 - 27100) have traffic as expected

The test in this morning is wrong.

But when comes to playstation, still NAT 3

**Comment by madeye** [comment]
For NAT3, which configuration are you using?

**Comment by sadoneli** [comment]
@madeye wrong typing ,it is still nat failed as the issue title mentioned,when usinig shadowsocks-libev 2.2.3

**Comment by madeye** [comment]
After some tests, I think it'd be a `ss-redir` specific issue, not related to new UDP multi-source change. I'm working on some fixes to this issue.

**Comment by madeye** [comment]
With NAT Type Test, now the NAT type becomes FullCone (NAT3), which is expected.

**Comment by madeye** [comment]
Tested in Garden Warfare, everything works well now. Other EA games should work now.

**Comment by sadoneli** [comment]
@madeye nice work!

**Comment by madeye** [comment]
Now NAT2 achieved!

![img_20150713_202211](https://cloud.githubusercontent.com/assets/627917/8649460/0ef78184-299d-11e5-95c3-49e94aa15514.jpg)

**Comment by clowwindy** [comment]
Good job!

**Comment by jannson** [comment]
Great job!

**Comment by sadoneli** [comment]
I am always hoping that！
 Grate job!!

**Comment by dsyo2008** [comment]
Great, finally solved. . good

**Comment by heeroyuyj** [comment]
wow, good job!!!!

**Comment by iblxjin** [comment]
WOW! You did something awesome, great!

**Comment by curdfu** [comment]
Great Job
Thanks to all of you
