### ISSUE TITLE
[License] Incompatible license between GPL and OpenSSL

### ISSUE THREAD

**Issue by hosiet** [shadowsocks/shadowsocks-libev#342]
I noticed this problem when running `lintian` in Debian, which shows
`E: shadowsocks-libev: possible-gpl-code-linked-with-openssl`

`shadowsocks-libev` is licensed under GPLv3+. So as described [here](https://people.gnome.org/~markmc/openssl-and-the-gpl), GPL is incompatible with OpenSSL License. When such a program should be linked with OpenSSL, an extra license exception should be added as described [here](https://lists.debian.org/debian-legal/2004/05/msg00595.html) with precautions listed [here](https://lists.debian.org/debian-legal/2004/05/msg00635.html).

This problem should be solved because openssl is being used as the *de facto* ssl/tls library in most cases.

**Comment by madeye** [comment]
Use PolarSSL instead.
