### ISSUE TITLE
can't download shadowsocks-libev v2.2.3

### ISSUE THREAD

**Issue by angusding** [shadowsocks/shadowsocks-libev#345]
--2015-07-13 22:32:21--  https://github.com/shadowsocks/shadowsocks-libev/archive/v2.2.3.tar.gz
Resolving github.com... 192.30.252.130
Connecting to github.com|192.30.252.130|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/shadowsocks/shadowsocks-libev/tar.gz/v2.2.3 [following]
--2015-07-13 22:32:22--  https://codeload.github.com/shadowsocks/shadowsocks-libev/tar.gz/v2.2.3
Resolving codeload.github.com... 192.30.252.145
Connecting to codeload.github.com|192.30.252.145|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-07-13 22:32:22 ERROR 404: Not Found.

Download failed.
--2015-07-13 22:32:22--  http://mirror2.openwrt.org/sources/v2.2.3.tar.gz
Resolving mirror2.openwrt.org... 46.4.11.11
Connecting to mirror2.openwrt.org|46.4.11.11|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-07-13 22:32:23 ERROR 404: Not Found.

Download failed.
--2015-07-13 22:32:23--  http://downloads.openwrt.org/sources/v2.2.3.tar.gz
Resolving downloads.openwrt.org... 78.24.191.177
Connecting to downloads.openwrt.org|78.24.191.177|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-07-13 22:32:23 ERROR 404: Not Found.

Download failed.
No more mirrors to try - giving up.

**Comment by madeye** [comment]
v2.2.3 has not been released.
