### ISSUE TITLE
Networks done for a while , shadowsocks can not return normal as fast as possible

### ISSUE THREAD

**Issue by netroby** [shadowsocks/shadowsocks-libev#349]
huzhifeng@postar:~/workspace/netroby/shadowsocks-libev$ grep -R "failed to resolve server name" *
src/netutils.c:                LOGE("failed to resolve server name, wait %.0f seconds", pow(2, i));
src/server.c:            LOGE("failed to resolve server name, wait %.0f seconds", pow(2, i));

Now the shadowsocks sleeps for 2^8 seconds , it seems too slow.
Once the network return online , we want our shadowsocks reconnect faster.
So, can we decrease the sleep waiting seconds?

May we sleep for every 5 seconds loop for 1000 times ?

**Comment by netroby** [comment]
You may testing this on wifi network. disable wifi, then shadowsocks will waiting for 2, 4, 16, 32, 64 seconds, it's terrible delay when wifi return online.

**Comment by madeye** [comment]
It only happens when starting the server. Nothing would be blocked if network is down.

**Comment by madeye** [comment]
This is used for one special scenario: when shadowsocks-libev is started by OS (e.g. a daemon service) and network is not ready, shadowsocks-libev will try several times and wait until the network is up.

**Comment by netroby** [comment]
The problem is the delay times will be so long . 2^8 = 256 seconds.
Once the network ready, shadowsocks-libev still waiting for next retries. 

As for now, we can only killed shadowsocks-libev , then start it by hand.

Not good for us use experiences.

**Comment by netroby** [comment]
@madeye Dear sir, I respect your great works, can you please rethink this problem for us. Our daily working needed SS, so it is a big problem for us.

**Comment by madeye** [comment]
Before proposing a code change, you'd better understand what it is and how it works first.

**Comment by netroby** [comment]
Thanks, i am try to learn more on it. The delay logic is not very well
