### ISSUE TITLE
Build error with openwrt uclibc.

### ISSUE THREAD

**Issue by hero18688** [shadowsocks/shadowsocks-libev#352]
/home/workingdir/Openwrt/981213_150712/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/lib/gcc/mips-openwrt-linux-uclibc/4.8.3/../../../../mips-openwrt-linux-uclibc/bin/ar: `u' modifier ignored since `D' is the default (see `U')
  CC       ss_local-utils.o
  CC       ss_local-jconf.o
  CC       ss_local-json.o
  CC       ss_local-encrypt.o
  CC       ss_local-udprelay.o
  CC       ss_local-cache.o
  CC       ss_local-acl.o
  CC       ss_local-netutils.o
  CC       ss_local-local.o
  CCLD     ss-local
/home/workingdir/Openwrt/981213_150712/staging_dir/target-mips_34kc_uClibc-0.9.33.2/usr/lib/libcrypto.so: warning: gethostbyname is obsolescent, use getnameinfo() instead.
../libsodium/src/libsodium/.libs/libsodium.a(libsodium_la-stream_chacha20_ref.o): In function `chacha_encrypt_bytes.part.0':
stream_chacha20_ref.c:(.text+0x1a0): undefined reference to `__stack_chk_guard'
stream_chacha20_ref.c:(.text+0x9b8): undefined reference to `__stack_chk_guard'
stream_chacha20_ref.c:(.text+0x9d0): undefined reference to `__stack_chk_fail'
stream_chacha20_ref.c:(.text+0xa18): undefined reference to `__stack_chk_guard'
../libsodium/src/libsodium/.libs/libsodium.a(libsodium_la-stream_chacha20_ref.o): In function `crypto_stream_chacha20_ref_xor_ic':
stream_chacha20_ref.c:(.text+0xbb4): undefined reference to `__stack_chk_guard'
stream_chacha20_ref.c:(.text+0xd64): undefined reference to `__stack_chk_fail'
../libsodium/src/libsodium/.libs/libsodium.a(libsodium_la-xor_salsa20_ref.o): In function `crypto_stream_salsa20_xor_ic':
xor_salsa20_ref.c:(.text+0xc): undefined reference to `__stack_chk_guard'
xor_salsa20_ref.c:(.text+0x25c): undefined reference to `__stack_chk_guard'
xor_salsa20_ref.c:(.text+0x274): undefined reference to `__stack_chk_fail'
../libsodium/src/libsodium/.libs/libsodium.a(libsodium_la-auth_poly1305_donna.o): In function `crypto_onetimeauth_poly1305_donna':
auth_poly1305_donna.c:(.text+0x9b4): undefined reference to `__stack_chk_guard'
auth_poly1305_donna.c:(.text+0xa50): undefined reference to `__stack_chk_fail'
../libsodium/src/libsodium/.libs/libsodium.a(libsodium_la-verify_poly1305_donna.o): In function `crypto_onetimeauth_poly1305_donna_verify':
verify_poly1305_donna.c:(.text+0x14): undefined reference to `__stack_chk_guard'
verify_poly1305_donna.c:(.text+0x70): undefined reference to `__stack_chk_fail'
collect2: error: ld returned 1 exit status
make[5]: *** [ss-local] Error 1
make[5]: Leaving directory `/home/workingdir/Openwrt/981213_150712/build_dir/target-mips_34kc_uClibc-0.9.33.2/shadowsocks-libev-53ddb3b/src'
make[4]: *** [all-recursive] Error 1
make[4]: Leaving directory `/home/workingdir/Openwrt/981213_150712/build_dir/target-mips_34kc_uClibc-0.9.33.2/shadowsocks-libev-53ddb3b'
make[3]: *** [all] Error 2
make[3]: Leaving directory `/home/workingdir/Openwrt/981213_150712/build_dir/target-mips_34kc_uClibc-0.9.33.2/shadowsocks-libev-53ddb3b'
make[2]: *** [/home/workingdir/Openwrt/981213_150712/build_dir/target-mips_34kc_uClibc-0.9.33.2/shadowsocks-libev-53ddb3b/.built] Error 2
make[2]: Leaving directory `/home/workingdir/Openwrt/981213_150712/package/my_package/shadowsocks-libev'
make[1]: *** [package/my_package/shadowsocks-libev/compile] Error 2
make[1]: Leaving directory `/home/workingdir/Openwrt/981213_150712'
make: *** [package/shadowsocks-libev/compile] 错误 2
➜  981213_150712 git:(master) ✗

**Comment by hero18688** [comment]
I have tried old version of months ago and latest version.

**Comment by madeye** [comment]
Post your issue on https://github.com/shadowsocks/openwrt-shadowsocks
