### ISSUE TITLE
关于ss-redir转发原理

### ISSUE THREAD

**Issue by neroxps** [shadowsocks/shadowsocks-libev#358]
最近一直在研究本地局域网自动代理。环境如下
A计算机（windows）ip=10.155.251.18 route=10.155.251.12
B计算机（centos）ip=10.155.251.12 route=10.155.251.1 内核开启了转发
网关=10.155.251.1
目标是，访问Gmail通过代理，其余直接转发。我通过内网的dns固定了smtp.gmail.com = 74.125.28.180
我在B计算机中部署了shadowsocks-libev的ss-redir，端口是1080。
iptables按照Advanced usage里面的配置。
网络结构应该如下。
A计算机发出TCP SYN包给74.125.28.180
数据包如下：
源IP=10.155.251.18 源端口=4555
目的IP=74.125.28.180 目的端口=465
由于A计算机设置默认网关为B计算机（centos）故此数据包会丢给B计算机。

根据Advanced usage里面的配置，数据包到达B计算机后，首先经过iptables
先到NAT PREROUTING，发现 iptables -t nat -A PREROUTING -p tcp -j SHADOWSOCKS
匹配该条目，转跳到SHADOWSOCKS的chain条目。
最终匹配iptables -t nat -A SHADOWSOCKS -p tcp -j REDIRECT --to-ports 1080（我的ss-redir为1080端口）

这句条目的意思就是，将所有的TCP连接都端口重定向到1080端口。意思数据包会改成

源ip=10.155.251.18 源端口=4555
目的ip=127.0.0.1目的端口=1080

那么问题来了，ss-redir如何知道我需要访问74.125.28.180。
而ss-redir返回的数据包的源IP地址和目的IP地址又是如何呈现的呢？

目前我试过很多种写法，发现只能在NAT 的OUTPUT表中写-p tcp -j REDIRECT --to-ports 1080，B计算机 telnet 74.125.28.180 465是通的。
但其他机器的TCP抓包显示，一直显示TCP Retransmission。

请问我如何设置，才能完成我的目的？

**Comment by madeye** [comment]
http://unix.stackexchange.com/questions/166692/how-does-a-transparent-socks-proxy-know-which-destination-ip-to-use

http://www.tldp.org/HOWTO/text/TransparentProxy

https://www.kernel.org/doc/Documentation/networking/tproxy.txt

http://darkk.net.ru/redsocks/
