### ISSUE TITLE
Question: How to use ss-redir with traditional SOCKS5 server?

### ISSUE THREAD

**Issue by thaink** [shadowsocks/shadowsocks-libev#360]
Hi,
I want to use ss-redir to as a socksify program to redirect traffic
from my computer to a traditional Socks5 proxy (Not shadowsocks server).

Is it possible? if yes, how can i do that?
I try to disable encryption to see if it would work or not.
But shadowsocks does not have something like "none" encryption option
in configuration file.
Thank you very much! :D

**Comment by madeye** [comment]
No, you can't.
