### ISSUE TITLE
Xbox one 100% packet loss

### ISSUE THREAD

**Issue by sadoneli** [shadowsocks/shadowsocks-libev#361]
When configured udp proxy through TPROXY as described in wiki.
everything works fine，PS4 get nat2 in -u mode.
but X1 have an issue of 100% packet loss.
I am not sure weather this problem comes from ss-redir

If the problem comes from ss-redir,
Is there any test I can do to help?

**Comment by smartepsh** [comment]
Hi, 
Can you share your configuration with iptables?
When configured udp relay with TPROXY in wiki, My Dns will not work...100% timeout...

**Comment by madeye** [comment]
It'd be a compatible issue of ss-redir. You can run `ss-redir` with `-v` option and post the logs when X1 running the speed test.

**Comment by madeye** [comment]
Also try to enlarge the timeout of ss-redir, e.g. "-t 600".

**Comment by sadoneli** [comment]
@smartepsh
you can not redirect all udp traffic，it will cause problem,blow is my setting for udp part

<pre># create ip rules
ip rule add fwmark 0x01/0x01 table 100
ip route add local 0.0.0.0/0 dev lo table 100

# creat mangle chain
iptables -t mangle -N SHADOWSOCKS2

# return these ip
iptables -t mangle -N SHADOWSOCKS2
iptables -t mangle -A SHADOWSOCKS2 -d 0.0.0.0/8 -j RETURN
iptables -t mangle -A SHADOWSOCKS2 -d 10.0.0.0/8 -j RETURN
iptables -t mangle -A SHADOWSOCKS2 -d 127.0.0.0/8 -j RETURN
iptables -t mangle -A SHADOWSOCKS2 -d 169.254.0.0/16 -j RETURN
iptables -t mangle -A SHADOWSOCKS2 -d 172.16.0.0/12 -j RETURN
iptables -t mangle -A SHADOWSOCKS2 -d 192.168.0.0/16 -j RETURN
iptables -t mangle -A SHADOWSOCKS2 -d 224.0.0.0/4 -j RETURN
iptables -t mangle -A SHADOWSOCKS2 -d 240.0.0.0/4 -j RETURN
iptables -t mangle -A SHADOWSOCKS2 -d $ss_server -j RETURN

# redirect udp traffic to tpoxy
iptables -t mangle -A SHADOWSOCKS2 -p udp -m set ! --match-set chnroute dst -j TPROXY --on-port 3333 --tproxy-mark 0x01/0x01

# apply rule for udp redirect
iptables -t mangle -A PREROUTING -p udp -j SHADOWSOCKS2</pre>

**Comment by sadoneli** [comment]
@madeye 
![qq 20150730220346](https://cloud.githubusercontent.com/assets/10495520/8985324/5f159042-3709-11e5-8b51-102b1121b54b.jpg)
when x1 test failed
![qq 20150730215220](https://cloud.githubusercontent.com/assets/10495520/8985341/797bcf1e-3709-11e5-8026-8aa4730e834c.gif)

Is this any help？
test three ss servers，all my own vps，with shadowsocks 2.6.11 on it

**Comment by madeye** [comment]
Try to redirect all logs to a plain text file and upload somewhere.

According to the screenshot, I cannot find anything useful.

**Comment by smartepsh** [comment]
@sadoneli Thanks, But it still not work...Can u post all your iptables rules and /etc/dnsmasq.conf ?
Only 5 kinds of ss-redir logs I can get:
server receive a packet
cache miss
connection timeout
one connection freed
server recv: Connection reset by peer...

So sad...

**Comment by madeye** [comment]
@sadoneli Could you change `MAX_UDP_PACKET_SIZE` to `576` and try again:

https://github.com/shadowsocks/shadowsocks-libev/blob/master/src/udprelay.h#L40

**Comment by madeye** [comment]
@sadoneli Also, could you try set LAN's MTU to 1397?

**Comment by sadoneli** [comment]
@madeye 

1  ok，i will try it

2 H oweve, Xbox1 is not capable of define mtu

**Comment by madeye** [comment]
To set MTU, add this line `dhcp-option-force=26,1397` to `dnsmasq.conf`.

**Comment by sadoneli** [comment]
@smartepsh 
Below is my nat rules setting, I am currently using ASUS Merlin, not openwrt, though I think things could works the same
<pre>#!/bin/sh

source /jffs/configs/ss.sh
chnroute="/jffs/ss/redchn/chnroute.txt"

ipset -F >/dev/null 2>&1
ipset -X >/dev/null 2>&1

# load chnroute to ipset
sed -e "s/^/-A chnroute &/g" -e "1 i\-N chnroute nethash --hashsize 4096" $chnroute | awk '{print $0} END{print "COMMIT"}' | ipset -R

# for router itself
ipset -N router iphash

# create nat chain
iptables -t nat -N SHADOWSOCKS

# not redirect these
iptables -t nat -A SHADOWSOCKS -d $ss_server -j RETURN
iptables -t nat -A SHADOWSOCKS -d 0.0.0.0/8 -j RETURN
iptables -t nat -A SHADOWSOCKS -d 10.0.0.0/8 -j RETURN
iptables -t nat -A SHADOWSOCKS -d 127.0.0.0/8 -j RETURN
iptables -t nat -A SHADOWSOCKS -d 169.254.0.0/16 -j RETURN
iptables -t nat -A SHADOWSOCKS -d 172.16.0.0/12 -j RETURN
iptables -t nat -A SHADOWSOCKS -d 192.168.0.0/16 -j RETURN
iptables -t nat -A SHADOWSOCKS -d 224.0.0.0/4 -j RETURN
iptables -t nat -A SHADOWSOCKS -d 240.0.0.0/4 -j RETURN

# others should be redirected
iptables -t nat -A SHADOWSOCKS -p tcp -m set ! --match-set chnroute dst -j REDIRECT --to-ports 3333
#iptables -t nat -A SHADOWSOCKS -p icmp -j REDIRECT --to-ports 3333
#iptables -t nat -A SHADOWSOCKS -p sctp -j REDIRECT --to-ports 3333


# create ip rules
ip rule add fwmark 0x01/0x01 table 100
ip route add local 0.0.0.0/0 dev lo table 100

# creat mangle chain
iptables -t mangle -N SHADOWSOCKS2

# return these ip
iptables -t mangle -N SHADOWSOCKS2
iptables -t mangle -A SHADOWSOCKS2 -d 0.0.0.0/8 -j RETURN
iptables -t mangle -A SHADOWSOCKS2 -d 10.0.0.0/8 -j RETURN
iptables -t mangle -A SHADOWSOCKS2 -d 127.0.0.0/8 -j RETURN
iptables -t mangle -A SHADOWSOCKS2 -d 169.254.0.0/16 -j RETURN
iptables -t mangle -A SHADOWSOCKS2 -d 172.16.0.0/12 -j RETURN
iptables -t mangle -A SHADOWSOCKS2 -d 192.168.0.0/16 -j RETURN
iptables -t mangle -A SHADOWSOCKS2 -d 224.0.0.0/4 -j RETURN
iptables -t mangle -A SHADOWSOCKS2 -d 240.0.0.0/4 -j RETURN

# redirect udp traffic to tpoxy
iptables -t mangle -A SHADOWSOCKS2 -d $ss_server -j RETURN
iptables -t mangle -A SHADOWSOCKS2 -d 208.67.220.220 -j RETURN
iptables -t mangle -A SHADOWSOCKS2 -p udp -m set ! --match-set chnroute dst -j TPROXY --on-port 3333 --tproxy-mark 0x01/0x01

# apply rule for udp redirect
iptables -t mangle -A PREROUTING -p udp -j SHADOWSOCKS2
iptables -t nat -A PREROUTING -i br0 -p tcp -j SHADOWSOCKS

# for router itself
iptables -t nat -A OUTPUT -p tcp -m set --match-set router dst -j REDIRECT --to-ports 3333</pre>

**Comment by sadoneli** [comment]
@madeye 
got it, I  will try it out~

**Comment by sadoneli** [comment]
@madeye 
<pre>#define MAX_UDP_PACKET_SIZE (576)</pre>

is this right?

**Comment by madeye** [comment]
I think you can use the latest commit directly: https://github.com/shadowsocks/shadowsocks-libev/commit/a9f8b2bdfab8dc2ec155000477a6562a89f610ed

**Comment by sadoneli** [comment]
I have conpiled the latest shadowsocks

the test guy said he still get 100% packet loss
and the nat type on x1 is restricted

btw, by force setting <code>dhcp-option-force=26,1397</code>
the mtu of x1 still get 1500
I don't hnow where is wrong

**Comment by madeye** [comment]
Try to tune the interface's MTU on router, like `ifconfig eth0 mtu 1400`.

With shadowsocks and TPROXY, I don't think Path MTU discovery could work properly. Then with a wrong MTU (typically larger than the allowed one), `DF` (don't fragment) UDP packets got 100% loss. I guess it's the major problem.

**Comment by sadoneli** [comment]
I have compiled the lasted shadowsocks-libev today.
By command below
<pre>ifconfig eth0 down
ifconfig eth0 mtu 1400
ifconfig eth0 up</pre>
I was able to change the mtu dispalyed on X1

result bleow:
default eth0 mtu=1500，shadowsocks disabled, X1 mtu is 1480，enable shadowsocks，X1 mtu is 1500
setting eth0 mtu=1488，shadowsocks disabled, X1 mtu is 1480，enable shadowsocks，X1 mtu is 1488
setting eth0 mtu=1400，shadowsocks disabled, X1 mtu is 1392，enable shadowsocks，X1 mtu is 1400
setting eth0 mtu=1397，shadowsocks disabled, X1 mtu is 1389，enable shadowsocks，X1 mtu is 1397

1.package still get 100% loss, in any mtu test circumstance.
2.when MTU is1500, XboxOne will decrease 20 to 1480, in other situation, the decrease value is 8.
3.when enabled shadowsocks, the MTU on Xboxone changed the same as eth0, TCP mode only still get this reselut
4. MTU 1397 is a weird value, when setting to this value, the X1 shows 1397 when ss enabled no matter what MTU of eth0 I changed. I have to reboot X1 and my router, to get it chang

**Comment by madeye** [comment]
Could you run tcpdump on your router when test the speed?
```
sudo tcpdump udp dst port YOUR_REMOTE_SERVER_PORT
```

**Comment by madeye** [comment]
Also, could you run the following command on your server in the same time?
```
sudo tcpdump udp dst port YOUR_REMOTE_SERVER_PORT
```

**Comment by sadoneli** [comment]
I am currently using ASUS RT-AC87U, with merlin firmware
no available packet grab software
I can try on my server

**Comment by Liqianyu** [comment]
This is my monitors record

x1_s.cap is Server
x1_r.cap is Router

filter is ip.addr==65.55.42.21

x1ds.xboxlive.com is 65.55.42.20\65.55.42.21
Delay test for XboxOne

cap download
http://1drv.ms/1EfxzQA

**Comment by Liqianyu** [comment]
In addition, it has been determined game mode (UDP forwarding) will cause CODAW, The Last Of Us and other games people search difficult

**Comment by madeye** [comment]
@Liqianyu According to your cap, it seems that every echo packet arrives normally.

**Comment by Liqianyu** [comment]
@madeye Under normal circumstances, there is a return packet length 105, as described above in FIG. But gaming mode router and server I did not see this package

**Comment by madeye** [comment]
@Liqianyu Could you run tcpdump on your server, I want to make sure the ping packet is properly sent to XBOX's server.

**Comment by Liqianyu** [comment]
@madeye Servers and routers are equipped with tcpdump. The above x1_s.cap is server listens.

**Comment by madeye** [comment]
@Liqianyu in x1_s.cap, I saw many echo test packets sent to 65.55.42.21:3074, but no packets received from that server.
Is it possible that XBOX's server blocked your server IP?
Could you try set a VPN on that server and run XBOX's test again?

**Comment by madeye** [comment]
BTW, which encryption are your using?

**Comment by Liqianyu** [comment]
@madeye Yes, I also have the same discovery and ideas, but not only me, my All vps is the same result.
encryption is AES-256-CFB
I do not think the problem is the server. If use vpn, you will not have this problem.

**Comment by Liqianyu** [comment]
BTW,My server is shadowsocks python

**Comment by madeye** [comment]
@Liqianyu Here is the same packet on the router and the server. You can see the data is exactly the same, The different lengths are because of the additional 4 bytes for VLAN (802.1q). It means shadowsocks does its job.

![image](https://cloud.githubusercontent.com/assets/627917/9153356/7585b7b8-3e83-11e5-8cbd-2e9a5930237d.png)

I think it's possible that XBOX blocks echo packets from VPS providers, which can avoid DDOS attacks on their server. Or XBOX takes your router's IP as your real IP and drops all packets from your VPS's IP.

**Comment by sadoneli** [comment]
I am wondering why VPN on the same vps works fine?

2015-08-09 10:53 GMT+08:00 Max Lv <notifications@github.com>:

**Comment by Liqianyu** [comment]
@madeye but，if you use pptp vpn is work 
On the same server, so I think Microsoft did not prevent the vps ip

**Comment by madeye** [comment]
Then I think XBOX may recognize the router's IP as your real IP.

Considering the incorrect MTU for shadowsocks, it's possible that XBOX use something like ICMP to do both path MTU discovery and IP address detection (traceroute like).

**Comment by Liqianyu** [comment]
@madeye 
However, I did not see icmp packets.

**Comment by Liqianyu** [comment]
https://www.v2ex.com/t/114234

这几天我也是一直走在找 shadowsocks 和 udp 转发相关的东西, 我其实已经在 kyonli 的那个 downloads 里用了支持 udp 转发的 ss-local 了, 并配合 ProxyCap 一起使用, 但是实际使用中, 只发现 QQ 的 UDP 连接最好, 有收有发 (这可能是因为这个程序它本身支持 s5 代理模式有关) 

之后我测试 GTA 5 和 Battlefield 4, 这两个游戏走 TCP 也走 UDP, 需要 UDP 连接的, 通过 ProxyCap 看只有 sent 无 recv, 然后各种连不上, 或者断线 

我以为是兼容性不好, 就拿来测试 STEAM, STEAM 通过 ProxyCap 时若不强制添加走 tcp 的参数就直接连都连不上, 此时看分析, 一样是 UDP 有发送无接收 

但是非原生支援的, 用 ProxyCap 也不一定能兼容, 表现为连不上, 就算连上了也会断线 (主要还是 Socks5 不支持 P2P 打洞) 对于这种情况

**Comment by madeye** [comment]
By digging into this issue further, I noticed that the `DF` flag is set for XBOX echo test. However, shadowsocks drop that flag when sending UDP packets to the remote server.

![image](https://cloud.githubusercontent.com/assets/627917/9243022/5baaa42e-41bd-11e5-8e3c-e2f9a0f6b47e.png)

**Comment by madeye** [comment]
@Liqianyu Could you try the latest server code on the `frag` branch? No need to update the client on the router.

https://github.com/shadowsocks/shadowsocks-libev/tree/frag

**Comment by sadoneli** [comment]
![1](https://cloud.githubusercontent.com/assets/10495520/9246636/7e9447fc-41df-11e5-8771-81baffcf899c.gif)
initial test showed some ip fragment error

still get 100% packet loss

**Comment by madeye** [comment]
Then, could you also try to update the router's shadowsocks-libev with the branch `frag`?

**Comment by sadoneli** [comment]
test is undertaking ...

btw, I invite you join our game test qq group
only 11 members in it, will not take you much time
goup Nu. 466278219

**Comment by madeye** [comment]
Sorry, I do not use IMs like QQ...

**Comment by sadoneli** [comment]
By update the ss-redir in router to  branch frag
still get 100% packet loss
![2015-08-13_17-50-49](https://cloud.githubusercontent.com/assets/10495520/9247552/baa8a772-41e6-11e5-9687-c91a5d15df00.png)

**Comment by smartepsh** [comment]
I have a same issue on my xbox one. 
But even though 100% loss, The xbox still can play online very well as normal....

**Comment by madeye** [comment]
@sadoneli @Liqianyu Could you test the latest version on the master branch?

**Comment by fenivana** [comment]
Still has the problem on 2.4.0.

**Comment by houzi-** [comment]
@sadoneli
The merlin asus firmware supports TPROXY module? Feeling merlin and tomato-arm-shibby loaded kernel modules are the same! Or you compile time to add? But I was always looking for the compiler does not add TPROXY module options!

**Comment by sadoneli** [comment]
@houzi- yes, we have enabled the Tproxy support in the kernel, and compiled the corresponding fimware

**Comment by houzi-** [comment]
@sadoneli

I ask whether the guidance about how do you at compile kernel menuconfig open the TPROXY support!

**Comment by wongsyrone** [comment]
You should select `iptables-mod-tproxy` and `kmod-ipt-tproxy` if compiling OpenWrt.

**Comment by houzi-** [comment]
@wongsyrone
Thank you! I'm not talking about OpenWrt! OpenWrt is easily solved!

**Comment by sadoneli** [comment]
@houzi- 
edit release/src-rt-6.x.4708/linux/linux-2.6.36/config_base.6a

make sure you set y to these three config blow:
CONFIG_NETFILTER_TPROXY=y
CONFIG_NETFILTER_XT_TARGET_TPROXY=y
CONFIG_NETFILTER_XT_MATCH_SOCKET=y

then you can compile your TPROXY suport Merlin fimware

**Comment by houzi-** [comment]
@sadoneli

thanks

**Comment by houzi-** [comment]
@sadoneli 

Sorry! I have a question to ask, that I was just 'config_base.6a' File not found 'CONFIG_NETFILTER_TPROXY', but you give the remaining two arguments I did not find, is not to follow the 'CONFIG_NETFILTER_TPROXY' back add up to?

**Comment by sadoneli** [comment]
@houzi- 大哥，你说中文吧，你这段我看不懂

**Comment by houzi-** [comment]
@sadoneli
就是你提供的参数中！我只找到CONFIG_NETFILTER_TPROXY
其他两个参数是否自己添加到
CONFIG_NETFILTER_TPROXY
的后面

**Comment by sadoneli** [comment]
是的，后面两个自己加上就行，位置应该不重要

**Comment by houzi-** [comment]
@sadoneli
谢谢！

**Comment by sadoneli** [comment]
@houzi- 
![2015-10-16_23-17-59](https://cloud.githubusercontent.com/assets/10495520/10545643/508d0aec-745c-11e5-992d-d3fe4b611187.png)
有强迫症的话就按字母顺序 加

**Comment by houzi-** [comment]
@wongsyrone
您好！
不知道你的Pcap_DNSProxy项目能否在tomato-arm下编译使用！

**Comment by McContax** [comment]
Ok! I know most part of you guys is Chinese.Ether am I.And I when I using the SS to play the last of us.I find it dificult to search the player.And it seems didn't work on BF4 even though the udp relay is enble.

**Comment by Jerome-lara** [comment]
@Liqianyu 是不是目前玩GTA BF4最好的办法就是找个靠谱的VPN？因为VPN可以TCP/UDP是吧？

**Comment by Jerome-lara** [comment]
@Liqianyu 另外问一句，挂了VPN之后，NAT类型是不是就和VPN有关了？现在家里NAT类型是3严格，连有些VPN就变成2了

**Comment by Paull** [comment]
@Jerome-lara 自有VPS可以给VPN帐号固定IP，然后在iptables里把相关端口转给这个固定IP，虽然是double nat但还是可以弄成full-cone nat（也就是type 1）

**Comment by Jerome-lara** [comment]
@Paull 谢谢回答，看起来就和路由器做端口映射一样

**Comment by Liqianyu** [comment]
@madeye
The latest version still does not work, perhaps the UDP broadcast packets do not support the cause?

**Comment by Jerome-lara** [comment]
@Paull 我刚买了个搬瓦工的vps，准备自己研究一下搭建一个PPTP。

**Comment by plumflowergreen** [comment]
搬瓦工 直接有一键安装 shadowsocks，比pptp好用很多。

**Comment by Jerome-lara** [comment]
@plumflowergreen 我知道，但是玩有些游戏SS不支持，比如GTA

**Comment by asasuou** [comment]
sockscap64？

**Comment by Jerome-lara** [comment]
@Paull 端口转发这样就行了吧？
iptables -t nat -A PREROUTING --dst 46.98.24.109 -p udp --dport 4500 -j DNAT --to-destination 192.168.0.150:4500
iptables -t nat -A POSTROUTING --dst 192.168.0.150 -p udp --dport 4500 -j SNAT --to-source 192.168.0.1
46.98.24.109是我的VPS ip地址，192.168.0.150是VPN帐号设置里给的固定IP。

**Comment by Paull** [comment]
@Jerome-lara 
-t nat -A PREROUTING -i venet0 -p tcp -m tcp --dport 22 -j RETURN
-t nat -A PREROUTING -i venet0 -p tcp -m tcp --dport 1723 -j RETURN
-t nat -A PREROUTING -i venet0 -p icmp -j RETURN
-t nat -A PREROUTING -i venet0 -j DNAT --to-destination 192.168.0.150
私人vpn反正没别的用途，除了ICMP、TCP22和TCP1723外全部重定向

**Comment by Jerome-lara** [comment]
@Paull 你给我的这几个命令是什么作用？

另外我之前发的端口转发输完是错的…
然后我又搜了一下完整的命令应该是这样的
iptables -t nat -A PREROUTING -d 公网地址 -p tcp --dport 80 -j DNAT --to 固定VPN地址:81
iptables -t nat -A POSTROUTING -d 固定VPN地址 -p tcp --dport 81 -j SNAT --to 192.168.0.1
iptables -A FORWARD -p tcp -d 固定VPN地址 --dport 81 -j ACCEPT
转发一个端口要打3条命令…

**Comment by crzidea** [comment]
Any update? I have the exactly same issue and still can't be solved. I'm playing Diablo 3 on xbox one connecting with raspberry pi.

**Comment by Jerome-lara** [comment]
@Paull 有一个问题，GOOGLE了一圈无解，输入你给的那4个，搬瓦工狂给我发邮件，说有漏洞强制给我添加一个条规则关闭53端口。。。邮件内容：
KiwiVM has detected an insecure recursive DNS resolver on IP 45.**.**.**, which may result in your server getting involved in DNS Amplification DoS attacks.
To prevent this from happening, KiwiVM has blocked port 53 in your server by adding the following iptables rules: 

    iptables -I INPUT -p udp --destination-port 53 -j DROP
    iptables -I FORWARD -p udp --destination-port 53 -j DROP

You can fix this vulnerability by securing your DNS daemon (or by removing it from your server).

Once this vulnerability is fixed, you may remove these iptables rules.

**Comment by sadoneli** [comment]
我觉得还是关了这个issue吧

**Comment by crzidea** [comment]
@sadoneli 不要关啊，问题还没解决。。。

**Comment by sadoneli** [comment]
@madeye 最近版本反映这事儿的人又多起来了，能不能有解决方案，希望作者能回复下喽~

**Comment by madeye** [comment]
It'd be a complexibility issue between transparent proxy and XBOX. It means I can do nothing to fix it from shadowsocks-libev itself.

Also, you may try this: http://lartc.org/howto/lartc.cookbook.mtu-mss.html. For example:

`iptables -A FORWARD -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --set-mss 1320`

**Comment by sadoneli** [comment]
@madeye  is 1320 a random number or suggest one?

**Comment by madeye** [comment]
Just a random number, which should be small enough for common links.

**Comment by madeye** [comment]
Please try the latest commit to see if it would help.

**Comment by Paull** [comment]
I'll try the latest this weekend.

**Comment by Paull** [comment]
上周末在自家的树莓派路由器上试了一下新版本，并没有解决该issue的感觉，也许是我姿势不对，可以指导后再测。
![ss_3 1 2](https://user-images.githubusercontent.com/273218/35312388-1e877b08-00f6-11e8-8bdb-e572179b4873.jpg)
此图是老版本ss-redir，3.1.2。
![ss_3 1 3](https://user-images.githubusercontent.com/273218/35312389-1eba1e6e-00f6-11e8-8b01-374390f8d06f.jpg)
此图是新版本ss-redir，3.1.3。

两个版本所有环境都一样，只有可执行文件不一样。
也用TCPDUMP抓了包，太大了不知道怎么发上来。。。
TCPDUMP显示3.1.3并没有完成整个测试流程，中间就断了，但是我看不懂包的具体内容@_@

**Comment by Jerome-lara** [comment]
@Paull 这么难搞，我还是用网易的uu主机加速吧，最近网易uu在内测主机版加速

**Comment by wangyu-** [comment]
@sadoneli  @Liqianyu 

Could you plz run this command at both sides(router and vps), and test again ?

```
echo 1 >  /proc/sys/net/ipv4/ip_no_pmtu_disc
```

I suspect PMTUD is broken for your path (router<---->vps).

**Comment by imwsy** [comment]
I can confirm the packet loss rate in the xbox test will not show 100% after both the server and the router shut down the **Path MTU Discovery** feature

**Comment by Stoptimerag** [comment]
> @madeye
> The latest version still does not work, perhaps the UDP broadcast packets do not support the cause?

大佬你的这个问题解决了吗？就是这个65.55.42.21 没有response的问题

**Comment by enihcam** [comment]
> I can confirm the packet loss rate in the xbox test will not show 100% after the server side (client does not need) shut down the **Path MTU Discovery** feature server and client (openwrt use luci-app-shadowsocks to enable udp relay) version are both [85a64ae](https://github.com/shadowsocks/shadowsocks-libev/commit/85a64ae8360759aa59ebe3061c092c9a2054d078)
> 
> disbale pmtu means **echo 1 > /proc/sys/net/ipv4/ip_no_pmtu_disc** enable pmtu means **echo 0 > /proc/sys/net/ipv4/ip_no_pmtu_disc**
> 
> By default, client enable pmtu / server enable pmtu --> 100% loss
> 
> client disbale pmtu / server disbale pmtu --> 0% loss client enable pmtu / server disbale pmtu --> 0% loss

you sure you want to set this value to 1?

```
ip_no_pmtu_disc - INTEGER
	Disable Path MTU Discovery. If enabled in mode 1 and a
	fragmentation-required ICMP is received, the PMTU to this
	destination will be set to min_pmtu (see below). You will need
	to raise min_pmtu to the smallest interface MTU on your system
	manually if you want to avoid locally generated fragments.

	In mode 2 incoming Path MTU Discovery messages will be
	discarded. Outgoing frames are handled the same as in mode 1,
	implicitly setting IP_PMTUDISC_DONT on every created socket.

	Mode 3 is a hardened pmtu discover mode. The kernel will only
	accept fragmentation-needed errors if the underlying protocol
	can verify them besides a plain socket lookup. Current
	protocols for which pmtu events will be honored are TCP, SCTP
	and DCCP as they verify e.g. the sequence number or the
	association. This mode should not be enabled globally but is
	only intended to secure e.g. name servers in namespaces where
	TCP path mtu must still work but path MTU information of other
	protocols should be discarded. If enabled globally this mode
	could break other protocols.

	Possible values: 0-3
	Default: FALSE
```

**Comment by RebelliousWhiz** [comment]
For whoever searches for a xbox proxy solution:

I gave up trying xbox with shadowsocks a long time ago. I think the time I put in was not quite worthy since my major need was to play xbox games in China and have more fun. You can purchase something like UU Game Booster (by NetEase). You will find your life will be way easier and better.

But if you are "because I can" type, don't mind me. It's fun trying, for sure.

**Comment by madeye** [comment]
Try https://github.com/shadowsocks/shadowsocks-libev/commit/46382c23fac8fbabb62130ef49d3f0bf4c807b43

**Comment by pexcn** [comment]
> Try [46382c2](https://github.com/shadowsocks/shadowsocks-libev/commit/46382c23fac8fbabb62130ef49d3f0bf4c807b43)

I tested, still have this problem.

**Comment by jiaxiaogang** [comment]
我的nat是开放,但多人测试是100%丢包,找谁说理去,upnp开了不行,然后试了下DMZ也不行,已崩溃

**Comment by jiaxiaogang** [comment]
## 我的nat是开放,但多人测试是100%丢包,找谁说理去,upnp开了不行,然后试了下DMZ也不行,已崩溃

**Comment by RebelliousWhiz** [comment]
> 我的nat是开放,但多人测试是100%丢包,找谁说理去,upnp开了不行,然后试了下DMZ也不行,已崩溃

别折腾了，用 uu 加速器吧，openwrt 也支持的，真的...
