### ISSUE TITLE
如何设置ss-redir模式下的udp relay？

### ISSUE THREAD

**Issue by smartepsh** [shadowsocks/shadowsocks-libev#362]
openwrt采用ss-redir模式运行，加入-u参数，iptables设置关于udp设置如下

ip rule add fwmark 0x01/0x01 table 100
ip route add local 0.0.0.0/0 dev lo table 100
iptables -t mangle -A SHADOWSOCKS -p udp -j TPROXY --on-port 65500 --tproxy-mark 0x01/0x01
iptables -t mangle -A PREROUTING -j SHADOWSOCKS

wiki上写的是转发53端口，我想全局转发，就去掉了dport，因为对iptables不是特别了解，所以也不知道这么写是否可以。。。

但是如果使用这个设置，我的dns服务会down掉，所有的网页均无法运行，无法正常使用。
如果不使用如上设置，仅启用tcp转发，那么功能一切正常。

现在想问下，有没有现成的可以实现全局udp relay的设置，最好有一套系统的设置指导。。。

**Comment by madeye** [comment]
https://github.com/shadowsocks/openwrt-shadowsocks

**Comment by smartepsh** [comment]
这个我也使用过，同样是udp+tcp全局转发模式dns服务down掉

**Comment by wendellou** [comment]
ss-redir  udp relay始终无法成功

**Comment by AlexZhuo** [comment]
我在Ubuntu16.04上开启成功，跟你的你iptables命令一样，也是DNS无法解析，原因是出现了环形转发，于是我加了下面几句之后，UDP转发正常，DNS正常
iptables -t mangle -I PREROUTING -d 127.0.0.0/24 -j RETURN
iptables -t mangle -I PREROUTING -d 192.168.0.0/16 -j RETURN
iptables -t mangle -I PREROUTING -d 0.0.0.0/8 -j RETURN
把Unbuntu电脑当路由器用，客户端实现了UDP转发

**Comment by kevinzu007** [comment]
@AlexZhuo  那是不是还要把国内的ip也要想nat表那样一一添加呢？
例如：
iptables -t   **mangle**   -A SHADOWSOCKS -d 114.114.0.0/16  -j RETURN

**Comment by kevinzu007** [comment]
如果只是使用个人电脑使用ss-redirx实现tcp+udp全局转发可以吗？

如果像tcp一样，设置output就会出现a以下错误：
x_tables: ip_tables: TPROXY target: used from hooks PREROUTING/OUTPUT, but only usable from PREROUTING

**Comment by AlexZhuo** [comment]
@kevinzu007 回答你第一个问题，如果你想实现UDP转发国内外分流的话，是需要加入mangle 国内路由表 -j RETURN的。
TProxy我试了一下，也不能作用在OUTPUT链上

**Comment by yiguihai** [comment]
我猜ss-redir得到的是192.168.*.*:53 的内网目的地数据包然后发到服务器 服务器上没有这个地址监听所以dns转发不了
