### ISSUE TITLE
mbed TLS (New PolarSSL)

### ISSUE THREAD

**Issue by MeganEllis** [shadowsocks/shadowsocks-libev#364]
Hi,
PolarSSL team changed the name to mbedTLS and the last version which works fine with shadowsocks-libev is `mbedtls-1.3.11-gpl.tgz`; when I tried to compile with current version (`mbedtls-2.0.0-gpl.tgz`) I got this message:
```
$ ./configure --prefix="$HOME/ss" --with-crypto-library=polarssl --with-polarssl=$HOME/mbedtls-build
...
checking for cipher_init_ctx in -lpolarssl... no
configure: error: PolarSSL libraries not found.
```
Would you please update the for latest mbedTLS?

PS: I already compiled mbedTLS 2.0.0 and also rename `libmbedtls.a` to `libpolarssl.a` in `lib` folder -like PolarSSL1.3.11-, but still got the error.

**Comment by madeye** [comment]
Currently, we do not support mbed TLS. So, just use PolarSSL or fix this issue yourself and submit a pull request instead.

**Comment by wongsyrone** [comment]
@MeganEllis  How to migrating from mbed TLS 1.3 to mbed TLS 2.0: https://tls.mbed.org/kb/how-to/upgrade-2.0

**Comment by wongsyrone** [comment]
@MeganEllis  Hi, can you test [this one](https://github.com/wongsyrone/shadowsocks-libev-mbedtls)?
