### ISSUE TITLE
希望增加指定用户启动进程

### ISSUE THREAD

**Issue by kn007** [shadowsocks/shadowsocks-libev#374]
你好，希望能增加指定用户启动进程的参数（跟https://github.com/shadowsocks/shadowsocks的--user参数一致）。谢谢。

在实际环境使用，还是十分必要的。

我现在是通过sudo指定用户启动，但这也导致启动一个ss，会有sudo进程与ss-server进程。浪费。

**Comment by madeye** [comment]
`-a`

**Comment by kn007** [comment]
非常感谢！
或许你可以在下一个版本编译的时候添加该参数说明和编辑README.md添加该参数。
握手！
