### ISSUE TITLE
Cross compile error on tomato-shibby MIPS build 

### ISSUE THREAD

**Issue by xixixihaha** [shadowsocks/shadowsocks-libev#375]
Is it possible to replace the atomic operations as it is hardware dependant.
I met the following issue when I was cross compiling it for MIPS (tomato Shibby build) 

make[7]: Entering directory `/Data/DDWRT/simonwork/release/src/router/shadowsocks-libev/src'
  CCLD   ss-local
../libcork/.libs/libcork.a(libcork_la-error.o): In function `cork_error_get':
/Data/DDWRT/simonwork/release/src/router/shadowsocks-libev/libcork/core/error.c:88: undefined reference to `__sync_val_compare_and_swap_4'
/Data/DDWRT/simonwork/release/src/router/shadowsocks-libev/libcork/core/error.c:92: undefined reference to `__sync_val_compare_and_swap_4'
/Data/DDWRT/simonwork/release/src/router/shadowsocks-libev/libcork/core/error.c:88: undefined reference to `__sync_val_compare_and_swap_4'

**Comment by madeye** [comment]
It's a bug of old GCC. Try some newer one.
