### ISSUE TITLE
v2.3.0 for OpenWRT return 404

### ISSUE THREAD

**Issue by yzsme** [shadowsocks/shadowsocks-libev#377]
Dear,

It seems that OpenWRT try to download v2.3.0 from https://github.com/shadowsocks/shadowsocks-libev/archive but only to receive 404.

mkdir -p /home/openwrt/openwrt/dl
/home/openwrt/openwrt/scripts/download.pl "/home/openwrt/openwrt/dl" "v2.3.0.tar.gz" "unknown" "https://github.com/shadowsocks/shadowsocks-libev/archive"
converted 'https://github.com/shadowsocks/shadowsocks-libev/archive/v2.3.0.tar.gz' (ANSI_X3.4-1968) -> 'https://github.com/shadowsocks/shadowsocks-libev/archive/v2.3.0.tar.gz' (UTF-8)
--2015-08-16 12:24:33--  https://github.com/shadowsocks/shadowsocks-libev/archive/v2.3.0.tar.gz
Resolving github.com (github.com)... 192.30.252.131
Connecting to github.com (github.com)|192.30.252.131|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/shadowsocks/shadowsocks-libev/tar.gz/v2.3.0 [following]
converted 'https://codeload.github.com/shadowsocks/shadowsocks-libev/tar.gz/v2.3.0' (ANSI_X3.4-1968) -> 'https://codeload.github.com/shadowsocks/shadowsocks-libev/tar.gz/v2.3.0' (UTF-8)
--2015-08-16 12:24:33--  https://codeload.github.com/shadowsocks/shadowsocks-libev/tar.gz/v2.3.0
Resolving codeload.github.com (codeload.github.com)... 192.30.252.147
Connecting to codeload.github.com (codeload.github.com)|192.30.252.147|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-08-16 12:24:34 ERROR 404: Not Found.

Download failed.
converted 'http://mirror2.openwrt.org/sources/v2.3.0.tar.gz' (ANSI_X3.4-1968) -> 'http://mirror2.openwrt.org/sources/v2.3.0.tar.gz' (UTF-8)
--2015-08-16 12:24:34--  http://mirror2.openwrt.org/sources/v2.3.0.tar.gz
Resolving mirror2.openwrt.org (mirror2.openwrt.org)... 46.4.11.11
Connecting to mirror2.openwrt.org (mirror2.openwrt.org)|46.4.11.11|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-08-16 12:24:34 ERROR 404: Not Found.

Download failed.
converted 'http://downloads.openwrt.org/sources/v2.3.0.tar.gz' (ANSI_X3.4-1968) -> 'http://downloads.openwrt.org/sources/v2.3.0.tar.gz' (UTF-8)
--2015-08-16 12:24:34--  http://downloads.openwrt.org/sources/v2.3.0.tar.gz
Resolving downloads.openwrt.org (downloads.openwrt.org)... 78.24.191.177
Connecting to downloads.openwrt.org (downloads.openwrt.org)|78.24.191.177|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-08-16 12:24:35 ERROR 404: Not Found.

Download failed.
No more mirrors to try - giving up.
Makefile:78: recipe for target '/home/openwrt/openwrt/dl/v2.3.0.tar.gz' failed
make[3]: *** [/home/openwrt/openwrt/dl/v2.3.0.tar.gz] Error 2
make[3]: Leaving directory '/home/openwrt/openwrt/package/shadowsocks-libev/openwrt'
package/Makefile:173: recipe for target 'package/shadowsocks-libev/openwrt/compile' failed
make[2]: *** [package/shadowsocks-libev/openwrt/compile] Error 2
make[2]: Leaving directory '/home/openwrt/openwrt'
package/Makefile:170: recipe for target '/home/openwrt/openwrt/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/stamp/.package_compile' failed
make[1]: *** [/home/openwrt/openwrt/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/openwrt/openwrt'
/home/openwrt/openwrt/include/toplevel.mk:171: recipe for target 'world' failed
make: *** [world] Error 2

Would you mind having a check?

Thank you & Best regards,
Zhensheng Yuan

**Comment by madeye** [comment]
Nor released yet.
