### ISSUE TITLE
server-multi-passwd.json for libev?

### ISSUE THREAD

**Issue by Itianxia** [shadowsocks/shadowsocks-libev#378]
Hi:
    Is there a server-multi-passwd.json for libev ? Only ss-Python support as i know.

**Comment by Itianxia** [comment]
Look forward to ss-manage Tutorial for libev.
thanks a lot.

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks/wiki/Manage-Multiple-Users

**Comment by madeye** [comment]
The API is exactly the same.

**Comment by madeye** [comment]
Also, https://github.com/shadowsocks/shadowsocks-libev/blob/master/shadowsocks-libev.8

**Comment by Itianxia** [comment]
ok, thanks,I'll check it.
btw, libev ;centos7;selinux disabled;iptables disabled.
got    ERROR: getpeername: Transport endpoint is not connected.
just leave it?
