### ISSUE TITLE
Openwrt 客户端问题

### ISSUE THREAD

**Issue by sinalpha** [shadowsocks/shadowsocks-libev#379]
shadowsocks 在openwrt上运行一段时间后，会有一个诡异的现象：

ssh 登陆路由器，在路由器（wan）上执行`wget`, `curl`, `ping`等命令，可以和代理服务器通信，能够正常访问获取墙外资源。
但是，在路由器的客户端（br-lan）workstation，无法和代理服务器通信。

必须执行 `\etc\init.d\shadowsocks restart`才能使客户端访问代理服务器。

---

尝试过 `\etc\init.d\chinadns restart` , `\etc\ini.t\network restart` , `\etc\init.d\dnsmasq restrat`均不能消除这个现象。

---

所以问题是，无法在openwrt路由器上监控shadowsocks客户端是否正常运行。

感觉shadowsocks在openwrt上运行一段时间后存在一个`伪正常`（面向路由器正常工作，面向主机不正常）的运行状态。

**Comment by madeye** [comment]
Post to https://github.com/shadowsocks/openwrt-shadowsocks

**Comment by madeye** [comment]
Also try http://shadowsocks.org/en/config/advanced.html
