### ISSUE TITLE
Could openwrt shadowsocks-libev connect to shadowsocks server (python)?

### ISSUE THREAD

**Issue by travelbob2005** [shadowsocks/shadowsocks-libev#380]
Hello,
If I using operwrt router with shadowsocks(libev) client installed in it,can I connect to shadowsocks server which is shadowsocks-python?

**Comment by madeye** [comment]
Of course yes.

**Comment by travelbob2005** [comment]
any special configuration need to set on shadowsocks server? because I use shadwosocks client(python) version,works with shadowsocks fine,but on openwrt router not working,unless I setup a shadwosocks libev version server on VPS......
