### ISSUE TITLE
using server-multi-passwd.json

### ISSUE THREAD

**Issue by nielspeen** [shadowsocks/shadowsocks-libev#383]
The Manage Multiple Users document (link below) suggests that his should work with both Python and libev versions:

ssserver --manager-address /var/run/shadowsocks-manager.sock -c tests/server-multi-passwd.json

However, the libev version of ss-server does not like this sample json file. I have to add the "server_port" and "password" fields to get it to start. It will then only listen on that one port, ignoring the multiple ports specified in the "port_password" table.

Is the libev version able to read a multi-passwd configuration? Or should the port/password combinations always be loaded through the manager socket?

If the manager socket is required, how do I enable it? Using --manager_address=127.0.0.1:2800 does not cause ss-server to listen on port 2800. Maybe I misunderstand how it's supposed to work?

* Documentation: https://github.com/Long-live-shadowsocks/shadowsocks-wiki/blob/master/Manage-Multiple-Users.md
* Sample json file: https://github.com/Long-live-shadowsocks/shadowsocks/blob/master/tests/server-multi-passwd.json

**Comment by madeye** [comment]
Try `ss-manager`.
