### ISSUE TITLE
Document for `ss-manager` is missing.

### ISSUE THREAD

**Issue by vimagick** [shadowsocks/shadowsocks-libev#384]
New command `ss-manger` was introduced in v2.3.0.
But I cannot figure it out how to use this wonderful feature.
There's a typo in README.md:  `--manager_address` should be `--manager-address`.
I'm a big fan of `shadowsocks`. Thank you for your hard work.

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks-libev/blob/master/shadowsocks-libev.8

**Comment by vimagick** [comment]
Thank you! :+1:

**Comment by ohyeah521** [comment]
@madeye  https://github.com/shadowsocks/shadowsocks-libev/blob/master/shadowsocks-libev.8  

这个链接失效了，求ss-manger用法。

**Comment by hosiet** [comment]
#385

https://github.com/shadowsocks/shadowsocks-libev/blob/master/man/ss-manager.1
