### ISSUE TITLE
multi-user

### ISSUE THREAD

**Issue by Tomzuo** [shadowsocks/shadowsocks-libev#385]
How to Support multi-user？

**Comment by madeye** [comment]
Duplicate with #384

**Comment by time-river** [comment]
According to my Google results, this version can't do it.

**Comment by nielspeen** [comment]
@time-river yes, it can do it. For example:

```
ss-manager --manager 127.0.0.1:2888 --executable /usr/bin/ss-server -v -c test.son
```
with this test.json:
```
{
        "server":"1.2.3.4",
        "port_password": {
        "8381": "foobar1",
        "8382": "foobar2",
        "8383": "foobar3",
        "8384": "foobar4",
        "8385": "foobar5",
        "8386": "foobar6",
        "8387": "foobar7",
        "8388": "foobar8",
        "8389": "foobar9"
    }
}
```
It launches a separate process for each user, so it's not really efficient if you have a lot of users. In that case you probably want to use the Go version instead.
