### ISSUE TITLE
Problems loading images/CSS et. al. with newer builds of ss-server

### ISSUE THREAD

**Issue by ufufufu** [shadowsocks/shadowsocks-libev#387]
When using ss-server builds compiled with the newer commits in the shadowsocks-libev git repo, as a browser proxy server, it seems that the server will drop plenty of objects in website pages that has plenty of images, CSS files, js files and more.

How to reproduce the problem:-
1. Clone the git repo locally in VPS, then compile the shadowsocks-libev suite (I use the method mentioned in https://wp.me/PrgSo-EM).
2. Then in my Windows computer, using shadowsocks-csharp as the SOCKS5 proxy client for Firefox, I will then open a page with plenty of images. A good example is the front page of lowendtalk:-
3. The result:-
![screenshot-www lowendtalk com 2015-09-04 21-32-17](https://cloud.githubusercontent.com/assets/9815496/9684786/872b06f2-534c-11e5-9a2d-3e9c709d052e.png)
As you can see, there are some missing images like the avatars of the thread starters listed in the website. Pressing CTRL + F5 in the browser very rarely solve the problem.

To fix this, what I have done is:-
1. Go to the git repo, and then run the `git reset ea2326ec8f` command, to reset the repo to the state as seen in https://github.com/shadowsocks/shadowsocks-libev/tree/ea2326ec8f9325e3d4a24775620eab1e8fa2d92d
2. Compile the shadowsocks-libev suite again and then restart the ss-server daemon. 
3. Then CTRL-F5 the lowendtalk website again.
![screenshot-www lowendtalk com 2015-09-04 21-39-14](https://cloud.githubusercontent.com/assets/9815496/9684966/987f9b06-534d-11e5-951b-e78842a78fb8.png)
Now, the website will load correctly.

My suspicion lies with the commit at https://github.com/shadowsocks/shadowsocks-libev/tree/a50e00c240b96e6c41855c051134cbbd7cc5f8df and maybe also https://github.com/shadowsocks/shadowsocks-libev/tree/491d22f7a88d880b9db488b12d389dba7ddb9788 but I cannot test it because I cannot revert the former commit; the git commandline programs will say that automatic revert has failed.

**Comment by wongsyrone** [comment]
Maybe an issue related to mbed TLS or PolarSSL? Can you try to build with OpenSSL and test again?

**Comment by madeye** [comment]
Which crypto are you using?

**Comment by ufufufu** [comment]
The very latest one at https://github.com/shadowsocks/shadowsocks-windows/commits/master which I compiled myself.

By the way, using the latest stable version at https://github.com/shadowsocks/shadowsocks-windows/releases will still exhibit the same problem.

**Comment by ufufufu** [comment]
With the latest commit, the compiled ss-server now works perfectly, whether using openssl-devel or mbedl-tls 2.0.0.

Thanks.
