### ISSUE TITLE
CPU exception occupancy

### ISSUE THREAD

**Issue by Talent30** [shadowsocks/shadowsocks-libev#388]
![bk5 wruppnw 3n6k9sn57uw](https://cloud.githubusercontent.com/assets/12595973/9704160/04a3f57a-54cf-11e5-9174-a81caf0ca23c.jpg)
There will be a certain time interval
You can temporarily solve the problem after the restart
![4j t6g d69pf 4c d_6itbp](https://cloud.githubusercontent.com/assets/12595973/9704172/6435250e-54cf-11e5-9585-404995205d44.png)

json
{
    "server":"0.0.0.0",
    "server_port":443,
    "local_port":1080,
    "password":"XXXXXXX",
    "timeout":600,
    "method":"chacha20",
    "fast_open": true
}
Ubuntu 14.04.3 LTS (GNU/Linux 3.13.0-46-generic x86_64)

**Comment by madeye** [comment]
http://shadowsocks.org/en/config/advanced.html
