### ISSUE TITLE
Lots of error message: ERROR: invalid password or cipher

### ISSUE THREAD

**Issue by smilinger** [shadowsocks/shadowsocks-libev#389]
After upgrade to v2.3.1 there are many error messages like this:
2015-09-07 02:16:50 ERROR: invalid password or cipher
2015-09-07 02:16:50 ERROR: failed to handshake with xxx.xxx.xxx.xxx

v2.3.0 has no such error message.

**Comment by madeye** [comment]
It's expected.

**Comment by wyf88** [comment]
@smilinger I can confirm this. It happened to me too after I upgraded shadowsocks-libev on the server side, but it only happens when I use the latest shadowsocks-windows client. After I use shadowsocks-qt5 instead, the error never occurs again. What's your shadowsocks client?

**Comment by wyf88** [comment]
After I upgrade to 2.3.2 on the server side, the error remains with shadowsocks-windows 2.5.6 on Windows 10 x64. No problem for the latest shadowsocks-qt5 client, as well as shadowsocks-ios and ShadowsocksX for OSX. I guess nothing can be done since the C# version has already been discontinued.

**Comment by GangZhuo** [comment]
I thinks I found the reason, see https://github.com/shadowsocks/shadowsocks-windows/pull/313 .
