### ISSUE TITLE
manager.c problem in cygwin

### ISSUE THREAD

**Issue by ekkolord** [shadowsocks/shadowsocks-libev#393]
```
  CC     manager.o
manager.c: In function ‘get_action’:
manager.c:163:5: error: array subscript has type ‘char’ [-Werror=char-subscripts]
     while(isspace(buf[pos]) && pos < len) pos++;
     ^
manager.c:167:5: error: array subscript has type ‘char’ [-Werror=char-subscripts]
     while((!isspace(buf[pos]) && buf[pos] != ':') && pos < len) pos++;
     ^
cc1: all warnings being treated as errors
Makefile:613: recipe for target 'manager.o' failed
```
BTW I have a 10mbps connection at home, and I use VMware Player to setup shadowsocks-libev
client for my computers, it can achieve 10mbps, and it's stable.

Sometimes I need a portable shadowsocks-libev client to use at school, then I choose the cygwin way,
but the speed of ss-local.exe is only ~4mbps(tested at home, haven't been tested at school),
if I download 3 files at the same time, the speed will be 10mbps.

Since I only do some simple browsing at school, I don't think the speed will be a problem for me.

**Comment by madeye** [comment]
Cygwin is much slower than a real POSIX system (even compared to a virtual machine), so the slow speed is expected.

**Comment by ekkolord** [comment]
Thank you!
