### ISSUE TITLE
打开太多udp导致  Too many open files 错误

### ISSUE THREAD

**Issue by dutonttie** [shadowsocks/shadowsocks-libev#394]
最近升级了到 v2.3.1， 3天后发现客户端刷新网页非常慢，我打开message.log发现大量too many open file信息（每次客户端刷新就这样）如图。
![message](https://cloud.githubusercontent.com/assets/9409003/9749830/61d1b660-56c3-11e5-8b2d-6bb5ea90729c.png)
下面是lsof 的内容，是ss-server
![lsof](https://cloud.githubusercontent.com/assets/9409003/9749846/7d37fd06-56c3-11e5-8707-034217e4a8c7.png)

**Comment by madeye** [comment]
http://shadowsocks.org/en/config/advanced.html

**Comment by dutonttie** [comment]
udp端口资源不释放可真要命，现在我的另外一台也出现udp的问题了，这台是bandwangon的；我不知道有多少服务器在用新版本，我感觉这是bug；
你上面的优化参数我已经改了，还是会出现，主要是openvz很多是不能修改的，但是ulimite这个我肯定已经改成功了51200，这个我已经查过open file 参数是修改成功了。
另外我估计使用net_speeder的程序的vps会放大这个问题，由于内存小的vps，我是每天重启的都这样。
看看我的messages截图。
![message](https://cloud.githubusercontent.com/assets/9409003/9835311/adcd9f0a-5a17-11e5-9390-d40c9d3574c9.png)

**Comment by dutonttie** [comment]
截图发错了是老的。这个才是
![bind](https://cloud.githubusercontent.com/assets/9409003/9835315/f3e73e7e-5a17-11e5-8b83-ce78d81233f5.PNG)

**Comment by kxmp** [comment]
U don't have enough memory, that's your server's problem.
