### ISSUE TITLE
problem with "I/O Error"

### ISSUE THREAD

**Issue by lution** [shadowsocks/shadowsocks-libev#397]
I have compiled a shadowsocks-libev v2.3.1 on my dd-wrt router( **DD-WRT v24-sp2 (10/08/14) kongac - build 25100M** ) 
ss-local and ss-redir seemed to be working fine on this .(*However ss-redir just runned without any error but i failed to make a transparent proxy on ss-redir for some iptables issue, it should be my problem*)

Then i updated my router to the lastest version dd-wrt (**DD-WRT v3.0-r27775M kongac (09/07/15)**), This time ss-local keeps working properly but when i tried to run ss-redir i got a `ss-redir: I/O error`, do you have any idea what might be causing this problem?

**Comment by madeye** [comment]
It's be an issue of your DD-WRT build, or shadowsocks.
