### ISSUE TITLE
V2 protocol

### ISSUE THREAD

**Issue by librehat** [shadowsocks/shadowsocks-libev#402]
I suggest we use this issue to design the next version (ver. 2) of the protocol which should be CCA secure. By negotiating and writing down technical details here, it'll be much easier to write a documentation.

Since ATYP is 8-bit, and the old type values are 1, 3, 4. Using bitwise operations to set new flags is brilliant (which is exactly something you did for the AUTH flag). Now I suggest we can use another bit for compression support (LZ4). All server ports adopting V2 protocol should be able to support compression if the ATYP has the flag set. Unlike AUTH, there is no need to introduce a boolean variable to explicitly turn on the compression.

If the compression is on, all data after the request header is compressed using LZ4 algorithm. Therefore, the server side needs to decompress those data first, then check the hash (if the AUTH is set).

As for the authentication and hash function of AUTH, there is no need to repeat the choices like encryption methods. Instead, I suggest we pick the optimal combination as the only implementation. That requires some benchmarkings which can be done once the methodology is fixed.

We also need to negotiate all details with all active maintainers to avoid the schism of this community and the incompatibility of the new protocol.

Last but not least, hope you don't mind for this issue open here.

**Comment by madeye** [comment]
I prefer to discussing the new protocol privately. You can resend your proposal to **all the core contributors** and discuss it through e-mail.
