### ISSUE TITLE
Server always prefer IPv4 over IPv6 for domain request

### ISSUE THREAD

**Issue by dujiulun** [shadowsocks/shadowsocks-libev#406]
服务器在收到类型为3（domain）的请求后，总是会优先解析IPv4地址，而不是使用getaddrinfo的顺序。

之前-go的服务器也是这样，但是在golang修复了golang/go#8453 （https://github.com/golang/go/issues/8453） 之后就变成了遵守系统的getaddrinfo优先级，可以通过/etc/gai.conf 控制顺序。

我也不是很清楚这是不是标准，上面的issue里说是RFC 6555或者6724……但是默认IPv4这种设定实在不太方便，在DigitalOcean某些机器上只有IPv6能上Google……

粗略看了一下代码， src/server.c#L602 表示使用了libcork，跟进去之后 libcork/core/ip-address.c#L472 直接写了"Try IPv4 first"，这也……

不知道开发者怎么看呢？

**Comment by madeye** [comment]
As the comment said, try IPv4 first.
