### ISSUE TITLE
最新的2.4.0版本不能启动

### ISSUE THREAD

**Issue by rwzsycwan** [shadowsocks/shadowsocks-libev#408]
debian 8 系统，最新的2.4.0版本编译安装后不能启动
root@localhost:/home# service shadowsocks-libev status
● shadowsocks-libev.service - Shadowsocks-libev Default Server Service
   Loaded: loaded (/lib/systemd/system/shadowsocks-libev.service; enabled)
   Active: failed (Result: exit-code) since Sun 2015-09-27 04:23:59 UTC; 8s ago
  Process: 20162 ExecStart=/usr/bin/ss-server -c /etc/shadowsocks-libev/config.json (code=exited, status=255)
 Main PID: 20162 (code=exited, status=255)

Sep 27 04:23:59 localhost systemd[1]: Started Shadowsocks-libev Default Server Service.
Sep 27 04:23:59 localhost ss-server[20162]: 2015-09-27 04:23:59 INFO: using tcp fast open
Sep 27 04:23:59 localhost ss-server[20162]: 2015-09-27 04:23:59 INFO: initialize ciphers... salsa20
Sep 27 04:23:59 localhost ss-server[20162]: 2015-09-27 04:23:59 ERROR: bind: Permission denied
Sep 27 04:23:59 localhost ss-server[20162]: 2015-09-27 04:23:59 ERROR: Could not bind
Sep 27 04:23:59 localhost ss-server[20162]: 2015-09-27 04:23:59 ERROR: bind() error
Sep 27 04:23:59 localhost systemd[1]: shadowsocks-libev.service: main process exited, code=exited, status=255/n/a
Sep 27 04:23:59 localhost systemd[1]: Unit shadowsocks-libev.service entered failed state.

好像是更新了shadowsocks-libev.service后不是root无法使用1000以内的端口

**Comment by wongsyrone** [comment]
绑定端口权限不够
`user=root`之后`systemctl daemon-reload`

**Comment by wongsyrone** [comment]
非要使用非root绑定低端口：http://stackoverflow.com/questions/413807/is-there-a-way-for-non-root-processes-to-bind-to-privileged-ports-1024-on-l

**Comment by hosiet** [comment]
当时添加 systemd 脚本时认为 root 用户并无必要，大多数情况下 ss 都没有必要使用低端口。

如果确有必要，可以按照 systemd 建议的做法，将 service 文件复制一份至 /etc/systemd/system
并自定义之，此处的配置文件优先级更高，且不会破坏系统的软件包管理机制。

Syrone Wong <notifications@github.com> 於 2015年9月27日週日 13:00 寫道：

**Comment by madeye** [comment]
@hosiet `-a user`选项可以在以root权限启动后，切换到相应用户运行，相关设置在 `/etc/default/shadowsocks-libev`中控制。所以建议修改现有逻辑，并提交 Pull Request。
