### ISSUE TITLE
版本更新后如何编译安装新版本？

### ISSUE THREAD

**Issue by sofs2005** [shadowsocks/shadowsocks-libev#411]
我的服务器是ubuntu的，通过git pull更新源码后，执行到
sh debian/autopkg.sh
cd ..
sudo dpkg -i shadowsocks-libev*.deb
总说找不到deb的文件，是怎么回事呢？
怎么更新版本呢？

**Comment by hosiet** [comment]
请贴出来终端的输出。

sofs2005 <notifications@github.com> 於 2015年9月28日週一 13:14 寫道：

**Comment by zhuzeitou** [comment]
我测试的情况是不会走到build，加了echo调试后发现停在这个位置
A=$(which debuild > /dev/null 2> /dev/null; echo $?)
，加上export就可以了

另外dh-systemd在debian 7.x需要wheezy-backports，还有除了dh-systemd还需要pkg-config mime-support init-system-helpers

**Comment by hosiet** [comment]
@zhuzeitou 
感谢补充，之后会去检查一下完整的依赖关系。有一些包是必要的，有一些是可选的。

在 Debian 7/8 上测试过后会提交修正的 PR。

**Comment by debiansid** [comment]
ubuntu 这个脚本也是不工作的

**Comment by hosiet** [comment]
@debiansid 

这里的问题是你没有安装 pkg-config，不是打包脚本的问题。所有打包需要的依赖在 `README.md` 中有记录。

**Comment by sofs2005** [comment]
今天更新后可以了
