### ISSUE TITLE
Raspberry Pi (Raspbian) did not include dh-systemd

### ISSUE THREAD

**Issue by s7lx** [shadowsocks/shadowsocks-libev#414]
Raspbian did not include 'dh-systemd'.
so I must install dh-systemd to build it.
Is any way to build deb package ?

**Comment by hosiet** [comment]
As said in the `README.md`, you may enable `debian-backports` and install that package by add software sources in `sources.list`. See also `http://backports.debian.org/Instructions/`.

`dh-systemd` and `init-system-helpers` are both of `all` architecture, so both Raspberry 1 and 2 series can install the package without causing any problem.
