### ISSUE TITLE
can not dpkg-buildpackage on debian7

### ISSUE THREAD

**Issue by debiansid** [shadowsocks/shadowsocks-libev#415]
dpkg-buildpackage -us -uc -i
dpkg-buildpackage: source package shadowsocks-libev
dpkg-buildpackage: source version 2.4.0-1
dpkg-buildpackage: source changed by Max Lv <max.c.lv@gmail.com>
dpkg-buildpackage: host architecture amd64
 dpkg-source -i --before-build shadowsocks-libev
dpkg-checkbuilddeps: Unmet build dependencies: dh-systemd (>= 1.5) pkg-config
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)

**Comment by debiansid** [comment]
sudo apt-get install dh-systemd autotools-dev
sudo: unable to resolve host linode
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package dh-systemd

**Comment by hosiet** [comment]
See #414 and take a try.
