### ISSUE TITLE
abnormal UDP port opened by ss-server

### ISSUE THREAD

**Issue by cattyhouse** [shadowsocks/shadowsocks-libev#416]
i'm running ss-server on my Linux server, I found an abnormal UPD port opened by ss-server 

* ss-server version:
2.3.1

* ss-server process
/usr/bin/ss-server -c /etc/shadowsocks.json -f /run/shadowsocks.pid -vvv

* ss-server config: `cat /etc/shadowsocks.json `
{
    "server":"0.0.0.0",
    "server_port":4043,
    "local_port":1913,
    "password":"vqrfewewfewdnwhhns",
    "timeout":600,
    "method":"aes-128-cfb"
}

* **abnormal UPD port 25335** opened by ss-server: `sudo netstat -nutlp4 | grep ss-server`
tcp        0      0 0.0.0.0:4043     0.0.0.0:*               LISTEN      2349/ss-server
udp        0      0 0.0.0.0:25335           0.0.0.0:*                           2349/ss-server

This happened about 1 min after ss-server is stated, not immediately. What is this UPD port for? 

thank you.

**Comment by madeye** [comment]
https://en.m.wikipedia.org/wiki/UDP_hole_punching
