### ISSUE TITLE
Does ss-libev support mbedTLS 2.x?

### ISSUE THREAD

**Issue by roytam1** [shadowsocks/shadowsocks-libev#422]
IIRC there is header changes in mbedTLS 2.x

**Comment by madeye** [comment]
Nope.

**Comment by bigtan** [comment]
Yep, already in use. Tested both in windows and debian/ubuntu.

if need, I can write a wiki, the compile of mbedtls in linux is ordinary, but in windows, you need to add some flag to make it work well.
# windows

## mbedtls
```
make lib WINDOWS_BUILD=1 no_test
make install DESTDIR="$HOME/prebuilt"
```
## shadowsocks-libev
```
./configure --prefix="$HOME/ss" --with-crypto-library=mbedtls --with-mbedtls=$HOME/prebuilt
make && make install
```
# linux
## mbedtls
```
make lib
make install DESTDIR="$HOME/prebuilt"
```
## shadowsocks-libev
```
./configure --prefix="$HOME/ss" --with-crypto-library=mbedtls --with-mbedtls=$HOME/prebuilt
make && make install
```

https://github.com/ARMmbed/mbedtls/issues/231
https://github.com/ARMmbed/mbedtls/issues/232

this two issue offer the way of compile mbedtls under windows system

**Comment by wongsyrone** [comment]
@bigtan 
Can you enable these defines in config.h of mbedtls
```c
#define MBEDTLS_THREADING_C
#define MBEDTLS_THREADING_PTHREAD
```
and test the performance? This combination will enable threading layer and use libpthread by default. Please use mbedtls 2.2

**Comment by bigtan** [comment]
I build both the with-thread and without-thread version and run them in one server. Maybe I can give you the config information and you can test its performance yourself. @wongsyrone
