### ISSUE TITLE
Fail to install ss-libev on my host

### ISSUE THREAD

**Issue by lixingcong** [shadowsocks/shadowsocks-libev#423]
The gpg key had been added and apt source list had been updated.

When I excute apt-get install shadowsocks-libev
It shows like that
"The following packages have unmet dependencies:
shadowsocks-libev : Depends: init-system-helpers (>= 1.18~) but 1.14 is to be installed"

What should I do?

**Comment by hosiet** [comment]
Read the Debian part of `README.md` and #414.

By the way, Ubuntu 14.04 is not supported because of that dependency problem as described in the issue. As 14.04 is a LTS version, should it be fixed? @madeye

**Comment by madeye** [comment]
@hosiet Yes, we should support Ubuntu 14.04.

**Comment by lixingcong** [comment]
Thanks to @hosiet 

I refered to this issue #414  and successfully install ss-liv on ubuntu 14.04 x64.

Add the following line to /etc/apt/sources.list:

	deb http://http.debian.net/debian wheezy-backports main

then execute:

	apt-get update

Finally install shadowsocks-libev by forcing dependencies:

	apt-get -t jessie-backports install shadowsocks-libev

It works. 

But I do not know if there is any risk.  :)

**Comment by hosiet** [comment]
Building the deb package on Ubuntu 14.04 may could fix the compatibility problem.

Could anyone give it a try on Ubuntu 14.04 and post the `Depends:` section in control file of generated deb package here?

**Comment by lixingcong** [comment]
@hosiet 
vps: ubuntu 14.04.3 server x64

root@localhost:~# apt-cache show shadowsocks-libev
Package: shadowsocks-libev
Version: 2.4.0-1
Architecture: amd64
Maintainer: Max Lv <max.c.lv@gmail.com>
Installed-Size: 892
Depends: libc6 (>= 2.9), libssl1.0.0 (>= 1.0.0), zlib1g (>= 1:1.1.4), init-system-helpers (>= 1.18~)
Breaks: shadowsocks (<< 1.5.3-2)
Replaces: shadowsocks (<< 1.5.3-2)
Homepage: http://www.shadowsocks.org
Priority: extra
Section: net
Filename: pool/main/s/shadowsocks-libev/shadowsocks-libev_2.4.0-1_amd64.deb
Size: 399490
SHA256: f5d9593db4d3f13dea326f8f901b0df853a21115447f20538fdd7b699a867d5f
SHA1: 51879e37ccd6a22ece486f702c745b6e95d45896
MD5sum: f1458c50e5c23baab2275409dc7945e1
Description: lightweight and secure socks5 proxy
 Shadowsocks-libev is a lightweight and secure socks5 proxy for
 embedded devices and low end boxes.
Description-md5: c0e92bb44ac6bb8e961a74c962fdda1b

**Comment by hosiet** [comment]
I built the package under a fresh Ubuntu 14.04 x86_64 environment and it seems to be working. The package requires an earlier version of `init-system-helpers` and works under Ubuntu 14.04.

```
Depends: libc6 (>= 2.17), libssl1.0.0 (>= 1.0.0), init-system-helpers (>= 1.13~)
```

The difference lies in the `postrm` script of debian, which is changed due to https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=721244.

* * *

possible solution
----------------------

So what should we do then? I think the best way is to modify shadowsocks/shadowsocks-org and provide a different deb package for Ubuntu 14.04 users.

**Comment by THWJ** [comment]
i use a small low-end vps, which run debian wheezy. I have  installed  shadowsocks-libev1.5.3-2, now i want to get update,and i get this error too.

**Comment by hosiet** [comment]
The problem seems to be fixed by 55ae226.

Please use Ubuntu-specific deb to fix problems around Ubuntu 14.04 as described in `README.md`. Any later version of Ubuntu (>= 14.10) or Debian (>= 8) would work fine too.

**Comment by THWJ** [comment]
在/etc/apt/sources.list中加入：
`deb http://http.debian.net/debian wheezy-backports main`
然后正常`apt-get upgrade shadowsocks-libev`就可以了

**Comment by William-Y** [comment]
OpenVZ的Debian wheezy 也有这问题，添加deb http://http.debian.net/debian wheezy-backports main到/etc/apt/sources.list可解～
