### ISSUE TITLE
It appears that PPA doesn't yet have the v2.3.1 

### ISSUE THREAD

**Issue by DamienGrand** [shadowsocks/shadowsocks-libev#427]
Hi! 
Just did apt-get update and apg-get upgrade

shadowsocks-libev still at 2.2.3 version.

Is the PPA not updated yet ?

**Comment by madeye** [comment]
Nope, build the package from the source: https://github.com/shadowsocks/shadowsocks-libev#build-package-from-source

**Comment by DamienGrand** [comment]
Well, I could wait for the PPA to update... I am assuming it will eventually update, right :) ?

**Comment by madeye** [comment]
Which PPA are you using? Try this: https://github.com/shadowsocks/shadowsocks-libev#install-from-repository

**Comment by DamienGrand** [comment]
I'm using http://shadowsocks.org/debian wheezy main

Sources list 


deb http://archive.ubuntu.com/ubuntu trusty main restricted universe
deb http://archive.ubuntu.com/ubuntu trusty-updates main restricted universe
deb http://security.ubuntu.com/ubuntu trusty-security main restricted universe $
deb http://archive.canonical.com/ubuntu trusty partner
deb http://shadowsocks.org/debian wheezy main

I'm trying to directly update via 

apt-get update 

apt-get install --only-upgrade shadowsocks-libev

After all is done I reboot and /usr/bin/ss-server --help still says 
----
shadowsocks-libev 2.2.3

  maintained by Max Lv <max.c.lv@gmail.com> and Linus Yang <laokongzi@gmail.com>

  usage:
----

**Comment by DamienGrand** [comment]
Okay I figured this out.
It's one of those unpleasant init helper issues

https://github.com/shadowsocks/shadowsocks-libev/issues/423#issuecomment-145337036
