### ISSUE TITLE
One more question - what is "onetime authentication" ?

### ISSUE THREAD

**Issue by DamienGrand** [shadowsocks/shadowsocks-libev#428]
Hi! 
One more question, if I may ask...
What is onetime authentication (I understand it's "experimental", just trying to decide whether I want to try it and what to expect)?

P.S.:
I did google and re-read the docs, and found no description.

**Comment by madeye** [comment]
It's a security enhancement, requiring latest server and client. For more details, please refer to the following links.

shadowsocks/shadowsocks#69
shadowsocks/shadowsocks#64
Long-live-shadowsocks/shadowsocks@ccd1c0b

**Comment by DamienGrand** [comment]
Ah, so it basically enables MACs such as  Poly1305 and others.
Cool beans, you're awesome.

Will try it out.

**Comment by exherb** [comment]
I'm using Surge iOS.

```
Proxy = custom, ?, 443, aes-256-cfb, password, http://?/SSEncrypt.module
```

Is there anyway to configure Surge for this onetime authentication feature? Thanks

@madeye

**Comment by learningis1st** [comment]
see https://trello.com/c/Nd2AaHu4/24-app-store-1-2-3
