### ISSUE TITLE
How to add multi-port support in openwrt's shadowsocks-libev client config.json

### ISSUE THREAD

**Issue by niclau** [shadowsocks/shadowsocks-libev#43]
I try to edit like this:
{
    "server": "123.123.123.1",
    "server_port": [8380, 8381, 8382, 8383],
    "local_port": 1081,
    "password": "barfoo!",
    "timeout": 60,
    "method": "aes-256-cfb"
}
But not work.

**Comment by gnu4cn** [comment]
[https://github.com/gnu4cn/openwrt-ss-configs](https://github.com/gnu4cn/openwrt-ss-configs)
