### ISSUE TITLE
How to build DEB with polarssl?

### ISSUE THREAD

**Issue by cuteribs** [shadowsocks/shadowsocks-libev#430]
I've run "./configure --with-crypto-library=polarssl --with-polarssl=/path/to/polarssl", 
but when I run "dpkg-buildpackage -us -uc -i", it still require libssl-dev to build the package.

**Comment by madeye** [comment]
Unfortunately, you can't do that.

**Comment by hosiet** [comment]
Checkout https://github.com/hosiet/shadowsocks-libev/
, if you like.

It is hard to get different Debian script to be merged into master branch, so I am keeping such solution as a fork now.

**Comment by cuteribs** [comment]
I'd got it work by one tiny change to "configure" file.
----------------------------------------------------------
# Check whether --with-crypto-library was given.
if test "${with_crypto_library+set}" = set; then :
  withval=$with_crypto_library;
    case "${withval}" in
      openssl|polarssl|mbedtls) ;;
      *) as_fn_error $? "bad value ${withval} for --with-crypto-library" "$LINENO" 5 ;;
    esac

else
  with_crypto_library="openssl"   ----> change "openssl" to "polarssl" or "mbedtls"

fi
