### ISSUE TITLE
shadowsocks-libev offer x64 file as x86

### ISSUE THREAD

**Issue by ayanamist** [shadowsocks/shadowsocks-libev#431]
deb http://shadowsocks.org/ubuntu trusty main
offer
http://shadowsocks.org/ubuntu/pool/main/s/shadowsocks-libev/shadowsocks-libev_2.4.0-1_i386.deb
but it contains a x64 file, so it can't be running

**Comment by madeye** [comment]
Fixed via https://github.com/shadowsocks/shadowsocks-org/commit/53c876472f458c50016fa3b56a51ec1803da8f58
