### ISSUE TITLE
The following packages have been kept back:   shadowsocks-libev

### ISSUE THREAD

**Issue by GitatHub** [shadowsocks/shadowsocks-libev#435]
Does SHADOWSOCKS-LIBEV never support debian 7+ through apt-get upgrade?

root@localhost:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 7.9 (wheezy)
Release:	7.9
Codename:	wheezy

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks-libev#build-package-from-source

Duplicate with #414
