### ISSUE TITLE
shadowsocks-libev is NOT running

### ISSUE THREAD

**Issue by GitatHub** [shadowsocks/shadowsocks-libev#436]
最新版安装之后，一切正常，但是运行一段时间之后，客户端收到 connection refused
登录服务端看到，shadowsocks-libev 服务已经不再运行了。以前的旧版没有遇到这种情况。
具体信息如下：
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:	trusty

ss-server --version

shadowsocks-libev 2.4.0

  maintained by Max Lv <max.c.lv@gmail.com> and Linus Yang <laokongzi@gmail.com>

通过
deb http://http.debian.net/debian wheezy-backports main
deb http://shadowsocks.org/ubuntu trusty main
安装的

**Comment by GitatHub** [comment]
换成了 debian 还是不能阻止自动被杀死

No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 7.9 (wheezy)
Release:	7.9
Codename:	wheezy

[FAIL] shadowsocks-libev is not running ... failed!

shadowsocks-libev 2.3.3

  maintained by Max Lv <max.c.lv@gmail.com> and Linus Yang <laokongzi@gmail.com>

不可能是 vps 主机内核的原因吧

**Comment by hosiet** [comment]
建议用监控软件管理之，或者尝试在前台进行运行并加上 -v 打印调试信息，或者使用类似 systemd 服务启动并查看运行日志等等。

如果有问题，可以把日志与 backtrace 等等的信息发上来。

**Comment by GitatHub** [comment]
把系统换成 DEBIAN 8.2 然后 APT 安装，默认配置下，这个问题消失了
目前已经正常运行超过4天，没有退出

除了偶尔有 reset 错误

Oct 27 --- ss-server[204]: time ERROR: server recv: Connection reset by peer
Oct 27 --- ss-server[204]: time ERROR: server recv: Connection reset by peer
Oct 27 --- ss-server[204]: time ERROR: server recv: Connection reset by peer
Oct 28 --- ss-server[204]: time ERROR: server recv: Connection reset by peer
Oct 28 --- ss-server[204]: time ERROR: server recv: Connection reset by peer
Oct 28 --- ss-server[204]: time ERROR: server recv: Connection reset by peer
Oct 28 --- ss-server[204]: time ERROR: server recv: Connection reset by peer
Oct 28 --- ss-server[204]: time ERROR: server recv: Connection reset by peer
Oct 28 --- ss-server[204]: time ERROR: server recv: Connection reset by peer
Oct 28 --- ss-server[204]: time ERROR: server recv: Connection reset by peer
Oct 28 --- ss-server[204]: time ERROR: server recv: Connection reset by peer
Oct 28 --- ss-server[204]: time ERROR: invalid header with addr type 117
Oct 28 --- ss-server[204]: time ERROR: failed to handshake with 159.226.22.8
Oct 28 --- ss-server[204]: time ERROR: server recv: Connection reset by peer
Oct 28 --- ss-server[204]: time ERROR: server recv: Connection reset by peer
Oct 28 --- ss-server[204]: time ERROR: server recv: Connection reset by peer
Oct 28 --- ss-server[204]: time ERROR: server recv: Connection reset by peer
Oct 30 --- ss-server[204]: time ERROR: server recv: Connection reset by peer
Oct 30 --- ss-server[204]: time ERROR: server recv: Connection reset by peer
Oct 30 --- ss-server[204]: time ERROR: server recv: Connection reset by peer
Oct 31 --- ss-server[204]: time ERROR: server recv: Connection reset by peer
Nov  1 --- ss-server[204]: time ERROR: server recv: Connection reset by peer
Nov  1 --- ss-server[204]: time ERROR: server recv: Connection reset by peer
Nov  1 --- ss-server[204]: time ERROR: server recv: Connection reset by peer
Nov  1 --- ss-server[204]: time ERROR: server recv: Connection reset by peer

**Comment by pospospos2007** [comment]
![image](https://cloud.githubusercontent.com/assets/11675650/23845343/73c0b1ae-0802-11e7-97c1-f55f303c8d2e.png)
你好，请问这个ss为何无法运行了？如何找到相关日志？

**Comment by guliujian** [comment]
把-d start关掉看报错啊

⁣Sent from BlueMail ​

**Comment by pospospos2007** [comment]
终于有人回复我啦，大哥，我研究了一下午，没有解决，都快哭了，能否qq联系一下？我的qq497603778

**Comment by pospospos2007** [comment]
我上面截图的原因我找到了，那个不是问题，是我没有正常关闭。现在的问题是，可以正常启动，但是用curl测试返回504，不知道原因，急死我了

**Comment by pospospos2007** [comment]
以前一直没问题的，后来需要不断重启ss，现在干脆用不了了。。。

**Comment by hosiet** [comment]
`sslocal` command is **not** provided by shadowsocks-libev so you shouldn't ask here. It is provided by the Python version.

**Comment by pospospos2007** [comment]
i knew ,but,i do not know where to ask for help ,sadly😓

2017-03-13 17:51 GMT+08:00 Boyuan Yang <notifications@github.com>:

**Comment by pospospos2007** [comment]
我现在正在解决的问题是，使用服务端代理，让我的服务器上的各种使用http协议访问的应用能够使用，但是现在我的ss在服务端莫名其妙不能用了，但是我的ss账号在windows可以用，我现在没法找到原因，折腾了一下午。。。

**Comment by pospospos2007** [comment]
心累

**Comment by pospospos2007** [comment]
特别无助，完全不知道怎么办。。。

**Comment by steve-jokes** [comment]
解决了吗

**Comment by pospospos2007** [comment]
不弄了，服务器到期了，换新服务器玩

**Comment by guliujian** [comment]
排查问题就不要放后台跑啊，直接放前台看日志。
