### ISSUE TITLE
Something was wrong while I using the toolchains of android to complete.

### ISSUE THREAD

**Issue by xseven007** [shadowsocks/shadowsocks-libev#439]
ev_select.c:259:23: error: expected ';' before 'mask'
               fd_mask mask = 1UL << bit;
                       ^
ev_select.c:262:34: error: 'mask' undeclared (first use in this function)
               events |= word_r & mask ? EV_READ  : 0;
                                  ^
Makefile:325: recipe for target 'ev.lo' failed
make[2]: *** [ev.lo] Error 1
make[2]: Leaving directory '/opt/shadowsocks-libev/libev'
Makefile:488: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/opt/shadowsocks-libev'
Makefile:310: recipe for target 'all' failed
make: *** [all] Error 2

##  "./configure --host=arm-linux-androideabi  CC=arm-linux-androideabi-gcc LD=arm-linux-androideabi-ld --with-openssl=/opt/openssl-1.0.2d/.openssl"

**Comment by madeye** [comment]
You need to debug this yourself. It's not an issue of shadowsocks-libev.
