### ISSUE TITLE
Sometimes it can not load css/js or other things in website

### ISSUE THREAD

**Issue by shixy91** [shadowsocks/shadowsocks-libev#440]
Hi, Thank you so much for your contribution!
With following your instruction, I tried to install this on both my bandwagonhost and digitalocean vps, I used to use the python version before, it showed no problem, but with this C version somtimes it can not load websites' css/js or some images, I looked for the problems in chrome F12, it shows 500 server internal error. When I refresh the pages it showed no improvement.
My vps system is centos 6 x64, and when I recovered my snapshot(python-version) in digitalocean this nearly never happens(in my memory it happened only 2 time, and when I refreshed the pages it is fine).
I start this ss-server like this:
nohup /usr/local/bin/ss-server -c /etc/ss-libev.json -u
The json file is the same as my python version.
And my ss-windows version is 2.5.6. My work system is win7 x64.
can you help me find out what's wrong with this? Thank you so much!

**Comment by GangZhuo** [comment]
Windows 客户端的问题，升级到最新版就行了

**Comment by shixy91** [comment]
Solved, thank you much. @GangZhuo
