### ISSUE TITLE
Found 1 bug.

### ISSUE THREAD

**Issue by shao222** [shadowsocks/shadowsocks-libev#442]
root@install:/home/shao# dpkg -i shadowsocks-libev_2.4.0-1_amd64.deb
(Reading database ... 31066 files and directories currently installed.)
Preparing to replace shadowsocks-libev 2.4.0-1 (using shadowsocks-libev_2.4.0-1_amd64.deb) ...
Unpacking replacement shadowsocks-libev ...
Setting up shadowsocks-libev (2.4.0-1) ...
Processing triggers for man-db ...

root@install:/home/shao# ss-server -v

**shadowsocks-libev 2.3.3**

**Comment by madeye** [comment]
`which ss-server`

**Comment by shao222** [comment]
apt-get download shadowsocks-libev 

Debian wheezy.

**Comment by madeye** [comment]
Fixed via https://github.com/shadowsocks/shadowsocks-org/commit/c38b7c7b646e5087d76aa6a9a25b5164510bbe5e
