### ISSUE TITLE
`ss-manager` -A support 

### ISSUE THREAD

**Issue by 7KjN3mHq** [shadowsocks/shadowsocks-libev#444]
Thanks for your developing. One time password is really cool. But here is an issue i found.
I tried 
with option --executable /usr/bin/ss-server -A -u -v -c /etc/shadowsocks/config.json
but ss-server processes didn't using -A . my version is shadowsocks-libev 2.4.0
Please fix, Thanks.

**Comment by 7KjN3mHq** [comment]
fix looks like not works.
I cloned and `./configure && make;make install` with HEAD.

#### conmandline
ss-manager  --manager-address 127.0.0.1:8888 --executable /usr/local/bin/ss-server -A -u -v -c /etc/shadowsocks/config.json
INFO: cmd: /usr/local/bin/ss-server -p 443 -m rc4-md5 -k password --manager-address 127.0.0.1:8888 -f /root/.shadowsocks/.shadowsocks_443.pid -t 240 -v -u -u -s 0.0.0.0
INFO: cmd: /usr/local/bin/ss-server -p 444 -m rc4-md5 -k password --manager-address 127.0.0.1:8888 -f /root/.shadowsocks/.shadowsocks_444.pid -t 240 -v -u -u -s 0.0.0.0


#### configfile
{
  "server":"0.0.0.0",
  "port_password": {
      "443": "password",
      "444": "password"
  },
  "timeout":240,
  "method":"rc4-md5"
}

**Comment by fortuna** [comment]
I also think that this issue has not been fixed. I have config:
````
{
  "server":"0.0.0.0",
  "port_password": {
    "2000": "FooBar1",
    "2001": "FooBar2"
  },
  "method": "aes-256-cfb",
  "fast_open": true,
  "auth": true
}
````

And I get this manager output:
````
ss-manager --manager-address 127.0.0.1:3000 -u -vv -c config.json
 2017-01-23 06:30:44 INFO: using tcp fast open
 2017-01-23 06:30:44 INFO: cmd: ss-server -p 2000 -m aes-256-cfb -k FooBar1 --manager-address 127.0.0.1:3000 -f /root/.shadowsocks/.shadowsocks_2000.pid -t 60 -v -u -u --fast_open -s 0.0.0.0
 2017-01-23 06:30:44 INFO: cmd: ss-server -p 2001 -m aes-256-cfb -k FooBar2 --manager-address 127.0.0.1:3000 -f /root/.shadowsocks/.shadowsocks_2001.pid -t 60 -v -u -u --fast_open -s 0.0.0.0
````

There's no `-A` that. Also, notice the duplicate `-u`.
