### ISSUE TITLE
disable logging into syslog

### ISSUE THREAD

**Issue by iceberg1369** [shadowsocks/shadowsocks-libev#447]
shadowsocks-libev fills syslog log file very soon, is there anyway I could disable logging or reduce logging level which is getting written to syslog?

**Comment by madeye** [comment]
By default, only errors are written to syslog. Make sure you didn't enable verbose mode

**Comment by iceberg1369** [comment]
is there anyway we could disable error logging as well?

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks-libev/blob/master/src/utils.h#L134

Remove Line 135 to 138 and recompile.
