### ISSUE TITLE
Cannot install from repository

### ISSUE THREAD

**Issue by bigZ-again** [shadowsocks/shadowsocks-libev#450]
Please see below:
root@vps25573495:~# apt-get install shadowsocks-libev
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package shadowsocks-libev
root@vps25573495:~# cat /proc/version
Linux version 2.6.27 (Debian 2.6.26-29) (dannf@debian.org) (gcc version 4.1.3 20080704 (prerelease) (Debian 4.1.2-25)) #1 SMP Sun Mar 4 22:43:21 UTC 2012
root@vps25573495:~# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 6.0.10 (squeeze)
Release:        6.0.10
Codename:       squeeze

Why? thanks.

**Comment by madeye** [comment]
Read the README.

**Comment by bigZ-again** [comment]
I DO EVERYTHING in README.

And maybe cause by i686.  Please see:
root@vps25573495:~# uname -a
Linux vps25573495.vm.ramnoc.net 2.6.27 #1 SMP Sun Mar 4 22:43:21 UTC 2012 i686 GNU/Linux

I just find binary-i386/amd64 dist, maybe need a binary-i686 dist. I am not sure.

**Comment by bigZ-again** [comment]
root@vps25573495:~# cat /etc/apt/sources.list
deb http://ftp.de.debian.org/debian squeeze main
deb http://ftp.debian.org/debian squeeze main contrib non-free
deb http://security.debian.org squeeze/updates main contrib non-free
deb http://shadowsocks.org/debian squeeze main
root@vps25573495:~# apt-get update
Hit http://security.debian.org squeeze/updates Release.gpg
Ign http://security.debian.org/ squeeze/updates/contrib Translation-en
Ign http://security.debian.org/ squeeze/updates/contrib Translation-en_US
Ign http://security.debian.org/ squeeze/updates/main Translation-en
Ign http://security.debian.org/ squeeze/updates/main Translation-en_US
Ign http://security.debian.org/ squeeze/updates/non-free Translation-en
Ign http://security.debian.org/ squeeze/updates/non-free Translation-en_US
Hit http://shadowsocks.org squeeze Release.gpg
Ign http://shadowsocks.org/debian/ squeeze/main Translation-en
Hit http://security.debian.org squeeze/updates Release
Ign http://shadowsocks.org/debian/ squeeze/main Translation-en_US
Hit http://security.debian.org squeeze/updates/main i386 Packages
Hit http://ftp.de.debian.org squeeze Release.gpg
Ign http://ftp.de.debian.org/debian/ squeeze/main Translation-en
Ign http://ftp.de.debian.org/debian/ squeeze/main Translation-en_US
Hit http://shadowsocks.org squeeze Release
Get:1 http://ftp.debian.org squeeze Release.gpg [1,655 B]
Ign http://ftp.debian.org/debian/ squeeze/contrib Translation-en
Ign http://ftp.debian.org/debian/ squeeze/contrib Translation-en_US
Ign http://ftp.debian.org/debian/ squeeze/main Translation-en
Ign http://ftp.debian.org/debian/ squeeze/main Translation-en_US
Ign http://ftp.debian.org/debian/ squeeze/non-free Translation-en
Ign http://ftp.debian.org/debian/ squeeze/non-free Translation-en_US
Hit http://security.debian.org squeeze/updates/contrib i386 Packages
Hit http://security.debian.org squeeze/updates/non-free i386 Packages
Ign http://shadowsocks.org squeeze/main i386 Packages
Hit http://ftp.de.debian.org squeeze Release
Hit http://ftp.debian.org squeeze Release
Ign http://shadowsocks.org squeeze/main i386 Packages
Hit http://ftp.de.debian.org squeeze/main i386 Packages
Hit http://shadowsocks.org squeeze/main i386 Packages
Hit http://ftp.debian.org squeeze/main i386 Packages
Hit http://ftp.debian.org squeeze/contrib i386 Packages
Hit http://ftp.debian.org squeeze/non-free i386 Packages
Fetched 1,655 B in 0s (2,008 B/s)
Reading package lists... Done
root@vps25573495:~# apt-get install shadowsocks-libev
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package shadowsocks-libev
root@vps25573495:~#

**Comment by madeye** [comment]
Try to install from source code.

**Comment by bigZ-again** [comment]
Maybe caused by old version. How to clearly remove old package? thanks.

root@vps25573495:~# ps -ef | grep shadow
root       464   460  0 02:33 pts/0    00:00:00 grep shadow
root       698     1  0 Nov01 ?        00:00:47 /usr/bin/ss-server -c /etc/shadowsocks/config.json -a root -u -f /var/run/shadowsocks/shadowsocks.pid
root@vps25573495:~# /usr/bin/ss-server --help | head -5

shadowsocks-libev 1.4.6

  maintained by Max Lv <max.c.lv@gmail.com> and Linus Yang <laokongzi@gmail.com>

root@vps25573495:~# apt-cache search shadowsocks
shadowsocks - A lightweight secured scoks5 proxy.
root@vps25573495:~# apt-cache search shadowsocks-libev
shadowsocks - A lightweight secured scoks5 proxy.
root@vps25573495:~# apt-get install shadowsocks
Reading package lists... Done
Building dependency tree
Reading state information... Done
shadowsocks is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 9 not upgraded.
root@vps25573495:~# apt-cache showpkg shadowsocks-libev
N: Unable to locate package shadowsocks-libev
root@vps25573495:~# apt-cache showpkg shadowsocks
Package: shadowsocks
Versions:
1.4.6-1 (/var/lib/apt/lists/shadowsocks.org_debian_dists_squeeze_main_binary-i386_Packages) (/var/lib/dpkg/status)
 Description Language:
                 File: /var/lib/apt/lists/shadowsocks.org_debian_dists_squeeze_main_binary-i386_Packages
                  MD5: 44b72f6c7094a970e61ff177da42d4d8


Reverse Depends:
Dependencies:
1.4.6-1 - libc6 (2 2.9) libssl0.9.8 (2 0.9.8m-1)
Provides:
1.4.6-1 -
Reverse Provides:
root@vps25573495:~#
