### ISSUE TITLE
仓库中的二进制package未及时更新

### ISSUE THREAD

**Issue by bigZ-again** [shadowsocks/shadowsocks-libev#451]
只需要简单看一下 shadowsocks-org/debian/dists/squeeze/ 目录的更新时间就可以发现，仓库中二进制package的更新是乎有问题。
虽然代码的改动是频繁的，每次都去更新仓库可能有点麻烦，但至少2-3个月应该强制去更新一遍仓库，这是非常必须的。
从用户的角度看，服务器端的shadowsocks还是不好装，网上大量的烂七八糟的安装介绍，都不如官方文档给出的从仓库安装简单，但是如果官方的仓库不能保证提供最新的二进制下载包，那不又退化成了一个摆设吗？
如果不是真正的二次开发，不建议用户下载源代码，在本地生成二进制文件，一是完全没有必要，二是大部分人可能又会碰到一堆新的坑。
维护非常非常重要，虽然它可能很乏味，但要坚持好习惯。:)

**Comment by madeye** [comment]
Shadowsocks-libev drops the support of Debian squeeze since 1.4.6. Upgrade to wheezy or build the binraries from source code.
