### ISSUE TITLE
libev 版本打开有时候无法打开网站

### ISSUE THREAD

**Issue by Mattosx** [shadowsocks/shadowsocks-libev#456]
libev 有时候无法打开网站,需要重新刷新好几次. google 主页这点特别明显.换 python 版本端口就马上可以打开.

**Comment by hosiet** [comment]
这种 issue 如果想真正解决的话，建议自己在服务器端监控抓包，浏览器端同样监控看看瓶颈出在哪里，是 DNS 或是服务器 IPv4/v6 的问题，或是其他。至少描述清楚所使用的环境，包括服务器端、服务器环境、客户端环境、ss 版本浏览器情况等等，给出切实步骤使得问题有稳定的重现方式。

否则问题无法重现，只能被打上 cannot reproduce 或者 invalid 的标签。
