### ISSUE TITLE
Something might be wrong during ./configure && make 

### ISSUE THREAD

**Issue by shixy91** [shadowsocks/shadowsocks-libev#459]
Before commit 912, it's OK, every time I firstly use make uninstall, then use git clone to get the latest version and then ./configure && make, but this time something's wrong.
it said:
udns_resolver.c:137: error: expected identifier or '(' before '}' token
udns_resolver.c:155: error: array type has incomplete element type
udns_resolver.c:175: warning: declaration does not declare anything
udns_resolver.c:177: error: expected specifier-qualifier-list before 'static'
make[2]: *** [udns_resolver.lo] Error 1
make[2]: Leaving directory `/root/shadowsocks-libev/libudns'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/root/shadowsocks-libev'
make: *** [all] Error 2
I don't know if there's anything changed caused this happened?
My system is centos 6.7 x86 minimal, 
Thank you so much!

**Comment by shixy91** [comment]
And I'm sure that the commit "try to support solaris" is fine, because I had reinstalled my system this afternoon, and after that the installation is fine.

**Comment by madeye** [comment]
What's your system, compiler and version?
