### ISSUE TITLE
Optimize battery usage on Android

### ISSUE THREAD

**Issue by Mygod** [shadowsocks/shadowsocks-libev#460]
Right now the timer fires an event every second no matter what.

Maybe it should be paused when all the callbacks are removed/paused (this should happen when the screen goes off).

**Comment by madeye** [comment]
From my understanding, a timer based on epoll won't cause any visible battery usage.

Another option is that we only trigger the timer when packets sent/received.

**Comment by Mygod** [comment]
Android 6.0 has introduced a battery saving feature called [Doze](http://developer.android.com/training/monitoring-device-state/doze-standby.html). I suspect keep firing timer events will kill this feature and cause battery consumptions indirectly.

**Comment by fishg** [comment]
Can you add a statistical switch ?

**Comment by Mygod** [comment]
I think d462e4cd8d44d7275957afab9255b98e54bb2630 has fixed this? Should we close this now?

**Comment by madeye** [comment]
Right.
