### ISSUE TITLE
v2.4.2 missing

### ISSUE THREAD

**Issue by insanefelix** [shadowsocks/shadowsocks-libev#467]
--2015-12-01 12:52:53--  https://github.com/shadowsocks/shadowsocks-libev/archive/v2.4.2.tar.gz
Resolving github.com (github.com)... 192.30.252.130
Connecting to github.com (github.com)|192.30.252.130|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/shadowsocks/shadowsocks-libev/tar.gz/v2.4.2 [following]
--2015-12-01 12:52:54--  https://codeload.github.com/shadowsocks/shadowsocks-libev/tar.gz/v2.4.2
Resolving codeload.github.com (codeload.github.com)... 192.30.252.146
Connecting to codeload.github.com (codeload.github.com)|192.30.252.146|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-12-01 12:52:56 ERROR 404: Not Found.

Download failed.

**Comment by madeye** [comment]
Not released yet.

**Comment by heavyT3333** [comment]
Hi do you know when the release will be?  I am trying to compile with openwrt and is failing on v2.4.2.tar.gz. Can you revert github to v2.4.1 in the meantime? so i can finish the compile.  
Thankyou

**Comment by insanefelix** [comment]
you could try:
git clone -b v2.4.1 https://github.com/shadowsocks/shadowsocks-libev.git

**Comment by heavyT3333** [comment]
Thanks insane, it worked :)
