### ISSUE TITLE
Question and Suggestion about One-Time Auth

### ISSUE THREAD

**Issue by lixin9311** [shadowsocks/shadowsocks-libev#468]
I believe the **OTA** described in [shadowsocks.org](https://shadowsocks.org/en/spec/one-time-auth.html) is expected to solve the **CCA** problem or **CCS** (I think it should be a kind of **Sniffing** instead of **Attack** from cryptanalysis.), which has been aggressively discussed  in [shadowsocks-rss/issues/38](https://github.com/breakwa11/shadowsocks-rss/issues/38).

I think the idea is good, but some doubts came to me about the **TCP Request's Chunk Authentication** part.
```
An OTA-enabled TCP Request's Chunk Packet
+----------+-----------+----------+----
| DATA.LEN | HMAC-SHA1 |   DATA   | ...
+----------+-----------+----------+----
|     2    |     10    | Variable | ...
+----------+-----------+----------+----
```
>DATA.LEN is a 16-bit big-endian integer indicating the length of DATA.
>The input of HMAC-SHA1 is DATA. And the key of HMAC-SHA1 is (IV + Chunk ID) where Chunk ID is an unsigned integer counted per connection from 0. In order to achieve this, both server side and client side need to keep a counter for each TCP connection. Chunk ID must be converted to big-endian before constructing the key of HMAC-SHA1.

The current implement of OTA changes the processing of TCP stream, by splitting stream into packets and appending length along with checksum to the packet header. And a packet sequence number counter for each connection keeps counting it.

Some preliminary tests I have run show it can impact a HTTP download action by **5%**. Though the impact in this test is small enough to be ignore, but I don't know how it will affect other TCP stream applications, or tons of connections.

Moreover, I don't think adding a header and checksum to each packets split from the stream can be called ***One-Time* Auth**.

I believe the checksum in the TCP request handshake packet is fairly enough to make it sniffing-proof, and the OTA header in each TCP chunk packet is unnecessary.

I think the key idea of Shadowsocks is **Secure**, **Simple** and **Efficient**. So I suggest removing the OTA header from TCP chunk packet and keeping the TCP stream intact, making it really **One-Time**.

**Comment by madeye** [comment]
I suggest you to read the document more carefully.

1. OTA won't affect your HTTP download speed, as we only apply OTA for request only.
2. OTA is required for CCA, which has been discussed for years. For more details, please refer to this link: https://github.com/shadowsocks/shadowsocks-libev/issues/428
3. The issue you mentioned is quite misleading. Still, I recommend you to read all the documents more carefully to learn what OTA is and how it works.

**Comment by madeye** [comment]
@librehat It seems that the document on shadowsocks.org is a bit confusing, which describes the chunks are for TCP request (acctually requests of shadowsocks protocol). Let's refine it and make it more clear.

**Comment by madeye** [comment]
Also a typical CCA attack against TCP payload from @clowwindy:

> Even if the header does not have a fixed length, if the data following the header is an HTTP or HTTPS request. Let’s take HTTP for example:

> GET /path

> If any of "GET " is changed, the client will receive a 400 response, most likely.

**Comment by lixin9311** [comment]
I've read your email.

You are talking about that, the firewall tries to emulate a client with recorded stream, then manipulate it to analyse the traffic.

According to an known [report](https://github.com/breakwa11/shadowsocks-rss/issues/38#issuecomment-138057405) the TCP request handshake packet is vulnerable by manipulating ATYP. But no attack on payload has been reported so far.

Adding CRC or HMAC-SHA1 check for payload can indeed improve security. But I think it is an unnecessary worry, because the attack cost is too high. But I seem to be convinced finally.

**Comment by librehat** [comment]
My laptop is broken, I'll update the doc when my new one arrives.
