### ISSUE TITLE
udprelay broken in 2.4.2

### ISSUE THREAD

**Issue by sadoneli** [shadowsocks/shadowsocks-libev#474]
![image](https://cloud.githubusercontent.com/assets/10495520/11681385/a41afa0e-9e99-11e5-8a2e-2b912f38e503.png)
Compiled using latest code (client and server), the udp is blocked when using TPROXY to redirect the udp traffic.

![image](https://cloud.githubusercontent.com/assets/10495520/11681420/d0a8ce48-9e99-11e5-9ae0-b841f9bca24d.png)
When using 2.4.1 , everything worked fine.

**Comment by madeye** [comment]
1. What's your configuration? Encryption method? Authentication? 
2. Any log of ss-redir?

**Comment by madeye** [comment]
Let's try 1164dc2

**Comment by sadoneli** [comment]
@madeye
![image](https://cloud.githubusercontent.com/assets/10495520/11683850/8532d210-9ea8-11e5-9fc2-ef49cd69f3a2.png)
 https://github.com/shadowsocks/shadowsocks-libev/commit/1164dc28cae8ea9d1f024c568b88afedb95825db worrks fine！
