### ISSUE TITLE
The ss-local ignore the .json's "local" segment, instead "127.0.0.1'

### ISSUE THREAD

**Issue by originalw** [shadowsocks/shadowsocks-libev#476]
On my dd-wrt router,i had to force it by -b in command line

**Comment by madeye** [comment]
`local_address`

**Comment by originalw** [comment]
Yes,it work.thanks,
But at this issue https://github.com/shadowsocks/shadowsocks-libev/issues/252 ,the right answer is "local"
And the guide with "local" all over internet,could you annouce it in readme.md?

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks/wiki/Configuration-via-Config-File
