### ISSUE TITLE
How do I use ss to tunnel all udp traffics?

### ISSUE THREAD

**Issue by Jermin** [shadowsocks/shadowsocks-libev#478]
Hey guys,

I've spent an entire day on trying to get this work. I used to use shadowvpn for openwrt to play games on my PC, and it worked out quite well. However, I flashed another firmware which have nwan and pppoeup integrated a few weeks ago.

nwan creates several virtual wans and pppoeup uses them to dial simultaneously. Now I have tripled my bandwidth. However, when I tried to play games using shadowvpn, the internet access was lost as soon as I enabled shadowvpn in luci. It seems that the iptables rules of shadowvpn are not compatible with those virtual wans. However, I failed to find a solution yet. :(

Then I recalled that I once had seen that ss could tunnel udp traffics. So I started googling once again.

I used luci to configue ss and chinadns to browse websites and watch youtube etc. I've never tinkered with ss-dir or ss-tunnel command before.

From what I know, it seems that I need to use ss-dir and tproxy to make shadowsocks tunnel udp traffics.

I tried to view the wiki page, but it redirected me to the homepage.

Can anyone shed some light on this? Any help will be greatly appreciated..

Best Regards,
Jermin

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks-libev#advanced-usage
