### ISSUE TITLE
ss-redir missing

### ISSUE THREAD

**Issue by xiaofami** [shadowsocks/shadowsocks-libev#480]
After compiling and installation,I only found `ss-local`,`ss-manager`,`ss-server` and `ss-tunnel` under `/usr/local/bin` .Need `ss-redir` for my devices in local network.

BTW,the tutorial for FreeBSD needs a little modification.You are supposed to run `./configure`,`./make` and `./make install` in a row.`make install` only does not work as intended.

**Comment by madeye** [comment]
`ss-redir` only supports Linux.

**Comment by xiaofami** [comment]
Is there any hope to port `ss-redir` to FreeBSD? My NAS runs FreeNAS so it would be really nice if it has `ss-redir`.
