### ISSUE TITLE
Shadowsocks_libev on FreeBSD can not use

### ISSUE THREAD

**Issue by hazdzz** [shadowsocks/shadowsocks-libev#482]
HELP! When I start shadows_libev on my FreeBSD server, it shows "ERROR: 7:15: Unknown value
/usr/local/etc/rc.d/shadowsocks_libev: WARNING: failed to start shadowsocks_libev". What should I do ?

FreeBSD 10.1-RELEASE

/etc/rc.conf :
#RECOMMENDED
shadowsocks_libev_enable="YES"
shadowsocks_libev_flags="-c /usr/local/etc/shadowsocks-libev/config.json"

/usr/local/etc/shadowsocks-libev : 
"server":"my_server_IPv4",
"server_port":8388,
"local_port":1080,
"password":"password",
"timeout":600,
"method":table

/usr/local/etc/rc.d/shadowsocks_libev:
. /etc/rc.subr

name="shadowsocks_libev"
rcvar=shadowsocks_libev_enable

load_rc_config $name

: ${shadowsocks_libev_enable:="YES"}
: ${shadowsocks_libev_config="/usr/local/etc/shadowsocks-libev/config.json"}

command="/usr/local/bin/ss-server"
pidfile="/var/run/shadowsocks-libev.pid"
required_files="${shadowsocks_libev_config}"

command_args="-f $pidfile -c $shadowsocks_libev_config"

run_rc_command "$1"

**Comment by madeye** [comment]
Check Column 15 of Line 7 of your config.json

`ERROR: 7:15: Unknown value`

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks/wiki/Configuration-via-Config-File

**Comment by hazdzz** [comment]
Still error
