### ISSUE TITLE
服务器端口配置错误，如何让ss-local退出

### ISSUE THREAD

**Issue by alfal** [shadowsocks/shadowsocks-libev#483]
ss-local启动后，它就一直在运行，当我关闭服务端的ss-server进程后，客户端的ss-local还在运行
我应该如何设置让ss-local自己退出？或者我应该如何改相关的代码？

**Comment by kxmp** [comment]
pkill ss-local

**Comment by alfal** [comment]
但是如何在客户端判断服务器端口末打开？

**Comment by smartepsh** [comment]
@alfal 你没必要关闭客户端的ss-local，抛开资源占用因素，除非你使用socks5代理的程序会自动检测端口关闭并切换至本地网络或其他代理。
