### ISSUE TITLE
tproxy + ss-redir 的在Linux路由器没有配置成功，请指导具体操作事项

### ISSUE THREAD

**Issue by shifengjiang** [shadowsocks/shadowsocks-libev#488]
我一年多来使用自己搭建的 shadowsocks-libev + ChinaDNS 的Debian 7.x 路由器，没有遇到什么问题，其间记不清何时将shadowsocks-libev 升级到2.0.1。 
最近决定转换到另一台Debian 8.2的机器，并使用最新版的 shadowsocks-libev 2.4.3，为了先看看是否可用，仅仅使用了经过验证的config.json配置文件和官方的如下推荐命令：

sudo iptables -t nat -A SHADOWSOCKS -d IP_of_my_remote_server -j RETURN

sudo iptables -t nat -A SHADOWSOCKS -d 0.0.0.0/8 -j RETURN
sudo iptables -t nat -A SHADOWSOCKS -d 10.0.0.0/8 -j RETURN
sudo iptables -t nat -A SHADOWSOCKS -d 127.0.0.0/8 -j RETURN
sudo iptables -t nat -A SHADOWSOCKS -d 169.254.0.0/16 -j RETURN
sudo iptables -t nat -A SHADOWSOCKS -d 172.16.0.0/12 -j RETURN
sudo iptables -t nat -A SHADOWSOCKS -d 192.168.0.0/16 -j RETURN
sudo iptables -t nat -A SHADOWSOCKS -d 224.0.0.0/4 -j RETURN
sudo iptables -t nat -A SHADOWSOCKS -d 240.0.0.0/4 -j RETURN

sudo iptables -t nat -A SHADOWSOCKS -p tcp -j REDIRECT --to-ports 1080

sudo ip rule add fwmark 0x01/0x01 table 100
sudo ip route add local 0.0.0.0/0 dev lo table 100
sudo iptables -t mangle -A SHADOWSOCKS -p udp --dport 53 -j TPROXY --on-port 1080 --tproxy-mark 0x01/0x01

sudo iptables -t nat -A PREROUTING -p tcp -j SHADOWSOCKS
sudo iptables -t mangle -A PREROUTING -j SHADOWSOCKS

自己先注意到ss-redir缺省监听端口新版本发现变化，后来经人点拨使用
sudo ss-redir -b 192.168.1.1 -u -c /etc/shadowsocks-libev/config.json -f /var/run/shadowsocks.pid 
或者
sudo ss-redir -b 0.0.0.0 -u -c /etc/shadowsocks-libev/config.json -f /var/run/shadowsocks.pid 

TCP转发都可以。

但UDP的转发始终没有成功。用了下面这组拷贝的命令后无论dnsmasq还是chinaDNS在53口监听的解析功能都会完全丧失:
sudo iptables -t mangle -N SHADOWSOCKS
sudo ip rule add fwmark 0x01/0x01 table 100
sudo ip route add local 0.0.0.0/0 dev lo table 100
sudo iptables -t mangle -A SHADOWSOCKS -p udp --dport 53 -j TPROXY --on-port 1080 --tproxy-mark 0x01/0x01
sudo iptables -t mangle -A PREROUTING -j SHADOWSOCKS

在局域网内一台机器遇到如下错误：
$ dig www.sina.com @192.168.1.1

 ; <<>> DiG 9.10-P2 <<>> www.sina.com @192.168.10.1
 ;; global options: +cmd
 ;; connection timed out; no servers could be reached
请问这个tproxy在普通linux发行版上有什么特别需要注意的地方吗？

**Comment by smartepsh** [comment]
dns转发请使用ss-tunnel

**Comment by madeye** [comment]
You have to debug this yourself or use solutions like openwrt-shadowsocks.
