### ISSUE TITLE
ss-redir 不可以转发到另一台机器上？

### ISSUE THREAD

**Issue by everpcpc** [shadowsocks/shadowsocks-libev#492]
我有4台机器，机器 A 是网关；机器 B 指定了 A 作为网关，日常使用；机器 C 上面跑了 ss-redir；机器 D 是 linode，上面跑了 ss-server。
其中 B 只有 lan，AC有 wan 和 lan。三台机器的 lan 都在同一个 二层里。

首先尝试在网关 A 本机上跑 ss-redir，然后使用 redirect --to-port $port，机器 B 可以通过 B->A->D 的路径正常上网。

然后尝试 使用机器 C 上的 ss-redir，在网关 A 上使用 DNAT --to-destination 机器C:$port。那么当前包的路径应该是 B->A->C->D。
在 ABCD上 tcpdump 抓包，能看到已经建立了 tcp 连接， D 上收到了请求并且 B 也收到了回包。但是紧接着 B 发出 tls hello 之后，就没有包的来往了。 D 的 443 端口也没有反应，也就是说 ss-server 收到了请求却没有将请求转发出去。这个有可能是什么原因呢？

**Comment by madeye** [comment]
You cannot do that. ss-redir needs to run on the gateway to get the dest address from kernel.
