### ISSUE TITLE
To support multiple cores and threads for maxim performance.

### ISSUE THREAD

**Issue by hero18688** [shadowsocks/shadowsocks-libev#493]
It is running on the WITI board which is based on MT7621AT with 2 cores 4 threads integrated.But ss-libev can't only use one thread.
![ss](https://cloud.githubusercontent.com/assets/5336956/11996550/20474bd4-aaa0-11e5-81ed-4c620ee45808.jpg)

**Comment by madeye** [comment]
It's quite simple to enable multiple working processes like this:

```
ss-redir -c config.json -u -f /tmp/pid1
ss-redir -c config.json -u -f /tmp/pid2
...
```

Then you will get several ss-redir processes working on the same port.

This feature require the change e921f40 and Linux kernel > 3.9.

BTW, it could even work like a load balancer for different server configs.
