### ISSUE TITLE
link failed while using ming-w64 to cross compile on linux

### ISSUE THREAD

**Issue by kery** [shadowsocks/shadowsocks-libev#503]
CCLD     ss-local.exe
../libcork/.libs/libcork.a(libcork_la-error.o): In function `cork_error__get':
/home/kery/code/shadowsocks-libev/libcork/core/error.c:79: undefined reference to `_pthread_getspecific'
../libcork/.libs/libcork.a(libcork_la-error.o): In function `cork_error___create_key':
/home/kery/code/shadowsocks-libev/libcork/core/error.c:79: undefined reference to `_pthread_key_create'
../libcork/.libs/libcork.a(libcork_la-error.o): In function `cork_error__get':
/home/kery/code/shadowsocks-libev/libcork/core/error.c:79: undefined reference to `_pthread_setspecific'

workaround:
add -lpthread to libcork/Makefile and recompile libcork

**Comment by madeye** [comment]
Cannot reproduce. Try to update your mingw.
