### ISSUE TITLE
Add whitelist for OTA feature?

### ISSUE THREAD

**Issue by dheminsgi** [shadowsocks/shadowsocks-libev#506]
When I started a virtual Linux machine on my MacBook, the SS server refused to shake hand with my laptop? I guess it's because both the Mac OS and the Linux tried to reach out my SS server, which was considered as multi-time authentication.

 I was wondering if it is possible to add a **white-list** feature for OTA, so my IP can be ignored as other attempts will be banned?

**Comment by madeye** [comment]
Double check your config on your laptop.
