### ISSUE TITLE
chacha20和chacha20-ietf这两种加密方式有什么区别？

### ISSUE THREAD

**Issue by diaochaju** [shadowsocks/shadowsocks-libev#507]
哪种比较快 / 比较安全？

**Comment by wongsyrone** [comment]
使用方面并无区别，安全性相当。区别主要位于算法内部，有兴趣参考https://tools.ietf.org/html/rfc7539#section-2.3

**Comment by lsnmx** [comment]
@wongsyrone shadowsocks-libev 服务端还需要装libsodium吗？

**Comment by wongsyrone** [comment]
项目自带一个libsodium，如果开启了`--enable-system-shared-lib`则需要另装

**Comment by lsnmx** [comment]
@wongsyrone 意思是shadowsocks-libev 服务端现在可以直接使用chacha20和chacha20-ietf这两种加密方式？我看网上全说要装libsodium才行，小白啊，麻烦告之一下，谢谢！

**Comment by rampageX** [comment]
网上说的是 python 版

**Comment by susating** [comment]
原来如此。感谢

**Comment by ZenFX** [comment]
谷歌搜chacha20-ietf搜到这个问题了，我想问下既然安全性差不多，为什么官网把chacha20-ietf列在Not Recommended里，而把chacha20列在Deprecated里？
[https://shadowsocks.org/en/spec/cipher.html](url)

**Comment by pexcn** [comment]
好像是非 ietf 版本的加密方法 iv 长度不够 12 位

**Comment by ZenFX** [comment]
@pexcn 找到了讨论的地方
https://github.com/shadowsocks/shadowsocks-org/issues/36

**Comment by cevin** [comment]
@mxlife  只是不推荐非ietf

**Comment by zckevin** [comment]
> The original ChaCha20 cipher with a 64-bit nonce and a 64-bit counter,
> allowing a practically unlimited amount of data to be encrypted with the same
> (key, nonce) pair.
> 
> The IETF variant increases the nonce size to 96 bits, but reduces the counter
> size down to 32 bits, allowing only up to 256 GB of data to be safely
> encrypted with a given (key, nonce) pair.

https://libsodium.gitbook.io/doc/advanced/stream_ciphers/chacha20
