### ISSUE TITLE
using upstream shadowsocks proxy by rules

### ISSUE THREAD

**Issue by frankxu2004** [shadowsocks/shadowsocks-libev#511]
Is it possible for a ss-server to use upstream shadowsocks as proxy, while routing some traffic to local while others to upstream shadosocks proxy. There are cases that a server inside GFW while another server outside GFW. I know that I could use iptables to simply redirect the packets, but how to implement the auto-routing feature?

**Comment by madeye** [comment]
Try https://github.com/cyfdecyf/cow

**Comment by ikesler** [comment]
If someone comes accross this issue - I had the same need and implemented simple upstream proxy support without additional software in [my fork](https://github.com/ikesler/go-shadowsocks2).

**Comment by miftachuda** [comment]
> If someone comes accross this issue - I had the same need and implemented simple upstream proxy support without additional software in [my fork](https://github.com/ikesler/go-shadowsocks2).

is this work for the client version too

**Comment by ikesler** [comment]
> > If someone comes accross this issue - I had the same need and implemented simple upstream proxy support without additional software in [my fork](https://github.com/ikesler/go-shadowsocks2).
> 
> is this work for the client version too

No, my solution is server-side only

**Comment by mfat** [comment]
> If someone comes accross this issue - I had the same need and implemented simple upstream proxy support without additional software in [my fork](https://github.com/ikesler/go-shadowsocks2).

@ikesler i need to set simple socks5 (not shadowsocks) as upstream proxy
