### ISSUE TITLE
服务器端查询状态会出一些奇怪问题

### ISSUE THREAD

**Issue by sergio13848** [shadowsocks/shadowsocks-libev#512]
可否询问一个问题还望解答下，谢谢。
查询服务器端状态会输出如下字样：
invalid password or cipher 
failed to handshake with xx 
但是链接正常，网上也查了下问题，没找到个确切的解答方案。

**Comment by madeye** [comment]
Just ignore them.

**Comment by kn007** [comment]
Same problem with shadowsocks-libev 2.4.4 and shadowsocks-win 2.5.2.

**Comment by kn007** [comment]
using shadowsocks-win 2.5.8 will return:
server recv: Connection reset by peer
