### ISSUE TITLE
shadowsocks-windows can't use it due to “unable to resolve”

### ISSUE THREAD

**Issue by simonsmh** [shadowsocks/shadowsocks-libev#520]
ss-server report "unable to resolve.".
This is appeared in shadowsocks-windows. The openwrt-shadowsocks and shadowsocks-android works great.
I tried the nameserver setting in ss-server, and I found it make the speed droped a lot.
I remember this didn't appear in the past. 
Any ideas? Thx.

**Comment by simonsmh** [comment]
ss-server built on conoha vps
ss-windows on windows 10 th2 release with firewall open

PS: I think ss-server should do sth to fix the "unable to resolve." issue, like dns udp forward in normal setting. Thx

**Comment by shixy91** [comment]
My ss-win didn't work very well either, finally I switched to ss-qt5, my vps is centos6 x64.

**Comment by simonsmh** [comment]
@shixy91 Its not a good solution, either.

**Comment by simonsmh** [comment]
I found this beta version of ss-win.
https://ci.appveyor.com/project/icylogic/shadowsocks-windows-l9mwe/build/job/04uysq3xeh55ff47/artifacts
This beta works great.
Problem solved.
@shixy91 You may need it.

**Comment by shixy91** [comment]
@simonsmh Thank you! :)
