### ISSUE TITLE
Out of memory 错误

### ISSUE THREAD

**Issue by Volftooth** [shadowsocks/shadowsocks-libev#530]
一般情况下浏览网页或者看下 y2b 什么的没有问题，但是只要用来连接更新 Android 的 SDK，服务器端 ss-server 100% 就会被杀掉，同时如果 SSH 有登录的话也一起被踢下线断开连接

dmesg 里面写 [12775.003213] Out of memory: Kill process 3766 (ss-server) score 1 or sacrifice child

期间有用 top 查看占用情况，发现只要一更新 Android 的 SDK，剩余内存真是秒减到 100MB 多，然后 SSH 就断开连接。同时 SDK Manager 也无法更新，ss-server 被干掉了

机器非常空，剩余内存 400MB 以上
这个到底是 bug 呢还是内存小了？
VPS 上没有开 swap

版本是：2.4.4

[12774.968282] ss-server invoked oom-killer: gfp_mask=0x201da, order=0, oom_adj=0, oom_score_adj=0
[12774.968944] ss-server cpuset=/ mems_allowed=0
[12774.969213] Pid: 3766, comm: ss-server Tainted: P           O 3.2.0-4-686-pae #1 Debian 3.2.54-2
[12774.999506] [ 3766]     0  3766     1217      127   0       0             0 ss-server
[12775.003213] Out of memory: Kill process 3766 (ss-server) score 1 or sacrifice child
[12775.003703] Killed process 3766 (ss-server) total-vm:4868kB, anon-rss:508kB, file-rss:0kB

**Comment by madeye** [comment]
1. Which version of shadowsocks-libev?
2. Which crypto are you using?

**Comment by madeye** [comment]
Also submit your config and command lines.

**Comment by madeye** [comment]
```
[12775.003703] Killed process 3766 (ss-server) total-vm:4868kB, anon-rss:508kB, file-rss:0kB
```

According to this log, when killed by oom-killer, the total memory used by `ss-server` (including VM) is only 4.8MB.

**Comment by Volftooth** [comment]
1.version: 2.4.4
2.aes-256-cfb

config file
`{
    "server":"xx.xx.xx.xx",
    "server_port":23,
    "local_port":1080,
    "password":"password",
    "timeout":60,
    "method":"aes-256-cfb"
}
`
command line:
/etc/init.d/shadowsocks-libev start      or
ss-server -c /etc/shadowsocks-libev/config.json -u -v > /var/log/sslog 2>&1 &

**Comment by madeye** [comment]
I suggest you contact your service provider. It seems an issue of the hypervisor of your node.

**Comment by Volftooth** [comment]
```
Active / Total Objects (% used)    : 523588 / 535173 (97.8%)
Active / Total Slabs (% used)      : 108490 / 108496 (100.0%)
Active / Total Caches (% used)     : 98 / 173 (56.6%)
Active / Total Size (% used)       : 429947.61K / 431366.59K (99.7%)
Minimum / Average / Maximum Object : 0.01K / 0.81K / 4096.00K

  OBJS ACTIVE  USE OBJ SIZE  SLABS OBJ/SLAB CACHE SIZE NAME
186364 186364 100%    2.00K  93182        2    372728K size-2048
196020 196020 100%    0.19K   9801       20     39204K skbuff_head_cache
  7072   7072 100%    1.00K   1768        4      7072K size-1024
 96996  96996 100%    0.06K   1644       59      6576K size-64
  3192   2618  82%    0.57K    456        7      1824K ext4_inode_cache
```

I finally found what caused memory consume, but I dont know why 'size-2048' use so much memory.
That happened when I upgrade Android SDK(Android SDK Manager) via shadowsocks-libev, other things(browse webpage etc) via shadowsocks-libev works normally.
