### ISSUE TITLE
gevent

### ISSUE THREAD

**Issue by VampireSH** [shadowsocks/shadowsocks-libev#537]
我看到有一些文章说安装这个可以优化shadowsocks，但是他们的文章都是使用Python版的，我想问一下对于我们的libev版有没有优化作用

**Comment by madeye** [comment]
Nope.

**Comment by mengskysama** [comment]
安装gevent并不能提高任何版本的shadowsocks性能，这里澄清一下。

**Comment by 70599** [comment]
那为什么会流行起这样的传说呢

**Comment by hosiet** [comment]
shadowsocks/shadowsocks#102
https://pypi.python.org/pypi/shadowsocks/1.4.3
