### ISSUE TITLE
windows下哪个客户端支持一次性验证

### ISSUE THREAD

**Issue by VampireSH** [shadowsocks/shadowsocks-libev#539]
请问有没有哪个版本的windows客户端支持一次性验证

**Comment by SuperHentai** [comment]
https://github.com/shadowsocks/shadowsocks-windows

**Comment by VampireSH** [comment]
这个的早就清了代码了吧，我想要的是可以在windows开启一次性验证的客户端

**Comment by pexcn** [comment]
https://github.com/shadowsocks/shadowsocks-windows/tree/master
