### ISSUE TITLE
Is shadowsocks-win or Shadowsocks-Qt5 Windows software compatible?

### ISSUE THREAD

**Issue by slrslr** [shadowsocks/shadowsocks-libev#540]
Hello,

i wanted to ask if the Windows client software mentioned at https://shadowsocks.org/en/download/clients.html is compatible with shadowsocks-libev?

Im asking because im facing issue described [there](https://github.com/shadowsocks/shadowsocks-qt5/issues/266)

Thank You

**Comment by madeye** [comment]
Yes, they are compatible.
