### ISSUE TITLE
[Windows-x86] build error: Can not find pthreads. This is required.

### ISSUE THREAD

**Issue by alexyangjie** [shadowsocks/shadowsocks-libev#541]
I tried to build the shadowsocks-libev v2.4.5 today on Windows x86 using mingw32. pthread library was installed using the mingw-get.exe. I encountered the following errors during the ./configure stage.

checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.exe
checking for suffix of executables... .exe
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking for a BSD-compatible install... /bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking for style of include used by make... GNU
checking whether make supports nested variables... yes
checking dependency style of gcc... gcc3
checking for ar... ar
checking the archiver (ar) interface... ar
checking whether make supports nested variables... (cached) yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking build system type... i686-pc-mingw32
checking host system type... i686-pc-mingw32
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for fgrep... /bin/grep -F
checking for ld used by gcc... c:/mingw/mingw32/bin/ld.exe
checking if the linker (c:/mingw/mingw32/bin/ld.exe) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /bin/nm -B
checking the name lister (/bin/nm -B) interface... BSD nm
checking whether ln -s works... no, using cp -pR
checking the maximum length of command line arguments... 8192
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert i686-pc-mingw32 file names to i686-pc-mingw32 format... func_convert_file_msys_to_w32
checking how to convert i686-pc-mingw32 file names to toolchain format... func_convert_file_msys_to_w32
checking for c:/mingw/mingw32/bin/ld.exe option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... file_magic ^x86 archive import|^x86 DLL
checking for dlltool... dlltool
checking how to associate runtime and link libraries... func_cygming_dll_for_implib
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for mt... no
checking if : is a manifest tool... no
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -DDLL_EXPORT -DPIC
checking if gcc PIC flag -DDLL_EXPORT -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (c:/mingw/mingw32/bin/ld.exe) supports shared libraries... yes
checking dynamic linker characteristics... Win32 ld.exe
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... no
checking whether to build static libraries... yes
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking whether ln -s works... no, using cp -pR
checking whether make sets $(MAKE)... (cached) yes
checking sys/inotify.h usability... no
checking sys/inotify.h presence... no
checking for sys/inotify.h... no
checking sys/epoll.h usability... no
checking sys/epoll.h presence... no
checking for sys/epoll.h... no
checking sys/event.h usability... no
checking sys/event.h presence... no
checking for sys/event.h... no
checking port.h usability... no
checking port.h presence... no
checking for port.h... no
checking poll.h usability... no
checking poll.h presence... no
checking for poll.h... no
checking sys/select.h usability... no
checking sys/select.h presence... no
checking for sys/select.h... no
checking sys/eventfd.h usability... no
checking sys/eventfd.h presence... no
checking for sys/eventfd.h... no
checking sys/signalfd.h usability... no
checking sys/signalfd.h presence... no
checking for sys/signalfd.h... no
checking for inotify_init... no
checking for epoll_ctl... no
checking for kqueue... no
checking for port_create... no
checking for poll... no
checking for select... no
checking for eventfd... no
checking for signalfd... no
checking for clock_gettime... no
checking for clock_gettime in -lrt... no
checking for clock_gettime... no
checking for nanosleep... yes
checking for library containing floor... none required
checking for thread local storage (TLS) class... __thread
checking for cipher_init_ctx in -lpolarssl... yes
checking polarssl version... ok
checking for C/C++ restrict keyword... __restrict
checking for netdb.h... no
checking for library containing inet_ntop... no
checking for inet_ntop... no
checking whether inet_ntop is declared... no
checking for what kind of host... MinGW
checking if compiler needs -Werror to reject unknown flags... no
checking for the pthreads library -lpthreads... no
checking whether pthreads work without any flags... no
checking whether pthreads work with -Kthread... no
checking whether pthreads work with -kthread... no
checking for the pthreads library -llthread... no
checking whether pthreads work with -pthread... no
checking whether pthreads work with -pthreads... no
checking whether pthreads work with -mthreads... no
checking for the pthreads library -lpthread... no
checking whether pthreads work with --thread-safe... no
checking whether pthreads work with -mt... no
checking for pthread-config... no
**configure: error: Can not find pthreads.  This is required.**

I also tried to build with openssl with the same error. All mingw32 components were just installed with latest version.

**Comment by madeye** [comment]
Try 32bit MingW-w64

**Comment by madeye** [comment]
Please refer to the following link for more details.
https://jenkins.shadowvpn.org/job/Shadowsocks-libev/cc=gcc,crypto=polarssl,host=i686-w64-mingw32,label=linux/155/console

**Comment by alexyangjie** [comment]
I still cannot build it. There are a couple of options in their download page. Which one should I use? I am currently using Win-builds installed to the MSYS. 

http://mingw-w64.org/doku.php/download

**Comment by hosiet** [comment]
Another convenient way is to build it under `mingw-w32/msys2` or `mingw-w64/msys2`. `ss-local` can be built without any problem as long as all dependencies are installed via `pacman`.

**Comment by alexyangjie** [comment]
Thanks @hosiet , I tried to build it in msys2 and it was a success. But when I run it in native cmd window, it says msys-2.0.dll is missing. I want it to be a independent executable without any dll dependency. Is that possible? Thanks.

**Comment by alexyangjie** [comment]
I tried to build it in MinGW-w64 Win32 Shell. ./configure stage passed. Make stage failed at the last bit...

  CC       ss_local-acl.o
  CC       ss_local-netutils.o
  CC       ss_local-local.o
  CC       ss_local-win32.o
  CCLD     ss-local.exe
Warning: resolving _select by linking to _select@20
Use --enable-stdcall-fixup to disable these warnings
Use --disable-stdcall-fixup to disable these fixups
`_select' referenced in section `.text' of C:/msys32/home/Admin/prebuilt/lib/libpolarssl.a(timing.o): defined in discarded section `.text' of C:/msys32/mingw32/bin/../lib/gcc/i686-w64-mingw32/5.3.0/../../../../i686-w64-mingw32/lib/../lib/libws2_32.a(diips00161.o)
collect2.exe: error: ld returned 1 exit status
Makefile:612: recipe for target 'ss-local.exe' failed
make[2]: *** [ss-local.exe] Error 1
make[2]: Leaving directory '/home/Admin/workspace/shadowsocks-libev/src'
Makefile:549: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/Admin/workspace/shadowsocks-libev'
Makefile:371: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by hosiet** [comment]
@alexyangjie 

Some solutions:
1. put corresponding dll together with the executable.
2. add the dll into `PATH`.
3. Use MINGW toolchain instead of msys2 toolchain. That is to say, install `mingw-w64-x86_64-*` or `mingw-w64-i686-*` libraries instead of the native libraries, and start msys2 with MinGW-w64 Win64/Win32 Shell instead of MSYS2 Shell.

**Comment by hosiet** [comment]
It is possible to use polarssl/openssl library from msys2 repo directly instead of manually specify the ssl library, which may solve the problem.

**Comment by alexyangjie** [comment]
Thank you @hosiet . 

Hi @madeye I can successfully build the ss-local.exe. But when I run it, the browser cannot connect. There is no error at the ss-local end, but in my ss-server log, below is the output. I turned on the one time authentication.

Feb 16 05:47:00 aspdrse1 ss-server: 2016-02-16 05:47:00 ERROR: failed to handshake with *.*.*.* (client IP hidden)
Feb 16 05:47:00 aspdrse1 ss-server: 2016-02-16 05:47:00 ERROR: authentication error from *.*.*.* (client IP hidden)
Feb 16 05:47:00 aspdrse1 ss-server: 2016-02-16 05:47:00 ERROR: authentication error from *.*.*.* (client IP hidden)

When I disable the one time authentication, there is no issue with connection.

**Comment by madeye** [comment]
1. I cannot reproduce your issue locally.  
2. Double check your config.
3. Make sure your are using the latest shadowsocks-libev on your server.

**Comment by madeye** [comment]
What do you mean by saying "disable one time auth"? Disable OTA on server or on client?

**Comment by alexyangjie** [comment]
When I enable OTA on both server and client, the client cannot connect to the server (windows client only. Another machine using OSX client is fine).

When I disable OTA on both server and client, the client can connect.

**Comment by alexyangjie** [comment]
I am pretty sure the config is OK. I just copied it from my OSX client, which is also using ss-local v2.4.5. 

The only difference is the platform. OSX works in OTA while Windows doesn't.

**Comment by madeye** [comment]
Please submit your config file here.

**Comment by alexyangjie** [comment]
client config.json
{
    "server":"aspdrse1.alexyang.me",
    "server_port":22,
    "local_address":"0.0.0.0",
    "local_port":8089,
    "password":"[hidden]",
    "timeout":600,
    "method":"chacha20"
}
command line: ss-local -A -c config.json

server config.json
{
    "server":"0.0.0.0",
    "server_port":22,
    "local_port":8089,
    "password":"[hidden]",
    "timeout":600,
    "method":"chacha20",
    "fast_open":true
}

command line: /usr/bin/ss-server -A -a root -c /etc/shadowsocks-libev/config.json -u

**Comment by alexyangjie** [comment]
Sorry @madeye , I forgot to close an old version of shadowsocks client...

No problem now. Thank you very much!
