### ISSUE TITLE
debian 8.2 x64 配置多用户后无法启动服务端

### ISSUE THREAD

**Issue by blackfoxsar** [shadowsocks/shadowsocks-libev#543]
shadowsocks-libev 2.4.0

ROOT账户直接启动，单端口/密码下没问题，多端口+多密码就会失败，log是：

shadowsocks-libev.service - Shadowsocks-libev Default Server Service
   Loaded: loaded (/lib/systemd/system/shadowsocks-libev.service; enabled)
   Active: failed (Result: exit-code) since Thu 2016-02-18 19:28:11 JST; 1s ago
  Process: 22778 ExecStart=/usr/bin/ss-server -a $USER -c $CONFFILE $DAEMON_ARGS (code=exited, status=1/FAILURE)
 Main PID: 22778 (code=exited, status=1/FAILURE)

Feb 18 19:28:11 jp-tokyo-conoha-1 ss-server[22778]: with Linux kernel > 3.7.0
Feb 18 19:28:11 jp-tokyo-conoha-1 ss-server[22778]: [--acl <acl_file>]         config file of ACL (Access Control List)
Feb 18 19:28:11 jp-tokyo-conoha-1 ss-server[22778]: only available in local and server mode
Feb 18 19:28:11 jp-tokyo-conoha-1 ss-server[22778]: [--manager-address <addr>] UNIX domain socket address
Feb 18 19:28:11 jp-tokyo-conoha-1 ss-server[22778]: only available in server and manager mode
Feb 18 19:28:11 jp-tokyo-conoha-1 ss-server[22778]: [--executable <path>]      path to the executable of ss-server
Feb 18 19:28:11 jp-tokyo-conoha-1 ss-server[22778]: only available in manager mode
Feb 18 19:28:11 jp-tokyo-conoha-1 ss-server[22778]: [-v]                       verbose mode
Feb 18 19:28:11 jp-tokyo-conoha-1 systemd[1]: shadowsocks-libev.service: main process exited, code=exited, status=1/FAILURE
Feb 18 19:28:11 jp-tokyo-conoha-1 systemd[1]: Unit shadowsocks-libev.service entered failed state.

config.json的内容如下：

{
    "server":"myip",
    "local_address":"127.0.0.1",
    "local_port":1080,
    "port_password":{
         "8000":"password1",
         "8001":"password2",
         "8002":"password3"
    },
    "timeout":120,
    "method":"aes-256-cfb",
    "fast_open": false
}

**Comment by madeye** [comment]
Not supported.
