### ISSUE TITLE
从国外翻回来的问题是否影响使用

### ISSUE THREAD

**Issue by xingezhang** [shadowsocks/shadowsocks-libev#546]
我在国内的阿里云上搭了一个服务端，我从国外的路由器客户端访问时，服务端显示getpeername: Transport endpoint is not connected，请问这是什么原因？是否影响使用？

**Comment by madeye** [comment]
It means some site cannot be reached. Nope.

**Comment by xingezhang** [comment]
意思是不影响使用，对吗？
