### ISSUE TITLE
Update ubuntu PPA

### ISSUE THREAD

**Issue by pjrobertson** [shadowsocks/shadowsocks-libev#548]
It looks like the packages on the [gh-pages](https://github.com/shadowsocks/shadowsocks-org/) site are somewhat outdated. It'd be great if they could be updated to the latest 2.4.5

Over the past few days I've started noticing slowdowns with shadowsocks so I'm not sure if an update to the GFW means it can now be detected...

**Comment by madeye** [comment]
Please build the package from source code.

**Comment by pjrobertson** [comment]
Does this mean the PPA is no longer supported? In which case the wiki should be updated to remove this, and the website should be as well

**Comment by madeye** [comment]
If you want a latest version, build the package from source code. The repository on shadowsocks.org is only updated occasionally with a stable version.
