### ISSUE TITLE
有时服务端发给客户端的包固定在260 byte长度

### ISSUE THREAD

**Issue by nightcoffee** [shadowsocks/shadowsocks-libev#550]
发现有时候下载文件会速度超慢或者根本没速度，服务端上抓包后发现服务端与remote连接是无碍的，也很快获得了remote的数据。
但是当server转发给local的时候不知道为什么会出现固定每次发260byte的包。

![qq 20160304231623](https://cloud.githubusercontent.com/assets/2611861/13531019/3d26f974-e25f-11e5-86ab-a5fd57033fea.png)

**Comment by madeye** [comment]
It's nothing to do with shadowsocks. Search MTU/MSS in Google.

**Comment by nightcoffee** [comment]
MTU限制的是IP包的大小，但这里是保持了每次发送的数据都是260 byte，如果第一次发送了258 byte，后面还会再补上2 byte的一次发送。
三次握手中也可以看到MSS协商结果是1260

**Comment by nightcoffee** [comment]
记录一下:
此问题是由锐速引起的，三次握手时锐速某些情况强制忽略了窗口扩大因子参数，导致Window size被限制在260

**Comment by cokebar** [comment]
@nightcoffee 我擦 用了这玩意儿还会给人降速？ 请问有什么方法避免么

**Comment by nightcoffee** [comment]
@cokebar 可能是偶尔出一次Bug，平时好好的……
