### ISSUE TITLE
manager API

### ISSUE THREAD

**Issue by iceberg1369** [shadowsocks/shadowsocks-libev#551]
Hi there
I invoked the ss-server manager api by this way.
ss-server -v --manager-address /var/run/shadowsocks-manager.sock -c /etc/shadowsocks/config.json

and then I used shadowsocks wiki python script to do some basic stuff.

import socket

cli = socket.socket(socket.AF_UNIX, socket.SOCK_DGRAM)
cli.bind('/tmp/client.sock')  # address of the client
cli.connect('/var/run/shadowsocks-manager.sock')  # address of Shadowsocks manager

cli.send(b'ping')
print(cli.recv(1506))  # You'll receive 'pong'

cli.send(b'add: {"server_port":8001, "password":"7cd308cc059"}')
print(cli.recv(1506))  # You'll receive 'ok'

cli.send(b'remove: {"server_port":8001}')
print(cli.recv(1506))  # You'll receive 'ok'

while True:
    print(cli.recv(1506))  # when data is transferred on Shadowsocks, you'll receive stat info every 10 seconds

but executing above script throws an error

root@debian:~# python test_manager.py
Traceback (most recent call last):
  File "test_manager.py", line 5, in <module>
    cli.bind('/tmp/client.sock')  # address of the client
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use

**Comment by madeye** [comment]
As it said, address already in use.

**Comment by madeye** [comment]
Try
```python
if os.path.exists( '/tmp/client.sock' ):
  os.remove( '/tmp/client.sock' )
```

**Comment by iceberg1369** [comment]
File "test_manager.py", line 9, in <module>
    cli.connect('/var/run/shadowsocks-manager.sock')  # address of Shadowsocks manager
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 2] No such file or directory

**Comment by iceberg1369** [comment]
even ss-server throws an error
ss-server -v --manager-address /var/run/shadowsocks-manager.sock -c /etc/shadowsocks/config.json

2016-03-04 02:06:55 INFO: initialize ciphers... salsa20
 2016-03-04 02:06:55 INFO: port reuse enabled
 2016-03-04 02:06:55 INFO: listening at 192.168.223.132:8888
 2016-03-04 02:07:25 ERROR: stat_sendto: No such file or directory
 2016-03-04 02:07:25 INFO: update traffic stat: tx: 0 rx: 0
 2016-03-04 02:07:25 ERROR: stat_sendto: No such file or directory

**Comment by madeye** [comment]
Make sure your have permission to create/write a file under ` /var/run`.

**Comment by iceberg1369** [comment]
I'm running under root user

**Comment by madeye** [comment]
You did wrong from the very beginning. `ss-manager` is the app to provide manager API, not `ss-server`.

**Comment by iceberg1369** [comment]
:| 
thank you
how many users I could add by manager API?
