### ISSUE TITLE
No incoming connections on P2P

### ISSUE THREAD

**Issue by slrslr** [shadowsocks/shadowsocks-libev#553]
Hello,

im using qbittorent set to use proxy created by shadowsocks client and shadowsocks-libev server.

It all working properly, except one thing, the torrent contents are downloaded, but not uploaded (seeded).

in qbittorent i set Port used for incoming connections: 19942

on the server side netstat|grep 19942 do not return any output

What i need to set on the shadowsocks-libev server so it start working? The server runs Linux CentOS 6.x and iptables with NAT is supported.

Thank you

**Comment by madeye** [comment]
I believe you cannot do that.

**Comment by slrslr** [comment]
What i canot do and why?
