### ISSUE TITLE
Block local access through shadosocks

### ISSUE THREAD

**Issue by ovizii** [shadowsocks/shadowsocks-libev#555]
I know this is a bit out of scope but could someone share a method to block access to the local network for clients connected through shadowsocks?

what I mean is that if I say run a VM inside my home network which runs shadowsocks and I want to give a friend access to shadowsocks to use as a proxy I am automatically giving him access to my home network.

Would it be possible to restrict access through shadowsocks to the internet only?

**Comment by madeye** [comment]
Use iptables.
