### ISSUE TITLE
Connection speed restricted (by GFW?) occasionally.

### ISSUE THREAD

**Issue by JunnanZ** [shadowsocks/shadowsocks-libev#557]
Hi guys, it seems that my shadowsocks connections occasionally experience speed restriction, about twice a day. 

I have two VPSs, one from Japan and the other from US, with shadowsocks-libev running on them. I'm using windows and android clients at the same time, both with OTA on. When there is a speed restriction, shadowsocks gets a really slow download speed (< 200KB/s), while normal connections are fine (6MB/s, which is my broadband speed.) The trick is, if I disconnect my home router from internet and reconnect, which will normally give it a new IP, the speeds of shadowsocks connections resume. Or if I change from one VPS to the other, speeds also resume. 

So I think maybe GFW has detected my ss connection with my VPS and throttled its speed. This may explain why the speed gets back to normal after I connect to the other VPS or change my IP. Are you experiencing the same problem? Is there any way to bypass this kind of detection? The OTA doesn't work here or my configuration is wrong? Thanks.

**Comment by madeye** [comment]
It's a typical QOS issue of your ISP,

**Comment by JunnanZ** [comment]
Thanks for your reply! Is there any way to do with QoS?
