### ISSUE TITLE
cannot use kqread on freebsd.

### ISSUE THREAD

**Issue by xpader** [shadowsocks/shadowsocks-libev#559]
Shadowsocks-libev on freebsd use select model, not kevent's kqread, looks like libev support this, can shadowsocks-libev support this ?

**Comment by xpader** [comment]
Actully all of the BSD based system support kqueue, like FreeBSD, OpenBSD, NetBSD and OSX.

**Comment by madeye** [comment]
Supported, but buggy or broken.
