### ISSUE TITLE
whitelist support

### ISSUE THREAD

**Issue by amphineko** [shadowsocks/shadowsocks-libev#560]
我正在一台 HAproxy 前端后使用 shadowsocks-libev 搭建服务器，然后前端服务器有时会接收到重放攻击，导致前端被 ss-server 加入黑名单。

I'm setting up shadowsocks-libev behind a HAproxy front-end, and the front-end server sometimes receives replay-attack, which causes she getting banned by ss-server.

**Comment by yousong** [comment]
跟haproxy配合的话，shadowsocks也可以考虑支持haproxy的proxy protocol

**Comment by amphineko** [comment]
@yousong 抱歉不太能明白你的意思

**Comment by yousong** [comment]
haproxy与ss-server建立连接之后，可以先进行PROXY protocol交互，把客户端的IP告知ss-server，这样ss-server就可以针对真实的客户端IP做处理了。相当于应用层的toa (tcp option address)
