### ISSUE TITLE
DNS round robin

### ISSUE THREAD

**Issue by nihaopaul** [shadowsocks/shadowsocks-libev#561]
When using hostnames with roundrobin addresses (multiple A records) only the first ip4 address is used and not re-queried or fallback to another address when unreachable.

**Comment by madeye** [comment]
Yes, it's an expected behavior.

**Comment by nihaopaul** [comment]
is the rational to prevent MITM attacks? i reported it as a bug since i have a server that keeps getting null-routed for an unspecific amount of time, i was hoping to fallover to several backup servers (cycle through them) until one reconnects instead of manually changing hosts.
