### ISSUE TITLE
Multi-account support?

### ISSUE THREAD

**Issue by zw963** [shadowsocks/shadowsocks-libev#563]
Current, I have to start two ss-server to support two account in difference port.

is there any config to support multi-account support ?

Thanks

**Comment by madeye** [comment]
Use two ss-local processes listening on the same port.

**Comment by madeye** [comment]
Nope.

**Comment by zw963** [comment]
请问是不是官方的 Windows 客户端也不支持连接到这个不版本的 ss-server ?

昨天一个朋友要用，折腾半天，3.0 无法启动，2.x 显示连接成功，但是无法上网.

**Comment by cokebar** [comment]
@zw963 try open two ss client on different port.

**Comment by zw963** [comment]
@cokebar ,  I make two config file, and start two ss-server, it worked.

Thanks.
