### ISSUE TITLE
Unbound w/ Shadowsocks 

### ISSUE THREAD

**Issue by williclarkam** [shadowsocks/shadowsocks-libev#566]
Hello, 

is there anyway to use unbound with Shadowsocks, my default dns resolver is my unbound service, but after I connect to Shadowsocks, it connect to 8.8.8.8 , it there any way to change the dns servers to point the domain resolving to my own unbound server?

Thanks

**Comment by madeye** [comment]
Use option `-d` to specify the resolver of `ss-server`.
