### ISSUE TITLE
Doesn't work with recommended configuration

### ISSUE THREAD

**Issue by windclimb** [shadowsocks/shadowsocks-libev#568]
Hello. I live in some Asian country (I can't tell which) and we have censorship.

I have installed Shadowsocks-libev to a blank server in Germany by instructions. Right now I'm in another european country, connection is very well. My friend from China tells that connection is well, too.
When I connect in my motherland it works 3-4 seconds only (500 Internal Privoxy error). But the Default server in Android client works. I think it is DPI. Maybe it's something with UDP? In my country UDP is blocked.

I also tried python version. Can somebody tell me how to configure my server like the Default server in Android client? Thank you very much.

P.S. Sorry for my English.

**Comment by madeye** [comment]
It has nothing to do with DPI. Double check your config.

**Comment by windclimb** [comment]
I installed exactly like in instruction on shadowsocks.org.

My shadowsocks.json:

{
    "server":"my_server_ip",
    "server_port":443,
    "local_address": "127.0.0.1",
    "local_port":1080,
    "password":"mypassword",
    "timeout":300,
    "method":"aes-256-cfb",
    "fast_open": false
}

It works everywhere but doesn't work in my country. Default server in Shadowsocks-Android works perfect.

**Comment by windclimb** [comment]
Please help :-(
Can you just show configs of the Default server in shadowsocks-android?

**Comment by madeye** [comment]
Double check the config of your client, not the server.

**Comment by panzhitian** [comment]
use a new port.
some isp blocks or filters special packets on 443.

**Comment by yeweishuai** [comment]
`{
"server":"my_server_ip",
"server_port":443,`

Here, change the `server_port` config to a number more than 1024 and see if it's ok. 
like:
`"server_port":7878,`
