### ISSUE TITLE
configure: error: Missing netfilter headers

### ISSUE THREAD

**Issue by dlan17** [shadowsocks/shadowsocks-libev#569]
this error  occur with latest linux-headers (kernel version 4.5), haven't checked old linux-headers

for detail info, please check downstream bug report at [1], and detail config.log is here[2] 
note: bug was reported against version 2.4.3, but still exist at version 2.4.5

[1] https://bugs.gentoo.org/show_bug.cgi?id=578206
[2] https://bugs.gentoo.org/attachment.cgi?id=428962

**Comment by madeye** [comment]
Tested with Linux 4.5 kernel on Ubuntu. No errors are observed.

It should be a downstream bug and required to be fixed by downstream maintainer.

**Comment by dlan17** [comment]
https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/F35B3R7LZMWIQNSEFX2AYC4TZYAG4CBP/

ok, it's a bug of glibc and >=linux-headers-4.5
