### ISSUE TITLE
how to use ss-redir?

### ISSUE THREAD

**Issue by asdyjd** [shadowsocks/shadowsocks-libev#570]
I have already used ss-server on server,and ss-local on my PC.
Now I want to try ss-redir.But I failed.
I replace the 123.123.123.123 with server's IP and 12345 to server's port.
iptables -t nat -A SHADOWSOCKS -d 123.123.123.123 -j RETURN
iptables -t nat -A SHADOWSOCKS -p tcp -j REDIRECT --to-ports 12345
iptables -t mangle -A SHADOWSOCKS -p udp --dport 53 -j TPROXY --on-port 12345 --tproxy-mark 0x01/0x01

But I didn't work.
How to do?

**Comment by madeye** [comment]
Follow the guide in README.md
