### ISSUE TITLE
Can I redirect ipv6 using ss-redir on OpenWRT router?

### ISSUE THREAD

**Issue by cokebar** [shadowsocks/shadowsocks-libev#571]
Situation is that both the server side & client side have IPv4/IPv6 dual stack network.
I want to redirect all foreign IPv6 data to ss-redir, just like aa65535's shadowsocks-libev-spec do on ipv4.
Is there any way to realize it?

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks-libev/pull/131

**Comment by cokebar** [comment]
So I know ss-redir support ipv6. But how to config with iptables? Using "ip6tables -t nat" just like iptables?

**Comment by madeye** [comment]
Right.
