### ISSUE TITLE
Client configuration: multiple servers

### ISSUE THREAD

**Issue by hydrandt** [shadowsocks/shadowsocks-libev#572]
Hi everyone,

I am trying to get a HA (highly available) client setup on OpenWRT, using shadowsocks-libev-spec. Configuring the client with multiple servers is not really documented, has been discussed here and there, but there is still no clear documentation.

I was not successful with specifying the servers in the json config like this:

<pre>
"server": ["1.1.1.1", "2.2.2.2"], 
</pre>

The only way I could start ss-redir to connect to multiple servers was:

<pre>
ss-redir -s 1.1.1.1 -s 2.2.2.2 -l 1080 -k secret.password -p 1234 -m aes-256-cfb -t 60 -b 0.0.0.0 -u -v
</pre>

How is this configuration supposed to behave?

From what I just tried, if the currently used server is 1.1.1.1 and I kill shadowsocks server there, the client immediately switches to 2.2.2.2. However, if I now start the server on 1.1.1.1 again, and kill it on 2.2.2.2, ss-redir writes "ERROR: getpeername: Transport endpoint is not connected" on stdout and stays this way. After I start the server on 2.2.2.2 again, connection is restored, and the 1.1.1.1 server is in use.

Is this the expected behavior?

Is it possible to specify multiple servers in the json config?

It would be great to have round-robin behavior here: If the current server stops responding, connect to next one, and when the last one stops responding, start again with the first one. What do you think?

Thank you so much for your great work. Shadowsocks makes life in China possible. I will be happy to contribute writing the documentation in English once I understand how it works.

**Comment by madeye** [comment]
Try HAProxy on local machine as a load balancer.

**Comment by madeye** [comment]
Also see https://github.com/shadowsocks/shadowsocks-libev/issues/493

**Comment by hydrandt** [comment]
Yes that's what I am configuring now. But, obviously it **is** possible to specify multiple servers. Could we please document how this behaves?
