### ISSUE TITLE
How to compile shadowsocks-libev on alpine linux

### ISSUE THREAD

**Issue by debiansid** [shadowsocks/shadowsocks-libev#583]
I want to switch my openwrt to alpine Linux,but have no idea how to make its alpine Linux package.

**Comment by madeye** [comment]
Nothing special. Refer to Alpine Linux's wiki pages for help.

**Comment by debiansid** [comment]
Question should be how to make its apk package on alpine Linux 

Error >>> shadowsocks-libev*: Running postcheck for shadowsocks-libev
>>> WARNING: shadowsocks-libev*: Found /usr/share/man but package name doesn't end with -doc
>>> ERROR: shadowsocks-libev*: Found uncompressed man pages:
        /usr/share/man/man1/ss-local.1
        /usr/share/man/man1/ss-manager.1
        /usr/share/man/man1/ss-redir.1
        /usr/share/man/man1/ss-tunnel.1
        /usr/share/man/man1/ss-server.1
        /usr/share/man/man8/shadowsocks-libev.8
>>> ERROR: shadowsocks-libev*: prepare_subpackages failed
>>> ERROR: shadowsocks-libev: all failed

**Comment by debiansid** [comment]
I managed to change abuild script on alpine which checking man page, now it works.

thanks
