### ISSUE TITLE
FreeBSD 下 rc.d 脚本需要改进

### ISSUE THREAD

**Issue by bao3** [shadowsocks/shadowsocks-libev#584]
我只是想使用 ss-local ，但是 rc.d 的脚本中 command 默认为 ss-server ，这导致我 service shadowsocks_libev start 无法启动，但是 ss-local -c 却可以。所以我手动修改了脚本，就可以启动了。我觉得是不是应该在 rc.conf 中增加一个 shadowsocks_libev_flags="local"  / “server” 的标记，方便 server 决定启动模式。

**Comment by madeye** [comment]
You'd better open a pull request instead.
