### ISSUE TITLE
Can't build the last git-version on windows 

### ISSUE THREAD

**Issue by xseven007** [shadowsocks/shadowsocks-libev#585]
CC       libshadowsocks_la-local.lo
local.c: In function 'server_recv_cb':
local.c:225:11: error: lvalue required as left operand of assignment
     errno = 0;
           ^
local.c:353:23: error: lvalue required as left operand of assignment
                 errno = 0;
                       ^
local.c: In function 'server_send_cb':
local.c:586:15: error: lvalue required as left operand of assignment
         errno = 0;
               ^
local.c: In function 'remote_recv_cb':
local.c:650:11: error: lvalue required as left operand of assignment
     errno = 0;
           ^
local.c:685:11: error: lvalue required as left operand of assignment
     errno = 0;
           ^
local.c: In function 'remote_send_cb':
local.c:748:15: error: lvalue required as left operand of assignment
         errno = 0;
               ^
Makefile:770: recipe for target 'libshadowsocks_la-local.lo' failed
make[2]: *** [libshadowsocks_la-local.lo] Error 1
make[2]: Leaving directory '/home/Phoenix xie/src/shadowsocks-libev/src'
Makefile:549: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/Phoenix xie/src/shadowsocks-libev'
Makefile:371: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by wongsyrone** [comment]
Windows has  _set_errno(0)
ref: https://msdn.microsoft.com/en-us/library/hf1920a7.aspx

**Comment by xseven007** [comment]
So, How to fix it? Add  "_set_errno( EILSEQ ); perror( "Oops" ); " in the file"local.c"?

**Comment by madeye** [comment]
@wongsyone Maybe you can open a pull request to fix this bug.

**Comment by xseven007** [comment]
@wongsyrone @madeye while we build ss on windows, we should test if it is windows, if it's ,there is no requied "errno = 0;" in the local.c and tunnel.c.

**Comment by wongsyrone** [comment]
If anyone has interest, please check https://github.com/wongsyrone/shadowsocks-libev-libsodium-for-server/commit/1b1ebdc74d107c7bc3dbe30ea01d1f0b69612864 , feel free to leave line notes
