### ISSUE TITLE
There's some conflicts in manual page and source code

### ISSUE THREAD

**Issue by kimw** [shadowsocks/shadowsocks-libev#594]
When I rearranging the manual page, I found conflicts in manual page and code. e.g.

- The '-l' option was declared in man page, but not implemented in code.
- The '-d' option was coded in source but can't be found in man page.

I made a matrix of functions in shadowsocks-libev, as attached.

[shadowsocks-libev functions matrix.pdf](https://github.com/shadowsocks/shadowsocks-libev/files/225842/shadowsocks-libev.functions.matrix.-.Sheet1-8.pdf)

The 'man' column means the option was found in manual page. The 'code' column means the option was found in source code. The red cells are the conflicts.

My question is, which one should I follow when I rearranging the man pages?

**Comment by madeye** [comment]
Follow the latest code. Many man pages are outdated now.
