### ISSUE TITLE
Why there's no '-i' option in ss-redir?

### ISSUE THREAD

**Issue by kimw** [shadowsocks/shadowsocks-libev#598]
The option '-i', which means bind the service to interface, was supported in `ss-server`, `ss-manager`, `ss-local` and `ss-tunnel`, but NOT in `ss-redir`.

I'm just wondering why doesn't the `ss-redir` support to bind to a specific interface? Is it a TODO or some reason (e.g. conflict with another feature)?

**Comment by madeye** [comment]
Nope.

**Comment by kimw** [comment]
@madeye Do you mean it's just a TODO?

**Comment by madeye** [comment]
No plan for that.
