### ISSUE TITLE
可否增加UDP over TCP的模式？

### ISSUE THREAD

**Issue by gaocuo** [shadowsocks/shadowsocks-libev#602]
部分地区和运营商对UDP包处理非常不友善，导致UDP包发送成功率不到10%，如果使用ss-tunnel 来转发dns 请求变得非常艰难，但是使用unbound 转发则正常，但unbound编译后将近600K的体积，想集成进路由固件非常困难，希望增加 UDP over TCP的选项。

**Comment by madeye** [comment]
No plan for this.
