### ISSUE TITLE
Image in dockerhub does not update automatically

### ISSUE THREAD

**Issue by ahxxm** [shadowsocks/shadowsocks-libev#605]
it's not quite possible for me to add trigger .. for example to add alpine image auto-build trigger, go to "Build Settings" section:

![image](https://cloud.githubusercontent.com/assets/1286225/14736243/6c80fcc8-08a8-11e6-9caf-a30c45f3b294.png)

the same as ubuntu..

**Comment by madeye** [comment]
@vimagick can help to update this.

**Comment by vimagick** [comment]
Do you mean setup trigger for [shadowsocks/shadowsocks-libev](https://hub.docker.com/r/shadowsocks/shadowsocks-libev/)?
I don't have permission to change settings, it's not created by me.

**Comment by madeye** [comment]
Just vimagick/shadowsocks-libev is OK.

**Comment by madeye** [comment]
Please use  vimagick/shadowsocks-libev directly. He will update the image for you.

**Comment by vimagick** [comment]
I've created a standalone git repo for [docker-shadowsocks-libev](https://github.com/EasyPi/docker-shadowsocks-libev).
The docker image has been migrated to [easypi/shadowsocks-libev](https://hub.docker.com/r/easypi/shadowsocks-libev/).
