### ISSUE TITLE
What dose option -i mean?

### ISSUE THREAD

**Issue by kimw** [shadowsocks/shadowsocks-libev#607]
Here's some words that I understand from the codes.
Please feel free to correct me if I misunderstand the question.

> Bind to a specific network interface. Which means, the traffic will send and
receive through the interface that is bound.
>
> For example, there are three interfaces in your device, which is lo (127.0.0.1),
eth0 (192.168.0.1) and eth1 (192.168.0.2). Meanwhile, you configure \fBshadowsocks-libev\fR to listen on 0.0.0.0:8388 and bind to eth1. That results the traffic go through eth1, but not lo nor eth0. This option is useful in multi-interface enviornment.

**Comment by madeye** [comment]
This option is for sending traffic through specific interface.

**Comment by kimw** [comment]
@madeye  How's about this one?

> -i interface
> Send traffic through specific network interface.
>
> For example, there are three interfaces in your device, which is
> lo (127.0.0.1), eth0 (192.168.0.1) and eth1 (192.168.0.2). Mean‐
> while, you configure shadowsocks-libev to listen on 0.0.0.0:8388
> and  bind to eth1. That results the traffic go out through eth1,
> but not lo nor eth0. This option is useful to  control  traffic
> in multi-interface environment.

**Comment by madeye** [comment]
LGTM.

**Comment by kimw** [comment]
@madeye What's LGTM?
