### ISSUE TITLE
--forbidden-ip 127.0.0.1,::1 ,main processes exited

### ISSUE THREAD

**Issue by sophauer** [shadowsocks/shadowsocks-libev#614]
新版本加上--forbidden-ip 127.0.0.1,::1参数运行,则立刻退出
不加这个参数则正常

centos 7 64x

**Comment by wongsyrone** [comment]
--forbidden-ip 是python版的参数，你应该用--acl

**Comment by sophauer** [comment]
谢谢赐教...但以前都可以

**Comment by kimw** [comment]
@sophauer
The previous version runs successful with option `--forbidden-ip` because it's ignored.
The news check options at startup, and returns `EXIT_FATAL` with usage printed while the option is not recognized.
