### ISSUE TITLE
允许在 Terminal 下访问 ss-server 的稳定客户端。

### ISSUE THREAD

**Issue by zw963** [shadowsocks/shadowsocks-libev#618]
当前我使用的方案时， 通过 ss-local 连接远程的 ss-libev server.

当我希望在 Terminal 下访问外网时， 我通过设定一个环境变量来达到这个效果。

```cl
 ╰─ $ type use_proxy
use_proxy is a function
use_proxy () 
{ 
    if [ $# == 0 ]; then
        export LD_PRELOAD=/home/zw963/Dropbox/linux/lib64/libproxychains4.so;
    else
        ( LD_PRELOAD=/home/zw963/Dropbox/linux/lib64/libproxychains4.so exec "$@" );
    fi
}
```

但是这种方式不够稳定， 常常很多基于脚本语言的程序无法正确的访问外网。

请问有没有类似的其他替代方案？ (更稳定，限制更少)
ss-tunnel 或 ss-redir 是否可以实现类似功能？ 不过我没连接 server 成功。

**Comment by zw963** [comment]
请教， 是不是我的思路一直有问题？ 简单问题复杂化？

数据通过 sock5 协议， 数据传输到本地， 还得再通过一个 proxy 程序 forward 到
http 或 https， 然后再 export http_proxy=???

**Comment by madeye** [comment]
https://www.inet.no/dante/doc/1.3.x/socksify.1.html

**Comment by zw963** [comment]
@madeye, 试了一下， socksify w3m www.google.com 可以工作。
但是这个工作原理似乎和 libproxychians4 一样的
socksify npm install, 仍然很慢, 不工作。

**Comment by zw963** [comment]
我试了下， stunnel 5 和 privoxy 似乎都不工作。  理论上都应该支持的？

**Comment by zw963** [comment]
我看到 android ss 客户端下面， 有一堆应用程序似乎跟这个有关。 
pdnsd, redsocks, tu2socks ss-local ss-tunnel, 到底那个才是正确的？

**Comment by s7lx** [comment]
run `ss-redir ` then use iptables forward data
