### ISSUE TITLE
Would listen port hopping be helpful?

### ISSUE THREAD

**Issue by XiaoxiaoPu** [shadowsocks/shadowsocks-libev#619]
Large amount traffic on single port may be conspicuous. How about change the port periodically? The port can be selected by an algorithm similar to [TOTP](https://en.wikipedia.org/wiki/Time-based_One-time_Password_Algorithm), so there's no negotiation between server and client. Detection and attack would also be harder.

Example algorithm:
port = HMAC-SHA1(timestamp, secret) mod range

**Comment by madeye** [comment]
No plan for this.

**Comment by kimw** [comment]
I'm not knowledge on security network. But I think, randomize the traffic port is unnecessary unless the traffic is really **amount**.

Would it be detected much easier while a series of random ports on a single IP?

Any more talk about on this topic are always welcome.
