### ISSUE TITLE
Connection reset by peer 这个问题很困扰

### ISSUE THREAD

**Issue by lingaoyi** [shadowsocks/shadowsocks-libev#621]
May  1 22:01:14 ss-local[5034]: remote_recv_cb_recv: Connection reset by peer
May  1 22:01:14 ss-local[5034]: remote_recv_cb_recv: Connection reset by peer
May  1 22:01:19 ss-local[5034]: remote_recv_cb_recv: Connection reset by peer
May  1 22:01:30 ss-local[5034]: remote_recv_cb_recv: Connection reset by peer
May  1 22:01:30 ss-local[5034]: remote_recv_cb_recv: Connection reset by peer
May  1 22:01:47 ss-local[5034]: remote_recv_cb_recv: Connection reset by peer
May  1 22:02:54 ss-local[5034]: remote_recv_cb_recv: Connection reset by peer
May  1 22:03:36 ss-local[5034]: remote_recv_cb_recv: Connection reset by peer

在梅林固件下看到后台出现这个东西，会导致SS断开，特别游戏模式尤其明显。

**Comment by madeye** [comment]
Enlarge the timeout on both client and server side.

**Comment by lingaoyi** [comment]
我已经把    "timeout": 800, 还是有几率出现断线情况。。。
