### ISSUE TITLE
Question: How to make libcrypto static link?

### ISSUE THREAD

**Issue by zhsj** [shadowsocks/shadowsocks-libev#623]
Background: 
Debian testing and Debian jessie have different version of libcrypto, and they are incompatible. But I want to build once and run on both of them. So I want to make the libcrypto statically linked.

I don't know much about autoconf. But I can manually link it. For example, 

```
gcc ss_local-*.o  -L../libcork/.libs/ -L../libev/.libs/ -L../libudns/.libs/ -L../libipset/.libs/ \
-L../libsodium/src/libsodium/.libs/  -Wl,-Bstatic -lcrypto -lsodium -lev -lipset -lcork \
-ludns -lm -Wl,-Bdynamic -lpthread -ldl -o ss_local
```

This will output `ss-local` which is statically linked with libcrypto.

Then my question is how can I deal with them with autoconf?

**Comment by madeye** [comment]
`./configure --help`

**Comment by wongsyrone** [comment]
try passing CFLAGS and LDFLAGS when executing `./configure`

**Comment by zhsj** [comment]
I tried `--enable-static`, ``--enable-static=crypto`, `--enable-static=libcrypto` but it didn't work.
I have no idea about`LDFLAGS` since it will mass up the link options.

**Comment by rampageX** [comment]
#with OpenSSL
    ./configure --prefix=/opt
    #OR mbedTLS static
    ./configure --prefix=/opt --with-crypto-library=mbedtls --with-mbedtls=/mmc/lib --with-mbedtls-include=/mmc/include--prefix=/opt --with-crypto-library=mbedtls --with-mbedtls=/mmc/lib --with-mbedtls-include=/mmc/include
    #then edit src/Makefile , find the LDFLAGS variable, and set it to "-all-static"
    sed -i 's/^LDFLAGS = /LDFLAGS = -all-static -s/g' src/Makefile
    #run `make`,  you'll get the static files
    make



    file src/ss-local
    src/ss-local: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), statically linked, not stripped

**Comment by rampageX** [comment]
Another way:

    LIBS="-ldl -lz" LDFLAGS="-Wl,-static -static -static-libgcc -s" ./configure --prefix=/opt
    make

**Comment by zhsj** [comment]
@rampageX you try to edit the Makefile manually and that is not what I want to see.
Besides, the `LDFLAGS` is much simpler if you try to link all libs statically including libc.
However I just want to link libcrypto meanwhile libc and others are still dynamically linked.  From my original post, you can see I have to pass ` -Wl,-Bstatic -lcrypto -lsodium -lev -lipset -lcork \
-ludns -lm -Wl,-Bdynamic -lpthread -ldl`. That's too long to make it work.
I hope I can find something like `--enable-static=crypto`, which means in autoconf's way.

**Comment by zoobab** [comment]
Try with musl-libc, glibc makes it difficult to compile static binaries.
