### ISSUE TITLE
Could not connect success if resotre with Titanium Backup.

### ISSUE THREAD

**Issue by zw963** [shadowsocks/shadowsocks-libev#624]
I have so many users app/data, i backup those with Titanium Backup, almost all is successful, except 
Shadowsocks, 

When open ss, seem like server/port/remote port/... everything is settings correctly.

When i check Network traffic, it keep Testing ... a while, and get a  message: `Failed to detect internet connection. Unable resolve host www.google.com ...`,  And then told me: `internet Unavailable`, But my WIFI is worked, internet is available.

Reinstall is not worked, the only solution is: remove and install again.

**Comment by zw963** [comment]
For clarify:

I must uninstall shadowsocks which install by Titanium backup, and install it from apk, and config to make it work.

**Comment by zw963** [comment]
There exist another bug, maybe relate to this issue.

When i first start ss, I set server/remote port/local port/password, and click connect icon, it worked.
stunnel is created, connect is available, But, all my settings is missing ... I have to settings those
config again to make it saved.

I think the two problem is caused by the same cause maybe?

**Comment by zw963** [comment]
I have tried to reinstall and config make it work, and backup it with TB, restore again, still not work.

Shadowsocks 2.10.1

**Comment by madeye** [comment]
Never backup shadowsocks like this, it will broke binary files located at /data.

Create a new profile for your config to avoid overwrite the default one.

**Comment by zw963** [comment]
> When i first start ss, I set server/remote port/local port/password, and click connect icon, it worked.
> stunnel is created, connect is available, But, all my settings is missing ... I have to settings those
> config again to make it saved.

This is not a bug ?

**Comment by zw963** [comment]
Create a new profile and settings my config, This solution is worked with TB restore.



> Never backup shadowsocks like this, it will broke binary files located at /data.

If broken binary file, why this work?
Do you very understood Titanium Backup work work process?
I don't know how do you get this conclusion, shadowsocks is NOT ONLY application `with
binary files located at /data`.
