### ISSUE TITLE
能否考虑底层增加KCP形式的UDP传输，加快传输速度？

### ISSUE THREAD

**Issue by bettermanbao** [shadowsocks/shadowsocks-libev#625]
最近看到了下面这个项目，用UDP协议代替TCP协议实现快速传输。
https://github.com/skywind3000/kcp

想请问一下ss-libev底层是否可以增加这种UDP的传输方式，供用户选择？这样可以大大提高与VPS的数据传输速度。

这个kcp源码也是C语言，移植过来应该也比较容易？谢谢！！！

**Comment by xpader** [comment]
现在 SS 的关键问题，还是在于墙有多高，你比如在香港弄一个 SS 就不会被墙拖的那么慢，所以你这个提议我认为意义不大。而且本身和 SS 的协议可能冲突较大。

**Comment by kimw** [comment]
And, the UDP can not work prefectly in some condition.
As I known, some ISP blocks UDP.

**Comment by madeye** [comment]
No plan for this.

**Comment by madeye** [comment]
Since we have [kcptun ](https://github.com/xtaci/kcptun) now. It's very easy to use both shadowsocks-libev and kcp together.

Here is a sample [docker image](https://hub.docker.com/r/yaleh/kcp-shadowsocks-server/~/dockerfile/) built for shadowsocks over kcp.

**Comment by bettermanbao** [comment]
Thanks, I tried kcptun. It works perfect. But the problem is it is written in go language, and go language runs very slow in most low-end box, like MIPS32 based router. Therefore, if there is a C version kcptun, it will be much helpful. I saw you have ported kcptun into SS-Android, very good trial.

**Comment by VampireSH** [comment]
好像有办法可以把kcp用在libev上

bettermanbao <notifications@github.com>于2016年8月9日周二 12:02写道：
