### ISSUE TITLE
about -i parameter

### ISSUE THREAD

**Issue by hkisl** [shadowsocks/shadowsocks-libev#626]
We have a multi wan Infrastructure on CentOS7. For network interface ens192, it has 202.74.0.42. we assigned interface label ens1921 on 27.50.36.65. 

When we use command > "ss-server  -s 183.2.185.134 -i ens1921 -k 12345678-p 1100  -m aes-256-cfb" to start the ss. I suppose the outgoing IP should be 27.50.36.65. However, after client connecting the SS, the outgoing IP is 202.74.0.42

We do further testing, > "curl http://google.com --interface ens1921", the outgoing IP is 27.50.36.65
>ss -n -a
tcp    TIME-WAIT  0      0      27.50.36.65:59400              216.58.221.238:80

May I know is it software design to use the first WAN IP on ens192 or I use the -i parameter wrongly? Thank you.

CentOS7 Network Infrastructure
> ip a show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: ens192: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP qlen 1000
    link/ether 00:50:56:a7:4b:af brd ff:ff:ff:ff:ff:ff
    inet 202.74.0.42/24 brd 202.74.0.255 scope global ens192
       valid_lft forever preferred_lft forever
    inet 27.50.36.65/26 scope global ens1921
       valid_lft forever preferred_lft forever
3: ens224: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP qlen 1000
    link/ether 00:50:56:a7:3c:d5 brd ff:ff:ff:ff:ff:ff
    inet 183.2.185.134/28 brd 183.2.185.143 scope global ens224
       valid_lft forever preferred_lft forever
4: ens256: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP qlen 1000
    link/ether 00:50:56:a7:3f:90 brd ff:ff:ff:ff:ff:ff

**Comment by madeye** [comment]
Run `ss-server` in root user and try again.

**Comment by hkisl** [comment]
Thank you for your reply.

With same CentOS7 network infrastructure. We used the latest code and start the ss-server again. Now, It reports "ERROR: setinterface: No such device"

[root@s5-serv] ss-server  -s 183.2.185.134 -i ens1921  -k bbbbbbbb -p 1100  -m aes-256-cfb
 2016-05-06 14:59:20 INFO: initializing ciphers... aes-256-cfb
 2016-05-06 14:59:20 INFO: port reuse enabled
 2016-05-06 14:59:20 INFO: listening at 183.2.185.134:1100
 2016-05-06 14:59:25 ERROR: setinterface: No such device
 2016-05-06 14:59:27 ERROR: setinterface: No such device
 2016-05-06 14:59:28 ERROR: setinterface: No such device

> ps aux
root      4581  0.0  0.0  18032  1488 pts/2    S+   15:00   0:00 ss-server -s 183.2.185.134 -i en
s1921 -k bbbbbbbb -p 1100 -m aes-256-cfb

CentOS7 Network Infrastructure:
ip a show
1: lo: mtu 65536 qdisc noqueue state UNKNOWN
link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
inet 127.0.0.1/8 scope host lo
valid_lft forever preferred_lft forever
2: ens192: mtu 1500 qdisc mq state UP qlen 1000
link/ether 00:50:56:a7:4b:af brd ff:ff:ff:ff:ff:ff
inet 202.74.0.42/24 brd 202.74.0.255 scope global ens192
valid_lft forever preferred_lft forever
inet 27.50.36.65/26 scope global ens1921
valid_lft forever preferred_lft forever
3: ens224: mtu 1500 qdisc mq state UP qlen 1000
link/ether 00:50:56:a7:3c:d5 brd ff:ff:ff:ff:ff:ff
inet 183.2.185.134/28 brd 183.2.185.143 scope global ens224
valid_lft forever preferred_lft forever
4: ens256: mtu 1500 qdisc mq state UP qlen 1000
link/ether 00:50:56:a7:3f:90 brd ff:ff:ff:ff:ff:ff

**Comment by madeye** [comment]
In your command line, you specify the interface to be `ens1921`. But in your `ip a show`, there is no `ens1921`, but only `ens192`.

**Comment by madeye** [comment]
In other words, `-i` here only works for primary, not alias to a NIC.

**Comment by hkisl** [comment]
Thank you for your reply.

We tried to add IP using ifconfig now but the result is same. Is it also not support?

[root@s5-server ~]# ss-server  -s 183.2.185.134 -i ens192:1 -k bbbbbbbb -p 1100  -m aes-256-cfb
 2016-05-06 15:28:25 INFO: initializing ciphers... aes-256-cfb
 2016-05-06 15:28:25 INFO: port reuse enabled
 2016-05-06 15:28:25 INFO: listening at 183.2.185.134:1100
 2016-05-06 15:28:27 ERROR: setinterface: No such device

[root@s5-server ~]# ifconfig
ens192: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 202.74.0.42  netmask 255.255.255.0  broadcast 202.74.0.255
        ether 00:50:56:a7:4b:af  txqueuelen 1000  (Ethernet)
        RX packets 3603780  bytes 528533272 (504.0 MiB)
        RX errors 0  dropped 128  overruns 0  frame 0
        TX packets 104842  bytes 72977742 (69.5 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

ens192:1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 27.50.36.65  netmask 255.255.255.192  broadcast 27.50.36.127
        ether 00:50:56:a7:4b:af  txqueuelen 1000  (Ethernet)

ens224: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 183.2.185.134  netmask 255.255.255.240  broadcast 183.2.185.143
        ether 00:50:56:a7:3c:d5  txqueuelen 1000  (Ethernet)
        RX packets 58400  bytes 6318847 (6.0 MiB)
        RX errors 0  dropped 58  overruns 0  frame 0
        TX packets 588  bytes 41217 (40.2 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

ens256: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        ether 00:50:56:a7:3f:90  txqueuelen 1000  (Ethernet)
        RX packets 3596221  bytes 515542272 (491.6 MiB)
        RX errors 0  dropped 206  overruns 0  frame 0
        TX packets 250  bytes 10500 (10.2 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        loop  txqueuelen 0  (Local Loopback)
        RX packets 443  bytes 38692 (37.7 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 443  bytes 38692 (37.7 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**Comment by madeye** [comment]
Update to the latest code and try `-b <ip_address>`.
