### ISSUE TITLE
Randomly not working

### ISSUE THREAD

**Issue by droseacc** [shadowsocks/shadowsocks-libev#633]
I have this running on a netgear wndr3800 with OpenWRT, the issue I have is it will run for a few hours, then give no errors, and not connect to any websites. I can still use the phone or desktop clients to connect to the server so the issue isn't there. Restarting the router or changing server (sometimes) fixes this

**Comment by madeye** [comment]
It looks a DNS issue. Make sure you're not using ChinaDNS.

**Comment by droseacc** [comment]
How else can I avoid DNS poisoning?

**Comment by lixingcong** [comment]
@droseacc 
use dnscrypt-proxy
