### ISSUE TITLE
about crypto library

### ISSUE THREAD

**Issue by rogers0** [shadowsocks/shadowsocks-libev#637]
README.md mentioned that:
    There are three crypto libraries available:
    OpenSSL (default)
    PolarSSL
    mbedTLS (NOT officially supported)
But accroding to the mbedTLS homepage [0], it was called PolarSSL.
So the doc seems to be quite old. Please update what the status is currently. Thank you!

[0] https://tls.mbed.org/

**Comment by hosiet** [comment]
Different package name in distributions and header files has prevented from smooth migration between polarssl and mbedtls. Also, there are various regressions. The full switch may need more tests and wait till polarssl fade out from linux distributions.

Also see #422 and #365.

**Comment by wongsyrone** [comment]
mbed TLS here means the library which version higher than v2.0.0.

**Comment by madeye** [comment]
As mentioned above, PolarSSL is still supported for compatibility.

**Comment by rogers0** [comment]
Thanks for the comments!

I think these info should be added into README.md
