### ISSUE TITLE
Can not build on ubuntu

### ISSUE THREAD

**Issue by debiansid** [shadowsocks/shadowsocks-libev#639]
dpkg-source: error: can't build with source format '3.0 (quilt)': no upstream tarball found at ../shadowsocks-libev_2.4.6.orig.tar.{bz2,gz,lzma,xz}
dpkg-buildpackage: error: dpkg-source -i -b shadowsocks-libev gave error exit status 255

**Comment by hosiet** [comment]
Which version of ubuntu are you using now?

**Comment by debiansid** [comment]
hosthatch:~$ lsb_release -r    
Release:        15.04

**Comment by hosiet** [comment]
Cannot reproduce on a fresh installed Ubuntu 15.04.

Note that ubuntu 15.04 has reached EOL by February 2016. Upgrade your system and try again.

**Comment by debiansid** [comment]
dpkg-source: error: can't build with source format '3.0 (quilt)': no upstream tarball found at ../shadowsocks-libev_2.4.6.orig.tar.{bz2,gz,lzma,xz}
dpkg-buildpackage: error: dpkg-source -i -b shadowsocks-libev gave error exit status 255
 14.04 has same error. 
ps newest git version

**Comment by hosiet** [comment]
Have you tried to add the '-b' option to dpkg-buildpackage, as README.md
required?

**Comment by kang000feng** [comment]
@madeye @hosiet @debiansid I have the same issue on ubuntu14.04 , how did you fix it? thank you! 

dpkg-source: error: can't build with source format '3.0 (quilt)': no upstream ta      rball found at ../shadowsocks-libev_2.4.7.orig.tar.{bz2,gz,lzma,xz}
dpkg-buildpackage: error: dpkg-source -i -b shadowsocks-libev gave error exit st      atus 255

**Comment by MatchboxDorry** [comment]
```dpkg-buildpackage -b -rfakeroot -us -uc```
