### ISSUE TITLE
handling of connect errors

### ISSUE THREAD

**Issue by vavrecan** [shadowsocks/shadowsocks-libev#640]
I was wondering why there is no error check after socket connect function call - 
https://github.com/shadowsocks/shadowsocks-libev/blob/master/src/redir.c#L651

Shadowsocks is actually giving no error information when it was not possible to connect to shadowsocks server. Why is that? Thanks a lot!

**Comment by madeye** [comment]
They are handled asynchronously in remote_send_cb().

https://github.com/shadowsocks/shadowsocks-libev/blob/master/src/redir.c#L433
