### ISSUE TITLE
Getting random periodic DNS failures.

### ISSUE THREAD

**Issue by droseacc** [shadowsocks/shadowsocks-libev#641]
Using OpenWrt Chaos Calmer 15.05.1

I'm getting random DNS failures for long periods without reason, I thought it might be related to ChinaDNS so I removed that and just use Shadowsock's forwarding directly, DNSmasq's DNS forwardings is set to 127.0.0.1#(UDP Local Port) and to not use the resolve file.  

This works fine usually but I'm getting random periods of anywhere from 5-30 minutes where the DNS won't work, the dekstop/android client still work while this is happening so doesn't appear to be a  server issue.  If I wait for a while this usually resolves itself without intervention, also changing server or restarting the router resolves this but it's not an ideal situation obviously.  I've checked the logs and nothing comes up related to this.

**Comment by madeye** [comment]
If restarting router works, it looks like an issue of your router's config.

Make sure to relax the nofile limits of your router OS. Try configs here: https://shadowsocks.org/en/config/advanced.html

**Comment by droseacc** [comment]
That guide is for the server.  Why is every issue here closed and ignored before it is solved. Really unhelpful.

**Comment by droseacc** [comment]
As per the guide; OpenWRT has no /etc/security/limits.conf so how could that be set.
