### ISSUE TITLE
newest trunk can not work

### ISSUE THREAD

**Issue by debiansid** [shadowsocks/shadowsocks-libev#642]
just git pull the newest trunk, but I can not connect from client anymore.
any clue why? or how to debug it

**Comment by madeye** [comment]
Add `-v` to your client's command line, and post your log here.

**Comment by debiansid** [comment]
--2016-05-23 13:17:28--  (try: 6)  http://www.wenxuecity.com/
Connecting to www.wenxuecity.com|104.197.50.65|:80... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.

root@openwrt-x86:~# ss-redir -c /etc/shadowsocks.json -v
 2016-05-23 13:16:58 INFO: initialize ciphers... rc4-md5
 2016-05-23 13:16:58 INFO: tcp port reuse enabled
 2016-05-23 13:16:58 INFO: listening at 127.0.0.1:1080

nothing special 
back to stable release fixed that issue.

**Comment by WANG-lp** [comment]
cannot work two

**Comment by madeye** [comment]
Please post the full log.

**Comment by WANG-lp** [comment]
back to dd90af is ok.
Full log:
![qq20160523-0 2x](https://cloud.githubusercontent.com/assets/1270875/15461288/54cf8e30-20ec-11e6-998a-a2176ce2170a.png)

**Comment by madeye** [comment]
I cannot reproduce the issue locally. And according to your log, everything works well.

**Comment by WANG-lp** [comment]
@madeye do you test the new server with old version client?

**Comment by madeye** [comment]
Both are latest.

**Comment by debiansid** [comment]
My client is old version for openwrt and Surge on iOS

**Comment by WANG-lp** [comment]
@debiansid me too, I use two kinds client, one for OpenWRT, one for x86 which was compiled in earlier days.

**Comment by wongsyrone** [comment]
I can also reproduce with shadowsocks-android which has old ss-local and shadowsocks-windows

**Comment by debiansid** [comment]
It looks like no way to compile trunk for openwrt

**Comment by debiansid** [comment]
@WANG-Ip does it work on your device?

**Comment by madeye** [comment]
Please try the latest commit.

**Comment by debiansid** [comment]
It is fixed,thanks

**Comment by madeye** [comment]
Thanks for the help.

**Comment by WANG-lp** [comment]
@debiansid  @madeye It works with the latest commit, thanks 👍
