### ISSUE TITLE
git version, error when compile with PolarSSL and MbedTLS

### ISSUE THREAD

**Issue by rampageX** [shadowsocks/shadowsocks-libev#643]
make[2]: Entering directory '/tmp/mnt/data/compile/shadowsocks-libev/src'
  CCLD     libshadowsocks.la
  CCLD     ss-local
  CCLD     ss-tunnel
  CCLD     ss-server
  CCLD     ss-manager
make[2]: *** No rule to make target 'ss-nat', needed by 'all-am'.  Stop.

with OpenSSL  compile fine.

**Comment by wongsyrone** [comment]
Try ./autogen.sh
