### ISSUE TITLE
Unexpected a when seeking value

### ISSUE THREAD

**Issue by kmahyyg** [shadowsocks/shadowsocks-libev#644]
[root /]# ss-server -c /etc/shadowsocks-libev/config.json -d start
    2016-05-24 07:03:39 ERROR: 7:14: Unexpected a when seeking value

Debian 8 x64 on OpenVZ
Hosted on Bandwagonhost  
Help!
Installed by 'apt-get install shadowsocks-libev -y'

m2crypto libsodium and shadowsocks python server 2.8.2 and openssl installed.

**Comment by kmahyyg** [comment]
Also ssserver (py) running normally.

**Comment by wongsyrone** [comment]
You'd better paste your config file, and check line 7 col 14. The value of method should be quoted.

**Comment by kmahyyg** [comment]
[root /]# cat /etc/shadowsocks-libev/config.json
{
    "server":"0.0.0.0",
    "server_port":*******,
    "local_port":1******,
    "pass*****************************",
    "timeout":60,
    "method":aes-256-cfb
}

[root 	/]#

**Comment by kimw** [comment]
Hi @kmahyyg,

According to the error message shows up, `ERROR: 7:14`, the config file is incorrect at line 7, character 14. As it is, `"method":aes-256-cfb`, should be `"method":"aes-256-cfb"` (the value should be quoted).

**Comment by kmahyyg** [comment]
Thank you very much!
Close Issue.

2016-05-29 16:54 GMT+08:00 Kim <notifications@github.com>:

> Hi @kmahyyg <https://github.com/kmahyyg>,
>
> According to the error message shows up, ERROR: 7:14, the config file is
> incorrect at line 7, character 14. As it is, "method":aes-256-cfb, should
> be "method":"aes-256-cfb" (the value should be quoted).
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/shadowsocks/shadowsocks-libev/issues/644#issuecomment-222349912>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AP1d43IoUMAx9tswD9F8s3vWLa7PKwB1ks5qGVQ8gaJpZM4IlXmt>
> .
>



-- 
Send From My Google Mail

Contact Me:

Twitter:@PotatoOnline
Facebook:Find"Yang Yuguang" (yang.yuguang.73@facebook.com)
QQ:920337808
Tencent Microblog:@kmahyyg @lyxyjg
G+:kmahyygyyg@gmail.com
