### ISSUE TITLE
求助出现"ERROR: accept: Too many open files"的奇怪现象

### ISSUE THREAD

**Issue by zc640618** [shadowsocks/shadowsocks-libev#645]
root@do-sfo1-01:~# service shadowsocks-libev status 
● shadowsocks-libev.service - Shadowsocks-libev Default Server Service
   Loaded: loaded (/lib/systemd/system/shadowsocks-libev.service; enabled)
   Active: active (running) since Wed 2016-05-25 17:09:46 CST; 25s ago
 Main PID: 484 (ss-server)
   CGroup: /system.slice/shadowsocks-libev.service
           └─484 /usr/bin/ss-server -a root -c /etc/shadowsocks-libev/config.json -u -A

May 25 17:09:46 do-sfo1-01 ss-server[484]: 2016-05-25 17:09:46 INFO: onetime authentication enabled
May 25 17:09:46 do-sfo1-01 ss-server[484]: 2016-05-25 17:09:46 INFO: UDP relay enabled
May 25 17:09:46 do-sfo1-01 ss-server[484]: 2016-05-25 17:09:46 INFO: initializing ciphers... aes-256-cfb
May 25 17:09:46 do-sfo1-01 ss-server[484]: 2016-05-25 17:09:46 INFO: port reuse enabled
May 25 17:09:46 do-sfo1-01 ss-server[484]: 2016-05-25 17:09:46 INFO: udp port reuse enabled
May 25 17:09:46 do-sfo1-01 ss-server[484]: 2016-05-25 17:09:46 INFO: listening at 0.0.0.0:995
root@do-sfo1-01:~# cat /proc/484/limits 
Limit                     Soft Limit           Hard Limit           Units     
Max cpu time              unlimited            unlimited            seconds   
Max file size             unlimited            unlimited            bytes     
Max data size             unlimited            unlimited            bytes     
Max stack size            8388608              unlimited            bytes     
Max core file size        0                    unlimited            bytes     
Max resident set          unlimited            unlimited            bytes     
Max processes             1909                 1909                 processes 
**Max open files            1024                 4096                 files**     
Max locked memory         65536                65536                bytes     
Max address space         unlimited            unlimited            bytes     
Max file locks            unlimited            unlimited            locks     
Max pending signals       1909                 1909                 signals   
Max msgqueue size         819200               819200               bytes     
Max nice priority         0                    0                    
Max realtime priority     0                    0                    
Max realtime timeout      unlimited            unlimited            us        
root@do-sfo1-01:~# ulimit -n
65536
root@do-sfo1-01:~# cat /etc/sysctl.conf
fs.file-max = 65535
net.core.rmem_max = 67108864
net.core.wmem_max = 67108864
net.core.netdev_max_backlog = 250000
net.core.somaxconn = 4096
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_tw_recycle = 0
net.ipv4.tcp_fin_timeout = 30
net.ipv4.tcp_keepalive_time = 1200
net.ipv4.ip_local_port_range = 10000 65000
net.ipv4.tcp_max_syn_backlog = 8192
net.ipv4.tcp_max_tw_buckets = 5000
net.ipv4.tcp_fastopen = 3
net.ipv4.tcp_mem = 25600 51200 102400
net.ipv4.tcp_rmem = 4096 87380 67108864
net.ipv4.tcp_wmem = 4096 65536 67108864
net.ipv4.tcp_mtu_probing = 1
net.ipv4.tcp_congestion_control = hybla

root@do-sfo1-01:~# cat /etc/security/limits.conf 
* soft nproc 65535
* hard nproc 65535
* soft nofile 65535
* hard nofile 65535

如上所示，log一直报"ERROR: accept: Too many open files"错误，ulimit什么都改过了没有作用，执行”cat /proc/$ss-server_pid/limits“还是提示”Max open files            1024                 4096                 files“，请指教是不是哪个姿势不对，谢谢！

**Comment by madeye** [comment]
https://shadowsocks.org/en/config/advanced.html

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks-libev/blob/master/debian/shadowsocks-libev.default#L25

**Comment by zc640618** [comment]
root@do-sfo1-01:~# cat /etc/default/shadowsocks-libev | grep MAXFD
# Note: `START', `GROUP' and `MAXFD' options are not recognized by systemd.
MAXFD=65535
这个数值已经改了

**Comment by wongsyrone** [comment]
你可以试一下直接从源码编译，不打deb包

**Comment by zc640618** [comment]
@wongsyrone 谢谢指教，不打包deb，直接make安装解决！

**Comment by hosiet** [comment]
用 systemd service 启动的话，/etc/default
下面的配置有一些不起作用的，`/etc/default/shadowsocks-libev`文件里有注释说明。

例如 MAXFD 的配置可能需要直接修改 service 文件，在较新的 systemd 版本中可以使用`systemctl edit`功能。

**Comment by zc640618** [comment]
@hosiet 修改这个文件也可以，谢谢指教！
/lib/systemd/system/shadowsocks-libev.service
