### ISSUE TITLE
ipv6 preference over ipv4 for hostname resolution

### ISSUE THREAD

**Issue by vavrecan** [shadowsocks/shadowsocks-libev#646]
I would like to prefer ipv6 if possible when doing hostname requests in cork_ip_init - https://github.com/shadowsocks/shadowsocks-libev/blob/ce0561a9992707a8409b9ca5a03f7aa7476608a1/libcork/core/ip-address.c#L482. 

Is the best way to achieve this to add new parameter to configuration? .e.g -6 ? Let me know and I will do this

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks-libev/blob/master/man/ss-server.1#L111

**Comment by vavrecan** [comment]
i have question because i am not sure if I understand it - the resolving is done over cork_ip_init which is in external library https://github.com/shadowsocks/shadowsocks-libev/blob/master/src/server.c#L702

and it indeed, does lookup ipv4 first, no matter what is the setting - correct?

**Comment by madeye** [comment]
Nope,  DNS resolving happens in libudns.

**Comment by vavrecan** [comment]
ahh i see, cork ip only matches if domain is IP address - I understand it now - thanks a lot!
