### ISSUE TITLE
请教ss-manager的用法

### ISSUE THREAD

**Issue by colingpt** [shadowsocks/shadowsocks-libev#649]
您好，新手一枚，第一次用api，跟着manual做了一上午。。。只有一次阴差阳错的成功配置，但是下午又不成了，不论怎么试都是返回:

`System.Net.Sockets.SocketException (0x80004005): 由于目标计算机积极拒绝，无法连接。 104.223.16.71:8989
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at Shadowsocks.Controller.Handler.ConnectCallback(IAsyncResult a)`

我根据example里的例子写了这个命令:

`ss-manager  --manager-address  /tmp/manager.sock  --executable  $(which  ss-server) 
/etc/shadowsocks-libev/config-test.json -f ss-manager`

config-test.json内容：
`{
"server":"我服务器ip",
"server_port":8989,
"local_address":"127.0.0.1",
"local_port":1080,
"password":"123456",
"timeout":600,
"method":"aes-256-cfb"
}`

之后安装了netcat-openbsd, `nc -Uu /tmp/manager.sock`连接

之后 add: {"server_port": 8989, "password":"123456"}，返回 ok

top进程里可以看到ss-manager和ss-server，但是连接后win客户端都是目标计算机积极拒绝。

不知哪里出错了，请指教。

同时有几个问题：

1.example里的例子`ss-manager  --manager-address  /tmp/manager.sock  --executable  $(which  ss-server) -s example.com -m aes-256-cfb -c /path/to/config.json`

·`-s example.com -m aes-256-cfb -c /path/to/config.json`这一部分应该都是配置ss-server的吧？那么一般config文件里有加密方式和主机地址，**需要写两遍吗？**
（我也试过
`ss-manager  --manager-address  /tmp/manager.sock  --executable  $(which  ss-server) -s example.com -m aes-256-cfb -c /etc/shadowsocks-libev/config.json -f ss-manager`
但不成功）

进入netcat后，ping返回`stat:{}`，必须执行add命令后, ping 才会返回`stat: {"8989":xxx}`,成功的那次，xxx会变化，并且比较大，后来服务器拒绝，数字比较小，变化也比较小。这里的问题是，我已经在config里配置了8989端口的密码，**看样子并没有随着ss启动,那么这里-c config file 有什么作用？**

我试着把config文件写为一个不存在的文件，看看是不是会生成新的文件，貌似也没有，**所以-f不是写入数据的命令吧**

2.我还试着修改了config文件，teddysun的一键安装版本里，ip地址写的是0.0.0.0，我搜了一下，网上说这样的地址相当于所有未知位置。我也试着改成0.0.0.0的地址，但没有作用。**我以前都是用自己的ip，这两者之间有什么区别吗**？

3.如果成功运行，**每次add一个端口和密码就会启用一个进程吗？**

4.如果成功运行，**怎样保证添加的端口在重启后依旧生效而不需要再次输入？有没有办法生成一个像python或go版本那样的config文件，方便配置保存？**

5.manual里有这么一句，
> Start the manager. Arguments for ss-server will be passed to generated ss-server process(es) respectively.

**这是否意味着ss-server启动时可以同时载入多个config文件？**，比如：
`ss-server -c /path/to/config.json config1.json config2.json`
或者
`ss-server -c /path/to/config.json /path/to/config1.json /path/to/config2.json`

我看了[teddysun写的一篇文章](https://shadowsocks.be/7.html)，貌似是为了使用多个ip，所以用不同的用户启动ss-server。

如果只有一个ip，
`ss-server -c /path/to/config.json -f pid1`
`ss-server -c /path/to/config2.json -f pid2`
应该就可以开启多进程来实现多用户吧。

刚接触linux不久，ss-manager的教程网上也不多，这里也没有wiki页，只能参照manual尝试了。。。走投无路来求助了，实在很喜欢这个功能。

非常谢谢！

**Comment by madeye** [comment]
A easy way to debug your config is using `ps aux | grep ss-server` to get the command line of your server processes. Make sure your client has the same config as your server.

**Comment by madeye** [comment]
Another way is to add `-v` option to your `ss-manager` command line, which will outputs detailed command line executed by `ss-manager`.

**Comment by colingpt** [comment]
really helpful........... thx
