### ISSUE TITLE
Multi Port and Password

### ISSUE THREAD

**Issue by MeganEllis** [shadowsocks/shadowsocks-libev#65]
Hi.
_ss-server_ won't listen on extra ports using config format like in "config-server-multi-passwd.json" or "config-server-multi-port.json".
This part not load with _ss-server_:

```
"port_password": {
  "8380": "barfoo-01!",
  "8381": "barfoo-02!"
 }
```

I'm on Debian and installing it with apt-get.

**Comment by gnu4cn** [comment]
[https://github.com/gnu4cn/openwrt-ss-configs](https://github.com/gnu4cn/openwrt-ss-configs)
