### ISSUE TITLE
getpeername: Transport endpoint is not connected

### ISSUE THREAD

**Issue by simonsmh** [shadowsocks/shadowsocks-libev#651]
Using Debian 8 and ss-libev just build from source.
Syslog:
May 27 10:28:52 simonsmh ss-server[497]: 2016-05-27 10:28:52 INFO: resolving hostname to IPv6 address first May 27 10:28:52 simonsmh ss-server[497]: 2016-05-27 10:28:52 INFO: using tcp fast open May 27 10:28:52 simonsmh ss-server[497]: 2016-05-27 10:28:52 INFO: onetime authentication enabled May 27 10:28:52 simonsmh ss-server[497]: 2016-05-27 10:28:52 INFO: UDP relay enabled May 27 10:28:52 simonsmh ss-server[497]: 2016-05-27 10:28:52 INFO: initializing ciphers... chacha20 May 27 10:28:52 simonsmh ss-server[497]: 2016-05-27 10:28:52 INFO: port reuse enabled May 27 10:28:52 simonsmh ss-server[497]: 2016-05-27 10:28:52 INFO: udp port reuse enabled May 27 10:28:52 simonsmh ss-server[497]: 2016-05-27 10:28:52 INFO: listening at 0.0.0.0:143 May 27 10:28:52 simonsmh ss-server[497]: 2016-05-27 10:28:52 INFO: port reuse enabled May 27 10:28:52 simonsmh ss-server[497]: 2016-05-27 10:28:52 INFO: udp port reuse。 enabled May 27 10:28:52 simonsmh ss-server[497]: 2016-05-27 10:28:52 INFO: listening at ::0:143 
May 27 10:32:14 simonsmh ss-server[497]: 2016-05-27 10:32:14 ERROR: getpeername: Transport endpoint is not connected
May 27 10:32:14 simonsmh ss-server[497]: 2016-05-27 10:32:14 ERROR: getpeername: Transport endpoint is not connected
May 27 10:32:21 simonsmh ss-server[497]: 2016-05-27 10:32:21 ERROR: getpeername: Transport endpoint is not connected
May 27 10:32:21 simonsmh ss-server[497]: 2016-05-27 10:32:21 ERROR: getpeername: Transport endpoint is not connected
May 27 10:32:33 simonsmh ss-server[497]: 2016-05-27 10:32:33 ERROR: getpeername: Transport endpoint is not connected
May 27 10:32:34 simonsmh ss-server[497]: 2016-05-27 10:32:34 ERROR: getpeername: Transport endpoint is not connected
May 27 10:32:57 simonsmh ss-server[497]: 2016-05-27 10:32:57 ERROR: getpeername: Transport endpoint is not connected
May 27 10:32:58 simonsmh ss-server[497]: 2016-05-27 10:32:58 ERROR: getpeername: Transport endpoint is not connected
May 27 10:33:44 simonsmh ss-server[497]: 2016-05-27 10:33:44 ERROR: getpeername: Transport endpoint is not connected
May 27 10:34:55 simonsmh ss-server[497]: 2016-05-27 10:34:55 ERROR: getpeername: Transport endpoint is not connected
May 27 10:34:55 simonsmh ss-server[497]: 2016-05-27 10:34:55 ERROR: getpeername: Transport endpoint is not connected
May 27 10:35:10 simonsmh ss-server[497]: 2016-05-27 10:35:10 ERROR: getpeername: Transport endpoint is not connected
May 27 10:35:11 simonsmh ss-server[497]: 2016-05-27 10:35:11 ERROR: getpeername: Transport endpoint is not connected
May 27 10:36:49 simonsmh ss-server[497]: 2016-05-27 10:36:49 ERROR: getpeername: Transport endpoint is not connected
May 27 10:36:49 simonsmh ss-server[497]: 2016-05-27 10:36:49 ERROR: getpeername: Transport endpoint is not connected
May 27 10:37:05 simonsmh ss-server[497]: 2016-05-27 10:37:05 ERROR: getpeername: Transport endpoint is not connected
May 27 10:37:06 simonsmh ss-server[497]: 2016-05-27 10:37:06 ERROR: getpeername: Transport endpoint is not connected
May 27 10:37:37 simonsmh ss-server[497]: 2016-05-27 10:37:37 ERROR: getpeername: Transport endpoint is not connected
May 27 10:37:38 simonsmh ss-server[497]: 2016-05-27 10:37:38 ERROR: getpeername: Transport endpoint is not connected
May 27 10:38:40 simonsmh ss-server[497]: 2016-05-27 10:38:40 ERROR: getpeername: Transport endpoint is not connected
May 27 10:38:40 simonsmh ss-server[497]: 2016-05-27 10:38:40 ERROR: getpeername: Transport endpoint is not connected
May 27 10:41:48 simonsmh ss-server[497]: 2016-05-27 10:41:48 ERROR: getpeername: Transport endpoint is not connected
May 27 10:42:58 simonsmh ss-server[497]: 2016-05-27 10:42:58 ERROR: getpeername: Transport endpoint is not connected
May 27 10:42:58 simonsmh ss-server[497]: 2016-05-27 10:42:58 ERROR: getpeername: Transport endpoint is not connected
May 27 10:44:21 simonsmh ss-server[497]: 2016-05-27 10:44:21 ERROR: getpeername: Transport endpoint is not connected
May 27 10:44:22 simonsmh ss-server[497]: 2016-05-27 10:44:22 ERROR: getpeername: Transport endpoint is not connected
May 27 10:44:35 simonsmh ss-server[497]: 2016-05-27 10:44:35 ERROR: getpeername: Transport endpoint is not connected
May 27 10:44:35 simonsmh ss-server[497]: 2016-05-27 10:44:35 ERROR: getpeername: Transport endpoint is not connected
May 27 10:46:09 simonsmh ss-server[497]: 2016-05-27 10:46:09 ERROR: getpeername: Transport endpoint is not connected
May 27 10:46:10 simonsmh ss-server[497]: 2016-05-27 10:46:10 ERROR: getpeername: Transport endpoint is not connected
May 27 10:46:29 simonsmh ss-server[497]: 2016-05-27 10:46:29 ERROR: getpeername: Transport endpoint is not connected

**Comment by simonsmh** [comment]
I'm using the newest commit. 
Please fix it.
Thanks for your work.

**Comment by madeye** [comment]
Double check your network.
