### ISSUE TITLE
udp转发的问题

### ISSUE THREAD

**Issue by pexcn** [shadowsocks/shadowsocks-libev#655]
由于运营商的问题，在我这里使用udp转发一段时间就不能使用了，导致udp转发无法解析域名。

通过`dig google.com @xx.xx.xx.xx -p xx`检查，无法得到解析的结果。
但是`dig google.com @xx.xx.xx.xx -p xx +tcp`则可以得到解析结果。

请问一下作者，以后会提供类似`pdnsd`的`TCP查询`这样的功能吗？

**Comment by pexcn** [comment]
这个主要是在路由器上用，能不能提供一个udp转发的模式之类的？比如默认udp或者udp包通过tcp发送？

**Comment by pexcn** [comment]
类似这个：[https://github.com/aa65535/openwrt-chinadns/issues/54](https://github.com/aa65535/openwrt-chinadns/issues/54)

**Comment by madeye** [comment]
No plan for this. Use pdnsd as UDP to TCP DNS proxy.

**Comment by pexcn** [comment]
Thanks.

**Comment by gaocuo** [comment]
pdnsd 在路由上占用资源有点多，峰值有30多M。

**Comment by madeye** [comment]
Try `unbound` if you have limited resource.

**Comment by gaocuo** [comment]
ok, thanks. I will try.

**Comment by pexcn** [comment]
What is `unbound`?

**Comment by gaocuo** [comment]
Unbound is a validating, recursive, and caching DNS resolver.

**Comment by pexcn** [comment]
But...how to use it ? For `pdnsd` ? or `shadowsocks` ?

**Comment by pexcn** [comment]
Ok... Now I know.
