### ISSUE TITLE
what is udprelay mode

### ISSUE THREAD

**Issue by ZekeLee** [shadowsocks/shadowsocks-libev#657]
how it works? I searched everywhere and still get confused...
and how ss-tunnel works

are they the same thing ?

**Comment by ZekeLee** [comment]
I use OpenWrt and pndsd and it's works well, I just didn't understand how to use udp relay mode and the ss-tunnel

**Comment by madeye** [comment]
Read the document. All specs of protocol can be found on the official website.

**Comment by ZekeLee** [comment]
@madeye The wiki document  https://github.com/shadowsocks/shadowsocks/wiki ?

This is for python edition and I can't find the introduction of udp relay mode and ss-tunnel.

真的不是伸手党，google了好几天也没弄清楚udp-relay和ss-tunnel的作用，没找到任何详细的说明，都是一带而过。
我现在这两个都没使用，就想知道他们的作用
