### ISSUE TITLE
ss-redir 用rc4-md5 错误，aes-256-cfb 正常

### ISSUE THREAD

**Issue by ejcjason** [shadowsocks/shadowsocks-libev#659]
版本信息：
ss-erver: shadowsocks-libev 2.4.5-2.4.7 都测试过
ss-redir:  shadowsocks-libev 2.3.0
问题说明：
ss-redir 和ss-server method同时设置为rc4-md5，报错：getpeername: Transport endpoint is not connected，但是用shadowsocks-OSX在同一网络环境，系统直接连接正常。
ss-redir 和ss-server method同时设置为aes-256-cfb，一切正常。

**Comment by madeye** [comment]
According to your log, it has nothing to do with encryption.
