### ISSUE TITLE
Error when make in windows

### ISSUE THREAD

**Issue by 404neko** [shadowsocks/shadowsocks-libev#660]
$ make && make install
D:/Bin/TDM-GCC/TDM-GCC-64/bin/make  all-recursive
make[1]: Entering directory 'H:/shadowsocks-libev-2.4.7'
Making all in libsodium
make[2]: Entering directory 'H:/shadowsocks-libev-2.4.7/libsodium'
Making all in src
make[3]: Entering directory 'H:/shadowsocks-libev-2.4.7/libsodium/src'
Making all in libsodium
make[4]: Entering directory 'H:/shadowsocks-libev-2.4.7/libsodium/src/libsodium'
/usr/bin/sh: -c: line 1: unexpected EOF while looking for matching `''
/usr/bin/sh: -c: line 2: syntax error: unexpected end of file
Makefile:3543: recipe for target 'all-recursive' failed
make[4]: *** [all-recursive] Error 1
make[4]: Leaving directory 'H:/shadowsocks-libev-2.4.7/libsodium/src/libsodium'
Makefile:366: recipe for target 'all-recursive' failed
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory 'H:/shadowsocks-libev-2.4.7/libsodium/src'
Makefile:415: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory 'H:/shadowsocks-libev-2.4.7/libsodium'
Makefile:549: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory 'H:/shadowsocks-libev-2.4.7'
Makefile:371: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by madeye** [comment]
Make sure you're building with latest MingW.
