### ISSUE TITLE
Openwrt compile error

### ISSUE THREAD

**Issue by 1558204459** [shadowsocks/shadowsocks-libev#663]
When i compile the shadowsocks for my openwrt route
It give me an error:
         configure: error: mbed TLS libraries not found.
how to solve it?

**Comment by madeye** [comment]
As the error said, you need mbed TLS library compiled first.

**Comment by wongsyrone** [comment]
Nope.

check https://github.com/wongsyrone/lede-1/blob/master/package/libs/mbedtls/patches/999-tweak-config-for-shadowsocks.patch and apply this to your codebase

**Comment by wongsyrone** [comment]
The root cause is some ciphers are disabled by default, just re-enable them to pass the configure stage.

**Comment by 1558204459** [comment]
Which file should i modify?

**Comment by wongsyrone** [comment]
You can simply put the patch above into `package/libs/mbedtls/patches` or edit the patch exists via quilt yourself.

**Comment by xayane** [comment]
额，请教下：
我这边提示的是“MBEDTLS_CIPHER_MODE_CFB required”，但是我这里没有大神所说的目录“package/libs/mbedtls/patches ”。
我只在m4/mbedtls.m4 看到了相关语句：
“AC_MSG_CHECKING([whether mbedtls supports Cipher Feedback mode or not])
  AC_COMPILE_IFELSE(
    [AC_LANG_PROGRAM(
      [[
#include <mbedtls/config.h>
      ]],
      [[
#ifndef MBEDTLS_CIPHER_MODE_CFB
#error Cipher Feedback mode a.k.a CFB not supported by your mbed TLS.
#endif
      ]]
    )],
    [AC_MSG_RESULT([ok])],
    [AC_MSG_ERROR([MBEDTLS_CIPHER_MODE_CFB required])]
  )
”

那我应该怎么修改呢。。。

**Comment by wongsyrone** [comment]
你需要重新编译mbedtls，默认OP的patch会关闭cfb，这样大部分加密都不可用了

**Comment by wongsyrone** [comment]
如果不会自己修改，复制 https://github.com/wongsyrone/lede-1/tree/master/package/libs/mbedtls 到 SDK的package目录里面，重新编译。那个补丁的意思是重新打开cfb, rc4, blowfish, camellia以及默认开启多线程支持，使用libpthread，musl的话是在libc里面，旧uclibc是单独的一个库。

**Comment by xayane** [comment]
Thanks for your detailed reply.
i just copyed https://github.com/wongsyrone/lede-1/tree/master/package/libs/mbedtls to SDK's package and typed “make V=99 package/mbedtls/compile” , and no errors.
then i re-compiled the  shadowsocks-libev by "make V=99 package/shadowsocks-libev/openwrt/compile", but the console showed the same error "MBEDTLS_CIPHER_MODE_CFB required"
well, is there something i did wrong?

PS：今天被教育了，github是一个全球平台，我用中文询问回答，这样别国的人在遇到相同的问题，就没法直接获得答案，还要耽误大家的时间，我以后把答案改成英文。

**Comment by tianlichunhong** [comment]
应该是copy到feeds/base/package/libs/mbedtls吧，我直接拷贝到SDK目录下的package不可以。

**Comment by ky0ncheng** [comment]
wget https://tls.mbed.org/download/mbedtls-2.4.0-gpl.tgz
tar -zxvf mbedtls-2.4.0-gpl.tgz
cd mbedtls-2.4.0
make
make install

**Comment by kevinzu007** [comment]
安装mbedtls-devel  或  libmbedtls-devel  或  libmbedtls-deve即可

**Comment by easoncxz** [comment]
Turns out the default package repositories for Ubuntu 16.04 contains the package `libmbedtls-dev`, which seems to resolve this dependency.
