### ISSUE TITLE
Can shadowsocks run with no encryption method,just as a proxy

### ISSUE THREAD

**Issue by 1558204459** [shadowsocks/shadowsocks-libev#665]

**Comment by madeye** [comment]
Nope.

**Comment by 1558204459** [comment]
Why?
Is there any way?
I just need to use it as a proxy

**Comment by celeron533** [comment]
@1558204459 , is it possible to use [Squid](http://www.squid-cache.org/) and setup authentication for you?

**Comment by spyff** [comment]
I created a fork for that

https://github.com/spyff/shadowsocks-libev-nocrypto
