### ISSUE TITLE
UDP转发功能故障

### ISSUE THREAD

**Issue by pexcn** [shadowsocks/shadowsocks-libev#667]
openwrt版本的问题，但是我觉得应该是上游项目的问题，所以发这里了。

我用pdnsd用作tcp查询解决dns污染，pdnsd端口是25，我在udp转发填写了`127.0.0.1:25`，本地udp转发的端口为`5300`，所以chinadns填写了`223.5.5.5,127.0.0.1:5300`

然后就有时候遇到无法解析的问题。通过dig排查：`dig google.com @192.168.1.1 -p 25`可以解析出结果。然后`dig google.com @192.168.1.1 -p 5300`就一直超时。重启shadowsocks, chinadns, pdnsd, dnsmasq都无法解决问题。最后重启路由器解决，这样的问题非常偶然，但是遇到多次了，很抱歉没有抓到log.

然后在chinadns改成`223.5.5.5,127.0.0.1:25`可以解决问题，但是有时候通过[ip.cn](ip.cn)这样的网站检查自己的ip发现是vps的ip，但是通过`223.5.5.5`解析`ip.cn`的服务器并不在国外。所以只好改回`223.5.5.5,127.0.0.1:5300`用udp转发pdnsd的端口了。

**Comment by madeye** [comment]
I cannot reproduce your issue locally. It looks like a network issue of your service provider or your ISP.

Also, the issue of ip.cn is related to chinadns. You may try to set rules in dnsmasq instead.

**Comment by gaocuo** [comment]
既然用了pdnsd做防投毒，就直接用8.8.8.8的tcp做upstream，然后把做个8.8.8.8的output走ss通道就好了
