### ISSUE TITLE
ss-server with open udp port?

### ISSUE THREAD

**Issue by xnoreq** [shadowsocks/shadowsocks-libev#669]
After I start ss-server it just listens on the tcp server port that I have configured. Fine.
But as soon as I connect with a client it starts listening on :: (that's IPv6) with a random port (I've seen >40000 so far), udp.

Why? What is it doing on this port? Why is it listening on a wildcard IPv6 address?

**Comment by madeye** [comment]
Make sure you didn't enable UDP relay.

**Comment by xnoreq** [comment]
No, I haven't enabled UDP relay. And even if, my config says server: "0.0.0.0" (IPv4 wildcard). Both server and client are not configured to use IPv6.
So it makes no sense why it is listening on :: udp.

PS: Please don't close issues that are not resolved yet.

**Comment by madeye** [comment]
If so, the UDP port is for DNS resolve. Shadowsocks-libev handles DNS queries by itself.

https://github.com/shadowsocks/shadowsocks-libev/tree/master/libudns

**Comment by xnoreq** [comment]
That is bad design. Query DNS source ports should be random.
http://www.kb.cert.org/vuls/id/800113

**Comment by xnoreq** [comment]
Also, if the nameserver is 127.0.0.1 or ::1 there is no need to bind to anything but those loopback addresses.
Just making suggestions to improve security.

**Comment by hosiet** [comment]
In https://github.com/shadowsocks/shadowsocks-libev/blob/v2.4.7/libudns/NOTES it has  stated a lot of its disadvantages and possible vulnabilities already, and is well aware of its design as a "stub resolver".

A real solution to the problem may be fixing them upstream, or use an alternative library. The problem would be hard to fix otherwise.

**Comment by madeye** [comment]
As mentioned by @hosiet, if you want to improve the security, you may use a local resolver by specifying it with `-d <local_resolver>`.
