### ISSUE TITLE
ss-local如何使用配置文件？

### ISSUE THREAD

**Issue by VampireSH** [shadowsocks/shadowsocks-libev#670]
ss-server可以使用配置文件用-c，那么ss-local有没有这个用法？我看man中没有说到如何使用配置文件？？？

**Comment by hosiet** [comment]
https://github.com/shadowsocks/shadowsocks-libev/blob/v2.4.7/man/ss-local.1#L83

**Comment by VampireSH** [comment]
我的意思是配置文件的格式怎么写，用-c这个我还是知道的，可能是我上面表达不清楚吧

**Comment by madeye** [comment]
https://shadowsocks.org/en/config/quick-guide.html

**Comment by VampireSH** [comment]
就是说local和server用同一个配置文件啰？
