### ISSUE TITLE
Cannot download podcasts hosted on SoundCloud

### ISSUE THREAD

**Issue by AndreaVEH** [shadowsocks/shadowsocks-libev#674]
When using AntennaPod to download podcasts or update the feeds hosted on SoundCloud, there is usually an error. The Downloads log of AntennaPod is ' IO Error: Failed to connect to feeds-tmp.soundcloud.com/200:2:cb62:741:::80'. And several podcasts always get the same error message. Other podcasts that are not hosted on SoundCloud can be downloaded normally.

**Comment by madeye** [comment]
I don't think it's related to shadowsocks. Double check the network of your server.

**Comment by AndreaVEH** [comment]
But I can directly download the podcasts using wget hosted on SoundCloud on the server. 

Here is the message from command line:
wget -v http://feeds.soundcloud.com/stream/268646041-thetalkshow-157-dan-frommer.mp3
--2016-06-12 10:35:25--  http://feeds.soundcloud.com/stream/268646041-thetalkshow-157-dan-frommer.mp3
Resolving feeds.soundcloud.com (feeds.soundcloud.com)... 72.21.91.127
Connecting to feeds.soundcloud.com (feeds.soundcloud.com)|72.21.91.127|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://feeds-tmp.soundcloud.com/stream/268646041-thetalkshow-157-dan-frommer.mp3 [following]
--2016-06-12 10:35:26--  http://feeds-tmp.soundcloud.com/stream/268646041-thetalkshow-157-dan-frommer.mp3
Resolving feeds-tmp.soundcloud.com (feeds-tmp.soundcloud.com)... 72.21.91.127
Reusing existing connection to feeds.soundcloud.com:80.
HTTP request sent, awaiting response... 302 Found
Location: http://ec-media.sndcdn.com/rMFR7HtohWlx?f10880d39085a94a0418a7ef61b03d5275edf83695e0cd6a5a31b907ecb279595bfc0e52f21563a91e73fa969eb2512225d6a71a618becdea17d8ca43c [following]
--2016-06-12 10:35:26--  http://ec-media.sndcdn.com/rMFR7HtohWlx?f10880d39085a94a0418a7ef61b03d5275edf83695e0cd6a5a31b907ecb279595bfc0e52f21563a91e73fa969eb2512225d6a71a618becdea17d8ca43c
Resolving ec-media.sndcdn.com (ec-media.sndcdn.com)... 72.21.81.77
Connecting to ec-media.sndcdn.com (ec-media.sndcdn.com)|72.21.81.77|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 104352705 (100M) [audio/mpeg]
Saving to: ‘268646041-thetalkshow-157-dan-frommer.mp3’

268646041-thetalkshow-15 100%[=================================>]  99.52M   103MB/s    in 1.0s    

2016-06-12 10:35:27 (103 MB/s) - ‘268646041-thetalkshow-157-dan-frommer.mp3’ saved [104352705/104352705]

I used **curl** first to download this podcast but failed, and I used **wget**, it succeeded.

**Comment by madeye** [comment]
I tried your link locally. It works well:

 ~> socksify wget http://feeds.soundcloud.com/stream/268646041-thetalkshow-157-dan-frommer.mp3
--2016-06-12 18:58:41--  http://feeds.soundcloud.com/stream/268646041-thetalkshow-157-dan-frommer.mp3
Resolving feeds.soundcloud.com (feeds.soundcloud.com)... 0.0.0.1
Connecting to feeds.soundcloud.com (feeds.soundcloud.com)|0.0.0.1|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://feeds-tmp.soundcloud.com/stream/268646041-thetalkshow-157-dan-frommer.mp3 [following]
--2016-06-12 18:58:42--  http://feeds-tmp.soundcloud.com/stream/268646041-thetalkshow-157-dan-frommer.mp3
Resolving feeds-tmp.soundcloud.com (feeds-tmp.soundcloud.com)... 0.0.0.2
Connecting to feeds-tmp.soundcloud.com (feeds-tmp.soundcloud.com)|0.0.0.2|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://ec-media.sndcdn.com/rMFR7HtohWlx?f10880d39085a94a0418a7ef61b03d5275edf83695e0cd6a5a31b907ecb27855776575803f68d0e6aa2666eff25eaf6d1e491c8c769de0b46a64db00a8 [following]
--2016-06-12 18:58:43--  http://ec-media.sndcdn.com/rMFR7HtohWlx?f10880d39085a94a0418a7ef61b03d5275edf83695e0cd6a5a31b907ecb27855776575803f68d0e6aa2666eff25eaf6d1e491c8c769de0b46a64db00a8
Resolving ec-media.sndcdn.com (ec-media.sndcdn.com)... 0.0.0.3
Connecting to ec-media.sndcdn.com (ec-media.sndcdn.com)|0.0.0.3|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 104352705 (100M) [audio/mpeg]
Saving to: ‘268646041-thetalkshow-157-dan-frommer.mp3’

100%[==============================================================================>] 104,352,705 29.8MB/s   in 3.8s

2016-06-12 18:58:46 (26.4 MB/s) - ‘268646041-thetalkshow-157-dan-frommer.mp3’ saved [104352705/104352705]

**Comment by AndreaVEH** [comment]
Sorry, I forgot to mention that the problem happened on my Nexus 5, but it's OK on the computer using chrome to download the same podcast via shadowsocks.

**Comment by AndreaVEH** [comment]
After latest AntennaPod update, the problem has gone. It seems the failure of downloading podcasts hosted on SoundCloud happened on the AntennaPod side. Sorry to disturb.

**Comment by AndreaVEH** [comment]
Just now the same problem occurred again. Only the podcasts hosted on SoundCloud would have the failure problem. Maybe the problem is on the SoundCloud side?
