### ISSUE TITLE
优化fast open特性

### ISSUE THREAD

**Issue by s7lx** [shadowsocks/shadowsocks-libev#675]
tcp fast open和锐速同时安装，可能导致访问google的时候被当做syn洪水攻击而被拒绝连接。
建议发现tcp fast open连接失败后自动关闭这个特性进行通信

**Comment by madeye** [comment]
No plan for this.

**Comment by blackgear** [comment]
> 解决方法很简单，配置锐速的shortRttMS参数即可，比如GCE上ping谷歌rtt约0.3ms，设置该参数为1就能让锐速跳过对访问谷歌的单向加速，但仍然保留到客户端的单向加速。
> https://twitter.com/atomhelix/status/852000755175235584
