### ISSUE TITLE
Have you stopped distribute the new version on debian repository servers?

### ISSUE THREAD

**Issue by GitatHub** [shadowsocks/shadowsocks-libev#676]
My vps is over debian 8 and keeping update ss-libev with source http://shadowsocks.org/debian wheezy main ,
but the running version have been at version 2.4.0 for months.
I see that the current release is 2.4.7, so have you stopped distribute the latest version over linux repos?
Thanks.

**Comment by madeye** [comment]
Build the package from the source code.

**Comment by GitatHub** [comment]
alright, it seems that http://shadowsocks.org/debian/ is no longer maitained.
