### ISSUE TITLE
About shadowsocks manager API

### ISSUE THREAD

**Issue by gyteng** [shadowsocks/shadowsocks-libev#682]
I developed a web-ui based on shadowsocks manager API. It can control shadowsocks server add/remove ports without restart server, so people can use it to share to others. Now I found that manager API is too simple, it need some new APIs.

Now, we have 3 commands for manager API:

1. `add: {"server_port": 8001, "password":"7cd308cc059"}`
1. `remove: {"server_port": 8001}`
1. `ping`

and we can reveive transfer statistics:

`stat: {"8001":11370}`

When the shadowsocks server is down and restart later, we don't know which ports we have added for it. So I think we need a new API like this:

send: `port`

and shadowsocks server will return the ports and password we have added:

`port: {"10000": "foo", "10001": "bar"}`

**Comment by madeye** [comment]
If the shadowsocks server is restarted, I think you can safely assume all the ports are cleared. Otherwise, you may list all the ports first and remove all existing ports.

Also, for security reason, I prefer not to storing and returning the password.

**Comment by madeye** [comment]
It's possible that only `ss-manager` crashes. For this situation, I will add a cleanup process when starting the `ss-manager`.

**Comment by gyteng** [comment]
But the manager part don't know when the server is restarted, so it have to add all the ports in several minutes again and again.

**Comment by gyteng** [comment]
And another reason is that manager API is base on UDP socket, when I send an `add` command or `remove` command, I don't know if the command is success in shadowsocks server.

**Comment by madeye** [comment]
I think you can have these assumptions:

1. If a `ss-server` crashed, user would restart it manually (`remove` and then `add`). Or you can write a ping test to detect the crash and restart automatically. If `ss-server` keeps crashing, double check your server's config.
2. If `ss-manager` restarts, all existed `ss-server` would be killed, or in other word, no old instances of `ss-server` are running after `ss-manager` starts.
3. After `add` or `remove`, there is always a `ok` sent back. If not, send the command again.
4. A `ping` can return the current list of ports opened. The best practice is to let one 'port' representing one `user`.

**Comment by gyteng** [comment]
It is a great solution, thx.
