### ISSUE TITLE
RPM build error (trunk)

### ISSUE THREAD

**Issue by debiansid** [shadowsocks/shadowsocks-libev#683]
sh genrpm.sh 
~/shadowsocks-libev ~/shadowsocks-libev/rpm
fatal: Unknown archive format 'tar.gz'

**Comment by madeye** [comment]
You have to debug the issue yourself. RPM is not officially supported.

**Comment by librehat** [comment]
You should use Copr repository where possible. Unless you're using non-RH distributions.

**Comment by debiansid** [comment]
I am trying to build rpm from trunk

**Comment by Cye3s** [comment]
To build 2.4.8+ rpm, you need to modify this file:
xxx/rpm/SPECS/shadowsocks-libev.spec
add this line under "%doc ${_mandir}":  %doc %{_defaultdocdir}/*
Then rpmbuild will package the new /usr/share/doc/shadowsocks-libev/*.html files.
 
Or just add this line to spec file:
%define _unpackaged_files_terminate_build 0
to ignore new html files.

Then:
sh genrpm.sh -f tar -v 2.4.8

You may need to "yum install asciidoc xmlto" first.
