### ISSUE TITLE
Better init script

### ISSUE THREAD

**Issue by euphoria360** [shadowsocks/shadowsocks-libev#684]
Hi.
When I started using this great software, I found out unlike other versions (GO, Python ...), I cant use "port_password" config option with it. since the software uses minimal resources, it was suggested to run several instances of it on different ports by creating different json config files. Well that is a GOOD approach, but if we want to make things automatic at startup things get ugly. Using rc.d is not a good way of starting a service and the init provided only opens one instance (/etc/shadowsocks-libev/config.json).

I tried to solve this by using a better init script which searches for jsons in "/etc/shadowsocks-libev" and opens an instance with each one. here is the init sript:
[http://pastebin.com/tdDVwzus](url)

the init creates new pid's for each instances. So far it worked great for me (centos 6.5) and it should be compatible with debian too.. if possible please include it, so others can enjoy it too.

**Comment by madeye** [comment]
Try this: https://github.com/shadowsocks/shadowsocks-manager
