### ISSUE TITLE
建议：当密码错误的时候，解析出来的域名明显有些是非法字符，可以对这个域名做个判断，当有非法字符的时候直接关断连接.

### ISSUE THREAD

**Issue by bloomsource** [shadowsocks/shadowsocks-libev#685]
我自己改的server版本加了这个功能。

**Comment by wongsyrone** [comment]
密码错误直接进黑名单了吧

**Comment by bloomsource** [comment]
不能简单进入黑名单，因为有时候你填错了密码会出现很多次这样的错误。

**Comment by madeye** [comment]
Enable `OTA` if you need to avoid invalid DNS query.

**Comment by wongsyrone** [comment]
目前libev的实际就是加黑名单，你不能区分具体行为，至于误封可以弄一个移除，因为你知道自己的ip，如果自己用可以简单重启服务端
