### ISSUE TITLE
question:is it possible to disable blacklist

### ISSUE THREAD

**Issue by sophauer** [shadowsocks/shadowsocks-libev#686]
hi,
many users could be rejected by server side due to password incorrect setup in client side,so
is it possible to disable server side 's put source IP to blacklist function

**Comment by madeye** [comment]
Black list is enabled if and only if you enabled OTA.

**Comment by sophauer** [comment]
thx for your quick reply,dude
but i'm pretty sure that i didn't run ss-server with -A(Enable OTA),and still,put source IP to blacklist function worked under version the newest version SS-libevc(centos 7 64 bit)

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks-libev/blob/master/src/server.c#L653

Two pre-conditions:

1. ACL is enabled and configured to black list mode.
2. OTA is enabled and get authentication errors.
