### ISSUE TITLE
ss-tunnel经常失效

### ISSUE THREAD

**Issue by ss-plus** [shadowsocks/shadowsocks-libev#689]
最近两个月，ss-tunnel频繁失效，必须隔段时间重启ss-tunnel才能通过它正常解析被污染的dns地址，但ss-redir和ss-local不受影响，能不能解决下ss-tunnel做dns解析频繁被污染的问题。

**Comment by madeye** [comment]
It looks like a QoS issue of your ISP or service provider. Try to deploy a UDP only server on a low port number, e.g. 53.
