### ISSUE TITLE
Should I select which Arch(MIPS/ARM) WiFi route for better ss support?

### ISSUE THREAD

**Issue by zw963** [shadowsocks/shadowsocks-libev#692]
Sorry for ask this problem here.

I want to buy a WIFI routes, use `merlin` or `openwrt' as firmware. 

I found more more older (and cheaper) route is `MIPS` arch, and
newer (and more price) is ARM.

I think those two arch binary format is not same, and maybe exist
some wired things when use ss client.

for the better use with ss, how should I to select?

**Comment by madeye** [comment]
OpenWRT and ARM are recommended.
