### ISSUE TITLE
Consider stripping invariant section from man pages

### ISSUE THREAD

**Issue by hosiet** [shadowsocks/shadowsocks-libev#693]
GFDL-licensed documents with invariant sections [are not DFSG-compatible](https://wiki.debian.org/DFSGLicenses#GNU_Free_Documentation_License_.28GFDL.29).

The invarient sections in current man pages are [mostly placeholders and meaningless words](https://github.com/shadowsocks/shadowsocks-libev/blob/master/man/shadowsocks-libev.8#L13). Please consider removing invariant sections in all man pages according to [the guide from Debian Wiki](https://wiki.debian.org/qa.debian.org/gfdlinvariant) to fit the requirement of Debian.

Thanks.

**Comment by madeye** [comment]
Maybe you can open a pull request. I'm not sure how to meet the requirements of Debian.

**Comment by hosiet** [comment]
Closed via #694.
