### ISSUE TITLE
[man page re-organize] Use asciidoc or markdown to replace current man pages

### ISSUE THREAD

**Issue by anonymous-contributor** [shadowsocks/shadowsocks-libev#696]
If no objection, I'd like to convert current manually coded man pages to asciidoc or markdown (I prefer asciidoc though).

As asciidoc is much easier to read, and can be output to html.

Thanks,
Adam

**Comment by madeye** [comment]
Of course.

**Comment by anonymous-contributor** [comment]
Thank you, I'll start the convert, and add jscon config vs command line parameter table.
