### ISSUE TITLE
您好，我在编译ss-libev时出现问题

### ISSUE THREAD

**Issue by wjz2001** [shadowsocks/shadowsocks-libev#701]
编译时显示以下错误：
make[2]: Leaving directory `/root/shadowsocks-libev/src'
Making all in doc
make[2]: Entering directory `/root/shadowsocks-libev/doc'
    [ASCII]  ss-local.xml
/bin/sh: 2: asciidoc: not found
make[2]: *** [ss-local.xml] Error 127
make[2]: Leaving directory `/root/shadowsocks-libev/doc'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/root/shadowsocks-libev'
make: *** [all] Error 2
请问会不会是代码有bug？

**Comment by pexcn** [comment]
Please install `asciidoc`.

**Comment by wongsyrone** [comment]
You can pass in `--disable-documentation` when `./configure`, the option issue has been fixed, please try latest commit.

**Comment by AUGxhub** [comment]
asciidoc is about 1G,and you have to download only for complie this ,it's not necessary.
  so the xiaomai's method is more effect
