### ISSUE TITLE
如何在server端中的.json 配置文件中配置自定义DNS

### ISSUE THREAD

**Issue by ygqsgm** [shadowsocks/shadowsocks-libev#702]
只有在命令行中 使用 -d 命令吗?
另试过改网卡的DNS但仍然是用原来的DNS。

**Comment by wongsyrone** [comment]
尝试
```
"nameserver":"8.8.8.8"
```

**Comment by ygqsgm** [comment]
@wongsyrone 谢谢，但是似乎不起作用。 我使用的系统是centos 6.5，不知是否与此有关系？

**Comment by ygqsgm** [comment]
形如 nohup ss-server -s 0.0.0.0 -p 1234 -k 12345 -m rc4-md5 -t 360 -d 8.8.4.4 -u &  即可用8844替代8888
