### ISSUE TITLE
README iptables not make effect for non ss-redir proxy?

### ISSUE THREAD

**Issue by zw963** [shadowsocks/shadowsocks-libev#703]
Following is my process:

1. In my ASUS RT-AC66U,  ss-redir listen on 1081, privoxy listen on 3128.
2. Following code from README [advanced-usage](https://github.com/shadowsocks/shadowsocks-libev#advanced-usage) worked for ss-redir, but not worked for privoxy.

worked version
```sh
iptables -t nat -F SHADOWSOCKS
iptables -t nat -N SHADOWSOCKS
iptables -t nat -A SHADOWSOCKS -d 202.56.13.13 -j RETURN
iptables -t nat -A SHADOWSOCKS -d 0.0.0.0/8 -j RETURN
iptables -t nat -A SHADOWSOCKS -d 10.0.0.0/8 -j RETURN
iptables -t nat -A SHADOWSOCKS -d 127.0.0.0/8 -j RETURN
iptables -t nat -A SHADOWSOCKS -d 169.254.0.0/16 -j RETURN
iptables -t nat -A SHADOWSOCKS -d 172.16.0.0/12 -j RETURN
iptables -t nat -A SHADOWSOCKS -d 192.168.0.0/16 -j RETURN
iptables -t nat -A SHADOWSOCKS -d 224.0.0.0/4 -j RETURN
iptables -t nat -A SHADOWSOCKS -d 240.0.0.0/4 -j RETURN
# 1081 is redir port.
iptables -t nat -A SHADOWSOCKS -p tcp -j REDIRECT --to-ports 1081
iptables -t nat -A PREROUTING -p tcp -j SHADOWSOCKS
```

Not worked version
```sh
iptables -t nat -F SHADOWSOCKS
iptables -t nat -N SHADOWSOCKS
iptables -t nat -A SHADOWSOCKS -d 202.56.13.13 -j RETURN
iptables -t nat -A SHADOWSOCKS -d 0.0.0.0/8 -j RETURN
iptables -t nat -A SHADOWSOCKS -d 10.0.0.0/8 -j RETURN
iptables -t nat -A SHADOWSOCKS -d 127.0.0.0/8 -j RETURN
iptables -t nat -A SHADOWSOCKS -d 169.254.0.0/16 -j RETURN
iptables -t nat -A SHADOWSOCKS -d 172.16.0.0/12 -j RETURN
iptables -t nat -A SHADOWSOCKS -d 192.168.0.0/16 -j RETURN
iptables -t nat -A SHADOWSOCKS -d 224.0.0.0/4 -j RETURN
iptables -t nat -A SHADOWSOCKS -d 240.0.0.0/4 -j RETURN
# 318 is privoxy proxy.
iptables -t nat -A SHADOWSOCKS -p tcp -j REDIRECT --to-ports 3128
iptables -t nat -A PREROUTING -p tcp -j SHADOWSOCKS
```

I just want to redirect all my traffic to privoxy, and, directly use 3128 in browser
is worked (3128 is correct listening on my route), but, it not worked.
my route ip address is 192.168.1.1, my pc ip use dhcp, 192.168.1.131

Could you please give me some clue about this?

Thanks

**Comment by madeye** [comment]
These rules are for `ss-redir` only.

**Comment by rampageX** [comment]
Add: 

    accept-intercepted-requests 1

to your privoxy configuration file.

But, only HTTP work, HTTPS not work.

**Comment by zw963** [comment]
> accept-intercepted-requests 1

Added. Still not worked.

> But, only HTTP work, HTTPS not work.
maybe this is the reason cause this. thanks.

**Comment by zw963** [comment]
@rampageX ,

 But, when I use privoxy proxy (port 3128) globally in my browser(or setting globally in my system), it seem like worked very well for any http/https website, e.g. youtube, facebook, twitter etc ...

In this case, How to explain  `privoxy is not support https` ?

**Comment by rampageX** [comment]
@zw963 
Just **intercepted mode** do not support HTTPS. You can read privoxy's documents.
