### ISSUE TITLE
disable-documentation

### ISSUE THREAD

**Issue by maxchendt** [shadowsocks/shadowsocks-libev#712]
For asciidoc needs  1,165 MB of additional disk space, I decide to disable --disable-documentation
`./configure --disable-documentation`
and great, succeed in compiling
`make`
however, not able to build deb on Ubuntu 14.04
`dpkg-buildpackage -us -uc -d -b -i`
https://github.com/shadowsocks/shadowsocks-libev/issues/701  comes back again

**Comment by madeye** [comment]
To build deb, `asciidoc` and `xmlto` are required.

**Comment by wongsyrone** [comment]
You may want to add the configure option to https://github.com/shadowsocks/shadowsocks-libev/blob/master/debian/rules#L19, but I'm not sure about it.
Any reason to install deb?

**Comment by hosiet** [comment]
Some simple extra work can help you to build a deb without documentation, just add corresponding compilation flags in `debian/rules` and strip `asciidoc` and `xmlto` from `debian/control`. You might need to do this manually.

**Comment by hosiet** [comment]
Plus, you need not install TeX Live. Don't install recommended packages when installing `asciidoc` and `xmlto`.

**Comment by maxchendt** [comment]
I do not know how to fix debian/rules
I do not know how to install asciidoc and xmlto without texlive etc
I think I compile ss-*, then tar the binary files and copy to other servers.
`tar -zcvpf ss-libev20160707.tar.gz  /usr/local/bin/ss-*`
