### ISSUE TITLE
windows客户端不能用，mac和android正常

### ISSUE THREAD

**Issue by ynhzzu** [shadowsocks/shadowsocks-libev#713]
之前所使用的是python版，今天装了c版的，测试windows3.0客户端连不上，但是mac和android无法使用，是怎么回事？

**Comment by ynhzzu** [comment]
错了，mac和android可用

**Comment by ynhzzu** [comment]
怎么关闭了？没人遇到这个问题？

**Comment by ragnaroks** [comment]
是否开启了一次认证?

**Comment by ynhzzu** [comment]
问题找到了，fast-open的问题。我的linux内核是3.10的，开启fast-open成功了，但是windows版本的shadowsocks客户端可能不支持fast-open，所以不能使用。android和mac的客户端版本正常。

**Comment by wongsyrone** [comment]
许多教程里面fast open都默认设置为3，但是没有说前提是服务端和客户端均为*nix且支持fast open。对于这种情况，可以把fast open设置为2，我这里是没问题的。

**Comment by ynhzzu** [comment]
@wongsyrone 还真是，3是客户端和服务端都开启，2是服务端开启，1是客户端开启。那net.ipv4.tcp_fastopen = 3这个需要改吗？
@madeye 问题直接被关闭了，这个最好写到文档里吧。python转c，我还很纳闷怎么偏偏windows客户端不能用，原来核心问题出在这个值上。

**Comment by wongsyrone** [comment]
写在sysctl.conf的内核参数只要改成net.ipv4.tcp_fastopen = 2就可以了，其实clowwindy的教程是没错的

> If **both** of your server **and** client are deployed on Linux 3.7+

还有

>  # turn on TCP Fast Open on **both client and server side**
>  net.ipv4.tcp_fastopen = 3

**Comment by ynhzzu** [comment]
好吧，是我不认真了。我改的是/proc/sys/net/ipv4/tcp_fastopen这个文件的值，效果一样。

**Comment by wongsyrone** [comment]
这两个是一样的，只不过一个是临时的，重启恢复，另一个是永久的
