### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by sadoneli** [shadowsocks/shadowsocks-libev#714]
cross compiled latest shadowsocks by using toolchain arm-uclibc-linux-2.6.36

`make[2]: Leaving directory `/media/lixin/disk1/make/shadowsocks-libev/src'
Making all in doc
make[2]: Entering directory `/media/lixin/disk1/make/shadowsocks-libev/doc'
    [ASCII]  ss-local.xml
/bin/sh: line 1: asciidoc: command not found
make[2]: *** [ss-local.xml] Error 127
make[2]: Leaving directory `/media/lixin/disk1/make/shadowsocks-libev/doc'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/media/lixin/disk1/make/shadowsocks-libev'
make: *** [all] Error 2`

**Comment by madeye** [comment]
Try this: https://github.com/shadowsocks/shadowsocks-libev/issues/701
