### ISSUE TITLE
怎样禁止对服务器所在LAN的代理

### ISSUE THREAD

**Issue by jokester** [shadowsocks/shadowsocks-libev#717]
默认是客户端可以访问到服务器及其私有LAN, 这个好像不太安全
我没有找到能方便地禁止代理服务器所在LAN的功能 (selinux或iptables应该可以做到, 但是颇麻烦)

如果没的话加一个如何?

**Comment by madeye** [comment]
No plan for this. Use iptables instead, no more than three rules.

**Comment by madeye** [comment]
Try `-a` option with
`
sudo iptables -D OUTPUT -d 127.0.0.1 -m owner --uid-owner uid-of-ss-server -j DROP`

**Comment by xxmali** [comment]
@madeye 大佬。如果开启obfs-server的话，你这种方法会造成ss无法使用。毕竟obfs-server和ss-server通过127.0.0.1通信。还有，ss-server -a ss指定用户后，obfs-server还是以root身份运行。

**Comment by jokester** [comment]
在docker容器中iptables drop掉private range的例子: [entry.sh](https://github.com/jokester/Dockerfiles/blob/42b828073b3d12dc498b2ebc3ad6d3547d3be5c3/shadowsocks-libev/entry.sh#L5-L13)

**Comment by xxmali** [comment]
然而很多人并不用docker。
