### ISSUE TITLE
"asciidoc & xmlto" is too big

### ISSUE THREAD

**Issue by s7lx** [shadowsocks/shadowsocks-libev#718]
dependence added  asciidoc and xmlto. 
but installing  asciidoc &xmlto need install more than 700Mbs packages on debian or other like system

any way to decline it or compile without documents ?

**Comment by hosiet** [comment]
Here is a proposal:

Pre-compile asciidoc files into groff man pages and use generated man pages in simple installation, just like the current situation of `configure` and `Makefile.in`, both of which are generated in advance using an old version of autoconf / automake. Every time the asciidoc documentation files are changed, the person who makes the commit shall update the generated man pages.

As for the **official** building process (i.e., the official build for Debian), we can build with asciidoc from source files. The solution is similar for autotools-related files (using `autoreconf` and discard previous `Makefile.in` / `configure` script).

**Comment by wongsyrone** [comment]
@s7lx 
To workaround this, you can try `./configure --disable-documentation`.
