### ISSUE TITLE
libev_2.4.7 Can not build on ubuntu14.04 

### ISSUE THREAD

**Issue by kang000feng** [shadowsocks/shadowsocks-libev#720]
I totally follow the guide of README.
dpkg-source: error: can't build with source format '3.0 (quilt)': no upstream tarball found at ../shadowsocks-libev_2.4.7.orig.tar.{bz2,gz,lzma,xz}
dpkg-buildpackage: error: dpkg-source -i -b shadowsocks-libev gave error exit status 255

**Comment by madeye** [comment]
Try to clean clone the repository and `dpkg-buildpackage -b -us -uc -i`
