### ISSUE TITLE
Fail to compile with MSYS2 on Windows 10

### ISSUE THREAD

**Issue by hazdzz** [shadowsocks/shadowsocks-libev#728]
When I tried './configure --prefix="$HOME/ss" --with-openssl="$HOME/prebuilt', it failed and showed 'configure: error: C compiler cannot create executables'. What should I do?

Below is the 'config.log'.

This file contains any messages produced by compilers while
running configure, to aid debugging if configure makes a mistake.

It was created by shadowsocks-libev configure 2.4.7, which was
generated by GNU Autoconf 2.69.  Invocation command line was

  $ ./configure --prefix=/home/jzhang/ss --with-openssl=/home/jzhang/prebuilt

## --------- ##

hostname = 
uname -m = 
uname -r = 
uname -s = 
uname -v = 

/usr/bin/uname -p = 
/bin/uname -X     = 

/bin/arch              = 
/usr/bin/arch -k       = 
/usr/convex/getsysinfo = 
/usr/bin/hostinfo      = 
/bin/machine           = 
/usr/bin/oslevel       = 
/bin/universe          = 

PATH: /usr/local/bin
PATH: /usr/bin
PATH: /bin
PATH: /opt/bin
PATH: /c/Windows/System32
PATH: /c/Windows
PATH: /c/Windows/System32/Wbem
PATH: /c/Windows/System32/WindowsPowerShell/v1.0/
PATH: /usr/bin/site_perl
PATH: /usr/bin/vendor_perl
PATH: /usr/bin/core_perl

## ----------- ##

configure:2339: loading site script /etc/config.site
| # This file is in public domain.
| # Original author: Karlson2k (Evgeny Grin)
| # Written for MSys2 to help running 'configure' scripts
| 
| # Use correct config.site even if CONFIG_SITE is not set
| if test "x$MSYSTEM" = "xMINGW64"; then
|   if test -r "${MINGW_PREFIX-/mingw64}/etc/config.site"; then
|     . "${MINGW_PREFIX-/mingw64}/etc/config.site"
|   fi
| elif test "x$MSYSTEM" = "xMINGW32"; then
|   if test -r "${MINGW_PREFIX-/mingw32}/etc/config.site"; then
|     . "${MINGW_PREFIX-/mingw32}/etc/config.site"
|   fi
| else
|   # Defaults for MSys2-targeted programs
| 
|   # Set proper selfname on bash and fallback to default name on other shells
|   test -n "${BASH_SOURCE}" 2>/dev/null && config_site_me="${BASH_SOURCE[0]##*/}" || config_site_me=config.site
| 
|   # Set default 'host' to speedup configure
|   if test -z "$build_alias"; then
|     build_alias="${MSYSTEM_CARCH-x86_64}-pc-msys"  && \
|       $as_echo "$config_site_me:${as_lineno-$LINENO}: default build_alias set to $build_alias" >&5 
|   fi
| 
|   # Set default 'prefix' to "/usr"
|   if ( test -z "$prefix" || test "x$prefix" = "xNONE" ) && \
|      ( test -z "$exec_prefix" || test "x$exec_prefix" = "xNONE" ); then
|     prefix="${MSYSTEM_PREFIX-/usr}" && \
|       $as_echo "$config_site_me:${as_lineno-$LINENO}: default prefix set to $prefix" >&5
|   fi
| 
| fi
config.site:23: default build_alias set to x86_64-pc-msys
configure:2520: checking for gcc
configure:2536: found /usr/bin/gcc
configure:2547: result: gcc
configure:2776: checking for C compiler version
configure:2785: gcc --version >&5
gcc (GCC) 5.3.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

configure:2796: $? = 0
configure:2785: gcc -v >&5
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-msys/5.3.0/lto-wrapper.exe
Target: x86_64-pc-msys
Configured with: /msys_scripts/gcc/src/gcc-5.3.0/configure --build=x86_64-pc-msys --prefix=/usr --libexecdir=/usr/lib --enable-bootstrap --enable-shared --enable-shared-libgcc --enable-static --enable-version-specific-runtime-libs --with-arch=x86-64 --with-tune=generic --disable-multilib --enable-__cxa_atexit --with-dwarf2 --enable-languages=c,c++,fortran,lto --enable-graphite --enable-threads=posix --enable-libatomic --enable-libcilkrts --enable-libgomp --enable-libitm --enable-libquadmath --enable-libquadmath-support --enable-libssp --disable-win32-registry --disable-symvers --with-gnu-ld --with-gnu-as --disable-isl-version-check --enable-checking=release --without-libiconv-prefix --without-libintl-prefix --with-system-zlib --enable-linker-build-id --with-default-libstdcxx-abi=gcc4-compatible
Thread model: posix
gcc version 5.3.0 (GCC) 
configure:2796: $? = 0
configure:2785: gcc -V >&5
gcc: error: unrecognized command line option '-V'
gcc: fatal error: no input files
compilation terminated.
configure:2796: $? = 1
configure:2785: gcc -qversion >&5
gcc: error: unrecognized command line option '-qversion'
gcc: fatal error: no input files
compilation terminated.
configure:2796: $? = 1
configure:2816: checking whether the C compiler works
configure:2838: 
configure:2842: $? = 0
configure:2880: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "shadowsocks-libev"
| #define PACKAGE_TARNAME "shadowsocks-libev"
| #define PACKAGE_VERSION "2.4.7"
| #define PACKAGE_STRING "shadowsocks-libev 2.4.7"
| #define PACKAGE_BUGREPORT "max.c.lv@gmail.com"
| #define PACKAGE_URL ""
| /* end confdefs.h.  */
| 
| int
| main ()
| {
| 
|   ;
|   return 0;
| }
configure:2885: error: in `/home/jzhang/shadowsocks-libev-master':
configure:2887: error: C compiler cannot create executables
See `config.log' for more details

## ---------------- ##

ac_cv_env_CC_set=
ac_cv_env_CC_value=
ac_cv_env_CFLAGS_set=
ac_cv_env_CFLAGS_value=
ac_cv_env_CPPFLAGS_set=
ac_cv_env_CPPFLAGS_value=
ac_cv_env_CPP_set=
ac_cv_env_CPP_value=
ac_cv_env_LDFLAGS_set=
ac_cv_env_LDFLAGS_value=
ac_cv_env_LIBS_set=
ac_cv_env_LIBS_value=
ac_cv_env_build_alias_set=
ac_cv_env_build_alias_value=
ac_cv_env_host_alias_set=
ac_cv_env_host_alias_value=
ac_cv_env_target_alias_set=
ac_cv_env_target_alias_value=
ac_cv_prog_ac_ct_CC=gcc

## ----------------- ##

ACLOCAL=''
AMDEPBACKSLASH=''
AMDEP_FALSE=''
AMDEP_TRUE=''
AMTAR=''
AM_BACKSLASH=''
AM_DEFAULT_V=''
AM_DEFAULT_VERBOSITY=''
AM_V=''
AR=''
ASCIIDOC=''
AUTOCONF=''
AUTOHEADER=''
AUTOMAKE=''
AWK=''
BUILD_REDIRECTOR_FALSE=''
BUILD_REDIRECTOR_TRUE=''
BUILD_WINCOMPAT_FALSE=''
BUILD_WINCOMPAT_TRUE=''
CC='gcc'
CCDEPMODE=''
CFLAGS=''
CPP=''
CPPFLAGS=''
CYGPATH_W=''
DEFS=''
DEPDIR=''
DLLTOOL=''
DSYMUTIL=''
DUMPBIN=''
ECHO_C=''
ECHO_N='-n'
ECHO_T=''
EGREP=''
ENABLE_DOCUMENTATION_FALSE=''
ENABLE_DOCUMENTATION_TRUE=''
EXEEXT=''
FGREP=''
GREP=''
GZIP=''
INET_NTOP_LIB=''
INSTALL_DATA=''
INSTALL_PROGRAM=''
INSTALL_SCRIPT=''
INSTALL_STRIP_PROGRAM=''
LD=''
LDFLAGS=''
LIBOBJS=''
LIBS=''
LIBTOOL=''
LIPO=''
LN_S=''
LTLIBOBJS=''
MAINT=''
MAINTAINER_MODE_FALSE=''
MAINTAINER_MODE_TRUE=''
MAKEINFO=''
MANIFEST_TOOL=''
MKDIR_P=''
MV=''
NM=''
NMEDIT=''
OBJDUMP=''
OBJEXT=''
OTOOL64=''
OTOOL=''
PACKAGE=''
PACKAGE_BUGREPORT='max.c.lv@gmail.com'
PACKAGE_NAME='shadowsocks-libev'
PACKAGE_STRING='shadowsocks-libev 2.4.7'
PACKAGE_TARNAME='shadowsocks-libev'
PACKAGE_URL=''
PACKAGE_VERSION='2.4.7'
PATH_SEPARATOR=':'
PTHREAD_CC=''
PTHREAD_CFLAGS=''
PTHREAD_LIBS=''
RANLIB=''
RM=''
SED=''
SET_MAKE=''
SHELL='/bin/sh'
STRIP=''
USE_SYSTEM_SHARED_LIB_FALSE=''
USE_SYSTEM_SHARED_LIB_TRUE=''
VERSION=''
XMLTO=''
ac_ct_AR=''
ac_ct_CC='gcc'
ac_ct_DUMPBIN=''
am__EXEEXT_FALSE=''
am__EXEEXT_TRUE=''
am__fastdepCC_FALSE=''
am__fastdepCC_TRUE=''
am__include=''
am__isrc=''
am__leading_dot=''
am__nodep=''
am__quote=''
am__tar=''
am__untar=''
ax_pthread_config=''
bindir='${exec_prefix}/bin'
build=''
build_alias='x86_64-pc-msys'
build_cpu=''
build_os=''
build_vendor=''
datadir='${datarootdir}'
datarootdir='${prefix}/share'
docdir='${datarootdir}/doc/${PACKAGE_TARNAME}'
dvidir='${docdir}'
exec_prefix='NONE'
host=''
host_alias=''
host_cpu=''
host_os=''
host_vendor=''
htmldir='${docdir}'
includedir='${prefix}/include'
infodir='${datarootdir}/info'
install_sh=''
libdir='${exec_prefix}/lib'
libexecdir='${exec_prefix}/libexec'
localedir='${datarootdir}/locale'
localstatedir='${prefix}/var'
mandir='${datarootdir}/man'
mkdir_p=''
oldincludedir='/usr/include'
pdfdir='${docdir}'
prefix='/home/jzhang/ss'
program_transform_name='s,x,x,'
psdir='${docdir}'
sbindir='${exec_prefix}/sbin'
sharedstatedir='${prefix}/com'
subdirs=''
sysconfdir='${prefix}/etc'
target_alias=''

## ----------- ##

/* confdefs.h */
#define PACKAGE_NAME "shadowsocks-libev"
#define PACKAGE_TARNAME "shadowsocks-libev"
#define PACKAGE_VERSION "2.4.7"
#define PACKAGE_STRING "shadowsocks-libev 2.4.7"
#define PACKAGE_BUGREPORT "max.c.lv@gmail.com"
#define PACKAGE_URL ""

configure: exit 77

**Comment by madeye** [comment]
Try http://mingw-w64.org
