### ISSUE TITLE
why start service fail?

### ISSUE THREAD

**Issue by uknowzheng** [shadowsocks/shadowsocks-libev#729]
uknow@uknow:~$ /etc/init.d/shadowsocks-libev status
● shadowsocks-libev.service - Shadowsocks-libev Default Server Service
   Loaded: loaded (/lib/systemd/system/shadowsocks-libev.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since 二 2016-07-19 21:47:50 XJT; 22s ago
     Docs: man:shadowsocks-libev(8)
  Process: 3652 ExecStart=/usr/bin/ss-server -a $USER -c $CONFFILE $DAEMON_ARGS (code=exited, status=255)
 Main PID: 3652 (code=exited, status=255)

7月 19 21:47:50 uknow systemd[1]: Started Shadowsocks-libev Default Server Service.
7月 19 21:47:50 uknow ss-server[3652]:  2016-07-19 21:47:50 INFO: UDP relay enabled
7月 19 21:47:50 uknow ss-server[3652]:  2016-07-19 21:47:50 INFO: initializing ciphers... aes-256-cfb
7月 19 21:47:50 uknow ss-server[3652]:  2016-07-19 21:47:50 INFO: port reuse enabled
7月 19 21:47:50 uknow ss-server[3652]:  2016-07-19 21:47:50 ERROR: bind: Cannot assign requested address
7月 19 21:47:50 uknow ss-server[3652]:  2016-07-19 21:47:50 ERROR: Could not bind
7月 19 21:47:50 uknow ss-server[3652]:  2016-07-19 21:47:50 ERROR: bind() error
7月 19 21:47:50 uknow systemd[1]: shadowsocks-libev.service: Main process exited, code=exited, status=255/n/a
7月 19 21:47:50 uknow systemd[1]: shadowsocks-libev.service: Unit entered failed state.
7月 19 21:47:50 uknow systemd[1]: shadowsocks-libev.service: Failed with result 'exit-code'.

**Comment by guliujian** [comment]
It says can't bind address so have you start one and not kill it or something wrong
