### ISSUE TITLE
--acl not worked ??

### ISSUE THREAD

**Issue by zw963** [shadowsocks/shadowsocks-libev#730]
Hi, I have tried many times, still could not make --acl worked.

Following is process:

1.  create acl.list, it content with following content
```sh
124.165.204.39
124.165.204.38
124.165.204.37
124.165.204.36
```
2. ss-server start with:  `/usr/bin/ss-server -c /etc/shadowsocks/config.json -u`
3. ss-local start with:  ss-local -c config.json -u --acl acl.list
4. from browser, config to use this socket 5 proxy.
5. access `ip138.com`, it ip address is within previous acllist.
6. return my VPS ip. what i expect is it return my local domain public IP.

Is there exist some disunderstood about --acl usage?

**Comment by madeye** [comment]
`--acl` means which IPs can access the server.
