### ISSUE TITLE
centos 6 install Failed

### ISSUE THREAD

**Issue by kingsonVIP** [shadowsocks/shadowsocks-libev#731]
make[2]: Leaving directory `/root/shadowsocks-libev/src'
Making all in doc
make[2]: Entering directory `/root/shadowsocks-libev/doc'
  GEN      shadowsocks-libev.xml
  GEN      shadowsocks-libev.8
  GEN      ss-local.xml
  GEN      ss-local.1
  GEN      ss-manager.xml
  GEN      ss-manager.1
  GEN      ss-nat.xml
  GEN      ss-nat.1
  GEN      ss-redir.xml
  GEN      ss-redir.1
  GEN      ss-server.xml
  GEN      ss-server.1
  GEN      ss-tunnel.xml
  GEN      ss-tunnel.1
  GEN      shadowsocks-libev.html
WARNING: non-standard html backend
WARNING: [quotes] ** missing tag definition: strong
WARNING: [quotes] * missing tag definition: strong
WARNING: [quotes] ``|'' missing tag definition: doublequoted
WARNING: [quotes] ' missing tag definition: emphasis
WARNING: [quotes] `|' missing tag definition: singlequoted
WARNING: [quotes] +++ missing tag definition: unquoted
WARNING: [quotes] $$ missing tag definition: unquoted
WARNING: [quotes] ++ missing tag definition: monospaced
WARNING: [quotes] + missing tag definition: monospaced
WARNING: [quotes] __ missing tag definition: emphasis
WARNING: [quotes] _ missing tag definition: emphasis
WARNING: [quotes] ## missing tag definition: unquoted
WARNING: [quotes] # missing tag definition: unquoted
WARNING: [quotes] ^ missing tag definition: superscript
WARNING: [quotes] ~ missing tag definition: subscript
WARNING: [admonitionparagraph] missing template section
WARNING: [admonitionparagraph] missing template section
WARNING: [admonitionparagraph] missing template section
WARNING: [paragraph] missing template section
WARNING: [admonitionparagraph] missing template section
WARNING: [admonitionparagraph] missing template section
WARNING: [literalparagraph] missing template section
WARNING: [verseparagraph] missing template section
WARNING: [literalparagraph] missing template section
WARNING: [admonitionparagraph] missing template section
WARNING: [admonitionparagraph] missing template section
WARNING: [admonitionparagraph] missing template section
WARNING: [admonitionparagraph] missing template section
WARNING: [admonitionparagraph] missing template section
FAILED: [listdef-bulleted] missing section: [listtags-bulleted]
make[2]: *** [shadowsocks-libev.html] Error 1
rm ss-server.xml ss-local.xml ss-redir.xml ss-nat.xml ss-tunnel.xml shadowsocks-libev.xml ss-manager.xml
make[2]: Leaving directory `/root/shadowsocks-libev/doc'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/root/shadowsocks-libev'
make: *** [all] Error 2

**Comment by consen** [comment]
I encountered the same issue, when gen rpm.
```
sh genrpm.sh -v 2.4.8
```
