### ISSUE TITLE
Start service failed on CentOS 7.2

### ISSUE THREAD

**Issue by smounives** [shadowsocks/shadowsocks-libev#733]
I installed from the repository,the package is shadowsocks-libev-2.4.7-1.el7.centos.x86_64.rpm.
Then I start the service:

 shadowsocks-libev.service - Shadowsocks-libev Default Server Service
   Loaded: loaded (/usr/lib/systemd/system/shadowsocks-libev.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Thu 2016-07-21 19:00:13 JST; 7s ago
  Process: 809 ExecStart=/usr/bin/ss-server -a $USER -c $CONFFILE $DAEMON_ARGS (code=exited, status=216/GROUP)
 Main PID: 809 (code=exited, status=216/GROUP)

Jul 21 19:00:13  systemd[1]: [/usr/lib/systemd/system/shadowsocks-libev.service:20] Failed to parse resource value, ignoring: $MAXFD
Jul 21 19:00:13  systemd[1]: Started Shadowsocks-libev Default Server Service.
Jul 21 19:00:13  systemd[1]: Starting Shadowsocks-libev Default Server Service...
Jul 21 19:00:13  systemd[1]: shadowsocks-libev.service: main process exited, code=exited, status=216/GROUP
Jul 21 19:00:13  systemd[1]: Unit shadowsocks-libev.service entered failed state.
Jul 21 19:00:13  systemd[1]: shadowsocks-libev.service failed.

**Comment by madeye** [comment]
Update your systemd files

https://github.com/shadowsocks/shadowsocks-libev/blob/master/debian/shadowsocks-libev.service

**Comment by smounives** [comment]
Thanks!
