### ISSUE TITLE
can not cross-build for openwrt

### ISSUE THREAD

**Issue by debiansid** [shadowsocks/shadowsocks-libev#734]
make[6]: Leaving directory '/home/storage/lede-1/build_dir/target-i386_pentium4_musl-1.1.15/shadowsocks-libev/openssl/shadowsocks-libev-2.4.8/src'
Making all in doc
make[6]: Entering directory '/home/storage/lede-1/build_dir/target-i386_pentium4_musl-1.1.15/shadowsocks-libev/openssl/shadowsocks-libev-2.4.8/doc'
  GEN      shadowsocks-libev.xml
/bin/bash: asciidoc: command not found
Makefile:629: recipe for target 'shadowsocks-libev.xml' failed
make[6]: *** [shadowsocks-libev.xml] Error 127
make[6]: Leaving directory '/home/storage/lede-1/build_dir/target-i386_pentium4_musl-1.1.15/shadowsocks-libev/openssl/shadowsocks-libev-2.4.8/doc'
Makefile:471: recipe for target 'all-recursive' failed
make[5]: *** [all-recursive] Error 1
make[5]: Leaving directory '/home/storage/lede-1/build_dir/target-i386_pentium4_musl-1.1.15/shadowsocks-libev/openssl/shadowsocks-libev-2.4.8'
Makefile:380: recipe for target 'all' failed
make[4]: *** [all] Error 2
make[4]: Leaving directory '/home/storage/lede-1/build_dir/target-i386_pentium4_musl-1.1.15/shadowsocks-libev/openssl/shadowsocks-libev-2.4.8'
Makefile:109: recipe for target '/home/storage/lede-1/build_dir/target-i386_pentium4_musl-1.1.15/shadowsocks-libev/openssl/shadowsocks-libev-2.4.8/.built' failed
make[3]: *** [/home/storage/lede-1/build_dir/target-i386_pentium4_musl-1.1.15/shadowsocks-libev/openssl/shadowsocks-libev-2.4.8/.built] Error 2
make[3]: Leaving directory '/home/storage/lede-1/package/openwrt-shadowsocks'
package/Makefile:187: recipe for target 'package/openwrt-shadowsocks/compile' failed
make[2]: *** [package/openwrt-shadowsocks/compile] Error 2
make[2]: Leaving directory '/home/storage/lede-1'
package/Makefile:184: recipe for target '/home/storage/lede-1/staging_dir/target-i386_pentium4_musl-1.1.15/stamp/.package_compile' failed
make[1]: *** [/home/storage/lede-1/staging_dir/target-i386_pentium4_musl-1.1.15/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/storage/lede-1'
/home/storage/lede-1/include/toplevel.mk:193: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by wongsyrone** [comment]
For OpenWrt/LEDE, you can simply disable docs

CONFIGURE_ARGS += --disable-documentation --disable-ssp

**Comment by tedaz** [comment]
@wongsyrone Would you please let me know where to change this setting?
PS: I'm building openwrt x86 with Ubuntu 14.04.

**Comment by wongsyrone** [comment]
add it to package Makefile, it is simply a wrapper.
ref: https://github.com/openwrt/openwrt/blob/master/include/package-defaults.mk#L78

**Comment by tedaz** [comment]
@wongsyrone Thanks for your help, after altered the shadowsocks-libev/openwrt/Makefile, the build process completed successfully. Is it possible to update this file and commit it to the git? Otherwise all other people want to build the openwrt version have to do this modification.

**Comment by wongsyrone** [comment]
What's your opinion? @madeye 
Should we disable docs by default on openwrt?

**Comment by madeye** [comment]
LGTM

**Comment by tedaz** [comment]
@wongsyrone It seems the command argument/method changed since 2.4.7 to 2.4.8, right? As below command failed on version 2.4.8:     "service_start /usr/bin/ss-redir -b 0.0.0.0 -c /etc/shadowsocks.json", 
    "service_start /usr/bin/ss-tunnel -c /etc/shadowsocks.json -l 5353 -L 8.8.8.8:53 -u";
shadowsocks.json
{
    "server":"0.0.0.0",
    "server_port":0000,
    "local_port":0000,
    "password":"****",
    "timeout":600,
    "method":"aes-256-cfb"
}
