### ISSUE TITLE
关于ss服务器端访问外网的问题

### ISSUE THREAD

**Issue by yebr** [shadowsocks/shadowsocks-libev#735]
我路由器的IP为192.168.1.1，
已绑定内网IP 192.168.0.1为SS服务器端的IP（"server": "192.168.0.1",），使用的端口为9999，
然后路由器已映射公网IP的9999端口给内网192.168.0.1（iptables -t nat -A PREROUTING -p tcp -d 219.0.0.1 --dport 9999 -j DNAT --to-destination 192.168.0.1）， 
ss连接建立成功，但通过iptables log和tcpdump发现，服务器端访问网络时，使用的源ip不是内网的192.168.0.1，而是没经过nat直接的使用公网IP 219.0.0.1，
请问是什么原因导致了这个问题？谢谢！

**Comment by madeye** [comment]
The IP address should be your last gateway's IP, which is 219.0.0.1 in your case.
