### ISSUE TITLE
compile shadowsocks-libev server in centos 7 without libevent package installed

### ISSUE THREAD

**Issue by zw963** [shadowsocks/shadowsocks-libev#736]
Hi, I compile shadowsocks-libev in my centos 7 VPS.

It worked very well for half one years.

I just wonder, why I am not install `libevent libevent-devel` package, it still work?
thanks.

**Comment by hosiet** [comment]
Since shadowsocks-libev never ever depends on libevent.

在 2016年7月22日週五 16:42，Billy.Zheng <notifications@github.com> 寫道：

**Comment by zw963** [comment]
Thanks.
