### ISSUE TITLE
2.4.8编译不通过

### ISSUE THREAD

**Issue by testcaoy7** [shadowsocks/shadowsocks-libev#737]
make的输出信息如下：

make  all-recursive
make[1]: Entering directory `/home/ubuntu/shadowsocks-libev-2.4.8'
Making all in libsodium
make[2]: Entering directory `/home/ubuntu/shadowsocks-libev-2.4.8/libsodium'
Making all in src
make[3]: Entering directory `/home/ubuntu/shadowsocks-libev-2.4.8/libsodium/src'
Making all in libsodium
make[4]: Entering directory `/home/ubuntu/shadowsocks-libev-2.4.8/libsodium/src/libsodium'
Making all in include
make[5]: Entering directory `/home/ubuntu/shadowsocks-libev-2.4.8/libsodium/src/libsodium/include'
make[5]: Nothing to be done for `all'.
make[5]: Leaving directory `/home/ubuntu/shadowsocks-libev-2.4.8/libsodium/src/libsodium/include'
make[5]: Entering directory `/home/ubuntu/shadowsocks-libev-2.4.8/libsodium/src/libsodium'
  CC       sodium/libsodium_la-version.lo
  CCLD     libsodium.la
libtool: link: warning: `-version-info/-version-number' is ignored for convenience libraries
make[5]: Leaving directory `/home/ubuntu/shadowsocks-libev-2.4.8/libsodium/src/libsodium'
make[4]: Leaving directory `/home/ubuntu/shadowsocks-libev-2.4.8/libsodium/src/libsodium'
make[4]: Entering directory `/home/ubuntu/shadowsocks-libev-2.4.8/libsodium/src'
make[4]: Nothing to be done for `all-am'.
make[4]: Leaving directory `/home/ubuntu/shadowsocks-libev-2.4.8/libsodium/src'
make[3]: Leaving directory `/home/ubuntu/shadowsocks-libev-2.4.8/libsodium/src'
make[3]: Entering directory `/home/ubuntu/shadowsocks-libev-2.4.8/libsodium'
make[3]: Nothing to be done for `all-am'.
make[3]: Leaving directory `/home/ubuntu/shadowsocks-libev-2.4.8/libsodium'
make[2]: Leaving directory `/home/ubuntu/shadowsocks-libev-2.4.8/libsodium'
Making all in libcork
make[2]: Entering directory `/home/ubuntu/shadowsocks-libev-2.4.8/libcork'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/home/ubuntu/shadowsocks-libev-2.4.8/libcork'
Making all in libipset
make[2]: Entering directory `/home/ubuntu/shadowsocks-libev-2.4.8/libipset'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/home/ubuntu/shadowsocks-libev-2.4.8/libipset'
Making all in libudns
make[2]: Entering directory `/home/ubuntu/shadowsocks-libev-2.4.8/libudns'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/home/ubuntu/shadowsocks-libev-2.4.8/libudns'
Making all in libev
make[2]: Entering directory `/home/ubuntu/shadowsocks-libev-2.4.8/libev'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/home/ubuntu/shadowsocks-libev-2.4.8/libev'
Making all in src
make[2]: Entering directory `/home/ubuntu/shadowsocks-libev-2.4.8/src'
  CC       libshadowsocks_libev_la-encrypt.lo
  CCLD     libshadowsocks-libev.la
  CC       ss_local-encrypt.o
  CCLD     ss-local
  CC       ss_tunnel-encrypt.o
  CCLD     ss-tunnel
  CC       ss_server-encrypt.o
  CCLD     ss-server
  CCLD     ss-manager
  CC       ss_redir-encrypt.o
  CCLD     ss-redir
make[2]: Leaving directory `/home/ubuntu/shadowsocks-libev-2.4.8/src'
Making all in doc
make[2]: Entering directory `/home/ubuntu/shadowsocks-libev-2.4.8/doc'
  GEN      shadowsocks-libev.xml
/bin/bash: asciidoc: command not found
make[2]: *** [shadowsocks-libev.xml] Error 127
make[2]: Leaving directory `/home/ubuntu/shadowsocks-libev-2.4.8/doc'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/ubuntu/shadowsocks-libev-2.4.8'
make: *** [all] Error 2

**Comment by testcaoy7** [comment]
操作系统是ubuntu 14.04 LTS

**Comment by lixingcong** [comment]
/bin/bash: asciidoc: command not found
错误这么明显，你都不看文档，肯定出错！

**Comment by VampireSH** [comment]
这么明显缺少某个程序…

Lixingcong <notifications@github.com>于2016年7月22日周五 20:07写道：

**Comment by testcaoy7** [comment]
解决了，是我不好，没看文档，2.4.8多了以前版本没有的依赖项
