### ISSUE TITLE
supported ciphers in Debian?

### ISSUE THREAD

**Issue by rogers0** [shadowsocks/shadowsocks-libev#739]
doc/shadowsocks-libev.asciidoc says:
`If built with PolarSSL or custom OpenSSL libraries, some of these ciphers may not work.`

my question is, is there a simple way to confirm/get the cipher list in Debian?

**Comment by madeye** [comment]
If built against mbedtls or polarssl, the supported ciphers are https://github.com/shadowsocks/shadowsocks-libev/blob/master/src/encrypt.c#L124
