### ISSUE TITLE
-i option can not work on virtual device

### ISSUE THREAD

**Issue by s7lx** [shadowsocks/shadowsocks-libev#742]
physical device `eth0` bind ip `a.a.a.a`
virtual device `eth0:1` bind ip `b.b.b.b`

run `sudo ss-server -s "a.a.a.a" -p 5105 -m "rc4-md5" -k "tttt" -i "eth0:1" -t 60`

vps receive data from `b.b.b.b` but sent data from `a.a.a.a`

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks-libev/issues/626#issuecomment-217367556
