### ISSUE TITLE
ShadowsocksX日志提示 CFNetwork SSLHandshake failed (-9806)

### ISSUE THREAD

**Issue by oocco** [shadowsocks/shadowsocks-libev#743]
android使用没有问题，但切换mac os x后无法连接，日志显示：

> 16/7/26 下午1:15:07.469 com.apple.WebKit.Networking[675]: CFNetwork SSLHandshake failed (-9806)
> 16/7/26 下午1:15:07.773 com.apple.WebKit.Networking[675]: CFNetwork SSLHandshake failed (-9806)
> 16/7/26 下午1:15:08.002 com.apple.WebKit.Networking[675]: CFNetwork SSLHandshake failed (-9806)
> 16/7/26 下午1:15:08.241 com.apple.WebKit.Networking[675]: CFNetwork SSLHandshake failed (-9806)
> 16/7/26 下午1:15:08.242 com.apple.WebKit.Networking[675]: NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9806)

使用pyhon版则正常，请问是什么问题，怎么解决？

**Comment by madeye** [comment]
Double check your local config.

**Comment by oocco** [comment]
thank you
but “local config” ，where？my pc or vps
can you tell me more detail?
I'm a beginner, and try a long time.
thank you very much~
