### ISSUE TITLE
Bad CPU type in executable in iOS 8.4 with A5(iPhone 4S) Processor ?

### ISSUE THREAD

**Issue by iMocW** [shadowsocks/shadowsocks-libev#744]
shadowsocks-libev 2.4.2 (deb name: me.qusic.shadowsocks).
`iPhone:~ root# ss-local -c "/private/etc/ssconf.json"`
`-sh: /usr/bin/ss-local: Bad CPU type in executable`

**Comment by hosiet** [comment]
I believe iPhone is not supported by upstream here. You should find
downstream packager for technical support and report the bug.

在 2016年7月27日週三 23:20，iMocW <notifications@github.com> 寫道：

**Comment by iMocW** [comment]
This software didn't come from your team ?

**Comment by iMocW** [comment]
There is a package name com.linusyang.shadowsocks provided a GUI for shadowsocks-libev on iOS and works fine just out of date and do not support chacha20 . Which one did this GUI use ?

**Comment by madeye** [comment]
For iOS, try https://github.com/shadowsocks/Potatso
