### ISSUE TITLE
GPG public key使用了弱安全性摘要算法(SHA1)

### ISSUE THREAD

**Issue by meteormatt** [shadowsocks/shadowsocks-libev#747]
```bash
W: http://shadowsocks.org/ubuntu/dists/trusty/InRelease: 密钥 BA5A4D12BACB1AEF47F19BD31939D14B1D27208A 生成的数字签名使用了弱安全性摘要算法(SHA1)
```
Ubuntu 16.04下`apt-get update`有错误提示.能不能更新下GPG public key？

**Comment by madeye** [comment]
Update from Debian official repository instead: https://github.com/shadowsocks/shadowsocks-libev#official-repository

**Comment by meteormatt** [comment]
`shadowsocks-libev`只有在Ubuntu 16.10里才有啊。http://packages.ubuntu.com/yakkety/shadowsocks-libev 怎么在16.04里使用16.10的包呢？

**Comment by wongsyrone** [comment]
Then you can build your deb package from source.
ref: https://github.com/shadowsocks/shadowsocks-libev#build-deb-package-from-source
