### ISSUE TITLE
Can't run /etc/init.d/shadowsocks ?

### ISSUE THREAD

**Issue by wangjianpeng** [shadowsocks/shadowsocks-libev#748]
I want to show the status of shadowsocks, so i input /etc/init.d/shadowsocks status , there are some errors "
`root@unity3d:/home/wjp# /etc/init.d/shadowsocks status
/etc/init.d/shadowsocks: line 18: /etc/rc.d/init.d/functions: No such file or directory
/etc/init.d/shadowsocks: line 115: status: command not found
root@unity3d:/home/wjp# /etc/init.d/shadowsocks start
/etc/init.d/shadowsocks: line 18: /etc/rc.d/init.d/functions: No such file or directory
Starting shadowsocks-server: /etc/init.d/shadowsocks: line 71: daemon: command not found
`
what should i do ? please help me

**Comment by hosiet** [comment]
Please provide information about the distribution you use and how you installed shadowsocks-libev onto your system. If you are working on a radhat-flavor distribution, check if you have installed `initscripts` package.

**Comment by madeye** [comment]
If you're using CentOS/Fedora, report your issue to @librehat : https://copr.fedorainfracloud.org/coprs/librehat/shadowsocks/
