### ISSUE TITLE
Add a new SS libev docker image

### ISSUE THREAD

**Issue by Secbone** [shadowsocks/shadowsocks-libev#749]
I build a shadowsocks-libev docker image, it's light and clean using this repo source code, and more easier to use, and I will maintain it with this source code updating. 

Could you consider create a link or repo to show it?

[docker-ss-libev](https://github.com/Secbone/docker-ss-libev)

:)

**Comment by wongsyrone** [comment]
You can send a Pull Request, then @madeye will review your changes.

**Comment by madeye** [comment]
Right.
