### ISSUE TITLE
MTU选项的问题

### ISSUE THREAD

**Issue by pexcn** [shadowsocks/shadowsocks-libev#754]
请问默认值是多少？作者推荐如何设置最佳值呢？

**Comment by pexcn** [comment]
还有就是MTU应该设置成自己网卡的MTU还是VPS上的最大值？

**Comment by wongsyrone** [comment]
从代码上看，默认值是1492，应该是设置为部署位置的对应MTU吧。
比如服务端就是VPS网卡的MTU，客户端是本地网卡的MTU，如有错误请指正。
这个选项应该是为了配合kcptun的。

**Comment by pexcn** [comment]
`src/udprelay.h` 里看到的是 `1492 - 1 - 28 - 2 - 64 = 1397`  
1397 才是默认吧？

**Comment by pexcn** [comment]
1492好像是PPPOE的最佳值，为什么要减去`- 1 - 28 - 2 - 64` ? 是否与加密方法，OTA等功能相关？

**Comment by pexcn** [comment]
如果不使用KCPTun，默认值就是最佳值了吗？

**Comment by wongsyrone** [comment]
你可以通过这个http://www.tp-link.us/FAQ-190.html测试一下，至于减去的那些，应该是各层包的包头。

**Comment by pexcn** [comment]
这倒是测试过了，联通1492，电信1480…

**Comment by madeye** [comment]
Use a smaller number only if you're facing UDP fragmentation issue when proxying PS4/Xbox One transparently.

Otherwise, don't touch that number.
