### ISSUE TITLE
TCP connection timeout

### ISSUE THREAD

**Issue by wwl1234** [shadowsocks/shadowsocks-libev#755]
我用的shadohowsocks android 通过jni编译后用java 来写的ss-local 命令等 在 server_recv_cb 方法中 int r = connect(remote->fd, (struct sockaddr *)&(remote->addr), remote->addr_len);  返回值是-1  
TCP connection timeout

**Comment by madeye** [comment]
1. You have to debug your bug by yourself.
2. Without opening source of your code, no one can help you.

**Comment by wwl1234** [comment]
好吧 还是很感谢你

**Comment by wwl1234** [comment]
在 ShadowsocksVpnService extends VpnService
 private void startShadowsocksDaemon(){
        try{
            java.lang.Process sslocalProcess =  new ProcessBuilder()
                    .command(Constants.Path.BASE + "ss-local", "-V", "-u"
                            , "-b", "127.0.0.1"
                            , "-t", "600"
                            , "-c", Constants.Path.BASE + "ss-local-vpn.conf","-A","-v")
                    .redirectErrorStream(true)
                    .start();
        }catch (Exception e){
            e.printStackTrace();
        }
    }

    private void startVpn(){
        Builder builder = new Builder();
        builder
                //                .setSession(Constants.Path.BASE + "ss-local-vpn.conf")
                .setSession("Default")
                .setMtu(VPN_MTU)
                .addAddress(PRIVATE_VLAN, 24)
                .addDnsServer("8.8.8.8");

        builder.addRoute("0.0.0.0", 0);
        builder.addRoute("8.8.0.0", 16);

        ParcelFileDescriptor conn = builder.establish();
        int fd =conn.getFd();
        try {
            java.lang.Process tun2socksProcess = new ProcessBuilder()
                    .command(Constants.Path.BASE + "tun2socks", "--netif-ipaddr", "26.26.26.2",
                            "--netif-netmask", "255.255.255.0", "--socks-server-addr", "127.0.0.1:1080",
                            "--tunfd", fd + "", "--tunmtu", "1397", "--loglevel", "3"
                            , "--enable-udprelay"/*"--dnsgw", "26.26.26.1:8153"*/,"--sock-path",Constants.Path.BASE+"sock_path")
                    .redirectErrorStream(true)
                    .start();
            
            if (fd != -1) {
                int tries = 1;
                while (tries < 5) {
                    Thread.sleep(1000 * tries);
                    int temp;
                    if ((temp =System.sendfd(fd)) != -1) {
                        Log.e("vvvvpppnnn","正常lianllll  "+temp);
                        return;
                    }
                    tries += 1;
                }
            }
        }catch (Exception e){
            Log.e("shadowsocks","异常了");
            e.printStackTrace();
        }
    }

ShadowsocksVpnThread

  @Override
    public void run() {
        try {
            new File(PATH).delete();
        } catch (Exception e) {
            e.printStackTrace();
        }

        try {
            LocalSocket localSocket = new LocalSocket();
            localSocket.bind(new LocalSocketAddress(PATH, LocalSocketAddress.Namespace.FILESYSTEM));
            serverSocket = new LocalServerSocket(localSocket.getFileDescriptor());
        } catch (Exception e) {
            e.printStackTrace();
            return;
        }

        ExecutorService pool = Executors.newFixedThreadPool(4);

        while (isRunning) {
            try {
                final LocalSocket socket = serverSocket.accept();
                pool.execute(new Runnable() {
                    @Override
                    public void run() {
                        try {
                            InputStream input = socket.getInputStream();
                            OutputStream output = socket.getOutputStream();

                            input.read();
                            FileDescriptor[] fds = socket.getAncillaryFileDescriptors();
                            Method getInt = FileDescriptor.class.getDeclaredMethod("getInt$");
                            if (fds != null && fds.length > 0) {
                                int fd = (int) getInt.invoke(fds[0]);
                                boolean ret = vpnService.protect(fd);
//                                Log.e("ss thread","fd "+fd+"  ret "+ret);

                                // Trick to close file decriptor
                                System.jniclose(fd);

                                if (ret) {
                                    output.write(0);
                                } else {
                                    output.write(1);
                                }
                            }

                            input.close();
                            output.close();

                        } catch (Exception e) {
                            e.printStackTrace();
                        }
                    }
                });

            } catch (Exception e) {
                e.printStackTrace();
                return;
            }

        }
    }
