### ISSUE TITLE
Merge MPTCP feature back to the master branch

### ISSUE THREAD

**Issue by madeye** [shadowsocks/shadowsocks-libev#756]
Downstream:

https://github.com/ovh/overthebox-shadowsocks-libev

References:

http://www.sajalkayan.com/post/fun-with-mptcp.html
https://lwn.net/Articles/544399/
http://www.slideshare.net/ovhcom/introduction-to-overthebox
http://bitsofnetworks.org/ovhs-overthebox-internet-access-link-aggregation-using-multipath-tcp.html

**Comment by pexcn** [comment]
请问MPTCP是指TCP多路复用吗？

**Comment by madeye** [comment]
Right. https://lwn.net/Articles/544399/

**Comment by pexcn** [comment]
虽然暂时看不懂，但是感觉好厉害。感谢回复~

**Comment by rstanislav** [comment]
On mptcp enabled kernel 4.1.20, with option in json config:
"mptcp" : true
i get
ERROR: failed to enable multipath TCP: Protocol not available

mptcp 100% enabled and working, for example output of 
dmesg | grep MPTCP
[    0.636141] MPTCP: Stable release v0.90

cat /proc/sys/net/ipv4/tcp_congestion_control
balia
