### ISSUE TITLE
v2.4.8 can't compile successfully.

### ISSUE THREAD

**Issue by angusding** [shadowsocks/shadowsocks-libev#759]
Error information:

  GEN      shadowsocks-libev.html
WARNING: non-standard html backend
WARNING: [quotes] ** missing tag definition: strong
WARNING: [quotes] * missing tag definition: strong
WARNING: [quotes] ``|'' missing tag definition: doublequoted
WARNING: [quotes] ' missing tag definition: emphasis
WARNING: [quotes] `|' missing tag definition: singlequoted
WARNING: [quotes] +++ missing tag definition: unquoted
WARNING: [quotes] $$ missing tag definition: unquoted
WARNING: [quotes] ++ missing tag definition: monospaced
WARNING: [quotes] + missing tag definition: monospaced
WARNING: [quotes] __ missing tag definition: emphasis
WARNING: [quotes] _ missing tag definition: emphasis
WARNING: [quotes] ## missing tag definition: unquoted
WARNING: [quotes] # missing tag definition: unquoted
WARNING: [quotes] ^ missing tag definition: superscript
WARNING: [quotes] ~ missing tag definition: subscript
WARNING: [admonitionparagraph] missing template section
WARNING: [admonitionparagraph] missing template section
WARNING: [admonitionparagraph] missing template section
WARNING: [paragraph] missing template section
WARNING: [admonitionparagraph] missing template section
WARNING: [admonitionparagraph] missing template section
WARNING: [literalparagraph] missing template section
WARNING: [verseparagraph] missing template section
WARNING: [literalparagraph] missing template section
WARNING: [admonitionparagraph] missing template section
WARNING: [admonitionparagraph] missing template section
WARNING: [admonitionparagraph] missing template section
WARNING: [admonitionparagraph] missing template section
WARNING: [admonitionparagraph] missing template section
FAILED: [listdef-bulleted] missing section: [listtags-bulleted]
make[5]: *** [shadowsocks-libev.html] Error 1
rm ss-server.xml ss-local.xml ss-redir.xml ss-nat.xml ss-tunnel.xml shadowsocks-libev.xml ss-manager.xml
make[5]: Leaving directory `/home/everun/openwrt/branches/chaos_calmer/openwrt/build_dir/target-mips_34kc_uClibc-0.9.33.2/shadowsocks-libev-openssl/shadowsocks-libev-2.4.8/doc'
make[4]: *** [all-recursive] Error 1
make[4]: Leaving directory `/home/everun/openwrt/branches/chaos_calmer/openwrt/build_dir/target-mips_34kc_uClibc-0.9.33.2/shadowsocks-libev-openssl/shadowsocks-libev-2.4.8'
make[3]: *** [all] Error 2
make[3]: Leaving directory `/home/everun/openwrt/branches/chaos_calmer/openwrt/build_dir/target-mips_34kc_uClibc-0.9.33.2/shadowsocks-libev-openssl/shadowsocks-libev-2.4.8'
make[2]: *** [/home/everun/openwrt/branches/chaos_calmer/openwrt/build_dir/target-mips_34kc_uClibc-0.9.33.2/shadowsocks-libev-openssl/shadowsocks-libev-2.4.8/.built] Error 2
make[2]: Leaving directory `/home/everun/openwrt/branches/chaos_calmer/openwrt/everun/2.applications/shadowsocks-libev'
make[1]: *** [package/everun/2.applications/shadowsocks-libev/compile] Error 2
make[1]: Leaving directory `/home/everun/openwrt/branches/chaos_calmer/openwrt'
make: *** [package/everun/2.applications/shadowsocks-libev/compile] Error 2

When patched asciidoc.conf from https://raw.githubusercontent.com/shadowsocks/shadowsocks-libev/9c00f5a6ac22665da3506a2e0c434f3401535755/doc/asciidoc.conf
Error infomation:
make[5]: Leaving directory `/home/everun/openwrt/branches/chaos_calmer/openwrt/build_dir/target-mips_34kc_uClibc-0.9.33.2/shadowsocks-libev-openssl/shadowsocks-libev-2.4.8/src'
Making all in doc
make[5]: Entering directory `/home/everun/openwrt/branches/chaos_calmer/openwrt/build_dir/target-mips_34kc_uClibc-0.9.33.2/shadowsocks-libev-openssl/shadowsocks-libev-2.4.8/doc'
  GEN      shadowsocks-libev.xml
WARNING: [partintroblock] missing template section
FAILED: [tabledef-default] missing section: [tabletags-header]
make[5]: *** [shadowsocks-libev.xml] Error 1
make[5]: Leaving directory `/home/everun/openwrt/branches/chaos_calmer/openwrt/build_dir/target-mips_34kc_uClibc-0.9.33.2/shadowsocks-libev-openssl/shadowsocks-libev-2.4.8/doc'
make[4]: *** [all-recursive] Error 1
make[4]: Leaving directory `/home/everun/openwrt/branches/chaos_calmer/openwrt/build_dir/target-mips_34kc_uClibc-0.9.33.2/shadowsocks-libev-openssl/shadowsocks-libev-2.4.8'
make[3]: *** [all] Error 2
make[3]: Leaving directory `/home/everun/openwrt/branches/chaos_calmer/openwrt/build_dir/target-mips_34kc_uClibc-0.9.33.2/shadowsocks-libev-openssl/shadowsocks-libev-2.4.8'
make[2]: *** [/home/everun/openwrt/branches/chaos_calmer/openwrt/build_dir/target-mips_34kc_uClibc-0.9.33.2/shadowsocks-libev-openssl/shadowsocks-libev-2.4.8/.built] Error 2
make[2]: Leaving directory `/home/everun/openwrt/branches/chaos_calmer/openwrt/everun/2.applications/shadowsocks-libev'
make[1]: *** [package/everun/2.applications/shadowsocks-libev/compile] Error 2
make[1]: Leaving directory `/home/everun/openwrt/branches/chaos_calmer/openwrt'
make: *** [package/everun/2.applications/shadowsocks-libev/compile] Error 2

**Comment by madeye** [comment]
Try the latest commit.
