### ISSUE TITLE
Is there a way to disable encryption?

### ISSUE THREAD

**Issue by zoobab** [shadowsocks/shadowsocks-libev#762]
Hi,

Is there a way to disable encryption?

The "table" algo seems to do encryption, and for my use case (simply having a socks proxy), I don't need encryption.

Could you add support for a none cipher (like openvpn has)?

Best,

**Comment by madeye** [comment]
Nope, you can't. Also, shadowsocks cannot work as a socks5 proxy.

If you're looking for a normal SOCKS5 proxy, try this: https://www.inet.no/dante/

**Comment by zoobab** [comment]
If I have  make a patch to disable the encryption, will you accept it?

**Comment by madeye** [comment]
You can keep your modification as a fork. But I choose not to merge the change back.

**Comment by spyff** [comment]
In this fork, the encryption is optional. Use `none` cipher to disable encryption.
https://github.com/spyff/shadowsocks-libev-nocrypto

**Comment by 0neday** [comment]
just test remove all encrytion, see here https://github.com/0neday/shadowsocks-libev-no-encryption/commit/2aa9c76c6e5c648ed194705db448d416f991bd5b
