### ISSUE TITLE
mptcp error

### ISSUE THREAD

**Issue by rstanislav** [shadowsocks/shadowsocks-libev#765]
On mptcp enabled kernel 4.1.20, with option in json config:
"mptcp" : true
i get
ERROR: failed to enable multipath TCP: Protocol not available

mptcp 100% enabled and working, for example output of 
dmesg | grep MPTCP
[ 0.636141] MPTCP: Stable release v0.90

cat /proc/sys/net/ipv4/tcp_congestion_control
balia
system is ubuntu 14.04.01
also i have disabled ipv6 in kernel.. maybe thats the cause ?

**Comment by rstanislav** [comment]
Erro is in this lines i guess:

> #ifdef __APPLE__
>         int opt = 1;
> #else
>         int opt = 5;
> #endif

opt value for mptcp option should be 1 in this line:

int err = setsockopt(remotefd, SOL_TCP, MPTCP_ENABLED, &opt, sizeof(opt));

> Since release 0.89, you can set mptcp_enabled to 2. In this case MPTCP will be enabled if the application has set the socket-option MPTCP_ENABLED (value 26) to 1. MPTCP_ENABLED is part of SOL_TCP:
> int enable = 1;
> setsockopt(fd, SOL_TCP, MPTCP_ENABLED, &enable, sizeof(enable));

sorry for my english btw.

**Comment by madeye** [comment]
I'm using the patch from OVH:

https://github.com/ovh/overthebox-shadowsocks-libev/blob/6b55660f39b57bdbb84780d0b3566bff796dfc71/src/server.c#L387

https://github.com/ovh/overthebox-shadowsocks-libev/blob/24be898ca436442bca26b9ee1e0d076f8a036690/src/netutils.h#L26

The interesting part is the MPTCP_ENABLED flag is different from MPTCP's source code: 

https://github.com/multipath-tcp/mptcp/blob/6d0ba0f70770330d82bdc1c4f891041b55abd62e/include/uapi/linux/tcp.h#L116

Could you modify MPTCP_ENABLED to `42` and try again?

**Comment by LazyZhu** [comment]
Actually, it's `26` in v0.90:
https://github.com/multipath-tcp/mptcp/blob/mptcp_v0.90/include/uapi/linux/tcp.h#L115

**Comment by madeye** [comment]
@LazyZhu OK. So we're still using the correct number.

**Comment by rstanislav** [comment]
I have found that somehow in patched mptcp kernel tcp.h i have MPTCP_ENABLED 42, so that was causing error, fixed it and now it works!

**Comment by rstanislav** [comment]
I double checked - in last release of MPTCP (0.91), MPTCP_ENABLED should be 42, not 26, info:

http://multipath-tcp.org/patches/mptcp-v4.1.25-6d0ba0f70770.patch

Line 8075-6:
 #define TCP_CC_INFO		26	/* Get Congestion Control (optional) info */
+#define MPTCP_ENABLED		42

**Comment by debiansid** [comment]
怎么使用mptcp?

**Comment by testcaoy7** [comment]
同问，怎么使用MPTCP
