### ISSUE TITLE
how i can test sslocal?

### ISSUE THREAD

**Issue by polinzhuo** [shadowsocks/shadowsocks-libev#766]
i installed shadowsocks as client in RaspberryPI. I would think that Kodi can use the proxy of sslocal. But it did not work well. How i can test sslocal whether can handle the request on port 1080?

**Comment by hosiet** [comment]
Try [proxychains](http://proxychains.sourceforge.net).

**Comment by madeye** [comment]
And [socksify](https://www.inet.no/dante/doc/1.3.x/socksify.1.html).

**Comment by polinzhuo** [comment]
kodi can use socks5 proxy, but the setting did not work. Must I use redirect proxy software?
