### ISSUE TITLE
Compilation issue on 14.04 (redclared TCP structs)

### ISSUE THREAD

**Issue by awbacker** [shadowsocks/shadowsocks-libev#768]
Having some issues compiling on 14.04.  Can't build the .deb package either, and can't install from the repo since that requires init-system-helpers 1.18 which isn't easily available on 14.04 (still hunting that down.)  Seems impossible to use here, which is odd considering its one of the most commonly deployed releases.

```
Linux localhost 4.6.3-x86_64 #1 SMP Thu Jul 7 17:35:46 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux

./configure --disable-documentation (800mb for those! x11! w.t.heck)
make
```

```
In file included from netutils.h:29:0,
                 from udprelay.c:60:
/usr/include/linux/tcp.h:24:8: error: redefinition of ‘struct tcphdr’
 struct tcphdr {
        ^
In file included from udprelay.c:38:0:
/usr/include/netinet/tcp.h:74:8: note: originally defined here
 struct tcphdr
        ^
In file included from netutils.h:29:0,
                 from udprelay.c:60:
/usr/include/linux/tcp.h:116:8: error: redefinition of ‘struct tcp_repair_opt’
 struct tcp_repair_opt {
        ^
In file included from udprelay.c:38:0:
/usr/include/netinet/tcp.h:259:8: note: originally defined here
 struct tcp_repair_opt
        ^
.... and so on
```

Here is the output of ./configure ([configure.out.txt](https://github.com/shadowsocks/shadowsocks-libev/files/412700/configure.out.txt))

Not sure where to go form here, but I've had bad luck with the go port as well.  Only one that runs is the python, which is not ideal.

**Comment by awbacker** [comment]
[configure.out.txt](https://github.com/shadowsocks/shadowsocks-libev/files/412700/configure.out.txt)

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks-libev/commit/722d8d0c6265705c9ca730d8d037301acf213c3c

**Comment by awbacker** [comment]
Jebus, are you a bot!  That was... just.... wow.
