### ISSUE TITLE
failed to resolve server name

### ISSUE THREAD

**Issue by simonsmh** [shadowsocks/shadowsocks-libev#769]
debian8.5 at latest commit
 2016-08-14 13:31:59 INFO: listening at 0.0.0.0:112
^C 2016-08-14 13:32:09 ERROR: failed to resolve server name,
 wait 8 seconds
^C 2016-08-14 13:32:14 ERROR: failed to resolve server name,
 wait 16 seconds
^C 2016-08-14 13:32:15 ERROR: failed to resolve server name,
 wait 32 seconds
^C 2016-08-14 13:32:17 ERROR: failed to resolve server name,
 wait 64 seconds
^C 2016-08-14 13:32:18 ERROR: failed to resolve server name,
 wait 128 seconds
 2016-08-14 13:32:18 ERROR: getaddrinfo: Address family for
hostname not supported
 2016-08-14 13:32:18 ERROR: bind() error
root@simonsmh:~#

**Comment by madeye** [comment]
Double check your hostname.

**Comment by simonsmh** [comment]
root@simonsmh:~# hostname -i
127.0.0.1 ::1
root@simonsmh:~#

**Comment by simonsmh** [comment]
`"server":["[::0]", "0.0.0.0"],` report bind error，
but `"server":"0.0.0.0",` works. 
@madeye

**Comment by madeye** [comment]
`"server":["::0", "0.0.0.0"]`

**Comment by hosiet** [comment]
@madeye I wrote `"server":["[::0]", "0.0.0.0"]` in `ss-server(1)` man page and it worked well in tagged 2.4.8 version. Has the behaviour changed since then?

**Comment by madeye** [comment]
@hosiet Let me correct the sample config. It'd be `"::0"`

**Comment by zinian** [comment]
"server":["::0", "0.0.0.0"]
需要主机有ipv6地址，没有还会同样的报错
希望可以像python版 直接 ::0  同时支持ipv4，ipv6。
