### ISSUE TITLE
如何避免被运营商QoS限速

### ISSUE THREAD

**Issue by kang000feng** [shadowsocks/shadowsocks-libev#771]
服务端已经是最新，发现在观看国外视频时没多久就被限速，从1MB／s下降到30－50KB／s，切换到另外一个端口又暂时恢复正常，后面又重复前述现象，试过常见端口443到2000以上端口，无改善。求教各位？！
另外观看国外视频经常性被断流，无论是直连还是开SS，ISP电信，有同样碰到该问题的吗？

**Comment by madeye** [comment]
Try some other ISP.
