### ISSUE TITLE
IPv6 优先

### ISSUE THREAD

**Issue by maxchendt** [shadowsocks/shadowsocks-libev#772]
请问如下情形如何实现：本地和vps都是双栈的，两者之间IPv4连接和IPv6连接都正常。
本地和vps IPv4连接下，发现ss-server总是连接网站的IPv4，传给本地。
本地和vps IPv6连接下，发现ss-server还是连接网站的IPv4，传给本地。

比如，本地 [2001::] 连接 ss  [2607::], 在vps上 命令 `lsof -i -P -n | grep [s]s-s` 的结果如下 （vps的 IPv4 为1.2.3.4）
ss-server   293 nobody    6u  IPv4 1745182358      0t0  TCP *:8964 (LISTEN)
ss-server   293 nobody    7u  IPv4 1745182360      0t0  UDP *:8964 
ss-server   293 nobody    8u  IPv6 1745182362      0t0  TCP *:8964 (LISTEN)
ss-server   293 nobody    9u  IPv6 1745182364      0t0  UDP *:8964 
ss-server   293 nobody   10u  IPv4 1996833488      0t0  TCP 1.2.3.4:44586->216.58.193.194:443 (ESTABLISHED)
ss-server   293 nobody   11u  IPv6 1996833562      0t0  TCP [2607::]:8964->[2001::]:47328 (ESTABLISHED)
ss-server   293 nobody   12u  IPv6 1996830577      0t0  TCP [2607::]:8964->[2001::]:47284 (ESTABLISHED)
ss-server   293 nobody   13u  IPv4 1996830598      0t0  TCP 1.2.3.4:51225->216.58.216.46:443 (ESTABLISHED)
ss-server   293 nobody   14u  IPv6 1996830993      0t0  TCP [2607::]:8964->[2001::]:47288 (ESTABLISHED)
我们看到，对于 youtu.be当前浏览，ss代理时，ss-server总是读取youtu.be的 IPv4网站，然后用IPv6打包送给本地

当前的想法是：能否local 与 server连接采用IPv6时，server端优先读取的是IPv6网站？
更进一步的想法：能否local 与 server连接采用IPv4时，server端仍然优先读取的是IPv6网站？（这样做的好处是，教育网等IPv6可以直通google 等IPv6网站，在没有native IPv6的地方，IPv4连接双栈的教育网ss-server，ss-server将读取的IPv6网站内容转IPv4传输给local端）

**Comment by wongsyrone** [comment]
使用参数
-6
Resovle hostname to IPv6 address first.

**Comment by maxchendt** [comment]
谢谢了！搞定！
src/server.c 中也看到了
`        case '6':
            ipv6first = 1;
            break;
`
成功实现 IPv4连接时，ss-server连接IPv6网站
`sudo lsof -i -P -n | grep [s]s-s` 结果如下（双栈的IPv4为 210.34.210.34, IPv6为2001:: ）
ss-server 32500  nobody    5u  IPv4 266180      0t0  UDP *:46568 
ss-server 32500  nobody    6u  IPv4 266183      0t0  TCP *:8683 (LISTEN)
ss-server 32500  nobody    7u  IPv4 266185      0t0  UDP *:8683 
ss-server 32500  nobody    8u  IPv6 266187      0t0  TCP *:8683 (LISTEN)
ss-server 32500  nobody    9u  IPv6 266189      0t0  UDP *:8683 
ss-server 32500  nobody   10u  IPv4 268346      0t0  TCP 210.34.210.34:8683->10.1.2.4:38518 (ESTABLISHED)
ss-server 32500  nobody   11u  IPv6 268349      0t0  TCP [2001::]:43958->[2607:f8b0:4007:800::200e]:443 (ESTABLISHED)
ss-server 32500  nobody   12u  IPv4 268350      0t0  TCP 210.34.210.34:8683->10.1.2.4:38522 (ESTABLISHED)
ss-server 32500  nobody   13u  IPv6 268351      0t0  TCP [2001::]:43960->[2607:f8b0:4007:800::200e]:443 (ESTABLISHED)
ss-server 32500  nobody   14u  IPv4 268352      0t0  TCP 210.34.210.34:8683->10.1.2.4:38526 (ESTABLISHED)
ss-server 32500  nobody   15u  IPv4 267841      0t0  TCP 210.34.210.34:8683->10.1.2.4:38530 (ESTABLISHED)
ss-server 32500  nobody   16u  IPv6 267844      0t0  TCP [2001::]:43962->[2607:f8b0:4007:800::200e]:443 (ESTABLISHED)
ss-server 32500  nobody   17u  IPv6 268359      0t0  TCP [2001::]:52010->[2607:f8b0:4007:807::2001]:443 (ESTABLISHED)
ss-server 32500  nobody   18u  IPv4 268362      0t0  TCP 210.34.210.34:8683->10.1.2.4:38542 (ESTABLISHED)
ss-server 32500  nobody   19u  IPv6 268365      0t0  TCP [2001::]:43970->[2607:f8b0:4007:800::200e]:443 (ESTABLISHED)
