### ISSUE TITLE
关于开机自启的问题

### ISSUE THREAD

**Issue by qious** [shadowsocks/shadowsocks-libev#774]
ubuntu 16.04.1 server lts
单独修改 /etc/default/shadowsocks-libev  里面的 START 值为 no (非 yes 的任意值)，并不能阻止开机自启，需要再执行 sudo systemctl disable shadowsocks-libev.service

**Comment by hosiet** [comment]
https://github.com/shadowsocks/shadowsocks-libev/blob/master/debian/shadowsocks-libev.default#L8

This is the normal behaviour.
