### ISSUE TITLE
udp command stat working abnormally

### ISSUE THREAD

**Issue by vkill** [shadowsocks/shadowsocks-libev#775]
```ruby
require 'socket'

u = UDPSocket.new
u.connect('127.0.0.1', 20000)

u.send('ping', 0)
u.recvmsg_nonblock
=> ["stat: {\"22001\":1007917}", #<Addrinfo: 127.0.0.1:20000 UDP>, 1073741824]

u.send('stat: {"22001":0}', 0)

u.send('ping', 0)
u.recvmsg_nonblock
=> ["stat: {\"22001\":0}", #<Addrinfo: 127.0.0.1:20000 UDP>, 1073741824]

# wait some times

u.send('ping', 0)
u.recvmsg_nonblock
=> ["stat: {\"22001\":1007917}", #<Addrinfo: 127.0.0.1:20000 UDP>, 1073741824]
```

Hi
My shadowsocks-libev version is 2.4.8
The traffic will auto recovery.
I think it's a bug.

**Comment by madeye** [comment]
```
u.send('stat: {"22001":0}', 0)
```

This command means you set the traffic of port 22001 to 0. It wouldn't work as the client will send the latest traffic number to `manager` and override the 0.

Actually, you should not use `stat` command in your app. It's for `ss-server` to send back the real time traffic number.

**Comment by vkill** [comment]
oh, maybe I should call `remove` then call `add`, the traffic number will back to 0.
