### ISSUE TITLE
How to build git version for openwrt

### ISSUE THREAD

**Issue by debiansid** [shadowsocks/shadowsocks-libev#777]
Is there a way to git pull newest version and compile for openwrt?

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks-libev/blob/master/openwrt/Makefile#L4

**Comment by debiansid** [comment]
this is 2.4.8, what i mean is the newest code from git

**Comment by madeye** [comment]
Change this version to your desired commit number.

**Comment by debiansid** [comment]
'5812840b' 
and change source URL into git?
