### ISSUE TITLE
Building shadowsocks-libev server on Cygwin (for Cygwin)

### ISSUE THREAD

**Issue by KarlM256** [shadowsocks/shadowsocks-libev#791]
Hi...

Since Cygwin is a Posix environment, I build and tested version 2.5.0 and master for Cygwin, The server fails with many errors. Can you advise on how I correct the problem? This was on a Win 7 Pro 64 machine. For the test I connected to the server with the shadowsocks-android client and then clicked on test link one time.
[shadowsocks-libev-master.txt](https://github.com/shadowsocks/shadowsocks-libev/files/445670/shadowsocks-libev-master.txt)

I have attached the build and test logs.

Thanks,

...Karl
[shadowsocks-libev-2.5.0.txt](https://github.com/shadowsocks/shadowsocks-libev/files/445659/shadowsocks-libev-2.5.0.txt)

**Comment by madeye** [comment]
Double check your client's config.

**Comment by bigtan** [comment]
@KarlM256 用msys2 + mingw64 的 gcc编译。

**Comment by KarlM256** [comment]
The default values for the command line options for shadowsocks-libev are much different than the shadowsocks python server. I had not expected that. It works fine now. Thanks.
