### ISSUE TITLE
编译waring？

### ISSUE THREAD

**Issue by sijidou** [shadowsocks/shadowsocks-libev#792]
HI！
我编译的时候总是报错，虽然最终是成功了没错，但总觉得怕怕的..
ev.c:1692:31: warning: 'ev_default_loop_ptr' initialized and declared 'extern'
   EV_API_DECL struct ev_loop *ev_default_loop_ptr = 0; /* needs to be initialised to make it a definition despite ex
                               ^
ev.c: In function 'evpipe_write':
ev.c:2321:11: warning: ignoring return value of 'write', declared with attribute warn_unused_result [-Wunused-result]
           write (evpipe [1], &counter, sizeof (uint64_t));
           ^
ev.c:2333:11: warning: ignoring return value of 'write', declared with attribute warn_unused_result [-Wunused-result]
           write (evpipe [1], &(evpipe [1]), 1);
           ^
ev.c: In function 'pipecb':
ev.c:2354:11: warning: ignoring return value of 'read', declared with attribute warn_unused_result [-Wunused-result]
           read (evpipe [1], &counter, sizeof (uint64_t));
           ^
ev.c:2368:11: warning: ignoring return value of 'read', declared with attribute warn_unused_result [-Wunused-result]
           read (evpipe [0], &dummy, sizeof (dummy));
           ^

代码是如上一段，环境是ubuntu 16..
这样编译后的，可以正常使用吗？

**Comment by madeye** [comment]
It's expected.
