### ISSUE TITLE
Useage of OTA

### ISSUE THREAD

**Issue by KarlM256** [shadowsocks/shadowsocks-libev#794]
Hi...

I see how OTA adds protection while I am using it with a client, by specifying OTA in the client.

Is there an advantage of specifying OTA on the server, other than keeping my users from not using OTA? What I mean is, does setting OTA offer any protection against attacks directed at the server itself, not just a particular session?

Thanks,

...Karl

**Comment by madeye** [comment]
Nope.

**Comment by KarlM256** [comment]
Thanks.
