### ISSUE TITLE
建议添加Centos编译安装的办法

### ISSUE THREAD

**Issue by VampireSH** [shadowsocks/shadowsocks-libev#795]
这是咱把https://teddysun.com/357.html By秋水逸冰的一键安装拆开来看后拉出来的
yum install 
wget unzip openssl-devel gcc swig python python-devel python-setuptools autoconf libtool libevent xmlto automake make curl curl-devel zlib-devel openssl-devel perl perl-devel cpio expat-devel gettext-devel asciidoc
建议在README上添加，因为估计也有人喜欢用源码编译的方式但是使用Centos系统而不知道依赖怎么安装

**Comment by debiansid** [comment]
同建议解决生成rpm的bug
