### ISSUE TITLE
请问加上--fast-open后，不能打开google网站，但是访问其他网站正常，知道是怎么回事吗？

### ISSUE THREAD

**Issue by renjie45** [shadowsocks/shadowsocks-libev#798]
Ubuntu 14.04.4 LTS (GNU/Linux 3.13.0-29-generic x86_64)
启动为ss-server -c /root/otaconfig.json -u -A --fast-open 
把--fast-open去掉后，google网站又正常了。
有装锐速。

**Comment by VampireSH** [comment]
反了

renjie45 <notifications@github.com>于2016年9月3日周六 13:13写道：

**Comment by way2stars** [comment]
你装了锐速吧？

**Comment by renjie45** [comment]
是的装了锐速了，好像是和锐速有关系。

**Comment by kang000feng** [comment]
@renjie45  @madeye  我也碰到了,跟你一样的, 请问找到真正原因了吗?

**Comment by blackgear** [comment]
> 解决方法很简单，配置锐速的shortRttMS参数即可，比如GCE上ping谷歌rtt约0.3ms，设置该参数为1就能让锐速跳过对访问谷歌的单向加速，但仍然保留到客户端的单向加速。
https://twitter.com/atomhelix/status/852000755175235584
