### ISSUE TITLE
Not found in Ubuntu 16.04 Repo

### ISSUE THREAD

**Issue by whao** [shadowsocks/shadowsocks-libev#799]
Shadowsocks-libev cannot be fount in Ubuntu 16.04 Official Repo

> whao@Wei-Parallels-Virtual-Platform:~$ sudo apt search shadowsocks
[sudo] password for whao: 
Sorting... Done
Full Text Search... Done
shadowsocks/xenial,xenial 2.1.0-1 all
  Fast tunnel proxy that helps you bypass firewalls

**Comment by hosiet** [comment]
It is expected. You can only find shadowsocks-libev on Ubuntu 16.10+ or
Debian 9+.

在 2016年9月3日週六 17:17，Wei Hao <notifications@github.com> 寫道：
