### ISSUE TITLE
Confused of the `-f <pid_file>` option of `ss-manager`

### ISSUE THREAD

**Issue by ungrown** [shadowsocks/shadowsocks-libev#800]
I have multiple users configured in my .conf file, with which runs `ss-manager` well, without `-f` switch, and there are pid files laid in my home dir.
However, I have no idea how to specify the <pid file> by `-f` switch. I have tried `ss-manager -f /path/to/file [ other options ... ]`, no good.
Doc is pretty poor, anyone got experience about `-f` of `ss-manager`?

**Comment by madeye** [comment]
It's the pid file for ss-manager.

**Comment by ungrown** [comment]
@madeye
Sorry for the unclear title. It's that the usage of `-f` option is really ambiguous in the doc. I followed the `--help` doc but it just didn't work.
