### ISSUE TITLE
`-f <pid_file>` option of ss-manager doesn't work

### ISSUE THREAD

**Issue by ungrown** [shadowsocks/shadowsocks-libev#801]
It just doesn't.
All I do is appending `-f /path/to/file` to my original ss-manager command which worked well. 
Let me know if I missed something. Thank you so much.

**Comment by madeye** [comment]
Post your command line here.

**Comment by ungrown** [comment]
```shell
ss-manager --manager -address 127.0.0.1:65000 -vuA -c /path/to/config.json
```
I simply added `-f /path/to/pidfile` to the command above.

**Comment by madeye** [comment]
`--manager -address` should be `--manager-address`.
