### ISSUE TITLE
`-f <pid_file>` option of ss-manager doesn't work

### ISSUE THREAD

**Issue by ungrown** [shadowsocks/shadowsocks-libev#802]
```shell
ss-manager --manager-address 127.0.0.1:65000 -vuA -c /path/to/config.json -f /path/to/pidfile
```

BTW you have impatiently closed two of my issues without any further interaction. I'm using mobile phone typing, there might be some typos or unclear composing. how can you just close the issues with a glance as like you hate them?

**Comment by madeye** [comment]
I cannot reproduce your issue by following your command line. It just works well.

Double check your command line. Make sure no typos there.

**Comment by pexcn** [comment]
-v 参数是不是会和 -f 产生冲突？

**Comment by madeye** [comment]
@pexcn Nope
