### ISSUE TITLE
It's a shame the issue board is empty, especialy with your "one-command-then-kill" reaction

### ISSUE THREAD

**Issue by ungrown** [shadowsocks/shadowsocks-libev#803]
Really good strategy. Enjoy your "stainless" issue board. 

*p.s. Thankfully you are the only one I know doing like this at github.*

**Comment by kimw** [comment]
Hi @ungrown,

Maybe the author, @madeye, just like to keep the issue list to be clean, I think. Just like I always want to be ;)  You know, my dirty todo list is a nightmare which makes me never want to check it :(

And, I wouldn't tell anyone, at the situation I think my question is not solved, I always **re-open** it again and again till I satisfied :) Hope it useful.

Yours, @kimw
