### ISSUE TITLE
MultiPath TCP function in 2.5.0

### ISSUE THREAD

**Issue by braveguywallce** [shadowsocks/shadowsocks-libev#806]
Hi, just very curious about the new feature in version 2.5.0, the so called " MultiPath TCP" supported. I would like to know if anyone else had ever test this  new feature by himself and report the actual outcome of the performance for shadowsocks with/without MultiPath TCP supported.  

After all, this is a new technology of network. Thanks for Max to bring this!

**Comment by madeye** [comment]
It's not implemented by me, but from OVH's fork.

https://github.com/shadowsocks/shadowsocks-libev/issues/756

**Comment by madeye** [comment]
It's an issue tracker. Please don't post general questions here.

**Comment by braveguywallce** [comment]
I will test it in my free time, thanks!
