### ISSUE TITLE
/etc/init.d/shadowsocks start报错

### ISSUE THREAD

**Issue by Dark1X** [shadowsocks/shadowsocks-libev#808]
version: shadowsocks-libev_2.4.8-3_ar71xx.ipk
Openwrt version: 14.07
操作流程：
shadowsocks的配置文件为：/etc/config/shadowsocks.json
安装好shadowsocks后在/etc/init.d中并没有看到启动脚本，于是新建了一个启动脚本，内容如下:
#!/bin/sh /etc/rc.common
START=95

SERVICE_USE_PID=1
SERVICE_WRITE_PID=1
SERVICE_DAEMONIZE=1
SERVICE_PID_FILE=/var/run/shadowsocks.pid
CONFIG=/etc/config/shadowsocks.json
DNS=8.8.8.8:53
TUNNEL_PORT=5353

start(){
service_start/usr/bin/ss-redir-c$CONFIG-b0.0.0.0-f$SERVICE_PID_FILE
}

stop(){
service_stop/usr/bin/ss-redir
}
保存退出后chmod a+x增加了运行权限。然后执行/etc/init.d/shadowsocks enable && /etc/init.d/shadowsocks start报错，报错信息如下：
/etc/rc.common: line 138: service_start/usr/bin/ss-redir-c/etc/config/shadowsocks.json-b0.0.0.0-f/var/run/shadowsocks.pid: not found
无解TAT

**Comment by xuanjingyao** [comment]
sed -i 's/\r$//' /etc/init.d/shadowsocks
可以更方便一点
try！
