### ISSUE TITLE
Consider bumping soname of libshadowsocks-libev

### ISSUE THREAD

**Issue by hosiet** [shadowsocks/shadowsocks-libev#811]
### What version of shadowsocks-libev are you using?
2.5.0 trunk

### What operating system are you using?
N/A

### What did you do?
N/A

### What did you expect to see?
The major version of libshadowsocks-libev should be increased due to the change on profile_t in shadowsocks.h in the recent pull request, since such change breaks ABI compatibility.

### What did you see instead?
N/A

### What is your config in detail (with all sensitive info masked)?
N/A

**Comment by madeye** [comment]
Could you open a pull request for this?

**Comment by hosiet** [comment]
OK, will open PR later.

在 2016年9月8日週四 11:57，Max Lv <notifications@github.com> 寫道：
