### ISSUE TITLE
--acl 使用方法

### ISSUE THREAD

**Issue by debiansid** [shadowsocks/shadowsocks-libev#812]
--acl 是如何使用的

Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
2.5.0 trunk

### What operating system are you using?
ubuntu & lede trunk

### What did you do?
ubuntu on vps as server, ss-redir/ss-local on lede trunk as client

### What did you expect to see?
acl acting 

### What did you see instead?
N/A

**Comment by madeye** [comment]
It's an hidden feature for Android/iOS client, not exposed.
