### ISSUE TITLE
--without-libpcre-prefix not working

### ISSUE THREAD

**Issue by xseven007** [shadowsocks/shadowsocks-libev#813]
First time, I have alreadly install libpcre pcre pcre-devel by pacman, then I tried to build with "./configure --with-openssl=$OPENSSL_PREFIX --disable-ssp --disable-documentation", and it said "*** libpcre was not found. "
And then I tried to build it with "./configure --with-openssl=$OPENSSL_PREFIX --disable-ssp --disable-documentation --without-libpcre-prefix", but it said "libpcre was not found." Again.
It is that the command line "--without-libpcre-prefix" does not work?

### What version of shadowsocks-libev are you using?
lastest github commits version 2.5.0 trunk

### What operating system are you using?
Windows 10, msys2 with mingw64

### What did you do?
Build from source with mingw64

### What did you expect to see?
build success

### What did you see instead?
checking for LIBPCRE... no
checking for libpcre... no
configure: error: ***
*** libpcre was not found.

### What is your config in detail (with all sensitive info masked)?
./configure --with-openssl=$OPENSSL_PREFIX --disable-ssp --disable-documentation --without-libpcre-prefix

**Comment by madeye** [comment]
Try the latest commit: https://github.com/shadowsocks/shadowsocks-libev/commit/fef0271f589c0cbb1e0467574a77c2f43d582a9e

**Comment by xseven007** [comment]
I have run "git pull" to get the latest github version, And It still show 
checking checking for pcre includes in /usr... checking for pcre headers in /usr/include... ok
checking for library containing pcre_exec... no
configure: error: Cannot find pcre library. Configure --with-pcre=DIR

I have already install pcre libpcre and so on.

$ pacman -Ss pcre
mingw32/mingw-w64-i686-pcre 8.38-1
    A library that implements Perl 5-style regular expressions (mingw-w64)
mingw64/mingw-w64-x86_64-pcre 8.38-1
    A library that implements Perl 5-style regular expressions (mingw-w64)
msys/libpcre 8.38-1 (libraries) [installed]
    A library that implements Perl 5-style regular expressions
msys/libpcre16 8.38-1 (libraries) [installed]
    A library that implements Perl 5-style regular expressions
msys/libpcre32 8.38-1 (libraries) [installed]
    A library that implements Perl 5-style regular expressions
msys/libpcrecpp 8.38-1 (libraries) [installed]
    A library that implements Perl 5-style regular expressions
msys/libpcreposix 8.38-1 (libraries) [installed]
    A library that implements Perl 5-style regular expressions
msys/pcre 8.38-1 [installed]
    A library that implements Perl 5-style regular expressions
msys/pcre-devel 8.38-1 (development) [installed]
    PCRE headers and libraries

**Comment by madeye** [comment]
As the error said, you need to `Configure --with-pcre=DIR`.

**Comment by xseven007** [comment]
Yes, I have. 
./configure --with-openssl=$OPENSSL_PREFIX --disable-ssp --disable-documentation --with-pcre=/usr

**Comment by wongsyrone** [comment]
You put pcre into msys2 instead of MinGW toolchain

**Comment by wongsyrone** [comment]
For MinGW64, install via `pacman -S mingw-w64-x86_64-pcre`

**Comment by xseven007** [comment]
OMG, I have know what problem with me.  when the configure command using"./configure --with-openssl=$OPENSSL_PREFIX --disable-ssp --disable-documentation --with-pcre=/usr/ ". And then build pass..

**Comment by madeye** [comment]
I don't think it's root cause, `--with-pcre=` is handled properly: https://github.com/shadowsocks/shadowsocks-libev/blob/master/m4/pcre.m4#L76

**Comment by xseven007** [comment]
So, I don't know what the real problem is. And I found that the exe files which are build with pcre shared library need the "libpcre-1.dll". Then I tried to rebuild the pcre frome source in order to get the static library. That's great!
