### ISSUE TITLE
能否支持多线程传输功能？

### ISSUE THREAD

**Issue by zhfreal** [shadowsocks/shadowsocks-libev#816]
目前较多的服务器/防火墙对单线程TCP连接有限速，但多线程连接能达到满意的速度。问题是目前很多程序不支持多线程连接网络传输。这些程序往往SS效果不是很好。能否在SS的传输层实现多线程连接传输的功能？相当于在客户端与服务端建立多条传输通道。SS对一条TCP连接的数据分发到多个传输通道，实现加速。这个需求难点是不是在分包和组包？

**Comment by zhfreal** [comment]
这个需求个人觉得很有趣。个人对网络协议不是太熟，请大神看看能否实现。

**Comment by madeye** [comment]
No plan for this. Also, try https://github.com/d1sm/finalspeed/tree/fileshare.

**Comment by ihciah** [comment]
> 目前较多的服务器/防火墙对单线程TCP连接有限速，但多线程连接能达到满意的速度。问题是目前很多程序不支持多线程连接网络传输。这些程序往往SS效果不是很好。能否在SS的传输层实现多线程连接传输的功能？相当于在客户端与服务端建立多条传输通道。SS对一条TCP连接的数据分发到多个传输通道，实现加速。这个需求难点是不是在分包和组包？

I implemented one: https://github.com/ihciah/go-shadowsocks-magic

**Comment by PantherJohn** [comment]
@zhfreal `kcptun` has the “conn” option for multithreaded UDP transfer. You might also be interested in [`viamillipede`](https://github.com/agokhale/viamillipede) that allows parallel sending of TCP packets. (not tested though)
