### ISSUE TITLE
Is there any instruction to compile another version - shadowsocks-libev-spec based on shadowsocks-libev ?

### ISSUE THREAD

**Issue by simonchen** [shadowsocks/shadowsocks-libev#817]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
2.5.0

### What operating system are you using?
Ubuntu server 14.04

### What did you do?
Compile the source code with Openwrt 

### What did you expect to see?
I want to get the optimized version where I can find ss-rules, ss-redir, ss-tunnel bin files in /usr/bin/ in my router with Openwrt system.

### What did you see instead?
By the default instruction, I just got ss-local, ss-redir, ss-tunnel.

### What is your config in detail (with all sensitive info masked)?
No extra config.

Thanks!

**Comment by madeye** [comment]
Build https://github.com/shadowsocks/openwrt-shadowsocks and https://github.com/shadowsocks/luci-app-shadowsocks separately.

**Comment by simonchen** [comment]
I appreciate your help, but unfortunately, I can't compile Luci-app-shadowsocks , below is the errors, any thoughts?

configure: error: Invalid kernel source directory /lib/modules/4.2.0-27-generic/source
make[2]: *** [/home/chen/openwrt/build_dir/target-mips_34kc_musl-1.1.15/linux-ar71xx_generic/ipset-6.24/.configured_yyy] Error 1
make[2]: Leaving directory `/home/chen/openwrt/package/network/utils/ipset'
make[1]: *** [package/network/utils/ipset/compile] Error 2
make[1]: Leaving directory `/home/chen/openwrt'
make: *** [package/luci-app-shadowsocks/compile] Error 2

**Comment by madeye** [comment]
Open an issue there: https://github.com/shadowsocks/luci-app-shadowsocks

**Comment by simonchen** [comment]
thanks again, I do
