### ISSUE TITLE
MultiplePath means communicating with multiple target servers?

### ISSUE THREAD

**Issue by simonchen** [shadowsocks/shadowsocks-libev#818]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
2.5.0

### What operating system are you using?
Openwrt

### What did you do?
I noticed that you added MultiPath TCP support.

### What did you expect to see?
Think about how to configure client side communicating with multiple target servers?
I'm not sure  that I'm understanding correctly, can MultiPath TCP do that?

**Comment by debiansid** [comment]
multipath-tcp.org

**Comment by simonchen** [comment]
I basically understand the principle how multi-tcp works, but not sure it 's applied to the purpose of connection between shadowsocks SINGLE client & MULTIPLE-servers, even the idea can't be realized by multi-tcp extension, yet it is possible?

**Comment by debiansid** [comment]
As long as shadowsocks works for single client to multiple servers , I thought mptcp works in that way.

**Comment by debiansid** [comment]
Quotes:
You can use ndiffports in order to generate more than one subflow per interface. Each subflow, that belongs to the same mptcp connection, has a different source port but you can't assign arbitrary source ports (this is a mptcp kernel job).
