### ISSUE TITLE
UDP relay issues while ota option changes

### ISSUE THREAD

**Issue by GhostFlying** [shadowsocks/shadowsocks-libev#819]
### What version of shadowsocks-libev are you using?

make with the lastest commit https://github.com/shadowsocks/shadowsocks-libev/commit/61cd731c4ee3c26533a96bf5a21631f31d747610 on Ubuntu 14.04

### What operating system are you using?

Server: Ubuntu 14.04
Client: Shadowsocks Android 3.0.8

### Steps to reproduce

1. simple run the server by ss-server -m chacha20 -p 443 -k test -t 600 -a root -u -s 0.0.0.0 -v

2. connect to server by shadowsocks-android 3.0.8 with udp relay enabled and ota enabled

3. test with any action has dns query, works well and ss-server print log like:
    
    [udp] cache miss: 8.8.8.8:53 <-> x.x.x.x:xx

4. disabled the ota, repeat step 3, then the dns query failed and ss-server print log like:

    [udp] server receive a packet

**Comment by madeye** [comment]
I cannot reproduce your issue. Try the following things:

1. Update shadowsocks-android to 3.1.2
2. Restart your server.

**Comment by GhostFlying** [comment]
I have reproduced after upgrade android client and restart server, and I will try to reproduce on another server.

**Comment by madeye** [comment]
Actually, UDP part doesn't change for months. It looks like that your issue is caused by incorrect config of the server that OTA is forced to be enabled.

**Comment by GhostFlying** [comment]
I reproduced this issue on anther Ubuntu 14.04 server with the same commit and command.

Then I reproduced this on the 3rd server with shadowsocks-libev 2.4.0 and this one print another log while  step 4:

2016-09-10 04:53:49 ERROR: [udp] server_ss_decrypt_all: File exists

**Comment by madeye** [comment]
Please try the latest commit of shadowsocks-libev.

**Comment by GhostFlying** [comment]
It works well, thanks.
