### ISSUE TITLE
Fedora 24 4.7.2-201, ss-redir[1572]: [udp] unable to get dest addr

### ISSUE THREAD

**Issue by bc13x** [shadowsocks/shadowsocks-libev#822]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
https://github.com/shadowsocks/shadowsocks-libev/commit/61cd731c4ee3c26533a96bf5a21631f31d747610

### What operating system are you using?
Fedora 24 

### What did you do?
dnf update kernel from 4.5.5-300 to 4.7.2-201

### What did you expect to see?
ss-redir works fine

### What did you see instead?
ss-redir[1572]: [udp] unable to get dest addr

and ss-redir works fine before kernel update

### What is your config in detail (with all sensitive info masked)?
	sudo ulimit -n 50000
	sudo ss-redir -s server_ip -p 57413 -l 1080 -k password -m aes-256-ctr -u -A -t 7200 -f /var/run/ss-redir.pid
	sudo iptables -t nat -N SHADOWSOCKS
	sudo iptables -t mangle -N SHADOWSOCKS
	sudo iptables -t mangle -N SHADOWSOCKS_MARK
	sudo iptables -t nat -A SHADOWSOCKS -d server_ip -j RETURN
	sudo iptables -t mangle -A SHADOWSOCKS -d server_ip -j RETURN
	sudo iptables -t mangle -A SHADOWSOCKS_MARK -d server_ip -j RETURN
	sudo iptables -t nat -A SHADOWSOCKS -d 10.0.0.0/8 -j RETURN
	sudo iptables -t nat -A SHADOWSOCKS -d 127.0.0.0/8 -j RETURN
	sudo iptables -t mangle -A SHADOWSOCKS -d 10.0.0.0/8 -j RETURN
	sudo iptables -t mangle -A SHADOWSOCKS -d 127.0.0.0/8 -j RETURN
	sudo iptables -t mangle -A SHADOWSOCKS_MARK -d 10.0.0.0/8 -j RETURN
	sudo iptables -t mangle -A SHADOWSOCKS_MARK -d 127.0.0.0/8 -j RETURN
	sudo iptables -t nat -A SHADOWSOCKS -p tcp -j REDIRECT --to-ports 1080
	sudo ip route add local default dev lo table 100
	sudo ip rule add fwmark 1 lookup 100
	sudo iptables -t mangle -A SHADOWSOCKS -p udp -j TPROXY --on-port 1080 --tproxy-mark 1
	sudo iptables -t mangle -A SHADOWSOCKS_MARK -p udp -j MARK --set-mark 1
	sudo iptables -t nat -A OUTPUT -p tcp -j SHADOWSOCKS
	sudo iptables -t mangle -A PREROUTING -p udp -j SHADOWSOCKS
	sudo iptables -t mangle -A OUTPUT -p udp -j SHADOWSOCKS_MARK

**Comment by madeye** [comment]
It's a known bug of Linux kernel 4.7.2. 
https://bugzilla.redhat.com/show_bug.cgi?id=1370061

**Comment by madeye** [comment]
Also see http://www.spinics.net/lists/netfilter-devel/msg43554.html

**Comment by v-gu** [comment]
Archlinux 4.8.14-2-ck-broadwell, problem still occurs.
Verifed the bug had been fixed upstream, and ck kernel indeed inherited the fix.

Here is the iptables rules:
```
iptables -t mangle -N SHADOWSOCKS
iptables -t mangle -A SHADOWSOCKS -d 0.0.0.0/8 -j RETURN
iptables -t mangle -A SHADOWSOCKS -d 10.0.0.0/8 -j RETURN
iptables -t mangle -A SHADOWSOCKS -d 127.0.0.0/8 -j RETURN
iptables -t mangle -A SHADOWSOCKS -d 169.254.0.0/16 -j RETURN
iptables -t mangle -A SHADOWSOCKS -d 172.16.0.0/12 -j RETURN
iptables -t mangle -A SHADOWSOCKS -d 192.168.0.0/16 -j RETURN
iptables -t mangle -A SHADOWSOCKS -d 193.0.0.0/8 -j RETURN
iptables -t mangle -A SHADOWSOCKS -d 224.0.0.0/4 -j RETURN
iptables -t mangle -A SHADOWSOCKS -d 240.0.0.0/4 -j RETURN
iptables -t mangle -A SHADOWSOCKS -p udp --dport 53 -j TPROXY --on-port 1080 --tproxy-mark 0x01/0x01
iptables -t mangle -A PREROUTING -j SHADOWSOCKS
ip rule add fwmark 1/1 lookup 100
ip route add local 0.0.0.0/0 dev lo table 100
```

Here is the kernel's dynamic debug output:
```
2016-12-13 16:07:58 ERROR: [udp] unable to get dest addr
xt_TPROXY: tproxy socket lookup: proto 17 ac121201:40049 -> 08080808:53, lookup type: 1, sock           (null)
xt_TPROXY: tproxy socket lookup: proto 17 ac121201:40049 -> ac12120a:1080, lookup type: 0, sock ffff880221104740
```
