### ISSUE TITLE
shadowsocks-libev 2.5.1

### ISSUE THREAD

**Issue by KarlM256** [shadowsocks/shadowsocks-libev#823]
Please answer these questions before submitting your issue. Thanks!

### What is your config in detail (with all sensitive info masked)? see attached log
[New Text Document.txt](https://github.com/shadowsocks/shadowsocks-libev/files/465709/New.Text.Document.txt)

**Comment by madeye** [comment]
Cygwin is not supported. As you're using Windows 10, try the Ubuntu subsystem: https://msdn.microsoft.com/en-us/commandline/wsl/about

**Comment by KarlM256** [comment]
Cygwin is a POSIX compliant environment. I just did a ./configure and make and it has been working fine.

The errors did not seem to be related to my build environment.
