### ISSUE TITLE
Shadowsocks over KCP can't relay udp using ss-local

### ISSUE THREAD

**Issue by smounives** [shadowsocks/shadowsocks-libev#826]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
2.5.1

### What operating system are you using?
Server: Debian 8.5
Client: Bash on Windows 10 1607 (Ubuntu 14.04)

### What did you do?
I followed [this](https://github.com/shadowsocks/shadowsocks-libev#shadowsocks-over-kcp) step by step

### What did you expect to see?
udp relay correctly.

### What did you see instead?
I got an error on ss-local
`ERROR: unsupported cmd: 3`

### What is your config in detail (with all sensitive info masked)?
```
ss-server -p PORT -k PASSWORD -m chacha20-ietf -u -A
ss-local -s IP -p KCPPORT -k PASSWORD -m chacha20-ietf -l 1080 -b 0.0.0.0 -A &
ss-local -s IP -p PORT -k PASSWORD -m chacha20-ietf -l 1080 -b 0.0.0.0 -U -A
```

**Comment by madeye** [comment]
What's your command line and config of your `ss-local`?

**Comment by smounives** [comment]
edited

**Comment by smounives** [comment]
If I change command line like this:
```
ss-server -p UDPPORT -k PASSWORD -m chacha20-ietf -U -A
ss-local -s IP -p UDPPORT -k PASSWORD -m chacha20-ietf -l 1080 -b 0.0.0.0 -U -A
```
ss-local still say " `ERROR: unsupported cmd: 3`"

**Comment by madeye** [comment]
Please try the latest commit (306f84b).

**Comment by madeye** [comment]
Also, your config is incorrect

`ss-local -s IP -p UDPPORT -k PASSWORD -m chacha20-ietf -l 1080 -b 0.0.0.0 -U -A`
should be
ss-local -s IP -p UDPPORT -k PASSWORD -m chacha20-ietf -l 1080 -b 0.0.0.0 -u -A

**Comment by madeye** [comment]
Similar for the server part

`ss-server -p UDPPORT -k PASSWORD -m chacha20-ietf -U -A`
should be
`ss-server -p UDPPORT -k PASSWORD -m chacha20-ietf -u -A`

**Comment by madeye** [comment]
Please try the latest commit (366fbac).

**Comment by smounives** [comment]
It works fine for me. Thanks!
