### ISSUE TITLE
ss-server, -u option has no effect on ubuntu

### ISSUE THREAD

**Issue by lcdtyph** [shadowsocks/shadowsocks-libev#827]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
2.5.2

### What operating system are you using?
ubuntu 16.04 LTS

### What did you do?
I run ss-server with cmd:
./ss-server -s 0.0.0.0 -p 12580 -m aes-256-cfb -k 123123123123 -u

### What did you expect to see?
I run it with -u option, so netstat must show the udp port being listening

### What did you see instead?
$ netstat -ant | grep 12580
tcp        0      0 0.0.0.0:12580           0.0.0.0:*               LISTEN     
only tcp port display

### What is your config in detail (with all sensitive info masked)?
./ss-server -s 0.0.0.0 -p 12580 -m aes-256-cfb -k 123123123123 -u

**Comment by lcdtyph** [comment]
Sorry, I executed wrong command....

**Comment by kang000feng** [comment]
@lcdtyph hello, i also encountered this issue, may i ask what is right command?

**Comment by lcdtyph** [comment]
@kang000feng 
`netstat -anu ` may be the right command to show all udp connection.
