### ISSUE TITLE
2.5.2无法编译

### ISSUE THREAD

**Issue by om2mo** [shadowsocks/shadowsocks-libev#828]
dpkg-buildpackage -b -us -uc -i

dpkg-buildpackage: source package shadowsocks-libev
dpkg-buildpackage: source version 2.5.2-1ubuntu1
dpkg-buildpackage: source distribution unstable
dpkg-buildpackage: source changed by Max Lv <max.c.lv@gmail.com>
dpkg-buildpackage: host architecture i386
 dpkg-source -i --before-build shadowsocks-libev
dpkg-checkbuilddeps: Unmet build dependencies: libpcre3-dev
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)

**Comment by madeye** [comment]
As the log said,
```
dpkg-checkbuilddeps: Unmet build dependencies: libpcre3-dev
```
Try `sudo apt-get install libpcre3-dev`

**Comment by om2mo** [comment]
Thank you I got it.
