### ISSUE TITLE
configure probably should be smart enough to disable / skip building documents...

### ISSUE THREAD

**Issue by ElTopo** [shadowsocks/shadowsocks-libev#831]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
v2.5.2

### What operating system are you using?
Linux  x86_64 (debian)

### What did you do?
./configure && make

### What did you expect to see?
by default, configure successfully generates makefile for building shadowsocks server binary files, and make successfully builds the binary files.

### What did you see instead?
./configure && make
...
make[2]: Entering directory '/home/lxl/GITs/shadowsocks-libev/doc'
  GEN      shadowsocks-libev.xml
/bin/bash: asciidoc: command not found

=================
I know I can use
./configure --disable-documentation
to skip building doc files, but it would be better if configure checks tools (for building documentation) for makefiles to skip doc targets if these tools are not available. 

After all, documentation files are optional for a working server, and these building tools require relatively large amount disk space for a small embedded system.

I wouldn't mind that target "all" does not including doc targets, in fact I even prefer to use
make doc
to build doc files.

Thanks.

**Comment by madeye** [comment]
I don't think documents are optional. And it's the developer's responsibility to make sure all the dependencies are met.

If you have any problem to build the package from source code, my suggestion is to follow the instructions to install OS specific prebuilt packages.

Also, you don't need to install asciidoc and xmlto on your embedded devices, which are only for cross-compile environment.
