### ISSUE TITLE
openwrt-shadowsocks 运行出现的错误问题

### ISSUE THREAD

**Issue by shao222** [shadowsocks/shadowsocks-libev#832]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
openwrt-shadowsocks 2.5.2 
from: https://github.com/shadowsocks/openwrt-shadowsocks

### What operating system are you using?
Openwrt Chaos Calmer 15.05.1

### What did you do?
配置启动后，log中一直出现如下错误，不知何解。求助！

```
Wed Sep 14 01:24:43 2016 kern.info ss-redir[4835]: Request did not begin with TLS handshake.
Wed Sep 14 01:19:23 2016 kern.err ss-redir[4835]: [udp] UDP server_recv_recvmsg fragmentation: File exists
Wed Sep 14 01:19:25 2016 kern.err ss-redir[4835]: [udp] UDP server_recv_recvmsg fragmentation: Operation now in progress

**Comment by madeye** [comment]
They doesn't matter. Just some warnings.

**Comment by debiansid** [comment]
用mbedtls 版本

**Comment by simonsmh** [comment]
ss-libev 253
完全使用ss-android连接外网服务器，openwrt使用ss-redir
openwrt 2 10.0.0.1使用时频繁连续出现
kern.info ss-redir[1629]: Request did not begin with TLS handshake.
同时ss-android建立连接时log显示
Connection closed by peer
openwrt 2 10.0.1.1使用时出现
kern.info ss-redir[1722]: Request did not begin with TLS handshake.
然而使用完全没问题
两者配置完全一样，环境完全一样
如果从2网络进入1时（不中断连接），ss-android也会继续工作

**Comment by nomadli** [comment]
出did not begin with TLS handshake时无法打开网页，关掉重新开，不出did not begin with TLS handshake 才能正常打开网页
