### ISSUE TITLE
a gaming issue

### ISSUE THREAD

**Issue by haodong** [shadowsocks/shadowsocks-libev#834]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
2.5.2 on my server, but ss-win (the latest version) on the client, also tried ss-libev of 2.4.8 on my router (default by meilin firmware, added UDP feature). I'm trying to compile the latest version manually. SS with Kcptun will also reproduce this issue.

### What operating system are you using?
Windows

### What did you do?
I run ss (router) or ss (win) + proxifier to play the game but unable to lunch multi-clients (more than 2) at the same time. ShadowVPN cannot either, but Astrill VPN can do that. Single or double clients are stable. All of my friends who use the same set to play the game can reproduce the exact result either.

### What did you expect to see?
To be able to play in multi-clients mode.

### What did you see instead?
I did not watch ss's log. But the game has reported that "The socket is closed' or  "The connection to the server was closed", which indicates, according to the GM, that "**its connection to the server is simply too poor to maintain and must be closed**". I think this is not a client issue, but rather, should be concluded as a network transferring problem that can be solved here. Ss is supposed to be able to transfer large-package data, like watching Youtube. Why can it not simply handle multiple gaming clients?

### What is your config in detail (with all sensitive info masked)?
{"password":"password","method":"aes-256-cfb","server_port":port,"server":"server.server.server.server"}

**Comment by madeye** [comment]
If your game is using UDP protocol, it's expected that shadowsocks cannot support multiple sessions on one IP.

My suggestion is to open multiple ss-win clients with different server IPs. Or try any VPN based solution.
