### ISSUE TITLE
ss-redir multiple server high availability suggest.

### ISSUE THREAD

**Issue by mengskysama** [shadowsocks/shadowsocks-libev#835]
### What version of shadowsocks-libev are you using?
shadowsocks-libev ss-redir 2.4.8

### What operating system are you using?
OpenWrt

### What did you do?
Config multiple server for high availability.
When a server down (could connect) this session should redispath to other server (like haproxy option                  redispatch).

### What did you expect to see?
 2016-09-16 15:49:19 INFO: redir to 8.8.8.8:53, len=32
 2016-09-16 15:49:19 INFO: redir to 119.160.254.197:80, len=632
 2016-09-16 15:49:19 ERROR: getpeername: Transport endpoint is not connected
 2016-09-16 15:49:19 INFO: redir to 8.8.8.8:53, len=50
 2016-09-16 15:49:19 ERROR: getpeername: Transport endpoint is not connected
 2016-09-16 15:49:19 INFO: redir to 8.8.8.8:53, len=57
 2016-09-16 15:49:19 INFO: redir to 119.160.254.197:80, len=632
 2016-09-16 15:49:19 ERROR: getpeername: Transport endpoint is not connected
 2016-09-16 15:49:19 INFO: redir to 8.8.8.8:53, len=34

### What did you see instead?
When I let a server down It's not work well.

Failed to load resource: net::ERR_EMPTY_RESPONSE
https://sb.scorecardresearch.com/p?c1=2&c2=7241469&c5=95993639&c7=http%3A%2…ce.yahoo.com%2Fquote%2Fddd%3Fltr%3D1&c14=-1&ns_c=UTF-8&ns__t=1474012161576 Failed to load resource: net::ERR_NAME_RESOLUTION_FAILED
https://platform.twitter.com/widgets.js Failed to load resource: net::ERR_NAME_RESOLUTION_FAILED
http://geo.query.yahoo.com/v1/public/yql?yhlVer=2&yhlClient=rapid&yhlS=9599…=1474012162134&yhlClientVer=3.39.1&yhlRnd=FqhvtVQs89DdtBgY&yhlCompressed=0 Failed to load resource: net::ERR_CONNECTION_REFUSED

### What is your config in detail (with all sensitive info masked)?
{
"server":["2.2.2.2","1.1.1.1"],
"server_port":12000,
"local_port":1081,
"local_address":"0.0.0.0",
"password":"1",
"timeout":600,
"method":"rc4-md5"
}

**Comment by madeye** [comment]
No plan for this.

You may also try: https://github.com/shadowsocks/shadowsocks-libev/issues/572 https://github.com/shadowsocks/shadowsocks-libev/issues/493

**Comment by mengskysama** [comment]
Haproxy is too large for my router.
I will try other way :(

**Comment by madeye** [comment]
I don't think haproxy is too large for routers. Actually, it's quite lightweight.

Try this https://blog.chionlab.moe/2016/01/27/use-haproxy-to-optimize-shadowsocks-on-openwrt/

**Comment by madeye** [comment]
For openwrt, you can just `opkg install haproxy`

**Comment by mengskysama** [comment]
thx. I build a haproxy without https binary just can put it.

**Comment by moralrebuild** [comment]
@madeye 
In fact, haproxy is sooo big! With 400KB binary file, It equals to the sum of two other largest components of LEDE, i.e. wpad-mini and busybox:

ls -lS bin/packages/mips_24kc/*
bin/packages/mips_24kc/base:
total 1940
-rw-r--r-- 1 col col 235596 Oct 20 23:55 wpad-mini_2016-12-19-ad02e79d-6_mips_24kc.ipk
-rw-r--r-- 1 col col 206354 Oct 20 23:56 busybox_1.25.1-4_mips_24kc.ipk
-rw-r--r-- 1 col col 167799 Oct 20 23:52 libmbedtls_2.6.0-2_mips_24kc.ipk
-rw-r--r-- 1 col col 151759 Oct 20 23:57 shadowsocks-libev_3.1.0-1_mips_24kc.ipk
-rw-r--r-- 1 col col  98300 Oct 20 23:55 ppp_2.4.7-11_mips_24kc.ipk
...
bin/packages/mips_24kc/packages:
total 672
-rw-r--r-- 1 col col 415933 Oct 21 13:33 haproxy-nossl_1.7.8-18_mips_24kc.ipk
-rw-r--r-- 1 col col 127842 Oct 20 23:55 libsodium_1.0.12-1_mips_24kc.ipk
-rw-r--r-- 1 col col  73482 Oct 20 23:53 libpcre_8.41-2_mips_24kc.ipk
