### ISSUE TITLE
路由器wan口为STA模式的wifi 运行ss-libev网络经常失去连接

### ISSUE THREAD

**Issue by aintnodawn** [shadowsocks/shadowsocks-libev#837]
路由器固件：OpenWrt Chaos Calmer 15.05
ss-libev版本：2.5.2

之前一直正常运行。最近换了网络，openwrt连接到另外一个wifi，其他设备有线连接路由器使用这个wifi。一旦ss-libev运行透明代理，几分钟后网络失去连接，路由器ping www.baidu.com 提示bad address，停止SS也依旧如此，过几分钟才恢复正常。路由器不启用ss而在pc上直接使用ssr无此现象。openwrt的上级路由设置DMZ主机为openwrt的ip地址。暂时未在日志里发现相关信息（服务端似乎显示timed out，但我不确定是否断线时的报错信息）

**Comment by madeye** [comment]
I don't think it's related to shadowsocks-libev. It'd be a bug of your ROM.
