### ISSUE TITLE
ss-manger didn't send "pong" when receive "ping"

### ISSUE THREAD

**Issue by gyteng** [shadowsocks/shadowsocks-libev#838]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
shadowsocks-libev 2.4.7

### What operating system are you using?
Ubuntu 14.04

### What did you do?
ss-manager -m aes-256-cfb -u --manager-address 0.0.0.0:9000

As the title, when I send "ping" to port 9000, it should send "pong" back, but these is no response.
The bug only shows when I use "ss-manager".

**Comment by wongsyrone** [comment]
May related to https://github.com/shadowsocks/shadowsocks-libev/issues/678

**Comment by gyteng** [comment]
@wongsyrone It's not the same problem

**Comment by wongsyrone** [comment]
Have you tried latest git HEAD?

**Comment by madeye** [comment]
Compared to python version, `ss-manager` sends `stat{}` instead of `pong` when receiving a `ping`.

Example:

```
ss-manager --manager-address 127.0.0.1:65000 -vuA -c debian/config.json
nc -u 127.0.0.1 65000
ping
stat: {}
add: {"server_port": 8001, "password":"7cd308cc059"}
ok
ping
stat: {"8001":0}
```

**Comment by gyteng** [comment]
Oh, there is something different between python version and libev version.
