### ISSUE TITLE
为啥pid文件里面不是pid值啊？

### ISSUE THREAD

**Issue by rexdf** [shadowsocks/shadowsocks-libev#840]
因为想用monit来监控shadowsocks-libev运行，但是`PIDFILE=/var/run/$NAME/$NAME.pid`这里面根本不知道是啥，反正不是PID值。

然后我尝试把`do_start()`改动成带--make-pidfile参数，但是pid文件里面依然是奇怪的随机数。

https://github.com/shadowsocks/shadowsocks-libev/blob/master/debian/shadowsocks-libev.init#L58-L62

**Comment by wongsyrone** [comment]
Any error log?

**Comment by rexdf** [comment]
`$lsof -i|grep ss-server
ss-server 32281        root    6u  IPv4 414582      0t0  TCP whatthefuck:6512 (LISTEN)

$cat /var/run/shadowsocks-libev/shadowsocks-libev.pid
1663
```

这个ss-server我一直在用，很正常。

**Comment by rexdf** [comment]
Ubuntu 16.04 x64 , `apt-get install shadowsocks-libev`  and  `deb http://shadowsocks.org/ubuntu trusty main` .

```
$wget https://raw.githubusercontent.com/shadowsocks/shadowsocks-libev/master/debian/shadowsocks-libev.init

$diff shadowsocks-libev.init /etc/init.d/shadowsocks-libev
9c9
< # Description:       Shadowsocks-libev is a lightweight secured
---
> # Description:       Shadowsocks-libev is a lightweight secured
10a11
> #
58,62c59,63
<     start-stop-daemon --start --quiet --pidfile $PIDFILE --chuid root:$GROUP --exec $DAEMON --test > /dev/null \
<         || return 1
<     start-stop-daemon --start --quiet --pidfile $PIDFILE --chuid root:$GROUP --exec $DAEMON -- \
<         -c "$CONFFILE" -a "$USER" -u -f $PIDFILE $DAEMON_ARGS \
<         || return 2
---
>  #   start-stop-daemon --start --quiet --pidfile $PIDFILE --make-pidfile --chuid root:$GROUP --exec $DAEMON --test > /dev/null \
>  #       || return 1
>     start-stop-daemon --start --quiet --pidfile $PIDFILE --make-pidfile --chuid root:$GROUP --exec $DAEMON -- \
>         -c "$CONFFILE" -a "$USER" -u -f $PIDFILE $DAEMON_ARGS
>  #       || return 2
```

**Comment by wongsyrone** [comment]
I cannot reproduce as well. The old repo is already deprecated, don't install that version.

**Comment by rexdf** [comment]
Should I compile it from source code?

Is my vps hacked?

**Comment by wongsyrone** [comment]
I suggest trying latest master source to make sure it is not caused by old version. Mine is Ubuntu 14.04

**Comment by madeye** [comment]
Double check if you're using systemd, which won't generate any PID file.

You can check it by `ls -l /var/run/shadowsocks-libev/shadowsocks-libev.pid`

**Comment by rexdf** [comment]
I'm not sure about it. 

Some services like fail2ban, nginx and redis-server etc are in `systemctl list-units`, and listed as `loaded active running`. All pidfiles of fail2ban and redis-server, nginx are correct.

I will try to figure out how to disable shadowsocks-libev systemd unit.
