### ISSUE TITLE
"Crunch: No server data received" when using with privoxy

### ISSUE THREAD

**Issue by humiaozuzu** [shadowsocks/shadowsocks-libev#841]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
2.5.2

### What operating system are you using?
server ubuntu 14.04 + python version
client system: OSX 10.11

### What did you do?
using telegram desktop over ss + privoxy (using http proxy)

### What did you expect to see?
normal access log

### What did you see instead?
a lot of privoxy log saying "Crunch: No server data received"
```
2016-09-23 01:22:14.213 700004bed Crunch: No server data received: http://91.108.56.160:80/api
"POST http://91.108.56.160:80/api HTTP/1.1" 500 775
"POST http://91.108.56.159:80/api HTTP/1.1" 502 0
"POST http://91.108.56.160:80/api HTTP/1.1" 502 0
```
but telegram client can be normal use. When I change the client from libev version to python version. The error log disappears

### What is your config in detail (with all sensitive info masked)?
```
{
"server": "1.2.3.4",
"server_port": 2333,
"method": "method",
"password": "password",
"timeout": 600,
"local_port": 1080,
"local_address": "127.0.0.1",
"auth": true
}
```

**Comment by humiaozuzu** [comment]
@madeye The problem appearred again when I upgrade to shadowsocks-libev 2.5.4 with OpenSSL 1.0.2j

**Comment by madeye** [comment]
Enlarge your `ss-local`'s timeout to avoid this message.

**Comment by dimzon** [comment]
Seem's like need same fix for ss-tunnel and ss-redir !
