### ISSUE TITLE
Wrong transfer statistics when using ss-manager

### ISSUE THREAD

**Issue by gyteng** [shadowsocks/shadowsocks-libev#844]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
2.5.3

### What operating system are you using?
Ubuntu 14.04

### What did you do?
ss-manager

For example, when ss-manager receive 'ping', it will send 'stat: {"10000": 123456}'.
But after shadowsocks client is disconnected, ss-manager will send the same transfer statistics like 'stat: {"10000": 123456}', unless the client connect next time and get a different transfer number.

**Comment by madeye** [comment]
So, what's your expected behavior?

**Comment by gyteng** [comment]
when shadowsocks client is disconnected, it should send stat: {10000: 0}

2016年9月26日 22:39，"Max Lv" <notifications@github.com>写道：

**Comment by gyteng** [comment]
I will take a screenshot to show this problem later

2016年9月26日 22:47，"古宇腾" <igyteng@gmail.com>写道：

**Comment by madeye** [comment]
First of all, there is no `disconnect` in shadowsocks protocol.

Shadowsocks-libev will send the total traffic of one session every time it  receives a `ping`. No traffic, no update.

To reset the traffic of a session, you have to remove it and add it back. But, this is not necessary.

**Comment by madeye** [comment]
A similar discussion can be found here: https://github.com/shadowsocks/shadowsocks-libev/issues/775

It's also doable to only send the diff traffic between two pings. Any suggestions?

**Comment by gyteng** [comment]
Oh, I see, It's not the same as python version.
