### ISSUE TITLE
shadowsocks-libev+qt5+chrome+switchyomega这问题出在哪里?

### ISSUE THREAD

**Issue by agzfan** [shadowsocks/shadowsocks-libev#845]
server
debian8
shadowsocks-libev v2.5.3 chacha20 ota udp

client
windows10
qt5 ota
chrome
switchyomega
都是最新版

switchyomega设置全局走这个ss

问题出在g.e-hentai.org点一个图集,鼠标点击翻页,每翻几次就会出现图片无法显示(switchyomega显示ip未加载)其实这个页面的图片是加载了的,只是一瞬间就变未加载图片无法显示

同一台vps用v2ray的ss协议建立的ss服务器,也是用qt5,udp+ota,没有出现这个问题......

用firefox内置代理走shadowsocks-libev全局,没这个问题

我3台vps都遇到这个问题,很奇怪....

**Comment by madeye** [comment]
Try this client: https://github.com/shadowsocks/shadowsocks-windows

**Comment by agzfan** [comment]
Shadowsocks-win-2.5.6关闭ota没有这个问题,看来是qt5的问题了,我去那边问下
