### ISSUE TITLE
关于服务端acl

### ISSUE THREAD

**Issue by baggiogogo** [shadowsocks/shadowsocks-libev#846]
请教下用supervisor托管shadowsocks-libev服务端的情况下，使用-A --acl blacklist.txt参数是否需要重新定位log文件位置到/var/log/syslog？
自己尝试输入错误的密码多次，但并无ip加入到blacklist中。
感谢!

**Comment by madeye** [comment]
Nope, the latest shadowsocks-libev will detect threats automatically. You don't need to redirect the log or specific a blacklist manually.
