### ISSUE TITLE
Package shadowsocks-libev is missing dependencies for the following libraries: libz.so.1

### ISSUE THREAD

**Issue by xayane** [shadowsocks/shadowsocks-libev#850]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
2.5.3

### What operating system are you using?
debian 8.0

### What did you do?
compile openwrt/lede version for my router

### What did you see instead?
"install -m0755 ./files/shadowsocks.init /home/uk/lede-sdk-ipq806x_gcc-5.4.0_musl-1.1.15_eabi.Linux-x86_64/build_dir/target-arm_cortex-a15+neon-vfpv4_musl-1.1.15_eabi/shadowsocks-libev-openssl/shadowsocks-libev-2.5.3/ipkg-arm_cortex-a15_neon-vfpv4/shadowsocks-libev/etc/init.d/shadowsocks
install -d -m0755 /home/uk/lede-sdk-ipq806x_gcc-5.4.0_musl-1.1.15_eabi.Linux-x86_64/build_dir/target-arm_cortex-a15+neon-vfpv4_musl-1.1.15_eabi/shadowsocks-libev-openssl/shadowsocks-libev-2.5.3/ipkg-arm_cortex-a15_neon-vfpv4/shadowsocks-libev/usr/bin
install -m0755 /home/uk/lede-sdk-ipq806x_gcc-5.4.0_musl-1.1.15_eabi.Linux-x86_64/build_dir/target-arm_cortex-a15+neon-vfpv4_musl-1.1.15_eabi/shadowsocks-libev-openssl/shadowsocks-libev-2.5.3/src/ss-{local,redir,tunnel} /home/uk/lede-sdk-ipq806x_gcc-5.4.0_musl-1.1.15_eabi.Linux-x86_64/build_dir/target-arm_cortex-a15+neon-vfpv4_musl-1.1.15_eabi/shadowsocks-libev-openssl/shadowsocks-libev-2.5.3/ipkg-arm_cortex-a15_neon-vfpv4/shadowsocks-libev/usr/bin
find /home/uk/lede-sdk-ipq806x_gcc-5.4.0_musl-1.1.15_eabi.Linux-x86_64/build_dir/target-arm_cortex-a15+neon-vfpv4_musl-1.1.15_eabi/shadowsocks-libev-openssl/shadowsocks-libev-2.5.3/ipkg-arm_cortex-a15_neon-vfpv4/shadowsocks-libev -name 'CVS' -o -name '.svn' -o -name '.#*' -o -name '*~'| xargs -r rm -rf

Package shadowsocks-libev is missing dependencies for the following libraries:
libz.so.1
Makefile:80: recipe for target '/home/uk/lede-sdk-ipq806x_gcc-5.4.0_musl-1.1.15_eabi.Linux-x86_64/bin/packages/arm_cortex-a15_neon-vfpv4/base/shadowsocks-libev_2.5.3_arm_cortex-a15_neon-vfpv4.ipk' failed
make[2]: *** [/home/uk/lede-sdk-ipq806x_gcc-5.4.0_musl-1.1.15_eabi.Linux-x86_64/bin/packages/arm_cortex-a15_neon-vfpv4/base/shadowsocks-libev_2.5.3_arm_cortex-a15_neon-vfpv4.ipk] Error 1
make[2]: Leaving directory '/home/uk/lede-sdk-ipq806x_gcc-5.4.0_musl-1.1.15_eabi.Linux-x86_64/package/shadowsocks-libev/openwrt'
package/Makefile:127: recipe for target 'package/shadowsocks-libev/openwrt/compile' failed
make[1]: *** [package/shadowsocks-libev/openwrt/compile] Error 2
make[1]: Leaving directory '/home/uk/lede-sdk-ipq806x_gcc-5.4.0_musl-1.1.15_eabi.Linux-x86_64'
/home/uk/lede-sdk-ipq806x_gcc-5.4.0_musl-1.1.15_eabi.Linux-x86_64/include/toplevel.mk:186: recipe for target 'package/shadowsocks-libev/openwrt/compile' failed
make: *** [package/shadowsocks-libev/openwrt/compile] Error 2
"

### What is your config in detail (with all sensitive info masked)?
1 git clone shadowsocks-libev
2  copyed https://github.com/wongsyrone/lede-1/tree/master/package/libs/mbedtls to my SDK and compiled
3 download zlib-1.2.8 to my SDK and compiled
4 make package/shadowsocks-libev/openwrt/compile, and error "Package shadowsocks-libev is missing dependencies for the following libraries: libz.so.1" showed.

what's wrong and what should i do?

**Comment by madeye** [comment]
Make sure you're building against trunk.

**Comment by madeye** [comment]
Also, refer to https://github.com/shadowsocks/openwrt-shadowsocks for more details.

**Comment by wongsyrone** [comment]
You are building the openssl variant, it requires zlib as dependency. You can check commits by nbd.

https://github.com/openwrt/packages/commits/master?author=nbd168

**Comment by xayane** [comment]
thanks! according to the commits, problem solved!

**Comment by jack338c** [comment]
@xayane ，你好，我也碰到了和你一样的问题，怎么可以解决，请指教，感谢！

**Comment by Biercenter** [comment]
./script/feed update -a
./script/feed install zlib
make V=s

**Comment by jack338c** [comment]
试过了，还是没有用
