### ISSUE TITLE
在lede编译显示没有shadowsocks-libev 二进制文件。

### ISSUE THREAD

**Issue by mrken2004** [shadowsocks/shadowsocks-libev#852]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?

shadowsocks 2.5.3
### What operating system are you using?

Lede （openwrt新分支）
### What did you do?

Build
### What did you expect to see?

显示“没有shadowsocks-libev 二进制文件”
### What is your config in detail (with all sensitive info masked)?

**Comment by Biercenter** [comment]
Makefile里依赖添加+zlib然后覆盖到feeds/packages/net/shadowsocks-libev/Makefile
./script/feeds update-a
./script/feeds install -a
make V=s packages/shadowaocks-libev/compile

**Comment by mrken2004** [comment]
@Biercenter 非常感谢！按照您的提示添加了zlib，现在LEDE上运行起来了！

**Comment by tedaz** [comment]
Is it necessary to commit this change to the repository?
Otherwise all users have to do this modification while building the shadowsocks for LEDE.

**Comment by wongsyrone** [comment]
It only affects the openssl variant.

**Comment by wongsyrone** [comment]
committed on https://github.com/shadowsocks/openwrt-shadowsocks/commit/c4a4b35462bd2c24a03b832e672bb6fac3bc054a
