### ISSUE TITLE
pcre应该使用哪一个版本,pcre或pcre2？

### ISSUE THREAD

**Issue by ccc1924** [shadowsocks/shadowsocks-libev#857]
Please answer these questions before submitting your issue. Thanks!

What version of shadowsocks-libev are you using?
2.5.3

What operating system are you using?
opensuse 42.1 leap

What did you do?
build shadowsocks-libev

**Comment by madeye** [comment]
pcre.

**Comment by gsw945** [comment]
[Ubuntu / Debian Install PCRE Library ( Perl 5 Compatible Regular Expression Library )](https://www.cyberciti.biz/faq/debian-ubuntu-linux-install-libpcre3-dev/)
```sehll
apt-get install libpcre3 libpcre3-dev
```
