### ISSUE TITLE
使用ss-redir转发SSH连接中断

### ISSUE THREAD

**Issue by qiuzi** [shadowsocks/shadowsocks-libev#861]
每隔一段时间连接自动断开，这问题很久以前一直存在

**Comment by fiercebead** [comment]
增加ss-server和ss-redir的timeout，比如 -t 7200，不过这样超过2小时没有数据经过ssh的话还是会断开的，可以根据需要调整。不知道能不能设置成无限timeout。

**Comment by qiuzi** [comment]
@fiercebead  没用，依然会断开连接

**Comment by fiercebead** [comment]
@qiuzi timeout肯定是有效果的，如果你把两边都设置为10，连上ssh后不动很快就会断开，如果设置为0，就根本无法连接，而且客户端的timeout无法超过服务端。如果timeout很大还是经常断开，那就是线路不够好呗，不过国内连到国外再好的线路能保证连着ssh一个月不断吗，估计不太可能。
