### ISSUE TITLE
SSL库的疑问

### ISSUE THREAD

**Issue by pexcn** [shadowsocks/shadowsocks-libev#862]
请问在编译安装的时候应该怎么选择 SSL 库？
OpenSSL 和 mbedTLS 之间如何选择，哪个性能比较好？

**Comment by fiercebead** [comment]
个人认为从使用角度来说感觉不到差别的吧，而且如果你用chacha20就更没什么影响了。
OpenSSL一般发行版都自带，比如我在VPS上的CentOS 7 安装openssl-devel 然后编译出来的二进制文件可以直接在其他全新安装的CentOS 7上使用。
如果是静态链接并且自己编译OpenSSL或者mbedTLS，我只想说编译OpenSSL花费的时间是mbedTLS的好多好多倍。

**Comment by pexcn** [comment]
疑问主要是在路由器上... 我选了 mbedTLS 了
