### ISSUE TITLE
2.5.3版本开启自动屏蔽后被误屏蔽的概率增大

### ISSUE THREAD

**Issue by HankAviator** [shadowsocks/shadowsocks-libev#863]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
2.5.3

### What operating system are you using?
服务器：Ubuntu 14.04 x64
客户端：Win 10 x64 / Android 6.0.1

### What did you do?
更新到2.5.3版本，开启OTA，默认开启自动屏蔽。https://github.com/shadowsocks/shadowsocks-libev/commit/a5c9bcfb5864e7b7b61be35ac07e61bb01d6fc59
正常使用ss，合法操作用户会在几十分钟到几个小时的周期内被随机添加到服务器端的黑名单中。

### What did you expect to see?
正常操作用户不被添加到黑名单中，或可以手动编辑黑名单。

### What did you see instead?
客户端IP被添加到黑名单中。

### What is your config in detail (with all sensitive info masked)?
```
{
"server":"0.0.0.0",
"server_port":19203,
"local_port":1080,
"password":"[MASKED]",
"timeout":300,
"method":"rc4-md5"
}
```
为开启OTA，`/etc/default/shadowsocks-libev`的`DAEMON_ARGS`被修改为`DAEMON_ARGS="-uAv"`
使用路由器，手机和电脑两个设备连接到相同路由器，因此IP是一致的。在各客户端上都开启了OTA。

**Comment by madeye** [comment]
Post your log here. Let's see what get your IP blocked.

**Comment by HankAviator** [comment]
```

Oct  2 11:54:16 snow /usr/bin/ss-server[9393]: remote connected
Oct  2 11:54:16 snow /usr/bin/ss-server[9393]: accept a connection
Oct  2 11:54:16 snow /usr/bin/ss-server[9393]: failed to handshake with [MY_IP]
Oct  2 11:54:16 snow /usr/bin/ss-server[9393]: current server connection: 25
Oct  2 11:54:32 snow /usr/bin/ss-server[9393]: TCP connection timeout
Oct  2 11:54:32 snow /usr/bin/ss-server[9393]: current remote connection: 24
Oct  2 11:54:32 snow /usr/bin/ss-server[9393]: current server connection: 24
Oct  2 11:54:32 snow /usr/bin/ss-server[9393]: [udp] connection timeout
Oct  2 11:54:32 snow /usr/bin/ss-server[9393]: [udp] one connection freed
Oct  2 11:54:35 snow /usr/bin/ss-server[9393]: TCP connection timeout
Oct  2 11:54:35 snow /usr/bin/ss-server[9393]: current remote connection: 23
Oct  2 11:54:35 snow /usr/bin/ss-server[9393]: current server connection: 23
Oct  2 11:54:37 snow /usr/bin/ss-server[9393]: TCP connection timeout
Oct  2 11:54:37 snow /usr/bin/ss-server[9393]: current remote connection: 22
Oct  2 11:54:37 snow /usr/bin/ss-server[9393]: current server connection: 22
Oct  2 11:54:45 snow /usr/bin/ss-server[9393]: block all requests from [MY_IP]
Oct  2 11:54:45 snow /usr/bin/ss-server[9393]: block all requests from [MY_IP]
Oct  2 11:54:51 snow /usr/bin/ss-server[9393]: [udp] connection timeout
Oct  2 11:54:51 snow /usr/bin/ss-server[9393]: [udp] one connection freed
Oct  2 11:54:52 snow /usr/bin/ss-server[9393]: [udp] server receive a packet
```
可能关联的log

**Comment by madeye** [comment]
@wongsyrone Is it related to the issue of shadowsocks-windows you mentioned before?

**Comment by HankAviator** [comment]
另外补充：的确是在Windows的客户端经常发生。Android暂时没有Windows上容易复现。

**Comment by wongsyrone** [comment]
Yes, it should be fixed in latest master branch, but not released yet. I recommend testing the appveyor version.

**Comment by HankAviator** [comment]
多谢！

**Comment by madeye** [comment]
Also, you can try this commit efafb59

**Comment by HankAviator** [comment]
多谢，神速。这个commit之后，服务器端的黑名单是否仍是主要靠自动运作？之后自述文件能做一下相关更新就好了。
