### ISSUE TITLE
OpenWRT上如何配置ss-server开机自启？

### ISSUE THREAD

**Issue by BrushXue** [shadowsocks/shadowsocks-libev#867]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
2.5.3

### What operating system are you using?
OpenWRT

### What did you do?
安装ipk文件

### What did you expect to see?
开机自启

### What did you see instead?
安装ipk以后只有/usr/bin/ss-server，没有出现/etc/init.d/shadowsocks文件，在OpenWRT里面怎么写这个文件，把其他Linux的文件直接复制过去能用吗？

**Comment by pexcn** [comment]
https://github.com/shadowsocks/luci-app-shadowsocks

**Comment by BrushXue** [comment]
只有管理client的页面啊？

**Comment by Biercenter** [comment]
ss-server -c /etc/shadowsocks.cfg -u -f /tmp/shfowsocks.pid 放到rc.local里就可以了，配置文件自己会弄吧。

**Comment by wtjfree** [comment]
luci在启动项下面有个可以添加脚本的地方 
在里面直接加一行更简单
ss-server -p 端口号 -k "密码" -m "加密模式" -u
加密模式缩写参考ss-server 在系统里面的提示
