### ISSUE TITLE
ss-redir, SHADOWSOCKS_MARK, no such file or directory.

### ISSUE THREAD

**Issue by d0u9** [shadowsocks/shadowsocks-libev#868]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
v2.5.3

### What operating system are you using?
Debian 8

### What did you do?
proxy all traffic via ss-redir

### What did you expect to see?
Error free

### What did you see instead?

when run `iptables -t mangle -A SHADOWSOCKS_MARK -p udp --dport 53 -j MARK --set-mark 1`,
`iptables: No chain/target/match by that name.` is reported.

when run `iptables -t mangle -A OUTPUT -j SHADOWSOCKS_MARK`,
`iptables v1.4.21: Couldn't load target `SHADOWSOCKS_MARK':No such file or directory` is reported.

### What is your config in detail (with all sensitive info masked)?

I follow the instruction [here](https://github.com/shadowsocks/shadowsocks-libev#advanced-usage) step by step but get errors.

I don't really know what is SHADOWSOCKS_MARK? it seems that this chain (if it is a chain) has never created.

Thx.

**Comment by fiercebead** [comment]
用这个命令创建它 `iptables -t mangle -N SHADOWSOCKS_MARK`.
对于这两个mangle表你也需要一些规则来略过必要的局域网IP和VPS IP.
如果你是要所有udp都走ss-redir，去掉`--dport 53`.

**Comment by madeye** [comment]
@fiercebead Thanks for the answer.

**Comment by yaochx** [comment]
@fiercebead [shadowsocks-libev#advanced-usage](https://github.com/shadowsocks/shadowsocks-libev#advanced-usage)
usage在第二行:  iptables -t mangle -N SHADOWSOCKS_MARK
应该已经创建了table，您的意思是再创建一次？我照做了还是有同样的问题

**Comment by fiercebead** [comment]
@yaochx 第二行是`iptables -t mangle -N SHADOWSOCKS`，没有创建`SHADOWSOCKS_MARK`
