### ISSUE TITLE
block all requests from

### ISSUE THREAD

**Issue by zhfish** [shadowsocks/shadowsocks-libev#870]
how close auto-block ?

### What version of shadowsocks-libev are you using?
2.5.3-1, master

### What operating system are you using?
client,win10

### What did you do?
block all requests from [MYIP]

### What is your config in detail (with all sensitive info masked)?
/usr/bin/ss-server -a root -c /etc/shadowsocks-libev/config.json -u --fast-open

**Comment by madeye** [comment]
Try the latest commit of shadowsocks-libev or update your windows client to the latest.
