### ISSUE TITLE
May I ask why openwrt version was deleted in v2.54?

### ISSUE THREAD

**Issue by manjuprajna** [shadowsocks/shadowsocks-libev#871]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?

v2.54
### What operating system are you using?

openwrt cc 1505
### What did you do?

nothing
### What did you expect to see?

openwrt version still remains
### What did you see instead?

openwrt version was deleted unluckily
### What is your config in detail (with all sensitive info masked)?
same as usual

I know we have openwrt version by aa65536, but it only has bin file, no init.d script, no json file, should accompanied with his luci-app-shadowsocks to work, but I don't need his luci, too big and too comlicated, I only use openwrt with ipset and my own simplified gfw list, that's simple, I don't need chnroute, I only visit very limited blocked websites.
so I really don't understand why you deleted this openwrt version. 
of course I can write an Makefile by myself or use v2.53 and manully modify it, but I really hope you can restore it. I think many people need this.
or should I persuade aa65536 to make two version of openwrt version like before?

**Comment by debiansid** [comment]
Agreed

**Comment by madeye** [comment]
You can open an issue for OpenWRT project to add the init script.

**Comment by manjuprajna** [comment]
but Dear sir: aa65536 said he won't accept any issues because his openwrt version only has bin files, every issue we meet should open here, he only accept luci-app issues.
so I am really confused.
