### ISSUE TITLE
random "failed to handshake with x.x.x.x"message on libev server side #869 #872

### ISSUE THREAD

**Issue by manjuprajna** [shadowsocks/shadowsocks-libev#874]
Dear sir:

I have to reopen this issue again, I think you're too busy, or should blame my poor English.
I said very clearly, before that issue happened,  I have never encounter such error message except those "realy failed handshake of wrong password or wrong encryption method, or one side OTA enable, another side OTA disable", many different clients, IOS, android, windows, openwrt version from v2.4.x to v2.5.x
but after upgrading  to these two commits and v2.54,  all of my server will have such kind of "faked" failed handshake message, all of my clients, no matter openwrt different version, IOS, android, all.

when last night I do this error log message test, I stopped shadowsocks-libev systemd service, used verbose mode, only one client online, that's myself, ONLY myself with openwrt ss-libev v2.53, not very old version. and I told you that before this issue, no matter how old client version is, never ever has this failed handshake problem.

and it's not only "warn"message, because when this error message show up, my browser webpage can not open, then after several seconds, webpage restored.

and, all of my clients ip, all have such error message.

**Comment by madeye** [comment]
As I mentioned in the previous comments, according to the log you provided, it's a bug of the clients you are using. You should try the latest ones.

Also, warnings like "failed to handshake" won't cause the error you mentioned.

**Comment by manjuprajna** [comment]
so dear madeye,  why all these clients, no matter windows, IOS, openwrt, android, they all have such kind of bug?
and while I did the test last night, both my openwrt router and my server are latest version, and only myself one client,  and the network is not crowed, ping time to my server is only 8ms.
if that's the bug of all the clients, why before you change auto block mechanism, I used so many versions of libev for almost one year, never ever has such kind of problem.
when I saw this error message before, those failed handshake ips, all are those malicious ips, and I used autoban to ban them. some times, if I changed password or encrypti;on method,  and I did not input correct password and correct encryption method, then I will see this error message.

if you say" Also, warnings like "failed to handshake" won't cause the error you mentioned.", do you mean the server is cheating me? or how could server side judge which is "client bug"you mentioned, which is a real authentication error? if like what you said, does it mean that even a malicious ip that can not successfully handshake with sever could still connect?

I don't understand, and I am quite confused.

sorry waste so much of your time, and thanks a lot!

**Comment by ihacklog** [comment]
@manjuprajna it's your client problem. if you does not know why, it does not mean that the shadowsocks-libev server has a bug ...
I've been useing shadowsocks-libev for a long time. It's stable and usable. 
So, try to find your problem.  Google it.

**Comment by manjuprajna** [comment]
oh, I am terribly sorry, my poor English, dear @madeye , do you misunderstand? this error message is from my CentOS server, not from my client, but of course it's caused by client.

**Comment by madeye** [comment]
My suggestion is to isolate your problem first.

For example, you may set up multiple servers for different clients. And try to observe which server still gets that warning.

**Comment by manjuprajna** [comment]
@ihacklog thank you for your kind concern on my useless ticket.
but I am really confused.
do you mean all my clients, including openwrt version, android version, windows version, they all have such kind of bugs?
but why before v2.53 everything is normal? 
or do you think the newest version "unmasked" a long time existing bug? is this what you mean?
every human made software has bugs, or @madeye and all programmers of the world they will lose job.
and I never said it's unstable, and unusable. only that when I am surfing, suddenly will cause empty respense and black web page, and will restore to normal after seconds.

and I think you should suggest @madeye to change every of recent release's description to "stable".

thank you.

**Comment by manjuprajna** [comment]
@madeye 
that's exactly what I did last night, actually this early morning at 4 am, nobody connect to my server except myself.
I will open a new vps to test.
if it's caused by old version, it seems impossible to ask all the people to upgrade to latest version, especially IOS version, because I don;'t know how to compile an IOS version, they have to download from apple store.
if only error message, that's no big deal, but it will cause empty response page, pretty much annoying.
it's not very often, so that's why you can not reproduce it, I waited for almost 20 minutes then captured that "failed to handshake". but I can not say that it's unlucky, because every ip address of my clients show this error message, and my friend phoned me that suddenly can not open google and youtube.

thanks again for your kind reply @madeye

**Comment by madeye** [comment]
Again, "Failed to handshake" won't cause any issue you mentioned, as it's just a warning.

You may get blocked by the server after too many tries or broken client implementation. But the error log should be "Block all requests from x.x.x.x" instead.

The only known client with empty header issue are old releases of shadowsocks-windows. If you don't use that client, your problem is not related to "auto blocking mechanism" introduced in the latest releases of shadowsocks-libev.

To narrow down your problem, you should use only one kind of client for a server. Then observe which kind of client cause the error you mentioned:

```
2016-10-10 04:30:41 INFO: TCP connection timeout
2016-10-10 04:30:41 INFO: incomplete header: 0
```

**Comment by zinian** [comment]
服务器是搬瓦工的哈？

**Comment by manjuprajna** [comment]
@zinian 搬瓦工的怎么可能8ms。

**Comment by madeye** [comment]
Closed as inactive.
