### ISSUE TITLE
编译时出现的警告

### ISSUE THREAD

**Issue by pexcn** [shadowsocks/shadowsocks-libev#875]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?

今天最新的 commit

### What operating system are you using?

Ubuntu 14.04 编译 Openwrt 15.05.1 的 ipk

### What did you do?

编译 Openwrt 15.05.1 的 shadowsocks 的 ipk

### What did you expect to see?

希望消除警告

### What did you see instead?

```
/home/pexcn/pexcn/OpenWrt/openwrt-cc/staging_dir/target-mips_34kc_uClibc-0.9.33.2/usr/lib/libcrypto.so: warning: gethostbyname is obsolescent, use getnameinfo() instead.
  CC       ss_redir-utils.o
  CC       ss_redir-jconf.o
  CC       ss_redir-json.o
  CC       ss_redir-encrypt.o
  CC       ss_redir-netutils.o
  CC       ss_redir-cache.o
  CC       ss_redir-udprelay.o
  CC       ss_redir-redir.o
  CC       ss_redir-http.o
  CC       ss_redir-tls.o
  CC       ss_redir-rule.o
  CCLD     ss-redir
```

出现 `warning: gethostbyname is obsolescent, use getnameinfo() instead.` 警告。

**Comment by madeye** [comment]
It's a warning for your libcrypto.so, not shadowsocks-libev.
