### ISSUE TITLE
i find some errors when i make it with cygwin on Windows7 X64

### ISSUE THREAD

**Issue by jhgongfu** [shadowsocks/shadowsocks-libev#876]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
2.5.4

### What operating system are you using?
cygwin on Windows7 X64

### What did you do?
i find some errors when i make it with cygwin on Windows7 X64

### What is your config in detail (with all sensitive info masked)?
this is the log 
[log.txt](https://github.com/shadowsocks/shadowsocks-libev/files/519323/log.txt)

**Comment by wongsyrone** [comment]
--disable-documentation

**Comment by wongsyrone** [comment]
Other warnings generated by libcork can be ignored
