### ISSUE TITLE
always notice mbedtls 

### ISSUE THREAD

**Issue by xingezhang** [shadowsocks/shadowsocks-libev#877]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?

2.5.4
### What operating system are you using?

LEDE
### What did you do?

Cross compile
### What is your config in detail (with all sensitive info masked)?
我使用LEDE的SDK交叉编译shadowsocks，提示mbedtls_cipher_mode required，我已经下载了https://github.com/wongsyrone/lede-1/tree/master/package/libs/mbedtls目录，并重新编译获得libmbedtls-2.3.0.ipk，可是重新编译shadowsocks时还是会出现同样的错误，求教这个怎么解决？

**Comment by Biercenter** [comment]
我也碰到这个问题无法解决，只编译了openssl版的，求解答

**Comment by madeye** [comment]
Post OpenWRT related issues here: https://github.com/shadowsocks/openwrt-shadowsocks

**Comment by aa65535** [comment]
clone [mbedtls](https://github.com/openwrt/openwrt/tree/master/package/libs/mbedtls) 到 package 目录下, 删除 `package/mbedtls/patches/200-config.patch` 文件, 然后编译.

**Comment by xingezhang** [comment]
谢谢，我试试看

**Comment by tianlichunhong** [comment]
终于搞清楚并编译成功，不容易呀！方法是复制 https://github.com/wongsyrone/lede-1/tree/master/package/libs/mbedtls中的999-tweak-config-for-shadowsocks.patch文件到SDK目录下的feeds/base/package/libs/mbedtls/patches。然后make package/shadowsocks-libev/compile V=99编译，就可以。刚开始一直以为将mbedtls目录拷贝到SDK的package下面，一直没有搞定。原来是拷贝到feeds下面的base的package。对于菜鸟，还请大神说的详细点。感谢各位大神。
