### ISSUE TITLE
self build ss-local exit with illegal instruction 4

### ISSUE THREAD

**Issue by humiaozuzu** [shadowsocks/shadowsocks-libev#878]
I've build one ss-libev from source using lastest code using `brew install shadowsocks-libev --HEAD` on my rmbp13 2015 early with osx Sierra beta and it runs well
But when it runs on another rmbp15 2015 early with osx Sierra and it exits with "illegal instruction 4"

Also I've tried running this one on both computers and everything is OK
https://homebrew.bintray.com/bottles/shadowsocks-libev-2.5.3.sierra.bottle.tar.gz

**Comment by humiaozuzu** [comment]
Just tried build on OSX 10.11.6 still can not run on that rmbp15 2015 early with osx Sierra

**Comment by madeye** [comment]
You need to build shadowsocks-libev on the platform you're using, not on other ones.

**Comment by humiaozuzu** [comment]
@madeye but why the one build on homebrew bottle can run on all platform?

**Comment by madeye** [comment]
1. Homebrew will solve all the dependencies automatically for you.
2. It provides different binaries for different platforms: https://github.com/Homebrew/homebrew-core/blob/master/Formula/shadowsocks-libev.rb#L10

**Comment by humiaozuzu** [comment]
@madeye yes, but my binariy build was build on macOS Sierra but can not run on other macOS Sierra macbooks. Is the bottle build for macOS Sierra different with the one build from source on my mac?

**Comment by madeye** [comment]
It depends on the toolchains and libraries on your first "macOS Sierra". Without solving dependency issues, you cannot just copy a binary from one machine to another and wish it work smoothly.

**Comment by humiaozuzu** [comment]
@madeye  I've also copied the openssl/pcre dylib to that mac. Also I want to explain that only that mac has this problem and many other mac with macOS Sierra are OK.

**Comment by humiaozuzu** [comment]
It seems that optimize flag related parameters may cause this problem. Does shadowsocks-libev have the same problem?
https://tickets.puppetlabs.com/browse/PA-181
https://github.com/puppetlabs/puppet-agent/pull/571/files

**Comment by madeye** [comment]
It also depends.

The configure scripts will auto detect the hardware feature like AES-NI, AVX, or SSE and enable them for the build platform. If you build the binary on a machine with these hardware extensions, it may cause compatibility issues on other machines, even all of them are using macOS Sierra.

**Comment by humiaozuzu** [comment]
@madeye So how can my mac build shadowsocks-libev like the one building homebrew bottle for macOS Sierra or I have to change my machine?

**Comment by madeye** [comment]
You have to figure out the reason by yourself. Or you can submit an issue to homebrew instead.
