### ISSUE TITLE
Unable to get server log

### ISSUE THREAD

**Issue by nodje** [shadowsocks/shadowsocks-libev#879]
I'm running latest version with the following command on Debian:
`/usr/bin/ss-server -c /etc/shadowsocks-libev/config.json -a nobody -u -f /var/run/shadowsocks-libev/shadowsocks-libev.pid`
but I'm unable to get any log.
I've tried running as root to see if any `/var/log/shadowsocks.log` would be created but couldn't get anything either way.
I can't find anything related in `/var/log/syslog`.

My goal is to have a script monitor the logs to ban potential attackers' IP.
What do you think of https://github.com/twfcc/shadowsocks-libev_firewall_utils ?
Useful?

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks-libev/issues/842

**Comment by nodje** [comment]
Ok, I get it now, you have to add the verbose option to get logs `-v`
Not obvious from the doc. It'd be good to add a word about this in the help:
```
Verbose mode. Also enables logging to system log when run as a daemon
```
And, possibly, adding the client IP in the logs would be useful ,and allowing to choose to which file to log to as well.

FYI, on the master branch (latest commit yesterday), when installing on debian, the `/etc/default/shadowsocks-libev` adds `DAEMON_ARGS="-u"` so that the default daemon becomes 
`/usr/bin/ss-server -c /etc/shadowsocks-libev/config.json -a root -u -f /var/run/shadowsocks-libev/shadowsocks-libev.pid -u`, repeating the `-u` option

**Comment by kang000feng** [comment]
@nodje @madeye Dear both,  where the logging will output to with option -v ? both /var/log/syslog and /var/log/shadowsocks.log ?

**Comment by hongkongkiwi** [comment]
Even enabling -v does not add logging, any ideas?
