### ISSUE TITLE
Support accessing pure IPv6 address

### ISSUE THREAD

**Issue by xdqi** [shadowsocks/shadowsocks-libev#88]
My server has IPv6 support, and I can access http://ipv6.google.com/ through shadowsocks.
Is there possible for shadowsocks to access a pure IPv6 address like http://[2404:6800:4005:807::1001]/ ?

**Comment by googolmo** [comment]
When my server access to ipv6 address, something error.
output is

'''
2016-03-10 07:19:39 ERROR: invalid header with addr type 17
'''

**Comment by xdqi** [comment]
I know what cause it just now. Please refer to https://github.com/FelisCatus/SwitchyOmega/issues/443 if you are using chromium browsers.
