### ISSUE TITLE
LEDE sdk下的编译问题

### ISSUE THREAD

**Issue by luckwang** [shadowsocks/shadowsocks-libev#882]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
shadowsocks-libev for lede

### What operating system are you using?
Ubuntu 16.04.1 LTS x64

### What did you do?
ubuntu下安装了:
build-essential libssl-dev libncurses5-dev unzip subversion mercurial gawk zlib1g-dev

按照shadowsocks-libev for openwrt编译操作步骤(sdk有所不同):
tar xjf lede-sdk-ar71xx-generic_gcc-5.4.0_musl-1.1.15.Linux-x86_64.tar.bz2
cd lede-sdk-ar71xx-generic_gcc-5.4.0_musl-1.1.15.Linux-x86_64
./scripts/feeds update packages
./scripts/feeds install libpcre
git clone https://github.com/shadowsocks/openwrt-shadowsocks.git package/shadowsocks-libev
make menuconfig
Network -> shadowsocks-libev
make package/shadowsocks-libev/compile V=99

编译出现错误：
checking for library containing floor... none required
checking for thread local storage (TLS) class... __thread
checking zlib.h usability... no
checking zlib.h presence... no
checking for zlib.h... no
configure: error: "zlib header files not found."
Makefile:83: recipe for target '/home/ubuntu/lede-sdk-ar71xx-generic_gcc-5.4.0_musl-1.1.15.Linux-x86_64/build_dir/target-mips_24kc_musl-1.1.15/shadowsocks-libev/openssl/shadowsocks-libev-2.5.5/.configured_yyny' failed

### What did you expect to see?
成功编译shadowsocks-libev-2.5.5 for lede ipk文件

### What did you see instead?
无

### What is your config in detail (with all sensitive info masked)?
无

**Comment by Biercenter** [comment]
依赖的zlib找不到，这是我的解决办法：
./scripts/feeds install libopenssl
上面的会自动安装zlib，然后编辑下面的文件，第37行+libpthread后面添加zlib依赖
vi package/shadowsocks-libev/Makefile
看起来像这样：	DEPENDS:=$(3) +libpcre +libpthread +zlib

**Comment by tedaz** [comment]
Would anybody could commit this change to the repo?
Otherwise any user who want to build this code have to do this modification once again.
