### ISSUE TITLE
Compilation error arm big endian.

### ISSUE THREAD

**Issue by jun0s** [shadowsocks/shadowsocks-libev#883]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
The last dev version.

### What operating system are you using?
Windows 10 last updates with (Ubuntu bash)
ommited@somepc:~/shadowsocks$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.1 LTS"

### What did you do?
Cross-Compiling
./configure --build=$BUILDMACH --host=$TARGETMACH --with-crypto-library=mbedtls --with-mbedtls-include=/home/ommited/mbedtls/include --with-mbedtsl-lib=/opt/armeb/tipm/usr/lib ac_cv_linux_vers=2

### What did you expect to see?
shadowsocks compiled... :)

### What did you see instead?

make[2]: se entra en el directorio '/home/ommited/shadowsocks/libev'
  CC       ev.lo
ev.c: In function 'ecb_unreachable':
ev.c:1125: warning: 'noreturn' function does return
ev.c:1514:3: error: #error "memory fences not defined for your architecture, please report"
ev.c: At top level:
ev.c:1825: warning: 'ev_default_loop_ptr' initialized and declared 'extern'
Makefile:404: fallo en las instrucciones para el objetivo 'ev.lo'

### What is your config in detail (with all sensitive info masked)?
last mbedtls arm big endian compiled...
last pcre arm big endian compiled...

thank your for u help :)

**Comment by hosiet** [comment]
This is the problem of libev, not ss-libev. Please report this problem to
libev developers and Microsoft.

Bash on windows is still beta. Please consider using a mature platform.

jun0s <notifications@github.com>于2016年10月13日周四 06:42写道：

**Comment by wongsyrone** [comment]
I think it's caused by your toolchain

**Comment by jun0s** [comment]
with the same toolchain and same context... "Bash Windows" (Ubuntu) i compile mbedtls and pcre without a problem.... and anothers "tools" too... but ok... i am try with a "real Ubuntu" context o envirmoment.
