### ISSUE TITLE
failed to handshake again as mentioned in #869 #872 #874

### ISSUE THREAD

**Issue by manjuprajna** [shadowsocks/shadowsocks-libev#884]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?

v2.55 both server side and client(openwrt)side
### What operating system are you using?
CentOS 7.2 x64 server side, openwrt 1505 client side

### What did you do?
working properly

### What did you expect to see?

normal error log
### What did you see instead?

Oct 13 20:47:39 ss-server: 2016-10-13 20:47:39 INFO: current remote connection: 3
Oct 13 20:47:39 ss-server: 2016-10-13 20:47:39 INFO: current server connection: 5
Oct 13 20:47:52 ss-server: 2016-10-13 20:47:52 INFO: server_recv close the connection
Oct 13 20:47:52 ss-server: 2016-10-13 20:47:52 INFO: current remote connection: 2
Oct 13 20:47:52 ss-server: 2016-10-13 20:47:52 INFO: current server connection: 4
Oct 13 20:47:53 ss-server: 2016-10-13 20:47:53 INFO: server_recv close the connection
Oct 13 20:47:53 ss-server: 2016-10-13 20:47:53 INFO: current remote connection: 1
Oct 13 20:47:53 ss-server: 2016-10-13 20:47:53 INFO: current server connection: 3
Oct 13 20:47:53 ss-server: 2016-10-13 20:47:53 INFO: server_recv close the connection
Oct 13 20:47:53 ss-server: 2016-10-13 20:47:53 INFO: current remote connection: 0
Oct 13 20:47:53 ss-server: 2016-10-13 20:47:53 INFO: current server connection: 2
Oct 13 20:48:28 ss-server: 2016-10-13 20:48:28 INFO: TCP connection timeout
Oct 13 20:48:28 ss-server: 2016-10-13 20:48:28 INFO: incomplete header: 0
Oct 13 20:48:28 ss-server: 2016-10-13 20:48:28 ERROR: failed to handshake with my ip
Oct 13 20:48:28 ss-server: 2016-10-13 20:48:28 INFO: current server connection: 1
Oct 13 20:48:33 ss-server: 2016-10-13 20:48:33 INFO: connect to 151.101.100.133:443
Oct 13 20:48:34 ss-server: 2016-10-13 20:48:33 INFO: remote connected
Oct 13 20:48:34 ss-server: 2016-10-13 20:48:33 INFO: server_recv close the connection
Oct 13 20:48:34 ss-server: 2016-10-13 20:48:33 INFO: current remote connection: 0
Oct 13 20:48:34 ss-server: 2016-10-13 20:48:33 INFO: current server connection: 0

### What is your config in detail (with all sensitive info masked)?
    "server":"0.0.0.0",
    "server_port":***,
    "password":"password",
    "method":"chacha20-ietf",
    "auth": true,
    "timeout":300

I opened a vultr server and only my openwrt router one client, both v2.55, still has such kind of error message, and I noticed that at first "incomplete header: 0", then "failed to handshake".

so it's not because of old client, since both are latest version.

I found this problem after efafb59, maybe before that also has such kind of problem, I am quite sure it's cause by auto block mechanism,because before that I never seen such kind of "failed handshake" with correct password and method.

I remember first after one commit that will randomly block my own ip and other decent clients, then you upgrade to efafb59, fixed #863, then I see error log of "failed to handshake".

but not very often, this vultr server I opened, I use for more than 24hrs, then one "failed to handshake".

but before 435401b, I got more of those "failed to handshake" error message, after 435401b, very few of this error message.

now not big deal, because I only see once within 24 hrs.

thank you for your marvelous work.

**Comment by madeye** [comment]
Again, this message is just a newly added warning, which is not related to any known connection loss.

For your case, it looks like an issue of `ss-redir` on your OpenWRT. Please try:

1. Update your server and client to 2.5.5.
2. Capture the log of `ss-redir`on your OpenWRT.

**Comment by madeye** [comment]
BTW, sometimes you may see this warning message due to unstable network connection, e.g. a shadowsocks connection established with no further transmission. But unless you see "block all requests from xxxx", shadowsocks itself won't block any request from any IP address.

**Comment by manjuprajna** [comment]
sorry, both server side and client side is V 2.55, 
and like I mentioned in old ticket, when such kind of "failed to handshake" appears, my chrome browser will lose connection indeed. 
if I did not encounter such problem, why would I open these tickets?

and since v2.55, I use in a vultr server for more than 24 hrs, then I "caught" this error messege.
and don't know how can I use ss-redir in verbose mode for more than 24 hrs,  router has no hard disk, limited memory.

**Comment by manjuprajna** [comment]
so you can close this ticket if you want.

not big deal since v2.55. thank you anyway.
