### ISSUE TITLE
openwrt wan口透明代理

### ISSUE THREAD

**Issue by JoveYu** [shadowsocks/shadowsocks-libev#885]
如何修改iptables才能在现有openwrt的ss-rules上支持wan口的透明代理

现状
现有一有线网络192.168.2.1 

openwrt WAN  192.168.2.10   网关 192.168.2.1
               LAN   192.168.1.100-255
手机      192.168.1.100   网关192.168.1.1

如何完成
电脑      192.168.2.100   网关192.168.2.10
的完美透明代理

**Comment by madeye** [comment]
1. Disable DHCP on 192.168.2.10
2. Set up your OpenWRT' wireless as bridge.
3, Set up your OpenWRT's wan interface as gateway.
