### ISSUE TITLE
rpmbuild error

### ISSUE THREAD

**Issue by debiansid** [shadowsocks/shadowsocks-libev#887]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
2.5.5

### What operating system are you using?

centos
### What did you do?

build rpm 
### What did you expect to see?
rpm will be built successfully

### What did you see instead?
```
Conflicts: python-shadowsocks python3-shadowsocks
Processing files: shadowsocks-libev-debuginfo-2.5.5-1.el6.i686
Processing files: shadowsocks-libev-devel-2.5.5-1.el6.i686
Requires(rpmlib): rpmlib(CompressedFileNames) <= 3.0.4-1 rpmlib(FileDigests) <= 4.6.0-1 rpmlib(PayloadFilesHavePrefix) <= 4.0-1
Checking for unpackaged file(s): /usr/lib/rpm/check-files /home/ezhang/rpmbuild/BUILDROOT/shadowsocks-libev-2.5.5-1.el6.i386
error: Installed (but unpackaged) file(s) found:
   /usr/share/doc/shadowsocks-libev/shadowsocks-libev.html
   /usr/share/doc/shadowsocks-libev/ss-local.html
   /usr/share/doc/shadowsocks-libev/ss-manager.html
   /usr/share/doc/shadowsocks-libev/ss-nat.html
   /usr/share/doc/shadowsocks-libev/ss-redir.html
   /usr/share/doc/shadowsocks-libev/ss-server.html
   /usr/share/doc/shadowsocks-libev/ss-tunnel.html


RPM build errors:
    Installed (but unpackaged) file(s) found:
   /usr/share/doc/shadowsocks-libev/shadowsocks-libev.html
   /usr/share/doc/shadowsocks-libev/ss-local.html
   /usr/share/doc/shadowsocks-libev/ss-manager.html
   /usr/share/doc/shadowsocks-libev/ss-nat.html
   /usr/share/doc/shadowsocks-libev/ss-redir.html
   /usr/share/doc/shadowsocks-libev/ss-server.html
   /usr/share/doc/shadowsocks-libev/ss-tunnel.html
```

**Comment by consen** [comment]
I encountered the same issue when build the latest rpm.

```
sh genrpm.sh -v 2.5.5
```

**Comment by madeye** [comment]
@librehat Any suggestion?

**Comment by wongsyrone** [comment]
Just information
1. https://docs.fedoraproject.org/ro/Fedora_Draft_Documentation/0.1/html/RPM_Guide/ch09s05s07.html
2. http://unix.stackexchange.com/questions/119373/rpm-installed-but-unpackaged-files-found-on-centos-6-with-cups-1-7-1

**Comment by debiansid** [comment]
ok, by adding %define _unpackaged_files_terminate_build 0 
fixed the problem, but I am not sure it is the best way to do it.

thanks @wongsyrone

**Comment by wongsyrone** [comment]
Yep. Method 1 just ignore it when finding unpacked files, it's straightforward but might not elegant; it changes the original RPM behavior; the other method involves many changes to `%files` rule, it complies to RPM, but not elegant.
