### ISSUE TITLE
sni 的 ss google play 无法下载东西

### ISSUE THREAD

**Issue by feijilei** [shadowsocks/shadowsocks-libev#889]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
v2.5.5

### What operating system are you using?
centos 6.7

### What did you do?
ss 的sni google play 无法使用（sni 应该是基于sniproxy）

**日志里面会报错 Request from xxx.xxx.xx.xxx did not include a hostname**

### What did you see instead?
无法下载

**Comment by madeye** [comment]
It's just a warning. If you don't want to see it, please update to the latest commit.
