### ISSUE TITLE
2.5.3版本的shadowsocks-libev，openwrt上的，如何设置才可以转发游戏的udp数据。

### ISSUE THREAD

**Issue by zaiweijian** [shadowsocks/shadowsocks-libev#893]
现在是ss搭配chinadns使用，网页浏览可以使用，但玩游戏时udp数据无法转发致使能进游戏页面但不能进入服务器。请问是否是设置问题还是什么？

**Comment by fiercebead** [comment]
chinadns或者pdnsd这些和ss-redir的udp有冲突吧，至少linux下是这样，别用chinadns，直接用8.8.8.8

**Comment by shenmadouyaowen** [comment]
https://www.sockscap64.com/forums/topic/shadowsocks%E5%AE%A2%E6%88%B7%E7%AB%AF%E9%85%8D%E7%BD%AE%E6%95%99%E7%A8%8B

可以看看这篇文章配置
