### ISSUE TITLE
is there any way to stop auto block ?

### ISSUE THREAD

**Issue by Tevic** [shadowsocks/shadowsocks-libev#899]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
2.5.5

### What operating system are you using?
Ubuntu 16.04.1

### What did you do?
Ip is blocked

### What did you expect to see?
shutdown auto block

### What did you see instead?
ip blocked

**Comment by madeye** [comment]
Nope, it's a must have.

Actually, random failure won't get your IP blocked, the server would reset the block status when one connection get established successfully.

**Comment by Sherlock-Holo** [comment]
是不是重启服务器或者ss-server就可以解除block了，咱试过转发服务器被block后重启ss服务器，然后就可以正常连接了

Max Lv <notifications@github.com>于2016年10月26日周三 06:11写道：

**Comment by Tevic** [comment]
> 重启是可以解决的，只是升级到新版以后，之前用haproxy做的代理服务器经常会被block，既然没有关闭选项只能先退回旧版，问下这个特性是哪个版本引入的

**Comment by madeye** [comment]
Update to the latest commit, add your local IP to the white list and enable ACL.

A sample ACL for your case can be found here:

https://github.com/shadowsocks/shadowsocks-libev/blob/master/acl/local.acl

**Comment by breakwa11** [comment]
If you really want to disable auto block:
in file `src/server.c`
in function `static void report_addr(int fd, int err_level)`
add a `return;` before the comment like this:
```c

static void
report_addr(int fd, int err_level)
{
    char *peer_name;
    peer_name = get_peer_name(fd);
    if (peer_name != NULL) {
        LOGE("failed to handshake with %s", peer_name);
        return; // Block all requests from this IP, if the err# exceeds 128.
        if (check_block_list(peer_name, err_level)) {
            LOGE("add %s to block list", peer_name);
        }
    }
}
```
save & make

but after that, your server will be unsafe

**Comment by Sherlock-Holo** [comment]
thanks

Max Lv <notifications@github.com>于2016年10月26日周三 10:33写道：

**Comment by Sherlock-Holo** [comment]
为什么会被经常block，咱的只是朋友使用时配置没调好然后不停错误连接被block而已。

Tevic <notifications@github.com>于2016年10月26日周三 10:04写道：

**Comment by breakwa11** [comment]
@Sherlock-Holo 特殊情况下，8次的连接超时（例如TCP握手后第一个包还没成功发送），就会被block，新版本好像只要4次？我没看最新的代码，不过应该是这两个数字

**Comment by Sherlock-Holo** [comment]
不知道，反正被block后重启服务器就搞定了，至于朋友是试了多久被ban就不知道了

破娃酱 <notifications@github.com>于2016年10月27日周四 00:03写道：
