### ISSUE TITLE
 cannot determine absolute directory name of `yes/lib'

### ISSUE THREAD

**Issue by k79e** [shadowsocks/shadowsocks-libev#90]
../libtool: line 5986: cd: yes/lib: No such file or directory
libtool: link: cannot determine absolute directory name of `yes/lib'
make: **\* [libcork.la] Error 1
I can't finish compile....
is that bug?

**Comment by myGod0rz** [comment]
- 1. Check permission|owner|se context;
- 2. Use absolute path
