### ISSUE TITLE
How to bind TCP and UDP ports independently?

### ISSUE THREAD

**Issue by vimagick** [shadowsocks/shadowsocks-libev#904]
There is only one option (`-p`) to bind ports for both TCP and UDP.
How can I bind ports independently?

It's useful when ISP only allow `80/tcp` and `53/udp`.
People can setup a `ss-server` to bypass firewall.

```
    ss-[local|redir|server|tunnel]

       -p <server_port>           port number of your remote server

       [-u]                       enable udprelay mode,
                                  TPROXY is required in redir mode
```

Thanks for your hard work! :+1:

**Comment by fiercebead** [comment]
You can run 2 ss-server

**Comment by vimagick** [comment]
@fiercebead  It's a good idea. :)

**Comment by madeye** [comment]
Use `-U` for udp only mode.

**Comment by vimagick** [comment]
Great solution! :+1:

I need to run two `ss-server` instances. (TCP ONLY + UDP ONLY)

**Comment by debiansid** [comment]
What is UDP for?

**Comment by vimagick** [comment]
@debiansid 
ss-server has udprelay mode to support UDP transparent proxy.
Several `iptables` rules are required to make it work.

```
ss-redir -c /etc/shadowsocks.json -u -l 1234 -f /var/run/ss-redir.pid
iptables ...
```
