### ISSUE TITLE
求帮助，关于supervisor配置。

### ISSUE THREAD

**Issue by 6656i** [shadowsocks/shadowsocks-libev#906]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
2.5.5
### What operating system are you using?
centos 6 32bit
### What did you do?
服务器有A、B、C、D，4个配置文件。
通过supervisor启动时，会启动4个同名进程，why？如果全部启动4个配置，则出现16个进程。。。，什么情况。
[program:shadowsocks-libev-A]
directory=/etc/shadowsocks-libev
command=ss-server -c /etc/shadowsocks-libev/config-A.json -u -f /var/run/shadowsocks-libev/shadowsocks-libev-A.pid
process_name=%(program_name)s
autostart=true
autoresart = true
redirect_stderr=true
stdout_logfile=/var/log/shadowsocks-libev/shadowsocks-libev-A.log
stdout_logfile_maxbytes=1MB
stdout_logfile_backups=0

而单独使用命令
ss-server -c /etc/shadowsocks-libev/config-A.json -u -f /var/run/shadowsocks-libev/shadowsocks-libev-A.pid
则正常，只会启动一个进程。

**Comment by madeye** [comment]
Remove `-f /var/run/shadowsocks-libev/shadowsocks-libev-A.pid` in your supervisor config.

**Comment by 6656i** [comment]
@madeye get it, thanks.
