### ISSUE TITLE
latest commit ss-server failed with code=killed, signal=SEGV

### ISSUE THREAD

**Issue by manjuprajna** [shadowsocks/shadowsocks-libev#907]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
v2.55 cfae8dc

### What operating system are you using?
CentOS 7.2 x64

### What did you do?
git pull to commit cfae8dc and compile

### What did you expect to see?
work as usual

### What did you see instead?
systemctl status shadowsocks-libev -l
● shadowsocks-libev.service - Shadowsocks-libev Default Server Service
   Loaded: loaded (/usr/lib/systemd/system/shadowsocks-libev.service; enabled; vendor preset: disabled)
   Active: failed (Result: signal) since Sat 2016-10-29 09:46:15 CST; 13s ago
     Docs: man:shadowsocks-libev(8)
  Process: 2598 ExecStart=/usr/bin/ss-server -a $USER -c $CONFFILE $DAEMON_ARGS (code=killed, signal=SEGV)
 Main PID: 2598 (code=killed, signal=SEGV)

Oct 29 09:45:30 localhost systemd[1]: Starting Shadowsocks-libev Default Server Service...
Oct 29 09:45:30 localhost ss-server[2598]: 2016-10-29 09:45:30 INFO: onetime authentication enabled
Oct 29 09:45:30 localhost ss-server[2598]: 2016-10-29 09:45:30 INFO: UDP relay enabled
Oct 29 09:45:30 localhost ss-server[2598]: 2016-10-29 09:45:30 INFO: initializing ciphers... chacha20-ietf
Oct 29 09:45:30 localhost ss-server[2598]: 2016-10-29 09:45:30 INFO: tcp port reuse enabled
Oct 29 09:45:30 localhost ss-server[2598]: 2016-10-29 09:45:30 INFO: udp port reuse enabled
Oct 29 09:45:30 localhost ss-server[2598]: 2016-10-29 09:45:30 INFO: listening at 0.0.0.0:8388
Oct 29 09:46:15 localhost systemd[1]: shadowsocks-libev.service: main process exited, code=killed, status=11/SEGV
Oct 29 09:46:15 localhost systemd[1]: Unit shadowsocks-libev.service entered failed state.
Oct 29 09:46:15 localhost systemd[1]: shadowsocks-libev.service failed.

### What is your config in detail (with all sensitive info masked)?
config as before, nothing changed, only difference is upgrading to latest commit.

after upgrading to latest commit, will immediately enter failed state when any clients try to connect.

**Comment by smounives** [comment]
I have the same problem

**Comment by wxyzh** [comment]
同样的问题，我用的ss-manger 启动监听的两个端口，当连接的时候，被连接端口的进程自动退出

**Comment by manjuprajna** [comment]
别的系统也是？
