### ISSUE TITLE
configure: error: MBEDTLS_CIPHER_MODE_CFB required

### ISSUE THREAD

**Issue by tianlichunhong** [shadowsocks/shadowsocks-libev#910]
checking for library containing floor... none required
checking for thread local storage (TLS) class... __thread
checking for mbedtls_cipher_setup in -lmbedcrypto... yes
checking whether mbedtls supports Cipher Feedback mode or not... configure: error: MBEDTLS_CIPHER_MODE_CFB required
make[2]: *** [/root/lede-sdk-ramips-mt7620_gcc-5.4.0_musl-1.1.15.Linux-x86_64/build_dir/target-mipsel_24kc_musl-1.1.15/shadowsocks-libev/mbedtls/shadowsocks-libev-2.5.5/.configured_yynyyyyy] Error 1
make[2]: Leaving directory `/root/lede-sdk-ramips-mt7620_gcc-5.4.0_musl-1.1.15.Linux-x86_64/package/shadowsocks-libev'
make[1]: *** [package/shadowsocks-libev/compile] Error 2
make[1]: Leaving directory `/root/lede-sdk-ramips-mt7620_gcc-5.4.0_musl-1.1.15.Linux-x86_64'
make: *** [package/shadowsocks-libev/compile] Error 2

不知道该如何办？有高手详细指点一下？

**Comment by kimw** [comment]
See #663. BTW, why not search it yourself?

**Comment by tianlichunhong** [comment]
I see the answer, but not understand. If some can tell me how to do step by step, it is many thanks. I have copy the file mbedtls to the package. But I do not know how to do next.
