### ISSUE TITLE
同配置 ss-local 两个进程，竟然能绑定同一端口

### ISSUE THREAD

**Issue by maxchendt** [shadowsocks/shadowsocks-libev#913]
shadowsocks-libev 2.5.3 on Ubuntu 16.04 x64

我把  ss-local 做成桌面快捷方式，点击启动。刚才不小心忘了已经打开一个 ss-local 了，又双击启动了一个，竟然启动成功 `sudo lsof -i -P -n | grep 8010` 结果如下

```
ss-local  23189 dengta    5u  IPv6 1156130      0t0  TCP [::1]:8010 (LISTEN)
ss-local  23189 dengta    6u  IPv6 1156133      0t0  UDP [::1]:8010 
ss-local  23189 dengta    7u  IPv6 1156263      0t0  TCP [::1]:8010->[::1]:40862 (ESTABLISHED)
ss-local  23196 dengta    5u  IPv6 1156156      0t0  TCP [::1]:8010 (LISTEN)
ss-local  23196 dengta    6u  IPv6 1156159      0t0  UDP [::1]:8010 
ss-local  23196 dengta   23u  IPv6 1153935      0t0  TCP [::1]:8010->[::1]:40920 (ESTABLISHED)
ss-local  23196 dengta   25u  IPv6 1153937      0t0  TCP [::1]:8010->[::1]:40924 (ESTABLISHED)

```

我们看到，ss-local 启动了两个进程 23189 和 23196，都绑定相同的 8010 端口 (IPv6). 测试了下，通过他代理，两个进程各代理大约一半的连接 ![screenshot from 2016-10-30 20-30-33](https://cloud.githubusercontent.com/assets/9275768/19836577/e846cd2e-9edf-11e6-9719-71c03cf576e9.png)

我觉得有点奇怪，记得以前如果已经打开一个 客户端，再打开另一个相同配置的客户端，会报告端口绑定错误并退出的。

**Comment by pexcn** [comment]
好像是为多核心的设备准备的

**Comment by breakwa11** [comment]
因为启用了SO_REUSEPORT

**Comment by aa65535** [comment]
#493
