### ISSUE TITLE
2.5.5在一段时间后各种客户端都无法连接

### ISSUE THREAD

**Issue by 476210180** [shadowsocks/shadowsocks-libev#914]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
shadowsocks-libev 2.5.5 with OpenSSL 1.0.1e 11 Feb 2013 from librehat repo.

### What operating system are you using?
CentOS 6.8 x86_64

### What did you do?
`service shadowsocks-libev start` 启动后过一段时间后各客户端（Android、Windows）均无法连接到服务器，只能更换IP或重启服务端。浏览器显示“连接被重置”。

### What is your config in detail (with all sensitive info masked)?
/etc/shadowsocks-libev/config.json
{
    "server":"0.0.0.0",
    "server_port":9822,
    "local_port":1080,
    "password":"###password###",
    "timeout":60,
    "method":"aes-128-cfb"
}

**Comment by madeye** [comment]
Try https://github.com/shadowsocks/shadowsocks-libev/issues/899#issuecomment-256233948

**Comment by 476210180** [comment]
@madeye 
感谢回复！是否能在`config.json`中指定 acl ？还是只能通过命令行指定？

**Comment by madeye** [comment]
Only available in command line.
