### ISSUE TITLE
is it possible OR where to set a white list after installing the ss-server?

### ISSUE THREAD

**Issue by GitatHub** [shadowsocks/shadowsocks-libev#917]
OK, I find the answer (failed)

https://github.com/shadowsocks/shadowsocks-libev/blob/master/doc/shadowsocks-libev.asciidoc

in /etc/default/shadowsocks-libev
set 
DAEMON_ARGS=" -u -w --acl /etc/shadowsocks-libev/local.acl "
-w enable white list in combining with enabling acl

I copied the local.acl file to /etc/shadowsocks-libev/.

FAILED:

  Process: 32380 ExecStart=/usr/bin/ss-server -a $USER -c $CONFFILE $DAEMON_ARGS (code=exited, status=1/FAILURE)

Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?

shadowsocks-libev_2.5.6-1_amd64.deb

### What operating system are you using?
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.6 (jessie)
Release:	8.6
Codename:	jessie

### What did you do?
normally set; normally working; doing nothing

### What did you expect to see?
I want to manually add ip white list after compiling and installing the server, is there a config file for this?

I saw this, however, it's for precompiling only
https://github.com/shadowsocks/shadowsocks-libev/blob/master/acl/local.acl

### What did you see instead?
I find some IPs are blocked by mistake, I want to add them to the whitelist w/o reinstalling ss-server

### What is your config in detail (with all sensitive info masked)?
{
    "server":["0.0.0.0","[::0]"],
    "server_port":xxx,
    "local_port":xxxx,
    "password":"xxxxxx",
    "timeout":60,
    "method":"xxxx-xxxx-xxx"
}

**Comment by haodong** [comment]
use https://github.com/cyfdecyf/cow or https://github.com/renzhn/MEOW/ instead.

**Comment by zsf222** [comment]
How did you know that use ["0.0.0.0","[::0]"] for more ips? There are no detailed documents in this repo? Many thanks.

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks-libev/issues/899#issuecomment-256233948

**Comment by GitatHub** [comment]
in /etc/default/shadowsocks-libev
set
DAEMON_ARGS=" -u -w --acl /etc/shadowsocks-libev/local.acl "
-w enable white list in combining with enabling acl

I copied the local.acl file to /etc/shadowsocks-libev/.

FAILED:

Process: 32380 ExecStart=/usr/bin/ss-server -a $USER -c $CONFFILE $DAEMON_ARGS **(code=exited, status=1/FAILURE)**

**Comment by madeye** [comment]
The document is out of date, fixed via https://github.com/shadowsocks/shadowsocks-libev/commit/3036443ac50e312aa87a57eec95763ffa525f5ab

Remove `-w` from your command line.

**Comment by GitatHub** [comment]
@madeye It works. Thanks.
