### ISSUE TITLE
confusions about the acl list

### ISSUE THREAD

**Issue by 476210180** [shadowsocks/shadowsocks-libev#918]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
shadowsocks-libev 2.5.5

### What operating system are you using?
CentOS 6.8 x86_64

### What did you do?
Use acl list to workaround issue #914 

### What did you expect to see?
If acl list is defined, IPs in the list should not being blocked by the server even if they has a incorrect configuration (my personal opinion)

### What did you see instead?
Server blocked IPs in the acl list

### What is your config in detail (with all sensitive info masked)?
There are 2 SS Android clients in use during this time period, one of them has a incorrect configuration.
Start up command line: `ss-server -c /etc/shadowsocks-libev/config.json -v --acl /etc/shadowsocks-libev/list.acl`
Whole contents of the acl file: 
[white_list]
60.18.128.0/17
Error message
![2016-11-03_230450](https://cloud.githubusercontent.com/assets/8447650/19972301/861c81b2-a21c-11e6-88f0-d58ad7e9928b.gif)

**Comment by madeye** [comment]
This feature requires 2.5.6. Update and try again.

**Comment by madeye** [comment]
Closed as inactive.
