### ISSUE TITLE
How can i open port on shadowsocks-libev server?

### ISSUE THREAD

**Issue by slrslr** [shadowsocks/shadowsocks-libev#919]
### What version of shadowsocks-libev are you using?
Shadowsocks-libev 2.5.1

### What operating system are you using?
Linux CentOS 6.x 64bit used on shadowsocks-libev server

### What did you do?
from remote computer: #  nmap -Pn -p 8999 myshadowsocksproxyserverip
PORT     STATE  SERVICE
8999/tcp closed bctp

on the shadowsocks-libev server: # iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination
ACCEPT     tcp  --  my.client-hostname.here      anywhere            tcp dpt:socks
REJECT     tcp  --  anywhere             anywhere            tcp dpt:socks reject-with icmp-port-unreachable

### What did you expect to see?
port 8999 open and shadowsocks-libev forwarding incoming connections to the shadowscosks client

Please how can open that port to work with shadowsocks-libev ? I have this port set in my torrent client as "Port used for incoming connections" so i would like ss-server to forward this connections to me. Also unsure if UDP/TCP.

Thank You

**Comment by madeye** [comment]
Nope, you cannot do reverse tunneling with shadowsocks. It's not supported.

**Comment by fiercebead** [comment]
To open port, the easiest way is disabling firewall.

CentOS 6:
```
service iptables stop
chkconfig iptables off
```

CentOS 7:
```
systemctl stop firewalld
systemctl disable firewalld
```

SELinux may cause some problems too.
Disable SELinux:
```
/etc/selinux/config
SELINUX=disabled
```
Need reboot, also you can use `setenforce 0` to set SELinux to permissive mode temporarily.
I'm not sure if CentOS 6's SELinux config file has the same path.

Finally, the "Port used for incoming connections" is the port that uTorrent listens, normally you would like to forward it on your router for best torrent speed, it is not related to shadowsocks at all.
