### ISSUE TITLE
Could madeye please kindly explain the usage of latest commit 980d801?

### ISSUE THREAD

**Issue by manjuprajna** [shadowsocks/shadowsocks-libev#921]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
ss-redir v2.56

### What operating system are you using?
openwrt chaos calmer 1505

### What did you do?
normal usage

### What did you expect to see?
what's the usage of this new timeout function

### What did you see instead?
nothing unusual

### What is your config in detail (with all sensitive info masked)?

before ss-redir on openwrt has a default time out which is 60s, so why now here comes a new commit for that?
and before the default time out is 60s, now why default is 600s, 10 times.

and I have another stupid question to ask: both client side and server side have time out config, for example, client side is 60s, server side is 300s, so if connection is established, how long will it last until time out? 60 or 300s?

thank you.

**Comment by madeye** [comment]
The larger default timeout is to solve long TCP connection issue. The smaller timeout of server and client is the effective one.
