### ISSUE TITLE
git pull更新失败

### ISSUE THREAD

**Issue by jinyujiao** [shadowsocks/shadowsocks-libev#923]
### What version of shadowsocks-libev are you using?
2.5.3

### What operating system are you using?
debian

### What did you do?
想更新下shadowsocks，结果报错。
操作如下：
cd shadowsocks-libev
git pull
./configure
make
sudo make install

### What did you see instead?
在执行make的时候提示：
Makefile:649: recipe for target 'ss-local' failed
make[2]: *** [ss-local] Error 1
make[2]: Leaving directory '/root/shadowsocks-libev/src'
Makefile:469: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/root/shadowsocks-libev'
Makefile:377: recipe for target 'all' failed
make: *** [all] Error 2

不知道哪里操作不对，希望能帮忙，谢谢了。

**Comment by madeye** [comment]
Try `make distclean`
