### ISSUE TITLE
HTTPS forwarding

### ISSUE THREAD

**Issue by LadMartin** [shadowsocks/shadowsocks-libev#926]
Hello 

### What version of shadowsocks-libev are you using?
2.5.4

### What operating system are you using?
Debian Jessie

### What did you do?

We have several slow communication lines, and we want to speed up the communication. So we use shadowsocks with the --mptcp option as a tunnel to server.

we have following setup
A USER -> Wi-Fi -> SQUID -> SHADOWSOCKS_CLIENT -> MPTCP -> SHADOWSOCKS_SERVER -> INTERNET

it works for HTTP, but not for HTTPS. We have problem with certificate most likely. But we dont want to add an authority to our client. 

for HTTPS:
We skip the SQUID and we redirect HTTPS to shadowsock directly.

This is the problem : 
Connecting to www.google.com (www.google.com)|216.58.209.164|:443... connected.
OpenSSL: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
Unable to establish SSL connection.

I would like to ask for an advice, what should be the way how to solve this case, what is the best practice here and how to setup it for example with iptables.

thank you

**Comment by rampageX** [comment]
Why you put SQUID front of SHADOWSOCKS_CLIENT? If you want use transparent redirector, you should just use ss-redir for CLIENT. I don't konw ss-redir support MPTCP or not, if not, use redsocks + ss-local.

**Comment by LadMartin** [comment]
squid is used for filtering HTTP (blacklist) and we don't need it for HTTPS. 

We are using ss-redir, it has --mptcp and it is working well for HTTP.

Simply what we do is HTTP redirecting through iptables to ss-redir. Should it work for HTTPS aswell? if yes maybe we have just a problem in the configuration.

we appreciate your help

**Comment by rampageX** [comment]
I don't have experience with MPTCP, but without it, use ss-redir with HTTPS is work fine here. You can switch off MPTCP and test again to find out whats wrong with this problem.

**Comment by madeye** [comment]
Try `ss-redir` instead. For more details, please refer to these slides: 

http://www.slideshare.net/ovhcom/introduction-to-overthebox

**Comment by LadMartin** [comment]
Thx, the link helped us

**Comment by leidemon** [comment]
> Thx, the link helped us. Sorry for no earlier response.

hi,LadMartin :
Do you have any blogs to share?

**Comment by leidemon** [comment]
> Try `ss-redir` instead. For more details, please refer to these slides:
> 
> http://www.slideshare.net/ovhcom/introduction-to-overthebox

hi，madeye：
Do you have new link for it?http://www.slideshare.net/ovhcom/introduction-to-overthebox is not available
