### ISSUE TITLE
请教下如何编译iOS可用的.a文件？

### ISSUE THREAD

**Issue by y1024** [shadowsocks/shadowsocks-libev#927]
请教下如何编译iOS可用的.a文件？
谢谢

**Comment by y1024** [comment]
使用 macOS编译的 10.12.1

**Comment by madeye** [comment]
No idea. I think you have to figure out the answer yourself.

**Comment by y1024** [comment]
额 谢谢 理解错了

**Comment by ameue** [comment]
官方编译出来的.a静态库只有x86架构，不知道如果编译出arm架构。而且编译后的include文件中的shadowsocks.h中，启动的是ss-local，iOS不支持socks代理，要自己处理packetFlow发给ss-local。
