### ISSUE TITLE
Build failure due to type incomplete with openssl

### ISSUE THREAD

**Issue by tontyoutoure** [shadowsocks/shadowsocks-libev#928]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?

2.5.6
### What operating system are you using?

Ubuntu 14.04
### What did you do?

Compile package
### What did you expect to see?

Compile success
### What did you see instead?
(end lines of make output);
In file included from encrypt.c:77:0:
encrypt.h:108:18: error: field 'evp' has incomplete type
     cipher_evp_t evp;
                  ^
encrypt.c: In function 'enc_key_init':
encrypt.c:1389:17: error: storage size of 'cipher_info' isn't known
     cipher_kt_t cipher_info;
                 ^
encrypt.c:1400:15: error: dereferencing pointer to incomplete type
         cipher->key_len = supported_ciphers_key_size[method];
               ^
encrypt.c:1401:15: error: dereferencing pointer to incomplete type
         cipher->iv_len  = supported_ciphers_iv_size[method];
               ^
encrypt.c:1389:17: error: unused variable 'cipher_info' [-Werror=unused-variable]
     cipher_kt_t cipher_info;
                 ^
cc1: all warnings being treated as errors
make[2]: *** [libshadowsocks_libev_la-encrypt.lo] Error 1
make[2]: Leaving directory `/home/likun/Downloads/shadowsocks-libev-master/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/likun/Downloads/shadowsocks-libev-master'
make: *** [all] Error 2

### What is your config in detail (with all sensitive info masked)?

./configure --prefix=$HOME/usr/local --with-pcre=$HOME/usr/local

**Comment by madeye** [comment]
Post your config.log and full output of your building here.

**Comment by tontyoutoure** [comment]
**Make output**
make  all-recursive
make[1]: Entering directory `/home/likun/Downloads/shadowsocks-libev-master'
Making all in libsodium
make[2]: Entering directory `/home/likun/Downloads/shadowsocks-libev-master/libsodium'
Making all in src
make[3]: Entering directory `/home/likun/Downloads/shadowsocks-libev-master/libsodium/src'
Making all in libsodium
make[4]: Entering directory `/home/likun/Downloads/shadowsocks-libev-master/libsodium/src/libsodium'
Making all in include
make[5]: Entering directory `/home/likun/Downloads/shadowsocks-libev-master/libsodium/src/libsodium/include'
make[5]: Nothing to be done for `all'.
make[5]: Leaving directory `/home/likun/Downloads/shadowsocks-libev-master/libsodium/src/libsodium/include'
make[5]: Entering directory `/home/likun/Downloads/shadowsocks-libev-master/libsodium/src/libsodium'
make[5]: Nothing to be done for `all-am'.
make[5]: Leaving directory `/home/likun/Downloads/shadowsocks-libev-master/libsodium/src/libsodium'
make[4]: Leaving directory `/home/likun/Downloads/shadowsocks-libev-master/libsodium/src/libsodium'
make[4]: Entering directory `/home/likun/Downloads/shadowsocks-libev-master/libsodium/src'
make[4]: Nothing to be done for `all-am'.
make[4]: Leaving directory `/home/likun/Downloads/shadowsocks-libev-master/libsodium/src'
make[3]: Leaving directory `/home/likun/Downloads/shadowsocks-libev-master/libsodium/src'
make[3]: Entering directory `/home/likun/Downloads/shadowsocks-libev-master/libsodium'
make[3]: Nothing to be done for `all-am'.
make[3]: Leaving directory `/home/likun/Downloads/shadowsocks-libev-master/libsodium'
make[2]: Leaving directory `/home/likun/Downloads/shadowsocks-libev-master/libsodium'
Making all in libcork
make[2]: Entering directory `/home/likun/Downloads/shadowsocks-libev-master/libcork'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/home/likun/Downloads/shadowsocks-libev-master/libcork'
Making all in libipset
make[2]: Entering directory `/home/likun/Downloads/shadowsocks-libev-master/libipset'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/home/likun/Downloads/shadowsocks-libev-master/libipset'
Making all in libudns
make[2]: Entering directory `/home/likun/Downloads/shadowsocks-libev-master/libudns'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/home/likun/Downloads/shadowsocks-libev-master/libudns'
Making all in libev
make[2]: Entering directory `/home/likun/Downloads/shadowsocks-libev-master/libev'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/home/likun/Downloads/shadowsocks-libev-master/libev'
Making all in src
make[2]: Entering directory `/home/likun/Downloads/shadowsocks-libev-master/src'
  CC       libshadowsocks_libev_la-encrypt.lo
In file included from encrypt.c:77:0:
encrypt.h:108:18: error: field 'evp' has incomplete type
     cipher_evp_t evp;
                  ^
encrypt.c: In function 'enc_key_init':
encrypt.c:1389:17: error: storage size of 'cipher_info' isn't known
     cipher_kt_t cipher_info;
                 ^
encrypt.c:1400:15: error: dereferencing pointer to incomplete type
         cipher->key_len = supported_ciphers_key_size[method];
               ^
encrypt.c:1401:15: error: dereferencing pointer to incomplete type
         cipher->iv_len  = supported_ciphers_iv_size[method];
               ^
encrypt.c:1389:17: error: unused variable 'cipher_info' [-Werror=unused-variable]
     cipher_kt_t cipher_info;
                 ^
cc1: all warnings being treated as errors
make[2]: *** [libshadowsocks_libev_la-encrypt.lo] Error 1
make[2]: Leaving directory `/home/likun/Downloads/shadowsocks-libev-master/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/likun/Downloads/shadowsocks-libev-master'
make: *** [all] Error 2

**config.log attached**
[config.log.txt](https://github.com/shadowsocks/shadowsocks-libev/files/577360/config.log.txt)

**Comment by madeye** [comment]
Could you make sure there exists correct `openssl/evp.h` under `/home/likun/usr/local/include`? It looks like you're including a broken header file.

**Comment by hosiet** [comment]
@madeye This is due to the API break of OpenSSL 1.1.0.

Debian is trying to put OpenSSL 1.1.0 into next release (Debian 9). Building against OpenSSL 1.1.0 will cause problems. This should be considered as a bug of ss-libev.

P.S. The current [v2.5.6+ds](https://tracker.debian.org/pkg/shadowsocks-libev) in Debian did not encounter this problem because it uses mbedTLS.

**Comment by wongsyrone** [comment]
If OpenSSL has something like Linux kernel version code, we can handle this for different versions.

**Comment by tontyoutoure** [comment]
So which exactly OpenSSL version should I use?

**Comment by wongsyrone** [comment]
Older than 1.1.0

**Comment by wongsyrone** [comment]
Got it.

1.1.0 should be `0x10100000L`

ref: https://wiki.openssl.org/index.php/Manual:OPENSSL_VERSION_NUMBER(3)
