### ISSUE TITLE
pcre library 问题

### ISSUE THREAD

**Issue by landvd** [shadowsocks/shadowsocks-libev#929]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
2.5.6

### What operating system are you using?
Ubuntu 16.04 LTS

### What did you do?
我在用ShadowSocks-libv V2.5.6，用--host=mipsel-linux-gnu，会提示
checking for library containing pcre_exec... no
configure: error: Cannot find pcre library. Configure --with-pcre=DIR，
但是不加--host=mipsel-linux-gnu就会正常，由于我的设备是MT7621A,属于mipsel架构，必须要添加才能运行，pcre我已经安装了8.3.9，但还是会提示以上错误。

**Comment by zinian** [comment]
apt-get install libpcre3 libpcre3-dev 
在centos 上是需要 pcre-devel，你有没有安装 libpcre3-dev

**Comment by fiercebead** [comment]
pcre也要`./configure --host=mipsel-linux-gnu`然后编译吧，就像你的openssl一样

**Comment by landvd** [comment]
已解决，pcre用./configure --host=mipsel-linux-gnu就可以了，pcre需要安装mipsel c++编译器
https://packages.debian.org/jessie/g++

**Comment by zuozhen** [comment]
我也遇到相同的问题，但是编译pcre （./configure --prefix=/home/zuozhen/workspace/shadowsocks-libev/pcre --host=arm-linux） 成功后，编译shadowsocks-libev时还是有这个错，提交了新的[issue 949](https://github.com/shadowsocks/shadowsocks-libev/issues/949)

**Comment by gatalon** [comment]
./scripts/feeds install libpcre
我是执行了这个就好了。

**Comment by linzhuvi** [comment]
> apt-get install libpcre3 libpcre3-dev
> 在centos 上是需要 pcre-devel，你有没有安装 libpcre3-dev

you xiu
