### ISSUE TITLE
Cannot genrate key and IV

### ISSUE THREAD

**Issue by SuperSuperSuperSuper5** [shadowsocks/shadowsocks-libev#930]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
2.5.6

### What operating system are you using?
CentOS 7

### What did you do?
start the ss-server

### What did you expect to see?
how to run it

### What did you see instead?
i don't kown

### What is your config in detail (with all sensitive info masked)?
./ss-server -s x.x.x.x -p 8001 -k passwd -m aes-256-cfb
or
./ss-server -s x.x.x.x -p 8001 -k passwd
or
./ss-server -s x.x.x.x -p 8001 -k passwd -m rc4-md5
it show me the same error:
initializing cipher... aes-256-cfb
Cannot generate key and IV,

initializing cipher... rc4-md5
Cannot generate key and IV,

but, i use it never use the key and IV command yet
so, i need some help
THX
jay

**Comment by shixy91** [comment]
i had the same problem on ubuntu 14.04 x64 with the latest commit
the log shows:
2016-11-08 18:52:36 INFO: onetime authentication enabled
 2016-11-08 18:52:36 INFO: UDP relay enabled
 2016-11-08 18:52:36 INFO: initializing ciphers... aes-256-cfb
 2016-11-08 18:52:36 ERROR: Cannot generate key and IV
commit 854c6f9 works fine, but the latest has this problem.
