### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by rstanislav** [shadowsocks/shadowsocks-libev#931]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
Current git trunk

### What operating system are you using?
Ubuntu 16.04

### What did you do?
/usr/local/bin/ss-server -c /etc/shadowsocks-libev/ss-config.json

### What did you expect to see?
running server

### What did you see instead?
2016-11-08 21:03:52 INFO: using tcp fast open
 2016-11-08 21:03:52 INFO: initializing ciphers... aes-128-cfb
Segmentation fault

### What is your config in detail (with all sensitive info masked)?
{
        "server": "192.168.1.10",
        "server_port": 444,
        "password":"(hidden for security reasons)",
        "method":"aes-128-cfb",
        "timeout": 600,
        "fast_open": true,
        "mptcp": true,
        "interface":"em1"
}

Last updated from trunk about 2 months ago, nothing changed in config etc..

ps ipv6 disabled in sysctl.. maybe thats the reason ?

**Comment by madeye** [comment]
Could you try again with 2965801?

**Comment by zinian** [comment]
@madeye  Debian GNU/Linux 8
 Latest commit 114bc67   
root@localhost:~# ss-server -p 443 -k password -m chacha20
 2016-11-08 23:16:49 INFO: initializing ciphers... chacha20
Segmentation fault

**Comment by madeye** [comment]
Please try c5eab13.
