### ISSUE TITLE
latest two commits of ss-server failed to run on CentOS 7

### ISSUE THREAD

**Issue by manjuprajna** [shadowsocks/shadowsocks-libev#933]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
v2.56 commit 114bc67 and commit 2965801 ss-server

### What operating system are you using?
CentOS 7.2

### What did you do?
compile to latest two commits

### What did you expect to see?
normal working 

### What did you see instead?
service failed

shadowsocks-libev.service - Shadowsocks-libev Default Server Service
   Loaded: loaded (/usr/lib/systemd/system/shadowsocks-libev.service; enabled; vendor preset: disabled)
   Active: failed (Result: signal) since Wed 2016-11-09 11:26:26 CST; 1min 0s ago
     Docs: man:shadowsocks-libev(8)
  Process: 1223 ExecStart=/usr/bin/ss-server -a $USER -c $CONFFILE $DAEMON_ARGS (code=killed, signal=SEGV)
 Main PID: 1223 (code=killed, signal=SEGV)

Nov 09 11:26:26 localhost systemd[1]: Started Shadowsocks-libev Default Server Service.
Nov 09 11:26:26 localhost systemd[1]: Starting Shadowsocks-libev Default Server Service...
Nov 09 11:26:26 localhost ss-server[1223]: 2016-11-09 11:26:26 INFO: onetime authentication enabled
Nov 09 11:26:26 localhost ss-server[1223]: 2016-11-09 11:26:26 INFO: UDP relay enabled
Nov 09 11:26:26 localhost ss-server[1223]: 2016-11-09 11:26:26 INFO: initializing ciphers... chacha20-ietf
Nov 09 11:26:26 localhost systemd[1]: shadowsocks-libev.service: main process exited, code=killed, status=11/SEGV
Nov 09 11:26:26 localhost systemd[1]: Unit shadowsocks-libev.service entered failed state.
Nov 09 11:26:26 localhost systemd[1]: shadowsocks-libev.service failed.

### What is your config in detail (with all sensitive info masked)?
same as before

I did not encounter problem mentioned in #930 after I compile commit b43a715, but both commit 114bc67 and commit 2965801, I see same error message as I pasted above.

**Comment by madeye** [comment]
Try c5eab13afd324f8aaa8df6597f62bde310bf52ae

**Comment by manjuprajna** [comment]
working normally now for 10 minutes, looking good.
@madeye you may close this issue, thank you!
