### ISSUE TITLE
Another app is currently holding the xtables lock error after commit b43a715

### ISSUE THREAD

**Issue by manjuprajna** [shadowsocks/shadowsocks-libev#935]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
v2.56

### What operating system are you using?
CentOS 7.2

### What did you do?
compile after commit b43a715

### What did you expect to see?
normal running state

### What did you see instead?
Nov  9 04:50:06 localhost ss-server: iptables: Bad rule (does a matching rule exist in that chain?).
Nov  9 04:50:06 localhost ss-server: Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
Nov  9 04:50:34 localhost ss-server: Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
Nov  9 04:51:17 localhost ss-server: Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
Nov  9 04:54:01 localhost ss-server: Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
Nov  9 04:55:45 localhost ss-server: Another app is currently holding the xtables lock. Perhaps you want to use the -w option?

### What is your config in detail (with all sensitive info masked)?
as before

I don't know the exact commit number that I compile and see such error message, maybe after commit b43a715, don't know what do these error message mean, seems my client side working normally.

and I am using CentOS firewalld, not iptables, maybe because of firewalld?

**Comment by madeye** [comment]
Could you try 	085efc1 again?

**Comment by manjuprajna** [comment]
I've upgraded to the latest commit, still the same error message:
Nov 10 09:37:17 localhost.localdomain ss-server[1206]: 2016-11-10 09:37:17 INFO: listening at 0.0.0.0:[port]
Nov 10 09:39:05 61-216-34-217.HINET-IP.hinet.net ss-server[1206]: iptables: Bad rule (does a matching rule exist in that chain?).
Nov 10 09:39:10 61-216-34-217.HINET-IP.hinet.net ss-server[1206]: Another app is currently holding the xtables lock. Perhaps you want to use the -w option?

I am using firewalld, not iptables, does it matter?

**Comment by wongsyrone** [comment]
I think it matters. Although firewalld may add interfaces for iptables compatibility, this is not guaranteed.

**Comment by madeye** [comment]
Do you have any issue with Docker?

**Comment by madeye** [comment]
You may also try https://www.digitalocean.com/community/tutorials/how-to-migrate-from-firewalld-to-iptables-on-centos-7.

BTW, these message are just warnings. You can keep using shadowsocks without any problem.

**Comment by manjuprajna** [comment]
all of my server are using firewalld, so I don't want to change into iptables,  because I have other applications, it will be very troublesome if I change.
yes, it's still working normally, but maybe will lose some new feature you design.
I hope if you have time, try to fix it and maintain compatibily with firewalld, because many people using firewalld, not only centos, fedora too.
thank you!

**Comment by wongsyrone** [comment]
if firewalld offers a symlink to iptables and cmdline conversion procedures, this should not happen. If they are just different utilities to maintain xtables in the kernel, the exclusive lock cannot be acquired when you starts another utility.

The best way to solve this is to pass vars to shell script and let users customize them, or offer some examples to get rid of messages flood.

> -w, --wait
Wait for the xtables lock. To prevent multiple instances of the program from running concurrently, an attempt will be made to obtain an exclusive lock at launch. By default, the program will exit if the lock cannot be obtained. This option will make the program wait until the exclusive lock can be obtained.

**Comment by manjuprajna** [comment]
@wongsyrone yes, now it's working normally, but plenty of error messages, pretty annoying.

**Comment by madeye** [comment]
@manjuprajna Try the latest commit c35b143282da033a4eb63d920b1197374549e7b4

**Comment by manjuprajna** [comment]
just upgraded to the latest commit, looking good, no error messages any more.
