### ISSUE TITLE
Argument list too long, cannot allocate symbol search list: Cannot allocate memory

### ISSUE THREAD

**Issue by manjuprajna** [shadowsocks/shadowsocks-libev#940]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
v2.56 commit 604b5e

### What operating system are you using?
CentOS 7.2 x64 kernel 4.8.6 elrepo

### What did you do?
upgrade to latest commit 604b5e

### What did you expect to see?
working normally

### What did you see instead?
error message:
Nov 10 20:26:45 localhost ss-server[1096]: sh: /usr/bin/firewall-cmd: Argument list too long
Nov 10 20:26:45 localhost ss-server[1096]: sh: /usr/bin/firewall-cmd: Argument list too long
Nov 10 20:26:45 localhost ss-server[1096]: sh: /usr/bin/firewall-cmd: Argument list too long
Nov 10 20:26:45 localhost ss-server[1096]: sh: /usr/bin/firewall-cmd: Argument list too long
Nov 10 20:26:45 localhost ss-server[1096]: sh: error while loading shared libraries: cannot allocate symbol search list: Cannot allocate memory
Nov 10 20:26:45 localhost ss-server[1096]: sh: error while loading shared libraries: cannot allocate symbol search list: Cannot allocate memory
Nov 10 20:26:45 localhost ss-server[1096]: sh: error while loading shared libraries: cannot allocate symbol search list: Cannot allocate memory
Nov 10 20:26:45 localhost ss-server[1096]: sh: error while loading shared libraries: cannot allocate symbol search list: Cannot allocate memory
Nov 10 20:26:45 localhost ss-server[1096]: sh: error while loading shared libraries: libtinfo.so.5: failed to map segment from shared object: Cannot allocate memory
Nov 10 20:26:45 localhost ss-server[1096]: sh: error while loading shared libraries: cannot allocate symbol search list: Cannot allocate memory

### What is your config in detail (with all sensitive info masked)?
same as before

paste log messages here:

Nov 10 20:26:18 localhost kernel: [ pid ]   uid  tgid total_vm      rss nr_ptes nr_pmds swapents oom_score_adj name
Nov 10 20:26:18 localhost kernel: [  360]     0   360     8745      277      20       3        0             0 systemd-journal
Nov 10 20:26:18 localhost kernel: [  386]     0   386    10984      229      22       3        0         -1000 systemd-udevd
Nov 10 20:26:18 localhost kernel: [  417]     0   417    70864      334      38       3        0             0 rsyslogd
Nov 10 20:26:18 localhost kernel: [  418]     0   418    83448     4449      84       3        0             0 firewalld
Nov 10 20:26:18 localhost kernel: [  419]    81   419     6755      181      18       3        0          -900 dbus-daemon
...................................
Nov 10 20:26:18 localhost kernel: [ 1096]     0  1096     5789      246      16       3        0             0 ss-server
Nov 10 20:26:18 localhost kernel: [ 1123]     0  1123    52723     1734      55       3        0             0 ssserver
Nov 10 20:26:18 localhost kernel: [ 1205]     0  1205    20642      231      44       3        0         -1000 sshd
Nov 10 20:26:18 localhost kernel: [ 2353]     0  2353    60917     3734      75       3        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2354]     0  2354    60876     3730      72       3        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2355]     0  2355    60876     3732      74       3        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2356]     0  2356    60843     3715      75       3        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2357]     0  2357    60810     3654      75       4        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2358]     0  2358    60810     3660      75       3        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2359]     0  2359    60701     3611      72       3        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2360]     0  2360    60701     3612      71       3        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2361]     0  2361    76985     3561      73       3        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2362]     0  2362    60634     3541      74       3        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2363]     0  2363    60634     3545      75       3        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2364]     0  2364    60734     3612      73       3        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2366]     0  2366    76985     3594      73       3        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2367]     0  2367    60668     3544      74       3        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2368]     0  2368    76985     3584      74       3        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2369]     0  2369    60568     3469      71       4        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2370]     0  2370    76952     3492      73       3        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2371]     0  2371    60668     3512      74       4        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2372]     0  2372    60601     3476      72       3        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2373]     0  2373    60601     3461      74       3        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2374]     0  2374    76919     3444      73       3        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2375]     0  2375    60535     3407      71       4        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2376]     0  2376    76886     3411      75       3        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2377]     0  2377    60502     3377      74       3        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2378]     0  2378    76853     3366      74       3        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2379]     0  2379    60502     3345      74       3        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2380]     0  2380    76752     3315      75       3        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2381]     0  2381    76785     3361      73       4        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2382]     0  2382    60469     3340      75       4        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2383]     0  2383    60502     3348      72       4        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2385]     0  2385    60469     3347      72       3        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2386]     0  2386    60300     3150      71       3        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2387]     0  2387    60207     3136      72       4        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2388]     0  2388    60207     3163      70       4        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2391]     0  2391    76524     3075      72       4        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2392]     0  2392    60207     3149      74       4        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2393]     0  2393    60140     3015      72       3        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2394]     0  2394    76457     3061      73       3        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2395]     0  2395    76323     2903      70       3        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2396]     0  2396    59973     2819      71       3        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2397]     0  2397    59905     2752      70       4        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2398]     0  2398    59939     2812      71       3        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2399]     0  2399    59839     2688      71       3        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2400]     0  2400    76155     2724      74       3        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2402]     0  2402    58896     2231      68       3        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2403]     0  2403    58896     2231      71       3        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2404]     0  2404    56218     2183      62       4        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2405]     0  2405    56185     2136      64       3        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2406]     0  2406    49361     1911      50       3        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2407]     0  2407    49361     1912      50       4        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2409]     0  2409    49361     1911      52       3        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2410]     0  2410    49361     1919      54       3        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2411]     0  2411    49361     1917      52       3        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2412]     0  2412    49361     1904      53       3        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2413]     0  2413    48105     1711      49       3        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2414]     0  2414    48105     1711      50       3        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2415]     0  2415    48105     1711      49       4        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2416]     0  2416    48105     1711      50       4        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2417]     0  2417    49262     1845      51       3        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2418]     0  2418    48105     1711      50       3        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2419]     0  2419    49361     1917      51       4        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2420]     0  2420    48105     1711      49       4        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2421]     0  2421    46475     1624      43       3        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2422]     0  2422    46993     1632      46       3        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2423]     0  2423    48105     1711      50       3        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2424]     0  2424    46475     1624      46       3        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2425]     0  2425    44175     1546      42       3        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2426]     0  2426    43521     1355      39       4        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2428]     0  2428    43521     1355      41       3        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2429]     0  2429    59282     1367      39       3        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2431]     0  2431    59317     1368      39       3        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2432]     0  2432    59282     1367      39       3        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2433]     0  2433    41022     1028      35       3        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2434]     0  2434    41022     1027      35       3        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2435]     0  2435    41022     1028      35       3        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2436]     0  2436    41022     1027      36       3        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2437]     0  2437    41022     1027      36       3        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2438]     0  2438    41022     1027      36       3        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2441]     0  2441    56296     1000      36       3        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2442]     0  2442    40499     1046      33       3        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2443]     0  2443    39912      928      34       4        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2444]     0  2444    39912      928      32       3        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2445]     0  2445     4762      465      14       3        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2446]     0  2446     4762      466      14       3        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2447]     0  2447     4762      465      14       3        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: [ 2448]     0  2448     4581      257      13       3        0             0 firewall-cmd
Nov 10 20:26:18 localhost kernel: Out of memory: Kill process 418 (firewalld) score 17 or sacrifice child
Nov 10 20:26:18 localhost kernel: Killed process 418 (firewalld) total-vm:333792kB, anon-rss:17728kB, file-rss:68kB, shmem-rss:0kB
Nov 10 20:26:20 localhost kernel: firewall-cmd invoked oom-killer: gfp_mask=0x24280ca(GFP_HIGHUSER_MOVABLE|__GFP_ZERO), order=0, oom_score_adj=0
Nov 10 20:26:20 localhost kernel: firewall-cmd cpuset=/ mems_allowed=0
Nov 10 20:26:20 localhost kernel: CPU: 0 PID: 2374 Comm: firewall-cmd Not tainted 4.8.6-1.el7.elrepo.x86_64 #1

not sure if related to elrepo kernel?

**Comment by manjuprajna** [comment]
systemctl status firewalld -l
● firewalld.service - firewalld - dynamic firewall daemon
   Loaded: loaded (/usr/lib/systemd/system/firewalld.service; enabled; vendor preset: enabled)
   Active: failed (Result: signal) since Thu 2016-11-10 20:26:41 CST; 30min ago
  Process: 418 ExecStart=/usr/sbin/firewalld --nofork --nopid $FIREWALLD_ARGS (code=killed, signal=KILL)
 Main PID: 418 (code=killed, signal=KILL)

Nov 10 19:47:19 localhost systemd[1]: Starting firewalld - dynamic firewall daemon...
Nov 10 19:47:20 localhost systemd[1]: Started firewalld - dynamic firewall daemon.
Nov 10 19:49:27 localhost firewalld[418]: 2016-11-10 19:49:27 ERROR: COMMAND_FAILED: '/sbin/iptables -w2 -D SHADOWSOCKS_LIBEV_1096 -d x.x.x.x -j DROP' failed: iptables: Bad rule (does a matching rule exist in that chain?).
Nov 10 19:49:32 localhost firewalld[418]: 2016-11-10 19:49:32 ERROR: COMMAND_FAILED: '/sbin/iptables -w2 -D SHADOWSOCKS_LIBEV_1096 -d x.x.x.x -j DROP' failed: iptables: Bad rule (does a matching rule exist in that chain?).
Nov 10 19:50:49 localhost firewalld[418]: 2016-11-10 19:50:49 ERROR: COMMAND_FAILED: '/sbin/iptables -w2 -D SHADOWSOCKS_LIBEV_1096 -d x.x.x.x -j DROP' failed: iptables: Bad rule (does a matching rule exist in that chain?).
Nov 10 19:55:15 localhost firewalld[418]: 2016-11-10 19:55:15 ERROR: COMMAND_FAILED: '/sbin/iptables -w2 -D SHADOWSOCKS_LIBEV_1096 -d x.x.x.x -j DROP' failed: iptables: Bad rule (does a matching rule exist in that chain?).
Nov 10 20:26:21 localhost systemd[1]: firewalld.service: main process exited, code=killed, status=9/KILL
Nov 10 20:26:41 localhost.localdomain systemd[1]: Unit firewalld.service entered failed state.
Nov 10 20:26:41 localhost.localdomain systemd[1]: firewalld.service failed.

**Comment by madeye** [comment]
Remove the symbolic link of iptables, which could cause issues.

**Comment by madeye** [comment]
It looks like some kind of dead lock, causing all the calls of firewall-cmd blocked.

You may need to detect what blocks all these iptables calls first.

As a workaround, you can run ss-server in non-profit mode for now.

**Comment by madeye** [comment]
@manjuprajna Could you try again with 05450b51d4d0e2c7bd4b879ad2a971bdbf01568b

**Comment by manjuprajna** [comment]
@madeye sorry, because of double 11, busy shoping online, :)
actually last night, I found it cause firewalld crash, thus make my vps naked running. port forwarding stopped, because masquerade stopped. 

here is log:
Nov 11 14:10:50 localhost firewalld: 2016-11-11 14:10:50 ERROR: COMMAND_FAILED: '/sbin/iptables -w2 -D SHADOWSOCKS_LIBEV_1098 -d [ip] -j DROP' failed: iptables: Bad rule (does a matching rule exist in that chain?).
Nov 11 14:10:51 localhost firewalld: 2016-11-11 14:10:51 ERROR: COMMAND_FAILED: '/sbin/iptables -w2 -A SHADOWSOCKS_LIBEV_1098 -d [ip] -j DROP' failed: iptables: No chain/target/match by that name.
Nov 11 14:10:51 localhost firewalld: 2016-11-11 14:10:51 ERROR: COMMAND_FAILED: '/sbin/iptables -w2 -D SHADOWSOCKS_LIBEV_1098 -d [ip] -j DROP' failed: iptables: Bad rule (does a matching rule exist in that chain?).
Nov 11 14:10:52 localhost firewalld: 2016-11-11 14:10:52 ERROR: COMMAND_FAILED: '/sbin/iptables -w2 -A SHADOWSOCKS_LIBEV_1098 -d [ip] -j DROP' failed: iptables: No chain/target/match by that name.
Nov 11 14:10:52 localhost firewalld: 2016-11-11 14:10:52 ERROR: COMMAND_FAILED: '/sbin/iptables -w2 -D SHADOWSOCKS_LIBEV_1098 -d [ip] -j DROP' failed: iptables: Bad rule (does a matching rule exist in that chain?).
Nov 11 14:10:53 localhost firewalld: 2016-11-11 14:10:53 ERROR: COMMAND_FAILED: '/sbin/iptables -w2 -A SHADOWSOCKS_LIBEV_1098 -d [ip] -j DROP' failed: iptables: No chain/target/match by that name.
Nov 11 14:10:53 localhost firewalld: 2016-11-11 14:10:53 ERROR: COMMAND_FAILED: '/sbin/iptables -w2 -D SHADOWSOCKS_LIBEV_1098 -d [ip] -j DROP' failed: iptables: Bad rule (does a matching rule exist in that chain?).
Nov 11 14:10:53 localhost firewalld: 2016-11-11 14:10:53 ERROR: COMMAND_FAILED: '/sbin/iptables -w2 -A SHADOWSOCKS_LIBEV_1098 -d [ip] -j DROP' failed: iptables: No chain/target/match by that name.
Nov 11 14:10:53 localhost firewalld: 2016-11-11 14:10:53 ERROR: COMMAND_FAILED: '/sbin/iptables -w2 -D SHADOWSOCKS_LIBEV_1098 -d [ip] -j DROP' failed: iptables: Bad rule (does a matching rule exist in that chain?).
Nov 11 14:10:54 localhost firewalld: 2016-11-11 14:10:54 ERROR: COMMAND_FAILED: '/sbin/iptables -w2 -A SHADOWSOCKS_LIBEV_1098 -d [ip] -j DROP' failed: iptables: No chain/target/match by that name.
Nov 11 14:10:54 localhost firewalld: 2016-11-11 14:10:54 ERROR: COMMAND_FAILED: '/sbin/iptables -w2 -D SHADOWSOCKS_LIBEV_1098 -d [ip] -j DROP' failed: iptables: Bad rule (does a matching rule exist in that chain?).
Nov 11 14:10:54 localhost firewalld: 2016-11-11 14:10:54 ERROR: COMMAND_FAILED: '/sbin/iptables -w2 -A SHADOWSOCKS_LIBEV_1098 -d [ip] -j DROP' failed: iptables: No chain/target/match by that name.
Nov 11 14:10:55 localhost firewalld: 2016-11-11 14:10:55 ERROR: COMMAND_FAILED: '/sbin/iptables -w2 -D SHADOWSOCKS_LIBEV_1098 -d [ip] -j DROP' failed: iptables: Bad rule (does a matching rule exist in that chain?).
Nov 11 14:12:23 localhost firewalld: 2016-11-11 14:12:23 ERROR: COMMAND_FAILED: '/sbin/iptables -w2 -A SHADOWSOCKS_LIBEV_1098 -d [ip] -j DROP' failed: iptables: No chain/target/match by that name.
Nov 11 14:12:23 localhost firewalld: 2016-11-11 14:12:23 ERROR: COMMAND_FAILED: '/sbin/iptables -w2 -D SHADOWSOCKS_LIBEV_1098 -d [ip] -j DROP' failed: iptables: Bad rule (does a matching rule exist in that chain?).
Nov 11 14:12:24 localhost firewalld: 2016-11-11 14:12:24 ERROR: COMMAND_FAILED: '/sbin/iptables -w2 -A SHADOWSOCKS_LIBEV_1098 -d [ip] -j DROP' failed: iptables: No chain/target/match by that name.
Nov 11 14:12:24 localhost firewalld: 2016-11-11 14:12:24 ERROR: COMMAND_FAILED: '/sbin/iptables -w2 -D SHADOWSOCKS_LIBEV_1098 -d [ip] -j DROP' failed: iptables: Bad rule (does a matching rule exist in that chain?).
Nov 11 14:13:27 localhost systemd: Stopping Shadowsocks-libev Default Server Service...
Nov 11 14:13:27 localhost firewalld: 2016-11-11 14:13:27 ERROR: COMMAND_FAILED: '/sbin/ip6tables -w2 -D OUTPUT -p tcp --tcp-flags RST RST -j SHADOWSOCKS_LIBEV_1098' failed: ip6tables v1.4.21: Couldn't load target `SHADOWSOCKS_LIBEV_1098':No such file or directory#012#012Try `ip6tables -h' or 'ip6tables --help' for more information.
Nov 11 14:13:27 localhost firewalld: 2016-11-11 14:13:27 ERROR: COMMAND_FAILED: '/sbin/ip6tables -w2 -F SHADOWSOCKS_LIBEV_1098' failed: ip6tables: No chain/target/match by that name.
Nov 11 14:13:27 localhost firewalld: 2016-11-11 14:13:27 ERROR: NOT_ENABLED
Nov 11 14:13:28 localhost firewalld: 2016-11-11 14:13:28 ERROR: COMMAND_FAILED: '/sbin/iptables -w2 -D OUTPUT -p tcp --tcp-flags RST RST -j SHADOWSOCKS_LIBEV_1098' failed: iptables v1.4.21: Couldn't load target `SHADOWSOCKS_LIBEV_1098':No such file or directory#012#012Try `iptables -h' or 'iptables --help' for more information.
Nov 11 14:13:28 localhost firewalld: 2016-11-11 14:13:28 ERROR: COMMAND_FAILED: '/sbin/iptables -w2 -F SHADOWSOCKS_LIBEV_1098' failed: iptables: No chain/target/match by that name.
Nov 11 14:13:28 localhost firewalld: 2016-11-11 14:13:28 ERROR: NOT_ENABLED

**Comment by manjuprajna** [comment]
many many like above error messages from last night until just now I upgrade to latest commit.
now it looks good, I will check after several hrs, thank you.

**Comment by manjuprajna** [comment]
@madeye and another "problem" I think should report to you, when I type systemctl stop shadowsocks-libev, it takes almost 2 to 3 seconds, before yesterday, it stopped at once. don't know why.

**Comment by madeye** [comment]
It's expected. Actually firewalld is much slower than iptables. For more details, please refer to this post: https://www.berrange.com/posts/2014/05/02/improving-libvirt-firewall-performance/

**Comment by manjuprajna** [comment]
I think for firewalld should use rich language command like this:
firewall-cmd --add-rich-rule="rule family='ipv4' source address='ip address or range' reject"

**Comment by madeye** [comment]
firewall-cmd doesn't support tcp-flags. That's the problem.

**Comment by manjuprajna** [comment]
@madeye good morning, you get up so early.
thank you.
so is there any solution for this?

**Comment by madeye** [comment]
Migrate to iptables.

**Comment by manjuprajna** [comment]
so can we sacrifice some unnecessary feature to maintain compatibility with firewalld?

**Comment by madeye** [comment]
Nope. It's required.

**Comment by manjuprajna** [comment]
or could you pls tell me a way to get rid of this feature? means that I will lose auto-block, right?

**Comment by madeye** [comment]
Run in non-root mode.

**Comment by madeye** [comment]
For example `-a nobody`.

**Comment by manjuprajna** [comment]
but before you fix #899 , I can see lots of logs that ips were successfully blocked. so you've changed whole auto-block mechanism.

**Comment by manjuprajna** [comment]
if I run in -a nobody, this means I will lose auto-block feature and can not bind ports below 1024, right? nothing more?

**Comment by madeye** [comment]
The basic "auto-block" feature still exists and doesn't change. The only difference is when running in root user, you will get a enhanced one.

**Comment by madeye** [comment]
You can still run with ports below 1024 and "auto-block" feature, but without the enhanced one.

**Comment by manjuprajna** [comment]
@madeye I am so sorry to waste so much of your time.
but could you pls explain what's the difference between basic "auto-block" and enhanced "auto block"?
basic one is like autoban.py, it will monitor key words like "failed to handshake", then block this ip, but enhanced one will use tcp_flags to match and filter traffic, right?

so you mean I can still use in root user using port below 1024 and keep basic auto-block to kick out those "sniffer" ips, right? but lose enhanced feature based on iptables tcp_flags.

I am now using the latest commit, looking good till now, no error messages.

**Comment by madeye** [comment]
Right.

**Comment by manjuprajna** [comment]
just now I changed my openwrt ss-libev json file with a wrong password, and got many "failed to handshake" error message on server side, but did not get blocked. 
so actually how many times of "failed to handshake"will cause ip blocked? and how long will it last? last until next boot or firewalld reload?

**Comment by manjuprajna** [comment]
I am really sorry to waste so much of your time, thanks a million!

**Comment by madeye** [comment]
It works automatically. A wrong password by mistake won't get your IP blocked. So don't worry about the details.

**Comment by manjuprajna** [comment]
thank you, pls close this ticket.
