### ISSUE TITLE
Too many error in log 

### ISSUE THREAD

**Issue by debiansid** [shadowsocks/shadowsocks-libev#945]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?

2.5.6
### What operating system are you using?
Ubuntu and openwrt

### What did you do?
ss-redir 

### What did you expect to see?

No errors
### What did you see instead?
On openwrt which is client

2016-11-13 16:53:27 ERROR: remote recv: Connection reset by peer
Sun Nov 13 16:53:37 2016 auth.info sshd[9911]: Accepted publickey for root from 192.168.88.11 port 52279 ssh2: RSA SHA256:8EZkNDVYqIl8TGb3TOpS76F/KP+t2eDsvFI8q4PeTe4
Sun Nov 13 16:55:53 2016 auth.info sshd[9911]: Received disconnect from 192.168.88.11 port 52279:11: disconnected by user
Sun Nov 13 16:55:53 2016 auth.info sshd[9911]: Disconnected from 192.168.88.11 port 52279
Sun Nov 13 16:56:17 2016 daemon.err ss-redir[8807]:  2016-11-13 16:56:17 ERROR: remote recv: Connection reset by peer
Sun Nov 13 16:56:32 2016 daemon.err ss-redir[8807]:  2016-11-13 16:56:32 ERROR: remote recv: Connection reset by peer
Sun Nov 13 16:56:40 2016 auth.info sshd[9899]: Received disconnect from 192.168.88.11 port 52132:11: disconnected by user
Sun Nov 13 16:56:40 2016 auth.info sshd[9899]: Disconnected from 192.168.88.11 port 52132
Sun Nov 13 16:57:20 2016 daemon.err ss-redir[8807]:  2016-11-13 16:57:20 ERROR: remote recv: Connection reset by peer
Sun Nov 13 16:57:43 2016 daemon.err ss-redir[8807]:  2016-11-13 16:57:43 ERROR: remote recv: Connection reset by peer
Sun Nov 13 16:59:37 2016 daemon.err ss-redir[8807]:  2016-11-13 16:59:37 ERROR: remote recv: Connection reset by peer
Sun Nov 13 17:01:55 2016 daemon.err ss-redir[8807]:  2016-11-13 17:01:55 ERROR: remote recv: Connection reset by peer

On Ubuntu 14.which is server 
ramnode /usr/bin/ss-server[16716]: failed to handshake with 125.119.15.168
Nov 13 09:10:56 ramnode /usr/bin/ss-server[16716]: failed to handshake with 36.248.62.83
Nov 13 09:11:07 ramnode /usr/bin/ss-server[16716]: failed to handshake with 123.139.19.0
Nov 13 09:17:01 ramnode CRON[17541]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Nov 13 09:25:21 ramnode /usr/bin/ss-server[16716]: failed to handshake with 222.244.111.165
Nov 13 09:25:32 ramnode /usr/bin/ss-server[16716]: failed to handshake with 60.13.138.29
Nov 13 09:25:42 ramnode /usr/bin/ss-server[16716]: failed to handshake with 14.104.185.92
Nov 13 09:25:53 ramnode /usr/bin/ss-server[16716]: failed to handshake with 220.173.17.67
Nov 13 09:43:15 ramnode /usr/bin/ss-server[16716]: failed to handshake with 101.68.5.103
Nov 13 09:43:25 ramnode /usr/bin/ss-server[16716]: failed to handshake with 61.55.208.173

### What is your config in detail (with all sensitive info masked)?

**Comment by slrslr** [comment]
Check this issue: https://github.com/shadowsocks/shadowsocks-libev/issues/282
Madeye seems to answered that.

**Comment by debiansid** [comment]
But I didn't see it before

**Comment by debiansid** [comment]
It was good before

**Comment by debiansid** [comment]
on anther openwrt client which is connecting same server , there is no such error.
version is 2.4.7 , so in newer version  the error is just being printed?

**Comment by debiansid** [comment]
Sun Nov 20 17:16:40 2016 daemon.err ss-redir[14084]:  2016-11-20 17:16:40 ERROR: remote recv: Connection reset by peer
Sun Nov 20 17:16:45 2016 auth.info sshd[14131]: Connection closed by 192.168.88.11 port 64488 [preauth]
Sun Nov 20 17:16:50 2016 auth.info sshd[14133]: Accepted publickey for root from 192.168.88.11 port 64490 ssh2: RSA SHA256:8EZkNDVYqIl8TGb3TOpS76F/KP+t2eDsvFI8q4PeTe4
Sun Nov 20 17:16:57 2016 daemon.err ss-redir[14084]:  2016-11-20 17:16:57 ERROR: remote recv: Connection reset by peer
Sun Nov 20 17:17:00 2016 daemon.err ss-redir[14084]:  2016-11-20 17:17:00 ERROR: remote recv: Connection reset by peer
Sun Nov 20 17:19:15 2016 daemon.err ss-tunnel[14176]:  2016-11-20 17:19:15 INFO: initializing ciphers... rc4-md5
Sun Nov 20 17:19:15 2016 daemon.err ss-tunnel[14176]:  2016-11-20 17:19:15 INFO: tcp port reuse enabled
Sun Nov 20 17:19:15 2016 daemon.err ss-tunnel[14176]:  2016-11-20 17:19:15 INFO: UDP relay enabled
Sun Nov 20 17:19:15 2016 daemon.err ss-tunnel[14176]:  2016-11-20 17:19:15 INFO: udp port reuse enabled
Sun Nov 20 17:19:15 2016 daemon.err ss-tunnel[14176]:  2016-11-20 17:19:15 INFO: listening at 127.0.0.1:40
Sun Nov 20 17:19:15 2016 daemon.err ss-redir[14175]:  2016-11-20 17:19:15 INFO: initializing ciphers... rc4-md5
Sun Nov 20 17:19:15 2016 daemon.err ss-redir[14175]:  2016-11-20 17:19:15 INFO: tcp port reuse enabled
Sun Nov 20 17:19:15 2016 daemon.err ss-redir[14175]:  2016-11-20 17:19:15 INFO: UDP relay enabled
Sun Nov 20 17:19:15 2016 daemon.err ss-redir[14175]:  2016-11-20 17:19:15 INFO: udp port reuse enabled
Sun Nov 20 17:19:15 2016 daemon.err ss-redir[14175]:  2016-11-20 17:19:15 INFO: listening at 0.0.0.0:1080
Sun Nov 20 17:28:40 2016 auth.info sshd[14133]: Received disconnect from 192.168.88.11 port 64490:11: disconnected by user
Sun Nov 20 17:28:40 2016 auth.info sshd[14133]: Disconnected from 192.168.88.11 port 64490
Sun Nov 20 17:43:30 2016 authpriv.alert sudo:   nobody : user NOT in sudoers ; TTY=unknown ; PWD=/mnt/backup/www/html/admin ; USER=root ; COMMAND=pihole status web
Sun Nov 20 17:50:08 2016 auth.info sshd[19236]: Accepted publickey for root from 192.168.88.10 port 48490 ssh2: RSA SHA256:8EZkNDVYqIl8TGb3TOpS76F/KP+t2eDsvFI8q4PeTe4
Sun Nov 20 17:50:11 2016 auth.info sshd[19236]: Received disconnect from 192.168.88.10 port 48490:11: disconnected by user
Sun Nov 20 17:50:11 2016 auth.info sshd[19236]: Disconnected from 

Now it is good again,so it must be code related
