### ISSUE TITLE
[Compile Error]  Cannot find pcre library. Configure --with-pcre=DIR

### ISSUE THREAD

**Issue by zuozhen** [shadowsocks/shadowsocks-libev#949]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
2.5.6

### What operating system are you using?
Debian 8

### What did you do?
cross compile shadowsocks-libev for arm-linux (ddwrt router)

### What is your config in detail (with all sensitive info masked)?
$ cd $DEST
$ cd pcre-8.38
$ ./configure --prefix=$DEST/pcre --host=arm-linux
$ make && make install
$ cd ../shadowsocks-libev
$ ./configure --prefix=$DEST/shadowsocks-libev-ddwrt --enable-static --with-openssl=$DEST/ssl --with-pcre=$DEST/pcre --host=arm-linux

### Output
checking checking for pcre includes in $DEST/pcre... checking for pcre headers in $DEST/pcre/include... ok
configure: adding $DEST/pcre/lib to RPATH
checking for library containing pcre_exec... no
configure: error: Cannot find pcre library. Configure --with-pcre=DIR

**Comment by madeye** [comment]
Submit your config.log for both pcre and shadowsocks-libev.

**Comment by madeye** [comment]
Closed as inactive.

**Comment by flintt** [comment]
在使用Openwrt SDK（OpenWrt-SDK-15.05.1-x86-generic_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64）交叉编译给x86平台使用时也出现该问题
具体操作：
在SDK目录下
`make package/shadowsocks-libev/compile V=99
`
出现以下错误停止编译
```
checking for pcre headers in ... not found
checking for library containing pcre_exec... no
configure: error: Cannot find pcre library. Configure --with-pcre=DIR
```
系统中已经安装过pcre
```
root@ubuntu:~# apt-get install libpcre3 libpcre3-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libpcre3 is already the newest version.
libpcre3-dev is already the newest version.
The following packages were automatically installed and are no longer required:
  linux-headers-3.13.0-24 linux-headers-3.13.0-24-generic
  linux-image-3.13.0-24-generic linux-image-extra-3.13.0-24-generic
Use 'apt-get autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 139 not upgraded.
```
不知如何解决？

**Comment by karldonitz** [comment]
@flintt 我装libpcre3不行， 装了libpcre3-dev就好了。

**Comment by zuozhen** [comment]
谢谢 @karldonitz 
好长时间没折腾这个了，有时间的话试一下。

**Comment by gatalon** [comment]
./scripts/feeds install libpcre
我是执行了这个就好了。

**Comment by brinkqiang** [comment]
> 在使用Openwrt SDK（OpenWrt-SDK-15.05.1-x86-generic_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64）交叉编译给x86平台使用时也出现该问题 具体操作： 在SDK目录下 `make package/shadowsocks-libev/compile V=99 ` 出现以下错误停止编译
> 
> ```
> checking for pcre headers in ... not found
> checking for library containing pcre_exec... no
> configure: error: Cannot find pcre library. Configure --with-pcre=DIR
> ```
> 
> 系统中已经安装过pcre
> 
> ```
> root@ubuntu:~# apt-get install libpcre3 libpcre3-dev
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> libpcre3 is already the newest version.
> libpcre3-dev is already the newest version.
> The following packages were automatically installed and are no longer required:
>   linux-headers-3.13.0-24 linux-headers-3.13.0-24-generic
>   linux-image-3.13.0-24-generic linux-image-extra-3.13.0-24-generic
> Use 'apt-get autoremove' to remove them.
> 0 upgraded, 0 newly installed, 0 to remove and 139 not upgraded.
> ```
> 
> 不知如何解决？

最后解决了吗?
