### ISSUE TITLE
multipath TCP: Protocol not available

### ISSUE THREAD

**Issue by nesro** [shadowsocks/shadowsocks-libev#950]
Hi,

the shadowsocks-libev with MPTCP works fine for us [0]. But with the latest update of the kernel [1] a lot of these of errors were printed:

2016-11-15 11:22:27 ERROR: failed to enable multipath TCP: Protocol not available

despite the errors, MPTCP was working great.

When I removed the logic here https://github.com/shadowsocks/shadowsocks-libev/blob/master/src/netutils.h#L49 and just hardcoded `#define MPTCP_ENABLED 42` the error disappeared.

Can anyone please look if he has the same issue?

Thanks!
Tomas

[0]
we use the latest version of shadowsocks-libev from github

[1]
from "http://dl.bintray.com/cpaasch/deb jessie main", package: apt-get install linux-mptcp
Linux 4mmultipath 4.1.35.mptcp #4 SMP Sat Nov 5 04:56:54 UTC 2016 x86_64 GNU/Linux
Debian 8.6

**Comment by madeye** [comment]
MPTCP is still not stable. The macros keep changing from time to time, as a result it's even hard to have a stable definition in our source code.

I think you can keep your local patch for now. Let's wait until we have a stable MPTCP kernel.

**Comment by debiansid** [comment]
how can shadowsocks-libev benefit from MPTCP when we have multiple ss servers but only 1 internet access?

**Comment by vfreex** [comment]
IMO it is always a risk to use a kernel module that is not included in the upstream kernel.

**Comment by debiansid** [comment]
Overthebox has it in their production for a while already

**Comment by nesro** [comment]
Ok, I will keep in mind the risk and I will use my local patch until the things get more stable. Thanks!
