### ISSUE TITLE
Got a 'IP fragment packets' problem when use as a proxy for PS4

### ISSUE THREAD

**Issue by anson0370** [shadowsocks/shadowsocks-libev#951]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
2.5.5

### What operating system are you using?
Server: centos7.2 Router:newifi mini with Padavan 3.4.3.9-099_11-01

### What did you do?
Setup in router and enable UDP relay.

### What did you expect to see?
Everything is fine.

### What did you see instead?
NAT mode was OK. Reported NAT 2. But a tip about 'IP fragment packets issue' displayed.

### What is your config in detail (with all sensitive info masked)?
```
{
    "server":"**.**.**.**",
    "server_port":8388,
    "local_port":1080,
    "password":"*********",
    "timeout":600,
    "method":"aes-256-cfb"
}
```

I try to set a different MTU with `--mtu` in `/etc/default/shadowsocks-libev` and restart the service. But looks like not worked. Tried 1492 and 1460.

I guess this is a known issue but I didn't find a useful solution. Anyway, thx for ur awesome works!

**Comment by madeye** [comment]
It's expected. And don't worry, it won't cause any real issue for PS4.

More discussions can be found here: https://github.com/shadowsocks/shadowsocks-libev/issues/361

**Comment by anson0370** [comment]
OK. In fact these games I tested are all good. But sometimes it feels like difficult to match a game (tested with Destiny).
Will close this issue.
