### ISSUE TITLE
configure: error: Cannot find `asciidoc` in PATH.

### ISSUE THREAD

**Issue by ifusernameif** [shadowsocks/shadowsocks-libev#955]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
2.5.6

### What operating system are you using?
macOS Sierra 10.12.1

### What did you do?
clone from github，then execute `./configure` in shadowsocks-libev root directory

### What did you expect to see?
i hope configure file successful execute
### What did you see instead?

checking pcre.h presence... no
configure: WARNING: pcre.h: accepted by the compiler, rejected by the preprocessor!
configure: WARNING: pcre.h: proceeding with the compiler's result
checking for pcre.h... yes
checking pcre/pcre.h usability... no
checking pcre/pcre.h presence... no
checking for pcre/pcre.h... no
checking for asciidoc... no
configure: error: Cannot find `asciidoc` in PATH.

**Comment by manjuprajna** [comment]
you must install asciidoc, or you will have to "--disable-documentation"
