### ISSUE TITLE
Is there possibility to support RouterOS?

### ISSUE THREAD

**Issue by breestealth** [shadowsocks/shadowsocks-libev#960]
I want to use RouterOS and the basic infrastructure of my family network. But I don't find the RouterOS version of shadowsocks-libev. Is there possibility to build for RouterOS or give some tips for build in RouterOS? 

Thanks a lot for your help.

**Comment by madeye** [comment]
I think it's possible. But of course, you need to cross-compile the project yourself.

**Comment by starter48** [comment]
I know this topic is 2 years old, but it still actual. So I decided to make some clearance about RouterOS.
RouterOS is a deep modified, partially **non-open source** linux, reinforced with protection from modification by 3rd party. That means the general answer is *NO, you can't add Shadowsocks into RouterOS*. You have to pray developers to add it, for example at their forum: https://forum.mikrotik.com/search.php?keywords=shadowsocks
May be future RouterOS release could provide extended support of guest OS...
But it is a spoon of hope in this barrel of disappointments: few RouterOS-based routers (only some single-core models, such as RB2011) can run buggy build of OpenWRT inside VM of RouterOS:
https://wiki.mikrotik.com/wiki/Manual:Metarouter (quite outdated info)
https://forum.mikrotik.com/viewtopic.php?f=15&t=128998 (OpenWRT VM image for RB2011)
So you can compile and install Shadowsocks into OpenWRT VM of compatible router with RouterOS.

**Comment by happy201807** [comment]
I am running a socks5 proxy (172.17.0.2) in docker container.Yes, v7 is now supported through docker. it works, but I don't know how to forward traffic to routeros (192.168.88.0), could you help me?
