### ISSUE TITLE
memory leak?

### ISSUE THREAD

**Issue by tim-le** [shadowsocks/shadowsocks-libev#965]
https://github.com/shadowsocks/shadowsocks-libev/blob/f38aedc71a419286cf2a6c1bb7411b159daa745c/src/server.c#L512
do we really need to close(-1)?

https://github.com/shadowsocks/shadowsocks-libev/blob/f38aedc71a419286cf2a6c1bb7411b159daa745c/src/server.c#L592
memory (remote = new_remote(sockfd);) leak?

**Comment by madeye** [comment]
Closed via c0b26e3
