### ISSUE TITLE
无法启动shadowsocks-libev

### ISSUE THREAD

**Issue by luxin88** [shadowsocks/shadowsocks-libev#971]
### What version of shadowsocks-libev are you using?
v2.5.6

### What operating system are you using?
ubuntu 16.04 amd64

### What did you do?
git clone 源码 并且编译安装

### What did you expect to see?
启动成功

### What did you see instead?
systemctl  start shadowsocks-libev的时候报错

Job for shadowsocks-libev.service failed because a configured resource limit was exceeded. See "systemctl status shadowsocks-libev.service" and "journalctl -xe" for details.

systemctl status shadowsocks-libev.service

11月 24 23:06:48 pc systemd[1]: shadowsocks-libev.service: Unit entered failed state.
11月 24 23:06:48 pc systemd[1]: shadowsocks-libev.service: Failed with result 'resources'.
11月 24 23:12:35 pc systemd[1]: shadowsocks-libev.service: Failed to load environment files: No such file or directory
11月 24 23:12:35 pc systemd[1]: shadowsocks-libev.service: Failed to run 'start' task: No such file or directory
11月 24 23:12:35 pc systemd[1]: Failed to start Shadowsocks-libev Default Server Service.
11月 24 23:12:35 pc systemd[1]: shadowsocks-libev.service: Failed with result 'resources'

**Comment by flying-neko** [comment]
Maybe because `dpkg -i shadowsocks-libev*.deb` will overwrite `/etc/shadowsocks-libev/config.json`.

I just want to complain about it. I'm not sure when but I can confirm it did not overwrite it before.

**Comment by hosiet** [comment]
Did your direct installation include the environment file (/etc/default/shadowsocks-libev)? Unfortunately the systemd service delivered in the repo is dedicated for packaging and would fail if that file does not exist.

**Comment by madeye** [comment]
Closed as inactive.

**Comment by luxin88** [comment]
rename /etc/default/shadowsocks-libev.* to /etc/default/shadowsocks-libev ,and it works, thanks
