### ISSUE TITLE
wishlist request: the supported cipher list by run-time result

### ISSUE THREAD

**Issue by rogers0** [shadowsocks/shadowsocks-libev#980]
### What version of shadowsocks-libev are you using?

2.5.6+ds-1 of Debian Stretch

### What did you expect to see?

I'm just wondering whether there's a way to get to know the supported ciphers on the system.

Like #851, it's better to show the supported cipher list by run-time result, instead of (or in addition to) in manpage. Because document may be not accurate.
Thanks!

**Comment by madeye** [comment]
No plan for this.

Actually, if you're using recommended ciphers like salsa20/chacha20 and aes-128/192/256 which are always usable on any platform.
