### ISSUE TITLE
建议在Debian打包脚本中添加可执行文件的CAP_NET_BIND_SERVICE权限

### ISSUE THREAD

**Issue by siyanmao** [shadowsocks/shadowsocks-libev#983]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
Newest Version, build from master branch.

### What operating system are you using?
Debian 8.6 jessie

Debian的打包脚本中，没有对可执行文件添加CAP_NET_BIND_SERVICE权限，而systemd service文件中放行了该权限。建议在打包脚本中设置几个可执行文件的CAP_NET_BIND_SERVICE权限。

**Comment by hosiet** [comment]
I know Arch Linux is doing that. I don't think we should call setcap in postinst.

@rogers0 What do you think?

**Comment by hosiet** [comment]
Another really minor issue: capabilities does not work on Debian GNU/kFreeBSD and Debian GNU/Hurd.

**Comment by rogers0** [comment]
@hosiet thanks for the pinging!
actually I have no idea/experience on CAP_NET_BIND_SERVICE.
It's always welcome if there's any patch.

**Comment by hosiet** [comment]
Closed via 363bf5735ed81e68839842e94d06e7c0eca14961.
