### ISSUE TITLE
shadowsocks-libev延迟很高

### ISSUE THREAD

**Issue by agzfan** [shadowsocks/shadowsocks-libev#984]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
V2.5.2

### What operating system are you using?
debian7

rdp连接一台法国服务器
我直连法国ping 450
ping洛杉矶180
洛杉矶ping法国130

国内连接法国延迟400多还丢包一堆,于是用一个洛杉矶的ss做代理
我发现shadowsocks-libev延迟非常的高,甚至比直连还高不少
换成v2ray(ss协议),或者ssr(auth_sha1_v4+http_simple)延迟最少减一半
v2ray和ssr延迟没感觉出有区别,但是libev太明显了.....

**Comment by madeye** [comment]
1. Try the latest version.
2. Make sure you set the DNS server correctly. (-d <dns_addr>).
3. Try speedtest.net to get the latency numbers and post here.

**Comment by wongsyrone** [comment]
如果不手动指定dns，确保/etc/resolv.conf里面的服务器为距离vps提供商最近的。

**Comment by madeye** [comment]
Closed as inactive.
