### ISSUE TITLE
&和?优先级不明确

### ISSUE THREAD

**Issue by wongsyrone** [shadowsocks/shadowsocks-libev#985]
https://github.com/shadowsocks/shadowsocks-libev/blob/master/src/json.c#L823

**Comment by madeye** [comment]
Open a pull request if possible.

**Comment by wongsyrone** [comment]
如果我没理解错的话，应该是 `(flags & flag_num_e_negative) ? -num_e : num_e` 吧

**Comment by madeye** [comment]
Right.

**Comment by Mygod** [comment]
http://en.cppreference.com/w/c/language/operator_precedence

**Comment by wongsyrone** [comment]
代码风格问题，PR已发
