### ISSUE TITLE
Use jemalloc to maximize ss performance

### ISSUE THREAD

**Issue by enihcam** [shadowsocks/shadowsocks-libev#991]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
2.5.6

### What operating system are you using?
Client: Archlinux
Server: Ubuntu

### What did you expect to see?
Use jemalloc to maximize ss-libev performance.
http://jemalloc.net/

**Comment by wongsyrone** [comment]
不一定适合嵌入式环境

**Comment by madeye** [comment]
`jemalloc` is designed for multi-threading and better scalability. However, `shadowsocks-libev` is designed to be a single-thread program and optimized for embedded devices.

So, no plan for this.

**Comment by madeye** [comment]
If you want to maximize the performance of shadowsocks-libev, just start multiple instances of shadowsocks-libev and let them listening on the same port.

**Comment by enihcam** [comment]
> If you want to maximize the performance of shadowsocks-libev, just start multiple instances of shadowsocks-libev and let them listening on the same port.

If one process is bound to a port, can another process be bound to it as well??

**Comment by madeye** [comment]
Yep  https://lwn.net/Articles/542629/
