### ISSUE TITLE
希望增加检测ss连接可用性和延迟

### ISSUE THREAD

**Issue by qiuzi** [shadowsocks/shadowsocks-libev#992]
多服务器里需要测试本地----SS----目标整个过程的可用性与延迟。
初步设想: ss-test -u -s xxx.xxx.xxx -p xxxx -m xxxx -k xxxx -d 8.8.8.8
SYN/ACK  from 8.8.8.8: seq=0 ttl=55 time=259.908 ms
SYN/ACK  from 8.8.8.8: seq=1 ttl=55 time=228.502 ms
SYN/ACK  from 8.8.8.8: seq=2 ttl=55 time=225.021 ms
类似ping结果

**Comment by madeye** [comment]
No plan for this. Actually, you can easily take advantage of tcpping and ss-tunnel to achieve this.

**Comment by qiuzi** [comment]
批量服务器使用起来太繁琐 不好做统计

**Comment by qiuzi** [comment]
ss-tunnel -b 0.0.0.0 -s xxx -p xxx -l 8881 -m xxx -k xxxx -L 180.149.132.47:80 -v -u

tcpping -p 8881 127.0.0.1
RST from 127.0.0.1: seq=22178331 ttl=64 time=-546132032.000ms
再无下文
