### ISSUE TITLE
Another null pointer issue

### ISSUE THREAD

**Issue by richardxx** [shadowsocks/shadowsocks-libev#993]
See the report:

http://t.sourcebrella.com:40072?user=guest&passwd=guest888#shadowsocks?5848fd2e692dac0e4435482f?46

When it goes to the else branch, variable "slice == nullptr" and it cannot be used directly at line 166.

**Comment by madeye** [comment]
You may also open an issue here: https://github.com/redjack/libcork

**Comment by richardxx** [comment]
Sure, thanks.
