### ISSUE TITLE
UDP over ss-redir

### ISSUE THREAD

**Issue by LadMartin** [shadowsocks/shadowsocks-libev#997]
Hello,

what we want to do is to send UDP traffic over TCP. Is it possible with ss-redir directly or do we need to use some other wrapping before redirecting to shadowsocks?

We found that there is this -u, but i don't much understand what does it do, if it switches between UDP and TCP as a trasnfer method or someting else. Because we are using --mptcp and we also want to use capacity of MPTCP for UDP. 

Thanks

**Comment by madeye** [comment]
It's not supported. Also, UDP over TCP is a very bad idea.
