### ISSUE TITLE
[Q] ss-server and ss-manager could not be compiled with mingw

### ISSUE THREAD

**Issue by zhfreal** [shadowsocks/shadowsocks-libev#999]
I could not compile ss-server.exe and ss-manger.exe with mingw for latest 2.5.6 any more . It‘s normal for ss-local and ss-tunnel. Does it not support any more , or am I missing something?

**Comment by madeye** [comment]
It's expected. Only ss-local and ss-tunnel can be compiled with mingw.

**Comment by zhfreal** [comment]
OK, thanks.
